In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np

In [2]:
esi = pd.read_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\CLIENT FILE\ESI CURRENT VESSELS.xlsx")
esi

         IMO    Fleet          Vessel Scrubber Unnamed: 4
0    9297589  CHARTER           ALANA       No        NaN
1    9625970        9       ANASTASIA       No        NaN
2    9342695  CHARTER   AS California       No        NaN
3    9314947  CHARTER     AS CAMELLIA      Yes        NaN
4    9321897       12    MSC NADIA IV       No        NaN
..       ...      ...             ...      ...        ...
429  9198587       14    MSC CHIARA X       No        NaN
430  9299032       19  MSC FALCON III       No        NaN
431  9962598       15     MSC LORENZA      Yes        NaN
432  9967263       23      MSC MAPUTO      Yes        NaN
433  9214898       14    MSC NICOLE X       No        NaN

[434 rows x 5 columns]

In [3]:
esi['Fleet'].unique()

array(['CHARTER', 9, 12, 15, 14, 1, 2, 22, 3, 7, 6, 5, 21, 'SORRENTO', 19,
       18, 11, 4, 8, 10, 16, 17, 24, 20, 23], dtype=object)

In [4]:
#charter
esi_charter = esi[esi['Fleet'] =='CHARTER']
esi_charter

         IMO    Fleet             Vessel Scrubber Unnamed: 4
0    9297589  CHARTER              ALANA       No        NaN
2    9342695  CHARTER      AS California       No        NaN
3    9314947  CHARTER        AS CAMELLIA      Yes        NaN
5    9247766  CHARTER       ATHENS GLORY      Yes        NaN
7    9727625  CHARTER        CAPE SOUNIO       No        NaN
8    9706205  CHARTER       CAPE TAINARO       No        NaN
9    9293791  CHARTER     CONTI CHIVALRY       No        NaN
10   9308613  CHARTER       Contship Fun       No        NaN
11   9373917  CHARTER       CONTSHIP OAK       No        NaN
12   9357810  CHARTER           EF Emira       No        NaN
13   9153862  CHARTER        EPAMINONDAS       No        NaN
14   9301469  CHARTER             Etoile       No        NaN
17   9256482  CHARTER         GSL NINGBO       No        NaN
18   9357793  CHARTER        Hansa Lanka       No        NaN
19   9535163  CHARTER    Henrika Schulte       No        NaN
20   9535187  CHARTER    Hermann Schulte       No        NaN
21   9535204  CHARTER     Hubert Schulte       No        NaN
23   9225770  CHARTER              Julie       No        NaN
24   9085558  CHARTER         Karlskrona       No        NaN
25   9085546  CHARTER             KLEVEN       No        NaN
26   9085534  CHARTER              KOTKA       No        NaN
27   9085522  CHARTER               KURE       No        NaN
28   9307243  CHARTER           Le Havre      Yes        NaN
29   9236535  CHARTER         Marianetta       No        NaN
30   9162227  CHARTER         MARIANNA I       No        NaN
31   9148025  CHARTER          MED AYDIN       No        NaN
32   9256365  CHARTER          MED CESME       No        NaN
33   9106479  CHARTER          MED CORLU       No        NaN
34   9106493  CHARTER        MED Denizli       No        NaN
35   9225794  CHARTER         MED SAMSUN       No        NaN
36   9141780  CHARTER        MED TRABZON       No        NaN
44   9619464  CHARTER         MSC AGADIR      Yes        NaN
71   9247730  CHARTER         MSC APOLLO      Yes        NaN
72   9262704  CHARTER       MSC AQUARIUS      Yes        NaN
78   9618317  CHARTER          MSC ATHOS      Yes        NaN
82   9605255  CHARTER           MSC AZOV      Yes        NaN
85   9480186  CHARTER      MSC BARCELONA       No        NaN
86   9461441  CHARTER           MSC BARI      Yes        NaN
94   9247742  CHARTER      MSC BOSPHORUS      Yes        NaN
100  9480203  CHARTER          MSC CADIZ       No        NaN
126  9480215  CHARTER         MSC CORUNA       No        NaN
129  9247754  CHARTER    MSC DARDANELLES      Yes        NaN
187  9225641  CHARTER          MSC ILONA       No        NaN
198  9135638  CHARTER         MED MERSIN       No        NaN
225  9461403  CHARTER      MSC LA SPEZIA      Yes        NaN
237  9461427  CHARTER        MSC LIVORNO      Yes        NaN
248  9480198  CHARTER         MSC MADRID       No        NaN
284  9349796  CHARTER       MSC MONTEREY       No        NaN
325  9256470  CHARTER        MSC QINGDAO      Yes        NaN
328  9484431  CHARTER        MSC RAVENNA      Yes        NaN
337  9304447  CHARTER           MSC ROMA      Yes        NaN
355  9460356  CHARTER         MSC SAVONA      Yes        NaN
387  9475258  CHARTER        MSC TARANTO      Yes        NaN
391  9285471  CHARTER        MSC TIANJIN       No        NaN
408  9480227  CHARTER           MSC VIGO       No        NaN
423  9813840  CHARTER  Spirit of Chennai      Yes        NaN
424  9813838  CHARTER  Spirit of Kolkata      Yes        NaN

In [5]:
#sorrento
esi_sorrento = esi[esi['Fleet'] == 'SORRENTO']
esi_sorrento

         IMO     Fleet                 Vessel Scrubber Unnamed: 4
50   9129873  SORRENTO              MSC ALEXA       No        NaN
54   9235050  SORRENTO             MSC ALYSSA       No        NaN
56   9839480  SORRENTO              MSC AMBRA      Yes        NaN
58   9606338  SORRENTO          MSC AMSTERDAM       No        NaN
88   9399014  SORRENTO           MSC BEATRICE      Yes        NaN
113  9930040  SORRENTO  MSC CELESTINO MARESCA      Yes        NaN
119  9708693  SORRENTO              MSC CLARA      Yes        NaN
134  9202649  SORRENTO              MSC DIEGO       No        NaN
135  9897004  SORRENTO            MSC DILETTA      Yes        NaN
159  9279965  SORRENTO           MSC FABIENNE       No        NaN
165  9401116  SORRENTO          MSC FRANCESCA      Yes        NaN
170  9202663  SORRENTO               MSC GINA       No        NaN
177  9647461  SORRENTO            MSC HAMBURG      Yes        NaN
195  9606326  SORRENTO           MSC ISTANBUL       No        NaN
196  9398371  SORRENTO              MSC IVANA      Yes        NaN
204  9966934  SORRENTO              MSC JIANI       No        NaN
211  9399026  SORRENTO             MSC KALINA      Yes        NaN
214  9467457  SORRENTO              MSC KATIE      Yes        NaN
220  9351581  SORRENTO                MSC KIM       No        NaN
223  9372470  SORRENTO            MSC KRYSTAL       No        NaN
228  9225665  SORRENTO              MSC LAURA      Yes        NaN
236  9281279  SORRENTO               MSC LISA       No        NaN
238  9606302  SORRENTO             MSC LONDON      Yes        NaN
239  9320403  SORRENTO             MSC LORENA       No        NaN
242  9230490  SORRENTO            MSC LORETTA      Yes        NaN
262  9275971  SORRENTO             MSC MARINA       No        NaN
263  9060637  SORRENTO            MSC MARTINA       No        NaN
268  9251717  SORRENTO            MSC MAUREEN       No        NaN
270  9708679  SORRENTO               MSC MAYA      Yes        NaN
272  9226918  SORRENTO            MSC MELISSA      Yes        NaN
276  9230488  SORRENTO           MSC MICHAELA      Yes        NaN
278  9897016  SORRENTO           MSC MICHELLE      Yes        NaN
287  9955789  SORRENTO             MSC NAHARA      Yes        NaN
292  9606314  SORRENTO           MSC NEW YORK       No        NaN
302  9349825  SORRENTO              MSC NURIA       No        NaN
306  9703306  SORRENTO             MSC OLIVER       No        NaN
307  9372482  SORRENTO             MSC ORIANE       No        NaN
310  9703291  SORRENTO              MSC OSCAR      Yes        NaN
319  9279977  SORRENTO            MSC POH LIN       No        NaN
326  9290282  SORRENTO            MSC RACHELE       No        NaN
331  9754965  SORRENTO               MSC REEF      Yes        NaN
332  9202651  SORRENTO             MSC REGINA       No        NaN
339  9320453  SORRENTO            MSC ROSARIA       No        NaN
375  9404663  SORRENTO              MSC SONIA      Yes        NaN
378  9279989  SORRENTO             MSC STELLA      Yes        NaN
381  9708681  SORRENTO              MSC SVEVA      Yes        NaN
393  9309461  SORRENTO             MSC TOMOKO       No        NaN
403  9461439  SORRENTO            MSC VALERIA       No        NaN
404  9484467  SORRENTO             MSC VANDYA       No        NaN
422  9703318  SORRENTO                MSC ZOE      Yes        NaN

In [6]:
#msc own vessels
esi_own = esi[(esi.Fleet !='CHARTER') & (esi.Fleet != 'SORRENTO')]
esi_own

         IMO Fleet          Vessel Scrubber Unnamed: 4
1    9625970     9       ANASTASIA       No        NaN
4    9321897    12    MSC NADIA IV       No        NaN
6    9334519    15   MSC ZAINA III       No        NaN
15   9453298    14      GOLD HOSHI       No        NaN
16   9463205    14     GOLD KOCHAV       No        NaN
..       ...   ...             ...      ...        ...
429  9198587    14    MSC CHIARA X       No        NaN
430  9299032    19  MSC FALCON III       No        NaN
431  9962598    15     MSC LORENZA      Yes        NaN
432  9967263    23      MSC MAPUTO      Yes        NaN
433  9214898    14    MSC NICOLE X       No        NaN

[327 rows x 5 columns]

In [7]:
esi_own['Fleet'].unique()

array([9, 12, 15, 14, 1, 2, 22, 3, 7, 6, 5, 21, 19, 18, 11, 4, 8, 10, 16,
       17, 24, 20, 23], dtype=object)

In [8]:
#msc own vessel imos to list
esi_own_lst = esi_own['IMO'].to_list()
esi_own_lst

[9625970,
 9321897,
 9334519,
 9453298,
 9463205,
 9180205,
 9330226,
 9166778,
 9190119,
 8512906,
 9235581,
 9169055,
 9932921,
 9057173,
 9618276,
 9770751,
 9123166,
 9301990,
 9618288,
 9842097,
 9196852,
 9319600,
 9008603,
 9242651,
 9261827,
 9259379,
 9306275,
 9227297,
 8521402,
 9169122,
 9282261,
 9254848,
 9323041,
 9297864,
 9710426,
 9857169,
 9839284,
 9244881,
 9162631,
 9263344,
 8913447,
 8512891,
 9857183,
 9263332,
 9226932,
 9360764,
 9289099,
 9203904,
 9297876,
 9770749,
 9930935,
 9720495,
 9313967,
 9103685,
 9702106,
 9289087,
 9169043,
 9262546,
 9102722,
 9360271,
 9154220,
 9210086,
 9625944,
 9946879,
 9295397,
 9253038,
 9705005,
 9229300,
 9316361,
 9710438,
 9299537,
 9198587,
 9936642,
 9936628,
 9113446,
 9301550,
 9241463,
 9307267,
 9426817,
 9295165,
 9250983,
 9927287,
 9930959,
 9200689,
 9262560,
 9306263,
 9720201,
 9102746,
 9237151,
 9301328,
 9444285,
 9294824,
 9110391,
 9169029,
 9282259,
 9236688,
 9278143,
 9064750,
 9215892,
 9166780,
 9735218,
 9704972,
 8917778,
 9326823,
 9334832,
 9463047,
 9004231,
 8201648,
 9302633,
 9842085,
 9299032,
 9290402,
 9120853,
 8413875,
 9344708,
 9152856,
 9289051,
 9153850,
 9720196,
 9947134,
 9210062,
 9415296,
 9631876,
 9283708,
 9316347,
 9350317,
 9127540,
 9463281,
 9224946,
 9962562,
 9962586,
 9197545,
 9124366,
 9231248,
 9181651,
 9929429,
 8201624,
 9839272,
 9154206,
 9110975,
 9433157,
 9000742,
 9720471,
 9622007,
 9215672,
 8918980,
 9039250,
 9227338,
 9275036,
 9450351,
 9244946,
 9236585,
 9232656,
 9467445,
 9227302,
 9110389,
 9242637,
 9927299,
 9123154,
 9051507,
 9305506,
 9439735,
 9064748,
 9162643,
 9947158,
 9347762,
 9383223,
 9334349,
 9704960,
 9237498,
 9962598,
 9934735,
 9327798,
 9251690,
 9308625,
 9400148,
 9231119,
 9625932,
 9252553,
 9252541,
 8201636,
 9238882,
 8918966,
 9967263,
 9932892,
 9465318,
 8616520,
 9155107,
 9964194,
 9962574,
 9540077,
 9169031,
 9181663,
 9315915,
 9720287,
 9102710,
 9936630,
 9231779,
 9169067,
 9720512,
 9196864,
 9839260,
 9293179,
 9932050,
 9060649,
 9294991,
 9149328,
 9307839,
 9471226,
 8918954,
 9278155,
 9214898,
 9228576,
 9315886,
 9308584,
 9326768,
 9084607,
 9778117,
 9946843,
 9256315,
 9456965,
 9336359,
 9408774,
 9857157,
 9281267,
 9735206,
 9336165,
 9239903,
 9161297,
 9240328,
 9256391,
 9267637,
 9222302,
 9074042,
 9139086,
 9299020,
 9154191,
 9450325,
 9235402,
 9930052,
 9139505,
 9465306,
 9240873,
 9419644,
 9038907,
 9293167,
 9957359,
 9337676,
 8714205,
 9401166,
 9491616,
 9110377,
 9434462,
 9222106,
 9290426,
 8913411,
 9702261,
 9181675,
 8715857,
 9241451,
 9720500,
 9116369,
 9471238,
 9292175,
 9231822,
 8913423,
 9036002,
 9180968,
 9224049,
 9778105,
 9778076,
 9720457,
 9210098,
 9224348,
 9793947,
 9162277,
 9927275,
 9702091,
 9695028,
 9220328,
 9259393,
 9210050,
 8918978,
 9330068,
 9231262,
 9200677,
 9308601,
 9351579,
 9316373,
 9008574,
 9189366,
 9930038,
 9248928,
 9299525,
 9295177,
 9230775,
 9931288,
 9337444,
 9302619,
 9302621,
 9315836,
 9227340,
 9251688,
 9242625,
 9238739,
 9304708,
 9146479,
 9908059,
 9702089,
 9947122,
 9908047,
 9236690,
 9288409,
 9778090,
 9322011,
 9146467,
 9344564,
 9141285,
 9315018,
 9326964,
 9354363,
 9315006,
 9198587,
 9299032,
 9962598,
 9967263,
 9214898]

# NOONDATA

In [9]:
#server noon data from jan to june
noondata = pd.read_csv(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\NOONDATA\Noon_data_Jan_Jun_2024.csv")

noondata

,id,pi_sog,pi_stw,true_wind_dir,true_wind_speed,relative_wind_speed,relative_wind_direction,caa,corrected_power,rw,...,rob_garbage_cat_a_plastic,rob_garbage_cat_b_organic,rob_garbage_cat_c_domestic,rob_garbage_cat_e_ashes,qty_sludge_disposed,steaming_time_m_e_lng,reefer_power_consumption,wind_direction_side,sea_direction_side,tot_sludge_removed
0,5777774,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5741339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5742629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5744471,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5753018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193489,5771713,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193490,5913276,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,80.0,NaN,NaN,NaN
193491,5940155,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2500.0,NaN,NaN,NaN
193492,5792431,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193493,5759666,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN

In [10]:
noondata.columns.tolist()

['id',
 'pi_sog',
 'pi_stw',
 'true_wind_dir',
 'true_wind_speed',
 'relative_wind_speed',
 'relative_wind_direction',
 'caa',
 'corrected_power',
 'rw',
 'ref_speed',
 'imo',
 'vessel',
 'id_vessel',
 'gid',
 'voyage',
 'corrected_date',
 'report_date_time',
 'report_date_time_offset',
 'report_type',
 'status',
 'lat',
 'long',
 'latitude',
 'longitude',
 'me_foc',
 'cargo_total',
 'total_steaming_time',
 'me_fuel_only_steaming_time',
 'miles_by_gps',
 'oil_cyl',
 'speed_by_log',
 'speed_by_gps',
 'rpm',
 'slip',
 'wind_direction',
 'wind_speed',
 'draft_aft',
 'draft_fwd',
 'displacement',
 'course_at_sea',
 'wave_height',
 'sea_direction',
 'cargo_total_teu',
 'ambient_temp',
 'sw_temp',
 'miles_by_speed_log',
 'eta_port_code',
 'eta_date_time',
 'eta_date_time_offset',
 'eta_port',
 'time_change',
 'time_sea',
 'temp_min',
 'temp_max',
 'requested_speed',
 'rem_dist_to_pilot',
 'rem_time_to_pilot',
 'total_unplnd_stpge_tech',
 'total_unplnd_stpge_ope_wx',
 'reefers_positive_plugged',
 'reefers_negative_plugged',
 'me_total_revs_counter',
 'port_code',
 'port',
 'aux_blowers_on',
 'hold_ventilation_on',
 'since_date_time',
 'since_date_time_offset',
 'time_hrs_anchor',
 'time_hrs_drift',
 'reason',
 'type_of_delay',
 'etb_date_time',
 'etb_date_time_offset',
 'pilot_date_time',
 'pilot_date_time_offset',
 'time_manoeuvring',
 'tug_arr',
 'tug_shift',
 'etd_date_time',
 'etd_date_time_offset',
 'shift_berth_hours',
 'cargo_load',
 'cargo_disch',
 'teu_full',
 'teu_empty',
 'bilge_removed',
 'garbage_removed',
 'garbage_remvl_reqstd',
 'garbage_remvl_cmplsry',
 'fw_supply',
 'cy_crew_signed_on',
 'cy_crew_signed_off',
 'cy_doctors_visit',
 'cy_mail_received_ref_no',
 'cy_lub_oil_sample_landed',
 'cy_checkd_for_stowaways',
 'cy_stowaways_on_board',
 'cy_dep_gm_mtr',
 'cy_requisitions_received',
 'distance_to_next_pilot',
 'tug_sailing_transit',
 'steaming_time_me_rsdl_vls',
 'steaming_time_me_rsdl_hs',
 'steaming_time_me_rsdl_uls',
 'steaming_time_me_dstlt_vls',
 'steaming_time_me_dstlt_uls',
 'steaming_time_me_tnktnr_dstlt_vls',
 'steaming_time_me_mdo',
 'steaming_time_aux_1',
 'steaming_time_aux_2',
 'steaming_time_aux_3',
 'steaming_time_aux_4',
 'steaming_time_aux_5',
 'steaming_time_sh_gen',
 'steaming_time_tg',
 'fuel_me_rsdl_vls',
 'fuel_me_rsdl_hs',
 'fuel_me_rsdl_uls',
 'fuel_me_dstlt_vls',
 'fuel_me_dstlt_uls',
 'fuel_me_mdo',
 'fuel_me_tnktnr_dstlt_vls',
 'fuel_aux_rsdl_vls',
 'fuel_aux_rsdl_hs',
 'fuel_aux_rsdl_uls',
 'fuel_aux_dstlt_vls',
 'fuel_aux_dstlt_uls',
 'fuel_aux_tnktnr_dstlt_vls',
 'fuel_aux_mdo',
 'fuel_boiler_rsdl_vls',
 'fuel_boiler_rsdl_hs',
 'fuel_boiler_rsdl_uls',
 'fuel_boiler_dstlt_vls',
 'fuel_boiler_dstlt_uls',
 'fuel_boiler_tnktnr_dstlt_vls',
 'fuel_boiler_mdo',
 'power_kw',
 'steaming_load_kw_aux_1',
 'steaming_load_kw_aux_2',
 'steaming_load_kw_aux_3',
 'steaming_load_kw_aux_4',
 'steaming_load_kw_aux_5',
 'steaming_load_kw_sh_gen',
 'steaming_load_kw_tg',
 'deck_last_change_user',
 'engine_last_change_user',
 'deck_part_is_complete',
 'engine_part_is_complete',
 'scavenge_pressure',
 'seca_entry_time',
 'seca_entry_lat',
 'seca_entry_long',
 'seca_exit_time',
 'seca_exit_lat',
 'seca_exit_long',
 'rob_fresh_water',
 'manvrng_miles_by_gps',
 'manvrng_miles_by_speed_log',
 'tanktainer_transfd_quantity',
 'pilot_taken',
 'date_time_start_transit',
 'date_time_start_transit_offset',
 'date_time_end_transit',
 'date_time_end_transit_offset',
 'ballast',
 'tanktainer_number',
 'steaming_kwhr_total',
 'cy_others',
 'rob_fo_sludge',
 'rob_lo_sludge',
 'rob_bilge',
 'sludge_removed_fo',
 'sludge_removed_lo',
 'sea_state',
 'cy_lub_added_to_system_me_cc',
 'cy_lub_added_to_system_ae_cc',
 'cy_lub_added_to_thrusters',
 'cy_me_lo_purifier_in_use',
 'cy_ballast',
 'cy_bending_moment',
 'cy_shearing_force',
 'cy_tortion_moment',
 'cy_supdt_auditor_signed_on',
 'cy_supdt_auditor_signed_off',
 'cy_cash_received',
 'cy_lub_oil_received_me_cyl',
 'cy_lub_oil_received_me_cc',
 'cy_lub_oil_received_ae_cc',
 'cy_me_under_piston_temp',
 'cy_mail_received',
 'wind_direction_port_stbd',
 'sea_direction_port_stbd',
 'time_pilot_onboard',
 'grades_rob',
 'so_2_co_2_ratio',
 'bunker_order',
 'remarks',
 'bdn_number',
 'fuel_type',
 'carbon_factor',
 'sulphur_content_pc',
 'quantity',
 'port_delivery',
 'product_quality',
 'tanktainer_number_1',
 'supplier',
 'delivery',
 'volume_lt',
 'density',
 'viscosity',
 'rob_dstlt_uls',
 'rob_dstlt_vls',
 'rob_rsdl_mdo',
 'rob_tnktnr_dstlt_vls',
 'rob_rsdl_vls',
 'rob_rsdl_hs',
 'rob_rsdl_uls',
 'has_cargo',
 'steaming_time_me_hs',
 'steaming_time_me_ls',
 'steaming_time_me_mgo',
 'steaming_time_me_mgo_ls',
 'fuel_me_hs',
 'fuel_me_ls',
 'fuel_me_mgo',
 'fuel_me_mgo_ls',
 'fuel_aux_hs',
 'fuel_aux_ls',
 'fuel_aux_mgo',
 'fuel_aux_mgo_ls',
 'fuel_boiler_hs',
 'fuel_boiler_ls',
 'fuel_boiler_mgo',
 'fuel_boiler_mgo_ls',
 'rob_fuel_hs_fo',
 'rob_fuel_ls_fo',
 'rob_fuel_mdo',
 'rob_fuel_mgo',
 'rob_fuel_mgo_ls',
 'rob_fuel_tanktainer_mgo',
 'eca_miles',
 'eca_time',
 'egcs_dry_waste_removed',
 'egcs_running_time',
 'egcs_wet_slurry_removed',
 'egcs_open_loop_running_time',
 'egcs_closed_loop_running_time',
 'voyage_order',
 'voyage_code',
 'eca',
 'eu',
 'sea_time',
 'eta_country_code',
 'port_country_code',
 'check_eta_code',
 'check_port_code',
 'status_temp_eu',
 'fuel_hs',
 'fuel_ls',
 'fuel_mdo',
 'fuel_mgo',
 'fuel_mgo_ls',
 'cargo_transport_work',
 'teu_transport_work',
 'eeoi_voyage_no',
 'cargo_total_old',
 'draft',
 'fo_per_24_hrs',
 'sfoc',
 'cy_oil_gm_hr',
 'scoc',
 'voyage_name',
 'total_fo',
 'total_co_2',
 'eeoi',
 'voy_condition',
 'same_date',
 'time_since_last_report',
 'wind_direction_360',
 'ref_power',
 'ref_fuel',
 'fuel_loss',
 'draft_pow',
 'draft_sp_pow',
 'fo_nor',
 'fo_model',
 'sfoc_model',
 'sfoc_deviation',
 'ref_power_corrected',
 'ref_fo_corrected',
 'propulsive_eff',
 'speed_performance',
 'pi',
 'me_con',
 'ae_con',
 'bl_con',
 't_con',
 'hs',
 'ls',
 'mdo',
 'mgo',
 'mgo_ls',
 't_co_2',
 'ae_t_steaming',
 'ae_power',
 'trim',
 'distance_covered',
 'updated_date',
 'hyd_slip_sog',
 'hyd_slip_stw',
 'fuel_rsdl_hs',
 'fuel_rsdl_vls',
 'fuel_rsdl_uls',
 'fuel_dstlt_vls',
 'fuel_dstlt_uls',
 'fuel_tnktnr_dstlt_vls',
 'rsdl_hs',
 'rsdl_vls',
 'rsdl_uls',
 'dstlt_vls',
 'dstlt_uls',
 'tnktnr_dstlt_vls',
 'fuel_m_e_lng',
 'fuel_aux_lng',
 'fuel_boiler_lng',
 'rob_rsdl_lng',
 'sulphur_content_pc_main',
 'quantity_main',
 'port_delivery_main',
 'product_quality_main',
 'delivery_main',
 'bdn_number_main',
 'fo_nor_sog',
 'fo_nor_stw',
 'created_at',
 'updated_at',
 'created_by_id',
 'updated_by_id',
 'rob_lng',
 'sludge_rob',
 'garbage_cat_a_plastic_removed',
 'garbage_cat_b_organic_removed',
 'garbage_cat_c_domestic_removed',
 'garbage_cat_e_ashes_removed',
 'rob_garbage_cat_a_plastic',
 'rob_garbage_cat_b_organic',
 'rob_garbage_cat_c_domestic',
 'rob_garbage_cat_e_ashes',
 'qty_sludge_disposed',
 'steaming_time_m_e_lng',
 'reefer_power_consumption',
 'wind_direction_side',
 'sea_direction_side',
 'tot_sludge_removed']

In [11]:
noondata_final = noondata[noondata['imo'].isin(esi_own_lst)].reset_index(drop = True) #filter msc own vessels from noon data using client send vessel list
noondata_final

,id,pi_sog,pi_stw,true_wind_dir,true_wind_speed,relative_wind_speed,relative_wind_direction,caa,corrected_power,rw,...,rob_garbage_cat_a_plastic,rob_garbage_cat_b_organic,rob_garbage_cat_c_domestic,rob_garbage_cat_e_ashes,qty_sludge_disposed,steaming_time_m_e_lng,reefer_power_consumption,wind_direction_side,sea_direction_side,tot_sludge_removed
0,5742629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5744471,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5753018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5757751,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5775081,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112661,5771702,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112662,5771713,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112663,5913276,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,80.0,NaN,NaN,NaN
112664,5940155,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2500.0,NaN,NaN,NaN
112665,5759666,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN

In [12]:
noondata_final.rename(columns = {'total_steaming_time':'STEAMING_TIME', 'me_fuel_only_steaming_time':'Total_M_E_Hours_Fuel_Only',
                              'speed_by_log':'SPEED_BY_LOG','speed_by_gps':'SPEED_BY_GPS','power_kw':'POWER_KW'}, inplace = True)

In [13]:
#checking all vessels are there in noon data
#unique vessels in client send data is
esi_own['IMO'].nunique()

322

In [14]:
#unique vessels in noon data msc own vessels
noondata_final['imo'].nunique()

317

In [15]:
#they are not equal.so find which imos are missing
lst_own = esi_own['IMO'].unique().tolist()
lst_own

[9625970,
 9321897,
 9334519,
 9453298,
 9463205,
 9180205,
 9330226,
 9166778,
 9190119,
 8512906,
 9235581,
 9169055,
 9932921,
 9057173,
 9618276,
 9770751,
 9123166,
 9301990,
 9618288,
 9842097,
 9196852,
 9319600,
 9008603,
 9242651,
 9261827,
 9259379,
 9306275,
 9227297,
 8521402,
 9169122,
 9282261,
 9254848,
 9323041,
 9297864,
 9710426,
 9857169,
 9839284,
 9244881,
 9162631,
 9263344,
 8913447,
 8512891,
 9857183,
 9263332,
 9226932,
 9360764,
 9289099,
 9203904,
 9297876,
 9770749,
 9930935,
 9720495,
 9313967,
 9103685,
 9702106,
 9289087,
 9169043,
 9262546,
 9102722,
 9360271,
 9154220,
 9210086,
 9625944,
 9946879,
 9295397,
 9253038,
 9705005,
 9229300,
 9316361,
 9710438,
 9299537,
 9198587,
 9936642,
 9936628,
 9113446,
 9301550,
 9241463,
 9307267,
 9426817,
 9295165,
 9250983,
 9927287,
 9930959,
 9200689,
 9262560,
 9306263,
 9720201,
 9102746,
 9237151,
 9301328,
 9444285,
 9294824,
 9110391,
 9169029,
 9282259,
 9236688,
 9278143,
 9064750,
 9215892,
 9166780,
 9735218,
 9704972,
 8917778,
 9326823,
 9334832,
 9463047,
 9004231,
 8201648,
 9302633,
 9842085,
 9299032,
 9290402,
 9120853,
 8413875,
 9344708,
 9152856,
 9289051,
 9153850,
 9720196,
 9947134,
 9210062,
 9415296,
 9631876,
 9283708,
 9316347,
 9350317,
 9127540,
 9463281,
 9224946,
 9962562,
 9962586,
 9197545,
 9124366,
 9231248,
 9181651,
 9929429,
 8201624,
 9839272,
 9154206,
 9110975,
 9433157,
 9000742,
 9720471,
 9622007,
 9215672,
 8918980,
 9039250,
 9227338,
 9275036,
 9450351,
 9244946,
 9236585,
 9232656,
 9467445,
 9227302,
 9110389,
 9242637,
 9927299,
 9123154,
 9051507,
 9305506,
 9439735,
 9064748,
 9162643,
 9947158,
 9347762,
 9383223,
 9334349,
 9704960,
 9237498,
 9962598,
 9934735,
 9327798,
 9251690,
 9308625,
 9400148,
 9231119,
 9625932,
 9252553,
 9252541,
 8201636,
 9238882,
 8918966,
 9967263,
 9932892,
 9465318,
 8616520,
 9155107,
 9964194,
 9962574,
 9540077,
 9169031,
 9181663,
 9315915,
 9720287,
 9102710,
 9936630,
 9231779,
 9169067,
 9720512,
 9196864,
 9839260,
 9293179,
 9932050,
 9060649,
 9294991,
 9149328,
 9307839,
 9471226,
 8918954,
 9278155,
 9214898,
 9228576,
 9315886,
 9308584,
 9326768,
 9084607,
 9778117,
 9946843,
 9256315,
 9456965,
 9336359,
 9408774,
 9857157,
 9281267,
 9735206,
 9336165,
 9239903,
 9161297,
 9240328,
 9256391,
 9267637,
 9222302,
 9074042,
 9139086,
 9299020,
 9154191,
 9450325,
 9235402,
 9930052,
 9139505,
 9465306,
 9240873,
 9419644,
 9038907,
 9293167,
 9957359,
 9337676,
 8714205,
 9401166,
 9491616,
 9110377,
 9434462,
 9222106,
 9290426,
 8913411,
 9702261,
 9181675,
 8715857,
 9241451,
 9720500,
 9116369,
 9471238,
 9292175,
 9231822,
 8913423,
 9036002,
 9180968,
 9224049,
 9778105,
 9778076,
 9720457,
 9210098,
 9224348,
 9793947,
 9162277,
 9927275,
 9702091,
 9695028,
 9220328,
 9259393,
 9210050,
 8918978,
 9330068,
 9231262,
 9200677,
 9308601,
 9351579,
 9316373,
 9008574,
 9189366,
 9930038,
 9248928,
 9299525,
 9295177,
 9230775,
 9931288,
 9337444,
 9302619,
 9302621,
 9315836,
 9227340,
 9251688,
 9242625,
 9238739,
 9304708,
 9146479,
 9908059,
 9702089,
 9947122,
 9908047,
 9236690,
 9288409,
 9778090,
 9322011,
 9146467,
 9344564,
 9141285,
 9315018,
 9326964,
 9354363,
 9315006]

In [16]:
lst_noon = noondata_final['imo'].unique().tolist()
lst_noon

[9231822,
 9239903,
 9326768,
 9453298,
 9231779,
 9778105,
 9347762,
 9110389,
 9242637,
 9229300,
 8918954,
 9038907,
 9295177,
 8616520,
 9793947,
 9315836,
 9704960,
 9471238,
 9057173,
 8918966,
 9210062,
 8512906,
 9110391,
 9210050,
 9305506,
 9330068,
 8913447,
 9222302,
 9927299,
 9354363,
 9227338,
 9242651,
 9946879,
 9947158,
 9957359,
 9465318,
 9084607,
 9720196,
 9932921,
 9622007,
 9288409,
 9103685,
 8918980,
 9064750,
 9236690,
 9306275,
 9720201,
 9154206,
 9256315,
 9169122,
 9256391,
 9259393,
 9360764,
 9308625,
 9297876,
 9439735,
 9315018,
 9267637,
 8913423,
 9299525,
 8413875,
 9306263,
 9344708,
 9463047,
 8201624,
 9299537,
 9408774,
 9155107,
 9275036,
 9315886,
 8201648,
 9908059,
 9149328,
 9232656,
 9227340,
 9415296,
 9162631,
 9290426,
 9465306,
 9289099,
 9702106,
 9238739,
 9401166,
 9293167,
 9936630,
 9315006,
 9123166,
 9842085,
 9932050,
 9931288,
 9337676,
 9008603,
 9456965,
 9471226,
 9778117,
 9947122,
 9932892,
 8918978,
 9400148,
 9930959,
 8714205,
 9238882,
 9720471,
 9051507,
 9102710,
 9189366,
 9060649,
 9227297,
 9253038,
 9308584,
 9735206,
 9146467,
 9337444,
 9710438,
 9778090,
 9282261,
 9252553,
 9169043,
 9315915,
 9153850,
 9166778,
 9839284,
 9224348,
 9116369,
 9230775,
 9262546,
 9307267,
 9463205,
 9618288,
 9197545,
 9326964,
 9695028,
 9704972,
 9839272,
 9039250,
 8917778,
 9127540,
 9146479,
 9224946,
 9248928,
 9263332,
 9278155,
 9301990,
 9308601,
 9491616,
 9930052,
 9169055,
 9778076,
 9857157,
 9433157,
 9702089,
 9720457,
 9196864,
 9242625,
 8201636,
 9064748,
 9180968,
 9360271,
 9120853,
 9450351,
 9710426,
 9181663,
 9383223,
 9074042,
 9720500,
 9169067,
 9720287,
 9231119,
 8521402,
 9297864,
 9036002,
 8715857,
 9008574,
 9224049,
 9295397,
 9313967,
 9169031,
 9618276,
 9326823,
 9227302,
 9162277,
 9947134,
 9231248,
 9244881,
 9319600,
 9236585,
 9241451,
 9330226,
 9169029,
 9934735,
 9210098,
 9293179,
 9181651,
 9261827,
 9301328,
 9927275,
 9166780,
 9702261,
 9857169,
 9625944,
 9289087,
 9215892,
 9302619,
 9000742,
 9152856,
 9323041,
 9316361,
 9327798,
 9702091,
 9278143,
 9467445,
 9927287,
 9930935,
 9228576,
 9240328,
 9304708,
 9263344,
 9316347,
 9839260,
 9334832,
 9139505,
 9301550,
 9350317,
 9930038,
 9162643,
 9463281,
 9252541,
 9735218,
 9180205,
 9302621,
 9236688,
 9110975,
 9450325,
 9222106,
 9235581,
 9908047,
 9625932,
 9842097,
 9294824,
 9336359,
 9334349,
 9302633,
 9250983,
 9295165,
 9102746,
 9540077,
 9292175,
 9241463,
 9102722,
 9181675,
 9344564,
 9307839,
 9770751,
 9231262,
 9123154,
 9316373,
 9336165,
 9322011,
 9190119,
 8913411,
 9203904,
 9259379,
 9237498,
 9200689,
 9196852,
 8512891,
 9929429,
 9004231,
 9215672,
 9113446,
 9139086,
 9141285,
 9161297,
 9210086,
 9426817,
 9220328,
 9262560,
 9289051,
 9294991,
 9419644,
 9444285,
 9200677,
 9631876,
 9240873,
 9936642,
 9124366,
 9235402,
 9434462,
 9946843,
 9251688,
 9251690,
 9705005,
 9282259,
 9290402,
 9299020,
 9237151,
 9154191,
 9244946,
 9281267,
 9110377,
 9770749,
 9254848,
 9351579,
 9154220,
 9625970,
 9857183,
 9962574,
 9964194,
 9720495,
 9720512,
 9936628,
 9226932,
 9334519,
 9283708,
 9321897,
 9962562,
 9962586]

In [17]:
res_lst = []
for element in lst_own:
    if element not in lst_noon:
        res_lst.append(element)
res_lst

[9198587, 9299032, 9962598, 9967263, 9214898]

In [18]:
len(res_lst)

5

In [19]:
# check with client file. if the NAME of the vessels are shaded, then that is a new vessel - no data for that vessel. But if in case thats not shaded, go and check Charter data

### checking the data of the IMOs , there in the charter data

In [20]:
charter = pd.read_csv(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\CHARTER\ESI_CHARTERDATA_JAN24_JUN24.csv")
charter

,id,gid,vessel_name,imo,voy,corrected_date,report_date_time,report_date_time_offset,report_type,status,...,engine_last_change_user,created_date,created_at,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng
0,4504377,d3d9b992-4c1c-45f5-8339-b446dbae8c22,MSC GRACE F,8918057,JJ403A,2024-02-02,2024-2-1 14:30,UTC +03:00,BRTH,DRIFTING,...,C_E,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
1,4490015,63f76f9b-b1e7-4954-bb5d-a16f3ffa577c,MSC GRACE F,8918057,JJ348R,2024-01-01,2024-1-1 12:00,UTC +03:00,DLY A,DRIFTING,...,C_E,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
2,4504380,d065e7c5-2e6f-432a-abb6-f26a308c54f7,MSC GRACE F,8918057,JJ403A,2024-02-04,2024-2-4 12:00,UTC +03:00,PORT,IN PORT,...,C_E,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
3,4490017,efb7c60c-f3a7-41b0-a85a-b73752c5a5b7,MSC GRACE F,8918057,JJ348R,2024-01-03,2024-1-3 12:00,UTC +03:00,DLY A,DRIFTING,...,C_E,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
4,4490019,553e023c-de8d-47ee-964f-2788a0fa5c6b,MSC GRACE F,8918057,JJ348R,2024-01-05,2024-1-5 12:00,UTC +03:00,DLY A,DRIFTING,...,C_E,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109100,4407163,c957c3c7-e591-4569-a6e9-6bc00a77709f,KOTKA,90855340,IU4124A,2024-06-21,2024-6-21 6:24,UTC +05:30,BRTH,DRIFTING,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
109101,4407164,903cf1b4-1ddc-4a1f-a0e5-f918da52f5bf,KOTKA,90855340,IU4124A,2024-06-21,2024-6-21 12:00,UTC +05:30,PORT,IN PORT,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
109102,4407165,84d673eb-1403-4a05-8662-49bec9e95ea6,KOTKA,90855340,IU4124A,2024-06-22,2024-6-21 22:06,UTC +05:30,SAIL,IN PORT,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
109103,4407166,a73219c5-15e0-4d6c-8917-305af026b032,KOTKA,90855340,IU4124A,2024-06-22,2024-6-22 0:06,UTC +05:30,COSP,DRIFTING,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
109104,4407167,c5efabec-2581-4da6-9a74-81478991621f,KOTKA,90855340,IU4124A,2024-06-22,2024-6-22 12:00,UTC +05:30,NOON,AT SEA,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0

In [21]:
remaining_data = charter[charter['imo'].isin(res_lst)]
remaining_data

Empty DataFrame
Columns: [id, gid, vessel_name, imo, voy, corrected_date, report_date_time, report_date_time_offset, report_type, status, latitude, longitude, m_e_foc, cargo_total, has_cargo, steaming_time, total_m_e_hours_fuel_only, miles_by_gps, oil_cyl, speed_by_log, speed_by_gps, rpm, slip, wind_direction, wind_speed, draft_aft, draft_fwd, displacement, course_at_sea, wave_height, sea_direction, cargo_total_teu, ambient_temp, sw_temp, miles_by_speed_log, eta_port_code, eta_date_time, eta_date_time_offset, eta_port, time_change, time_sea, temp_min, temp_max, requested_speed, rem_dist_to_pilot, rem_time_to_pilot, total_unplnd_stpge_tech, total_unplnd_stpge_ope_wx, reefers_positive_plugged, reefers_negative_plugged, me_total_revs_counter, port_code, port, aux_blowers_on, hold_ventilation_on, since_date_time, since_date_time_offset, time_hrs_anchor, time_hrs_drift, reason, type_of_delay, etb_date_time, etb_date_time_offset, pilot_date_time, pilot_date_time_offset, time_manoeuvring, tug_arr, tug_shift, etd_date_time, etd_date_time_offset, shift_berth_hours, cargo_disch, teu_full, teu_empty, bilge_removed, garbage_removed, garbage_remvl_reqstd, garbage_remvl_cmplsry, fw_supply, cy_crew_signed_on, cy_crew_signed_off, cy_doctors_visit, cy_mail_received_ref_no, cy_lub_oil_sample_landed, cy_checkd_for_stowaways, cy_stowaways_on_board, cy_dep_gm_mtr, cy_requisitions_received, distance_to_next_pilot, tug_sailing_transit, steaming_time_m_e_rsdl_vls, steaming_time_m_e_rsdl_hs, steaming_time_m_e_rsdl_uls, steaming_time_m_e_dstlt_vls, steaming_time_m_e_dstlt_uls, steaming_time_m_e_tnktnr_dstlt_vls, steaming_time_m_e_hs, steaming_time_m_e_ls, steaming_time_m_e_mdo, steaming_time_m_e_mgo, ...]
Index: []

[0 rows x 257 columns]

In [22]:
# if the data of those vessels available in the charter data, then merge the data with noondata

## filling the Port_delivery column

In [23]:
noondata_final.columns.to_list()

['id',
 'pi_sog',
 'pi_stw',
 'true_wind_dir',
 'true_wind_speed',
 'relative_wind_speed',
 'relative_wind_direction',
 'caa',
 'corrected_power',
 'rw',
 'ref_speed',
 'imo',
 'vessel',
 'id_vessel',
 'gid',
 'voyage',
 'corrected_date',
 'report_date_time',
 'report_date_time_offset',
 'report_type',
 'status',
 'lat',
 'long',
 'latitude',
 'longitude',
 'me_foc',
 'cargo_total',
 'STEAMING_TIME',
 'Total_M_E_Hours_Fuel_Only',
 'miles_by_gps',
 'oil_cyl',
 'SPEED_BY_LOG',
 'SPEED_BY_GPS',
 'rpm',
 'slip',
 'wind_direction',
 'wind_speed',
 'draft_aft',
 'draft_fwd',
 'displacement',
 'course_at_sea',
 'wave_height',
 'sea_direction',
 'cargo_total_teu',
 'ambient_temp',
 'sw_temp',
 'miles_by_speed_log',
 'eta_port_code',
 'eta_date_time',
 'eta_date_time_offset',
 'eta_port',
 'time_change',
 'time_sea',
 'temp_min',
 'temp_max',
 'requested_speed',
 'rem_dist_to_pilot',
 'rem_time_to_pilot',
 'total_unplnd_stpge_tech',
 'total_unplnd_stpge_ope_wx',
 'reefers_positive_plugged',
 'reefers_negative_plugged',
 'me_total_revs_counter',
 'port_code',
 'port',
 'aux_blowers_on',
 'hold_ventilation_on',
 'since_date_time',
 'since_date_time_offset',
 'time_hrs_anchor',
 'time_hrs_drift',
 'reason',
 'type_of_delay',
 'etb_date_time',
 'etb_date_time_offset',
 'pilot_date_time',
 'pilot_date_time_offset',
 'time_manoeuvring',
 'tug_arr',
 'tug_shift',
 'etd_date_time',
 'etd_date_time_offset',
 'shift_berth_hours',
 'cargo_load',
 'cargo_disch',
 'teu_full',
 'teu_empty',
 'bilge_removed',
 'garbage_removed',
 'garbage_remvl_reqstd',
 'garbage_remvl_cmplsry',
 'fw_supply',
 'cy_crew_signed_on',
 'cy_crew_signed_off',
 'cy_doctors_visit',
 'cy_mail_received_ref_no',
 'cy_lub_oil_sample_landed',
 'cy_checkd_for_stowaways',
 'cy_stowaways_on_board',
 'cy_dep_gm_mtr',
 'cy_requisitions_received',
 'distance_to_next_pilot',
 'tug_sailing_transit',
 'steaming_time_me_rsdl_vls',
 'steaming_time_me_rsdl_hs',
 'steaming_time_me_rsdl_uls',
 'steaming_time_me_dstlt_vls',
 'steaming_time_me_dstlt_uls',
 'steaming_time_me_tnktnr_dstlt_vls',
 'steaming_time_me_mdo',
 'steaming_time_aux_1',
 'steaming_time_aux_2',
 'steaming_time_aux_3',
 'steaming_time_aux_4',
 'steaming_time_aux_5',
 'steaming_time_sh_gen',
 'steaming_time_tg',
 'fuel_me_rsdl_vls',
 'fuel_me_rsdl_hs',
 'fuel_me_rsdl_uls',
 'fuel_me_dstlt_vls',
 'fuel_me_dstlt_uls',
 'fuel_me_mdo',
 'fuel_me_tnktnr_dstlt_vls',
 'fuel_aux_rsdl_vls',
 'fuel_aux_rsdl_hs',
 'fuel_aux_rsdl_uls',
 'fuel_aux_dstlt_vls',
 'fuel_aux_dstlt_uls',
 'fuel_aux_tnktnr_dstlt_vls',
 'fuel_aux_mdo',
 'fuel_boiler_rsdl_vls',
 'fuel_boiler_rsdl_hs',
 'fuel_boiler_rsdl_uls',
 'fuel_boiler_dstlt_vls',
 'fuel_boiler_dstlt_uls',
 'fuel_boiler_tnktnr_dstlt_vls',
 'fuel_boiler_mdo',
 'POWER_KW',
 'steaming_load_kw_aux_1',
 'steaming_load_kw_aux_2',
 'steaming_load_kw_aux_3',
 'steaming_load_kw_aux_4',
 'steaming_load_kw_aux_5',
 'steaming_load_kw_sh_gen',
 'steaming_load_kw_tg',
 'deck_last_change_user',
 'engine_last_change_user',
 'deck_part_is_complete',
 'engine_part_is_complete',
 'scavenge_pressure',
 'seca_entry_time',
 'seca_entry_lat',
 'seca_entry_long',
 'seca_exit_time',
 'seca_exit_lat',
 'seca_exit_long',
 'rob_fresh_water',
 'manvrng_miles_by_gps',
 'manvrng_miles_by_speed_log',
 'tanktainer_transfd_quantity',
 'pilot_taken',
 'date_time_start_transit',
 'date_time_start_transit_offset',
 'date_time_end_transit',
 'date_time_end_transit_offset',
 'ballast',
 'tanktainer_number',
 'steaming_kwhr_total',
 'cy_others',
 'rob_fo_sludge',
 'rob_lo_sludge',
 'rob_bilge',
 'sludge_removed_fo',
 'sludge_removed_lo',
 'sea_state',
 'cy_lub_added_to_system_me_cc',
 'cy_lub_added_to_system_ae_cc',
 'cy_lub_added_to_thrusters',
 'cy_me_lo_purifier_in_use',
 'cy_ballast',
 'cy_bending_moment',
 'cy_shearing_force',
 'cy_tortion_moment',
 'cy_supdt_auditor_signed_on',
 'cy_supdt_auditor_signed_off',
 'cy_cash_received',
 'cy_lub_oil_received_me_cyl',
 'cy_lub_oil_received_me_cc',
 'cy_lub_oil_received_ae_cc',
 'cy_me_under_piston_temp',
 'cy_mail_received',
 'wind_direction_port_stbd',
 'sea_direction_port_stbd',
 'time_pilot_onboard',
 'grades_rob',
 'so_2_co_2_ratio',
 'bunker_order',
 'remarks',
 'bdn_number',
 'fuel_type',
 'carbon_factor',
 'sulphur_content_pc',
 'quantity',
 'port_delivery',
 'product_quality',
 'tanktainer_number_1',
 'supplier',
 'delivery',
 'volume_lt',
 'density',
 'viscosity',
 'rob_dstlt_uls',
 'rob_dstlt_vls',
 'rob_rsdl_mdo',
 'rob_tnktnr_dstlt_vls',
 'rob_rsdl_vls',
 'rob_rsdl_hs',
 'rob_rsdl_uls',
 'has_cargo',
 'steaming_time_me_hs',
 'steaming_time_me_ls',
 'steaming_time_me_mgo',
 'steaming_time_me_mgo_ls',
 'fuel_me_hs',
 'fuel_me_ls',
 'fuel_me_mgo',
 'fuel_me_mgo_ls',
 'fuel_aux_hs',
 'fuel_aux_ls',
 'fuel_aux_mgo',
 'fuel_aux_mgo_ls',
 'fuel_boiler_hs',
 'fuel_boiler_ls',
 'fuel_boiler_mgo',
 'fuel_boiler_mgo_ls',
 'rob_fuel_hs_fo',
 'rob_fuel_ls_fo',
 'rob_fuel_mdo',
 'rob_fuel_mgo',
 'rob_fuel_mgo_ls',
 'rob_fuel_tanktainer_mgo',
 'eca_miles',
 'eca_time',
 'egcs_dry_waste_removed',
 'egcs_running_time',
 'egcs_wet_slurry_removed',
 'egcs_open_loop_running_time',
 'egcs_closed_loop_running_time',
 'voyage_order',
 'voyage_code',
 'eca',
 'eu',
 'sea_time',
 'eta_country_code',
 'port_country_code',
 'check_eta_code',
 'check_port_code',
 'status_temp_eu',
 'fuel_hs',
 'fuel_ls',
 'fuel_mdo',
 'fuel_mgo',
 'fuel_mgo_ls',
 'cargo_transport_work',
 'teu_transport_work',
 'eeoi_voyage_no',
 'cargo_total_old',
 'draft',
 'fo_per_24_hrs',
 'sfoc',
 'cy_oil_gm_hr',
 'scoc',
 'voyage_name',
 'total_fo',
 'total_co_2',
 'eeoi',
 'voy_condition',
 'same_date',
 'time_since_last_report',
 'wind_direction_360',
 'ref_power',
 'ref_fuel',
 'fuel_loss',
 'draft_pow',
 'draft_sp_pow',
 'fo_nor',
 'fo_model',
 'sfoc_model',
 'sfoc_deviation',
 'ref_power_corrected',
 'ref_fo_corrected',
 'propulsive_eff',
 'speed_performance',
 'pi',
 'me_con',
 'ae_con',
 'bl_con',
 't_con',
 'hs',
 'ls',
 'mdo',
 'mgo',
 'mgo_ls',
 't_co_2',
 'ae_t_steaming',
 'ae_power',
 'trim',
 'distance_covered',
 'updated_date',
 'hyd_slip_sog',
 'hyd_slip_stw',
 'fuel_rsdl_hs',
 'fuel_rsdl_vls',
 'fuel_rsdl_uls',
 'fuel_dstlt_vls',
 'fuel_dstlt_uls',
 'fuel_tnktnr_dstlt_vls',
 'rsdl_hs',
 'rsdl_vls',
 'rsdl_uls',
 'dstlt_vls',
 'dstlt_uls',
 'tnktnr_dstlt_vls',
 'fuel_m_e_lng',
 'fuel_aux_lng',
 'fuel_boiler_lng',
 'rob_rsdl_lng',
 'sulphur_content_pc_main',
 'quantity_main',
 'port_delivery_main',
 'product_quality_main',
 'delivery_main',
 'bdn_number_main',
 'fo_nor_sog',
 'fo_nor_stw',
 'created_at',
 'updated_at',
 'created_by_id',
 'updated_by_id',
 'rob_lng',
 'sludge_rob',
 'garbage_cat_a_plastic_removed',
 'garbage_cat_b_organic_removed',
 'garbage_cat_c_domestic_removed',
 'garbage_cat_e_ashes_removed',
 'rob_garbage_cat_a_plastic',
 'rob_garbage_cat_b_organic',
 'rob_garbage_cat_c_domestic',
 'rob_garbage_cat_e_ashes',
 'qty_sludge_disposed',
 'steaming_time_m_e_lng',
 'reefer_power_consumption',
 'wind_direction_side',
 'sea_direction_side',
 'tot_sludge_removed']

In [24]:
noondata_final['port_delivery'] = noondata_final['port_delivery'].fillna(noondata_final['port_code'])
noondata_final

,id,pi_sog,pi_stw,true_wind_dir,true_wind_speed,relative_wind_speed,relative_wind_direction,caa,corrected_power,rw,...,rob_garbage_cat_a_plastic,rob_garbage_cat_b_organic,rob_garbage_cat_c_domestic,rob_garbage_cat_e_ashes,qty_sludge_disposed,steaming_time_m_e_lng,reefer_power_consumption,wind_direction_side,sea_direction_side,tot_sludge_removed
0,5742629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5744471,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5753018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5757751,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5775081,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112661,5771702,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112662,5771713,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112663,5913276,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,80.0,NaN,NaN,NaN
112664,5940155,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2500.0,NaN,NaN,NaN
112665,5759666,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN

### check the port_delivery column and replace the NaN values

In [25]:
values_to_replace = ['<N/A>', '<N_A>']
noondata_final['port_delivery'] = noondata_final['port_delivery'].replace(values_to_replace, np.nan)
noondata_final[noondata_final['port_delivery'] == '<N_A>']

Empty DataFrame
Columns: [id, pi_sog, pi_stw, true_wind_dir, true_wind_speed, relative_wind_speed, relative_wind_direction, caa, corrected_power, rw, ref_speed, imo, vessel, id_vessel, gid, voyage, corrected_date, report_date_time, report_date_time_offset, report_type, status, lat, long, latitude, longitude, me_foc, cargo_total, STEAMING_TIME, Total_M_E_Hours_Fuel_Only, miles_by_gps, oil_cyl, SPEED_BY_LOG, SPEED_BY_GPS, rpm, slip, wind_direction, wind_speed, draft_aft, draft_fwd, displacement, course_at_sea, wave_height, sea_direction, cargo_total_teu, ambient_temp, sw_temp, miles_by_speed_log, eta_port_code, eta_date_time, eta_date_time_offset, eta_port, time_change, time_sea, temp_min, temp_max, requested_speed, rem_dist_to_pilot, rem_time_to_pilot, total_unplnd_stpge_tech, total_unplnd_stpge_ope_wx, reefers_positive_plugged, reefers_negative_plugged, me_total_revs_counter, port_code, port, aux_blowers_on, hold_ventilation_on, since_date_time, since_date_time_offset, time_hrs_anchor, time_hrs_drift, reason, type_of_delay, etb_date_time, etb_date_time_offset, pilot_date_time, pilot_date_time_offset, time_manoeuvring, tug_arr, tug_shift, etd_date_time, etd_date_time_offset, shift_berth_hours, cargo_load, cargo_disch, teu_full, teu_empty, bilge_removed, garbage_removed, garbage_remvl_reqstd, garbage_remvl_cmplsry, fw_supply, cy_crew_signed_on, cy_crew_signed_off, cy_doctors_visit, cy_mail_received_ref_no, cy_lub_oil_sample_landed, cy_checkd_for_stowaways, cy_stowaways_on_board, cy_dep_gm_mtr, ...]
Index: []

[0 rows x 356 columns]

In [26]:
noondata_final[['port_code','port_delivery']]

       port_code port_delivery
0            NaN           NaN
1            NaN           NaN
2            NaN           NaN
3            NaN           NaN
4            NaN           NaN
...          ...           ...
112661     ITVCE         ITVCE
112662       NaN           NaN
112663     ITRAN         ITRAN
112664     SGSIN         SGSIN
112665     CNFAN         CNFAN

[112666 rows x 2 columns]

#### 2. Ffill and bfill

In [27]:
noondata_final = noondata_final.sort_values(['report_date_time'])
noondata_final

,id,pi_sog,pi_stw,true_wind_dir,true_wind_speed,relative_wind_speed,relative_wind_direction,caa,corrected_power,rw,...,rob_garbage_cat_a_plastic,rob_garbage_cat_b_organic,rob_garbage_cat_c_domestic,rob_garbage_cat_e_ashes,qty_sludge_disposed,steaming_time_m_e_lng,reefer_power_consumption,wind_direction_side,sea_direction_side,tot_sludge_removed
88376,5733388,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100991,5759240,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99146,5733092,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94762,5741971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.8,0.17,1.0,0.1,NaN,NaN,NaN,NaN,NaN,0.0
52550,5761282,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27559,6310734,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79239,6299314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45027,6300457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45355,6301752,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60049,6300456,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
noondata_final['port_delivery'] = noondata_final.groupby(['imo'])['port_delivery'].transform(lambda v: v.ffill())
noondata_final['port_delivery'] = noondata_final.groupby(['imo'])['port_delivery'].transform(lambda v: v.bfill())

In [29]:
noondata_final['port_delivery'].isna().sum()

0

In [30]:
rows_with_missing_values = noondata_final[noondata_final['port_delivery'].isna()]
rows_with_missing_values

Empty DataFrame
Columns: [id, pi_sog, pi_stw, true_wind_dir, true_wind_speed, relative_wind_speed, relative_wind_direction, caa, corrected_power, rw, ref_speed, imo, vessel, id_vessel, gid, voyage, corrected_date, report_date_time, report_date_time_offset, report_type, status, lat, long, latitude, longitude, me_foc, cargo_total, STEAMING_TIME, Total_M_E_Hours_Fuel_Only, miles_by_gps, oil_cyl, SPEED_BY_LOG, SPEED_BY_GPS, rpm, slip, wind_direction, wind_speed, draft_aft, draft_fwd, displacement, course_at_sea, wave_height, sea_direction, cargo_total_teu, ambient_temp, sw_temp, miles_by_speed_log, eta_port_code, eta_date_time, eta_date_time_offset, eta_port, time_change, time_sea, temp_min, temp_max, requested_speed, rem_dist_to_pilot, rem_time_to_pilot, total_unplnd_stpge_tech, total_unplnd_stpge_ope_wx, reefers_positive_plugged, reefers_negative_plugged, me_total_revs_counter, port_code, port, aux_blowers_on, hold_ventilation_on, since_date_time, since_date_time_offset, time_hrs_anchor, time_hrs_drift, reason, type_of_delay, etb_date_time, etb_date_time_offset, pilot_date_time, pilot_date_time_offset, time_manoeuvring, tug_arr, tug_shift, etd_date_time, etd_date_time_offset, shift_berth_hours, cargo_load, cargo_disch, teu_full, teu_empty, bilge_removed, garbage_removed, garbage_remvl_reqstd, garbage_remvl_cmplsry, fw_supply, cy_crew_signed_on, cy_crew_signed_off, cy_doctors_visit, cy_mail_received_ref_no, cy_lub_oil_sample_landed, cy_checkd_for_stowaways, cy_stowaways_on_board, cy_dep_gm_mtr, ...]
Index: []

[0 rows x 356 columns]

In [31]:
#rows_with_missing_values.to_excel('/Users/Ann Mary Thomas/Downloads/check2.xlsx')

### adding REMARK column

In [32]:
columns = ['sulphur_content_pc','quantity']
noondata_final[columns].dtypes

sulphur_content_pc    float64
quantity              float64
dtype: object

In [33]:
noondata_final['quantity'] = noondata_final['quantity'].astype(float)

In [34]:
FINALNOON = noondata_final

In [61]:
noondata_final.to_csv('noondata_final.csv')

In [37]:
# Access data for the vessel with IMO number 9704960
vessel_data = noondata_final[noondata_final['imo'] == 9704960]

In [42]:
# Ensure 'report_date_time' is in datetime format
vessel_data['report_date_time'] = pd.to_datetime(noondata_final['report_date_time'])

# Extract the date part and get unique dates
unique_dates = vessel_data['report_date_time'].dt.date.unique()

# Convert to a list if needed
unique_dates_list = unique_dates.tolist()

# Display the unique dates
print(unique_dates_list)

[datetime.date(2024, 1, 1), datetime.date(2024, 1, 2), datetime.date(2024, 1, 3), datetime.date(2024, 1, 4), datetime.date(2024, 1, 5), datetime.date(2024, 1, 6), datetime.date(2024, 1, 7), datetime.date(2024, 1, 8), datetime.date(2024, 1, 9), datetime.date(2024, 1, 10), datetime.date(2024, 1, 11), datetime.date(2024, 1, 12), datetime.date(2024, 1, 13), datetime.date(2024, 1, 14), datetime.date(2024, 1, 15), datetime.date(2024, 1, 16), datetime.date(2024, 1, 17), datetime.date(2024, 1, 18), datetime.date(2024, 1, 19), datetime.date(2024, 1, 20), datetime.date(2024, 1, 21), datetime.date(2024, 1, 22), datetime.date(2024, 1, 23), datetime.date(2024, 1, 24), datetime.date(2024, 1, 25), datetime.date(2024, 1, 26), datetime.date(2024, 1, 27), datetime.date(2024, 1, 28), datetime.date(2024, 1, 29), datetime.date(2024, 1, 30), datetime.date(2024, 1, 31), datetime.date(2024, 2, 1), datetime.date(2024, 2, 2), datetime.date(2024, 2, 3), datetime.date(2024, 2, 4), datetime.date(2024, 2, 5), datetime.date(2024, 2, 6), datetime.date(2024, 2, 7), datetime.date(2024, 2, 8), datetime.date(2024, 2, 9), datetime.date(2024, 2, 10), datetime.date(2024, 2, 11), datetime.date(2024, 2, 12), datetime.date(2024, 2, 13), datetime.date(2024, 2, 14), datetime.date(2024, 2, 15), datetime.date(2024, 2, 16), datetime.date(2024, 2, 17), datetime.date(2024, 2, 18), datetime.date(2024, 2, 19), datetime.date(2024, 2, 20), datetime.date(2024, 2, 21), datetime.date(2024, 2, 22), datetime.date(2024, 2, 23), datetime.date(2024, 2, 24), datetime.date(2024, 2, 25), datetime.date(2024, 2, 26), datetime.date(2024, 2, 27), datetime.date(2024, 2, 28), datetime.date(2024, 2, 29), datetime.date(2024, 3, 1), datetime.date(2024, 3, 2), datetime.date(2024, 3, 3), datetime.date(2024, 3, 4), datetime.date(2024, 3, 5), datetime.date(2024, 3, 6), datetime.date(2024, 3, 7), datetime.date(2024, 3, 8), datetime.date(2024, 3, 9), datetime.date(2024, 3, 10), datetime.date(2024, 3, 11), datetime.date(2024, 3, 12), datetime.date(2024, 3, 13), datetime.date(2024, 3, 14), datetime.date(2024, 3, 15), datetime.date(2024, 3, 16), datetime.date(2024, 3, 17), datetime.date(2024, 3, 18), datetime.date(2024, 3, 19), datetime.date(2024, 3, 20), datetime.date(2024, 3, 21), datetime.date(2024, 3, 22), datetime.date(2024, 3, 23), datetime.date(2024, 3, 24), datetime.date(2024, 3, 25), datetime.date(2024, 3, 26), datetime.date(2024, 3, 27), datetime.date(2024, 3, 28), datetime.date(2024, 3, 29), datetime.date(2024, 3, 30), datetime.date(2024, 3, 31), datetime.date(2024, 4, 1), datetime.date(2024, 4, 2), datetime.date(2024, 4, 3), datetime.date(2024, 4, 4), datetime.date(2024, 4, 5), datetime.date(2024, 4, 6), datetime.date(2024, 4, 7), datetime.date(2024, 4, 8), datetime.date(2024, 4, 9), datetime.date(2024, 4, 10), datetime.date(2024, 4, 11), datetime.date(2024, 4, 12), datetime.date(2024, 4, 13), datetime.date(2024, 4, 14), datetime.date(2024, 4, 15), datetime.date(2024, 4, 16), datetime.date(2024, 4, 17), datetime.date(2024, 4, 18), datetime.date(2024, 4, 19), datetime.date(2024, 4, 20), datetime.date(2024, 4, 21), datetime.date(2024, 4, 22), datetime.date(2024, 4, 23), datetime.date(2024, 4, 24), datetime.date(2024, 4, 25), datetime.date(2024, 4, 26), datetime.date(2024, 4, 27), datetime.date(2024, 4, 28), datetime.date(2024, 4, 29), datetime.date(2024, 4, 30), datetime.date(2024, 5, 1), datetime.date(2024, 5, 2), datetime.date(2024, 5, 3), datetime.date(2024, 5, 4), datetime.date(2024, 5, 5), datetime.date(2024, 5, 6), datetime.date(2024, 5, 7), datetime.date(2024, 5, 8), datetime.date(2024, 5, 9), datetime.date(2024, 5, 10), datetime.date(2024, 5, 11), datetime.date(2024, 5, 12), datetime.date(2024, 5, 13), datetime.date(2024, 5, 14), datetime.date(2024, 5, 15), datetime.date(2024, 5, 16), datetime.date(2024, 5, 17), datetime.date(2024, 5, 18), datetime.date(2024, 5, 19), datetime.date(2024, 5, 20), datetime.date(2024, 5, 21), datetime.date(2024, 5, 22), datetime.date(2024, 5, 23), datetime.date(2024, 5, 24), datetime.date(2024, 5, 25), datetime.date(2024, 5, 26), datetime.date(2024, 5, 27), datetime.date(2024, 5, 28), datetime.date(2024, 5, 29), datetime.date(2024, 5, 30), datetime.date(2024, 5, 31), datetime.date(2024, 6, 1), datetime.date(2024, 6, 2), datetime.date(2024, 6, 3), datetime.date(2024, 6, 4), datetime.date(2024, 6, 5), datetime.date(2024, 6, 6), datetime.date(2024, 6, 7), datetime.date(2024, 6, 8), datetime.date(2024, 6, 9), datetime.date(2024, 6, 10), datetime.date(2024, 6, 11), datetime.date(2024, 6, 12), datetime.date(2024, 6, 13), datetime.date(2024, 6, 14), datetime.date(2024, 6, 15), datetime.date(2024, 6, 16), datetime.date(2024, 6, 17), datetime.date(2024, 6, 18), datetime.date(2024, 6, 19), datetime.date(2024, 6, 20), datetime.date(2024, 6, 21), datetime.date(2024, 6, 22), datetime.date(2024, 6, 23), datetime.date(2024, 6, 24), datetime.date(2024, 6, 25), datetime.date(2024, 6, 26), datetime.date(2024, 6, 27), datetime.date(2024, 6, 28), datetime.date(2024, 6, 29)]

In [45]:
#use python remarks function next
def remark(data1):
    r1 = data1[data1['sulphur_content_pc']==0]
    r1['Remarks'] = "Sulphur is not given"
    hs_data = data1[data1['fuel_type']=='RESIDUAL HS']
    r2 = hs_data[(hs_data['sulphur_content_pc']<0.5) | (hs_data['sulphur_content_pc']>3.5) ]
    r2['Remarks'] = "Fuel Type or Sulphur will be wrong"
    ls_data = data1[(data1['fuel_type']=='RESIDUAL VLS') | (data1['fuel_type']=='DISTILLATE ULS')| (data1['fuel_type']=='DISTILLATE VLS') | (data1['fuel_type']=='RESIDUAL ULS')  | (data1['fuel_type']=='TANKTAINER DISTILLATE VLS')]
    r3 = ls_data[(ls_data['sulphur_content_pc']<0) | (ls_data['sulphur_content_pc']>0.5) ]
    r3['Remarks'] = "Fuel Type or Sulphur will be wrong"
    r4 = data1[data1['sulphur_content_pc'].isnull()]
    r4['Remarks'] = "Sulphur is not given"
    r5 = data1[data1['quantity']<=0]
    r5['Remarks'] = "quantity is not given"
    r6 = data1[data1['quantity'].isnull()]
    r6['Remarks'] = "quantity is not given"
    r7 = data1[data1['bdn_number'].isnull()]
    r7['Remarks'] = "BDN is not given"
    data1["joinall"]= data1['bdn_number'].str.replace(r'[-_\s.,/]+', '')
    data1["is_alpha_Delivery"]= data1["joinall"].str.isalpha()
    r8 = data1[data1['is_alpha_Delivery']==True]
    r8['Remarks'] = "BDN is not given"
    r9 = data1[data1['bdn_number']=='0']
    r9['Remarks'] = "BDN is not given"
    df = pd.concat([r1,r2,r3,r4,r5,r6,r7,r8,r9])
    df.drop('is_alpha_Delivery', axis=1, inplace=True)
    df.drop('joinall', axis=1, inplace=True)
    p = df.groupby('gid')['Remarks'].agg(','.join).reset_index()
    dict_remarks = pd.Series(p['Remarks'].values,index=p['gid']).to_dict()
    import numpy as np
    df['REMARKS'] = np.nan
    df['REMARKS'] = df['REMARKS'].fillna(df['gid'].apply(lambda x:dict_remarks.get(x)))
    df.drop('Remarks', axis=1, inplace=True)
    df.drop_duplicates(keep='first',inplace=True)
    return df

In [46]:
output = remark(FINALNOON)
output

,id,pi_sog,pi_stw,true_wind_dir,true_wind_speed,relative_wind_speed,relative_wind_direction,caa,corrected_power,rw,...,rob_garbage_cat_b_organic,rob_garbage_cat_c_domestic,rob_garbage_cat_e_ashes,qty_sludge_disposed,steaming_time_m_e_lng,reefer_power_consumption,wind_direction_side,sea_direction_side,tot_sludge_removed,REMARKS
111118,5764561,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sulphur is not given
2477,5754557,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sulphur is not given
91970,5763623,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sulphur is not given
88083,5751895,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sulphur is not given
57105,5763654,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sulphur is not given
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82833,5758401,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BDN is not given
47,5758405,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BDN is not given
65932,6294577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BDN is not given
32138,6294591,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BDN is not given
5799,6269131,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BDN is not given

In [60]:
output.to_csv("output.csv")

In [48]:
vsl_data = output[output['imo'] == 9704960]

In [50]:
# Ensure 'report_date_time' is in datetime format
vsl_data['report_date_time'] = pd.to_datetime(noondata_final['report_date_time'])

# Extract the date part and get unique dates
unique_dates = vsl_data['report_date_time'].dt.date.unique()

# Convert to a list if needed
unique_dates_list = unique_dates.tolist()

# Display the unique dates
print(unique_dates_list)

[datetime.date(2024, 1, 1), datetime.date(2024, 1, 2), datetime.date(2024, 1, 3), datetime.date(2024, 1, 4), datetime.date(2024, 1, 5), datetime.date(2024, 1, 6), datetime.date(2024, 1, 7), datetime.date(2024, 1, 8), datetime.date(2024, 1, 9), datetime.date(2024, 1, 10), datetime.date(2024, 1, 11), datetime.date(2024, 1, 12), datetime.date(2024, 1, 13), datetime.date(2024, 1, 14), datetime.date(2024, 1, 15), datetime.date(2024, 1, 16), datetime.date(2024, 1, 17), datetime.date(2024, 1, 18), datetime.date(2024, 1, 19), datetime.date(2024, 1, 20), datetime.date(2024, 1, 21), datetime.date(2024, 1, 22), datetime.date(2024, 1, 23), datetime.date(2024, 1, 24), datetime.date(2024, 1, 25), datetime.date(2024, 1, 26), datetime.date(2024, 1, 27), datetime.date(2024, 1, 28), datetime.date(2024, 1, 29), datetime.date(2024, 1, 30), datetime.date(2024, 1, 31), datetime.date(2024, 2, 1), datetime.date(2024, 2, 2), datetime.date(2024, 2, 3), datetime.date(2024, 2, 4), datetime.date(2024, 2, 5), datetime.date(2024, 2, 6), datetime.date(2024, 2, 7), datetime.date(2024, 2, 8), datetime.date(2024, 2, 9), datetime.date(2024, 2, 10), datetime.date(2024, 2, 11), datetime.date(2024, 2, 12), datetime.date(2024, 2, 13), datetime.date(2024, 2, 14), datetime.date(2024, 2, 15), datetime.date(2024, 2, 16), datetime.date(2024, 2, 17), datetime.date(2024, 2, 18), datetime.date(2024, 2, 19), datetime.date(2024, 2, 20), datetime.date(2024, 2, 21), datetime.date(2024, 2, 22), datetime.date(2024, 2, 23), datetime.date(2024, 2, 24), datetime.date(2024, 2, 25), datetime.date(2024, 2, 26), datetime.date(2024, 2, 27), datetime.date(2024, 2, 28), datetime.date(2024, 2, 29), datetime.date(2024, 3, 1), datetime.date(2024, 3, 2), datetime.date(2024, 3, 3), datetime.date(2024, 3, 4), datetime.date(2024, 3, 5), datetime.date(2024, 3, 6), datetime.date(2024, 3, 7), datetime.date(2024, 3, 8), datetime.date(2024, 3, 9), datetime.date(2024, 3, 10), datetime.date(2024, 3, 11), datetime.date(2024, 3, 12), datetime.date(2024, 3, 13), datetime.date(2024, 3, 14), datetime.date(2024, 3, 15), datetime.date(2024, 3, 16), datetime.date(2024, 3, 17), datetime.date(2024, 3, 18), datetime.date(2024, 3, 19), datetime.date(2024, 3, 20), datetime.date(2024, 3, 21), datetime.date(2024, 3, 22), datetime.date(2024, 3, 23), datetime.date(2024, 3, 24), datetime.date(2024, 3, 25), datetime.date(2024, 3, 26), datetime.date(2024, 3, 27), datetime.date(2024, 3, 28), datetime.date(2024, 3, 29), datetime.date(2024, 3, 30), datetime.date(2024, 3, 31), datetime.date(2024, 4, 1), datetime.date(2024, 4, 2), datetime.date(2024, 4, 3), datetime.date(2024, 4, 4), datetime.date(2024, 4, 5), datetime.date(2024, 4, 6), datetime.date(2024, 4, 7), datetime.date(2024, 4, 8), datetime.date(2024, 4, 9), datetime.date(2024, 4, 10), datetime.date(2024, 4, 11), datetime.date(2024, 4, 12), datetime.date(2024, 4, 13), datetime.date(2024, 4, 14), datetime.date(2024, 4, 15), datetime.date(2024, 4, 16), datetime.date(2024, 4, 17), datetime.date(2024, 4, 18), datetime.date(2024, 4, 19), datetime.date(2024, 4, 20), datetime.date(2024, 4, 21), datetime.date(2024, 4, 22), datetime.date(2024, 4, 23), datetime.date(2024, 4, 24), datetime.date(2024, 4, 25), datetime.date(2024, 4, 26), datetime.date(2024, 4, 27), datetime.date(2024, 4, 28), datetime.date(2024, 4, 29), datetime.date(2024, 4, 30), datetime.date(2024, 5, 1), datetime.date(2024, 5, 2), datetime.date(2024, 5, 3), datetime.date(2024, 5, 4), datetime.date(2024, 5, 5), datetime.date(2024, 5, 6), datetime.date(2024, 5, 7), datetime.date(2024, 5, 8), datetime.date(2024, 5, 9), datetime.date(2024, 5, 10), datetime.date(2024, 5, 11), datetime.date(2024, 5, 12), datetime.date(2024, 5, 13), datetime.date(2024, 5, 14), datetime.date(2024, 5, 15), datetime.date(2024, 5, 16), datetime.date(2024, 5, 17), datetime.date(2024, 5, 18), datetime.date(2024, 5, 19), datetime.date(2024, 5, 20), datetime.date(2024, 5, 21), datetime.date(2024, 5, 22), datetime.date(2024, 5, 23), datetime.date(2024, 5, 24), datetime.date(2024, 5, 25), datetime.date(2024, 5, 26), datetime.date(2024, 5, 27), datetime.date(2024, 5, 28), datetime.date(2024, 5, 29), datetime.date(2024, 5, 30), datetime.date(2024, 5, 31), datetime.date(2024, 6, 1), datetime.date(2024, 6, 2), datetime.date(2024, 6, 3), datetime.date(2024, 6, 4), datetime.date(2024, 6, 5), datetime.date(2024, 6, 6), datetime.date(2024, 6, 7), datetime.date(2024, 6, 8), datetime.date(2024, 6, 9), datetime.date(2024, 6, 10), datetime.date(2024, 6, 11), datetime.date(2024, 6, 12), datetime.date(2024, 6, 13), datetime.date(2024, 6, 14), datetime.date(2024, 6, 15), datetime.date(2024, 6, 16), datetime.date(2024, 6, 17), datetime.date(2024, 6, 18), datetime.date(2024, 6, 19), datetime.date(2024, 6, 20), datetime.date(2024, 6, 21), datetime.date(2024, 6, 22), datetime.date(2024, 6, 23), datetime.date(2024, 6, 24), datetime.date(2024, 6, 25), datetime.date(2024, 6, 26), datetime.date(2024, 6, 27), datetime.date(2024, 6, 28), datetime.date(2024, 6, 29)]

In [51]:
#Join this remarks to main data
dict_remark = pd.Series(output['REMARKS'].values,index=output['gid']).to_dict()
import numpy as np
FINALNOON['REMARKS'] = np.nan
FINALNOON['REMARKS'] = FINALNOON['REMARKS'].fillna(FINALNOON['gid'].apply(lambda x:dict_remark.get(x)))
FINALNOON

,id,pi_sog,pi_stw,true_wind_dir,true_wind_speed,relative_wind_speed,relative_wind_direction,caa,corrected_power,rw,...,rob_garbage_cat_e_ashes,qty_sludge_disposed,steaming_time_m_e_lng,reefer_power_consumption,wind_direction_side,sea_direction_side,tot_sludge_removed,joinall,is_alpha_Delivery,REMARKS
88376,5733388,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
100991,5759240,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
99146,5733092,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
94762,5741971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.1,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
52550,5761282,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27559,6310734,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
79239,6299314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
45027,6300457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
45355,6301752,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
60049,6300456,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."

In [52]:
FINALNOON.drop('is_alpha_Delivery', axis=1, inplace=True)
FINALNOON.drop('joinall', axis=1, inplace=True)
FINALNOON

,id,pi_sog,pi_stw,true_wind_dir,true_wind_speed,relative_wind_speed,relative_wind_direction,caa,corrected_power,rw,...,rob_garbage_cat_b_organic,rob_garbage_cat_c_domestic,rob_garbage_cat_e_ashes,qty_sludge_disposed,steaming_time_m_e_lng,reefer_power_consumption,wind_direction_side,sea_direction_side,tot_sludge_removed,REMARKS
88376,5733388,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
100991,5759240,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
99146,5733092,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
94762,5741971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.17,1.0,0.1,NaN,NaN,NaN,NaN,NaN,0.0,"Sulphur is not given,quantity is not given,BDN..."
52550,5761282,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27559,6310734,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
79239,6299314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
45027,6300457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
45355,6301752,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
60049,6300456,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."

In [53]:
#changes to Delivery column - > MANUALLY CHECK ALL PROBLEMS IN DELIVERY COLUMN

# 1.if delivery column having 0 or multiple 0 then Remarks updated as 'BDN not given'
# 2.if 'BDN' comes first or last ,then remove 'BDN'
# 3. if '.' is comes at last , then remove it
# 4. if '.' comes in between , then change it to underscore
# 5. if * and _ comes last or first ,it can be removed using following function

In [54]:
#if delivery column starts or ends with underscore(_ and *)
def delivery_modification(FINALNOON):
    FINALNOON["bdn_number"] = FINALNOON["bdn_number"].astype('string')
    FINALNOON_nan=FINALNOON[FINALNOON['bdn_number'].isna()]
    FINALNOON_nan_gid_list = list(FINALNOON_nan['gid'])
    FINALNOON_not_nan=FINALNOON[~FINALNOON['gid'].isin(FINALNOON_nan_gid_list)]
    FINALNOON_not_nan["bdn_number"] = FINALNOON_not_nan["bdn_number"].apply(lambda x: x.strip("_*"))
    FINALNOON_delivery_concat = pd.concat([FINALNOON_not_nan,FINALNOON_nan])
    FINALNOON = FINALNOON.drop(['bdn_number'], axis=1)
    dict_noon_delivery = pd.Series(FINALNOON_delivery_concat['bdn_number'].values,index=FINALNOON_delivery_concat['gid']).to_dict()
    FINALNOON['bdn_number'] = np.nan
    FINALNOON['bdn_number'] = FINALNOON['bdn_number'].fillna(FINALNOON['gid'].apply(lambda x:dict_noon_delivery.get(x)))
    return FINALNOON

In [55]:
FINALNOON = delivery_modification(FINALNOON)
FINALNOON

,id,pi_sog,pi_stw,true_wind_dir,true_wind_speed,relative_wind_speed,relative_wind_direction,caa,corrected_power,rw,...,rob_garbage_cat_c_domestic,rob_garbage_cat_e_ashes,qty_sludge_disposed,steaming_time_m_e_lng,reefer_power_consumption,wind_direction_side,sea_direction_side,tot_sludge_removed,REMARKS,bdn_number
88376,5733388,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",NaN
100991,5759240,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",NaN
99146,5733092,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",NaN
94762,5741971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,0.1,NaN,NaN,NaN,NaN,NaN,0.0,"Sulphur is not given,quantity is not given,BDN...",NaN
52550,5761282,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27559,6310734,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",NaN
79239,6299314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",NaN
45027,6300457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",NaN
45355,6301752,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",NaN
60049,6300456,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",NaN

In [56]:
FINALNOON.columns.to_list()

['id',
 'pi_sog',
 'pi_stw',
 'true_wind_dir',
 'true_wind_speed',
 'relative_wind_speed',
 'relative_wind_direction',
 'caa',
 'corrected_power',
 'rw',
 'ref_speed',
 'imo',
 'vessel',
 'id_vessel',
 'gid',
 'voyage',
 'corrected_date',
 'report_date_time',
 'report_date_time_offset',
 'report_type',
 'status',
 'lat',
 'long',
 'latitude',
 'longitude',
 'me_foc',
 'cargo_total',
 'STEAMING_TIME',
 'Total_M_E_Hours_Fuel_Only',
 'miles_by_gps',
 'oil_cyl',
 'SPEED_BY_LOG',
 'SPEED_BY_GPS',
 'rpm',
 'slip',
 'wind_direction',
 'wind_speed',
 'draft_aft',
 'draft_fwd',
 'displacement',
 'course_at_sea',
 'wave_height',
 'sea_direction',
 'cargo_total_teu',
 'ambient_temp',
 'sw_temp',
 'miles_by_speed_log',
 'eta_port_code',
 'eta_date_time',
 'eta_date_time_offset',
 'eta_port',
 'time_change',
 'time_sea',
 'temp_min',
 'temp_max',
 'requested_speed',
 'rem_dist_to_pilot',
 'rem_time_to_pilot',
 'total_unplnd_stpge_tech',
 'total_unplnd_stpge_ope_wx',
 'reefers_positive_plugged',
 'reefers_negative_plugged',
 'me_total_revs_counter',
 'port_code',
 'port',
 'aux_blowers_on',
 'hold_ventilation_on',
 'since_date_time',
 'since_date_time_offset',
 'time_hrs_anchor',
 'time_hrs_drift',
 'reason',
 'type_of_delay',
 'etb_date_time',
 'etb_date_time_offset',
 'pilot_date_time',
 'pilot_date_time_offset',
 'time_manoeuvring',
 'tug_arr',
 'tug_shift',
 'etd_date_time',
 'etd_date_time_offset',
 'shift_berth_hours',
 'cargo_load',
 'cargo_disch',
 'teu_full',
 'teu_empty',
 'bilge_removed',
 'garbage_removed',
 'garbage_remvl_reqstd',
 'garbage_remvl_cmplsry',
 'fw_supply',
 'cy_crew_signed_on',
 'cy_crew_signed_off',
 'cy_doctors_visit',
 'cy_mail_received_ref_no',
 'cy_lub_oil_sample_landed',
 'cy_checkd_for_stowaways',
 'cy_stowaways_on_board',
 'cy_dep_gm_mtr',
 'cy_requisitions_received',
 'distance_to_next_pilot',
 'tug_sailing_transit',
 'steaming_time_me_rsdl_vls',
 'steaming_time_me_rsdl_hs',
 'steaming_time_me_rsdl_uls',
 'steaming_time_me_dstlt_vls',
 'steaming_time_me_dstlt_uls',
 'steaming_time_me_tnktnr_dstlt_vls',
 'steaming_time_me_mdo',
 'steaming_time_aux_1',
 'steaming_time_aux_2',
 'steaming_time_aux_3',
 'steaming_time_aux_4',
 'steaming_time_aux_5',
 'steaming_time_sh_gen',
 'steaming_time_tg',
 'fuel_me_rsdl_vls',
 'fuel_me_rsdl_hs',
 'fuel_me_rsdl_uls',
 'fuel_me_dstlt_vls',
 'fuel_me_dstlt_uls',
 'fuel_me_mdo',
 'fuel_me_tnktnr_dstlt_vls',
 'fuel_aux_rsdl_vls',
 'fuel_aux_rsdl_hs',
 'fuel_aux_rsdl_uls',
 'fuel_aux_dstlt_vls',
 'fuel_aux_dstlt_uls',
 'fuel_aux_tnktnr_dstlt_vls',
 'fuel_aux_mdo',
 'fuel_boiler_rsdl_vls',
 'fuel_boiler_rsdl_hs',
 'fuel_boiler_rsdl_uls',
 'fuel_boiler_dstlt_vls',
 'fuel_boiler_dstlt_uls',
 'fuel_boiler_tnktnr_dstlt_vls',
 'fuel_boiler_mdo',
 'POWER_KW',
 'steaming_load_kw_aux_1',
 'steaming_load_kw_aux_2',
 'steaming_load_kw_aux_3',
 'steaming_load_kw_aux_4',
 'steaming_load_kw_aux_5',
 'steaming_load_kw_sh_gen',
 'steaming_load_kw_tg',
 'deck_last_change_user',
 'engine_last_change_user',
 'deck_part_is_complete',
 'engine_part_is_complete',
 'scavenge_pressure',
 'seca_entry_time',
 'seca_entry_lat',
 'seca_entry_long',
 'seca_exit_time',
 'seca_exit_lat',
 'seca_exit_long',
 'rob_fresh_water',
 'manvrng_miles_by_gps',
 'manvrng_miles_by_speed_log',
 'tanktainer_transfd_quantity',
 'pilot_taken',
 'date_time_start_transit',
 'date_time_start_transit_offset',
 'date_time_end_transit',
 'date_time_end_transit_offset',
 'ballast',
 'tanktainer_number',
 'steaming_kwhr_total',
 'cy_others',
 'rob_fo_sludge',
 'rob_lo_sludge',
 'rob_bilge',
 'sludge_removed_fo',
 'sludge_removed_lo',
 'sea_state',
 'cy_lub_added_to_system_me_cc',
 'cy_lub_added_to_system_ae_cc',
 'cy_lub_added_to_thrusters',
 'cy_me_lo_purifier_in_use',
 'cy_ballast',
 'cy_bending_moment',
 'cy_shearing_force',
 'cy_tortion_moment',
 'cy_supdt_auditor_signed_on',
 'cy_supdt_auditor_signed_off',
 'cy_cash_received',
 'cy_lub_oil_received_me_cyl',
 'cy_lub_oil_received_me_cc',
 'cy_lub_oil_received_ae_cc',
 'cy_me_under_piston_temp',
 'cy_mail_received',
 'wind_direction_port_stbd',
 'sea_direction_port_stbd',
 'time_pilot_onboard',
 'grades_rob',
 'so_2_co_2_ratio',
 'bunker_order',
 'remarks',
 'fuel_type',
 'carbon_factor',
 'sulphur_content_pc',
 'quantity',
 'port_delivery',
 'product_quality',
 'tanktainer_number_1',
 'supplier',
 'delivery',
 'volume_lt',
 'density',
 'viscosity',
 'rob_dstlt_uls',
 'rob_dstlt_vls',
 'rob_rsdl_mdo',
 'rob_tnktnr_dstlt_vls',
 'rob_rsdl_vls',
 'rob_rsdl_hs',
 'rob_rsdl_uls',
 'has_cargo',
 'steaming_time_me_hs',
 'steaming_time_me_ls',
 'steaming_time_me_mgo',
 'steaming_time_me_mgo_ls',
 'fuel_me_hs',
 'fuel_me_ls',
 'fuel_me_mgo',
 'fuel_me_mgo_ls',
 'fuel_aux_hs',
 'fuel_aux_ls',
 'fuel_aux_mgo',
 'fuel_aux_mgo_ls',
 'fuel_boiler_hs',
 'fuel_boiler_ls',
 'fuel_boiler_mgo',
 'fuel_boiler_mgo_ls',
 'rob_fuel_hs_fo',
 'rob_fuel_ls_fo',
 'rob_fuel_mdo',
 'rob_fuel_mgo',
 'rob_fuel_mgo_ls',
 'rob_fuel_tanktainer_mgo',
 'eca_miles',
 'eca_time',
 'egcs_dry_waste_removed',
 'egcs_running_time',
 'egcs_wet_slurry_removed',
 'egcs_open_loop_running_time',
 'egcs_closed_loop_running_time',
 'voyage_order',
 'voyage_code',
 'eca',
 'eu',
 'sea_time',
 'eta_country_code',
 'port_country_code',
 'check_eta_code',
 'check_port_code',
 'status_temp_eu',
 'fuel_hs',
 'fuel_ls',
 'fuel_mdo',
 'fuel_mgo',
 'fuel_mgo_ls',
 'cargo_transport_work',
 'teu_transport_work',
 'eeoi_voyage_no',
 'cargo_total_old',
 'draft',
 'fo_per_24_hrs',
 'sfoc',
 'cy_oil_gm_hr',
 'scoc',
 'voyage_name',
 'total_fo',
 'total_co_2',
 'eeoi',
 'voy_condition',
 'same_date',
 'time_since_last_report',
 'wind_direction_360',
 'ref_power',
 'ref_fuel',
 'fuel_loss',
 'draft_pow',
 'draft_sp_pow',
 'fo_nor',
 'fo_model',
 'sfoc_model',
 'sfoc_deviation',
 'ref_power_corrected',
 'ref_fo_corrected',
 'propulsive_eff',
 'speed_performance',
 'pi',
 'me_con',
 'ae_con',
 'bl_con',
 't_con',
 'hs',
 'ls',
 'mdo',
 'mgo',
 'mgo_ls',
 't_co_2',
 'ae_t_steaming',
 'ae_power',
 'trim',
 'distance_covered',
 'updated_date',
 'hyd_slip_sog',
 'hyd_slip_stw',
 'fuel_rsdl_hs',
 'fuel_rsdl_vls',
 'fuel_rsdl_uls',
 'fuel_dstlt_vls',
 'fuel_dstlt_uls',
 'fuel_tnktnr_dstlt_vls',
 'rsdl_hs',
 'rsdl_vls',
 'rsdl_uls',
 'dstlt_vls',
 'dstlt_uls',
 'tnktnr_dstlt_vls',
 'fuel_m_e_lng',
 'fuel_aux_lng',
 'fuel_boiler_lng',
 'rob_rsdl_lng',
 'sulphur_content_pc_main',
 'quantity_main',
 'port_delivery_main',
 'product_quality_main',
 'delivery_main',
 'bdn_number_main',
 'fo_nor_sog',
 'fo_nor_stw',
 'created_at',
 'updated_at',
 'created_by_id',
 'updated_by_id',
 'rob_lng',
 'sludge_rob',
 'garbage_cat_a_plastic_removed',
 'garbage_cat_b_organic_removed',
 'garbage_cat_c_domestic_removed',
 'garbage_cat_e_ashes_removed',
 'rob_garbage_cat_a_plastic',
 'rob_garbage_cat_b_organic',
 'rob_garbage_cat_c_domestic',
 'rob_garbage_cat_e_ashes',
 'qty_sludge_disposed',
 'steaming_time_m_e_lng',
 'reefer_power_consumption',
 'wind_direction_side',
 'sea_direction_side',
 'tot_sludge_removed',
 'REMARKS',
 'bdn_number']

In [58]:
FINALNOON = FINALNOON[['id',
 'imo',
 'vessel',
 'id_vessel',
 'gid',
 'voyage',
 'corrected_date',
 'report_date_time',
 'report_date_time_offset',
 'report_type',
 'status',
 'lat',
 'long',
 'latitude',
 'longitude',
 'me_foc',
 'cargo_total',
 'STEAMING_TIME',
 'Total_M_E_Hours_Fuel_Only',
 'miles_by_gps',
 'oil_cyl',
 'rpm',
 'slip',
 'wind_direction',
 'wind_speed',
 'draft_aft',
 'draft_fwd',
 'displacement',
 'course_at_sea',
 'wave_height',
 'sea_direction',
 'cargo_total_teu',
 'ambient_temp',
 'sw_temp',
 'miles_by_speed_log',
 'eta_port_code',
 'eta_date_time',
 'eta_date_time_offset',
 'eta_port',
 'time_change',
 'time_sea',
 'temp_min',
 'temp_max',
 'requested_speed',
 'rem_dist_to_pilot',
 'rem_time_to_pilot',
 'total_unplnd_stpge_tech',
 'total_unplnd_stpge_ope_wx',
 'reefers_positive_plugged',
 'reefers_negative_plugged',
 'me_total_revs_counter',
 'port_code',
 'port',
 'aux_blowers_on',
 'hold_ventilation_on',
 'since_date_time',
 'since_date_time_offset',
 'time_hrs_anchor',
 'time_hrs_drift',
 'reason',
 'type_of_delay',
 'etb_date_time',
 'etb_date_time_offset',
 'pilot_date_time',
 'pilot_date_time_offset',
 'time_manoeuvring',
 'tug_arr',
 'tug_shift',
 'etd_date_time',
 'etd_date_time_offset',
 'shift_berth_hours',
 'cargo_load',
 'cargo_disch',
 'teu_full',
 'teu_empty',
 'bilge_removed',
 'garbage_removed',
 'garbage_remvl_reqstd',
 'garbage_remvl_cmplsry',
 'fw_supply',
 'cy_crew_signed_on',
 'cy_crew_signed_off',
 'cy_doctors_visit',
 'cy_mail_received_ref_no',
 'cy_lub_oil_sample_landed',
 'cy_checkd_for_stowaways',
 'cy_stowaways_on_board',
 'cy_dep_gm_mtr',
 'cy_requisitions_received',
 'distance_to_next_pilot',
 'tug_sailing_transit',
 'steaming_time_me_rsdl_vls',
 'steaming_time_me_rsdl_hs',
 'steaming_time_me_rsdl_uls',
 'steaming_time_me_dstlt_vls',
 'steaming_time_me_dstlt_uls',
 'steaming_time_me_tnktnr_dstlt_vls',
 'steaming_time_me_mdo',
 'steaming_time_aux_1',
 'steaming_time_aux_2',
 'steaming_time_aux_3',
 'steaming_time_aux_4',
 'steaming_time_aux_5',
 'steaming_time_sh_gen',
 'steaming_time_tg',
 'fuel_me_rsdl_vls',
 'fuel_me_rsdl_hs',
 'fuel_me_rsdl_uls',
 'fuel_me_dstlt_vls',
 'fuel_me_dstlt_uls',
 'fuel_me_mdo',
 'fuel_me_tnktnr_dstlt_vls',
 'fuel_aux_rsdl_vls',
 'fuel_aux_rsdl_hs',
 'fuel_aux_rsdl_uls',
 'fuel_aux_dstlt_vls',
 'fuel_aux_dstlt_uls',
 'fuel_aux_tnktnr_dstlt_vls',
 'fuel_aux_mdo',
 'fuel_boiler_rsdl_vls',
 'fuel_boiler_rsdl_hs',
 'fuel_boiler_rsdl_uls',
 'fuel_boiler_dstlt_vls',
 'fuel_boiler_dstlt_uls',
 'fuel_boiler_tnktnr_dstlt_vls',
 'fuel_boiler_mdo',
 'POWER_KW',
 'steaming_load_kw_aux_1',
 'steaming_load_kw_aux_2',
 'steaming_load_kw_aux_3',
 'steaming_load_kw_aux_4',
 'steaming_load_kw_aux_5',
 'steaming_load_kw_sh_gen',
 'steaming_load_kw_tg',
 'deck_last_change_user',
 'engine_last_change_user',
 'deck_part_is_complete',
 'engine_part_is_complete',
 'scavenge_pressure',
 'seca_entry_time',
 'seca_entry_lat',
 'seca_entry_long',
 'seca_exit_time',
 'seca_exit_lat',
 'seca_exit_long',
 'rob_fresh_water',
 'manvrng_miles_by_gps',
 'manvrng_miles_by_speed_log',
 'tanktainer_transfd_quantity',
 'pilot_taken',
 'date_time_start_transit',
 'date_time_start_transit_offset',
 'date_time_end_transit',
 'date_time_end_transit_offset',
 'ballast',
 'tanktainer_number',
 'steaming_kwhr_total',
 'cy_others',
 'rob_fo_sludge',
 'rob_lo_sludge',
 'rob_bilge',
 'sludge_removed_fo',
 'sludge_removed_lo',
 'sea_state',
 'cy_lub_added_to_system_me_cc',
 'cy_lub_added_to_system_ae_cc',
 'cy_lub_added_to_thrusters',
 'cy_me_lo_purifier_in_use',
 'cy_ballast',
 'cy_bending_moment',
 'cy_shearing_force',
 'cy_tortion_moment',
 'cy_supdt_auditor_signed_on',
 'cy_supdt_auditor_signed_off',
 'cy_cash_received',
 'cy_lub_oil_received_me_cyl',
 'cy_lub_oil_received_me_cc',
 'cy_lub_oil_received_ae_cc',
 'cy_me_under_piston_temp',
 'cy_mail_received',
 'wind_direction_port_stbd',
 'sea_direction_port_stbd',
 'time_pilot_onboard',
 'grades_rob',
 'so_2_co_2_ratio',
 'bunker_order',
 'remarks',
 'bdn_number',
 'fuel_type',
 'carbon_factor',
 'sulphur_content_pc',
 'quantity',
 'port_delivery',
 'product_quality',
 'tanktainer_number_1',
 'supplier',
 'volume_lt',
 'density',
 'viscosity',
 'rob_dstlt_uls',
 'rob_dstlt_vls',
 'rob_rsdl_mdo',
 'rob_tnktnr_dstlt_vls',
 'rob_rsdl_vls',
 'rob_rsdl_hs',
 'rob_rsdl_uls',
 'has_cargo',
 'steaming_time_me_hs',
 'steaming_time_me_ls',
 'steaming_time_me_mgo',
 'steaming_time_me_mgo_ls',
 'fuel_me_hs',
 'fuel_me_ls',
 'fuel_me_mgo',
 'fuel_me_mgo_ls',
 'fuel_aux_hs',
 'fuel_aux_ls',
 'fuel_aux_mgo',
 'fuel_aux_mgo_ls',
 'fuel_boiler_hs',
 'fuel_boiler_ls',
 'fuel_boiler_mgo',
 'fuel_boiler_mgo_ls',
 'rob_fuel_hs_fo',
 'rob_fuel_ls_fo',
 'rob_fuel_mdo',
 'rob_fuel_mgo',
 'rob_fuel_mgo_ls',
 'rob_fuel_tanktainer_mgo',
 'eca_miles',
 'eca_time',
 'egcs_dry_waste_removed',
 'egcs_running_time',
 'egcs_wet_slurry_removed',
 'egcs_open_loop_running_time',
 'egcs_closed_loop_running_time',
 'voyage_order',
 'voyage_code',
 'eca',
 'eu',
 'sea_time',
 'eta_country_code',
 'port_country_code',
 'check_eta_code',
 'check_port_code',
 'status_temp_eu',
 'fuel_hs',
 'fuel_ls',
 'fuel_mdo',
 'fuel_mgo',
 'fuel_mgo_ls',
 'cargo_transport_work',
 'teu_transport_work',
 'eeoi_voyage_no',
 'cargo_total_old',
 'draft',
 'fo_per_24_hrs',
 'sfoc',
 'cy_oil_gm_hr',
 'scoc',
 'voyage_name',
 'total_fo',
 'total_co_2',
 'eeoi',
 'voy_condition',
 'same_date',
 'time_since_last_report',
 'wind_direction_360',
 'true_wind_speed',
 'true_wind_dir',
 'ref_power',
 'ref_fuel',
 'fuel_loss',
 'relative_wind_speed',
 'relative_wind_direction',
 'caa',
 'rw',
 'corrected_power',
 'draft_pow',
 'draft_sp_pow',
 'fo_nor',
 'fo_model',
 'sfoc_model',
 'sfoc_deviation',
 'ref_power_corrected',
 'ref_fo_corrected',
 'propulsive_eff',
 'speed_performance',
 'ref_speed',
 'pi',
 'me_con',
 'ae_con',
 'bl_con',
 't_con',
 'hs',
 'ls',
 'mdo',
 'mgo',
 'mgo_ls',
 't_co_2',
 'ae_t_steaming',
 'ae_power',
 'trim',
 'distance_covered',
 'updated_date',
 'hyd_slip_sog',
 'hyd_slip_stw',
 'fuel_rsdl_hs',
 'fuel_rsdl_vls',
 'fuel_rsdl_uls',
 'fuel_dstlt_vls',
 'fuel_dstlt_uls',
 'fuel_tnktnr_dstlt_vls',
 'rsdl_hs',
 'rsdl_vls',
 'rsdl_uls',
 'dstlt_vls',
 'dstlt_uls',
 'tnktnr_dstlt_vls',
 'created_at',
 'updated_at',
 'created_by_id',
 'updated_by_id',
 'SPEED_BY_LOG',
 'SPEED_BY_GPS',
 'fuel_m_e_lng',
 'fuel_aux_lng',
 'fuel_boiler_lng',
 'rob_rsdl_lng',
 'sulphur_content_pc_main',
 'quantity_main',
 'port_delivery_main',
 'product_quality_main',
 'delivery_main',
 'bdn_number_main',
 'delivery','REMARKS']]
FINALNOON

,id,imo,vessel,id_vessel,gid,voyage,corrected_date,report_date_time,report_date_time_offset,report_type,...,fuel_boiler_lng,rob_rsdl_lng,sulphur_content_pc_main,quantity_main,port_delivery_main,product_quality_main,delivery_main,bdn_number_main,delivery,REMARKS
88376,5733388,8918966,MSC MANDY,MAND,5189579,NaN,2024-01-01 00:00:00,2024-01-01 00:00:00,UTC+00:00,Powerpack,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
100991,5759240,9618276,MSC AGRIGENTO,AGRI,5190842,NaN,2024-01-01 00:00:00,2024-01-01 00:00:00,UTC+00:00,Bunker,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
99146,5733092,8913447,MSC ATLANTIC,ATLA,5194800,NaN,2024-01-01 00:00:00,2024-01-01 00:00:00,UTC+00:00,Powerpack,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
94762,5741971,9229300,MSC CATHERINE VI,CATR,5188869,NaN,2023-12-31 18:00:00,2024-01-01 00:00:00,UTC-06:00,Sailing,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
52550,5761282,9720500,MSC SASHA,SASH,5189797,NaN,2024-01-01 00:00:00,2024-01-01 00:00:00,UTC+00:00,Bunker,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27559,6310734,9239903,MSC PAMIRA III,PAMI,5529610,NaN,2024-06-30 00:00:00,2024-06-30 00:00:00,UTC+00:00,Powerpack,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
79239,6299314,8201636,MSC MALIN,MALI,5529409,NaN,2024-06-30 00:00:00,2024-06-30 00:00:00,UTC+00:00,Powerpack,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
45027,6300457,8918966,MSC MANDY,MAND,5529375,NaN,2024-06-30 00:00:00,2024-06-30 00:00:00,UTC+00:00,Powerpack,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
45355,6301752,9084607,MSC NITA,NITA,5529704,NaN,2024-06-30 00:00:00,2024-06-30 00:00:00,UTC+00:00,Powerpack,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
60049,6300456,8918966,MSC MANDY,MAND,5529379,NaN,2024-06-30 00:00:00,2024-06-30 00:00:00,UTC+00:00,Powerpack,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."

In [59]:
a=FINALNOON.to_csv('FINALNOON.csv')

In [46]:
FINALNOON['report_type'] = FINALNOON['report_type'].replace('Refueling', 'REFL')

In [47]:
refl = FINALNOON[FINALNOON['report_type'] == 'REFL']
refl

,id,imo,vessel,id_vessel,gid,voyage,corrected_date,report_date_time,report_date_time_offset,report_type,...,fuel_boiler_lng,rob_rsdl_lng,sulphur_content_pc_main,quantity_main,port_delivery_main,product_quality_main,delivery_main,bdn_number_main,delivery,REMARKS
520,5732600,8521402,MSC ANNAMARIA,ANMA,5189583,NaN,2023-12-31 21:25:00,2024-01-01 00:25:00,UTC-03:00,REFL,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,None
79819,5732601,8521402,MSC ANNAMARIA,ANMA,5189587,NaN,2023-12-31 21:35:00,2024-01-01 00:35:00,UTC-03:00,REFL,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,None
82883,5760028,9702089,MSC VITA,VITA,5189807,NaN,2024-01-01 11:00:00,2024-01-01 10:00:00,UTC+01:00,REFL,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,None
112233,5753589,9330226,MSC ABIGAIL F,ABIG,5190958,NaN,2024-01-01 12:14:00,2024-01-01 12:14:00,UTC+00:00,REFL,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,None
111745,5748708,9292175,MSC SHANELLE V,SHNL,5190148,NaN,2024-01-01 13:15:00,2024-01-01 13:15:00,UTC+00:00,REFL,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55649,6311513,9244881,MSC ARUSHI R,ARUS,5532057,NaN,2024-06-30 15:39:00,2024-06-30 13:39:00,UTC+02:00,REFL,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,None
26328,6304722,9162643,MSC LEA,LEA,5530815,NaN,2024-06-30 17:30:00,2024-06-30 14:30:00,UTC+03:00,REFL,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,None
26085,6299544,8512906,MSC ADELE,ADEL,5533194,NaN,2024-06-30 22:06:00,2024-06-30 16:36:00,UTC+05:30,REFL,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,None
78786,6321378,9360271,MSC CAPE III,CAPE,5531232,NaN,2024-06-30 19:48:00,2024-06-30 19:48:00,UTC+00:00,REFL,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,None
28226,6311514,9244881,MSC ARUSHI R,ARUS,5532055,NaN,2024-06-30 22:30:00,2024-06-30 20:30:00,UTC+02:00,REFL,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,None

In [48]:
refl.to_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\OUTPUT\MSCSMCY MISSING BDNs refl.xlsx",index = False)

In [49]:
refl_remarks = refl[refl['REMARKS'].notnull()]
refl_remarks

,id,imo,vessel,id_vessel,gid,voyage,corrected_date,report_date_time,report_date_time_offset,report_type,...,fuel_boiler_lng,rob_rsdl_lng,sulphur_content_pc_main,quantity_main,port_delivery_main,product_quality_main,delivery_main,bdn_number_main,delivery,REMARKS
95123,5740180,9210086,MSC CAPUCINE R,CAPU,5195354,NaN,2024-01-03 20:55:00,2024-01-04 01:55:00,UTC-05:00,REFL,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BDN is not given
2202,5754557,9344708,MSC GENERAL IV,GENL,5194814,NaN,2024-01-04 10:58:00,2024-01-04 02:58:00,UTC+08:00,REFL,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,Sulphur is not given
111403,5764561,9932050,MSC MONICA CRISTINA,MMON,5215649,NaN,2024-01-04 07:30:00,2024-01-04 06:30:00,UTC+01:00,REFL,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,Sulphur is not given
85662,5734485,9060649,MSC MONICA III,MONI,5196751,NaN,2024-01-04 17:25:00,2024-01-04 13:25:00,UTC+04:00,REFL,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BDN is not given
95423,5734429,9057173,MSC AGATA II,AGAT,5196743,NaN,2024-01-05 09:54:00,2024-01-05 09:54:00,UTC+00:00,REFL,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BDN is not given
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77306,6311819,9251688,MSC VANESSA,VANE,5522637,NaN,2024-06-24 13:45:00,2024-06-24 17:45:00,UTC-04:00,REFL,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BDN is not given
55753,6311821,9251688,MSC VANESSA,VANE,5522641,NaN,2024-06-25 22:05:00,2024-06-26 02:05:00,UTC-04:00,REFL,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,BDN is not given
28848,6306734,9210098,MSC SINES R,SINE,5524150,NaN,2024-06-26 19:30:00,2024-06-26 17:30:00,UTC+02:00,REFL,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BDN is not given
26310,6304154,9154191,MSC POSITANO,POSI,5527862,NaN,2024-06-28 23:54:00,2024-06-28 18:54:00,UTC+05:00,REFL,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BDN is not given
58050,6321080,9354363,WEC MONDRIAAN,WECM,5531076,NaN,2024-06-30 09:40:00,2024-06-30 09:40:00,UTC+00:00,REFL,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BDN is not given

In [50]:
refl_remarks.to_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\OUTPUT FOR CLIENT\MSCSMCY MISSING BDNs.xlsx",index = False)

# CHARTER

In [51]:
charter

,id,gid,vessel_name,imo,voy,corrected_date,report_date_time,report_date_time_offset,report_type,status,...,engine_last_change_user,created_date,created_at,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng
0,4504377,d3d9b992-4c1c-45f5-8339-b446dbae8c22,MSC GRACE F,8918057,JJ403A,2024-02-02,2024-2-1 14:30,UTC +03:00,BRTH,DRIFTING,...,C_E,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
1,4490015,63f76f9b-b1e7-4954-bb5d-a16f3ffa577c,MSC GRACE F,8918057,JJ348R,2024-01-01,2024-1-1 12:00,UTC +03:00,DLY A,DRIFTING,...,C_E,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
2,4504380,d065e7c5-2e6f-432a-abb6-f26a308c54f7,MSC GRACE F,8918057,JJ403A,2024-02-04,2024-2-4 12:00,UTC +03:00,PORT,IN PORT,...,C_E,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
3,4490017,efb7c60c-f3a7-41b0-a85a-b73752c5a5b7,MSC GRACE F,8918057,JJ348R,2024-01-03,2024-1-3 12:00,UTC +03:00,DLY A,DRIFTING,...,C_E,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
4,4490019,553e023c-de8d-47ee-964f-2788a0fa5c6b,MSC GRACE F,8918057,JJ348R,2024-01-05,2024-1-5 12:00,UTC +03:00,DLY A,DRIFTING,...,C_E,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109100,4407163,c957c3c7-e591-4569-a6e9-6bc00a77709f,KOTKA,90855340,IU4124A,2024-06-21,2024-6-21 6:24,UTC +05:30,BRTH,DRIFTING,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
109101,4407164,903cf1b4-1ddc-4a1f-a0e5-f918da52f5bf,KOTKA,90855340,IU4124A,2024-06-21,2024-6-21 12:00,UTC +05:30,PORT,IN PORT,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
109102,4407165,84d673eb-1403-4a05-8662-49bec9e95ea6,KOTKA,90855340,IU4124A,2024-06-22,2024-6-21 22:06,UTC +05:30,SAIL,IN PORT,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
109103,4407166,a73219c5-15e0-4d6c-8917-305af026b032,KOTKA,90855340,IU4124A,2024-06-22,2024-6-22 0:06,UTC +05:30,COSP,DRIFTING,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
109104,4407167,c5efabec-2581-4da6-9a74-81478991621f,KOTKA,90855340,IU4124A,2024-06-22,2024-6-22 12:00,UTC +05:30,NOON,AT SEA,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0

In [52]:
esi_charter

         IMO    Fleet             Vessel Scrubber
0    9297589  CHARTER              ALANA       No
2    9342695  CHARTER      AS California       No
3    9314947  CHARTER        AS CAMELLIA      Yes
5    9247766  CHARTER       ATHENS GLORY      Yes
7    9727625  CHARTER        CAPE SOUNIO       No
8    9706205  CHARTER       CAPE TAINARO       No
9    9293791  CHARTER     CONTI CHIVALRY       No
10   9308613  CHARTER       Contship Fun       No
11   9373917  CHARTER       CONTSHIP OAK       No
12   9357810  CHARTER           EF Emira       No
13   9153862  CHARTER        EPAMINONDAS       No
14   9301469  CHARTER             Etoile       No
17   9256482  CHARTER         GSL NINGBO       No
18   9357793  CHARTER        Hansa Lanka       No
19   9535163  CHARTER    Henrika Schulte       No
20   9535187  CHARTER    Hermann Schulte       No
21   9535204  CHARTER     Hubert Schulte       No
23   9225770  CHARTER              Julie       No
24   9085558  CHARTER         Karlskrona       No
25   9085546  CHARTER             KLEVEN       No
26   9085534  CHARTER              KOTKA       No
27   9085522  CHARTER               KURE       No
28   9307243  CHARTER           Le Havre      Yes
29   9236535  CHARTER         Marianetta       No
30   9162227  CHARTER         MARIANNA I       No
31   9148025  CHARTER          MED AYDIN       No
32   9256365  CHARTER          MED CESME       No
33   9106479  CHARTER          MED CORLU       No
34   9106493  CHARTER        MED Denizli       No
35   9225794  CHARTER         MED SAMSUN       No
36   9141780  CHARTER        MED TRABZON       No
44   9619464  CHARTER         MSC AGADIR      Yes
71   9247730  CHARTER         MSC APOLLO      Yes
72   9262704  CHARTER       MSC AQUARIUS      Yes
78   9618317  CHARTER          MSC ATHOS      Yes
82   9605255  CHARTER           MSC AZOV      Yes
85   9480186  CHARTER      MSC BARCELONA       No
86   9461441  CHARTER           MSC BARI      Yes
94   9247742  CHARTER      MSC BOSPHORUS      Yes
100  9480203  CHARTER          MSC CADIZ       No
126  9480215  CHARTER         MSC CORUNA       No
129  9247754  CHARTER    MSC DARDANELLES      Yes
187  9225641  CHARTER          MSC ILONA       No
198  9135638  CHARTER         MED MERSIN       No
225  9461403  CHARTER      MSC LA SPEZIA      Yes
237  9461427  CHARTER        MSC LIVORNO      Yes
248  9480198  CHARTER         MSC MADRID       No
284  9349796  CHARTER       MSC MONTEREY       No
325  9256470  CHARTER        MSC QINGDAO      Yes
328  9484431  CHARTER        MSC RAVENNA      Yes
337  9304447  CHARTER           MSC ROMA      Yes
355  9460356  CHARTER         MSC SAVONA      Yes
387  9475258  CHARTER        MSC TARANTO      Yes
391  9285471  CHARTER        MSC TIANJIN       No
408  9480227  CHARTER           MSC VIGO       No
423  9813840  CHARTER  Spirit of Chennai      Yes
424  9813838  CHARTER  Spirit of Kolkata      Yes

In [53]:
esi_charter.shape

(57, 4)

In [54]:
esi_charter_lst = esi_charter['IMO'].to_list()
esi_charter_lst

[9297589,
 9342695,
 9314947,
 9247766,
 9727625,
 9706205,
 9293791,
 9308613,
 9373917,
 9357810,
 9153862,
 9301469,
 9256482,
 9357793,
 9535163,
 9535187,
 9535204,
 9225770,
 9085558,
 9085546,
 9085534,
 9085522,
 9307243,
 9236535,
 9162227,
 9148025,
 9256365,
 9106479,
 9106493,
 9225794,
 9141780,
 9619464,
 9247730,
 9262704,
 9618317,
 9605255,
 9480186,
 9461441,
 9247742,
 9480203,
 9480215,
 9247754,
 9225641,
 9135638,
 9461403,
 9461427,
 9480198,
 9349796,
 9256470,
 9484431,
 9304447,
 9460356,
 9475258,
 9285471,
 9480227,
 9813840,
 9813838]

In [55]:
charter_final = charter[charter['imo'].isin(esi_charter_lst)].reset_index(drop = True) #filter msc own vessels from noon data using client send vessel list
charter_final

,id,gid,vessel_name,imo,voy,corrected_date,report_date_time,report_date_time_offset,report_type,status,...,engine_last_change_user,created_date,created_at,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng
0,4390940,04e97cdd-425a-48d8-a82d-96ab08f2670f,MARIANNA I,9162227,KQ416R,2024-05-02,2024-5-1 12:54,UTC +10:00,BRTH,DRIFTING,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
1,4390941,fff9cd3e-6e1c-4f4a-8bea-dd0639364122,MARIANNA I,9162227,KQ416R,2024-05-02,2024-5-2 9:56,UTC +10:00,REFL,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
2,4390942,d665ed27-97bb-4729-9a82-5d9b3c8320bc,MARIANNA I,9162227,KQ416R,2024-05-02,2024-5-2 9:56,UTC +10:00,REFL,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
3,4390943,9ed58560-2390-4bc2-8760-19d54f2c0205,MARIANNA I,9162227,KQ416R,2024-05-02,2024-5-2 12:00,UTC +10:00,PORT,IN PORT,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
4,4390944,8be23b32-c833-4bbc-95f0-7e42ebfbc185,MARIANNA I,9162227,KQ416R,2024-05-03,2024-5-2 14:12,UTC +10:00,SAIL,IN PORT,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15754,4535513,ba747b07-1910-4457-9da3-8c90318a4952,MSC TIANJIN,9285471,XA417A,2024-04-30,2024-4-29 23:42,UTC +02:00,SAIL,IN PORT,...,LIVIU NITU,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
15755,4535514,21eaf1bb-040a-4e4b-a71f-0010be0e302c,MSC TIANJIN,9285471,XA417A,2024-04-30,2024-4-30 1:00,UTC +02:00,COSP,DRIFTING,...,LIVIU NITU,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
15756,4535515,261455b7-d387-43b2-9d5c-07d4b97e38a6,MSC TIANJIN,9285471,XA417A,2024-04-30,2024-4-30 12:00,UTC +02:00,NOON,AT SEA,...,LIVIU NITU,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
15757,4535516,59114342-9b8d-468f-8e1f-7448fd5a666f,MSC TIANJIN,9285471,XA417A,2024-05-01,2024-4-30 20:00,UTC +02:00,EOSP,AT SEA,...,LIVIU NITU,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
15758,4535517,7df1e1cf-1c5d-4f72-82bf-a6681fe5ac54,MSC TIANJIN,9285471,XA417A,2024-05-01,2024-4-30 20:30,UTC +02:00,DLY A,DRIFTING,...,LIVIU NITU,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0

In [56]:
#checking all vessels are there in noon data
#unique vessels in client send data is
esi_charter['IMO'].nunique()

57

In [57]:
#unique vessels in noon data msc own vessels
charter_final['imo'].nunique()

53

In [58]:
esi_charter_lst = esi_charter['IMO'].to_list()
esi_charter_lst

[9297589,
 9342695,
 9314947,
 9247766,
 9727625,
 9706205,
 9293791,
 9308613,
 9373917,
 9357810,
 9153862,
 9301469,
 9256482,
 9357793,
 9535163,
 9535187,
 9535204,
 9225770,
 9085558,
 9085546,
 9085534,
 9085522,
 9307243,
 9236535,
 9162227,
 9148025,
 9256365,
 9106479,
 9106493,
 9225794,
 9141780,
 9619464,
 9247730,
 9262704,
 9618317,
 9605255,
 9480186,
 9461441,
 9247742,
 9480203,
 9480215,
 9247754,
 9225641,
 9135638,
 9461403,
 9461427,
 9480198,
 9349796,
 9256470,
 9484431,
 9304447,
 9460356,
 9475258,
 9285471,
 9480227,
 9813840,
 9813838]

In [59]:
charter_lst = charter_final['imo'].unique().tolist()
charter_lst

[9162227,
 9085522,
 9085534,
 9085546,
 9106479,
 9106493,
 9141780,
 9247766,
 9256365,
 9256470,
 9256482,
 9262704,
 9285471,
 9293791,
 9297589,
 9349796,
 9357793,
 9357810,
 9373917,
 9148025,
 9460356,
 9461403,
 9461427,
 9461441,
 9475258,
 9480186,
 9480198,
 9480203,
 9480215,
 9480227,
 9484431,
 9535163,
 9535187,
 9153862,
 9225641,
 9535204,
 9605255,
 9618317,
 9619464,
 9225770,
 9225794,
 9236535,
 9247742,
 9247754,
 9301469,
 9304447,
 9307243,
 9308613,
 9342695,
 9706205,
 9727625,
 9813838,
 9813840]

In [60]:
res_lst = []
for element in esi_charter_lst:
    if element not in charter_lst:
        res_lst.append(element)
res_lst

[9314947, 9085558, 9247730, 9135638]

In [61]:
# check with client file. if the NAME of the vessels are shaded, then that is a new vessel - no data for that vessel. But if in case thats not shaded, go and check Charter data

# filling the Port_delivery column

In [62]:
charter_final.columns.to_list()

['id',
 'gid',
 'vessel_name',
 'imo',
 'voy',
 'corrected_date',
 'report_date_time',
 'report_date_time_offset',
 'report_type',
 'status',
 'latitude',
 'longitude',
 'm_e_foc',
 'cargo_total',
 'has_cargo',
 'steaming_time',
 'total_m_e_hours_fuel_only',
 'miles_by_gps',
 'oil_cyl',
 'speed_by_log',
 'speed_by_gps',
 'rpm',
 'slip',
 'wind_direction',
 'wind_speed',
 'draft_aft',
 'draft_fwd',
 'displacement',
 'course_at_sea',
 'wave_height',
 'sea_direction',
 'cargo_total_teu',
 'ambient_temp',
 'sw_temp',
 'miles_by_speed_log',
 'eta_port_code',
 'eta_date_time',
 'eta_date_time_offset',
 'eta_port',
 'time_change',
 'time_sea',
 'temp_min',
 'temp_max',
 'requested_speed',
 'rem_dist_to_pilot',
 'rem_time_to_pilot',
 'total_unplnd_stpge_tech',
 'total_unplnd_stpge_ope_wx',
 'reefers_positive_plugged',
 'reefers_negative_plugged',
 'me_total_revs_counter',
 'port_code',
 'port',
 'aux_blowers_on',
 'hold_ventilation_on',
 'since_date_time',
 'since_date_time_offset',
 'time_hrs_anchor',
 'time_hrs_drift',
 'reason',
 'type_of_delay',
 'etb_date_time',
 'etb_date_time_offset',
 'pilot_date_time',
 'pilot_date_time_offset',
 'time_manoeuvring',
 'tug_arr',
 'tug_shift',
 'etd_date_time',
 'etd_date_time_offset',
 'shift_berth_hours',
 'cargo_disch',
 'teu_full',
 'teu_empty',
 'bilge_removed',
 'garbage_removed',
 'garbage_remvl_reqstd',
 'garbage_remvl_cmplsry',
 'fw_supply',
 'cy_crew_signed_on',
 'cy_crew_signed_off',
 'cy_doctors_visit',
 'cy_mail_received_ref_no',
 'cy_lub_oil_sample_landed',
 'cy_checkd_for_stowaways',
 'cy_stowaways_on_board',
 'cy_dep_gm_mtr',
 'cy_requisitions_received',
 'distance_to_next_pilot',
 'tug_sailing_transit',
 'steaming_time_m_e_rsdl_vls',
 'steaming_time_m_e_rsdl_hs',
 'steaming_time_m_e_rsdl_uls',
 'steaming_time_m_e_dstlt_vls',
 'steaming_time_m_e_dstlt_uls',
 'steaming_time_m_e_tnktnr_dstlt_vls',
 'steaming_time_m_e_hs',
 'steaming_time_m_e_ls',
 'steaming_time_m_e_mdo',
 'steaming_time_m_e_mgo',
 'steaming_time_m_e_mgo_ls',
 'steaming_time_aux_1',
 'steaming_time_aux_2',
 'steaming_time_aux_3',
 'steaming_time_aux_4',
 'steaming_time_aux_5',
 'steaming_time_sh_gen',
 'steaming_time_tg',
 'power_kw',
 'steaming_load_kw_aux_1',
 'steaming_load_kw_aux_2',
 'steaming_load_kw_aux_3',
 'steaming_load_kw_aux_4',
 'steaming_load_kw_aux_5',
 'steaming_load_kw_sh_gen',
 'steaming_load_kw_tg',
 'fuel_m_e_rsdl_vls',
 'fuel_m_e_rsdl_hs',
 'fuel_m_e_rsdl_uls',
 'fuel_m_e_dstlt_vls',
 'fuel_m_e_dstlt_uls',
 'fuel_m_e_tnktnr_dstlt_vls',
 'fuel_m_e_hs',
 'fuel_m_e_ls',
 'fuel_m_e_mdo',
 'fuel_m_e_mgo',
 'fuel_m_e_mgo_ls',
 'fuel_aux_rsdl_vls',
 'fuel_aux_rsdl_hs',
 'fuel_aux_rsdl_uls',
 'fuel_aux_dstlt_vls',
 'fuel_aux_dstlt_uls',
 'fuel_aux_tnktnr_dstlt_vls',
 'fuel_aux_hs',
 'fuel_aux_ls',
 'fuel_aux_mdo',
 'fuel_aux_mgo',
 'fuel_aux_mgo_ls',
 'fuel_boiler_rsdl_vls',
 'fuel_boiler_rsdl_hs',
 'fuel_boiler_rsdl_uls',
 'fuel_boiler_dstlt_vls',
 'fuel_boiler_dstlt_uls',
 'fuel_boiler_tnktnr_dstlt_vls',
 'fuel_boiler_hs',
 'fuel_boiler_ls',
 'fuel_boiler_mdo',
 'fuel_boiler_mgo',
 'fuel_boiler_mgo_ls',
 'deck_last_change_user',
 'deck_part_is_complete',
 'engine_part_is_complete',
 'scavenge_pressure',
 'seca_entry_time',
 'seca_entry_lat',
 'seca_entry_long',
 'rob_fresh_water',
 'manvrng_miles_by_gps',
 'manvrng_miles_by_speed_log',
 'tanktainer_transfd_quantity',
 'pilot_taken',
 'date_time_start_transit',
 'date_time_start_transit_offset',
 'date_time_end_transit',
 'date_time_end_transit_offset',
 'ballast',
 'tanktainer_number',
 'steaming_kwhr_total',
 'cy_others',
 'rob_fo_sludge',
 'rob_lo_sludge',
 'rob_bilge',
 'sludge_removed_fo',
 'sludge_removed_lo',
 'sea_state',
 'cy_lub_added_to_system_mecc',
 'cy_lub_added_to_system_aecc',
 'cy_lub_added_to_thrusters',
 'cy_me_lo_purifier_in_use',
 'cy_ballast',
 'cy_bending_moment',
 'cy_shearing_force',
 'cy_tortion_moment',
 'cy_supdt_auditor_signed_on',
 'cy_supdt_auditor_signed_off',
 'cy_cash_received',
 'cy_lub_oil_received_mecyl',
 'cy_lub_oil_received_mecc',
 'cy_lub_oil_received_aecc',
 'cy_m_e_under_piston_temp',
 'cy_mail_received',
 'wind_direction_port_stbd',
 'sea_direction_port_stbd',
 'time_pilot_onboard',
 'grades_rob',
 'bunker_order',
 'remarks',
 'fuel_type',
 'carbon_factor',
 'so_2_co_2_ratio',
 'sulphur_content_pc',
 'quantity',
 'port_delivery',
 'product_quality',
 'tanktainer_number_1',
 'supplier',
 'delivery',
 'vol_lt',
 'den',
 'vis',
 'fuel_hs',
 'fuel_ls',
 'fuel_mdo',
 'fuel_mgo',
 'fuel_mgo_ls',
 'bdn',
 'rob_dstlt_uls',
 'rob_dstlt_vls',
 'rob_rsdl_mdo',
 'rob_tnktnr_dstlt_vls',
 'rob_rsdl_vls',
 'rob_rsdl_hs',
 'rob_rsdl_uls',
 'rob_fuel_hsfo',
 'rob_fuel_lsfo',
 'rob_fuel_mdo',
 'rob_fuel_mgo',
 'rob_fuel_mgo_ls',
 'rob_fuel_tanktainer_mgo',
 'eca_miles',
 'eca_time',
 'egcs_dry_waste_removed',
 'egcs_running_time',
 'egcs_wet_slurry_removed',
 'egcs_open_loop_running_time',
 'egcs_closed_loop_running_time',
 'updated_date',
 'fuel_rsdl_hs',
 'fuel_rsdl_vls',
 'fuel_rsdl_uls',
 'fuel_dstlt_vls',
 'fuel_dstlt_uls',
 'fuel_tnktnr_dstlt_vls',
 'cargo_load',
 'seca_exit_time',
 'seca_exit_lat',
 'seca_exit_long',
 'engine_last_change_user',
 'created_date',
 'created_at',
 'updated_at',
 'created_by_id',
 'updated_by_id',
 'fuel_m_e_lng',
 'fuel_aux_lng',
 'fuel_boiler_lng',
 'rob_boiler_lng']

In [63]:
charter_final['port_delivery'] = charter_final['port_delivery'].fillna(charter_final['port_code'])
charter_final

,id,gid,vessel_name,imo,voy,corrected_date,report_date_time,report_date_time_offset,report_type,status,...,engine_last_change_user,created_date,created_at,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng
0,4390940,04e97cdd-425a-48d8-a82d-96ab08f2670f,MARIANNA I,9162227,KQ416R,2024-05-02,2024-5-1 12:54,UTC +10:00,BRTH,DRIFTING,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
1,4390941,fff9cd3e-6e1c-4f4a-8bea-dd0639364122,MARIANNA I,9162227,KQ416R,2024-05-02,2024-5-2 9:56,UTC +10:00,REFL,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
2,4390942,d665ed27-97bb-4729-9a82-5d9b3c8320bc,MARIANNA I,9162227,KQ416R,2024-05-02,2024-5-2 9:56,UTC +10:00,REFL,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
3,4390943,9ed58560-2390-4bc2-8760-19d54f2c0205,MARIANNA I,9162227,KQ416R,2024-05-02,2024-5-2 12:00,UTC +10:00,PORT,IN PORT,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
4,4390944,8be23b32-c833-4bbc-95f0-7e42ebfbc185,MARIANNA I,9162227,KQ416R,2024-05-03,2024-5-2 14:12,UTC +10:00,SAIL,IN PORT,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15754,4535513,ba747b07-1910-4457-9da3-8c90318a4952,MSC TIANJIN,9285471,XA417A,2024-04-30,2024-4-29 23:42,UTC +02:00,SAIL,IN PORT,...,LIVIU NITU,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
15755,4535514,21eaf1bb-040a-4e4b-a71f-0010be0e302c,MSC TIANJIN,9285471,XA417A,2024-04-30,2024-4-30 1:00,UTC +02:00,COSP,DRIFTING,...,LIVIU NITU,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
15756,4535515,261455b7-d387-43b2-9d5c-07d4b97e38a6,MSC TIANJIN,9285471,XA417A,2024-04-30,2024-4-30 12:00,UTC +02:00,NOON,AT SEA,...,LIVIU NITU,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
15757,4535516,59114342-9b8d-468f-8e1f-7448fd5a666f,MSC TIANJIN,9285471,XA417A,2024-05-01,2024-4-30 20:00,UTC +02:00,EOSP,AT SEA,...,LIVIU NITU,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
15758,4535517,7df1e1cf-1c5d-4f72-82bf-a6681fe5ac54,MSC TIANJIN,9285471,XA417A,2024-05-01,2024-4-30 20:30,UTC +02:00,DLY A,DRIFTING,...,LIVIU NITU,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0

# check the port_delivery column and replace the NaN values

In [64]:
values_to_replace = ['<N/A>', '<N_A>']
charter_final['port_delivery'] = charter_final['port_delivery'].replace(values_to_replace, np.nan)
charter_final[charter_final['port_delivery'] == '<N_A>']

Empty DataFrame
Columns: [id, gid, vessel_name, imo, voy, corrected_date, report_date_time, report_date_time_offset, report_type, status, latitude, longitude, m_e_foc, cargo_total, has_cargo, steaming_time, total_m_e_hours_fuel_only, miles_by_gps, oil_cyl, speed_by_log, speed_by_gps, rpm, slip, wind_direction, wind_speed, draft_aft, draft_fwd, displacement, course_at_sea, wave_height, sea_direction, cargo_total_teu, ambient_temp, sw_temp, miles_by_speed_log, eta_port_code, eta_date_time, eta_date_time_offset, eta_port, time_change, time_sea, temp_min, temp_max, requested_speed, rem_dist_to_pilot, rem_time_to_pilot, total_unplnd_stpge_tech, total_unplnd_stpge_ope_wx, reefers_positive_plugged, reefers_negative_plugged, me_total_revs_counter, port_code, port, aux_blowers_on, hold_ventilation_on, since_date_time, since_date_time_offset, time_hrs_anchor, time_hrs_drift, reason, type_of_delay, etb_date_time, etb_date_time_offset, pilot_date_time, pilot_date_time_offset, time_manoeuvring, tug_arr, tug_shift, etd_date_time, etd_date_time_offset, shift_berth_hours, cargo_disch, teu_full, teu_empty, bilge_removed, garbage_removed, garbage_remvl_reqstd, garbage_remvl_cmplsry, fw_supply, cy_crew_signed_on, cy_crew_signed_off, cy_doctors_visit, cy_mail_received_ref_no, cy_lub_oil_sample_landed, cy_checkd_for_stowaways, cy_stowaways_on_board, cy_dep_gm_mtr, cy_requisitions_received, distance_to_next_pilot, tug_sailing_transit, steaming_time_m_e_rsdl_vls, steaming_time_m_e_rsdl_hs, steaming_time_m_e_rsdl_uls, steaming_time_m_e_dstlt_vls, steaming_time_m_e_dstlt_uls, steaming_time_m_e_tnktnr_dstlt_vls, steaming_time_m_e_hs, steaming_time_m_e_ls, steaming_time_m_e_mdo, steaming_time_m_e_mgo, ...]
Index: []

[0 rows x 257 columns]

In [65]:
charter_final[['port_code','port_delivery']]

      port_code port_delivery
0         AUBNE         AUBNE
1           NaN         AUBNE
2           NaN         AUBNE
3         AUBNE         AUBNE
4         AUBNE         AUBNE
...         ...           ...
15754     ITSPE         ITSPE
15755     ITSPE         ITSPE
15756     ITSPE         ITSPE
15757     FRFOS         FRFOS
15758     FRFOS         FRFOS

[15759 rows x 2 columns]

# 2. Ffill and bfill

In [66]:
charter_final = charter_final.sort_values(['report_date_time'])
charter_final

,id,gid,vessel_name,imo,voy,corrected_date,report_date_time,report_date_time_offset,report_type,status,...,engine_last_change_user,created_date,created_at,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng
6857,4500384,ed348459-1ec1-4b17-94f2-63534cbddf06,MSC VIGO,9480227,NG349W,2024-01-01,2024-1-1 10:18,UTC -06:00,DLY A,DRIFTING,...,CE,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
4235,4492948,62f10e88-328b-43a2-af64-9ca86744c745,ATHENS GLORY,9247766,349N,2024-01-01,2024-1-1 11:30,UTC -05:00,EOSP,AT SEA,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
4953,4496836,a7d84f7b-1a92-4fd4-8729-a89731681fe5,MSC MONTEREY,9349796,HI401A,2024-01-01,2024-1-1 12:00,UTC +09:00,DLY A,DRIFTING,...,Ch.Eng,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
4749,4495327,236c9f94-126b-4618-9efe-6dd677a5e340,LE HAVRE,9307243,MA344R,2024-01-01,2024-1-1 12:00,UTC +01:00,NOON,AT SEA,...,SEMENOV A.,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
6798,4500325,c6aa9168-8e9e-49c4-962b-2a4957cfdc14,MSC CORUNA,9480215,NY349R,2024-01-01,2024-1-1 12:00,UTC +00:00,NOON,AT SEA,...,C_E,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2700,4394387,314e0434-a8ef-4741-8ce9-496c35649b73,ETOILE,9301469,HG418A,2024-05-09,2024-5-9 7:12,UTC +09:00,COSP,DRIFTING,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
380,4390346,30de0eed-3fa7-40ce-9569-f97cc3c25672,MED TRABZON,9141780,AS418A,2024-05-09,2024-5-9 8:12,UTC +02:00,COSP,DRIFTING,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
1039,4396670,920e1cba-e1bc-4449-8ce3-700a5e1dfa32,EF EMIRA,9357810,DA418R,2024-05-09,2024-5-9 8:36,UTC +03:00,COSP,DRIFTING,...,C_E JOHN CAJILIG,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
2793,4394651,854d105e-3e19-4520-b1f1-52ea80492e15,MSC ROMA,9304447,IP419A,2024-05-09,2024-5-9 9:00,UTC +05:00,COSP,DRIFTING,...,NOVYTSKYY SERGEY,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
782,4394002,96662cf7-b099-48f0-a99b-5007c5b6909e,CONTI CHIVALRY,9293791,MA414R,2024-05-09,2024-5-9 9:00,UTC +08:00,EOSP,AT SEA,...,CE,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0

In [67]:
charter_final['port_delivery'] = charter_final.groupby(['imo'])['port_delivery'].transform(lambda v: v.ffill())
charter_final['port_delivery'] = charter_final.groupby(['imo'])['port_delivery'].transform(lambda v: v.bfill())

In [68]:
charter_final['port_delivery'].isna().sum()

0

# adding REMARK column

In [69]:
charter_final.to_csv('charter_final.csv')

In [70]:
columns = ['sulphur_content_pc','quantity']
charter_final[columns].dtypes

sulphur_content_pc    float64
quantity              float64
dtype: object

In [71]:
charter_final['quantity'] = charter_final['quantity'].astype(float)

In [72]:
FINALCHARTER = charter_final

In [73]:
#use python remarks function next
def remark(data1):
    r1 = data1[data1['sulphur_content_pc']==0]
    r1['Remarks'] = "Sulphur is not given"
    hs_data = data1[data1['fuel_type']=='RESIDUAL HS']
    r2 = hs_data[(hs_data['sulphur_content_pc']<0.5) | (hs_data['sulphur_content_pc']>3.5) ]
    r2['Remarks'] = "Fuel Type or Sulphur will be wrong"
    ls_data = data1[(data1['fuel_type']=='RESIDUAL VLS') | (data1['fuel_type']=='DISTILLATE ULS')| (data1['fuel_type']=='DISTILLATE VLS') | (data1['fuel_type']=='RESIDUAL ULS')  | (data1['fuel_type']=='TANKTAINER DISTILLATE VLS')]
    r3 = ls_data[(ls_data['sulphur_content_pc']<0) | (ls_data['sulphur_content_pc']>0.5) ]
    r3['Remarks'] = "Fuel Type or Sulphur will be wrong"
    r4 = data1[data1['sulphur_content_pc'].isnull()]
    r4['Remarks'] = "Sulphur is not given"
    r5 = data1[data1['quantity']<=0]
    r5['Remarks'] = "quantity is not given"
    r6 = data1[data1['quantity'].isnull()]
    r6['Remarks'] = "quantity is not given"
    r7 = data1[data1['delivery'].isnull()]
    r7['Remarks'] = "BDN is not given"
    data1["joinall"]= data1['delivery'].str.replace(r'[-_\s.,/]+', '')
    data1["is_alpha_Delivery"]= data1["joinall"].str.isalpha()
    r8 = data1[data1['is_alpha_Delivery']==True]
    r8['Remarks'] = "BDN is not given"
    r9 = data1[data1['delivery']=='0']
    r9['Remarks'] = "BDN is not given"
    df = pd.concat([r1,r2,r3,r4,r5,r6,r7,r8,r9])
    df.drop('is_alpha_Delivery', axis=1, inplace=True)
    df.drop('joinall', axis=1, inplace=True)
    p = df.groupby('gid')['Remarks'].agg(','.join).reset_index()
    dict_remarks = pd.Series(p['Remarks'].values,index=p['gid']).to_dict()
    import numpy as np
    df['REMARKS'] = np.nan
    df['REMARKS'] = df['REMARKS'].fillna(df['gid'].apply(lambda x:dict_remarks.get(x)))
    df.drop('Remarks', axis=1, inplace=True)
    df.drop_duplicates(keep='first',inplace=True)
    return df

In [74]:
output = remark(FINALCHARTER)
output

,id,gid,vessel_name,imo,voy,corrected_date,report_date_time,report_date_time_offset,report_type,status,...,created_date,created_at,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng,REMARKS
3326,4490311,d54b3fce-c7e4-4423-bd60-99066cd81cc5,KOTKA,9085534,ZF350A,2024-01-01,2024-1-1 9:42,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,Sulphur is not given
4214,4492927,a030ad08-a899-45f3-8fb8-c828f0d620bc,MSC BOSPHORUS,9247742,FR350W,2024-01-13,2024-1-13 10:08,UTC -05:00,REFL,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,"Sulphur is not given,Fuel Type or Sulphur will..."
3886,4492098,3362ebed-91e9-4b62-8269-f3e6f9b5a739,MSC ILONA,9225641,UA351A,2024-01-16,2024-1-16 3:45,UTC -05:00,REFL,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,"Sulphur is not given,BDN is not given"
4294,4493169,eb234fe9-286c-4bd5-9b2a-ed2ed9db4042,MSC TURIN II,9256365,UI350R,2024-01-02,2024-1-2 4:25,UTC +03:00,REFL,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,Sulphur is not given
4295,4493170,1ef7aba0-7c24-413c-b45d-b31016207e15,MSC TURIN II,9256365,UI350R,2024-01-02,2024-1-2 7:25,UTC +03:00,REFL,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,Sulphur is not given
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8913,4508019,326f74c3-658f-45b0-9543-8f172f6abc66,MSC TIANJIN,9285471,ME405W,2024-02-11,2024-2-10 13:10,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,BDN is not given
9917,4521476,42edc2a3-0ec6-4af8-a7c9-25f5ca3308ca,MSC TIANJIN,9285471,ME405W,2024-03-02,2024-3-2 2:00,UTC -05:00,REFL,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,BDN is not given
11180,4526702,1d049daf-2523-44dd-a540-b0f9e148cc44,MSC SAVONA,9460356,UK409R,2024-03-22,2024-3-22 3:30,UTC -07:00,REFL,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,BDN is not given
9781,4520830,6e5c835c-01ac-4f6f-8400-dc050834ba4b,MSC QINGDAO,9256470,ME407W,2024-03-14,2024-3-13 18:20,UTC -04:00,REFL,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,BDN is not given
9780,4520829,6016dcdd-3502-4c1e-89ba-4d47eb5c87a5,MSC QINGDAO,9256470,ME407W,2024-03-14,2024-3-13 18:20,UTC -04:00,REFL,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,BDN is not given

In [75]:
#Join this remarks to main data
dict_remark = pd.Series(output['REMARKS'].values,index=output['gid']).to_dict()
import numpy as np
FINALCHARTER['REMARKS'] = np.nan
FINALCHARTER['REMARKS'] = FINALCHARTER['REMARKS'].fillna(FINALCHARTER['gid'].apply(lambda x:dict_remark.get(x)))
FINALCHARTER.tail()

,id,gid,vessel_name,imo,voy,corrected_date,report_date_time,report_date_time_offset,report_type,status,...,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng,joinall,is_alpha_Delivery,REMARKS
2700,4394387,314e0434-a8ef-4741-8ce9-496c35649b73,ETOILE,9301469,HG418A,2024-05-09,2024-5-9 7:12,UTC +09:00,COSP,DRIFTING,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
380,4390346,30de0eed-3fa7-40ce-9569-f97cc3c25672,MED TRABZON,9141780,AS418A,2024-05-09,2024-5-9 8:12,UTC +02:00,COSP,DRIFTING,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
1039,4396670,920e1cba-e1bc-4449-8ce3-700a5e1dfa32,EF EMIRA,9357810,DA418R,2024-05-09,2024-5-9 8:36,UTC +03:00,COSP,DRIFTING,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
2793,4394651,854d105e-3e19-4520-b1f1-52ea80492e15,MSC ROMA,9304447,IP419A,2024-05-09,2024-5-9 9:00,UTC +05:00,COSP,DRIFTING,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
782,4394002,96662cf7-b099-48f0-a99b-5007c5b6909e,CONTI CHIVALRY,9293791,MA414R,2024-05-09,2024-5-9 9:00,UTC +08:00,EOSP,AT SEA,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."

In [76]:
FINALCHARTER.drop('is_alpha_Delivery', axis=1, inplace=True)
FINALCHARTER.drop('joinall', axis=1, inplace=True)
FINALCHARTER

,id,gid,vessel_name,imo,voy,corrected_date,report_date_time,report_date_time_offset,report_type,status,...,created_date,created_at,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng,REMARKS
6857,4500384,ed348459-1ec1-4b17-94f2-63534cbddf06,MSC VIGO,9480227,NG349W,2024-01-01,2024-1-1 10:18,UTC -06:00,DLY A,DRIFTING,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,"Sulphur is not given,quantity is not given,BDN..."
4235,4492948,62f10e88-328b-43a2-af64-9ca86744c745,ATHENS GLORY,9247766,349N,2024-01-01,2024-1-1 11:30,UTC -05:00,EOSP,AT SEA,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,"Sulphur is not given,quantity is not given,BDN..."
4953,4496836,a7d84f7b-1a92-4fd4-8729-a89731681fe5,MSC MONTEREY,9349796,HI401A,2024-01-01,2024-1-1 12:00,UTC +09:00,DLY A,DRIFTING,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,"Sulphur is not given,quantity is not given,BDN..."
4749,4495327,236c9f94-126b-4618-9efe-6dd677a5e340,LE HAVRE,9307243,MA344R,2024-01-01,2024-1-1 12:00,UTC +01:00,NOON,AT SEA,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,"Sulphur is not given,quantity is not given,BDN..."
6798,4500325,c6aa9168-8e9e-49c4-962b-2a4957cfdc14,MSC CORUNA,9480215,NY349R,2024-01-01,2024-1-1 12:00,UTC +00:00,NOON,AT SEA,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,"Sulphur is not given,quantity is not given,BDN..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2700,4394387,314e0434-a8ef-4741-8ce9-496c35649b73,ETOILE,9301469,HG418A,2024-05-09,2024-5-9 7:12,UTC +09:00,COSP,DRIFTING,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,"Sulphur is not given,quantity is not given,BDN..."
380,4390346,30de0eed-3fa7-40ce-9569-f97cc3c25672,MED TRABZON,9141780,AS418A,2024-05-09,2024-5-9 8:12,UTC +02:00,COSP,DRIFTING,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,"Sulphur is not given,quantity is not given,BDN..."
1039,4396670,920e1cba-e1bc-4449-8ce3-700a5e1dfa32,EF EMIRA,9357810,DA418R,2024-05-09,2024-5-9 8:36,UTC +03:00,COSP,DRIFTING,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,"Sulphur is not given,quantity is not given,BDN..."
2793,4394651,854d105e-3e19-4520-b1f1-52ea80492e15,MSC ROMA,9304447,IP419A,2024-05-09,2024-5-9 9:00,UTC +05:00,COSP,DRIFTING,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,"Sulphur is not given,quantity is not given,BDN..."
782,4394002,96662cf7-b099-48f0-a99b-5007c5b6909e,CONTI CHIVALRY,9293791,MA414R,2024-05-09,2024-5-9 9:00,UTC +08:00,EOSP,AT SEA,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,"Sulphur is not given,quantity is not given,BDN..."

In [77]:
#changes to Delivery column - > MANUALLY CHECK ALL PROBLEMS IN DELIVERY COLUMN

# 1.if delivery column having 0 or multiple 0 then Remarks updated as 'BDN not given'
# 2.if 'BDN' comes first or last ,then remove 'BDN'
# 3. if '.' is comes at last , then remove it
# 4. if '.' comes in between , then change it to underscore
# 5. if * and _ comes last or first ,it can be removed using following function

In [78]:
#if delivery column starts or ends with underscore(_ and *)
def delivery_modification(FINALCHARTER):
    FINALCHARTER["delivery"] = FINALCHARTER["delivery"].astype('string')
    FINALCHARTER_nan=FINALCHARTER[FINALCHARTER['delivery'].isna()]
    FINALCHARTER_nan_gid_list = list(FINALCHARTER_nan['gid'])
    FINALCHARTER_not_nan=FINALCHARTER[~FINALCHARTER['gid'].isin(FINALCHARTER_nan_gid_list)]
    FINALCHARTER_not_nan["delivery"] = FINALCHARTER_not_nan["delivery"].apply(lambda x: x.strip("_*"))
    FINALCHARTER_delivery_concat = pd.concat([FINALCHARTER_not_nan,FINALCHARTER_nan])
    FINALCHARTER = FINALCHARTER.drop(['delivery'], axis=1)
    dict_noon_delivery = pd.Series(FINALCHARTER_delivery_concat['delivery'].values,index=FINALCHARTER_delivery_concat['gid']).to_dict()
    FINALCHARTER['delivery'] = np.nan
    FINALCHARTER['delivery'] = FINALCHARTER['delivery'].fillna(FINALCHARTER['gid'].apply(lambda x:dict_noon_delivery.get(x)))
    return FINALCHARTER

In [79]:
FINALCHARTER = delivery_modification(FINALCHARTER)
FINALCHARTER

,id,gid,vessel_name,imo,voy,corrected_date,report_date_time,report_date_time_offset,report_type,status,...,created_at,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng,REMARKS,delivery
6857,4500384,ed348459-1ec1-4b17-94f2-63534cbddf06,MSC VIGO,9480227,NG349W,2024-01-01,2024-1-1 10:18,UTC -06:00,DLY A,DRIFTING,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,"Sulphur is not given,quantity is not given,BDN...",<NA>
4235,4492948,62f10e88-328b-43a2-af64-9ca86744c745,ATHENS GLORY,9247766,349N,2024-01-01,2024-1-1 11:30,UTC -05:00,EOSP,AT SEA,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,"Sulphur is not given,quantity is not given,BDN...",<NA>
4953,4496836,a7d84f7b-1a92-4fd4-8729-a89731681fe5,MSC MONTEREY,9349796,HI401A,2024-01-01,2024-1-1 12:00,UTC +09:00,DLY A,DRIFTING,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,"Sulphur is not given,quantity is not given,BDN...",<NA>
4749,4495327,236c9f94-126b-4618-9efe-6dd677a5e340,LE HAVRE,9307243,MA344R,2024-01-01,2024-1-1 12:00,UTC +01:00,NOON,AT SEA,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,"Sulphur is not given,quantity is not given,BDN...",<NA>
6798,4500325,c6aa9168-8e9e-49c4-962b-2a4957cfdc14,MSC CORUNA,9480215,NY349R,2024-01-01,2024-1-1 12:00,UTC +00:00,NOON,AT SEA,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,"Sulphur is not given,quantity is not given,BDN...",<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2700,4394387,314e0434-a8ef-4741-8ce9-496c35649b73,ETOILE,9301469,HG418A,2024-05-09,2024-5-9 7:12,UTC +09:00,COSP,DRIFTING,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,"Sulphur is not given,quantity is not given,BDN...",<NA>
380,4390346,30de0eed-3fa7-40ce-9569-f97cc3c25672,MED TRABZON,9141780,AS418A,2024-05-09,2024-5-9 8:12,UTC +02:00,COSP,DRIFTING,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,"Sulphur is not given,quantity is not given,BDN...",<NA>
1039,4396670,920e1cba-e1bc-4449-8ce3-700a5e1dfa32,EF EMIRA,9357810,DA418R,2024-05-09,2024-5-9 8:36,UTC +03:00,COSP,DRIFTING,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,"Sulphur is not given,quantity is not given,BDN...",<NA>
2793,4394651,854d105e-3e19-4520-b1f1-52ea80492e15,MSC ROMA,9304447,IP419A,2024-05-09,2024-5-9 9:00,UTC +05:00,COSP,DRIFTING,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,"Sulphur is not given,quantity is not given,BDN...",<NA>
782,4394002,96662cf7-b099-48f0-a99b-5007c5b6909e,CONTI CHIVALRY,9293791,MA414R,2024-05-09,2024-5-9 9:00,UTC +08:00,EOSP,AT SEA,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,"Sulphur is not given,quantity is not given,BDN...",<NA>

In [80]:
FINALCHARTER.columns.to_list()

['id',
 'gid',
 'vessel_name',
 'imo',
 'voy',
 'corrected_date',
 'report_date_time',
 'report_date_time_offset',
 'report_type',
 'status',
 'latitude',
 'longitude',
 'm_e_foc',
 'cargo_total',
 'has_cargo',
 'steaming_time',
 'total_m_e_hours_fuel_only',
 'miles_by_gps',
 'oil_cyl',
 'speed_by_log',
 'speed_by_gps',
 'rpm',
 'slip',
 'wind_direction',
 'wind_speed',
 'draft_aft',
 'draft_fwd',
 'displacement',
 'course_at_sea',
 'wave_height',
 'sea_direction',
 'cargo_total_teu',
 'ambient_temp',
 'sw_temp',
 'miles_by_speed_log',
 'eta_port_code',
 'eta_date_time',
 'eta_date_time_offset',
 'eta_port',
 'time_change',
 'time_sea',
 'temp_min',
 'temp_max',
 'requested_speed',
 'rem_dist_to_pilot',
 'rem_time_to_pilot',
 'total_unplnd_stpge_tech',
 'total_unplnd_stpge_ope_wx',
 'reefers_positive_plugged',
 'reefers_negative_plugged',
 'me_total_revs_counter',
 'port_code',
 'port',
 'aux_blowers_on',
 'hold_ventilation_on',
 'since_date_time',
 'since_date_time_offset',
 'time_hrs_anchor',
 'time_hrs_drift',
 'reason',
 'type_of_delay',
 'etb_date_time',
 'etb_date_time_offset',
 'pilot_date_time',
 'pilot_date_time_offset',
 'time_manoeuvring',
 'tug_arr',
 'tug_shift',
 'etd_date_time',
 'etd_date_time_offset',
 'shift_berth_hours',
 'cargo_disch',
 'teu_full',
 'teu_empty',
 'bilge_removed',
 'garbage_removed',
 'garbage_remvl_reqstd',
 'garbage_remvl_cmplsry',
 'fw_supply',
 'cy_crew_signed_on',
 'cy_crew_signed_off',
 'cy_doctors_visit',
 'cy_mail_received_ref_no',
 'cy_lub_oil_sample_landed',
 'cy_checkd_for_stowaways',
 'cy_stowaways_on_board',
 'cy_dep_gm_mtr',
 'cy_requisitions_received',
 'distance_to_next_pilot',
 'tug_sailing_transit',
 'steaming_time_m_e_rsdl_vls',
 'steaming_time_m_e_rsdl_hs',
 'steaming_time_m_e_rsdl_uls',
 'steaming_time_m_e_dstlt_vls',
 'steaming_time_m_e_dstlt_uls',
 'steaming_time_m_e_tnktnr_dstlt_vls',
 'steaming_time_m_e_hs',
 'steaming_time_m_e_ls',
 'steaming_time_m_e_mdo',
 'steaming_time_m_e_mgo',
 'steaming_time_m_e_mgo_ls',
 'steaming_time_aux_1',
 'steaming_time_aux_2',
 'steaming_time_aux_3',
 'steaming_time_aux_4',
 'steaming_time_aux_5',
 'steaming_time_sh_gen',
 'steaming_time_tg',
 'power_kw',
 'steaming_load_kw_aux_1',
 'steaming_load_kw_aux_2',
 'steaming_load_kw_aux_3',
 'steaming_load_kw_aux_4',
 'steaming_load_kw_aux_5',
 'steaming_load_kw_sh_gen',
 'steaming_load_kw_tg',
 'fuel_m_e_rsdl_vls',
 'fuel_m_e_rsdl_hs',
 'fuel_m_e_rsdl_uls',
 'fuel_m_e_dstlt_vls',
 'fuel_m_e_dstlt_uls',
 'fuel_m_e_tnktnr_dstlt_vls',
 'fuel_m_e_hs',
 'fuel_m_e_ls',
 'fuel_m_e_mdo',
 'fuel_m_e_mgo',
 'fuel_m_e_mgo_ls',
 'fuel_aux_rsdl_vls',
 'fuel_aux_rsdl_hs',
 'fuel_aux_rsdl_uls',
 'fuel_aux_dstlt_vls',
 'fuel_aux_dstlt_uls',
 'fuel_aux_tnktnr_dstlt_vls',
 'fuel_aux_hs',
 'fuel_aux_ls',
 'fuel_aux_mdo',
 'fuel_aux_mgo',
 'fuel_aux_mgo_ls',
 'fuel_boiler_rsdl_vls',
 'fuel_boiler_rsdl_hs',
 'fuel_boiler_rsdl_uls',
 'fuel_boiler_dstlt_vls',
 'fuel_boiler_dstlt_uls',
 'fuel_boiler_tnktnr_dstlt_vls',
 'fuel_boiler_hs',
 'fuel_boiler_ls',
 'fuel_boiler_mdo',
 'fuel_boiler_mgo',
 'fuel_boiler_mgo_ls',
 'deck_last_change_user',
 'deck_part_is_complete',
 'engine_part_is_complete',
 'scavenge_pressure',
 'seca_entry_time',
 'seca_entry_lat',
 'seca_entry_long',
 'rob_fresh_water',
 'manvrng_miles_by_gps',
 'manvrng_miles_by_speed_log',
 'tanktainer_transfd_quantity',
 'pilot_taken',
 'date_time_start_transit',
 'date_time_start_transit_offset',
 'date_time_end_transit',
 'date_time_end_transit_offset',
 'ballast',
 'tanktainer_number',
 'steaming_kwhr_total',
 'cy_others',
 'rob_fo_sludge',
 'rob_lo_sludge',
 'rob_bilge',
 'sludge_removed_fo',
 'sludge_removed_lo',
 'sea_state',
 'cy_lub_added_to_system_mecc',
 'cy_lub_added_to_system_aecc',
 'cy_lub_added_to_thrusters',
 'cy_me_lo_purifier_in_use',
 'cy_ballast',
 'cy_bending_moment',
 'cy_shearing_force',
 'cy_tortion_moment',
 'cy_supdt_auditor_signed_on',
 'cy_supdt_auditor_signed_off',
 'cy_cash_received',
 'cy_lub_oil_received_mecyl',
 'cy_lub_oil_received_mecc',
 'cy_lub_oil_received_aecc',
 'cy_m_e_under_piston_temp',
 'cy_mail_received',
 'wind_direction_port_stbd',
 'sea_direction_port_stbd',
 'time_pilot_onboard',
 'grades_rob',
 'bunker_order',
 'remarks',
 'fuel_type',
 'carbon_factor',
 'so_2_co_2_ratio',
 'sulphur_content_pc',
 'quantity',
 'port_delivery',
 'product_quality',
 'tanktainer_number_1',
 'supplier',
 'vol_lt',
 'den',
 'vis',
 'fuel_hs',
 'fuel_ls',
 'fuel_mdo',
 'fuel_mgo',
 'fuel_mgo_ls',
 'bdn',
 'rob_dstlt_uls',
 'rob_dstlt_vls',
 'rob_rsdl_mdo',
 'rob_tnktnr_dstlt_vls',
 'rob_rsdl_vls',
 'rob_rsdl_hs',
 'rob_rsdl_uls',
 'rob_fuel_hsfo',
 'rob_fuel_lsfo',
 'rob_fuel_mdo',
 'rob_fuel_mgo',
 'rob_fuel_mgo_ls',
 'rob_fuel_tanktainer_mgo',
 'eca_miles',
 'eca_time',
 'egcs_dry_waste_removed',
 'egcs_running_time',
 'egcs_wet_slurry_removed',
 'egcs_open_loop_running_time',
 'egcs_closed_loop_running_time',
 'updated_date',
 'fuel_rsdl_hs',
 'fuel_rsdl_vls',
 'fuel_rsdl_uls',
 'fuel_dstlt_vls',
 'fuel_dstlt_uls',
 'fuel_tnktnr_dstlt_vls',
 'cargo_load',
 'seca_exit_time',
 'seca_exit_lat',
 'seca_exit_long',
 'engine_last_change_user',
 'created_date',
 'created_at',
 'updated_at',
 'created_by_id',
 'updated_by_id',
 'fuel_m_e_lng',
 'fuel_aux_lng',
 'fuel_boiler_lng',
 'rob_boiler_lng',
 'REMARKS',
 'delivery']

In [81]:
FINALCHARTER = FINALCHARTER[['id',
 'gid',
 'vessel_name',
 'imo',
 'voy',
 'corrected_date',
 'report_date_time',
 'report_date_time_offset',
 'report_type',
 'status',
 'latitude',
 'longitude',
 'm_e_foc',
 'cargo_total',
 'has_cargo',
 'steaming_time',
 'total_m_e_hours_fuel_only',
 'miles_by_gps',
 'oil_cyl',
 'speed_by_log',
 'speed_by_gps',
 'rpm',
 'slip',
 'wind_direction',
 'wind_speed',
 'draft_aft',
 'draft_fwd',
 'displacement',
 'course_at_sea',
 'wave_height',
 'sea_direction',
 'cargo_total_teu',
 'ambient_temp',
 'sw_temp',
 'miles_by_speed_log',
 'eta_port_code',
 'eta_date_time',
 'eta_date_time_offset',
 'eta_port',
 'time_change',
 'time_sea',
 'temp_min',
 'temp_max',
 'requested_speed',
 'rem_dist_to_pilot',
 'rem_time_to_pilot',
 'total_unplnd_stpge_tech',
 'total_unplnd_stpge_ope_wx',
 'reefers_positive_plugged',
 'reefers_negative_plugged',
 'me_total_revs_counter',
 'port_code',
 'port',
 'aux_blowers_on',
 'hold_ventilation_on',
 'since_date_time',
 'since_date_time_offset',
 'time_hrs_anchor',
 'time_hrs_drift',
 'reason',
 'type_of_delay',
 'etb_date_time',
 'etb_date_time_offset',
 'pilot_date_time',
 'pilot_date_time_offset',
 'time_manoeuvring',
 'tug_arr',
 'tug_shift',
 'etd_date_time',
 'etd_date_time_offset',
 'shift_berth_hours',
 'cargo_disch',
 'teu_full',
 'teu_empty',
 'bilge_removed',
 'garbage_removed',
 'garbage_remvl_reqstd',
 'garbage_remvl_cmplsry',
 'fw_supply',
 'cy_crew_signed_on',
 'cy_crew_signed_off',
 'cy_doctors_visit',
 'cy_mail_received_ref_no',
 'cy_lub_oil_sample_landed',
 'cy_checkd_for_stowaways',
 'cy_stowaways_on_board',
 'cy_dep_gm_mtr',
 'cy_requisitions_received',
 'distance_to_next_pilot',
 'tug_sailing_transit',
 'steaming_time_m_e_rsdl_vls',
 'steaming_time_m_e_rsdl_hs',
 'steaming_time_m_e_rsdl_uls',
 'steaming_time_m_e_dstlt_vls',
 'steaming_time_m_e_dstlt_uls',
 'steaming_time_m_e_tnktnr_dstlt_vls',
 'steaming_time_m_e_hs',
 'steaming_time_m_e_ls',
 'steaming_time_m_e_mdo',
 'steaming_time_m_e_mgo',
 'steaming_time_m_e_mgo_ls',
 'steaming_time_aux_1',
 'steaming_time_aux_2',
 'steaming_time_aux_3',
 'steaming_time_aux_4',
 'steaming_time_aux_5',
 'steaming_time_sh_gen',
 'steaming_time_tg',
 'power_kw',
 'steaming_load_kw_aux_1',
 'steaming_load_kw_aux_2',
 'steaming_load_kw_aux_3',
 'steaming_load_kw_aux_4',
 'steaming_load_kw_aux_5',
 'steaming_load_kw_sh_gen',
 'steaming_load_kw_tg',
 'fuel_m_e_rsdl_vls',
 'fuel_m_e_rsdl_hs',
 'fuel_m_e_rsdl_uls',
 'fuel_m_e_dstlt_vls',
 'fuel_m_e_dstlt_uls',
 'fuel_m_e_tnktnr_dstlt_vls',
 'fuel_m_e_hs',
 'fuel_m_e_ls',
 'fuel_m_e_mdo',
 'fuel_m_e_mgo',
 'fuel_m_e_mgo_ls',
 'fuel_aux_rsdl_vls',
 'fuel_aux_rsdl_hs',
 'fuel_aux_rsdl_uls',
 'fuel_aux_dstlt_vls',
 'fuel_aux_dstlt_uls',
 'fuel_aux_tnktnr_dstlt_vls',
 'fuel_aux_hs',
 'fuel_aux_ls',
 'fuel_aux_mdo',
 'fuel_aux_mgo',
 'fuel_aux_mgo_ls',
 'fuel_boiler_rsdl_vls',
 'fuel_boiler_rsdl_hs',
 'fuel_boiler_rsdl_uls',
 'fuel_boiler_dstlt_vls',
 'fuel_boiler_dstlt_uls',
 'fuel_boiler_tnktnr_dstlt_vls',
 'fuel_boiler_hs',
 'fuel_boiler_ls',
 'fuel_boiler_mdo',
 'fuel_boiler_mgo',
 'fuel_boiler_mgo_ls',
 'deck_last_change_user',
 'deck_part_is_complete',
 'engine_part_is_complete',
 'scavenge_pressure',
 'seca_entry_time',
 'seca_entry_lat',
 'seca_entry_long',
 'rob_fresh_water',
 'manvrng_miles_by_gps',
 'manvrng_miles_by_speed_log',
 'tanktainer_transfd_quantity',
 'pilot_taken',
 'date_time_start_transit',
 'date_time_start_transit_offset',
 'date_time_end_transit',
 'date_time_end_transit_offset',
 'ballast',
 'tanktainer_number',
 'steaming_kwhr_total',
 'cy_others',
 'rob_fo_sludge',
 'rob_lo_sludge',
 'rob_bilge',
 'sludge_removed_fo',
 'sludge_removed_lo',
 'sea_state',
 'cy_lub_added_to_system_mecc',
 'cy_lub_added_to_system_aecc',
 'cy_lub_added_to_thrusters',
 'cy_me_lo_purifier_in_use',
 'cy_ballast',
 'cy_bending_moment',
 'cy_shearing_force',
 'cy_tortion_moment',
 'cy_supdt_auditor_signed_on',
 'cy_supdt_auditor_signed_off',
 'cy_cash_received',
 'cy_lub_oil_received_mecyl',
 'cy_lub_oil_received_mecc',
 'cy_lub_oil_received_aecc',
 'cy_m_e_under_piston_temp',
 'cy_mail_received',
 'wind_direction_port_stbd',
 'sea_direction_port_stbd',
 'time_pilot_onboard',
 'grades_rob',
 'bunker_order',
 'remarks',
 'fuel_type',
 'carbon_factor',
 'so_2_co_2_ratio',
 'sulphur_content_pc',
 'quantity',
 'port_delivery',
 'product_quality',
 'tanktainer_number_1',
 'supplier',
 'vol_lt',
 'den',
 'vis',
 'fuel_hs',
 'fuel_ls',
 'fuel_mdo',
 'fuel_mgo',
 'fuel_mgo_ls',
 'bdn',
 'rob_dstlt_uls',
 'rob_dstlt_vls',
 'rob_rsdl_mdo',
 'rob_tnktnr_dstlt_vls',
 'rob_rsdl_vls',
 'rob_rsdl_hs',
 'rob_rsdl_uls',
 'rob_fuel_hsfo',
 'rob_fuel_lsfo',
 'rob_fuel_mdo',
 'rob_fuel_mgo',
 'rob_fuel_mgo_ls',
 'rob_fuel_tanktainer_mgo',
 'eca_miles',
 'eca_time',
 'egcs_dry_waste_removed',
 'egcs_running_time',
 'egcs_wet_slurry_removed',
 'egcs_open_loop_running_time',
 'egcs_closed_loop_running_time',
 'updated_date',
 'fuel_rsdl_hs',
 'fuel_rsdl_vls',
 'fuel_rsdl_uls',
 'fuel_dstlt_vls',
 'fuel_dstlt_uls',
 'fuel_tnktnr_dstlt_vls',
 'cargo_load',
 'seca_exit_time',
 'seca_exit_lat',
 'seca_exit_long',
 'engine_last_change_user',
 'created_date',
 'created_at',
 'updated_at',
 'created_by_id',
 'updated_by_id',
 'fuel_m_e_lng',
 'fuel_aux_lng',
 'fuel_boiler_lng',
 'rob_boiler_lng',
 'delivery',
 'REMARKS'
 
]]
FINALCHARTER

,id,gid,vessel_name,imo,voy,corrected_date,report_date_time,report_date_time_offset,report_type,status,...,created_at,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng,delivery,REMARKS
6857,4500384,ed348459-1ec1-4b17-94f2-63534cbddf06,MSC VIGO,9480227,NG349W,2024-01-01,2024-1-1 10:18,UTC -06:00,DLY A,DRIFTING,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,<NA>,"Sulphur is not given,quantity is not given,BDN..."
4235,4492948,62f10e88-328b-43a2-af64-9ca86744c745,ATHENS GLORY,9247766,349N,2024-01-01,2024-1-1 11:30,UTC -05:00,EOSP,AT SEA,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,<NA>,"Sulphur is not given,quantity is not given,BDN..."
4953,4496836,a7d84f7b-1a92-4fd4-8729-a89731681fe5,MSC MONTEREY,9349796,HI401A,2024-01-01,2024-1-1 12:00,UTC +09:00,DLY A,DRIFTING,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,<NA>,"Sulphur is not given,quantity is not given,BDN..."
4749,4495327,236c9f94-126b-4618-9efe-6dd677a5e340,LE HAVRE,9307243,MA344R,2024-01-01,2024-1-1 12:00,UTC +01:00,NOON,AT SEA,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,<NA>,"Sulphur is not given,quantity is not given,BDN..."
6798,4500325,c6aa9168-8e9e-49c4-962b-2a4957cfdc14,MSC CORUNA,9480215,NY349R,2024-01-01,2024-1-1 12:00,UTC +00:00,NOON,AT SEA,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,<NA>,"Sulphur is not given,quantity is not given,BDN..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2700,4394387,314e0434-a8ef-4741-8ce9-496c35649b73,ETOILE,9301469,HG418A,2024-05-09,2024-5-9 7:12,UTC +09:00,COSP,DRIFTING,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,<NA>,"Sulphur is not given,quantity is not given,BDN..."
380,4390346,30de0eed-3fa7-40ce-9569-f97cc3c25672,MED TRABZON,9141780,AS418A,2024-05-09,2024-5-9 8:12,UTC +02:00,COSP,DRIFTING,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,<NA>,"Sulphur is not given,quantity is not given,BDN..."
1039,4396670,920e1cba-e1bc-4449-8ce3-700a5e1dfa32,EF EMIRA,9357810,DA418R,2024-05-09,2024-5-9 8:36,UTC +03:00,COSP,DRIFTING,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,<NA>,"Sulphur is not given,quantity is not given,BDN..."
2793,4394651,854d105e-3e19-4520-b1f1-52ea80492e15,MSC ROMA,9304447,IP419A,2024-05-09,2024-5-9 9:00,UTC +05:00,COSP,DRIFTING,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,<NA>,"Sulphur is not given,quantity is not given,BDN..."
782,4394002,96662cf7-b099-48f0-a99b-5007c5b6909e,CONTI CHIVALRY,9293791,MA414R,2024-05-09,2024-5-9 9:00,UTC +08:00,EOSP,AT SEA,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,<NA>,"Sulphur is not given,quantity is not given,BDN..."

In [82]:
refl_charter = FINALCHARTER[FINALCHARTER['report_type'] == 'REFL']
refl_charter

,id,gid,vessel_name,imo,voy,corrected_date,report_date_time,report_date_time_offset,report_type,status,...,created_at,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng,delivery,REMARKS
4367,4493242,3eacc476-c023-494d-a6ce-a1aa6378218d,MSC QINGDAO,9256470,ME351W,2024-01-02,2024-1-1 14:35,UTC +00:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,2195,None
3326,4490311,d54b3fce-c7e4-4423-bd60-99066cd81cc5,KOTKA,9085534,ZF350A,2024-01-01,2024-1-1 9:42,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,14799,Sulphur is not given
4590,4494685,a0467399-7302-4cfa-a98e-01ae7ba67a4c,ALANA,9297589,RC352R,2024-01-13,2024-1-12 13:00,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,BRZI _ 32,None
4214,4492927,a030ad08-a899-45f3-8fb8-c828f0d620bc,MSC BOSPHORUS,9247742,FR350W,2024-01-13,2024-1-13 10:08,UTC -05:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0847-GB,"Sulphur is not given,Fuel Type or Sulphur will..."
4321,4493196,d52d5be1-85ba-4971-99cf-d1cefe281b8c,MED CESME,9256365,DD402A,2024-01-14,2024-1-13 15:20,UTC +03:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,164069,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2166,4400611,5d08330f-f1fe-437d-9978-56f153b43d29,HUBERT SCHULTE,9535204,NG415E,2024-05-10,2024-5-9 17:18,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,BRBTB202400000478,None
2167,4400612,4ce4295a-b97c-47d5-be01-7e7c08138ced,HUBERT SCHULTE,9535204,NG415E,2024-05-10,2024-5-9 22:00,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,BRDI_105,None
785,4394005,23856d53-69cf-4984-ba31-2a1c6678e5ea,CONTI CHIVALRY,9293791,MA414R,2024-05-10,2024-5-9 23:05,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,100389,None
1946,4400564,a1695f38-5432-4fd1-b96c-10e1b23789be,HERMANN SCHULTE,9535187,NG418E,2024-05-09,2024-5-9 2:04,UTC -05:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,10108338,Sulphur is not given
3136,4403161,d8ced3a9-4ae4-45f7-8309-df6814f5441f,SPIRIT OF KOLKATA,9813838,SH417R,2024-05-09,2024-5-9 7:00,UTC +05:30,REFL,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,2013,None

In [83]:
refl_charter.to_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\OUTPUT\CHARTER MISSING BDNs refl.xlsx",index = False)

In [84]:
refl_charter_remarks = refl_charter[refl_charter['REMARKS'].notnull()]
refl_charter_remarks

,id,gid,vessel_name,imo,voy,corrected_date,report_date_time,report_date_time_offset,report_type,status,...,created_at,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng,delivery,REMARKS
3326,4490311,d54b3fce-c7e4-4423-bd60-99066cd81cc5,KOTKA,9085534,ZF350A,2024-01-01,2024-1-1 9:42,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,14799,Sulphur is not given
4214,4492927,a030ad08-a899-45f3-8fb8-c828f0d620bc,MSC BOSPHORUS,9247742,FR350W,2024-01-13,2024-1-13 10:08,UTC -05:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0847-GB,"Sulphur is not given,Fuel Type or Sulphur will..."
3886,4492098,3362ebed-91e9-4b62-8269-f3e6f9b5a739,MSC ILONA,9225641,UA351A,2024-01-16,2024-1-16 3:45,UTC -05:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,SAME,"Sulphur is not given,BDN is not given"
4396,4493271,63f3dd26-1f0b-4148-badc-642801d8e206,MSC QINGDAO,9256470,ME351W,2024-01-20,2024-1-19 12:45,UTC -05:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,no,BDN is not given
4784,4495362,ed4be9a0-656b-45bc-a5fe-fc662341fde2,LE HAVRE,9307243,MA403A,2024-01-20,2024-1-19 20:00,UTC +01:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,<NA>,"Sulphur is not given,quantity is not given,BDN..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1939,4400557,dcbd0471-2359-4ac3-a338-72f6c00134ab,HERMANN SCHULTE,9535187,NG415W,2024-05-05,2024-5-4 21:00,UTC -04:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,38086,Sulphur is not given
629,4392827,e7d58ff1-a6cf-43b0-81e8-47cfdc055a86,GSL NINGBO,9256482,UL416W,2024-05-04,2024-5-4 8:50,UTC -04:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0,"Sulphur is not given,BDN is not given"
3094,4402379,8a6003d0-b97c-407a-b393-c3e6ad116a93,CAPE SOUNIO,9727625,FI416R,2024-05-06,2024-5-6 8:40,UTC -03:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,11954,Sulphur is not given
1830,4400130,b9e5e972-44d0-4213-a5b6-60681bd0033e,MSC RAVENNA,9484431,IS414B,2024-05-07,2024-5-7 8:05,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,<NA>,"Sulphur is not given,quantity is not given,BDN..."
1946,4400564,a1695f38-5432-4fd1-b96c-10e1b23789be,HERMANN SCHULTE,9535187,NG418E,2024-05-09,2024-5-9 2:04,UTC -05:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,10108338,Sulphur is not given

In [85]:
refl_charter_remarks.to_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\OUTPUT FOR CLIENT\CHARTER MISSING BDNs.xlsx",index = False)

# SORRENTO VESSEL

In [86]:
#sorrento vessel data client given
esi_sorrento

         IMO     Fleet                 Vessel Scrubber
50   9129873  SORRENTO              MSC ALEXA       No
54   9235050  SORRENTO             MSC ALYSSA       No
56   9839480  SORRENTO              MSC AMBRA      Yes
58   9606338  SORRENTO          MSC AMSTERDAM       No
88   9399014  SORRENTO           MSC BEATRICE      Yes
113  9930040  SORRENTO  MSC CELESTINO MARESCA      Yes
119  9708693  SORRENTO              MSC CLARA      Yes
134  9202649  SORRENTO              MSC DIEGO       No
135  9897004  SORRENTO            MSC DILETTA      Yes
159  9279965  SORRENTO           MSC FABIENNE       No
165  9401116  SORRENTO          MSC FRANCESCA      Yes
170  9202663  SORRENTO               MSC GINA       No
177  9647461  SORRENTO            MSC HAMBURG      Yes
195  9606326  SORRENTO           MSC ISTANBUL       No
196  9398371  SORRENTO              MSC IVANA      Yes
204  9966934  SORRENTO              MSC JIANI       No
211  9399026  SORRENTO             MSC KALINA      Yes
214  9467457  SORRENTO              MSC KATIE      Yes
220  9351581  SORRENTO                MSC KIM       No
223  9372470  SORRENTO            MSC KRYSTAL       No
228  9225665  SORRENTO              MSC LAURA      Yes
236  9281279  SORRENTO               MSC LISA       No
238  9606302  SORRENTO             MSC LONDON      Yes
239  9320403  SORRENTO             MSC LORENA       No
242  9230490  SORRENTO            MSC LORETTA      Yes
262  9275971  SORRENTO             MSC MARINA       No
263  9060637  SORRENTO            MSC MARTINA       No
268  9251717  SORRENTO            MSC MAUREEN       No
270  9708679  SORRENTO               MSC MAYA      Yes
272  9226918  SORRENTO            MSC MELISSA      Yes
276  9230488  SORRENTO           MSC MICHAELA      Yes
278  9897016  SORRENTO           MSC MICHELLE      Yes
287  9955789  SORRENTO             MSC NAHARA      Yes
292  9606314  SORRENTO           MSC NEW YORK       No
302  9349825  SORRENTO              MSC NURIA       No
306  9703306  SORRENTO             MSC OLIVER       No
307  9372482  SORRENTO             MSC ORIANE       No
310  9703291  SORRENTO              MSC OSCAR      Yes
319  9279977  SORRENTO            MSC POH LIN       No
326  9290282  SORRENTO            MSC RACHELE       No
331  9754965  SORRENTO               MSC REEF      Yes
332  9202651  SORRENTO             MSC REGINA       No
339  9320453  SORRENTO            MSC ROSARIA       No
375  9404663  SORRENTO              MSC SONIA      Yes
378  9279989  SORRENTO             MSC STELLA      Yes
381  9708681  SORRENTO              MSC SVEVA      Yes
393  9309461  SORRENTO             MSC TOMOKO       No
403  9461439  SORRENTO            MSC VALERIA       No
404  9484467  SORRENTO             MSC VANDYA       No
422  9703318  SORRENTO                MSC ZOE      Yes

In [87]:
esi_sorrento_lst = esi_sorrento['IMO'].to_list()
esi_sorrento_lst

[9129873,
 9235050,
 9839480,
 9606338,
 9399014,
 9930040,
 9708693,
 9202649,
 9897004,
 9279965,
 9401116,
 9202663,
 9647461,
 9606326,
 9398371,
 9966934,
 9399026,
 9467457,
 9351581,
 9372470,
 9225665,
 9281279,
 9606302,
 9320403,
 9230490,
 9275971,
 9060637,
 9251717,
 9708679,
 9226918,
 9230488,
 9897016,
 9955789,
 9606314,
 9349825,
 9703306,
 9372482,
 9703291,
 9279977,
 9290282,
 9754965,
 9202651,
 9320453,
 9404663,
 9279989,
 9708681,
 9309461,
 9461439,
 9484467,
 9703318]

In [88]:
sorrentodata_final = charter[charter['imo'].isin(esi_sorrento_lst)]
sorrentodata_final

,id,gid,vessel_name,imo,voy,corrected_date,report_date_time,report_date_time_offset,report_type,status,...,engine_last_change_user,created_date,created_at,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng
5,4506400,ba391a82-fdb3-4401-9cd2-ca20df7040ee,MSC LAURA,9225665,NI406R,2024-02-06,2024-2-5 20:42,UTC +02:00,COSP,DRIFTING,...,CH. ENG.,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
38,4393381,82aa2941-638a-45fd-8d80-63899150c977,MSC LISA,9281279,CI418R,2024-05-12,2024-5-12 12:00,UTC -03:00,NOON,AT SEA,...,CH.ENG,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
104,4393378,6b2b0274-7f00-4d9a-88c7-78e32af73b06,MSC LISA,9281279,CI418R,2024-05-11,2024-5-11 12:00,UTC -03:00,PORT,IN PORT,...,CH.ENG,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
112,4506401,623249cb-eb0c-4e71-87ed-12de31699833,MSC LAURA,9225665,NI406R,2024-02-06,2024-2-6 12:00,UTC +02:00,NOON,AT SEA,...,CH. ENG.,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
113,4506402,7f25e64f-b8bf-474e-9549-11166ffc9f1f,MSC LAURA,9225665,NI406R,2024-02-07,2024-2-6 15:30,UTC +02:00,EOSP,AT SEA,...,CH. ENG.,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106963,4535440,6fbaeeb8-edbd-4275-95fe-5c0014358f32,MSC LISA,9281279,CI416A,2024-04-28,2024-4-27 14:30,UTC +01:00,SAIL,IN PORT,...,CH.ENG,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
106964,4535441,1ef8bfc8-addb-49c1-8140-cd4513799857,MSC LISA,9281279,CI416A,2024-04-28,2024-4-27 16:18,UTC +01:00,COSP,DRIFTING,...,CH.ENG,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
106965,4535442,8c173712-b377-4c80-89b4-03c0f6e495c3,MSC LISA,9281279,CI416A,2024-04-28,2024-4-28 12:00,UTC +00:00,NOON,AT SEA,...,CH.ENG,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
106966,4535443,6f12a269-f6ee-4f52-a330-9f04ee8347a2,MSC LISA,9281279,CI416A,2024-04-29,2024-4-29 12:00,UTC +00:00,NOON,AT SEA,...,CH.ENG,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
106967,4535444,bb75437e-c1cd-47c8-82a8-3e7680a6223e,MSC LISA,9281279,CI416A,2024-04-30,2024-4-30 12:00,UTC -01:00,NOON,AT SEA,...,CH.ENG,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0

In [89]:
sorrentodata_final['imo'].nunique()

50

In [90]:
esi_sorrento['IMO'].nunique()

50

In [91]:
lst_sorrento = sorrentodata_final['imo'].unique().tolist()

In [92]:
res_lst = []
for element in esi_sorrento_lst:
    if element not in lst_sorrento:
        res_lst.append(element)
res_lst

[]

# FILLING PORT_DELIVERY

In [93]:
sorrentodata_final.columns.to_list()

['id',
 'gid',
 'vessel_name',
 'imo',
 'voy',
 'corrected_date',
 'report_date_time',
 'report_date_time_offset',
 'report_type',
 'status',
 'latitude',
 'longitude',
 'm_e_foc',
 'cargo_total',
 'has_cargo',
 'steaming_time',
 'total_m_e_hours_fuel_only',
 'miles_by_gps',
 'oil_cyl',
 'speed_by_log',
 'speed_by_gps',
 'rpm',
 'slip',
 'wind_direction',
 'wind_speed',
 'draft_aft',
 'draft_fwd',
 'displacement',
 'course_at_sea',
 'wave_height',
 'sea_direction',
 'cargo_total_teu',
 'ambient_temp',
 'sw_temp',
 'miles_by_speed_log',
 'eta_port_code',
 'eta_date_time',
 'eta_date_time_offset',
 'eta_port',
 'time_change',
 'time_sea',
 'temp_min',
 'temp_max',
 'requested_speed',
 'rem_dist_to_pilot',
 'rem_time_to_pilot',
 'total_unplnd_stpge_tech',
 'total_unplnd_stpge_ope_wx',
 'reefers_positive_plugged',
 'reefers_negative_plugged',
 'me_total_revs_counter',
 'port_code',
 'port',
 'aux_blowers_on',
 'hold_ventilation_on',
 'since_date_time',
 'since_date_time_offset',
 'time_hrs_anchor',
 'time_hrs_drift',
 'reason',
 'type_of_delay',
 'etb_date_time',
 'etb_date_time_offset',
 'pilot_date_time',
 'pilot_date_time_offset',
 'time_manoeuvring',
 'tug_arr',
 'tug_shift',
 'etd_date_time',
 'etd_date_time_offset',
 'shift_berth_hours',
 'cargo_disch',
 'teu_full',
 'teu_empty',
 'bilge_removed',
 'garbage_removed',
 'garbage_remvl_reqstd',
 'garbage_remvl_cmplsry',
 'fw_supply',
 'cy_crew_signed_on',
 'cy_crew_signed_off',
 'cy_doctors_visit',
 'cy_mail_received_ref_no',
 'cy_lub_oil_sample_landed',
 'cy_checkd_for_stowaways',
 'cy_stowaways_on_board',
 'cy_dep_gm_mtr',
 'cy_requisitions_received',
 'distance_to_next_pilot',
 'tug_sailing_transit',
 'steaming_time_m_e_rsdl_vls',
 'steaming_time_m_e_rsdl_hs',
 'steaming_time_m_e_rsdl_uls',
 'steaming_time_m_e_dstlt_vls',
 'steaming_time_m_e_dstlt_uls',
 'steaming_time_m_e_tnktnr_dstlt_vls',
 'steaming_time_m_e_hs',
 'steaming_time_m_e_ls',
 'steaming_time_m_e_mdo',
 'steaming_time_m_e_mgo',
 'steaming_time_m_e_mgo_ls',
 'steaming_time_aux_1',
 'steaming_time_aux_2',
 'steaming_time_aux_3',
 'steaming_time_aux_4',
 'steaming_time_aux_5',
 'steaming_time_sh_gen',
 'steaming_time_tg',
 'power_kw',
 'steaming_load_kw_aux_1',
 'steaming_load_kw_aux_2',
 'steaming_load_kw_aux_3',
 'steaming_load_kw_aux_4',
 'steaming_load_kw_aux_5',
 'steaming_load_kw_sh_gen',
 'steaming_load_kw_tg',
 'fuel_m_e_rsdl_vls',
 'fuel_m_e_rsdl_hs',
 'fuel_m_e_rsdl_uls',
 'fuel_m_e_dstlt_vls',
 'fuel_m_e_dstlt_uls',
 'fuel_m_e_tnktnr_dstlt_vls',
 'fuel_m_e_hs',
 'fuel_m_e_ls',
 'fuel_m_e_mdo',
 'fuel_m_e_mgo',
 'fuel_m_e_mgo_ls',
 'fuel_aux_rsdl_vls',
 'fuel_aux_rsdl_hs',
 'fuel_aux_rsdl_uls',
 'fuel_aux_dstlt_vls',
 'fuel_aux_dstlt_uls',
 'fuel_aux_tnktnr_dstlt_vls',
 'fuel_aux_hs',
 'fuel_aux_ls',
 'fuel_aux_mdo',
 'fuel_aux_mgo',
 'fuel_aux_mgo_ls',
 'fuel_boiler_rsdl_vls',
 'fuel_boiler_rsdl_hs',
 'fuel_boiler_rsdl_uls',
 'fuel_boiler_dstlt_vls',
 'fuel_boiler_dstlt_uls',
 'fuel_boiler_tnktnr_dstlt_vls',
 'fuel_boiler_hs',
 'fuel_boiler_ls',
 'fuel_boiler_mdo',
 'fuel_boiler_mgo',
 'fuel_boiler_mgo_ls',
 'deck_last_change_user',
 'deck_part_is_complete',
 'engine_part_is_complete',
 'scavenge_pressure',
 'seca_entry_time',
 'seca_entry_lat',
 'seca_entry_long',
 'rob_fresh_water',
 'manvrng_miles_by_gps',
 'manvrng_miles_by_speed_log',
 'tanktainer_transfd_quantity',
 'pilot_taken',
 'date_time_start_transit',
 'date_time_start_transit_offset',
 'date_time_end_transit',
 'date_time_end_transit_offset',
 'ballast',
 'tanktainer_number',
 'steaming_kwhr_total',
 'cy_others',
 'rob_fo_sludge',
 'rob_lo_sludge',
 'rob_bilge',
 'sludge_removed_fo',
 'sludge_removed_lo',
 'sea_state',
 'cy_lub_added_to_system_mecc',
 'cy_lub_added_to_system_aecc',
 'cy_lub_added_to_thrusters',
 'cy_me_lo_purifier_in_use',
 'cy_ballast',
 'cy_bending_moment',
 'cy_shearing_force',
 'cy_tortion_moment',
 'cy_supdt_auditor_signed_on',
 'cy_supdt_auditor_signed_off',
 'cy_cash_received',
 'cy_lub_oil_received_mecyl',
 'cy_lub_oil_received_mecc',
 'cy_lub_oil_received_aecc',
 'cy_m_e_under_piston_temp',
 'cy_mail_received',
 'wind_direction_port_stbd',
 'sea_direction_port_stbd',
 'time_pilot_onboard',
 'grades_rob',
 'bunker_order',
 'remarks',
 'fuel_type',
 'carbon_factor',
 'so_2_co_2_ratio',
 'sulphur_content_pc',
 'quantity',
 'port_delivery',
 'product_quality',
 'tanktainer_number_1',
 'supplier',
 'delivery',
 'vol_lt',
 'den',
 'vis',
 'fuel_hs',
 'fuel_ls',
 'fuel_mdo',
 'fuel_mgo',
 'fuel_mgo_ls',
 'bdn',
 'rob_dstlt_uls',
 'rob_dstlt_vls',
 'rob_rsdl_mdo',
 'rob_tnktnr_dstlt_vls',
 'rob_rsdl_vls',
 'rob_rsdl_hs',
 'rob_rsdl_uls',
 'rob_fuel_hsfo',
 'rob_fuel_lsfo',
 'rob_fuel_mdo',
 'rob_fuel_mgo',
 'rob_fuel_mgo_ls',
 'rob_fuel_tanktainer_mgo',
 'eca_miles',
 'eca_time',
 'egcs_dry_waste_removed',
 'egcs_running_time',
 'egcs_wet_slurry_removed',
 'egcs_open_loop_running_time',
 'egcs_closed_loop_running_time',
 'updated_date',
 'fuel_rsdl_hs',
 'fuel_rsdl_vls',
 'fuel_rsdl_uls',
 'fuel_dstlt_vls',
 'fuel_dstlt_uls',
 'fuel_tnktnr_dstlt_vls',
 'cargo_load',
 'seca_exit_time',
 'seca_exit_lat',
 'seca_exit_long',
 'engine_last_change_user',
 'created_date',
 'created_at',
 'updated_at',
 'created_by_id',
 'updated_by_id',
 'fuel_m_e_lng',
 'fuel_aux_lng',
 'fuel_boiler_lng',
 'rob_boiler_lng']

In [94]:
sorrentodata_final['port_delivery'] = sorrentodata_final['port_delivery'].fillna(sorrentodata_final['port_code'])
sorrentodata_final

,id,gid,vessel_name,imo,voy,corrected_date,report_date_time,report_date_time_offset,report_type,status,...,engine_last_change_user,created_date,created_at,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng
5,4506400,ba391a82-fdb3-4401-9cd2-ca20df7040ee,MSC LAURA,9225665,NI406R,2024-02-06,2024-2-5 20:42,UTC +02:00,COSP,DRIFTING,...,CH. ENG.,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
38,4393381,82aa2941-638a-45fd-8d80-63899150c977,MSC LISA,9281279,CI418R,2024-05-12,2024-5-12 12:00,UTC -03:00,NOON,AT SEA,...,CH.ENG,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
104,4393378,6b2b0274-7f00-4d9a-88c7-78e32af73b06,MSC LISA,9281279,CI418R,2024-05-11,2024-5-11 12:00,UTC -03:00,PORT,IN PORT,...,CH.ENG,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
112,4506401,623249cb-eb0c-4e71-87ed-12de31699833,MSC LAURA,9225665,NI406R,2024-02-06,2024-2-6 12:00,UTC +02:00,NOON,AT SEA,...,CH. ENG.,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
113,4506402,7f25e64f-b8bf-474e-9549-11166ffc9f1f,MSC LAURA,9225665,NI406R,2024-02-07,2024-2-6 15:30,UTC +02:00,EOSP,AT SEA,...,CH. ENG.,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106963,4535440,6fbaeeb8-edbd-4275-95fe-5c0014358f32,MSC LISA,9281279,CI416A,2024-04-28,2024-4-27 14:30,UTC +01:00,SAIL,IN PORT,...,CH.ENG,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
106964,4535441,1ef8bfc8-addb-49c1-8140-cd4513799857,MSC LISA,9281279,CI416A,2024-04-28,2024-4-27 16:18,UTC +01:00,COSP,DRIFTING,...,CH.ENG,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
106965,4535442,8c173712-b377-4c80-89b4-03c0f6e495c3,MSC LISA,9281279,CI416A,2024-04-28,2024-4-28 12:00,UTC +00:00,NOON,AT SEA,...,CH.ENG,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
106966,4535443,6f12a269-f6ee-4f52-a330-9f04ee8347a2,MSC LISA,9281279,CI416A,2024-04-29,2024-4-29 12:00,UTC +00:00,NOON,AT SEA,...,CH.ENG,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
106967,4535444,bb75437e-c1cd-47c8-82a8-3e7680a6223e,MSC LISA,9281279,CI416A,2024-04-30,2024-4-30 12:00,UTC -01:00,NOON,AT SEA,...,CH.ENG,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0

In [95]:
values_to_replace = ['NULL', '<N_A>']
sorrentodata_final['port_delivery'] = sorrentodata_final['port_delivery'].replace(values_to_replace, np.nan)
sorrentodata_final[sorrentodata_final['port_delivery'] == '<N/A>']

Empty DataFrame
Columns: [id, gid, vessel_name, imo, voy, corrected_date, report_date_time, report_date_time_offset, report_type, status, latitude, longitude, m_e_foc, cargo_total, has_cargo, steaming_time, total_m_e_hours_fuel_only, miles_by_gps, oil_cyl, speed_by_log, speed_by_gps, rpm, slip, wind_direction, wind_speed, draft_aft, draft_fwd, displacement, course_at_sea, wave_height, sea_direction, cargo_total_teu, ambient_temp, sw_temp, miles_by_speed_log, eta_port_code, eta_date_time, eta_date_time_offset, eta_port, time_change, time_sea, temp_min, temp_max, requested_speed, rem_dist_to_pilot, rem_time_to_pilot, total_unplnd_stpge_tech, total_unplnd_stpge_ope_wx, reefers_positive_plugged, reefers_negative_plugged, me_total_revs_counter, port_code, port, aux_blowers_on, hold_ventilation_on, since_date_time, since_date_time_offset, time_hrs_anchor, time_hrs_drift, reason, type_of_delay, etb_date_time, etb_date_time_offset, pilot_date_time, pilot_date_time_offset, time_manoeuvring, tug_arr, tug_shift, etd_date_time, etd_date_time_offset, shift_berth_hours, cargo_disch, teu_full, teu_empty, bilge_removed, garbage_removed, garbage_remvl_reqstd, garbage_remvl_cmplsry, fw_supply, cy_crew_signed_on, cy_crew_signed_off, cy_doctors_visit, cy_mail_received_ref_no, cy_lub_oil_sample_landed, cy_checkd_for_stowaways, cy_stowaways_on_board, cy_dep_gm_mtr, cy_requisitions_received, distance_to_next_pilot, tug_sailing_transit, steaming_time_m_e_rsdl_vls, steaming_time_m_e_rsdl_hs, steaming_time_m_e_rsdl_uls, steaming_time_m_e_dstlt_vls, steaming_time_m_e_dstlt_uls, steaming_time_m_e_tnktnr_dstlt_vls, steaming_time_m_e_hs, steaming_time_m_e_ls, steaming_time_m_e_mdo, steaming_time_m_e_mgo, ...]
Index: []

[0 rows x 257 columns]

In [96]:
sorrentodata_final[['port_code','port_delivery']]

       port_code port_delivery
5          ILHFA         ILHFA
38         CAHAL         CAHAL
104        CAHAL         CAHAL
112        ILHFA         ILHFA
113        EGDAM         EGDAM
...          ...           ...
106963     PTSIE         PTSIE
106964     PTSIE         PTSIE
106965     PTSIE         PTSIE
106966     PTSIE         PTSIE
106967     PTSIE         PTSIE

[12813 rows x 2 columns]

In [97]:
sorrentodata_final = sorrentodata_final.sort_values(['report_date_time'])
sorrentodata_final['port_delivery'] = sorrentodata_final.groupby(['imo'])['port_delivery'].transform(lambda v: v.ffill())
sorrentodata_final['port_delivery'] = sorrentodata_final.groupby(['imo'])['port_delivery'].transform(lambda v: v.bfill())
sorrentodata_final

,id,gid,vessel_name,imo,voy,corrected_date,report_date_time,report_date_time_offset,report_type,status,...,engine_last_change_user,created_date,created_at,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng
52945,4493570,3bc7c682-dd86-467e-b2ed-4170389b767e,MSC FABIENNE,9279965,XA351A,2024-01-01,2024-1-1 12:00,UTC +03:00,NOON,AT SEA,...,Ch.Engineer,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
53098,4493723,4ec78e3d-3ad3-4482-8a36-746b8c4d3c00,MSC STELLA,9279989,NG350E,2024-01-01,2024-1-1 12:00,UTC -05:00,NOON,AT SEA,...,Chief Engineer,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
68316,4501439,d974daaa-d1cc-4ae6-b4e6-5accd215d6c6,MSC AMSTERDAM,9606338,QJ348S,2024-01-01,2024-1-1 12:00,UTC +08:00,DLY A,DRIFTING,...,Ch. Eng,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
56169,4494226,2b99983f-10a5-4772-946d-ac2590a781b7,MSC RACHELE,9290282,ME351E,2024-01-01,2024-1-1 12:00,UTC -05:00,PORT,IN PORT,...,Chief Engineer,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
51140,4491756,a7eee58b-29b7-42c8-ba2e-0c64b16d19f3,MSC REGINA,9202651,OM347A,2024-01-01,2024-1-1 12:00,UTC +03:00,DLY A,DRIFTING,...,CHENG,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1750,4393313,f3a7859c-d65c-4fea-9969-b9782d7fa138,MSC STELLA,9279989,NG417W,2024-05-09,2024-5-9 6:18,UTC -04:00,BRTH,DRIFTING,...,CH.ENG,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
10359,4392294,47e09aad-b939-4da2-b4d1-6ae49cb91e46,MSC ALYSSA,9235050,CX418A,2024-05-09,2024-5-9 8:00,UTC +02:00,EOSP,AT SEA,...,CH ENG,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
10360,4392295,1f440b50-f542-4097-8026-0a08f7561b94,MSC ALYSSA,9235050,CX418A,2024-05-09,2024-5-9 8:06,UTC +02:00,DLY A,DRIFTING,...,CH ENG,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
13379,4402098,00bee91c-8fdb-41b7-a1f2-70fa911ed3d7,MSC MAYA,9708679,FT407E,2024-05-09,2024-5-9 8:30,UTC +08:00,BRTH,DRIFTING,...,CH.ENG,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
5763,4399043,6ca41997-8846-4b4f-a853-c8ba238006d6,MSC VALERIA,9461439,FY416R,2024-05-09,2024-5-9 8:30,UTC +00:00,SAIL,IN PORT,...,CH.ENG.,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0

In [98]:
sorrentodata_final = sorrentodata_final.sort_values(['report_date_time'])
sorrentodata_final['port_delivery'] = sorrentodata_final.groupby(['imo'])['port_delivery'].transform(lambda v: v.ffill())
sorrentodata_final['port_delivery'] = sorrentodata_final.groupby(['imo'])['port_delivery'].transform(lambda v: v.bfill())
sorrentodata_final

,id,gid,vessel_name,imo,voy,corrected_date,report_date_time,report_date_time_offset,report_type,status,...,engine_last_change_user,created_date,created_at,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng
52945,4493570,3bc7c682-dd86-467e-b2ed-4170389b767e,MSC FABIENNE,9279965,XA351A,2024-01-01,2024-1-1 12:00,UTC +03:00,NOON,AT SEA,...,Ch.Engineer,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
58993,4497748,7bfc7956-a4db-49c9-b0c2-215bb701301e,MSC IVANA,9398371,FW351W,2024-01-01,2024-1-1 12:00,UTC +08:00,NOON,AT SEA,...,Chief Eng,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
58239,4496996,1ad5324f-0a87-4f13-87bc-c90482ea0cee,MSC NURIA,9349825,NK349R,2024-01-01,2024-1-1 12:00,UTC +00:00,DLY A,DRIFTING,...,Ch. Eng. Pul Zarko,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
61828,4502410,4834cd9a-b51d-410d-9872-b5480c66494e,MSC MAYA,9708679,FT347E,2024-01-01,2024-1-1 12:00,UTC +08:00,NOON,AT SEA,...,Ch.Eng,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
59231,4497985,7613834f-813b-4639-9bd4-c0df07a7f18c,MSC BEATRICE,9399014,ZF349A,2024-01-01,2024-1-1 12:00,UTC +05:30,NOON,AT SEA,...,CHIEF ENGINEER,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1750,4393313,f3a7859c-d65c-4fea-9969-b9782d7fa138,MSC STELLA,9279989,NG417W,2024-05-09,2024-5-9 6:18,UTC -04:00,BRTH,DRIFTING,...,CH.ENG,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
10359,4392294,47e09aad-b939-4da2-b4d1-6ae49cb91e46,MSC ALYSSA,9235050,CX418A,2024-05-09,2024-5-9 8:00,UTC +02:00,EOSP,AT SEA,...,CH ENG,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
10360,4392295,1f440b50-f542-4097-8026-0a08f7561b94,MSC ALYSSA,9235050,CX418A,2024-05-09,2024-5-9 8:06,UTC +02:00,DLY A,DRIFTING,...,CH ENG,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
13379,4402098,00bee91c-8fdb-41b7-a1f2-70fa911ed3d7,MSC MAYA,9708679,FT407E,2024-05-09,2024-5-9 8:30,UTC +08:00,BRTH,DRIFTING,...,CH.ENG,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
5763,4399043,6ca41997-8846-4b4f-a853-c8ba238006d6,MSC VALERIA,9461439,FY416R,2024-05-09,2024-5-9 8:30,UTC +00:00,SAIL,IN PORT,...,CH.ENG.,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0

In [99]:
sorrentodata_final['port_delivery'].isna().sum()

0

In [100]:
sorrentodata_final.to_csv('sorrentodata_final.csv')

# Adding remarks column

In [101]:
#use python remarks function next
def remark(data1):
    r1 = data1[data1['sulphur_content_pc']==0]
    r1['Remarks'] = "Sulphur is not given"
    hs_data = data1[data1['fuel_type']=='RESIDUAL HS']
    r2 = hs_data[(hs_data['sulphur_content_pc']<0.5) | (hs_data['sulphur_content_pc']>3.5) ]
    r2['Remarks'] = "Fuel Type or Sulphur will be wrong"
    ls_data = data1[(data1['fuel_type']=='RESIDUAL VLS') | (data1['fuel_type']=='DISTILLATE ULS')| (data1['fuel_type']=='DISTILLATE VLS') | (data1['fuel_type']=='RESIDUAL ULS')  | (data1['fuel_type']=='TANKTAINER DISTILLATE VLS')]
    r3 = ls_data[(ls_data['sulphur_content_pc']<0) | (ls_data['sulphur_content_pc']>0.5) ]
    r3['Remarks'] = "Fuel Type or Sulphur will be wrong"
    r4 = data1[data1['sulphur_content_pc'].isnull()]
    r4['Remarks'] = "Sulphur is not given"
    r5 = data1[data1['quantity']<=0]
    r5['Remarks'] = "quantity is not given"
    r6 = data1[data1['quantity'].isnull()]
    r6['Remarks'] = "quantity is not given"
    r7 = data1[data1['delivery'].isnull()]
    r7['Remarks'] = "BDN is not given"
    data1["joinall"]= data1['delivery'].str.replace(r'[-_\s.,/]+', '')
    data1["is_alpha_delivery"]= data1["joinall"].str.isalpha()
    r8 = data1[data1['is_alpha_delivery']==True]
    r8['Remarks'] = "BDN is not given"
    r9 = data1[data1['delivery']=='0']
    r9['Remarks'] = "BDN is not given"
    df = pd.concat([r1,r2,r3,r4,r5,r6,r7,r8,r9])
    df.drop('is_alpha_delivery', axis=1, inplace=True)
    df.drop('joinall', axis=1, inplace=True)
    p = df.groupby('gid')['Remarks'].agg(','.join).reset_index()
    dict_remarks = pd.Series(p['Remarks'].values,index=p['gid']).to_dict()
    import numpy as np
    df['REMARKS'] = np.nan
    df['REMARKS'] = df['REMARKS'].fillna(df['gid'].apply(lambda x:dict_remarks.get(x)))
    df.drop('Remarks', axis=1, inplace=True)
    df.drop_duplicates(keep='first',inplace=True)
    return df

In [102]:
output = remark(sorrentodata_final)
output

,id,gid,vessel_name,imo,voy,corrected_date,report_date_time,report_date_time_offset,report_type,status,...,created_date,created_at,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng,REMARKS
53111,4493736,6fc57f78-723e-402b-9d36-98c208da040c,MSC STELLA,9279989,NG350E,2024-01-13,2024-1-12 19:50,UTC +01:00,REFL,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,Sulphur is not given
51930,4492546,a01618bc-bb31-4683-9932-78494d4c4439,MSC MELISSA,9226918,OW401R,2024-01-12,2024-1-12 3:20,UTC +00:00,REFL,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,Sulphur is not given
51929,4492545,63990e38-0431-4812-89ed-1de09f021d35,MSC MELISSA,9226918,OW401R,2024-01-12,2024-1-12 3:20,UTC +00:00,REFL,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,Sulphur is not given
68234,4501357,b027b770-e743-4ba4-89e9-f1f0a1430e91,MSC NEW YORK,9606314,QJ350S,2024-01-12,2024-1-12 6:45,UTC +09:00,REFL,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,Sulphur is not given
51110,4491726,40834d6f-1661-4f5b-9480-9cbeafd162d7,MSC DIEGO,9202649,OM352A,2024-01-09,2024-1-8 14:25,UTC +05:30,REFL,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,Sulphur is not given
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1851,4393419,aae25f7a-fe3a-46ff-b49d-6b02d555e268,MSC LISA,9281279,CI421A,2024-05-30,2024-5-30 8:54,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,BDN is not given
75719,4507718,abbe3849-08c6-4054-829c-29332e999624,MSC FABIENNE,9279965,NT404A,2024-02-02,2024-2-1 18:20,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,BDN is not given
96825,4537500,971f8b08-a873-4d82-b90c-6bcecda6b50e,MSC ROSARIA,9320453,MX416R,2024-04-25,2024-4-24 15:35,UTC -04:00,REFL,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,BDN is not given
3460,4396851,2ecd8b7b-9867-4d54-98fb-85671f26e139,MSC ORIANE,9372482,MX420R,2024-05-24,2024-5-23 18:35,UTC -04:00,REFL,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,BDN is not given
65172,4505963,97d6856c-4261-4a11-977a-e3891514cde1,MSC REGINA,9202651,OM401R,2024-02-21,2024-2-20 22:20,UTC +04:00,REFL,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,BDN is not given

In [103]:
dict_remark = pd.Series(output['REMARKS'].values,index=output['gid']).to_dict()
import numpy as np
sorrentodata_final['REMARKS'] = np.nan
sorrentodata_final['REMARKS'] = sorrentodata_final['REMARKS'].fillna(sorrentodata_final['gid'].apply(lambda x:dict_remark.get(x)))
sorrentodata_final

,id,gid,vessel_name,imo,voy,corrected_date,report_date_time,report_date_time_offset,report_type,status,...,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng,joinall,is_alpha_delivery,REMARKS
52945,4493570,3bc7c682-dd86-467e-b2ed-4170389b767e,MSC FABIENNE,9279965,XA351A,2024-01-01,2024-1-1 12:00,UTC +03:00,NOON,AT SEA,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
58993,4497748,7bfc7956-a4db-49c9-b0c2-215bb701301e,MSC IVANA,9398371,FW351W,2024-01-01,2024-1-1 12:00,UTC +08:00,NOON,AT SEA,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
58239,4496996,1ad5324f-0a87-4f13-87bc-c90482ea0cee,MSC NURIA,9349825,NK349R,2024-01-01,2024-1-1 12:00,UTC +00:00,DLY A,DRIFTING,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
61828,4502410,4834cd9a-b51d-410d-9872-b5480c66494e,MSC MAYA,9708679,FT347E,2024-01-01,2024-1-1 12:00,UTC +08:00,NOON,AT SEA,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
59231,4497985,7613834f-813b-4639-9bd4-c0df07a7f18c,MSC BEATRICE,9399014,ZF349A,2024-01-01,2024-1-1 12:00,UTC +05:30,NOON,AT SEA,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1750,4393313,f3a7859c-d65c-4fea-9969-b9782d7fa138,MSC STELLA,9279989,NG417W,2024-05-09,2024-5-9 6:18,UTC -04:00,BRTH,DRIFTING,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
10359,4392294,47e09aad-b939-4da2-b4d1-6ae49cb91e46,MSC ALYSSA,9235050,CX418A,2024-05-09,2024-5-9 8:00,UTC +02:00,EOSP,AT SEA,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
10360,4392295,1f440b50-f542-4097-8026-0a08f7561b94,MSC ALYSSA,9235050,CX418A,2024-05-09,2024-5-9 8:06,UTC +02:00,DLY A,DRIFTING,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
13379,4402098,00bee91c-8fdb-41b7-a1f2-70fa911ed3d7,MSC MAYA,9708679,FT407E,2024-05-09,2024-5-9 8:30,UTC +08:00,BRTH,DRIFTING,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."
5763,4399043,6ca41997-8846-4b4f-a853-c8ba238006d6,MSC VALERIA,9461439,FY416R,2024-05-09,2024-5-9 8:30,UTC +00:00,SAIL,IN PORT,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN..."

In [107]:
sorrentodata_final.drop('is_alpha_Delivery', axis=1, inplace=True)
sorrentodata_final.drop('joinall', axis=1, inplace=True)
sorrentodata_final

KeyError: "['is_alpha_Delivery'] not found in axis"

In [108]:
#changes to Delivery column - > MANUALLY CHECK ALL PROBLEMS IN DELIVERY COLUMN

# 1.if deelivery column having 0 or multiple 0 then Remarks updated as 'BDN not given'
# 2.if 'BDN' comes first or last ,then remove 'BDN'
# 3. if '.' is comes at last , then remove it
# 4. if '.' comes in between , then change it to underscore
# 5. if * and _ comes last or first ,it can be removed using following function

In [109]:
#if delivery column starts or ends with underscore(_ and *)
def delivery_modification(sorrentodata_final):
    sorrentodata_final["delivery"] = sorrentodata_final["delivery"].astype('string')
    sorrentodata_final_nan = sorrentodata_final[sorrentodata_final['delivery'].isna()]
    sorrentodata_final_nan_gid_list = list(sorrentodata_final_nan['gid'])
    sorrentodata_final_not_nan = sorrentodata_final[~sorrentodata_final['gid'].isin(sorrentodata_final_nan_gid_list)]
    sorrentodata_final_not_nan["delivery"] = sorrentodata_final_not_nan["delivery"].apply(lambda x: x.strip("_*"))
    sorrentodata_final_delivery_concat = pd.concat([sorrentodata_final_not_nan,sorrentodata_final_nan])
    sorrentodata_final = sorrentodata_final.drop(['delivery'], axis=1)
    dict_noon_delivery = pd.Series(sorrentodata_final_delivery_concat['delivery'].values,index=sorrentodata_final_delivery_concat['gid']).to_dict()
    sorrentodata_final['delivery'] = np.nan
    sorrentodata_final['delivery'] = sorrentodata_final['delivery'].fillna(sorrentodata_final['gid'].apply(lambda x:dict_noon_delivery.get(x)))
    return sorrentodata_final

In [110]:
sorrentodata_final = delivery_modification(sorrentodata_final)
sorrentodata_final

,id,gid,vessel_name,imo,voy,corrected_date,report_date_time,report_date_time_offset,report_type,status,...,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng,joinall,is_alpha_delivery,REMARKS,delivery
52945,4493570,3bc7c682-dd86-467e-b2ed-4170389b767e,MSC FABIENNE,9279965,XA351A,2024-01-01,2024-1-1 12:00,UTC +03:00,NOON,AT SEA,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",<NA>
58993,4497748,7bfc7956-a4db-49c9-b0c2-215bb701301e,MSC IVANA,9398371,FW351W,2024-01-01,2024-1-1 12:00,UTC +08:00,NOON,AT SEA,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",<NA>
58239,4496996,1ad5324f-0a87-4f13-87bc-c90482ea0cee,MSC NURIA,9349825,NK349R,2024-01-01,2024-1-1 12:00,UTC +00:00,DLY A,DRIFTING,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",<NA>
61828,4502410,4834cd9a-b51d-410d-9872-b5480c66494e,MSC MAYA,9708679,FT347E,2024-01-01,2024-1-1 12:00,UTC +08:00,NOON,AT SEA,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",<NA>
59231,4497985,7613834f-813b-4639-9bd4-c0df07a7f18c,MSC BEATRICE,9399014,ZF349A,2024-01-01,2024-1-1 12:00,UTC +05:30,NOON,AT SEA,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1750,4393313,f3a7859c-d65c-4fea-9969-b9782d7fa138,MSC STELLA,9279989,NG417W,2024-05-09,2024-5-9 6:18,UTC -04:00,BRTH,DRIFTING,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",<NA>
10359,4392294,47e09aad-b939-4da2-b4d1-6ae49cb91e46,MSC ALYSSA,9235050,CX418A,2024-05-09,2024-5-9 8:00,UTC +02:00,EOSP,AT SEA,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",<NA>
10360,4392295,1f440b50-f542-4097-8026-0a08f7561b94,MSC ALYSSA,9235050,CX418A,2024-05-09,2024-5-9 8:06,UTC +02:00,DLY A,DRIFTING,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",<NA>
13379,4402098,00bee91c-8fdb-41b7-a1f2-70fa911ed3d7,MSC MAYA,9708679,FT407E,2024-05-09,2024-5-9 8:30,UTC +08:00,BRTH,DRIFTING,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",<NA>
5763,4399043,6ca41997-8846-4b4f-a853-c8ba238006d6,MSC VALERIA,9461439,FY416R,2024-05-09,2024-5-9 8:30,UTC +00:00,SAIL,IN PORT,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",<NA>

In [111]:
sorrentodata_final.columns.to_list()

['id',
 'gid',
 'vessel_name',
 'imo',
 'voy',
 'corrected_date',
 'report_date_time',
 'report_date_time_offset',
 'report_type',
 'status',
 'latitude',
 'longitude',
 'm_e_foc',
 'cargo_total',
 'has_cargo',
 'steaming_time',
 'total_m_e_hours_fuel_only',
 'miles_by_gps',
 'oil_cyl',
 'speed_by_log',
 'speed_by_gps',
 'rpm',
 'slip',
 'wind_direction',
 'wind_speed',
 'draft_aft',
 'draft_fwd',
 'displacement',
 'course_at_sea',
 'wave_height',
 'sea_direction',
 'cargo_total_teu',
 'ambient_temp',
 'sw_temp',
 'miles_by_speed_log',
 'eta_port_code',
 'eta_date_time',
 'eta_date_time_offset',
 'eta_port',
 'time_change',
 'time_sea',
 'temp_min',
 'temp_max',
 'requested_speed',
 'rem_dist_to_pilot',
 'rem_time_to_pilot',
 'total_unplnd_stpge_tech',
 'total_unplnd_stpge_ope_wx',
 'reefers_positive_plugged',
 'reefers_negative_plugged',
 'me_total_revs_counter',
 'port_code',
 'port',
 'aux_blowers_on',
 'hold_ventilation_on',
 'since_date_time',
 'since_date_time_offset',
 'time_hrs_anchor',
 'time_hrs_drift',
 'reason',
 'type_of_delay',
 'etb_date_time',
 'etb_date_time_offset',
 'pilot_date_time',
 'pilot_date_time_offset',
 'time_manoeuvring',
 'tug_arr',
 'tug_shift',
 'etd_date_time',
 'etd_date_time_offset',
 'shift_berth_hours',
 'cargo_disch',
 'teu_full',
 'teu_empty',
 'bilge_removed',
 'garbage_removed',
 'garbage_remvl_reqstd',
 'garbage_remvl_cmplsry',
 'fw_supply',
 'cy_crew_signed_on',
 'cy_crew_signed_off',
 'cy_doctors_visit',
 'cy_mail_received_ref_no',
 'cy_lub_oil_sample_landed',
 'cy_checkd_for_stowaways',
 'cy_stowaways_on_board',
 'cy_dep_gm_mtr',
 'cy_requisitions_received',
 'distance_to_next_pilot',
 'tug_sailing_transit',
 'steaming_time_m_e_rsdl_vls',
 'steaming_time_m_e_rsdl_hs',
 'steaming_time_m_e_rsdl_uls',
 'steaming_time_m_e_dstlt_vls',
 'steaming_time_m_e_dstlt_uls',
 'steaming_time_m_e_tnktnr_dstlt_vls',
 'steaming_time_m_e_hs',
 'steaming_time_m_e_ls',
 'steaming_time_m_e_mdo',
 'steaming_time_m_e_mgo',
 'steaming_time_m_e_mgo_ls',
 'steaming_time_aux_1',
 'steaming_time_aux_2',
 'steaming_time_aux_3',
 'steaming_time_aux_4',
 'steaming_time_aux_5',
 'steaming_time_sh_gen',
 'steaming_time_tg',
 'power_kw',
 'steaming_load_kw_aux_1',
 'steaming_load_kw_aux_2',
 'steaming_load_kw_aux_3',
 'steaming_load_kw_aux_4',
 'steaming_load_kw_aux_5',
 'steaming_load_kw_sh_gen',
 'steaming_load_kw_tg',
 'fuel_m_e_rsdl_vls',
 'fuel_m_e_rsdl_hs',
 'fuel_m_e_rsdl_uls',
 'fuel_m_e_dstlt_vls',
 'fuel_m_e_dstlt_uls',
 'fuel_m_e_tnktnr_dstlt_vls',
 'fuel_m_e_hs',
 'fuel_m_e_ls',
 'fuel_m_e_mdo',
 'fuel_m_e_mgo',
 'fuel_m_e_mgo_ls',
 'fuel_aux_rsdl_vls',
 'fuel_aux_rsdl_hs',
 'fuel_aux_rsdl_uls',
 'fuel_aux_dstlt_vls',
 'fuel_aux_dstlt_uls',
 'fuel_aux_tnktnr_dstlt_vls',
 'fuel_aux_hs',
 'fuel_aux_ls',
 'fuel_aux_mdo',
 'fuel_aux_mgo',
 'fuel_aux_mgo_ls',
 'fuel_boiler_rsdl_vls',
 'fuel_boiler_rsdl_hs',
 'fuel_boiler_rsdl_uls',
 'fuel_boiler_dstlt_vls',
 'fuel_boiler_dstlt_uls',
 'fuel_boiler_tnktnr_dstlt_vls',
 'fuel_boiler_hs',
 'fuel_boiler_ls',
 'fuel_boiler_mdo',
 'fuel_boiler_mgo',
 'fuel_boiler_mgo_ls',
 'deck_last_change_user',
 'deck_part_is_complete',
 'engine_part_is_complete',
 'scavenge_pressure',
 'seca_entry_time',
 'seca_entry_lat',
 'seca_entry_long',
 'rob_fresh_water',
 'manvrng_miles_by_gps',
 'manvrng_miles_by_speed_log',
 'tanktainer_transfd_quantity',
 'pilot_taken',
 'date_time_start_transit',
 'date_time_start_transit_offset',
 'date_time_end_transit',
 'date_time_end_transit_offset',
 'ballast',
 'tanktainer_number',
 'steaming_kwhr_total',
 'cy_others',
 'rob_fo_sludge',
 'rob_lo_sludge',
 'rob_bilge',
 'sludge_removed_fo',
 'sludge_removed_lo',
 'sea_state',
 'cy_lub_added_to_system_mecc',
 'cy_lub_added_to_system_aecc',
 'cy_lub_added_to_thrusters',
 'cy_me_lo_purifier_in_use',
 'cy_ballast',
 'cy_bending_moment',
 'cy_shearing_force',
 'cy_tortion_moment',
 'cy_supdt_auditor_signed_on',
 'cy_supdt_auditor_signed_off',
 'cy_cash_received',
 'cy_lub_oil_received_mecyl',
 'cy_lub_oil_received_mecc',
 'cy_lub_oil_received_aecc',
 'cy_m_e_under_piston_temp',
 'cy_mail_received',
 'wind_direction_port_stbd',
 'sea_direction_port_stbd',
 'time_pilot_onboard',
 'grades_rob',
 'bunker_order',
 'remarks',
 'fuel_type',
 'carbon_factor',
 'so_2_co_2_ratio',
 'sulphur_content_pc',
 'quantity',
 'port_delivery',
 'product_quality',
 'tanktainer_number_1',
 'supplier',
 'vol_lt',
 'den',
 'vis',
 'fuel_hs',
 'fuel_ls',
 'fuel_mdo',
 'fuel_mgo',
 'fuel_mgo_ls',
 'bdn',
 'rob_dstlt_uls',
 'rob_dstlt_vls',
 'rob_rsdl_mdo',
 'rob_tnktnr_dstlt_vls',
 'rob_rsdl_vls',
 'rob_rsdl_hs',
 'rob_rsdl_uls',
 'rob_fuel_hsfo',
 'rob_fuel_lsfo',
 'rob_fuel_mdo',
 'rob_fuel_mgo',
 'rob_fuel_mgo_ls',
 'rob_fuel_tanktainer_mgo',
 'eca_miles',
 'eca_time',
 'egcs_dry_waste_removed',
 'egcs_running_time',
 'egcs_wet_slurry_removed',
 'egcs_open_loop_running_time',
 'egcs_closed_loop_running_time',
 'updated_date',
 'fuel_rsdl_hs',
 'fuel_rsdl_vls',
 'fuel_rsdl_uls',
 'fuel_dstlt_vls',
 'fuel_dstlt_uls',
 'fuel_tnktnr_dstlt_vls',
 'cargo_load',
 'seca_exit_time',
 'seca_exit_lat',
 'seca_exit_long',
 'engine_last_change_user',
 'created_date',
 'created_at',
 'updated_at',
 'created_by_id',
 'updated_by_id',
 'fuel_m_e_lng',
 'fuel_aux_lng',
 'fuel_boiler_lng',
 'rob_boiler_lng',
 'joinall',
 'is_alpha_delivery',
 'REMARKS',
 'delivery']

In [112]:
sorrentodata_final = sorrentodata_final[['id',
 'gid',
 'vessel_name',
 'imo',
 'voy',
 'corrected_date',
 'report_date_time',
 'report_date_time_offset',
 'report_type',
 'status',
 'latitude',
 'longitude',
 'm_e_foc',
 'cargo_total',
 'has_cargo',
 'steaming_time',
 'total_m_e_hours_fuel_only',
 'miles_by_gps',
 'oil_cyl',
 'speed_by_log',
 'speed_by_gps',
 'rpm',
 'slip',
 'wind_direction',
 'wind_speed',
 'draft_aft',
 'draft_fwd',
 'displacement',
 'course_at_sea',
 'wave_height',
 'sea_direction',
 'cargo_total_teu',
 'ambient_temp',
 'sw_temp',
 'miles_by_speed_log',
 'eta_port_code',
 'eta_date_time',
 'eta_date_time_offset',
 'eta_port',
 'time_change',
 'time_sea',
 'temp_min',
 'temp_max',
 'requested_speed',
 'rem_dist_to_pilot',
 'rem_time_to_pilot',
 'total_unplnd_stpge_tech',
 'total_unplnd_stpge_ope_wx',
 'reefers_positive_plugged',
 'reefers_negative_plugged',
 'me_total_revs_counter',
 'port_code',
 'port',
 'aux_blowers_on',
 'hold_ventilation_on',
 'since_date_time',
 'since_date_time_offset',
 'time_hrs_anchor',
 'time_hrs_drift',
 'reason',
 'type_of_delay',
 'etb_date_time',
 'etb_date_time_offset',
 'pilot_date_time',
 'pilot_date_time_offset',
 'time_manoeuvring',
 'tug_arr',
 'tug_shift',
 'etd_date_time',
 'etd_date_time_offset',
 'shift_berth_hours',
 'cargo_disch',
 'teu_full',
 'teu_empty',
 'bilge_removed',
 'garbage_removed',
 'garbage_remvl_reqstd',
 'garbage_remvl_cmplsry',
 'fw_supply',
 'cy_crew_signed_on',
 'cy_crew_signed_off',
 'cy_doctors_visit',
 'cy_mail_received_ref_no',
 'cy_lub_oil_sample_landed',
 'cy_checkd_for_stowaways',
 'cy_stowaways_on_board',
 'cy_dep_gm_mtr',
 'cy_requisitions_received',
 'distance_to_next_pilot',
 'tug_sailing_transit',
 'steaming_time_m_e_rsdl_vls',
 'steaming_time_m_e_rsdl_hs',
 'steaming_time_m_e_rsdl_uls',
 'steaming_time_m_e_dstlt_vls',
 'steaming_time_m_e_dstlt_uls',
 'steaming_time_m_e_tnktnr_dstlt_vls',
 'steaming_time_m_e_hs',
 'steaming_time_m_e_ls',
 'steaming_time_m_e_mdo',
 'steaming_time_m_e_mgo',
 'steaming_time_m_e_mgo_ls',
 'steaming_time_aux_1',
 'steaming_time_aux_2',
 'steaming_time_aux_3',
 'steaming_time_aux_4',
 'steaming_time_aux_5',
 'steaming_time_sh_gen',
 'steaming_time_tg',
 'power_kw',
 'steaming_load_kw_aux_1',
 'steaming_load_kw_aux_2',
 'steaming_load_kw_aux_3',
 'steaming_load_kw_aux_4',
 'steaming_load_kw_aux_5',
 'steaming_load_kw_sh_gen',
 'steaming_load_kw_tg',
 'fuel_m_e_rsdl_vls',
 'fuel_m_e_rsdl_hs',
 'fuel_m_e_rsdl_uls',
 'fuel_m_e_dstlt_vls',
 'fuel_m_e_dstlt_uls',
 'fuel_m_e_tnktnr_dstlt_vls',
 'fuel_m_e_hs',
 'fuel_m_e_ls',
 'fuel_m_e_mdo',
 'fuel_m_e_mgo',
 'fuel_m_e_mgo_ls',
 'fuel_aux_rsdl_vls',
 'fuel_aux_rsdl_hs',
 'fuel_aux_rsdl_uls',
 'fuel_aux_dstlt_vls',
 'fuel_aux_dstlt_uls',
 'fuel_aux_tnktnr_dstlt_vls',
 'fuel_aux_hs',
 'fuel_aux_ls',
 'fuel_aux_mdo',
 'fuel_aux_mgo',
 'fuel_aux_mgo_ls',
 'fuel_boiler_rsdl_vls',
 'fuel_boiler_rsdl_hs',
 'fuel_boiler_rsdl_uls',
 'fuel_boiler_dstlt_vls',
 'fuel_boiler_dstlt_uls',
 'fuel_boiler_tnktnr_dstlt_vls',
 'fuel_boiler_hs',
 'fuel_boiler_ls',
 'fuel_boiler_mdo',
 'fuel_boiler_mgo',
 'fuel_boiler_mgo_ls',
 'deck_last_change_user',
 'deck_part_is_complete',
 'engine_part_is_complete',
 'scavenge_pressure',
 'seca_entry_time',
 'seca_entry_lat',
 'seca_entry_long',
 'rob_fresh_water',
 'manvrng_miles_by_gps',
 'manvrng_miles_by_speed_log',
 'tanktainer_transfd_quantity',
 'pilot_taken',
 'date_time_start_transit',
 'date_time_start_transit_offset',
 'date_time_end_transit',
 'date_time_end_transit_offset',
 'ballast',
 'tanktainer_number',
 'steaming_kwhr_total',
 'cy_others',
 'rob_fo_sludge',
 'rob_lo_sludge',
 'rob_bilge',
 'sludge_removed_fo',
 'sludge_removed_lo',
 'sea_state',
 'cy_lub_added_to_system_mecc',
 'cy_lub_added_to_system_aecc',
 'cy_lub_added_to_thrusters',
 'cy_me_lo_purifier_in_use',
 'cy_ballast',
 'cy_bending_moment',
 'cy_shearing_force',
 'cy_tortion_moment',
 'cy_supdt_auditor_signed_on',
 'cy_supdt_auditor_signed_off',
 'cy_cash_received',
 'cy_lub_oil_received_mecyl',
 'cy_lub_oil_received_mecc',
 'cy_lub_oil_received_aecc',
 'cy_m_e_under_piston_temp',
 'cy_mail_received',
 'wind_direction_port_stbd',
 'sea_direction_port_stbd',
 'time_pilot_onboard',
 'grades_rob',
 'bunker_order',
 'remarks',
 'fuel_type',
 'carbon_factor',
 'so_2_co_2_ratio',
 'sulphur_content_pc',
 'quantity',
 'port_delivery',
 'product_quality',
 'tanktainer_number_1',
 'supplier',
 'vol_lt',
 'den',
 'vis',
 'fuel_hs',
 'fuel_ls',
 'fuel_mdo',
 'fuel_mgo',
 'fuel_mgo_ls',
 'bdn',
 'rob_dstlt_uls',
 'rob_dstlt_vls',
 'rob_rsdl_mdo',
 'rob_tnktnr_dstlt_vls',
 'rob_rsdl_vls',
 'rob_rsdl_hs',
 'rob_rsdl_uls',
 'rob_fuel_hsfo',
 'rob_fuel_lsfo',
 'rob_fuel_mdo',
 'rob_fuel_mgo',
 'rob_fuel_mgo_ls',
 'rob_fuel_tanktainer_mgo',
 'eca_miles',
 'eca_time',
 'egcs_dry_waste_removed',
 'egcs_running_time',
 'egcs_wet_slurry_removed',
 'egcs_open_loop_running_time',
 'egcs_closed_loop_running_time',
 'updated_date',
 'fuel_rsdl_hs',
 'fuel_rsdl_vls',
 'fuel_rsdl_uls',
 'fuel_dstlt_vls',
 'fuel_dstlt_uls',
 'fuel_tnktnr_dstlt_vls',
 'cargo_load',
 'seca_exit_time',
 'seca_exit_lat',
 'seca_exit_long',
 'engine_last_change_user',
 'created_date',
 'created_at',
 'updated_at',
 'created_by_id',
 'updated_by_id',
 'fuel_m_e_lng',
 'fuel_aux_lng',
 'fuel_boiler_lng',
 'rob_boiler_lng',
 'joinall',
 'is_alpha_delivery',
 'REMARKS',
 'delivery']]
sorrentodata_final

,id,gid,vessel_name,imo,voy,corrected_date,report_date_time,report_date_time_offset,report_type,status,...,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng,joinall,is_alpha_delivery,REMARKS,delivery
52945,4493570,3bc7c682-dd86-467e-b2ed-4170389b767e,MSC FABIENNE,9279965,XA351A,2024-01-01,2024-1-1 12:00,UTC +03:00,NOON,AT SEA,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",<NA>
58993,4497748,7bfc7956-a4db-49c9-b0c2-215bb701301e,MSC IVANA,9398371,FW351W,2024-01-01,2024-1-1 12:00,UTC +08:00,NOON,AT SEA,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",<NA>
58239,4496996,1ad5324f-0a87-4f13-87bc-c90482ea0cee,MSC NURIA,9349825,NK349R,2024-01-01,2024-1-1 12:00,UTC +00:00,DLY A,DRIFTING,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",<NA>
61828,4502410,4834cd9a-b51d-410d-9872-b5480c66494e,MSC MAYA,9708679,FT347E,2024-01-01,2024-1-1 12:00,UTC +08:00,NOON,AT SEA,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",<NA>
59231,4497985,7613834f-813b-4639-9bd4-c0df07a7f18c,MSC BEATRICE,9399014,ZF349A,2024-01-01,2024-1-1 12:00,UTC +05:30,NOON,AT SEA,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1750,4393313,f3a7859c-d65c-4fea-9969-b9782d7fa138,MSC STELLA,9279989,NG417W,2024-05-09,2024-5-9 6:18,UTC -04:00,BRTH,DRIFTING,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",<NA>
10359,4392294,47e09aad-b939-4da2-b4d1-6ae49cb91e46,MSC ALYSSA,9235050,CX418A,2024-05-09,2024-5-9 8:00,UTC +02:00,EOSP,AT SEA,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",<NA>
10360,4392295,1f440b50-f542-4097-8026-0a08f7561b94,MSC ALYSSA,9235050,CX418A,2024-05-09,2024-5-9 8:06,UTC +02:00,DLY A,DRIFTING,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",<NA>
13379,4402098,00bee91c-8fdb-41b7-a1f2-70fa911ed3d7,MSC MAYA,9708679,FT407E,2024-05-09,2024-5-9 8:30,UTC +08:00,BRTH,DRIFTING,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",<NA>
5763,4399043,6ca41997-8846-4b4f-a853-c8ba238006d6,MSC VALERIA,9461439,FY416R,2024-05-09,2024-5-9 8:30,UTC +00:00,SAIL,IN PORT,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",<NA>

In [113]:
refl_sorrento = sorrentodata_final[sorrentodata_final['report_type'] == 'REFL']
refl_sorrento

,id,gid,vessel_name,imo,voy,corrected_date,report_date_time,report_date_time_offset,report_type,status,...,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng,joinall,is_alpha_delivery,REMARKS,delivery
61191,4499944,b523dd11-7f20-4f68-940a-b017e4a2f101,MSC KATIE,9467457,FD401W,2024-01-11,2024-1-10 22:30,UTC +09:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,21612251,False,None,21612251
68182,4501305,4cf5e530-752c-45a8-8d99-8c6106089784,MSC LONDON,9606302,QG401W,2024-01-12,2024-1-11 12:20,UTC +08:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,2022188,False,None,2022188
52977,4493602,5c2543b3-d2dc-4225-b412-c46116e37789,MSC FABIENNE,9279965,XA351A,2024-01-12,2024-1-11 17:10,UTC +03:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,158315,False,None,158315
68233,4501356,464e01f8-7661-4bdc-904b-6a3cc3b18854,MSC NEW YORK,9606314,QJ350S,2024-01-12,2024-1-11 22:30,UTC +09:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,1051429,False,None,1051429
60701,4499455,58f0886d-6db1-4af9-a9bd-d0c9ebb63e3a,MSC VALERIA,9461439,FY348R,2024-01-13,2024-1-12 18:26,UTC +08:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,7378,False,None,7378
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3045,4396432,ff2bb689-cd6d-44f0-8629-27c56c4f581b,MSC KIM,9351581,NC413R,2024-05-10,2024-5-9 14:35,UTC +02:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,BRDI84,False,None,BRDI_84
3046,4396433,d4035347-44b3-46b3-914e-0f08723b1cdb,MSC KIM,9351581,NC413R,2024-05-10,2024-5-9 16:45,UTC +02:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,BRZI171,False,None,BRZI_171
13381,4402100,1a4cc199-55dd-4668-8e35-a8ec4e0ff1f6,MSC MAYA,9708679,FT407E,2024-05-10,2024-5-9 17:08,UTC +08:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,18972,False,None,18972
13438,4402157,ca8a7330-aade-4821-8685-d83382573d10,MSC SVEVA,9708681,QG418E,2024-05-09,2024-5-9 3:22,UTC +00:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,BQI2199,False,None,BQI2_199
4662,4397944,d4d2f11b-5da4-4dba-b60b-f23c1942f5b2,MSC FRANCESCA,9401116,OW416R,2024-05-09,2024-5-9 5:12,UTC +02:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,A0890,False,None,A0890

In [114]:
refl_sorrento.to_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\OUTPUT\SORRENTO MISSING BDNs refl.xlsx",index = False)

In [115]:
refl_sorrento_remarks = refl_sorrento[refl_sorrento['REMARKS'].notnull()]
refl_sorrento_remarks

,id,gid,vessel_name,imo,voy,corrected_date,report_date_time,report_date_time_offset,report_type,status,...,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng,joinall,is_alpha_delivery,REMARKS,delivery
53111,4493736,6fc57f78-723e-402b-9d36-98c208da040c,MSC STELLA,9279989,NG350E,2024-01-13,2024-1-12 19:50,UTC +01:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,110795BRDI20,False,Sulphur is not given,110795_BRDI_20
51930,4492546,a01618bc-bb31-4683-9932-78494d4c4439,MSC MELISSA,9226918,OW401R,2024-01-12,2024-1-12 3:20,UTC +00:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,480319530A,False,Sulphur is not given,480319530A
51929,4492545,63990e38-0431-4812-89ed-1de09f021d35,MSC MELISSA,9226918,OW401R,2024-01-12,2024-1-12 3:20,UTC +00:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,480319530,False,Sulphur is not given,480319530
68234,4501357,b027b770-e743-4ba4-89e9-f1f0a1430e91,MSC NEW YORK,9606314,QJ350S,2024-01-12,2024-1-12 6:45,UTC +09:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,FF00110782,False,Sulphur is not given,FF00110782
61944,4502526,62fb10b3-243c-417c-b021-b04f8bdfd5fa,MSC CLARA,9708693,FT348E,2024-01-06,2024-1-5 17:18,UTC +08:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,6254,False,Fuel Type or Sulphur will be wrong,6254
51110,4491726,40834d6f-1661-4f5b-9480-9cbeafd162d7,MSC DIEGO,9202649,OM352A,2024-01-09,2024-1-8 14:25,UTC +05:30,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,411,False,Sulphur is not given,411
75719,4507718,abbe3849-08c6-4054-829c-29332e999624,MSC FABIENNE,9279965,NT404A,2024-02-02,2024-2-1 18:20,UTC +02:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NO,True,BDN is not given,NO
66157,4506956,5970fb57-83b3-4dbf-96d0-27e3f938d11a,MSC ALYSSA,9235050,CI406R,2024-02-13,2024-2-13 0:00,UTC +00:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,0,False,"Sulphur is not given,BDN is not given",0
70497,4511611,722839ec-543a-44b2-bab5-a2b1c877f371,MSC IVANA,9398371,FW351W,2024-02-14,2024-2-14 0:20,UTC +01:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,BQ1274,False,Fuel Type or Sulphur will be wrong,BQ12_74
77935,4509932,d519ea74-4bfa-4bc0-b627-c272049d9baf,MSC ROSARIA,9320453,MX406R,2024-02-20,2024-2-20 0:10,UTC -05:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,BDN is not given,<NA>
65172,4505963,97d6856c-4261-4a11-977a-e3891514cde1,MSC REGINA,9202651,OM401R,2024-02-21,2024-2-20 22:20,UTC +04:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,0,False,BDN is not given,0
63723,4504507,70037bff-42fe-4443-a837-6ef1f580cbd8,MSC MARTINA,9060637,OM402R,2024-02-29,2024-2-28 14:00,UTC +02:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,5345,False,Sulphur is not given,5345
63724,4504508,603a645a-8249-4119-90c7-501e753a2f45,MSC MARTINA,9060637,OM402R,2024-02-29,2024-2-28 15:20,UTC +02:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,5344,False,Sulphur is not given,5344
63725,4504509,1a7da3a3-42fa-4aac-89a1-6e589c8a02d3,MSC MARTINA,9060637,OM402R,2024-02-29,2024-2-28 17:30,UTC +02:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,5323,False,Sulphur is not given,5323
63733,4504517,d18be661-8df5-42ef-9bf3-802f49852da2,MSC MARTINA,9060637,OM409A,2024-03-01,2024-2-29 15:00,UTC +02:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,3781,False,Sulphur is not given,3781
65908,4506707,3996f580-0709-4d03-9043-c4b8632dba41,MSC MELISSA,9226918,OW404R,2024-02-10,2024-2-9 19:10,UTC +00:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,480321065,False,Sulphur is not given,480321065
92701,4531507,b26641ed-ed17-4ceb-805b-c6140ac30fe8,MSC DILETTA,9897004,FJ402E,2024-03-12,2024-3-11 14:57,UTC +08:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",<NA>
92699,4531505,d86386aa-be02-449a-9211-67b957b99d87,MSC DILETTA,9897004,FJ402E,2024-03-11,2024-3-11 2:00,UTC +08:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",<NA>
78157,4519332,fed803bc-bef6-47c1-9d28-4646c189ed74,MSC DIEGO,9202649,OM352A,2024-03-15,2024-3-14 14:27,UTC +02:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,ABSDIEGO140324,False,Sulphur is not given,ABS DIEGO 14.03.24
78175,4519350,fda6ce27-7b40-46b9-95a1-82ef4b52efc1,MSC DIEGO,9202649,OM406R,2024-03-27,2024-3-26 20:10,UTC +02:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,MSC126,False,Sulphur is not given,MSC126
79090,4520265,78343892-8205-44d5-b627-8cdc18b9ef72,MSC MICHAELA,9230488,UK408R,2024-03-08,2024-3-7 12:45,UTC -08:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,BDN is not given,<NA>
80236,4521417,0f9b48a5-55cb-4672-ace7-e980dfec4177,MSC LISA,9281279,MX409R,2024-03-07,2024-3-7 2:25,UTC +00:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,BDN is not given,<NA>
96824,4537499,c78107b4-6e49-4621-9961-25d2b9e1ae7c,MSC ROSARIA,9320453,MX416R,2024-04-25,2024-4-24 12:25,UTC -04:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,BDN is not given,<NA>
96825,4537500,971f8b08-a873-4d82-b90c-6bcecda6b50e,MSC ROSARIA,9320453,MX416R,2024-04-25,2024-4-24 15:35,UTC -04:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NotApl,True,BDN is not given,Not Apl.
102120,4542796,08856b18-12e0-4bb6-add9-0f099539d9e1,MSC AMSTERDAM,9606338,QG417E,2024-04-30,2024-4-29 18:10,UTC +01:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NL0074002680,False,Sulphur is not given,NL0074002680
100692,4541370,f6aa2414-daa1-44a6-add1-4943c1b66543,MSC KATIE,9467457,IS413A,2024-05-01,2024-4-30 17:23,UTC +02:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,1954,False,"Sulphur is not given,Fuel Type or Sulphur will...",1954
106910,4535387,124f7373-e22c-452e-af00-8dcb9cac67cb,MSC STELLA,9279989,NG417W,2024-04-30,2024-4-30 5:00,UTC +02:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,BRZI160,False,Sulphur is not given,BRZI_160
93206,4532021,ddd4d0b9-ab86-407c-a888-41c6594fc9ba,MSC MARTINA,9060637,OM409A,2024-04-10,2024-4-9 18:00,UTC +03:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,RSV9743,False,Sulphur is not given,RSV 9743
13445,4402164,16282380-7fee-4529-973b-3b5c421a86ff,MSC SVEVA,9708681,QG418E,2024-05-12,2024-5-11 12:44,UTC +02:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,BRBTB202400000489,False,Fuel Type or Sulphur will be wrong,BRBTB202400000489
1556,4393119,d265d3d3-959e-4e28-b87d-e38fefe2ca8e,MSC MARINA,9275971,XA404A,2024-05-13,2024-5-13 5:40,UTC +08:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Fuel Type or Sulphur will be wrong,BDN is not ...",<NA>
7947,4391394,620fa7a2-e0ae-46aa-8a98-3e2808b3399d,MSC REGINA,9202651,OM414A,2024-05-22,2024-5-21 13:40,UTC +02:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NA,True,"Sulphur is not given,BDN is not given",N.A.
7948,4391395,eb6c02f7-06c7-49cb-84bf-af0b580ca6eb,MSC REGINA,9202651,OM414A,2024-05-22,2024-5-21 13:50,UTC +02:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NA,True,"Sulphur is not given,BDN is not given",N.A
7949,4391396,5ea53085-ebe5-416a-8b3c-034b2f712975,MSC REGINA,9202651,OM414A,2024-05-22,2024-5-21 14:00,UTC +02:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,BDN is not given",<NA>
3460,4396851,2ecd8b7b-9867-4d54-98fb-85671f26e139,MSC ORIANE,9372482,MX420R,2024-05-24,2024-5-23 18:35,UTC -04:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NIL,True,BDN is not given,NIL
3461,4396852,04985951-66b2-4a55-b2fd-36e9882b68e6,MSC ORIANE,9372482,MX420R,2024-05-24,2024-5-23 18:35,UTC -04:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,BDN is not given,<NA>
3388,4396779,141685f4-1074-4c3d-a172-6258542d9d57,MSC KRYSTAL,9372470,NJ417R,2024-05-26,2024-5-25 13:35,UTC +02:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,BRBTB202497108695BD,False,Sulphur is not given,BRBTB202497108695BD
13182,4401901,274a22da-9965-422c-9564-07d7415b0371,MSC OLIVER,9703306,FT409E,2024-05-26,2024-5-25 23:00,UTC +07:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,"Sulphur is not given,quantity is not given,BDN...",<NA>
3472,4396863,cce39773-a2ca-4e6d-b4b4-7bcb896a1cda,MSC ORIANE,9372482,MX420R,2024-05-27,2024-5-27 7:50,UTC -04:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,BDN is not given,<NA>
1584,4393147,13a070d5-97dc-4a7e-b684-fe93efd5578e,MSC MARINA,9275971,QM420A,2024-05-29,2024-5-28 21:46,UTC +00:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,2405730,False,Fuel Type or Sulphur will be wrong,2405730
8899,4401063,ad99dacc-fba5-46af-a67e-48624a1c2800,MSC ISTANBUL,9606326,QG420E,2024-05-30,2024-5-29 14:00,UTC -09:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,BRDI129,False,Sulphur is not given,BRDI129
1851,4393419,aae25f7a-fe3a-46ff-b49d-6b02d555e268,MSC LISA,9281279,CI421A,2024-05-30,2024-5-30 8:54,UTC +02:00,REFL,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,BDN is not given,<NA>

In [116]:
refl_sorrento_remarks.to_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\OUTPUT FOR CLIENT\SORRENTO MISSING BDNs.xlsx",index = False)