In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np

In [2]:
# DOWNLOAD THE FILE FROM MSC SITE
mscsmcy = pd.read_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\SCRUBBER DAYS/MSCSMCY Scrubber_Data.xlsx")
mscsmcy

            Vessel   IMO No  SO2/CO2 ppm  Fuel Sulphur  Scrubber Days
0          MSC ABY  9166778         6.18          0.14              7
1          MSC ABY  9166778         1.22          0.03             31
2        MSC ADITI  9235581         6.09          0.14             11
3        MSC ADITI  9235581         0.79          0.02            168
4    MSC AGRIGENTO  9618276         5.55          0.13              8
..             ...      ...          ...           ...            ...
218   MSC YUVIKA V  9141285         8.59          0.20              2
219   MSC YUVIKA V  9141285         3.47          0.08            175
220   WEC DE HOOGH  9315018         0.72          0.02            158
221   WEC VAN RIJN  9315006        12.70          0.29              1
222   WEC VAN RIJN  9315006         0.96          0.02             82

[223 rows x 5 columns]

In [3]:
# DOWNLOAD THE FILE FROM MSC SITE
charter = pd.read_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\SCRUBBER DAYS\CHARTER Scrubber_Data.xlsx")
charter

            Vessel   IMO No  SO2/CO2 ppm  Fuel Sulphur  Scrubber Days
0          MSC ABY  9166778         6.18          0.14              7
1          MSC ABY  9166778         1.22          0.03             31
2        MSC ADITI  9235581         6.09          0.14             11
3        MSC ADITI  9235581         0.79          0.02            168
4    MSC AGRIGENTO  9618276         5.55          0.13              8
..             ...      ...          ...           ...            ...
218   MSC YUVIKA V  9141285         8.59          0.20              2
219   MSC YUVIKA V  9141285         3.47          0.08            175
220   WEC DE HOOGH  9315018         0.72          0.02            158
221   WEC VAN RIJN  9315006        12.70          0.29              1
222   WEC VAN RIJN  9315006         0.96          0.02             82

[223 rows x 5 columns]

In [5]:
# DOWNLOAD THE FILE FROM MSC SITE
sorrento = pd.read_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\SCRUBBER DAYS/SORRENTO Scrubber_Data.xlsx")
sorrento

               Vessel   IMO No  SO2/CO2 ppm  Fuel Sulphur  Scrubber Days
0       AS CALIFORNIA  9342695         1.00          0.02              1
1        ATHENS GLORY  9247766         0.10          0.00            139
2            LE HAVRE  9307243         9.97          0.23             44
3            LE HAVRE  9307243         2.38          0.05             71
4          MSC AGADIR  9619464         7.83          0.18             92
5          MSC AGADIR  9619464         2.46          0.06             71
6        MSC AQUARIUS  9262704         0.48          0.01            117
7           MSC ATHOS  9618317         0.10          0.00              1
8            MSC AZOV  9605255         0.90          0.02             80
9            MSC BARI  9461441         8.81          0.20            112
10           MSC BARI  9461441         2.16          0.05             65
11      MSC BOSPHORUS  9247742         0.18          0.00             47
12      MSC LA SPEZIA  9461403         8.33          0.19             86
13      MSC LA SPEZIA  9461403         2.15          0.05             84
14        MSC LIVORNO  9461427         7.02          0.16             82
15        MSC LIVORNO  9461427         2.50          0.06            105
16        MSC RAVENNA  9484431         8.90          0.20            113
17        MSC RAVENNA  9484431         1.66          0.04             68
18           MSC ROMA  9304447         6.66          0.15              3
19           MSC ROMA  9304447         1.14          0.03            175
20         MSC SAVONA  9460356         8.88          0.20             51
21         MSC SAVONA  9460356         1.70          0.04             92
22        MSC TARANTO  9475258         8.25          0.19             96
23        MSC TARANTO  9475258         1.63          0.04             69
24  SPIRIT OF CHENNAI  9813840         5.68          0.13            163
25  SPIRIT OF CHENNAI  9813840         4.20          0.10             44
26  SPIRIT OF KOLKATA  9813838         5.62          0.13             13
27  SPIRIT OF KOLKATA  9813838         2.12          0.05            104

In [6]:
esi = pd.read_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\CLIENT FILE\ESI CURRENT VESSELS.xlsx")
esi

         IMO    Fleet          Vessel Scrubber Unnamed: 4
0    9297589  CHARTER           ALANA       No        NaN
1    9625970        9       ANASTASIA       No        NaN
2    9342695  CHARTER   AS California       No        NaN
3    9314947  CHARTER     AS CAMELLIA      Yes        NaN
4    9321897       12    MSC NADIA IV       No        NaN
..       ...      ...             ...      ...        ...
429  9198587       14    MSC CHIARA X       No        NaN
430  9299032       19  MSC FALCON III       No        NaN
431  9962598       15     MSC LORENZA      Yes        NaN
432  9967263       23      MSC MAPUTO      Yes        NaN
433  9214898       14    MSC NICOLE X       No        NaN

[434 rows x 5 columns]

In [7]:
esi_charter = esi[esi['Fleet'] =='CHARTER']
esi_sorrento = esi[esi['Fleet'] == 'SORRENTO']
esi_own = esi[(esi.Fleet !='CHARTER') & (esi.Fleet != 'SORRENTO')]

In [8]:
esi_charter.shape

(57, 5)

In [9]:
esi_sorrento

         IMO     Fleet                 Vessel Scrubber Unnamed: 4
50   9129873  SORRENTO              MSC ALEXA       No        NaN
54   9235050  SORRENTO             MSC ALYSSA       No        NaN
56   9839480  SORRENTO              MSC AMBRA      Yes        NaN
58   9606338  SORRENTO          MSC AMSTERDAM       No        NaN
88   9399014  SORRENTO           MSC BEATRICE      Yes        NaN
113  9930040  SORRENTO  MSC CELESTINO MARESCA      Yes        NaN
119  9708693  SORRENTO              MSC CLARA      Yes        NaN
134  9202649  SORRENTO              MSC DIEGO       No        NaN
135  9897004  SORRENTO            MSC DILETTA      Yes        NaN
159  9279965  SORRENTO           MSC FABIENNE       No        NaN
165  9401116  SORRENTO          MSC FRANCESCA      Yes        NaN
170  9202663  SORRENTO               MSC GINA       No        NaN
177  9647461  SORRENTO            MSC HAMBURG      Yes        NaN
195  9606326  SORRENTO           MSC ISTANBUL       No        NaN
196  9398371  SORRENTO              MSC IVANA      Yes        NaN
204  9966934  SORRENTO              MSC JIANI       No        NaN
211  9399026  SORRENTO             MSC KALINA      Yes        NaN
214  9467457  SORRENTO              MSC KATIE      Yes        NaN
220  9351581  SORRENTO                MSC KIM       No        NaN
223  9372470  SORRENTO            MSC KRYSTAL       No        NaN
228  9225665  SORRENTO              MSC LAURA      Yes        NaN
236  9281279  SORRENTO               MSC LISA       No        NaN
238  9606302  SORRENTO             MSC LONDON      Yes        NaN
239  9320403  SORRENTO             MSC LORENA       No        NaN
242  9230490  SORRENTO            MSC LORETTA      Yes        NaN
262  9275971  SORRENTO             MSC MARINA       No        NaN
263  9060637  SORRENTO            MSC MARTINA       No        NaN
268  9251717  SORRENTO            MSC MAUREEN       No        NaN
270  9708679  SORRENTO               MSC MAYA      Yes        NaN
272  9226918  SORRENTO            MSC MELISSA      Yes        NaN
276  9230488  SORRENTO           MSC MICHAELA      Yes        NaN
278  9897016  SORRENTO           MSC MICHELLE      Yes        NaN
287  9955789  SORRENTO             MSC NAHARA      Yes        NaN
292  9606314  SORRENTO           MSC NEW YORK       No        NaN
302  9349825  SORRENTO              MSC NURIA       No        NaN
306  9703306  SORRENTO             MSC OLIVER       No        NaN
307  9372482  SORRENTO             MSC ORIANE       No        NaN
310  9703291  SORRENTO              MSC OSCAR      Yes        NaN
319  9279977  SORRENTO            MSC POH LIN       No        NaN
326  9290282  SORRENTO            MSC RACHELE       No        NaN
331  9754965  SORRENTO               MSC REEF      Yes        NaN
332  9202651  SORRENTO             MSC REGINA       No        NaN
339  9320453  SORRENTO            MSC ROSARIA       No        NaN
375  9404663  SORRENTO              MSC SONIA      Yes        NaN
378  9279989  SORRENTO             MSC STELLA      Yes        NaN
381  9708681  SORRENTO              MSC SVEVA      Yes        NaN
393  9309461  SORRENTO             MSC TOMOKO       No        NaN
403  9461439  SORRENTO            MSC VALERIA       No        NaN
404  9484467  SORRENTO             MSC VANDYA       No        NaN
422  9703318  SORRENTO                MSC ZOE      Yes        NaN

In [10]:
esi_sorrento.shape

(50, 5)

In [11]:
esi_own

         IMO Fleet          Vessel Scrubber Unnamed: 4
1    9625970     9       ANASTASIA       No        NaN
4    9321897    12    MSC NADIA IV       No        NaN
6    9334519    15   MSC ZAINA III       No        NaN
15   9453298    14      GOLD HOSHI       No        NaN
16   9463205    14     GOLD KOCHAV       No        NaN
..       ...   ...             ...      ...        ...
429  9198587    14    MSC CHIARA X       No        NaN
430  9299032    19  MSC FALCON III       No        NaN
431  9962598    15     MSC LORENZA      Yes        NaN
432  9967263    23      MSC MAPUTO      Yes        NaN
433  9214898    14    MSC NICOLE X       No        NaN

[327 rows x 5 columns]

In [12]:
#client send mscsmcy vessel imo list
esi_own_lst = esi_own['IMO'].to_list()
esi_own_lst

[9625970,
 9321897,
 9334519,
 9453298,
 9463205,
 9180205,
 9330226,
 9166778,
 9190119,
 8512906,
 9235581,
 9169055,
 9932921,
 9057173,
 9618276,
 9770751,
 9123166,
 9301990,
 9618288,
 9842097,
 9196852,
 9319600,
 9008603,
 9242651,
 9261827,
 9259379,
 9306275,
 9227297,
 8521402,
 9169122,
 9282261,
 9254848,
 9323041,
 9297864,
 9710426,
 9857169,
 9839284,
 9244881,
 9162631,
 9263344,
 8913447,
 8512891,
 9857183,
 9263332,
 9226932,
 9360764,
 9289099,
 9203904,
 9297876,
 9770749,
 9930935,
 9720495,
 9313967,
 9103685,
 9702106,
 9289087,
 9169043,
 9262546,
 9102722,
 9360271,
 9154220,
 9210086,
 9625944,
 9946879,
 9295397,
 9253038,
 9705005,
 9229300,
 9316361,
 9710438,
 9299537,
 9198587,
 9936642,
 9936628,
 9113446,
 9301550,
 9241463,
 9307267,
 9426817,
 9295165,
 9250983,
 9927287,
 9930959,
 9200689,
 9262560,
 9306263,
 9720201,
 9102746,
 9237151,
 9301328,
 9444285,
 9294824,
 9110391,
 9169029,
 9282259,
 9236688,
 9278143,
 9064750,
 9215892,
 9166780,
 9735218,
 9704972,
 8917778,
 9326823,
 9334832,
 9463047,
 9004231,
 8201648,
 9302633,
 9842085,
 9299032,
 9290402,
 9120853,
 8413875,
 9344708,
 9152856,
 9289051,
 9153850,
 9720196,
 9947134,
 9210062,
 9415296,
 9631876,
 9283708,
 9316347,
 9350317,
 9127540,
 9463281,
 9224946,
 9962562,
 9962586,
 9197545,
 9124366,
 9231248,
 9181651,
 9929429,
 8201624,
 9839272,
 9154206,
 9110975,
 9433157,
 9000742,
 9720471,
 9622007,
 9215672,
 8918980,
 9039250,
 9227338,
 9275036,
 9450351,
 9244946,
 9236585,
 9232656,
 9467445,
 9227302,
 9110389,
 9242637,
 9927299,
 9123154,
 9051507,
 9305506,
 9439735,
 9064748,
 9162643,
 9947158,
 9347762,
 9383223,
 9334349,
 9704960,
 9237498,
 9962598,
 9934735,
 9327798,
 9251690,
 9308625,
 9400148,
 9231119,
 9625932,
 9252553,
 9252541,
 8201636,
 9238882,
 8918966,
 9967263,
 9932892,
 9465318,
 8616520,
 9155107,
 9964194,
 9962574,
 9540077,
 9169031,
 9181663,
 9315915,
 9720287,
 9102710,
 9936630,
 9231779,
 9169067,
 9720512,
 9196864,
 9839260,
 9293179,
 9932050,
 9060649,
 9294991,
 9149328,
 9307839,
 9471226,
 8918954,
 9278155,
 9214898,
 9228576,
 9315886,
 9308584,
 9326768,
 9084607,
 9778117,
 9946843,
 9256315,
 9456965,
 9336359,
 9408774,
 9857157,
 9281267,
 9735206,
 9336165,
 9239903,
 9161297,
 9240328,
 9256391,
 9267637,
 9222302,
 9074042,
 9139086,
 9299020,
 9154191,
 9450325,
 9235402,
 9930052,
 9139505,
 9465306,
 9240873,
 9419644,
 9038907,
 9293167,
 9957359,
 9337676,
 8714205,
 9401166,
 9491616,
 9110377,
 9434462,
 9222106,
 9290426,
 8913411,
 9702261,
 9181675,
 8715857,
 9241451,
 9720500,
 9116369,
 9471238,
 9292175,
 9231822,
 8913423,
 9036002,
 9180968,
 9224049,
 9778105,
 9778076,
 9720457,
 9210098,
 9224348,
 9793947,
 9162277,
 9927275,
 9702091,
 9695028,
 9220328,
 9259393,
 9210050,
 8918978,
 9330068,
 9231262,
 9200677,
 9308601,
 9351579,
 9316373,
 9008574,
 9189366,
 9930038,
 9248928,
 9299525,
 9295177,
 9230775,
 9931288,
 9337444,
 9302619,
 9302621,
 9315836,
 9227340,
 9251688,
 9242625,
 9238739,
 9304708,
 9146479,
 9908059,
 9702089,
 9947122,
 9908047,
 9236690,
 9288409,
 9778090,
 9322011,
 9146467,
 9344564,
 9141285,
 9315018,
 9326964,
 9354363,
 9315006,
 9198587,
 9299032,
 9962598,
 9967263,
 9214898]

In [13]:
len(esi_own_lst)

327

In [14]:
missing_imo = [IMO for IMO in esi_own_lst if IMO not in mscsmcy]
missing_imo

[9625970,
 9321897,
 9334519,
 9453298,
 9463205,
 9180205,
 9330226,
 9166778,
 9190119,
 8512906,
 9235581,
 9169055,
 9932921,
 9057173,
 9618276,
 9770751,
 9123166,
 9301990,
 9618288,
 9842097,
 9196852,
 9319600,
 9008603,
 9242651,
 9261827,
 9259379,
 9306275,
 9227297,
 8521402,
 9169122,
 9282261,
 9254848,
 9323041,
 9297864,
 9710426,
 9857169,
 9839284,
 9244881,
 9162631,
 9263344,
 8913447,
 8512891,
 9857183,
 9263332,
 9226932,
 9360764,
 9289099,
 9203904,
 9297876,
 9770749,
 9930935,
 9720495,
 9313967,
 9103685,
 9702106,
 9289087,
 9169043,
 9262546,
 9102722,
 9360271,
 9154220,
 9210086,
 9625944,
 9946879,
 9295397,
 9253038,
 9705005,
 9229300,
 9316361,
 9710438,
 9299537,
 9198587,
 9936642,
 9936628,
 9113446,
 9301550,
 9241463,
 9307267,
 9426817,
 9295165,
 9250983,
 9927287,
 9930959,
 9200689,
 9262560,
 9306263,
 9720201,
 9102746,
 9237151,
 9301328,
 9444285,
 9294824,
 9110391,
 9169029,
 9282259,
 9236688,
 9278143,
 9064750,
 9215892,
 9166780,
 9735218,
 9704972,
 8917778,
 9326823,
 9334832,
 9463047,
 9004231,
 8201648,
 9302633,
 9842085,
 9299032,
 9290402,
 9120853,
 8413875,
 9344708,
 9152856,
 9289051,
 9153850,
 9720196,
 9947134,
 9210062,
 9415296,
 9631876,
 9283708,
 9316347,
 9350317,
 9127540,
 9463281,
 9224946,
 9962562,
 9962586,
 9197545,
 9124366,
 9231248,
 9181651,
 9929429,
 8201624,
 9839272,
 9154206,
 9110975,
 9433157,
 9000742,
 9720471,
 9622007,
 9215672,
 8918980,
 9039250,
 9227338,
 9275036,
 9450351,
 9244946,
 9236585,
 9232656,
 9467445,
 9227302,
 9110389,
 9242637,
 9927299,
 9123154,
 9051507,
 9305506,
 9439735,
 9064748,
 9162643,
 9947158,
 9347762,
 9383223,
 9334349,
 9704960,
 9237498,
 9962598,
 9934735,
 9327798,
 9251690,
 9308625,
 9400148,
 9231119,
 9625932,
 9252553,
 9252541,
 8201636,
 9238882,
 8918966,
 9967263,
 9932892,
 9465318,
 8616520,
 9155107,
 9964194,
 9962574,
 9540077,
 9169031,
 9181663,
 9315915,
 9720287,
 9102710,
 9936630,
 9231779,
 9169067,
 9720512,
 9196864,
 9839260,
 9293179,
 9932050,
 9060649,
 9294991,
 9149328,
 9307839,
 9471226,
 8918954,
 9278155,
 9214898,
 9228576,
 9315886,
 9308584,
 9326768,
 9084607,
 9778117,
 9946843,
 9256315,
 9456965,
 9336359,
 9408774,
 9857157,
 9281267,
 9735206,
 9336165,
 9239903,
 9161297,
 9240328,
 9256391,
 9267637,
 9222302,
 9074042,
 9139086,
 9299020,
 9154191,
 9450325,
 9235402,
 9930052,
 9139505,
 9465306,
 9240873,
 9419644,
 9038907,
 9293167,
 9957359,
 9337676,
 8714205,
 9401166,
 9491616,
 9110377,
 9434462,
 9222106,
 9290426,
 8913411,
 9702261,
 9181675,
 8715857,
 9241451,
 9720500,
 9116369,
 9471238,
 9292175,
 9231822,
 8913423,
 9036002,
 9180968,
 9224049,
 9778105,
 9778076,
 9720457,
 9210098,
 9224348,
 9793947,
 9162277,
 9927275,
 9702091,
 9695028,
 9220328,
 9259393,
 9210050,
 8918978,
 9330068,
 9231262,
 9200677,
 9308601,
 9351579,
 9316373,
 9008574,
 9189366,
 9930038,
 9248928,
 9299525,
 9295177,
 9230775,
 9931288,
 9337444,
 9302619,
 9302621,
 9315836,
 9227340,
 9251688,
 9242625,
 9238739,
 9304708,
 9146479,
 9908059,
 9702089,
 9947122,
 9908047,
 9236690,
 9288409,
 9778090,
 9322011,
 9146467,
 9344564,
 9141285,
 9315018,
 9326964,
 9354363,
 9315006,
 9198587,
 9299032,
 9962598,
 9967263,
 9214898]

In [15]:
#scrubber days mscsmcy vessel imo list
scrubber_own_lst = mscsmcy['IMO No'].to_list()
scrubber_own_lst

[9166778,
 9166778,
 9235581,
 9235581,
 9618276,
 9618276,
 9618288,
 9618288,
 9842097,
 9842097,
 9242651,
 9227297,
 9282261,
 9282261,
 9297864,
 9297864,
 9710426,
 9710426,
 9857169,
 9839284,
 9839284,
 9244881,
 9263344,
 9263344,
 9857183,
 9263332,
 9263332,
 9226932,
 9226932,
 9289099,
 9289099,
 9297876,
 9930935,
 9930935,
 9720495,
 9313967,
 9313967,
 9103685,
 9103685,
 9702106,
 9702106,
 9289087,
 9289087,
 9154220,
 9154220,
 9210086,
 9210086,
 9705005,
 9705005,
 9316361,
 9710438,
 9710438,
 9936642,
 9936628,
 9936628,
 9307267,
 9307267,
 9250983,
 9250983,
 9237151,
 9237151,
 9110391,
 9110391,
 9282259,
 9282259,
 9278143,
 9215892,
 9166780,
 9735218,
 9735218,
 9704972,
 9704972,
 9463047,
 9463047,
 9842085,
 9842085,
 9120853,
 9120853,
 9152856,
 9720196,
 9720196,
 9947134,
 9947134,
 9316347,
 9463281,
 9124366,
 9124366,
 9231248,
 9231248,
 9181651,
 9929429,
 9929429,
 9839272,
 9839272,
 9110975,
 9110975,
 9433157,
 9000742,
 9720471,
 9720471,
 9215672,
 9215672,
 8918980,
 9227338,
 9467445,
 9467445,
 9227302,
 9123154,
 9305506,
 9305506,
 9334349,
 9334349,
 9704960,
 9704960,
 9934735,
 9934735,
 9327798,
 9251690,
 9932892,
 9932892,
 9465318,
 9465318,
 9155107,
 9155107,
 9181663,
 9315915,
 9315915,
 9720287,
 9720287,
 9936630,
 9231779,
 9196864,
 9839260,
 9839260,
 9293179,
 9060649,
 9060649,
 9149328,
 9149328,
 9471226,
 9471226,
 9778117,
 9778117,
 9456965,
 9408774,
 9857157,
 9281267,
 9281267,
 9735206,
 9735206,
 9161297,
 9161297,
 9240328,
 9267637,
 9267637,
 9222302,
 9222302,
 9074042,
 9154191,
 9930052,
 9930052,
 9139505,
 9139505,
 9465306,
 9465306,
 9240873,
 9038907,
 9038907,
 9293167,
 9401166,
 9401166,
 9110377,
 9110377,
 9434462,
 9290426,
 9290426,
 8913411,
 9702261,
 9702261,
 9181675,
 9720500,
 9471238,
 9471238,
 9231822,
 9224049,
 9224049,
 9778076,
 9778076,
 9720457,
 9720457,
 9210098,
 9210098,
 9224348,
 9702091,
 9702091,
 9695028,
 9695028,
 9231262,
 9200677,
 9351579,
 9351579,
 9316373,
 9316373,
 9008574,
 9930038,
 9930038,
 9299525,
 9299525,
 9931288,
 9337444,
 9251688,
 9702089,
 9702089,
 9947122,
 9947122,
 9236690,
 9778090,
 9778090,
 9141285,
 9141285,
 9315018,
 9315006,
 9315006]

In [16]:
len(scrubber_own_lst)

223

In [17]:
#client send mscsmcy vessel imo list
esi_charter_lst = esi_charter['IMO'].to_list()
esi_charter_lst

[9297589,
 9342695,
 9314947,
 9247766,
 9727625,
 9706205,
 9293791,
 9308613,
 9373917,
 9357810,
 9153862,
 9301469,
 9256482,
 9357793,
 9535163,
 9535187,
 9535204,
 9225770,
 9085558,
 9085546,
 9085534,
 9085522,
 9307243,
 9236535,
 9162227,
 9148025,
 9256365,
 9106479,
 9106493,
 9225794,
 9141780,
 9619464,
 9247730,
 9262704,
 9618317,
 9605255,
 9480186,
 9461441,
 9247742,
 9480203,
 9480215,
 9247754,
 9225641,
 9135638,
 9461403,
 9461427,
 9480198,
 9349796,
 9256470,
 9484431,
 9304447,
 9460356,
 9475258,
 9285471,
 9480227,
 9813840,
 9813838]

In [18]:
len(esi_charter_lst)

57

In [19]:
#scrubber days mscsmcy vessel imo list
scrubber_charter_lst = charter['IMO No'].to_list()
scrubber_charter_lst

[9166778,
 9166778,
 9235581,
 9235581,
 9618276,
 9618276,
 9618288,
 9618288,
 9842097,
 9842097,
 9242651,
 9227297,
 9282261,
 9282261,
 9297864,
 9297864,
 9710426,
 9710426,
 9857169,
 9839284,
 9839284,
 9244881,
 9263344,
 9263344,
 9857183,
 9263332,
 9263332,
 9226932,
 9226932,
 9289099,
 9289099,
 9297876,
 9930935,
 9930935,
 9720495,
 9313967,
 9313967,
 9103685,
 9103685,
 9702106,
 9702106,
 9289087,
 9289087,
 9154220,
 9154220,
 9210086,
 9210086,
 9705005,
 9705005,
 9316361,
 9710438,
 9710438,
 9936642,
 9936628,
 9936628,
 9307267,
 9307267,
 9250983,
 9250983,
 9237151,
 9237151,
 9110391,
 9110391,
 9282259,
 9282259,
 9278143,
 9215892,
 9166780,
 9735218,
 9735218,
 9704972,
 9704972,
 9463047,
 9463047,
 9842085,
 9842085,
 9120853,
 9120853,
 9152856,
 9720196,
 9720196,
 9947134,
 9947134,
 9316347,
 9463281,
 9124366,
 9124366,
 9231248,
 9231248,
 9181651,
 9929429,
 9929429,
 9839272,
 9839272,
 9110975,
 9110975,
 9433157,
 9000742,
 9720471,
 9720471,
 9215672,
 9215672,
 8918980,
 9227338,
 9467445,
 9467445,
 9227302,
 9123154,
 9305506,
 9305506,
 9334349,
 9334349,
 9704960,
 9704960,
 9934735,
 9934735,
 9327798,
 9251690,
 9932892,
 9932892,
 9465318,
 9465318,
 9155107,
 9155107,
 9181663,
 9315915,
 9315915,
 9720287,
 9720287,
 9936630,
 9231779,
 9196864,
 9839260,
 9839260,
 9293179,
 9060649,
 9060649,
 9149328,
 9149328,
 9471226,
 9471226,
 9778117,
 9778117,
 9456965,
 9408774,
 9857157,
 9281267,
 9281267,
 9735206,
 9735206,
 9161297,
 9161297,
 9240328,
 9267637,
 9267637,
 9222302,
 9222302,
 9074042,
 9154191,
 9930052,
 9930052,
 9139505,
 9139505,
 9465306,
 9465306,
 9240873,
 9038907,
 9038907,
 9293167,
 9401166,
 9401166,
 9110377,
 9110377,
 9434462,
 9290426,
 9290426,
 8913411,
 9702261,
 9702261,
 9181675,
 9720500,
 9471238,
 9471238,
 9231822,
 9224049,
 9224049,
 9778076,
 9778076,
 9720457,
 9720457,
 9210098,
 9210098,
 9224348,
 9702091,
 9702091,
 9695028,
 9695028,
 9231262,
 9200677,
 9351579,
 9351579,
 9316373,
 9316373,
 9008574,
 9930038,
 9930038,
 9299525,
 9299525,
 9931288,
 9337444,
 9251688,
 9702089,
 9702089,
 9947122,
 9947122,
 9236690,
 9778090,
 9778090,
 9141285,
 9141285,
 9315018,
 9315006,
 9315006]

In [20]:
len(scrubber_charter_lst)

223

In [21]:
#client send mscsmcy vessel imo list
esi_sorrento_lst = esi_sorrento['IMO'].to_list()
esi_sorrento_lst

[9129873,
 9235050,
 9839480,
 9606338,
 9399014,
 9930040,
 9708693,
 9202649,
 9897004,
 9279965,
 9401116,
 9202663,
 9647461,
 9606326,
 9398371,
 9966934,
 9399026,
 9467457,
 9351581,
 9372470,
 9225665,
 9281279,
 9606302,
 9320403,
 9230490,
 9275971,
 9060637,
 9251717,
 9708679,
 9226918,
 9230488,
 9897016,
 9955789,
 9606314,
 9349825,
 9703306,
 9372482,
 9703291,
 9279977,
 9290282,
 9754965,
 9202651,
 9320453,
 9404663,
 9279989,
 9708681,
 9309461,
 9461439,
 9484467,
 9703318]

In [22]:
len(esi_sorrento_lst)

50

In [23]:
#scrubber days mscsmcy vessel imo list
scrubber_sorrento_lst = sorrento['IMO No'].to_list()
scrubber_sorrento_lst

[9342695,
 9247766,
 9307243,
 9307243,
 9619464,
 9619464,
 9262704,
 9618317,
 9605255,
 9461441,
 9461441,
 9247742,
 9461403,
 9461403,
 9461427,
 9461427,
 9484431,
 9484431,
 9304447,
 9304447,
 9460356,
 9460356,
 9475258,
 9475258,
 9813840,
 9813840,
 9813838,
 9813838]

In [24]:
len(scrubber_sorrento_lst)

28

### checking for mscsmcy scrubber days vessel list in mscsmcy,charter,sorrento vessel lists

In [25]:
#check in msc own vessel list
res_lst = []
for element in scrubber_own_lst:
    if element not in esi_own_lst:
        res_lst.append(element)
res_lst

[]

In [26]:
len(res_lst)

0

In [27]:
#checking in charter vessel list
res_lst = []
for element in scrubber_own_lst:
    if element not in scrubber_charter_lst:
        res_lst.append(element)
res_lst

[]

In [28]:
len(res_lst)

0

In [29]:
#checking in sorrento vessel list
res_lst = []
for element in scrubber_own_lst:
    if element not in scrubber_sorrento_lst:
        res_lst.append(element)
res_lst

[9166778,
 9166778,
 9235581,
 9235581,
 9618276,
 9618276,
 9618288,
 9618288,
 9842097,
 9842097,
 9242651,
 9227297,
 9282261,
 9282261,
 9297864,
 9297864,
 9710426,
 9710426,
 9857169,
 9839284,
 9839284,
 9244881,
 9263344,
 9263344,
 9857183,
 9263332,
 9263332,
 9226932,
 9226932,
 9289099,
 9289099,
 9297876,
 9930935,
 9930935,
 9720495,
 9313967,
 9313967,
 9103685,
 9103685,
 9702106,
 9702106,
 9289087,
 9289087,
 9154220,
 9154220,
 9210086,
 9210086,
 9705005,
 9705005,
 9316361,
 9710438,
 9710438,
 9936642,
 9936628,
 9936628,
 9307267,
 9307267,
 9250983,
 9250983,
 9237151,
 9237151,
 9110391,
 9110391,
 9282259,
 9282259,
 9278143,
 9215892,
 9166780,
 9735218,
 9735218,
 9704972,
 9704972,
 9463047,
 9463047,
 9842085,
 9842085,
 9120853,
 9120853,
 9152856,
 9720196,
 9720196,
 9947134,
 9947134,
 9316347,
 9463281,
 9124366,
 9124366,
 9231248,
 9231248,
 9181651,
 9929429,
 9929429,
 9839272,
 9839272,
 9110975,
 9110975,
 9433157,
 9000742,
 9720471,
 9720471,
 9215672,
 9215672,
 8918980,
 9227338,
 9467445,
 9467445,
 9227302,
 9123154,
 9305506,
 9305506,
 9334349,
 9334349,
 9704960,
 9704960,
 9934735,
 9934735,
 9327798,
 9251690,
 9932892,
 9932892,
 9465318,
 9465318,
 9155107,
 9155107,
 9181663,
 9315915,
 9315915,
 9720287,
 9720287,
 9936630,
 9231779,
 9196864,
 9839260,
 9839260,
 9293179,
 9060649,
 9060649,
 9149328,
 9149328,
 9471226,
 9471226,
 9778117,
 9778117,
 9456965,
 9408774,
 9857157,
 9281267,
 9281267,
 9735206,
 9735206,
 9161297,
 9161297,
 9240328,
 9267637,
 9267637,
 9222302,
 9222302,
 9074042,
 9154191,
 9930052,
 9930052,
 9139505,
 9139505,
 9465306,
 9465306,
 9240873,
 9038907,
 9038907,
 9293167,
 9401166,
 9401166,
 9110377,
 9110377,
 9434462,
 9290426,
 9290426,
 8913411,
 9702261,
 9702261,
 9181675,
 9720500,
 9471238,
 9471238,
 9231822,
 9224049,
 9224049,
 9778076,
 9778076,
 9720457,
 9720457,
 9210098,
 9210098,
 9224348,
 9702091,
 9702091,
 9695028,
 9695028,
 9231262,
 9200677,
 9351579,
 9351579,
 9316373,
 9316373,
 9008574,
 9930038,
 9930038,
 9299525,
 9299525,
 9931288,
 9337444,
 9251688,
 9702089,
 9702089,
 9947122,
 9947122,
 9236690,
 9778090,
 9778090,
 9141285,
 9141285,
 9315018,
 9315006,
 9315006]

In [30]:
len(res_lst)

223

### checking for charter scrubber days vessel list in mscsmcy,charter,sorrento vessel lists

In [31]:
#check in charter vessel list
res_lst = []
for element in scrubber_charter_lst:
    if element not in esi_charter_lst:
        res_lst.append(element)
res_lst

[9166778,
 9166778,
 9235581,
 9235581,
 9618276,
 9618276,
 9618288,
 9618288,
 9842097,
 9842097,
 9242651,
 9227297,
 9282261,
 9282261,
 9297864,
 9297864,
 9710426,
 9710426,
 9857169,
 9839284,
 9839284,
 9244881,
 9263344,
 9263344,
 9857183,
 9263332,
 9263332,
 9226932,
 9226932,
 9289099,
 9289099,
 9297876,
 9930935,
 9930935,
 9720495,
 9313967,
 9313967,
 9103685,
 9103685,
 9702106,
 9702106,
 9289087,
 9289087,
 9154220,
 9154220,
 9210086,
 9210086,
 9705005,
 9705005,
 9316361,
 9710438,
 9710438,
 9936642,
 9936628,
 9936628,
 9307267,
 9307267,
 9250983,
 9250983,
 9237151,
 9237151,
 9110391,
 9110391,
 9282259,
 9282259,
 9278143,
 9215892,
 9166780,
 9735218,
 9735218,
 9704972,
 9704972,
 9463047,
 9463047,
 9842085,
 9842085,
 9120853,
 9120853,
 9152856,
 9720196,
 9720196,
 9947134,
 9947134,
 9316347,
 9463281,
 9124366,
 9124366,
 9231248,
 9231248,
 9181651,
 9929429,
 9929429,
 9839272,
 9839272,
 9110975,
 9110975,
 9433157,
 9000742,
 9720471,
 9720471,
 9215672,
 9215672,
 8918980,
 9227338,
 9467445,
 9467445,
 9227302,
 9123154,
 9305506,
 9305506,
 9334349,
 9334349,
 9704960,
 9704960,
 9934735,
 9934735,
 9327798,
 9251690,
 9932892,
 9932892,
 9465318,
 9465318,
 9155107,
 9155107,
 9181663,
 9315915,
 9315915,
 9720287,
 9720287,
 9936630,
 9231779,
 9196864,
 9839260,
 9839260,
 9293179,
 9060649,
 9060649,
 9149328,
 9149328,
 9471226,
 9471226,
 9778117,
 9778117,
 9456965,
 9408774,
 9857157,
 9281267,
 9281267,
 9735206,
 9735206,
 9161297,
 9161297,
 9240328,
 9267637,
 9267637,
 9222302,
 9222302,
 9074042,
 9154191,
 9930052,
 9930052,
 9139505,
 9139505,
 9465306,
 9465306,
 9240873,
 9038907,
 9038907,
 9293167,
 9401166,
 9401166,
 9110377,
 9110377,
 9434462,
 9290426,
 9290426,
 8913411,
 9702261,
 9702261,
 9181675,
 9720500,
 9471238,
 9471238,
 9231822,
 9224049,
 9224049,
 9778076,
 9778076,
 9720457,
 9720457,
 9210098,
 9210098,
 9224348,
 9702091,
 9702091,
 9695028,
 9695028,
 9231262,
 9200677,
 9351579,
 9351579,
 9316373,
 9316373,
 9008574,
 9930038,
 9930038,
 9299525,
 9299525,
 9931288,
 9337444,
 9251688,
 9702089,
 9702089,
 9947122,
 9947122,
 9236690,
 9778090,
 9778090,
 9141285,
 9141285,
 9315018,
 9315006,
 9315006]

In [32]:
len(res_lst)

223

In [33]:
#checking in own vessel list
res_lst = []
for element in scrubber_charter_lst:
    if element not in esi_own_lst:
        res_lst.append(element)
res_lst

[]

In [34]:
len(res_lst)

0

In [35]:
##check in sorrento vessel list
res_lst = []
for element in scrubber_charter_lst:
    if element not in esi_sorrento_lst:
        res_lst.append(element)
res_lst

[9166778,
 9166778,
 9235581,
 9235581,
 9618276,
 9618276,
 9618288,
 9618288,
 9842097,
 9842097,
 9242651,
 9227297,
 9282261,
 9282261,
 9297864,
 9297864,
 9710426,
 9710426,
 9857169,
 9839284,
 9839284,
 9244881,
 9263344,
 9263344,
 9857183,
 9263332,
 9263332,
 9226932,
 9226932,
 9289099,
 9289099,
 9297876,
 9930935,
 9930935,
 9720495,
 9313967,
 9313967,
 9103685,
 9103685,
 9702106,
 9702106,
 9289087,
 9289087,
 9154220,
 9154220,
 9210086,
 9210086,
 9705005,
 9705005,
 9316361,
 9710438,
 9710438,
 9936642,
 9936628,
 9936628,
 9307267,
 9307267,
 9250983,
 9250983,
 9237151,
 9237151,
 9110391,
 9110391,
 9282259,
 9282259,
 9278143,
 9215892,
 9166780,
 9735218,
 9735218,
 9704972,
 9704972,
 9463047,
 9463047,
 9842085,
 9842085,
 9120853,
 9120853,
 9152856,
 9720196,
 9720196,
 9947134,
 9947134,
 9316347,
 9463281,
 9124366,
 9124366,
 9231248,
 9231248,
 9181651,
 9929429,
 9929429,
 9839272,
 9839272,
 9110975,
 9110975,
 9433157,
 9000742,
 9720471,
 9720471,
 9215672,
 9215672,
 8918980,
 9227338,
 9467445,
 9467445,
 9227302,
 9123154,
 9305506,
 9305506,
 9334349,
 9334349,
 9704960,
 9704960,
 9934735,
 9934735,
 9327798,
 9251690,
 9932892,
 9932892,
 9465318,
 9465318,
 9155107,
 9155107,
 9181663,
 9315915,
 9315915,
 9720287,
 9720287,
 9936630,
 9231779,
 9196864,
 9839260,
 9839260,
 9293179,
 9060649,
 9060649,
 9149328,
 9149328,
 9471226,
 9471226,
 9778117,
 9778117,
 9456965,
 9408774,
 9857157,
 9281267,
 9281267,
 9735206,
 9735206,
 9161297,
 9161297,
 9240328,
 9267637,
 9267637,
 9222302,
 9222302,
 9074042,
 9154191,
 9930052,
 9930052,
 9139505,
 9139505,
 9465306,
 9465306,
 9240873,
 9038907,
 9038907,
 9293167,
 9401166,
 9401166,
 9110377,
 9110377,
 9434462,
 9290426,
 9290426,
 8913411,
 9702261,
 9702261,
 9181675,
 9720500,
 9471238,
 9471238,
 9231822,
 9224049,
 9224049,
 9778076,
 9778076,
 9720457,
 9720457,
 9210098,
 9210098,
 9224348,
 9702091,
 9702091,
 9695028,
 9695028,
 9231262,
 9200677,
 9351579,
 9351579,
 9316373,
 9316373,
 9008574,
 9930038,
 9930038,
 9299525,
 9299525,
 9931288,
 9337444,
 9251688,
 9702089,
 9702089,
 9947122,
 9947122,
 9236690,
 9778090,
 9778090,
 9141285,
 9141285,
 9315018,
 9315006,
 9315006]

In [36]:
len(res_lst)

223

### checking for sorrento scrubber days vessel list in mscsmcy,charter,sorrento vessel lists

In [37]:
#check in sorrento vessel list
res_lst = []
for element in scrubber_sorrento_lst:
    if element not in esi_sorrento_lst:
        res_lst.append(element)
res_lst

[9342695,
 9247766,
 9307243,
 9307243,
 9619464,
 9619464,
 9262704,
 9618317,
 9605255,
 9461441,
 9461441,
 9247742,
 9461403,
 9461403,
 9461427,
 9461427,
 9484431,
 9484431,
 9304447,
 9304447,
 9460356,
 9460356,
 9475258,
 9475258,
 9813840,
 9813840,
 9813838,
 9813838]

In [38]:
len(res_lst)

28

In [39]:
#checking in own vessel list
res_lst = []
for element in scrubber_sorrento_lst:
    if element not in esi_own_lst:
        res_lst.append(element)
res_lst

[9342695,
 9247766,
 9307243,
 9307243,
 9619464,
 9619464,
 9262704,
 9618317,
 9605255,
 9461441,
 9461441,
 9247742,
 9461403,
 9461403,
 9461427,
 9461427,
 9484431,
 9484431,
 9304447,
 9304447,
 9460356,
 9460356,
 9475258,
 9475258,
 9813840,
 9813840,
 9813838,
 9813838]

In [40]:
len(res_lst)

28

In [41]:
#checking in charter vessel list
res_lst = []
for element in scrubber_sorrento_lst:
    if element not in esi_charter_lst:
        res_lst.append(element)
res_lst

[]

In [42]:
len(res_lst)

0