In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
#client send fuel distance data ,(otherwise tell software team to download it)
import pandas as pd
data = pd.read_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\CLIENT FILE\Fuel and Distance.xlsx")
data

            Row Labels      IMO  Sum of Total Fuel  Sum of MILES BY GPS
0                ALANA  9297589          1711.0460         20454.500203
1            ANASTASIA  9625970          2843.9400         24013.600008
2        AS CALIFORNIA  9342695          5373.8100         42556.100127
3         ATHENS GLORY  9247766         10082.6200         36149.699999
4          CAPE SOUNIO  9727625         10604.7930         44180.000183
..                 ...      ...                ...                  ...
419  SPIRIT OF KOLKATA  9813838          2022.7810         28585.599991
420       WEC DE HOOGH  9315018          2317.9700         29138.300045
421     WEC FRANS HALS  9326964          2402.4300         31596.300025
422      WEC MONDRIAAN  9354363          2630.3200         33688.300180
423       WEC VAN RIJN  9315006          2048.7996         21498.500059

[424 rows x 4 columns]

#### client send fuel distance data ,(otherwise tell software team to download it)

In [4]:
data.dtypes

Row Labels              object
IMO                      int64
Sum of Total Fuel      float64
Sum of MILES BY GPS    float64
dtype: object

In [5]:
data.rename(columns = {'Row Labels':'Ship Name', 'IMO':'imo',
                              'Sum of MILES BY GPS':'sailedDistance','Sum of Total Fuel':'consumption'}, inplace = True)

### Change the startDate as per the period

In [6]:
data['startDate'] = "2023-07-01T00:00:00.000Z"
data

,Ship Name,imo,consumption,sailedDistance,startDate
0,ALANA,9297589,1711.0460,20454.500203,2023-07-01T00:00:00.000Z
1,ANASTASIA,9625970,2843.9400,24013.600008,2023-07-01T00:00:00.000Z
2,AS CALIFORNIA,9342695,5373.8100,42556.100127,2023-07-01T00:00:00.000Z
3,ATHENS GLORY,9247766,10082.6200,36149.699999,2023-07-01T00:00:00.000Z
4,CAPE SOUNIO,9727625,10604.7930,44180.000183,2023-07-01T00:00:00.000Z
...,...,...,...,...,...
419,SPIRIT OF KOLKATA,9813838,2022.7810,28585.599991,2023-07-01T00:00:00.000Z
420,WEC DE HOOGH,9315018,2317.9700,29138.300045,2023-07-01T00:00:00.000Z
421,WEC FRANS HALS,9326964,2402.4300,31596.300025,2023-07-01T00:00:00.000Z
422,WEC MONDRIAAN,9354363,2630.3200,33688.300180,2023-07-01T00:00:00.000Z
423,WEC VAN RIJN,9315006,2048.7996,21498.500059,2023-07-01T00:00:00.000Z

In [7]:
#vessel list first client send
esi = pd.read_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\CLIENT FILE\ESI CURRENT VESSELS.xlsx")
esi

         IMO    Fleet          Vessel Scrubber Unnamed: 4
0    9297589  CHARTER           ALANA       No        NaN
1    9625970        9       ANASTASIA       No        NaN
2    9342695  CHARTER   AS California       No        NaN
3    9314947  CHARTER     AS CAMELLIA      Yes        NaN
4    9321897       12    MSC NADIA IV       No        NaN
..       ...      ...             ...      ...        ...
429  9198587       14    MSC CHIARA X       No        NaN
430  9299032       19  MSC FALCON III       No        NaN
431  9962598       15     MSC LORENZA      Yes        NaN
432  9967263       23      MSC MAPUTO      Yes        NaN
433  9214898       14    MSC NICOLE X       No        NaN

[434 rows x 5 columns]

In [8]:
#charter
esi_charter = esi[esi['Fleet'] =='CHARTER']
#sorrento
esi_sorrento = esi[esi['Fleet'] == 'SORRENTO']
#msc own vessels
esi_own = esi[(esi.Fleet !='CHARTER') & (esi.Fleet != 'SORRENTO')]

In [9]:
esi_charter

         IMO    Fleet             Vessel Scrubber Unnamed: 4
0    9297589  CHARTER              ALANA       No        NaN
2    9342695  CHARTER      AS California       No        NaN
3    9314947  CHARTER        AS CAMELLIA      Yes        NaN
5    9247766  CHARTER       ATHENS GLORY      Yes        NaN
7    9727625  CHARTER        CAPE SOUNIO       No        NaN
8    9706205  CHARTER       CAPE TAINARO       No        NaN
9    9293791  CHARTER     CONTI CHIVALRY       No        NaN
10   9308613  CHARTER       Contship Fun       No        NaN
11   9373917  CHARTER       CONTSHIP OAK       No        NaN
12   9357810  CHARTER           EF Emira       No        NaN
13   9153862  CHARTER        EPAMINONDAS       No        NaN
14   9301469  CHARTER             Etoile       No        NaN
17   9256482  CHARTER         GSL NINGBO       No        NaN
18   9357793  CHARTER        Hansa Lanka       No        NaN
19   9535163  CHARTER    Henrika Schulte       No        NaN
20   9535187  CHARTER    Hermann Schulte       No        NaN
21   9535204  CHARTER     Hubert Schulte       No        NaN
23   9225770  CHARTER              Julie       No        NaN
24   9085558  CHARTER         Karlskrona       No        NaN
25   9085546  CHARTER             KLEVEN       No        NaN
26   9085534  CHARTER              KOTKA       No        NaN
27   9085522  CHARTER               KURE       No        NaN
28   9307243  CHARTER           Le Havre      Yes        NaN
29   9236535  CHARTER         Marianetta       No        NaN
30   9162227  CHARTER         MARIANNA I       No        NaN
31   9148025  CHARTER          MED AYDIN       No        NaN
32   9256365  CHARTER          MED CESME       No        NaN
33   9106479  CHARTER          MED CORLU       No        NaN
34   9106493  CHARTER        MED Denizli       No        NaN
35   9225794  CHARTER         MED SAMSUN       No        NaN
36   9141780  CHARTER        MED TRABZON       No        NaN
44   9619464  CHARTER         MSC AGADIR      Yes        NaN
71   9247730  CHARTER         MSC APOLLO      Yes        NaN
72   9262704  CHARTER       MSC AQUARIUS      Yes        NaN
78   9618317  CHARTER          MSC ATHOS      Yes        NaN
82   9605255  CHARTER           MSC AZOV      Yes        NaN
85   9480186  CHARTER      MSC BARCELONA       No        NaN
86   9461441  CHARTER           MSC BARI      Yes        NaN
94   9247742  CHARTER      MSC BOSPHORUS      Yes        NaN
100  9480203  CHARTER          MSC CADIZ       No        NaN
126  9480215  CHARTER         MSC CORUNA       No        NaN
129  9247754  CHARTER    MSC DARDANELLES      Yes        NaN
187  9225641  CHARTER          MSC ILONA       No        NaN
198  9135638  CHARTER         MED MERSIN       No        NaN
225  9461403  CHARTER      MSC LA SPEZIA      Yes        NaN
237  9461427  CHARTER        MSC LIVORNO      Yes        NaN
248  9480198  CHARTER         MSC MADRID       No        NaN
284  9349796  CHARTER       MSC MONTEREY       No        NaN
325  9256470  CHARTER        MSC QINGDAO      Yes        NaN
328  9484431  CHARTER        MSC RAVENNA      Yes        NaN
337  9304447  CHARTER           MSC ROMA      Yes        NaN
355  9460356  CHARTER         MSC SAVONA      Yes        NaN
387  9475258  CHARTER        MSC TARANTO      Yes        NaN
391  9285471  CHARTER        MSC TIANJIN       No        NaN
408  9480227  CHARTER           MSC VIGO       No        NaN
423  9813840  CHARTER  Spirit of Chennai      Yes        NaN
424  9813838  CHARTER  Spirit of Kolkata      Yes        NaN

In [10]:
esi_sorrento

         IMO     Fleet                 Vessel Scrubber Unnamed: 4
50   9129873  SORRENTO              MSC ALEXA       No        NaN
54   9235050  SORRENTO             MSC ALYSSA       No        NaN
56   9839480  SORRENTO              MSC AMBRA      Yes        NaN
58   9606338  SORRENTO          MSC AMSTERDAM       No        NaN
88   9399014  SORRENTO           MSC BEATRICE      Yes        NaN
113  9930040  SORRENTO  MSC CELESTINO MARESCA      Yes        NaN
119  9708693  SORRENTO              MSC CLARA      Yes        NaN
134  9202649  SORRENTO              MSC DIEGO       No        NaN
135  9897004  SORRENTO            MSC DILETTA      Yes        NaN
159  9279965  SORRENTO           MSC FABIENNE       No        NaN
165  9401116  SORRENTO          MSC FRANCESCA      Yes        NaN
170  9202663  SORRENTO               MSC GINA       No        NaN
177  9647461  SORRENTO            MSC HAMBURG      Yes        NaN
195  9606326  SORRENTO           MSC ISTANBUL       No        NaN
196  9398371  SORRENTO              MSC IVANA      Yes        NaN
204  9966934  SORRENTO              MSC JIANI       No        NaN
211  9399026  SORRENTO             MSC KALINA      Yes        NaN
214  9467457  SORRENTO              MSC KATIE      Yes        NaN
220  9351581  SORRENTO                MSC KIM       No        NaN
223  9372470  SORRENTO            MSC KRYSTAL       No        NaN
228  9225665  SORRENTO              MSC LAURA      Yes        NaN
236  9281279  SORRENTO               MSC LISA       No        NaN
238  9606302  SORRENTO             MSC LONDON      Yes        NaN
239  9320403  SORRENTO             MSC LORENA       No        NaN
242  9230490  SORRENTO            MSC LORETTA      Yes        NaN
262  9275971  SORRENTO             MSC MARINA       No        NaN
263  9060637  SORRENTO            MSC MARTINA       No        NaN
268  9251717  SORRENTO            MSC MAUREEN       No        NaN
270  9708679  SORRENTO               MSC MAYA      Yes        NaN
272  9226918  SORRENTO            MSC MELISSA      Yes        NaN
276  9230488  SORRENTO           MSC MICHAELA      Yes        NaN
278  9897016  SORRENTO           MSC MICHELLE      Yes        NaN
287  9955789  SORRENTO             MSC NAHARA      Yes        NaN
292  9606314  SORRENTO           MSC NEW YORK       No        NaN
302  9349825  SORRENTO              MSC NURIA       No        NaN
306  9703306  SORRENTO             MSC OLIVER       No        NaN
307  9372482  SORRENTO             MSC ORIANE       No        NaN
310  9703291  SORRENTO              MSC OSCAR      Yes        NaN
319  9279977  SORRENTO            MSC POH LIN       No        NaN
326  9290282  SORRENTO            MSC RACHELE       No        NaN
331  9754965  SORRENTO               MSC REEF      Yes        NaN
332  9202651  SORRENTO             MSC REGINA       No        NaN
339  9320453  SORRENTO            MSC ROSARIA       No        NaN
375  9404663  SORRENTO              MSC SONIA      Yes        NaN
378  9279989  SORRENTO             MSC STELLA      Yes        NaN
381  9708681  SORRENTO              MSC SVEVA      Yes        NaN
393  9309461  SORRENTO             MSC TOMOKO       No        NaN
403  9461439  SORRENTO            MSC VALERIA       No        NaN
404  9484467  SORRENTO             MSC VANDYA       No        NaN
422  9703318  SORRENTO                MSC ZOE      Yes        NaN

In [11]:
esi_own

         IMO Fleet          Vessel Scrubber Unnamed: 4
1    9625970     9       ANASTASIA       No        NaN
4    9321897    12    MSC NADIA IV       No        NaN
6    9334519    15   MSC ZAINA III       No        NaN
15   9453298    14      GOLD HOSHI       No        NaN
16   9463205    14     GOLD KOCHAV       No        NaN
..       ...   ...             ...      ...        ...
429  9198587    14    MSC CHIARA X       No        NaN
430  9299032    19  MSC FALCON III       No        NaN
431  9962598    15     MSC LORENZA      Yes        NaN
432  9967263    23      MSC MAPUTO      Yes        NaN
433  9214898    14    MSC NICOLE X       No        NaN

[327 rows x 5 columns]

In [12]:
esi_own_lst = esi_own['IMO'].to_list()
esi_own_lst

[9625970,
 9321897,
 9334519,
 9453298,
 9463205,
 9180205,
 9330226,
 9166778,
 9190119,
 8512906,
 9235581,
 9169055,
 9932921,
 9057173,
 9618276,
 9770751,
 9123166,
 9301990,
 9618288,
 9842097,
 9196852,
 9319600,
 9008603,
 9242651,
 9261827,
 9259379,
 9306275,
 9227297,
 8521402,
 9169122,
 9282261,
 9254848,
 9323041,
 9297864,
 9710426,
 9857169,
 9839284,
 9244881,
 9162631,
 9263344,
 8913447,
 8512891,
 9857183,
 9263332,
 9226932,
 9360764,
 9289099,
 9203904,
 9297876,
 9770749,
 9930935,
 9720495,
 9313967,
 9103685,
 9702106,
 9289087,
 9169043,
 9262546,
 9102722,
 9360271,
 9154220,
 9210086,
 9625944,
 9946879,
 9295397,
 9253038,
 9705005,
 9229300,
 9316361,
 9710438,
 9299537,
 9198587,
 9936642,
 9936628,
 9113446,
 9301550,
 9241463,
 9307267,
 9426817,
 9295165,
 9250983,
 9927287,
 9930959,
 9200689,
 9262560,
 9306263,
 9720201,
 9102746,
 9237151,
 9301328,
 9444285,
 9294824,
 9110391,
 9169029,
 9282259,
 9236688,
 9278143,
 9064750,
 9215892,
 9166780,
 9735218,
 9704972,
 8917778,
 9326823,
 9334832,
 9463047,
 9004231,
 8201648,
 9302633,
 9842085,
 9299032,
 9290402,
 9120853,
 8413875,
 9344708,
 9152856,
 9289051,
 9153850,
 9720196,
 9947134,
 9210062,
 9415296,
 9631876,
 9283708,
 9316347,
 9350317,
 9127540,
 9463281,
 9224946,
 9962562,
 9962586,
 9197545,
 9124366,
 9231248,
 9181651,
 9929429,
 8201624,
 9839272,
 9154206,
 9110975,
 9433157,
 9000742,
 9720471,
 9622007,
 9215672,
 8918980,
 9039250,
 9227338,
 9275036,
 9450351,
 9244946,
 9236585,
 9232656,
 9467445,
 9227302,
 9110389,
 9242637,
 9927299,
 9123154,
 9051507,
 9305506,
 9439735,
 9064748,
 9162643,
 9947158,
 9347762,
 9383223,
 9334349,
 9704960,
 9237498,
 9962598,
 9934735,
 9327798,
 9251690,
 9308625,
 9400148,
 9231119,
 9625932,
 9252553,
 9252541,
 8201636,
 9238882,
 8918966,
 9967263,
 9932892,
 9465318,
 8616520,
 9155107,
 9964194,
 9962574,
 9540077,
 9169031,
 9181663,
 9315915,
 9720287,
 9102710,
 9936630,
 9231779,
 9169067,
 9720512,
 9196864,
 9839260,
 9293179,
 9932050,
 9060649,
 9294991,
 9149328,
 9307839,
 9471226,
 8918954,
 9278155,
 9214898,
 9228576,
 9315886,
 9308584,
 9326768,
 9084607,
 9778117,
 9946843,
 9256315,
 9456965,
 9336359,
 9408774,
 9857157,
 9281267,
 9735206,
 9336165,
 9239903,
 9161297,
 9240328,
 9256391,
 9267637,
 9222302,
 9074042,
 9139086,
 9299020,
 9154191,
 9450325,
 9235402,
 9930052,
 9139505,
 9465306,
 9240873,
 9419644,
 9038907,
 9293167,
 9957359,
 9337676,
 8714205,
 9401166,
 9491616,
 9110377,
 9434462,
 9222106,
 9290426,
 8913411,
 9702261,
 9181675,
 8715857,
 9241451,
 9720500,
 9116369,
 9471238,
 9292175,
 9231822,
 8913423,
 9036002,
 9180968,
 9224049,
 9778105,
 9778076,
 9720457,
 9210098,
 9224348,
 9793947,
 9162277,
 9927275,
 9702091,
 9695028,
 9220328,
 9259393,
 9210050,
 8918978,
 9330068,
 9231262,
 9200677,
 9308601,
 9351579,
 9316373,
 9008574,
 9189366,
 9930038,
 9248928,
 9299525,
 9295177,
 9230775,
 9931288,
 9337444,
 9302619,
 9302621,
 9315836,
 9227340,
 9251688,
 9242625,
 9238739,
 9304708,
 9146479,
 9908059,
 9702089,
 9947122,
 9908047,
 9236690,
 9288409,
 9778090,
 9322011,
 9146467,
 9344564,
 9141285,
 9315018,
 9326964,
 9354363,
 9315006,
 9198587,
 9299032,
 9962598,
 9967263,
 9214898]

In [13]:
len(esi_own_lst)

327

In [14]:
esi_charter_lst = esi_charter['IMO'].to_list()
esi_charter_lst

[9297589,
 9342695,
 9314947,
 9247766,
 9727625,
 9706205,
 9293791,
 9308613,
 9373917,
 9357810,
 9153862,
 9301469,
 9256482,
 9357793,
 9535163,
 9535187,
 9535204,
 9225770,
 9085558,
 9085546,
 9085534,
 9085522,
 9307243,
 9236535,
 9162227,
 9148025,
 9256365,
 9106479,
 9106493,
 9225794,
 9141780,
 9619464,
 9247730,
 9262704,
 9618317,
 9605255,
 9480186,
 9461441,
 9247742,
 9480203,
 9480215,
 9247754,
 9225641,
 9135638,
 9461403,
 9461427,
 9480198,
 9349796,
 9256470,
 9484431,
 9304447,
 9460356,
 9475258,
 9285471,
 9480227,
 9813840,
 9813838]

In [15]:
len(esi_charter_lst)

57

In [16]:
esi_sorrento_lst = esi_sorrento['IMO'].to_list()
esi_sorrento_lst

[9129873,
 9235050,
 9839480,
 9606338,
 9399014,
 9930040,
 9708693,
 9202649,
 9897004,
 9279965,
 9401116,
 9202663,
 9647461,
 9606326,
 9398371,
 9966934,
 9399026,
 9467457,
 9351581,
 9372470,
 9225665,
 9281279,
 9606302,
 9320403,
 9230490,
 9275971,
 9060637,
 9251717,
 9708679,
 9226918,
 9230488,
 9897016,
 9955789,
 9606314,
 9349825,
 9703306,
 9372482,
 9703291,
 9279977,
 9290282,
 9754965,
 9202651,
 9320453,
 9404663,
 9279989,
 9708681,
 9309461,
 9461439,
 9484467,
 9703318]

In [17]:
len(esi_sorrento_lst)

50

### seperate msc own vessel,charter,sorrento fuel distance data based on above list

In [18]:
#msc own vessels
mscown = data[data['imo'].isin(esi_own_lst)] 
mscown

,Ship Name,imo,consumption,sailedDistance,startDate
1,ANASTASIA,9625970,2843.9400,24013.600008,2023-07-01T00:00:00.000Z
12,GOLD HOSHI,9453298,6935.7000,57064.019953,2023-07-01T00:00:00.000Z
13,GOLD KOCHAV,9463205,6400.7000,59456.200028,2023-07-01T00:00:00.000Z
19,JOLLY BLUE,9180205,3082.5300,30002.399850,2023-07-01T00:00:00.000Z
34,MSC ABIGAIL F,9330226,2527.5900,32914.800017,2023-07-01T00:00:00.000Z
...,...,...,...,...,...
416,MSC ZAINA III,9334519,3689.9000,32641.300047,2023-07-01T00:00:00.000Z
420,WEC DE HOOGH,9315018,2317.9700,29138.300045,2023-07-01T00:00:00.000Z
421,WEC FRANS HALS,9326964,2402.4300,31596.300025,2023-07-01T00:00:00.000Z
422,WEC MONDRIAAN,9354363,2630.3200,33688.300180,2023-07-01T00:00:00.000Z
423,WEC VAN RIJN,9315006,2048.7996,21498.500059,2023-07-01T00:00:00.000Z

In [19]:
mscown = mscown[['startDate','imo','consumption','sailedDistance']]
mscown

                    startDate      imo  consumption  sailedDistance
1    2023-07-01T00:00:00.000Z  9625970    2843.9400    24013.600008
12   2023-07-01T00:00:00.000Z  9453298    6935.7000    57064.019953
13   2023-07-01T00:00:00.000Z  9463205    6400.7000    59456.200028
19   2023-07-01T00:00:00.000Z  9180205    3082.5300    30002.399850
34   2023-07-01T00:00:00.000Z  9330226    2527.5900    32914.800017
..                        ...      ...          ...             ...
416  2023-07-01T00:00:00.000Z  9334519    3689.9000    32641.300047
420  2023-07-01T00:00:00.000Z  9315018    2317.9700    29138.300045
421  2023-07-01T00:00:00.000Z  9326964    2402.4300    31596.300025
422  2023-07-01T00:00:00.000Z  9354363    2630.3200    33688.300180
423  2023-07-01T00:00:00.000Z  9315006    2048.7996    21498.500059

[320 rows x 4 columns]

In [20]:
import numpy as np
mscown['consumption'] = np.round(mscown['consumption'], decimals = 0)
mscown['sailedDistance'] = np.round(mscown['sailedDistance'], decimals = 0)
mscown

                    startDate      imo  consumption  sailedDistance
1    2023-07-01T00:00:00.000Z  9625970       2844.0         24014.0
12   2023-07-01T00:00:00.000Z  9453298       6936.0         57064.0
13   2023-07-01T00:00:00.000Z  9463205       6401.0         59456.0
19   2023-07-01T00:00:00.000Z  9180205       3083.0         30002.0
34   2023-07-01T00:00:00.000Z  9330226       2528.0         32915.0
..                        ...      ...          ...             ...
416  2023-07-01T00:00:00.000Z  9334519       3690.0         32641.0
420  2023-07-01T00:00:00.000Z  9315018       2318.0         29138.0
421  2023-07-01T00:00:00.000Z  9326964       2402.0         31596.0
422  2023-07-01T00:00:00.000Z  9354363       2630.0         33688.0
423  2023-07-01T00:00:00.000Z  9315006       2049.0         21499.0

[320 rows x 4 columns]

In [21]:
mscown.dtypes

startDate          object
imo                 int64
consumption       float64
sailedDistance    float64
dtype: object

In [27]:
mscown.to_csv(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\FUEL DISTANCE\mscown_fuel_distance.csv",index=False)

In [28]:
#charter
charter = data[data['imo'].isin(esi_charter_lst)] 
charter

,Ship Name,imo,consumption,sailedDistance,startDate
0,ALANA,9297589,1711.04600,20454.500203,2023-07-01T00:00:00.000Z
2,AS CALIFORNIA,9342695,5373.81000,42556.100127,2023-07-01T00:00:00.000Z
3,ATHENS GLORY,9247766,10082.62000,36149.699999,2023-07-01T00:00:00.000Z
4,CAPE SOUNIO,9727625,10604.79300,44180.000183,2023-07-01T00:00:00.000Z
5,CAPE TAINARO,9706205,9089.92000,37415.300192,2023-07-01T00:00:00.000Z
6,CONTI CHIVALRY,9293791,12555.49000,45516.269999,2023-07-01T00:00:00.000Z
7,CONTSHIP FUN,9308613,2195.43000,23587.599996,2023-07-01T00:00:00.000Z
8,CONTSHIP OAK,9373917,1245.26000,9238.599955,2023-07-01T00:00:00.000Z
9,EF EMIRA,9357810,2202.60900,18273.300093,2023-07-01T00:00:00.000Z
10,EPAMINONDAS,9153862,8946.30000,42655.200288,2023-07-01T00:00:00.000Z
11,ETOILE,9301469,3645.02400,34754.400020,2023-07-01T00:00:00.000Z
14,GSL NINGBO,9256482,14823.29000,50645.999747,2023-07-01T00:00:00.000Z
15,HANSA LANKA,9357793,3694.73000,34170.999942,2023-07-01T00:00:00.000Z
16,HENRIKA SCHULTE,9535163,7398.83000,45951.599978,2023-07-01T00:00:00.000Z
17,HERMANN SCHULTE,9535187,8281.54000,46857.599776,2023-07-01T00:00:00.000Z
18,HUBERT SCHULTE,9535204,7112.89900,45934.300035,2023-07-01T00:00:00.000Z
20,JULIE,9225770,4122.16000,35241.300073,2023-07-01T00:00:00.000Z
21,KLEVEN,9085546,8358.30300,39446.630017,2023-07-01T00:00:00.000Z
22,KOTKA,9085534,9363.64000,43129.000174,2023-07-01T00:00:00.000Z
23,KURE,9085522,8339.20300,39787.999833,2023-07-01T00:00:00.000Z
24,LE HAVRE,9307243,13910.34000,47926.500120,2023-07-01T00:00:00.000Z
25,MARIANETTA,9236535,8413.20100,48184.999939,2023-07-01T00:00:00.000Z
26,MARIANNA I,9162227,9893.89000,42078.299794,2023-07-01T00:00:00.000Z
27,MED AYDIN,9148025,2079.90400,24459.130096,2023-07-01T00:00:00.000Z
28,MED CESME,9256365,1781.66000,17323.350076,2023-07-01T00:00:00.000Z
29,MED CORLU,9106479,1727.70000,19329.809911,2023-07-01T00:00:00.000Z
30,MED DENIZLI,9106493,1823.33996,21360.399997,2023-07-01T00:00:00.000Z
31,MED MERSIN,9135638,2481.69000,22453.929966,2023-07-01T00:00:00.000Z
32,MED SAMSUN,9225794,3049.32700,26802.199967,2023-07-01T00:00:00.000Z
33,MED TRABZON,9141780,2527.86200,25596.400021,2023-07-01T00:00:00.000Z
41,MSC AGADIR,9619464,10865.95000,34069.200122,2023-07-01T00:00:00.000Z
68,MSC AQUARIUS,9262704,7922.07000,37231.000000,2023-07-01T00:00:00.000Z
74,MSC ATHOS,9618317,10176.92400,36446.499836,2023-07-01T00:00:00.000Z
78,MSC AZOV,9605255,12119.35500,49026.999914,2023-07-01T00:00:00.000Z
81,MSC BARCELONA,9480186,7789.08200,35225.500080,2023-07-01T00:00:00.000Z
82,MSC BARI,9461441,16896.04000,49212.799870,2023-07-01T00:00:00.000Z
90,MSC BOSPHORUS,9247742,11510.91000,46947.000213,2023-07-01T00:00:00.000Z
96,MSC CADIZ,9480203,8412.01400,40454.000062,2023-07-01T00:00:00.000Z
121,MSC CORUNA,9480215,8113.13110,38784.899986,2023-07-01T00:00:00.000Z
124,MSC DARDANELLES,9247754,4784.27500,20872.000039,2023-07-01T00:00:00.000Z
182,MSC ILONA,9225641,7671.52000,37935.500159,2023-07-01T00:00:00.000Z
219,MSC LA SPEZIA,9461403,16965.85000,44939.400166,2023-07-01T00:00:00.000Z
231,MSC LIVORNO,9461427,15283.43800,48856.500051,2023-07-01T00:00:00.000Z
242,MSC MADRID,9480198,7963.45000,39258.299958,2023-07-01T00:00:00.000Z
278,MSC MONTEREY,9349796,5222.10000,30009.400064,2023-07-01T00:00:00.000Z
319,MSC QINGDAO,9256470,11565.43000,41373.300017,2023-07-01T00:00:00.000Z
322,MSC RAVENNA,9484431,11871.26700,40886.299998,2023-07-01T00:00:00.000Z
331,MSC ROMA,9304447,12292.78300,47244.999786,2023-07-01T00:00:00.000Z
349,MSC SAVONA,9460356,15337.19100,43014.079998,2023-07-01T00:00:00.000Z
381,MSC TARANTO,9475258,16987.55500,51066.099950,2023-07-01T00:00:00.000Z
385,MSC TIANJIN,9285471,9956.22000,38609.200019,2023-07-01T00:00:00.000Z
402,MSC VIGO,9480227,9475.34000,44602.700002,2023-07-01T00:00:00.000Z
418,SPIRIT OF CHENNAI,9813840,2224.62200,26957.899945,2023-07-01T00:00:00.000Z
419,SPIRIT OF KOLKATA,9813838,2022.78100,28585.599991,2023-07-01T00:00:00.000Z

In [29]:
charter.shape

(54, 5)

In [30]:
charter = charter[['startDate','imo','consumption','sailedDistance']]
charter

                    startDate      imo  consumption  sailedDistance
0    2023-07-01T00:00:00.000Z  9297589   1711.04600    20454.500203
2    2023-07-01T00:00:00.000Z  9342695   5373.81000    42556.100127
3    2023-07-01T00:00:00.000Z  9247766  10082.62000    36149.699999
4    2023-07-01T00:00:00.000Z  9727625  10604.79300    44180.000183
5    2023-07-01T00:00:00.000Z  9706205   9089.92000    37415.300192
6    2023-07-01T00:00:00.000Z  9293791  12555.49000    45516.269999
7    2023-07-01T00:00:00.000Z  9308613   2195.43000    23587.599996
8    2023-07-01T00:00:00.000Z  9373917   1245.26000     9238.599955
9    2023-07-01T00:00:00.000Z  9357810   2202.60900    18273.300093
10   2023-07-01T00:00:00.000Z  9153862   8946.30000    42655.200288
11   2023-07-01T00:00:00.000Z  9301469   3645.02400    34754.400020
14   2023-07-01T00:00:00.000Z  9256482  14823.29000    50645.999747
15   2023-07-01T00:00:00.000Z  9357793   3694.73000    34170.999942
16   2023-07-01T00:00:00.000Z  9535163   7398.83000    45951.599978
17   2023-07-01T00:00:00.000Z  9535187   8281.54000    46857.599776
18   2023-07-01T00:00:00.000Z  9535204   7112.89900    45934.300035
20   2023-07-01T00:00:00.000Z  9225770   4122.16000    35241.300073
21   2023-07-01T00:00:00.000Z  9085546   8358.30300    39446.630017
22   2023-07-01T00:00:00.000Z  9085534   9363.64000    43129.000174
23   2023-07-01T00:00:00.000Z  9085522   8339.20300    39787.999833
24   2023-07-01T00:00:00.000Z  9307243  13910.34000    47926.500120
25   2023-07-01T00:00:00.000Z  9236535   8413.20100    48184.999939
26   2023-07-01T00:00:00.000Z  9162227   9893.89000    42078.299794
27   2023-07-01T00:00:00.000Z  9148025   2079.90400    24459.130096
28   2023-07-01T00:00:00.000Z  9256365   1781.66000    17323.350076
29   2023-07-01T00:00:00.000Z  9106479   1727.70000    19329.809911
30   2023-07-01T00:00:00.000Z  9106493   1823.33996    21360.399997
31   2023-07-01T00:00:00.000Z  9135638   2481.69000    22453.929966
32   2023-07-01T00:00:00.000Z  9225794   3049.32700    26802.199967
33   2023-07-01T00:00:00.000Z  9141780   2527.86200    25596.400021
41   2023-07-01T00:00:00.000Z  9619464  10865.95000    34069.200122
68   2023-07-01T00:00:00.000Z  9262704   7922.07000    37231.000000
74   2023-07-01T00:00:00.000Z  9618317  10176.92400    36446.499836
78   2023-07-01T00:00:00.000Z  9605255  12119.35500    49026.999914
81   2023-07-01T00:00:00.000Z  9480186   7789.08200    35225.500080
82   2023-07-01T00:00:00.000Z  9461441  16896.04000    49212.799870
90   2023-07-01T00:00:00.000Z  9247742  11510.91000    46947.000213
96   2023-07-01T00:00:00.000Z  9480203   8412.01400    40454.000062
121  2023-07-01T00:00:00.000Z  9480215   8113.13110    38784.899986
124  2023-07-01T00:00:00.000Z  9247754   4784.27500    20872.000039
182  2023-07-01T00:00:00.000Z  9225641   7671.52000    37935.500159
219  2023-07-01T00:00:00.000Z  9461403  16965.85000    44939.400166
231  2023-07-01T00:00:00.000Z  9461427  15283.43800    48856.500051
242  2023-07-01T00:00:00.000Z  9480198   7963.45000    39258.299958
278  2023-07-01T00:00:00.000Z  9349796   5222.10000    30009.400064
319  2023-07-01T00:00:00.000Z  9256470  11565.43000    41373.300017
322  2023-07-01T00:00:00.000Z  9484431  11871.26700    40886.299998
331  2023-07-01T00:00:00.000Z  9304447  12292.78300    47244.999786
349  2023-07-01T00:00:00.000Z  9460356  15337.19100    43014.079998
381  2023-07-01T00:00:00.000Z  9475258  16987.55500    51066.099950
385  2023-07-01T00:00:00.000Z  9285471   9956.22000    38609.200019
402  2023-07-01T00:00:00.000Z  9480227   9475.34000    44602.700002
418  2023-07-01T00:00:00.000Z  9813840   2224.62200    26957.899945
419  2023-07-01T00:00:00.000Z  9813838   2022.78100    28585.599991

In [31]:
charter['consumption'] = np.round(charter['consumption'], decimals = 0)
charter['sailedDistance'] = np.round(charter['sailedDistance'], decimals = 0)
charter

                    startDate      imo  consumption  sailedDistance
0    2023-07-01T00:00:00.000Z  9297589       1711.0         20455.0
2    2023-07-01T00:00:00.000Z  9342695       5374.0         42556.0
3    2023-07-01T00:00:00.000Z  9247766      10083.0         36150.0
4    2023-07-01T00:00:00.000Z  9727625      10605.0         44180.0
5    2023-07-01T00:00:00.000Z  9706205       9090.0         37415.0
6    2023-07-01T00:00:00.000Z  9293791      12555.0         45516.0
7    2023-07-01T00:00:00.000Z  9308613       2195.0         23588.0
8    2023-07-01T00:00:00.000Z  9373917       1245.0          9239.0
9    2023-07-01T00:00:00.000Z  9357810       2203.0         18273.0
10   2023-07-01T00:00:00.000Z  9153862       8946.0         42655.0
11   2023-07-01T00:00:00.000Z  9301469       3645.0         34754.0
14   2023-07-01T00:00:00.000Z  9256482      14823.0         50646.0
15   2023-07-01T00:00:00.000Z  9357793       3695.0         34171.0
16   2023-07-01T00:00:00.000Z  9535163       7399.0         45952.0
17   2023-07-01T00:00:00.000Z  9535187       8282.0         46858.0
18   2023-07-01T00:00:00.000Z  9535204       7113.0         45934.0
20   2023-07-01T00:00:00.000Z  9225770       4122.0         35241.0
21   2023-07-01T00:00:00.000Z  9085546       8358.0         39447.0
22   2023-07-01T00:00:00.000Z  9085534       9364.0         43129.0
23   2023-07-01T00:00:00.000Z  9085522       8339.0         39788.0
24   2023-07-01T00:00:00.000Z  9307243      13910.0         47927.0
25   2023-07-01T00:00:00.000Z  9236535       8413.0         48185.0
26   2023-07-01T00:00:00.000Z  9162227       9894.0         42078.0
27   2023-07-01T00:00:00.000Z  9148025       2080.0         24459.0
28   2023-07-01T00:00:00.000Z  9256365       1782.0         17323.0
29   2023-07-01T00:00:00.000Z  9106479       1728.0         19330.0
30   2023-07-01T00:00:00.000Z  9106493       1823.0         21360.0
31   2023-07-01T00:00:00.000Z  9135638       2482.0         22454.0
32   2023-07-01T00:00:00.000Z  9225794       3049.0         26802.0
33   2023-07-01T00:00:00.000Z  9141780       2528.0         25596.0
41   2023-07-01T00:00:00.000Z  9619464      10866.0         34069.0
68   2023-07-01T00:00:00.000Z  9262704       7922.0         37231.0
74   2023-07-01T00:00:00.000Z  9618317      10177.0         36446.0
78   2023-07-01T00:00:00.000Z  9605255      12119.0         49027.0
81   2023-07-01T00:00:00.000Z  9480186       7789.0         35226.0
82   2023-07-01T00:00:00.000Z  9461441      16896.0         49213.0
90   2023-07-01T00:00:00.000Z  9247742      11511.0         46947.0
96   2023-07-01T00:00:00.000Z  9480203       8412.0         40454.0
121  2023-07-01T00:00:00.000Z  9480215       8113.0         38785.0
124  2023-07-01T00:00:00.000Z  9247754       4784.0         20872.0
182  2023-07-01T00:00:00.000Z  9225641       7672.0         37936.0
219  2023-07-01T00:00:00.000Z  9461403      16966.0         44939.0
231  2023-07-01T00:00:00.000Z  9461427      15283.0         48857.0
242  2023-07-01T00:00:00.000Z  9480198       7963.0         39258.0
278  2023-07-01T00:00:00.000Z  9349796       5222.0         30009.0
319  2023-07-01T00:00:00.000Z  9256470      11565.0         41373.0
322  2023-07-01T00:00:00.000Z  9484431      11871.0         40886.0
331  2023-07-01T00:00:00.000Z  9304447      12293.0         47245.0
349  2023-07-01T00:00:00.000Z  9460356      15337.0         43014.0
381  2023-07-01T00:00:00.000Z  9475258      16988.0         51066.0
385  2023-07-01T00:00:00.000Z  9285471       9956.0         38609.0
402  2023-07-01T00:00:00.000Z  9480227       9475.0         44603.0
418  2023-07-01T00:00:00.000Z  9813840       2225.0         26958.0
419  2023-07-01T00:00:00.000Z  9813838       2023.0         28586.0

In [32]:
charter.to_csv(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\FUEL DISTANCE\charter_fuel_distance.csv",index=False)

In [33]:
#sorrento
sorrento = data[data['imo'].isin(esi_sorrento_lst)] 
sorrento

,Ship Name,imo,consumption,sailedDistance,startDate
47,MSC ALEXA,9129873,3721.120,24760.500000,2023-07-01T00:00:00.000Z
51,MSC ALYSSA,9235050,6093.727,45511.299996,2023-07-01T00:00:00.000Z
53,MSC AMBRA,9839480,19930.180,51603.999956,2023-07-01T00:00:00.000Z
55,MSC AMSTERDAM,9606338,13812.600,46770.600008,2023-07-01T00:00:00.000Z
84,MSC BEATRICE,9399014,8178.410,30665.899971,2023-07-01T00:00:00.000Z
109,MSC CELESTINO MARESCA,9930040,15293.460,46642.200000,2023-07-01T00:00:00.000Z
114,MSC CLARA,9708693,17350.730,49403.999911,2023-07-01T00:00:00.000Z
129,MSC DIEGO,9202649,2743.910,24162.899992,2023-07-01T00:00:00.000Z
130,MSC DILETTA,9897004,22400.889,53258.199984,2023-07-01T00:00:00.000Z
154,MSC FABIENNE,9279965,7384.220,41806.030009,2023-07-01T00:00:00.000Z
160,MSC FRANCESCA,9401116,8754.650,33944.300009,2023-07-01T00:00:00.000Z
165,MSC GINA,9202663,4703.837,33503.510124,2023-07-01T00:00:00.000Z
172,MSC HAMBURG,9647461,15742.759,48176.399996,2023-07-01T00:00:00.000Z
190,MSC ISTANBUL,9606326,15554.870,49174.500038,2023-07-01T00:00:00.000Z
191,MSC IVANA,9398371,9788.890,35840.950052,2023-07-01T00:00:00.000Z
198,MSC JIANI,9966934,1584.290,19946.000058,2023-07-01T00:00:00.000Z
205,MSC KALINA,9399026,11081.850,36559.499994,2023-07-01T00:00:00.000Z
208,MSC KATIE,9467457,14951.910,49165.999938,2023-07-01T00:00:00.000Z
214,MSC KIM,9351581,6926.050,37890.000134,2023-07-01T00:00:00.000Z
217,MSC KRYSTAL,9372470,7365.580,44738.699979,2023-07-01T00:00:00.000Z
222,MSC LAURA,9225665,10847.412,41653.500040,2023-07-01T00:00:00.000Z
230,MSC LISA,9281279,7471.760,44231.599984,2023-07-01T00:00:00.000Z
232,MSC LONDON,9606302,15123.090,45752.499992,2023-07-01T00:00:00.000Z
233,MSC LORENA,9320403,9044.660,46527.999961,2023-07-01T00:00:00.000Z
236,MSC LORETTA,9230490,11105.510,43404.499888,2023-07-01T00:00:00.000Z
256,MSC MARINA,9275971,4969.604,22042.300050,2023-07-01T00:00:00.000Z
257,MSC MARTINA,9060637,4429.420,26794.900166,2023-07-01T00:00:00.000Z
262,MSC MAUREEN,9251717,5357.770,23353.800084,2023-07-01T00:00:00.000Z
264,MSC MAYA,9708679,18022.440,51865.000022,2023-07-01T00:00:00.000Z
266,MSC MELISSA,9226918,7412.090,32877.430028,2023-07-01T00:00:00.000Z
270,MSC MICHAELA,9230488,9537.431,42335.299857,2023-07-01T00:00:00.000Z
272,MSC MICHELLE,9897016,20085.540,51969.700062,2023-07-01T00:00:00.000Z
282,MSC NAHARA,9955789,3247.450,21191.499999,2023-07-01T00:00:00.000Z
287,MSC NEW YORK,9606314,12793.630,46684.199980,2023-07-01T00:00:00.000Z
296,MSC NURIA,9349825,6638.630,40789.999870,2023-07-01T00:00:00.000Z
300,MSC OLIVER,9703306,15416.980,48079.999808,2023-07-01T00:00:00.000Z
301,MSC ORIANE,9372482,6998.140,39829.130171,2023-07-01T00:00:00.000Z
304,MSC OSCAR,9703291,17957.721,50897.699899,2023-07-01T00:00:00.000Z
313,MSC POH LIN,9279977,7665.410,44770.099918,2023-07-01T00:00:00.000Z
320,MSC RACHELE,9290282,9584.130,38468.400024,2023-07-01T00:00:00.000Z
325,MSC REEF,9754965,18050.010,51784.999756,2023-07-01T00:00:00.000Z
326,MSC REGINA,9202651,4669.974,28464.600021,2023-07-01T00:00:00.000Z
333,MSC ROSARIA,9320453,8811.900,46478.800009,2023-07-01T00:00:00.000Z
369,MSC SONIA,9404663,12836.700,42925.299941,2023-07-01T00:00:00.000Z
372,MSC STELLA,9279989,10205.323,47208.699954,2023-07-01T00:00:00.000Z
375,MSC SVEVA,9708681,17891.260,53023.000044,2023-07-01T00:00:00.000Z
387,MSC TOMOKO,9309461,10401.640,39315.299970,2023-07-01T00:00:00.000Z
397,MSC VALERIA,9461439,14507.310,47316.500205,2023-07-01T00:00:00.000Z
398,MSC VANDYA,9484467,10279.020,34469.999930,2023-07-01T00:00:00.000Z
417,MSC ZOE,9703318,16859.927,51459.299968,2023-07-01T00:00:00.000Z

In [34]:
sorrento.shape

(50, 5)

In [35]:
sorrento = sorrento[['startDate','imo','consumption','sailedDistance']]
sorrento

                    startDate      imo  consumption  sailedDistance
47   2023-07-01T00:00:00.000Z  9129873     3721.120    24760.500000
51   2023-07-01T00:00:00.000Z  9235050     6093.727    45511.299996
53   2023-07-01T00:00:00.000Z  9839480    19930.180    51603.999956
55   2023-07-01T00:00:00.000Z  9606338    13812.600    46770.600008
84   2023-07-01T00:00:00.000Z  9399014     8178.410    30665.899971
109  2023-07-01T00:00:00.000Z  9930040    15293.460    46642.200000
114  2023-07-01T00:00:00.000Z  9708693    17350.730    49403.999911
129  2023-07-01T00:00:00.000Z  9202649     2743.910    24162.899992
130  2023-07-01T00:00:00.000Z  9897004    22400.889    53258.199984
154  2023-07-01T00:00:00.000Z  9279965     7384.220    41806.030009
160  2023-07-01T00:00:00.000Z  9401116     8754.650    33944.300009
165  2023-07-01T00:00:00.000Z  9202663     4703.837    33503.510124
172  2023-07-01T00:00:00.000Z  9647461    15742.759    48176.399996
190  2023-07-01T00:00:00.000Z  9606326    15554.870    49174.500038
191  2023-07-01T00:00:00.000Z  9398371     9788.890    35840.950052
198  2023-07-01T00:00:00.000Z  9966934     1584.290    19946.000058
205  2023-07-01T00:00:00.000Z  9399026    11081.850    36559.499994
208  2023-07-01T00:00:00.000Z  9467457    14951.910    49165.999938
214  2023-07-01T00:00:00.000Z  9351581     6926.050    37890.000134
217  2023-07-01T00:00:00.000Z  9372470     7365.580    44738.699979
222  2023-07-01T00:00:00.000Z  9225665    10847.412    41653.500040
230  2023-07-01T00:00:00.000Z  9281279     7471.760    44231.599984
232  2023-07-01T00:00:00.000Z  9606302    15123.090    45752.499992
233  2023-07-01T00:00:00.000Z  9320403     9044.660    46527.999961
236  2023-07-01T00:00:00.000Z  9230490    11105.510    43404.499888
256  2023-07-01T00:00:00.000Z  9275971     4969.604    22042.300050
257  2023-07-01T00:00:00.000Z  9060637     4429.420    26794.900166
262  2023-07-01T00:00:00.000Z  9251717     5357.770    23353.800084
264  2023-07-01T00:00:00.000Z  9708679    18022.440    51865.000022
266  2023-07-01T00:00:00.000Z  9226918     7412.090    32877.430028
270  2023-07-01T00:00:00.000Z  9230488     9537.431    42335.299857
272  2023-07-01T00:00:00.000Z  9897016    20085.540    51969.700062
282  2023-07-01T00:00:00.000Z  9955789     3247.450    21191.499999
287  2023-07-01T00:00:00.000Z  9606314    12793.630    46684.199980
296  2023-07-01T00:00:00.000Z  9349825     6638.630    40789.999870
300  2023-07-01T00:00:00.000Z  9703306    15416.980    48079.999808
301  2023-07-01T00:00:00.000Z  9372482     6998.140    39829.130171
304  2023-07-01T00:00:00.000Z  9703291    17957.721    50897.699899
313  2023-07-01T00:00:00.000Z  9279977     7665.410    44770.099918
320  2023-07-01T00:00:00.000Z  9290282     9584.130    38468.400024
325  2023-07-01T00:00:00.000Z  9754965    18050.010    51784.999756
326  2023-07-01T00:00:00.000Z  9202651     4669.974    28464.600021
333  2023-07-01T00:00:00.000Z  9320453     8811.900    46478.800009
369  2023-07-01T00:00:00.000Z  9404663    12836.700    42925.299941
372  2023-07-01T00:00:00.000Z  9279989    10205.323    47208.699954
375  2023-07-01T00:00:00.000Z  9708681    17891.260    53023.000044
387  2023-07-01T00:00:00.000Z  9309461    10401.640    39315.299970
397  2023-07-01T00:00:00.000Z  9461439    14507.310    47316.500205
398  2023-07-01T00:00:00.000Z  9484467    10279.020    34469.999930
417  2023-07-01T00:00:00.000Z  9703318    16859.927    51459.299968

In [36]:
sorrento['consumption'] = np.round(sorrento['consumption'], decimals = 0)
sorrento['sailedDistance'] = np.round(sorrento['sailedDistance'], decimals = 0)
sorrento

                    startDate      imo  consumption  sailedDistance
47   2023-07-01T00:00:00.000Z  9129873       3721.0         24760.0
51   2023-07-01T00:00:00.000Z  9235050       6094.0         45511.0
53   2023-07-01T00:00:00.000Z  9839480      19930.0         51604.0
55   2023-07-01T00:00:00.000Z  9606338      13813.0         46771.0
84   2023-07-01T00:00:00.000Z  9399014       8178.0         30666.0
109  2023-07-01T00:00:00.000Z  9930040      15293.0         46642.0
114  2023-07-01T00:00:00.000Z  9708693      17351.0         49404.0
129  2023-07-01T00:00:00.000Z  9202649       2744.0         24163.0
130  2023-07-01T00:00:00.000Z  9897004      22401.0         53258.0
154  2023-07-01T00:00:00.000Z  9279965       7384.0         41806.0
160  2023-07-01T00:00:00.000Z  9401116       8755.0         33944.0
165  2023-07-01T00:00:00.000Z  9202663       4704.0         33504.0
172  2023-07-01T00:00:00.000Z  9647461      15743.0         48176.0
190  2023-07-01T00:00:00.000Z  9606326      15555.0         49175.0
191  2023-07-01T00:00:00.000Z  9398371       9789.0         35841.0
198  2023-07-01T00:00:00.000Z  9966934       1584.0         19946.0
205  2023-07-01T00:00:00.000Z  9399026      11082.0         36559.0
208  2023-07-01T00:00:00.000Z  9467457      14952.0         49166.0
214  2023-07-01T00:00:00.000Z  9351581       6926.0         37890.0
217  2023-07-01T00:00:00.000Z  9372470       7366.0         44739.0
222  2023-07-01T00:00:00.000Z  9225665      10847.0         41654.0
230  2023-07-01T00:00:00.000Z  9281279       7472.0         44232.0
232  2023-07-01T00:00:00.000Z  9606302      15123.0         45752.0
233  2023-07-01T00:00:00.000Z  9320403       9045.0         46528.0
236  2023-07-01T00:00:00.000Z  9230490      11106.0         43404.0
256  2023-07-01T00:00:00.000Z  9275971       4970.0         22042.0
257  2023-07-01T00:00:00.000Z  9060637       4429.0         26795.0
262  2023-07-01T00:00:00.000Z  9251717       5358.0         23354.0
264  2023-07-01T00:00:00.000Z  9708679      18022.0         51865.0
266  2023-07-01T00:00:00.000Z  9226918       7412.0         32877.0
270  2023-07-01T00:00:00.000Z  9230488       9537.0         42335.0
272  2023-07-01T00:00:00.000Z  9897016      20086.0         51970.0
282  2023-07-01T00:00:00.000Z  9955789       3247.0         21191.0
287  2023-07-01T00:00:00.000Z  9606314      12794.0         46684.0
296  2023-07-01T00:00:00.000Z  9349825       6639.0         40790.0
300  2023-07-01T00:00:00.000Z  9703306      15417.0         48080.0
301  2023-07-01T00:00:00.000Z  9372482       6998.0         39829.0
304  2023-07-01T00:00:00.000Z  9703291      17958.0         50898.0
313  2023-07-01T00:00:00.000Z  9279977       7665.0         44770.0
320  2023-07-01T00:00:00.000Z  9290282       9584.0         38468.0
325  2023-07-01T00:00:00.000Z  9754965      18050.0         51785.0
326  2023-07-01T00:00:00.000Z  9202651       4670.0         28465.0
333  2023-07-01T00:00:00.000Z  9320453       8812.0         46479.0
369  2023-07-01T00:00:00.000Z  9404663      12837.0         42925.0
372  2023-07-01T00:00:00.000Z  9279989      10205.0         47209.0
375  2023-07-01T00:00:00.000Z  9708681      17891.0         53023.0
387  2023-07-01T00:00:00.000Z  9309461      10402.0         39315.0
397  2023-07-01T00:00:00.000Z  9461439      14507.0         47317.0
398  2023-07-01T00:00:00.000Z  9484467      10279.0         34470.0
417  2023-07-01T00:00:00.000Z  9703318      16860.0         51459.0

In [37]:
sorrento.to_csv(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\FUEL DISTANCE\sorrento_fuel_distance.csv",index=False)