In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd

# CHARTER & SORRENTO

In [2]:
charter_remark = pd.read_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\OUTPUT\CHARTER MISSING BDNs refl.xlsx")

In [3]:
charter_remarks = charter_remark[charter_remark['report_type'] == 'REFL']

In [4]:
charter_remarks.columns.to_list()

['id',
 'gid',
 'vessel_name',
 'imo',
 'voy',
 'corrected_date',
 'report_date_time',
 'report_date_time_offset',
 'report_type',
 'status',
 'latitude',
 'longitude',
 'm_e_foc',
 'cargo_total',
 'has_cargo',
 'steaming_time',
 'total_m_e_hours_fuel_only',
 'miles_by_gps',
 'oil_cyl',
 'speed_by_log',
 'speed_by_gps',
 'rpm',
 'slip',
 'wind_direction',
 'wind_speed',
 'draft_aft',
 'draft_fwd',
 'displacement',
 'course_at_sea',
 'wave_height',
 'sea_direction',
 'cargo_total_teu',
 'ambient_temp',
 'sw_temp',
 'miles_by_speed_log',
 'eta_port_code',
 'eta_date_time',
 'eta_date_time_offset',
 'eta_port',
 'time_change',
 'time_sea',
 'temp_min',
 'temp_max',
 'requested_speed',
 'rem_dist_to_pilot',
 'rem_time_to_pilot',
 'total_unplnd_stpge_tech',
 'total_unplnd_stpge_ope_wx',
 'reefers_positive_plugged',
 'reefers_negative_plugged',
 'me_total_revs_counter',
 'port_code',
 'port',
 'aux_blowers_on',
 'hold_ventilation_on',
 'since_date_time',
 'since_date_time_offset',
 'time_hrs_anchor',
 'time_hrs_drift',
 'reason',
 'type_of_delay',
 'etb_date_time',
 'etb_date_time_offset',
 'pilot_date_time',
 'pilot_date_time_offset',
 'time_manoeuvring',
 'tug_arr',
 'tug_shift',
 'etd_date_time',
 'etd_date_time_offset',
 'shift_berth_hours',
 'cargo_disch',
 'teu_full',
 'teu_empty',
 'bilge_removed',
 'garbage_removed',
 'garbage_remvl_reqstd',
 'garbage_remvl_cmplsry',
 'fw_supply',
 'cy_crew_signed_on',
 'cy_crew_signed_off',
 'cy_doctors_visit',
 'cy_mail_received_ref_no',
 'cy_lub_oil_sample_landed',
 'cy_checkd_for_stowaways',
 'cy_stowaways_on_board',
 'cy_dep_gm_mtr',
 'cy_requisitions_received',
 'distance_to_next_pilot',
 'tug_sailing_transit',
 'steaming_time_m_e_rsdl_vls',
 'steaming_time_m_e_rsdl_hs',
 'steaming_time_m_e_rsdl_uls',
 'steaming_time_m_e_dstlt_vls',
 'steaming_time_m_e_dstlt_uls',
 'steaming_time_m_e_tnktnr_dstlt_vls',
 'steaming_time_m_e_hs',
 'steaming_time_m_e_ls',
 'steaming_time_m_e_mdo',
 'steaming_time_m_e_mgo',
 'steaming_time_m_e_mgo_ls',
 'steaming_time_aux_1',
 'steaming_time_aux_2',
 'steaming_time_aux_3',
 'steaming_time_aux_4',
 'steaming_time_aux_5',
 'steaming_time_sh_gen',
 'steaming_time_tg',
 'power_kw',
 'steaming_load_kw_aux_1',
 'steaming_load_kw_aux_2',
 'steaming_load_kw_aux_3',
 'steaming_load_kw_aux_4',
 'steaming_load_kw_aux_5',
 'steaming_load_kw_sh_gen',
 'steaming_load_kw_tg',
 'fuel_m_e_rsdl_vls',
 'fuel_m_e_rsdl_hs',
 'fuel_m_e_rsdl_uls',
 'fuel_m_e_dstlt_vls',
 'fuel_m_e_dstlt_uls',
 'fuel_m_e_tnktnr_dstlt_vls',
 'fuel_m_e_hs',
 'fuel_m_e_ls',
 'fuel_m_e_mdo',
 'fuel_m_e_mgo',
 'fuel_m_e_mgo_ls',
 'fuel_aux_rsdl_vls',
 'fuel_aux_rsdl_hs',
 'fuel_aux_rsdl_uls',
 'fuel_aux_dstlt_vls',
 'fuel_aux_dstlt_uls',
 'fuel_aux_tnktnr_dstlt_vls',
 'fuel_aux_hs',
 'fuel_aux_ls',
 'fuel_aux_mdo',
 'fuel_aux_mgo',
 'fuel_aux_mgo_ls',
 'fuel_boiler_rsdl_vls',
 'fuel_boiler_rsdl_hs',
 'fuel_boiler_rsdl_uls',
 'fuel_boiler_dstlt_vls',
 'fuel_boiler_dstlt_uls',
 'fuel_boiler_tnktnr_dstlt_vls',
 'fuel_boiler_hs',
 'fuel_boiler_ls',
 'fuel_boiler_mdo',
 'fuel_boiler_mgo',
 'fuel_boiler_mgo_ls',
 'deck_last_change_user',
 'deck_part_is_complete',
 'engine_part_is_complete',
 'scavenge_pressure',
 'seca_entry_time',
 'seca_entry_lat',
 'seca_entry_long',
 'rob_fresh_water',
 'manvrng_miles_by_gps',
 'manvrng_miles_by_speed_log',
 'tanktainer_transfd_quantity',
 'pilot_taken',
 'date_time_start_transit',
 'date_time_start_transit_offset',
 'date_time_end_transit',
 'date_time_end_transit_offset',
 'ballast',
 'tanktainer_number',
 'steaming_kwhr_total',
 'cy_others',
 'rob_fo_sludge',
 'rob_lo_sludge',
 'rob_bilge',
 'sludge_removed_fo',
 'sludge_removed_lo',
 'sea_state',
 'cy_lub_added_to_system_mecc',
 'cy_lub_added_to_system_aecc',
 'cy_lub_added_to_thrusters',
 'cy_me_lo_purifier_in_use',
 'cy_ballast',
 'cy_bending_moment',
 'cy_shearing_force',
 'cy_tortion_moment',
 'cy_supdt_auditor_signed_on',
 'cy_supdt_auditor_signed_off',
 'cy_cash_received',
 'cy_lub_oil_received_mecyl',
 'cy_lub_oil_received_mecc',
 'cy_lub_oil_received_aecc',
 'cy_m_e_under_piston_temp',
 'cy_mail_received',
 'wind_direction_port_stbd',
 'sea_direction_port_stbd',
 'time_pilot_onboard',
 'grades_rob',
 'bunker_order',
 'remarks',
 'fuel_type',
 'carbon_factor',
 'so_2_co_2_ratio',
 'sulphur_content_pc',
 'quantity',
 'port_delivery',
 'product_quality',
 'tanktainer_number_1',
 'supplier',
 'vol_lt',
 'den',
 'vis',
 'fuel_hs',
 'fuel_ls',
 'fuel_mdo',
 'fuel_mgo',
 'fuel_mgo_ls',
 'bdn',
 'rob_dstlt_uls',
 'rob_dstlt_vls',
 'rob_rsdl_mdo',
 'rob_tnktnr_dstlt_vls',
 'rob_rsdl_vls',
 'rob_rsdl_hs',
 'rob_rsdl_uls',
 'rob_fuel_hsfo',
 'rob_fuel_lsfo',
 'rob_fuel_mdo',
 'rob_fuel_mgo',
 'rob_fuel_mgo_ls',
 'rob_fuel_tanktainer_mgo',
 'eca_miles',
 'eca_time',
 'egcs_dry_waste_removed',
 'egcs_running_time',
 'egcs_wet_slurry_removed',
 'egcs_open_loop_running_time',
 'egcs_closed_loop_running_time',
 'updated_date',
 'fuel_rsdl_hs',
 'fuel_rsdl_vls',
 'fuel_rsdl_uls',
 'fuel_dstlt_vls',
 'fuel_dstlt_uls',
 'fuel_tnktnr_dstlt_vls',
 'cargo_load',
 'seca_exit_time',
 'seca_exit_lat',
 'seca_exit_long',
 'engine_last_change_user',
 'created_date',
 'created_at',
 'updated_at',
 'created_by_id',
 'updated_by_id',
 'fuel_m_e_lng',
 'fuel_aux_lng',
 'fuel_boiler_lng',
 'rob_boiler_lng',
 'delivery',
 'REMARKS']

In [5]:
charter_remarks = charter_remarks.rename(columns={
    'gid': 'GID',
     'imo'  :     'IMO_No',
    'vessel_name'   :  'VSL',
    'report_date_time'  :'REPORT_DATE_TIME',
    'sulphur_content_pc': 'Sulphur_Content_PC',
    'quantity': 'Quantity',
    'port_delivery': 'Port_Delivery',
    'product_quality': 'Product_Quality',
    'delivery': 'Delivery',
    'bdn': 'BDN'
})

In [6]:
charter_remarks

,id,GID,VSL,IMO_No,voy,corrected_date,REPORT_DATE_TIME,report_date_time_offset,report_type,status,...,created_at,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng,Delivery,REMARKS
0,4493242,3eacc476-c023-494d-a6ce-a1aa6378218d,MSC QINGDAO,9256470,ME351W,2024-01-02,2024-1-1 14:35,UTC +00:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,2195,NaN
1,4490311,d54b3fce-c7e4-4423-bd60-99066cd81cc5,KOTKA,9085534,ZF350A,2024-01-01,2024-1-1 9:42,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,14799,Sulphur is not given
2,4494685,a0467399-7302-4cfa-a98e-01ae7ba67a4c,ALANA,9297589,RC352R,2024-01-13,2024-1-12 13:00,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BRZI _ 32,NaN
3,4492927,a030ad08-a899-45f3-8fb8-c828f0d620bc,MSC BOSPHORUS,9247742,FR350W,2024-01-13,2024-1-13 10:08,UTC -05:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,0847-GB,"Sulphur is not given,Fuel Type or Sulphur will..."
4,4493196,d52d5be1-85ba-4971-99cf-d1cefe281b8c,MED CESME,9256365,DD402A,2024-01-14,2024-1-13 15:20,UTC +03:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,164069,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,4400611,5d08330f-f1fe-437d-9978-56f153b43d29,HUBERT SCHULTE,9535204,NG415E,2024-05-10,2024-5-9 17:18,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BRBTB202400000478,NaN
386,4400612,4ce4295a-b97c-47d5-be01-7e7c08138ced,HUBERT SCHULTE,9535204,NG415E,2024-05-10,2024-5-9 22:00,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BRDI_105,NaN
387,4394005,23856d53-69cf-4984-ba31-2a1c6678e5ea,CONTI CHIVALRY,9293791,MA414R,2024-05-10,2024-5-9 23:05,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,100389,NaN
388,4400564,a1695f38-5432-4fd1-b96c-10e1b23789be,HERMANN SCHULTE,9535187,NG418E,2024-05-09,2024-5-9 2:04,UTC -05:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,10108338,Sulphur is not given
389,4403161,d8ced3a9-4ae4-45f7-8309-df6814f5441f,SPIRIT OF KOLKATA,9813838,SH417R,2024-05-09,2024-5-9 7:00,UTC +05:30,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,2013,NaN

In [7]:
client_charter_bdn = pd.read_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\CLIENT FILE\CHARTER MISSING BDNs.xlsx")

In [8]:
client_charter_bdn.columns.tolist()

['id',
 'gid',
 'vessel_name',
 'imo',
 'voy',
 'corrected_date',
 'report_date_time',
 'report_date_time_offset',
 'report_type',
 'status',
 'latitude',
 'longitude',
 'm_e_foc',
 'cargo_total',
 'has_cargo',
 'steaming_time',
 'total_m_e_hours_fuel_only',
 'miles_by_gps',
 'oil_cyl',
 'speed_by_log',
 'speed_by_gps',
 'rpm',
 'slip',
 'wind_direction',
 'wind_speed',
 'draft_aft',
 'draft_fwd',
 'displacement',
 'course_at_sea',
 'wave_height',
 'sea_direction',
 'cargo_total_teu',
 'ambient_temp',
 'sw_temp',
 'miles_by_speed_log',
 'eta_port_code',
 'eta_date_time',
 'eta_date_time_offset',
 'eta_port',
 'time_change',
 'time_sea',
 'temp_min',
 'temp_max',
 'requested_speed',
 'rem_dist_to_pilot',
 'rem_time_to_pilot',
 'total_unplnd_stpge_tech',
 'total_unplnd_stpge_ope_wx',
 'reefers_positive_plugged',
 'reefers_negative_plugged',
 'me_total_revs_counter',
 'port_code',
 'port',
 'aux_blowers_on',
 'hold_ventilation_on',
 'since_date_time',
 'since_date_time_offset',
 'time_hrs_anchor',
 'time_hrs_drift',
 'reason',
 'type_of_delay',
 'etb_date_time',
 'etb_date_time_offset',
 'pilot_date_time',
 'pilot_date_time_offset',
 'time_manoeuvring',
 'tug_arr',
 'tug_shift',
 'etd_date_time',
 'etd_date_time_offset',
 'shift_berth_hours',
 'cargo_disch',
 'teu_full',
 'teu_empty',
 'bilge_removed',
 'garbage_removed',
 'garbage_remvl_reqstd',
 'garbage_remvl_cmplsry',
 'fw_supply',
 'cy_crew_signed_on',
 'cy_crew_signed_off',
 'cy_doctors_visit',
 'cy_mail_received_ref_no',
 'cy_lub_oil_sample_landed',
 'cy_checkd_for_stowaways',
 'cy_stowaways_on_board',
 'cy_dep_gm_mtr',
 'cy_requisitions_received',
 'distance_to_next_pilot',
 'tug_sailing_transit',
 'steaming_time_m_e_rsdl_vls',
 'steaming_time_m_e_rsdl_hs',
 'steaming_time_m_e_rsdl_uls',
 'steaming_time_m_e_dstlt_vls',
 'steaming_time_m_e_dstlt_uls',
 'steaming_time_m_e_tnktnr_dstlt_vls',
 'steaming_time_m_e_hs',
 'steaming_time_m_e_ls',
 'steaming_time_m_e_mdo',
 'steaming_time_m_e_mgo',
 'steaming_time_m_e_mgo_ls',
 'steaming_time_aux_1',
 'steaming_time_aux_2',
 'steaming_time_aux_3',
 'steaming_time_aux_4',
 'steaming_time_aux_5',
 'steaming_time_sh_gen',
 'steaming_time_tg',
 'power_kw',
 'steaming_load_kw_aux_1',
 'steaming_load_kw_aux_2',
 'steaming_load_kw_aux_3',
 'steaming_load_kw_aux_4',
 'steaming_load_kw_aux_5',
 'steaming_load_kw_sh_gen',
 'steaming_load_kw_tg',
 'fuel_m_e_rsdl_vls',
 'fuel_m_e_rsdl_hs',
 'fuel_m_e_rsdl_uls',
 'fuel_m_e_dstlt_vls',
 'fuel_m_e_dstlt_uls',
 'fuel_m_e_tnktnr_dstlt_vls',
 'fuel_m_e_hs',
 'fuel_m_e_ls',
 'fuel_m_e_mdo',
 'fuel_m_e_mgo',
 'fuel_m_e_mgo_ls',
 'fuel_aux_rsdl_vls',
 'fuel_aux_rsdl_hs',
 'fuel_aux_rsdl_uls',
 'fuel_aux_dstlt_vls',
 'fuel_aux_dstlt_uls',
 'fuel_aux_tnktnr_dstlt_vls',
 'fuel_aux_hs',
 'fuel_aux_ls',
 'fuel_aux_mdo',
 'fuel_aux_mgo',
 'fuel_aux_mgo_ls',
 'fuel_boiler_rsdl_vls',
 'fuel_boiler_rsdl_hs',
 'fuel_boiler_rsdl_uls',
 'fuel_boiler_dstlt_vls',
 'fuel_boiler_dstlt_uls',
 'fuel_boiler_tnktnr_dstlt_vls',
 'fuel_boiler_hs',
 'fuel_boiler_ls',
 'fuel_boiler_mdo',
 'fuel_boiler_mgo',
 'fuel_boiler_mgo_ls',
 'deck_last_change_user',
 'deck_part_is_complete',
 'engine_part_is_complete',
 'scavenge_pressure',
 'seca_entry_time',
 'seca_entry_lat',
 'seca_entry_long',
 'rob_fresh_water',
 'manvrng_miles_by_gps',
 'manvrng_miles_by_speed_log',
 'tanktainer_transfd_quantity',
 'pilot_taken',
 'date_time_start_transit',
 'date_time_start_transit_offset',
 'date_time_end_transit',
 'date_time_end_transit_offset',
 'ballast',
 'tanktainer_number',
 'steaming_kwhr_total',
 'cy_others',
 'rob_fo_sludge',
 'rob_lo_sludge',
 'rob_bilge',
 'sludge_removed_fo',
 'sludge_removed_lo',
 'sea_state',
 'cy_lub_added_to_system_mecc',
 'cy_lub_added_to_system_aecc',
 'cy_lub_added_to_thrusters',
 'cy_me_lo_purifier_in_use',
 'cy_ballast',
 'cy_bending_moment',
 'cy_shearing_force',
 'cy_tortion_moment',
 'cy_supdt_auditor_signed_on',
 'cy_supdt_auditor_signed_off',
 'cy_cash_received',
 'cy_lub_oil_received_mecyl',
 'cy_lub_oil_received_mecc',
 'cy_lub_oil_received_aecc',
 'cy_m_e_under_piston_temp',
 'cy_mail_received',
 'wind_direction_port_stbd',
 'sea_direction_port_stbd',
 'time_pilot_onboard',
 'grades_rob',
 'bunker_order',
 'remarks',
 'fuel_type',
 'carbon_factor',
 'so_2_co_2_ratio',
 'sulphur_content_pc',
 'quantity',
 'port_delivery',
 'product_quality',
 'tanktainer_number_1',
 'supplier',
 'vol_lt',
 'den',
 'vis',
 'fuel_hs',
 'fuel_ls',
 'fuel_mdo',
 'fuel_mgo',
 'fuel_mgo_ls',
 'bdn',
 'rob_dstlt_uls',
 'rob_dstlt_vls',
 'rob_rsdl_mdo',
 'rob_tnktnr_dstlt_vls',
 'rob_rsdl_vls',
 'rob_rsdl_hs',
 'rob_rsdl_uls',
 'rob_fuel_hsfo',
 'rob_fuel_lsfo',
 'rob_fuel_mdo',
 'rob_fuel_mgo',
 'rob_fuel_mgo_ls',
 'rob_fuel_tanktainer_mgo',
 'eca_miles',
 'eca_time',
 'egcs_dry_waste_removed',
 'egcs_running_time',
 'egcs_wet_slurry_removed',
 'egcs_open_loop_running_time',
 'egcs_closed_loop_running_time',
 'updated_date',
 'fuel_rsdl_hs',
 'fuel_rsdl_vls',
 'fuel_rsdl_uls',
 'fuel_dstlt_vls',
 'fuel_dstlt_uls',
 'fuel_tnktnr_dstlt_vls',
 'cargo_load',
 'seca_exit_time',
 'seca_exit_lat',
 'seca_exit_long',
 'engine_last_change_user',
 'created_date',
 'created_at',
 'updated_at',
 'created_by_id',
 'updated_by_id',
 'fuel_m_e_lng',
 'fuel_aux_lng',
 'fuel_boiler_lng',
 'rob_boiler_lng',
 'delivery',
 'REMARKS']

In [9]:
#client_charter_bdn = client_charter_bdn.rename(columns=lambda x: x.lower(), inplace=True)
client_charter_bdn = client_charter_bdn.rename(columns={
    'gid': 'GID',
      'imo'  :     'IMO_No',
    'vessel_name'   :  'VSL',
    'report_date_time'  :'REPORT_DATE_TIME',
    'sulphur_content_pc': 'Sulphur_Content_PC',
    'quantity': 'Quantity',
    'port_delivery': 'Port_Delivery',
    'product_quality': 'Product_Quality',
    'delivery': 'Delivery',
    'bdn': 'BDN'
})

In [10]:
client_charter_bdn

,id,GID,VSL,IMO_No,voy,corrected_date,REPORT_DATE_TIME,report_date_time_offset,report_type,status,...,created_at,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng,Delivery,REMARKS
0,4508826,13c39c39-a7fb-455a-a332-4f3a2ae8ebd2,ALANA,9297589,RC406R,2024-02-18,2024-2-17 14:19,UTC +01:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BRBTB202417EB7ECC4C,Sulphur is not given
1,4537973,a6cd03e5-341b-4070-b442-1b5f1d146b9f,AS CALIFORNIA,9342695,FC413A,2024-04-03,2024-4-2 17:25,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,7746,Sulphur is not given
2,4510435,91e79d0b-6040-4dcd-b276-1819db70bc72,AS CALIFORNIA,9342695,KE402R,2024-02-02,2024-2-2 5:30,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,16012,Sulphur is not given
3,4492974,18db67d8-62dc-4035-a72a-3b93931a7a39,ATHENS GLORY,9247766,352S,2024-01-17,2024-1-16 16:45,UTC -06:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,20171068,BDN is not given
4,4530377,bb03d4d8-1951-4d66-aafd-a024fd202af2,CAPE SOUNIO,9727625,FI409A,2024-03-10,2024-3-9 21:00,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,2,IGNORE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,4493169,eb234fe9-286c-4bd5-9b2a-ed2ed9db4042,MSC TURIN II,9256365,UI350R,2024-01-02,2024-1-2 4:25,UTC +03:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,165120,Sulphur is not given
82,4544776,14c84554-7fd6-4ebc-a391-62962d4d9ce3,SPIRIT OF CHENNAI,9813840,AA411A,2024-04-02,2024-4-2 7:36,UTC +03:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,0,IGNORE
83,4544837,0df390b6-f52d-4aa8-ba4a-efdd8a991d11,SPIRIT OF CHENNAI,9813840,AA415A,2024-04-27,2024-4-27 10:45,UTC +03:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,2000085901,Sulphur is not given
84,4403240,40ffe7ad-169e-464c-9854-9b1c09e1be4e,SPIRIT OF CHENNAI,9813840,AA419A,2024-05-18,2024-5-17 15:30,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,176,Sulphur is not given
85,4503605,1b985475-c5c5-45f0-87b0-12a8fa04261a,SPIRIT OF CHENNAI,9813840,AA402A,2024-01-22,2024-1-22 0:25,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,A40 907,"Sulphur is not given,Fuel Type or Sulphur will..."

In [11]:
value_map = dict(zip(client_charter_bdn['GID'], client_charter_bdn['Sulphur_Content_PC']))
charter_remarks['Sulphur_Content_PC'] = charter_remarks['GID'].map(value_map).fillna(charter_remarks['Sulphur_Content_PC'])

value_map = dict(zip(client_charter_bdn['GID'], client_charter_bdn['REPORT_DATE_TIME']))
charter_remarks['REPORT_DATE_TIME'] = charter_remarks['GID'].map(value_map).fillna(charter_remarks['REPORT_DATE_TIME'])

value_map_1 = dict(zip(client_charter_bdn['GID'], client_charter_bdn['Quantity']))
charter_remarks['Quantity'] = charter_remarks['GID'].map(value_map_1).fillna(charter_remarks['Quantity'])


value_map_2 = dict(zip(client_charter_bdn['GID'], client_charter_bdn['Product_Quality']))
charter_remarks['Product_Quality'] = charter_remarks['GID'].map(value_map_2).fillna(charter_remarks['Product_Quality'])

value_map_2 = dict(zip(client_charter_bdn['GID'], client_charter_bdn['Delivery']))
charter_remarks['Delivery'] = charter_remarks['GID'].map(value_map_2).fillna(charter_remarks['Delivery'])
charter_remarks

,id,GID,VSL,IMO_No,voy,corrected_date,REPORT_DATE_TIME,report_date_time_offset,report_type,status,...,created_at,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng,Delivery,REMARKS
0,4493242,3eacc476-c023-494d-a6ce-a1aa6378218d,MSC QINGDAO,9256470,ME351W,2024-01-02,2024-1-1 14:35,UTC +00:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,2195,NaN
1,4490311,d54b3fce-c7e4-4423-bd60-99066cd81cc5,KOTKA,9085534,ZF350A,2024-01-01,2024-1-1 9:42,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,14799,Sulphur is not given
2,4494685,a0467399-7302-4cfa-a98e-01ae7ba67a4c,ALANA,9297589,RC352R,2024-01-13,2024-1-12 13:00,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BRZI _ 32,NaN
3,4492927,a030ad08-a899-45f3-8fb8-c828f0d620bc,MSC BOSPHORUS,9247742,FR350W,2024-01-13,2024-1-13 10:08,UTC -05:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,0847-GB,"Sulphur is not given,Fuel Type or Sulphur will..."
4,4493196,d52d5be1-85ba-4971-99cf-d1cefe281b8c,MED CESME,9256365,DD402A,2024-01-14,2024-1-13 15:20,UTC +03:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,164069,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,4400611,5d08330f-f1fe-437d-9978-56f153b43d29,HUBERT SCHULTE,9535204,NG415E,2024-05-10,2024-5-9 17:18,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BRBTB202400000478,NaN
386,4400612,4ce4295a-b97c-47d5-be01-7e7c08138ced,HUBERT SCHULTE,9535204,NG415E,2024-05-10,2024-5-9 22:00,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BRDI_105,NaN
387,4394005,23856d53-69cf-4984-ba31-2a1c6678e5ea,CONTI CHIVALRY,9293791,MA414R,2024-05-10,2024-5-9 23:05,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,100389,NaN
388,4400564,a1695f38-5432-4fd1-b96c-10e1b23789be,HERMANN SCHULTE,9535187,NG418E,2024-05-09,2024-5-9 2:04,UTC -05:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,10108338,Sulphur is not given
389,4403161,d8ced3a9-4ae4-45f7-8309-df6814f5441f,SPIRIT OF KOLKATA,9813838,SH417R,2024-05-09,2024-5-9 7:00,UTC +05:30,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,2013,NaN

In [12]:
ignored_data = client_charter_bdn[client_charter_bdn['REMARKS']=='IGNORE']
ignored_data_lst = ignored_data['GID'].unique().tolist()
ignored_data_lst

['bb03d4d8-1951-4d66-aafd-a024fd202af2',
 '96e1fa95-9144-4e59-9310-769dff4cfdc3',
 '280bf040-4cef-49d6-9692-2031bef4785a',
 'ee6b6917-0a6b-4d3e-8892-88ee59c210fa',
 '9f693bd8-3458-40b8-85d0-137db5d38f8c',
 'cf760d76-632f-454f-a967-bda23370f3d6',
 '8435752a-d767-40b0-8a0a-10a5d96bd1b5',
 '42402b6d-8e6e-4a38-bdce-5bc9ef993dcc',
 '14c84554-7fd6-4ebc-a391-62962d4d9ce3']

In [13]:
file_change_refl_vtout_ignored = charter_remarks[~charter_remarks['GID'].isin(ignored_data_lst)]
cr=file_change_refl_vtout_ignored[['GID','IMO_No','VSL','REPORT_DATE_TIME','Sulphur_Content_PC','Quantity','Port_Delivery','Product_Quality','Delivery']]

In [14]:
# charter_remarks_db = file_change_refl_vtout_ignored[['GID','Sulphur_Content_PC','Quantity','Port_Delivery','Product_Quality','Delivery']]
# charter_remarks_db

In [15]:
#charter_remarks_db['Sulphur_Content_PC'].isna().sum()
cr['Sulphur_Content_PC'].isna().sum()

0

In [16]:
# chart_nan = charter_remarks_db[charter_remarks_db['Sulphur_Content_PC'].isna()]
# chart_nan
chart_nan = cr[cr['Sulphur_Content_PC'].isna()]
chart_nan

Empty DataFrame
Columns: [GID, IMO_No, VSL, REPORT_DATE_TIME, Sulphur_Content_PC, Quantity, Port_Delivery, Product_Quality, Delivery]
Index: []

In [17]:
# charter_remarks_db['BDN'] = 'YES'
# charter_remarks_db
cr['BDN'] = 'YES'
cr

,GID,IMO_No,VSL,REPORT_DATE_TIME,Sulphur_Content_PC,Quantity,Port_Delivery,Product_Quality,Delivery,BDN
0,3eacc476-c023-494d-a6ce-a1aa6378218d,9256470,MSC QINGDAO,2024-1-1 14:35,0.4700,1000.019,ITGOA,RESIDUAL VLS,2195,YES
1,d54b3fce-c7e4-4423-bd60-99066cd81cc5,9085534,KOTKA,2024-1-1 9:42,0.4860,4498.000,SGSIN,RESIDUAL VLS,14799,YES
2,a0467399-7302-4cfa-a98e-01ae7ba67a4c,9297589,ALANA,2024-1-12 13:00,0.0990,300.597,BEANR,RESIDUAL ULS,BRZI _ 32,YES
3,a030ad08-a899-45f3-8fb8-c828f0d620bc,9247742,MSC BOSPHORUS,2024-1-13 10:08,2.8300,2885.250,PAROD,RESIDUAL HS,0847-GB,YES
4,d52d5be1-85ba-4971-99cf-d1cefe281b8c,9256365,MED CESME,2024-1-13 15:20,0.0500,50.000,TRITY,DISTILLATES,164069,YES
...,...,...,...,...,...,...,...,...,...,...
385,5d08330f-f1fe-437d-9978-56f153b43d29,9535204,HUBERT SCHULTE,2024-5-9 17:18,0.0989,401.336,BEANR,DISTILLATES,BRBTB202400000478,YES
386,4ce4295a-b97c-47d5-be01-7e7c08138ced,9535204,HUBERT SCHULTE,2024-5-9 22:00,0.5000,1000.000,BEANR,RESIDUAL VLS,BRDI_105,YES
387,23856d53-69cf-4984-ba31-2a1c6678e5ea,9293791,CONTI CHIVALRY,2024-5-9 23:05,0.0916,499.707,SGSIN,DISTILLATES,100389,YES
388,a1695f38-5432-4fd1-b96c-10e1b23789be,9535187,HERMANN SCHULTE,2024-5-9 2:04,0.0939,350.440,USMSY,DISTILLATES,10108338,YES
389,d8ced3a9-4ae4-45f7-8309-df6814f5441f,9813838,SPIRIT OF KOLKATA,2024-5-9 7:00,1.8100,255.000,LKCMB,RESIDUAL HS,2013,YES

### SORRENTO

In [18]:
sorrento_remark = pd.read_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\OUTPUT\SORRENTO MISSING BDNs refl.xlsx")
sorrento_remark

,id,gid,vessel_name,imo,voy,corrected_date,report_date_time,report_date_time_offset,report_type,status,...,created_at,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng,REMARKS,delivery
0,4505963,97d6856c-4261-4a11-977a-e3891514cde1,MSC REGINA,9202651,OM401R,2024-02-21,2024-2-20 22:20,UTC +04:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN is not given,0
1,4520265,78343892-8205-44d5-b627-8cdc18b9ef72,MSC MICHAELA,9230488,UK408R,2024-03-08,2024-3-7 12:45,UTC -08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN is not given,NaN
2,4507718,abbe3849-08c6-4054-829c-29332e999624,MSC FABIENNE,9279965,NT404A,2024-02-02,2024-2-1 18:20,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN is not given,NO
3,4521417,0f9b48a5-55cb-4672-ace7-e980dfec4177,MSC LISA,9281279,MX409R,2024-03-07,2024-3-7 2:25,UTC +00:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN is not given,NaN
4,4393419,aae25f7a-fe3a-46ff-b49d-6b02d555e268,MSC LISA,9281279,CI421A,2024-05-30,2024-5-30 8:54,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN is not given,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367,4545474,25c45230-03f8-44a3-ba35-b97a1799af5a,MSC JIANI,9966934,YB413R,2024-04-16,2024-4-15 14:45,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,NaN,245578624
368,4504213,1464f0aa-214f-4d5f-91b7-9aa70687d1ca,MSC JIANI,9966934,XA352A,2024-01-15,2024-1-15 2:50,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,NaN,40410
369,4504203,ee7bd179-e0c7-421f-9d84-0c9e6ae33b15,MSC JIANI,9966934,XA352A,2024-01-10,2024-1-9 17:00,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,NaN,36-2300139
370,4504214,bc0dd51c-5113-4329-a163-b2a8b3e7f4e4,MSC JIANI,9966934,XA352A,2024-01-15,2024-1-15 8:00,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,NaN,eGID2024010941
371,4531849,8e69c893-5bce-41a4-8680-0544c5d14c37,MSC JIANI,9966934,YB410R,2024-03-20,2024-3-20 10:00,UTC +01:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,NaN,245352291

In [19]:
sorrento_remarks = sorrento_remark[sorrento_remark['report_type'] == 'REFL']
sorrento_remarks

,id,gid,vessel_name,imo,voy,corrected_date,report_date_time,report_date_time_offset,report_type,status,...,created_at,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng,REMARKS,delivery
0,4505963,97d6856c-4261-4a11-977a-e3891514cde1,MSC REGINA,9202651,OM401R,2024-02-21,2024-2-20 22:20,UTC +04:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN is not given,0
1,4520265,78343892-8205-44d5-b627-8cdc18b9ef72,MSC MICHAELA,9230488,UK408R,2024-03-08,2024-3-7 12:45,UTC -08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN is not given,NaN
2,4507718,abbe3849-08c6-4054-829c-29332e999624,MSC FABIENNE,9279965,NT404A,2024-02-02,2024-2-1 18:20,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN is not given,NO
3,4521417,0f9b48a5-55cb-4672-ace7-e980dfec4177,MSC LISA,9281279,MX409R,2024-03-07,2024-3-7 2:25,UTC +00:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN is not given,NaN
4,4393419,aae25f7a-fe3a-46ff-b49d-6b02d555e268,MSC LISA,9281279,CI421A,2024-05-30,2024-5-30 8:54,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN is not given,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367,4545474,25c45230-03f8-44a3-ba35-b97a1799af5a,MSC JIANI,9966934,YB413R,2024-04-16,2024-4-15 14:45,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,NaN,245578624
368,4504213,1464f0aa-214f-4d5f-91b7-9aa70687d1ca,MSC JIANI,9966934,XA352A,2024-01-15,2024-1-15 2:50,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,NaN,40410
369,4504203,ee7bd179-e0c7-421f-9d84-0c9e6ae33b15,MSC JIANI,9966934,XA352A,2024-01-10,2024-1-9 17:00,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,NaN,36-2300139
370,4504214,bc0dd51c-5113-4329-a163-b2a8b3e7f4e4,MSC JIANI,9966934,XA352A,2024-01-15,2024-1-15 8:00,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,NaN,eGID2024010941
371,4531849,8e69c893-5bce-41a4-8680-0544c5d14c37,MSC JIANI,9966934,YB410R,2024-03-20,2024-3-20 10:00,UTC +01:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,NaN,245352291

In [20]:
client_sorrento_bdn = pd.read_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\CLIENT FILE\SORRENTO MISSING BDNs.xlsx")
client_sorrento_bdn

,id,gid,vessel_name,imo,voy,corrected_date,report_date_time,report_date_time_offset,report_type,status,...,created_at,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng,delivery,REMARKS
0,4506956,5970fb57-83b3-4dbf-96d0-27e3f938d11a,MSC ALYSSA,9235050,CI406R,2024-02-13,2024-2-13 0:00,UTC +00:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,0,Sulphur is not given
1,4542796,08856b18-12e0-4bb6-add9-0f099539d9e1,MSC AMSTERDAM,9606338,QG417E,2024-04-30,2024-4-29 18:10,UTC +01:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,NL0074002680,Sulphur is not given
2,4502526,62fb10b3-243c-417c-b021-b04f8bdfd5fa,MSC CLARA,9708693,FT348E,2024-01-06,2024-1-5 17:18,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,6254,Sulphur is not given
3,4491726,40834d6f-1661-4f5b-9480-9cbeafd162d7,MSC DIEGO,9202649,OM352A,2024-01-09,2024-1-8 14:25,UTC +05:30,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,411,Sulphur is not given
4,4519332,fed803bc-bef6-47c1-9d28-4646c189ed74,MSC DIEGO,9202649,OM352A,2024-03-15,2024-3-14 14:27,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,ABS DIEGO 14.03.24,Sulphur is not given
5,4519350,fda6ce27-7b40-46b9-95a1-82ef4b52efc1,MSC DIEGO,9202649,OM406R,2024-03-27,2024-3-26 20:10,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,MSC126,"Sulphur is not given,BDN is not given"
6,4531507,b26641ed-ed17-4ceb-805b-c6140ac30fe8,MSC DILETTA,9897004,FJ402E,2024-03-12,2024-3-11 14:57,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,13720788,Sulphur is not given
7,4531505,d86386aa-be02-449a-9211-67b957b99d87,MSC DILETTA,9897004,FJ402E,2024-03-11,2024-3-11 2:00,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,F055101,Sulphur is not given
8,4507718,abbe3849-08c6-4054-829c-29332e999624,MSC FABIENNE,9279965,NT404A,2024-02-02,2024-2-1 18:20,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,NO,Sulphur is not given
9,4397938,27ff2ad1-4e94-4d01-8ced-67f0655e29a4,MSC FRANCESCA,9401116,OW416R,2024-05-08,2024-5-8 6:30,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,4.06524E+11,Sulphur is not given
10,4401063,ad99dacc-fba5-46af-a67e-48624a1c2800,MSC ISTANBUL,9606326,QG420E,2024-05-30,2024-5-29 14:00,UTC -09:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BRDI129,Sulphur is not given
11,4401060,868f0e5c-a172-4dd0-a7a6-8d37999a7e2e,MSC ISTANBUL,9606326,QG420E,2024-05-29,2024-5-28 13:00,UTC -09:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,2.024E+11,Sulphur is not given
12,4511611,722839ec-543a-44b2-bab5-a2b1c877f371,MSC IVANA,9398371,FW351W,2024-02-14,2024-2-14 0:20,UTC +01:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BQ12_74,Sulphur is not given
13,4541370,f6aa2414-daa1-44a6-add1-4943c1b66543,MSC KATIE,9467457,IS413A,2024-05-01,2024-4-30 17:23,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,1954,Sulphur is not given
14,4527564,cef8edd4-f217-4077-a399-fd1cdc4a33d0,MSC KATIE,9467457,FD410E,2024-03-17,2024-3-16 15:10,UTC +01:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,4.06024E+11,"Sulphur is not given,Fuel Type or Sulphur will..."
15,4538562,97d11533-c1d7-45c9-9e93-699817a400eb,MSC KIM,9351581,NC413R,2024-04-17,2024-4-17 10:32,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,2.024E+11,Sulphur is not given
16,4396429,51538578-58d5-4a2e-9e9c-799da4a6eb08,MSC KIM,9351581,NC413R,2024-05-08,2024-5-7 16:10,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,2.024E+11,Sulphur is not given
17,4396779,141685f4-1074-4c3d-a172-6258542d9d57,MSC KRYSTAL,9372470,NJ417R,2024-05-26,2024-5-25 13:35,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BRBTB202497108695BD,"Sulphur is not given,BDN is not given"
18,4521417,0f9b48a5-55cb-4672-ace7-e980dfec4177,MSC LISA,9281279,MX409R,2024-03-07,2024-3-7 2:25,UTC +00:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,9956309,"Sulphur is not given,BDN is not given"
19,4393419,aae25f7a-fe3a-46ff-b49d-6b02d555e268,MSC LISA,9281279,CI421A,2024-05-30,2024-5-30 8:54,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,480327746,"Sulphur is not given,BDN is not given"
20,4393147,13a070d5-97dc-4a7e-b684-fe93efd5578e,MSC MARINA,9275971,QM420A,2024-05-29,2024-5-28 21:46,UTC +00:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,2405730,Sulphur is not given
21,4393119,d265d3d3-959e-4e28-b87d-e38fefe2ca8e,MSC MARINA,9275971,XA404A,2024-05-13,2024-5-13 5:40,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,ZJ20241678,Sulphur is not given
22,4504507,70037bff-42fe-4443-a837-6ef1f580cbd8,MSC MARTINA,9060637,OM402R,2024-02-29,2024-2-28 14:00,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,5345,BDN is not given
23,4504508,603a645a-8249-4119-90c7-501e753a2f45,MSC MARTINA,9060637,OM402R,2024-02-29,2024-2-28 15:20,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,5344,BDN is not given
24,4504509,1a7da3a3-42fa-4aac-89a1-6e589c8a02d3,MSC MARTINA,9060637,OM402R,2024-02-29,2024-2-28 17:30,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,5323,BDN is not given
25,4504517,d18be661-8df5-42ef-9bf3-802f49852da2,MSC MARTINA,9060637,OM409A,2024-03-01,2024-2-29 15:00,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,3781,BDN is not given
26,4532021,ddd4d0b9-ab86-407c-a888-41c6594fc9ba,MSC MARTINA,9060637,OM409A,2024-04-10,2024-4-9 18:00,UTC +03:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,RSV 9743,BDN is not given
27,4492546,a01618bc-bb31-4683-9932-78494d4c4439,MSC MELISSA,9226918,OW401R,2024-01-12,2024-1-12 3:20,UTC +00:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,480319530A,BDN is not given
28,4492545,63990e38-0431-4812-89ed-1de09f021d35,MSC MELISSA,9226918,OW401R,2024-01-12,2024-1-12 3:20,UTC +00:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,480319530,BDN is not given
29,4506707,3996f580-0709-4d03-9043-c4b8632dba41,MSC MELISSA,9226918,OW404R,2024-02-10,2024-2-9 19:10,UTC +00:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,480321065,BDN is not given
30,4520265,78343892-8205-44d5-b627-8cdc18b9ef72,MSC MICHAELA,9230488,UK408R,2024-03-08,2024-3-7 12:45,UTC -08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN DATE 07.03.2024,BDN is not given
31,4501357,b027b770-e743-4ba4-89e9-f1f0a1430e91,MSC NEW YORK,9606314,QJ350S,2024-01-12,2024-1-12 6:45,UTC +09:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,FF00110782,BDN is not given
32,4401901,274a22da-9965-422c-9564-07d7415b0371,MSC OLIVER,9703306,FT409E,2024-05-26,2024-5-25 23:00,UTC +07:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BC/VITOL/24/00224,BDN is not given
33,4396863,cce39773-a2ca-4e6d-b4b4-7bcb896a1cda,MSC ORIANE,9372482,MX420R,2024-05-27,2024-5-27 7:50,UTC -04:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN DATE 27.05.2024,BDN is not given
34,4396852,04985951-66b2-4a55-b2fd-36e9882b68e6,MSC ORIANE,9372482,MX420R,2024-05-24,2024-5-23 18:35,UTC -04:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,10155347,Fuel Type or Sulphur will be wrong
35,4396851,2ecd8b7b-9867-4d54-98fb-85671f26e139,MSC ORIANE,9372482,MX420R,2024-05-24,2024-5-23 18:35,UTC -04:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,10155347,Fuel Type or Sulphur will be wrong
36,4391394,620fa7a2-e0ae-46aa-8a98-3e2808b3399d,MSC REGINA,9202651,OM414A,2024-05-22,2024-5-21 13:40,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,N.A.,IGNORE
37,4391395,eb6c02f7-06c7-49cb-84bf-af0b580ca6eb,MSC REGINA,9202651,OM414A,2024-05-22,2024-5-21 13:50,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,N.A,IGNORE
38,4391396,5ea53085-ebe5-416a-8b3c-034b2f712975,MSC REGINA,9202651,OM414A,2024-05-22,2024-5-21 14:00,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,NaN,IGNORE
39,4505963,97d6856c-4261-4a11-977a-e3891514cde1,MSC REGINA,9202651,OM401R,2024-02-21,2024-2-20 22:20,UTC +04:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN DATE 20.02.2024,Fuel Type or Sulphur will be wrong
40,4509932,d519ea74-4bfa-4bc0-b627-c272049d9baf,MSC ROSARIA,9320453,MX406R,2024-02-20,2024-2-20 0:10,UTC -05:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN DATE 20.02.2024,BDN is not given
41,4537500,971f8b08-a873-4d82-b90c-6bcecda6b50e,MSC ROSARIA,9320453,MX416R,2024-04-25,2024-4-24 15:35,UTC -04:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN DATE 24.04.2024,BDN is not given
42,4537499,c78107b4-6e49-4621-9961-25d2b9e1ae7c,MSC ROSARIA,9320453,MX416R,2024-04-25,2024-4-24 12:25,UTC -04:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN DATE 24.04.2024,Fuel Type or Sulphur will be wrong
43,4493736,6fc57f78-723e-402b-9d36-98c208da040c,MSC STELLA,9279989,NG350E,2024-01-13,2024-1-12 19:50,UTC +01:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,110795_BRDI_20,"Sulphur is not given,quantity is not given,BDN..."
44,4535387,124f7373-e22c-452e-af00-8dcb9cac67cb,MSC STELLA,9279989,NG417W,2024-04-30,2024-4-30 5:00,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BRZI_160,"Sulphur is not given,quantity is not given,BDN..."
45,4402164,16282380-7fee-4529-973b-3b5c421a86ff,MSC SVEVA,9708681,QG418E,2024-05-12,2024-5-11 12:44,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BRBTB202400000489,"Sulphur is not given,quantity is not given,BDN..."
46,4516089,c7cbcad2-c0e5-4725-a862-b5e3dd919ab9,MSC SVEVA,9708681,FS403E,2024-02-04,2024-2-4 4:45,UTC +01:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BQI2_54 111576,Check the quantity

In [21]:
#client_charter_bdn = client_charter_bdn.rename(columns=lambda x: x.lower(), inplace=True)
sorrento_remarks = sorrento_remarks.rename(columns={
    'gid': 'GID',
      'imo'  :     'IMO_No',
    'vessel_name'   :  'VSL',
    'report_date_time'  :'REPORT_DATE_TIME',
    'sulphur_content_pc': 'Sulphur_Content_PC',
    'quantity': 'Quantity',
    'port_delivery': 'Port_Delivery',
    'product_quality': 'Product_Quality',
    'delivery': 'Delivery',
    'bdn': 'BDN'
})

In [22]:
#client_charter_bdn = client_charter_bdn.rename(columns=lambda x: x.lower(), inplace=True)
client_sorrento_bdn = client_sorrento_bdn.rename(columns={
    'gid': 'GID',
      'imo'  :     'IMO_No',
    'vessel_name'   :  'VSL',
    'report_date_time'  :'REPORT_DATE_TIME',
    'sulphur_content_pc': 'Sulphur_Content_PC',
    'quantity': 'Quantity',
    'port_delivery': 'Port_Delivery',
    'product_quality': 'Product_Quality',
    'delivery': 'Delivery',
    'bdn': 'BDN'
})

In [23]:
sorrento_remarks

,id,GID,VSL,IMO_No,voy,corrected_date,REPORT_DATE_TIME,report_date_time_offset,report_type,status,...,created_at,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng,REMARKS,Delivery
0,4505963,97d6856c-4261-4a11-977a-e3891514cde1,MSC REGINA,9202651,OM401R,2024-02-21,2024-2-20 22:20,UTC +04:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN is not given,0
1,4520265,78343892-8205-44d5-b627-8cdc18b9ef72,MSC MICHAELA,9230488,UK408R,2024-03-08,2024-3-7 12:45,UTC -08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN is not given,NaN
2,4507718,abbe3849-08c6-4054-829c-29332e999624,MSC FABIENNE,9279965,NT404A,2024-02-02,2024-2-1 18:20,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN is not given,NO
3,4521417,0f9b48a5-55cb-4672-ace7-e980dfec4177,MSC LISA,9281279,MX409R,2024-03-07,2024-3-7 2:25,UTC +00:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN is not given,NaN
4,4393419,aae25f7a-fe3a-46ff-b49d-6b02d555e268,MSC LISA,9281279,CI421A,2024-05-30,2024-5-30 8:54,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN is not given,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367,4545474,25c45230-03f8-44a3-ba35-b97a1799af5a,MSC JIANI,9966934,YB413R,2024-04-16,2024-4-15 14:45,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,NaN,245578624
368,4504213,1464f0aa-214f-4d5f-91b7-9aa70687d1ca,MSC JIANI,9966934,XA352A,2024-01-15,2024-1-15 2:50,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,NaN,40410
369,4504203,ee7bd179-e0c7-421f-9d84-0c9e6ae33b15,MSC JIANI,9966934,XA352A,2024-01-10,2024-1-9 17:00,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,NaN,36-2300139
370,4504214,bc0dd51c-5113-4329-a163-b2a8b3e7f4e4,MSC JIANI,9966934,XA352A,2024-01-15,2024-1-15 8:00,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,NaN,eGID2024010941
371,4531849,8e69c893-5bce-41a4-8680-0544c5d14c37,MSC JIANI,9966934,YB410R,2024-03-20,2024-3-20 10:00,UTC +01:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,NaN,245352291

In [24]:
client_sorrento_bdn

,id,GID,VSL,IMO_No,voy,corrected_date,REPORT_DATE_TIME,report_date_time_offset,report_type,status,...,created_at,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng,Delivery,REMARKS
0,4506956,5970fb57-83b3-4dbf-96d0-27e3f938d11a,MSC ALYSSA,9235050,CI406R,2024-02-13,2024-2-13 0:00,UTC +00:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,0,Sulphur is not given
1,4542796,08856b18-12e0-4bb6-add9-0f099539d9e1,MSC AMSTERDAM,9606338,QG417E,2024-04-30,2024-4-29 18:10,UTC +01:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,NL0074002680,Sulphur is not given
2,4502526,62fb10b3-243c-417c-b021-b04f8bdfd5fa,MSC CLARA,9708693,FT348E,2024-01-06,2024-1-5 17:18,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,6254,Sulphur is not given
3,4491726,40834d6f-1661-4f5b-9480-9cbeafd162d7,MSC DIEGO,9202649,OM352A,2024-01-09,2024-1-8 14:25,UTC +05:30,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,411,Sulphur is not given
4,4519332,fed803bc-bef6-47c1-9d28-4646c189ed74,MSC DIEGO,9202649,OM352A,2024-03-15,2024-3-14 14:27,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,ABS DIEGO 14.03.24,Sulphur is not given
5,4519350,fda6ce27-7b40-46b9-95a1-82ef4b52efc1,MSC DIEGO,9202649,OM406R,2024-03-27,2024-3-26 20:10,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,MSC126,"Sulphur is not given,BDN is not given"
6,4531507,b26641ed-ed17-4ceb-805b-c6140ac30fe8,MSC DILETTA,9897004,FJ402E,2024-03-12,2024-3-11 14:57,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,13720788,Sulphur is not given
7,4531505,d86386aa-be02-449a-9211-67b957b99d87,MSC DILETTA,9897004,FJ402E,2024-03-11,2024-3-11 2:00,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,F055101,Sulphur is not given
8,4507718,abbe3849-08c6-4054-829c-29332e999624,MSC FABIENNE,9279965,NT404A,2024-02-02,2024-2-1 18:20,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,NO,Sulphur is not given
9,4397938,27ff2ad1-4e94-4d01-8ced-67f0655e29a4,MSC FRANCESCA,9401116,OW416R,2024-05-08,2024-5-8 6:30,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,4.06524E+11,Sulphur is not given
10,4401063,ad99dacc-fba5-46af-a67e-48624a1c2800,MSC ISTANBUL,9606326,QG420E,2024-05-30,2024-5-29 14:00,UTC -09:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BRDI129,Sulphur is not given
11,4401060,868f0e5c-a172-4dd0-a7a6-8d37999a7e2e,MSC ISTANBUL,9606326,QG420E,2024-05-29,2024-5-28 13:00,UTC -09:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,2.024E+11,Sulphur is not given
12,4511611,722839ec-543a-44b2-bab5-a2b1c877f371,MSC IVANA,9398371,FW351W,2024-02-14,2024-2-14 0:20,UTC +01:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BQ12_74,Sulphur is not given
13,4541370,f6aa2414-daa1-44a6-add1-4943c1b66543,MSC KATIE,9467457,IS413A,2024-05-01,2024-4-30 17:23,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,1954,Sulphur is not given
14,4527564,cef8edd4-f217-4077-a399-fd1cdc4a33d0,MSC KATIE,9467457,FD410E,2024-03-17,2024-3-16 15:10,UTC +01:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,4.06024E+11,"Sulphur is not given,Fuel Type or Sulphur will..."
15,4538562,97d11533-c1d7-45c9-9e93-699817a400eb,MSC KIM,9351581,NC413R,2024-04-17,2024-4-17 10:32,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,2.024E+11,Sulphur is not given
16,4396429,51538578-58d5-4a2e-9e9c-799da4a6eb08,MSC KIM,9351581,NC413R,2024-05-08,2024-5-7 16:10,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,2.024E+11,Sulphur is not given
17,4396779,141685f4-1074-4c3d-a172-6258542d9d57,MSC KRYSTAL,9372470,NJ417R,2024-05-26,2024-5-25 13:35,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BRBTB202497108695BD,"Sulphur is not given,BDN is not given"
18,4521417,0f9b48a5-55cb-4672-ace7-e980dfec4177,MSC LISA,9281279,MX409R,2024-03-07,2024-3-7 2:25,UTC +00:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,9956309,"Sulphur is not given,BDN is not given"
19,4393419,aae25f7a-fe3a-46ff-b49d-6b02d555e268,MSC LISA,9281279,CI421A,2024-05-30,2024-5-30 8:54,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,480327746,"Sulphur is not given,BDN is not given"
20,4393147,13a070d5-97dc-4a7e-b684-fe93efd5578e,MSC MARINA,9275971,QM420A,2024-05-29,2024-5-28 21:46,UTC +00:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,2405730,Sulphur is not given
21,4393119,d265d3d3-959e-4e28-b87d-e38fefe2ca8e,MSC MARINA,9275971,XA404A,2024-05-13,2024-5-13 5:40,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,ZJ20241678,Sulphur is not given
22,4504507,70037bff-42fe-4443-a837-6ef1f580cbd8,MSC MARTINA,9060637,OM402R,2024-02-29,2024-2-28 14:00,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,5345,BDN is not given
23,4504508,603a645a-8249-4119-90c7-501e753a2f45,MSC MARTINA,9060637,OM402R,2024-02-29,2024-2-28 15:20,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,5344,BDN is not given
24,4504509,1a7da3a3-42fa-4aac-89a1-6e589c8a02d3,MSC MARTINA,9060637,OM402R,2024-02-29,2024-2-28 17:30,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,5323,BDN is not given
25,4504517,d18be661-8df5-42ef-9bf3-802f49852da2,MSC MARTINA,9060637,OM409A,2024-03-01,2024-2-29 15:00,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,3781,BDN is not given
26,4532021,ddd4d0b9-ab86-407c-a888-41c6594fc9ba,MSC MARTINA,9060637,OM409A,2024-04-10,2024-4-9 18:00,UTC +03:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,RSV 9743,BDN is not given
27,4492546,a01618bc-bb31-4683-9932-78494d4c4439,MSC MELISSA,9226918,OW401R,2024-01-12,2024-1-12 3:20,UTC +00:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,480319530A,BDN is not given
28,4492545,63990e38-0431-4812-89ed-1de09f021d35,MSC MELISSA,9226918,OW401R,2024-01-12,2024-1-12 3:20,UTC +00:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,480319530,BDN is not given
29,4506707,3996f580-0709-4d03-9043-c4b8632dba41,MSC MELISSA,9226918,OW404R,2024-02-10,2024-2-9 19:10,UTC +00:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,480321065,BDN is not given
30,4520265,78343892-8205-44d5-b627-8cdc18b9ef72,MSC MICHAELA,9230488,UK408R,2024-03-08,2024-3-7 12:45,UTC -08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN DATE 07.03.2024,BDN is not given
31,4501357,b027b770-e743-4ba4-89e9-f1f0a1430e91,MSC NEW YORK,9606314,QJ350S,2024-01-12,2024-1-12 6:45,UTC +09:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,FF00110782,BDN is not given
32,4401901,274a22da-9965-422c-9564-07d7415b0371,MSC OLIVER,9703306,FT409E,2024-05-26,2024-5-25 23:00,UTC +07:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BC/VITOL/24/00224,BDN is not given
33,4396863,cce39773-a2ca-4e6d-b4b4-7bcb896a1cda,MSC ORIANE,9372482,MX420R,2024-05-27,2024-5-27 7:50,UTC -04:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN DATE 27.05.2024,BDN is not given
34,4396852,04985951-66b2-4a55-b2fd-36e9882b68e6,MSC ORIANE,9372482,MX420R,2024-05-24,2024-5-23 18:35,UTC -04:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,10155347,Fuel Type or Sulphur will be wrong
35,4396851,2ecd8b7b-9867-4d54-98fb-85671f26e139,MSC ORIANE,9372482,MX420R,2024-05-24,2024-5-23 18:35,UTC -04:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,10155347,Fuel Type or Sulphur will be wrong
36,4391394,620fa7a2-e0ae-46aa-8a98-3e2808b3399d,MSC REGINA,9202651,OM414A,2024-05-22,2024-5-21 13:40,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,N.A.,IGNORE
37,4391395,eb6c02f7-06c7-49cb-84bf-af0b580ca6eb,MSC REGINA,9202651,OM414A,2024-05-22,2024-5-21 13:50,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,N.A,IGNORE
38,4391396,5ea53085-ebe5-416a-8b3c-034b2f712975,MSC REGINA,9202651,OM414A,2024-05-22,2024-5-21 14:00,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,NaN,IGNORE
39,4505963,97d6856c-4261-4a11-977a-e3891514cde1,MSC REGINA,9202651,OM401R,2024-02-21,2024-2-20 22:20,UTC +04:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN DATE 20.02.2024,Fuel Type or Sulphur will be wrong
40,4509932,d519ea74-4bfa-4bc0-b627-c272049d9baf,MSC ROSARIA,9320453,MX406R,2024-02-20,2024-2-20 0:10,UTC -05:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN DATE 20.02.2024,BDN is not given
41,4537500,971f8b08-a873-4d82-b90c-6bcecda6b50e,MSC ROSARIA,9320453,MX416R,2024-04-25,2024-4-24 15:35,UTC -04:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN DATE 24.04.2024,BDN is not given
42,4537499,c78107b4-6e49-4621-9961-25d2b9e1ae7c,MSC ROSARIA,9320453,MX416R,2024-04-25,2024-4-24 12:25,UTC -04:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN DATE 24.04.2024,Fuel Type or Sulphur will be wrong
43,4493736,6fc57f78-723e-402b-9d36-98c208da040c,MSC STELLA,9279989,NG350E,2024-01-13,2024-1-12 19:50,UTC +01:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,110795_BRDI_20,"Sulphur is not given,quantity is not given,BDN..."
44,4535387,124f7373-e22c-452e-af00-8dcb9cac67cb,MSC STELLA,9279989,NG417W,2024-04-30,2024-4-30 5:00,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BRZI_160,"Sulphur is not given,quantity is not given,BDN..."
45,4402164,16282380-7fee-4529-973b-3b5c421a86ff,MSC SVEVA,9708681,QG418E,2024-05-12,2024-5-11 12:44,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BRBTB202400000489,"Sulphur is not given,quantity is not given,BDN..."
46,4516089,c7cbcad2-c0e5-4725-a862-b5e3dd919ab9,MSC SVEVA,9708681,FS403E,2024-02-04,2024-2-4 4:45,UTC +01:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BQI2_54 111576,Check the quantity

In [25]:
value_map = dict(zip(client_sorrento_bdn['GID'], client_sorrento_bdn['Sulphur_Content_PC']))
sorrento_remarks['Sulphur_Content_PC'] = sorrento_remarks['GID'].map(value_map).fillna(sorrento_remarks['Sulphur_Content_PC'])

value_map = dict(zip(client_sorrento_bdn['GID'], client_sorrento_bdn['REPORT_DATE_TIME']))
sorrento_remarks['REPORT_DATE_TIME'] = sorrento_remarks['GID'].map(value_map).fillna(sorrento_remarks['REPORT_DATE_TIME'])

value_map_1 = dict(zip(client_sorrento_bdn['GID'], client_sorrento_bdn['Quantity']))
sorrento_remarks['Quantity'] = sorrento_remarks['GID'].map(value_map_1).fillna(sorrento_remarks['Quantity'])

value_map_1 = dict(zip(client_sorrento_bdn['GID'], client_sorrento_bdn['Product_Quality']))
sorrento_remarks['Product_Quality'] = sorrento_remarks['GID'].map(value_map_1).fillna(sorrento_remarks['Product_Quality'])

value_map_2 = dict(zip(client_sorrento_bdn['GID'], client_sorrento_bdn['Delivery']))
sorrento_remarks['Delivery'] = sorrento_remarks['GID'].map(value_map_2).fillna(sorrento_remarks['Delivery'])
sorrento_remarks

,id,GID,VSL,IMO_No,voy,corrected_date,REPORT_DATE_TIME,report_date_time_offset,report_type,status,...,created_at,updated_at,created_by_id,updated_by_id,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_boiler_lng,REMARKS,Delivery
0,4505963,97d6856c-4261-4a11-977a-e3891514cde1,MSC REGINA,9202651,OM401R,2024-02-21,2024-2-20 22:20,UTC +04:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN is not given,BDN DATE 20.02.2024
1,4520265,78343892-8205-44d5-b627-8cdc18b9ef72,MSC MICHAELA,9230488,UK408R,2024-03-08,2024-3-7 12:45,UTC -08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN is not given,BDN DATE 07.03.2024
2,4507718,abbe3849-08c6-4054-829c-29332e999624,MSC FABIENNE,9279965,NT404A,2024-02-02,2024-2-1 18:20,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN is not given,NO
3,4521417,0f9b48a5-55cb-4672-ace7-e980dfec4177,MSC LISA,9281279,MX409R,2024-03-07,2024-3-7 2:25,UTC +00:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN is not given,9956309
4,4393419,aae25f7a-fe3a-46ff-b49d-6b02d555e268,MSC LISA,9281279,CI421A,2024-05-30,2024-5-30 8:54,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,BDN is not given,480327746
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367,4545474,25c45230-03f8-44a3-ba35-b97a1799af5a,MSC JIANI,9966934,YB413R,2024-04-16,2024-4-15 14:45,UTC +02:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,NaN,245578624
368,4504213,1464f0aa-214f-4d5f-91b7-9aa70687d1ca,MSC JIANI,9966934,XA352A,2024-01-15,2024-1-15 2:50,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,NaN,40410
369,4504203,ee7bd179-e0c7-421f-9d84-0c9e6ae33b15,MSC JIANI,9966934,XA352A,2024-01-10,2024-1-9 17:00,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,NaN,36-2300139
370,4504214,bc0dd51c-5113-4329-a163-b2a8b3e7f4e4,MSC JIANI,9966934,XA352A,2024-01-15,2024-1-15 8:00,UTC +08:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,NaN,eGID2024010941
371,4531849,8e69c893-5bce-41a4-8680-0544c5d14c37,MSC JIANI,9966934,YB410R,2024-03-20,2024-3-20 10:00,UTC +01:00,REFL,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,NaN,245352291

In [26]:
ignored_data_s = client_sorrento_bdn[client_sorrento_bdn['REMARKS']=='IGNORE']
ignored_data_lst_s = ignored_data_s['GID'].unique().tolist()
ignored_data_lst_s

['620fa7a2-e0ae-46aa-8a98-3e2808b3399d',
 'eb6c02f7-06c7-49cb-84bf-af0b580ca6eb',
 '5ea53085-ebe5-416a-8b3c-034b2f712975']

In [27]:
file_change_refl_vtout_ignored_s = sorrento_remarks[~sorrento_remarks['GID'].isin(ignored_data_lst_s)]
#sorrento_remarks_db = file_change_refl_vtout_ignored_s[['GID','Sulphur_Content_PC','Quantity','Port_Delivery','Product_Quality','Delivery']]
#sorrento_remarks_db

In [28]:
sr=file_change_refl_vtout_ignored_s[['GID','IMO_No','VSL','REPORT_DATE_TIME','Sulphur_Content_PC','Quantity','Port_Delivery','Product_Quality','Delivery']]

In [29]:
sr['Sulphur_Content_PC'].isna().sum()

0

In [30]:
sorrentonan = sr[sr['Sulphur_Content_PC'].isna()]
sorrentonan

Empty DataFrame
Columns: [GID, IMO_No, VSL, REPORT_DATE_TIME, Sulphur_Content_PC, Quantity, Port_Delivery, Product_Quality, Delivery]
Index: []

In [31]:
sr['BDN'] = 'YES'
sr

,GID,IMO_No,VSL,REPORT_DATE_TIME,Sulphur_Content_PC,Quantity,Port_Delivery,Product_Quality,Delivery,BDN
0,97d6856c-4261-4a11-977a-e3891514cde1,9202651,MSC REGINA,2024-2-20 22:20,0.0800,80.000,AEAUH,DISTILLATES,BDN DATE 20.02.2024,YES
1,78343892-8205-44d5-b627-8cdc18b9ef72,9230488,MSC MICHAELA,2024-3-7 12:45,1.2100,1500.300,USSEA,RESIDUAL HS,BDN DATE 07.03.2024,YES
2,abbe3849-08c6-4054-829c-29332e999624,9279965,MSC FABIENNE,2024-2-1 18:20,0.0900,100.630,DEHAM,DISTILLATES,NO,YES
3,0f9b48a5-55cb-4672-ace7-e980dfec4177,9281279,MSC LISA,2024-3-7 2:25,0.0108,600.770,USNYC,DISTILLATES,9956309,YES
4,aae25f7a-fe3a-46ff-b49d-6b02d555e268,9281279,MSC LISA,2024-5-30 8:54,0.0640,399.900,ESVLC,DISTILLATES,480327746,YES
...,...,...,...,...,...,...,...,...,...,...
367,25c45230-03f8-44a3-ba35-b97a1799af5a,9966934,MSC JIANI,2024-4-15 14:45,0.0010,77.429,ESBCN,DISTILLATES,245578624,YES
368,1464f0aa-214f-4d5f-91b7-9aa70687d1ca,9966934,MSC JIANI,2024-1-15 2:50,0.0870,149.992,SGSIN,DISTILLATES,40410,YES
369,ee7bd179-e0c7-421f-9d84-0c9e6ae33b15,9966934,MSC JIANI,2024-1-9 17:00,0.4650,496.844,CNSHA,RESIDUAL VLS,36-2300139,YES
370,bc0dd51c-5113-4329-a163-b2a8b3e7f4e4,9966934,MSC JIANI,2024-1-15 8:00,0.4900,500.172,SGSIN,RESIDUAL VLS,eGID2024010941,YES
371,8e69c893-5bce-41a4-8680-0544c5d14c37,9966934,MSC JIANI,2024-3-20 10:00,0.4900,200.000,ESBCN,RESIDUAL VLS,245352291,YES

In [32]:
# charter_sorrento_db = pd.concat([charter_remarks_db,sorrento_remarks_db])
# charter_sorrento_db

In [33]:
charter_sorrento_dbs=pd.concat([cr,sr])
charter_sorrento_dbs

,GID,IMO_No,VSL,REPORT_DATE_TIME,Sulphur_Content_PC,Quantity,Port_Delivery,Product_Quality,Delivery,BDN
0,3eacc476-c023-494d-a6ce-a1aa6378218d,9256470,MSC QINGDAO,2024-1-1 14:35,0.470,1000.019,ITGOA,RESIDUAL VLS,2195,YES
1,d54b3fce-c7e4-4423-bd60-99066cd81cc5,9085534,KOTKA,2024-1-1 9:42,0.486,4498.000,SGSIN,RESIDUAL VLS,14799,YES
2,a0467399-7302-4cfa-a98e-01ae7ba67a4c,9297589,ALANA,2024-1-12 13:00,0.099,300.597,BEANR,RESIDUAL ULS,BRZI _ 32,YES
3,a030ad08-a899-45f3-8fb8-c828f0d620bc,9247742,MSC BOSPHORUS,2024-1-13 10:08,2.830,2885.250,PAROD,RESIDUAL HS,0847-GB,YES
4,d52d5be1-85ba-4971-99cf-d1cefe281b8c,9256365,MED CESME,2024-1-13 15:20,0.050,50.000,TRITY,DISTILLATES,164069,YES
...,...,...,...,...,...,...,...,...,...,...
367,25c45230-03f8-44a3-ba35-b97a1799af5a,9966934,MSC JIANI,2024-4-15 14:45,0.001,77.429,ESBCN,DISTILLATES,245578624,YES
368,1464f0aa-214f-4d5f-91b7-9aa70687d1ca,9966934,MSC JIANI,2024-1-15 2:50,0.087,149.992,SGSIN,DISTILLATES,40410,YES
369,ee7bd179-e0c7-421f-9d84-0c9e6ae33b15,9966934,MSC JIANI,2024-1-9 17:00,0.465,496.844,CNSHA,RESIDUAL VLS,36-2300139,YES
370,bc0dd51c-5113-4329-a163-b2a8b3e7f4e4,9966934,MSC JIANI,2024-1-15 8:00,0.490,500.172,SGSIN,RESIDUAL VLS,eGID2024010941,YES
371,8e69c893-5bce-41a4-8680-0544c5d14c37,9966934,MSC JIANI,2024-3-20 10:00,0.490,200.000,ESBCN,RESIDUAL VLS,245352291,YES

### Download the file and give it to software team to update this through 'UPDATE GID CODE (CHARTER)'

In [34]:
#charter_sorrento_db.to_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JUL23 TO DEC23/OUTPUT FOR DB/charter_sorrento_update_GID.xlsx", index = False)

In [35]:
charter_sorrento_dbs.to_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24/OUTPUT FOR DB/charter_sorrento_update_GID.xlsx", index = False)

In [36]:
#charter_sorrento_db.to_csv(r"D:\Navalt\MSC\2024\ESI\Group A\JUL23 TO DEC23/OUTPUT FOR DB/charter_sorrento_update_GID.csv", index = False)

In [37]:
charter_sorrento_dbs.to_csv(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24/OUTPUT FOR DB/charter_sorrento_update_GID.csv", index = False)

# MSCSMCY

In [77]:
msc_remark = pd.read_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\OUTPUT/MSCSMCY MISSING BDNs refl.xlsx")
msc_remark

,id,imo,vessel,id_vessel,gid,voyage,corrected_date,report_date_time,report_date_time_offset,report_type,...,fuel_boiler_lng,rob_rsdl_lng,sulphur_content_pc_main,quantity_main,port_delivery_main,product_quality_main,delivery_main,bdn_number_main,delivery,REMARKS
0,5732600,8521402,MSC ANNAMARIA,ANMA,5189583,NaN,2023-12-31 21:25:00,2024-01-01 00:25:00,UTC-03:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
1,5732601,8521402,MSC ANNAMARIA,ANMA,5189587,NaN,2023-12-31 21:35:00,2024-01-01 00:35:00,UTC-03:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2,5760028,9702089,MSC VITA,VITA,5189807,NaN,2024-01-01 11:00:00,2024-01-01 10:00:00,UTC+01:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
3,5753589,9330226,MSC ABIGAIL F,ABIG,5190958,NaN,2024-01-01 12:14:00,2024-01-01 12:14:00,UTC+00:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
4,5748708,9292175,MSC SHANELLE V,SHNL,5190148,NaN,2024-01-01 13:15:00,2024-01-01 13:15:00,UTC+00:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2303,6311513,9244881,MSC ARUSHI R,ARUS,5532057,NaN,2024-06-30 15:39:00,2024-06-30 13:39:00,UTC+02:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2304,6304722,9162643,MSC LEA,LEA,5530815,NaN,2024-06-30 17:30:00,2024-06-30 14:30:00,UTC+03:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2305,6299544,8512906,MSC ADELE,ADEL,5533194,NaN,2024-06-30 22:06:00,2024-06-30 16:36:00,UTC+05:30,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2306,6321378,9360271,MSC CAPE III,CAPE,5531232,NaN,2024-06-30 19:48:00,2024-06-30 19:48:00,UTC+00:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2307,6311514,9244881,MSC ARUSHI R,ARUS,5532055,NaN,2024-06-30 22:30:00,2024-06-30 20:30:00,UTC+02:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN

In [78]:
msc_remarks = msc_remark[msc_remark['report_type'] == 'REFL']
msc_remarks

,id,imo,vessel,id_vessel,gid,voyage,corrected_date,report_date_time,report_date_time_offset,report_type,...,fuel_boiler_lng,rob_rsdl_lng,sulphur_content_pc_main,quantity_main,port_delivery_main,product_quality_main,delivery_main,bdn_number_main,delivery,REMARKS
0,5732600,8521402,MSC ANNAMARIA,ANMA,5189583,NaN,2023-12-31 21:25:00,2024-01-01 00:25:00,UTC-03:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
1,5732601,8521402,MSC ANNAMARIA,ANMA,5189587,NaN,2023-12-31 21:35:00,2024-01-01 00:35:00,UTC-03:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2,5760028,9702089,MSC VITA,VITA,5189807,NaN,2024-01-01 11:00:00,2024-01-01 10:00:00,UTC+01:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
3,5753589,9330226,MSC ABIGAIL F,ABIG,5190958,NaN,2024-01-01 12:14:00,2024-01-01 12:14:00,UTC+00:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
4,5748708,9292175,MSC SHANELLE V,SHNL,5190148,NaN,2024-01-01 13:15:00,2024-01-01 13:15:00,UTC+00:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2303,6311513,9244881,MSC ARUSHI R,ARUS,5532057,NaN,2024-06-30 15:39:00,2024-06-30 13:39:00,UTC+02:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2304,6304722,9162643,MSC LEA,LEA,5530815,NaN,2024-06-30 17:30:00,2024-06-30 14:30:00,UTC+03:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2305,6299544,8512906,MSC ADELE,ADEL,5533194,NaN,2024-06-30 22:06:00,2024-06-30 16:36:00,UTC+05:30,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2306,6321378,9360271,MSC CAPE III,CAPE,5531232,NaN,2024-06-30 19:48:00,2024-06-30 19:48:00,UTC+00:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2307,6311514,9244881,MSC ARUSHI R,ARUS,5532055,NaN,2024-06-30 22:30:00,2024-06-30 20:30:00,UTC+02:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN

In [79]:
client_msc_bdn = pd.read_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\CLIENT FILE/MSCSMCY MISSING BDNs.xlsx")
client_msc_bdn

,id,imo,vessel,id_vessel,gid,voyage,corrected_date,report_date_time,report_date_time_offset,report_type,...,fuel_boiler_lng,rob_rsdl_lng,sulphur_content_pc_main,quantity_main,port_delivery_main,product_quality_main,delivery_main,bdn_number_main,delivery,REMARKS
0,5740180,9210086,MSC ABY,ABY,5218514,NaN,2024-01-11 23:40:00,2024-01-12 04:40:00,UTC-05:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24A00047,BDN is not given
1,5754557,9344708,MSC ADYA,NaN,cab0d3d6-2059-486d-84ac-79592a1d3343,NaN,2024-06-01 00:00:00,2024-02-20 03:05:00,UTC-02-20,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FLNGBELLINA-2024-003,BDN is not given
2,5764561,9932050,MSC ADYA,NaN,4c78b1d1-fd7e-4a3b-a795-0add2d885bca,NaN,2024-06-01 00:00:00,2024-02-20 11:25:00,UTC-02-20,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GET00104,BDN is not given
3,5734485,9060649,MSC ADYA,NaN,8bddafa1-5a61-41ef-83d8-2ea47d3ff073,NaN,2024-06-01 00:00:00,2024-02-20 13:54:00,UTC-02-21,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6676,BDN is not given
4,5734429,9057173,MSC ADYA,NaN,a250d520-4fd9-4495-8553-c77893803097,NaN,2024-06-01 00:00:00,2024-03-28 23:40:00,UTC-03-29,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BDN DATE 28.03.2024,"Sulphur is not given,BDN is not given"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,6304154,9154191,WEC MONDRIAAN,WECM,5452082,NaN,2024-05-18 14:40:00,2024-05-18 14:40:00,UTC+00:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,282024001035,BDN is not given
225,6321080,9354363,WEC MONDRIAAN,WECM,5489520,NaN,2024-06-09 13:20:00,2024-06-09 13:20:00,UTC+00:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,282024001035,BDN is not given
226,5750179,9301990,WEC MONDRIAAN,WECM,5531076,NaN,2024-06-30 09:40:00,2024-06-30 09:40:00,UTC+00:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,282024001035,BDN is not given
227,5778373,9253038,WEC VAN RIJN,WVRN,5384661,NaN,2024-04-13 22:50:00,2024-04-13 22:50:00,UTC+02:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RJ1304.1,BDN is not given
228,5781101,9293167,WEC VAN RIJN,WVRN,5480292,NaN,2024-06-04 22:30:00,2024-06-04 20:30:00,UTC+02:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A46242,BDN is not given

In [81]:
#client_charter_bdn = client_charter_bdn.rename(columns=lambda x: x.lower(), inplace=True)
client_msc_bdn = client_msc_bdn.rename(columns={
    'gid': 'GID',
      'imo'  :     'IMO_No',
    'vessel'   :  'VSL',
    'report_date_time'  :'REPORT_DATE_TIME',
    'sulphur_content_pc': 'Sulphur_Content_PC',
    'quantity': 'Quantity',
    'port_delivery': 'Port_Delivery',
    'product_quality': 'Product_Quality',
    'delivery': 'Delivery',
    'bdn': 'BDN'
})

In [82]:
#client_charter_bdn = client_charter_bdn.rename(columns=lambda x: x.lower(), inplace=True)
msc_remarks = msc_remarks.rename(columns={
    'gid': 'GID',
      'imo'  :     'IMO_No',
    'vessel'   :  'VSL',
    'report_date_time'  :'REPORT_DATE_TIME',
    'sulphur_content_pc': 'Sulphur_Content_PC',
    'quantity': 'Quantity',
    'port_delivery': 'Port_Delivery',
    'product_quality': 'Product_Quality',
    'delivery': 'Delivery',
    'bdn': 'BDN'
})

In [83]:
msc_remarks

,id,IMO_No,VSL,id_vessel,GID,voyage,corrected_date,REPORT_DATE_TIME,report_date_time_offset,report_type,...,fuel_boiler_lng,rob_rsdl_lng,sulphur_content_pc_main,quantity_main,port_delivery_main,product_quality_main,delivery_main,bdn_number_main,Delivery,REMARKS
0,5732600,8521402,MSC ANNAMARIA,ANMA,5189583,NaN,2023-12-31 21:25:00,2024-01-01 00:25:00,UTC-03:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
1,5732601,8521402,MSC ANNAMARIA,ANMA,5189587,NaN,2023-12-31 21:35:00,2024-01-01 00:35:00,UTC-03:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2,5760028,9702089,MSC VITA,VITA,5189807,NaN,2024-01-01 11:00:00,2024-01-01 10:00:00,UTC+01:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
3,5753589,9330226,MSC ABIGAIL F,ABIG,5190958,NaN,2024-01-01 12:14:00,2024-01-01 12:14:00,UTC+00:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
4,5748708,9292175,MSC SHANELLE V,SHNL,5190148,NaN,2024-01-01 13:15:00,2024-01-01 13:15:00,UTC+00:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2303,6311513,9244881,MSC ARUSHI R,ARUS,5532057,NaN,2024-06-30 15:39:00,2024-06-30 13:39:00,UTC+02:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2304,6304722,9162643,MSC LEA,LEA,5530815,NaN,2024-06-30 17:30:00,2024-06-30 14:30:00,UTC+03:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2305,6299544,8512906,MSC ADELE,ADEL,5533194,NaN,2024-06-30 22:06:00,2024-06-30 16:36:00,UTC+05:30,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2306,6321378,9360271,MSC CAPE III,CAPE,5531232,NaN,2024-06-30 19:48:00,2024-06-30 19:48:00,UTC+00:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2307,6311514,9244881,MSC ARUSHI R,ARUS,5532055,NaN,2024-06-30 22:30:00,2024-06-30 20:30:00,UTC+02:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN

In [84]:
client_msc_bdn

,id,IMO_No,VSL,id_vessel,GID,voyage,corrected_date,REPORT_DATE_TIME,report_date_time_offset,report_type,...,fuel_boiler_lng,rob_rsdl_lng,sulphur_content_pc_main,quantity_main,port_delivery_main,product_quality_main,delivery_main,bdn_number_main,Delivery,REMARKS
0,5740180,9210086,MSC ABY,ABY,5218514,NaN,2024-01-11 23:40:00,2024-01-12 04:40:00,UTC-05:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24A00047,BDN is not given
1,5754557,9344708,MSC ADYA,NaN,cab0d3d6-2059-486d-84ac-79592a1d3343,NaN,2024-06-01 00:00:00,2024-02-20 03:05:00,UTC-02-20,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FLNGBELLINA-2024-003,BDN is not given
2,5764561,9932050,MSC ADYA,NaN,4c78b1d1-fd7e-4a3b-a795-0add2d885bca,NaN,2024-06-01 00:00:00,2024-02-20 11:25:00,UTC-02-20,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GET00104,BDN is not given
3,5734485,9060649,MSC ADYA,NaN,8bddafa1-5a61-41ef-83d8-2ea47d3ff073,NaN,2024-06-01 00:00:00,2024-02-20 13:54:00,UTC-02-21,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6676,BDN is not given
4,5734429,9057173,MSC ADYA,NaN,a250d520-4fd9-4495-8553-c77893803097,NaN,2024-06-01 00:00:00,2024-03-28 23:40:00,UTC-03-29,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BDN DATE 28.03.2024,"Sulphur is not given,BDN is not given"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,6304154,9154191,WEC MONDRIAAN,WECM,5452082,NaN,2024-05-18 14:40:00,2024-05-18 14:40:00,UTC+00:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,282024001035,BDN is not given
225,6321080,9354363,WEC MONDRIAAN,WECM,5489520,NaN,2024-06-09 13:20:00,2024-06-09 13:20:00,UTC+00:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,282024001035,BDN is not given
226,5750179,9301990,WEC MONDRIAAN,WECM,5531076,NaN,2024-06-30 09:40:00,2024-06-30 09:40:00,UTC+00:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,282024001035,BDN is not given
227,5778373,9253038,WEC VAN RIJN,WVRN,5384661,NaN,2024-04-13 22:50:00,2024-04-13 22:50:00,UTC+02:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RJ1304.1,BDN is not given
228,5781101,9293167,WEC VAN RIJN,WVRN,5480292,NaN,2024-06-04 22:30:00,2024-06-04 20:30:00,UTC+02:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A46242,BDN is not given

In [85]:
value_map = dict(zip(client_msc_bdn['GID'], client_msc_bdn['Sulphur_Content_PC']))
msc_remarks['Sulphur_Content_PC'] = msc_remarks['GID'].map(value_map).fillna(msc_remarks['Sulphur_Content_PC'])

value_map = dict(zip(client_msc_bdn['GID'], client_msc_bdn['REPORT_DATE_TIME']))
msc_remarks['REPORT_DATE_TIME'] = msc_remarks['GID'].map(value_map).fillna(msc_remarks['REPORT_DATE_TIME'])


value_map_1 = dict(zip(client_msc_bdn['GID'], client_msc_bdn['Quantity']))
msc_remarks['Quantity'] = msc_remarks['GID'].map(value_map_1).fillna(msc_remarks['Quantity'])

value_map_1 = dict(zip(client_msc_bdn['GID'], client_msc_bdn['Product_Quality']))
msc_remarks['Product_Quality'] = msc_remarks['GID'].map(value_map_1).fillna(msc_remarks['Product_Quality'])

value_map_2 = dict(zip(client_msc_bdn['GID'], client_msc_bdn['Delivery']))
msc_remarks['Delivery'] = msc_remarks['GID'].map(value_map_2).fillna(msc_remarks['Delivery'])
msc_remarks

,id,IMO_No,VSL,id_vessel,GID,voyage,corrected_date,REPORT_DATE_TIME,report_date_time_offset,report_type,...,fuel_boiler_lng,rob_rsdl_lng,sulphur_content_pc_main,quantity_main,port_delivery_main,product_quality_main,delivery_main,bdn_number_main,Delivery,REMARKS
0,5732600,8521402,MSC ANNAMARIA,ANMA,5189583,NaN,2023-12-31 21:25:00,2024-01-01 00:25:00,UTC-03:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
1,5732601,8521402,MSC ANNAMARIA,ANMA,5189587,NaN,2023-12-31 21:35:00,2024-01-01 00:35:00,UTC-03:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2,5760028,9702089,MSC VITA,VITA,5189807,NaN,2024-01-01 11:00:00,2024-01-01 10:00:00,UTC+01:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
3,5753589,9330226,MSC ABIGAIL F,ABIG,5190958,NaN,2024-01-01 12:14:00,2024-01-01 12:14:00,UTC+00:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
4,5748708,9292175,MSC SHANELLE V,SHNL,5190148,NaN,2024-01-01 13:15:00,2024-01-01 13:15:00,UTC+00:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2303,6311513,9244881,MSC ARUSHI R,ARUS,5532057,NaN,2024-06-30 15:39:00,2024-06-30 13:39:00,UTC+02:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2304,6304722,9162643,MSC LEA,LEA,5530815,NaN,2024-06-30 17:30:00,2024-06-30 14:30:00,UTC+03:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2305,6299544,8512906,MSC ADELE,ADEL,5533194,NaN,2024-06-30 22:06:00,2024-06-30 16:36:00,UTC+05:30,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2306,6321378,9360271,MSC CAPE III,CAPE,5531232,NaN,2024-06-30 19:48:00,2024-06-30 19:48:00,UTC+00:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2307,6311514,9244881,MSC ARUSHI R,ARUS,5532055,NaN,2024-06-30 22:30:00,2024-06-30 20:30:00,UTC+02:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN

In [86]:
msc_remarks['Delivery'].value_counts()

BRBRB202400009063      8
282024001035           4
BDN DATE 26.02.2024    4
BDN DATE 23.06.2024    3
BDN DATE 18.01.2024    3
                      ..
FLNGVENOSA-2024-016    1
AE190845               1
12711381               1
16040                  1
BDN DATE 28.06.2024    1
Name: Delivery, Length: 181, dtype: int64

In [87]:
msc_remarks

,id,IMO_No,VSL,id_vessel,GID,voyage,corrected_date,REPORT_DATE_TIME,report_date_time_offset,report_type,...,fuel_boiler_lng,rob_rsdl_lng,sulphur_content_pc_main,quantity_main,port_delivery_main,product_quality_main,delivery_main,bdn_number_main,Delivery,REMARKS
0,5732600,8521402,MSC ANNAMARIA,ANMA,5189583,NaN,2023-12-31 21:25:00,2024-01-01 00:25:00,UTC-03:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
1,5732601,8521402,MSC ANNAMARIA,ANMA,5189587,NaN,2023-12-31 21:35:00,2024-01-01 00:35:00,UTC-03:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2,5760028,9702089,MSC VITA,VITA,5189807,NaN,2024-01-01 11:00:00,2024-01-01 10:00:00,UTC+01:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
3,5753589,9330226,MSC ABIGAIL F,ABIG,5190958,NaN,2024-01-01 12:14:00,2024-01-01 12:14:00,UTC+00:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
4,5748708,9292175,MSC SHANELLE V,SHNL,5190148,NaN,2024-01-01 13:15:00,2024-01-01 13:15:00,UTC+00:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2303,6311513,9244881,MSC ARUSHI R,ARUS,5532057,NaN,2024-06-30 15:39:00,2024-06-30 13:39:00,UTC+02:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2304,6304722,9162643,MSC LEA,LEA,5530815,NaN,2024-06-30 17:30:00,2024-06-30 14:30:00,UTC+03:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2305,6299544,8512906,MSC ADELE,ADEL,5533194,NaN,2024-06-30 22:06:00,2024-06-30 16:36:00,UTC+05:30,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2306,6321378,9360271,MSC CAPE III,CAPE,5531232,NaN,2024-06-30 19:48:00,2024-06-30 19:48:00,UTC+00:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2307,6311514,9244881,MSC ARUSHI R,ARUS,5532055,NaN,2024-06-30 22:30:00,2024-06-30 20:30:00,UTC+02:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN

In [89]:
msc_remarks.to_csv("msc_remarks.csv")

In [90]:
msc_remarks_ignore = client_msc_bdn[(client_msc_bdn['REMARKS'] == 'IGNORE') | (client_msc_bdn['REMARKS'] == 'Debunker ignore')]
msc_remarks_ignore

,id,IMO_No,VSL,id_vessel,GID,voyage,corrected_date,REPORT_DATE_TIME,report_date_time_offset,report_type,...,fuel_boiler_lng,rob_rsdl_lng,sulphur_content_pc_main,quantity_main,port_delivery_main,product_quality_main,delivery_main,bdn_number_main,Delivery,REMARKS
58,5782291,9301550,MSC CAPRI,CAPR,5279523,NaN,2024-02-17 20:30:00,2024-02-17 18:30:00,UTC+02:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IGNORE
136,6255954,9354363,MSC MARIAGRAZIA,NaN,1ef7d4a1-15a4-4ece-9f66-00e7ab03b10e,NaN,2024-05-31 00:00:00,2024-05-25 19:36:00,UTC-05-26,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IGNORE
138,6242665,9226932,MSC MARIAGRAZIA,NaN,b6073898-97ba-47c1-b21d-064a4007273f,NaN,2024-05-31 00:00:00,2024-05-27 13:10:00,UTC-05-28,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IGNORE
142,6339573,9946879,MSC MARIE,NaN,b04b925d-5bf1-43a2-ad7b-f519fedaf912,NaN,2024-05-31 00:00:00,2024-03-09 19:35:00,UTC-03-10,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IGNORE
144,6339191,9360764,MSC MARIE,NaN,ce795b15-0578-4a3f-b5eb-742b24ff80f9,NaN,2024-05-31 00:00:00,2024-03-10 17:15:00,UTC-03-11,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IGNORE

In [91]:
gid = msc_remarks_ignore['GID'].unique().tolist()
gid

[5279523,
 '1ef7d4a1-15a4-4ece-9f66-00e7ab03b10e',
 'b6073898-97ba-47c1-b21d-064a4007273f',
 'b04b925d-5bf1-43a2-ad7b-f519fedaf912',
 'ce795b15-0578-4a3f-b5eb-742b24ff80f9']

In [92]:
msc_remarks_ok = msc_remarks[~msc_remarks['GID'].isin(gid)]
msc_remarks_ok

,id,IMO_No,VSL,id_vessel,GID,voyage,corrected_date,REPORT_DATE_TIME,report_date_time_offset,report_type,...,fuel_boiler_lng,rob_rsdl_lng,sulphur_content_pc_main,quantity_main,port_delivery_main,product_quality_main,delivery_main,bdn_number_main,Delivery,REMARKS
0,5732600,8521402,MSC ANNAMARIA,ANMA,5189583,NaN,2023-12-31 21:25:00,2024-01-01 00:25:00,UTC-03:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
1,5732601,8521402,MSC ANNAMARIA,ANMA,5189587,NaN,2023-12-31 21:35:00,2024-01-01 00:35:00,UTC-03:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2,5760028,9702089,MSC VITA,VITA,5189807,NaN,2024-01-01 11:00:00,2024-01-01 10:00:00,UTC+01:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
3,5753589,9330226,MSC ABIGAIL F,ABIG,5190958,NaN,2024-01-01 12:14:00,2024-01-01 12:14:00,UTC+00:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
4,5748708,9292175,MSC SHANELLE V,SHNL,5190148,NaN,2024-01-01 13:15:00,2024-01-01 13:15:00,UTC+00:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2303,6311513,9244881,MSC ARUSHI R,ARUS,5532057,NaN,2024-06-30 15:39:00,2024-06-30 13:39:00,UTC+02:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2304,6304722,9162643,MSC LEA,LEA,5530815,NaN,2024-06-30 17:30:00,2024-06-30 14:30:00,UTC+03:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2305,6299544,8512906,MSC ADELE,ADEL,5533194,NaN,2024-06-30 22:06:00,2024-06-30 16:36:00,UTC+05:30,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2306,6321378,9360271,MSC CAPE III,CAPE,5531232,NaN,2024-06-30 19:48:00,2024-06-30 19:48:00,UTC+00:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN
2307,6311514,9244881,MSC ARUSHI R,ARUS,5532055,NaN,2024-06-30 22:30:00,2024-06-30 20:30:00,UTC+02:00,REFL,...,0,NaN,NaN,NaN,NaN,NaN,NaN,YES,NaN,NaN

In [93]:
# msc_remarks_db = msc_remarks_ok[['GID','Sulphur_Content_PC','Quantity','Port_Delivery','Product_Quality','Delivery']]
# msc_remarks_db

In [94]:
ms=msc_remarks_ok[['GID','IMO_No','VSL','REPORT_DATE_TIME','Sulphur_Content_PC','Quantity','Port_Delivery','Product_Quality','Delivery']]

In [95]:
ms['Sulphur_Content_PC'].isna().sum()

0

In [96]:
nan = ms[ms['Sulphur_Content_PC'].isna()]
nan

Empty DataFrame
Columns: [GID, IMO_No, VSL, REPORT_DATE_TIME, Sulphur_Content_PC, Quantity, Port_Delivery, Product_Quality, Delivery]
Index: []

In [97]:
msc_remarks_db_final = ms.dropna(subset=['Sulphur_Content_PC']).reset_index(drop=True)
msc_remarks_db_final

,GID,IMO_No,VSL,REPORT_DATE_TIME,Sulphur_Content_PC,Quantity,Port_Delivery,Product_Quality,Delivery
0,5189583,8521402,MSC ANNAMARIA,2024-01-01 00:25:00,0.4200,100.253,BRBEL,NaN,NaN
1,5189587,8521402,MSC ANNAMARIA,2024-01-01 00:35:00,0.0100,50.028,BRBEL,NaN,NaN
2,5189807,9702089,MSC VITA,2024-01-01 10:00:00,2.8900,999.909,BEANR,NaN,NaN
3,5190958,9330226,MSC ABIGAIL F,2024-01-01 12:14:00,0.0985,129.754,BEANR,NaN,NaN
4,5190148,9292175,MSC SHANELLE V,2024-01-01 13:15:00,0.5000,1000.899,BEANR,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2298,5532057,9244881,MSC ARUSHI R,2024-06-30 13:39:00,0.0995,230.020,BEANR,NaN,NaN
2299,5530815,9162643,MSC LEA,2024-06-30 14:30:00,0.4700,250.000,ILHFA,NaN,NaN
2300,5533194,8512906,MSC ADELE,2024-06-30 16:36:00,0.0430,49.607,LKCMB,NaN,NaN
2301,5531232,9360271,MSC CAPE III,2024-06-30 19:48:00,0.4800,201.126,AUBNE,NaN,NaN
2302,5532055,9244881,MSC ARUSHI R,2024-06-30 20:30:00,2.4300,3448.010,BEANR,NaN,NaN

In [98]:
msc_remarks_db_final['BDN'] = 'YES'
msc_remarks_db_final

,GID,IMO_No,VSL,REPORT_DATE_TIME,Sulphur_Content_PC,Quantity,Port_Delivery,Product_Quality,Delivery,BDN
0,5189583,8521402,MSC ANNAMARIA,2024-01-01 00:25:00,0.4200,100.253,BRBEL,NaN,NaN,YES
1,5189587,8521402,MSC ANNAMARIA,2024-01-01 00:35:00,0.0100,50.028,BRBEL,NaN,NaN,YES
2,5189807,9702089,MSC VITA,2024-01-01 10:00:00,2.8900,999.909,BEANR,NaN,NaN,YES
3,5190958,9330226,MSC ABIGAIL F,2024-01-01 12:14:00,0.0985,129.754,BEANR,NaN,NaN,YES
4,5190148,9292175,MSC SHANELLE V,2024-01-01 13:15:00,0.5000,1000.899,BEANR,NaN,NaN,YES
...,...,...,...,...,...,...,...,...,...,...
2298,5532057,9244881,MSC ARUSHI R,2024-06-30 13:39:00,0.0995,230.020,BEANR,NaN,NaN,YES
2299,5530815,9162643,MSC LEA,2024-06-30 14:30:00,0.4700,250.000,ILHFA,NaN,NaN,YES
2300,5533194,8512906,MSC ADELE,2024-06-30 16:36:00,0.0430,49.607,LKCMB,NaN,NaN,YES
2301,5531232,9360271,MSC CAPE III,2024-06-30 19:48:00,0.4800,201.126,AUBNE,NaN,NaN,YES
2302,5532055,9244881,MSC ARUSHI R,2024-06-30 20:30:00,2.4300,3448.010,BEANR,NaN,NaN,YES

### Download the file and give the software team to update this through 'UPDATE GID CODE (NOONDATA)'

In [99]:
#msc_remarks_db_final.to_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JUL23 TO DEC23/OUTPUT FOR DB/MSCSMCY_update_GID.xlsx", index = False)

In [100]:
#msc_remarks_db_final.to_csv(r"D:\Navalt\MSC\2024\ESI\Group A\JUL23 TO DEC23/OUTPUT FOR DB/MSCSMCY_update_GID.csv", index = False)

In [101]:
msc_remarks_db_final.to_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24/OUTPUT FOR DB/MSCSMCY_update_GID.xlsx", index = False)

In [102]:
msc_remarks_db_final.to_csv(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24/OUTPUT FOR DB/MSCSMCY_update_GID.csv", index = False)