In [4]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd

In [5]:
data1 = pd.read_excel(r'D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\BUNKER DATA\CHARTER_ESI_BUNKER.xlsx')
data2 = pd.read_excel(r'D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\BUNKER DATA\MSCSMCY_ESI_BUNKER.xlsx')
data3 = pd.read_excel(r'D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\BUNKER DATA\SORRENTO_ESI_BUNKER.xlsx')

In [6]:
#all 2 datas may contain mscsmcy,charter and sorrento vessels data,so combine 3 datas and check
data = pd.concat([data1,data2,data3])
data

,Vessel,IMO No,Bunker Delivery Date,BDN Number,Fuel Type,Mass(Tonne),Sulphur Content(%),Bunker Port
0,AS CALIFORNIA,9342695,02 Feb 2024,16012,Medium,1696.461,0.480,SGSIN
1,AS CALIFORNIA,9342695,19 May 2024,17873,Medium,1698.000,0.483,SGSIN
2,AS CALIFORNIA,9342695,03 Apr 2024,7746,Medium,1599.375,0.490,SGSIN
3,ATHENS GLORY,9247766,19 Mar 2024,SHELL TRIP NO 9946776,Low,150.000,0.094,USHOU
4,ATHENS GLORY,9247766,26 Jan 2024,PY129833,High,1991.323,1.710,PACTB
...,...,...,...,...,...,...,...,...
340,MSC VANDYA,9484467,01 Mar 2024,104644,Low,180.110,0.011,USOAK
341,MSC ZOE,9703318,20 Jan 2024,0226 & 0227,High,3497.425,2.630,GRPIR
342,MSC ZOE,9703318,18 Mar 2024,6079,High,1797.250,2.770,SGSIN
343,MSC ZOE,9703318,17 Apr 2024,5532,High,5999.428,2.830,SGSIN
344,MSC ZOE,9703318,02 Feb 2024,A40925,High,2298.604,3.500,GRPIR

In [7]:
#drop duplicates by GID
# data = data.drop_duplicates(subset=['GID'])
# data

In [8]:
#vessel list first client send
esi = pd.read_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\CLIENT FILE\ESI CURRENT VESSELS.xlsx")
esi

         IMO    Fleet          Vessel Scrubber Unnamed: 4
0    9297589  CHARTER           ALANA       No        NaN
1    9625970        9       ANASTASIA       No        NaN
2    9342695  CHARTER   AS California       No        NaN
3    9314947  CHARTER     AS CAMELLIA      Yes        NaN
4    9321897       12    MSC NADIA IV       No        NaN
..       ...      ...             ...      ...        ...
429  9198587       14    MSC CHIARA X       No        NaN
430  9299032       19  MSC FALCON III       No        NaN
431  9962598       15     MSC LORENZA      Yes        NaN
432  9967263       23      MSC MAPUTO      Yes        NaN
433  9214898       14    MSC NICOLE X       No        NaN

[434 rows x 5 columns]

In [9]:
esi_charter = esi[esi['Fleet'] =='CHARTER']
esi_sorrento = esi[esi['Fleet'] == 'SORRENTO']
esi_own = esi[(esi.Fleet !='CHARTER') & (esi.Fleet != 'SORRENTO')]

In [10]:
esi_charter

         IMO    Fleet             Vessel Scrubber Unnamed: 4
0    9297589  CHARTER              ALANA       No        NaN
2    9342695  CHARTER      AS California       No        NaN
3    9314947  CHARTER        AS CAMELLIA      Yes        NaN
5    9247766  CHARTER       ATHENS GLORY      Yes        NaN
7    9727625  CHARTER        CAPE SOUNIO       No        NaN
8    9706205  CHARTER       CAPE TAINARO       No        NaN
9    9293791  CHARTER     CONTI CHIVALRY       No        NaN
10   9308613  CHARTER       Contship Fun       No        NaN
11   9373917  CHARTER       CONTSHIP OAK       No        NaN
12   9357810  CHARTER           EF Emira       No        NaN
13   9153862  CHARTER        EPAMINONDAS       No        NaN
14   9301469  CHARTER             Etoile       No        NaN
17   9256482  CHARTER         GSL NINGBO       No        NaN
18   9357793  CHARTER        Hansa Lanka       No        NaN
19   9535163  CHARTER    Henrika Schulte       No        NaN
20   9535187  CHARTER    Hermann Schulte       No        NaN
21   9535204  CHARTER     Hubert Schulte       No        NaN
23   9225770  CHARTER              Julie       No        NaN
24   9085558  CHARTER         Karlskrona       No        NaN
25   9085546  CHARTER             KLEVEN       No        NaN
26   9085534  CHARTER              KOTKA       No        NaN
27   9085522  CHARTER               KURE       No        NaN
28   9307243  CHARTER           Le Havre      Yes        NaN
29   9236535  CHARTER         Marianetta       No        NaN
30   9162227  CHARTER         MARIANNA I       No        NaN
31   9148025  CHARTER          MED AYDIN       No        NaN
32   9256365  CHARTER          MED CESME       No        NaN
33   9106479  CHARTER          MED CORLU       No        NaN
34   9106493  CHARTER        MED Denizli       No        NaN
35   9225794  CHARTER         MED SAMSUN       No        NaN
36   9141780  CHARTER        MED TRABZON       No        NaN
44   9619464  CHARTER         MSC AGADIR      Yes        NaN
71   9247730  CHARTER         MSC APOLLO      Yes        NaN
72   9262704  CHARTER       MSC AQUARIUS      Yes        NaN
78   9618317  CHARTER          MSC ATHOS      Yes        NaN
82   9605255  CHARTER           MSC AZOV      Yes        NaN
85   9480186  CHARTER      MSC BARCELONA       No        NaN
86   9461441  CHARTER           MSC BARI      Yes        NaN
94   9247742  CHARTER      MSC BOSPHORUS      Yes        NaN
100  9480203  CHARTER          MSC CADIZ       No        NaN
126  9480215  CHARTER         MSC CORUNA       No        NaN
129  9247754  CHARTER    MSC DARDANELLES      Yes        NaN
187  9225641  CHARTER          MSC ILONA       No        NaN
198  9135638  CHARTER         MED MERSIN       No        NaN
225  9461403  CHARTER      MSC LA SPEZIA      Yes        NaN
237  9461427  CHARTER        MSC LIVORNO      Yes        NaN
248  9480198  CHARTER         MSC MADRID       No        NaN
284  9349796  CHARTER       MSC MONTEREY       No        NaN
325  9256470  CHARTER        MSC QINGDAO      Yes        NaN
328  9484431  CHARTER        MSC RAVENNA      Yes        NaN
337  9304447  CHARTER           MSC ROMA      Yes        NaN
355  9460356  CHARTER         MSC SAVONA      Yes        NaN
387  9475258  CHARTER        MSC TARANTO      Yes        NaN
391  9285471  CHARTER        MSC TIANJIN       No        NaN
408  9480227  CHARTER           MSC VIGO       No        NaN
423  9813840  CHARTER  Spirit of Chennai      Yes        NaN
424  9813838  CHARTER  Spirit of Kolkata      Yes        NaN

In [11]:
esi_sorrento

         IMO     Fleet                 Vessel Scrubber Unnamed: 4
50   9129873  SORRENTO              MSC ALEXA       No        NaN
54   9235050  SORRENTO             MSC ALYSSA       No        NaN
56   9839480  SORRENTO              MSC AMBRA      Yes        NaN
58   9606338  SORRENTO          MSC AMSTERDAM       No        NaN
88   9399014  SORRENTO           MSC BEATRICE      Yes        NaN
113  9930040  SORRENTO  MSC CELESTINO MARESCA      Yes        NaN
119  9708693  SORRENTO              MSC CLARA      Yes        NaN
134  9202649  SORRENTO              MSC DIEGO       No        NaN
135  9897004  SORRENTO            MSC DILETTA      Yes        NaN
159  9279965  SORRENTO           MSC FABIENNE       No        NaN
165  9401116  SORRENTO          MSC FRANCESCA      Yes        NaN
170  9202663  SORRENTO               MSC GINA       No        NaN
177  9647461  SORRENTO            MSC HAMBURG      Yes        NaN
195  9606326  SORRENTO           MSC ISTANBUL       No        NaN
196  9398371  SORRENTO              MSC IVANA      Yes        NaN
204  9966934  SORRENTO              MSC JIANI       No        NaN
211  9399026  SORRENTO             MSC KALINA      Yes        NaN
214  9467457  SORRENTO              MSC KATIE      Yes        NaN
220  9351581  SORRENTO                MSC KIM       No        NaN
223  9372470  SORRENTO            MSC KRYSTAL       No        NaN
228  9225665  SORRENTO              MSC LAURA      Yes        NaN
236  9281279  SORRENTO               MSC LISA       No        NaN
238  9606302  SORRENTO             MSC LONDON      Yes        NaN
239  9320403  SORRENTO             MSC LORENA       No        NaN
242  9230490  SORRENTO            MSC LORETTA      Yes        NaN
262  9275971  SORRENTO             MSC MARINA       No        NaN
263  9060637  SORRENTO            MSC MARTINA       No        NaN
268  9251717  SORRENTO            MSC MAUREEN       No        NaN
270  9708679  SORRENTO               MSC MAYA      Yes        NaN
272  9226918  SORRENTO            MSC MELISSA      Yes        NaN
276  9230488  SORRENTO           MSC MICHAELA      Yes        NaN
278  9897016  SORRENTO           MSC MICHELLE      Yes        NaN
287  9955789  SORRENTO             MSC NAHARA      Yes        NaN
292  9606314  SORRENTO           MSC NEW YORK       No        NaN
302  9349825  SORRENTO              MSC NURIA       No        NaN
306  9703306  SORRENTO             MSC OLIVER       No        NaN
307  9372482  SORRENTO             MSC ORIANE       No        NaN
310  9703291  SORRENTO              MSC OSCAR      Yes        NaN
319  9279977  SORRENTO            MSC POH LIN       No        NaN
326  9290282  SORRENTO            MSC RACHELE       No        NaN
331  9754965  SORRENTO               MSC REEF      Yes        NaN
332  9202651  SORRENTO             MSC REGINA       No        NaN
339  9320453  SORRENTO            MSC ROSARIA       No        NaN
375  9404663  SORRENTO              MSC SONIA      Yes        NaN
378  9279989  SORRENTO             MSC STELLA      Yes        NaN
381  9708681  SORRENTO              MSC SVEVA      Yes        NaN
393  9309461  SORRENTO             MSC TOMOKO       No        NaN
403  9461439  SORRENTO            MSC VALERIA       No        NaN
404  9484467  SORRENTO             MSC VANDYA       No        NaN
422  9703318  SORRENTO                MSC ZOE      Yes        NaN

In [12]:
esi_own

         IMO Fleet          Vessel Scrubber Unnamed: 4
1    9625970     9       ANASTASIA       No        NaN
4    9321897    12    MSC NADIA IV       No        NaN
6    9334519    15   MSC ZAINA III       No        NaN
15   9453298    14      GOLD HOSHI       No        NaN
16   9463205    14     GOLD KOCHAV       No        NaN
..       ...   ...             ...      ...        ...
429  9198587    14    MSC CHIARA X       No        NaN
430  9299032    19  MSC FALCON III       No        NaN
431  9962598    15     MSC LORENZA      Yes        NaN
432  9967263    23      MSC MAPUTO      Yes        NaN
433  9214898    14    MSC NICOLE X       No        NaN

[327 rows x 5 columns]

## mscsmcy

In [13]:
#client send mscsmcy vessel imo list
esi_own_lst = esi_own['IMO'].to_list()
esi_own_lst

[9625970,
 9321897,
 9334519,
 9453298,
 9463205,
 9180205,
 9330226,
 9166778,
 9190119,
 8512906,
 9235581,
 9169055,
 9932921,
 9057173,
 9618276,
 9770751,
 9123166,
 9301990,
 9618288,
 9842097,
 9196852,
 9319600,
 9008603,
 9242651,
 9261827,
 9259379,
 9306275,
 9227297,
 8521402,
 9169122,
 9282261,
 9254848,
 9323041,
 9297864,
 9710426,
 9857169,
 9839284,
 9244881,
 9162631,
 9263344,
 8913447,
 8512891,
 9857183,
 9263332,
 9226932,
 9360764,
 9289099,
 9203904,
 9297876,
 9770749,
 9930935,
 9720495,
 9313967,
 9103685,
 9702106,
 9289087,
 9169043,
 9262546,
 9102722,
 9360271,
 9154220,
 9210086,
 9625944,
 9946879,
 9295397,
 9253038,
 9705005,
 9229300,
 9316361,
 9710438,
 9299537,
 9198587,
 9936642,
 9936628,
 9113446,
 9301550,
 9241463,
 9307267,
 9426817,
 9295165,
 9250983,
 9927287,
 9930959,
 9200689,
 9262560,
 9306263,
 9720201,
 9102746,
 9237151,
 9301328,
 9444285,
 9294824,
 9110391,
 9169029,
 9282259,
 9236688,
 9278143,
 9064750,
 9215892,
 9166780,
 9735218,
 9704972,
 8917778,
 9326823,
 9334832,
 9463047,
 9004231,
 8201648,
 9302633,
 9842085,
 9299032,
 9290402,
 9120853,
 8413875,
 9344708,
 9152856,
 9289051,
 9153850,
 9720196,
 9947134,
 9210062,
 9415296,
 9631876,
 9283708,
 9316347,
 9350317,
 9127540,
 9463281,
 9224946,
 9962562,
 9962586,
 9197545,
 9124366,
 9231248,
 9181651,
 9929429,
 8201624,
 9839272,
 9154206,
 9110975,
 9433157,
 9000742,
 9720471,
 9622007,
 9215672,
 8918980,
 9039250,
 9227338,
 9275036,
 9450351,
 9244946,
 9236585,
 9232656,
 9467445,
 9227302,
 9110389,
 9242637,
 9927299,
 9123154,
 9051507,
 9305506,
 9439735,
 9064748,
 9162643,
 9947158,
 9347762,
 9383223,
 9334349,
 9704960,
 9237498,
 9962598,
 9934735,
 9327798,
 9251690,
 9308625,
 9400148,
 9231119,
 9625932,
 9252553,
 9252541,
 8201636,
 9238882,
 8918966,
 9967263,
 9932892,
 9465318,
 8616520,
 9155107,
 9964194,
 9962574,
 9540077,
 9169031,
 9181663,
 9315915,
 9720287,
 9102710,
 9936630,
 9231779,
 9169067,
 9720512,
 9196864,
 9839260,
 9293179,
 9932050,
 9060649,
 9294991,
 9149328,
 9307839,
 9471226,
 8918954,
 9278155,
 9214898,
 9228576,
 9315886,
 9308584,
 9326768,
 9084607,
 9778117,
 9946843,
 9256315,
 9456965,
 9336359,
 9408774,
 9857157,
 9281267,
 9735206,
 9336165,
 9239903,
 9161297,
 9240328,
 9256391,
 9267637,
 9222302,
 9074042,
 9139086,
 9299020,
 9154191,
 9450325,
 9235402,
 9930052,
 9139505,
 9465306,
 9240873,
 9419644,
 9038907,
 9293167,
 9957359,
 9337676,
 8714205,
 9401166,
 9491616,
 9110377,
 9434462,
 9222106,
 9290426,
 8913411,
 9702261,
 9181675,
 8715857,
 9241451,
 9720500,
 9116369,
 9471238,
 9292175,
 9231822,
 8913423,
 9036002,
 9180968,
 9224049,
 9778105,
 9778076,
 9720457,
 9210098,
 9224348,
 9793947,
 9162277,
 9927275,
 9702091,
 9695028,
 9220328,
 9259393,
 9210050,
 8918978,
 9330068,
 9231262,
 9200677,
 9308601,
 9351579,
 9316373,
 9008574,
 9189366,
 9930038,
 9248928,
 9299525,
 9295177,
 9230775,
 9931288,
 9337444,
 9302619,
 9302621,
 9315836,
 9227340,
 9251688,
 9242625,
 9238739,
 9304708,
 9146479,
 9908059,
 9702089,
 9947122,
 9908047,
 9236690,
 9288409,
 9778090,
 9322011,
 9146467,
 9344564,
 9141285,
 9315018,
 9326964,
 9354363,
 9315006,
 9198587,
 9299032,
 9962598,
 9967263,
 9214898]

In [14]:
len(esi_own_lst)

327

In [15]:
data

,Vessel,IMO No,Bunker Delivery Date,BDN Number,Fuel Type,Mass(Tonne),Sulphur Content(%),Bunker Port
0,AS CALIFORNIA,9342695,02 Feb 2024,16012,Medium,1696.461,0.480,SGSIN
1,AS CALIFORNIA,9342695,19 May 2024,17873,Medium,1698.000,0.483,SGSIN
2,AS CALIFORNIA,9342695,03 Apr 2024,7746,Medium,1599.375,0.490,SGSIN
3,ATHENS GLORY,9247766,19 Mar 2024,SHELL TRIP NO 9946776,Low,150.000,0.094,USHOU
4,ATHENS GLORY,9247766,26 Jan 2024,PY129833,High,1991.323,1.710,PACTB
...,...,...,...,...,...,...,...,...
340,MSC VANDYA,9484467,01 Mar 2024,104644,Low,180.110,0.011,USOAK
341,MSC ZOE,9703318,20 Jan 2024,0226 & 0227,High,3497.425,2.630,GRPIR
342,MSC ZOE,9703318,18 Mar 2024,6079,High,1797.250,2.770,SGSIN
343,MSC ZOE,9703318,17 Apr 2024,5532,High,5999.428,2.830,SGSIN
344,MSC ZOE,9703318,02 Feb 2024,A40925,High,2298.604,3.500,GRPIR

In [16]:
#seperate this imo vessel datas from bunker report data as msc own vessels
mscown = data[data['IMO No'].isin(esi_own_lst)] 
mscown

,Vessel,IMO No,Bunker Delivery Date,BDN Number,Fuel Type,Mass(Tonne),Sulphur Content(%),Bunker Port
0,ANASTASIA,9625970,28 Jun 2024,21405662,Medium,740.000,0.41,AUHPT
1,ANASTASIA,9625970,14 Apr 2024,21405662,Medium,740.000,0.41,AUHPT
2,GOLD HOSHI,9453298,17 Apr 2024,T3432,Medium,1400.000,0.45,ILHFA
3,GOLD HOSHI,9453298,13 Jun 2024,T3432,Medium,1400.000,0.45,ILHFA
4,GOLD HOSHI,9453298,13 Jun 2024,T3432,Medium,1400.000,0.45,ILHFA
...,...,...,...,...,...,...,...,...
2012,WEC VAN RIJN,9315006,13 Apr 2024,TOUR30011,Medium,133.169,0.49,BEANR
2013,WEC VAN RIJN,9315006,23 Jun 2024,TOUR30011,Medium,133.169,0.49,BEANR
2014,WEC VAN RIJN,9315006,30 Apr 2024,TOUR30011,Medium,133.169,0.49,BEANR
2015,WEC VAN RIJN,9315006,04 Jun 2024,TOUR30011,Medium,133.169,0.49,BEANR
2016,WEC VAN RIJN,9315006,04 Jun 2024,TOUR30011,Medium,133.169,0.49,BEANR

In [17]:
mscown['IMO No'].nunique()

274

In [18]:
#mscown = mscown.rename(columns={'Ship IMO': 'imo', 'Note nr': 'number','Delivery Date': 'deliveryDate','Mass': 'mass','Sulphur Content': 'sulphurContent','Bunker Port': 'bunkerPort'})
#mscown

In [19]:
mscown = mscown.rename(columns={'IMO No': 'imo', 'BDN Number': 'number','Bunker Delivery Date': 'deliveryDate','Mass(Tonne)': 'mass','Sulphur Content(%)': 'sulphurContent','Bunker Port': 'bunkerPort'})
mscown

,Vessel,imo,deliveryDate,number,Fuel Type,mass,sulphurContent,bunkerPort
0,ANASTASIA,9625970,28 Jun 2024,21405662,Medium,740.000,0.41,AUHPT
1,ANASTASIA,9625970,14 Apr 2024,21405662,Medium,740.000,0.41,AUHPT
2,GOLD HOSHI,9453298,17 Apr 2024,T3432,Medium,1400.000,0.45,ILHFA
3,GOLD HOSHI,9453298,13 Jun 2024,T3432,Medium,1400.000,0.45,ILHFA
4,GOLD HOSHI,9453298,13 Jun 2024,T3432,Medium,1400.000,0.45,ILHFA
...,...,...,...,...,...,...,...,...
2012,WEC VAN RIJN,9315006,13 Apr 2024,TOUR30011,Medium,133.169,0.49,BEANR
2013,WEC VAN RIJN,9315006,23 Jun 2024,TOUR30011,Medium,133.169,0.49,BEANR
2014,WEC VAN RIJN,9315006,30 Apr 2024,TOUR30011,Medium,133.169,0.49,BEANR
2015,WEC VAN RIJN,9315006,04 Jun 2024,TOUR30011,Medium,133.169,0.49,BEANR
2016,WEC VAN RIJN,9315006,04 Jun 2024,TOUR30011,Medium,133.169,0.49,BEANR

In [20]:
mscown_BUNKER = mscown[['imo','number','deliveryDate','mass','sulphurContent','bunkerPort']]
mscown_BUNKER

          imo     number deliveryDate      mass  sulphurContent bunkerPort
0     9625970   21405662  28 Jun 2024   740.000            0.41      AUHPT
1     9625970   21405662  14 Apr 2024   740.000            0.41      AUHPT
2     9453298      T3432  17 Apr 2024  1400.000            0.45      ILHFA
3     9453298      T3432  13 Jun 2024  1400.000            0.45      ILHFA
4     9453298      T3432  13 Jun 2024  1400.000            0.45      ILHFA
...       ...        ...          ...       ...             ...        ...
2012  9315006  TOUR30011  13 Apr 2024   133.169            0.49      BEANR
2013  9315006  TOUR30011  23 Jun 2024   133.169            0.49      BEANR
2014  9315006  TOUR30011  30 Apr 2024   133.169            0.49      BEANR
2015  9315006  TOUR30011  04 Jun 2024   133.169            0.49      BEANR
2016  9315006  TOUR30011  04 Jun 2024   133.169            0.49      BEANR

[2003 rows x 6 columns]

In [21]:
mscown_BUNKER.dtypes

imo                 int64
number             object
deliveryDate       object
mass              float64
sulphurContent    float64
bunkerPort         object
dtype: object

In [22]:
mscown_BUNKER['number'] = mscown_BUNKER['number'].astype(str)
#mscown_BUNKER['mass'] = mscown_BUNKER['mass'].astype(int) 
#mscown_BUNKER['sulphurContent'] = mscown_BUNKER['sulphurContent'].astype(int) 
mscown_BUNKER['bunkerPort'] = mscown_BUNKER['bunkerPort'].astype(str)

In [23]:
mscown_BUNKER.dtypes

imo                 int64
number             object
deliveryDate       object
mass              float64
sulphurContent    float64
bunkerPort         object
dtype: object

In [24]:
mscown_BUNKER.isna().sum()

imo               0
number            0
deliveryDate      0
mass              0
sulphurContent    0
bunkerPort        0
dtype: int64

In [25]:
mscown_BUNKER.to_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\BUNKER DATA/MSCSMCY_BUNKER_DATA_API.xlsx",index=False)

In [26]:
mscown_BUNKER.to_csv(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\BUNKER DATA/MSCSMCY_BUNKER_DATA_API.csv",index=False)

## charter

In [27]:
#client send charter vessel list
esi_charter_lst = esi_charter['IMO'].to_list()
esi_charter_lst

[9297589,
 9342695,
 9314947,
 9247766,
 9727625,
 9706205,
 9293791,
 9308613,
 9373917,
 9357810,
 9153862,
 9301469,
 9256482,
 9357793,
 9535163,
 9535187,
 9535204,
 9225770,
 9085558,
 9085546,
 9085534,
 9085522,
 9307243,
 9236535,
 9162227,
 9148025,
 9256365,
 9106479,
 9106493,
 9225794,
 9141780,
 9619464,
 9247730,
 9262704,
 9618317,
 9605255,
 9480186,
 9461441,
 9247742,
 9480203,
 9480215,
 9247754,
 9225641,
 9135638,
 9461403,
 9461427,
 9480198,
 9349796,
 9256470,
 9484431,
 9304447,
 9460356,
 9475258,
 9285471,
 9480227,
 9813840,
 9813838]

In [28]:
len(esi_charter_lst)

57

In [29]:
data

,Vessel,IMO No,Bunker Delivery Date,BDN Number,Fuel Type,Mass(Tonne),Sulphur Content(%),Bunker Port
0,AS CALIFORNIA,9342695,02 Feb 2024,16012,Medium,1696.461,0.480,SGSIN
1,AS CALIFORNIA,9342695,19 May 2024,17873,Medium,1698.000,0.483,SGSIN
2,AS CALIFORNIA,9342695,03 Apr 2024,7746,Medium,1599.375,0.490,SGSIN
3,ATHENS GLORY,9247766,19 Mar 2024,SHELL TRIP NO 9946776,Low,150.000,0.094,USHOU
4,ATHENS GLORY,9247766,26 Jan 2024,PY129833,High,1991.323,1.710,PACTB
...,...,...,...,...,...,...,...,...
340,MSC VANDYA,9484467,01 Mar 2024,104644,Low,180.110,0.011,USOAK
341,MSC ZOE,9703318,20 Jan 2024,0226 & 0227,High,3497.425,2.630,GRPIR
342,MSC ZOE,9703318,18 Mar 2024,6079,High,1797.250,2.770,SGSIN
343,MSC ZOE,9703318,17 Apr 2024,5532,High,5999.428,2.830,SGSIN
344,MSC ZOE,9703318,02 Feb 2024,A40925,High,2298.604,3.500,GRPIR

In [30]:
charter = data[data['IMO No'].isin(esi_charter_lst)] 
charter

,Vessel,IMO No,Bunker Delivery Date,BDN Number,Fuel Type,Mass(Tonne),Sulphur Content(%),Bunker Port
0,AS CALIFORNIA,9342695,02 Feb 2024,16012,Medium,1696.461,0.4800,SGSIN
1,AS CALIFORNIA,9342695,19 May 2024,17873,Medium,1698.000,0.4830,SGSIN
2,AS CALIFORNIA,9342695,03 Apr 2024,7746,Medium,1599.375,0.4900,SGSIN
3,ATHENS GLORY,9247766,19 Mar 2024,SHELL TRIP NO 9946776,Low,150.000,0.0940,USHOU
4,ATHENS GLORY,9247766,26 Jan 2024,PY129833,High,1991.323,1.7100,PACTB
...,...,...,...,...,...,...,...,...
836,MSC JEANNE,9135638,12 Jan 2024,BRBTB202300001186,Low,250.150,0.0146,BEANR
837,MSC JEANNE,9135638,22 Jun 2024,BRBTB202300001186,Low,250.150,0.0146,BEANR
838,MSC JEANNE,9135638,15 Apr 2024,BRBTB202300001186,Low,250.150,0.0146,BEANR
839,MSC JEANNE,9135638,15 Apr 2024,BRBTB202300001186,Low,250.150,0.0146,BEANR
840,MSC JEANNE,9135638,07 Feb 2024,BRBTB202300001186,Low,250.150,0.0146,BEANR

In [31]:
charter['IMO No'].nunique()

39

In [32]:
#charter = charter.rename(columns={'Ship_imo': 'imo', 'Note nr': 'number','Delivery Date': 'deliveryDate','Mass': 'mass','Sulphur Content': 'sulphurContent','Bunker Port': 'bunkerPort'})
#charter

In [33]:
charter = charter.rename(columns={'IMO No': 'imo', 'BDN Number': 'number','Bunker Delivery Date': 'deliveryDate','Mass(Tonne)': 'mass','Sulphur Content(%)': 'sulphurContent','Bunker Port': 'bunkerPort'})
charter

,Vessel,imo,deliveryDate,number,Fuel Type,mass,sulphurContent,bunkerPort
0,AS CALIFORNIA,9342695,02 Feb 2024,16012,Medium,1696.461,0.4800,SGSIN
1,AS CALIFORNIA,9342695,19 May 2024,17873,Medium,1698.000,0.4830,SGSIN
2,AS CALIFORNIA,9342695,03 Apr 2024,7746,Medium,1599.375,0.4900,SGSIN
3,ATHENS GLORY,9247766,19 Mar 2024,SHELL TRIP NO 9946776,Low,150.000,0.0940,USHOU
4,ATHENS GLORY,9247766,26 Jan 2024,PY129833,High,1991.323,1.7100,PACTB
...,...,...,...,...,...,...,...,...
836,MSC JEANNE,9135638,12 Jan 2024,BRBTB202300001186,Low,250.150,0.0146,BEANR
837,MSC JEANNE,9135638,22 Jun 2024,BRBTB202300001186,Low,250.150,0.0146,BEANR
838,MSC JEANNE,9135638,15 Apr 2024,BRBTB202300001186,Low,250.150,0.0146,BEANR
839,MSC JEANNE,9135638,15 Apr 2024,BRBTB202300001186,Low,250.150,0.0146,BEANR
840,MSC JEANNE,9135638,07 Feb 2024,BRBTB202300001186,Low,250.150,0.0146,BEANR

In [34]:
charter_BUNKER = charter[['imo','number','deliveryDate','mass','sulphurContent','bunkerPort']]
charter_BUNKER

,imo,number,deliveryDate,mass,sulphurContent,bunkerPort
0,9342695,16012,02 Feb 2024,1696.461,0.4800,SGSIN
1,9342695,17873,19 May 2024,1698.000,0.4830,SGSIN
2,9342695,7746,03 Apr 2024,1599.375,0.4900,SGSIN
3,9247766,SHELL TRIP NO 9946776,19 Mar 2024,150.000,0.0940,USHOU
4,9247766,PY129833,26 Jan 2024,1991.323,1.7100,PACTB
...,...,...,...,...,...,...
836,9135638,BRBTB202300001186,12 Jan 2024,250.150,0.0146,BEANR
837,9135638,BRBTB202300001186,22 Jun 2024,250.150,0.0146,BEANR
838,9135638,BRBTB202300001186,15 Apr 2024,250.150,0.0146,BEANR
839,9135638,BRBTB202300001186,15 Apr 2024,250.150,0.0146,BEANR
840,9135638,BRBTB202300001186,07 Feb 2024,250.150,0.0146,BEANR

In [35]:
charter_BUNKER.isna().sum()

imo               0
number            0
deliveryDate      0
mass              0
sulphurContent    0
bunkerPort        0
dtype: int64

In [36]:
charter_BUNKER.dtypes

imo                 int64
number             object
deliveryDate       object
mass              float64
sulphurContent    float64
bunkerPort         object
dtype: object

In [37]:
mscown_BUNKER['number'] = mscown_BUNKER['number'].astype(str)
#mscown_BUNKER['deliveryDate'] = mscown_BUNKER['deliveryDate'].dt.date.astype(str)

In [38]:
charter_BUNKER

,imo,number,deliveryDate,mass,sulphurContent,bunkerPort
0,9342695,16012,02 Feb 2024,1696.461,0.4800,SGSIN
1,9342695,17873,19 May 2024,1698.000,0.4830,SGSIN
2,9342695,7746,03 Apr 2024,1599.375,0.4900,SGSIN
3,9247766,SHELL TRIP NO 9946776,19 Mar 2024,150.000,0.0940,USHOU
4,9247766,PY129833,26 Jan 2024,1991.323,1.7100,PACTB
...,...,...,...,...,...,...
836,9135638,BRBTB202300001186,12 Jan 2024,250.150,0.0146,BEANR
837,9135638,BRBTB202300001186,22 Jun 2024,250.150,0.0146,BEANR
838,9135638,BRBTB202300001186,15 Apr 2024,250.150,0.0146,BEANR
839,9135638,BRBTB202300001186,15 Apr 2024,250.150,0.0146,BEANR
840,9135638,BRBTB202300001186,07 Feb 2024,250.150,0.0146,BEANR

In [39]:
charter_BUNKER.to_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\BUNKER DATA/CHARTER_BUNKER_DATA_API.xlsx",index=False)

In [40]:
charter_BUNKER.to_csv(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\BUNKER DATA\CHARTER_BUNKER_DATA_API.csv",index=False)

## SORRENTO

In [41]:
#client send sorrento vessel list
esi_sorrento_lst = esi_sorrento['IMO'].to_list()
esi_sorrento_lst

[9129873,
 9235050,
 9839480,
 9606338,
 9399014,
 9930040,
 9708693,
 9202649,
 9897004,
 9279965,
 9401116,
 9202663,
 9647461,
 9606326,
 9398371,
 9966934,
 9399026,
 9467457,
 9351581,
 9372470,
 9225665,
 9281279,
 9606302,
 9320403,
 9230490,
 9275971,
 9060637,
 9251717,
 9708679,
 9226918,
 9230488,
 9897016,
 9955789,
 9606314,
 9349825,
 9703306,
 9372482,
 9703291,
 9279977,
 9290282,
 9754965,
 9202651,
 9320453,
 9404663,
 9279989,
 9708681,
 9309461,
 9461439,
 9484467,
 9703318]

In [42]:
len(esi_sorrento_lst)

50

In [43]:
sorrento = data[data['IMO No'].isin(esi_sorrento_lst)] 
sorrento

,Vessel,IMO No,Bunker Delivery Date,BDN Number,Fuel Type,Mass(Tonne),Sulphur Content(%),Bunker Port
0,MSC ALEXA,9129873,08 Mar 2024,9911,Low,114.927,0.0174,LKCMB
1,MSC ALEXA,9129873,08 Mar 2024,9912,Low,84.727,0.0174,LKCMB
2,MSC ALEXA,9129873,04 Feb 2024,9855,Low,139.915,0.0360,LKCMB
3,MSC ALEXA,9129873,04 Feb 2024,9854,Medium,399.762,0.4890,LKCMB
4,MSC ALEXA,9129873,08 Mar 2024,9910,Medium,399.853,0.4840,LKCMB
...,...,...,...,...,...,...,...,...
340,MSC VANDYA,9484467,01 Mar 2024,104644,Low,180.110,0.0110,USOAK
341,MSC ZOE,9703318,20 Jan 2024,0226 & 0227,High,3497.425,2.6300,GRPIR
342,MSC ZOE,9703318,18 Mar 2024,6079,High,1797.250,2.7700,SGSIN
343,MSC ZOE,9703318,17 Apr 2024,5532,High,5999.428,2.8300,SGSIN
344,MSC ZOE,9703318,02 Feb 2024,A40925,High,2298.604,3.5000,GRPIR

In [44]:
sorrento['IMO No'].nunique()

48

In [45]:
#sorrento = sorrento.rename(columns={'Ship_IMO': 'imo', 'Note nr': 'number','Delivery Date': 'deliveryDate','Mass': 'mass','Sulphur Content': 'sulphurContent','Bunker Port': 'bunkerPort'})
#sorrento

In [46]:
sorrento = sorrento.rename(columns={'IMO No': 'imo', 'BDN Number': 'number','Bunker Delivery Date': 'deliveryDate','Mass(Tonne)': 'mass','Sulphur Content(%)': 'sulphurContent','Bunker Port': 'bunkerPort'})
sorrento

,Vessel,imo,deliveryDate,number,Fuel Type,mass,sulphurContent,bunkerPort
0,MSC ALEXA,9129873,08 Mar 2024,9911,Low,114.927,0.0174,LKCMB
1,MSC ALEXA,9129873,08 Mar 2024,9912,Low,84.727,0.0174,LKCMB
2,MSC ALEXA,9129873,04 Feb 2024,9855,Low,139.915,0.0360,LKCMB
3,MSC ALEXA,9129873,04 Feb 2024,9854,Medium,399.762,0.4890,LKCMB
4,MSC ALEXA,9129873,08 Mar 2024,9910,Medium,399.853,0.4840,LKCMB
...,...,...,...,...,...,...,...,...
340,MSC VANDYA,9484467,01 Mar 2024,104644,Low,180.110,0.0110,USOAK
341,MSC ZOE,9703318,20 Jan 2024,0226 & 0227,High,3497.425,2.6300,GRPIR
342,MSC ZOE,9703318,18 Mar 2024,6079,High,1797.250,2.7700,SGSIN
343,MSC ZOE,9703318,17 Apr 2024,5532,High,5999.428,2.8300,SGSIN
344,MSC ZOE,9703318,02 Feb 2024,A40925,High,2298.604,3.5000,GRPIR

In [47]:
sorrento_BUNKER = sorrento[['imo','number','deliveryDate','mass','sulphurContent','bunkerPort']]
sorrento_BUNKER

         imo       number deliveryDate      mass  sulphurContent bunkerPort
0    9129873         9911  08 Mar 2024   114.927          0.0174      LKCMB
1    9129873         9912  08 Mar 2024    84.727          0.0174      LKCMB
2    9129873         9855  04 Feb 2024   139.915          0.0360      LKCMB
3    9129873         9854  04 Feb 2024   399.762          0.4890      LKCMB
4    9129873         9910  08 Mar 2024   399.853          0.4840      LKCMB
..       ...          ...          ...       ...             ...        ...
340  9484467       104644  01 Mar 2024   180.110          0.0110      USOAK
341  9703318  0226 & 0227  20 Jan 2024  3497.425          2.6300      GRPIR
342  9703318         6079  18 Mar 2024  1797.250          2.7700      SGSIN
343  9703318         5532  17 Apr 2024  5999.428          2.8300      SGSIN
344  9703318       A40925  02 Feb 2024  2298.604          3.5000      GRPIR

[345 rows x 6 columns]

In [48]:
sorrento_BUNKER.isna().sum()

imo               0
number            0
deliveryDate      0
mass              0
sulphurContent    0
bunkerPort        0
dtype: int64

In [49]:
sorrento_BUNKER.dtypes

imo                 int64
number             object
deliveryDate       object
mass              float64
sulphurContent    float64
bunkerPort         object
dtype: object

In [50]:
sorrento_BUNKER.to_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\BUNKER DATA/SORRENTO_BUNKER_DATA_API.xlsx",index=False)

In [51]:
sorrento_BUNKER.to_csv(r"D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\BUNKER DATA/SORRENTO_BUNKER_DATA_API.csv",index=False)