In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
data=pd.read_csv("NOONDATA_WEC_VAN_RIJIN.csv")

In [3]:
data.head()

,idvessel,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,...,FUEL_Rsdl_ULS,FUEL_Dstlt_VLS,FUEL_Dstlt_ULS,FUEL_Tnktnr_Dstlt_VLS,Rsdl_HS,Rsdl_VLS,Rsdl_ULS,Dstlt_VLS,Dstlt_ULS,Tnktnr_Dstlt_VLS
0,WVRN,00e66315-51ce-4a9c-8cf2-49fdf73aa5e0,WEC VAN RIJN,9315006.0,NaN,14/09/2021 00:00,13/09/2021 12:06,UTC +02:00,SND,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,WVRN,0e496c4d-ca4b-4066-9ba0-7b9183a426d3,WEC VAN RIJN,9315006.0,NaN,14/09/2021 00:00,13/09/2021 12:06,UTC +02:00,SND,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,WVRN,372bdd23-ca88-47e4-b1a9-7293e73071d3,WEC VAN RIJN,9315006.0,NaN,14/09/2021 00:00,13/09/2021 12:06,UTC +02:00,SND,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,WVRN,b0c23f60-2da5-429d-beaa-f487cbc74c92,WEC VAN RIJN,9315006.0,NaN,14/09/2021 00:00,13/09/2021 12:06,UTC +02:00,SND,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,WVRN,c629f0dd-429c-48ca-a465-f2ead92b2056,WEC VAN RIJN,9315006.0,NaN,14/09/2021 00:00,13/09/2021 12:06,UTC +02:00,SND,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
df=data.copy()

In [5]:
df.dtypes #checking the variable types

idvessel             object
GID                  object
VSL                  object
IMO_No              float64
VOY                  object
                     ...
Rsdl_VLS            float64
Rsdl_ULS            float64
Dstlt_VLS           float64
Dstlt_ULS           float64
Tnktnr_Dstlt_VLS    float64
Length: 321, dtype: object

In [6]:

df['REPORT_DATE_TIME'] = pd.to_datetime(df['REPORT_DATE_TIME'], format='%d/%m/%Y %H:%M', errors='coerce')

# Extract the date and time components
df['Date'] = df['REPORT_DATE_TIME'].dt.date
df['Time'] = df['REPORT_DATE_TIME'].dt.time

# Convert the 'Date' column to datetime
df['Date'] = pd.to_datetime(df['Date'])

# Filter for the year 2021
cii_year = 2023
Res_df = df[df['Date'].dt.year == cii_year]
Res_df.set_index('Date', inplace=True)

In [7]:
Res_df.head()

,idvessel,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,...,FUEL_Dstlt_VLS,FUEL_Dstlt_ULS,FUEL_Tnktnr_Dstlt_VLS,Rsdl_HS,Rsdl_VLS,Rsdl_ULS,Dstlt_VLS,Dstlt_ULS,Tnktnr_Dstlt_VLS,Time
Date,,,,,,,,,,,,,,,,,,,,,
2023-01-01,WVRN,1464071e-57e4-49b7-93d7-785790945511,WEC VAN RIJN,9315006.0,EC248R,01/01/2023 00:00,2023-01-01 12:00:00,UTC +01:00,PORT,IN PORT,...,0.0,1.98,0.0,0.0,0.00,0.0,0.0,1.98,0.0,12:00:00
2023-01-02,WVRN,7c47f0af-cc29-4d41-a1b0-c4042178cc95,WEC VAN RIJN,9315006.0,EC248R,02/01/2023 00:00,2023-01-02 12:00:00,UTC +01:00,PORT,IN PORT,...,0.0,2.03,0.0,0.0,0.00,0.0,0.0,2.03,0.0,12:00:00
2023-01-03,WVRN,1ef5ddd0-0f81-47b8-99c5-ffaf2938f2e0,WEC VAN RIJN,9315006.0,EC248R,03/01/2023 00:00,2023-01-03 12:00:00,UTC +01:00,PORT,IN PORT,...,0.0,1.93,0.0,0.0,0.68,0.0,0.0,1.93,0.0,12:00:00
2023-01-03,WVRN,5b064ae7-6988-4a3f-a035-bd9b37e29b16,WEC VAN RIJN,9315006.0,NaN,04/01/2023 00:00,2023-01-03 18:29:00,UTC +01:00,SND,NaN,...,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,18:29:00
2023-01-03,WVRN,60a74f1e-dbfc-4aa1-b341-193abe289c9a,WEC VAN RIJN,9315006.0,NaN,04/01/2023 00:00,2023-01-03 18:29:00,UTC +01:00,SND,NaN,...,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,18:29:00

In [8]:
Res_df = Res_df.sort_values(by='REPORT_DATE_TIME')

In [9]:

start_date = '2023-06-18'
end_date = '2023-07-18'
start_date = pd.to_datetime(start_date, format='%Y-%m-%d')
end_date = pd.to_datetime(end_date, format='%Y-%m-%d')

filtered_df = Res_df[(Res_df['REPORT_DATE_TIME'] >= start_date) & (Res_df['REPORT_DATE_TIME'] <= end_date)]

In [10]:
filtered_df.head()

,idvessel,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,...,FUEL_Dstlt_VLS,FUEL_Dstlt_ULS,FUEL_Tnktnr_Dstlt_VLS,Rsdl_HS,Rsdl_VLS,Rsdl_ULS,Dstlt_VLS,Dstlt_ULS,Tnktnr_Dstlt_VLS,Time
Date,,,,,,,,,,,,,,,,,,,,,
2023-06-18,WVRN,dc22b483-fe43-4393-a4ee-aa27adf50fe9,WEC VAN RIJN,9315006.0,NaN,18/06/2023 00:00,2023-06-18 09:25:00,UTC +02:00,REFL,NaN,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.00,0.0,09:25:00
2023-06-18,WVRN,48d45d8e-b611-4fcb-8cd6-66e7dc377282,WEC VAN RIJN,9315006.0,EC324A,18/06/2023 00:00,2023-06-18 12:00:00,UTC +02:00,PORT,IN PORT,...,0.0,3.510,0.0,0.0,0.0,0.0,0.0,3.51,0.0,12:00:00
2023-06-18,WVRN,5216d875-54ef-4ea4-9785-c59a29c79a6b,WEC VAN RIJN,9315006.0,NaN,19/06/2023 00:00,2023-06-18 13:55:00,UTC +02:00,REFL,NaN,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.00,0.0,13:55:00
2023-06-19,WVRN,a0b5f3c0-d4ca-4cd2-9019-2b9165a374e9,WEC VAN RIJN,9315006.0,EC324A,19/06/2023 00:00,2023-06-19 12:00:00,UTC +02:00,PORT,IN PORT,...,0.0,3.955,0.0,0.0,0.0,0.0,0.0,3.95,0.0,12:00:00
2023-06-19,WVRN,b064ab6d-c768-46db-a840-1880551559d5,WEC VAN RIJN,9315006.0,NaN,20/06/2023 00:00,2023-06-19 22:59:00,UTC +02:00,SND,NaN,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.00,0.0,22:59:00

In [11]:
pd.set_option('display.max_columns', None)  
filtered_df.tail()

,idvessel,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,LAT,LONG_,LATITUDE,LONGITUDE,M_E_FOC,CARGO_TOTAL,Has_Cargo,TOTAL_STEAMING_TIME,M_E_Fuel_Only_Steaming_Time,MILES_BY_GPS,OIL_CYL,SOW,SOG,RPM,SLIP,WIND_DIRECTION,WIND_SPEED,DRAFT_AFT,DRAFT_FWD,DISPLACEMENT,COURSE_AT_SEA,WAVE_HEIGHT,SEA_DIRECTION,CARGO_TOTAL_TEU,AMBIENT_TEMP,SW_TEMP,MILES_BY_SPEED_LOG,ETA_PORT_CODE,ETA_DATE_TIME,ETA_DATE_TIME_Offset,ETA_PORT,TIME_CHANGE,TIME_SEA,TEMP_MIN,TEMP_MAX,REQUESTED_SPEED,REM_DIST_TO_PILOT,REM_TIME_TO_PILOT,TOTAL_UNPLND_STPGE_TECH,TOTAL_UNPLND_STPGE_OPE_WX,REEFERS_POSITIVE_PLUGGED,REEFERS_NEGATIVE_PLUGGED,ME_TOTAL_REVS_COUNTER,PORT_CODE,PORT,AUX_BLOWERS_ON,HOLD_VENTILATION_ON,SINCE_DATE_TIME,SINCE_DATE_TIME_Offset,TIME_HRS_ANCHOR,TIME_HRS_DRIFT,REASON,TYPE_OF_DELAY,ETB_DATE_TIME,ETB_DATE_TIME_Offset,PILOT_DATE_TIME,PILOT_DATE_TIME_Offset,TIME_MANOEUVRING,TUG_ARR,TUG_SHIFT,ETD_DATE_TIME,ETD_DATE_TIME_Offset,SHIFT_BERTH_HOURS,CARGO_LOAD,CARGO_DISCH,TEU_FULL,TEU_EMPTY,BILGE_REMOVED,GARBAGE_REMOVED,GARBAGE_REMVL_REQSTD,GARBAGE_REMVL_CMPLSRY,FW_SUPPLY,CY_CREW_SIGNED_ON,CY_CREW_SIGNED_OFF,CY_DOCTORS_VISIT,CY_MAIL_RECEIVED_Ref_NO,CY_LUB_OIL_SAMPLE_LANDED,CY_CHECKD_FOR_STOWAWAYS,CY_STOWAWAYS_ON_BOARD,CY_DEP_GM_Mtr,CY_REQUISITIONS_RECEIVED,DISTANCE_TO_NEXT_PILOT,TUG_SAILING_TRANSIT,STEAMING_TIME_M_E_Rsdl_VLS,STEAMING_TIME_M_E_Rsdl_HS,STEAMING_TIME_M_E_Rsdl_ULS,STEAMING_TIME_M_E_Dstlt_VLS,STEAMING_TIME_M_E_Dstlt_ULS,STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS,STEAMING_TIME_M_E_HS,STEAMING_TIME_M_E_LS,STEAMING_TIME_M_E_MDO,STEAMING_TIME_M_E_MGO,STEAMING_TIME_M_E_MGO_LS,STEAMING_TIME_AUX_1,STEAMING_TIME_AUX_2,STEAMING_TIME_AUX_3,STEAMING_TIME_AUX_4,STEAMING_TIME_AUX_5,STEAMING_TIME_SH_GEN,STEAMING_TIME_TG,POWER_kW,STEAMING_LOAD_KW_AUX_1,STEAMING_LOAD_KW_AUX_2,STEAMING_LOAD_KW_AUX_3,STEAMING_LOAD_KW_AUX_4,STEAMING_LOAD_KW_AUX_5,STEAMING_LOAD_KW_SH_GEN,STEAMING_LOAD_KW_TG,FUEL_M_E_Rsdl_VLS,FUEL_M_E_Rsdl_HS,FUEL_M_E_Rsdl_ULS,FUEL_M_E_Dstlt_VLS,FUEL_M_E_Dstlt_ULS,FUEL_M_E_Tnktnr_Dstlt_VLS,FUEL_M_E_HS,FUEL_M_E_LS,FUEL_M_E_MDO,FUEL_M_E_MGO,FUEL_M_E_MGO_LS,FUEL_Aux_Rsdl_VLS,FUEL_Aux_Rsdl_HS,FUEL_Aux_Rsdl_ULS,FUEL_Aux_Dstlt_VLS,FUEL_Aux_Dstlt_ULS,FUEL_Aux_Tnktnr_Dstlt_VLS,FUEL_AUX_HS,FUEL_AUX_LS,FUEL_AUX_MDO,FUEL_AUX_MGO,FUEL_AUX_MGO_LS,FUEL_Boiler_Rsdl_VLS,FUEL_Boiler_Rsdl_HS,FUEL_Boiler_Rsdl_ULS,FUEL_Boiler_Dstlt_VLS,FUEL_Boiler_Dstlt_ULS,FUEL_Boiler_Tnktnr_Dstlt_VLS,FUEL_BOILER_HS,FUEL_BOILER_LS,FUEL_BOILER_MDO,FUEL_BOILER_MGO,FUEL_BOILER_MGO_LS,DECK_LAST_CHANGE_USER,ENGINE_LAST_CHANGE_USER,DECK_PART_IS_COMPLETE,ENGINE_PART_IS_COMPLETE,SCAVENGE_PRESSURE,SECA_ENTRY_TIME,SECA_ENTRY_LAT,SECA_ENTRY_LONG,SECA_EXIT_TIME,SECA_EXIT_LAT,SECA_EXIT_LONG,ROB_FRESH_WATER,MANVRNG_MILES_BY_GPS,MANVRNG_MILES_BY_SPEED_LOG,TANKTAINER_TRANSFD_QUANTITY,PILOT_TAKEN,DATE_TIME_START_TRANSIT,DATE_TIME_START_TRANSIT_Offset,DATE_TIME_END_TRANSIT,DATE_TIME_END_TRANSIT_Offset,BALLAST,TANKTAINER_NUMBER,STEAMING_KWHR_TOTAL,CY_OTHERS,ROB_FO_SLUDGE,ROB_LO_SLUDGE,ROB_BILGE,SLUDGE_REMOVED_FO,SLUDGE_REMOVED_LO,SEA_STATE,CY_LUB_ADDED_TO_SYSTEM_MECC,CY_LUB_ADDED_TO_SYSTEM_AECC,CY_LUB_ADDED_TO_THRUSTERS,CY_ME_LO_PURIFIER_IN_USE,CY_BALLAST,CY_BENDING_MOMENT,CY_SHEARING_FORCE,CY_TORTION_MOMENT,CY_SUPDT_AUDITOR_SIGNED_ON,CY_SUPDT_AUDITOR_SIGNED_OFF,CY_CASH_RECEIVED,CY_LUB_OIL_RECEIVED_MECYL,CY_LUB_OIL_RECEIVED_MECC,CY_LUB_OIL_RECEIVED_AECC,CY_M_E_UNDER_PISTON_TEMP,CY_MAIL_RECEIVED,WIND_DIRECTION_PORT_STBD,SEA_DIRECTION_PORT_STBD,TIME_PILOT_ONBOARD,GRADES_ROB,SO2_CO2_RATIO,Bunker_Order,Remarks,Fuel_Type,Carbon_Factor,Sulphur_Content_PC,Quantity,Port_Delivery,Product_Quality,Tanktainer_Number_1,Supplier,Delivery,Vol_Lt,Den,Vis,ROB_Dstlt_ULS,ROB_Dstlt_VLS,ROB_Rsdl_MDO,ROB_Tnktnr_Dstlt_VLS,ROB_Rsdl_VLS,ROB_Rsdl_HS,ROB_Rsdl_ULS,ROB_Fuel_HSFO,ROB_Fuel_LSFO,ROB_Fuel_MDO,ROB_Fuel_MGO,ROB_Fuel_MGO_LS,ROB_Fuel_Tanktainer_MGO,ECA_MILES,ECA_TIME,EGCS_DRY_WASTE_REMOVED,EGCS_RUNNING_TIME,EGCS_WET_SLURRY_REMOVED,EGCS_OPEN_LOOP_RUNNING_TIME,EGCS_CLOSED_LOOP_RUNNING_TIME,Voyage_Order,Voyage_Code,ECA,EU,Sea_Time,ETA_Country_Code,Port_Country_Code,check_ETA_code,check_Port_code,Status_TEMP_EU,FUEL_HS,FUEL_LS,FUEL_MDO,FUEL_MGO,FUEL_MGO_LS,Cargo_Transport_Work,TEU_Transport_Work,EEOI_Voyage_no,CARGO_TOTAL_Old,DRAFT,FO_per_24Hrs,SFOC,CY_OIL_gm_hr,SCOC,Voyage_Name,TOTAL_FO,TOTAL_CO2,EEOI,voyCondition,samedate,timesincelastreport,BDN,Wind_direction_360,True_wind_speed,True_wind_dir,ref_power,ref_fuel,fuel_loss,Relative_wind_speed,Relative_wind_direction,CAA,RW,Corrected_Power,draft_pow,draft_sp_pow,fo_nor,fo_model,sfoc_model,sfoc_deviation,ref_power_corrected,ref_FO_corrected,Propulsive_eff,speed_performance,Ref_speed,P_I,MEcon,AEcon,BLcon,Tcon,HS,LS,MDO,MGO,MGOLS,TCO2,AETsteaming,AEPOWER,TRIM,DISTANCECOVERED,updated_date,hyd_slip_sog,hyd_slip_stw,FUEL_Rsdl_HS,FUEL_Rsdl_VLS,FUEL_Rsdl_ULS,FUEL_Dstlt_VLS,FUEL_Dstlt_ULS,FUEL_Tnktnr_Dstlt_VLS,Rsdl_HS,Rsdl_VLS,Rsdl_ULS,Dstlt_VLS,Dstlt_ULS,Tnktnr_Dstlt_VLS,Time
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023-07-16,WVRN,37482954-1094-4df0-abd3-d257d5bfc6bb,WEC VAN RIJN,9315006.0,NaN,17/07/2023 00:00,2023-07-16 15:47:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,5444.0,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,351.0,219.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,364.0,GBTHP-NLMOE,N,Y,0.0,NL,GB,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,364.0,0.0,0.00,0.0000,0.000,0.0,0.0,0.0,0.000,0.0000,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,07/08/2023 10:33,NaN,NaN,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.00,0.0,15:47:00
2023-07-16,WVRN,0f25946c-b890-4239-99e7-79852c6c9b46,WEC VAN RIJN,9315006.0,NaN,17/07/2023 00:00,2023-07-16 15:47:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,5444.0,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,351.0,219.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,364.0,GBTHP-NLMOE,N,Y,0.0,NL,GB,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,364.0,0.0,0.00,0.0000,0.000,0.0,0.0,0.0,0.000,0.0000,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,07/08/2023 10:33,NaN,NaN,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.00,0.0,15:47:00
2023-07-16,WVRN,5fbf6f2a-b9f1-447e-ae98-a6a99b5a5d51,WEC VAN RIJN,9315006.0,NaN,17/07/2023 00:00,2023-07-16 15:47:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,5444.0,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,351.0,219.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,364.0,GBTHP-NLMOE,N,Y,0.0,NL,GB,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,364.0,0.0,0.00,0.0000,0.000,0.0,0.0,0.0,0.000,0.0000,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,07/08/2023 10:33,NaN,NaN,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.00,0.0,15:47:00
2023-07-16,WVRN,b20b3bc5-2a06-4f32-a757-1e633165a55c,WEC VAN RIJN,9315006.0,EC328A,17/07/2023 00:00,2023-07-16 15:48:00,UTC +02:00,BRTH,DRIFTING,5159N,00359E,51.983333,3.983333,2.53,5444.0,True,3.8,3.8,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.4,6.9,14279.0,0.0,0.0,0.0,570.0,20.0,17.0,NaN,NLMOE,16/07/2023 04:00,UTC +02:00,NaN,NaN,3.8,395.0,410.0,12.5,NaN,NaN,0.0,0.0,1.0,2.0,114000.0,NLMOE,MOERDIJK,False,False,NaN,NaN,NaN,NaN,NOON,NaN,16/07/2023 17:00,UTC +02:00,16/07/2023 11:30,UTC +02:00,3.8,0.0,0.0,19/07/2023 03:00,UTC +02:00,NaN,NaN,NaN,351.0,219.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,3.8,0.0,0.0,0.0,0.0,0.0,3.8,3.8,3.8,0.0,0.0,0.0,3.8,0.0,3520.0,150.0,150.0,0.0,0.0,0.0,300.0,0.0,0.0,0.0,0.0,0.0,2.53,0.0,0.0,0.0,0.0,0.0,2.53,0.0,0.0,0.0,0.0,0.236,0.0,0.0,0.0,0.0,0.0,0.236,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,2ND OFF,CH. ENG,TRUE,TRUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,112.0,36.0,36.0,NaN,FALSE,NaN,NaN,NaN,NaN,3450,0,1140,NaN,NaN,NaN,0.8,NaN,NaN,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,102.12,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,364.0,GBTHP-NLMOE,N,Y,3.8,NL,GB,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2.766,195984.0,20520.0,364.0,0.0,7.15,15.9789,189.145,0.0,0.0,0.0,2.766,8.8678,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.53,0.24,0.00,2.77,0.0,0.0,0.0,0.0,2.77,8.88,7.6,300.0,0.5,36.0,07/08/2023 10:33,NaN,NaN,0.0,0.0,0.0,0.0,2.766,0.0,0.0,0.0,0.0,0.0,2.77,0.0,15:48:00
2023-07-17,WVRN,79fe27c7-2387-439d-9b1e-72a981e82272,WEC VAN RIJN,9315006.0,EC328A,17/07/2023 00:00,2023-07-17 12:00:00,UTC +02:00,PORT,IN PORT,5159N,00359E,51.983333,3.983333,0.00,5444.0,True,20.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.4,6.9,14279.0,0.0,0.0,0.0,570.0,23.0,19.0,NaN,NLMOE,16/07/2023 04:00,UTC +02:00,NaN,NaN,20.2,395.0,410.0,12.5,NaN,NaN,0.0,0.0,1.0,2.0,0.0,NLMOE,MOERDIJK,False,False,NaN,NaN,NaN,NaN,NOON,NaN,16/07/2023 17:00,UTC +02:00,NaN,NaN,NaN,NaN,NaN,19/07/2023 03:00,UTC +02:00,0.0,NaN,NaN,351.0,219.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.2,0.3,0.0,0.0,0.0,0.0,0.0,0.0,250.0,150.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,1.030,0.0,0.0,0.0,0.0,0.0,1.030,0.0,0.0,0.0,0.0,0.62,0.0,0.0,0.0,0.0,0.0,0.62,2ND OFF,CH. ENG,TRUE,TRUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,112.0,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,3450,0,4975,NaN,NaN,NaN,0.8,NaN,NaN,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.47,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.47,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,364.0,GBTHP-NLMOE,N,Y,0.0,NL,GB,NaN,NaN,0.0,0.0,0.0,0.0,0.0,1.650,0.0,0.0,364.0,0.0,7.15,0.0000,0.000,0.0,0.0,0.0,1.650,5.2899,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,1.03,0.62,1.65,0.0,0.0,0.0,0.0,1.65,5.29,20.5,400.0,0.5,0.0,07/08/2023 10:33,NaN,NaN,0.0,0.0,0.0,0.0,1.650,0.0,0.0,0.0,0.0,0.0,1.65,0.0,12:00:00

In [12]:
filtered_df['Total_Calculated_MGO_LS'] = filtered_df[['FUEL_M_E_MGO_LS', 'FUEL_AUX_MGO_LS', 'FUEL_BOILER_MGO_LS']].sum(axis=1)

filtered_df['Total_Calculated_ULS'] = filtered_df[['FUEL_M_E_Dstlt_ULS', 'FUEL_Aux_Dstlt_ULS', 'FUEL_Boiler_Dstlt_ULS']].sum(axis=1)

filtered_df['Total_fuel'] = filtered_df[['Total_Calculated_MGO_LS', 'Total_Calculated_ULS']].sum(axis=1)

filtered_df['Total_BIO_Calculated'] = (filtered_df['Total_Calculated_MGO_LS'] * 2.417) + (filtered_df['Total_Calculated_ULS'] * 2.567)

In [13]:
dist = filtered_df['MILES_BY_GPS'].sum()
dist

5095.4

In [14]:
dwt= 13734
filtered_df = filtered_df.assign(DWT=dwt)

In [15]:
TAFC= filtered_df['Total_BIO_Calculated'].sum() * 10**6
print(TAFC)

998574304.0

# ATTAINED CII

In [16]:
ATT_CII = TAFC / (dist * dwt)
ATT_CII

14.26937858483779

# REFERENCE CII

In [17]:
'''

CII(REF)= A.CAPACITY^-C

PARAMETER FOR A AND C ARE

SHIP TYPE                           A            C         CAPACITY
TANKER                             5247         0.610       DWT
CONTAIER SHIP                      1984         0.489       DWT
BULK CARRIER: DWT >= 2,79,000      4745         0.622       2,79,00     
BULK CARRIER: DWT <= 2,79,00       4745         0.622       DWT
COMBINATION CARRIER                40853        0.812       DWT

'''

'\n\nCII(REF)= A.CAPACITY^-C\n\nPARAMETER FOR A AND C ARE\n\nSHIP TYPE                           A            C         CAPACITY\nTANKER                             5247         0.610       DWT\nCONTAIER SHIP                      1984         0.489       DWT\nBULK CARRIER: DWT >= 2,79,000      4745         0.622       2,79,00     \nBULK CARRIER: DWT <= 2,79,00       4745         0.622       DWT\nCOMBINATION CARRIER                40853        0.812       DWT\n\n'

In [19]:
#Parameters for reference cii
a = int(input("A:"))
c = float(input("C:"))
dwt= 13734

A:1984
C:0.489

In [20]:
CII_REF = a * (dwt ** (-c))
print(CII_REF)

18.800046080728777

# REQUIRED CII

In [21]:
'''
Required CII= CII(REF) * [(100-Z)/100]

REDUCATION FACTOR(Z%)
YEAR           REDUCTION FACTOR RELATIVE TO 2019
2019                   
2020                  1%
2021                  2%
2022                  3%
2023                  5%
2024                  7%
2025                  9%
2026                  11%

'''

'\nRequired CII= CII(REF) * [(100-Z)/100]\n\nREDUCATION FACTOR(Z%)\nYEAR           REDUCTION FACTOR RELATIVE TO 2019\n2019                   \n2020                  1%\n2021                  2%\n2022                  3%\n2023                  5%\n2024                  7%\n2025                  9%\n2026                  11%\n\n'

In [22]:
#Z-Reduction value
years = {
    2019: 0,
    2020: 1,
    2021: 2,
    2022: 3 ,
    2023: 5 ,
    2024: 7 ,
    2025: 9 ,
    2026: 11
}

a = int(input("Enter a year: "))    #ENTER THE CII YEAR
if a in years:
    Z = years[a]
    print(Z)
else:
    print("No Z value")

Enter a year: 2023
5

In [23]:
#Required CII 
CII_REQ = CII_REF * ((100 - Z) / 100)
print(CII_REQ)

17.860043776692336

# CII RATIO

In [24]:
#CII Ratio
CII_RATIO= ATT_CII/ CII_REQ
print(CII_RATIO)

0.7989554092504283

In [25]:
ships = {
    'BULK': {'D1': 0.86, 'D2': 0.94, 'D3': 1.06, 'D4': 1.18},
    'TANKER': {'D1': 0.82, 'D2': 0.93, 'D3': 1.08, 'D4': 1.28},
    'CONTAINER': {'D1': 0.83, 'D2': 0.94, 'D3': 1.07, 'D4': 1.19},
    'COMBINATION': {'D1': 0.87, 'D2': 0.96, 'D3': 1.06, 'D4': 1.14},
    'GENERAL CARGO SHIP': {'D1': 0.83, 'D2': 0.94, 'D3': 1.06, 'D4': 1.19},
}

def ratings(ship, cii_ratio):
    a = ships.get(ship)
    if a:
        if cii_ratio <= a['D1']:
            return 'A RATING'
        elif a['D1'] < cii_ratio <= a['D2']:
            return 'B RATING'
        elif a['D2'] < cii_ratio <= a['D3']:
            return 'C RATING'
        elif a['D3'] < cii_ratio <= a['D4']:
            return 'D RATING'
        else:
            return 'E RATING'
    else:
        return 'Data not founded'

ship = input("Enter the ship: ").strip().upper()  
CII_RATIO = CII_RATIO
rating = ratings(ship, CII_RATIO)
print(f'The rating is: {rating}')

Enter the ship: container
The rating is: A RATING

# NORMAL FUEL

In [26]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [27]:
data=pd.read_csv("NOONDATA_WEC_VAN_RIJIN.csv")

In [28]:
data.head()

,idvessel,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,LAT,LONG_,LATITUDE,LONGITUDE,M_E_FOC,CARGO_TOTAL,Has_Cargo,TOTAL_STEAMING_TIME,M_E_Fuel_Only_Steaming_Time,MILES_BY_GPS,OIL_CYL,SOW,SOG,RPM,SLIP,WIND_DIRECTION,WIND_SPEED,DRAFT_AFT,DRAFT_FWD,DISPLACEMENT,COURSE_AT_SEA,WAVE_HEIGHT,SEA_DIRECTION,CARGO_TOTAL_TEU,AMBIENT_TEMP,SW_TEMP,MILES_BY_SPEED_LOG,ETA_PORT_CODE,ETA_DATE_TIME,ETA_DATE_TIME_Offset,ETA_PORT,TIME_CHANGE,TIME_SEA,TEMP_MIN,TEMP_MAX,REQUESTED_SPEED,REM_DIST_TO_PILOT,REM_TIME_TO_PILOT,TOTAL_UNPLND_STPGE_TECH,TOTAL_UNPLND_STPGE_OPE_WX,REEFERS_POSITIVE_PLUGGED,REEFERS_NEGATIVE_PLUGGED,ME_TOTAL_REVS_COUNTER,PORT_CODE,PORT,AUX_BLOWERS_ON,HOLD_VENTILATION_ON,SINCE_DATE_TIME,SINCE_DATE_TIME_Offset,TIME_HRS_ANCHOR,TIME_HRS_DRIFT,REASON,TYPE_OF_DELAY,ETB_DATE_TIME,ETB_DATE_TIME_Offset,PILOT_DATE_TIME,PILOT_DATE_TIME_Offset,TIME_MANOEUVRING,TUG_ARR,TUG_SHIFT,ETD_DATE_TIME,ETD_DATE_TIME_Offset,SHIFT_BERTH_HOURS,CARGO_LOAD,CARGO_DISCH,TEU_FULL,TEU_EMPTY,BILGE_REMOVED,GARBAGE_REMOVED,GARBAGE_REMVL_REQSTD,GARBAGE_REMVL_CMPLSRY,FW_SUPPLY,CY_CREW_SIGNED_ON,CY_CREW_SIGNED_OFF,CY_DOCTORS_VISIT,CY_MAIL_RECEIVED_Ref_NO,CY_LUB_OIL_SAMPLE_LANDED,CY_CHECKD_FOR_STOWAWAYS,CY_STOWAWAYS_ON_BOARD,CY_DEP_GM_Mtr,CY_REQUISITIONS_RECEIVED,DISTANCE_TO_NEXT_PILOT,TUG_SAILING_TRANSIT,STEAMING_TIME_M_E_Rsdl_VLS,STEAMING_TIME_M_E_Rsdl_HS,STEAMING_TIME_M_E_Rsdl_ULS,STEAMING_TIME_M_E_Dstlt_VLS,STEAMING_TIME_M_E_Dstlt_ULS,STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS,STEAMING_TIME_M_E_HS,STEAMING_TIME_M_E_LS,STEAMING_TIME_M_E_MDO,STEAMING_TIME_M_E_MGO,STEAMING_TIME_M_E_MGO_LS,STEAMING_TIME_AUX_1,STEAMING_TIME_AUX_2,STEAMING_TIME_AUX_3,STEAMING_TIME_AUX_4,STEAMING_TIME_AUX_5,STEAMING_TIME_SH_GEN,STEAMING_TIME_TG,POWER_kW,STEAMING_LOAD_KW_AUX_1,STEAMING_LOAD_KW_AUX_2,STEAMING_LOAD_KW_AUX_3,STEAMING_LOAD_KW_AUX_4,STEAMING_LOAD_KW_AUX_5,STEAMING_LOAD_KW_SH_GEN,STEAMING_LOAD_KW_TG,FUEL_M_E_Rsdl_VLS,FUEL_M_E_Rsdl_HS,FUEL_M_E_Rsdl_ULS,FUEL_M_E_Dstlt_VLS,FUEL_M_E_Dstlt_ULS,FUEL_M_E_Tnktnr_Dstlt_VLS,FUEL_M_E_HS,FUEL_M_E_LS,FUEL_M_E_MDO,FUEL_M_E_MGO,FUEL_M_E_MGO_LS,FUEL_Aux_Rsdl_VLS,FUEL_Aux_Rsdl_HS,FUEL_Aux_Rsdl_ULS,FUEL_Aux_Dstlt_VLS,FUEL_Aux_Dstlt_ULS,FUEL_Aux_Tnktnr_Dstlt_VLS,FUEL_AUX_HS,FUEL_AUX_LS,FUEL_AUX_MDO,FUEL_AUX_MGO,FUEL_AUX_MGO_LS,FUEL_Boiler_Rsdl_VLS,FUEL_Boiler_Rsdl_HS,FUEL_Boiler_Rsdl_ULS,FUEL_Boiler_Dstlt_VLS,FUEL_Boiler_Dstlt_ULS,FUEL_Boiler_Tnktnr_Dstlt_VLS,FUEL_BOILER_HS,FUEL_BOILER_LS,FUEL_BOILER_MDO,FUEL_BOILER_MGO,FUEL_BOILER_MGO_LS,DECK_LAST_CHANGE_USER,ENGINE_LAST_CHANGE_USER,DECK_PART_IS_COMPLETE,ENGINE_PART_IS_COMPLETE,SCAVENGE_PRESSURE,SECA_ENTRY_TIME,SECA_ENTRY_LAT,SECA_ENTRY_LONG,SECA_EXIT_TIME,SECA_EXIT_LAT,SECA_EXIT_LONG,ROB_FRESH_WATER,MANVRNG_MILES_BY_GPS,MANVRNG_MILES_BY_SPEED_LOG,TANKTAINER_TRANSFD_QUANTITY,PILOT_TAKEN,DATE_TIME_START_TRANSIT,DATE_TIME_START_TRANSIT_Offset,DATE_TIME_END_TRANSIT,DATE_TIME_END_TRANSIT_Offset,BALLAST,TANKTAINER_NUMBER,STEAMING_KWHR_TOTAL,CY_OTHERS,ROB_FO_SLUDGE,ROB_LO_SLUDGE,ROB_BILGE,SLUDGE_REMOVED_FO,SLUDGE_REMOVED_LO,SEA_STATE,CY_LUB_ADDED_TO_SYSTEM_MECC,CY_LUB_ADDED_TO_SYSTEM_AECC,CY_LUB_ADDED_TO_THRUSTERS,CY_ME_LO_PURIFIER_IN_USE,CY_BALLAST,CY_BENDING_MOMENT,CY_SHEARING_FORCE,CY_TORTION_MOMENT,CY_SUPDT_AUDITOR_SIGNED_ON,CY_SUPDT_AUDITOR_SIGNED_OFF,CY_CASH_RECEIVED,CY_LUB_OIL_RECEIVED_MECYL,CY_LUB_OIL_RECEIVED_MECC,CY_LUB_OIL_RECEIVED_AECC,CY_M_E_UNDER_PISTON_TEMP,CY_MAIL_RECEIVED,WIND_DIRECTION_PORT_STBD,SEA_DIRECTION_PORT_STBD,TIME_PILOT_ONBOARD,GRADES_ROB,SO2_CO2_RATIO,Bunker_Order,Remarks,Fuel_Type,Carbon_Factor,Sulphur_Content_PC,Quantity,Port_Delivery,Product_Quality,Tanktainer_Number_1,Supplier,Delivery,Vol_Lt,Den,Vis,ROB_Dstlt_ULS,ROB_Dstlt_VLS,ROB_Rsdl_MDO,ROB_Tnktnr_Dstlt_VLS,ROB_Rsdl_VLS,ROB_Rsdl_HS,ROB_Rsdl_ULS,ROB_Fuel_HSFO,ROB_Fuel_LSFO,ROB_Fuel_MDO,ROB_Fuel_MGO,ROB_Fuel_MGO_LS,ROB_Fuel_Tanktainer_MGO,ECA_MILES,ECA_TIME,EGCS_DRY_WASTE_REMOVED,EGCS_RUNNING_TIME,EGCS_WET_SLURRY_REMOVED,EGCS_OPEN_LOOP_RUNNING_TIME,EGCS_CLOSED_LOOP_RUNNING_TIME,Voyage_Order,Voyage_Code,ECA,EU,Sea_Time,ETA_Country_Code,Port_Country_Code,check_ETA_code,check_Port_code,Status_TEMP_EU,FUEL_HS,FUEL_LS,FUEL_MDO,FUEL_MGO,FUEL_MGO_LS,Cargo_Transport_Work,TEU_Transport_Work,EEOI_Voyage_no,CARGO_TOTAL_Old,DRAFT,FO_per_24Hrs,SFOC,CY_OIL_gm_hr,SCOC,Voyage_Name,TOTAL_FO,TOTAL_CO2,EEOI,voyCondition,samedate,timesincelastreport,BDN,Wind_direction_360,True_wind_speed,True_wind_dir,ref_power,ref_fuel,fuel_loss,Relative_wind_speed,Relative_wind_direction,CAA,RW,Corrected_Power,draft_pow,draft_sp_pow,fo_nor,fo_model,sfoc_model,sfoc_deviation,ref_power_corrected,ref_FO_corrected,Propulsive_eff,speed_performance,Ref_speed,P_I,MEcon,AEcon,BLcon,Tcon,HS,LS,MDO,MGO,MGOLS,TCO2,AETsteaming,AEPOWER,TRIM,DISTANCECOVERED,updated_date,hyd_slip_sog,hyd_slip_stw,FUEL_Rsdl_HS,FUEL_Rsdl_VLS,FUEL_Rsdl_ULS,FUEL_Dstlt_VLS,FUEL_Dstlt_ULS,FUEL_Tnktnr_Dstlt_VLS,Rsdl_HS,Rsdl_VLS,Rsdl_ULS,Dstlt_VLS,Dstlt_ULS,Tnktnr_Dstlt_VLS
0,WVRN,00e66315-51ce-4a9c-8cf2-49fdf73aa5e0,WEC VAN RIJN,9315006.0,NaN,14/09/2021 00:00,13/09/2021 12:06,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,FALSE,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ballast,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,07/10/2021 08:39,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,WVRN,0e496c4d-ca4b-4066-9ba0-7b9183a426d3,WEC VAN RIJN,9315006.0,NaN,14/09/2021 00:00,13/09/2021 12:06,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,FALSE,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ballast,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,07/10/2021 08:39,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,WVRN,372bdd23-ca88-47e4-b1a9-7293e73071d3,WEC VAN RIJN,9315006.0,NaN,14/09/2021 00:00,13/09/2021 12:06,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,FALSE,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ballast,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,07/10/2021 08:39,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,WVRN,b0c23f60-2da5-429d-beaa-f487cbc74c92,WEC VAN RIJN,9315006.0,NaN,14/09/2021 00:00,13/09/2021 12:06,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,FALSE,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ballast,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,07/10/2021 08:39,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,WVRN,c629f0dd-429c-48ca-a465-f2ead92b2056,WEC VAN RIJN,9315006.0,NaN,14/09/2021 00:00,13/09/2021 12:06,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,FALSE,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ballast,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,07/10/2021 08:39,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:
df=data.copy()

In [30]:

df['REPORT_DATE_TIME'] = pd.to_datetime(df['REPORT_DATE_TIME'], format='%d/%m/%Y %H:%M', errors='coerce')

# Extract the date and time components
df['Date'] = df['REPORT_DATE_TIME'].dt.date
df['Time'] = df['REPORT_DATE_TIME'].dt.time

# Convert the 'Date' column to datetime
df['Date'] = pd.to_datetime(df['Date'])

# Filter for the year 2021
cii_year = 2023
Res_dfn = df[df['Date'].dt.year == cii_year]
Res_dfn.set_index('Date', inplace=True)

In [31]:
Res_dfn.head()

,idvessel,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,LAT,LONG_,LATITUDE,LONGITUDE,M_E_FOC,CARGO_TOTAL,Has_Cargo,TOTAL_STEAMING_TIME,M_E_Fuel_Only_Steaming_Time,MILES_BY_GPS,OIL_CYL,SOW,SOG,RPM,SLIP,WIND_DIRECTION,WIND_SPEED,DRAFT_AFT,DRAFT_FWD,DISPLACEMENT,COURSE_AT_SEA,WAVE_HEIGHT,SEA_DIRECTION,CARGO_TOTAL_TEU,AMBIENT_TEMP,SW_TEMP,MILES_BY_SPEED_LOG,ETA_PORT_CODE,ETA_DATE_TIME,ETA_DATE_TIME_Offset,ETA_PORT,TIME_CHANGE,TIME_SEA,TEMP_MIN,TEMP_MAX,REQUESTED_SPEED,REM_DIST_TO_PILOT,REM_TIME_TO_PILOT,TOTAL_UNPLND_STPGE_TECH,TOTAL_UNPLND_STPGE_OPE_WX,REEFERS_POSITIVE_PLUGGED,REEFERS_NEGATIVE_PLUGGED,ME_TOTAL_REVS_COUNTER,PORT_CODE,PORT,AUX_BLOWERS_ON,HOLD_VENTILATION_ON,SINCE_DATE_TIME,SINCE_DATE_TIME_Offset,TIME_HRS_ANCHOR,TIME_HRS_DRIFT,REASON,TYPE_OF_DELAY,ETB_DATE_TIME,ETB_DATE_TIME_Offset,PILOT_DATE_TIME,PILOT_DATE_TIME_Offset,TIME_MANOEUVRING,TUG_ARR,TUG_SHIFT,ETD_DATE_TIME,ETD_DATE_TIME_Offset,SHIFT_BERTH_HOURS,CARGO_LOAD,CARGO_DISCH,TEU_FULL,TEU_EMPTY,BILGE_REMOVED,GARBAGE_REMOVED,GARBAGE_REMVL_REQSTD,GARBAGE_REMVL_CMPLSRY,FW_SUPPLY,CY_CREW_SIGNED_ON,CY_CREW_SIGNED_OFF,CY_DOCTORS_VISIT,CY_MAIL_RECEIVED_Ref_NO,CY_LUB_OIL_SAMPLE_LANDED,CY_CHECKD_FOR_STOWAWAYS,CY_STOWAWAYS_ON_BOARD,CY_DEP_GM_Mtr,CY_REQUISITIONS_RECEIVED,DISTANCE_TO_NEXT_PILOT,TUG_SAILING_TRANSIT,STEAMING_TIME_M_E_Rsdl_VLS,STEAMING_TIME_M_E_Rsdl_HS,STEAMING_TIME_M_E_Rsdl_ULS,STEAMING_TIME_M_E_Dstlt_VLS,STEAMING_TIME_M_E_Dstlt_ULS,STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS,STEAMING_TIME_M_E_HS,STEAMING_TIME_M_E_LS,STEAMING_TIME_M_E_MDO,STEAMING_TIME_M_E_MGO,STEAMING_TIME_M_E_MGO_LS,STEAMING_TIME_AUX_1,STEAMING_TIME_AUX_2,STEAMING_TIME_AUX_3,STEAMING_TIME_AUX_4,STEAMING_TIME_AUX_5,STEAMING_TIME_SH_GEN,STEAMING_TIME_TG,POWER_kW,STEAMING_LOAD_KW_AUX_1,STEAMING_LOAD_KW_AUX_2,STEAMING_LOAD_KW_AUX_3,STEAMING_LOAD_KW_AUX_4,STEAMING_LOAD_KW_AUX_5,STEAMING_LOAD_KW_SH_GEN,STEAMING_LOAD_KW_TG,FUEL_M_E_Rsdl_VLS,FUEL_M_E_Rsdl_HS,FUEL_M_E_Rsdl_ULS,FUEL_M_E_Dstlt_VLS,FUEL_M_E_Dstlt_ULS,FUEL_M_E_Tnktnr_Dstlt_VLS,FUEL_M_E_HS,FUEL_M_E_LS,FUEL_M_E_MDO,FUEL_M_E_MGO,FUEL_M_E_MGO_LS,FUEL_Aux_Rsdl_VLS,FUEL_Aux_Rsdl_HS,FUEL_Aux_Rsdl_ULS,FUEL_Aux_Dstlt_VLS,FUEL_Aux_Dstlt_ULS,FUEL_Aux_Tnktnr_Dstlt_VLS,FUEL_AUX_HS,FUEL_AUX_LS,FUEL_AUX_MDO,FUEL_AUX_MGO,FUEL_AUX_MGO_LS,FUEL_Boiler_Rsdl_VLS,FUEL_Boiler_Rsdl_HS,FUEL_Boiler_Rsdl_ULS,FUEL_Boiler_Dstlt_VLS,FUEL_Boiler_Dstlt_ULS,FUEL_Boiler_Tnktnr_Dstlt_VLS,FUEL_BOILER_HS,FUEL_BOILER_LS,FUEL_BOILER_MDO,FUEL_BOILER_MGO,FUEL_BOILER_MGO_LS,DECK_LAST_CHANGE_USER,ENGINE_LAST_CHANGE_USER,DECK_PART_IS_COMPLETE,ENGINE_PART_IS_COMPLETE,SCAVENGE_PRESSURE,SECA_ENTRY_TIME,SECA_ENTRY_LAT,SECA_ENTRY_LONG,SECA_EXIT_TIME,SECA_EXIT_LAT,SECA_EXIT_LONG,ROB_FRESH_WATER,MANVRNG_MILES_BY_GPS,MANVRNG_MILES_BY_SPEED_LOG,TANKTAINER_TRANSFD_QUANTITY,PILOT_TAKEN,DATE_TIME_START_TRANSIT,DATE_TIME_START_TRANSIT_Offset,DATE_TIME_END_TRANSIT,DATE_TIME_END_TRANSIT_Offset,BALLAST,TANKTAINER_NUMBER,STEAMING_KWHR_TOTAL,CY_OTHERS,ROB_FO_SLUDGE,ROB_LO_SLUDGE,ROB_BILGE,SLUDGE_REMOVED_FO,SLUDGE_REMOVED_LO,SEA_STATE,CY_LUB_ADDED_TO_SYSTEM_MECC,CY_LUB_ADDED_TO_SYSTEM_AECC,CY_LUB_ADDED_TO_THRUSTERS,CY_ME_LO_PURIFIER_IN_USE,CY_BALLAST,CY_BENDING_MOMENT,CY_SHEARING_FORCE,CY_TORTION_MOMENT,CY_SUPDT_AUDITOR_SIGNED_ON,CY_SUPDT_AUDITOR_SIGNED_OFF,CY_CASH_RECEIVED,CY_LUB_OIL_RECEIVED_MECYL,CY_LUB_OIL_RECEIVED_MECC,CY_LUB_OIL_RECEIVED_AECC,CY_M_E_UNDER_PISTON_TEMP,CY_MAIL_RECEIVED,WIND_DIRECTION_PORT_STBD,SEA_DIRECTION_PORT_STBD,TIME_PILOT_ONBOARD,GRADES_ROB,SO2_CO2_RATIO,Bunker_Order,Remarks,Fuel_Type,Carbon_Factor,Sulphur_Content_PC,Quantity,Port_Delivery,Product_Quality,Tanktainer_Number_1,Supplier,Delivery,Vol_Lt,Den,Vis,ROB_Dstlt_ULS,ROB_Dstlt_VLS,ROB_Rsdl_MDO,ROB_Tnktnr_Dstlt_VLS,ROB_Rsdl_VLS,ROB_Rsdl_HS,ROB_Rsdl_ULS,ROB_Fuel_HSFO,ROB_Fuel_LSFO,ROB_Fuel_MDO,ROB_Fuel_MGO,ROB_Fuel_MGO_LS,ROB_Fuel_Tanktainer_MGO,ECA_MILES,ECA_TIME,EGCS_DRY_WASTE_REMOVED,EGCS_RUNNING_TIME,EGCS_WET_SLURRY_REMOVED,EGCS_OPEN_LOOP_RUNNING_TIME,EGCS_CLOSED_LOOP_RUNNING_TIME,Voyage_Order,Voyage_Code,ECA,EU,Sea_Time,ETA_Country_Code,Port_Country_Code,check_ETA_code,check_Port_code,Status_TEMP_EU,FUEL_HS,FUEL_LS,FUEL_MDO,FUEL_MGO,FUEL_MGO_LS,Cargo_Transport_Work,TEU_Transport_Work,EEOI_Voyage_no,CARGO_TOTAL_Old,DRAFT,FO_per_24Hrs,SFOC,CY_OIL_gm_hr,SCOC,Voyage_Name,TOTAL_FO,TOTAL_CO2,EEOI,voyCondition,samedate,timesincelastreport,BDN,Wind_direction_360,True_wind_speed,True_wind_dir,ref_power,ref_fuel,fuel_loss,Relative_wind_speed,Relative_wind_direction,CAA,RW,Corrected_Power,draft_pow,draft_sp_pow,fo_nor,fo_model,sfoc_model,sfoc_deviation,ref_power_corrected,ref_FO_corrected,Propulsive_eff,speed_performance,Ref_speed,P_I,MEcon,AEcon,BLcon,Tcon,HS,LS,MDO,MGO,MGOLS,TCO2,AETsteaming,AEPOWER,TRIM,DISTANCECOVERED,updated_date,hyd_slip_sog,hyd_slip_stw,FUEL_Rsdl_HS,FUEL_Rsdl_VLS,FUEL_Rsdl_ULS,FUEL_Dstlt_VLS,FUEL_Dstlt_ULS,FUEL_Tnktnr_Dstlt_VLS,Rsdl_HS,Rsdl_VLS,Rsdl_ULS,Dstlt_VLS,Dstlt_ULS,Tnktnr_Dstlt_VLS,Time
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023-01-01,WVRN,1464071e-57e4-49b7-93d7-785790945511,WEC VAN RIJN,9315006.0,EC248R,01/01/2023 00:00,2023-01-01 12:00:00,UTC +01:00,PORT,IN PORT,4059N,00854W,40.983333,-8.9,0.00,9800.7,True,23.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.75,7.7,15767.0,0.0,0.0,0.0,348.0,16.0,11.0,NaN,PTLEI,31/12/2022 10:00,UTC +01:00,NaN,NaN,23.3,381.0,415.0,13.0,NaN,NaN,0.0,0.0,0.0,8.0,0.0,PTLEI,LEIXOES,False,False,NaN,NaN,NaN,NaN,Awaiting for pilot boarding time,NaN,31/12/2022 12:42,UTC +02:00,NaN,NaN,NaN,NaN,NaN,03/01/2023 23:00,UTC +01:00,0.0,NaN,NaN,193.0,259.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,180.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.90,0.0,0.0,0.0,0.0,0.0,0.90,0.0,0.0,0.0,0.0,1.08,0.0,0.0,0.0,0.0,0.0,1.08,2ND OFF,CH.ENG,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82.0,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,3256.0,0.0,4194.0,AE 2 - 23.3 h x 180 kWs SFOC 214.6 gKwh,NaN,NaN,0.3,NaN,NaN,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,179.65,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,179.65,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,299.0,NLMOE-PTLEI,N,Y,0.0,PT,NL,NaN,NaN,0.0,0.0,0.00,0.0,0.0,1.98,0.0,0.0,299.0,0.0,7.725,0.00,0.000,0.0,0.0,0.0,1.98,6.34788,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.90,1.08,1.98,0.0,0.00,0.0,0.0,1.98,6.35,23.3,180.0,0.05,0.0,14/02/2023 12:02,NaN,NaN,0.0,0.00,0.0,0.0,1.98,0.0,0.0,0.00,0.0,0.0,1.98,0.0,12:00:00
2023-01-02,WVRN,7c47f0af-cc29-4d41-a1b0-c4042178cc95,WEC VAN RIJN,9315006.0,EC248R,02/01/2023 00:00,2023-01-02 12:00:00,UTC +01:00,PORT,IN PORT,4059N,00854W,40.983333,-8.9,0.00,9800.7,True,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.75,7.7,15767.0,0.0,0.0,0.0,348.0,16.0,11.0,NaN,PTLEI,31/12/2022 10:00,UTC +01:00,NaN,NaN,24.0,381.0,415.0,13.0,NaN,NaN,0.0,0.0,0.0,8.0,0.0,PTLEI,LEIXOES,False,False,NaN,NaN,NaN,NaN,Awaiting for pilot boarding time,NaN,31/12/2022 12:42,UTC +02:00,NaN,NaN,NaN,NaN,NaN,03/01/2023 23:00,UTC +01:00,0.0,NaN,NaN,193.0,259.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,180.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.95,0.0,0.0,0.0,0.0,0.0,0.95,0.0,0.0,0.0,0.0,1.08,0.0,0.0,0.0,0.0,0.0,1.08,2ND OFF,CH.ENG,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.0,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,3256.0,0.0,4320.0,AE 2 - 24 h x 180 kWs SFOC 214.6 gKwh,NaN,NaN,0.3,NaN,NaN,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177.62,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,177.62,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,299.0,NLMOE-PTLEI,N,Y,0.0,PT,NL,NaN,NaN,0.0,0.0,0.00,0.0,0.0,2.03,0.0,0.0,299.0,0.0,7.725,0.00,0.000,0.0,0.0,0.0,2.03,6.50818,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.95,1.08,2.03,0.0,0.00,0.0,0.0,2.03,6.51,24.0,180.0,0.05,0.0,14/02/2023 12:02,NaN,NaN,0.0,0.00,0.0,0.0,2.03,0.0,0.0,0.00,0.0,0.0,2.03,0.0,12:00:00
2023-01-03,WVRN,1ef5ddd0-0f81-47b8-99c5-ffaf2938f2e0,WEC VAN RIJN,9315006.0,EC248R,03/01/2023 00:00,2023-01-03 12:00:00,UTC +01:00,PORT,IN PORT,4059N,00854W,40.983333,-8.9,0.68,9800.7,True,1.5,1.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.75,7.7,15767.0,0.0,0.0,0.0,348.0,16.0,11.0,NaN,PTLEI,31/12/2022 10:00,UTC +01:00,NaN,NaN,24.0,381.0,415.0,13.0,NaN,NaN,0.0,0.0,0.0,8.0,0.0,PTLEI,LEIXOES,False,False,NaN,NaN,NaN,NaN,Awaiting for pilot boarding time,NaN,31/12/2022 12:42,UTC +02:00,NaN,NaN,NaN,NaN,NaN,03/01/2023 23:00,UTC +01:00,1.5,NaN,NaN,193.0,259.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.5,0.0,0.0,0.0,0.0,0.0,0.0,1.5,0.0,0.0,0.0,5.0,20.5,0.0,0.0,0.0,0.0,0.0,2300.0,155.0,155.0,0.0,0.0,0.0,0.0,0.0,0.68,0.0,0.0,0.0,0.0,0.0,0.0,0.68,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.91,0.0,0.0,0.0,0.0,0.0,0.91,0.0,0.0,0.0,0.0,1.02,0.0,0.0,0.0,0.0,0.0,1.02,2ND OFF,CH.ENG,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,79.0,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,3256.0,0.0,4440.0,Shifting ME 1.5 h x 2300 kWts SFOC 194.2 g_kW...,NaN,NaN,0.3,NaN,NaN,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,175.69,0.0,0.0,0.0,117.34,0.0,0.0,0.0,117.34,0.0,0.0,175.69,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,299.0,NLMOE-PTLEI,N,Y,1.5,PT,NL,NaN,NaN,0.0,0.0,0.68,0.0,0.0,1.93,0.0,0.0,299.0,0.0,7.725,10.88,197.101,0.0,0.0,0.0,2.61,8.30510,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.68,0.91,1.02,2.61,0.0,0.68,0.0,0.0,1.93,8.31,25.5,310.0,0.05,0.0,14/02/2023 12:02,NaN,NaN,0.0,0.68,0.0,0.0,1.93,0.0,0.0,0.68,0.0,0.0,1.93,0.0,12:00:00
2023-01-03,WVRN,5b064ae7-6988-4a3f-a035-bd9b37e29b16,WEC VAN RIJN,9315006.0,NaN,04/01/2023 00:00,2023-01-03 18:29:00,UTC +01:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,9800.7,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,193.0,259.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,299.0,NLMOE-PTLEI,N,Y,0.0,PT,NL,NaN,NaN,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,299.0,0.0,0.000,0.00,0.000,0.0,0.0,0.0,0.00,0.00000,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.0,0.0,0.00,0.0,14/02/2023 12:02,NaN,NaN,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,18:29:00
2023-01-03,WVRN,60a74f1e-dbfc-4aa1-b341-193abe289c9a,WEC VAN RIJN,9315006.0,NaN,04/01/2023 00:00,2023-01-03 18:29:00,UTC +01:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,9800.7,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,193.0,259.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,299.0,NLMOE-PTLEI,N,Y,0.0,PT,NL,NaN,NaN,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,299.0,0.0,0.000,0.00,0.000,0.0,0.0,0.0,0.00,0.00000,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.0,0.0,0.00,0.0,14/02/2023 12:02,NaN,NaN,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,18:29:00

In [32]:
Res_dfn = Res_dfn.sort_values(by='REPORT_DATE_TIME')

In [33]:

start_date = '2023-05-17'
end_date = '2023-06-17'
start_date = pd.to_datetime(start_date, format='%Y-%m-%d')
end_date = pd.to_datetime(end_date, format='%Y-%m-%d')

filtered_df = Res_dfn[(Res_dfn['REPORT_DATE_TIME'] >= start_date) & (Res_dfn['REPORT_DATE_TIME'] <= end_date)]

In [34]:
filtered_df.head()

,idvessel,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,LAT,LONG_,LATITUDE,LONGITUDE,M_E_FOC,CARGO_TOTAL,Has_Cargo,TOTAL_STEAMING_TIME,M_E_Fuel_Only_Steaming_Time,MILES_BY_GPS,OIL_CYL,SOW,SOG,RPM,SLIP,WIND_DIRECTION,WIND_SPEED,DRAFT_AFT,DRAFT_FWD,DISPLACEMENT,COURSE_AT_SEA,WAVE_HEIGHT,SEA_DIRECTION,CARGO_TOTAL_TEU,AMBIENT_TEMP,SW_TEMP,MILES_BY_SPEED_LOG,ETA_PORT_CODE,ETA_DATE_TIME,ETA_DATE_TIME_Offset,ETA_PORT,TIME_CHANGE,TIME_SEA,TEMP_MIN,TEMP_MAX,REQUESTED_SPEED,REM_DIST_TO_PILOT,REM_TIME_TO_PILOT,TOTAL_UNPLND_STPGE_TECH,TOTAL_UNPLND_STPGE_OPE_WX,REEFERS_POSITIVE_PLUGGED,REEFERS_NEGATIVE_PLUGGED,ME_TOTAL_REVS_COUNTER,PORT_CODE,PORT,AUX_BLOWERS_ON,HOLD_VENTILATION_ON,SINCE_DATE_TIME,SINCE_DATE_TIME_Offset,TIME_HRS_ANCHOR,TIME_HRS_DRIFT,REASON,TYPE_OF_DELAY,ETB_DATE_TIME,ETB_DATE_TIME_Offset,PILOT_DATE_TIME,PILOT_DATE_TIME_Offset,TIME_MANOEUVRING,TUG_ARR,TUG_SHIFT,ETD_DATE_TIME,ETD_DATE_TIME_Offset,SHIFT_BERTH_HOURS,CARGO_LOAD,CARGO_DISCH,TEU_FULL,TEU_EMPTY,BILGE_REMOVED,GARBAGE_REMOVED,GARBAGE_REMVL_REQSTD,GARBAGE_REMVL_CMPLSRY,FW_SUPPLY,CY_CREW_SIGNED_ON,CY_CREW_SIGNED_OFF,CY_DOCTORS_VISIT,CY_MAIL_RECEIVED_Ref_NO,CY_LUB_OIL_SAMPLE_LANDED,CY_CHECKD_FOR_STOWAWAYS,CY_STOWAWAYS_ON_BOARD,CY_DEP_GM_Mtr,CY_REQUISITIONS_RECEIVED,DISTANCE_TO_NEXT_PILOT,TUG_SAILING_TRANSIT,STEAMING_TIME_M_E_Rsdl_VLS,STEAMING_TIME_M_E_Rsdl_HS,STEAMING_TIME_M_E_Rsdl_ULS,STEAMING_TIME_M_E_Dstlt_VLS,STEAMING_TIME_M_E_Dstlt_ULS,STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS,STEAMING_TIME_M_E_HS,STEAMING_TIME_M_E_LS,STEAMING_TIME_M_E_MDO,STEAMING_TIME_M_E_MGO,STEAMING_TIME_M_E_MGO_LS,STEAMING_TIME_AUX_1,STEAMING_TIME_AUX_2,STEAMING_TIME_AUX_3,STEAMING_TIME_AUX_4,STEAMING_TIME_AUX_5,STEAMING_TIME_SH_GEN,STEAMING_TIME_TG,POWER_kW,STEAMING_LOAD_KW_AUX_1,STEAMING_LOAD_KW_AUX_2,STEAMING_LOAD_KW_AUX_3,STEAMING_LOAD_KW_AUX_4,STEAMING_LOAD_KW_AUX_5,STEAMING_LOAD_KW_SH_GEN,STEAMING_LOAD_KW_TG,FUEL_M_E_Rsdl_VLS,FUEL_M_E_Rsdl_HS,FUEL_M_E_Rsdl_ULS,FUEL_M_E_Dstlt_VLS,FUEL_M_E_Dstlt_ULS,FUEL_M_E_Tnktnr_Dstlt_VLS,FUEL_M_E_HS,FUEL_M_E_LS,FUEL_M_E_MDO,FUEL_M_E_MGO,FUEL_M_E_MGO_LS,FUEL_Aux_Rsdl_VLS,FUEL_Aux_Rsdl_HS,FUEL_Aux_Rsdl_ULS,FUEL_Aux_Dstlt_VLS,FUEL_Aux_Dstlt_ULS,FUEL_Aux_Tnktnr_Dstlt_VLS,FUEL_AUX_HS,FUEL_AUX_LS,FUEL_AUX_MDO,FUEL_AUX_MGO,FUEL_AUX_MGO_LS,FUEL_Boiler_Rsdl_VLS,FUEL_Boiler_Rsdl_HS,FUEL_Boiler_Rsdl_ULS,FUEL_Boiler_Dstlt_VLS,FUEL_Boiler_Dstlt_ULS,FUEL_Boiler_Tnktnr_Dstlt_VLS,FUEL_BOILER_HS,FUEL_BOILER_LS,FUEL_BOILER_MDO,FUEL_BOILER_MGO,FUEL_BOILER_MGO_LS,DECK_LAST_CHANGE_USER,ENGINE_LAST_CHANGE_USER,DECK_PART_IS_COMPLETE,ENGINE_PART_IS_COMPLETE,SCAVENGE_PRESSURE,SECA_ENTRY_TIME,SECA_ENTRY_LAT,SECA_ENTRY_LONG,SECA_EXIT_TIME,SECA_EXIT_LAT,SECA_EXIT_LONG,ROB_FRESH_WATER,MANVRNG_MILES_BY_GPS,MANVRNG_MILES_BY_SPEED_LOG,TANKTAINER_TRANSFD_QUANTITY,PILOT_TAKEN,DATE_TIME_START_TRANSIT,DATE_TIME_START_TRANSIT_Offset,DATE_TIME_END_TRANSIT,DATE_TIME_END_TRANSIT_Offset,BALLAST,TANKTAINER_NUMBER,STEAMING_KWHR_TOTAL,CY_OTHERS,ROB_FO_SLUDGE,ROB_LO_SLUDGE,ROB_BILGE,SLUDGE_REMOVED_FO,SLUDGE_REMOVED_LO,SEA_STATE,CY_LUB_ADDED_TO_SYSTEM_MECC,CY_LUB_ADDED_TO_SYSTEM_AECC,CY_LUB_ADDED_TO_THRUSTERS,CY_ME_LO_PURIFIER_IN_USE,CY_BALLAST,CY_BENDING_MOMENT,CY_SHEARING_FORCE,CY_TORTION_MOMENT,CY_SUPDT_AUDITOR_SIGNED_ON,CY_SUPDT_AUDITOR_SIGNED_OFF,CY_CASH_RECEIVED,CY_LUB_OIL_RECEIVED_MECYL,CY_LUB_OIL_RECEIVED_MECC,CY_LUB_OIL_RECEIVED_AECC,CY_M_E_UNDER_PISTON_TEMP,CY_MAIL_RECEIVED,WIND_DIRECTION_PORT_STBD,SEA_DIRECTION_PORT_STBD,TIME_PILOT_ONBOARD,GRADES_ROB,SO2_CO2_RATIO,Bunker_Order,Remarks,Fuel_Type,Carbon_Factor,Sulphur_Content_PC,Quantity,Port_Delivery,Product_Quality,Tanktainer_Number_1,Supplier,Delivery,Vol_Lt,Den,Vis,ROB_Dstlt_ULS,ROB_Dstlt_VLS,ROB_Rsdl_MDO,ROB_Tnktnr_Dstlt_VLS,ROB_Rsdl_VLS,ROB_Rsdl_HS,ROB_Rsdl_ULS,ROB_Fuel_HSFO,ROB_Fuel_LSFO,ROB_Fuel_MDO,ROB_Fuel_MGO,ROB_Fuel_MGO_LS,ROB_Fuel_Tanktainer_MGO,ECA_MILES,ECA_TIME,EGCS_DRY_WASTE_REMOVED,EGCS_RUNNING_TIME,EGCS_WET_SLURRY_REMOVED,EGCS_OPEN_LOOP_RUNNING_TIME,EGCS_CLOSED_LOOP_RUNNING_TIME,Voyage_Order,Voyage_Code,ECA,EU,Sea_Time,ETA_Country_Code,Port_Country_Code,check_ETA_code,check_Port_code,Status_TEMP_EU,FUEL_HS,FUEL_LS,FUEL_MDO,FUEL_MGO,FUEL_MGO_LS,Cargo_Transport_Work,TEU_Transport_Work,EEOI_Voyage_no,CARGO_TOTAL_Old,DRAFT,FO_per_24Hrs,SFOC,CY_OIL_gm_hr,SCOC,Voyage_Name,TOTAL_FO,TOTAL_CO2,EEOI,voyCondition,samedate,timesincelastreport,BDN,Wind_direction_360,True_wind_speed,True_wind_dir,ref_power,ref_fuel,fuel_loss,Relative_wind_speed,Relative_wind_direction,CAA,RW,Corrected_Power,draft_pow,draft_sp_pow,fo_nor,fo_model,sfoc_model,sfoc_deviation,ref_power_corrected,ref_FO_corrected,Propulsive_eff,speed_performance,Ref_speed,P_I,MEcon,AEcon,BLcon,Tcon,HS,LS,MDO,MGO,MGOLS,TCO2,AETsteaming,AEPOWER,TRIM,DISTANCECOVERED,updated_date,hyd_slip_sog,hyd_slip_stw,FUEL_Rsdl_HS,FUEL_Rsdl_VLS,FUEL_Rsdl_ULS,FUEL_Dstlt_VLS,FUEL_Dstlt_ULS,FUEL_Tnktnr_Dstlt_VLS,Rsdl_HS,Rsdl_VLS,Rsdl_ULS,Dstlt_VLS,Dstlt_ULS,Tnktnr_Dstlt_VLS,Time
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023-07-19,WVRN,35055f9a-a80b-46d1-af54-2309c9eb8ca8,WEC VAN RIJN,9315006.0,EC328A,19/07/2023 00:00,2023-07-19 12:00:00,UTC +02:00,PORT,IN PORT,5159N,00359E,51.983333,3.983333,2.66,5444.0,True,5.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.4,6.9,14279.0,0.0,0.0,0.0,570.0,23.0,19.0,NaN,NLMOE,16/07/2023 04:00,UTC +02:00,NaN,NaN,24.0,395.0,410.0,12.5,NaN,NaN,0.0,0.0,1.0,2.0,150000.0,NLMOE,MOERDIJK,False,False,NaN,NaN,NaN,NaN,NOON,NaN,16/07/2023 17:00,UTC +02:00,NaN,NaN,NaN,NaN,NaN,19/07/2023 15:00,UTC +02:00,5.0,NaN,NaN,351.0,219.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,5.0,20.1,10.1,0.0,0.0,0.0,5.0,0.0,1618.0,280.0,220.0,0.0,0.0,0.0,300.0,0.0,0.0,0.0,0.0,0.0,2.66,0.0,0.0,0.0,0.0,0.0,2.66,0.0,0.0,0.0,0.0,1.338,0.0,0.0,0.0,0.0,0.0,1.338,0.0,0.0,0.0,0.0,0.45,0.0,0.0,0.0,0.0,0.0,0.45,2ND OFF,CH. ENG,TRUE,TRUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110.0,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,3450,0,1550,NaN,NaN,NaN,0.8,NaN,NaN,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,259.91,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,259.91,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,364.0,GBTHP-NLMOE,N,Y,5.0,NL,GB,NaN,NaN,0.0,0.0,0.0,0.0,0.0,4.448,0.0,0.0,364.0,0.0,7.15,12.768,328.801,0.0,0.0,0.0,4.448,14.2603,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.66,1.34,0.45,4.45,0.0,0.0,0.0,0.0,4.45,14.27,30.2,500.0,0.5,0.0,07/08/2023 10:33,NaN,NaN,0.0,0.0,0.0,0.0,4.448,0.0,0.0,0.0,0.0,0.0,4.45,0.0,12:00:00
2023-07-19,WVRN,2ef7c84d-e96e-411a-8590-871b4fd6d3ae,WEC VAN RIJN,9315006.0,NaN,20/07/2023 00:00,2023-07-19 16:05:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,5444.0,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,351.0,219.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,364.0,GBTHP-NLMOE,N,Y,0.0,NL,GB,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,364.0,0.0,0.00,0.000,0.000,0.0,0.0,0.0,0.000,0.0000,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,07/08/2023 10:33,NaN,NaN,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.00,0.0,16:05:00
2023-07-19,WVRN,35285b8e-1cd2-43a4-8ad1-a08627bec291,WEC VAN RIJN,9315006.0,NaN,20/07/2023 00:00,2023-07-19 16:05:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,5444.0,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,351.0,219.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,364.0,GBTHP-NLMOE,N,Y,0.0,NL,GB,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,364.0,0.0,0.00,0.000,0.000,0.0,0.0,0.0,0.000,0.0000,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,07/08/2023 10:33,NaN,NaN,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.00,0.0,16:05:00
2023-07-19,WVRN,43ef424f-6188-4b0e-a1b0-4ce8ca0ee625,WEC VAN RIJN,9315006.0,NaN,20/07/2023 00:00,2023-07-19 16:05:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,5444.0,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,351.0,219.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,364.0,GBTHP-NLMOE,N,Y,0.0,NL,GB,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,364.0,0.0,0.00,0.000,0.000,0.0,0.0,0.0,0.000,0.0000,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,07/08/2023 10:33,NaN,NaN,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.00,0.0,16:05:00
2023-07-19,WVRN,4d763760-3785-4346-b2b5-52f62475b41f,WEC VAN RIJN,9315006.0,NaN,20/07/2023 00:00,2023-07-19 16:05:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,5444.0,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,351.0,219.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,364.0,GBTHP-NLMOE,N,Y,0.0,NL,GB,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,364.0,0.0,0.00,0.000,0.000,0.0,0.0,0.0,0.000,0.0000,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,07/08/2023 10:33,NaN,NaN,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.00,0.0,16:05:00

In [35]:
pd.set_option('display.max_columns', None)  
filtered_df.tail()

,idvessel,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,LAT,LONG_,LATITUDE,LONGITUDE,M_E_FOC,CARGO_TOTAL,Has_Cargo,TOTAL_STEAMING_TIME,M_E_Fuel_Only_Steaming_Time,MILES_BY_GPS,OIL_CYL,SOW,SOG,RPM,SLIP,WIND_DIRECTION,WIND_SPEED,DRAFT_AFT,DRAFT_FWD,DISPLACEMENT,COURSE_AT_SEA,WAVE_HEIGHT,SEA_DIRECTION,CARGO_TOTAL_TEU,AMBIENT_TEMP,SW_TEMP,MILES_BY_SPEED_LOG,ETA_PORT_CODE,ETA_DATE_TIME,ETA_DATE_TIME_Offset,ETA_PORT,TIME_CHANGE,TIME_SEA,TEMP_MIN,TEMP_MAX,REQUESTED_SPEED,REM_DIST_TO_PILOT,REM_TIME_TO_PILOT,TOTAL_UNPLND_STPGE_TECH,TOTAL_UNPLND_STPGE_OPE_WX,REEFERS_POSITIVE_PLUGGED,REEFERS_NEGATIVE_PLUGGED,ME_TOTAL_REVS_COUNTER,PORT_CODE,PORT,AUX_BLOWERS_ON,HOLD_VENTILATION_ON,SINCE_DATE_TIME,SINCE_DATE_TIME_Offset,TIME_HRS_ANCHOR,TIME_HRS_DRIFT,REASON,TYPE_OF_DELAY,ETB_DATE_TIME,ETB_DATE_TIME_Offset,PILOT_DATE_TIME,PILOT_DATE_TIME_Offset,TIME_MANOEUVRING,TUG_ARR,TUG_SHIFT,ETD_DATE_TIME,ETD_DATE_TIME_Offset,SHIFT_BERTH_HOURS,CARGO_LOAD,CARGO_DISCH,TEU_FULL,TEU_EMPTY,BILGE_REMOVED,GARBAGE_REMOVED,GARBAGE_REMVL_REQSTD,GARBAGE_REMVL_CMPLSRY,FW_SUPPLY,CY_CREW_SIGNED_ON,CY_CREW_SIGNED_OFF,CY_DOCTORS_VISIT,CY_MAIL_RECEIVED_Ref_NO,CY_LUB_OIL_SAMPLE_LANDED,CY_CHECKD_FOR_STOWAWAYS,CY_STOWAWAYS_ON_BOARD,CY_DEP_GM_Mtr,CY_REQUISITIONS_RECEIVED,DISTANCE_TO_NEXT_PILOT,TUG_SAILING_TRANSIT,STEAMING_TIME_M_E_Rsdl_VLS,STEAMING_TIME_M_E_Rsdl_HS,STEAMING_TIME_M_E_Rsdl_ULS,STEAMING_TIME_M_E_Dstlt_VLS,STEAMING_TIME_M_E_Dstlt_ULS,STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS,STEAMING_TIME_M_E_HS,STEAMING_TIME_M_E_LS,STEAMING_TIME_M_E_MDO,STEAMING_TIME_M_E_MGO,STEAMING_TIME_M_E_MGO_LS,STEAMING_TIME_AUX_1,STEAMING_TIME_AUX_2,STEAMING_TIME_AUX_3,STEAMING_TIME_AUX_4,STEAMING_TIME_AUX_5,STEAMING_TIME_SH_GEN,STEAMING_TIME_TG,POWER_kW,STEAMING_LOAD_KW_AUX_1,STEAMING_LOAD_KW_AUX_2,STEAMING_LOAD_KW_AUX_3,STEAMING_LOAD_KW_AUX_4,STEAMING_LOAD_KW_AUX_5,STEAMING_LOAD_KW_SH_GEN,STEAMING_LOAD_KW_TG,FUEL_M_E_Rsdl_VLS,FUEL_M_E_Rsdl_HS,FUEL_M_E_Rsdl_ULS,FUEL_M_E_Dstlt_VLS,FUEL_M_E_Dstlt_ULS,FUEL_M_E_Tnktnr_Dstlt_VLS,FUEL_M_E_HS,FUEL_M_E_LS,FUEL_M_E_MDO,FUEL_M_E_MGO,FUEL_M_E_MGO_LS,FUEL_Aux_Rsdl_VLS,FUEL_Aux_Rsdl_HS,FUEL_Aux_Rsdl_ULS,FUEL_Aux_Dstlt_VLS,FUEL_Aux_Dstlt_ULS,FUEL_Aux_Tnktnr_Dstlt_VLS,FUEL_AUX_HS,FUEL_AUX_LS,FUEL_AUX_MDO,FUEL_AUX_MGO,FUEL_AUX_MGO_LS,FUEL_Boiler_Rsdl_VLS,FUEL_Boiler_Rsdl_HS,FUEL_Boiler_Rsdl_ULS,FUEL_Boiler_Dstlt_VLS,FUEL_Boiler_Dstlt_ULS,FUEL_Boiler_Tnktnr_Dstlt_VLS,FUEL_BOILER_HS,FUEL_BOILER_LS,FUEL_BOILER_MDO,FUEL_BOILER_MGO,FUEL_BOILER_MGO_LS,DECK_LAST_CHANGE_USER,ENGINE_LAST_CHANGE_USER,DECK_PART_IS_COMPLETE,ENGINE_PART_IS_COMPLETE,SCAVENGE_PRESSURE,SECA_ENTRY_TIME,SECA_ENTRY_LAT,SECA_ENTRY_LONG,SECA_EXIT_TIME,SECA_EXIT_LAT,SECA_EXIT_LONG,ROB_FRESH_WATER,MANVRNG_MILES_BY_GPS,MANVRNG_MILES_BY_SPEED_LOG,TANKTAINER_TRANSFD_QUANTITY,PILOT_TAKEN,DATE_TIME_START_TRANSIT,DATE_TIME_START_TRANSIT_Offset,DATE_TIME_END_TRANSIT,DATE_TIME_END_TRANSIT_Offset,BALLAST,TANKTAINER_NUMBER,STEAMING_KWHR_TOTAL,CY_OTHERS,ROB_FO_SLUDGE,ROB_LO_SLUDGE,ROB_BILGE,SLUDGE_REMOVED_FO,SLUDGE_REMOVED_LO,SEA_STATE,CY_LUB_ADDED_TO_SYSTEM_MECC,CY_LUB_ADDED_TO_SYSTEM_AECC,CY_LUB_ADDED_TO_THRUSTERS,CY_ME_LO_PURIFIER_IN_USE,CY_BALLAST,CY_BENDING_MOMENT,CY_SHEARING_FORCE,CY_TORTION_MOMENT,CY_SUPDT_AUDITOR_SIGNED_ON,CY_SUPDT_AUDITOR_SIGNED_OFF,CY_CASH_RECEIVED,CY_LUB_OIL_RECEIVED_MECYL,CY_LUB_OIL_RECEIVED_MECC,CY_LUB_OIL_RECEIVED_AECC,CY_M_E_UNDER_PISTON_TEMP,CY_MAIL_RECEIVED,WIND_DIRECTION_PORT_STBD,SEA_DIRECTION_PORT_STBD,TIME_PILOT_ONBOARD,GRADES_ROB,SO2_CO2_RATIO,Bunker_Order,Remarks,Fuel_Type,Carbon_Factor,Sulphur_Content_PC,Quantity,Port_Delivery,Product_Quality,Tanktainer_Number_1,Supplier,Delivery,Vol_Lt,Den,Vis,ROB_Dstlt_ULS,ROB_Dstlt_VLS,ROB_Rsdl_MDO,ROB_Tnktnr_Dstlt_VLS,ROB_Rsdl_VLS,ROB_Rsdl_HS,ROB_Rsdl_ULS,ROB_Fuel_HSFO,ROB_Fuel_LSFO,ROB_Fuel_MDO,ROB_Fuel_MGO,ROB_Fuel_MGO_LS,ROB_Fuel_Tanktainer_MGO,ECA_MILES,ECA_TIME,EGCS_DRY_WASTE_REMOVED,EGCS_RUNNING_TIME,EGCS_WET_SLURRY_REMOVED,EGCS_OPEN_LOOP_RUNNING_TIME,EGCS_CLOSED_LOOP_RUNNING_TIME,Voyage_Order,Voyage_Code,ECA,EU,Sea_Time,ETA_Country_Code,Port_Country_Code,check_ETA_code,check_Port_code,Status_TEMP_EU,FUEL_HS,FUEL_LS,FUEL_MDO,FUEL_MGO,FUEL_MGO_LS,Cargo_Transport_Work,TEU_Transport_Work,EEOI_Voyage_no,CARGO_TOTAL_Old,DRAFT,FO_per_24Hrs,SFOC,CY_OIL_gm_hr,SCOC,Voyage_Name,TOTAL_FO,TOTAL_CO2,EEOI,voyCondition,samedate,timesincelastreport,BDN,Wind_direction_360,True_wind_speed,True_wind_dir,ref_power,ref_fuel,fuel_loss,Relative_wind_speed,Relative_wind_direction,CAA,RW,Corrected_Power,draft_pow,draft_sp_pow,fo_nor,fo_model,sfoc_model,sfoc_deviation,ref_power_corrected,ref_FO_corrected,Propulsive_eff,speed_performance,Ref_speed,P_I,MEcon,AEcon,BLcon,Tcon,HS,LS,MDO,MGO,MGOLS,TCO2,AETsteaming,AEPOWER,TRIM,DISTANCECOVERED,updated_date,hyd_slip_sog,hyd_slip_stw,FUEL_Rsdl_HS,FUEL_Rsdl_VLS,FUEL_Rsdl_ULS,FUEL_Dstlt_VLS,FUEL_Dstlt_ULS,FUEL_Tnktnr_Dstlt_VLS,Rsdl_HS,Rsdl_VLS,Rsdl_ULS,Dstlt_VLS,Dstlt_ULS,Tnktnr_Dstlt_VLS,Time
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023-08-16,WVRN,792113c4-4f7d-4abb-8fcd-fcf149916530,WEC VAN RIJN,9315006.0,EC332A,17/08/2023 00:00,2023-08-16 13:12:00,UTC +02:00,SAIL,IN PORT,5146N,00355E,51.766667,3.916667,0.00,8624.0,True,1.2,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0,0.0,0.0,8.5,8.3,17444.0,0.0,0.00,0.00,727.0,19.0,17.0,NaN,ESBIO,19/08/2023 06:00,UTC +02:00,BILBAO,NaN,1.2,395.0,410.0,5.7,NaN,NaN,0.0,0.0,2.0,31.0,0.0,BEANR,ANTWERP,False,False,NaN,NaN,NaN,NaN,ANCHORAGE,NaN,16/08/2023 06:00,UTC +02:00,NaN,NaN,NaN,NaN,0.0,16/08/2023 13:30,UTC +02:00,NaN,2907.3,534.6,503.0,224.0,0.0,NaN,False,False,0.0,0.0,0.0,No,0,0,YES,NO,0.79,0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.2,0.6,0.0,0.0,0.0,0.0,0.0,0.0,220.0,150.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.073,0.0,0.0,0.0,0.0,0.0,0.073,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2ND OFF,CH. ENG,TRUE,TRUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.0,0.0,NaN,0.0,FALSE,NaN,NaN,NaN,NaN,3156,0,354,NaN,NaN,NaN,0.1,NaN,NaN,0.0,0.0,0.0,0.0,1.0,NaN,73.0,66.0,26.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,228.06,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,228.06,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,380.0,BEANR-ESBIO,N,Y,0.0,ES,BE,NaN,NaN,0.0,0.0,0.00,0.0,0.0,0.073,0.0,0.0,379.0,0.0,8.4,0.0000,0.0000,0.0,0.0,0.0,0.073,0.234038,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.07,0.0,0.07,0.0,0.00,0.0,0.0,0.07,0.22,1.8,370.0,0.2,0.0,06/09/2023 12:21,NaN,NaN,0.0,0.00,0.0,0.0,0.073,0.0,0.0,0.00,0.0,0.0,0.07,0.0,13:12:00
2023-08-16,WVRN,8290fb17-4ede-455b-b1f7-791cdd64d651,WEC VAN RIJN,9315006.0,EC332A,17/08/2023 00:00,2023-08-16 19:18:00,UTC +02:00,COSP,DRIFTING,5122N,00241E,51.366667,2.683333,5.75,8624.0,True,6.1,6.1,77.0,0.0,0.0000,0.0000,0.0,0.0,45.0,5.0,8.5,8.3,17444.0,270.0,0.40,45.00,727.0,24.0,17.0,NaN,ESBIO,18/08/2023 21:30,UTC +02:00,BILBAO,NaN,6.1,395.0,410.0,14.3,NaN,NaN,0.0,0.0,2.0,31.0,183000.0,BEANR,ANTWERP,False,False,NaN,NaN,NaN,NaN,ANCHORAGE,NaN,16/08/2023 06:00,UTC +02:00,NaN,NaN,6.1,NaN,NaN,16/08/2023 13:30,UTC +02:00,NaN,NaN,NaN,503.0,224.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,724.0,0.0,0.0,0.0,0.0,0.0,6.1,0.0,0.0,0.0,0.0,0.0,6.1,6.1,6.1,0.0,0.0,0.0,6.1,0.0,4984.0,150.0,150.0,0.0,0.0,0.0,300.0,0.0,0.00,0.0,0.0,0.0,5.75,0.0,0.0,0.00,0.0,0.0,5.75,0.0,0.0,0.0,0.0,0.370,0.0,0.0,0.0,0.0,0.0,0.370,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2ND OFF,CH. ENG,TRUE,TRUE,0,NaN,NaN,NaN,NaN,NaN,NaN,102.0,77.0,76.9,NaN,TRUE,NaN,NaN,NaN,NaN,3156,0,1830,NaN,NaN,NaN,0.2,NaN,NaN,2.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,P,P,6.2,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,221.94,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,221.94,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,380.0,BEANR-ESBIO,N,Y,6.1,ES,BE,NaN,NaN,0.0,0.0,0.00,0.0,0.0,6.120,664048.0,55979.0,380.0,0.0,8.4,22.6230,189.1300,0.0,0.0,0.0,6.120,19.620700,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.75,0.37,0.0,6.12,0.0,0.00,0.0,0.0,6.12,19.62,12.2,300.0,0.2,77.0,06/09/2023 12:21,NaN,NaN,0.0,0.00,0.0,0.0,6.120,0.0,0.0,0.00,0.0,0.0,6.12,0.0,19:18:00
2023-08-17,WVRN,a73a9aa5-fdbc-4cb4-b9d5-18ad2614ef0b,WEC VAN RIJN,9315006.0,EC332A,17/08/2023 00:00,2023-08-17 12:00:00,UTC +02:00,NOON,AT SEA,4948N,00321W,49.800000,-3.350000,18.68,8624.0,True,16.7,16.7,257.0,0.0,15.3832,15.3892,129.0,0.0,160.0,6.0,8.4,8.2,17424.0,240.0,2.52,174.43,727.0,22.0,17.0,256.9,ESBIO,18/08/2023 19:00,UTC +02:00,BILBAO,NaN,16.7,395.0,410.0,15.0,466.0,31.0,0.0,0.0,2.0,31.0,501000.0,BEANR,ANTWERP,False,False,NaN,NaN,NaN,NaN,ANCHORAGE,NaN,16/08/2023 06:00,UTC +02:00,NaN,NaN,NaN,NaN,NaN,16/08/2023 13:30,UTC +02:00,NaN,NaN,NaN,503.0,224.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,16.7,0.0,0.0,0.0,0.0,0.0,16.7,0.0,0.0,0.0,0.0,0.0,16.7,0.0,5845.0,0.0,0.0,0.0,0.0,0.0,332.0,0.0,0.00,0.0,0.0,0.0,18.68,0.0,0.0,0.00,0.0,0.0,18.68,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2ND OFF,CH. ENG,TRUE,TRUE,2.7,NaN,NaN,NaN,NaN,NaN,NaN,100.0,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,3156,0,5544,ADJUST SPEED ACCORDING CHARTER INSTRUCTIONS,NaN,NaN,0.2,NaN,NaN,5.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,P,P,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,203.26,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,203.26,0.0,257.0,16.7,NaN,0.0,NaN,0.0,0.0,380.0,BEANR-ESBIO,N,Y,16.7,ES,BE,NaN,NaN,0.0,0.0,0.00,0.0,0.0,18.680,2216370.0,186839.0,380.0,0.0,8.3,26.8455,191.3710,0.0,0.0,0.0,18.680,59.888100,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.68,0.00,0.0,18.68,0.0,0.00,0.0,0.0,18.68,59.89,0.0,0.0,0.2,257.0,06/09/2023 12:21,NaN,NaN,0.0,0.00,0.0,0.0,18.680,0.0,0.0,0.00,0.0,0.0,18.68,0.0,12:00:00
2023-08-18,WVRN,a46af1e3-f597-4d6a-8b39-bc484d763fd7,WEC VAN RIJN,9315006.0,EC332A,18/08/2023 00:00,2023-08-18 12:00:00,UTC +02:00,NOON,AT SEA,4534N,00416W,45.566667,-4.266667,22.83,8624.0,True,24.0,24.0,327.0,0.0,13.6208,13.6250,129.0,0.3,20.0,5.0,8.4,8.2,17400.0,159.0,0.47,169.16,727.0,23.0,17.0,326.9,ESBIO,19/08/2023 00:01,UTC +02:00,BILBAO,NaN,24.0,395.0,410.0,11.6,139.0,12.0,0.0,0.0,2.0,31.0,720000.0,BEANR,ANTWERP,False,False,NaN,NaN,NaN,NaN,ANCHORAGE,NaN,16/08/2023 06:00,UTC +02:00,NaN,NaN,NaN,NaN,NaN,16/08/2023 13:30,UTC +02:00,NaN,NaN,NaN,503.0,224.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,0.0,0.0,0.0,24.0,0.0,0.0,24.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,5564.0,0.0,0.0,0.0,0.0,0.0,332.0,0.0,17.14,0.0,0.0,0.0,5.69,0.0,0.0,17.14,0.0,0.0,5.69,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2ND OFF,CH. ENG,TRUE,TRUE,2.6,NaN,NaN,NaN,NaN,NaN,NaN,105.0,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,3156,0,8160,ADJUST SPEED ACCORDING CHARTER INSTRUCTIONS,NaN,NaN,0.2,NaN,NaN,2.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,P,P,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,197.57,0.0,0.0,0.0,221.72,0.0,0.0,0.0,221.72,0.0,0.0,197.57,0.0,75.0,4.8,NaN,0.0,NaN,0.0,0.0,380.0,BEANR-ESBIO,N,Y,48.0,ES,BE,NaN,NaN,0.0,0.0,17.14,0.0,0.0,5.690,2820050.0,237729.0,380.0,0.0,8.3,11.4150,85.4826,0.0,0.0,0.0,22.830,71.616100,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.83,0.00,0.0,22.83,0.0,17.14,0.0,0.0,5.69,71.62,0.0,0.0,0.2,327.0,06/09/2023 12:21,NaN,NaN,0.0,17.14,0.0,0.0,5.690,0.0,0.0,17.14,0.0,0.0,5.69,0.0,12:00:00
2023-08-18,WVRN,1991073c-d982-415b-ae79-9249d33be91f,WEC VAN RIJN,9315006.0,EC332A,19/08/2023 00:00,2023-08-18 23:48:00,UTC +02:00,EOSP,AT SEA,4324N,00306W,43.400000,-3.100000,9.38,8624.0,True,11.8,11.8,139.0,0.0,11.7712,11.7797,129.0,-0.6,25.0,4.0,8.4,8.2,17390.0,158.0,0.39,168.29,727.0,19.0,17.0,138.9,ESBIO,19/08/2023 00:01,UTC +02:00,NaN,NaN,11.8,395.0,410.0,11.6,NaN,NaN,0.0,0.0,2.0,31.0,354000.0,ESBIO,BILBAO,False,False,NaN,NaN,NaN,NaN,ANCHORAGE,NaN,19/08/2023 00:30,UTC +02:00,NaN,NaN,NaN,NaN,NaN,16/08/2023 13:30,UTC +02:00,NaN,NaN,NaN,503.0,224.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.8,0.0,0.0,0.0,0.0,0.0,0.0,11.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.8,0.0,4206.0,0.0,0.0,0.0,0.0,0.0,351.0,0.0,9.38,0.0,0.0,0.0,0.00,0.0,0.0,9.38,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2ND OFF,CH. ENG,TRUE,TRUE,1.4,NaN,NaN,NaN,NaN,NaN,NaN,105.0,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,3156,0,4141,NaN,NaN,NaN,0.2,NaN,NaN,2.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,P,P,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,212.34,0.0,0.0,0.0,212.34,0.0,0.0,0.00,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,380.0,BEANR-ESBIO,N,Y,11.8,ES,BE,NaN,NaN,0.0,0.0,9.38,0.0,0.0,0.000,1198740.0,101053.0,380.0,0.0,8.3,19.0780,188.9960,0.0,0.0,0.0,9.380,29.209300,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.38,0.00,0.0,9.38,0.0,9.38,0.0,0.0,0.00,29.21,0.0,0.0,0.2,139.0,06/09/2023 12:21,NaN,NaN,0.0,9.38,0.0,0.0,0.000,0.0,0.0,9.38,0.0,0.0,0.00,0.0,23:48:00

In [36]:
filtered_df['Total_Calculated_MGO_LS'] = filtered_df[['FUEL_M_E_MGO_LS', 'FUEL_AUX_MGO_LS', 'FUEL_BOILER_MGO_LS']].sum(axis=1)

filtered_df['Total_Calculated_ULS'] = filtered_df[['FUEL_M_E_Dstlt_ULS', 'FUEL_Aux_Dstlt_ULS', 'FUEL_Boiler_Dstlt_ULS']].sum(axis=1)

filtered_df['Total_fuel'] = filtered_df[['Total_Calculated_MGO_LS', 'Total_Calculated_ULS']].sum(axis=1)

filtered_df['Total_BIO_Calculated'] = (filtered_df['Total_Calculated_MGO_LS'] * 3.206) + (filtered_df['Total_Calculated_ULS'] * 3.206)

In [37]:
dist = filtered_df['MILES_BY_GPS'].sum()
print(dist)

6114.0

In [38]:
dwt= 13734
filtered_df = filtered_df.assign(DWT=dwt)

In [39]:
TAFC= filtered_df['Total_BIO_Calculated'].sum() * 10**6
print(TAFC)

1520451912.0

# ATTAINED CII

In [40]:
ATT_CII = TAFC / (dist * dwt)
ATT_CII

18.107154682840505

# REFERNCE CII

In [41]:
'''

CII(REF)= A.CAPACITY^-C

PARAMETER FOR A AND C ARE

SHIP TYPE                           A            C         CAPACITY
TANKER                             5247         0.610       DWT
CONTAIER SHIP                      1984         0.489       DWT
BULK CARRIER: DWT >= 2,79,000      4745         0.622       2,79,00     
BULK CARRIER: DWT <= 2,79,00       4745         0.622       DWT
COMBINATION CARRIER                40853        0.812       DWT

'''

'\n\nCII(REF)= A.CAPACITY^-C\n\nPARAMETER FOR A AND C ARE\n\nSHIP TYPE                           A            C         CAPACITY\nTANKER                             5247         0.610       DWT\nCONTAIER SHIP                      1984         0.489       DWT\nBULK CARRIER: DWT >= 2,79,000      4745         0.622       2,79,00     \nBULK CARRIER: DWT <= 2,79,00       4745         0.622       DWT\nCOMBINATION CARRIER                40853        0.812       DWT\n\n'

In [42]:
#Parameters for reference cii
a = int(input("A:"))
c = float(input("C:"))
dwt= 13734

A:1984
C:0.489

In [43]:
CII_REF = a * (dwt ** (-c))
print(CII_REF)

18.800046080728777

# REQUIRED CII

In [44]:
'''
Required CII= CII(REF) * [(100-Z)/100]

REDUCATION FACTOR(Z%)
YEAR           REDUCTION FACTOR RELATIVE TO 2019
2019                   
2020                  1%
2021                  2%
2022                  3%
2023                  5%
2024                  7%
2025                  9%
2026                  11%

'''

'\nRequired CII= CII(REF) * [(100-Z)/100]\n\nREDUCATION FACTOR(Z%)\nYEAR           REDUCTION FACTOR RELATIVE TO 2019\n2019                   \n2020                  1%\n2021                  2%\n2022                  3%\n2023                  5%\n2024                  7%\n2025                  9%\n2026                  11%\n\n'

In [45]:
#Z-Reduction value
years = {
    2019: 0,
    2020: 1,
    2021: 2,
    2022: 3 ,
    2023: 5 ,
    2024: 7 ,
    2025: 9 ,
    2026: 11
}

a = int(input("Enter a year: "))    #ENTER THE CII YEAR
if a in years:
    Z = years[a]
    print(Z)
else:
    print("No Z value")

Enter a year: 2023
5

In [46]:
#Required CII 
CII_REQ = CII_REF * ((100 - Z) / 100)
print(CII_REQ)

17.860043776692336

# CII RATIO

In [47]:
'''

CII RATIO= ATTAINED CII/ REQUIRED CII
                                                DD VECTORS
SHIP TYPE                          CAPACITY     D1     D2    D3    D4  
BULK CARRIER                         DWT       0.86   0.94  1.06  1.18
TANKER                               DWT       0.82   0.93  1.08  1.28
CONTAINER                            DWT       0.83   0.94  1.07  1.19
COMBINATION                          DWT       0.87   0.96  1.06  1.14
GENERAL CARGO SHIP                   DWT       0.83   0.94  1.06  1.19


CII RATIO <= D1 ---------- A RATING
D1<CII RATIO <= D2 ------- B RATING
D2<CII RATIO <= D3 ------- C RATING
D3<CII RATIO <= D4 ------- D RATING
CII RATIO  > D4 ---------- E RATING

A – Major superior performance level
B – Minor superior performance level
C – Moderate performance level
D – Minor Inferior performance level
E – Inferior performance level

All vessels must aspire to be at least C-rated.Any vessel that is rated D or E for three years in a row will have to 
submit a corrective action plan that explains the efforts that will be taken to achieve an acceptable rating (C or above). 
 
'''

'\n\nCII RATIO= ATTAINED CII/ REQUIRED CII\n                                                DD VECTORS\nSHIP TYPE                          CAPACITY     D1     D2    D3    D4  \nBULK CARRIER                         DWT       0.86   0.94  1.06  1.18\nTANKER                               DWT       0.82   0.93  1.08  1.28\nCONTAINER                            DWT       0.83   0.94  1.07  1.19\nCOMBINATION                          DWT       0.87   0.96  1.06  1.14\nGENERAL CARGO SHIP                   DWT       0.83   0.94  1.06  1.19\n\n\nCII RATIO <= D1 ---------- A RATING\nD1<CII RATIO <= D2 ------- B RATING\nD2<CII RATIO <= D3 ------- C RATING\nD3<CII RATIO <= D4 ------- D RATING\nCII RATIO  > D4 ---------- E RATING\n\nA – Major superior performance level\nB – Minor superior performance level\nC – Moderate performance level\nD – Minor Inferior performance level\nE – Inferior performance level\n\nAll vessels must aspire to be at least C-rated.Any vessel that is rated D or E for three years in a row will have to \nsubmit a corrective action plan that explains the efforts that will be taken to achieve an acceptable rating (C or above). \n \n'

In [48]:
#CII Ratio
CII_RATIO= ATT_CII/ CII_REQuuuuuj
print(CII_RATIO)

1.0138359630714149

In [49]:
ships = {
    'BULK': {'D1': 0.86, 'D2': 0.94, 'D3': 1.06, 'D4': 1.18},
    'TANKER': {'D1': 0.82, 'D2': 0.93, 'D3': 1.08, 'D4': 1.28},
    'CONTAINER': {'D1': 0.83, 'D2': 0.94, 'D3': 1.07, 'D4': 1.19},
    'COMBINATION': {'D1': 0.87, 'D2': 0.96, 'D3': 1.06, 'D4': 1.14},
    'GENERAL CARGO SHIP': {'D1': 0.83, 'D2': 0.94, 'D3': 1.06, 'D4': 1.19},
}

def ratings(ship, cii_ratio):
    a = ships.get(ship)
    if a:
        if cii_ratio <= a['D1']:
            return 'A RATING'
        elif a['D1'] < cii_ratio <= a['D2']:
            return 'B RATING'
        elif a['D2'] < cii_ratio <= a['D3']:
            return 'C RATING'
        elif a['D3'] < cii_ratio <= a['D4']:
            return 'D RATING'
        else:
            return 'E RATING'
    else:
        return 'Data not founded'

ship = input("Enter the ship: ").strip().upper()  
CII_RATIO = CII_RATIO
rating = ratings(ship, CII_RATIO)
print(f'The rating is: {rating}')

Enter the ship: container
The rating for MSC AGREGENTO is: C RATING

In [1]:
import pandas as pd
final= {
    'Fuel': ['Bio fuel', 'Normal Fuel'],
    'Attained_CII': [14.269, 18.10],  
    'Required_CII': [17.860, 17.860],
    'Reference_CII':[18.80,18.80],
    'CII Ratio':[0.798,1.06],
    'CII Rating':['A RATING','C RATING']
    
}
final_df = pd.DataFrame(final)
final_df

,Fuel,Attained_CII,Required_CII,Reference_CII,CII Ratio,CII Rating
0,Bio fuel,14.269,17.86,18.8,0.798,A RATING
1,Normal Fuel,18.100,17.86,18.8,1.060,C RATING