In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
data=pd.read_csv("NOONDATA_WEC VAN EYCK.csv")

In [3]:
data.head()

,idvessel,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,...,FUEL_Rsdl_ULS,FUEL_Dstlt_VLS,FUEL_Dstlt_ULS,FUEL_Tnktnr_Dstlt_VLS,Rsdl_HS,Rsdl_VLS,Rsdl_ULS,Dstlt_VLS,Dstlt_ULS,Tnktnr_Dstlt_VLS
0,WVEY,4deec51e-9ff0-4a2c-a57d-bc003f3cfdaf,WEC VAN EYCK,9365984.0,EK046A,12/11/2020 00:00,12/11/2020 00:54,UTC +00:00,SAIL,IN PORT,...,0.0,0.0,1.67,0.0,0.0,0.00,0.0,0.0,1.67,0.0
1,WVEY,d5bcff04-5965-4ed7-958e-18f49f9a9b88,WEC VAN EYCK,9365984.0,EK046A,12/11/2020 00:00,12/11/2020 01:48,UTC +00:00,COSP,DRIFTING,...,0.0,0.0,0.12,0.0,0.0,0.52,0.0,0.0,0.12,0.0
2,WVEY,ad1e4d16-b5ef-4a13-b990-a96affeeec9c,WEC VAN EYCK,9365984.0,EK046A,12/11/2020 00:00,12/11/2020 12:00,UTC +00:00,NOON,AT SEA,...,0.0,0.0,0.00,0.0,0.0,9.81,0.0,0.0,0.00,0.0
3,WVEY,aa6db1ea-7bbc-41f2-9986-fa5f4c24a3dd,WEC VAN EYCK,9365984.0,EK046A,13/11/2020 00:00,12/11/2020 15:30,UTC +00:00,EOSP,AT SEA,...,0.0,0.0,0.00,0.0,0.0,2.68,0.0,0.0,0.00,0.0
4,WVEY,c1584f05-d139-403a-b77a-18ee7147765a,WEC VAN EYCK,9365984.0,EK046A,13/11/2020 00:00,12/11/2020 20:24,UTC +00:00,BRTH,DRIFTING,...,0.0,0.0,0.12,0.0,0.0,1.83,0.0,0.0,0.12,0.0

In [4]:
df=data.copy()

In [5]:
df.dtypes #checking the variable types

idvessel             object
GID                  object
VSL                  object
IMO_No              float64
VOY                  object
                     ...
Rsdl_VLS            float64
Rsdl_ULS            float64
Dstlt_VLS           float64
Dstlt_ULS           float64
Tnktnr_Dstlt_VLS    float64
Length: 321, dtype: object

In [6]:
df['REPORT_DATE_TIME'] = pd.to_datetime(df['REPORT_DATE_TIME'], format='%d/%m/%Y %H:%M', errors='coerce')

df['Date'] = df['REPORT_DATE_TIME'].dt.date
df['Time'] = df['REPORT_DATE_TIME'].dt.time

df['Date'] = pd.to_datetime(df['Date'])

cii_year = 2023
Res_df = df[df['Date'].dt.year == cii_year]
Res_df.set_index('Date', inplace=True)

In [7]:
Res_df.head()

,idvessel,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,...,FUEL_Dstlt_VLS,FUEL_Dstlt_ULS,FUEL_Tnktnr_Dstlt_VLS,Rsdl_HS,Rsdl_VLS,Rsdl_ULS,Dstlt_VLS,Dstlt_ULS,Tnktnr_Dstlt_VLS,Time
Date,,,,,,,,,,,,,,,,,,,,,
2023-01-01,WVEY,cbdf5a2f-14e8-4ece-bbb7-ee565e555c0a,WEC VAN EYCK,9365984.0,EI251A,01/01/2023 00:00,2023-01-01 12:00:00,UTC +01:00,NOON,AT SEA,...,0.0,18.96,0.0,0.0,0.00,0.0,0.0,18.96,0.0,12:00:00
2023-01-02,WVEY,aeff2126-5a79-4b20-b2cc-b04bad7641a6,WEC VAN EYCK,9365984.0,EI251A,02/01/2023 00:00,2023-01-02 12:00:00,UTC +01:00,NOON,AT SEA,...,0.0,4.36,0.0,0.0,15.32,0.0,0.0,4.36,0.0,12:00:00
2023-01-02,WVEY,b848b9c5-af76-46ad-beaf-69f341ba71fd,WEC VAN EYCK,9365984.0,EI251A,03/01/2023 00:00,2023-01-02 23:30:00,UTC +01:00,EOSP,AT SEA,...,0.0,0.00,0.0,0.0,13.07,0.0,0.0,0.00,0.0,23:30:00
2023-01-03,WVEY,40e7b2cb-b492-4015-a0cd-b483c66d5a94,WEC VAN EYCK,9365984.0,NaN,03/01/2023 00:00,2023-01-03 01:05:00,UTC +01:00,SND,NaN,...,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,01:05:00
2023-01-03,WVEY,63ef18b3-6cc3-4ae7-b631-3576b4d06073,WEC VAN EYCK,9365984.0,NaN,03/01/2023 00:00,2023-01-03 01:05:00,UTC +01:00,SND,NaN,...,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,01:05:00

In [8]:
Res_df = Res_df.sort_values(by='REPORT_DATE_TIME')

In [9]:
start_date = '2023-05-31'
end_date = '2023-07-01'
start_date = pd.to_datetime(start_date, format='%Y-%m-%d')
end_date = pd.to_datetime(end_date, format='%Y-%m-%d')

filtered_df = Res_df[(Res_df['REPORT_DATE_TIME'] >= start_date) & (Res_df['REPORT_DATE_TIME'] <= end_date)]

In [10]:
filtered_df.head()

,idvessel,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,...,FUEL_Dstlt_VLS,FUEL_Dstlt_ULS,FUEL_Tnktnr_Dstlt_VLS,Rsdl_HS,Rsdl_VLS,Rsdl_ULS,Dstlt_VLS,Dstlt_ULS,Tnktnr_Dstlt_VLS,Time
Date,,,,,,,,,,,,,,,,,,,,,
2023-05-31,WVEY,39ef6f12-4eeb-49f1-99a5-97c18a48d4e9,WEC VAN EYCK,9365984.0,EI322A,31/05/2023 00:00,2023-05-31 06:00:00,UTC +02:00,EOSP,AT SEA,...,0.0,6.26,0.0,0.0,0.0,0.0,0.0,6.26,0.0,06:00:00
2023-05-31,WVEY,3642a685-91b8-480a-873f-b449b1b586bc,WEC VAN EYCK,9365984.0,NaN,31/05/2023 00:00,2023-05-31 11:47:00,UTC +02:00,SND,NaN,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,11:47:00
2023-05-31,WVEY,851e211d-295c-4334-b70b-f759302b32c3,WEC VAN EYCK,9365984.0,NaN,31/05/2023 00:00,2023-05-31 11:47:00,UTC +02:00,SND,NaN,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,11:47:00
2023-05-31,WVEY,b69f71a1-3bef-4652-834f-35b30757cc8b,WEC VAN EYCK,9365984.0,NaN,31/05/2023 00:00,2023-05-31 11:47:00,UTC +02:00,SND,NaN,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,11:47:00
2023-05-31,WVEY,cd83c900-5879-4268-99be-054ce1e49c8e,WEC VAN EYCK,9365984.0,NaN,31/05/2023 00:00,2023-05-31 11:47:00,UTC +02:00,SND,NaN,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,11:47:00

In [11]:
pd.set_option('display.max_columns', None)  
filtered_df.tail()

,idvessel,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,LAT,LONG_,LATITUDE,LONGITUDE,M_E_FOC,CARGO_TOTAL,Has_Cargo,TOTAL_STEAMING_TIME,M_E_Fuel_Only_Steaming_Time,MILES_BY_GPS,OIL_CYL,SOW,SOG,RPM,SLIP,WIND_DIRECTION,WIND_SPEED,DRAFT_AFT,DRAFT_FWD,DISPLACEMENT,COURSE_AT_SEA,WAVE_HEIGHT,SEA_DIRECTION,CARGO_TOTAL_TEU,AMBIENT_TEMP,SW_TEMP,MILES_BY_SPEED_LOG,ETA_PORT_CODE,ETA_DATE_TIME,ETA_DATE_TIME_Offset,ETA_PORT,TIME_CHANGE,TIME_SEA,TEMP_MIN,TEMP_MAX,REQUESTED_SPEED,REM_DIST_TO_PILOT,REM_TIME_TO_PILOT,TOTAL_UNPLND_STPGE_TECH,TOTAL_UNPLND_STPGE_OPE_WX,REEFERS_POSITIVE_PLUGGED,REEFERS_NEGATIVE_PLUGGED,ME_TOTAL_REVS_COUNTER,PORT_CODE,PORT,AUX_BLOWERS_ON,HOLD_VENTILATION_ON,SINCE_DATE_TIME,SINCE_DATE_TIME_Offset,TIME_HRS_ANCHOR,TIME_HRS_DRIFT,REASON,TYPE_OF_DELAY,ETB_DATE_TIME,ETB_DATE_TIME_Offset,PILOT_DATE_TIME,PILOT_DATE_TIME_Offset,TIME_MANOEUVRING,TUG_ARR,TUG_SHIFT,ETD_DATE_TIME,ETD_DATE_TIME_Offset,SHIFT_BERTH_HOURS,CARGO_LOAD,CARGO_DISCH,TEU_FULL,TEU_EMPTY,BILGE_REMOVED,GARBAGE_REMOVED,GARBAGE_REMVL_REQSTD,GARBAGE_REMVL_CMPLSRY,FW_SUPPLY,CY_CREW_SIGNED_ON,CY_CREW_SIGNED_OFF,CY_DOCTORS_VISIT,CY_MAIL_RECEIVED_Ref_NO,CY_LUB_OIL_SAMPLE_LANDED,CY_CHECKD_FOR_STOWAWAYS,CY_STOWAWAYS_ON_BOARD,CY_DEP_GM_Mtr,CY_REQUISITIONS_RECEIVED,DISTANCE_TO_NEXT_PILOT,TUG_SAILING_TRANSIT,STEAMING_TIME_M_E_Rsdl_VLS,STEAMING_TIME_M_E_Rsdl_HS,STEAMING_TIME_M_E_Rsdl_ULS,STEAMING_TIME_M_E_Dstlt_VLS,STEAMING_TIME_M_E_Dstlt_ULS,STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS,STEAMING_TIME_M_E_HS,STEAMING_TIME_M_E_LS,STEAMING_TIME_M_E_MDO,STEAMING_TIME_M_E_MGO,STEAMING_TIME_M_E_MGO_LS,STEAMING_TIME_AUX_1,STEAMING_TIME_AUX_2,STEAMING_TIME_AUX_3,STEAMING_TIME_AUX_4,STEAMING_TIME_AUX_5,STEAMING_TIME_SH_GEN,STEAMING_TIME_TG,POWER_kW,STEAMING_LOAD_KW_AUX_1,STEAMING_LOAD_KW_AUX_2,STEAMING_LOAD_KW_AUX_3,STEAMING_LOAD_KW_AUX_4,STEAMING_LOAD_KW_AUX_5,STEAMING_LOAD_KW_SH_GEN,STEAMING_LOAD_KW_TG,FUEL_M_E_Rsdl_VLS,FUEL_M_E_Rsdl_HS,FUEL_M_E_Rsdl_ULS,FUEL_M_E_Dstlt_VLS,FUEL_M_E_Dstlt_ULS,FUEL_M_E_Tnktnr_Dstlt_VLS,FUEL_M_E_HS,FUEL_M_E_LS,FUEL_M_E_MDO,FUEL_M_E_MGO,FUEL_M_E_MGO_LS,FUEL_Aux_Rsdl_VLS,FUEL_Aux_Rsdl_HS,FUEL_Aux_Rsdl_ULS,FUEL_Aux_Dstlt_VLS,FUEL_Aux_Dstlt_ULS,FUEL_Aux_Tnktnr_Dstlt_VLS,FUEL_AUX_HS,FUEL_AUX_LS,FUEL_AUX_MDO,FUEL_AUX_MGO,FUEL_AUX_MGO_LS,FUEL_Boiler_Rsdl_VLS,FUEL_Boiler_Rsdl_HS,FUEL_Boiler_Rsdl_ULS,FUEL_Boiler_Dstlt_VLS,FUEL_Boiler_Dstlt_ULS,FUEL_Boiler_Tnktnr_Dstlt_VLS,FUEL_BOILER_HS,FUEL_BOILER_LS,FUEL_BOILER_MDO,FUEL_BOILER_MGO,FUEL_BOILER_MGO_LS,DECK_LAST_CHANGE_USER,ENGINE_LAST_CHANGE_USER,DECK_PART_IS_COMPLETE,ENGINE_PART_IS_COMPLETE,SCAVENGE_PRESSURE,SECA_ENTRY_TIME,SECA_ENTRY_LAT,SECA_ENTRY_LONG,SECA_EXIT_TIME,SECA_EXIT_LAT,SECA_EXIT_LONG,ROB_FRESH_WATER,MANVRNG_MILES_BY_GPS,MANVRNG_MILES_BY_SPEED_LOG,TANKTAINER_TRANSFD_QUANTITY,PILOT_TAKEN,DATE_TIME_START_TRANSIT,DATE_TIME_START_TRANSIT_Offset,DATE_TIME_END_TRANSIT,DATE_TIME_END_TRANSIT_Offset,BALLAST,TANKTAINER_NUMBER,STEAMING_KWHR_TOTAL,CY_OTHERS,ROB_FO_SLUDGE,ROB_LO_SLUDGE,ROB_BILGE,SLUDGE_REMOVED_FO,SLUDGE_REMOVED_LO,SEA_STATE,CY_LUB_ADDED_TO_SYSTEM_MECC,CY_LUB_ADDED_TO_SYSTEM_AECC,CY_LUB_ADDED_TO_THRUSTERS,CY_ME_LO_PURIFIER_IN_USE,CY_BALLAST,CY_BENDING_MOMENT,CY_SHEARING_FORCE,CY_TORTION_MOMENT,CY_SUPDT_AUDITOR_SIGNED_ON,CY_SUPDT_AUDITOR_SIGNED_OFF,CY_CASH_RECEIVED,CY_LUB_OIL_RECEIVED_MECYL,CY_LUB_OIL_RECEIVED_MECC,CY_LUB_OIL_RECEIVED_AECC,CY_M_E_UNDER_PISTON_TEMP,CY_MAIL_RECEIVED,WIND_DIRECTION_PORT_STBD,SEA_DIRECTION_PORT_STBD,TIME_PILOT_ONBOARD,GRADES_ROB,SO2_CO2_RATIO,Bunker_Order,Remarks,Fuel_Type,Carbon_Factor,Sulphur_Content_PC,Quantity,Port_Delivery,Product_Quality,Tanktainer_Number_1,Supplier,Delivery,Vol_Lt,Den,Vis,ROB_Dstlt_ULS,ROB_Dstlt_VLS,ROB_Rsdl_MDO,ROB_Tnktnr_Dstlt_VLS,ROB_Rsdl_VLS,ROB_Rsdl_HS,ROB_Rsdl_ULS,ROB_Fuel_HSFO,ROB_Fuel_LSFO,ROB_Fuel_MDO,ROB_Fuel_MGO,ROB_Fuel_MGO_LS,ROB_Fuel_Tanktainer_MGO,ECA_MILES,ECA_TIME,EGCS_DRY_WASTE_REMOVED,EGCS_RUNNING_TIME,EGCS_WET_SLURRY_REMOVED,EGCS_OPEN_LOOP_RUNNING_TIME,EGCS_CLOSED_LOOP_RUNNING_TIME,Voyage_Order,Voyage_Code,ECA,EU,Sea_Time,ETA_Country_Code,Port_Country_Code,check_ETA_code,check_Port_code,Status_TEMP_EU,FUEL_HS,FUEL_LS,FUEL_MDO,FUEL_MGO,FUEL_MGO_LS,Cargo_Transport_Work,TEU_Transport_Work,EEOI_Voyage_no,CARGO_TOTAL_Old,DRAFT,FO_per_24Hrs,SFOC,CY_OIL_gm_hr,SCOC,Voyage_Name,TOTAL_FO,TOTAL_CO2,EEOI,voyCondition,samedate,timesincelastreport,BDN,Wind_direction_360,True_wind_speed,True_wind_dir,ref_power,ref_fuel,fuel_loss,Relative_wind_speed,Relative_wind_direction,CAA,RW,Corrected_Power,draft_pow,draft_sp_pow,fo_nor,fo_model,sfoc_model,sfoc_deviation,ref_power_corrected,ref_FO_corrected,Propulsive_eff,speed_performance,Ref_speed,P_I,MEcon,AEcon,BLcon,Tcon,HS,LS,MDO,MGO,MGOLS,TCO2,AETsteaming,AEPOWER,TRIM,DISTANCECOVERED,updated_date,hyd_slip_sog,hyd_slip_stw,FUEL_Rsdl_HS,FUEL_Rsdl_VLS,FUEL_Rsdl_ULS,FUEL_Dstlt_VLS,FUEL_Dstlt_ULS,FUEL_Tnktnr_Dstlt_VLS,Rsdl_HS,Rsdl_VLS,Rsdl_ULS,Dstlt_VLS,Dstlt_ULS,Tnktnr_Dstlt_VLS,Time
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023-06-30,WVEY,c24cb185-7453-4cde-9952-7ca70d7887d6,WEC VAN EYCK,9365984.0,NaN,01/07/2023 00:00,2023-06-30 15:53:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,3211.9,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,231.0,10.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,424.0,ESBIO-GBTHP,N,Y,0.0,GB,ES,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,424.0,0.0,0.0,0.00,0.000,0.0,0.0,0.0,0.00,0.00000,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,13/07/2023 12:02,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,15:53:00
2023-06-30,WVEY,cb561ba5-33d1-488d-9340-7ea267994232,WEC VAN EYCK,9365984.0,NaN,01/07/2023 00:00,2023-06-30 15:53:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,3211.9,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,231.0,10.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,424.0,ESBIO-GBTHP,N,Y,0.0,GB,ES,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,424.0,0.0,0.0,0.00,0.000,0.0,0.0,0.0,0.00,0.00000,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,13/07/2023 12:02,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,15:53:00
2023-06-30,WVEY,cb7c64b9-001d-489f-b201-f4569ec8cf46,WEC VAN EYCK,9365984.0,NaN,01/07/2023 00:00,2023-06-30 15:53:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,3211.9,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,231.0,10.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,424.0,ESBIO-GBTHP,N,Y,0.0,GB,ES,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,424.0,0.0,0.0,0.00,0.000,0.0,0.0,0.0,0.00,0.00000,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,13/07/2023 12:02,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,15:53:00
2023-06-30,WVEY,57c8f918-a1a3-46c5-81dc-6f0240bdcd4d,WEC VAN EYCK,9365984.0,EI326A,01/07/2023 00:00,2023-06-30 15:54:00,UTC +02:00,SAIL,IN PORT,5007N,00100W,50.116667,-1.000000,0.00,1459.1,True,3.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.4,4.8,8752.0,0.0,0.00,0.0,256.0,20.0,15.0,NaN,NLMOE,01/07/2023 01:15,UTC +02:00,MOERDIJK,NaN,3.9,70.0,70.0,11.8,NaN,NaN,0.0,0.0,4.0,0.0,0.0,GBTHP,THAMESPORT,False,False,NaN,NaN,NaN,NaN,Port Contamination,NaN,30/06/2023 05:30,UTC +02:00,NaN,NaN,NaN,NaN,0.0,30/06/2023 16:00,UTC +02:00,NaN,510.6,2263.4,73.0,183.0,0.0,NaN,False,False,0.0,0.0,0.0,No,0.0,0.0,Yes,0.0,2.89,0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,250.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.20,0.0,0.0,0.0,0.0,0.0,0.20,0.0,0.0,0.0,0.0,0.11,0.0,0.0,0.0,0.0,0.0,0.11,2O,CE,TRUE,TRUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.0,0.0,NaN,0.0,FALSE,NaN,NaN,NaN,NaN,2265.0,0.0,975.0,NaN,NaN,NaN,0.1,NaN,NaN,0.0,0.0,0.0,0.0,1.0,NaN,95.0,96.0,38.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,102.17,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,425.0,GBTHP-NLMOE,N,Y,0.0,NL,GB,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.31,0.0,0.0,424.0,0.0,5.1,0.00,0.000,0.0,0.0,0.0,0.31,0.99386,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.20,0.11,0.31,0.0,0.0,0.0,0.0,0.31,0.99,3.9,250.0,0.6,0.0,21/07/2023 18:37,NaN,NaN,0.0,0.0,0.0,0.0,0.31,0.0,0.0,0.0,0.0,0.0,0.31,0.0,15:54:00
2023-06-30,WVEY,54da040b-f017-43c9-bf9c-e703f174aafa,WEC VAN EYCK,9365984.0,EI326A,01/07/2023 00:00,2023-06-30 18:54:00,UTC +02:00,COSP,DRIFTING,5126N,00129E,51.433333,1.483333,2.14,1459.1,True,3.0,3.0,31.8,0.0,0.0,0.0,0.0,0.0,80.0,15.0,5.4,4.8,8752.0,53.0,1.27,80.0,256.0,17.0,17.0,NaN,NLMOE,01/07/2023 01:15,UTC +02:00,MOERDIJK,NaN,3.0,340.0,358.0,15.5,NaN,NaN,0.0,0.0,4.0,0.0,90000.0,GBTHP,THAMESPORT,False,False,NaN,NaN,NaN,NaN,Port Contamination,NaN,30/06/2023 05:30,UTC +02:00,NaN,NaN,3.0,NaN,NaN,30/06/2023 16:00,UTC +02:00,NaN,NaN,NaN,73.0,183.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.6,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,3.0,0.0,0.0,0.0,3.0,0.0,3560.0,0.0,250.0,0.0,0.0,0.0,200.0,0.0,0.0,0.0,0.0,0.0,2.14,0.0,0.0,0.0,0.0,0.0,2.14,0.0,0.0,0.0,0.0,0.16,0.0,0.0,0.0,0.0,0.0,0.16,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,2O,CE,TRUE,TRUE,1.7,NaN,NaN,NaN,NaN,NaN,NaN,37.0,31.8,31.8,NaN,TRUE,NaN,NaN,NaN,NaN,2265.0,0.0,1350.0,NaN,NaN,NaN,0.1,NaN,NaN,4.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,S,S,2.96,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.87,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,99.87,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,425.0,GBTHP-NLMOE,N,Y,3.0,NL,GB,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2.30,46399.4,8140.8,425.0,0.0,5.1,17.12,200.375,0.0,0.0,0.0,2.30,7.37380,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.14,0.16,0.00,2.30,0.0,0.0,0.0,0.0,2.30,7.37,3.0,250.0,0.6,31.8,21/07/2023 18:37,NaN,NaN,0.0,0.0,0.0,0.0,2.30,0.0,0.0,0.0,0.0,0.0,2.30,0.0,18:54:00

In [12]:
filtered_df['Total_Calculated_MGO_LS'] = filtered_df[[ 'FUEL_AUX_MGO_LS', 'FUEL_BOILER_MGO_LS']].sum(axis=1)

filtered_df['Total_Calculated_ULS'] = filtered_df[[ 'FUEL_Aux_Dstlt_ULS', 'FUEL_Boiler_Dstlt_ULS']].sum(axis=1)

filtered_df['Total_Calculated_LS'] =  filtered_df[['FUEL_M_E_LS','FUEL_M_E_Rsdl_VLS']].sum(axis=1)

filtered_df['Total_fuel'] = filtered_df[['Total_Calculated_MGO_LS', 'Total_Calculated_ULS','Total_Calculated_LS']].sum(axis=1)

filtered_df['Total_BIO_Calculated'] = (filtered_df['Total_Calculated_MGO_LS'] * 2.417) + (filtered_df['Total_Calculated_ULS'] * 2.567)+ (filtered_df['Total_Calculated_LS']* 2.417)

In [13]:
dist = filtered_df['MILES_BY_GPS'].sum()
dist

7033.200000000001

In [14]:
dwt= 9587
filtered_df = filtered_df.assign(DWT=dwt)

In [15]:
TAFC= filtered_df['Total_BIO_Calculated'].sum() * 10**6
print(TAFC)

1154897620.0

# ATTAINED CII

In [17]:
ATT_CII = TAFC / (dist * dwt)
ATT_CII

17.128044852534806

# REFERENCE CII

In [21]:
'''

CII(REF)= A.CAPACITY^-C

PARAMETER FOR A AND C ARE

SHIP TYPE                           A            C         CAPACITY
TANKER                             5247         0.610       DWT
CONTAIER SHIP                      1984         0.489       DWT
BULK CARRIER: DWT >= 2,79,000      4745         0.622       2,79,00     
BULK CARRIER: DWT <= 2,79,00       4745         0.622       DWT
COMBINATION CARRIER                40853        0.812       DWT

'''

'\n\nCII(REF)= A.CAPACITY^-C\n\nPARAMETER FOR A AND C ARE\n\nSHIP TYPE                           A            C         CAPACITY\nTANKER                             5247         0.610       DWT\nCONTAIER SHIP                      1984         0.489       DWT\nBULK CARRIER: DWT >= 2,79,000      4745         0.622       2,79,00     \nBULK CARRIER: DWT <= 2,79,00       4745         0.622       DWT\nCOMBINATION CARRIER                40853        0.812       DWT\n\n'

In [22]:
#Parameters for reference cii
a = int(input("A:"))
c = float(input("C:"))
dwt= 9587

A:1984
C:0.489

In [23]:
CII_REF = a * (dwt ** (-c))
print(CII_REF)

22.4129392579026

In [24]:
# REQUIRED CII

In [25]:
'''
Required CII= CII(REF) * [(100-Z)/100]

REDUCATION FACTOR(Z%)
YEAR           REDUCTION FACTOR RELATIVE TO 2019
2019                   
2020                  1%
2021                  2%
2022                  3%
2023                  5%
2024                  7%
2025                  9%
2026                  11%

'''

'\nRequired CII= CII(REF) * [(100-Z)/100]\n\nREDUCATION FACTOR(Z%)\nYEAR           REDUCTION FACTOR RELATIVE TO 2019\n2019                   \n2020                  1%\n2021                  2%\n2022                  3%\n2023                  5%\n2024                  7%\n2025                  9%\n2026                  11%\n\n'

In [26]:
#Z-Reduction value
years = {
    2019: 0,
    2020: 1,
    2021: 2,
    2022: 3 ,
    2023: 5 ,
    2024: 7 ,
    2025: 9 ,
    2026: 11
}

a = int(input("Enter a year: "))    #ENTER THE CII YEAR
if a in years:
    Z = years[a]
    print(Z)
else:
    print("No Z value")

Enter a year: 2023
5

# REQUIRED CII

In [27]:
#Required CII 
CII_REQ = CII_REF * ((100 - Z) / 100)
print(CII_REQ)

21.29229229500747

# CII RATIO

In [29]:
#CII Ratio
CII_RATIO= ATT_CII/ CII_REQ
print(CII_RATIO)

0.8044246535423957

In [30]:
ships = {
    'BULK': {'D1': 0.86, 'D2': 0.94, 'D3': 1.06, 'D4': 1.18},
    'TANKER': {'D1': 0.82, 'D2': 0.93, 'D3': 1.08, 'D4': 1.28},
    'CONTAINER': {'D1': 0.83, 'D2': 0.94, 'D3': 1.07, 'D4': 1.19},
    'COMBINATION': {'D1': 0.87, 'D2': 0.96, 'D3': 1.06, 'D4': 1.14},
    'GENERAL CARGO SHIP': {'D1': 0.83, 'D2': 0.94, 'D3': 1.06, 'D4': 1.19},
}

def ratings(ship, cii_ratio):
    a = ships.get(ship)
    if a:
        if cii_ratio <= a['D1']:
            return 'A RATING'
        elif a['D1'] < cii_ratio <= a['D2']:
            return 'B RATING'
        elif a['D2'] < cii_ratio <= a['D3']:
            return 'C RATING'
        elif a['D3'] < cii_ratio <= a['D4']:
            return 'D RATING'
        else:
            return 'E RATING'
    else:
        return 'Data not founded'

ship = input("Enter the ship: ").strip().upper()  
CII_RATIO = CII_RATIO
rating = ratings(ship, CII_RATIO)
print(f'The rating is: {rating}')

Enter the ship: container
The rating is: A RATING

# Normal Fuel

In [32]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [33]:
data=pd.read_csv("NOONDATA_WEC VAN EYCK.csv")

In [34]:
data.head()

,idvessel,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,LAT,LONG_,LATITUDE,LONGITUDE,M_E_FOC,CARGO_TOTAL,Has_Cargo,TOTAL_STEAMING_TIME,M_E_Fuel_Only_Steaming_Time,MILES_BY_GPS,OIL_CYL,SOW,SOG,RPM,SLIP,WIND_DIRECTION,WIND_SPEED,DRAFT_AFT,DRAFT_FWD,DISPLACEMENT,COURSE_AT_SEA,WAVE_HEIGHT,SEA_DIRECTION,CARGO_TOTAL_TEU,AMBIENT_TEMP,SW_TEMP,MILES_BY_SPEED_LOG,ETA_PORT_CODE,ETA_DATE_TIME,ETA_DATE_TIME_Offset,ETA_PORT,TIME_CHANGE,TIME_SEA,TEMP_MIN,TEMP_MAX,REQUESTED_SPEED,REM_DIST_TO_PILOT,REM_TIME_TO_PILOT,TOTAL_UNPLND_STPGE_TECH,TOTAL_UNPLND_STPGE_OPE_WX,REEFERS_POSITIVE_PLUGGED,REEFERS_NEGATIVE_PLUGGED,ME_TOTAL_REVS_COUNTER,PORT_CODE,PORT,AUX_BLOWERS_ON,HOLD_VENTILATION_ON,SINCE_DATE_TIME,SINCE_DATE_TIME_Offset,TIME_HRS_ANCHOR,TIME_HRS_DRIFT,REASON,TYPE_OF_DELAY,ETB_DATE_TIME,ETB_DATE_TIME_Offset,PILOT_DATE_TIME,PILOT_DATE_TIME_Offset,TIME_MANOEUVRING,TUG_ARR,TUG_SHIFT,ETD_DATE_TIME,ETD_DATE_TIME_Offset,SHIFT_BERTH_HOURS,CARGO_LOAD,CARGO_DISCH,TEU_FULL,TEU_EMPTY,BILGE_REMOVED,GARBAGE_REMOVED,GARBAGE_REMVL_REQSTD,GARBAGE_REMVL_CMPLSRY,FW_SUPPLY,CY_CREW_SIGNED_ON,CY_CREW_SIGNED_OFF,CY_DOCTORS_VISIT,CY_MAIL_RECEIVED_Ref_NO,CY_LUB_OIL_SAMPLE_LANDED,CY_CHECKD_FOR_STOWAWAYS,CY_STOWAWAYS_ON_BOARD,CY_DEP_GM_Mtr,CY_REQUISITIONS_RECEIVED,DISTANCE_TO_NEXT_PILOT,TUG_SAILING_TRANSIT,STEAMING_TIME_M_E_Rsdl_VLS,STEAMING_TIME_M_E_Rsdl_HS,STEAMING_TIME_M_E_Rsdl_ULS,STEAMING_TIME_M_E_Dstlt_VLS,STEAMING_TIME_M_E_Dstlt_ULS,STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS,STEAMING_TIME_M_E_HS,STEAMING_TIME_M_E_LS,STEAMING_TIME_M_E_MDO,STEAMING_TIME_M_E_MGO,STEAMING_TIME_M_E_MGO_LS,STEAMING_TIME_AUX_1,STEAMING_TIME_AUX_2,STEAMING_TIME_AUX_3,STEAMING_TIME_AUX_4,STEAMING_TIME_AUX_5,STEAMING_TIME_SH_GEN,STEAMING_TIME_TG,POWER_kW,STEAMING_LOAD_KW_AUX_1,STEAMING_LOAD_KW_AUX_2,STEAMING_LOAD_KW_AUX_3,STEAMING_LOAD_KW_AUX_4,STEAMING_LOAD_KW_AUX_5,STEAMING_LOAD_KW_SH_GEN,STEAMING_LOAD_KW_TG,FUEL_M_E_Rsdl_VLS,FUEL_M_E_Rsdl_HS,FUEL_M_E_Rsdl_ULS,FUEL_M_E_Dstlt_VLS,FUEL_M_E_Dstlt_ULS,FUEL_M_E_Tnktnr_Dstlt_VLS,FUEL_M_E_HS,FUEL_M_E_LS,FUEL_M_E_MDO,FUEL_M_E_MGO,FUEL_M_E_MGO_LS,FUEL_Aux_Rsdl_VLS,FUEL_Aux_Rsdl_HS,FUEL_Aux_Rsdl_ULS,FUEL_Aux_Dstlt_VLS,FUEL_Aux_Dstlt_ULS,FUEL_Aux_Tnktnr_Dstlt_VLS,FUEL_AUX_HS,FUEL_AUX_LS,FUEL_AUX_MDO,FUEL_AUX_MGO,FUEL_AUX_MGO_LS,FUEL_Boiler_Rsdl_VLS,FUEL_Boiler_Rsdl_HS,FUEL_Boiler_Rsdl_ULS,FUEL_Boiler_Dstlt_VLS,FUEL_Boiler_Dstlt_ULS,FUEL_Boiler_Tnktnr_Dstlt_VLS,FUEL_BOILER_HS,FUEL_BOILER_LS,FUEL_BOILER_MDO,FUEL_BOILER_MGO,FUEL_BOILER_MGO_LS,DECK_LAST_CHANGE_USER,ENGINE_LAST_CHANGE_USER,DECK_PART_IS_COMPLETE,ENGINE_PART_IS_COMPLETE,SCAVENGE_PRESSURE,SECA_ENTRY_TIME,SECA_ENTRY_LAT,SECA_ENTRY_LONG,SECA_EXIT_TIME,SECA_EXIT_LAT,SECA_EXIT_LONG,ROB_FRESH_WATER,MANVRNG_MILES_BY_GPS,MANVRNG_MILES_BY_SPEED_LOG,TANKTAINER_TRANSFD_QUANTITY,PILOT_TAKEN,DATE_TIME_START_TRANSIT,DATE_TIME_START_TRANSIT_Offset,DATE_TIME_END_TRANSIT,DATE_TIME_END_TRANSIT_Offset,BALLAST,TANKTAINER_NUMBER,STEAMING_KWHR_TOTAL,CY_OTHERS,ROB_FO_SLUDGE,ROB_LO_SLUDGE,ROB_BILGE,SLUDGE_REMOVED_FO,SLUDGE_REMOVED_LO,SEA_STATE,CY_LUB_ADDED_TO_SYSTEM_MECC,CY_LUB_ADDED_TO_SYSTEM_AECC,CY_LUB_ADDED_TO_THRUSTERS,CY_ME_LO_PURIFIER_IN_USE,CY_BALLAST,CY_BENDING_MOMENT,CY_SHEARING_FORCE,CY_TORTION_MOMENT,CY_SUPDT_AUDITOR_SIGNED_ON,CY_SUPDT_AUDITOR_SIGNED_OFF,CY_CASH_RECEIVED,CY_LUB_OIL_RECEIVED_MECYL,CY_LUB_OIL_RECEIVED_MECC,CY_LUB_OIL_RECEIVED_AECC,CY_M_E_UNDER_PISTON_TEMP,CY_MAIL_RECEIVED,WIND_DIRECTION_PORT_STBD,SEA_DIRECTION_PORT_STBD,TIME_PILOT_ONBOARD,GRADES_ROB,SO2_CO2_RATIO,Bunker_Order,Remarks,Fuel_Type,Carbon_Factor,Sulphur_Content_PC,Quantity,Port_Delivery,Product_Quality,Tanktainer_Number_1,Supplier,Delivery,Vol_Lt,Den,Vis,ROB_Dstlt_ULS,ROB_Dstlt_VLS,ROB_Rsdl_MDO,ROB_Tnktnr_Dstlt_VLS,ROB_Rsdl_VLS,ROB_Rsdl_HS,ROB_Rsdl_ULS,ROB_Fuel_HSFO,ROB_Fuel_LSFO,ROB_Fuel_MDO,ROB_Fuel_MGO,ROB_Fuel_MGO_LS,ROB_Fuel_Tanktainer_MGO,ECA_MILES,ECA_TIME,EGCS_DRY_WASTE_REMOVED,EGCS_RUNNING_TIME,EGCS_WET_SLURRY_REMOVED,EGCS_OPEN_LOOP_RUNNING_TIME,EGCS_CLOSED_LOOP_RUNNING_TIME,Voyage_Order,Voyage_Code,ECA,EU,Sea_Time,ETA_Country_Code,Port_Country_Code,check_ETA_code,check_Port_code,Status_TEMP_EU,FUEL_HS,FUEL_LS,FUEL_MDO,FUEL_MGO,FUEL_MGO_LS,Cargo_Transport_Work,TEU_Transport_Work,EEOI_Voyage_no,CARGO_TOTAL_Old,DRAFT,FO_per_24Hrs,SFOC,CY_OIL_gm_hr,SCOC,Voyage_Name,TOTAL_FO,TOTAL_CO2,EEOI,voyCondition,samedate,timesincelastreport,BDN,Wind_direction_360,True_wind_speed,True_wind_dir,ref_power,ref_fuel,fuel_loss,Relative_wind_speed,Relative_wind_direction,CAA,RW,Corrected_Power,draft_pow,draft_sp_pow,fo_nor,fo_model,sfoc_model,sfoc_deviation,ref_power_corrected,ref_FO_corrected,Propulsive_eff,speed_performance,Ref_speed,P_I,MEcon,AEcon,BLcon,Tcon,HS,LS,MDO,MGO,MGOLS,TCO2,AETsteaming,AEPOWER,TRIM,DISTANCECOVERED,updated_date,hyd_slip_sog,hyd_slip_stw,FUEL_Rsdl_HS,FUEL_Rsdl_VLS,FUEL_Rsdl_ULS,FUEL_Dstlt_VLS,FUEL_Dstlt_ULS,FUEL_Tnktnr_Dstlt_VLS,Rsdl_HS,Rsdl_VLS,Rsdl_ULS,Dstlt_VLS,Dstlt_ULS,Tnktnr_Dstlt_VLS
0,WVEY,4deec51e-9ff0-4a2c-a57d-bc003f3cfdaf,WEC VAN EYCK,9365984.0,EK046A,12/11/2020 00:00,12/11/2020 00:54,UTC +00:00,SAIL,IN PORT,NaN,NaN,NaN,NaN,0.00,4101.0,True,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.5,5.35,10737.0,0.0,0.00,0.00,415.0,NaN,NaN,NaN,PTLEI,44147.66667,UTC +00:00,LEIXOES,NaN,100.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,PTSET,SETUBAL,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,3620.0,2353.0,335.0,80.0,0.0,NaN,False,False,0.0,0.0,0.0,No,0.0,0.0,Yes,No,1.94,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,237.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.07,0.0,0.0,0.0,0.0,0.0,1.07,0.0,0.0,0.0,0.0,0.6,0.0,0.0,0.0,0.0,0.0,0.6,NaN,NaN,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.0,0.0,NaN,0.0,FALSE,NaN,NaN,NaN,NaN,1473.0,NaN,0.0,NaN,NaN,NaN,2.5,NaN,NaN,NaN,0.0,0.0,0.0,1.0,NaN,71.0,63.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,False,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.39,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0,0.0,0.0,111.39,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.0,PTSET-PTLEI,N,Y,0.0,PT,PT,NaN,NaN,0.0,0.0,0.00,0.0,0.0,1.67,0.0,0.0,100.0,0.0,5.925,0.00000,0.000,0.0,0.0,0.0,1.67,5.35402,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,1.07,0.6,1.67,0.0,0.00,0.0,0.0,1.67,5.35,12.9,237.0,1.15,0.0,24/03/2022 08:44,NaN,NaN,0.0,0.00,0.0,0.0,1.67,0.0,0.0,0.00,0.0,0.0,1.67,0.0
1,WVEY,d5bcff04-5965-4ed7-958e-18f49f9a9b88,WEC VAN EYCK,9365984.0,EK046A,12/11/2020 00:00,12/11/2020 01:48,UTC +00:00,COSP,DRIFTING,3826N,00859W,38.433333,-8.983333,0.52,4101.0,True,NaN,NaN,7.4,0.0,0.0,0.0,0.0,0.0,20.0,5.0,6.5,5.35,10737.0,218.0,0.14,20.00,415.0,17.0,13.0,NaN,PTLEI,12/11/2020,UTC +00:00,LEIXOES,NaN,0.9,NaN,NaN,15.5,NaN,NaN,0.0,0.0,0.0,0.0,0.0,PTSET,SETUBAL,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335.0,80.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201.5,0.0,0.9,0.0,0.0,0.0,0.0,0.0,0.0,0.9,0.0,0.0,0.0,0.9,0.0,0.0,0.0,0.0,0.0,0.0,2900.0,345.0,0.0,0.0,0.0,0.0,0.0,0.0,0.52,0.0,0.0,0.0,0.0,0.0,0.0,0.52,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.12,0.0,0.0,0.0,0.0,0.0,0.12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,True,True,1.8,NaN,NaN,NaN,NaN,NaN,NaN,105.0,7.4,7.4,NaN,TRUE,NaN,NaN,NaN,NaN,1473.0,NaN,311.0,NaN,NaN,NaN,2.5,NaN,NaN,2.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,0.8,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.27,0.0,0.0,0.0,274.07,0.0,0.0,0.0,274.07,0.0,0.0,111.27,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.0,PTSET-PTLEI,N,Y,0.9,PT,PT,NaN,NaN,0.0,0.0,0.52,0.0,0.0,0.12,30347.4,3071.0,101.0,0.0,5.925,13.86670,199.234,0.0,0.0,0.0,0.64,2.00400,0.0,Laden,0.0,NaN,NO,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.52,0.12,0.0,0.64,0.0,0.52,0.0,0.0,0.12,2.00,0.9,345.0,1.15,7.4,24/03/2022 08:43,NaN,NaN,0.0,0.52,0.0,0.0,0.12,0.0,0.0,0.52,0.0,0.0,0.12,0.0
2,WVEY,ad1e4d16-b5ef-4a13-b990-a96affeeec9c,WEC VAN EYCK,9365984.0,EK046A,12/11/2020 00:00,12/11/2020 12:00,UTC +00:00,NOON,AT SEA,4023N,00913W,40.383333,-9.216667,9.81,4101.0,True,NaN,NaN,151.3,0.0,0.0,0.0,0.0,0.0,30.0,8.0,6.5,5.35,10737.0,25.0,0.44,153.16,415.0,17.0,13.0,151.3,PTLEI,12/11/2020,UTC +00:00,LEIXOES,NaN,10.2,358.0,373.0,15.0,50.4,4.0,0.0,0.0,0.0,0.0,0.0,PTSET,SETUBAL,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335.0,80.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.2,0.0,0.0,0.0,0.0,0.0,0.0,10.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.2,0.0,4850.0,0.0,0.0,0.0,0.0,0.0,225.0,0.0,9.81,0.0,0.0,0.0,0.0,0.0,0.0,9.81,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,True,True,2.6,NaN,NaN,NaN,NaN,NaN,NaN,104.0,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,1473.0,NaN,0.0,NaN,NaN,NaN,2.5,NaN,NaN,2.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,264.26,0.0,0.0,0.0,264.26,0.0,0.0,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.0,PTSET-PTLEI,N,Y,10.2,PT,PT,NaN,NaN,0.0,0.0,9.81,0.0,0.0,0.00,620481.0,62789.5,101.0,0.0,5.925,23.08240,198.302,0.0,0.0,0.0,9.81,30.54830,0.0,Laden,0.0,NaN,NO,30.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.81,0.00,0.0,9.81,0.0,9.81,0.0,0.0,0.00,30.55,0.0,0.0,1.15,151.3,24/03/2022 08:44,NaN,NaN,0.0,9.81,0.0,0.0,0.00,0.0,0.0,9.81,0.0,0.0,0.00,0.0
3,WVEY,aa6db1ea-7bbc-41f2-9986-fa5f4c24a3dd,WEC VAN EYCK,9365984.0,EK046A,13/11/2020 00:00,12/11/2020 15:30,UTC +00:00,EOSP,AT SEA,4106N,00847W,41.100000,-8.783333,2.68,4101.0,True,NaN,NaN,47.1,0.0,0.0,0.0,154.0,0.0,30.0,8.0,6.5,5.35,10737.0,25.0,0.33,148.51,415.0,20.0,13.0,47.1,NaN,44147.66667,UTC +00:00,NaN,NaN,3.5,312.0,337.0,15.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,PTLEI,LEIXOES,False,False,NaN,NaN,NaN,NaN,NaN,NaN,44147.85,UTC +00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335.0,80.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.5,0.0,0.0,0.0,0.0,0.0,0.0,3.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5,0.0,3850.0,0.0,0.0,0.0,0.0,0.0,225.0,0.0,2.68,0.0,0.0,0.0,0.0,0.0,0.0,2.68,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,True,True,0.8,NaN,NaN,NaN,NaN,NaN,NaN,104.0,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,1473.0,NaN,0.0,NaN,NaN,NaN,2.5,NaN,NaN,2.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,261.58,0.0,0.0,0.0,261.58,0.0,0.0,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.0,PTSET-PTLEI,N,Y,3.5,PT,PT,NaN,NaN,0.0,0.0,2.68,0.0,0.0,0.00,193157.0,19546.5,101.0,0.0,5.925,18.37710,198.887,0.0,0.0,0.0,2.68,8.34552,0.0,Laden,0.0,NaN,NO,330.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.68,0.00,0.0,2.68,0.0,2.68,0.0,0.0,0.00,8.35,0.0,0.0,1.15,47.1,24/03/2022 08:43,NaN,NaN,0.0,2.68,0.0,0.0,0.00,0.0,0.0,2.68,0.0,0.0,0.00,0.0
4,WVEY,c1584f05-d139-403a-b77a-18ee7147765a,WEC VAN EYCK,9365984.0,EK046A,13/11/2020 00:00,12/11/2020 20:24,UTC +00:00,BRTH,DRIFTING,4106N,00847W,41.100000,-8.783333,1.83,4101.0,True,NaN,NaN,21.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.5,5.35,10737.0,0.0,0.00,0.00,415.0,20.0,13.0,NaN,NaN,12/11/2020,UTC +00:00,NaN,NaN,4.9,312.0,337.0,15.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,PTLEI,LEIXOES,False,False,NaN,NaN,NaN,NaN,NaN,NaN,12/11/2020,UTC +00:00,44147.79167,UTC +00:00,4.9,0.0,0.0,13/11/2020,UTC +00:00,NaN,NaN,NaN,335.0,80.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.9,0.0,0.0,0.0,0.0,0.0,0.0,4.9,0.0,0.0,0.0,1.5,0.0,0.0,0.0,0.0,3.4,0.0,1900.0,240.0,0.0,0.0,0.0,0.0,225.0,0.0,1.83,0.0,0.0,0.0,0.0,0.0,0.0,1.83,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.12,0.0,0.0,0.0,0.0,0.0,0.12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.0,21.1,21.1,NaN,FALSE,NaN,NaN,NaN,NaN,1473.0,NaN,1125.0,NaN,NaN,NaN,2.0,NaN,NaN,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.15,0.0,0.0,0.0,259.75,0.0,0.0,0.0,259.75,0.0,0.0,111.15,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.0,PTSET-PTLEI,N,Y,4.9,PT,PT,NaN,NaN,0.0,0.0,1.83,0.0,0.0,0.12,86531.1,8756.5,101.0,0.0,5.925,8.96327,196.563,0.0,0.0,0.0,1.95,6.08334,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.83,0.12,0.0,1.95,0.0,1.83,0.0,0.0,0.12,6.08,1.5,240.0,1.15,21.1,24/03/2022 08:43,NaN,NaN,0.0,1.83,0.0,0.0,0.12,0.0,0.0,1.83,0.0,0.0,0.12,0.0

In [35]:
df=data.copy()

In [36]:
df['REPORT_DATE_TIME'] = pd.to_datetime(df['REPORT_DATE_TIME'], format='%d/%m/%Y %H:%M', errors='coerce')

# Extract the date and time components
df['Date'] = df['REPORT_DATE_TIME'].dt.date
df['Time'] = df['REPORT_DATE_TIME'].dt.time

# Convert the 'Date' column to datetime
df['Date'] = pd.to_datetime(df['Date'])

# Filter for the year 2021
cii_year = 2023
Res_dfn = df[df['Date'].dt.year == cii_year]
Res_dfn.set_index('Date', inplace=True)

In [37]:
Res_dfn.head()

,idvessel,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,LAT,LONG_,LATITUDE,LONGITUDE,M_E_FOC,CARGO_TOTAL,Has_Cargo,TOTAL_STEAMING_TIME,M_E_Fuel_Only_Steaming_Time,MILES_BY_GPS,OIL_CYL,SOW,SOG,RPM,SLIP,WIND_DIRECTION,WIND_SPEED,DRAFT_AFT,DRAFT_FWD,DISPLACEMENT,COURSE_AT_SEA,WAVE_HEIGHT,SEA_DIRECTION,CARGO_TOTAL_TEU,AMBIENT_TEMP,SW_TEMP,MILES_BY_SPEED_LOG,ETA_PORT_CODE,ETA_DATE_TIME,ETA_DATE_TIME_Offset,ETA_PORT,TIME_CHANGE,TIME_SEA,TEMP_MIN,TEMP_MAX,REQUESTED_SPEED,REM_DIST_TO_PILOT,REM_TIME_TO_PILOT,TOTAL_UNPLND_STPGE_TECH,TOTAL_UNPLND_STPGE_OPE_WX,REEFERS_POSITIVE_PLUGGED,REEFERS_NEGATIVE_PLUGGED,ME_TOTAL_REVS_COUNTER,PORT_CODE,PORT,AUX_BLOWERS_ON,HOLD_VENTILATION_ON,SINCE_DATE_TIME,SINCE_DATE_TIME_Offset,TIME_HRS_ANCHOR,TIME_HRS_DRIFT,REASON,TYPE_OF_DELAY,ETB_DATE_TIME,ETB_DATE_TIME_Offset,PILOT_DATE_TIME,PILOT_DATE_TIME_Offset,TIME_MANOEUVRING,TUG_ARR,TUG_SHIFT,ETD_DATE_TIME,ETD_DATE_TIME_Offset,SHIFT_BERTH_HOURS,CARGO_LOAD,CARGO_DISCH,TEU_FULL,TEU_EMPTY,BILGE_REMOVED,GARBAGE_REMOVED,GARBAGE_REMVL_REQSTD,GARBAGE_REMVL_CMPLSRY,FW_SUPPLY,CY_CREW_SIGNED_ON,CY_CREW_SIGNED_OFF,CY_DOCTORS_VISIT,CY_MAIL_RECEIVED_Ref_NO,CY_LUB_OIL_SAMPLE_LANDED,CY_CHECKD_FOR_STOWAWAYS,CY_STOWAWAYS_ON_BOARD,CY_DEP_GM_Mtr,CY_REQUISITIONS_RECEIVED,DISTANCE_TO_NEXT_PILOT,TUG_SAILING_TRANSIT,STEAMING_TIME_M_E_Rsdl_VLS,STEAMING_TIME_M_E_Rsdl_HS,STEAMING_TIME_M_E_Rsdl_ULS,STEAMING_TIME_M_E_Dstlt_VLS,STEAMING_TIME_M_E_Dstlt_ULS,STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS,STEAMING_TIME_M_E_HS,STEAMING_TIME_M_E_LS,STEAMING_TIME_M_E_MDO,STEAMING_TIME_M_E_MGO,STEAMING_TIME_M_E_MGO_LS,STEAMING_TIME_AUX_1,STEAMING_TIME_AUX_2,STEAMING_TIME_AUX_3,STEAMING_TIME_AUX_4,STEAMING_TIME_AUX_5,STEAMING_TIME_SH_GEN,STEAMING_TIME_TG,POWER_kW,STEAMING_LOAD_KW_AUX_1,STEAMING_LOAD_KW_AUX_2,STEAMING_LOAD_KW_AUX_3,STEAMING_LOAD_KW_AUX_4,STEAMING_LOAD_KW_AUX_5,STEAMING_LOAD_KW_SH_GEN,STEAMING_LOAD_KW_TG,FUEL_M_E_Rsdl_VLS,FUEL_M_E_Rsdl_HS,FUEL_M_E_Rsdl_ULS,FUEL_M_E_Dstlt_VLS,FUEL_M_E_Dstlt_ULS,FUEL_M_E_Tnktnr_Dstlt_VLS,FUEL_M_E_HS,FUEL_M_E_LS,FUEL_M_E_MDO,FUEL_M_E_MGO,FUEL_M_E_MGO_LS,FUEL_Aux_Rsdl_VLS,FUEL_Aux_Rsdl_HS,FUEL_Aux_Rsdl_ULS,FUEL_Aux_Dstlt_VLS,FUEL_Aux_Dstlt_ULS,FUEL_Aux_Tnktnr_Dstlt_VLS,FUEL_AUX_HS,FUEL_AUX_LS,FUEL_AUX_MDO,FUEL_AUX_MGO,FUEL_AUX_MGO_LS,FUEL_Boiler_Rsdl_VLS,FUEL_Boiler_Rsdl_HS,FUEL_Boiler_Rsdl_ULS,FUEL_Boiler_Dstlt_VLS,FUEL_Boiler_Dstlt_ULS,FUEL_Boiler_Tnktnr_Dstlt_VLS,FUEL_BOILER_HS,FUEL_BOILER_LS,FUEL_BOILER_MDO,FUEL_BOILER_MGO,FUEL_BOILER_MGO_LS,DECK_LAST_CHANGE_USER,ENGINE_LAST_CHANGE_USER,DECK_PART_IS_COMPLETE,ENGINE_PART_IS_COMPLETE,SCAVENGE_PRESSURE,SECA_ENTRY_TIME,SECA_ENTRY_LAT,SECA_ENTRY_LONG,SECA_EXIT_TIME,SECA_EXIT_LAT,SECA_EXIT_LONG,ROB_FRESH_WATER,MANVRNG_MILES_BY_GPS,MANVRNG_MILES_BY_SPEED_LOG,TANKTAINER_TRANSFD_QUANTITY,PILOT_TAKEN,DATE_TIME_START_TRANSIT,DATE_TIME_START_TRANSIT_Offset,DATE_TIME_END_TRANSIT,DATE_TIME_END_TRANSIT_Offset,BALLAST,TANKTAINER_NUMBER,STEAMING_KWHR_TOTAL,CY_OTHERS,ROB_FO_SLUDGE,ROB_LO_SLUDGE,ROB_BILGE,SLUDGE_REMOVED_FO,SLUDGE_REMOVED_LO,SEA_STATE,CY_LUB_ADDED_TO_SYSTEM_MECC,CY_LUB_ADDED_TO_SYSTEM_AECC,CY_LUB_ADDED_TO_THRUSTERS,CY_ME_LO_PURIFIER_IN_USE,CY_BALLAST,CY_BENDING_MOMENT,CY_SHEARING_FORCE,CY_TORTION_MOMENT,CY_SUPDT_AUDITOR_SIGNED_ON,CY_SUPDT_AUDITOR_SIGNED_OFF,CY_CASH_RECEIVED,CY_LUB_OIL_RECEIVED_MECYL,CY_LUB_OIL_RECEIVED_MECC,CY_LUB_OIL_RECEIVED_AECC,CY_M_E_UNDER_PISTON_TEMP,CY_MAIL_RECEIVED,WIND_DIRECTION_PORT_STBD,SEA_DIRECTION_PORT_STBD,TIME_PILOT_ONBOARD,GRADES_ROB,SO2_CO2_RATIO,Bunker_Order,Remarks,Fuel_Type,Carbon_Factor,Sulphur_Content_PC,Quantity,Port_Delivery,Product_Quality,Tanktainer_Number_1,Supplier,Delivery,Vol_Lt,Den,Vis,ROB_Dstlt_ULS,ROB_Dstlt_VLS,ROB_Rsdl_MDO,ROB_Tnktnr_Dstlt_VLS,ROB_Rsdl_VLS,ROB_Rsdl_HS,ROB_Rsdl_ULS,ROB_Fuel_HSFO,ROB_Fuel_LSFO,ROB_Fuel_MDO,ROB_Fuel_MGO,ROB_Fuel_MGO_LS,ROB_Fuel_Tanktainer_MGO,ECA_MILES,ECA_TIME,EGCS_DRY_WASTE_REMOVED,EGCS_RUNNING_TIME,EGCS_WET_SLURRY_REMOVED,EGCS_OPEN_LOOP_RUNNING_TIME,EGCS_CLOSED_LOOP_RUNNING_TIME,Voyage_Order,Voyage_Code,ECA,EU,Sea_Time,ETA_Country_Code,Port_Country_Code,check_ETA_code,check_Port_code,Status_TEMP_EU,FUEL_HS,FUEL_LS,FUEL_MDO,FUEL_MGO,FUEL_MGO_LS,Cargo_Transport_Work,TEU_Transport_Work,EEOI_Voyage_no,CARGO_TOTAL_Old,DRAFT,FO_per_24Hrs,SFOC,CY_OIL_gm_hr,SCOC,Voyage_Name,TOTAL_FO,TOTAL_CO2,EEOI,voyCondition,samedate,timesincelastreport,BDN,Wind_direction_360,True_wind_speed,True_wind_dir,ref_power,ref_fuel,fuel_loss,Relative_wind_speed,Relative_wind_direction,CAA,RW,Corrected_Power,draft_pow,draft_sp_pow,fo_nor,fo_model,sfoc_model,sfoc_deviation,ref_power_corrected,ref_FO_corrected,Propulsive_eff,speed_performance,Ref_speed,P_I,MEcon,AEcon,BLcon,Tcon,HS,LS,MDO,MGO,MGOLS,TCO2,AETsteaming,AEPOWER,TRIM,DISTANCECOVERED,updated_date,hyd_slip_sog,hyd_slip_stw,FUEL_Rsdl_HS,FUEL_Rsdl_VLS,FUEL_Rsdl_ULS,FUEL_Dstlt_VLS,FUEL_Dstlt_ULS,FUEL_Tnktnr_Dstlt_VLS,Rsdl_HS,Rsdl_VLS,Rsdl_ULS,Dstlt_VLS,Dstlt_ULS,Tnktnr_Dstlt_VLS,Time
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023-01-01,WVEY,cbdf5a2f-14e8-4ece-bbb7-ee565e555c0a,WEC VAN EYCK,9365984.0,EI251A,01/01/2023 00:00,2023-01-01 12:00:00,UTC +01:00,NOON,AT SEA,4938N,00351W,49.633333,-3.850000,18.96,6332.8,True,24.0,24.0,216.82,0.0,9.03417,9.03417,154.0,1.3,10.0,30.0,5.9,4.9,9358.0,242.0,2.53,14.25,157.0,11.0,10.0,216.82,ESBIO,03/01/2023 23:59,UTC +01:00,BILBAO,NaN,24.0,328.0,340.0,12.4,446.8,36.0,0.0,0.0,0.0,0.0,720000.0,NLRTM,ROTTERDAM,False,False,NaN,NaN,NaN,NaN,Port Contamination,NaN,24/12/2022 07:00,UTC +01:00,NaN,NaN,NaN,NaN,NaN,30/12/2022 20:00,UTC +01:00,NaN,NaN,NaN,206.0,274.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,3949.0,0.0,0.0,0.0,0.0,0.0,250.0,0.0,0.00,0.0,0.0,0.0,18.96,0.0,0.0,0.00,0.0,0.0,18.96,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2O,CE,True,True,0.7,NaN,NaN,NaN,NaN,NaN,NaN,52.0,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,1680.0,0.0,6000.0,NaN,NaN,NaN,0.1,NaN,NaN,5.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,186.75,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,186.75,0.0,216.82,24.0,NaN,0.0,NaN,0.0,0.0,379.0,NLMOE-ESBIO,N,Y,24.0,ES,NL,NaN,NaN,0.0,0.0,0.00,0.0,0.0,18.96,1373080.0,104074.0,379.0,0.0,5.4,18.9600,200.0510,0.0,0.0,0.0,18.96,60.7858,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.96,0.0,0.0,18.96,0.0,0.00,0.0,0.0,18.96,60.79,0.0,0.0,1.0,216.82,14/02/2023 14:18,NaN,NaN,0.0,0.00,0.0,0.0,18.96,0.0,0.0,0.00,0.0,0.0,18.96,0.0,12:00:00
2023-01-02,WVEY,aeff2126-5a79-4b20-b2cc-b04bad7641a6,WEC VAN EYCK,9365984.0,EI251A,02/01/2023 00:00,2023-01-02 12:00:00,UTC +01:00,NOON,AT SEA,4615N,00447W,46.250000,-4.783333,19.68,6332.8,True,24.0,24.0,263.70,0.0,10.98750,10.98750,154.0,2.5,30.0,25.0,5.9,4.9,9358.0,156.0,1.52,49.54,157.0,10.0,10.0,263.70,ESBIO,02/01/2023 23:59,UTC +01:00,BILBAO,NaN,24.0,352.0,369.0,15.4,184.9,12.0,0.0,0.0,0.0,0.0,720000.0,NLRTM,ROTTERDAM,False,False,NaN,NaN,NaN,NaN,Port Contamination,NaN,24/12/2022 07:00,UTC +01:00,NaN,NaN,NaN,NaN,NaN,30/12/2022 20:00,UTC +01:00,NaN,NaN,NaN,206.0,274.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,0.0,0.0,0.0,24.0,0.0,0.0,24.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,4524.0,0.0,0.0,0.0,0.0,0.0,250.0,0.0,15.32,0.0,0.0,0.0,4.36,0.0,0.0,15.32,0.0,0.0,4.36,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2O,CE,True,True,2.2,NaN,NaN,NaN,NaN,NaN,NaN,57.0,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,1680.0,0.0,6000.0,NaN,NaN,NaN,0.1,NaN,NaN,4.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,182.39,0.0,0.0,0.0,129.94,0.0,0.0,0.0,129.94,0.0,0.0,182.39,0.0,52.30,6.5,NaN,0.0,NaN,0.0,0.0,379.0,NLMOE-ESBIO,N,Y,48.0,ES,NL,NaN,NaN,0.0,0.0,15.32,0.0,0.0,4.36,1669960.0,126576.0,379.0,0.0,5.4,9.8400,90.6278,0.0,0.0,0.0,19.68,61.6846,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.68,0.0,0.0,19.68,0.0,15.32,0.0,0.0,4.36,61.68,0.0,0.0,1.0,263.70,14/02/2023 14:18,NaN,NaN,0.0,15.32,0.0,0.0,4.36,0.0,0.0,15.32,0.0,0.0,4.36,0.0,12:00:00
2023-01-02,WVEY,b848b9c5-af76-46ad-beaf-69f341ba71fd,WEC VAN EYCK,9365984.0,EI251A,03/01/2023 00:00,2023-01-02 23:30:00,UTC +01:00,EOSP,AT SEA,4329N,00309W,43.483333,-3.150000,13.07,6332.8,True,11.5,11.5,179.80,0.0,15.63480,15.63480,154.0,2.5,20.0,15.0,5.9,4.9,9358.0,157.0,0.16,106.71,157.0,8.0,10.0,179.80,ESBIO,02/01/2023 23:59,UTC +01:00,NaN,NaN,11.5,332.0,344.0,15.4,NaN,NaN,0.0,0.0,0.0,0.0,345000.0,ESBIO,BILBAO,False,False,NaN,NaN,NaN,NaN,Port Contamination,NaN,03/01/2023 01:00,UTC +01:00,NaN,NaN,NaN,NaN,NaN,30/12/2022 20:00,UTC +01:00,NaN,NaN,NaN,206.0,274.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.5,0.0,0.0,0.0,0.0,0.0,0.0,11.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.5,0.0,5681.0,0.0,0.0,0.0,0.0,0.0,250.0,0.0,13.07,0.0,0.0,0.0,0.00,0.0,0.0,13.07,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2O,CE,True,True,0.7,NaN,NaN,NaN,NaN,NaN,NaN,58.0,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,1680.0,0.0,2875.0,NaN,NaN,NaN,0.1,NaN,NaN,2.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,116.87,0.0,0.0,0.0,116.87,0.0,0.0,0.00,0.0,0.00,0.0,NaN,0.0,NaN,0.0,0.0,379.0,NLMOE-ESBIO,N,Y,11.5,ES,NL,NaN,NaN,0.0,0.0,13.07,0.0,0.0,0.00,1138640.0,86304.0,379.0,0.0,5.4,27.2765,200.0570,0.0,0.0,0.0,13.07,40.7000,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.07,0.0,0.0,13.07,0.0,13.07,0.0,0.0,0.00,40.70,0.0,0.0,1.0,179.80,14/02/2023 14:18,NaN,NaN,0.0,13.07,0.0,0.0,0.00,0.0,0.0,13.07,0.0,0.0,0.00,0.0,23:30:00
2023-01-03,WVEY,40e7b2cb-b492-4015-a0cd-b483c66d5a94,WEC VAN EYCK,9365984.0,NaN,03/01/2023 00:00,2023-01-03 01:05:00,UTC +01:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,6332.8,False,NaN,NaN,0.00,NaN,0.00000,0.00000,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,206.0,274.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,379.0,NLMOE-ESBIO,N,Y,0.0,ES,NL,NaN,NaN,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,379.0,0.0,0.0,0.0000,0.0000,0.0,0.0,0.0,0.00,0.0000,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.00,14/02/2023 11:59,NaN,NaN,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,01:05:00
2023-01-03,WVEY,63ef18b3-6cc3-4ae7-b631-3576b4d06073,WEC VAN EYCK,9365984.0,NaN,03/01/2023 00:00,2023-01-03 01:05:00,UTC +01:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,6332.8,False,NaN,NaN,0.00,NaN,0.00000,0.00000,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,206.0,274.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,379.0,NLMOE-ESBIO,N,Y,0.0,ES,NL,NaN,NaN,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,379.0,0.0,0.0,0.0000,0.0000,0.0,0.0,0.0,0.00,0.0000,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.00,14/02/2023 11:59,NaN,NaN,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,01:05:00

In [38]:
Res_dfn = Res_dfn.sort_values(by='REPORT_DATE_TIME')

In [39]:
start_date = '2023-07-02'
end_date = '2023-08-02'
start_date = pd.to_datetime(start_date, format='%Y-%m-%d')
end_date = pd.to_datetime(end_date, format='%Y-%m-%d')

filtered_df = Res_dfn[(Res_dfn['REPORT_DATE_TIME'] >= start_date) & (Res_dfn['REPORT_DATE_TIME'] <= end_date)]

In [40]:
filtered_df.head()

,idvessel,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,LAT,LONG_,LATITUDE,LONGITUDE,M_E_FOC,CARGO_TOTAL,Has_Cargo,TOTAL_STEAMING_TIME,M_E_Fuel_Only_Steaming_Time,MILES_BY_GPS,OIL_CYL,SOW,SOG,RPM,SLIP,WIND_DIRECTION,WIND_SPEED,DRAFT_AFT,DRAFT_FWD,DISPLACEMENT,COURSE_AT_SEA,WAVE_HEIGHT,SEA_DIRECTION,CARGO_TOTAL_TEU,AMBIENT_TEMP,SW_TEMP,MILES_BY_SPEED_LOG,ETA_PORT_CODE,ETA_DATE_TIME,ETA_DATE_TIME_Offset,ETA_PORT,TIME_CHANGE,TIME_SEA,TEMP_MIN,TEMP_MAX,REQUESTED_SPEED,REM_DIST_TO_PILOT,REM_TIME_TO_PILOT,TOTAL_UNPLND_STPGE_TECH,TOTAL_UNPLND_STPGE_OPE_WX,REEFERS_POSITIVE_PLUGGED,REEFERS_NEGATIVE_PLUGGED,ME_TOTAL_REVS_COUNTER,PORT_CODE,PORT,AUX_BLOWERS_ON,HOLD_VENTILATION_ON,SINCE_DATE_TIME,SINCE_DATE_TIME_Offset,TIME_HRS_ANCHOR,TIME_HRS_DRIFT,REASON,TYPE_OF_DELAY,ETB_DATE_TIME,ETB_DATE_TIME_Offset,PILOT_DATE_TIME,PILOT_DATE_TIME_Offset,TIME_MANOEUVRING,TUG_ARR,TUG_SHIFT,ETD_DATE_TIME,ETD_DATE_TIME_Offset,SHIFT_BERTH_HOURS,CARGO_LOAD,CARGO_DISCH,TEU_FULL,TEU_EMPTY,BILGE_REMOVED,GARBAGE_REMOVED,GARBAGE_REMVL_REQSTD,GARBAGE_REMVL_CMPLSRY,FW_SUPPLY,CY_CREW_SIGNED_ON,CY_CREW_SIGNED_OFF,CY_DOCTORS_VISIT,CY_MAIL_RECEIVED_Ref_NO,CY_LUB_OIL_SAMPLE_LANDED,CY_CHECKD_FOR_STOWAWAYS,CY_STOWAWAYS_ON_BOARD,CY_DEP_GM_Mtr,CY_REQUISITIONS_RECEIVED,DISTANCE_TO_NEXT_PILOT,TUG_SAILING_TRANSIT,STEAMING_TIME_M_E_Rsdl_VLS,STEAMING_TIME_M_E_Rsdl_HS,STEAMING_TIME_M_E_Rsdl_ULS,STEAMING_TIME_M_E_Dstlt_VLS,STEAMING_TIME_M_E_Dstlt_ULS,STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS,STEAMING_TIME_M_E_HS,STEAMING_TIME_M_E_LS,STEAMING_TIME_M_E_MDO,STEAMING_TIME_M_E_MGO,STEAMING_TIME_M_E_MGO_LS,STEAMING_TIME_AUX_1,STEAMING_TIME_AUX_2,STEAMING_TIME_AUX_3,STEAMING_TIME_AUX_4,STEAMING_TIME_AUX_5,STEAMING_TIME_SH_GEN,STEAMING_TIME_TG,POWER_kW,STEAMING_LOAD_KW_AUX_1,STEAMING_LOAD_KW_AUX_2,STEAMING_LOAD_KW_AUX_3,STEAMING_LOAD_KW_AUX_4,STEAMING_LOAD_KW_AUX_5,STEAMING_LOAD_KW_SH_GEN,STEAMING_LOAD_KW_TG,FUEL_M_E_Rsdl_VLS,FUEL_M_E_Rsdl_HS,FUEL_M_E_Rsdl_ULS,FUEL_M_E_Dstlt_VLS,FUEL_M_E_Dstlt_ULS,FUEL_M_E_Tnktnr_Dstlt_VLS,FUEL_M_E_HS,FUEL_M_E_LS,FUEL_M_E_MDO,FUEL_M_E_MGO,FUEL_M_E_MGO_LS,FUEL_Aux_Rsdl_VLS,FUEL_Aux_Rsdl_HS,FUEL_Aux_Rsdl_ULS,FUEL_Aux_Dstlt_VLS,FUEL_Aux_Dstlt_ULS,FUEL_Aux_Tnktnr_Dstlt_VLS,FUEL_AUX_HS,FUEL_AUX_LS,FUEL_AUX_MDO,FUEL_AUX_MGO,FUEL_AUX_MGO_LS,FUEL_Boiler_Rsdl_VLS,FUEL_Boiler_Rsdl_HS,FUEL_Boiler_Rsdl_ULS,FUEL_Boiler_Dstlt_VLS,FUEL_Boiler_Dstlt_ULS,FUEL_Boiler_Tnktnr_Dstlt_VLS,FUEL_BOILER_HS,FUEL_BOILER_LS,FUEL_BOILER_MDO,FUEL_BOILER_MGO,FUEL_BOILER_MGO_LS,DECK_LAST_CHANGE_USER,ENGINE_LAST_CHANGE_USER,DECK_PART_IS_COMPLETE,ENGINE_PART_IS_COMPLETE,SCAVENGE_PRESSURE,SECA_ENTRY_TIME,SECA_ENTRY_LAT,SECA_ENTRY_LONG,SECA_EXIT_TIME,SECA_EXIT_LAT,SECA_EXIT_LONG,ROB_FRESH_WATER,MANVRNG_MILES_BY_GPS,MANVRNG_MILES_BY_SPEED_LOG,TANKTAINER_TRANSFD_QUANTITY,PILOT_TAKEN,DATE_TIME_START_TRANSIT,DATE_TIME_START_TRANSIT_Offset,DATE_TIME_END_TRANSIT,DATE_TIME_END_TRANSIT_Offset,BALLAST,TANKTAINER_NUMBER,STEAMING_KWHR_TOTAL,CY_OTHERS,ROB_FO_SLUDGE,ROB_LO_SLUDGE,ROB_BILGE,SLUDGE_REMOVED_FO,SLUDGE_REMOVED_LO,SEA_STATE,CY_LUB_ADDED_TO_SYSTEM_MECC,CY_LUB_ADDED_TO_SYSTEM_AECC,CY_LUB_ADDED_TO_THRUSTERS,CY_ME_LO_PURIFIER_IN_USE,CY_BALLAST,CY_BENDING_MOMENT,CY_SHEARING_FORCE,CY_TORTION_MOMENT,CY_SUPDT_AUDITOR_SIGNED_ON,CY_SUPDT_AUDITOR_SIGNED_OFF,CY_CASH_RECEIVED,CY_LUB_OIL_RECEIVED_MECYL,CY_LUB_OIL_RECEIVED_MECC,CY_LUB_OIL_RECEIVED_AECC,CY_M_E_UNDER_PISTON_TEMP,CY_MAIL_RECEIVED,WIND_DIRECTION_PORT_STBD,SEA_DIRECTION_PORT_STBD,TIME_PILOT_ONBOARD,GRADES_ROB,SO2_CO2_RATIO,Bunker_Order,Remarks,Fuel_Type,Carbon_Factor,Sulphur_Content_PC,Quantity,Port_Delivery,Product_Quality,Tanktainer_Number_1,Supplier,Delivery,Vol_Lt,Den,Vis,ROB_Dstlt_ULS,ROB_Dstlt_VLS,ROB_Rsdl_MDO,ROB_Tnktnr_Dstlt_VLS,ROB_Rsdl_VLS,ROB_Rsdl_HS,ROB_Rsdl_ULS,ROB_Fuel_HSFO,ROB_Fuel_LSFO,ROB_Fuel_MDO,ROB_Fuel_MGO,ROB_Fuel_MGO_LS,ROB_Fuel_Tanktainer_MGO,ECA_MILES,ECA_TIME,EGCS_DRY_WASTE_REMOVED,EGCS_RUNNING_TIME,EGCS_WET_SLURRY_REMOVED,EGCS_OPEN_LOOP_RUNNING_TIME,EGCS_CLOSED_LOOP_RUNNING_TIME,Voyage_Order,Voyage_Code,ECA,EU,Sea_Time,ETA_Country_Code,Port_Country_Code,check_ETA_code,check_Port_code,Status_TEMP_EU,FUEL_HS,FUEL_LS,FUEL_MDO,FUEL_MGO,FUEL_MGO_LS,Cargo_Transport_Work,TEU_Transport_Work,EEOI_Voyage_no,CARGO_TOTAL_Old,DRAFT,FO_per_24Hrs,SFOC,CY_OIL_gm_hr,SCOC,Voyage_Name,TOTAL_FO,TOTAL_CO2,EEOI,voyCondition,samedate,timesincelastreport,BDN,Wind_direction_360,True_wind_speed,True_wind_dir,ref_power,ref_fuel,fuel_loss,Relative_wind_speed,Relative_wind_direction,CAA,RW,Corrected_Power,draft_pow,draft_sp_pow,fo_nor,fo_model,sfoc_model,sfoc_deviation,ref_power_corrected,ref_FO_corrected,Propulsive_eff,speed_performance,Ref_speed,P_I,MEcon,AEcon,BLcon,Tcon,HS,LS,MDO,MGO,MGOLS,TCO2,AETsteaming,AEPOWER,TRIM,DISTANCECOVERED,updated_date,hyd_slip_sog,hyd_slip_stw,FUEL_Rsdl_HS,FUEL_Rsdl_VLS,FUEL_Rsdl_ULS,FUEL_Dstlt_VLS,FUEL_Dstlt_ULS,FUEL_Tnktnr_Dstlt_VLS,Rsdl_HS,Rsdl_VLS,Rsdl_ULS,Dstlt_VLS,Dstlt_ULS,Tnktnr_Dstlt_VLS,Time
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023-07-02,WVEY,1f662360-6abb-4420-b05d-3e72bcf5ef0d,WEC VAN EYCK,9365984.0,EI326A,02/07/2023 00:00,2023-07-02 12:00:00,UTC +02:00,PORT,IN PORT,5158N,00337E,51.966667,3.616667,1.96,1459.1,True,3.3,3.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.4,4.8,8752.0,0.0,0.0,0.0,256.0,22.0,18.0,NaN,NLMOE,01/07/2023 01:15,UTC +02:00,NaN,NaN,24.0,70.0,70.0,15.5,NaN,NaN,0.0,0.0,4.0,0.0,63000.0,NLMOE,MOERDIJK,False,False,NaN,NaN,NaN,NaN,Port Contamination,NaN,01/07/2023 06:00,UTC +02:00,NaN,NaN,NaN,NaN,NaN,03/07/2023 05:00,UTC +02:00,2.1,NaN,NaN,73.0,183.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,3.3,0.0,0.0,0.0,0.0,0.0,3.3,0.0,24.0,0.0,0.0,0.0,2.1,0.0,30.0,0.0,250.0,0.0,0.0,0.0,200.0,0.0,0.0,0.0,0.0,0.0,1.96,0.0,0.0,0.0,0.0,0.0,1.96,0.0,0.0,0.0,0.0,1.26,0.0,0.0,0.0,0.0,0.0,1.26,0.0,0.0,0.0,0.0,0.59,0.0,0.0,0.0,0.0,0.0,0.59,2O,CE,TRUE,TRUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.0,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,2265.0,0.0,6660.0,NaN,NaN,NaN,0.1,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,240.18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,240.18,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,425.0,GBTHP-NLMOE,N,Y,3.3,NL,GB,NaN,NaN,0.0,0.0,0.0,0.0,0.0,3.81,0.0,0.0,425.0,0.0,5.1,14.2545,19798.0,0.0,0.0,0.0,3.81,12.2149,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.96,1.26,0.59,3.81,0.0,0.0,0.0,0.0,3.81,12.21,24.0,250.0,0.6,0.0,21/07/2023 18:37,NaN,NaN,0.0,0.0,0.0,0.0,3.81,0.0,0.0,0.0,0.0,0.0,3.81,0.0,12:00:00
2023-07-03,WVEY,efa0f727-fca3-42da-adfd-87d8af0aa98b,WEC VAN EYCK,9365984.0,NaN,03/07/2023 00:00,2023-07-03 06:11:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,1459.1,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.0,183.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,425.0,GBTHP-NLMOE,N,Y,0.0,NL,GB,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,425.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.00,0.0000,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,25/07/2023 10:52,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,06:11:00
2023-07-03,WVEY,ed1a3f1e-a995-4a08-90df-2aa3d3d2b106,WEC VAN EYCK,9365984.0,NaN,03/07/2023 00:00,2023-07-03 06:11:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,1459.1,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.0,183.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,425.0,GBTHP-NLMOE,N,Y,0.0,NL,GB,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,425.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.00,0.0000,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,25/07/2023 10:52,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,06:11:00
2023-07-03,WVEY,e5b80fcd-b9b1-42d3-ba94-73c4ca2cc455,WEC VAN EYCK,9365984.0,NaN,03/07/2023 00:00,2023-07-03 06:11:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,1459.1,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.0,183.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,425.0,GBTHP-NLMOE,N,Y,0.0,NL,GB,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,425.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.00,0.0000,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,25/07/2023 10:52,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,06:11:00
2023-07-03,WVEY,3339df19-ae6c-4690-8a9e-a94a52394175,WEC VAN EYCK,9365984.0,NaN,03/07/2023 00:00,2023-07-03 06:11:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,1459.1,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.0,183.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,425.0,GBTHP-NLMOE,N,Y,0.0,NL,GB,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,425.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.00,0.0000,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,25/07/2023 10:52,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,06:11:00

In [41]:
pd.set_option('display.max_columns', None)  
filtered_df.tail()

,idvessel,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,LAT,LONG_,LATITUDE,LONGITUDE,M_E_FOC,CARGO_TOTAL,Has_Cargo,TOTAL_STEAMING_TIME,M_E_Fuel_Only_Steaming_Time,MILES_BY_GPS,OIL_CYL,SOW,SOG,RPM,SLIP,WIND_DIRECTION,WIND_SPEED,DRAFT_AFT,DRAFT_FWD,DISPLACEMENT,COURSE_AT_SEA,WAVE_HEIGHT,SEA_DIRECTION,CARGO_TOTAL_TEU,AMBIENT_TEMP,SW_TEMP,MILES_BY_SPEED_LOG,ETA_PORT_CODE,ETA_DATE_TIME,ETA_DATE_TIME_Offset,ETA_PORT,TIME_CHANGE,TIME_SEA,TEMP_MIN,TEMP_MAX,REQUESTED_SPEED,REM_DIST_TO_PILOT,REM_TIME_TO_PILOT,TOTAL_UNPLND_STPGE_TECH,TOTAL_UNPLND_STPGE_OPE_WX,REEFERS_POSITIVE_PLUGGED,REEFERS_NEGATIVE_PLUGGED,ME_TOTAL_REVS_COUNTER,PORT_CODE,PORT,AUX_BLOWERS_ON,HOLD_VENTILATION_ON,SINCE_DATE_TIME,SINCE_DATE_TIME_Offset,TIME_HRS_ANCHOR,TIME_HRS_DRIFT,REASON,TYPE_OF_DELAY,ETB_DATE_TIME,ETB_DATE_TIME_Offset,PILOT_DATE_TIME,PILOT_DATE_TIME_Offset,TIME_MANOEUVRING,TUG_ARR,TUG_SHIFT,ETD_DATE_TIME,ETD_DATE_TIME_Offset,SHIFT_BERTH_HOURS,CARGO_LOAD,CARGO_DISCH,TEU_FULL,TEU_EMPTY,BILGE_REMOVED,GARBAGE_REMOVED,GARBAGE_REMVL_REQSTD,GARBAGE_REMVL_CMPLSRY,FW_SUPPLY,CY_CREW_SIGNED_ON,CY_CREW_SIGNED_OFF,CY_DOCTORS_VISIT,CY_MAIL_RECEIVED_Ref_NO,CY_LUB_OIL_SAMPLE_LANDED,CY_CHECKD_FOR_STOWAWAYS,CY_STOWAWAYS_ON_BOARD,CY_DEP_GM_Mtr,CY_REQUISITIONS_RECEIVED,DISTANCE_TO_NEXT_PILOT,TUG_SAILING_TRANSIT,STEAMING_TIME_M_E_Rsdl_VLS,STEAMING_TIME_M_E_Rsdl_HS,STEAMING_TIME_M_E_Rsdl_ULS,STEAMING_TIME_M_E_Dstlt_VLS,STEAMING_TIME_M_E_Dstlt_ULS,STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS,STEAMING_TIME_M_E_HS,STEAMING_TIME_M_E_LS,STEAMING_TIME_M_E_MDO,STEAMING_TIME_M_E_MGO,STEAMING_TIME_M_E_MGO_LS,STEAMING_TIME_AUX_1,STEAMING_TIME_AUX_2,STEAMING_TIME_AUX_3,STEAMING_TIME_AUX_4,STEAMING_TIME_AUX_5,STEAMING_TIME_SH_GEN,STEAMING_TIME_TG,POWER_kW,STEAMING_LOAD_KW_AUX_1,STEAMING_LOAD_KW_AUX_2,STEAMING_LOAD_KW_AUX_3,STEAMING_LOAD_KW_AUX_4,STEAMING_LOAD_KW_AUX_5,STEAMING_LOAD_KW_SH_GEN,STEAMING_LOAD_KW_TG,FUEL_M_E_Rsdl_VLS,FUEL_M_E_Rsdl_HS,FUEL_M_E_Rsdl_ULS,FUEL_M_E_Dstlt_VLS,FUEL_M_E_Dstlt_ULS,FUEL_M_E_Tnktnr_Dstlt_VLS,FUEL_M_E_HS,FUEL_M_E_LS,FUEL_M_E_MDO,FUEL_M_E_MGO,FUEL_M_E_MGO_LS,FUEL_Aux_Rsdl_VLS,FUEL_Aux_Rsdl_HS,FUEL_Aux_Rsdl_ULS,FUEL_Aux_Dstlt_VLS,FUEL_Aux_Dstlt_ULS,FUEL_Aux_Tnktnr_Dstlt_VLS,FUEL_AUX_HS,FUEL_AUX_LS,FUEL_AUX_MDO,FUEL_AUX_MGO,FUEL_AUX_MGO_LS,FUEL_Boiler_Rsdl_VLS,FUEL_Boiler_Rsdl_HS,FUEL_Boiler_Rsdl_ULS,FUEL_Boiler_Dstlt_VLS,FUEL_Boiler_Dstlt_ULS,FUEL_Boiler_Tnktnr_Dstlt_VLS,FUEL_BOILER_HS,FUEL_BOILER_LS,FUEL_BOILER_MDO,FUEL_BOILER_MGO,FUEL_BOILER_MGO_LS,DECK_LAST_CHANGE_USER,ENGINE_LAST_CHANGE_USER,DECK_PART_IS_COMPLETE,ENGINE_PART_IS_COMPLETE,SCAVENGE_PRESSURE,SECA_ENTRY_TIME,SECA_ENTRY_LAT,SECA_ENTRY_LONG,SECA_EXIT_TIME,SECA_EXIT_LAT,SECA_EXIT_LONG,ROB_FRESH_WATER,MANVRNG_MILES_BY_GPS,MANVRNG_MILES_BY_SPEED_LOG,TANKTAINER_TRANSFD_QUANTITY,PILOT_TAKEN,DATE_TIME_START_TRANSIT,DATE_TIME_START_TRANSIT_Offset,DATE_TIME_END_TRANSIT,DATE_TIME_END_TRANSIT_Offset,BALLAST,TANKTAINER_NUMBER,STEAMING_KWHR_TOTAL,CY_OTHERS,ROB_FO_SLUDGE,ROB_LO_SLUDGE,ROB_BILGE,SLUDGE_REMOVED_FO,SLUDGE_REMOVED_LO,SEA_STATE,CY_LUB_ADDED_TO_SYSTEM_MECC,CY_LUB_ADDED_TO_SYSTEM_AECC,CY_LUB_ADDED_TO_THRUSTERS,CY_ME_LO_PURIFIER_IN_USE,CY_BALLAST,CY_BENDING_MOMENT,CY_SHEARING_FORCE,CY_TORTION_MOMENT,CY_SUPDT_AUDITOR_SIGNED_ON,CY_SUPDT_AUDITOR_SIGNED_OFF,CY_CASH_RECEIVED,CY_LUB_OIL_RECEIVED_MECYL,CY_LUB_OIL_RECEIVED_MECC,CY_LUB_OIL_RECEIVED_AECC,CY_M_E_UNDER_PISTON_TEMP,CY_MAIL_RECEIVED,WIND_DIRECTION_PORT_STBD,SEA_DIRECTION_PORT_STBD,TIME_PILOT_ONBOARD,GRADES_ROB,SO2_CO2_RATIO,Bunker_Order,Remarks,Fuel_Type,Carbon_Factor,Sulphur_Content_PC,Quantity,Port_Delivery,Product_Quality,Tanktainer_Number_1,Supplier,Delivery,Vol_Lt,Den,Vis,ROB_Dstlt_ULS,ROB_Dstlt_VLS,ROB_Rsdl_MDO,ROB_Tnktnr_Dstlt_VLS,ROB_Rsdl_VLS,ROB_Rsdl_HS,ROB_Rsdl_ULS,ROB_Fuel_HSFO,ROB_Fuel_LSFO,ROB_Fuel_MDO,ROB_Fuel_MGO,ROB_Fuel_MGO_LS,ROB_Fuel_Tanktainer_MGO,ECA_MILES,ECA_TIME,EGCS_DRY_WASTE_REMOVED,EGCS_RUNNING_TIME,EGCS_WET_SLURRY_REMOVED,EGCS_OPEN_LOOP_RUNNING_TIME,EGCS_CLOSED_LOOP_RUNNING_TIME,Voyage_Order,Voyage_Code,ECA,EU,Sea_Time,ETA_Country_Code,Port_Country_Code,check_ETA_code,check_Port_code,Status_TEMP_EU,FUEL_HS,FUEL_LS,FUEL_MDO,FUEL_MGO,FUEL_MGO_LS,Cargo_Transport_Work,TEU_Transport_Work,EEOI_Voyage_no,CARGO_TOTAL_Old,DRAFT,FO_per_24Hrs,SFOC,CY_OIL_gm_hr,SCOC,Voyage_Name,TOTAL_FO,TOTAL_CO2,EEOI,voyCondition,samedate,timesincelastreport,BDN,Wind_direction_360,True_wind_speed,True_wind_dir,ref_power,ref_fuel,fuel_loss,Relative_wind_speed,Relative_wind_direction,CAA,RW,Corrected_Power,draft_pow,draft_sp_pow,fo_nor,fo_model,sfoc_model,sfoc_deviation,ref_power_corrected,ref_FO_corrected,Propulsive_eff,speed_performance,Ref_speed,P_I,MEcon,AEcon,BLcon,Tcon,HS,LS,MDO,MGO,MGOLS,TCO2,AETsteaming,AEPOWER,TRIM,DISTANCECOVERED,updated_date,hyd_slip_sog,hyd_slip_stw,FUEL_Rsdl_HS,FUEL_Rsdl_VLS,FUEL_Rsdl_ULS,FUEL_Dstlt_VLS,FUEL_Dstlt_ULS,FUEL_Tnktnr_Dstlt_VLS,Rsdl_HS,Rsdl_VLS,Rsdl_ULS,Dstlt_VLS,Dstlt_ULS,Tnktnr_Dstlt_VLS,Time
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023-08-01,WVEY,78893644-0725-42bf-b4c8-693fb07d9354,WEC VAN EYCK,9365984.0,NaN,01/08/2023 00:00,2023-08-01 01:23:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,1371.2,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.0,97.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,437.0,GBTHP-NLRTM,N,Y,0.0,NL,GB,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,437.0,0.0,0.0,0.0000,0.000,0.0,0.0,0.0,0.00,0.00000,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,24/08/2023 09:09,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,01:23:00
2023-08-01,WVEY,0c8ff11e-2e23-4401-8cf6-d7b8e7da1293,WEC VAN EYCK,9365984.0,NaN,01/08/2023 00:00,2023-08-01 01:23:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,1371.2,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.0,97.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,437.0,GBTHP-NLRTM,N,Y,0.0,NL,GB,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,437.0,0.0,0.0,0.0000,0.000,0.0,0.0,0.0,0.00,0.00000,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,24/08/2023 09:09,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,01:23:00
2023-08-01,WVEY,18d34a59-619e-4133-a619-ffe6d1c25366,WEC VAN EYCK,9365984.0,EI331A,01/08/2023 00:00,2023-08-01 01:24:00,UTC +02:00,BRTH,DRIFTING,5158N,00339E,51.966667,3.65,1.53,1371.2,True,2.4,2.4,20.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.7,4.5,8833.0,0.0,0.0,0.0,172.0,17.0,16.0,NaN,NLRTM,01/08/2023 23:30,UTC +02:00,NaN,NaN,2.4,337.0,354.0,15.5,NaN,NaN,0.0,0.0,2.0,0.0,720000.0,NLRTM,ROTTERDAM,False,False,NaN,NaN,NaN,NaN,Port Contamination,NaN,31/07/2023 23:00,UTC +02:00,31/07/2023 23:40,UTC +02:00,2.4,0.0,0.0,02/08/2023 02:00,UTC +02:00,NaN,NaN,NaN,75.0,97.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,2.4,0.0,0.0,0.0,0.0,0.0,2.4,0.0,2.4,0.0,0.0,0.0,2.4,0.0,3188.0,0.0,250.0,0.0,0.0,0.0,200.0,0.0,0.0,0.0,0.0,0.0,1.53,0.0,0.0,0.0,0.0,0.0,1.53,0.0,0.0,0.0,0.0,0.13,0.0,0.0,0.0,0.0,0.0,0.13,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,2O,CE,TRUE,TRUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.0,20.5,20.5,NaN,FALSE,NaN,NaN,NaN,NaN,2260.0,0.0,1080.0,NaN,NaN,NaN,1.2,NaN,NaN,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82.31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,82.31,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,437.0,GBTHP-NLRTM,N,Y,2.4,NL,GB,NaN,NaN,0.0,0.0,0.0,0.0,0.0,1.66,28109.6,3526.0,437.0,0.0,5.1,15.3000,199.969,0.0,0.0,0.0,1.66,5.32196,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.53,0.13,0.00,1.66,0.0,0.0,0.0,0.0,1.66,5.32,2.4,250.0,1.2,20.5,24/08/2023 09:09,NaN,NaN,0.0,0.0,0.0,0.0,1.66,0.0,0.0,0.0,0.0,0.0,1.66,0.0,01:24:00
2023-08-01,WVEY,70b926c2-6831-4839-b0d8-ee983034457a,WEC VAN EYCK,9365984.0,EI331A,01/08/2023 00:00,2023-08-01 12:00:00,UTC +02:00,PORT,IN PORT,5158N,00339E,51.966667,3.65,2.23,1371.2,True,10.6,4.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.7,4.5,8833.0,0.0,0.0,0.0,172.0,23.0,18.0,NaN,NLRTM,01/08/2023 23:30,UTC +02:00,NaN,NaN,10.6,70.0,70.0,15.5,NaN,NaN,0.0,0.0,3.0,0.0,126000.0,NLRTM,ROTTERDAM,False,False,NaN,NaN,NaN,NaN,Port Contamination,NaN,31/07/2023 23:00,UTC +02:00,NaN,NaN,NaN,NaN,NaN,02/08/2023 02:00,UTC +02:00,4.2,NaN,NaN,75.0,97.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,4.2,0.0,0.0,0.0,0.0,0.0,4.2,0.0,10.6,0.0,0.0,0.0,4.2,0.0,2649.0,0.0,250.0,0.0,0.0,0.0,200.0,0.0,0.0,0.0,0.0,0.0,2.23,0.0,0.0,0.0,0.0,0.0,2.23,0.0,0.0,0.0,0.0,0.56,0.0,0.0,0.0,0.0,0.0,0.56,0.0,0.0,0.0,0.0,0.18,0.0,0.0,0.0,0.0,0.0,0.18,2O,CE,TRUE,TRUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.0,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,2260.0,0.0,3490.0,NaN,NaN,NaN,1.2,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,79.34,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,79.34,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,437.0,GBTHP-NLRTM,N,Y,4.2,NL,GB,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2.97,0.0,0.0,437.0,0.0,5.1,12.7429,200.435,0.0,0.0,0.0,2.97,9.52182,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.23,0.56,0.18,2.97,0.0,0.0,0.0,0.0,2.97,9.52,10.6,250.0,1.2,0.0,24/08/2023 09:09,NaN,NaN,0.0,0.0,0.0,0.0,2.97,0.0,0.0,0.0,0.0,0.0,2.97,0.0,12:00:00
2023-08-01,WVEY,e579deff-8d09-4d1f-8347-6cbbe1cd837e,WEC VAN EYCK,9365984.0,NaN,02/08/2023 00:00,2023-08-01 23:55:00,UTC +02:00,REFL,NaN,NaN,NaN,NaN,NaN,NaN,1371.2,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.0,97.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,DISTILLATE ULS,NaN,0.099,75.083,NLRTM,DISTILLATES,NaN,NORTHSTAR,HAL20238003,86.322,0.8698,5.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,437.0,GBTHP-NLRTM,N,Y,0.0,NL,GB,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,437.0,0.0,0.0,0.0000,0.000,0.0,0.0,0.0,0.00,0.00000,0.0,Laden,0.0,NaN,NO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,24/08/2023 09:09,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,23:55:00

In [42]:
filtered_df['Total_Calculated_MGO_LS'] = filtered_df[[ 'FUEL_AUX_MGO_LS', 'FUEL_BOILER_MGO_LS']].sum(axis=1)

filtered_df['Total_Calculated_ULS'] = filtered_df[[ 'FUEL_Aux_Dstlt_ULS', 'FUEL_Boiler_Dstlt_ULS']].sum(axis=1)

filtered_df['Total_Calculated_LS'] =  filtered_df[['FUEL_M_E_LS','FUEL_M_E_Rsdl_VLS']].sum(axis=1)

filtered_df['Total_fuel'] = filtered_df[['Total_Calculated_MGO_LS', 'Total_Calculated_ULS','Total_Calculated_LS']].sum(axis=1)

filtered_df['Total_Normal_Calculated'] = (filtered_df['Total_Calculated_MGO_LS'] * 3.206) + (filtered_df['Total_Calculated_ULS'] *3.206)+ (filtered_df['Total_Calculated_LS']* 3.151)

In [43]:
dist = filtered_df['MILES_BY_GPS'].sum()
print(dist)

6917.7

In [44]:
dwt= 9587
filtered_df = filtered_df.assign(DWT=dwt)

In [45]:
TAFC= filtered_df['Total_Normal_Calculated'].sum() * 10**6
print(TAFC)

1434803000.0

# ATTAINED CII

In [46]:
ATT_CII = TAFC / (dist * dwt)
ATT_CII

21.63454792685365

In [47]:
'''

CII(REF)= A.CAPACITY^-C

PARAMETER FOR A AND C ARE

SHIP TYPE                           A            C         CAPACITY
TANKER                             5247         0.610       DWT
CONTAIER SHIP                      1984         0.489       DWT
BULK CARRIER: DWT >= 2,79,000      4745         0.622       2,79,00     
BULK CARRIER: DWT <= 2,79,00       4745         0.622       DWT
COMBINATION CARRIER                40853        0.812       DWT

'''

'\n\nCII(REF)= A.CAPACITY^-C\n\nPARAMETER FOR A AND C ARE\n\nSHIP TYPE                           A            C         CAPACITY\nTANKER                             5247         0.610       DWT\nCONTAIER SHIP                      1984         0.489       DWT\nBULK CARRIER: DWT >= 2,79,000      4745         0.622       2,79,00     \nBULK CARRIER: DWT <= 2,79,00       4745         0.622       DWT\nCOMBINATION CARRIER                40853        0.812       DWT\n\n'

In [48]:
#Parameters for reference cii
a = int(input("A:"))
c = float(input("C:"))
dwt= 9587

A:1984
C:0.489

In [49]:
CII_REF = a * (dwt ** (-c))
print(CII_REF)

22.4129392579026

In [50]:
'''
Required CII= CII(REF) * [(100-Z)/100]

REDUCATION FACTOR(Z%)
YEAR           REDUCTION FACTOR RELATIVE TO 2019
2019                   
2020                  1%
2021                  2%
2022                  3%
2023                  5%
2024                  7%
2025                  9%
2026                  11%

'''

'\nRequired CII= CII(REF) * [(100-Z)/100]\n\nREDUCATION FACTOR(Z%)\nYEAR           REDUCTION FACTOR RELATIVE TO 2019\n2019                   \n2020                  1%\n2021                  2%\n2022                  3%\n2023                  5%\n2024                  7%\n2025                  9%\n2026                  11%\n\n'

In [51]:
#Z-Reduction value
years = {
    2019: 0,
    2020: 1,
    2021: 2,
    2022: 3 ,
    2023: 5 ,
    2024: 7 ,
    2025: 9 ,
    2026: 11
}

a = int(input("Enter a year: "))    #ENTER THE CII YEAR
if a in years:
    Z = years[a]
    print(Z)
else:
    print("No Z value")

Enter a year: 2023
5

In [52]:
#Required CII 
CII_REQ = CII_REF * ((100 - Z) / 100)
print(CII_REQ)

21.29229229500747

In [53]:
'''

CII RATIO= ATTAINED CII/ REQUIRED CII
                                                DD VECTORS
SHIP TYPE                          CAPACITY     D1     D2    D3    D4  
BULK CARRIER                         DWT       0.86   0.94  1.06  1.18
TANKER                               DWT       0.82   0.93  1.08  1.28
CONTAINER                            DWT       0.83   0.94  1.07  1.19
COMBINATION                          DWT       0.87   0.96  1.06  1.14
GENERAL CARGO SHIP                   DWT       0.83   0.94  1.06  1.19


CII RATIO <= D1 ---------- A RATING
D1<CII RATIO <= D2 ------- B RATING
D2<CII RATIO <= D3 ------- C RATING
D3<CII RATIO <= D4 ------- D RATING
CII RATIO  > D4 ---------- E RATING

A – Major superior performance level
B – Minor superior performance level
C – Moderate performance level
D – Minor Inferior performance level
E – Inferior performance level

All vessels must aspire to be at least C-rated.Any vessel that is rated D or E for three years in a row will have to 
submit a corrective action plan that explains the efforts that will be taken to achieve an acceptable rating (C or above). 
 
'''

'\n\nCII RATIO= ATTAINED CII/ REQUIRED CII\n                                                DD VECTORS\nSHIP TYPE                          CAPACITY     D1     D2    D3    D4  \nBULK CARRIER                         DWT       0.86   0.94  1.06  1.18\nTANKER                               DWT       0.82   0.93  1.08  1.28\nCONTAINER                            DWT       0.83   0.94  1.07  1.19\nCOMBINATION                          DWT       0.87   0.96  1.06  1.14\nGENERAL CARGO SHIP                   DWT       0.83   0.94  1.06  1.19\n\n\nCII RATIO <= D1 ---------- A RATING\nD1<CII RATIO <= D2 ------- B RATING\nD2<CII RATIO <= D3 ------- C RATING\nD3<CII RATIO <= D4 ------- D RATING\nCII RATIO  > D4 ---------- E RATING\n\nA – Major superior performance level\nB – Minor superior performance level\nC – Moderate performance level\nD – Minor Inferior performance level\nE – Inferior performance level\n\nAll vessels must aspire to be at least C-rated.Any vessel that is rated D or E for three years in a row will have to \nsubmit a corrective action plan that explains the efforts that will be taken to achieve an acceptable rating (C or above). \n \n'

In [54]:
#CII Ratio
CII_RATIO= ATT_CII/ CII_REQ
print(CII_RATIO)

1.0160741561831006

In [55]:
ships = {
    'BULK': {'D1': 0.86, 'D2': 0.94, 'D3': 1.06, 'D4': 1.18},
    'TANKER': {'D1': 0.82, 'D2': 0.93, 'D3': 1.08, 'D4': 1.28},
    'CONTAINER': {'D1': 0.83, 'D2': 0.94, 'D3': 1.07, 'D4': 1.19},
    'COMBINATION': {'D1': 0.87, 'D2': 0.96, 'D3': 1.06, 'D4': 1.14},
    'GENERAL CARGO SHIP': {'D1': 0.83, 'D2': 0.94, 'D3': 1.06, 'D4': 1.19},
}

def ratings(ship, cii_ratio):
    a = ships.get(ship)
    if a:
        if cii_ratio <= a['D1']:
            return 'A RATING'
        elif a['D1'] < cii_ratio <= a['D2']:
            return 'B RATING'
        elif a['D2'] < cii_ratio <= a['D3']:
            return 'C RATING'
        elif a['D3'] < cii_ratio <= a['D4']:
            return 'D RATING'
        else:
            return 'E RATING'
    else:
        return 'Data not founded'

ship = input("Enter the ship: ").strip().upper()  
CII_RATIO = CII_RATIO
rating = ratings(ship, CII_RATIO)
print(f'The rating is: {rating}')

Enter the ship: container
The rating is: C RATING

In [57]:
import pandas as pd
final= {
    'Fuel': ['Bio fuel', 'Normal Fuel'],
    'Attained_CII': [17.21, 21.63],  
    'Required_CII': [22.41,22.41],
    'Reference_CII':[21.29,21.29],
    'CII Ratio':[0.80,1.01],
    'CII Rating':['A RATING','C RATING']
    
}
final_df = pd.DataFrame(final)
final_df

,Fuel,Attained_CII,Required_CII,Reference_CII,CII Ratio,CII Rating
0,Bio fuel,17.21,22.41,21.29,0.80,A RATING
1,Normal Fuel,21.63,22.41,21.29,1.01,C RATING