In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
data=pd.read_csv("NOONDATA_WEC DE HOOGH.csv")

In [3]:
data.head()

,idvessel,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,...,FUEL_Rsdl_ULS,FUEL_Dstlt_VLS,FUEL_Dstlt_ULS,FUEL_Tnktnr_Dstlt_VLS,Rsdl_HS,Rsdl_VLS,Rsdl_ULS,Dstlt_VLS,Dstlt_ULS,Tnktnr_Dstlt_VLS
0,WDHG,0969ecda-c424-4a1a-8c65-bd515e7341a4,WEC DE HOOGH,9315018,EC137A,20/09/2021 00:00,20/09/2021 07:54,UTC +02:00,COSP,DRIFTING,...,0,0,0.97,0.0,0.0,0.0,0,0,0.97,0.0
1,WDHG,100aacb7-9173-4e7b-9a84-e7e78eb5933d,WEC DE HOOGH,9315018,EC137A,20/09/2021 00:00,20/09/2021 12:00,UTC +02:00,NOON,AT SEA,...,0,0,4.20,0.0,0.0,0.0,0,0,4.20,0.0
2,WDHG,11b92cc4-6eda-4b5c-b4c4-f0ea291cfb91,WEC DE HOOGH,9315018,NaN,20/09/2021 00:00,20/09/2021 06:30,UTC +02:00,SND,NaN,...,0,0,0.00,0.0,0.0,0.0,0,0,0.00,0.0
3,WDHG,1ca21df8-d4ab-4af2-9f84-8d0075ed3c45,WEC DE HOOGH,9315018,EC137A,20/09/2021 00:00,20/09/2021 06:30,UTC +02:00,SAIL,IN PORT,...,0,0,1.03,0.0,0.0,0.0,0,0,1.03,0.0
4,WDHG,4276b8fc-c70a-45e2-9a7d-b87415ff1691,WEC DE HOOGH,9315018,NaN,20/09/2021 00:00,20/09/2021 06:30,UTC +02:00,SND,NaN,...,0,0,0.00,0.0,0.0,0.0,0,0,0.00,0.0

In [4]:
df=data.copy()

In [5]:
df['REPORT_DATE_TIME'] = pd.to_datetime(df['REPORT_DATE_TIME'], format='%d/%m/%Y %H:%M', errors='coerce')

# Extract the date and time components
df['Date'] = df['REPORT_DATE_TIME'].dt.date
df['Time'] = df['REPORT_DATE_TIME'].dt.time

# Convert the 'Date' column to datetime
df['Date'] = pd.to_datetime(df['Date'])

# Filter for the year 2021
cii_year = 2023
Res_df = df[df['Date'].dt.year == cii_year]
Res_df.set_index('Date', inplace=True)

In [6]:
Res_df.head()

,idvessel,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,...,FUEL_Dstlt_VLS,FUEL_Dstlt_ULS,FUEL_Tnktnr_Dstlt_VLS,Rsdl_HS,Rsdl_VLS,Rsdl_ULS,Dstlt_VLS,Dstlt_ULS,Tnktnr_Dstlt_VLS,Time
Date,,,,,,,,,,,,,,,,,,,,,
2023-01-01,WDHG,537da5c5-a2fd-48e7-af01-46ba197f468a,WEC DE HOOGH,9315018,EC249A,01/01/2023 00:00,2023-01-01 12:00:00,UTC +01:00,NOON,AT SEA,...,0,15.44,0.0,0.0,0.00,0,0,15.44,0.0,12:00:00
2023-01-02,WDHG,c4b0b4c6-4f1f-49f3-832e-ace51920be18,WEC DE HOOGH,9315018,EC249A,02/01/2023 00:00,2023-01-02 12:00:00,UTC +01:00,NOON,AT SEA,...,0,10.17,0.0,0.0,16.53,0,0,10.17,0.0,12:00:00
2023-01-03,WDHG,7004b66b-dd9a-4e82-9de5-3c4a6dafdeb3,WEC DE HOOGH,9315018,EC249A,03/01/2023 00:00,2023-01-03 09:30:00,UTC +01:00,EOSP,AT SEA,...,0,0.00,0.0,0.0,24.70,0,0,0.00,0.0,09:30:00
2023-01-03,WDHG,0478d78d-4d64-4c96-a620-2430d15eac27,WEC DE HOOGH,9315018,NaN,04/01/2023 00:00,2023-01-03 12:59:00,UTC +01:00,SND,NaN,...,0,0.00,0.0,0.0,0.00,0,0,0.00,0.0,12:59:00
2023-01-03,WDHG,0529d3c5-e8ca-405b-bb5a-6ccdec18e1b1,WEC DE HOOGH,9315018,NaN,04/01/2023 00:00,2023-01-03 12:59:00,UTC +01:00,SND,NaN,...,0,0.00,0.0,0.0,0.00,0,0,0.00,0.0,12:59:00

In [7]:
Res_df = Res_df.sort_values(by='REPORT_DATE_TIME')

In [8]:
start_date = '2023-06-10'
end_date = '2023-07-10'
start_date = pd.to_datetime(start_date, format='%Y-%m-%d')
end_date = pd.to_datetime(end_date, format='%Y-%m-%d')

filtered_df = Res_df[(Res_df['REPORT_DATE_TIME'] >= start_date) & (Res_df['REPORT_DATE_TIME'] <= end_date)]

In [9]:
filtered_df.head()

,idvessel,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,...,FUEL_Dstlt_VLS,FUEL_Dstlt_ULS,FUEL_Tnktnr_Dstlt_VLS,Rsdl_HS,Rsdl_VLS,Rsdl_ULS,Dstlt_VLS,Dstlt_ULS,Tnktnr_Dstlt_VLS,Time
Date,,,,,,,,,,,,,,,,,,,,,
2023-06-10,WDHG,d138cc09-e28b-4438-808f-130393335bfb,WEC DE HOOGH,9315018,NaN,10/06/2023 00:00,2023-06-10 08:45:00,UTC +02:00,REFL,NaN,...,0,0.00,0.0,0.0,0.0,0,0,0.00,0.0,08:45:00
2023-06-10,WDHG,42367035-387f-46dd-a8e1-fd071c11d08c,WEC DE HOOGH,9315018,EC321R,10/06/2023 00:00,2023-06-10 12:00:00,UTC +02:00,PORT,IN PORT,...,0,4.83,0.0,0.0,0.0,0,0,4.83,0.0,12:00:00
2023-06-11,WDHG,22b70681-67ce-4a72-86a2-60b73b83fa73,WEC DE HOOGH,9315018,NaN,11/06/2023 00:00,2023-06-11 10:27:00,UTC +02:00,REFL,NaN,...,0,0.00,0.0,0.0,0.0,0,0,0.00,0.0,10:27:00
2023-06-11,WDHG,7722d78c-712b-4b96-84b1-c41fab820bd6,WEC DE HOOGH,9315018,EC321R,11/06/2023 00:00,2023-06-11 12:00:00,UTC +02:00,PORT,IN PORT,...,0,4.19,0.0,0.0,0.0,0,0,4.19,0.0,12:00:00
2023-06-12,WDHG,3d5e6f51-59c4-4498-b6eb-16a26e0e862d,WEC DE HOOGH,9315018,NaN,12/06/2023 00:00,2023-06-12 00:29:00,UTC +02:00,SND,NaN,...,0,0.00,0.0,0.0,0.0,0,0,0.00,0.0,00:29:00

In [10]:
pd.set_option('display.max_columns', None)  
filtered_df.tail()

,idvessel,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,LAT,LONG_,LATITUDE,LONGITUDE,M_E_FOC,CARGO_TOTAL,Has_Cargo,TOTAL_STEAMING_TIME,M_E_Fuel_Only_Steaming_Time,MILES_BY_GPS,OIL_CYL,SOW,SOG,RPM,SLIP,WIND_DIRECTION,WIND_SPEED,DRAFT_AFT,DRAFT_FWD,DISPLACEMENT,COURSE_AT_SEA,WAVE_HEIGHT,SEA_DIRECTION,CARGO_TOTAL_TEU,AMBIENT_TEMP,SW_TEMP,MILES_BY_SPEED_LOG,ETA_PORT_CODE,ETA_DATE_TIME,ETA_DATE_TIME_Offset,ETA_PORT,TIME_CHANGE,TIME_SEA,TEMP_MIN,TEMP_MAX,REQUESTED_SPEED,REM_DIST_TO_PILOT,REM_TIME_TO_PILOT,TOTAL_UNPLND_STPGE_TECH,TOTAL_UNPLND_STPGE_OPE_WX,REEFERS_POSITIVE_PLUGGED,REEFERS_NEGATIVE_PLUGGED,ME_TOTAL_REVS_COUNTER,PORT_CODE,PORT,AUX_BLOWERS_ON,HOLD_VENTILATION_ON,SINCE_DATE_TIME,SINCE_DATE_TIME_Offset,TIME_HRS_ANCHOR,TIME_HRS_DRIFT,REASON,TYPE_OF_DELAY,ETB_DATE_TIME,ETB_DATE_TIME_Offset,PILOT_DATE_TIME,PILOT_DATE_TIME_Offset,TIME_MANOEUVRING,TUG_ARR,TUG_SHIFT,ETD_DATE_TIME,ETD_DATE_TIME_Offset,SHIFT_BERTH_HOURS,CARGO_LOAD,CARGO_DISCH,TEU_FULL,TEU_EMPTY,BILGE_REMOVED,GARBAGE_REMOVED,GARBAGE_REMVL_REQSTD,GARBAGE_REMVL_CMPLSRY,FW_SUPPLY,CY_CREW_SIGNED_ON,CY_CREW_SIGNED_OFF,CY_DOCTORS_VISIT,CY_MAIL_RECEIVED_Ref_NO,CY_LUB_OIL_SAMPLE_LANDED,CY_CHECKD_FOR_STOWAWAYS,CY_STOWAWAYS_ON_BOARD,CY_DEP_GM_Mtr,CY_REQUISITIONS_RECEIVED,DISTANCE_TO_NEXT_PILOT,TUG_SAILING_TRANSIT,STEAMING_TIME_M_E_Rsdl_VLS,STEAMING_TIME_M_E_Rsdl_HS,STEAMING_TIME_M_E_Rsdl_ULS,STEAMING_TIME_M_E_Dstlt_VLS,STEAMING_TIME_M_E_Dstlt_ULS,STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS,STEAMING_TIME_M_E_HS,STEAMING_TIME_M_E_LS,STEAMING_TIME_M_E_MDO,STEAMING_TIME_M_E_MGO,STEAMING_TIME_M_E_MGO_LS,STEAMING_TIME_AUX_1,STEAMING_TIME_AUX_2,STEAMING_TIME_AUX_3,STEAMING_TIME_AUX_4,STEAMING_TIME_AUX_5,STEAMING_TIME_SH_GEN,STEAMING_TIME_TG,POWER_kW,STEAMING_LOAD_KW_AUX_1,STEAMING_LOAD_KW_AUX_2,STEAMING_LOAD_KW_AUX_3,STEAMING_LOAD_KW_AUX_4,STEAMING_LOAD_KW_AUX_5,STEAMING_LOAD_KW_SH_GEN,STEAMING_LOAD_KW_TG,FUEL_M_E_Rsdl_VLS,FUEL_M_E_Rsdl_HS,FUEL_M_E_Rsdl_ULS,FUEL_M_E_Dstlt_VLS,FUEL_M_E_Dstlt_ULS,FUEL_M_E_Tnktnr_Dstlt_VLS,FUEL_M_E_HS,FUEL_M_E_LS,FUEL_M_E_MDO,FUEL_M_E_MGO,FUEL_M_E_MGO_LS,FUEL_Aux_Rsdl_VLS,FUEL_Aux_Rsdl_HS,FUEL_Aux_Rsdl_ULS,FUEL_Aux_Dstlt_VLS,FUEL_Aux_Dstlt_ULS,FUEL_Aux_Tnktnr_Dstlt_VLS,FUEL_AUX_HS,FUEL_AUX_LS,FUEL_AUX_MDO,FUEL_AUX_MGO,FUEL_AUX_MGO_LS,FUEL_Boiler_Rsdl_VLS,FUEL_Boiler_Rsdl_HS,FUEL_Boiler_Rsdl_ULS,FUEL_Boiler_Dstlt_VLS,FUEL_Boiler_Dstlt_ULS,FUEL_Boiler_Tnktnr_Dstlt_VLS,FUEL_BOILER_HS,FUEL_BOILER_LS,FUEL_BOILER_MDO,FUEL_BOILER_MGO,FUEL_BOILER_MGO_LS,DECK_LAST_CHANGE_USER,ENGINE_LAST_CHANGE_USER,DECK_PART_IS_COMPLETE,ENGINE_PART_IS_COMPLETE,SCAVENGE_PRESSURE,SECA_ENTRY_TIME,SECA_ENTRY_LAT,SECA_ENTRY_LONG,SECA_EXIT_TIME,SECA_EXIT_LAT,SECA_EXIT_LONG,ROB_FRESH_WATER,MANVRNG_MILES_BY_GPS,MANVRNG_MILES_BY_SPEED_LOG,TANKTAINER_TRANSFD_QUANTITY,PILOT_TAKEN,DATE_TIME_START_TRANSIT,DATE_TIME_START_TRANSIT_Offset,DATE_TIME_END_TRANSIT,DATE_TIME_END_TRANSIT_Offset,BALLAST,TANKTAINER_NUMBER,STEAMING_KWHR_TOTAL,CY_OTHERS,ROB_FO_SLUDGE,ROB_LO_SLUDGE,ROB_BILGE,SLUDGE_REMOVED_FO,SLUDGE_REMOVED_LO,SEA_STATE,CY_LUB_ADDED_TO_SYSTEM_MECC,CY_LUB_ADDED_TO_SYSTEM_AECC,CY_LUB_ADDED_TO_THRUSTERS,CY_ME_LO_PURIFIER_IN_USE,CY_BALLAST,CY_BENDING_MOMENT,CY_SHEARING_FORCE,CY_TORTION_MOMENT,CY_SUPDT_AUDITOR_SIGNED_ON,CY_SUPDT_AUDITOR_SIGNED_OFF,CY_CASH_RECEIVED,CY_LUB_OIL_RECEIVED_MECYL,CY_LUB_OIL_RECEIVED_MECC,CY_LUB_OIL_RECEIVED_AECC,CY_M_E_UNDER_PISTON_TEMP,CY_MAIL_RECEIVED,WIND_DIRECTION_PORT_STBD,SEA_DIRECTION_PORT_STBD,TIME_PILOT_ONBOARD,GRADES_ROB,SO2_CO2_RATIO,Bunker_Order,Remarks,Fuel_Type,Carbon_Factor,Sulphur_Content_PC,Quantity,Port_Delivery,Product_Quality,Tanktainer_Number_1,Supplier,Delivery,Vol_Lt,Den,Vis,ROB_Dstlt_ULS,ROB_Dstlt_VLS,ROB_Rsdl_MDO,ROB_Tnktnr_Dstlt_VLS,ROB_Rsdl_VLS,ROB_Rsdl_HS,ROB_Rsdl_ULS,ROB_Fuel_HSFO,ROB_Fuel_LSFO,ROB_Fuel_MDO,ROB_Fuel_MGO,ROB_Fuel_MGO_LS,ROB_Fuel_Tanktainer_MGO,ECA_MILES,ECA_TIME,EGCS_DRY_WASTE_REMOVED,EGCS_RUNNING_TIME,EGCS_WET_SLURRY_REMOVED,EGCS_OPEN_LOOP_RUNNING_TIME,EGCS_CLOSED_LOOP_RUNNING_TIME,Voyage_Order,Voyage_Code,ECA,EU,Sea_Time,ETA_Country_Code,Port_Country_Code,check_ETA_code,check_Port_code,Status_TEMP_EU,FUEL_HS,FUEL_LS,FUEL_MDO,FUEL_MGO,FUEL_MGO_LS,Cargo_Transport_Work,TEU_Transport_Work,EEOI_Voyage_no,CARGO_TOTAL_Old,DRAFT,FO_per_24Hrs,SFOC,CY_OIL_gm_hr,SCOC,Voyage_Name,TOTAL_FO,TOTAL_CO2,EEOI,voyCondition,samedate,timesincelastreport,BDN,Wind_direction_360,True_wind_speed,True_wind_dir,ref_power,ref_fuel,fuel_loss,Relative_wind_speed,Relative_wind_direction,CAA,RW,Corrected_Power,draft_pow,draft_sp_pow,fo_nor,fo_model,sfoc_model,sfoc_deviation,ref_power_corrected,ref_FO_corrected,Propulsive_eff,speed_performance,Ref_speed,P_I,MEcon,AEcon,BLcon,Tcon,HS,LS,MDO,MGO,MGOLS,TCO2,AETsteaming,AEPOWER,TRIM,DISTANCECOVERED,updated_date,hyd_slip_sog,hyd_slip_stw,FUEL_Rsdl_HS,FUEL_Rsdl_VLS,FUEL_Rsdl_ULS,FUEL_Dstlt_VLS,FUEL_Dstlt_ULS,FUEL_Tnktnr_Dstlt_VLS,Rsdl_HS,Rsdl_VLS,Rsdl_ULS,Dstlt_VLS,Dstlt_ULS,Tnktnr_Dstlt_VLS,Time
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023-07-05,WDHG,5c000c88-7481-4bf7-8597-5173a8646440,WEC DE HOOGH,9315018,EC325,06/07/2023 00:00,2023-07-05 18:12:00,UTC +02:00,BRTH,DRIFTING,5128N,00135E,51.466667,1.583333,3.00,5825.6,True,3.7,3.7,36.4,0.0,0.0000,0.0000,0.0,0.0,0.0,0,7.3,7.1,14977.0,0,0.00,0.00,560.0,19.0,18.0,NaN,GBTHP,05/07/2023 15:00,UTC +02:00,NaN,NaN,3.7,401.0,435.0,13.8,NaN,NaN,0.0,0.0,1.0,2.0,85373.0,GBTHP,THAMESPORT,False,False,NaN,NaN,NaN,NaN,bearth occupied,NaN,05/07/2023 18:00,UTC +02:00,05/07/2023 14:54,UTC +02:00,3.7,0.0,0.0,05/07/2023 22:00,UTC +02:00,NaN,NaN,NaN,441,119,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,3.7,0.0,0.0,0.0,0.0,0,3.7,3.7,3.7,0.0,0.0,0.0,3.7,0.0,4058,180.0,180.0,0.0,0.0,0.0,300.0,0.0,0.0,0.0,0,0,3.00,0.0,0,0.0,0.0,0.0,3.00,0.0,0,0,0,0.30,0.0,0,0,0,0,0.30,0.0,0,0,0,0.00,0.0,0.0,0,0,0,0.00,2O,CE,TRUE,TRUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,36.4,38.5,NaN,FALSE,NaN,NaN,NaN,NaN,2808.0,0.0,16347.0,NaN,NaN,NaN,2.6,NaN,NaN,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,58.00,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,361.0,PTLEI-GBTHP,N,Y,3.7,GB,PT,NaN,NaN,0,0.0,0.0,0.0,0.0,3.30,212052.0,20384.0,361.0,0,7.20,19.4595,199.806,0,0,0,3.30,10.57980,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.00,0.30,0.00,3.30,0.0,0.0,0.0,0.0,3.30,10.58,7.4,360,0.2,36.4,25/07/2023 10:52,NaN,NaN,0.0,0.0,0,0,3.30,0.0,0.0,0.0,0,0,3.30,0.0,18:12:00
2023-07-05,WDHG,5cc35a44-84f7-4aea-9e8b-b983f6a8f23f,WEC DE HOOGH,9315018,NaN,06/07/2023 00:00,2023-07-05 22:41:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,5825.6,False,NaN,NaN,0.0,NaN,0.0000,0.0000,0.0,0.0,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,441,119,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0,0.00,0.0,0,0.0,0.0,0.0,0.00,0.0,0,0,0,0.00,0.0,0,0,0,0,0.00,0.0,0,0,0,0.00,0.0,0.0,0,0,0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,361.0,PTLEI-GBTHP,N,Y,0.0,GB,PT,NaN,NaN,0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,361.0,0,0.00,0.0000,0.000,0,0,0,0.00,0.00000,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0,0.0,0.0,25/07/2023 10:52,NaN,NaN,0.0,0.0,0,0,0.00,0.0,0.0,0.0,0,0,0.00,0.0,22:41:00
2023-07-05,WDHG,8110f2d3-025b-4b4c-a818-f42593bf9bc8,WEC DE HOOGH,9315018,NaN,06/07/2023 00:00,2023-07-05 22:41:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,5825.6,False,NaN,NaN,0.0,NaN,0.0000,0.0000,0.0,0.0,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,441,119,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0,0.00,0.0,0,0.0,0.0,0.0,0.00,0.0,0,0,0,0.00,0.0,0,0,0,0,0.00,0.0,0,0,0,0.00,0.0,0.0,0,0,0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,361.0,PTLEI-GBTHP,N,Y,0.0,GB,PT,NaN,NaN,0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,361.0,0,0.00,0.0000,0.000,0,0,0,0.00,0.00000,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0,0.0,0.0,25/07/2023 10:52,NaN,NaN,0.0,0.0,0,0,0.00,0.0,0.0,0.0,0,0,0.00,0.0,22:41:00
2023-07-05,WDHG,dff65ee0-b466-4a41-b94d-b87a66c1f9a9,WEC DE HOOGH,9315018,NaN,06/07/2023 00:00,2023-07-05 22:41:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,5825.6,False,NaN,NaN,0.0,NaN,0.0000,0.0000,0.0,0.0,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,441,119,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0,0.00,0.0,0,0.0,0.0,0.0,0.00,0.0,0,0,0,0.00,0.0,0,0,0,0,0.00,0.0,0,0,0,0.00,0.0,0.0,0,0,0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,361.0,PTLEI-GBTHP,N,Y,0.0,GB,PT,NaN,NaN,0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,361.0,0,0.00,0.0000,0.000,0,0,0,0.00,0.00000,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0,0.0,0.0,25/07/2023 10:52,NaN,NaN,0.0,0.0,0,0,0.00,0.0,0.0,0.0,0,0,0.00,0.0,22:41:00
2023-07-05,WDHG,da72bd77-b94c-43f4-b928-648579c62afd,WEC DE HOOGH,9315018,NaN,06/07/2023 00:00,2023-07-05 22:41:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,5825.6,False,NaN,NaN,0.0,NaN,0.0000,0.0000,0.0,0.0,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,441,119,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0,0.00,0.0,0,0.0,0.0,0.0,0.00,0.0,0,0,0,0.00,0.0,0,0,0,0,0.00,0.0,0,0,0,0.00,0.0,0.0,0,0,0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,361.0,PTLEI-GBTHP,N,Y,0.0,GB,PT,NaN,NaN,0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,361.0,0,0.00,0.0000,0.000,0,0,0,0.00,0.00000,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0,0.0,0.0,25/07/2023 10:52,NaN,NaN,0.0,0.0,0,0,0.00,0.0,0.0,0.0,0,0,0.00,0.0,22:41:00
2023-07-05,WDHG,f4f3c952-46e6-48b1-8e30-06ea7d4fed3a,WEC DE HOOGH,9315018,NaN,06/07/2023 00:00,2023-07-05 22:41:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,5825.6,False,NaN,NaN,0.0,NaN,0.0000,0.0000,0.0,0.0,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,441,119,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0,0.00,0.0,0,0.0,0.0,0.0,0.00,0.0,0,0,0,0.00,0.0,0,0,0,0,0.00,0.0,0,0,0,0.00,0.0,0.0,0,0,0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,361.0,PTLEI-GBTHP,N,Y,0.0,GB,PT,NaN,NaN,0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,361.0,0,0.00,0.0000,0.000,0,0,0,0.00,0.00000,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0,0.0,0.0,25/07/2023 10:52,NaN,NaN,0.0,0.0,0,0,0.00,0.0,0.0,0.0,0,0,0.00,0.0,22:41:00
2023-07-05,WDHG,b0a400eb-5e88-4d8b-8163-50992da74a70,WEC DE HOOGH,9315018,NaN,06/07/2023 00:00,2023-07-05 22:41:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,5825.6,False,NaN,NaN,0.0,NaN,0.0000,0.0000,0.0,0.0,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,441,119,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0,0.00,0.0,0,0.0,0.0,0.0,0.00,0.0,0,0,0,0.00,0.0,0,0,0,0,0.00,0.0,0,0,0,0.00,0.0,0.0,0,0,0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,361.0,PTLEI-GBTHP,N,Y,0.0,GB,PT,NaN,NaN,0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,361.0,0,0.00,0.0000,0.000,0,0,0,0.00,0.00000,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0,0.0,0.0,25/07/2023 10:52,NaN,NaN,0.0,0.0,0,0,0.00,0.0,0.0,0.0,0,0,0.00,0.0,22:41:00
2023-07-05,WDHG,4690d0e1-8601-49bb-9d62-fabf956417f4,WEC DE HOOGH,9315018,EC327,06/07/2023 00:00,2023-07-05 22:42:00,UTC +02:00,SAIL,IN PORT,5128N,00135E,51.466667,1.583333,0.00,5260.3,True,4.5,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0,0.0,0,7.7,6.0,13700.0,0,0.00,0.00,592.0,19.0,18.0,NaN,NLMOE,06/07/2023 08:30,UTC +02:00,MOERDIJK,NaN,4.5,401.0,435.0,13.8,NaN,NaN,0.0,0.0,1.0,3.0,85373.0,GBTHP,THAMESPORT,False,False,NaN,NaN,NaN,NaN,bearth occupied,NaN,05/07/2023 18:00,UTC +02:00,NaN,NaN,NaN,NaN,0.0,05/07/2023 22:00,UTC +02:00,NaN,696.1,1261.4,341,251,0.0,NaN,False,False,0.0,0.0,0.0,No,0.0,0.0,0,0.0,0.87,0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,4.5,0.0,0.0,0.0,0.0,0.0,0.0,0,350.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.00,0.0,0,0.0,0.0,0.0,0.00,0.0,0,0,0,0.33,0.0,0,0,0,0,0.33,0.0,0,0,0,0.18,0.0,0.0,0,0,0,0.18,2O,CE,TRUE,TRUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,0.0,NaN,0.0,FALSE,NaN,NaN,NaN,NaN,2808.0,0.0,1575.0,NaN,NaN,NaN,2.6,NaN,NaN,0.0,0.0,0.0,0.0,1.0,NaN,93.0,80.0,23.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,FALSE,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.49,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,57.49,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,362.0,GBTHP-NLMOE,N,Y,0.0,NL,GB,NaN,NaN,0,0.0,0.0,0.0,0.0,0.51,0.0,0.0,361.0,0,6.85,0.0000,0.000,0,0,0,0.51,1.63506,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.33,0.18,0.51,0.0,0.0,0.0,0.0,0.51,1.64,4.5,350,1.7,0.0,04/08/2023 19:44,NaN,NaN,0.0,0.0,0,0,0.51,0.0,0.0,0.0,0,0,0.51,0.0,22:42:00
2023-07-06,WDHG,5124a853-ecc2-42ae-8ac6-915ae8cf8e2e,WEC DE HOOGH,9315018,EC327,06/07/2023 00:00,2023-07-06 01:54:00,UTC +02:00,COSP,DRIFTING,5126N,00130E,51.433333,1.500000,3.00,5260.3,True,3.2,3.2,32.6,0.0,0.0000,0.0000,0.0,0.0,115.0,2,7.7,6.0,13700.0,62,0.02,115.00,592.0,17.0,14.0,NaN,NLMOE,06/07/2023 08:30,UTC +02:00,MOERDIJK,NaN,3.2,401.0,435.0,13.8,NaN,NaN,0.0,0.0,1.0,3.0,85376.0,GBTHP,THAMESPORT,False,False,NaN,NaN,NaN,NaN,bearth occupied,NaN,05/07/2023 18:00,UTC +02:00,NaN,NaN,3.2,NaN,NaN,05/07/2023 22:00,UTC +02:00,NaN,NaN,NaN,341,251,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96.6,0.0,0.0,0.0,0.0,0.0,3.2,0.0,0.0,0.0,0.0,0,3.2,3.2,3.2,0.0,0.0,0.0,3.2,0.0,4692,180.0,180.0,0.0,0.0,0.0,300.0,0.0,0.0,0.0,0,0,3.00,0.0,0,0.0,0.0,0.0,3.00,0.0,0,0,0,0.27,0.0,0,0,0,0,0.27,0.0,0,0,0,0.00,0.0,0.0,0,0,0,0.00,2O,CE,TRUE,TRUE,1.3,NaN,NaN,NaN,NaN,NaN,NaN,41.0,32.6,38.0,NaN,TRUE,NaN,NaN,NaN,NaN,2808.0,0.0,16167.0,NaN,NaN,NaN,2.6,NaN,NaN,1.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,P,P,3.3,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,54.22,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,362.0,GBTHP-NLMOE,N,Y,3.2,NL,GB,NaN,NaN,0,0.0,0.0,0.0,0.0,3.27,171486.0,19299.2,362.0,0,6.85,22.5000,199.808,0,0,0,3.27,10.48360,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.00,0.27,0.00,3.27,0.0,0.0,0.0,0.0,3.27,10.48,6.4,360,1.7,32.6,04/08/2023 19:44,NaN,NaN,0.0,0.0,0,0,3.27,0.0,0.0,0.0,0,0,3.27,0.0,01:54:00
2023-07-06,WDHG,ce52a5c9-24ca-487e-9570-5c7c1d308ed2,WEC DE HOOGH,9315018,EC327,06/07/2023 00:00,2023-07-06 08:00:00,UTC +02:00,EOSP,AT SEA,5158N,00337E,51.966667,3.616667,5.92,5260.3,True,6.1,6.1,88.9,0.0,13.9016,14.5738,128.7,0.0,125.0,1,7.8,6.4,14100.0,73,1.30,176.91,592.0,17.0,14.0,84.8,NLMOE,06/07/2023 08:30,UTC +02:00,NaN,NaN,6.1,401.0,435.0,13.8,NaN,NaN,0.0,0.0,1.0,3.0,85382.0,NLMOE,MOERDIJK,False,False,NaN,NaN,NaN,NaN,bearth occupied,NaN,06/07/2023 13:00,UTC +02:00,NaN,NaN,NaN,NaN,NaN,05/07/2023 22:00,UTC +02:00,NaN,NaN,NaN,341,251,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,6.1,0.0,0.0,0.0,0.0,0,6.1,6.1,0.0,0.0,0.0,0.0,6.1,0.0,4848,350.0,0.0,0.0,0.0,0.0,350.0,0.0,0.0,0.0,0,0,5.92,0.0,0,0.0,0.0,0.0,5.92,0.0,0,0,0,0.45,0.0,0,0,0,0,0.45,0.0,0,0,0,0.00,0.0,0.0,0,0,0,0.00,2O,CE,TRUE,TRUE,1.3,NaN,NaN,NaN,NaN,NaN,NaN,41.0,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,3200.0,0.0,31710.0,NaN,NaN,NaN,2.6,NaN,NaN,4.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,S,S,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.85,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.85,0.0,88.9,6.1,NaN,0.0,NaN,0.0,0.0,362.0,GBTHP-NLMOE,N,Y,6.1,NL,GB,NaN,NaN,0,0.0,0.0,0.0,0.0,6.37,467641.0,52628.8,362.0,0,7.10,23.2918,200.184,0,0,0,6.37,20.42220,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5.92,0.45,0.00,6.37,0.0,0.0,0.0,0.0,6.37,20.42,6.1,350,1.4,88.9,04/08/2023 19:44,NaN,NaN,0.0,0.0,0,0,6.37,0.0,0.0,0.0,0,0,6.37,0.0,08:00:00

In [11]:
filtered_df['Total_Calculated_MGO_LS'] = filtered_df[['FUEL_M_E_MGO_LS', 'FUEL_AUX_MGO_LS', 'FUEL_BOILER_MGO_LS']].sum(axis=1)

filtered_df['Total_Calculated_ULS'] = filtered_df[['FUEL_M_E_Dstlt_ULS', 'FUEL_Aux_Dstlt_ULS', 'FUEL_Boiler_Dstlt_ULS']].sum(axis=1)

filtered_df['Total_Calculated_LS'] =  filtered_df[['FUEL_M_E_LS','FUEL_M_E_Rsdl_VLS']].sum(axis=1)

filtered_df['Total_fuel'] = filtered_df[['Total_Calculated_MGO_LS', 'Total_Calculated_ULS','Total_Calculated_LS']].sum(axis=1)

filtered_df['Total_BIO_Calculated'] = (filtered_df['Total_Calculated_MGO_LS'] * 2.417) + (filtered_df['Total_Calculated_ULS'] * 2.567)+ (filtered_df['Total_Calculated_LS']* 2.417)

In [12]:
dist = filtered_df['MILES_BY_GPS'].sum()
dist

5160.75

In [13]:
dwt= 13716
filtered_df = filtered_df.assign(DWT=dwt)

In [14]:
TAFC= filtered_df['Total_BIO_Calculated'].sum() * 10**6
print(TAFC)

2206763040.0

# ATTAINED CII

In [16]:
ATT_CII = TAFC / (dist * dwt)
ATT_CII

31.175641871486988

# REFERENCE CII

In [18]:
'''

CII(REF)= A.CAPACITY^-C

PARAMETER FOR A AND C ARE

SHIP TYPE                           A            C         CAPACITY
TANKER                             5247         0.610       DWT
CONTAIER SHIP                      1984         0.489       DWT
BULK CARRIER: DWT >= 2,79,000      4745         0.622       2,79,00     
BULK CARRIER: DWT <= 2,79,00       4745         0.622       DWT
COMBINATION CARRIER                40853        0.812       DWT

'''

'\n\nCII(REF)= A.CAPACITY^-C\n\nPARAMETER FOR A AND C ARE\n\nSHIP TYPE                           A            C         CAPACITY\nTANKER                             5247         0.610       DWT\nCONTAIER SHIP                      1984         0.489       DWT\nBULK CARRIER: DWT >= 2,79,000      4745         0.622       2,79,00     \nBULK CARRIER: DWT <= 2,79,00       4745         0.622       DWT\nCOMBINATION CARRIER                40853        0.812       DWT\n\n'

In [20]:
#Parameters for reference cii
a = int(input("A:"))
c = float(input("C:"))
dwt= 13716

A:1984
C:0.489

In [21]:
CII_REF = a * (dwt ** (-c))
print(CII_REF)

18.812106634619678

# REQUIRED CII

In [23]:
'''
Required CII= CII(REF) * [(100-Z)/100]

REDUCATION FACTOR(Z%)
YEAR           REDUCTION FACTOR RELATIVE TO 2019
2019                   
2020                  1%
2021                  2%
2022                  3%
2023                  5%
2024                  7%
2025                  9%
2026                  11%

'''

'\nRequired CII= CII(REF) * [(100-Z)/100]\n\nREDUCATION FACTOR(Z%)\nYEAR           REDUCTION FACTOR RELATIVE TO 2019\n2019                   \n2020                  1%\n2021                  2%\n2022                  3%\n2023                  5%\n2024                  7%\n2025                  9%\n2026                  11%\n\n'

In [24]:
#Z-Reduction value
years = {
    2019: 0,
    2020: 1,
    2021: 2,
    2022: 3 ,
    2023: 5 ,
    2024: 7 ,
    2025: 9 ,
    2026: 11
}

a = int(input("Enter a year: "))    #ENTER THE CII YEAR
if a in years:
    Z = years[a]
    print(Z)
else:
    print("No Z value")

Enter a year: 2023
5

In [25]:
#Required CII 
CII_REQ = CII_REF * ((100 - Z) / 100)
print(CII_REQ)

17.871501302888692

# CII RATIO

In [27]:
#CII Ratio
CII_RATIO= ATT_CII/ CII_REQ
print(CII_RATIO)

1.7444332931586368

In [29]:
ships = {
    'BULK': {'D1': 0.86, 'D2': 0.94, 'D3': 1.06, 'D4': 1.18},
    'TANKER': {'D1': 0.82, 'D2': 0.93, 'D3': 1.08, 'D4': 1.28},
    'CONTAINER': {'D1': 0.83, 'D2': 0.94, 'D3': 1.07, 'D4': 1.19},
    'COMBINATION': {'D1': 0.87, 'D2': 0.96, 'D3': 1.06, 'D4': 1.14},
    'GENERAL CARGO SHIP': {'D1': 0.83, 'D2': 0.94, 'D3': 1.06, 'D4': 1.19},
}

def ratings(ship, cii_ratio):
    a = ships.get(ship)
    if a:
        if cii_ratio <= a['D1']:
            return 'A RATING'
        elif a['D1'] < cii_ratio <= a['D2']:
            return 'B RATING'
        elif a['D2'] < cii_ratio <= a['D3']:
            return 'C RATING'
        elif a['D3'] < cii_ratio <= a['D4']:
            return 'D RATING'
        else:
            return 'E RATING'
    else:
        return 'Data not founded'

ship = input("Enter the ship: ").strip().upper()  
CII_RATIO = CII_RATIO
rating = ratings(ship, CII_RATIO)
print(f'The rating is: {rating}')

Enter the ship: container
The rating is: E RATING

# NORMAL FUEL

In [31]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [32]:
data=pd.read_csv("NOONDATA_WEC DE HOOGH.csv")

In [33]:
data.head()

,idvessel,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,LAT,LONG_,LATITUDE,LONGITUDE,M_E_FOC,CARGO_TOTAL,Has_Cargo,TOTAL_STEAMING_TIME,M_E_Fuel_Only_Steaming_Time,MILES_BY_GPS,OIL_CYL,SOW,SOG,RPM,SLIP,WIND_DIRECTION,WIND_SPEED,DRAFT_AFT,DRAFT_FWD,DISPLACEMENT,COURSE_AT_SEA,WAVE_HEIGHT,SEA_DIRECTION,CARGO_TOTAL_TEU,AMBIENT_TEMP,SW_TEMP,MILES_BY_SPEED_LOG,ETA_PORT_CODE,ETA_DATE_TIME,ETA_DATE_TIME_Offset,ETA_PORT,TIME_CHANGE,TIME_SEA,TEMP_MIN,TEMP_MAX,REQUESTED_SPEED,REM_DIST_TO_PILOT,REM_TIME_TO_PILOT,TOTAL_UNPLND_STPGE_TECH,TOTAL_UNPLND_STPGE_OPE_WX,REEFERS_POSITIVE_PLUGGED,REEFERS_NEGATIVE_PLUGGED,ME_TOTAL_REVS_COUNTER,PORT_CODE,PORT,AUX_BLOWERS_ON,HOLD_VENTILATION_ON,SINCE_DATE_TIME,SINCE_DATE_TIME_Offset,TIME_HRS_ANCHOR,TIME_HRS_DRIFT,REASON,TYPE_OF_DELAY,ETB_DATE_TIME,ETB_DATE_TIME_Offset,PILOT_DATE_TIME,PILOT_DATE_TIME_Offset,TIME_MANOEUVRING,TUG_ARR,TUG_SHIFT,ETD_DATE_TIME,ETD_DATE_TIME_Offset,SHIFT_BERTH_HOURS,CARGO_LOAD,CARGO_DISCH,TEU_FULL,TEU_EMPTY,BILGE_REMOVED,GARBAGE_REMOVED,GARBAGE_REMVL_REQSTD,GARBAGE_REMVL_CMPLSRY,FW_SUPPLY,CY_CREW_SIGNED_ON,CY_CREW_SIGNED_OFF,CY_DOCTORS_VISIT,CY_MAIL_RECEIVED_Ref_NO,CY_LUB_OIL_SAMPLE_LANDED,CY_CHECKD_FOR_STOWAWAYS,CY_STOWAWAYS_ON_BOARD,CY_DEP_GM_Mtr,CY_REQUISITIONS_RECEIVED,DISTANCE_TO_NEXT_PILOT,TUG_SAILING_TRANSIT,STEAMING_TIME_M_E_Rsdl_VLS,STEAMING_TIME_M_E_Rsdl_HS,STEAMING_TIME_M_E_Rsdl_ULS,STEAMING_TIME_M_E_Dstlt_VLS,STEAMING_TIME_M_E_Dstlt_ULS,STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS,STEAMING_TIME_M_E_HS,STEAMING_TIME_M_E_LS,STEAMING_TIME_M_E_MDO,STEAMING_TIME_M_E_MGO,STEAMING_TIME_M_E_MGO_LS,STEAMING_TIME_AUX_1,STEAMING_TIME_AUX_2,STEAMING_TIME_AUX_3,STEAMING_TIME_AUX_4,STEAMING_TIME_AUX_5,STEAMING_TIME_SH_GEN,STEAMING_TIME_TG,POWER_kW,STEAMING_LOAD_KW_AUX_1,STEAMING_LOAD_KW_AUX_2,STEAMING_LOAD_KW_AUX_3,STEAMING_LOAD_KW_AUX_4,STEAMING_LOAD_KW_AUX_5,STEAMING_LOAD_KW_SH_GEN,STEAMING_LOAD_KW_TG,FUEL_M_E_Rsdl_VLS,FUEL_M_E_Rsdl_HS,FUEL_M_E_Rsdl_ULS,FUEL_M_E_Dstlt_VLS,FUEL_M_E_Dstlt_ULS,FUEL_M_E_Tnktnr_Dstlt_VLS,FUEL_M_E_HS,FUEL_M_E_LS,FUEL_M_E_MDO,FUEL_M_E_MGO,FUEL_M_E_MGO_LS,FUEL_Aux_Rsdl_VLS,FUEL_Aux_Rsdl_HS,FUEL_Aux_Rsdl_ULS,FUEL_Aux_Dstlt_VLS,FUEL_Aux_Dstlt_ULS,FUEL_Aux_Tnktnr_Dstlt_VLS,FUEL_AUX_HS,FUEL_AUX_LS,FUEL_AUX_MDO,FUEL_AUX_MGO,FUEL_AUX_MGO_LS,FUEL_Boiler_Rsdl_VLS,FUEL_Boiler_Rsdl_HS,FUEL_Boiler_Rsdl_ULS,FUEL_Boiler_Dstlt_VLS,FUEL_Boiler_Dstlt_ULS,FUEL_Boiler_Tnktnr_Dstlt_VLS,FUEL_BOILER_HS,FUEL_BOILER_LS,FUEL_BOILER_MDO,FUEL_BOILER_MGO,FUEL_BOILER_MGO_LS,DECK_LAST_CHANGE_USER,ENGINE_LAST_CHANGE_USER,DECK_PART_IS_COMPLETE,ENGINE_PART_IS_COMPLETE,SCAVENGE_PRESSURE,SECA_ENTRY_TIME,SECA_ENTRY_LAT,SECA_ENTRY_LONG,SECA_EXIT_TIME,SECA_EXIT_LAT,SECA_EXIT_LONG,ROB_FRESH_WATER,MANVRNG_MILES_BY_GPS,MANVRNG_MILES_BY_SPEED_LOG,TANKTAINER_TRANSFD_QUANTITY,PILOT_TAKEN,DATE_TIME_START_TRANSIT,DATE_TIME_START_TRANSIT_Offset,DATE_TIME_END_TRANSIT,DATE_TIME_END_TRANSIT_Offset,BALLAST,TANKTAINER_NUMBER,STEAMING_KWHR_TOTAL,CY_OTHERS,ROB_FO_SLUDGE,ROB_LO_SLUDGE,ROB_BILGE,SLUDGE_REMOVED_FO,SLUDGE_REMOVED_LO,SEA_STATE,CY_LUB_ADDED_TO_SYSTEM_MECC,CY_LUB_ADDED_TO_SYSTEM_AECC,CY_LUB_ADDED_TO_THRUSTERS,CY_ME_LO_PURIFIER_IN_USE,CY_BALLAST,CY_BENDING_MOMENT,CY_SHEARING_FORCE,CY_TORTION_MOMENT,CY_SUPDT_AUDITOR_SIGNED_ON,CY_SUPDT_AUDITOR_SIGNED_OFF,CY_CASH_RECEIVED,CY_LUB_OIL_RECEIVED_MECYL,CY_LUB_OIL_RECEIVED_MECC,CY_LUB_OIL_RECEIVED_AECC,CY_M_E_UNDER_PISTON_TEMP,CY_MAIL_RECEIVED,WIND_DIRECTION_PORT_STBD,SEA_DIRECTION_PORT_STBD,TIME_PILOT_ONBOARD,GRADES_ROB,SO2_CO2_RATIO,Bunker_Order,Remarks,Fuel_Type,Carbon_Factor,Sulphur_Content_PC,Quantity,Port_Delivery,Product_Quality,Tanktainer_Number_1,Supplier,Delivery,Vol_Lt,Den,Vis,ROB_Dstlt_ULS,ROB_Dstlt_VLS,ROB_Rsdl_MDO,ROB_Tnktnr_Dstlt_VLS,ROB_Rsdl_VLS,ROB_Rsdl_HS,ROB_Rsdl_ULS,ROB_Fuel_HSFO,ROB_Fuel_LSFO,ROB_Fuel_MDO,ROB_Fuel_MGO,ROB_Fuel_MGO_LS,ROB_Fuel_Tanktainer_MGO,ECA_MILES,ECA_TIME,EGCS_DRY_WASTE_REMOVED,EGCS_RUNNING_TIME,EGCS_WET_SLURRY_REMOVED,EGCS_OPEN_LOOP_RUNNING_TIME,EGCS_CLOSED_LOOP_RUNNING_TIME,Voyage_Order,Voyage_Code,ECA,EU,Sea_Time,ETA_Country_Code,Port_Country_Code,check_ETA_code,check_Port_code,Status_TEMP_EU,FUEL_HS,FUEL_LS,FUEL_MDO,FUEL_MGO,FUEL_MGO_LS,Cargo_Transport_Work,TEU_Transport_Work,EEOI_Voyage_no,CARGO_TOTAL_Old,DRAFT,FO_per_24Hrs,SFOC,CY_OIL_gm_hr,SCOC,Voyage_Name,TOTAL_FO,TOTAL_CO2,EEOI,voyCondition,samedate,timesincelastreport,BDN,Wind_direction_360,True_wind_speed,True_wind_dir,ref_power,ref_fuel,fuel_loss,Relative_wind_speed,Relative_wind_direction,CAA,RW,Corrected_Power,draft_pow,draft_sp_pow,fo_nor,fo_model,sfoc_model,sfoc_deviation,ref_power_corrected,ref_FO_corrected,Propulsive_eff,speed_performance,Ref_speed,P_I,MEcon,AEcon,BLcon,Tcon,HS,LS,MDO,MGO,MGOLS,TCO2,AETsteaming,AEPOWER,TRIM,DISTANCECOVERED,updated_date,hyd_slip_sog,hyd_slip_stw,FUEL_Rsdl_HS,FUEL_Rsdl_VLS,FUEL_Rsdl_ULS,FUEL_Dstlt_VLS,FUEL_Dstlt_ULS,FUEL_Tnktnr_Dstlt_VLS,Rsdl_HS,Rsdl_VLS,Rsdl_ULS,Dstlt_VLS,Dstlt_ULS,Tnktnr_Dstlt_VLS
0,WDHG,0969ecda-c424-4a1a-8c65-bd515e7341a4,WEC DE HOOGH,9315018,EC137A,20/09/2021 00:00,20/09/2021 07:54,UTC +02:00,COSP,DRIFTING,NaN,NaN,NaN,NaN,0.88,7733.4,True,1.4,1.4,12.0,0.0,0.0000,0.0000,0.0,0.0,25.0,15,8.3,8.3,17442.8,279,1.27,25.00,461.0,17.0,15.0,NaN,ESVGO,44462.25,UTC +02:00,VIGO,NaN,1.4,NaN,NaN,14.5,NaN,NaN,0.0,0.0,27.0,71.0,128.0,NLRTM,ROTTERDAM,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,288,173,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,906.0,0.0,0.0,0.0,0.0,0.0,1.4,0.0,0.0,0.0,0.0,0,1.4,1.4,1.4,0.0,0.0,0.0,1.4,0.0,3153,150.0,150.0,0.0,0.0,0.0,600.0,0.0,0.0,0.0,0,0,0.88,0.0,0,0.0,0.0,0.0,0.88,0.0,0,0,0,0.09,0.0,0,0,0,0,0.09,0.0,0,0,0,0.00,0.0,0.0,0,0,0,0.00,NaN,NaN,True,True,1.7,NaN,NaN,NaN,NaN,NaN,NaN,56.0,12.0,12.0,NaN,TRUE,NaN,NaN,NaN,NaN,3833.9,0.0,420.0,NaN,NaN,NaN,0.0,NaN,NaN,4.0,0.0,0.0,0.0,Both,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,1.6,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,164.06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,164.06,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,101.0,NLRTM-ESVGO,N,Y,1.4,ES,NL,NaN,NaN,0,0.0,0.0,0.0,0.0,0.97,92800.8,5532.0,101.0,0,8.3,15.0857,199.357,0,0,0,0.97,3.10982,0,Laden,0,NaN,NO,25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.88,0.09,0.00,0.97,0.0,0.0,0.0,0.0,0.97,3.11,2.8,300,0.0,12.0,23/03/2022 20:39,NaN,NaN,0.0,0.0,0,0,0.97,0.0,0.0,0.0,0,0,0.97,0.0
1,WDHG,100aacb7-9173-4e7b-9a84-e7e78eb5933d,WEC DE HOOGH,9315018,EC137A,20/09/2021 00:00,20/09/2021 12:00,UTC +02:00,NOON,AT SEA,5140N,00219W,51.666667,-2.316667,4.20,7733.4,True,4.1,4.1,65.9,0.0,16.0488,16.0732,78.0,0.0,35.0,15,8.3,8.3,17442.8,223,0.50,113.75,461.0,19.0,16.0,65.8,ESVGO,44462.25,UTC +02:00,VIGO,NaN,4.1,395.0,439.0,14.5,840.0,60.0,0.0,0.0,27.0,71.0,0.0,NLRTM,ROTTERDAM,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,288,173,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,4.1,0.0,0.0,0.0,0.0,0,4.1,0.0,0.0,0.0,0.0,0.0,4.1,0.0,5119,0.0,0.0,0.0,0.0,0.0,600.0,0.0,0.0,0.0,0,0,4.20,0.0,0,0.0,0.0,0.0,4.20,0.0,0,0,0,0.00,0.0,0,0,0,0,0.00,0.0,0,0,0,0.00,0.0,0.0,0,0,0,0.00,NaN,NaN,True,True,1.2,NaN,NaN,NaN,NaN,NaN,NaN,56.0,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,3833.9,0.0,5119.0,NaN,NaN,NaN,0.0,NaN,NaN,2.0,0.0,0.0,0.0,Both,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,159.86,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,159.86,0.0,65.9,4.1,NaN,0.0,NaN,0.0,0.0,101.0,NLRTM-ESVGO,N,Y,4.1,ES,NL,NaN,NaN,0,0.0,0.0,0.0,0.0,4.20,509631.0,30379.9,101.0,0,8.3,24.5854,200.115,0,0,0,4.20,13.46520,0,Laden,0,NaN,NO,325,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4.20,0.00,0.00,4.20,0.0,0.0,0.0,0.0,4.20,13.47,0.0,0,0.0,65.9,23/03/2022 20:39,NaN,NaN,0.0,0.0,0,0,4.20,0.0,0.0,0.0,0,0,4.20,0.0
2,WDHG,11b92cc4-6eda-4b5c-b4c4-f0ea291cfb91,WEC DE HOOGH,9315018,NaN,20/09/2021 00:00,20/09/2021 06:30,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,7733.4,False,NaN,NaN,0.0,NaN,0.0000,0.0000,0.0,0.0,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,288,173,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.00,0.0,0,0.0,0.0,0.0,0.00,0.0,0,0,0,0.00,0.0,0,0,0,0,0.00,0.0,0,0,0,0.00,0.0,0.0,0,0,0,0.00,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.0,NLRTM-ESVGO,N,Y,0.0,ES,NL,NaN,NaN,0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,101.0,0,0.0,0.0000,0.000,0,0,0,0.00,0.00000,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0,0.0,0.0,07/10/2021 08:39,NaN,NaN,0.0,0.0,0,0,0.00,0.0,0.0,0.0,0,0,0.00,0.0
3,WDHG,1ca21df8-d4ab-4af2-9f84-8d0075ed3c45,WEC DE HOOGH,9315018,EC137A,20/09/2021 00:00,20/09/2021 06:30,UTC +02:00,SAIL,IN PORT,NaN,NaN,NaN,NaN,0.00,7733.4,True,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0,0.0,0,8.3,8.3,17442.8,0,0.00,0.00,461.0,NaN,NaN,NaN,ESVGO,44462.25,UTC +02:00,VIGO,NaN,100.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,27.0,71.0,0.0,NLRTM,ROTTERDAM,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,1647.9,432.8,288,173,0.0,NaN,False,False,0.0,0.0,0.0,No,0.0,0.0,1,0.0,0.8,526-00009_ 526-00010_526-00011_ 526-00003_ 526...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,7.5,7.5,0.0,0.0,0.0,0.0,0.0,0,280.0,280.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.00,0.0,0,0.0,0.0,0.0,0.00,0.0,0,0,0,0.88,0.0,0,0,0,0,0.88,0.0,0,0,0,0.15,0.0,0.0,0,0,0,0.15,NaN,NaN,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.0,0.0,NaN,0.0,FALSE,NaN,NaN,NaN,NaN,3833.9,0.0,4200.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,500.0,0.0,0.0,Both,NaN,73.0,66.0,50.0,0.0,0.0,0.0,0.0,0.0,3895.0,NaN,False,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.03,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,101.0,NLRTM-ESVGO,N,Y,0.0,ES,NL,NaN,NaN,0,0.0,0.0,0.0,0.0,1.03,0.0,0.0,100.0,0,8.3,0.0000,0.000,0,0,0,1.03,3.30218,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.88,0.15,1.03,0.0,0.0,0.0,0.0,1.03,3.30,15.0,560,0.0,0.0,23/03/2022 20:39,NaN,NaN,0.0,0.0,0,0,1.03,0.0,0.0,0.0,0,0,1.03,0.0
4,WDHG,4276b8fc-c70a-45e2-9a7d-b87415ff1691,WEC DE HOOGH,9315018,NaN,20/09/2021 00:00,20/09/2021 06:30,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,7733.4,False,NaN,NaN,0.0,NaN,0.0000,0.0000,0.0,0.0,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,288,173,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.00,0.0,0,0.0,0.0,0.0,0.00,0.0,0,0,0,0.00,0.0,0,0,0,0,0.00,0.0,0,0,0,0.00,0.0,0.0,0,0,0,0.00,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.0,NLRTM-ESVGO,N,Y,0.0,ES,NL,NaN,NaN,0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,101.0,0,0.0,0.0000,0.000,0,0,0,0.00,0.00000,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0,0.0,0.0,07/10/2021 08:39,NaN,NaN,0.0,0.0,0,0,0.00,0.0,0.0,0.0,0,0,0.00,0.0

In [34]:
df=data.copy()

In [35]:
df['REPORT_DATE_TIME'] = pd.to_datetime(df['REPORT_DATE_TIME'], format='%d/%m/%Y %H:%M', errors='coerce')

# Extract the date and time components
df['Date'] = df['REPORT_DATE_TIME'].dt.date
df['Time'] = df['REPORT_DATE_TIME'].dt.time

# Convert the 'Date' column to datetime
df['Date'] = pd.to_datetime(df['Date'])

# Filter for the year 2021
cii_year = 2023
Res_dfn = df[df['Date'].dt.year == cii_year]
Res_dfn.set_index('Date', inplace=True)

In [36]:
Res_dfn.head()

,idvessel,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,LAT,LONG_,LATITUDE,LONGITUDE,M_E_FOC,CARGO_TOTAL,Has_Cargo,TOTAL_STEAMING_TIME,M_E_Fuel_Only_Steaming_Time,MILES_BY_GPS,OIL_CYL,SOW,SOG,RPM,SLIP,WIND_DIRECTION,WIND_SPEED,DRAFT_AFT,DRAFT_FWD,DISPLACEMENT,COURSE_AT_SEA,WAVE_HEIGHT,SEA_DIRECTION,CARGO_TOTAL_TEU,AMBIENT_TEMP,SW_TEMP,MILES_BY_SPEED_LOG,ETA_PORT_CODE,ETA_DATE_TIME,ETA_DATE_TIME_Offset,ETA_PORT,TIME_CHANGE,TIME_SEA,TEMP_MIN,TEMP_MAX,REQUESTED_SPEED,REM_DIST_TO_PILOT,REM_TIME_TO_PILOT,TOTAL_UNPLND_STPGE_TECH,TOTAL_UNPLND_STPGE_OPE_WX,REEFERS_POSITIVE_PLUGGED,REEFERS_NEGATIVE_PLUGGED,ME_TOTAL_REVS_COUNTER,PORT_CODE,PORT,AUX_BLOWERS_ON,HOLD_VENTILATION_ON,SINCE_DATE_TIME,SINCE_DATE_TIME_Offset,TIME_HRS_ANCHOR,TIME_HRS_DRIFT,REASON,TYPE_OF_DELAY,ETB_DATE_TIME,ETB_DATE_TIME_Offset,PILOT_DATE_TIME,PILOT_DATE_TIME_Offset,TIME_MANOEUVRING,TUG_ARR,TUG_SHIFT,ETD_DATE_TIME,ETD_DATE_TIME_Offset,SHIFT_BERTH_HOURS,CARGO_LOAD,CARGO_DISCH,TEU_FULL,TEU_EMPTY,BILGE_REMOVED,GARBAGE_REMOVED,GARBAGE_REMVL_REQSTD,GARBAGE_REMVL_CMPLSRY,FW_SUPPLY,CY_CREW_SIGNED_ON,CY_CREW_SIGNED_OFF,CY_DOCTORS_VISIT,CY_MAIL_RECEIVED_Ref_NO,CY_LUB_OIL_SAMPLE_LANDED,CY_CHECKD_FOR_STOWAWAYS,CY_STOWAWAYS_ON_BOARD,CY_DEP_GM_Mtr,CY_REQUISITIONS_RECEIVED,DISTANCE_TO_NEXT_PILOT,TUG_SAILING_TRANSIT,STEAMING_TIME_M_E_Rsdl_VLS,STEAMING_TIME_M_E_Rsdl_HS,STEAMING_TIME_M_E_Rsdl_ULS,STEAMING_TIME_M_E_Dstlt_VLS,STEAMING_TIME_M_E_Dstlt_ULS,STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS,STEAMING_TIME_M_E_HS,STEAMING_TIME_M_E_LS,STEAMING_TIME_M_E_MDO,STEAMING_TIME_M_E_MGO,STEAMING_TIME_M_E_MGO_LS,STEAMING_TIME_AUX_1,STEAMING_TIME_AUX_2,STEAMING_TIME_AUX_3,STEAMING_TIME_AUX_4,STEAMING_TIME_AUX_5,STEAMING_TIME_SH_GEN,STEAMING_TIME_TG,POWER_kW,STEAMING_LOAD_KW_AUX_1,STEAMING_LOAD_KW_AUX_2,STEAMING_LOAD_KW_AUX_3,STEAMING_LOAD_KW_AUX_4,STEAMING_LOAD_KW_AUX_5,STEAMING_LOAD_KW_SH_GEN,STEAMING_LOAD_KW_TG,FUEL_M_E_Rsdl_VLS,FUEL_M_E_Rsdl_HS,FUEL_M_E_Rsdl_ULS,FUEL_M_E_Dstlt_VLS,FUEL_M_E_Dstlt_ULS,FUEL_M_E_Tnktnr_Dstlt_VLS,FUEL_M_E_HS,FUEL_M_E_LS,FUEL_M_E_MDO,FUEL_M_E_MGO,FUEL_M_E_MGO_LS,FUEL_Aux_Rsdl_VLS,FUEL_Aux_Rsdl_HS,FUEL_Aux_Rsdl_ULS,FUEL_Aux_Dstlt_VLS,FUEL_Aux_Dstlt_ULS,FUEL_Aux_Tnktnr_Dstlt_VLS,FUEL_AUX_HS,FUEL_AUX_LS,FUEL_AUX_MDO,FUEL_AUX_MGO,FUEL_AUX_MGO_LS,FUEL_Boiler_Rsdl_VLS,FUEL_Boiler_Rsdl_HS,FUEL_Boiler_Rsdl_ULS,FUEL_Boiler_Dstlt_VLS,FUEL_Boiler_Dstlt_ULS,FUEL_Boiler_Tnktnr_Dstlt_VLS,FUEL_BOILER_HS,FUEL_BOILER_LS,FUEL_BOILER_MDO,FUEL_BOILER_MGO,FUEL_BOILER_MGO_LS,DECK_LAST_CHANGE_USER,ENGINE_LAST_CHANGE_USER,DECK_PART_IS_COMPLETE,ENGINE_PART_IS_COMPLETE,SCAVENGE_PRESSURE,SECA_ENTRY_TIME,SECA_ENTRY_LAT,SECA_ENTRY_LONG,SECA_EXIT_TIME,SECA_EXIT_LAT,SECA_EXIT_LONG,ROB_FRESH_WATER,MANVRNG_MILES_BY_GPS,MANVRNG_MILES_BY_SPEED_LOG,TANKTAINER_TRANSFD_QUANTITY,PILOT_TAKEN,DATE_TIME_START_TRANSIT,DATE_TIME_START_TRANSIT_Offset,DATE_TIME_END_TRANSIT,DATE_TIME_END_TRANSIT_Offset,BALLAST,TANKTAINER_NUMBER,STEAMING_KWHR_TOTAL,CY_OTHERS,ROB_FO_SLUDGE,ROB_LO_SLUDGE,ROB_BILGE,SLUDGE_REMOVED_FO,SLUDGE_REMOVED_LO,SEA_STATE,CY_LUB_ADDED_TO_SYSTEM_MECC,CY_LUB_ADDED_TO_SYSTEM_AECC,CY_LUB_ADDED_TO_THRUSTERS,CY_ME_LO_PURIFIER_IN_USE,CY_BALLAST,CY_BENDING_MOMENT,CY_SHEARING_FORCE,CY_TORTION_MOMENT,CY_SUPDT_AUDITOR_SIGNED_ON,CY_SUPDT_AUDITOR_SIGNED_OFF,CY_CASH_RECEIVED,CY_LUB_OIL_RECEIVED_MECYL,CY_LUB_OIL_RECEIVED_MECC,CY_LUB_OIL_RECEIVED_AECC,CY_M_E_UNDER_PISTON_TEMP,CY_MAIL_RECEIVED,WIND_DIRECTION_PORT_STBD,SEA_DIRECTION_PORT_STBD,TIME_PILOT_ONBOARD,GRADES_ROB,SO2_CO2_RATIO,Bunker_Order,Remarks,Fuel_Type,Carbon_Factor,Sulphur_Content_PC,Quantity,Port_Delivery,Product_Quality,Tanktainer_Number_1,Supplier,Delivery,Vol_Lt,Den,Vis,ROB_Dstlt_ULS,ROB_Dstlt_VLS,ROB_Rsdl_MDO,ROB_Tnktnr_Dstlt_VLS,ROB_Rsdl_VLS,ROB_Rsdl_HS,ROB_Rsdl_ULS,ROB_Fuel_HSFO,ROB_Fuel_LSFO,ROB_Fuel_MDO,ROB_Fuel_MGO,ROB_Fuel_MGO_LS,ROB_Fuel_Tanktainer_MGO,ECA_MILES,ECA_TIME,EGCS_DRY_WASTE_REMOVED,EGCS_RUNNING_TIME,EGCS_WET_SLURRY_REMOVED,EGCS_OPEN_LOOP_RUNNING_TIME,EGCS_CLOSED_LOOP_RUNNING_TIME,Voyage_Order,Voyage_Code,ECA,EU,Sea_Time,ETA_Country_Code,Port_Country_Code,check_ETA_code,check_Port_code,Status_TEMP_EU,FUEL_HS,FUEL_LS,FUEL_MDO,FUEL_MGO,FUEL_MGO_LS,Cargo_Transport_Work,TEU_Transport_Work,EEOI_Voyage_no,CARGO_TOTAL_Old,DRAFT,FO_per_24Hrs,SFOC,CY_OIL_gm_hr,SCOC,Voyage_Name,TOTAL_FO,TOTAL_CO2,EEOI,voyCondition,samedate,timesincelastreport,BDN,Wind_direction_360,True_wind_speed,True_wind_dir,ref_power,ref_fuel,fuel_loss,Relative_wind_speed,Relative_wind_direction,CAA,RW,Corrected_Power,draft_pow,draft_sp_pow,fo_nor,fo_model,sfoc_model,sfoc_deviation,ref_power_corrected,ref_FO_corrected,Propulsive_eff,speed_performance,Ref_speed,P_I,MEcon,AEcon,BLcon,Tcon,HS,LS,MDO,MGO,MGOLS,TCO2,AETsteaming,AEPOWER,TRIM,DISTANCECOVERED,updated_date,hyd_slip_sog,hyd_slip_stw,FUEL_Rsdl_HS,FUEL_Rsdl_VLS,FUEL_Rsdl_ULS,FUEL_Dstlt_VLS,FUEL_Dstlt_ULS,FUEL_Tnktnr_Dstlt_VLS,Rsdl_HS,Rsdl_VLS,Rsdl_ULS,Dstlt_VLS,Dstlt_ULS,Tnktnr_Dstlt_VLS,Time
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023-01-01,WDHG,537da5c5-a2fd-48e7-af01-46ba197f468a,WEC DE HOOGH,9315018,EC249A,01/01/2023 00:00,2023-01-01 12:00:00,UTC +01:00,NOON,AT SEA,5005N,00226W,50.083333,-2.433333,15.44,9688.2,True,16.0,16.0,185.2,0.0,11.9500,11.5750,128.7,2.0,45.0,30,8.6,8.5,17684.0,254,3.06,65.57,605.0,12.0,8.0,191.2,ESVGO,03/01/2023 05:00,UTC +00:00,VIGO,NaN,16.0,405.0,435.0,15.8,628.2,42.0,0.0,0.0,9.0,24.0,82839.0,GBTHP,THAMESPORT,False,False,NaN,NaN,NaN,NaN,AWATING FOR BERTHING,NaN,31/12/2022 07:15,UTC +01:00,NaN,NaN,NaN,NaN,NaN,31/12/2022 20:00,UTC +00:00,NaN,NaN,NaN,301,410,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,16.0,0.0,0.0,0.0,0.0,0,16.0,0.0,0.0,0.0,0.0,0.0,16.0,0.0,5099,0.0,0.0,0.0,0.0,0.0,305.0,0.0,0.00,0.0,0,0,15.44,0.0,0,0.00,0.0,0.0,15.44,0.0,0,0,0,0.0,0.0,0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0.0,0,0,0,0.0,2O,CE,True,True,1.5,NaN,NaN,NaN,NaN,NaN,NaN,37.0,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,3531.0,0.0,77238.0,NaN,NaN,NaN,0.1,NaN,NaN,5.0,0.0,0.0,0.0,Both,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,247.60,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,247.60,0.0,185.2,16.0,NaN,0.0,NaN,0.0,0.0,309.0,PTLIS-PTSET,N,Y,16.0,PT,PT,NaN,NaN,0,0.0,0.00,0.0,0.0,15.44,1794250.0,131677.0,309.0,0,8.55,23.1600,189.2530,0,0,0,15.44,49.5006,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15.44,0.0,0.0,15.44,0.0,0.00,0.0,0.0,15.44,49.50,0.0,0,0.1,185.2,14/02/2023 14:18,NaN,NaN,0.0,0.00,0,0,15.44,0.0,0.0,0.00,0,0,15.44,0.0,12:00:00
2023-01-02,WDHG,c4b0b4c6-4f1f-49f3-832e-ace51920be18,WEC DE HOOGH,9315018,EC249A,02/01/2023 00:00,2023-01-02 12:00:00,UTC +01:00,NOON,AT SEA,4627N,00738W,46.450000,-7.633333,26.70,9688.2,True,24.0,24.0,314.6,0.0,13.1083,13.1083,128.7,0.6,23.0,38,8.5,8.4,17684.0,208,3.94,34.17,605.0,12.0,8.0,314.6,ESVGO,03/01/2023 09:00,UTC +00:00,VIGO,NaN,24.0,405.0,440.0,14.3,313.3,22.0,0.0,0.0,9.0,24.0,82863.0,GBTHP,THAMESPORT,False,False,NaN,NaN,NaN,NaN,AWATING FOR BERTHING,NaN,31/12/2022 07:15,UTC +01:00,NaN,NaN,NaN,NaN,NaN,31/12/2022 20:00,UTC +00:00,NaN,NaN,NaN,301,410,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,0.0,0.0,0.0,24.0,0.0,0.0,24.0,0.0,0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,5800,0.0,0.0,0.0,0.0,0.0,300.0,0.0,16.53,0.0,0,0,10.17,0.0,0,16.53,0.0,0.0,10.17,0.0,0,0,0,0.0,0.0,0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0.0,0,0,0,0.0,2O,CE,True,True,2.1,NaN,NaN,NaN,NaN,NaN,NaN,48.0,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,3531.0,0.0,82638.0,NaN,NaN,NaN,0.1,NaN,NaN,5.0,0.0,0.0,0.0,Both,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,237.43,0.0,0.0,0.0,286.27,0.0,0.0,0.0,286.27,0.0,0.0,237.43,0.0,111.6,9.4,NaN,0.0,NaN,0.0,0.0,309.0,PTLIS-PTSET,N,Y,48.0,PT,PT,NaN,NaN,0,0.0,16.53,0.0,0.0,10.17,3047910.0,223681.0,309.0,0,8.45,13.3500,95.9052,0,0,0,26.70,84.0794,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,26.70,0.0,0.0,26.70,0.0,16.53,0.0,0.0,10.17,84.08,0.0,0,0.1,314.6,14/02/2023 14:18,NaN,NaN,0.0,16.53,0,0,10.17,0.0,0.0,16.53,0,0,10.17,0.0,12:00:00
2023-01-03,WDHG,7004b66b-dd9a-4e82-9de5-3c4a6dafdeb3,WEC DE HOOGH,9315018,EC249A,03/01/2023 00:00,2023-01-03 09:30:00,UTC +01:00,EOSP,AT SEA,4217N,00856W,42.283333,-8.933333,24.70,9688.2,True,21.5,21.5,305.0,0.0,14.2093,14.1860,128.7,1.3,5.0,30,8.5,8.4,17684.0,125,1.43,9.46,605.0,11.0,8.0,305.5,ESVGO,03/01/2023 09:00,UTC +00:00,NaN,NaN,21.5,403.0,445.0,14.3,NaN,NaN,0.0,0.0,9.0,24.0,82885.0,ESVGO,VIGO,False,False,NaN,NaN,NaN,NaN,AWATING FOR BERTHING,NaN,03/01/2023 12:30,UTC +01:00,NaN,NaN,NaN,NaN,NaN,31/12/2022 20:00,UTC +00:00,NaN,NaN,NaN,301,410,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.5,0.0,0.0,0.0,0.0,0.0,0.0,21.5,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,21.5,0.0,5936,0.0,0.0,0.0,0.0,0.0,300.0,0.0,24.70,0.0,0,0,0.00,0.0,0,24.70,0.0,0.0,0.00,0.0,0,0,0,0.0,0.0,0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0.0,0,0,0,0.0,2O,CE,True,True,2.2,NaN,NaN,NaN,NaN,NaN,NaN,50.0,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,3531.0,0.0,123516.0,NaN,NaN,NaN,0.1,NaN,NaN,4.0,0.0,0.0,0.0,Both,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,261.57,0.0,0.0,0.0,261.57,0.0,0.0,0.00,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,309.0,PTLIS-PTSET,N,Y,21.5,PT,PT,NaN,NaN,0,0.0,24.70,0.0,0.0,0.00,2954900.0,216855.0,309.0,0,8.45,27.5721,193.5370,0,0,0,24.70,76.9158,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24.70,0.0,0.0,24.70,0.0,24.70,0.0,0.0,0.00,76.92,0.0,0,0.1,305.0,14/02/2023 14:18,NaN,NaN,0.0,24.70,0,0,0.00,0.0,0.0,24.70,0,0,0.00,0.0,09:30:00
2023-01-03,WDHG,0478d78d-4d64-4c96-a620-2430d15eac27,WEC DE HOOGH,9315018,NaN,04/01/2023 00:00,2023-01-03 12:59:00,UTC +01:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,9688.2,False,NaN,NaN,0.0,NaN,0.0000,0.0000,0.0,0.0,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,301,410,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0,0,0.00,0.0,0,0.00,0.0,0.0,0.00,0.0,0,0,0,0.0,0.0,0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0.0,0,0,0,0.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,309.0,PTLIS-PTSET,N,Y,0.0,PT,PT,NaN,NaN,0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,309.0,0,0.00,0.0000,0.0000,0,0,0,0.00,0.0000,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.0,0,0.0,0.0,14/02/2023 12:03,NaN,NaN,0.0,0.00,0,0,0.00,0.0,0.0,0.00,0,0,0.00,0.0,12:59:00
2023-01-03,WDHG,0529d3c5-e8ca-405b-bb5a-6ccdec18e1b1,WEC DE HOOGH,9315018,NaN,04/01/2023 00:00,2023-01-03 12:59:00,UTC +01:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,9688.2,False,NaN,NaN,0.0,NaN,0.0000,0.0000,0.0,0.0,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,301,410,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0,0,0.00,0.0,0,0.00,0.0,0.0,0.00,0.0,0,0,0,0.0,0.0,0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0.0,0,0,0,0.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,309.0,PTLIS-PTSET,N,Y,0.0,PT,PT,NaN,NaN,0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,309.0,0,0.00,0.0000,0.0000,0,0,0,0.00,0.0000,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.0,0,0.0,0.0,14/02/2023 12:03,NaN,NaN,0.0,0.00,0,0,0.00,0.0,0.0,0.00,0,0,0.00,0.0,12:59:00

In [37]:
Res_dfn = Res_dfn.sort_values(by='REPORT_DATE_TIME')

In [38]:
start_date = '2023-07-11'
end_date = '2023-08-11'
start_date = pd.to_datetime(start_date, format='%Y-%m-%d')
end_date = pd.to_datetime(end_date, format='%Y-%m-%d')

filtered_df = Res_dfn[(Res_dfn['REPORT_DATE_TIME'] >= start_date) & (Res_dfn['REPORT_DATE_TIME'] <= end_date)]

In [39]:
filtered_df.head()

,idvessel,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,LAT,LONG_,LATITUDE,LONGITUDE,M_E_FOC,CARGO_TOTAL,Has_Cargo,TOTAL_STEAMING_TIME,M_E_Fuel_Only_Steaming_Time,MILES_BY_GPS,OIL_CYL,SOW,SOG,RPM,SLIP,WIND_DIRECTION,WIND_SPEED,DRAFT_AFT,DRAFT_FWD,DISPLACEMENT,COURSE_AT_SEA,WAVE_HEIGHT,SEA_DIRECTION,CARGO_TOTAL_TEU,AMBIENT_TEMP,SW_TEMP,MILES_BY_SPEED_LOG,ETA_PORT_CODE,ETA_DATE_TIME,ETA_DATE_TIME_Offset,ETA_PORT,TIME_CHANGE,TIME_SEA,TEMP_MIN,TEMP_MAX,REQUESTED_SPEED,REM_DIST_TO_PILOT,REM_TIME_TO_PILOT,TOTAL_UNPLND_STPGE_TECH,TOTAL_UNPLND_STPGE_OPE_WX,REEFERS_POSITIVE_PLUGGED,REEFERS_NEGATIVE_PLUGGED,ME_TOTAL_REVS_COUNTER,PORT_CODE,PORT,AUX_BLOWERS_ON,HOLD_VENTILATION_ON,SINCE_DATE_TIME,SINCE_DATE_TIME_Offset,TIME_HRS_ANCHOR,TIME_HRS_DRIFT,REASON,TYPE_OF_DELAY,ETB_DATE_TIME,ETB_DATE_TIME_Offset,PILOT_DATE_TIME,PILOT_DATE_TIME_Offset,TIME_MANOEUVRING,TUG_ARR,TUG_SHIFT,ETD_DATE_TIME,ETD_DATE_TIME_Offset,SHIFT_BERTH_HOURS,CARGO_LOAD,CARGO_DISCH,TEU_FULL,TEU_EMPTY,BILGE_REMOVED,GARBAGE_REMOVED,GARBAGE_REMVL_REQSTD,GARBAGE_REMVL_CMPLSRY,FW_SUPPLY,CY_CREW_SIGNED_ON,CY_CREW_SIGNED_OFF,CY_DOCTORS_VISIT,CY_MAIL_RECEIVED_Ref_NO,CY_LUB_OIL_SAMPLE_LANDED,CY_CHECKD_FOR_STOWAWAYS,CY_STOWAWAYS_ON_BOARD,CY_DEP_GM_Mtr,CY_REQUISITIONS_RECEIVED,DISTANCE_TO_NEXT_PILOT,TUG_SAILING_TRANSIT,STEAMING_TIME_M_E_Rsdl_VLS,STEAMING_TIME_M_E_Rsdl_HS,STEAMING_TIME_M_E_Rsdl_ULS,STEAMING_TIME_M_E_Dstlt_VLS,STEAMING_TIME_M_E_Dstlt_ULS,STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS,STEAMING_TIME_M_E_HS,STEAMING_TIME_M_E_LS,STEAMING_TIME_M_E_MDO,STEAMING_TIME_M_E_MGO,STEAMING_TIME_M_E_MGO_LS,STEAMING_TIME_AUX_1,STEAMING_TIME_AUX_2,STEAMING_TIME_AUX_3,STEAMING_TIME_AUX_4,STEAMING_TIME_AUX_5,STEAMING_TIME_SH_GEN,STEAMING_TIME_TG,POWER_kW,STEAMING_LOAD_KW_AUX_1,STEAMING_LOAD_KW_AUX_2,STEAMING_LOAD_KW_AUX_3,STEAMING_LOAD_KW_AUX_4,STEAMING_LOAD_KW_AUX_5,STEAMING_LOAD_KW_SH_GEN,STEAMING_LOAD_KW_TG,FUEL_M_E_Rsdl_VLS,FUEL_M_E_Rsdl_HS,FUEL_M_E_Rsdl_ULS,FUEL_M_E_Dstlt_VLS,FUEL_M_E_Dstlt_ULS,FUEL_M_E_Tnktnr_Dstlt_VLS,FUEL_M_E_HS,FUEL_M_E_LS,FUEL_M_E_MDO,FUEL_M_E_MGO,FUEL_M_E_MGO_LS,FUEL_Aux_Rsdl_VLS,FUEL_Aux_Rsdl_HS,FUEL_Aux_Rsdl_ULS,FUEL_Aux_Dstlt_VLS,FUEL_Aux_Dstlt_ULS,FUEL_Aux_Tnktnr_Dstlt_VLS,FUEL_AUX_HS,FUEL_AUX_LS,FUEL_AUX_MDO,FUEL_AUX_MGO,FUEL_AUX_MGO_LS,FUEL_Boiler_Rsdl_VLS,FUEL_Boiler_Rsdl_HS,FUEL_Boiler_Rsdl_ULS,FUEL_Boiler_Dstlt_VLS,FUEL_Boiler_Dstlt_ULS,FUEL_Boiler_Tnktnr_Dstlt_VLS,FUEL_BOILER_HS,FUEL_BOILER_LS,FUEL_BOILER_MDO,FUEL_BOILER_MGO,FUEL_BOILER_MGO_LS,DECK_LAST_CHANGE_USER,ENGINE_LAST_CHANGE_USER,DECK_PART_IS_COMPLETE,ENGINE_PART_IS_COMPLETE,SCAVENGE_PRESSURE,SECA_ENTRY_TIME,SECA_ENTRY_LAT,SECA_ENTRY_LONG,SECA_EXIT_TIME,SECA_EXIT_LAT,SECA_EXIT_LONG,ROB_FRESH_WATER,MANVRNG_MILES_BY_GPS,MANVRNG_MILES_BY_SPEED_LOG,TANKTAINER_TRANSFD_QUANTITY,PILOT_TAKEN,DATE_TIME_START_TRANSIT,DATE_TIME_START_TRANSIT_Offset,DATE_TIME_END_TRANSIT,DATE_TIME_END_TRANSIT_Offset,BALLAST,TANKTAINER_NUMBER,STEAMING_KWHR_TOTAL,CY_OTHERS,ROB_FO_SLUDGE,ROB_LO_SLUDGE,ROB_BILGE,SLUDGE_REMOVED_FO,SLUDGE_REMOVED_LO,SEA_STATE,CY_LUB_ADDED_TO_SYSTEM_MECC,CY_LUB_ADDED_TO_SYSTEM_AECC,CY_LUB_ADDED_TO_THRUSTERS,CY_ME_LO_PURIFIER_IN_USE,CY_BALLAST,CY_BENDING_MOMENT,CY_SHEARING_FORCE,CY_TORTION_MOMENT,CY_SUPDT_AUDITOR_SIGNED_ON,CY_SUPDT_AUDITOR_SIGNED_OFF,CY_CASH_RECEIVED,CY_LUB_OIL_RECEIVED_MECYL,CY_LUB_OIL_RECEIVED_MECC,CY_LUB_OIL_RECEIVED_AECC,CY_M_E_UNDER_PISTON_TEMP,CY_MAIL_RECEIVED,WIND_DIRECTION_PORT_STBD,SEA_DIRECTION_PORT_STBD,TIME_PILOT_ONBOARD,GRADES_ROB,SO2_CO2_RATIO,Bunker_Order,Remarks,Fuel_Type,Carbon_Factor,Sulphur_Content_PC,Quantity,Port_Delivery,Product_Quality,Tanktainer_Number_1,Supplier,Delivery,Vol_Lt,Den,Vis,ROB_Dstlt_ULS,ROB_Dstlt_VLS,ROB_Rsdl_MDO,ROB_Tnktnr_Dstlt_VLS,ROB_Rsdl_VLS,ROB_Rsdl_HS,ROB_Rsdl_ULS,ROB_Fuel_HSFO,ROB_Fuel_LSFO,ROB_Fuel_MDO,ROB_Fuel_MGO,ROB_Fuel_MGO_LS,ROB_Fuel_Tanktainer_MGO,ECA_MILES,ECA_TIME,EGCS_DRY_WASTE_REMOVED,EGCS_RUNNING_TIME,EGCS_WET_SLURRY_REMOVED,EGCS_OPEN_LOOP_RUNNING_TIME,EGCS_CLOSED_LOOP_RUNNING_TIME,Voyage_Order,Voyage_Code,ECA,EU,Sea_Time,ETA_Country_Code,Port_Country_Code,check_ETA_code,check_Port_code,Status_TEMP_EU,FUEL_HS,FUEL_LS,FUEL_MDO,FUEL_MGO,FUEL_MGO_LS,Cargo_Transport_Work,TEU_Transport_Work,EEOI_Voyage_no,CARGO_TOTAL_Old,DRAFT,FO_per_24Hrs,SFOC,CY_OIL_gm_hr,SCOC,Voyage_Name,TOTAL_FO,TOTAL_CO2,EEOI,voyCondition,samedate,timesincelastreport,BDN,Wind_direction_360,True_wind_speed,True_wind_dir,ref_power,ref_fuel,fuel_loss,Relative_wind_speed,Relative_wind_direction,CAA,RW,Corrected_Power,draft_pow,draft_sp_pow,fo_nor,fo_model,sfoc_model,sfoc_deviation,ref_power_corrected,ref_FO_corrected,Propulsive_eff,speed_performance,Ref_speed,P_I,MEcon,AEcon,BLcon,Tcon,HS,LS,MDO,MGO,MGOLS,TCO2,AETsteaming,AEPOWER,TRIM,DISTANCECOVERED,updated_date,hyd_slip_sog,hyd_slip_stw,FUEL_Rsdl_HS,FUEL_Rsdl_VLS,FUEL_Rsdl_ULS,FUEL_Dstlt_VLS,FUEL_Dstlt_ULS,FUEL_Tnktnr_Dstlt_VLS,Rsdl_HS,Rsdl_VLS,Rsdl_ULS,Dstlt_VLS,Dstlt_ULS,Tnktnr_Dstlt_VLS,Time
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023-07-11,WDHG,14828884-8b12-4801-b953-9ef58701dfd4,WEC DE HOOGH,9315018,EC327,11/07/2023 00:00,2023-07-11 12:00:00,UTC +02:00,PORT,IN PORT,5158N,00337E,51.966667,3.616667,0.00,5260.3,True,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,7.8,6.4,14100.0,0,0.0,0.0,592.0,24.0,18.0,NaN,NLMOE,06/07/2023 08:30,UTC +02:00,NaN,NaN,24.0,401.0,435.0,13.8,NaN,NaN,0.0,0.0,1.0,8.0,85393.0,NLMOE,MOERDIJK,False,False,NaN,NaN,NaN,NaN,bearth occupied,NaN,06/07/2023 13:00,UTC +02:00,NaN,NaN,NaN,NaN,NaN,11/07/2023 12:00,UTC +02:00,NaN,NaN,NaN,341,251,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0,350.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.00,0.0,0,0.0,0.0,0.0,0.00,0.0,0,0,0,1.76,0.0,0,0,0,0,1.76,0.0,0,0,0,0.96,0.0,0.0,0,0,0,0.96,2O,CE,TRUE,TRUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,3200.0,0.0,8400.0,NaN,NaN,NaN,2.6,NaN,NaN,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,253.68,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,253.68,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,362.0,GBTHP-NLMOE,N,Y,0.0,NL,GB,NaN,NaN,0,0.0,0.0,0.0,0.0,2.72,0.0,0.0,362.0,0,7.1,0.0000,0.000,0,0,0,2.72,8.72032,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,1.76,0.96,2.72,0.0,0.0,0.0,0.0,2.72,8.72,24.0,350,1.4,0.0,07/08/2023 10:33,NaN,NaN,0.0,0.0,0,0,2.72,0.0,0.0,0.0,0,0,2.72,0.0,12:00:00
2023-07-12,WDHG,65aa7dbb-fede-4fc7-b378-4ad018482e74,WEC DE HOOGH,9315018,EC327,12/07/2023 00:00,2023-07-12 12:00:00,UTC +02:00,PORT,IN PORT,5158N,00337E,51.966667,3.616667,0.00,5260.3,True,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,7.8,6.4,14100.0,0,0.0,0.0,592.0,24.0,18.0,NaN,NLMOE,06/07/2023 08:30,UTC +02:00,NaN,NaN,24.0,401.0,435.0,13.8,NaN,NaN,0.0,0.0,1.0,8.0,85393.0,NLMOE,MOERDIJK,False,False,NaN,NaN,NaN,NaN,bearth occupied,NaN,06/07/2023 13:00,UTC +02:00,NaN,NaN,NaN,NaN,NaN,13/07/2023 12:00,UTC +02:00,NaN,NaN,NaN,341,251,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0,350.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.00,0.0,0,0.0,0.0,0.0,0.00,0.0,0,0,0,1.76,0.0,0,0,0,0,1.76,0.0,0,0,0,0.96,0.0,0.0,0,0,0,0.96,2O,CE,TRUE,TRUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,3200.0,0.0,8400.0,NaN,NaN,NaN,2.6,NaN,NaN,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,250.96,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,250.96,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,362.0,GBTHP-NLMOE,N,Y,0.0,NL,GB,NaN,NaN,0,0.0,0.0,0.0,0.0,2.72,0.0,0.0,362.0,0,7.1,0.0000,0.000,0,0,0,2.72,8.72032,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,1.76,0.96,2.72,0.0,0.0,0.0,0.0,2.72,8.72,24.0,350,1.4,0.0,07/08/2023 10:33,NaN,NaN,0.0,0.0,0,0,2.72,0.0,0.0,0.0,0,0,2.72,0.0,12:00:00
2023-07-13,WDHG,4b876f38-eb53-438a-9017-dea4a90496ef,WEC DE HOOGH,9315018,EC327,13/07/2023 00:00,2023-07-13 12:00:00,UTC +02:00,PORT,IN PORT,5158N,00337E,51.966667,3.616667,1.82,5260.3,True,3.3,3.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,7.8,6.4,14100.0,0,0.0,0.0,592.0,22.0,18.0,NaN,NLMOE,06/07/2023 08:30,UTC +02:00,NaN,NaN,24.0,401.0,435.0,13.8,NaN,NaN,0.0,0.0,1.0,8.0,85396.0,NLMOE,MOERDIJK,False,False,NaN,NaN,NaN,NaN,bearth occupied,NaN,06/07/2023 13:00,UTC +02:00,NaN,NaN,NaN,NaN,NaN,13/07/2023 23:00,UTC +02:00,3.3,NaN,NaN,341,251,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,3.3,0.0,0.0,0.0,0.0,0,3.3,24.0,3.3,0.0,0.0,0.0,3.3,0.0,2758,350.0,180.0,0.0,0.0,0.0,300.0,0.0,0.0,0.0,0,0,1.82,0.0,0,0.0,0.0,0.0,1.82,0.0,0,0,0,1.80,0.0,0,0,0,0,1.80,0.0,0,0,0,0.83,0.0,0.0,0,0,0,0.83,2O,CE,TRUE,TRUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,3200.0,0.0,17533.0,NaN,NaN,NaN,2.6,NaN,NaN,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,246.51,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,246.51,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,362.0,GBTHP-NLMOE,N,Y,3.3,NL,GB,NaN,NaN,0,0.0,0.0,0.0,0.0,4.45,0.0,0.0,362.0,0,7.1,13.2364,199.969,0,0,0,4.45,14.26670,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.82,1.80,0.83,4.45,0.0,0.0,0.0,0.0,4.45,14.27,27.3,530,1.4,0.0,07/08/2023 10:33,NaN,NaN,0.0,0.0,0,0,4.45,0.0,0.0,0.0,0,0,4.45,0.0,12:00:00
2023-07-14,WDHG,e4d59fa3-673f-4661-8201-4fc6219c6701,WEC DE HOOGH,9315018,NaN,14/07/2023 00:00,2023-07-14 02:23:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,5260.3,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,341,251,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0,0.00,0.0,0,0.0,0.0,0.0,0.00,0.0,0,0,0,0.00,0.0,0,0,0,0,0.00,0.0,0,0,0,0.00,0.0,0.0,0,0,0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,362.0,GBTHP-NLMOE,N,Y,0.0,NL,GB,NaN,NaN,0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,362.0,0,0.0,0.0000,0.000,0,0,0,0.00,0.00000,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0,0.0,0.0,07/08/2023 10:33,NaN,NaN,0.0,0.0,0,0,0.00,0.0,0.0,0.0,0,0,0.00,0.0,02:23:00
2023-07-14,WDHG,da94f9d5-a8ab-484f-93a5-a815a8ab3399,WEC DE HOOGH,9315018,NaN,14/07/2023 00:00,2023-07-14 02:23:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,5260.3,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,341,251,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0,0.00,0.0,0,0.0,0.0,0.0,0.00,0.0,0,0,0,0.00,0.0,0,0,0,0,0.00,0.0,0,0,0,0.00,0.0,0.0,0,0,0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,362.0,GBTHP-NLMOE,N,Y,0.0,NL,GB,NaN,NaN,0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,362.0,0,0.0,0.0000,0.000,0,0,0,0.00,0.00000,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0,0.0,0.0,07/08/2023 10:33,NaN,NaN,0.0,0.0,0,0,0.00,0.0,0.0,0.0,0,0,0.00,0.0,02:23:00

In [40]:
pd.set_option('display.max_columns', None)  
filtered_df.tail()

,idvessel,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,LAT,LONG_,LATITUDE,LONGITUDE,M_E_FOC,CARGO_TOTAL,Has_Cargo,TOTAL_STEAMING_TIME,M_E_Fuel_Only_Steaming_Time,MILES_BY_GPS,OIL_CYL,SOW,SOG,RPM,SLIP,WIND_DIRECTION,WIND_SPEED,DRAFT_AFT,DRAFT_FWD,DISPLACEMENT,COURSE_AT_SEA,WAVE_HEIGHT,SEA_DIRECTION,CARGO_TOTAL_TEU,AMBIENT_TEMP,SW_TEMP,MILES_BY_SPEED_LOG,ETA_PORT_CODE,ETA_DATE_TIME,ETA_DATE_TIME_Offset,ETA_PORT,TIME_CHANGE,TIME_SEA,TEMP_MIN,TEMP_MAX,REQUESTED_SPEED,REM_DIST_TO_PILOT,REM_TIME_TO_PILOT,TOTAL_UNPLND_STPGE_TECH,TOTAL_UNPLND_STPGE_OPE_WX,REEFERS_POSITIVE_PLUGGED,REEFERS_NEGATIVE_PLUGGED,ME_TOTAL_REVS_COUNTER,PORT_CODE,PORT,AUX_BLOWERS_ON,HOLD_VENTILATION_ON,SINCE_DATE_TIME,SINCE_DATE_TIME_Offset,TIME_HRS_ANCHOR,TIME_HRS_DRIFT,REASON,TYPE_OF_DELAY,ETB_DATE_TIME,ETB_DATE_TIME_Offset,PILOT_DATE_TIME,PILOT_DATE_TIME_Offset,TIME_MANOEUVRING,TUG_ARR,TUG_SHIFT,ETD_DATE_TIME,ETD_DATE_TIME_Offset,SHIFT_BERTH_HOURS,CARGO_LOAD,CARGO_DISCH,TEU_FULL,TEU_EMPTY,BILGE_REMOVED,GARBAGE_REMOVED,GARBAGE_REMVL_REQSTD,GARBAGE_REMVL_CMPLSRY,FW_SUPPLY,CY_CREW_SIGNED_ON,CY_CREW_SIGNED_OFF,CY_DOCTORS_VISIT,CY_MAIL_RECEIVED_Ref_NO,CY_LUB_OIL_SAMPLE_LANDED,CY_CHECKD_FOR_STOWAWAYS,CY_STOWAWAYS_ON_BOARD,CY_DEP_GM_Mtr,CY_REQUISITIONS_RECEIVED,DISTANCE_TO_NEXT_PILOT,TUG_SAILING_TRANSIT,STEAMING_TIME_M_E_Rsdl_VLS,STEAMING_TIME_M_E_Rsdl_HS,STEAMING_TIME_M_E_Rsdl_ULS,STEAMING_TIME_M_E_Dstlt_VLS,STEAMING_TIME_M_E_Dstlt_ULS,STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS,STEAMING_TIME_M_E_HS,STEAMING_TIME_M_E_LS,STEAMING_TIME_M_E_MDO,STEAMING_TIME_M_E_MGO,STEAMING_TIME_M_E_MGO_LS,STEAMING_TIME_AUX_1,STEAMING_TIME_AUX_2,STEAMING_TIME_AUX_3,STEAMING_TIME_AUX_4,STEAMING_TIME_AUX_5,STEAMING_TIME_SH_GEN,STEAMING_TIME_TG,POWER_kW,STEAMING_LOAD_KW_AUX_1,STEAMING_LOAD_KW_AUX_2,STEAMING_LOAD_KW_AUX_3,STEAMING_LOAD_KW_AUX_4,STEAMING_LOAD_KW_AUX_5,STEAMING_LOAD_KW_SH_GEN,STEAMING_LOAD_KW_TG,FUEL_M_E_Rsdl_VLS,FUEL_M_E_Rsdl_HS,FUEL_M_E_Rsdl_ULS,FUEL_M_E_Dstlt_VLS,FUEL_M_E_Dstlt_ULS,FUEL_M_E_Tnktnr_Dstlt_VLS,FUEL_M_E_HS,FUEL_M_E_LS,FUEL_M_E_MDO,FUEL_M_E_MGO,FUEL_M_E_MGO_LS,FUEL_Aux_Rsdl_VLS,FUEL_Aux_Rsdl_HS,FUEL_Aux_Rsdl_ULS,FUEL_Aux_Dstlt_VLS,FUEL_Aux_Dstlt_ULS,FUEL_Aux_Tnktnr_Dstlt_VLS,FUEL_AUX_HS,FUEL_AUX_LS,FUEL_AUX_MDO,FUEL_AUX_MGO,FUEL_AUX_MGO_LS,FUEL_Boiler_Rsdl_VLS,FUEL_Boiler_Rsdl_HS,FUEL_Boiler_Rsdl_ULS,FUEL_Boiler_Dstlt_VLS,FUEL_Boiler_Dstlt_ULS,FUEL_Boiler_Tnktnr_Dstlt_VLS,FUEL_BOILER_HS,FUEL_BOILER_LS,FUEL_BOILER_MDO,FUEL_BOILER_MGO,FUEL_BOILER_MGO_LS,DECK_LAST_CHANGE_USER,ENGINE_LAST_CHANGE_USER,DECK_PART_IS_COMPLETE,ENGINE_PART_IS_COMPLETE,SCAVENGE_PRESSURE,SECA_ENTRY_TIME,SECA_ENTRY_LAT,SECA_ENTRY_LONG,SECA_EXIT_TIME,SECA_EXIT_LAT,SECA_EXIT_LONG,ROB_FRESH_WATER,MANVRNG_MILES_BY_GPS,MANVRNG_MILES_BY_SPEED_LOG,TANKTAINER_TRANSFD_QUANTITY,PILOT_TAKEN,DATE_TIME_START_TRANSIT,DATE_TIME_START_TRANSIT_Offset,DATE_TIME_END_TRANSIT,DATE_TIME_END_TRANSIT_Offset,BALLAST,TANKTAINER_NUMBER,STEAMING_KWHR_TOTAL,CY_OTHERS,ROB_FO_SLUDGE,ROB_LO_SLUDGE,ROB_BILGE,SLUDGE_REMOVED_FO,SLUDGE_REMOVED_LO,SEA_STATE,CY_LUB_ADDED_TO_SYSTEM_MECC,CY_LUB_ADDED_TO_SYSTEM_AECC,CY_LUB_ADDED_TO_THRUSTERS,CY_ME_LO_PURIFIER_IN_USE,CY_BALLAST,CY_BENDING_MOMENT,CY_SHEARING_FORCE,CY_TORTION_MOMENT,CY_SUPDT_AUDITOR_SIGNED_ON,CY_SUPDT_AUDITOR_SIGNED_OFF,CY_CASH_RECEIVED,CY_LUB_OIL_RECEIVED_MECYL,CY_LUB_OIL_RECEIVED_MECC,CY_LUB_OIL_RECEIVED_AECC,CY_M_E_UNDER_PISTON_TEMP,CY_MAIL_RECEIVED,WIND_DIRECTION_PORT_STBD,SEA_DIRECTION_PORT_STBD,TIME_PILOT_ONBOARD,GRADES_ROB,SO2_CO2_RATIO,Bunker_Order,Remarks,Fuel_Type,Carbon_Factor,Sulphur_Content_PC,Quantity,Port_Delivery,Product_Quality,Tanktainer_Number_1,Supplier,Delivery,Vol_Lt,Den,Vis,ROB_Dstlt_ULS,ROB_Dstlt_VLS,ROB_Rsdl_MDO,ROB_Tnktnr_Dstlt_VLS,ROB_Rsdl_VLS,ROB_Rsdl_HS,ROB_Rsdl_ULS,ROB_Fuel_HSFO,ROB_Fuel_LSFO,ROB_Fuel_MDO,ROB_Fuel_MGO,ROB_Fuel_MGO_LS,ROB_Fuel_Tanktainer_MGO,ECA_MILES,ECA_TIME,EGCS_DRY_WASTE_REMOVED,EGCS_RUNNING_TIME,EGCS_WET_SLURRY_REMOVED,EGCS_OPEN_LOOP_RUNNING_TIME,EGCS_CLOSED_LOOP_RUNNING_TIME,Voyage_Order,Voyage_Code,ECA,EU,Sea_Time,ETA_Country_Code,Port_Country_Code,check_ETA_code,check_Port_code,Status_TEMP_EU,FUEL_HS,FUEL_LS,FUEL_MDO,FUEL_MGO,FUEL_MGO_LS,Cargo_Transport_Work,TEU_Transport_Work,EEOI_Voyage_no,CARGO_TOTAL_Old,DRAFT,FO_per_24Hrs,SFOC,CY_OIL_gm_hr,SCOC,Voyage_Name,TOTAL_FO,TOTAL_CO2,EEOI,voyCondition,samedate,timesincelastreport,BDN,Wind_direction_360,True_wind_speed,True_wind_dir,ref_power,ref_fuel,fuel_loss,Relative_wind_speed,Relative_wind_direction,CAA,RW,Corrected_Power,draft_pow,draft_sp_pow,fo_nor,fo_model,sfoc_model,sfoc_deviation,ref_power_corrected,ref_FO_corrected,Propulsive_eff,speed_performance,Ref_speed,P_I,MEcon,AEcon,BLcon,Tcon,HS,LS,MDO,MGO,MGOLS,TCO2,AETsteaming,AEPOWER,TRIM,DISTANCECOVERED,updated_date,hyd_slip_sog,hyd_slip_stw,FUEL_Rsdl_HS,FUEL_Rsdl_VLS,FUEL_Rsdl_ULS,FUEL_Dstlt_VLS,FUEL_Dstlt_ULS,FUEL_Tnktnr_Dstlt_VLS,Rsdl_HS,Rsdl_VLS,Rsdl_ULS,Dstlt_VLS,Dstlt_ULS,Tnktnr_Dstlt_VLS,Time
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023-08-10,WDHG,185e6880-da62-4b75-925a-ee13a423c21c,WEC DE HOOGH,9315018,NaN,11/08/2023 00:00,2023-08-10 12:23:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,7724.3,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,474,207,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0,0,0.0,0.0,0,0.00,0.0,0.0,0.0,0.0,0,0,0,0.00,0.0,0,0,0,0,0.00,0.0,0,0,0,0.0,0.0,0.0,0,0,0,0.0,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,376.0,BEANR-ESBIO,N,Y,0.0,ES,BE,NaN,NaN,0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,376.0,0,0.00,0.00,0.000,0,0,0,0.00,0.00000,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.0,0,0.0,0.0,24/08/2023 09:09,NaN,NaN,0.0,0.00,0,0,0.00,0.0,0.0,0.00,0,0,0.00,0.0,12:23:00
2023-08-10,WDHG,3418da5f-ea37-4f4b-b149-42c46ac8bd02,WEC DE HOOGH,9315018,NaN,11/08/2023 00:00,2023-08-10 12:23:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,7724.3,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,474,207,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0,0,0.0,0.0,0,0.00,0.0,0.0,0.0,0.0,0,0,0,0.00,0.0,0,0,0,0,0.00,0.0,0,0,0,0.0,0.0,0.0,0,0,0,0.0,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,376.0,BEANR-ESBIO,N,Y,0.0,ES,BE,NaN,NaN,0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,376.0,0,0.00,0.00,0.000,0,0,0,0.00,0.00000,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.0,0,0.0,0.0,24/08/2023 09:09,NaN,NaN,0.0,0.00,0,0,0.00,0.0,0.0,0.00,0,0,0.00,0.0,12:23:00
2023-08-10,WDHG,d7692cd7-efb7-433f-9b04-998a95e7d0b8,WEC DE HOOGH,9315018,NaN,11/08/2023 00:00,2023-08-10 12:23:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,7724.3,False,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,474,207,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0,0,0.0,0.0,0,0.00,0.0,0.0,0.0,0.0,0,0,0,0.00,0.0,0,0,0,0,0.00,0.0,0,0,0,0.0,0.0,0.0,0,0,0,0.0,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,376.0,BEANR-ESBIO,N,Y,0.0,ES,BE,NaN,NaN,0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,376.0,0,0.00,0.00,0.000,0,0,0,0.00,0.00000,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.0,0,0.0,0.0,24/08/2023 09:09,NaN,NaN,0.0,0.00,0,0,0.00,0.0,0.0,0.00,0,0,0.00,0.0,12:23:00
2023-08-10,WDHG,225303fe-e7f1-466f-a931-2b0a40dd158c,WEC DE HOOGH,9315018,EC331,11/08/2023 00:00,2023-08-10 12:24:00,UTC +02:00,SAIL,IN PORT,4331N,00313W,43.516667,-3.216667,0.00,6321.9,True,0.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,7.5,7.2,15159.0,0,0.0,0.0,568.0,22.0,18.0,NaN,ESVGO,11/08/2023 23:30,UTC +02:00,VIGO,NaN,0.4,382.0,418.0,5.0,NaN,NaN,0.0,0.0,5.0,47.0,85906.0,ESBIO,BILBAO,False,False,NaN,NaN,NaN,NaN,bearth occupied,NaN,09/08/2023 23:00,UTC +02:00,NaN,NaN,NaN,NaN,0.0,10/08/2023 13:00,UTC +02:00,NaN,0.0,1402.4,374,194,0.0,NaN,False,False,0.0,0.0,0.0,No,0.0,0.0,0,0.0,1.13,0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.4,0.4,0.0,0.0,0.0,0.0,0.0,0,180.0,180.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0,0,0.0,0.0,0,0.00,0.0,0.0,0.0,0.0,0,0,0,0.03,0.0,0,0,0,0,0.03,0.0,0,0,0,0.0,0.0,0.0,0,0,0,0.0,2O,CE,TRUE,TRUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.0,0.0,NaN,0.0,FALSE,NaN,NaN,NaN,NaN,2830.0,0.0,144.0,NaN,NaN,NaN,3.1,NaN,NaN,0.0,0.0,0.0,0.0,1.0,NaN,91.0,86.0,45.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,FALSE,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180.73,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,180.73,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,377.0,ESBIO-ESVGO,N,Y,0.0,ES,ES,NaN,NaN,0,0.0,0.00,0.0,0.0,0.03,0.0,0.0,376.0,0,7.35,0.00,0.000,0,0,0,0.03,0.09618,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.03,0.0,0.03,0.0,0.00,0.0,0.0,0.03,0.10,0.8,360,0.3,0.0,05/09/2023 23:17,NaN,NaN,0.0,0.00,0,0,0.03,0.0,0.0,0.00,0,0,0.03,0.0,12:24:00
2023-08-10,WDHG,8fec73da-fbd3-4287-83c3-33712c318271,WEC DE HOOGH,9315018,EC331,11/08/2023 00:00,2023-08-10 13:24:00,UTC +02:00,COSP,DRIFTING,4324N,00306W,43.400000,-3.100000,0.62,6321.9,True,1.0,1.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,20,7.5,7.2,15159.0,326,1.2,0.0,568.0,22.0,18.0,NaN,ESVGO,11/08/2023 23:30,UTC +02:00,VIGO,NaN,1.0,382.0,418.0,13.3,NaN,NaN,0.0,0.0,5.0,47.0,86906.0,ESBIO,BILBAO,False,False,NaN,NaN,NaN,NaN,bearth occupied,NaN,09/08/2023 23:00,UTC +02:00,NaN,NaN,1.0,NaN,NaN,10/08/2023 13:00,UTC +02:00,NaN,NaN,NaN,374,194,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,455.3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,3670,140.0,140.0,0.0,0.0,0.0,400.0,0.0,0.62,0.0,0,0,0.0,0.0,0,0.62,0.0,0.0,0.0,0.0,0,0,0,0.06,0.0,0,0,0,0,0.06,0.0,0,0,0,0.0,0.0,0.0,0,0,0,0.0,2O,CE,TRUE,TRUE,1.5,NaN,NaN,NaN,NaN,NaN,NaN,45.0,5.0,5.1,NaN,TRUE,NaN,NaN,NaN,NaN,2830.0,0.0,3670.0,NaN,NaN,NaN,3.1,NaN,NaN,3.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,P,P,0.7,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180.67,0.0,0.0,0.0,292.84,0.0,0.0,0.0,292.84,0.0,0.0,180.67,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,377.0,ESBIO-ESVGO,N,Y,1.0,ES,ES,NaN,NaN,0,0.0,0.62,0.0,0.0,0.06,31609.5,2840.0,377.0,0,7.35,14.88,168.937,0,0,0,0.68,2.12304,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.62,0.06,0.0,0.68,0.0,0.62,0.0,0.0,0.06,2.12,2.0,280,0.3,5.0,05/09/2023 23:17,NaN,NaN,0.0,0.62,0,0,0.06,0.0,0.0,0.62,0,0,0.06,0.0,13:24:00

In [41]:
filtered_df['Total_Calculated_MGO_LS'] = filtered_df[['FUEL_M_E_MGO_LS', 'FUEL_AUX_MGO_LS', 'FUEL_BOILER_MGO_LS']].sum(axis=1)

filtered_df['Total_Calculated_ULS'] = filtered_df[['FUEL_M_E_Dstlt_ULS', 'FUEL_Aux_Dstlt_ULS', 'FUEL_Boiler_Dstlt_ULS']].sum(axis=1)

filtered_df['Total_Calculated_LS'] =  filtered_df[['FUEL_M_E_LS','FUEL_M_E_Rsdl_VLS']].sum(axis=1)

filtered_df['Total_fuel'] = filtered_df[['Total_Calculated_MGO_LS', 'Total_Calculated_ULS','Total_Calculated_LS']].sum(axis=1)

filtered_df['Total_BIO_Calculated'] = (filtered_df['Total_Calculated_MGO_LS'] * 3.206) + (filtered_df['Total_Calculated_ULS'] * 3.206)+ (filtered_df['Total_Calculated_LS']* 3.151)

In [42]:
dist = filtered_df['MILES_BY_GPS'].sum()
print(dist)

6027.26

In [43]:
dwt= 13716
filtered_df = filtered_df.assign(DWT=dwt)

In [44]:
TAFC= filtered_df['Total_BIO_Calculated'].sum() * 10**6
print(TAFC)

3313672139.9999995

# ATTAINED CII

In [45]:
ATT_CII = TAFC / (dist * dwt)
ATT_CII

40.08317675179291

# REFERENCE CII

In [46]:
'''

CII(REF)= A.CAPACITY^-C

PARAMETER FOR A AND C ARE

SHIP TYPE                           A            C         CAPACITY
TANKER                             5247         0.610       DWT
CONTAIER SHIP                      1984         0.489       DWT
BULK CARRIER: DWT >= 2,79,000      4745         0.622       2,79,00     
BULK CARRIER: DWT <= 2,79,00       4745         0.622       DWT
COMBINATION CARRIER                40853        0.812       DWT

'''

'\n\nCII(REF)= A.CAPACITY^-C\n\nPARAMETER FOR A AND C ARE\n\nSHIP TYPE                           A            C         CAPACITY\nTANKER                             5247         0.610       DWT\nCONTAIER SHIP                      1984         0.489       DWT\nBULK CARRIER: DWT >= 2,79,000      4745         0.622       2,79,00     \nBULK CARRIER: DWT <= 2,79,00       4745         0.622       DWT\nCOMBINATION CARRIER                40853        0.812       DWT\n\n'

In [48]:
#Parameters for reference cii
a = int(input("A:"))
c = float(input("C:"))
dwt= 13716

A:1984
C:0.489

In [49]:
CII_REF = a * (dwt ** (-c))
print(CII_REF)

18.812106634619678

# REQUIRED CII

In [50]:
'''
Required CII= CII(REF) * [(100-Z)/100]

REDUCATION FACTOR(Z%)
YEAR           REDUCTION FACTOR RELATIVE TO 2019
2019                   
2020                  1%
2021                  2%
2022                  3%
2023                  5%
2024                  7%
2025                  9%
2026                  11%

'''

'\nRequired CII= CII(REF) * [(100-Z)/100]\n\nREDUCATION FACTOR(Z%)\nYEAR           REDUCTION FACTOR RELATIVE TO 2019\n2019                   \n2020                  1%\n2021                  2%\n2022                  3%\n2023                  5%\n2024                  7%\n2025                  9%\n2026                  11%\n\n'

In [51]:
#Z-Reduction value
years = {
    2019: 0,
    2020: 1,
    2021: 2,
    2022: 3 ,
    2023: 5 ,
    2024: 7 ,
    2025: 9 ,
    2026: 11
}

a = int(input("Enter a year: "))    #ENTER THE CII YEAR
if a in years:
    Z = years[a]
    print(Z)
else:
    print("No Z value")

Enter a year: 2023
5

In [52]:
#Required CII 
CII_REQ = CII_REF * ((100 - Z) / 100)
print(CII_REQ)

17.871501302888692

# CII RATIO

In [53]:
'''

CII RATIO= ATTAINED CII/ REQUIRED CII
                                                DD VECTORS
SHIP TYPE                          CAPACITY     D1     D2    D3    D4  
BULK CARRIER                         DWT       0.86   0.94  1.06  1.18
TANKER                               DWT       0.82   0.93  1.08  1.28
CONTAINER                            DWT       0.83   0.94  1.07  1.19
COMBINATION                          DWT       0.87   0.96  1.06  1.14
GENERAL CARGO SHIP                   DWT       0.83   0.94  1.06  1.19


CII RATIO <= D1 ---------- A RATING
D1<CII RATIO <= D2 ------- B RATING
D2<CII RATIO <= D3 ------- C RATING
D3<CII RATIO <= D4 ------- D RATING
CII RATIO  > D4 ---------- E RATING

A – Major superior performance level
B – Minor superior performance level
C – Moderate performance level
D – Minor Inferior performance level
E – Inferior performance level

All vessels must aspire to be at least C-rated.Any vessel that is rated D or E for three years in a row will have to 
submit a corrective action plan that explains the efforts that will be taken to achieve an acceptable rating (C or above). 
 
'''

'\n\nCII RATIO= ATTAINED CII/ REQUIRED CII\n                                                DD VECTORS\nSHIP TYPE                          CAPACITY     D1     D2    D3    D4  \nBULK CARRIER                         DWT       0.86   0.94  1.06  1.18\nTANKER                               DWT       0.82   0.93  1.08  1.28\nCONTAINER                            DWT       0.83   0.94  1.07  1.19\nCOMBINATION                          DWT       0.87   0.96  1.06  1.14\nGENERAL CARGO SHIP                   DWT       0.83   0.94  1.06  1.19\n\n\nCII RATIO <= D1 ---------- A RATING\nD1<CII RATIO <= D2 ------- B RATING\nD2<CII RATIO <= D3 ------- C RATING\nD3<CII RATIO <= D4 ------- D RATING\nCII RATIO  > D4 ---------- E RATING\n\nA – Major superior performance level\nB – Minor superior performance level\nC – Moderate performance level\nD – Minor Inferior performance level\nE – Inferior performance level\n\nAll vessels must aspire to be at least C-rated.Any vessel that is rated D or E for three years in a row will have to \nsubmit a corrective action plan that explains the efforts that will be taken to achieve an acceptable rating (C or above). \n \n'

In [54]:
#CII Ratio
CII_RATIO= ATT_CII/ CII_REQ
print(CII_RATIO)

2.242854479456295

In [55]:
ships = {
    'BULK': {'D1': 0.86, 'D2': 0.94, 'D3': 1.06, 'D4': 1.18},
    'TANKER': {'D1': 0.82, 'D2': 0.93, 'D3': 1.08, 'D4': 1.28},
    'CONTAINER': {'D1': 0.83, 'D2': 0.94, 'D3': 1.07, 'D4': 1.19},
    'COMBINATION': {'D1': 0.87, 'D2': 0.96, 'D3': 1.06, 'D4': 1.14},
    'GENERAL CARGO SHIP': {'D1': 0.83, 'D2': 0.94, 'D3': 1.06, 'D4': 1.19},
}

def ratings(ship, cii_ratio):
    a = ships.get(ship)
    if a:
        if cii_ratio <= a['D1']:
            return 'A RATING'
        elif a['D1'] < cii_ratio <= a['D2']:
            return 'B RATING'
        elif a['D2'] < cii_ratio <= a['D3']:
            return 'C RATING'
        elif a['D3'] < cii_ratio <= a['D4']:
            return 'D RATING'
        else:
            return 'E RATING'
    else:
        return 'Data not founded'

ship = input("Enter the ship: ").strip().upper()  
CII_RATIO = CII_RATIO
rating = ratings(ship, CII_RATIO)
print(f'The rating is: {rating}')

Enter the ship: container
The rating is: E RATING

In [56]:
import pandas as pd
final= {
    'Fuel': ['Bio fuel', 'Normal Fuel'],
    'Attained_CII': [31.17, 38.24],  
    'Required_CII': [17.86,17.87],
    'Reference_CII':[18.80,18.81],
    'CII Ratio':[1.74,2.14],
    'CII Rating':['E RATING','E RATING']
    
}
final_df = pd.DataFrame(final)
final_df

,Fuel,Attained_CII,Required_CII,Reference_CII,CII Ratio,CII Rating
0,Bio fuel,31.17,17.86,18.80,1.74,E RATING
1,Normal Fuel,38.24,17.87,18.81,2.14,E RATING