In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd

In [3]:
charter = pd.read_excel(r"D:\Navalt\MSC\2024\Weekly Data\CHARTER\CLIENT\CORRECTED\AUG_2024.xlsx")
charter

,Unnamed: 0,GID,VSL,IMO No,VOY,Corrected Date,REPORT DATE TIME,REPORT DATE TIME Offset,Report Type,Status,...,ROB Rsdl HS,ROB Rsdl ULS,ROB Rsdl LNG,ECA MILES,ECA TIME,EGCS DRY WASTE REMOVED,EGCS RUNNING TIME,EGCS WET SLURRY REMOVED,EGCS OPEN LOOP RUNNING TIME,EGCS CLOSED LOOP RUNNING TIME
0,2798,202b3fcb-ddcb-41ef-8365-b3d28ddcb8ca,MSC AURELIA,76021200.0,407,2024-08-01,2024-08-01 06:12:00,UTC +02:00,EOSP,AT SEA,...,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
1,2805,26e61ea7-3216-4bb7-a0ce-e5b69d34cf60,MSC AURELIA,76021200.0,407,2024-08-01,2024-08-01 06:42:00,UTC +02:00,BRTH,DRIFTING,...,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2806,571a8985-617b-4f85-9eab-ef133661da63,MSC AURELIA,76021200.0,407,2024-08-01,2024-08-01 12:00:00,UTC +02:00,PORT,IN PORT,...,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2813,a9d7bd6d-6015-4dd0-8e9e-f40d2c5285eb,MSC AURELIA,76021200.0,407,2024-08-02,2024-08-01 19:30:00,UTC +02:00,SAIL,IN PORT,...,0.00,0.0,0.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN
4,2814,50ad5a0d-838a-4c10-9d7d-94d8c1bde30e,MSC AURELIA,76021200.0,407,2024-08-02,2024-08-01 19:48:00,UTC +02:00,COSP,DRIFTING,...,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47591,83946,3779916a-357d-47ca-85a0-0a957a87dc39,MSC COTONOU VIII,99836710.0,UL430W,2024-08-28,2024-08-28 12:00:00,UTC -01:00,NOON,AT SEA,...,919.11,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
47592,83947,a7e76ef4-1b7d-45d0-a629-4b0afb94199a,MSC COTONOU VIII,99836710.0,UL430W,2024-08-29,2024-08-29 12:00:00,UTC +00:00,NOON,AT SEA,...,835.93,0.0,0.0,0.0,0.0,NaN,23.0,NaN,23.0,0.0
47593,83948,3de94823-cffe-469d-b306-02b47aea9d1f,MSC COTONOU VIII,99836710.0,UL430W,2024-08-30,2024-08-30 12:00:00,UTC +00:00,NOON,AT SEA,...,749.71,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
47594,83949,fc8528e4-6372-4790-8fbd-3465bb213757,MSC COTONOU VIII,99836710.0,UL430W,2024-08-31,2024-08-31 12:00:00,UTC +00:00,NOON,AT SEA,...,665.45,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
47595,73022,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
sm = pd.read_excel(r"C:\Users\akshaya\Downloads\SM_VESSEL_17.10.xlsx")
sm

,Fleet,Class,Segment,Trade,Name,Type,Ex Name,Year of Built,Hull No.,IMO,TEU,GRT,LBP,Engine
0,1,FAST FEEDER,1600,Line E1 - Gioia Taur,MSC ADRIANA II,Container,MSC Malaysia,1998.0,339,9169055,1388.0,25219.0,198.70,12510
1,1,FAST FEEDER,1800,Extra Vessels,MSC ASLI,Container,Linkoln / Norasia Sa,1998.0,2243,9162631,1733.0,24836.0,201.74,12000
2,1,FAST FEEDER,1800,Line A - Adriatic To,MSC CAITLIN,Container,Oxford,1998.0,338,9169043,1658.0,25219.0,201.86,12510
3,1,FAST FEEDER,1800,Line G String 1,MSC EDITH,Container,Lykes Crusader,1998.0,336,9169029,1733.0,25219.0,198.70,12510
4,1,FAST FEEDER,1800,Line A - Adriatic To,MSC LEA II,Container,Shropshire,2000.0,2244,9162643,1733.0,24836.0,201.74,12000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594,9,MADISON,1800,W/W,MSC MADISON II,Container,Bright Horizon,2002.0,MC 300-1,9231119,1842.0,23132.0,182.00,15785
595,9,JINHAI 12000,11500,NWC to SAFR,MSC EUGENIA,Container,NaN,2022.0,J0264,9785469,12108.0,113697.0,313.13,40200
596,9,HAITI,1800,Italy - North Africa,MSC HAITI II,Container,MV Yellow Stone,2002.0,SS182,9225251,1706.0,27839.0,175.40,7788
597,9,JINHAI 12000,11500,NWC To South Africa,MSC CASSANDRE,Container,NaN,2022.0,J0265,9785471,12108.0,113697.0,313.13,40200
598,9,HAITI,1800,USA - South Africa (,MSC SILVER II,Container,M/V SILVERFJORD,2002.0,SS181,9225249,1706.0,27828.0,175.40,7788

In [17]:
charter['IMO No'].nunique()

843

In [19]:
# Assuming charter_df and fleet_df are your dataframes

# Extract the IMO numbers from each dataframe
charter_IMO = set(charter['IMO No'])
sm_IMO = set(sm['IMO'])

# Find the common IMO numbers
common_IMO = charter_IMO.intersection(sm_IMO)

# Print the common IMO numbers
print(common_IMO)
common_IMO_count = len(common_IMO)
print(common_IMO_count)

set()
0

In [21]:
noon = charter[charter['IMO No'].isin(common_IMO)]
print(noon)

Empty DataFrame
Columns: [Unnamed: 0, GID, VSL, IMO No, VOY, Corrected Date, REPORT DATE TIME, REPORT DATE TIME Offset, Report Type, Status, LAT, LONG, M E FOC, CARGO TOTAL, Has Cargo, STEAMING TIME, Total M E Hours Fuel Only, MILES BY GPS, OIL CYL, SPEED BY LOG, SPEED BY GPS, RPM, SLIP, WIND DIRECTION, WIND SPEED, DRAFT AFT, DRAFT FWD, DISPLACEMENT, COURSE AT SEA, WAVE HEIGHT, SEA DIRECTION, CARGO TOTAL TEU, AMBIENT TEMP, SW TEMP, MILES BY SPEED LOG, ETA PORT CODE, ETA DATE TIME, ETA DATE TIME Offset, ETA PORT, TIME CHANGE, TIME SEA, TEMP MIN, TEMP MAX, REQUESTED SPEED, REM DIST TO PILOT, REM TIME TO PILOT, TOTAL UNPLND STPGE TECH, TOTAL UNPLND STPGE OPE WX, REEFERS POSITIVE PLUGGED, REEFERS NEGATIVE PLUGGED, ME TOTAL REVS COUNTER, PORT CODE, PORT, AUX BLOWERS ON, HOLD VENTILATION ON, TIME HRS ANCHOR, TIME HRS DRIFT, REASON, TYPE OF DELAY, ETB DATE TIME, ETB DATE TIME Offset, PILOT DATE TIME, PILOT DATE TIME Offset, TIME MANOEUVRING, TUG ARR, TUG SHIFT, ETD DATE TIME, ETD DATE TIME Offset, SHIFT BERTH HOURS, CARGO LOAD, CARGO DISCH, TEU FULL, TEU EMPTY, BILGE REMOVED, GARBAGE REMOVED, GARBAGE REMVL REQSTD, GARBAGE REMVL CMPLSRY, FW SUPPLY, CY CREW SIGNED ON, CY CREW SIGNED OFF, CY DOCTORS VISIT, CY MAIL RECEIVED Ref NO, CY LUB OIL SAMPLE LANDED, CY CHECKD FOR STOWAWAYS, CY STOWAWAYS ON BOARD, CY DEP GM Mtr, CY REQUISITIONS RECEIVED, DISTANCE TO NEXT PILOT, TUG SAILING TRANSIT, STEAMING TIME M E Rsdl VLS, STEAMING TIME M E Rsdl HS, STEAMING TIME M E Rsdl ULS, STEAMING TIME M E Dstlt VLS, STEAMING TIME M E Dstlt ULS, STEAMING TIME M E Tnktnr Dstlt VLS, STEAMING TIME M E MDO, STEAMING TIME AUX 1, STEAMING TIME AUX 2, STEAMING TIME AUX 3, STEAMING TIME AUX 4, ...]
Index: []

[0 rows x 216 columns]

In [23]:
charter = charter[~charter['IMO No'].isin(common_IMO)]
print(charter)

       Unnamed: 0                                   GID               VSL  \
0            2798  202b3fcb-ddcb-41ef-8365-b3d28ddcb8ca       MSC AURELIA
1            2805  26e61ea7-3216-4bb7-a0ce-e5b69d34cf60       MSC AURELIA
2            2806  571a8985-617b-4f85-9eab-ef133661da63       MSC AURELIA
3            2813  a9d7bd6d-6015-4dd0-8e9e-f40d2c5285eb       MSC AURELIA
4            2814  50ad5a0d-838a-4c10-9d7d-94d8c1bde30e       MSC AURELIA
...           ...                                   ...               ...
47591       83946  3779916a-357d-47ca-85a0-0a957a87dc39  MSC COTONOU VIII
47592       83947  a7e76ef4-1b7d-45d0-a629-4b0afb94199a  MSC COTONOU VIII
47593       83948  3de94823-cffe-469d-b306-02b47aea9d1f  MSC COTONOU VIII
47594       83949  fc8528e4-6372-4790-8fbd-3465bb213757  MSC COTONOU VIII
47595       73022                                   NaN               NaN

           IMO No     VOY Corrected Date    REPORT DATE TIME  \
0      76021200.0     407     2024-08-01 2024-08-01 06:12:00
1      76021200.0     407     2024-08-01 2024-08-01 06:42:00
2      76021200.0     407     2024-08-01 2024-08-01 12:00:00
3      76021200.0     407     2024-08-02 2024-08-01 19:30:00
4      76021200.0     407     2024-08-02 2024-08-01 19:48:00
...           ...     ...            ...                 ...
47591  99836710.0  UL430W     2024-08-28 2024-08-28 12:00:00
47592  99836710.0  UL430W     2024-08-29 2024-08-29 12:00:00
47593  99836710.0  UL430W     2024-08-30 2024-08-30 12:00:00
47594  99836710.0  UL430W     2024-08-31 2024-08-31 12:00:00
47595         NaN     NaN            NaT                 NaT

      REPORT DATE TIME Offset Report Type    Status  ... ROB Rsdl HS  \
0                  UTC +02:00        EOSP    AT SEA  ...        0.00
1                  UTC +02:00        BRTH  DRIFTING  ...        0.00
2                  UTC +02:00        PORT   IN PORT  ...        0.00
3                  UTC +02:00        SAIL   IN PORT  ...        0.00
4                  UTC +02:00        COSP  DRIFTING  ...        0.00
...                       ...         ...       ...  ...         ...
47591              UTC -01:00        NOON    AT SEA  ...      919.11
47592              UTC +00:00        NOON    AT SEA  ...      835.93
47593              UTC +00:00        NOON    AT SEA  ...      749.71
47594              UTC +00:00        NOON    AT SEA  ...      665.45
47595                     NaN         NaN       NaN  ...         NaN

      ROB Rsdl ULS  ROB Rsdl LNG  ECA MILES  ECA TIME  EGCS DRY WASTE REMOVED  \
0              0.0           0.0        0.0       0.0                     NaN
1              0.0           0.0        NaN       NaN                     NaN
2              0.0           0.0        NaN       NaN                     NaN
3              0.0           0.0        NaN       NaN                     0.0
4              0.0           0.0        NaN       NaN                     NaN
...            ...           ...        ...       ...                     ...
47591          0.0           0.0        0.0       0.0                     NaN
47592          0.0           0.0        0.0       0.0                     NaN
47593          0.0           0.0        0.0       0.0                     NaN
47594          0.0           0.0        0.0       0.0                     NaN
47595          NaN           NaN        NaN       NaN                     NaN

       EGCS RUNNING TIME  EGCS WET SLURRY REMOVED  \
0                    NaN                      NaN
1                    NaN                      NaN
2                    NaN                      NaN
3                    NaN                      0.0
4                    NaN                      NaN
...                  ...                      ...
47591               24.0                      NaN
47592               23.0                      NaN
47593               24.0                      NaN
47594               24.0                      NaN
47595                NaN                      NaN

       EGCS OPEN LOOP RUNNING TIME  EGCS CLOSED LOOP RUNNING TIME
0                              NaN                            NaN
1                              NaN                            NaN
2                              NaN                            NaN
3                              NaN                            NaN
4                              NaN                            NaN
...                            ...                            ...
47591                         24.0                            0.0
47592                         23.0                            0.0
47593                         24.0                            0.0
47594                         24.0                            0.0
47595                          NaN                            NaN

[47596 rows x 216 columns]

In [25]:
charter=charter.drop(columns=['Unnamed: 0'])
charter

,GID,VSL,IMO No,VOY,Corrected Date,REPORT DATE TIME,REPORT DATE TIME Offset,Report Type,Status,LAT,...,ROB Rsdl HS,ROB Rsdl ULS,ROB Rsdl LNG,ECA MILES,ECA TIME,EGCS DRY WASTE REMOVED,EGCS RUNNING TIME,EGCS WET SLURRY REMOVED,EGCS OPEN LOOP RUNNING TIME,EGCS CLOSED LOOP RUNNING TIME
0,202b3fcb-ddcb-41ef-8365-b3d28ddcb8ca,MSC AURELIA,76021200.0,407,2024-08-01,2024-08-01 06:12:00,UTC +02:00,EOSP,AT SEA,4328N,...,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
1,26e61ea7-3216-4bb7-a0ce-e5b69d34cf60,MSC AURELIA,76021200.0,407,2024-08-01,2024-08-01 06:42:00,UTC +02:00,BRTH,DRIFTING,4328N,...,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,571a8985-617b-4f85-9eab-ef133661da63,MSC AURELIA,76021200.0,407,2024-08-01,2024-08-01 12:00:00,UTC +02:00,PORT,IN PORT,4328N,...,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,a9d7bd6d-6015-4dd0-8e9e-f40d2c5285eb,MSC AURELIA,76021200.0,407,2024-08-02,2024-08-01 19:30:00,UTC +02:00,SAIL,IN PORT,4328N,...,0.00,0.0,0.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN
4,50ad5a0d-838a-4c10-9d7d-94d8c1bde30e,MSC AURELIA,76021200.0,407,2024-08-02,2024-08-01 19:48:00,UTC +02:00,COSP,DRIFTING,4328N,...,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47591,3779916a-357d-47ca-85a0-0a957a87dc39,MSC COTONOU VIII,99836710.0,UL430W,2024-08-28,2024-08-28 12:00:00,UTC -01:00,NOON,AT SEA,1624S,...,919.11,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
47592,a7e76ef4-1b7d-45d0-a629-4b0afb94199a,MSC COTONOU VIII,99836710.0,UL430W,2024-08-29,2024-08-29 12:00:00,UTC +00:00,NOON,AT SEA,2034S,...,835.93,0.0,0.0,0.0,0.0,NaN,23.0,NaN,23.0,0.0
47593,3de94823-cffe-469d-b306-02b47aea9d1f,MSC COTONOU VIII,99836710.0,UL430W,2024-08-30,2024-08-30 12:00:00,UTC +00:00,NOON,AT SEA,2459S,...,749.71,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
47594,fc8528e4-6372-4790-8fbd-3465bb213757,MSC COTONOU VIII,99836710.0,UL430W,2024-08-31,2024-08-31 12:00:00,UTC +00:00,NOON,AT SEA,2932S,...,665.45,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
47595,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
charter = charter.drop_duplicates(subset=['GID'],keep='first')

In [29]:
duplicate_gid = charter[charter.duplicated(subset='GID', keep=False)]
duplicate_gid

Empty DataFrame
Columns: [GID, VSL, IMO No, VOY, Corrected Date, REPORT DATE TIME, REPORT DATE TIME Offset, Report Type, Status, LAT, LONG, M E FOC, CARGO TOTAL, Has Cargo, STEAMING TIME, Total M E Hours Fuel Only, MILES BY GPS, OIL CYL, SPEED BY LOG, SPEED BY GPS, RPM, SLIP, WIND DIRECTION, WIND SPEED, DRAFT AFT, DRAFT FWD, DISPLACEMENT, COURSE AT SEA, WAVE HEIGHT, SEA DIRECTION, CARGO TOTAL TEU, AMBIENT TEMP, SW TEMP, MILES BY SPEED LOG, ETA PORT CODE, ETA DATE TIME, ETA DATE TIME Offset, ETA PORT, TIME CHANGE, TIME SEA, TEMP MIN, TEMP MAX, REQUESTED SPEED, REM DIST TO PILOT, REM TIME TO PILOT, TOTAL UNPLND STPGE TECH, TOTAL UNPLND STPGE OPE WX, REEFERS POSITIVE PLUGGED, REEFERS NEGATIVE PLUGGED, ME TOTAL REVS COUNTER, PORT CODE, PORT, AUX BLOWERS ON, HOLD VENTILATION ON, TIME HRS ANCHOR, TIME HRS DRIFT, REASON, TYPE OF DELAY, ETB DATE TIME, ETB DATE TIME Offset, PILOT DATE TIME, PILOT DATE TIME Offset, TIME MANOEUVRING, TUG ARR, TUG SHIFT, ETD DATE TIME, ETD DATE TIME Offset, SHIFT BERTH HOURS, CARGO LOAD, CARGO DISCH, TEU FULL, TEU EMPTY, BILGE REMOVED, GARBAGE REMOVED, GARBAGE REMVL REQSTD, GARBAGE REMVL CMPLSRY, FW SUPPLY, CY CREW SIGNED ON, CY CREW SIGNED OFF, CY DOCTORS VISIT, CY MAIL RECEIVED Ref NO, CY LUB OIL SAMPLE LANDED, CY CHECKD FOR STOWAWAYS, CY STOWAWAYS ON BOARD, CY DEP GM Mtr, CY REQUISITIONS RECEIVED, DISTANCE TO NEXT PILOT, TUG SAILING TRANSIT, STEAMING TIME M E Rsdl VLS, STEAMING TIME M E Rsdl HS, STEAMING TIME M E Rsdl ULS, STEAMING TIME M E Dstlt VLS, STEAMING TIME M E Dstlt ULS, STEAMING TIME M E Tnktnr Dstlt VLS, STEAMING TIME M E MDO, STEAMING TIME AUX 1, STEAMING TIME AUX 2, STEAMING TIME AUX 3, STEAMING TIME AUX 4, STEAMING TIME AUX 5, ...]
Index: []

[0 rows x 215 columns]

In [31]:
charter.columns.to_list()

['GID',
 'VSL',
 'IMO No',
 'VOY',
 'Corrected Date',
 'REPORT DATE TIME',
 'REPORT DATE TIME Offset',
 'Report Type',
 'Status',
 'LAT',
 'LONG',
 'M E FOC',
 'CARGO TOTAL',
 'Has Cargo',
 'STEAMING TIME',
 'Total M E Hours Fuel Only',
 'MILES BY GPS',
 'OIL CYL',
 'SPEED BY LOG',
 'SPEED BY GPS',
 'RPM',
 'SLIP',
 'WIND DIRECTION',
 'WIND SPEED',
 'DRAFT AFT',
 'DRAFT FWD',
 'DISPLACEMENT',
 'COURSE AT SEA',
 'WAVE HEIGHT',
 'SEA DIRECTION',
 'CARGO TOTAL TEU',
 'AMBIENT TEMP',
 'SW TEMP',
 'MILES BY SPEED LOG',
 'ETA PORT CODE',
 'ETA DATE TIME',
 'ETA DATE TIME Offset',
 'ETA PORT',
 'TIME CHANGE',
 'TIME SEA',
 'TEMP MIN',
 'TEMP MAX',
 'REQUESTED SPEED',
 'REM DIST TO PILOT',
 'REM TIME TO PILOT',
 'TOTAL UNPLND STPGE TECH',
 'TOTAL UNPLND STPGE OPE WX',
 'REEFERS POSITIVE PLUGGED',
 'REEFERS NEGATIVE PLUGGED',
 'ME TOTAL REVS COUNTER',
 'PORT CODE',
 'PORT',
 'AUX BLOWERS ON',
 'HOLD VENTILATION ON',
 'TIME HRS ANCHOR',
 'TIME HRS DRIFT',
 'REASON',
 'TYPE OF DELAY',
 'ETB DATE TIME',
 'ETB DATE TIME Offset',
 'PILOT DATE TIME',
 'PILOT DATE TIME Offset',
 'TIME MANOEUVRING',
 'TUG ARR',
 'TUG SHIFT',
 'ETD DATE TIME',
 'ETD DATE TIME Offset',
 'SHIFT BERTH HOURS',
 'CARGO LOAD',
 'CARGO DISCH',
 'TEU FULL',
 'TEU EMPTY',
 'BILGE REMOVED',
 'GARBAGE REMOVED',
 'GARBAGE REMVL REQSTD',
 'GARBAGE REMVL CMPLSRY',
 'FW SUPPLY',
 'CY CREW SIGNED ON',
 'CY CREW SIGNED OFF',
 'CY DOCTORS VISIT',
 'CY MAIL RECEIVED Ref NO',
 'CY LUB OIL SAMPLE LANDED',
 'CY CHECKD FOR STOWAWAYS',
 'CY STOWAWAYS ON BOARD',
 'CY DEP GM Mtr',
 'CY REQUISITIONS RECEIVED',
 'DISTANCE TO NEXT PILOT',
 'TUG SAILING TRANSIT',
 'STEAMING TIME M E Rsdl VLS',
 'STEAMING TIME M E Rsdl HS',
 'STEAMING TIME M E Rsdl ULS',
 'STEAMING TIME M E Dstlt VLS',
 'STEAMING TIME M E Dstlt ULS',
 'STEAMING TIME M E Tnktnr Dstlt VLS',
 'STEAMING TIME M E MDO',
 'STEAMING TIME AUX 1',
 'STEAMING TIME AUX 2',
 'STEAMING TIME AUX 3',
 'STEAMING TIME AUX 4',
 'STEAMING TIME AUX 5',
 'STEAMING TIME SH GEN',
 'STEAMING TIME TG',
 'FUEL M E Rsdl VLS',
 'FUEL M E Rsdl HS',
 'FUEL M E Rsdl ULS',
 'FUEL M E Dstlt VLS',
 'FUEL M E Dstlt ULS',
 'FUEL M E MDO',
 'FUEL M E LNG',
 'FUEL M E Tnktnr Dstlt VLS',
 'FUEL Aux Rsdl VLS',
 'FUEL Aux Rsdl HS',
 'FUEL Aux Rsdl ULS',
 'FUEL Aux Dstlt VLS',
 'FUEL Aux Dstlt ULS',
 'FUEL Aux Tnktnr Dstlt VLS',
 'FUEL Aux LNG',
 'FUEL Aux MDO',
 'FUEL Boiler Rsdl VLS',
 'FUEL Boiler Rsdl HS',
 'FUEL Boiler Rsdl ULS',
 'FUEL Boiler Dstlt VLS',
 'FUEL Boiler Dstlt ULS',
 'FUEL Boiler Tnktnr Dstlt VLS',
 'FUEL Boiler LNG',
 'FUEL Boiler MDO',
 'POWER KW',
 'STEAMING LOAD KW AUX 1',
 'STEAMING LOAD KW AUX 2',
 'STEAMING LOAD KW AUX 3',
 'STEAMING LOAD KW AUX 4',
 'STEAMING LOAD KW AUX 5',
 'STEAMING LOAD KW SH GEN',
 'STEAMING LOAD KW TG',
 'DECK LAST CHANGE USER',
 'ENGINE LAST CHANGE USER',
 'DECK PART IS COMPLETE',
 'ENGINE PART IS COMPLETE',
 'SCAVENGE PRESSURE',
 'SECA ENTRY TIME',
 'SECA ENTRY LAT',
 'SECA ENTRY LONG',
 'SECA EXIT TIME',
 'SECA EXIT LAT',
 'SECA EXIT LONG',
 'ROB FRESH WATER',
 'MANVRNG MILES BY GPS',
 'MANVRNG MILES BY SPEED LOG',
 'TANKTAINER TRANSFD QUANTITY',
 'PILOT TAKEN',
 'DATE TIME START TRANSIT',
 'DATE TIME START TRANSIT Offset',
 'DATE TIME END TRANSIT',
 'DATE TIME END TRANSIT Offset',
 'BALLAST',
 'TANKTAINER NUMBER',
 'STEAMING KWHR TOTAL',
 'CY OTHERS',
 'ROB FO SLUDGE',
 'ROB LO SLUDGE',
 'ROB BILGE',
 'SLUDGE REMOVED FO',
 'SLUDGE REMOVED LO',
 'SEA STATE',
 'CY LUB ADDED TO SYSTEM MECC',
 'CY LUB ADDED TO SYSTEM AECC',
 'CY LUB ADDED TO THRUSTERS',
 'CY ME LO PURIFIER IN USE',
 'CY BALLAST',
 'CY BENDING MOMENT',
 'CY SHEARING FORCE',
 'CY TORTION MOMENT',
 'CY SUPDT AUDITOR SIGNED ON',
 'CY SUPDT AUDITOR SIGNED OFF',
 'CY CASH RECEIVED',
 'CY LUB OIL RECEIVED MECYL',
 'CY LUB OIL RECEIVED MECC',
 'CY LUB OIL RECEIVED AECC',
 'CY M E UNDER PISTON TEMP',
 'CY MAIL RECEIVED',
 'WIND DIRECTION PORT STBD',
 'SEA DIRECTION PORT STBD',
 'TIME PILOT ONBOARD',
 'GRADES ROB',
 'SO2 CO2 RATIO',
 'Bunker Order',
 'Remarks',
 'BDN Number',
 'Fuel Type',
 'Carbon Factor',
 'Sulphur Content PC',
 'Quantity',
 'Port Delivery',
 'Product Quality',
 'Tanktainer Number_1',
 'Supplier',
 'Delivery',
 'Vol Lt',
 'Den',
 'Vis',
 'ROB Dstlt ULS',
 'ROB Dstlt VLS',
 'ROB Rsdl MDO',
 'ROB Tnktnr Dstlt VLS',
 'ROB Rsdl VLS',
 'ROB Rsdl HS',
 'ROB Rsdl ULS',
 'ROB Rsdl LNG',
 'ECA MILES',
 'ECA TIME',
 'EGCS DRY WASTE REMOVED',
 'EGCS RUNNING TIME',
 'EGCS WET SLURRY REMOVED',
 'EGCS OPEN LOOP RUNNING TIME',
 'EGCS CLOSED LOOP RUNNING TIME']

In [33]:
charter['STEAMING TIME M E HS'] = charter['STEAMING TIME M E Rsdl HS']
charter['STEAMING TIME M E LS'] = charter[['STEAMING TIME M E Rsdl ULS','STEAMING TIME M E Rsdl VLS']].sum(axis=1) 
charter['STEAMING TIME M E MGO'] = charter[['STEAMING TIME M E Dstlt VLS','STEAMING TIME M E Tnktnr Dstlt VLS']].sum(axis=1)
charter['STEAMING TIME M E MGO LS'] = charter['STEAMING TIME M E Dstlt ULS']
charter['FUEL M E HS'] = charter['FUEL M E Rsdl HS'] 
charter['FUEL M E LS'] = charter[['FUEL M E Rsdl VLS','FUEL M E Rsdl ULS']].sum(axis=1)
charter['FUEL M E MGO'] = charter[['FUEL M E Dstlt VLS','FUEL M E Tnktnr Dstlt VLS']].sum(axis=1)
charter['FUEL M E MGO LS'] = charter['FUEL M E Dstlt ULS']
charter['FUEL Aux HS'] = charter['FUEL Aux Rsdl HS']
charter['FUEL Aux LS'] = charter[['FUEL Aux Rsdl VLS','FUEL Aux Rsdl ULS']].sum(axis=1)
charter['FUEL Aux MGO'] = charter[['FUEL Aux Dstlt VLS','FUEL Aux Tnktnr Dstlt VLS']].sum(axis=1)
charter['FUEL Aux MGO LS'] = charter['FUEL Aux Dstlt ULS']
charter['FUEL Boiler HS'] = charter['FUEL Boiler Rsdl HS'] 
charter['FUEL Boiler LS'] = charter[['FUEL Boiler Rsdl VLS','FUEL Boiler Rsdl ULS']].sum(axis=1)
charter['FUEL Boiler MGO'] = charter[['FUEL Boiler Dstlt VLS','FUEL Boiler Tnktnr Dstlt VLS']].sum(axis=1)
charter['FUEL Boiler MGO LS'] = charter['FUEL Boiler Dstlt ULS']
charter['ROB FUEL HSFO'] = charter['ROB Rsdl HS'] 
charter['ROB FUEL LSFO'] = charter[['ROB Rsdl VLS','ROB Rsdl ULS']].sum(axis=1)
charter['ROB FUEL MDO'] = charter['ROB Rsdl MDO']
charter['ROB FUEL MGO'] = charter['ROB Dstlt VLS']
charter['ROB FUEL MGO LS'] = charter['ROB Dstlt ULS']
charter['ROB FUEL Tanktainer MGO'] = charter['ROB Tnktnr Dstlt VLS']
charter

,GID,VSL,IMO No,VOY,Corrected Date,REPORT DATE TIME,REPORT DATE TIME Offset,Report Type,Status,LAT,...,FUEL Boiler HS,FUEL Boiler LS,FUEL Boiler MGO,FUEL Boiler MGO LS,ROB FUEL HSFO,ROB FUEL LSFO,ROB FUEL MDO,ROB FUEL MGO,ROB FUEL MGO LS,ROB FUEL Tanktainer MGO
0,202b3fcb-ddcb-41ef-8365-b3d28ddcb8ca,MSC AURELIA,76021200.0,407,2024-08-01,2024-08-01 06:12:00,UTC +02:00,EOSP,AT SEA,4328N,...,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,292.30,0.0
1,26e61ea7-3216-4bb7-a0ce-e5b69d34cf60,MSC AURELIA,76021200.0,407,2024-08-01,2024-08-01 06:42:00,UTC +02:00,BRTH,DRIFTING,4328N,...,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,291.86,0.0
2,571a8985-617b-4f85-9eab-ef133661da63,MSC AURELIA,76021200.0,407,2024-08-01,2024-08-01 12:00:00,UTC +02:00,PORT,IN PORT,4328N,...,0.0,0.0,0.0,0.02,0.00,0.0,0.0,0.0,290.64,0.0
3,a9d7bd6d-6015-4dd0-8e9e-f40d2c5285eb,MSC AURELIA,76021200.0,407,2024-08-02,2024-08-01 19:30:00,UTC +02:00,SAIL,IN PORT,4328N,...,0.0,0.0,0.0,0.02,0.00,0.0,0.0,0.0,288.74,0.0
4,50ad5a0d-838a-4c10-9d7d-94d8c1bde30e,MSC AURELIA,76021200.0,407,2024-08-02,2024-08-01 19:48:00,UTC +02:00,COSP,DRIFTING,4328N,...,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,288.48,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47591,3779916a-357d-47ca-85a0-0a957a87dc39,MSC COTONOU VIII,99836710.0,UL430W,2024-08-28,2024-08-28 12:00:00,UTC -01:00,NOON,AT SEA,1624S,...,0.0,0.0,0.0,0.00,919.11,0.0,0.0,0.0,0.00,0.0
47592,a7e76ef4-1b7d-45d0-a629-4b0afb94199a,MSC COTONOU VIII,99836710.0,UL430W,2024-08-29,2024-08-29 12:00:00,UTC +00:00,NOON,AT SEA,2034S,...,0.0,0.0,0.0,0.00,835.93,0.0,0.0,0.0,0.00,0.0
47593,3de94823-cffe-469d-b306-02b47aea9d1f,MSC COTONOU VIII,99836710.0,UL430W,2024-08-30,2024-08-30 12:00:00,UTC +00:00,NOON,AT SEA,2459S,...,0.0,0.0,0.0,0.00,749.71,0.0,0.0,0.0,0.00,0.0
47594,fc8528e4-6372-4790-8fbd-3465bb213757,MSC COTONOU VIII,99836710.0,UL430W,2024-08-31,2024-08-31 12:00:00,UTC +00:00,NOON,AT SEA,2932S,...,0.0,0.0,0.0,0.00,665.45,0.0,0.0,0.0,0.00,0.0
47595,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN

In [35]:
#remove 'BDN Number' column
charter = charter.drop('BDN Number',axis=1)
charter

,GID,VSL,IMO No,VOY,Corrected Date,REPORT DATE TIME,REPORT DATE TIME Offset,Report Type,Status,LAT,...,FUEL Boiler HS,FUEL Boiler LS,FUEL Boiler MGO,FUEL Boiler MGO LS,ROB FUEL HSFO,ROB FUEL LSFO,ROB FUEL MDO,ROB FUEL MGO,ROB FUEL MGO LS,ROB FUEL Tanktainer MGO
0,202b3fcb-ddcb-41ef-8365-b3d28ddcb8ca,MSC AURELIA,76021200.0,407,2024-08-01,2024-08-01 06:12:00,UTC +02:00,EOSP,AT SEA,4328N,...,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,292.30,0.0
1,26e61ea7-3216-4bb7-a0ce-e5b69d34cf60,MSC AURELIA,76021200.0,407,2024-08-01,2024-08-01 06:42:00,UTC +02:00,BRTH,DRIFTING,4328N,...,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,291.86,0.0
2,571a8985-617b-4f85-9eab-ef133661da63,MSC AURELIA,76021200.0,407,2024-08-01,2024-08-01 12:00:00,UTC +02:00,PORT,IN PORT,4328N,...,0.0,0.0,0.0,0.02,0.00,0.0,0.0,0.0,290.64,0.0
3,a9d7bd6d-6015-4dd0-8e9e-f40d2c5285eb,MSC AURELIA,76021200.0,407,2024-08-02,2024-08-01 19:30:00,UTC +02:00,SAIL,IN PORT,4328N,...,0.0,0.0,0.0,0.02,0.00,0.0,0.0,0.0,288.74,0.0
4,50ad5a0d-838a-4c10-9d7d-94d8c1bde30e,MSC AURELIA,76021200.0,407,2024-08-02,2024-08-01 19:48:00,UTC +02:00,COSP,DRIFTING,4328N,...,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,288.48,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47591,3779916a-357d-47ca-85a0-0a957a87dc39,MSC COTONOU VIII,99836710.0,UL430W,2024-08-28,2024-08-28 12:00:00,UTC -01:00,NOON,AT SEA,1624S,...,0.0,0.0,0.0,0.00,919.11,0.0,0.0,0.0,0.00,0.0
47592,a7e76ef4-1b7d-45d0-a629-4b0afb94199a,MSC COTONOU VIII,99836710.0,UL430W,2024-08-29,2024-08-29 12:00:00,UTC +00:00,NOON,AT SEA,2034S,...,0.0,0.0,0.0,0.00,835.93,0.0,0.0,0.0,0.00,0.0
47593,3de94823-cffe-469d-b306-02b47aea9d1f,MSC COTONOU VIII,99836710.0,UL430W,2024-08-30,2024-08-30 12:00:00,UTC +00:00,NOON,AT SEA,2459S,...,0.0,0.0,0.0,0.00,749.71,0.0,0.0,0.0,0.00,0.0
47594,fc8528e4-6372-4790-8fbd-3465bb213757,MSC COTONOU VIII,99836710.0,UL430W,2024-08-31,2024-08-31 12:00:00,UTC +00:00,NOON,AT SEA,2932S,...,0.0,0.0,0.0,0.00,665.45,0.0,0.0,0.0,0.00,0.0
47595,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN

In [37]:
#add 'SINCE_DATE_TIME','SINCE_DATE_TIME_Offset' columns as null value
import numpy as np
charter['SINCE_DATE_TIME'] = np.nan
charter['SINCE_DATE_TIME_Offset'] = np.nan
charter

,GID,VSL,IMO No,VOY,Corrected Date,REPORT DATE TIME,REPORT DATE TIME Offset,Report Type,Status,LAT,...,FUEL Boiler MGO,FUEL Boiler MGO LS,ROB FUEL HSFO,ROB FUEL LSFO,ROB FUEL MDO,ROB FUEL MGO,ROB FUEL MGO LS,ROB FUEL Tanktainer MGO,SINCE_DATE_TIME,SINCE_DATE_TIME_Offset
0,202b3fcb-ddcb-41ef-8365-b3d28ddcb8ca,MSC AURELIA,76021200.0,407,2024-08-01,2024-08-01 06:12:00,UTC +02:00,EOSP,AT SEA,4328N,...,0.0,0.00,0.00,0.0,0.0,0.0,292.30,0.0,NaN,NaN
1,26e61ea7-3216-4bb7-a0ce-e5b69d34cf60,MSC AURELIA,76021200.0,407,2024-08-01,2024-08-01 06:42:00,UTC +02:00,BRTH,DRIFTING,4328N,...,0.0,0.00,0.00,0.0,0.0,0.0,291.86,0.0,NaN,NaN
2,571a8985-617b-4f85-9eab-ef133661da63,MSC AURELIA,76021200.0,407,2024-08-01,2024-08-01 12:00:00,UTC +02:00,PORT,IN PORT,4328N,...,0.0,0.02,0.00,0.0,0.0,0.0,290.64,0.0,NaN,NaN
3,a9d7bd6d-6015-4dd0-8e9e-f40d2c5285eb,MSC AURELIA,76021200.0,407,2024-08-02,2024-08-01 19:30:00,UTC +02:00,SAIL,IN PORT,4328N,...,0.0,0.02,0.00,0.0,0.0,0.0,288.74,0.0,NaN,NaN
4,50ad5a0d-838a-4c10-9d7d-94d8c1bde30e,MSC AURELIA,76021200.0,407,2024-08-02,2024-08-01 19:48:00,UTC +02:00,COSP,DRIFTING,4328N,...,0.0,0.00,0.00,0.0,0.0,0.0,288.48,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47591,3779916a-357d-47ca-85a0-0a957a87dc39,MSC COTONOU VIII,99836710.0,UL430W,2024-08-28,2024-08-28 12:00:00,UTC -01:00,NOON,AT SEA,1624S,...,0.0,0.00,919.11,0.0,0.0,0.0,0.00,0.0,NaN,NaN
47592,a7e76ef4-1b7d-45d0-a629-4b0afb94199a,MSC COTONOU VIII,99836710.0,UL430W,2024-08-29,2024-08-29 12:00:00,UTC +00:00,NOON,AT SEA,2034S,...,0.0,0.00,835.93,0.0,0.0,0.0,0.00,0.0,NaN,NaN
47593,3de94823-cffe-469d-b306-02b47aea9d1f,MSC COTONOU VIII,99836710.0,UL430W,2024-08-30,2024-08-30 12:00:00,UTC +00:00,NOON,AT SEA,2459S,...,0.0,0.00,749.71,0.0,0.0,0.0,0.00,0.0,NaN,NaN
47594,fc8528e4-6372-4790-8fbd-3465bb213757,MSC COTONOU VIII,99836710.0,UL430W,2024-08-31,2024-08-31 12:00:00,UTC +00:00,NOON,AT SEA,2932S,...,0.0,0.00,665.45,0.0,0.0,0.0,0.00,0.0,NaN,NaN
47595,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
col = pd.read_excel(r"D:\Navalt\MSC\2023\Weekly Data\SERVER REF\Updated calculations in DB for updated fuel type 1.xlsx")
col

,Noondata,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Charter Data
0,idvessel,NaN,NaN,NaN,NaN,NaN,NaN,GID
1,GID,NaN,NaN,NaN,NaN,NaN,NaN,VSL
2,VSL,NaN,NaN,NaN,NaN,NaN,NaN,IMO_No
3,IMO_No,NaN,NaN,NaN,NaN,NaN,NaN,VOY
4,VOY,NaN,NaN,NaN,NaN,NaN,NaN,Corrected_Date
...,...,...,...,...,...,...,...,...
261,Kwhr_total,NaN,NaN,NaN,NaN,NaN,NaN,Sludge_rob
262,Sludge_rob,NaN,NaN,NaN,NaN,NaN,NaN,Sludge_min_discharge_request
263,Sludge_min_discharge_request,NaN,NaN,NaN,NaN,NaN,NaN,Rob_actual_sludge
264,Rob_actual_sludge,NaN,NaN,NaN,NaN,NaN,NaN,Qty_sludge_disposed
265,Qty_sludge_disposed,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
col_lst = col['Charter Data'].tolist()
col_lst

['GID',
 'VSL',
 'IMO_No',
 'VOY',
 'Corrected_Date',
 'REPORT_DATE_TIME',
 'REPORT_DATE_TIME_Offset',
 'Report_Type',
 'Status',
 'LAT',
 'LONG_',
 'M_E_FOC',
 'CARGO_TOTAL',
 'Has_Cargo',
 'STEAMING_TIME',
 'Total_M_E_Hours_Fuel_Only',
 'MILES_BY_GPS',
 'OIL_CYL',
 'SPEED_BY_LOG',
 'SPEED_BY_GPS',
 'RPM',
 'SLIP',
 'WIND_DIRECTION',
 'WIND_SPEED',
 'DRAFT_AFT',
 'DRAFT_FWD',
 'DISPLACEMENT',
 'COURSE_AT_SEA',
 'WAVE_HEIGHT',
 'SEA_DIRECTION',
 'CARGO_TOTAL_TEU',
 'AMBIENT_TEMP',
 'SW_TEMP',
 'MILES_BY_SPEED_LOG',
 'ETA_PORT_CODE',
 'ETA_DATE_TIME',
 'ETA_DATE_TIME_Offset',
 'ETA_PORT',
 'TIME_CHANGE',
 'TIME_SEA',
 'TEMP_MIN',
 'TEMP_MAX',
 'REQUESTED_SPEED',
 'REM_DIST_TO_PILOT',
 'REM_TIME_TO_PILOT',
 'TOTAL_UNPLND_STPGE_TECH',
 'TOTAL_UNPLND_STPGE_OPE_WX',
 'REEFERS_POSITIVE_PLUGGED',
 'REEFERS_NEGATIVE_PLUGGED',
 'ME_TOTAL_REVS_COUNTER',
 'PORT_CODE',
 'PORT',
 'AUX_BLOWERS_ON',
 'HOLD_VENTILATION_ON',
 'SINCE_DATE_TIME',
 'SINCE_DATE_TIME_Offset',
 'TIME_HRS_ANCHOR',
 'TIME_HRS_DRIFT',
 'REASON',
 'TYPE_OF_DELAY',
 'ETB_DATE_TIME',
 'ETB_DATE_TIME_Offset',
 'PILOT_DATE_TIME',
 'PILOT_DATE_TIME_Offset',
 'TIME_MANOEUVRING',
 'TUG_ARR',
 'TUG_SHIFT',
 'ETD_DATE_TIME',
 'ETD_DATE_TIME_Offset',
 'SHIFT_BERTH_HOURS',
 'CARGO_LOAD',
 'CARGO_DISCH',
 'TEU_FULL',
 'TEU_EMPTY',
 'BILGE_REMOVED',
 'GARBAGE_REMOVED',
 'GARBAGE_REMVL_REQSTD',
 'GARBAGE_REMVL_CMPLSRY',
 'FW_SUPPLY',
 'CY_CREW_SIGNED_ON',
 'CY_CREW_SIGNED_OFF',
 'CY_DOCTORS_VISIT',
 'CY_MAIL_RECEIVED_Ref_NO',
 'CY_LUB_OIL_SAMPLE_LANDED',
 'CY_CHECKD_FOR_STOWAWAYS',
 'CY_STOWAWAYS_ON_BOARD',
 'CY_DEP_GM_Mtr',
 'CY_REQUISITIONS_RECEIVED',
 'DISTANCE_TO_NEXT_PILOT',
 'TUG_SAILING_TRANSIT',
 'STEAMING_TIME_M_E_Rsdl_VLS',
 'STEAMING_TIME_M_E_Rsdl_HS',
 'STEAMING_TIME_M_E_Rsdl_ULS',
 'STEAMING_TIME_M_E_Dstlt_VLS',
 'STEAMING_TIME_M_E_Dstlt_ULS',
 'STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS',
 'STEAMING_TIME_M_E_HS',
 'STEAMING_TIME_M_E_LS',
 'STEAMING_TIME_M_E_MDO',
 'STEAMING_TIME_M_E_MGO',
 'STEAMING_TIME_M_E_MGO_LS',
 'STEAMING_TIME_AUX_1',
 'STEAMING_TIME_AUX_2',
 'STEAMING_TIME_AUX_3',
 'STEAMING_TIME_AUX_4',
 'STEAMING_TIME_AUX_5',
 'STEAMING_TIME_SH_GEN',
 'STEAMING_TIME_TG',
 'POWER_KW',
 'STEAMING_LOAD_KW_AUX_1',
 'STEAMING_LOAD_KW_AUX_2',
 'STEAMING_LOAD_KW_AUX_3',
 'STEAMING_LOAD_KW_AUX_4',
 'STEAMING_LOAD_KW_AUX_5',
 'STEAMING_LOAD_KW_SH_GEN',
 'STEAMING_LOAD_KW_TG',
 'FUEL_M_E_Rsdl_VLS',
 'FUEL_M_E_Rsdl_HS',
 'FUEL_M_E_Rsdl_ULS',
 'FUEL_M_E_Dstlt_VLS',
 'FUEL_M_E_Dstlt_ULS',
 'FUEL_M_E_Tnktnr_Dstlt_VLS',
 'FUEL_M_E_HS',
 'FUEL_M_E_LS',
 'FUEL_M_E_MDO',
 'FUEL_M_E_MGO',
 'FUEL_M_E_MGO_LS',
 'FUEL_Aux_Rsdl_VLS',
 'FUEL_Aux_Rsdl_HS',
 'FUEL_Aux_Rsdl_ULS',
 'FUEL_Aux_Dstlt_VLS',
 'FUEL_Aux_Dstlt_ULS',
 'FUEL_Aux_Tnktnr_Dstlt_VLS',
 'FUEL_AUX_HS',
 'FUEL_AUX_LS',
 'FUEL_AUX_MDO',
 'FUEL_AUX_MGO',
 'FUEL_AUX_MGO_LS',
 'FUEL_Boiler_Rsdl_VLS',
 'FUEL_Boiler_Rsdl_HS',
 'FUEL_Boiler_Rsdl_ULS',
 'FUEL_Boiler_Dstlt_VLS',
 'FUEL_Boiler_Dstlt_ULS',
 'FUEL_Boiler_Tnktnr_Dstlt_VLS',
 'FUEL_BOILER_HS',
 'FUEL_BOILER_LS',
 'FUEL_BOILER_MDO',
 'FUEL_BOILER_MGO',
 'FUEL_BOILER_MGO_LS',
 'DECK_LAST_CHANGE_USER',
 'ENGINE_LAST_CHANGE_USER',
 'DECK_PART_IS_COMPLETE',
 'ENGINE_PART_IS_COMPLETE',
 'SCAVENGE_PRESSURE',
 'SECA_ENTRY_TIME',
 'SECA_ENTRY_LAT',
 'SECA_ENTRY_LONG',
 'SECA_EXIT_TIME',
 'SECA_EXIT_LAT',
 'SECA_EXIT_LONG',
 'ROB_FRESH_WATER',
 'MANVRNG_MILES_BY_GPS',
 'MANVRNG_MILES_BY_SPEED_LOG',
 'TANKTAINER_TRANSFD_QUANTITY',
 'PILOT_TAKEN',
 'DATE_TIME_START_TRANSIT',
 'DATE_TIME_START_TRANSIT_Offset',
 'DATE_TIME_END_TRANSIT',
 'DATE_TIME_END_TRANSIT_Offset',
 'BALLAST',
 'TANKTAINER_NUMBER',
 'STEAMING_KWHR_TOTAL',
 'CY_OTHERS',
 'ROB_FO_SLUDGE',
 'ROB_LO_SLUDGE',
 'ROB_BILGE',
 'SLUDGE_REMOVED_FO',
 'SLUDGE_REMOVED_LO',
 'SEA_STATE',
 'CY_LUB_ADDED_TO_SYSTEM_MECC',
 'CY_LUB_ADDED_TO_SYSTEM_AECC',
 'CY_LUB_ADDED_TO_THRUSTERS',
 'CY_ME_LO_PURIFIER_IN_USE',
 'CY_BALLAST',
 'CY_BENDING_MOMENT',
 'CY_SHEARING_FORCE',
 'CY_TORTION_MOMENT',
 'CY_SUPDT_AUDITOR_SIGNED_ON',
 'CY_SUPDT_AUDITOR_SIGNED_OFF',
 'CY_CASH_RECEIVED',
 'CY_LUB_OIL_RECEIVED_MECYL',
 'CY_LUB_OIL_RECEIVED_MECC',
 'CY_LUB_OIL_RECEIVED_AECC',
 'CY_M_E_UNDER_PISTON_TEMP',
 'CY_MAIL_RECEIVED',
 'WIND_DIRECTION_PORT_STBD',
 'SEA_DIRECTION_PORT_STBD',
 'TIME_PILOT_ONBOARD',
 'GRADES_ROB',
 'SO2_CO2_RATIO',
 'Bunker_Order',
 'Remarks',
 'Fuel_Type',
 'Carbon_Factor',
 'Sulphur_Content_PC',
 'Quantity',
 'Port_Delivery',
 'Product_Quality',
 'Tanktainer_Number_1',
 'Supplier',
 'Delivery',
 'Vol_Lt',
 'Den',
 'Vis',
 'ROB_Dstlt_ULS',
 'ROB_Dstlt_VLS',
 'ROB_Rsdl_MDO',
 'ROB_Tnktnr_Dstlt_VLS',
 'ROB_Rsdl_VLS',
 'ROB_Rsdl_HS',
 'ROB_Rsdl_ULS',
 'ROB_Fuel_HSFO',
 'ROB_Fuel_LSFO',
 'ROB_Fuel_MDO',
 'ROB_Fuel_MGO',
 'ROB_Fuel_MGO_LS',
 'ROB_Fuel_Tanktainer_MGO',
 'ECA_MILES',
 'ECA_TIME',
 'EGCS_DRY_WASTE_REMOVED',
 'EGCS_RUNNING_TIME',
 'EGCS_WET_SLURRY_REMOVED',
 'EGCS_OPEN_LOOP_RUNNING_TIME',
 'EGCS_CLOSED_LOOP_RUNNING_TIME',
 'FUEL_M_E_LNG',
 'FUEL_Aux_LNG',
 'FUEL_Boiler_LNG',
 'ROB_Rsdl_LNG',
 'Max_Residual_HS_capacity',
 'Max_Lng_capacity',
 'Min_Lng_request',
 'Tanktainer_min_request',
 'Comments',
 'Template_version',
 'Pilot_date/time',
 'PIER_date/time',
 'Hold_ventilation_off',
 'Rob_tot_Sludge',
 'Reefer_power_consumption',
 'Tanktainer_distillates_transfd',
 'Hold_Ventilation_On/Off',
 'Tot_sludge_removed',
 'Garbage_cat_a_-_plastic_removed',
 'Garbage_cat_b_-_organic_removed',
 'Garbage_cat_c_-_domestic_removed',
 'Garbage_cat_e_-_ashes_removed',
 'Rob_garbage_cat_a_-_plastic',
 'Rob_garbage_cat_b_-_organic',
 'Rob_garbage_cat_c_-_domestic',
 'Rob_garbage_cat_e_-_ashes',
 'Kwhr_total',
 'Sludge_rob',
 'Sludge_min_discharge_request',
 'Rob_actual_sludge',
 'Qty_sludge_disposed',
 nan]

In [43]:
weekcol = charter.columns.tolist()
weekcol

['GID',
 'VSL',
 'IMO No',
 'VOY',
 'Corrected Date',
 'REPORT DATE TIME',
 'REPORT DATE TIME Offset',
 'Report Type',
 'Status',
 'LAT',
 'LONG',
 'M E FOC',
 'CARGO TOTAL',
 'Has Cargo',
 'STEAMING TIME',
 'Total M E Hours Fuel Only',
 'MILES BY GPS',
 'OIL CYL',
 'SPEED BY LOG',
 'SPEED BY GPS',
 'RPM',
 'SLIP',
 'WIND DIRECTION',
 'WIND SPEED',
 'DRAFT AFT',
 'DRAFT FWD',
 'DISPLACEMENT',
 'COURSE AT SEA',
 'WAVE HEIGHT',
 'SEA DIRECTION',
 'CARGO TOTAL TEU',
 'AMBIENT TEMP',
 'SW TEMP',
 'MILES BY SPEED LOG',
 'ETA PORT CODE',
 'ETA DATE TIME',
 'ETA DATE TIME Offset',
 'ETA PORT',
 'TIME CHANGE',
 'TIME SEA',
 'TEMP MIN',
 'TEMP MAX',
 'REQUESTED SPEED',
 'REM DIST TO PILOT',
 'REM TIME TO PILOT',
 'TOTAL UNPLND STPGE TECH',
 'TOTAL UNPLND STPGE OPE WX',
 'REEFERS POSITIVE PLUGGED',
 'REEFERS NEGATIVE PLUGGED',
 'ME TOTAL REVS COUNTER',
 'PORT CODE',
 'PORT',
 'AUX BLOWERS ON',
 'HOLD VENTILATION ON',
 'TIME HRS ANCHOR',
 'TIME HRS DRIFT',
 'REASON',
 'TYPE OF DELAY',
 'ETB DATE TIME',
 'ETB DATE TIME Offset',
 'PILOT DATE TIME',
 'PILOT DATE TIME Offset',
 'TIME MANOEUVRING',
 'TUG ARR',
 'TUG SHIFT',
 'ETD DATE TIME',
 'ETD DATE TIME Offset',
 'SHIFT BERTH HOURS',
 'CARGO LOAD',
 'CARGO DISCH',
 'TEU FULL',
 'TEU EMPTY',
 'BILGE REMOVED',
 'GARBAGE REMOVED',
 'GARBAGE REMVL REQSTD',
 'GARBAGE REMVL CMPLSRY',
 'FW SUPPLY',
 'CY CREW SIGNED ON',
 'CY CREW SIGNED OFF',
 'CY DOCTORS VISIT',
 'CY MAIL RECEIVED Ref NO',
 'CY LUB OIL SAMPLE LANDED',
 'CY CHECKD FOR STOWAWAYS',
 'CY STOWAWAYS ON BOARD',
 'CY DEP GM Mtr',
 'CY REQUISITIONS RECEIVED',
 'DISTANCE TO NEXT PILOT',
 'TUG SAILING TRANSIT',
 'STEAMING TIME M E Rsdl VLS',
 'STEAMING TIME M E Rsdl HS',
 'STEAMING TIME M E Rsdl ULS',
 'STEAMING TIME M E Dstlt VLS',
 'STEAMING TIME M E Dstlt ULS',
 'STEAMING TIME M E Tnktnr Dstlt VLS',
 'STEAMING TIME M E MDO',
 'STEAMING TIME AUX 1',
 'STEAMING TIME AUX 2',
 'STEAMING TIME AUX 3',
 'STEAMING TIME AUX 4',
 'STEAMING TIME AUX 5',
 'STEAMING TIME SH GEN',
 'STEAMING TIME TG',
 'FUEL M E Rsdl VLS',
 'FUEL M E Rsdl HS',
 'FUEL M E Rsdl ULS',
 'FUEL M E Dstlt VLS',
 'FUEL M E Dstlt ULS',
 'FUEL M E MDO',
 'FUEL M E LNG',
 'FUEL M E Tnktnr Dstlt VLS',
 'FUEL Aux Rsdl VLS',
 'FUEL Aux Rsdl HS',
 'FUEL Aux Rsdl ULS',
 'FUEL Aux Dstlt VLS',
 'FUEL Aux Dstlt ULS',
 'FUEL Aux Tnktnr Dstlt VLS',
 'FUEL Aux LNG',
 'FUEL Aux MDO',
 'FUEL Boiler Rsdl VLS',
 'FUEL Boiler Rsdl HS',
 'FUEL Boiler Rsdl ULS',
 'FUEL Boiler Dstlt VLS',
 'FUEL Boiler Dstlt ULS',
 'FUEL Boiler Tnktnr Dstlt VLS',
 'FUEL Boiler LNG',
 'FUEL Boiler MDO',
 'POWER KW',
 'STEAMING LOAD KW AUX 1',
 'STEAMING LOAD KW AUX 2',
 'STEAMING LOAD KW AUX 3',
 'STEAMING LOAD KW AUX 4',
 'STEAMING LOAD KW AUX 5',
 'STEAMING LOAD KW SH GEN',
 'STEAMING LOAD KW TG',
 'DECK LAST CHANGE USER',
 'ENGINE LAST CHANGE USER',
 'DECK PART IS COMPLETE',
 'ENGINE PART IS COMPLETE',
 'SCAVENGE PRESSURE',
 'SECA ENTRY TIME',
 'SECA ENTRY LAT',
 'SECA ENTRY LONG',
 'SECA EXIT TIME',
 'SECA EXIT LAT',
 'SECA EXIT LONG',
 'ROB FRESH WATER',
 'MANVRNG MILES BY GPS',
 'MANVRNG MILES BY SPEED LOG',
 'TANKTAINER TRANSFD QUANTITY',
 'PILOT TAKEN',
 'DATE TIME START TRANSIT',
 'DATE TIME START TRANSIT Offset',
 'DATE TIME END TRANSIT',
 'DATE TIME END TRANSIT Offset',
 'BALLAST',
 'TANKTAINER NUMBER',
 'STEAMING KWHR TOTAL',
 'CY OTHERS',
 'ROB FO SLUDGE',
 'ROB LO SLUDGE',
 'ROB BILGE',
 'SLUDGE REMOVED FO',
 'SLUDGE REMOVED LO',
 'SEA STATE',
 'CY LUB ADDED TO SYSTEM MECC',
 'CY LUB ADDED TO SYSTEM AECC',
 'CY LUB ADDED TO THRUSTERS',
 'CY ME LO PURIFIER IN USE',
 'CY BALLAST',
 'CY BENDING MOMENT',
 'CY SHEARING FORCE',
 'CY TORTION MOMENT',
 'CY SUPDT AUDITOR SIGNED ON',
 'CY SUPDT AUDITOR SIGNED OFF',
 'CY CASH RECEIVED',
 'CY LUB OIL RECEIVED MECYL',
 'CY LUB OIL RECEIVED MECC',
 'CY LUB OIL RECEIVED AECC',
 'CY M E UNDER PISTON TEMP',
 'CY MAIL RECEIVED',
 'WIND DIRECTION PORT STBD',
 'SEA DIRECTION PORT STBD',
 'TIME PILOT ONBOARD',
 'GRADES ROB',
 'SO2 CO2 RATIO',
 'Bunker Order',
 'Remarks',
 'Fuel Type',
 'Carbon Factor',
 'Sulphur Content PC',
 'Quantity',
 'Port Delivery',
 'Product Quality',
 'Tanktainer Number_1',
 'Supplier',
 'Delivery',
 'Vol Lt',
 'Den',
 'Vis',
 'ROB Dstlt ULS',
 'ROB Dstlt VLS',
 'ROB Rsdl MDO',
 'ROB Tnktnr Dstlt VLS',
 'ROB Rsdl VLS',
 'ROB Rsdl HS',
 'ROB Rsdl ULS',
 'ROB Rsdl LNG',
 'ECA MILES',
 'ECA TIME',
 'EGCS DRY WASTE REMOVED',
 'EGCS RUNNING TIME',
 'EGCS WET SLURRY REMOVED',
 'EGCS OPEN LOOP RUNNING TIME',
 'EGCS CLOSED LOOP RUNNING TIME',
 'STEAMING TIME M E HS',
 'STEAMING TIME M E LS',
 'STEAMING TIME M E MGO',
 'STEAMING TIME M E MGO LS',
 'FUEL M E HS',
 'FUEL M E LS',
 'FUEL M E MGO',
 'FUEL M E MGO LS',
 'FUEL Aux HS',
 'FUEL Aux LS',
 'FUEL Aux MGO',
 'FUEL Aux MGO LS',
 'FUEL Boiler HS',
 'FUEL Boiler LS',
 'FUEL Boiler MGO',
 'FUEL Boiler MGO LS',
 'ROB FUEL HSFO',
 'ROB FUEL LSFO',
 'ROB FUEL MDO',
 'ROB FUEL MGO',
 'ROB FUEL MGO LS',
 'ROB FUEL Tanktainer MGO',
 'SINCE_DATE_TIME',
 'SINCE_DATE_TIME_Offset']

In [45]:
#correct column names as per noon Updated calculations in DB for updated fuel type file - charter data
#main difference is _,so replace all space as _
charter.columns = charter.columns.str.replace(' ','_')

In [47]:
charter.columns.tolist()

['GID',
 'VSL',
 'IMO_No',
 'VOY',
 'Corrected_Date',
 'REPORT_DATE_TIME',
 'REPORT_DATE_TIME_Offset',
 'Report_Type',
 'Status',
 'LAT',
 'LONG',
 'M_E_FOC',
 'CARGO_TOTAL',
 'Has_Cargo',
 'STEAMING_TIME',
 'Total_M_E_Hours_Fuel_Only',
 'MILES_BY_GPS',
 'OIL_CYL',
 'SPEED_BY_LOG',
 'SPEED_BY_GPS',
 'RPM',
 'SLIP',
 'WIND_DIRECTION',
 'WIND_SPEED',
 'DRAFT_AFT',
 'DRAFT_FWD',
 'DISPLACEMENT',
 'COURSE_AT_SEA',
 'WAVE_HEIGHT',
 'SEA_DIRECTION',
 'CARGO_TOTAL_TEU',
 'AMBIENT_TEMP',
 'SW_TEMP',
 'MILES_BY_SPEED_LOG',
 'ETA_PORT_CODE',
 'ETA_DATE_TIME',
 'ETA_DATE_TIME_Offset',
 'ETA_PORT',
 'TIME_CHANGE',
 'TIME_SEA',
 'TEMP_MIN',
 'TEMP_MAX',
 'REQUESTED_SPEED',
 'REM_DIST_TO_PILOT',
 'REM_TIME_TO_PILOT',
 'TOTAL_UNPLND_STPGE_TECH',
 'TOTAL_UNPLND_STPGE_OPE_WX',
 'REEFERS_POSITIVE_PLUGGED',
 'REEFERS_NEGATIVE_PLUGGED',
 'ME_TOTAL_REVS_COUNTER',
 'PORT_CODE',
 'PORT',
 'AUX_BLOWERS_ON',
 'HOLD_VENTILATION_ON',
 'TIME_HRS_ANCHOR',
 'TIME_HRS_DRIFT',
 'REASON',
 'TYPE_OF_DELAY',
 'ETB_DATE_TIME',
 'ETB_DATE_TIME_Offset',
 'PILOT_DATE_TIME',
 'PILOT_DATE_TIME_Offset',
 'TIME_MANOEUVRING',
 'TUG_ARR',
 'TUG_SHIFT',
 'ETD_DATE_TIME',
 'ETD_DATE_TIME_Offset',
 'SHIFT_BERTH_HOURS',
 'CARGO_LOAD',
 'CARGO_DISCH',
 'TEU_FULL',
 'TEU_EMPTY',
 'BILGE_REMOVED',
 'GARBAGE_REMOVED',
 'GARBAGE_REMVL_REQSTD',
 'GARBAGE_REMVL_CMPLSRY',
 'FW_SUPPLY',
 'CY_CREW_SIGNED_ON',
 'CY_CREW_SIGNED_OFF',
 'CY_DOCTORS_VISIT',
 'CY_MAIL_RECEIVED_Ref_NO',
 'CY_LUB_OIL_SAMPLE_LANDED',
 'CY_CHECKD_FOR_STOWAWAYS',
 'CY_STOWAWAYS_ON_BOARD',
 'CY_DEP_GM_Mtr',
 'CY_REQUISITIONS_RECEIVED',
 'DISTANCE_TO_NEXT_PILOT',
 'TUG_SAILING_TRANSIT',
 'STEAMING_TIME_M_E_Rsdl_VLS',
 'STEAMING_TIME_M_E_Rsdl_HS',
 'STEAMING_TIME_M_E_Rsdl_ULS',
 'STEAMING_TIME_M_E_Dstlt_VLS',
 'STEAMING_TIME_M_E_Dstlt_ULS',
 'STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS',
 'STEAMING_TIME_M_E_MDO',
 'STEAMING_TIME_AUX_1',
 'STEAMING_TIME_AUX_2',
 'STEAMING_TIME_AUX_3',
 'STEAMING_TIME_AUX_4',
 'STEAMING_TIME_AUX_5',
 'STEAMING_TIME_SH_GEN',
 'STEAMING_TIME_TG',
 'FUEL_M_E_Rsdl_VLS',
 'FUEL_M_E_Rsdl_HS',
 'FUEL_M_E_Rsdl_ULS',
 'FUEL_M_E_Dstlt_VLS',
 'FUEL_M_E_Dstlt_ULS',
 'FUEL_M_E_MDO',
 'FUEL_M_E_LNG',
 'FUEL_M_E_Tnktnr_Dstlt_VLS',
 'FUEL_Aux_Rsdl_VLS',
 'FUEL_Aux_Rsdl_HS',
 'FUEL_Aux_Rsdl_ULS',
 'FUEL_Aux_Dstlt_VLS',
 'FUEL_Aux_Dstlt_ULS',
 'FUEL_Aux_Tnktnr_Dstlt_VLS',
 'FUEL_Aux_LNG',
 'FUEL_Aux_MDO',
 'FUEL_Boiler_Rsdl_VLS',
 'FUEL_Boiler_Rsdl_HS',
 'FUEL_Boiler_Rsdl_ULS',
 'FUEL_Boiler_Dstlt_VLS',
 'FUEL_Boiler_Dstlt_ULS',
 'FUEL_Boiler_Tnktnr_Dstlt_VLS',
 'FUEL_Boiler_LNG',
 'FUEL_Boiler_MDO',
 'POWER_KW',
 'STEAMING_LOAD_KW_AUX_1',
 'STEAMING_LOAD_KW_AUX_2',
 'STEAMING_LOAD_KW_AUX_3',
 'STEAMING_LOAD_KW_AUX_4',
 'STEAMING_LOAD_KW_AUX_5',
 'STEAMING_LOAD_KW_SH_GEN',
 'STEAMING_LOAD_KW_TG',
 'DECK_LAST_CHANGE_USER',
 'ENGINE_LAST_CHANGE_USER',
 'DECK_PART_IS_COMPLETE',
 'ENGINE_PART_IS_COMPLETE',
 'SCAVENGE_PRESSURE',
 'SECA_ENTRY_TIME',
 'SECA_ENTRY_LAT',
 'SECA_ENTRY_LONG',
 'SECA_EXIT_TIME',
 'SECA_EXIT_LAT',
 'SECA_EXIT_LONG',
 'ROB_FRESH_WATER',
 'MANVRNG_MILES_BY_GPS',
 'MANVRNG_MILES_BY_SPEED_LOG',
 'TANKTAINER_TRANSFD_QUANTITY',
 'PILOT_TAKEN',
 'DATE_TIME_START_TRANSIT',
 'DATE_TIME_START_TRANSIT_Offset',
 'DATE_TIME_END_TRANSIT',
 'DATE_TIME_END_TRANSIT_Offset',
 'BALLAST',
 'TANKTAINER_NUMBER',
 'STEAMING_KWHR_TOTAL',
 'CY_OTHERS',
 'ROB_FO_SLUDGE',
 'ROB_LO_SLUDGE',
 'ROB_BILGE',
 'SLUDGE_REMOVED_FO',
 'SLUDGE_REMOVED_LO',
 'SEA_STATE',
 'CY_LUB_ADDED_TO_SYSTEM_MECC',
 'CY_LUB_ADDED_TO_SYSTEM_AECC',
 'CY_LUB_ADDED_TO_THRUSTERS',
 'CY_ME_LO_PURIFIER_IN_USE',
 'CY_BALLAST',
 'CY_BENDING_MOMENT',
 'CY_SHEARING_FORCE',
 'CY_TORTION_MOMENT',
 'CY_SUPDT_AUDITOR_SIGNED_ON',
 'CY_SUPDT_AUDITOR_SIGNED_OFF',
 'CY_CASH_RECEIVED',
 'CY_LUB_OIL_RECEIVED_MECYL',
 'CY_LUB_OIL_RECEIVED_MECC',
 'CY_LUB_OIL_RECEIVED_AECC',
 'CY_M_E_UNDER_PISTON_TEMP',
 'CY_MAIL_RECEIVED',
 'WIND_DIRECTION_PORT_STBD',
 'SEA_DIRECTION_PORT_STBD',
 'TIME_PILOT_ONBOARD',
 'GRADES_ROB',
 'SO2_CO2_RATIO',
 'Bunker_Order',
 'Remarks',
 'Fuel_Type',
 'Carbon_Factor',
 'Sulphur_Content_PC',
 'Quantity',
 'Port_Delivery',
 'Product_Quality',
 'Tanktainer_Number_1',
 'Supplier',
 'Delivery',
 'Vol_Lt',
 'Den',
 'Vis',
 'ROB_Dstlt_ULS',
 'ROB_Dstlt_VLS',
 'ROB_Rsdl_MDO',
 'ROB_Tnktnr_Dstlt_VLS',
 'ROB_Rsdl_VLS',
 'ROB_Rsdl_HS',
 'ROB_Rsdl_ULS',
 'ROB_Rsdl_LNG',
 'ECA_MILES',
 'ECA_TIME',
 'EGCS_DRY_WASTE_REMOVED',
 'EGCS_RUNNING_TIME',
 'EGCS_WET_SLURRY_REMOVED',
 'EGCS_OPEN_LOOP_RUNNING_TIME',
 'EGCS_CLOSED_LOOP_RUNNING_TIME',
 'STEAMING_TIME_M_E_HS',
 'STEAMING_TIME_M_E_LS',
 'STEAMING_TIME_M_E_MGO',
 'STEAMING_TIME_M_E_MGO_LS',
 'FUEL_M_E_HS',
 'FUEL_M_E_LS',
 'FUEL_M_E_MGO',
 'FUEL_M_E_MGO_LS',
 'FUEL_Aux_HS',
 'FUEL_Aux_LS',
 'FUEL_Aux_MGO',
 'FUEL_Aux_MGO_LS',
 'FUEL_Boiler_HS',
 'FUEL_Boiler_LS',
 'FUEL_Boiler_MGO',
 'FUEL_Boiler_MGO_LS',
 'ROB_FUEL_HSFO',
 'ROB_FUEL_LSFO',
 'ROB_FUEL_MDO',
 'ROB_FUEL_MGO',
 'ROB_FUEL_MGO_LS',
 'ROB_FUEL_Tanktainer_MGO',
 'SINCE_DATE_TIME',
 'SINCE_DATE_TIME_Offset']

In [49]:
col_lst

['GID',
 'VSL',
 'IMO_No',
 'VOY',
 'Corrected_Date',
 'REPORT_DATE_TIME',
 'REPORT_DATE_TIME_Offset',
 'Report_Type',
 'Status',
 'LAT',
 'LONG_',
 'M_E_FOC',
 'CARGO_TOTAL',
 'Has_Cargo',
 'STEAMING_TIME',
 'Total_M_E_Hours_Fuel_Only',
 'MILES_BY_GPS',
 'OIL_CYL',
 'SPEED_BY_LOG',
 'SPEED_BY_GPS',
 'RPM',
 'SLIP',
 'WIND_DIRECTION',
 'WIND_SPEED',
 'DRAFT_AFT',
 'DRAFT_FWD',
 'DISPLACEMENT',
 'COURSE_AT_SEA',
 'WAVE_HEIGHT',
 'SEA_DIRECTION',
 'CARGO_TOTAL_TEU',
 'AMBIENT_TEMP',
 'SW_TEMP',
 'MILES_BY_SPEED_LOG',
 'ETA_PORT_CODE',
 'ETA_DATE_TIME',
 'ETA_DATE_TIME_Offset',
 'ETA_PORT',
 'TIME_CHANGE',
 'TIME_SEA',
 'TEMP_MIN',
 'TEMP_MAX',
 'REQUESTED_SPEED',
 'REM_DIST_TO_PILOT',
 'REM_TIME_TO_PILOT',
 'TOTAL_UNPLND_STPGE_TECH',
 'TOTAL_UNPLND_STPGE_OPE_WX',
 'REEFERS_POSITIVE_PLUGGED',
 'REEFERS_NEGATIVE_PLUGGED',
 'ME_TOTAL_REVS_COUNTER',
 'PORT_CODE',
 'PORT',
 'AUX_BLOWERS_ON',
 'HOLD_VENTILATION_ON',
 'SINCE_DATE_TIME',
 'SINCE_DATE_TIME_Offset',
 'TIME_HRS_ANCHOR',
 'TIME_HRS_DRIFT',
 'REASON',
 'TYPE_OF_DELAY',
 'ETB_DATE_TIME',
 'ETB_DATE_TIME_Offset',
 'PILOT_DATE_TIME',
 'PILOT_DATE_TIME_Offset',
 'TIME_MANOEUVRING',
 'TUG_ARR',
 'TUG_SHIFT',
 'ETD_DATE_TIME',
 'ETD_DATE_TIME_Offset',
 'SHIFT_BERTH_HOURS',
 'CARGO_LOAD',
 'CARGO_DISCH',
 'TEU_FULL',
 'TEU_EMPTY',
 'BILGE_REMOVED',
 'GARBAGE_REMOVED',
 'GARBAGE_REMVL_REQSTD',
 'GARBAGE_REMVL_CMPLSRY',
 'FW_SUPPLY',
 'CY_CREW_SIGNED_ON',
 'CY_CREW_SIGNED_OFF',
 'CY_DOCTORS_VISIT',
 'CY_MAIL_RECEIVED_Ref_NO',
 'CY_LUB_OIL_SAMPLE_LANDED',
 'CY_CHECKD_FOR_STOWAWAYS',
 'CY_STOWAWAYS_ON_BOARD',
 'CY_DEP_GM_Mtr',
 'CY_REQUISITIONS_RECEIVED',
 'DISTANCE_TO_NEXT_PILOT',
 'TUG_SAILING_TRANSIT',
 'STEAMING_TIME_M_E_Rsdl_VLS',
 'STEAMING_TIME_M_E_Rsdl_HS',
 'STEAMING_TIME_M_E_Rsdl_ULS',
 'STEAMING_TIME_M_E_Dstlt_VLS',
 'STEAMING_TIME_M_E_Dstlt_ULS',
 'STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS',
 'STEAMING_TIME_M_E_HS',
 'STEAMING_TIME_M_E_LS',
 'STEAMING_TIME_M_E_MDO',
 'STEAMING_TIME_M_E_MGO',
 'STEAMING_TIME_M_E_MGO_LS',
 'STEAMING_TIME_AUX_1',
 'STEAMING_TIME_AUX_2',
 'STEAMING_TIME_AUX_3',
 'STEAMING_TIME_AUX_4',
 'STEAMING_TIME_AUX_5',
 'STEAMING_TIME_SH_GEN',
 'STEAMING_TIME_TG',
 'POWER_KW',
 'STEAMING_LOAD_KW_AUX_1',
 'STEAMING_LOAD_KW_AUX_2',
 'STEAMING_LOAD_KW_AUX_3',
 'STEAMING_LOAD_KW_AUX_4',
 'STEAMING_LOAD_KW_AUX_5',
 'STEAMING_LOAD_KW_SH_GEN',
 'STEAMING_LOAD_KW_TG',
 'FUEL_M_E_Rsdl_VLS',
 'FUEL_M_E_Rsdl_HS',
 'FUEL_M_E_Rsdl_ULS',
 'FUEL_M_E_Dstlt_VLS',
 'FUEL_M_E_Dstlt_ULS',
 'FUEL_M_E_Tnktnr_Dstlt_VLS',
 'FUEL_M_E_HS',
 'FUEL_M_E_LS',
 'FUEL_M_E_MDO',
 'FUEL_M_E_MGO',
 'FUEL_M_E_MGO_LS',
 'FUEL_Aux_Rsdl_VLS',
 'FUEL_Aux_Rsdl_HS',
 'FUEL_Aux_Rsdl_ULS',
 'FUEL_Aux_Dstlt_VLS',
 'FUEL_Aux_Dstlt_ULS',
 'FUEL_Aux_Tnktnr_Dstlt_VLS',
 'FUEL_AUX_HS',
 'FUEL_AUX_LS',
 'FUEL_AUX_MDO',
 'FUEL_AUX_MGO',
 'FUEL_AUX_MGO_LS',
 'FUEL_Boiler_Rsdl_VLS',
 'FUEL_Boiler_Rsdl_HS',
 'FUEL_Boiler_Rsdl_ULS',
 'FUEL_Boiler_Dstlt_VLS',
 'FUEL_Boiler_Dstlt_ULS',
 'FUEL_Boiler_Tnktnr_Dstlt_VLS',
 'FUEL_BOILER_HS',
 'FUEL_BOILER_LS',
 'FUEL_BOILER_MDO',
 'FUEL_BOILER_MGO',
 'FUEL_BOILER_MGO_LS',
 'DECK_LAST_CHANGE_USER',
 'ENGINE_LAST_CHANGE_USER',
 'DECK_PART_IS_COMPLETE',
 'ENGINE_PART_IS_COMPLETE',
 'SCAVENGE_PRESSURE',
 'SECA_ENTRY_TIME',
 'SECA_ENTRY_LAT',
 'SECA_ENTRY_LONG',
 'SECA_EXIT_TIME',
 'SECA_EXIT_LAT',
 'SECA_EXIT_LONG',
 'ROB_FRESH_WATER',
 'MANVRNG_MILES_BY_GPS',
 'MANVRNG_MILES_BY_SPEED_LOG',
 'TANKTAINER_TRANSFD_QUANTITY',
 'PILOT_TAKEN',
 'DATE_TIME_START_TRANSIT',
 'DATE_TIME_START_TRANSIT_Offset',
 'DATE_TIME_END_TRANSIT',
 'DATE_TIME_END_TRANSIT_Offset',
 'BALLAST',
 'TANKTAINER_NUMBER',
 'STEAMING_KWHR_TOTAL',
 'CY_OTHERS',
 'ROB_FO_SLUDGE',
 'ROB_LO_SLUDGE',
 'ROB_BILGE',
 'SLUDGE_REMOVED_FO',
 'SLUDGE_REMOVED_LO',
 'SEA_STATE',
 'CY_LUB_ADDED_TO_SYSTEM_MECC',
 'CY_LUB_ADDED_TO_SYSTEM_AECC',
 'CY_LUB_ADDED_TO_THRUSTERS',
 'CY_ME_LO_PURIFIER_IN_USE',
 'CY_BALLAST',
 'CY_BENDING_MOMENT',
 'CY_SHEARING_FORCE',
 'CY_TORTION_MOMENT',
 'CY_SUPDT_AUDITOR_SIGNED_ON',
 'CY_SUPDT_AUDITOR_SIGNED_OFF',
 'CY_CASH_RECEIVED',
 'CY_LUB_OIL_RECEIVED_MECYL',
 'CY_LUB_OIL_RECEIVED_MECC',
 'CY_LUB_OIL_RECEIVED_AECC',
 'CY_M_E_UNDER_PISTON_TEMP',
 'CY_MAIL_RECEIVED',
 'WIND_DIRECTION_PORT_STBD',
 'SEA_DIRECTION_PORT_STBD',
 'TIME_PILOT_ONBOARD',
 'GRADES_ROB',
 'SO2_CO2_RATIO',
 'Bunker_Order',
 'Remarks',
 'Fuel_Type',
 'Carbon_Factor',
 'Sulphur_Content_PC',
 'Quantity',
 'Port_Delivery',
 'Product_Quality',
 'Tanktainer_Number_1',
 'Supplier',
 'Delivery',
 'Vol_Lt',
 'Den',
 'Vis',
 'ROB_Dstlt_ULS',
 'ROB_Dstlt_VLS',
 'ROB_Rsdl_MDO',
 'ROB_Tnktnr_Dstlt_VLS',
 'ROB_Rsdl_VLS',
 'ROB_Rsdl_HS',
 'ROB_Rsdl_ULS',
 'ROB_Fuel_HSFO',
 'ROB_Fuel_LSFO',
 'ROB_Fuel_MDO',
 'ROB_Fuel_MGO',
 'ROB_Fuel_MGO_LS',
 'ROB_Fuel_Tanktainer_MGO',
 'ECA_MILES',
 'ECA_TIME',
 'EGCS_DRY_WASTE_REMOVED',
 'EGCS_RUNNING_TIME',
 'EGCS_WET_SLURRY_REMOVED',
 'EGCS_OPEN_LOOP_RUNNING_TIME',
 'EGCS_CLOSED_LOOP_RUNNING_TIME',
 'FUEL_M_E_LNG',
 'FUEL_Aux_LNG',
 'FUEL_Boiler_LNG',
 'ROB_Rsdl_LNG',
 'Max_Residual_HS_capacity',
 'Max_Lng_capacity',
 'Min_Lng_request',
 'Tanktainer_min_request',
 'Comments',
 'Template_version',
 'Pilot_date/time',
 'PIER_date/time',
 'Hold_ventilation_off',
 'Rob_tot_Sludge',
 'Reefer_power_consumption',
 'Tanktainer_distillates_transfd',
 'Hold_Ventilation_On/Off',
 'Tot_sludge_removed',
 'Garbage_cat_a_-_plastic_removed',
 'Garbage_cat_b_-_organic_removed',
 'Garbage_cat_c_-_domestic_removed',
 'Garbage_cat_e_-_ashes_removed',
 'Rob_garbage_cat_a_-_plastic',
 'Rob_garbage_cat_b_-_organic',
 'Rob_garbage_cat_c_-_domestic',
 'Rob_garbage_cat_e_-_ashes',
 'Kwhr_total',
 'Sludge_rob',
 'Sludge_min_discharge_request',
 'Rob_actual_sludge',
 'Qty_sludge_disposed',
 nan]

In [51]:
weekcol = charter.columns.tolist()
weekcol

['GID',
 'VSL',
 'IMO_No',
 'VOY',
 'Corrected_Date',
 'REPORT_DATE_TIME',
 'REPORT_DATE_TIME_Offset',
 'Report_Type',
 'Status',
 'LAT',
 'LONG',
 'M_E_FOC',
 'CARGO_TOTAL',
 'Has_Cargo',
 'STEAMING_TIME',
 'Total_M_E_Hours_Fuel_Only',
 'MILES_BY_GPS',
 'OIL_CYL',
 'SPEED_BY_LOG',
 'SPEED_BY_GPS',
 'RPM',
 'SLIP',
 'WIND_DIRECTION',
 'WIND_SPEED',
 'DRAFT_AFT',
 'DRAFT_FWD',
 'DISPLACEMENT',
 'COURSE_AT_SEA',
 'WAVE_HEIGHT',
 'SEA_DIRECTION',
 'CARGO_TOTAL_TEU',
 'AMBIENT_TEMP',
 'SW_TEMP',
 'MILES_BY_SPEED_LOG',
 'ETA_PORT_CODE',
 'ETA_DATE_TIME',
 'ETA_DATE_TIME_Offset',
 'ETA_PORT',
 'TIME_CHANGE',
 'TIME_SEA',
 'TEMP_MIN',
 'TEMP_MAX',
 'REQUESTED_SPEED',
 'REM_DIST_TO_PILOT',
 'REM_TIME_TO_PILOT',
 'TOTAL_UNPLND_STPGE_TECH',
 'TOTAL_UNPLND_STPGE_OPE_WX',
 'REEFERS_POSITIVE_PLUGGED',
 'REEFERS_NEGATIVE_PLUGGED',
 'ME_TOTAL_REVS_COUNTER',
 'PORT_CODE',
 'PORT',
 'AUX_BLOWERS_ON',
 'HOLD_VENTILATION_ON',
 'TIME_HRS_ANCHOR',
 'TIME_HRS_DRIFT',
 'REASON',
 'TYPE_OF_DELAY',
 'ETB_DATE_TIME',
 'ETB_DATE_TIME_Offset',
 'PILOT_DATE_TIME',
 'PILOT_DATE_TIME_Offset',
 'TIME_MANOEUVRING',
 'TUG_ARR',
 'TUG_SHIFT',
 'ETD_DATE_TIME',
 'ETD_DATE_TIME_Offset',
 'SHIFT_BERTH_HOURS',
 'CARGO_LOAD',
 'CARGO_DISCH',
 'TEU_FULL',
 'TEU_EMPTY',
 'BILGE_REMOVED',
 'GARBAGE_REMOVED',
 'GARBAGE_REMVL_REQSTD',
 'GARBAGE_REMVL_CMPLSRY',
 'FW_SUPPLY',
 'CY_CREW_SIGNED_ON',
 'CY_CREW_SIGNED_OFF',
 'CY_DOCTORS_VISIT',
 'CY_MAIL_RECEIVED_Ref_NO',
 'CY_LUB_OIL_SAMPLE_LANDED',
 'CY_CHECKD_FOR_STOWAWAYS',
 'CY_STOWAWAYS_ON_BOARD',
 'CY_DEP_GM_Mtr',
 'CY_REQUISITIONS_RECEIVED',
 'DISTANCE_TO_NEXT_PILOT',
 'TUG_SAILING_TRANSIT',
 'STEAMING_TIME_M_E_Rsdl_VLS',
 'STEAMING_TIME_M_E_Rsdl_HS',
 'STEAMING_TIME_M_E_Rsdl_ULS',
 'STEAMING_TIME_M_E_Dstlt_VLS',
 'STEAMING_TIME_M_E_Dstlt_ULS',
 'STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS',
 'STEAMING_TIME_M_E_MDO',
 'STEAMING_TIME_AUX_1',
 'STEAMING_TIME_AUX_2',
 'STEAMING_TIME_AUX_3',
 'STEAMING_TIME_AUX_4',
 'STEAMING_TIME_AUX_5',
 'STEAMING_TIME_SH_GEN',
 'STEAMING_TIME_TG',
 'FUEL_M_E_Rsdl_VLS',
 'FUEL_M_E_Rsdl_HS',
 'FUEL_M_E_Rsdl_ULS',
 'FUEL_M_E_Dstlt_VLS',
 'FUEL_M_E_Dstlt_ULS',
 'FUEL_M_E_MDO',
 'FUEL_M_E_LNG',
 'FUEL_M_E_Tnktnr_Dstlt_VLS',
 'FUEL_Aux_Rsdl_VLS',
 'FUEL_Aux_Rsdl_HS',
 'FUEL_Aux_Rsdl_ULS',
 'FUEL_Aux_Dstlt_VLS',
 'FUEL_Aux_Dstlt_ULS',
 'FUEL_Aux_Tnktnr_Dstlt_VLS',
 'FUEL_Aux_LNG',
 'FUEL_Aux_MDO',
 'FUEL_Boiler_Rsdl_VLS',
 'FUEL_Boiler_Rsdl_HS',
 'FUEL_Boiler_Rsdl_ULS',
 'FUEL_Boiler_Dstlt_VLS',
 'FUEL_Boiler_Dstlt_ULS',
 'FUEL_Boiler_Tnktnr_Dstlt_VLS',
 'FUEL_Boiler_LNG',
 'FUEL_Boiler_MDO',
 'POWER_KW',
 'STEAMING_LOAD_KW_AUX_1',
 'STEAMING_LOAD_KW_AUX_2',
 'STEAMING_LOAD_KW_AUX_3',
 'STEAMING_LOAD_KW_AUX_4',
 'STEAMING_LOAD_KW_AUX_5',
 'STEAMING_LOAD_KW_SH_GEN',
 'STEAMING_LOAD_KW_TG',
 'DECK_LAST_CHANGE_USER',
 'ENGINE_LAST_CHANGE_USER',
 'DECK_PART_IS_COMPLETE',
 'ENGINE_PART_IS_COMPLETE',
 'SCAVENGE_PRESSURE',
 'SECA_ENTRY_TIME',
 'SECA_ENTRY_LAT',
 'SECA_ENTRY_LONG',
 'SECA_EXIT_TIME',
 'SECA_EXIT_LAT',
 'SECA_EXIT_LONG',
 'ROB_FRESH_WATER',
 'MANVRNG_MILES_BY_GPS',
 'MANVRNG_MILES_BY_SPEED_LOG',
 'TANKTAINER_TRANSFD_QUANTITY',
 'PILOT_TAKEN',
 'DATE_TIME_START_TRANSIT',
 'DATE_TIME_START_TRANSIT_Offset',
 'DATE_TIME_END_TRANSIT',
 'DATE_TIME_END_TRANSIT_Offset',
 'BALLAST',
 'TANKTAINER_NUMBER',
 'STEAMING_KWHR_TOTAL',
 'CY_OTHERS',
 'ROB_FO_SLUDGE',
 'ROB_LO_SLUDGE',
 'ROB_BILGE',
 'SLUDGE_REMOVED_FO',
 'SLUDGE_REMOVED_LO',
 'SEA_STATE',
 'CY_LUB_ADDED_TO_SYSTEM_MECC',
 'CY_LUB_ADDED_TO_SYSTEM_AECC',
 'CY_LUB_ADDED_TO_THRUSTERS',
 'CY_ME_LO_PURIFIER_IN_USE',
 'CY_BALLAST',
 'CY_BENDING_MOMENT',
 'CY_SHEARING_FORCE',
 'CY_TORTION_MOMENT',
 'CY_SUPDT_AUDITOR_SIGNED_ON',
 'CY_SUPDT_AUDITOR_SIGNED_OFF',
 'CY_CASH_RECEIVED',
 'CY_LUB_OIL_RECEIVED_MECYL',
 'CY_LUB_OIL_RECEIVED_MECC',
 'CY_LUB_OIL_RECEIVED_AECC',
 'CY_M_E_UNDER_PISTON_TEMP',
 'CY_MAIL_RECEIVED',
 'WIND_DIRECTION_PORT_STBD',
 'SEA_DIRECTION_PORT_STBD',
 'TIME_PILOT_ONBOARD',
 'GRADES_ROB',
 'SO2_CO2_RATIO',
 'Bunker_Order',
 'Remarks',
 'Fuel_Type',
 'Carbon_Factor',
 'Sulphur_Content_PC',
 'Quantity',
 'Port_Delivery',
 'Product_Quality',
 'Tanktainer_Number_1',
 'Supplier',
 'Delivery',
 'Vol_Lt',
 'Den',
 'Vis',
 'ROB_Dstlt_ULS',
 'ROB_Dstlt_VLS',
 'ROB_Rsdl_MDO',
 'ROB_Tnktnr_Dstlt_VLS',
 'ROB_Rsdl_VLS',
 'ROB_Rsdl_HS',
 'ROB_Rsdl_ULS',
 'ROB_Rsdl_LNG',
 'ECA_MILES',
 'ECA_TIME',
 'EGCS_DRY_WASTE_REMOVED',
 'EGCS_RUNNING_TIME',
 'EGCS_WET_SLURRY_REMOVED',
 'EGCS_OPEN_LOOP_RUNNING_TIME',
 'EGCS_CLOSED_LOOP_RUNNING_TIME',
 'STEAMING_TIME_M_E_HS',
 'STEAMING_TIME_M_E_LS',
 'STEAMING_TIME_M_E_MGO',
 'STEAMING_TIME_M_E_MGO_LS',
 'FUEL_M_E_HS',
 'FUEL_M_E_LS',
 'FUEL_M_E_MGO',
 'FUEL_M_E_MGO_LS',
 'FUEL_Aux_HS',
 'FUEL_Aux_LS',
 'FUEL_Aux_MGO',
 'FUEL_Aux_MGO_LS',
 'FUEL_Boiler_HS',
 'FUEL_Boiler_LS',
 'FUEL_Boiler_MGO',
 'FUEL_Boiler_MGO_LS',
 'ROB_FUEL_HSFO',
 'ROB_FUEL_LSFO',
 'ROB_FUEL_MDO',
 'ROB_FUEL_MGO',
 'ROB_FUEL_MGO_LS',
 'ROB_FUEL_Tanktainer_MGO',
 'SINCE_DATE_TIME',
 'SINCE_DATE_TIME_Offset']

In [53]:
charter.rename(columns = {'LONG':'LONG_','FUEL_Aux_MDO':'FUEL_AUX_MDO','FUEL_Boiler_MDO':'FUEL_BOILER_MDO','FUEL_Aux_HS':'FUEL_AUX_HS','FUEL_Aux_LS':'FUEL_AUX_LS','FUEL_Aux_MGO':'FUEL_AUX_MGO','FUEL_Aux_MGO_LS':'FUEL_AUX_MGO_LS','FUEL_Boiler_HS':'FUEL_BOILER_HS','FUEL_Boiler_LS':'FUEL_BOILER_LS','FUEL_Boiler_MGO':'FUEL_BOILER_MGO','FUEL_Boiler_MGO_LS':'FUEL_BOILER_MGO_LS','ROB_FUEL_HSFO':'ROB_Fuel_HSFO','ROB_FUEL_LSFO':'ROB_Fuel_LSFO','ROB_FUEL_MDO':'ROB_Fuel_MDO','ROB_FUEL_MGO':'ROB_Fuel_MGO','ROB_FUEL_MGO_LS':'ROB_Fuel_MGO_LS','ROB_FUEL_Tanktainer_MGO':'ROB_Fuel_Tanktainer_MGO'}, inplace = True)

In [55]:
weekcol = charter.columns.tolist()
weekcol

['GID',
 'VSL',
 'IMO_No',
 'VOY',
 'Corrected_Date',
 'REPORT_DATE_TIME',
 'REPORT_DATE_TIME_Offset',
 'Report_Type',
 'Status',
 'LAT',
 'LONG_',
 'M_E_FOC',
 'CARGO_TOTAL',
 'Has_Cargo',
 'STEAMING_TIME',
 'Total_M_E_Hours_Fuel_Only',
 'MILES_BY_GPS',
 'OIL_CYL',
 'SPEED_BY_LOG',
 'SPEED_BY_GPS',
 'RPM',
 'SLIP',
 'WIND_DIRECTION',
 'WIND_SPEED',
 'DRAFT_AFT',
 'DRAFT_FWD',
 'DISPLACEMENT',
 'COURSE_AT_SEA',
 'WAVE_HEIGHT',
 'SEA_DIRECTION',
 'CARGO_TOTAL_TEU',
 'AMBIENT_TEMP',
 'SW_TEMP',
 'MILES_BY_SPEED_LOG',
 'ETA_PORT_CODE',
 'ETA_DATE_TIME',
 'ETA_DATE_TIME_Offset',
 'ETA_PORT',
 'TIME_CHANGE',
 'TIME_SEA',
 'TEMP_MIN',
 'TEMP_MAX',
 'REQUESTED_SPEED',
 'REM_DIST_TO_PILOT',
 'REM_TIME_TO_PILOT',
 'TOTAL_UNPLND_STPGE_TECH',
 'TOTAL_UNPLND_STPGE_OPE_WX',
 'REEFERS_POSITIVE_PLUGGED',
 'REEFERS_NEGATIVE_PLUGGED',
 'ME_TOTAL_REVS_COUNTER',
 'PORT_CODE',
 'PORT',
 'AUX_BLOWERS_ON',
 'HOLD_VENTILATION_ON',
 'TIME_HRS_ANCHOR',
 'TIME_HRS_DRIFT',
 'REASON',
 'TYPE_OF_DELAY',
 'ETB_DATE_TIME',
 'ETB_DATE_TIME_Offset',
 'PILOT_DATE_TIME',
 'PILOT_DATE_TIME_Offset',
 'TIME_MANOEUVRING',
 'TUG_ARR',
 'TUG_SHIFT',
 'ETD_DATE_TIME',
 'ETD_DATE_TIME_Offset',
 'SHIFT_BERTH_HOURS',
 'CARGO_LOAD',
 'CARGO_DISCH',
 'TEU_FULL',
 'TEU_EMPTY',
 'BILGE_REMOVED',
 'GARBAGE_REMOVED',
 'GARBAGE_REMVL_REQSTD',
 'GARBAGE_REMVL_CMPLSRY',
 'FW_SUPPLY',
 'CY_CREW_SIGNED_ON',
 'CY_CREW_SIGNED_OFF',
 'CY_DOCTORS_VISIT',
 'CY_MAIL_RECEIVED_Ref_NO',
 'CY_LUB_OIL_SAMPLE_LANDED',
 'CY_CHECKD_FOR_STOWAWAYS',
 'CY_STOWAWAYS_ON_BOARD',
 'CY_DEP_GM_Mtr',
 'CY_REQUISITIONS_RECEIVED',
 'DISTANCE_TO_NEXT_PILOT',
 'TUG_SAILING_TRANSIT',
 'STEAMING_TIME_M_E_Rsdl_VLS',
 'STEAMING_TIME_M_E_Rsdl_HS',
 'STEAMING_TIME_M_E_Rsdl_ULS',
 'STEAMING_TIME_M_E_Dstlt_VLS',
 'STEAMING_TIME_M_E_Dstlt_ULS',
 'STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS',
 'STEAMING_TIME_M_E_MDO',
 'STEAMING_TIME_AUX_1',
 'STEAMING_TIME_AUX_2',
 'STEAMING_TIME_AUX_3',
 'STEAMING_TIME_AUX_4',
 'STEAMING_TIME_AUX_5',
 'STEAMING_TIME_SH_GEN',
 'STEAMING_TIME_TG',
 'FUEL_M_E_Rsdl_VLS',
 'FUEL_M_E_Rsdl_HS',
 'FUEL_M_E_Rsdl_ULS',
 'FUEL_M_E_Dstlt_VLS',
 'FUEL_M_E_Dstlt_ULS',
 'FUEL_M_E_MDO',
 'FUEL_M_E_LNG',
 'FUEL_M_E_Tnktnr_Dstlt_VLS',
 'FUEL_Aux_Rsdl_VLS',
 'FUEL_Aux_Rsdl_HS',
 'FUEL_Aux_Rsdl_ULS',
 'FUEL_Aux_Dstlt_VLS',
 'FUEL_Aux_Dstlt_ULS',
 'FUEL_Aux_Tnktnr_Dstlt_VLS',
 'FUEL_Aux_LNG',
 'FUEL_AUX_MDO',
 'FUEL_Boiler_Rsdl_VLS',
 'FUEL_Boiler_Rsdl_HS',
 'FUEL_Boiler_Rsdl_ULS',
 'FUEL_Boiler_Dstlt_VLS',
 'FUEL_Boiler_Dstlt_ULS',
 'FUEL_Boiler_Tnktnr_Dstlt_VLS',
 'FUEL_Boiler_LNG',
 'FUEL_BOILER_MDO',
 'POWER_KW',
 'STEAMING_LOAD_KW_AUX_1',
 'STEAMING_LOAD_KW_AUX_2',
 'STEAMING_LOAD_KW_AUX_3',
 'STEAMING_LOAD_KW_AUX_4',
 'STEAMING_LOAD_KW_AUX_5',
 'STEAMING_LOAD_KW_SH_GEN',
 'STEAMING_LOAD_KW_TG',
 'DECK_LAST_CHANGE_USER',
 'ENGINE_LAST_CHANGE_USER',
 'DECK_PART_IS_COMPLETE',
 'ENGINE_PART_IS_COMPLETE',
 'SCAVENGE_PRESSURE',
 'SECA_ENTRY_TIME',
 'SECA_ENTRY_LAT',
 'SECA_ENTRY_LONG',
 'SECA_EXIT_TIME',
 'SECA_EXIT_LAT',
 'SECA_EXIT_LONG',
 'ROB_FRESH_WATER',
 'MANVRNG_MILES_BY_GPS',
 'MANVRNG_MILES_BY_SPEED_LOG',
 'TANKTAINER_TRANSFD_QUANTITY',
 'PILOT_TAKEN',
 'DATE_TIME_START_TRANSIT',
 'DATE_TIME_START_TRANSIT_Offset',
 'DATE_TIME_END_TRANSIT',
 'DATE_TIME_END_TRANSIT_Offset',
 'BALLAST',
 'TANKTAINER_NUMBER',
 'STEAMING_KWHR_TOTAL',
 'CY_OTHERS',
 'ROB_FO_SLUDGE',
 'ROB_LO_SLUDGE',
 'ROB_BILGE',
 'SLUDGE_REMOVED_FO',
 'SLUDGE_REMOVED_LO',
 'SEA_STATE',
 'CY_LUB_ADDED_TO_SYSTEM_MECC',
 'CY_LUB_ADDED_TO_SYSTEM_AECC',
 'CY_LUB_ADDED_TO_THRUSTERS',
 'CY_ME_LO_PURIFIER_IN_USE',
 'CY_BALLAST',
 'CY_BENDING_MOMENT',
 'CY_SHEARING_FORCE',
 'CY_TORTION_MOMENT',
 'CY_SUPDT_AUDITOR_SIGNED_ON',
 'CY_SUPDT_AUDITOR_SIGNED_OFF',
 'CY_CASH_RECEIVED',
 'CY_LUB_OIL_RECEIVED_MECYL',
 'CY_LUB_OIL_RECEIVED_MECC',
 'CY_LUB_OIL_RECEIVED_AECC',
 'CY_M_E_UNDER_PISTON_TEMP',
 'CY_MAIL_RECEIVED',
 'WIND_DIRECTION_PORT_STBD',
 'SEA_DIRECTION_PORT_STBD',
 'TIME_PILOT_ONBOARD',
 'GRADES_ROB',
 'SO2_CO2_RATIO',
 'Bunker_Order',
 'Remarks',
 'Fuel_Type',
 'Carbon_Factor',
 'Sulphur_Content_PC',
 'Quantity',
 'Port_Delivery',
 'Product_Quality',
 'Tanktainer_Number_1',
 'Supplier',
 'Delivery',
 'Vol_Lt',
 'Den',
 'Vis',
 'ROB_Dstlt_ULS',
 'ROB_Dstlt_VLS',
 'ROB_Rsdl_MDO',
 'ROB_Tnktnr_Dstlt_VLS',
 'ROB_Rsdl_VLS',
 'ROB_Rsdl_HS',
 'ROB_Rsdl_ULS',
 'ROB_Rsdl_LNG',
 'ECA_MILES',
 'ECA_TIME',
 'EGCS_DRY_WASTE_REMOVED',
 'EGCS_RUNNING_TIME',
 'EGCS_WET_SLURRY_REMOVED',
 'EGCS_OPEN_LOOP_RUNNING_TIME',
 'EGCS_CLOSED_LOOP_RUNNING_TIME',
 'STEAMING_TIME_M_E_HS',
 'STEAMING_TIME_M_E_LS',
 'STEAMING_TIME_M_E_MGO',
 'STEAMING_TIME_M_E_MGO_LS',
 'FUEL_M_E_HS',
 'FUEL_M_E_LS',
 'FUEL_M_E_MGO',
 'FUEL_M_E_MGO_LS',
 'FUEL_AUX_HS',
 'FUEL_AUX_LS',
 'FUEL_AUX_MGO',
 'FUEL_AUX_MGO_LS',
 'FUEL_BOILER_HS',
 'FUEL_BOILER_LS',
 'FUEL_BOILER_MGO',
 'FUEL_BOILER_MGO_LS',
 'ROB_Fuel_HSFO',
 'ROB_Fuel_LSFO',
 'ROB_Fuel_MDO',
 'ROB_Fuel_MGO',
 'ROB_Fuel_MGO_LS',
 'ROB_Fuel_Tanktainer_MGO',
 'SINCE_DATE_TIME',
 'SINCE_DATE_TIME_Offset']

In [57]:
temp3 = []
for element in weekcol:
    if element not in col_lst:
        temp3.append(element)

temp3

[]

In [59]:
temp4 = []
for element in col_lst:
    if element not in weekcol:
        temp4.append(element)

temp4

['Max_Residual_HS_capacity',
 'Max_Lng_capacity',
 'Min_Lng_request',
 'Tanktainer_min_request',
 'Comments',
 'Template_version',
 'Pilot_date/time',
 'PIER_date/time',
 'Hold_ventilation_off',
 'Rob_tot_Sludge',
 'Reefer_power_consumption',
 'Tanktainer_distillates_transfd',
 'Hold_Ventilation_On/Off',
 'Tot_sludge_removed',
 'Garbage_cat_a_-_plastic_removed',
 'Garbage_cat_b_-_organic_removed',
 'Garbage_cat_c_-_domestic_removed',
 'Garbage_cat_e_-_ashes_removed',
 'Rob_garbage_cat_a_-_plastic',
 'Rob_garbage_cat_b_-_organic',
 'Rob_garbage_cat_c_-_domestic',
 'Rob_garbage_cat_e_-_ashes',
 'Kwhr_total',
 'Sludge_rob',
 'Sludge_min_discharge_request',
 'Rob_actual_sludge',
 'Qty_sludge_disposed',
 nan]

In [61]:
charter[temp4] = np.nan
charter

,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,LAT,...,Rob_garbage_cat_a_-_plastic,Rob_garbage_cat_b_-_organic,Rob_garbage_cat_c_-_domestic,Rob_garbage_cat_e_-_ashes,Kwhr_total,Sludge_rob,Sludge_min_discharge_request,Rob_actual_sludge,Qty_sludge_disposed,NaN
0,202b3fcb-ddcb-41ef-8365-b3d28ddcb8ca,MSC AURELIA,76021200.0,407,2024-08-01,2024-08-01 06:12:00,UTC +02:00,EOSP,AT SEA,4328N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,26e61ea7-3216-4bb7-a0ce-e5b69d34cf60,MSC AURELIA,76021200.0,407,2024-08-01,2024-08-01 06:42:00,UTC +02:00,BRTH,DRIFTING,4328N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,571a8985-617b-4f85-9eab-ef133661da63,MSC AURELIA,76021200.0,407,2024-08-01,2024-08-01 12:00:00,UTC +02:00,PORT,IN PORT,4328N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,a9d7bd6d-6015-4dd0-8e9e-f40d2c5285eb,MSC AURELIA,76021200.0,407,2024-08-02,2024-08-01 19:30:00,UTC +02:00,SAIL,IN PORT,4328N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,50ad5a0d-838a-4c10-9d7d-94d8c1bde30e,MSC AURELIA,76021200.0,407,2024-08-02,2024-08-01 19:48:00,UTC +02:00,COSP,DRIFTING,4328N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47591,3779916a-357d-47ca-85a0-0a957a87dc39,MSC COTONOU VIII,99836710.0,UL430W,2024-08-28,2024-08-28 12:00:00,UTC -01:00,NOON,AT SEA,1624S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47592,a7e76ef4-1b7d-45d0-a629-4b0afb94199a,MSC COTONOU VIII,99836710.0,UL430W,2024-08-29,2024-08-29 12:00:00,UTC +00:00,NOON,AT SEA,2034S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47593,3de94823-cffe-469d-b306-02b47aea9d1f,MSC COTONOU VIII,99836710.0,UL430W,2024-08-30,2024-08-30 12:00:00,UTC +00:00,NOON,AT SEA,2459S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47594,fc8528e4-6372-4790-8fbd-3465bb213757,MSC COTONOU VIII,99836710.0,UL430W,2024-08-31,2024-08-31 12:00:00,UTC +00:00,NOON,AT SEA,2932S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47595,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
columns_to_fill_zero = ['FUEL_M_E_LNG', 'FUEL_Aux_LNG', 'FUEL_Boiler_LNG', 'ROB_Rsdl_LNG']

charter[columns_to_fill_zero] = charter[columns_to_fill_zero].fillna(0)
charter

,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,LAT,...,Rob_garbage_cat_a_-_plastic,Rob_garbage_cat_b_-_organic,Rob_garbage_cat_c_-_domestic,Rob_garbage_cat_e_-_ashes,Kwhr_total,Sludge_rob,Sludge_min_discharge_request,Rob_actual_sludge,Qty_sludge_disposed,NaN
0,202b3fcb-ddcb-41ef-8365-b3d28ddcb8ca,MSC AURELIA,76021200.0,407,2024-08-01,2024-08-01 06:12:00,UTC +02:00,EOSP,AT SEA,4328N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,26e61ea7-3216-4bb7-a0ce-e5b69d34cf60,MSC AURELIA,76021200.0,407,2024-08-01,2024-08-01 06:42:00,UTC +02:00,BRTH,DRIFTING,4328N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,571a8985-617b-4f85-9eab-ef133661da63,MSC AURELIA,76021200.0,407,2024-08-01,2024-08-01 12:00:00,UTC +02:00,PORT,IN PORT,4328N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,a9d7bd6d-6015-4dd0-8e9e-f40d2c5285eb,MSC AURELIA,76021200.0,407,2024-08-02,2024-08-01 19:30:00,UTC +02:00,SAIL,IN PORT,4328N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,50ad5a0d-838a-4c10-9d7d-94d8c1bde30e,MSC AURELIA,76021200.0,407,2024-08-02,2024-08-01 19:48:00,UTC +02:00,COSP,DRIFTING,4328N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47591,3779916a-357d-47ca-85a0-0a957a87dc39,MSC COTONOU VIII,99836710.0,UL430W,2024-08-28,2024-08-28 12:00:00,UTC -01:00,NOON,AT SEA,1624S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47592,a7e76ef4-1b7d-45d0-a629-4b0afb94199a,MSC COTONOU VIII,99836710.0,UL430W,2024-08-29,2024-08-29 12:00:00,UTC +00:00,NOON,AT SEA,2034S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47593,3de94823-cffe-469d-b306-02b47aea9d1f,MSC COTONOU VIII,99836710.0,UL430W,2024-08-30,2024-08-30 12:00:00,UTC +00:00,NOON,AT SEA,2459S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47594,fc8528e4-6372-4790-8fbd-3465bb213757,MSC COTONOU VIII,99836710.0,UL430W,2024-08-31,2024-08-31 12:00:00,UTC +00:00,NOON,AT SEA,2932S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47595,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
import re
def replace_special_characters(value):
    if isinstance(value, str):
        # Replace all the special characters with underscores
        value = re.sub(r'[,\;\!\/\\\;\'\"\@\#\$\%\^\(\)]', '_', value)
    return value

charter = charter.applymap(replace_special_characters)
charter

,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,LAT,...,Rob_garbage_cat_a_-_plastic,Rob_garbage_cat_b_-_organic,Rob_garbage_cat_c_-_domestic,Rob_garbage_cat_e_-_ashes,Kwhr_total,Sludge_rob,Sludge_min_discharge_request,Rob_actual_sludge,Qty_sludge_disposed,NaN
0,202b3fcb-ddcb-41ef-8365-b3d28ddcb8ca,MSC AURELIA,76021200.0,407,2024-08-01,2024-08-01 06:12:00,UTC +02:00,EOSP,AT SEA,4328N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,26e61ea7-3216-4bb7-a0ce-e5b69d34cf60,MSC AURELIA,76021200.0,407,2024-08-01,2024-08-01 06:42:00,UTC +02:00,BRTH,DRIFTING,4328N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,571a8985-617b-4f85-9eab-ef133661da63,MSC AURELIA,76021200.0,407,2024-08-01,2024-08-01 12:00:00,UTC +02:00,PORT,IN PORT,4328N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,a9d7bd6d-6015-4dd0-8e9e-f40d2c5285eb,MSC AURELIA,76021200.0,407,2024-08-02,2024-08-01 19:30:00,UTC +02:00,SAIL,IN PORT,4328N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,50ad5a0d-838a-4c10-9d7d-94d8c1bde30e,MSC AURELIA,76021200.0,407,2024-08-02,2024-08-01 19:48:00,UTC +02:00,COSP,DRIFTING,4328N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47591,3779916a-357d-47ca-85a0-0a957a87dc39,MSC COTONOU VIII,99836710.0,UL430W,2024-08-28,2024-08-28 12:00:00,UTC -01:00,NOON,AT SEA,1624S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47592,a7e76ef4-1b7d-45d0-a629-4b0afb94199a,MSC COTONOU VIII,99836710.0,UL430W,2024-08-29,2024-08-29 12:00:00,UTC +00:00,NOON,AT SEA,2034S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47593,3de94823-cffe-469d-b306-02b47aea9d1f,MSC COTONOU VIII,99836710.0,UL430W,2024-08-30,2024-08-30 12:00:00,UTC +00:00,NOON,AT SEA,2459S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47594,fc8528e4-6372-4790-8fbd-3465bb213757,MSC COTONOU VIII,99836710.0,UL430W,2024-08-31,2024-08-31 12:00:00,UTC +00:00,NOON,AT SEA,2932S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47595,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
charter[charter.apply(lambda x: x.str.contains(',|;').any(), axis=1)]

Empty DataFrame
Columns: [GID, VSL, IMO_No, VOY, Corrected_Date, REPORT_DATE_TIME, REPORT_DATE_TIME_Offset, Report_Type, Status, LAT, LONG_, M_E_FOC, CARGO_TOTAL, Has_Cargo, STEAMING_TIME, Total_M_E_Hours_Fuel_Only, MILES_BY_GPS, OIL_CYL, SPEED_BY_LOG, SPEED_BY_GPS, RPM, SLIP, WIND_DIRECTION, WIND_SPEED, DRAFT_AFT, DRAFT_FWD, DISPLACEMENT, COURSE_AT_SEA, WAVE_HEIGHT, SEA_DIRECTION, CARGO_TOTAL_TEU, AMBIENT_TEMP, SW_TEMP, MILES_BY_SPEED_LOG, ETA_PORT_CODE, ETA_DATE_TIME, ETA_DATE_TIME_Offset, ETA_PORT, TIME_CHANGE, TIME_SEA, TEMP_MIN, TEMP_MAX, REQUESTED_SPEED, REM_DIST_TO_PILOT, REM_TIME_TO_PILOT, TOTAL_UNPLND_STPGE_TECH, TOTAL_UNPLND_STPGE_OPE_WX, REEFERS_POSITIVE_PLUGGED, REEFERS_NEGATIVE_PLUGGED, ME_TOTAL_REVS_COUNTER, PORT_CODE, PORT, AUX_BLOWERS_ON, HOLD_VENTILATION_ON, TIME_HRS_ANCHOR, TIME_HRS_DRIFT, REASON, TYPE_OF_DELAY, ETB_DATE_TIME, ETB_DATE_TIME_Offset, PILOT_DATE_TIME, PILOT_DATE_TIME_Offset, TIME_MANOEUVRING, TUG_ARR, TUG_SHIFT, ETD_DATE_TIME, ETD_DATE_TIME_Offset, SHIFT_BERTH_HOURS, CARGO_LOAD, CARGO_DISCH, TEU_FULL, TEU_EMPTY, BILGE_REMOVED, GARBAGE_REMOVED, GARBAGE_REMVL_REQSTD, GARBAGE_REMVL_CMPLSRY, FW_SUPPLY, CY_CREW_SIGNED_ON, CY_CREW_SIGNED_OFF, CY_DOCTORS_VISIT, CY_MAIL_RECEIVED_Ref_NO, CY_LUB_OIL_SAMPLE_LANDED, CY_CHECKD_FOR_STOWAWAYS, CY_STOWAWAYS_ON_BOARD, CY_DEP_GM_Mtr, CY_REQUISITIONS_RECEIVED, DISTANCE_TO_NEXT_PILOT, TUG_SAILING_TRANSIT, STEAMING_TIME_M_E_Rsdl_VLS, STEAMING_TIME_M_E_Rsdl_HS, STEAMING_TIME_M_E_Rsdl_ULS, STEAMING_TIME_M_E_Dstlt_VLS, STEAMING_TIME_M_E_Dstlt_ULS, STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS, STEAMING_TIME_M_E_MDO, STEAMING_TIME_AUX_1, STEAMING_TIME_AUX_2, STEAMING_TIME_AUX_3, STEAMING_TIME_AUX_4, STEAMING_TIME_AUX_5, ...]
Index: []

[0 rows x 266 columns]

In [68]:
#corrected_date,report_date_time column format change to yyyy-mm-dd-hh:mm:ss
charter[['Corrected_Date','REPORT_DATE_TIME']]

      Corrected_Date    REPORT_DATE_TIME
0         2024-08-01 2024-08-01 06:12:00
1         2024-08-01 2024-08-01 06:42:00
2         2024-08-01 2024-08-01 12:00:00
3         2024-08-02 2024-08-01 19:30:00
4         2024-08-02 2024-08-01 19:48:00
...              ...                 ...
47591     2024-08-28 2024-08-28 12:00:00
47592     2024-08-29 2024-08-29 12:00:00
47593     2024-08-30 2024-08-30 12:00:00
47594     2024-08-31 2024-08-31 12:00:00
47595            NaT                 NaT

[47596 rows x 2 columns]

In [69]:
charter['Corrected_Date'] = pd.to_datetime(charter['Corrected_Date'], format='%y/%m/%d %H:%M:%S').dt.strftime('%Y-%m-%d %H:%M:%S')
charter['Corrected_Date']

0        2024-08-01 00:00:00
1        2024-08-01 00:00:00
2        2024-08-01 00:00:00
3        2024-08-02 00:00:00
4        2024-08-02 00:00:00
                ...
47591    2024-08-28 00:00:00
47592    2024-08-29 00:00:00
47593    2024-08-30 00:00:00
47594    2024-08-31 00:00:00
47595                    NaN
Name: Corrected_Date, Length: 47596, dtype: object

In [70]:
charter['REPORT_DATE_TIME'] = pd.to_datetime(charter['REPORT_DATE_TIME'], format='%y/%m/%d %H:%M:%S').dt.strftime('%Y-%m-%d %H:%M:%S')
charter['REPORT_DATE_TIME']

0        2024-08-01 06:12:00
1        2024-08-01 06:42:00
2        2024-08-01 12:00:00
3        2024-08-01 19:30:00
4        2024-08-01 19:48:00
                ...
47591    2024-08-28 12:00:00
47592    2024-08-29 12:00:00
47593    2024-08-30 12:00:00
47594    2024-08-31 12:00:00
47595                    NaN
Name: REPORT_DATE_TIME, Length: 47596, dtype: object

In [71]:
charter[['Corrected_Date','REPORT_DATE_TIME']]

            Corrected_Date     REPORT_DATE_TIME
0      2024-08-01 00:00:00  2024-08-01 06:12:00
1      2024-08-01 00:00:00  2024-08-01 06:42:00
2      2024-08-01 00:00:00  2024-08-01 12:00:00
3      2024-08-02 00:00:00  2024-08-01 19:30:00
4      2024-08-02 00:00:00  2024-08-01 19:48:00
...                    ...                  ...
47591  2024-08-28 00:00:00  2024-08-28 12:00:00
47592  2024-08-29 00:00:00  2024-08-29 12:00:00
47593  2024-08-30 00:00:00  2024-08-30 12:00:00
47594  2024-08-31 00:00:00  2024-08-31 12:00:00
47595                  NaN                  NaN

[47596 rows x 2 columns]

In [72]:
charterfinal = charter[['GID',
 'VSL',
 'IMO_No',
 'VOY',
 'Corrected_Date',
 'REPORT_DATE_TIME',
 'REPORT_DATE_TIME_Offset',
 'Report_Type',
 'Status',
 'LAT',
 'LONG_',
 'M_E_FOC',
 'CARGO_TOTAL',
 'Has_Cargo',
 'STEAMING_TIME',
 'Total_M_E_Hours_Fuel_Only',
 'MILES_BY_GPS',
 'OIL_CYL',
 'SPEED_BY_LOG',
 'SPEED_BY_GPS',
 'RPM',
 'SLIP',
 'WIND_DIRECTION',
 'WIND_SPEED',
 'DRAFT_AFT',
 'DRAFT_FWD',
 'DISPLACEMENT',
 'COURSE_AT_SEA',
 'WAVE_HEIGHT',
 'SEA_DIRECTION',
 'CARGO_TOTAL_TEU',
 'AMBIENT_TEMP',
 'SW_TEMP',
 'MILES_BY_SPEED_LOG',
 'ETA_PORT_CODE',
 'ETA_DATE_TIME',
 'ETA_DATE_TIME_Offset',
 'ETA_PORT',
 'TIME_CHANGE',
 'TIME_SEA',
 'TEMP_MIN',
 'TEMP_MAX',
 'REQUESTED_SPEED',
 'REM_DIST_TO_PILOT',
 'REM_TIME_TO_PILOT',
 'TOTAL_UNPLND_STPGE_TECH',
 'TOTAL_UNPLND_STPGE_OPE_WX',
 'REEFERS_POSITIVE_PLUGGED',
 'REEFERS_NEGATIVE_PLUGGED',
 'ME_TOTAL_REVS_COUNTER',
 'PORT_CODE',
 'PORT',
 'AUX_BLOWERS_ON',
 'HOLD_VENTILATION_ON',
 'SINCE_DATE_TIME',
 'SINCE_DATE_TIME_Offset',
 'TIME_HRS_ANCHOR',
 'TIME_HRS_DRIFT',
 'REASON',
 'TYPE_OF_DELAY',
 'ETB_DATE_TIME',
 'ETB_DATE_TIME_Offset',
 'PILOT_DATE_TIME',
 'PILOT_DATE_TIME_Offset',
 'TIME_MANOEUVRING',
 'TUG_ARR',
 'TUG_SHIFT',
 'ETD_DATE_TIME',
 'ETD_DATE_TIME_Offset',
 'SHIFT_BERTH_HOURS',
 'CARGO_LOAD',
 'CARGO_DISCH',
 'TEU_FULL',
 'TEU_EMPTY',
 'BILGE_REMOVED',
 'GARBAGE_REMOVED',
 'GARBAGE_REMVL_REQSTD',
 'GARBAGE_REMVL_CMPLSRY',
 'FW_SUPPLY',
 'CY_CREW_SIGNED_ON',
 'CY_CREW_SIGNED_OFF',
 'CY_DOCTORS_VISIT',
 'CY_MAIL_RECEIVED_Ref_NO',
 'CY_LUB_OIL_SAMPLE_LANDED',
 'CY_CHECKD_FOR_STOWAWAYS',
 'CY_STOWAWAYS_ON_BOARD',
 'CY_DEP_GM_Mtr',
 'CY_REQUISITIONS_RECEIVED',
 'DISTANCE_TO_NEXT_PILOT',
 'TUG_SAILING_TRANSIT',
 'STEAMING_TIME_M_E_Rsdl_VLS',
 'STEAMING_TIME_M_E_Rsdl_HS',
 'STEAMING_TIME_M_E_Rsdl_ULS',
 'STEAMING_TIME_M_E_Dstlt_VLS',
 'STEAMING_TIME_M_E_Dstlt_ULS',
 'STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS',
 'STEAMING_TIME_M_E_HS',
 'STEAMING_TIME_M_E_LS',
 'STEAMING_TIME_M_E_MDO',
 'STEAMING_TIME_M_E_MGO',
 'STEAMING_TIME_M_E_MGO_LS',
 'STEAMING_TIME_AUX_1',
 'STEAMING_TIME_AUX_2',
 'STEAMING_TIME_AUX_3',
 'STEAMING_TIME_AUX_4',
 'STEAMING_TIME_AUX_5',
 'STEAMING_TIME_SH_GEN',
 'STEAMING_TIME_TG',
 'POWER_KW',
 'STEAMING_LOAD_KW_AUX_1',
 'STEAMING_LOAD_KW_AUX_2',
 'STEAMING_LOAD_KW_AUX_3',
 'STEAMING_LOAD_KW_AUX_4',
 'STEAMING_LOAD_KW_AUX_5',
 'STEAMING_LOAD_KW_SH_GEN',
 'STEAMING_LOAD_KW_TG',
 'FUEL_M_E_Rsdl_VLS',
 'FUEL_M_E_Rsdl_HS',
 'FUEL_M_E_Rsdl_ULS',
 'FUEL_M_E_Dstlt_VLS',
 'FUEL_M_E_Dstlt_ULS',
 'FUEL_M_E_Tnktnr_Dstlt_VLS',
 'FUEL_M_E_HS',
 'FUEL_M_E_LS',
 'FUEL_M_E_MDO',
 'FUEL_M_E_MGO',
 'FUEL_M_E_MGO_LS',
 'FUEL_Aux_Rsdl_VLS',
 'FUEL_Aux_Rsdl_HS',
 'FUEL_Aux_Rsdl_ULS',
 'FUEL_Aux_Dstlt_VLS',
 'FUEL_Aux_Dstlt_ULS',
 'FUEL_Aux_Tnktnr_Dstlt_VLS',
 'FUEL_AUX_HS',
 'FUEL_AUX_LS',
 'FUEL_AUX_MDO',
 'FUEL_AUX_MGO',
 'FUEL_AUX_MGO_LS',
 'FUEL_Boiler_Rsdl_VLS',
 'FUEL_Boiler_Rsdl_HS',
 'FUEL_Boiler_Rsdl_ULS',
 'FUEL_Boiler_Dstlt_VLS',
 'FUEL_Boiler_Dstlt_ULS',
 'FUEL_Boiler_Tnktnr_Dstlt_VLS',
 'FUEL_BOILER_HS',
 'FUEL_BOILER_LS',
 'FUEL_BOILER_MDO',
 'FUEL_BOILER_MGO',
 'FUEL_BOILER_MGO_LS',
 'DECK_LAST_CHANGE_USER',
 'ENGINE_LAST_CHANGE_USER',
 'DECK_PART_IS_COMPLETE',
 'ENGINE_PART_IS_COMPLETE',
 'SCAVENGE_PRESSURE',
 'SECA_ENTRY_TIME',
 'SECA_ENTRY_LAT',
 'SECA_ENTRY_LONG',
 'SECA_EXIT_TIME',
 'SECA_EXIT_LAT',
 'SECA_EXIT_LONG',
 'ROB_FRESH_WATER',
 'MANVRNG_MILES_BY_GPS',
 'MANVRNG_MILES_BY_SPEED_LOG',
 'TANKTAINER_TRANSFD_QUANTITY',
 'PILOT_TAKEN',
 'DATE_TIME_START_TRANSIT',
 'DATE_TIME_START_TRANSIT_Offset',
 'DATE_TIME_END_TRANSIT',
 'DATE_TIME_END_TRANSIT_Offset',
 'BALLAST',
 'TANKTAINER_NUMBER',
 'STEAMING_KWHR_TOTAL',
 'CY_OTHERS',
 'ROB_FO_SLUDGE',
 'ROB_LO_SLUDGE',
 'ROB_BILGE',
 'SLUDGE_REMOVED_FO',
 'SLUDGE_REMOVED_LO',
 'SEA_STATE',
 'CY_LUB_ADDED_TO_SYSTEM_MECC',
 'CY_LUB_ADDED_TO_SYSTEM_AECC',
 'CY_LUB_ADDED_TO_THRUSTERS',
 'CY_ME_LO_PURIFIER_IN_USE',
 'CY_BALLAST',
 'CY_BENDING_MOMENT',
 'CY_SHEARING_FORCE',
 'CY_TORTION_MOMENT',
 'CY_SUPDT_AUDITOR_SIGNED_ON',
 'CY_SUPDT_AUDITOR_SIGNED_OFF',
 'CY_CASH_RECEIVED',
 'CY_LUB_OIL_RECEIVED_MECYL',
 'CY_LUB_OIL_RECEIVED_MECC',
 'CY_LUB_OIL_RECEIVED_AECC',
 'CY_M_E_UNDER_PISTON_TEMP',
 'CY_MAIL_RECEIVED',
 'WIND_DIRECTION_PORT_STBD',
 'SEA_DIRECTION_PORT_STBD',
 'TIME_PILOT_ONBOARD',
 'GRADES_ROB',
 'SO2_CO2_RATIO',
 'Bunker_Order',
 'Remarks',
 'Fuel_Type',
 'Carbon_Factor',
 'Sulphur_Content_PC',
 'Quantity',
 'Port_Delivery',
 'Product_Quality',
 'Tanktainer_Number_1',
 'Supplier',
 'Delivery',
 'Vol_Lt',
 'Den',
 'Vis',
 'ROB_Dstlt_ULS',
 'ROB_Dstlt_VLS',
 'ROB_Rsdl_MDO',
 'ROB_Tnktnr_Dstlt_VLS',
 'ROB_Rsdl_VLS',
 'ROB_Rsdl_HS',
 'ROB_Rsdl_ULS',
 'ROB_Fuel_HSFO',
 'ROB_Fuel_LSFO',
 'ROB_Fuel_MDO',
 'ROB_Fuel_MGO',
 'ROB_Fuel_MGO_LS',
 'ROB_Fuel_Tanktainer_MGO',
 'ECA_MILES',
 'ECA_TIME',
 'EGCS_DRY_WASTE_REMOVED',
 'EGCS_RUNNING_TIME',
 'EGCS_WET_SLURRY_REMOVED',
 'EGCS_OPEN_LOOP_RUNNING_TIME',
 'EGCS_CLOSED_LOOP_RUNNING_TIME',
 'FUEL_M_E_LNG','FUEL_Aux_LNG','FUEL_Boiler_LNG','ROB_Rsdl_LNG']]
charterfinal

,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,LAT,...,ECA_TIME,EGCS_DRY_WASTE_REMOVED,EGCS_RUNNING_TIME,EGCS_WET_SLURRY_REMOVED,EGCS_OPEN_LOOP_RUNNING_TIME,EGCS_CLOSED_LOOP_RUNNING_TIME,FUEL_M_E_LNG,FUEL_Aux_LNG,FUEL_Boiler_LNG,ROB_Rsdl_LNG
0,202b3fcb-ddcb-41ef-8365-b3d28ddcb8ca,MSC AURELIA,76021200.0,407,2024-08-01 00:00:00,2024-08-01 06:12:00,UTC +02:00,EOSP,AT SEA,4328N,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
1,26e61ea7-3216-4bb7-a0ce-e5b69d34cf60,MSC AURELIA,76021200.0,407,2024-08-01 00:00:00,2024-08-01 06:42:00,UTC +02:00,BRTH,DRIFTING,4328N,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
2,571a8985-617b-4f85-9eab-ef133661da63,MSC AURELIA,76021200.0,407,2024-08-01 00:00:00,2024-08-01 12:00:00,UTC +02:00,PORT,IN PORT,4328N,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
3,a9d7bd6d-6015-4dd0-8e9e-f40d2c5285eb,MSC AURELIA,76021200.0,407,2024-08-02 00:00:00,2024-08-01 19:30:00,UTC +02:00,SAIL,IN PORT,4328N,...,NaN,0.0,NaN,0.0,NaN,NaN,0.0,0.0,0.0,0.0
4,50ad5a0d-838a-4c10-9d7d-94d8c1bde30e,MSC AURELIA,76021200.0,407,2024-08-02 00:00:00,2024-08-01 19:48:00,UTC +02:00,COSP,DRIFTING,4328N,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47591,3779916a-357d-47ca-85a0-0a957a87dc39,MSC COTONOU VIII,99836710.0,UL430W,2024-08-28 00:00:00,2024-08-28 12:00:00,UTC -01:00,NOON,AT SEA,1624S,...,0.0,NaN,24.0,NaN,24.0,0.0,0.0,0.0,0.0,0.0
47592,a7e76ef4-1b7d-45d0-a629-4b0afb94199a,MSC COTONOU VIII,99836710.0,UL430W,2024-08-29 00:00:00,2024-08-29 12:00:00,UTC +00:00,NOON,AT SEA,2034S,...,0.0,NaN,23.0,NaN,23.0,0.0,0.0,0.0,0.0,0.0
47593,3de94823-cffe-469d-b306-02b47aea9d1f,MSC COTONOU VIII,99836710.0,UL430W,2024-08-30 00:00:00,2024-08-30 12:00:00,UTC +00:00,NOON,AT SEA,2459S,...,0.0,NaN,24.0,NaN,24.0,0.0,0.0,0.0,0.0,0.0
47594,fc8528e4-6372-4790-8fbd-3465bb213757,MSC COTONOU VIII,99836710.0,UL430W,2024-08-31 00:00:00,2024-08-31 12:00:00,UTC +00:00,NOON,AT SEA,2932S,...,0.0,NaN,24.0,NaN,24.0,0.0,0.0,0.0,0.0,0.0
47595,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0

In [73]:
# Remove the last digit from the IMO column
charterfinal['IMO_No'] = charterfinal['IMO_No'].astype(str).str[:-1]

charterfinal

,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,LAT,...,ECA_TIME,EGCS_DRY_WASTE_REMOVED,EGCS_RUNNING_TIME,EGCS_WET_SLURRY_REMOVED,EGCS_OPEN_LOOP_RUNNING_TIME,EGCS_CLOSED_LOOP_RUNNING_TIME,FUEL_M_E_LNG,FUEL_Aux_LNG,FUEL_Boiler_LNG,ROB_Rsdl_LNG
0,202b3fcb-ddcb-41ef-8365-b3d28ddcb8ca,MSC AURELIA,76021200.,407,2024-08-01 00:00:00,2024-08-01 06:12:00,UTC +02:00,EOSP,AT SEA,4328N,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
1,26e61ea7-3216-4bb7-a0ce-e5b69d34cf60,MSC AURELIA,76021200.,407,2024-08-01 00:00:00,2024-08-01 06:42:00,UTC +02:00,BRTH,DRIFTING,4328N,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
2,571a8985-617b-4f85-9eab-ef133661da63,MSC AURELIA,76021200.,407,2024-08-01 00:00:00,2024-08-01 12:00:00,UTC +02:00,PORT,IN PORT,4328N,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
3,a9d7bd6d-6015-4dd0-8e9e-f40d2c5285eb,MSC AURELIA,76021200.,407,2024-08-02 00:00:00,2024-08-01 19:30:00,UTC +02:00,SAIL,IN PORT,4328N,...,NaN,0.0,NaN,0.0,NaN,NaN,0.0,0.0,0.0,0.0
4,50ad5a0d-838a-4c10-9d7d-94d8c1bde30e,MSC AURELIA,76021200.,407,2024-08-02 00:00:00,2024-08-01 19:48:00,UTC +02:00,COSP,DRIFTING,4328N,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47591,3779916a-357d-47ca-85a0-0a957a87dc39,MSC COTONOU VIII,99836710.,UL430W,2024-08-28 00:00:00,2024-08-28 12:00:00,UTC -01:00,NOON,AT SEA,1624S,...,0.0,NaN,24.0,NaN,24.0,0.0,0.0,0.0,0.0,0.0
47592,a7e76ef4-1b7d-45d0-a629-4b0afb94199a,MSC COTONOU VIII,99836710.,UL430W,2024-08-29 00:00:00,2024-08-29 12:00:00,UTC +00:00,NOON,AT SEA,2034S,...,0.0,NaN,23.0,NaN,23.0,0.0,0.0,0.0,0.0,0.0
47593,3de94823-cffe-469d-b306-02b47aea9d1f,MSC COTONOU VIII,99836710.,UL430W,2024-08-30 00:00:00,2024-08-30 12:00:00,UTC +00:00,NOON,AT SEA,2459S,...,0.0,NaN,24.0,NaN,24.0,0.0,0.0,0.0,0.0,0.0
47594,fc8528e4-6372-4790-8fbd-3465bb213757,MSC COTONOU VIII,99836710.,UL430W,2024-08-31 00:00:00,2024-08-31 12:00:00,UTC +00:00,NOON,AT SEA,2932S,...,0.0,NaN,24.0,NaN,24.0,0.0,0.0,0.0,0.0,0.0
47595,NaN,NaN,na,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0

In [74]:
charterfinal.to_csv(r"D:\Navalt\MSC\2024\Weekly Data\CHARTER\CSV\charterdata_Aug_2024.csv",index=False)

In [75]:
charterfinal.to_excel(r"D:\Navalt\MSC\2024\Weekly Data\CHARTER\EXCEL\finalcharterdataAug2024.xlsx",index=False)

In [39]:
noon.to_csv(r"D:\Navalt\MSC\2024\Weekly Data\CHARTER\NOON\Noon_Jul_2024.csv",index=False)