# IMPORT DATA

In [22]:
import pandas as pd

In [23]:
imo=pd.read_csv('IMO_DCS_2023.csv')
imo

C:\Users\akshaya\AppData\Local\Temp\ipykernel_380\3651507769.py:1: DtypeWarning: Columns (18,20,64,66,68,75) have mixed types. Specify dtype option on import or set low_memory=False.
  imo=pd.read_csv('IMO_DCS_2023.csv')

,Source_System,IMO,Date_UTC,Time_UTC,Event,Event_Id,Sort_Number,Time_Since_Previous_Report,Distance,Latitude_North_South,...,ME_Consumption_BDN_2,AE_Fuel_BDN,AE_Consumption,Reefer_SFOC,Reefer_Fuel_Type,Wind_Force_Kn,Wind_Force_Bft,Wind_Dir_Degree,Remarks,Reefer_Fuel_BDN
0,OVDAdmin,7602120,2023-01-01,10:00,PORT NOON,NaN,NaN,24.0,0.0,N,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
1,OVDAdmin,7602120,2023-01-02,10:00,PORT NOON,NaN,NaN,24.0,0.0,N,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
2,OVDAdmin,7602120,2023-01-03,10:00,PORT NOON,NaN,NaN,24.0,0.0,N,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
3,OVDAdmin,7602120,2023-01-04,10:00,PORT NOON,NaN,NaN,24.0,0.0,N,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
4,OVDAdmin,7602120,2023-01-05,10:00,PORT NOON,NaN,NaN,24.0,0.0,N,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363902,OVDAdmin,9962550,2023-12-31,5:12,DEPARTURE,5191171.0,NaN,1.2,0.0,S,...,NaN,NaN,NaN,158.5,MGO,NaN,NaN,NaN,NaN,NaN
363903,OVDAdmin,9962550,2023-12-31,5:13,DEPARTURE,5191171.0,NaN,0.0,0.0,S,...,NaN,NaN,NaN,158.5,MGO,NaN,NaN,NaN,NaN,NaN
363904,OVDAPI,9962550,2023-12-31,7:30,COSP,5191159.0,NaN,2.3,13.0,N,...,NaN,NaN,NaN,158.5,MGO,15.0,4.0,330.0,NaN,NaN
363905,OVDAPI,9962550,2023-12-31,14:36,EOSP,5191170.0,NaN,7.1,60.0,N,...,NaN,NaN,NaN,158.5,MGO,15.0,4.0,330.0,NaN,NaN
363906,OVDAPI,9962550,2023-12-31,15:00,DELAY,5191169.0,NaN,0.4,1.0,N,...,NaN,NaN,NaN,158.5,MGO,NaN,NaN,NaN,NaN,NaN

In [24]:
lim=pd.read_csv('Limmasol_2023.csv')
lim

C:\Users\akshaya\AppData\Local\Temp\ipykernel_380\1334575195.py:1: DtypeWarning: Columns (156,157,158) have mixed types. Specify dtype option on import or set low_memory=False.
  lim=pd.read_csv('Limmasol_2023.csv')

,MessagesId,ImoNumber,vName,MessageType,DateTimeLt,DateTimeUtc,Latitude,Longitude,CargoMT,CargoTEU,...,Rob Adjustment ULS,Rob Adjustment Dist,Rob Adjustment LNG,Drydock,Rob Ajustment VLS,Rob Ajustment ULS,Rob Ajustment Dist,Rob Ajustment LNG,DryDock,Drydock2
0,4504378,9289051,MSC GIANNINA II,Delay,2023-01-01 10:18:00 +10:00,2023-01-01 0:18,4304N,13153E,12186.1,902.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4503870,9309289,MSC BELMONTE III,Delay,2023-01-01 11:24:00 +11:00,2023-01-01 0:24,3406S,15130E,16405.0,1738.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4504253,9456965,MSC ODESSA V,Berthing,2022-12-31 18:24:00 -06:00,2023-01-01 0:24,NaN,NaN,8998.5,2627.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4505330,9194866,MSC CHERYL 3,COSP,2023-01-01 08:30:00 +08:00,2023-01-01 0:30,0113N,10339E,7780.0,1145.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4504470,9239903,MSC PAMIRA III,COSP Transit,2023-01-01 03:30:00 +03:00,2023-01-01 0:30,4112N,02906E,13141.0,489.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
382729,5190496,9227285,MSC YANG R,EOSP,2024-01-01 08:24:00 +09:00,2023-12-31 23:24,3452N,12851E,13379.0,1528.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
382730,5189071,9252230,MSC REN V,COSP,2024-01-01 06:30:00 +07:00,2023-12-31 23:30,NaN,NaN,26635.7,2449.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
382731,5188828,9936628,MSC CLAUDE GIRARDET,Berthing,2024-01-01 07:42:00 +08:00,2023-12-31 23:42,NaN,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
382732,5189670,9930935,MSC BIANCA SILVIA,Delay,2023-12-31 20:48:00 -03:00,2023-12-31 23:48,3641S,07303W,75023.5,5836.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
382733,5189109,9327683,MSC MAKALU III,COSP,2024-01-01 07:54:00 +08:00,2023-12-31 23:54,2226N,11428E,5084.8,831.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
imo.shape

(363907, 77)

In [26]:
lim.shape

(382734, 172)

In [27]:
imo.columns.to_list()

['Source_System',
 'IMO',
 'Date_UTC',
 'Time_UTC',
 'Event',
 'Event_Id',
 'Sort_Number',
 'Time_Since_Previous_Report',
 'Distance',
 'Latitude_North_South',
 'Latitude_Degree',
 'Latitude_Minutes',
 'Longitude_East_West',
 'Longitude_Degree',
 'Longitude_Minutes',
 'Voyage_From',
 'Voyage_To',
 'Voyage_Number',
 'Voyage_Type',
 'Service',
 'Offhire_Reasons',
 'Cargo_Mt',
 'Cargo_m3',
 'Reefer_40_Chilled',
 'Reefer_20_Frozen',
 'Reefer_40_Frozen',
 'Passengers',
 'Time_Elapsed_Sailing',
 'Time_Elapsed_Maneuvering',
 'Time_Elapsed_Waiting',
 'Time_Elapsed_Anchoring',
 'Time_Elapsed_Drifting',
 'ME_Consumption_HFO',
 'ME_Consumption_LFO',
 'ME_Consumption_MGO',
 'ME_Consumption_MDO',
 'ME_Consumption_LNG',
 'ME_Consumption_LPGP',
 'ME_Consumption_LPGB',
 'ME_Consumption_M',
 'ME_Consumption_E',
 'ME_Consumption_O',
 'ME_Consumption_O_type',
 'AE_Consumption_HFO',
 'AE_Consumption_LFO',
 'AE_Consumption_MGO',
 'AE_Consumption_MDO',
 'AE_Consumption_LNG',
 'Boiler_Consumption_HFO',
 'Boiler_Consumption_LFO',
 'Boiler_Consumption_MGO',
 'Boiler_Consumption_MDO',
 'Boiler_Consumption_LNG',
 'HFO_ROB',
 'LFO_ROB',
 'MGO_ROB',
 'MDO_ROB',
 'LNG_ROB',
 'LPGP_ROB',
 'LPGB_ROB',
 'Methanol_ROB',
 'Ethanol_ROB',
 'O_ROB',
 'O_ROB_type',
 'ME_Fuel_BDN',
 'ME_Consumption',
 'ME_Fuel_BDN_2',
 'ME_Consumption_BDN_2',
 'AE_Fuel_BDN',
 'AE_Consumption',
 'Reefer_SFOC',
 'Reefer_Fuel_Type',
 'Wind_Force_Kn',
 'Wind_Force_Bft',
 'Wind_Dir_Degree',
 'Remarks',
 'Reefer_Fuel_BDN']

# IMO CHECKING

In [28]:
imo_unique_count= len(set(imo["IMO"]))
imo_unique_count

576

In [29]:
lim_unique_count= len(set(lim["ImoNumber"]))
lim_unique_count

552

In [30]:
imo_unique_missing=set(imo["IMO"])
imo_unique_missing

{7602120,
 7826790,
 8201624,
 8201636,
 8201648,
 8413875,
 8413887,
 8420892,
 8420907,
 8505836,
 8509375,
 8509387,
 8512891,
 8512906,
 8521397,
 8521402,
 8608200,
 8616520,
 8618293,
 8712520,
 8714205,
 8715857,
 8715869,
 8715871,
 8913411,
 8913423,
 8913447,
 8917778,
 8918057,
 8918954,
 8918966,
 8918978,
 8918980,
 9000742,
 9004231,
 9008574,
 9008603,
 9036002,
 9038907,
 9039250,
 9043756,
 9051478,
 9051492,
 9051507,
 9057173,
 9060649,
 9062984,
 9062996,
 9064748,
 9064750,
 9067544,
 9074042,
 9084607,
 9102710,
 9102722,
 9102746,
 9103685,
 9106479,
 9106493,
 9108398,
 9110377,
 9110389,
 9110391,
 9110975,
 9113446,
 9116369,
 9120841,
 9120853,
 9123154,
 9123166,
 9123221,
 9124366,
 9124512,
 9127021,
 9127540,
 9134490,
 9135638,
 9138783,
 9139086,
 9139505,
 9141285,
 9141297,
 9141780,
 9143879,
 9144134,
 9146467,
 9146479,
 9147071,
 9147215,
 9147227,
 9148025,
 9149328,
 9150080,
 9152856,
 9153850,
 9154191,
 9154206,
 9154220,
 9155107,
 9158525,
 9160920,
 9160982,
 9161297,
 9162277,
 9162631,
 9162643,
 9163192,
 9163207,
 9166651,
 9166778,
 9166780,
 9168831,
 9168843,
 9169029,
 9169031,
 9169043,
 9169055,
 9169067,
 9169122,
 9180190,
 9180205,
 9180968,
 9181651,
 9181663,
 9181675,
 9188219,
 9189366,
 9190092,
 9190119,
 9193680,
 9193719,
 9194866,
 9196838,
 9196852,
 9196864,
 9197545,
 9200677,
 9200689,
 9203538,
 9203904,
 9210050,
 9210062,
 9210086,
 9210098,
 9215672,
 9215892,
 9217565,
 9219379,
 9219393,
 9220328,
 9221059,
 9222106,
 9222120,
 9222273,
 9222285,
 9222302,
 9223904,
 9224049,
 9224051,
 9224348,
 9224946,
 9225249,
 9225251,
 9225794,
 9226360,
 9226932,
 9227285,
 9227297,
 9227302,
 9227314,
 9227326,
 9227338,
 9227340,
 9228576,
 9229300,
 9229312,
 9230775,
 9231119,
 9231248,
 9231250,
 9231262,
 9231779,
 9231810,
 9231822,
 9232395,
 9232462,
 9232632,
 9232644,
 9232656,
 9232761,
 9232773,
 9232890,
 9235402,
 9235581,
 9235608,
 9235610,
 9236212,
 9236224,
 9236444,
 9236585,
 9236688,
 9236690,
 9237151,
 9237371,
 9237498,
 9238739,
 9238741,
 9238789,
 9238882,
 9239733,
 9239903,
 9240328,
 9240873,
 9241451,
 9241463,
 9241475,
 9242625,
 9242637,
 9242651,
 9243239,
 9243241,
 9243394,
 9243409,
 9244881,
 9244946,
 9246566,
 9248148,
 9248928,
 9250983,
 9251688,
 9251690,
 9252230,
 9252541,
 9252553,
 9253014,
 9253038,
 9254848,
 9256315,
 9256327,
 9256365,
 9256391,
 9259379,
 9259381,
 9259393,
 9261815,
 9261827,
 9262546,
 9262560,
 9263332,
 9263344,
 9265598,
 9267637,
 9267649,
 9270828,
 9275024,
 9275036,
 9275373,
 9275397,
 9278143,
 9278155,
 9280861,
 9281267,
 9282259,
 9282261,
 9285665,
 9285691,
 9286231,
 9286267,
 9286774,
 9287792,
 9287900,
 9287924,
 9288409,
 9289051,
 9289087,
 9289099,
 9289544,
 9289960,
 9289972,
 9290402,
 9290426,
 9290488,
 9292175,
 9293167,
 9293179,
 9293442,
 9293466,
 9293777,
 9294408,
 9294824,
 9294989,
 9294991,
 9295165,
 9295177,
 9295397,
 9297864,
 9297876,
 9299020,
 9299525,
 9299537,
 9301328,
 9301330,
 9301483,
 9301550,
 9301990,
 9302085,
 9302619,
 9302621,
 9302633,
 9304459,
 9304708,
 9304746,
 9305001,
 9305013,
 9305477,
 9305489,
 9305506,
 9306263,
 9306275,
 9307267,
 9307839,
 9308584,
 9308601,
 9308625,
 9309289,
 9309411,
 9309447,
 9309459,
 9311737,
 9313943,
 9313967,
 9315006,
 9315018,
 9315379,
 9315381,
 9315836,
 9315886,
 9315915,
 9316347,
 9316359,
 9316361,
 9316373,
 9317925,
 9317937,
 9318046,
 9318058,
 9318187,
 9318773,
 9319600,
 9320398,
 9321897,
 9322011,
 9323041,
 9323493,
 9326768,
 9326823,
 9326835,
 9326940,
 9326964,
 9327671,
 9327683,
 9327798,
 9327803,
 9330068,
 9330226,
 9330238,
 9330240,
 9330264,
 9332729,
 9334349,
 9334519,
 9334832,
 9334844,
 9336165,
 9336359,
 9337444,
 9337676,
 9341122,
 9344564,
 9344708,
 9346017,
 9347762,
 9347803,
 9347970,
 9350317,
 9351579,
 9354363,
 9354416,
 9357107,
 9358905,
 9360271,
 9360283,
 9360764,
 9362449,
 9365984,
 9366421,
 9369734,
 9369758,
 9374571,
 9374595,
 9376141,
 9380271,
 9383223,
 9392561,
 9393022,
 9393307,
 9393319,
 9393321,
 9398216,
 9398228,
 9399765,
 9400148,
 9401166,
 9401685,
 9401776,
 9403396,
 9403437,
 9408774,
 9415296,
 9419644,
 9426817,
 9433157,
 9434462,
 9435820,
 9436472,
 9439735,
 9440306,
 9444285,
 9449687,
 9449821,
 9449869,
 9450296,
 9450325,
 9450351,
 9453298,
 9456965,
 9463035,
 9463047,
 9463059,
 9463205,
 9463281,
 9465241,
 9465253,
 9465265,
 9465277,
 9465306,
 9465318,
 9466960,
 9467445,
 9471226,
 9471238,
 9477309,
 9477610,
 9491616,
 9499010,
 9502908,
 9502960,
 9503732,
 9540065,
 9540077,
 9605152,
 9605231,
 9605243,
 9618276,
 9618288,
 9619452,
 9622007,
 9625932,
 9625944,
 9625970,
 9631876,
 9695016,
 9695028,
 9702065,
 9702077,
 9702089,
 9702091,
 9702106,
 9702261,
 9702273,
 9704960,
 9704972,
 9704984,
 9704996,
 9705005,
 9706310,
 9710426,
 9710438,
 9720196,
 9720201,
 9720287,
 9720457,
 9720471,
 9720483,
 9720495,
 9720500,
 9720512,
 9720524,
 9724049,
 9735206,
 9735218,
 9745653,
 9756729,
 9756731,
 9770737,
 9770749,
 9770751,
 9770763,
 9778076,
 9778088,
 9778090,
 9778105,
 9778117,
 9785445,
 9785457,
 9785469,
 9785471,
 9785483,
 9793947,
 9839260,
 9839272,
 9839284,
 9839296,
 9839301,
 9842061,
 9842073,
 9842085,
 9842097,
 9842102,
 9857157,
 9857169,
 9857171,
 9857183,
 9896983,
 9896995,
 9908047,
 9908059,
 9927251,
 9927263,
 9927275,
 9927287,
 9927299,
 9929429,
 9929431,
 9930038,
 9930052,
 9930064,
 9930935,
 9930947,
 9930959,
 9930961,
 9931288,
 9931290,
 9932036,
 9932048,
 9932050,
 9932062,
 9932892,
 9932907,
 9932919,
 9934735,
 9934747,
 9936616,
 9936628,
 9936630,
 9936642,
 9946714,
 9946843,
 9946855,
 9946867,
 9947110,
 9947122,
 9947134,
 9957347,
 9962548,
 9962550}

In [31]:
lim_unique_missing=set(lim['ImoNumber'])
lim_unique_missing

{7602120,
 7826790,
 8201624,
 8201636,
 8201648,
 8413875,
 8413887,
 8420892,
 8420907,
 8505836,
 8509375,
 8509387,
 8512891,
 8512906,
 8521397,
 8521402,
 8608200,
 8616520,
 8618293,
 8712520,
 8714205,
 8715857,
 8715869,
 8715871,
 8913411,
 8913423,
 8913447,
 8917778,
 8918057,
 8918954,
 8918966,
 8918978,
 8918980,
 9000742,
 9004231,
 9008574,
 9008603,
 9036002,
 9038907,
 9039250,
 9043756,
 9051478,
 9051492,
 9051507,
 9057173,
 9060649,
 9062984,
 9062996,
 9064748,
 9064750,
 9067544,
 9074042,
 9084607,
 9102710,
 9102722,
 9102746,
 9103685,
 9108398,
 9110377,
 9110389,
 9110391,
 9110975,
 9113446,
 9116369,
 9120841,
 9120853,
 9123154,
 9123166,
 9123221,
 9124366,
 9124512,
 9127021,
 9127540,
 9134490,
 9135638,
 9138783,
 9139086,
 9139505,
 9141285,
 9141297,
 9143879,
 9144134,
 9146467,
 9146479,
 9147071,
 9147227,
 9149328,
 9150080,
 9152856,
 9153850,
 9154191,
 9154206,
 9154220,
 9155107,
 9160982,
 9161297,
 9162277,
 9162631,
 9162643,
 9163192,
 9163207,
 9166651,
 9166778,
 9166780,
 9168831,
 9168843,
 9169029,
 9169031,
 9169043,
 9169055,
 9169067,
 9169122,
 9180190,
 9180205,
 9180968,
 9181651,
 9181663,
 9181675,
 9188219,
 9189366,
 9190092,
 9190119,
 9193680,
 9193719,
 9194866,
 9196838,
 9196852,
 9196864,
 9197545,
 9200677,
 9200689,
 9203538,
 9203904,
 9210050,
 9210062,
 9210086,
 9210098,
 9215672,
 9215892,
 9217565,
 9219393,
 9220328,
 9221059,
 9222106,
 9222120,
 9222302,
 9223904,
 9224049,
 9224051,
 9224348,
 9224946,
 9225249,
 9225251,
 9226360,
 9226932,
 9227285,
 9227297,
 9227302,
 9227314,
 9227326,
 9227338,
 9227340,
 9228576,
 9229300,
 9229312,
 9230775,
 9231119,
 9231248,
 9231250,
 9231262,
 9231779,
 9231810,
 9231822,
 9232395,
 9232462,
 9232632,
 9232644,
 9232656,
 9232761,
 9232773,
 9232890,
 9235402,
 9235581,
 9235608,
 9235610,
 9236212,
 9236224,
 9236444,
 9236585,
 9236688,
 9236690,
 9237151,
 9237371,
 9237498,
 9238739,
 9238741,
 9238789,
 9238882,
 9239733,
 9239903,
 9240328,
 9240873,
 9241451,
 9241463,
 9241475,
 9242625,
 9242637,
 9242651,
 9243239,
 9243241,
 9243394,
 9243409,
 9244881,
 9244946,
 9246566,
 9248148,
 9248928,
 9250983,
 9251688,
 9251690,
 9252230,
 9252541,
 9252553,
 9253014,
 9253038,
 9254848,
 9256315,
 9256327,
 9256365,
 9256391,
 9259379,
 9259381,
 9259393,
 9261815,
 9261827,
 9262546,
 9262560,
 9263332,
 9263344,
 9267637,
 9267649,
 9270828,
 9275024,
 9275036,
 9275373,
 9275397,
 9278143,
 9278155,
 9280861,
 9281267,
 9282259,
 9282261,
 9285665,
 9285691,
 9286231,
 9286267,
 9287792,
 9287900,
 9287924,
 9288409,
 9289051,
 9289087,
 9289099,
 9289544,
 9289960,
 9289972,
 9290402,
 9290426,
 9290488,
 9292175,
 9293167,
 9293179,
 9293442,
 9293466,
 9293777,
 9294408,
 9294824,
 9294989,
 9294991,
 9295165,
 9295177,
 9295397,
 9297864,
 9297876,
 9299020,
 9299525,
 9299537,
 9301328,
 9301330,
 9301483,
 9301550,
 9301990,
 9302085,
 9302619,
 9302621,
 9302633,
 9304459,
 9304708,
 9304746,
 9305001,
 9305013,
 9305477,
 9305489,
 9305506,
 9306263,
 9306275,
 9307267,
 9307839,
 9308584,
 9308601,
 9308625,
 9309289,
 9309411,
 9309447,
 9309459,
 9311737,
 9313943,
 9313967,
 9315006,
 9315018,
 9315379,
 9315381,
 9315836,
 9315886,
 9315915,
 9316347,
 9316359,
 9316361,
 9316373,
 9317925,
 9317937,
 9318046,
 9318058,
 9318187,
 9318773,
 9319600,
 9322011,
 9323041,
 9323493,
 9326768,
 9326823,
 9326940,
 9326964,
 9327671,
 9327683,
 9327798,
 9327803,
 9330068,
 9330226,
 9330238,
 9330240,
 9330264,
 9332729,
 9334349,
 9334832,
 9334844,
 9336165,
 9336359,
 9337444,
 9337676,
 9341122,
 9344564,
 9344708,
 9346017,
 9347762,
 9347803,
 9347970,
 9350317,
 9351579,
 9354363,
 9354416,
 9357107,
 9358905,
 9360271,
 9360283,
 9365984,
 9366421,
 9369734,
 9369758,
 9374571,
 9374595,
 9376141,
 9380271,
 9383223,
 9392561,
 9393022,
 9393307,
 9393319,
 9393321,
 9398216,
 9398228,
 9399765,
 9400148,
 9401166,
 9401685,
 9401776,
 9403396,
 9403437,
 9408774,
 9415296,
 9419644,
 9426817,
 9433157,
 9434462,
 9435820,
 9436472,
 9439735,
 9440306,
 9444285,
 9449687,
 9449869,
 9450296,
 9450325,
 9450351,
 9453298,
 9456965,
 9463035,
 9463047,
 9463059,
 9463205,
 9463281,
 9465241,
 9465253,
 9465265,
 9465277,
 9465306,
 9465318,
 9466960,
 9467445,
 9471226,
 9471238,
 9477309,
 9477610,
 9491616,
 9499010,
 9502908,
 9502960,
 9503732,
 9540065,
 9540077,
 9605243,
 9618264,
 9618276,
 9618288,
 9618290,
 9618305,
 9618317,
 9619452,
 9622007,
 9625932,
 9625944,
 9625970,
 9631876,
 9695016,
 9695028,
 9702065,
 9702077,
 9702089,
 9702091,
 9702106,
 9702261,
 9702273,
 9704960,
 9704972,
 9704984,
 9704996,
 9705005,
 9706310,
 9710426,
 9710438,
 9720196,
 9720201,
 9720287,
 9720457,
 9720471,
 9720483,
 9720495,
 9720500,
 9720512,
 9720524,
 9724049,
 9735206,
 9735218,
 9745653,
 9756729,
 9756731,
 9770737,
 9770749,
 9770751,
 9770763,
 9778076,
 9778088,
 9778090,
 9778105,
 9778117,
 9785445,
 9785457,
 9785469,
 9785471,
 9785483,
 9793947,
 9839260,
 9839272,
 9839284,
 9839296,
 9839301,
 9842061,
 9842073,
 9842085,
 9842097,
 9842102,
 9857157,
 9857169,
 9857171,
 9857183,
 9896983,
 9896995,
 9908047,
 9908059,
 9927251,
 9927263,
 9927275,
 9927287,
 9927299,
 9929429,
 9929431,
 9930038,
 9930052,
 9930064,
 9930935,
 9930947,
 9930959,
 9931288,
 9931290,
 9932036,
 9932048,
 9932050,
 9932062,
 9932892,
 9932907,
 9934735,
 9934747,
 9936616,
 9936628,
 9936630,
 9936642,
 9946714,
 9946843,
 9946855,
 9947110,
 9947122,
 9947134}

In [32]:
missing_lim = lim_unique_missing - imo_unique_missing
missing_lim

{9618264, 9618290, 9618305, 9618317}

In [33]:
missing_imo = imo_unique_missing - lim_unique_missing
missing_imo
#imp

{9106479,
 9106493,
 9141780,
 9147215,
 9148025,
 9158525,
 9160920,
 9219379,
 9222273,
 9222285,
 9225794,
 9265598,
 9286774,
 9320398,
 9321897,
 9326835,
 9334519,
 9360764,
 9362449,
 9449821,
 9605152,
 9605231,
 9930961,
 9932919,
 9946867,
 9957347,
 9962548,
 9962550}

In [34]:
print("Missing imo dcs", len(missing_imo))
print("Missing imo limmasol", len(missing_lim))

Missing imo dcs 28
Missing imo limmasol 4

In [35]:
imo_df=imo.copy()
lim_df=lim.copy()

In [16]:
imo_set ={9106479,
 9106493,
 9141780,
 9147215,
 9148025,
 9158525,
 9160920,
 9219379,
 9222273,
 9222285,
 9225794,
 9265598,
 9286774,
 9320398,
 9321897,
 9326835,
 9334519,
 9360764,
 9362449,
 9449821,
 9605152,
 9605231,
 9930961,
 9932919,
 9946867,
 9957347,
 9962548,
 9962550}

imolst = list(imo_set)

# Create a generator expression to format each IMO number with single quotes
formatted_imolst = ("{}".format(imo) for imo in imolst)

# Convert the generator object to a list
formatted_imolst_list = list(formatted_imolst)

print(formatted_imolst_list)

['9222273', '9225794', '9222285', '9320398', '9147215', '9362449', '9930961', '9148025', '9141780', '9932919', '9160920', '9449821', '9605152', '9957347', '9321897', '9158525', '9106479', '9605231', '9219379', '9962548', '9326835', '9962550', '9334519', '9946867', '9286774', '9360764', '9106493', '9265598']

In [36]:
imo_lst=['9618264', '9618290', '9618305', '9618317']
lim_df = lim_df[~lim_df['ImoNumber'].isin(imo_lst)]
lim_df['ImoNumber'] = lim_df['ImoNumber'].astype(str)
lim_df = lim_df[~lim_df['ImoNumber'].isin(imo_lst)]

In [37]:
imo_lst=['9222273', '9225794', '9222285', '9320398', '9147215', '9362449', '9930961', '9148025', '9141780', '9932919', '9160920', '9449821', '9605152', '9957347', '9321897', '9158525', '9106479', '9605231', '9219379', '9962548', '9326835', '9962550', '9334519', '9946867', '9286774', '9360764', '9106493', '9265598']
imo_df = imo_df[~imo_df['IMO'].isin(imo_lst)]
imo_df['IMO'] = imo_df['IMO'].astype(str)
imo_df = imo_df[~imo_df['IMO'].isin(imo_lst)]

In [38]:
print('imo dcs',imo_df['IMO'].nunique())
print('Limmasol',lim_df['ImoNumber'].nunique())

imo dcs 548
Limmasol 548

In [39]:
imo_df['Date_UTC'] = pd.to_datetime(imo_df['Date_UTC'])

# Group by 'imo' and remove duplicates based on combination of 'date_utc', 'time_utc', and 'distance'
imo_df = imo_df.groupby('IMO').apply(lambda x: x.drop_duplicates(subset=['Date_UTC', 'Time_UTC', 'Distance','ME_Consumption_HFO','ME_Consumption_HFO','ME_Consumption_LFO',
 'ME_Consumption_MGO',
 'ME_Consumption_MDO',
 'ME_Consumption_LNG',
 'AE_Consumption_HFO',
 'AE_Consumption_LFO',
 'AE_Consumption_MGO',
 'AE_Consumption_MDO',
 'AE_Consumption_LNG',
 'Boiler_Consumption_HFO',
 'Boiler_Consumption_LFO',
 'Boiler_Consumption_MGO',
 'Boiler_Consumption_MDO',
 'Boiler_Consumption_LNG'])).reset_index(drop=True)

In [40]:
lim_df.columns.to_list()

['MessagesId',
 'ImoNumber',
 'vName',
 'MessageType',
 'DateTimeLt',
 'DateTimeUtc',
 'Latitude',
 'Longitude',
 'CargoMT',
 'CargoTEU',
 'DraftAft',
 'DraftFwd',
 'Speed by gps',
 'Speed by log',
 'FOC_AE_DIS',
 'FOC_AE_DIS_ULS',
 'FOC_AE_DIS_VLS',
 'FOC_AE_LNG',
 'FOC_AE_RES_HS',
 'FOC_AE_RES_ULS',
 'FOC_AE_RES_VLS',
 'FOC_BLR_DIS',
 'FOC_BLR_DIS_ULS',
 'FOC_BLR_DIS_VLS',
 'FOC_BLR_LNG',
 'FOC_BLR_RES_HS',
 'FOC_BLR_RES_ULS',
 'FOC_BLR_RES_VLS',
 'FOC_ME_DIS',
 'FOC_ME_DIS_ULS',
 'FOC_ME_DIS_VLS',
 'FOC_ME_LNG',
 'FOC_ME_RES_HS',
 'FOC_ME_RES_ULS',
 'FOC_ME_RES_VLS',
 'Hours_AE_1',
 'Hours_AE_2',
 'Hours_AE_3',
 'Hours_AE_4',
 'Hours_AE_5',
 'Hours_ME',
 'Hours_SG',
 'Hours_TG',
 'Power_AE_1',
 'Power_AE_2',
 'Power_AE_3',
 'Power_AE_4',
 'Power_AE_5',
 'Power_ME',
 'Power_SG',
 'Power_TG',
 'ROB_DIS',
 'ROB_DIS_ULS',
 'ROB_DIS_VLS',
 'ROB_LNG',
 'ROB_RES_HS',
 'ROB_RES_ULS',
 'ROB_RES_VLS',
 'Port Code',
 'Port Name',
 'ETA Date/Time',
 'Eta date/time',
 'Sludge rob',
 'Sludge min discharge request',
 'Max Residual HS capacity',
 'Max Lng capacity',
 'Min Lng request',
 'Tanktainer number',
 'Port bunkering',
 'Wind direction',
 'Miles by gps',
 'STEAMING TIME M/E RESIDUAL HS',
 'RPM',
 'Slip',
 'Displacement',
 'ETA Port Code',
 'ETA Port Name',
 'Wind speed',
 'Course at Sea',
 'Number of Tanktainer',
 'Wave height',
 'Sea state',
 'Ambient temp',
 'Sw temp',
 'Miles speed log',
 'Requested speed',
 'Time change',
 'Time sea',
 'kwhr total',
 'Scavenge pressure',
 'Reefers positive plugged',
 'Reefers negative plugged',
 'Me total revs counter',
 'Rob fresh water',
 'SEA DIRECTION',
 'Eca miles',
 'Eca time',
 'Egcs running time',
 'So2/co2 ratio',
 'Rob tot Sludge',
 'Ballast',
 'Egcs closed loop running time',
 'Egcs open loop running time',
 'Steaming time m/e lng',
 'Reefer power consumption',
 'Pilot date/time',
 'PIER date/time',
 'Time manoeuvring',
 'Estimated departure date/time',
 'Manoeuvring miles by gps',
 'Manoeuvring miles by speed log',
 'Kwhr total',
 'Hold ventilation off',
 'ETB Date/Time',
 'Steaming time m/e residual hs',
 'Steaming time m/e residual uls',
 'Steaming time m/e residual vls',
 'Steaming time m/e distillate vls',
 'Steaming time m/e distillate uls',
 'Rpm',
 'Type of delay',
 'Reason',
 'Time hrs. anchor',
 'Time hrs. drift',
 'TEU Full',
 'TEU Empty',
 'Fresh water supply',
 'Tanktainer distillates transfd',
 'Hold Ventilation On/Off',
 'Bilge removed',
 'Tot sludge removed',
 'Garbage cat a - plastic removed',
 'Garbage cat b - organic removed',
 'Garbage cat c - domestic removed',
 'Garbage cat e - ashes removed',
 'Rob garbage cat a - plastic',
 'Rob garbage cat b - organic',
 'Rob garbage cat c - domestic',
 'Rob garbage cat e - ashes',
 'Egcs wet waste removed',
 'Egcs dry waste removed',
 'Shift berth hours',
 'Oil Cylinder',
 'ROB fresh water',
 'Product Name',
 'Physical supplier name',
 'Volume',
 'Quantity',
 'Density at 15°C',
 'Viscosity at 40°C or 50°C',
 'Sulfur content',
 'Bunker Order',
 'Bdn number',
 'Rob actual sludge',
 'Rob actual bilge',
 'Qty sludge disposed',
 'Tanktainer min request',
 'Comments',
 'Template version',
 'TANKTAINER ROB',
 'Rob Ajustment HS',
 'Rob Adjustment VLS',
 'Rob Adjustment ULS',
 'Rob Adjustment Dist',
 'Rob Adjustment LNG',
 'Drydock',
 'Rob Ajustment VLS',
 'Rob Ajustment ULS',
 'Rob Ajustment Dist',
 'Rob Ajustment LNG',
 'DryDock',
 'Drydock2']

In [41]:
lim_df['DateTimeUtc'] = pd.to_datetime(lim_df['DateTimeUtc'])

# Group by 'imo' and remove duplicates based on combination of 'date_utc', 'time_utc', and 'distance'
lim_df = lim_df.groupby('ImoNumber').apply(lambda x: x.drop_duplicates(subset=['MessagesId', 'DateTimeUtc','RPM', 'Miles by gps','kwhr total'])).reset_index(drop=True)

In [42]:
imo_df.shape

(351155, 77)

In [43]:
lim_df.shape

(380010, 172)


columns_of_interest = ['IMO','Date_UTC', 'Time_UTC']
duplicates = imo_df.duplicated()
duplicate_rows = imo_df[duplicates]
print(duplicate_rows)
#duplicate_rows.to_csv('D.csv', index=False)
#imo_df.drop_duplicates(inplace=True)

# REPORT TYPE CHCEKING

In [44]:
unique_events_count = imo_df['Event'].nunique()

print("Number of unique events:", unique_events_count)

Number of unique events: 45

In [45]:
unique_event_count = imo_df['Event'].unique()

unique_event_count

array(['PORT NOON', 'DEPARTURE', 'BOSP', 'NOON REPORT', 'EOSP', 'ARRIVAL',
       'duplicate', 'DELAY ARRIVAL', 'Noon (Position) - Port',
       'Begin of sea passage', 'End of sea passage',
       'Noon (Position) - Sea passage', 'DELAY', 'cancelled', 'COSP',
       'NOON', 'COSP TRANSIT', 'DELAY DEPARTURE', 'ignore', 'Arrival',
       'Departure', 'Duplicate', 'duplciate', 'PORTNOON', 'wrong entry',
       'Cancelled', 'At Anchor', 'Noon', nan, 'Port Noon',
       'canal passage', 'Begin Of Sea Passage', 'Noon At Sea',
       'End Of Sea Passage', 'Begin Fuel Change Over',
       'End Fuel Change Over', 'Noon In Port', 'Begin Waiting/Drifting',
       'End Waiting/Drifting', 'Destination Changed', 'Drop Anchor',
       'Heave Anchor', 'Noon Maneuvering', 'noon at port', 'SOSP', 'noon'],
      dtype=object)

In [46]:
imo_df

,Source_System,IMO,Date_UTC,Time_UTC,Event,Event_Id,Sort_Number,Time_Since_Previous_Report,Distance,Latitude_North_South,...,ME_Consumption_BDN_2,AE_Fuel_BDN,AE_Consumption,Reefer_SFOC,Reefer_Fuel_Type,Wind_Force_Kn,Wind_Force_Bft,Wind_Dir_Degree,Remarks,Reefer_Fuel_BDN
0,OVDAdmin,7602120,2023-01-01,10:00,PORT NOON,NaN,NaN,24.0,0.0,N,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
1,OVDAdmin,7602120,2023-01-02,10:00,PORT NOON,NaN,NaN,24.0,0.0,N,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
2,OVDAdmin,7602120,2023-01-03,10:00,PORT NOON,NaN,NaN,24.0,0.0,N,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
3,OVDAdmin,7602120,2023-01-04,10:00,PORT NOON,NaN,NaN,24.0,0.0,N,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
4,OVDAdmin,7602120,2023-01-05,10:00,PORT NOON,NaN,NaN,24.0,0.0,N,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351150,OVDAPI,9947134,2023-12-27,9:00,NOON,5181079.0,NaN,24.0,279.0,S,...,NaN,NaN,NaN,153.8,HFO,20.0,5.0,100.0,NaN,NaN
351151,OVDAPI,9947134,2023-12-28,10:00,NOON,5183009.0,NaN,25.0,503.0,S,...,NaN,NaN,NaN,153.8,HFO,12.0,4.0,90.0,NaN,NaN
351152,OVDAPI,9947134,2023-12-29,10:00,NOON,5184824.0,NaN,24.0,457.0,S,...,NaN,NaN,NaN,153.8,HFO,20.0,5.0,20.0,NaN,NaN
351153,OVDAPI,9947134,2023-12-30,10:00,NOON,5186493.0,NaN,24.0,458.0,S,...,NaN,NaN,NaN,153.8,HFO,11.0,4.0,30.0,NaN,NaN
351154,OVDAPI,9947134,2023-12-31,11:00,NOON,5188287.0,NaN,25.0,475.0,S,...,NaN,NaN,NaN,153.8,HFO,16.0,4.0,350.0,NaN,NaN

# Days

In [47]:
imo_df['Date_UTC'] = pd.to_datetime(imo_df['Date_UTC'])

result = imo_df.groupby('IMO')['Date_UTC'].agg(['min', 'max']).reset_index()

# Calculate number of days
result['min'] = pd.to_datetime(result['min'])
result['max'] = pd.to_datetime(result['max'])
result['Days Count'] = (result['max'] - result['min']).dt.days + 1

missing_dates = []

for _, row in result.iterrows():
    imo_no = row['IMO']
    date_range = pd.date_range(start=row['min'], end=row['max'], freq='D')
    actual_dates = set(imo_df[imo_df['IMO'] == imo_no]['Date_UTC'])
    missing = list(set(date_range) - actual_dates)
    missing_str = [date.strftime('%Y-%m-%d') for date in missing]  # Convert datetime.date objects to string
    missing_dates.append([imo_no, missing_str, len(missing)])


missing_dates_imodcs = pd.DataFrame(missing_dates, columns=['imo', 'Missing Dates', 'Count'])

print(missing_dates_imodcs)

         imo                         Missing Dates  Count
0    7602120                                    []      0
1    7826790                                    []      0
2    8201624                                    []      0
3    8201636                                    []      0
4    8201648                                    []      0
..       ...                                   ...    ...
543  9946843              [2023-07-26, 2023-07-25]      2
544  9946855              [2023-10-17, 2023-10-18]      2
545  9947110  [2023-12-11, 2023-09-02, 2023-06-09]      3
546  9947122                                    []      0
547  9947134                                    []      0

[548 rows x 3 columns]

In [48]:
missing_dates_imodcs.to_csv('MIMO-2023.csv')

In [49]:
lim_df['DateTimeUtc'] = pd.to_datetime(lim_df['DateTimeUtc'])

result = lim_df.groupby('ImoNumber')['DateTimeUtc'].agg(['min', 'max']).reset_index()

# Calculate number of days
result['min'] = pd.to_datetime(result['min'])
result['max'] = pd.to_datetime(result['max'])
result['Days Count'] = (result['max'] - result['min']).dt.days + 1

missing_dates = []

for _, row in result.iterrows():
    imo_no = row['ImoNumber']
    date_range = pd.date_range(start=row['min'], end=row['max'], freq='D').date
    actual_dates = set(lim_df[lim_df['ImoNumber'] == imo_no]['DateTimeUtc'].dt.date)
    missing = list(set(date_range) - actual_dates)
    missing_str = [date.strftime('%Y-%m-%d') for date in missing]  # Convert datetime.date objects to string
    missing_dates.append([imo_no, missing_str, len(missing)])


missing_dates_lim = pd.DataFrame(missing_dates, columns=['imo', 'Missing Dates', 'Count'])

missing_dates_lim

         imo                                      Missing Dates  Count
0    7602120  [2023-08-30, 2023-05-05, 2023-03-05, 2023-03-1...     63
1    7826790  [2023-01-06, 2023-02-10, 2023-06-20, 2023-06-1...      5
2    8201624                                                 []      0
3    8201636                                                 []      0
4    8201648                                                 []      0
..       ...                                                ...    ...
543  9946843                                                 []      0
544  9946855                                                 []      0
545  9947110                           [2023-12-11, 2023-09-02]      2
546  9947122                                                 []      0
547  9947134                                                 []      0

[548 rows x 3 columns]

In [50]:
missing_dates_lim.to_csv('MLIM-2023.csv')

In [51]:
imo_df['Date_UTC']= pd.to_datetime(imo_df['Date_UTC']).dt.date
imo_df['Date_UTC']=imo_df['Date_UTC'].astype(str)

In [52]:
lim_df['DateTimeUtc']= pd.to_datetime(lim_df['DateTimeUtc']).dt.date
lim_df['DateTimeUtc']=lim_df['DateTimeUtc'].astype(str)

In [53]:
# Iterate through each row of missing_dates_imo
for _, row in missing_dates_imodcs.iterrows():
    imo_no = row['imo']
    missing_dates = row['Missing Dates']
    
    # Convert missing_dates to datetime objects
    missing_dates = pd.to_datetime(missing_dates)
    
    # Filter out rows with the specified IMO and missing dates
    lim_df = lim_df[~((lim_df['ImoNumber'] == imo_no) & lim_df['DateTimeUtc'].isin(missing_dates))]

In [54]:
# Iterate through each row of missing_dates_imo
for _, row in missing_dates_lim.iterrows():
    imo_no = row['imo']
    missing_dates = row['Missing Dates']
    
    # Convert missing_dates to datetime objects
    missing_dates = pd.to_datetime(missing_dates)
    
    # Filter out rows with the specified IMO and missing dates
    imo_df = imo_df[~((imo_df['IMO'] == imo_no) & imo_df['Date_UTC'].isin(missing_dates))]

In [55]:
imo_df.shape

(351155, 77)

In [56]:
lim_df.shape

(380010, 172)

# Fuel and Distance

In [57]:
imo_df['MGO_MDO']=imo_df[['ME_Consumption_MGO','ME_Consumption_MDO','AE_Consumption_MGO','AE_Consumption_MDO','Boiler_Consumption_MGO','Boiler_Consumption_MDO']].sum(axis=1)

In [58]:
imo_df['Total_ME']=imo_df[['ME_Consumption_HFO','ME_Consumption_LFO','ME_Consumption_MGO','ME_Consumption_MDO']].sum(axis=1)
imo_df['Total_AE']=imo_df[['AE_Consumption_HFO','AE_Consumption_LFO','AE_Consumption_MGO','AE_Consumption_MDO']].sum(axis=1)
imo_df['Total_Boiler']=imo_df[['Boiler_Consumption_HFO','Boiler_Consumption_LFO','Boiler_Consumption_MGO','Boiler_Consumption_MDO']].sum(axis=1)

In [59]:
fuel_imodcs=imo_df[['IMO','Distance','Date_UTC','ME_Consumption_HFO', 'ME_Consumption_LFO','AE_Consumption_HFO','AE_Consumption_LFO',
                    'Boiler_Consumption_HFO','Boiler_Consumption_LFO','MGO_MDO','Total_ME','Total_AE','Total_Boiler'
]]

In [60]:
fuel_imodcs

,IMO,Distance,Date_UTC,ME_Consumption_HFO,ME_Consumption_LFO,AE_Consumption_HFO,AE_Consumption_LFO,Boiler_Consumption_HFO,Boiler_Consumption_LFO,MGO_MDO,Total_ME,Total_AE,Total_Boiler
0,7602120,0.0,2023-01-01,0.0,0.0,0.0,0.0,0.0,0.0,2.22,0.0,2.10,0.12
1,7602120,0.0,2023-01-02,0.0,0.0,0.0,0.0,0.0,0.0,2.16,0.0,2.04,0.12
2,7602120,0.0,2023-01-03,0.0,0.0,0.0,0.0,0.0,0.0,2.16,0.0,2.04,0.12
3,7602120,0.0,2023-01-04,0.0,0.0,0.0,0.0,0.0,0.0,2.22,0.0,2.10,0.12
4,7602120,0.0,2023-01-05,0.0,0.0,0.0,0.0,0.0,0.0,2.43,0.0,2.31,0.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
351150,9947134,279.0,2023-12-27,72.0,0.0,13.0,0.0,1.0,0.0,0.00,72.0,13.00,1.00
351151,9947134,503.0,2023-12-28,110.0,0.0,13.0,0.0,0.0,0.0,0.00,110.0,13.00,0.00
351152,9947134,457.0,2023-12-29,107.0,0.0,7.0,0.0,0.0,0.0,0.00,107.0,7.00,0.00
351153,9947134,458.0,2023-12-30,113.0,0.0,0.0,0.0,0.4,0.0,0.00,113.0,0.00,0.40
351154,9947134,475.0,2023-12-31,117.0,0.0,0.0,0.0,0.9,0.0,0.00,117.0,0.00,0.90

In [61]:
import pandas as pd

# Assuming 'fuel_imodcs' is your DataFrame containing fuel data
fuel_imodcs['Date_UTC'] = pd.to_datetime(fuel_imodcs['Date_UTC'])

# Extracting the month from 'Date_UTC'
fuel_imodcs['month'] = fuel_imodcs['Date_UTC'].dt.month

# Grouping by 'imo' and performing aggregations
grouped_df = fuel_imodcs.groupby('IMO').agg({
    'Date_UTC': 'first',  # Assuming you want the first date in each group
    'Distance': 'sum',
    'ME_Consumption_HFO': 'sum',
    'ME_Consumption_LFO': 'sum',
    'AE_Consumption_HFO': 'sum',
    'AE_Consumption_LFO': 'sum',
    'Boiler_Consumption_HFO': 'sum',
    'Boiler_Consumption_LFO': 'sum',
    'MGO_MDO': 'sum',
    'Total_ME': 'sum',
    'Total_AE': 'sum',
    'Total_Boiler': 'sum'
}).reset_index()

# Sorting the DataFrame by 'imo'
fuel_imo_grouped_df = grouped_df.sort_values(by='IMO')


fuel_imo_grouped_df

C:\Users\akshaya\AppData\Local\Temp\ipykernel_380\3244407165.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_imodcs['Date_UTC'] = pd.to_datetime(fuel_imodcs['Date_UTC'])
C:\Users\akshaya\AppData\Local\Temp\ipykernel_380\3244407165.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_imodcs['month'] = fuel_imodcs['Date_UTC'].dt.month

,IMO,Date_UTC,Distance,ME_Consumption_HFO,ME_Consumption_LFO,AE_Consumption_HFO,AE_Consumption_LFO,Boiler_Consumption_HFO,Boiler_Consumption_LFO,MGO_MDO,Total_ME,Total_AE,Total_Boiler
0,7602120,2023-01-01,7148.25,0.00,0.00,0.00,0.00,0.00,0.00,1831.35,536.97,1252.34,42.04
1,7826790,2023-01-01,25245.83,0.00,3707.64,0.00,0.00,0.00,0.02,2951.14,3736.42,2574.12,348.26
2,8201624,2023-01-01,55148.10,0.00,4211.27,0.00,3.74,0.00,0.80,1468.14,4211.97,1306.56,165.42
3,8201636,2023-01-01,61608.90,0.00,3743.94,0.00,0.00,0.00,0.00,1202.28,3753.64,1006.95,185.63
4,8201648,2023-01-01,60307.10,0.00,3968.15,0.00,0.00,0.00,0.10,1573.69,3968.15,1350.57,223.22
...,...,...,...,...,...,...,...,...,...,...,...,...,...
543,9946843,2023-07-24,36308.00,5904.27,0.00,2141.26,0.00,171.17,0.00,580.12,6303.37,2303.43,190.02
544,9946855,2023-10-16,16383.90,3639.76,0.00,714.33,0.00,96.40,0.00,244.32,3689.10,848.03,157.68
545,9947110,2023-06-08,54155.15,10664.63,0.00,2526.95,0.00,426.10,0.00,349.98,10832.73,2655.52,479.41
546,9947122,2023-08-22,33226.40,6198.71,40.60,1482.10,50.40,92.80,198.18,135.75,6261.61,1615.75,321.18
547,9947134,2023-09-27,13297.60,2449.20,43.40,862.50,0.00,143.70,67.40,308.40,2514.10,1035.20,325.30

In [62]:
fuel_imo_grouped_df

,IMO,Date_UTC,Distance,ME_Consumption_HFO,ME_Consumption_LFO,AE_Consumption_HFO,AE_Consumption_LFO,Boiler_Consumption_HFO,Boiler_Consumption_LFO,MGO_MDO,Total_ME,Total_AE,Total_Boiler
0,7602120,2023-01-01,7148.25,0.00,0.00,0.00,0.00,0.00,0.00,1831.35,536.97,1252.34,42.04
1,7826790,2023-01-01,25245.83,0.00,3707.64,0.00,0.00,0.00,0.02,2951.14,3736.42,2574.12,348.26
2,8201624,2023-01-01,55148.10,0.00,4211.27,0.00,3.74,0.00,0.80,1468.14,4211.97,1306.56,165.42
3,8201636,2023-01-01,61608.90,0.00,3743.94,0.00,0.00,0.00,0.00,1202.28,3753.64,1006.95,185.63
4,8201648,2023-01-01,60307.10,0.00,3968.15,0.00,0.00,0.00,0.10,1573.69,3968.15,1350.57,223.22
...,...,...,...,...,...,...,...,...,...,...,...,...,...
543,9946843,2023-07-24,36308.00,5904.27,0.00,2141.26,0.00,171.17,0.00,580.12,6303.37,2303.43,190.02
544,9946855,2023-10-16,16383.90,3639.76,0.00,714.33,0.00,96.40,0.00,244.32,3689.10,848.03,157.68
545,9947110,2023-06-08,54155.15,10664.63,0.00,2526.95,0.00,426.10,0.00,349.98,10832.73,2655.52,479.41
546,9947122,2023-08-22,33226.40,6198.71,40.60,1482.10,50.40,92.80,198.18,135.75,6261.61,1615.75,321.18
547,9947134,2023-09-27,13297.60,2449.20,43.40,862.50,0.00,143.70,67.40,308.40,2514.10,1035.20,325.30

import pandas as pd

# Assuming 'fuel_imodcs' is your DataFrame containing fuel data
fuel_imodcs['Date_UTC'] = pd.to_datetime(fuel_imodcs['Date_UTC'])

# Assigning a unique number to each date within each vessel's data
fuel_imodcs['Days_running_imodcs'] = fuel_imodcs.groupby('IMO').cumcount() + 1

# Modifying the assigned day numbers to ensure they don't exceed 365
fuel_imodcs['Days_running_imodcs'] = fuel_imodcs['Days_running_imodcs'].apply(lambda x: x % 365 if x <= 365 else x % 365 + 1)

# Grouping by 'IMO' and summing the modified assigned numbers to calculate days run
grouped_dates = fuel_imodcs.groupby('IMO')['Days_running_imodcs'].agg(Days_running_imodcs='max')

# Calculating the count of missing days for each vessel
grouped_dates['Missing_days_imodcs'] = 365 - grouped_dates['Days_running_imodcs']

grouped_dates = grouped_dates.reset_index()

grouped_dates.head(7)

In [63]:
import pandas as pd

# Assuming 'fuel_imodcs' is your DataFrame containing fuel data
fuel_imodcs['Date_UTC'] = pd.to_datetime(fuel_imodcs['Date_UTC'])

# Dropping duplicate rows based on 'IMO' and 'Date_UTC' columns
fuel_imodcs.drop_duplicates(subset=['IMO', 'Date_UTC'], inplace=True)

# Assigning a unique number to each date within each vessel's data
fuel_imodcs['Days_running_imodcs'] = fuel_imodcs.groupby('IMO').cumcount() + 1

# Modifying the assigned day numbers to ensure they don't exceed 365
fuel_imodcs['Days_running_imodcs'] = fuel_imodcs['Days_running_imodcs'].apply(lambda x: x % 365 if x <= 365 else x % 365 + 1)

# Grouping by 'IMO' and summing the modified assigned numbers to calculate days run
grouped_dates = fuel_imodcs.groupby('IMO')['Days_running_imodcs'].agg(Days_running_imodcs='max')

# Calculating the count of missing days for each vessel
grouped_dates['Missing_days_imodcs'] = 365 - grouped_dates['Days_running_imodcs']

# Extracting count of unique dates for each IMO
count_unique_dates_per_imo = fuel_imodcs.groupby('IMO')['Date_UTC'].nunique().reset_index()
count_unique_dates_per_imo.columns = ['IMO', 'Count_Unique_Dates']

# Merging the two DataFrames on 'IMO'
merged_data = pd.merge(grouped_dates, count_unique_dates_per_imo, on='IMO')

merged_data.head(7)

C:\Users\akshaya\AppData\Local\Temp\ipykernel_380\780805684.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_imodcs['Date_UTC'] = pd.to_datetime(fuel_imodcs['Date_UTC'])
C:\Users\akshaya\AppData\Local\Temp\ipykernel_380\780805684.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_imodcs.drop_duplicates(subset=['IMO', 'Date_UTC'], inplace=True)
C:\Users\akshaya\AppData\Local\Temp\ipykernel_380\780805684.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_imodcs['Days_running_imodcs'] = fuel_imodcs.groupby('IMO').cumcount() + 1
C:\Users\akshaya\AppData\Local\Temp\ipykernel_380\780805684.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_imodcs['Days_running_imodcs'] = fuel_imodcs['Days_running_imodcs'].apply(lambda x: x % 365 if x <= 365 else x % 365 + 1)

       IMO  Days_running_imodcs  Missing_days_imodcs  Count_Unique_Dates
0  7602120                  364                    1                 365
1  7826790                  364                    1                 365
2  8201624                  364                    1                 365
3  8201636                  364                    1                 365
4  8201648                  364                    1                 365
5  8413875                  363                    2                 363
6  8413887                  152                  213                 152

In [64]:
merged_data.to_csv("merged_data- 2023.csv")

In [65]:
# Merging 'grouped_dates' DataFrame with 'fuel_imo_grouped_df' on the 'IMO' column
fuel_imo_grouped_df = pd.merge(fuel_imo_grouped_df, merged_data, on='IMO', how='left')

fuel_imo_grouped_df.head(7)

,IMO,Date_UTC,Distance,ME_Consumption_HFO,ME_Consumption_LFO,AE_Consumption_HFO,AE_Consumption_LFO,Boiler_Consumption_HFO,Boiler_Consumption_LFO,MGO_MDO,Total_ME,Total_AE,Total_Boiler,Days_running_imodcs,Missing_days_imodcs,Count_Unique_Dates
0,7602120,2023-01-01,7148.25,0.0,0.00,0.0,0.00,0.0,0.00,1831.35,536.97,1252.34,42.04,364,1,365
1,7826790,2023-01-01,25245.83,0.0,3707.64,0.0,0.00,0.0,0.02,2951.14,3736.42,2574.12,348.26,364,1,365
2,8201624,2023-01-01,55148.10,0.0,4211.27,0.0,3.74,0.0,0.80,1468.14,4211.97,1306.56,165.42,364,1,365
3,8201636,2023-01-01,61608.90,0.0,3743.94,0.0,0.00,0.0,0.00,1202.28,3753.64,1006.95,185.63,364,1,365
4,8201648,2023-01-01,60307.10,0.0,3968.15,0.0,0.00,0.0,0.10,1573.69,3968.15,1350.57,223.22,364,1,365
5,8413875,2023-01-01,31747.36,0.0,1777.55,0.0,0.00,0.0,0.25,1124.83,1777.80,975.66,149.17,363,2,363
6,8413887,2023-01-01,20076.15,0.0,1252.63,0.0,0.00,0.0,0.00,594.77,1310.23,414.11,123.06,152,213,152

In [67]:
fuel_imo_grouped_df.to_csv('fuel_grouped_imo_df-2023.csv')

fuel_imo_grouped_df['IMO'] = fuel_imo_grouped_df['IMO'].astype(str)
result_fuel_df = fuel_imo_grouped_df.merge(fuel_imo_grouped_df, left_on=['imo', 'month'], right_on=['IMO', 'month'], how='inner')
print(result_fuel_df)

In [68]:
#result_fuel_df.to_csv('Data comparison.csv')

In [69]:
#lim

In [70]:
lim_df['Distance_lim']= lim_df[['Miles by gps','Manoeuvring miles by gps']].sum(axis=1)
lim_df['ME_hs_lima'] =  lim_df[['FOC_ME_RES_HS']]
lim_df['AUX_hs_lima'] =  lim_df[['FOC_AE_RES_HS']]
lim_df['Boiler_hs_lima'] =  lim_df[['FOC_BLR_RES_HS']]
 
lim_df['ME_ls_lima'] =  lim_df[['FOC_ME_RES_ULS','FOC_ME_RES_VLS']].sum(axis = 1) 
lim_df['AUX_ls_lima'] =  lim_df[['FOC_ME_RES_ULS','FOC_ME_RES_VLS']].sum(axis = 1)  
lim_df['Boiler_ls_lima'] =  lim_df[['FOC_BLR_RES_VLS','FOC_BLR_RES_ULS']] .sum(axis = 1)
 
lim_df['ME_uls_lima'] =  lim_df[['FOC_ME_DIS','FOC_ME_DIS_ULS','FOC_ME_DIS_VLS']].sum(axis = 1) 
lim_df['AUX_uls_lima'] =  lim_df[['FOC_AE_DIS','FOC_AE_DIS_ULS','FOC_AE_DIS_VLS']].sum(axis = 1) 
lim_df['Boiler_uls_lima'] =  lim_df[['FOC_BLR_DIS','FOC_BLR_DIS_ULS','FOC_BLR_DIS_VLS']] .sum(axis = 1)
 
lim_df['Total_ME_lima'] = lim_df[['ME_hs_lima','ME_ls_lima','ME_uls_lima']].sum(axis = 1)   
lim_df['Total_AUX_lima'] = lim_df[['AUX_hs_lima','AUX_ls_lima','AUX_uls_lima']].sum(axis = 1) 
lim_df['Total_Boiler_lima'] = lim_df[['Boiler_hs_lima','Boiler_ls_lima','Boiler_uls_lima']].sum(axis = 1)


lim_df["Total_HS"]=lim_df[['FOC_ME_RES_HS','FOC_AE_RES_HS',"FOC_BLR_RES_HS"]].sum(axis = 1) 
lim_df["Total_LS"]=lim_df[['FOC_ME_RES_ULS','FOC_ME_RES_VLS','FOC_ME_RES_ULS','FOC_ME_RES_VLS','FOC_BLR_RES_VLS','FOC_BLR_RES_ULS']].sum(axis = 1) 
lim_df["Total_ULS"]=lim_df[['FOC_ME_DIS','FOC_ME_DIS_ULS','FOC_ME_DIS_VLS','FOC_AE_DIS','FOC_AE_DIS_ULS','FOC_AE_DIS_VLS','FOC_BLR_DIS','FOC_BLR_DIS_ULS','FOC_BLR_DIS_VLS']].sum(axis = 1)

In [71]:
fuel_lim=lim_df[['ImoNumber','vName','Distance_lim','DateTimeUtc','Total_HS','Total_LS','Total_ULS','Total_ME_lima','Total_AUX_lima','Total_Boiler_lima']]

In [72]:
import pandas as pd

# Selecting specific columns from lim_df
#fuel_lim = lim_df[['ImoNumber', 'vName', 'Miles by gps', 'DateTimeUtc', 'Total_ME_lima', 'Total_AUX_lima', 'Total_Boiler_lima']]

# Convert 'DateTimeUtc' column to datetime
fuel_lim['DateTimeUtc'] = pd.to_datetime(fuel_lim['DateTimeUtc'])

# Extracting the month from 'DateTimeUtc'

# Grouping by 'ImoNumber' and 'month' and aggregating
fuel_lim_grouped = fuel_lim.groupby(['ImoNumber']).agg({
    'vName': 'first',  # Assuming 'vName' doesn't change within a month
    'Distance_lim': 'sum',
    'DateTimeUtc': 'first',
    'Total_HS':'sum',
    'Total_LS':'sum',
    'Total_ULS':'sum',
    'Total_ME_lima': 'sum',
    'Total_AUX_lima': 'sum',
    'Total_Boiler_lima': 'sum'
}).reset_index()


fuel_lim_grouped

C:\Users\akshaya\AppData\Local\Temp\ipykernel_380\101913375.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_lim['DateTimeUtc'] = pd.to_datetime(fuel_lim['DateTimeUtc'])

,ImoNumber,vName,Distance_lim,DateTimeUtc,Total_HS,Total_LS,Total_ULS,Total_ME_lima,Total_AUX_lima,Total_Boiler_lima
0,7602120,MSC AURELIA,5488.50,2023-02-02,0.000,0.000,1338.9080,395.070,910.5920,33.2460
1,7826790,GNV AZZURRA,24559.93,2023-01-01,0.000,7247.260,2867.0300,3651.340,6125.7700,337.1800
2,8201624,MSC IRIS,55148.10,2023-01-01,0.000,8423.276,1467.8254,4211.938,5513.8237,165.3397
3,8201636,MSC MALIN,61608.90,2023-01-01,0.000,7487.880,1202.2630,3753.640,4750.8730,185.6300
4,8201648,MSC EYRA,60307.10,2023-01-01,0.000,7936.400,1572.8350,3968.150,5318.1200,222.9650
...,...,...,...,...,...,...,...,...,...,...
543,9946843,MSC NOA ARIELA,36308.00,2023-07-24,8216.699,0.000,580.1200,6303.370,2303.4290,190.0200
544,9946855,MSC VALENTINA,16383.90,2023-10-16,4450.490,0.000,244.3210,3689.101,848.0300,157.6800
545,9947110,MSC CHIYO,54155.15,2023-06-08,13617.680,0.000,349.9800,10832.730,2655.5200,479.4100
546,9947122,MSC VIVIENNE,33226.40,2023-08-22,7773.610,279.380,135.7500,6261.610,1605.9500,321.1800
547,9947134,MSC GIUSY,13297.60,2023-09-27,3455.400,154.200,308.4000,2514.100,1078.6000,325.3000

import pandas as pd

# Assuming 'fuel_imodcs' is your DataFrame containing fuel data
fuel_lim['DateTimeUtc'] = pd.to_datetime(fuel_lim['DateTimeUtc'])

# Assigning a unique number to each date within each vessel's data
fuel_lim['Days_running_limasol'] = fuel_lim.groupby('ImoNumber').cumcount() + 1

# Modifying the assigned day numbers to ensure they don't exceed 365
fuel_lim['Days_running_limasol'] = fuel_lim['Days_running_limasol'].apply(lambda x: x % 365 if x <= 365 else x % 365 + 1)

# Grouping by 'IMO' and summing the modified assigned numbers to calculate days run
grouped_dates_lim = fuel_lim.groupby('ImoNumber')['Days_running_limasol'].agg(Days_running_limasol='max')
grouped_dates_lim['Lim_missing_days'] = 365 - grouped_dates_lim['Days_running_limasol']

grouped_dates_lim = grouped_dates_lim.reset_index()

grouped_dates_lim.head(7)

In [73]:
import pandas as pd

# Assuming 'fuel_lim' is your DataFrame containing fuel data
fuel_lim['DateTimeUtc'] = pd.to_datetime(fuel_lim['DateTimeUtc'])

# Dropping duplicate rows based on 'ImoNumber' and 'DateTimeUtc' columns
fuel_lim.drop_duplicates(subset=['ImoNumber', 'DateTimeUtc'], inplace=True)

# Assigning a unique number to each date within each vessel's data
fuel_lim['Days_running_limasol'] = fuel_lim.groupby('ImoNumber').cumcount() + 1

# Modifying the assigned day numbers to ensure they don't exceed 365
fuel_lim['Days_running_limasol'] = fuel_lim['Days_running_limasol'].apply(lambda x: x % 365 if x <= 365 else x % 365 + 1)

# Grouping by 'ImoNumber' and summing the modified assigned numbers to calculate days run
grouped_dates = fuel_lim.groupby('ImoNumber')['Days_running_limasol'].agg(Days_running_limasol='max')

# Calculating the count of missing days for each vessel
grouped_dates['Missing_days_limasol'] = 365 - grouped_dates['Days_running_limasol']

# Extracting count of unique dates for each ImoNumber
count_unique_dates_per_imo = fuel_lim.groupby('ImoNumber')['DateTimeUtc'].nunique().reset_index()
count_unique_dates_per_imo.columns = ['ImoNumber', 'Count_Unique_Dates']

# Merging the two DataFrames on 'ImoNumber'
merged_data_lim = pd.merge(grouped_dates, count_unique_dates_per_imo, on='ImoNumber')

merged_data_lim.head(7)

C:\Users\akshaya\AppData\Local\Temp\ipykernel_380\2118210751.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_lim['DateTimeUtc'] = pd.to_datetime(fuel_lim['DateTimeUtc'])
C:\Users\akshaya\AppData\Local\Temp\ipykernel_380\2118210751.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_lim.drop_duplicates(subset=['ImoNumber', 'DateTimeUtc'], inplace=True)
C:\Users\akshaya\AppData\Local\Temp\ipykernel_380\2118210751.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_lim['Days_running_limasol'] = fuel_lim.groupby('ImoNumber').cumcount() + 1
C:\Users\akshaya\AppData\Local\Temp\ipykernel_380\2118210751.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_lim['Days_running_limasol'] = fuel_lim['Days_running_limasol'].apply(lambda x: x % 365 if x <= 365 else x % 365 + 1)

  ImoNumber  Days_running_limasol  Missing_days_limasol  Count_Unique_Dates
0   7602120                   270                    95                 270
1   7826790                   360                     5                 360
2   8201624                   364                     1                 365
3   8201636                   364                     1                 365
4   8201648                   364                     1                 365
5   8413875                   363                     2                 363
6   8413887                   152                   213                 152

In [74]:
# Merging 'grouped_dates' DataFrame with 'fuel_imo_grouped_df' on the 'IMO' column
fuel_lim_grouped_df = pd.merge(fuel_lim_grouped, merged_data_lim, on='ImoNumber', how='left')

fuel_lim_grouped_df.head(7)

,ImoNumber,vName,Distance_lim,DateTimeUtc,Total_HS,Total_LS,Total_ULS,Total_ME_lima,Total_AUX_lima,Total_Boiler_lima,Days_running_limasol,Missing_days_limasol,Count_Unique_Dates
0,7602120,MSC AURELIA,5488.50,2023-02-02,0.0,0.0000,1338.9080,395.0700,910.5920,33.2460,270,95,270
1,7826790,GNV AZZURRA,24559.93,2023-01-01,0.0,7247.2600,2867.0300,3651.3400,6125.7700,337.1800,360,5,360
2,8201624,MSC IRIS,55148.10,2023-01-01,0.0,8423.2760,1467.8254,4211.9380,5513.8237,165.3397,364,1,365
3,8201636,MSC MALIN,61608.90,2023-01-01,0.0,7487.8800,1202.2630,3753.6400,4750.8730,185.6300,364,1,365
4,8201648,MSC EYRA,60307.10,2023-01-01,0.0,7936.4000,1572.8350,3968.1500,5318.1200,222.9650,364,1,365
5,8413875,MSC GABRIELLA,31747.36,2023-01-01,0.0,3555.2948,1123.9693,1777.7714,2752.3917,149.1010,363,2,363
6,8413887,MSC LUCIA,20076.15,2023-01-01,0.0,2505.2600,594.7700,1310.2300,1666.7400,123.0600,152,213,152

In [75]:
fuel_lim_grouped_df=fuel_lim_grouped_df[['ImoNumber','vName',"DateTimeUtc",'Days_running_limasol','Missing_days_limasol','Distance_lim',"Total_HS","Total_LS","Total_ULS","Total_ME_lima","Total_AUX_lima","Total_Boiler_lima"]]

In [76]:
fuel_imo_grouped_df=fuel_imo_grouped_df[["IMO",'Date_UTC','Days_running_imodcs','Missing_days_imodcs','Distance','ME_Consumption_HFO','ME_Consumption_LFO','AE_Consumption_HFO','AE_Consumption_LFO','Boiler_Consumption_HFO','Boiler_Consumption_LFO','MGO_MDO','Total_ME','Total_AE','Total_Boiler']]

In [77]:
result_df= fuel_imo_grouped_df.merge(fuel_lim_grouped_df, left_on=['IMO'], right_on=['ImoNumber'], how='inner')

result_df

,IMO,Date_UTC,Days_running_imodcs,Missing_days_imodcs,Distance,ME_Consumption_HFO,ME_Consumption_LFO,AE_Consumption_HFO,AE_Consumption_LFO,Boiler_Consumption_HFO,...,DateTimeUtc,Days_running_limasol,Missing_days_limasol,Distance_lim,Total_HS,Total_LS,Total_ULS,Total_ME_lima,Total_AUX_lima,Total_Boiler_lima
0,7602120,2023-01-01,364,1,7148.25,0.00,0.00,0.00,0.00,0.00,...,2023-02-02,270,95,5488.50,0.000,0.000,1338.9080,395.070,910.5920,33.2460
1,7826790,2023-01-01,364,1,25245.83,0.00,3707.64,0.00,0.00,0.00,...,2023-01-01,360,5,24559.93,0.000,7247.260,2867.0300,3651.340,6125.7700,337.1800
2,8201624,2023-01-01,364,1,55148.10,0.00,4211.27,0.00,3.74,0.00,...,2023-01-01,364,1,55148.10,0.000,8423.276,1467.8254,4211.938,5513.8237,165.3397
3,8201636,2023-01-01,364,1,61608.90,0.00,3743.94,0.00,0.00,0.00,...,2023-01-01,364,1,61608.90,0.000,7487.880,1202.2630,3753.640,4750.8730,185.6300
4,8201648,2023-01-01,364,1,60307.10,0.00,3968.15,0.00,0.00,0.00,...,2023-01-01,364,1,60307.10,0.000,7936.400,1572.8350,3968.150,5318.1200,222.9650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
543,9946843,2023-07-24,159,206,36308.00,5904.27,0.00,2141.26,0.00,171.17,...,2023-07-24,161,204,36308.00,8216.699,0.000,580.1200,6303.370,2303.4290,190.0200
544,9946855,2023-10-16,75,290,16383.90,3639.76,0.00,714.33,0.00,96.40,...,2023-10-16,77,288,16383.90,4450.490,0.000,244.3210,3689.101,848.0300,157.6800
545,9947110,2023-06-08,204,161,54155.15,10664.63,0.00,2526.95,0.00,426.10,...,2023-06-08,205,160,54155.15,13617.680,0.000,349.9800,10832.730,2655.5200,479.4100
546,9947122,2023-08-22,132,233,33226.40,6198.71,40.60,1482.10,50.40,92.80,...,2023-08-22,132,233,33226.40,7773.610,279.380,135.7500,6261.610,1605.9500,321.1800
547,9947134,2023-09-27,96,269,13297.60,2449.20,43.40,862.50,0.00,143.70,...,2023-09-27,96,269,13297.60,3455.400,154.200,308.4000,2514.100,1078.6000,325.3000

In [78]:
result_df['Diff_dist']=result_df['Distance_lim']-result_df['Distance']
result_df['Diff_ME']=result_df['Total_ME_lima']-result_df['Total_ME']
result_df['Diff_AUX']=result_df['Total_AUX_lima']-result_df['Total_AE']
result_df['Diff_Boiler']=result_df['Total_Boiler_lima']-result_df['Total_Boiler']

In [79]:
result_df.columns.to_list()

['IMO',
 'Date_UTC',
 'Days_running_imodcs',
 'Missing_days_imodcs',
 'Distance',
 'ME_Consumption_HFO',
 'ME_Consumption_LFO',
 'AE_Consumption_HFO',
 'AE_Consumption_LFO',
 'Boiler_Consumption_HFO',
 'Boiler_Consumption_LFO',
 'MGO_MDO',
 'Total_ME',
 'Total_AE',
 'Total_Boiler',
 'ImoNumber',
 'vName',
 'DateTimeUtc',
 'Days_running_limasol',
 'Missing_days_limasol',
 'Distance_lim',
 'Total_HS',
 'Total_LS',
 'Total_ULS',
 'Total_ME_lima',
 'Total_AUX_lima',
 'Total_Boiler_lima',
 'Diff_dist',
 'Diff_ME',
 'Diff_AUX',
 'Diff_Boiler']

In [80]:
result_dc=result_df[['IMO','vName','DateTimeUtc','Days_running_imodcs','Missing_days_imodcs','Days_running_limasol','Missing_days_limasol','Distance','Distance_lim','Diff_dist','Total_ME','Total_ME_lima','Diff_ME','Total_AE','Total_AUX_lima','Diff_AUX','Total_Boiler','Total_Boiler_lima','Diff_Boiler']]

In [81]:
result_dc.to_csv('result_dc_all- 2023.csv')

In [82]:
result=result_df[['IMO','vName','DateTimeUtc','Days_running_imodcs','Missing_days_imodcs','Days_running_limasol','Missing_days_limasol','Distance','Distance_lim',
'Diff_dist','ME_Consumption_HFO','ME_Consumption_LFO','AE_Consumption_HFO','AE_Consumption_LFO','Boiler_Consumption_HFO','Boiler_Consumption_LFO','MGO_MDO','Total_ME','Total_AE','Total_Boiler','Total_HS',
 'Total_LS','Total_ULS','Total_ME_lima','Total_AUX_lima','Total_Boiler_lima','Diff_ME','Diff_AUX','Diff_Boiler']]

In [83]:
result.to_csv('result_all- 2023.csv')