# IMPORT DATA

In [1]:
import pandas as pd

In [3]:
imo=pd.read_excel('MRV - IMO DCS Data 2022.xlsx')
imo

,IMO,Date_UTC,Time_UTC,Voyage_From,Voyage_To,Voyage_Number,check,Service,Latitude_Degree,Latitude_Minutes,...,Boiler_Consumption_MGO,Boiler_Consumption_MDO,Boiler_Consumption_LNG,HFO_ROB,LFO_ROB,MGO_ROB,MDO_ROB,LNG_ROB,Offhire_Reasons,Unnamed: 49
0,9235581,2022-01-01,02:00:00,NaN,NaN,KQ150A,9.235581e+11,PANDA,18.0,52.0,...,0.00,0.0,0.0,1428.51,327.70,380.88,0.0,0.0,NaN,NaN
1,9235581,2022-01-02,02:00:00,NaN,NaN,KQ150A,9.235581e+11,PANDA,23.0,22.0,...,0.00,0.0,0.0,1381.11,327.70,380.88,0.0,0.0,NaN,NaN
2,9235581,2022-01-03,02:00:00,NaN,NaN,KQ150A,9.235581e+11,PANDA,26.0,29.0,...,0.00,0.0,0.0,1349.11,327.70,380.88,0.0,0.0,NaN,NaN
3,9235581,2022-01-03,05:30:00,NaN,NaN,KQ150A,9.235581e+11,PANDA,26.0,27.0,...,0.00,0.0,0.0,1347.31,327.70,380.88,0.0,0.0,NaN,NaN
4,9235581,2022-01-03,11:54:00,CNYTN,AUBNE,KQ150A,9.235581e+11,PANDA,26.0,27.0,...,0.00,0.0,0.0,1340.01,327.70,380.88,0.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293097,9235610,2022-12-29,12:00:00,NaN,NaN,RL252A,9.235610e+10,NWC TO/FROM PORTBURY GREENOCK,53.0,30.0,...,0.28,0.0,0.0,0.00,275.31,133.09,0.0,0.0,NaN,NaN
293098,9235610,2022-12-30,01:30:00,GBLIV,NaN,RL252R,9.235610e+11,NWC TO/FROM PORTBURY GREENOCK,53.0,30.0,...,0.40,0.0,0.0,0.00,275.23,132.23,0.0,0.0,NaN,NaN
293099,9235610,2022-12-30,04:42:00,NaN,NaN,RL252R,9.235610e+11,NWC TO/FROM PORTBURY GREENOCK,53.0,32.0,...,0.04,0.0,0.0,0.00,273.63,132.00,0.0,0.0,NaN,NaN
293100,9235610,2022-12-30,12:00:00,NaN,NaN,RL252R,9.235610e+11,NWC TO/FROM PORTBURY GREENOCK,53.0,33.0,...,0.08,0.0,0.0,0.00,269.98,131.92,0.0,0.0,NaN,NaN
293101,9235610,2022-12-31,12:00:00,NaN,NaN,RL252R,9.235610e+11,NWC TO/FROM PORTBURY GREENOCK,51.0,36.0,...,0.12,0.0,0.0,0.00,257.98,131.80,0.0,0.0,NaN,NaN

In [4]:
lim=pd.read_csv('Cleaned 2022.csv')
lim

C:\Users\akshaya\AppData\Local\Temp\ipykernel_111620\362373408.py:1: DtypeWarning: Columns (63,64,150) have mixed types. Specify dtype option on import or set low_memory=False.
  lim=pd.read_csv('Cleaned 2022.csv')

,Unnamed: 0,MessagesId,ImoNumber,vName,MessageType,DateTimeLt,DateTimeUtc,Latitude,Longitude,CargoMT,...,Bdn number,Rob actual sludge,Rob actual bilge,Qty sludge disposed,Steaming time m/e lng,Reefer power consumption,Tanktainer min request,Comments,Template version,TANKTAINER ROB
0,195574,4615891,7826790,GNV AZZURRA,EOSP,2022-08-21 20:36:00+01:00,2022-08-21 19:36:00,4116N,01925E,492.0,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
1,200875,4615898,7826790,GNV AZZURRA,EOSP,2022-08-27 18:54:00+01:00,2022-08-27 17:54:00,4116N,01925E,0.0,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
2,208384,4615895,7826790,GNV AZZURRA,EOSP,2022-09-05 07:42:00+01:00,2022-09-05 06:42:00,4110N,01650E,582.0,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
3,251964,4615893,7826790,GNV AZZURRA,Port Noon,2022-10-23 12:00:00+01:00,2022-10-23 11:00:00,NaN,NaN,582.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,255639,4615900,7826790,GNV AZZURRA,Port Noon,2022-10-27 12:00:00+01:00,2022-10-27 11:00:00,NaN,NaN,582.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317068,315110,4500198,9927263,MSC AAYA,Sailing,2022-12-30 04:54:00+08:00,2022-12-29 20:54:00,NaN,NaN,35963.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
317069,315139,4500473,9927263,MSC AAYA,COSP,2022-12-30 06:18:00+08:00,2022-12-29 22:18:00,3600N,12021E,35963.0,...,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
317070,315394,4500589,9927263,MSC AAYA,Noon,2022-12-30 12:00:00+08:00,2022-12-30 04:00:00,3503N,12130E,35963.0,...,NaN,NaN,NaN,NaN,0.0,11.6,NaN,NaN,NaN,NaN
317071,316346,4502149,9927263,MSC AAYA,EOSP,2022-12-31 12:00:00+08:00,2022-12-31 04:00:00,3036N,12316E,35963.0,...,NaN,NaN,NaN,NaN,0.0,50.0,NaN,NaN,NaN,NaN
317072,316353,4502205,9927263,MSC AAYA,Delay,2022-12-31 12:30:00+08:00,2022-12-31 04:30:00,3035N,12311E,35963.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN

In [5]:
imo.shape

(293102, 50)

In [6]:
lim.shape

(317073, 161)

In [7]:
imo.columns.to_list()

['IMO',
 'Date_UTC',
 'Time_UTC',
 'Voyage_From',
 'Voyage_To',
 'Voyage_Number',
 'check',
 'Service',
 'Latitude_Degree',
 'Latitude_Minutes',
 'Latitude_North_South',
 'Longitude_Degree',
 'Longitude_Minutes',
 'Longitude_East_West',
 'Wind_Dir_Degree',
 'Wind_Force_Kn',
 'Wind_Force_Bft',
 'Event',
 'Time_Since_Previous_Report',
 'Time_Elapsed_Sailing',
 'Time_Elapsed_Maneuvering',
 'Time_Elapsed_Waiting',
 'Time_Elapsed_Anchoring',
 'Distance',
 'Cargo_Mt',
 'Reefer_40_Chilled',
 'Reefer_40_Frozen',
 'Passengers',
 'ME_Consumption_HFO',
 'ME_Consumption_LFO',
 'ME_Consumption_MGO',
 'ME_Consumption_MDO',
 'ME_Consumption_LNG',
 'AE_Consumption_HFO',
 'AE_Consumption_LFO',
 'AE_Consumption_MGO',
 'AE_Consumption_MDO',
 'AE_Consumption_LNG',
 'Boiler_Consumption_HFO',
 'Boiler_Consumption_LFO',
 'Boiler_Consumption_MGO',
 'Boiler_Consumption_MDO',
 'Boiler_Consumption_LNG',
 'HFO_ROB',
 'LFO_ROB',
 'MGO_ROB',
 'MDO_ROB',
 'LNG_ROB',
 'Offhire_Reasons',
 'Unnamed: 49']

# IMO CHECKING

In [8]:
imo_unique_count= len(set(imo["IMO"]))
imo_unique_count

471

In [9]:
lim_unique_count= len(set(lim["ImoNumber"]))
lim_unique_count

469

In [10]:
imo_unique_missing=set(imo["IMO"])
imo_unique_missing

{7602120,
 7826790,
 8201624,
 8201636,
 8201648,
 8413875,
 8413887,
 8420892,
 8420907,
 8505836,
 8509375,
 8509387,
 8512891,
 8512906,
 8521402,
 8608200,
 8616520,
 8618293,
 8712520,
 8714205,
 8715857,
 8715869,
 8715871,
 8913411,
 8913423,
 8913447,
 8917778,
 8918057,
 8918954,
 8918966,
 8918978,
 8918980,
 9000742,
 9004231,
 9008574,
 9008603,
 9036002,
 9038907,
 9039250,
 9043756,
 9051478,
 9051492,
 9051507,
 9057173,
 9060649,
 9062984,
 9062996,
 9064748,
 9064750,
 9067544,
 9074042,
 9084607,
 9102710,
 9102722,
 9102746,
 9103685,
 9108398,
 9110377,
 9110389,
 9110391,
 9110975,
 9113446,
 9116369,
 9120853,
 9123154,
 9123166,
 9123221,
 9124366,
 9124512,
 9127021,
 9127540,
 9134490,
 9135638,
 9138783,
 9139086,
 9139505,
 9141285,
 9141297,
 9143879,
 9144134,
 9146479,
 9147071,
 9147227,
 9149328,
 9150080,
 9152856,
 9154191,
 9154206,
 9154220,
 9155107,
 9160920,
 9160982,
 9161297,
 9162277,
 9162631,
 9162643,
 9163192,
 9163207,
 9166651,
 9166778,
 9166780,
 9169029,
 9169031,
 9169043,
 9169055,
 9169067,
 9169122,
 9180190,
 9180205,
 9180968,
 9181651,
 9181663,
 9181675,
 9188219,
 9189366,
 9190092,
 9190119,
 9193680,
 9193719,
 9194866,
 9196838,
 9196864,
 9197545,
 9200677,
 9200689,
 9203538,
 9203904,
 9210050,
 9210062,
 9210086,
 9210098,
 9215892,
 9217565,
 9219393,
 9220328,
 9221059,
 9222106,
 9222120,
 9222302,
 9224049,
 9224051,
 9224348,
 9224946,
 9225249,
 9225251,
 9226932,
 9227285,
 9227297,
 9227302,
 9227314,
 9227326,
 9227338,
 9227340,
 9228576,
 9229300,
 9229312,
 9230775,
 9231119,
 9231248,
 9231250,
 9231262,
 9231779,
 9231810,
 9231822,
 9232395,
 9232462,
 9232632,
 9232644,
 9232656,
 9232761,
 9232773,
 9232890,
 9235402,
 9235581,
 9235608,
 9235610,
 9236212,
 9236224,
 9236444,
 9236585,
 9236688,
 9236690,
 9237151,
 9237371,
 9238739,
 9238741,
 9238789,
 9238882,
 9239733,
 9239903,
 9240328,
 9240873,
 9241451,
 9241463,
 9241475,
 9242625,
 9242637,
 9242651,
 9243239,
 9243241,
 9243394,
 9243409,
 9244881,
 9246566,
 9248928,
 9250983,
 9251688,
 9251690,
 9253014,
 9253038,
 9256315,
 9256327,
 9259381,
 9259393,
 9261815,
 9261827,
 9262546,
 9262560,
 9263332,
 9263344,
 9267637,
 9267649,
 9270828,
 9275036,
 9275373,
 9275397,
 9278143,
 9278155,
 9280861,
 9281267,
 9282259,
 9282261,
 9285665,
 9285691,
 9286231,
 9286267,
 9287792,
 9287900,
 9287924,
 9289051,
 9289087,
 9289099,
 9289544,
 9289960,
 9289972,
 9290402,
 9290426,
 9292175,
 9293167,
 9293179,
 9293442,
 9293777,
 9294989,
 9294991,
 9295165,
 9295177,
 9295397,
 9297864,
 9297876,
 9299525,
 9299537,
 9301328,
 9301330,
 9301483,
 9301550,
 9301990,
 9302085,
 9302619,
 9302621,
 9302633,
 9304459,
 9304746,
 9305001,
 9305013,
 9305477,
 9305489,
 9305506,
 9306263,
 9306275,
 9307267,
 9307839,
 9308584,
 9308601,
 9308625,
 9309289,
 9309411,
 9309447,
 9309459,
 9313943,
 9313967,
 9315006,
 9315018,
 9315379,
 9315381,
 9315836,
 9315915,
 9316347,
 9316359,
 9316361,
 9316373,
 9317925,
 9317937,
 9318046,
 9318058,
 9318187,
 9318773,
 9319600,
 9322011,
 9323041,
 9326768,
 9326823,
 9326940,
 9326964,
 9327683,
 9327798,
 9327803,
 9330226,
 9330238,
 9330240,
 9330264,
 9332729,
 9334349,
 9334832,
 9334844,
 9336165,
 9336359,
 9337444,
 9341122,
 9344564,
 9346017,
 9347762,
 9347803,
 9347970,
 9350317,
 9351579,
 9354363,
 9354416,
 9357107,
 9358905,
 9360271,
 9360283,
 9365984,
 9366421,
 9369734,
 9369758,
 9374571,
 9374595,
 9376141,
 9383223,
 9392561,
 9393022,
 9393307,
 9393319,
 9393321,
 9398216,
 9398228,
 9401166,
 9401685,
 9401776,
 9403396,
 9403437,
 9408774,
 9415296,
 9419644,
 9426817,
 9433157,
 9434462,
 9435820,
 9436472,
 9439735,
 9440306,
 9449687,
 9449869,
 9453298,
 9456965,
 9463035,
 9463047,
 9463059,
 9463205,
 9463281,
 9465241,
 9465253,
 9465265,
 9465277,
 9465306,
 9465318,
 9466960,
 9467445,
 9471226,
 9471238,
 9477610,
 9491616,
 9499010,
 9502908,
 9502960,
 9503732,
 9618276,
 9618288,
 9619452,
 9622007,
 9625932,
 9625944,
 9625970,
 9631876,
 9695028,
 9702065,
 9702077,
 9702089,
 9702091,
 9702106,
 9702261,
 9702273,
 9704960,
 9704972,
 9704984,
 9704996,
 9705005,
 9706310,
 9710426,
 9710438,
 9720196,
 9720201,
 9720287,
 9720457,
 9720471,
 9720483,
 9720495,
 9720500,
 9720512,
 9720524,
 9724049,
 9735206,
 9735218,
 9745653,
 9756729,
 9756731,
 9770737,
 9770749,
 9770751,
 9770763,
 9778076,
 9778088,
 9778090,
 9778105,
 9778117,
 9785445,
 9785457,
 9785469,
 9785471,
 9785483,
 9793947,
 9839260,
 9839272,
 9839284,
 9839296,
 9839301,
 9842061,
 9842073,
 9842085,
 9842097,
 9842102,
 9857157,
 9857169,
 9857171,
 9857183,
 9896983,
 9896995,
 9908047,
 9908059,
 9927251,
 9927263}

In [11]:
lim_unique_missing=set(lim['ImoNumber'])
lim_unique_missing

{7826790,
 8201624,
 8201636,
 8201648,
 8413875,
 8413887,
 8420892,
 8420907,
 8505836,
 8509375,
 8509387,
 8512891,
 8512906,
 8521397,
 8521402,
 8608200,
 8616520,
 8618293,
 8714205,
 8715857,
 8715869,
 8715871,
 8913411,
 8913423,
 8913447,
 8917778,
 8918057,
 8918954,
 8918966,
 8918978,
 8918980,
 9000742,
 9004231,
 9008574,
 9008603,
 9036002,
 9038907,
 9039250,
 9043756,
 9051478,
 9051492,
 9051507,
 9057173,
 9060649,
 9062984,
 9062996,
 9064748,
 9064750,
 9067544,
 9074042,
 9084607,
 9102710,
 9102722,
 9102746,
 9103685,
 9108398,
 9110377,
 9110389,
 9110391,
 9110975,
 9113446,
 9116369,
 9120853,
 9123154,
 9123166,
 9123221,
 9124366,
 9124512,
 9127021,
 9127540,
 9134490,
 9135638,
 9138783,
 9139086,
 9139505,
 9141285,
 9141297,
 9143879,
 9144134,
 9146479,
 9147071,
 9147227,
 9149328,
 9152856,
 9154191,
 9154206,
 9154220,
 9155107,
 9160982,
 9161297,
 9162277,
 9162631,
 9162643,
 9163192,
 9163207,
 9166651,
 9166778,
 9166780,
 9169029,
 9169031,
 9169043,
 9169055,
 9169067,
 9169122,
 9180190,
 9180205,
 9180968,
 9181651,
 9181663,
 9181675,
 9188219,
 9189366,
 9190092,
 9190119,
 9193680,
 9193719,
 9194866,
 9196838,
 9196864,
 9197545,
 9200677,
 9200689,
 9203538,
 9203904,
 9210050,
 9210062,
 9210086,
 9210098,
 9215672,
 9215892,
 9217565,
 9219393,
 9220328,
 9221059,
 9222106,
 9222120,
 9222302,
 9224049,
 9224051,
 9224348,
 9224946,
 9225249,
 9225251,
 9226932,
 9227285,
 9227297,
 9227302,
 9227314,
 9227326,
 9227338,
 9227340,
 9228576,
 9229300,
 9229312,
 9230775,
 9231119,
 9231248,
 9231250,
 9231262,
 9231779,
 9231810,
 9231822,
 9232395,
 9232462,
 9232632,
 9232644,
 9232656,
 9232761,
 9232773,
 9232890,
 9235402,
 9235581,
 9235608,
 9235610,
 9236212,
 9236224,
 9236444,
 9236585,
 9236688,
 9236690,
 9237151,
 9238739,
 9238741,
 9238789,
 9238882,
 9239733,
 9239903,
 9240328,
 9240873,
 9241451,
 9241463,
 9241475,
 9242625,
 9242637,
 9242651,
 9243239,
 9243241,
 9243394,
 9243409,
 9244881,
 9248928,
 9250983,
 9251688,
 9251690,
 9253014,
 9253038,
 9256315,
 9256327,
 9256365,
 9259381,
 9259393,
 9261815,
 9261827,
 9262546,
 9262560,
 9263332,
 9263344,
 9267637,
 9267649,
 9270828,
 9275036,
 9275373,
 9275397,
 9278143,
 9278155,
 9280861,
 9281267,
 9282259,
 9282261,
 9285665,
 9285691,
 9286231,
 9286267,
 9287900,
 9287924,
 9289051,
 9289087,
 9289099,
 9289544,
 9289960,
 9289972,
 9290402,
 9290426,
 9292175,
 9293167,
 9293179,
 9293442,
 9293777,
 9294824,
 9294989,
 9294991,
 9295165,
 9295177,
 9295397,
 9297864,
 9297876,
 9299525,
 9299537,
 9301328,
 9301330,
 9301483,
 9301550,
 9301990,
 9302085,
 9302619,
 9302621,
 9302633,
 9304459,
 9304746,
 9305001,
 9305013,
 9305477,
 9305489,
 9305506,
 9306263,
 9306275,
 9307267,
 9307839,
 9308584,
 9308601,
 9308625,
 9309289,
 9309411,
 9309447,
 9309459,
 9313943,
 9313967,
 9315379,
 9315381,
 9315836,
 9315886,
 9315915,
 9316347,
 9316359,
 9316361,
 9316373,
 9317925,
 9317937,
 9318046,
 9318058,
 9318187,
 9318773,
 9319600,
 9322011,
 9323041,
 9326768,
 9326823,
 9327683,
 9327798,
 9327803,
 9330226,
 9330238,
 9330240,
 9330264,
 9332729,
 9334349,
 9334832,
 9334844,
 9336165,
 9336359,
 9337444,
 9341122,
 9344564,
 9346017,
 9347762,
 9347803,
 9347970,
 9350317,
 9351579,
 9357107,
 9358905,
 9360271,
 9360283,
 9366421,
 9369734,
 9369758,
 9374571,
 9374595,
 9376141,
 9383223,
 9392561,
 9393022,
 9393307,
 9393319,
 9393321,
 9398216,
 9398228,
 9401166,
 9401685,
 9401776,
 9403396,
 9403437,
 9408774,
 9415296,
 9419644,
 9426817,
 9433157,
 9434462,
 9435820,
 9436472,
 9439735,
 9440306,
 9449687,
 9449869,
 9450351,
 9453298,
 9456965,
 9463035,
 9463047,
 9463059,
 9463205,
 9463281,
 9465241,
 9465253,
 9465265,
 9465277,
 9465306,
 9465318,
 9466960,
 9467445,
 9471226,
 9471238,
 9477309,
 9477610,
 9491616,
 9499010,
 9502908,
 9502960,
 9503732,
 9618264,
 9618276,
 9618288,
 9618290,
 9618305,
 9618317,
 9619452,
 9622007,
 9625932,
 9625944,
 9625970,
 9631876,
 9695016,
 9695028,
 9702065,
 9702077,
 9702089,
 9702091,
 9702106,
 9702261,
 9702273,
 9704960,
 9704972,
 9704984,
 9704996,
 9705005,
 9706310,
 9710426,
 9710438,
 9720196,
 9720201,
 9720287,
 9720457,
 9720471,
 9720483,
 9720495,
 9720500,
 9720512,
 9720524,
 9724049,
 9735206,
 9735218,
 9745653,
 9756729,
 9756731,
 9770737,
 9770749,
 9770751,
 9770763,
 9778076,
 9778088,
 9778090,
 9778105,
 9778117,
 9785445,
 9785457,
 9785469,
 9785471,
 9785483,
 9793947,
 9839260,
 9839272,
 9839284,
 9839296,
 9839301,
 9842061,
 9842073,
 9842085,
 9842097,
 9842102,
 9857157,
 9857169,
 9857171,
 9857183,
 9896983,
 9896995,
 9908047,
 9908059,
 9927251,
 9927263}

In [12]:
missing_lim = lim_unique_missing - imo_unique_missing
missing_lim

{8521397,
 9215672,
 9256365,
 9294824,
 9315886,
 9450351,
 9477309,
 9618264,
 9618290,
 9618305,
 9618317,
 9695016}

In [13]:
missing_imo = imo_unique_missing - lim_unique_missing
missing_imo
#imp

{7602120,
 8712520,
 9150080,
 9160920,
 9237371,
 9246566,
 9287792,
 9315006,
 9315018,
 9326940,
 9326964,
 9354363,
 9354416,
 9365984}

In [14]:
print("Missing imo dcs", len(missing_imo))
print("Missing imo limmasol", len(missing_lim))

Missing imo dcs 14
Missing imo limmasol 12

In [15]:
imo_df=imo.copy()
lim_df=lim.copy()

In [16]:
imo_set ={9287792,
 9160920,
 8712520,
 9326940,
 9326964,
 9365984,
 9315006,
 9315018,
 9237371,
 9354363,
 9354416,
 9150080,
 9246566,
 7602120
}

imolst = list(imo_set)

# Create a generator expression to format each IMO number with single quotes
formatted_imolst = ("{}".format(imo) for imo in imolst)

# Convert the generator object to a list
formatted_imolst_list = list(formatted_imolst)

print(formatted_imolst_list)

['9365984', '9150080', '9237371', '9246566', '8712520', '7602120', '9315018', '9287792', '9354416', '9326964', '9160920', '9354363', '9326940', '9315006']

In [17]:
#Comparion between imo dcs with noon data

In [18]:
imo_values_df1 = set(lim['ImoNumber'])
imo_values_df2 = set(imo['IMO'])

# Identify 'imo' values in df1 that are not in df2
imos_not_in_df2 = [imo for imo in imo_values_df1 if imo not in imo_values_df2]

# Identify 'imo' values in df2 that are not in df1
imos_not_in_df1 = [imo for imo in imo_values_df2 if imo not in imo_values_df1]

In [19]:
imos_not_in_df2

[9618264,
 9450351,
 9618290,
 9618305,
 9618317,
 9294824,
 9477309,
 9256365,
 9315886,
 8521397,
 9215672,
 9695016]

In [20]:
imos_not_in_df1

[9287792,
 9160920,
 8712520,
 9326940,
 9326964,
 9365984,
 9315006,
 9315018,
 9237371,
 9354363,
 9354416,
 9150080,
 9246566,
 7602120]

In [21]:
lim_df=lim.copy()
imo_df=imo.copy()

In [22]:
imo_lst=['9618305', '9294824', '9695016', '9618317', '9256365', '9450351', '9315886', '9618290', '9618264', '8521397', '9215672', '9477309']
lim_df = lim_df[~lim_df['ImoNumber'].isin(imo_lst)]
lim_df['ImoNumber'] = lim_df['ImoNumber'].astype(str)
lim_df = lim_df[~lim_df['ImoNumber'].isin(imo_lst)]

In [23]:
imo_lst=['9365984', '9150080', '9237371', '9246566', '8712520', '7602120', '9315018', '9287792', '9354416', '9326964', '9160920', '9354363', '9326940', '9315006']
imo_df = imo_df[~imo_df['IMO'].isin(imo_lst)]
imo_df['IMO'] = imo_df['IMO'].astype(str)
imo_df = imo_df[~imo_df['IMO'].isin(imo_lst)]

In [24]:
print('imo dcs',imo_df['IMO'].nunique())
print('Limmasol',lim_df['ImoNumber'].nunique())

imo dcs 457
Limmasol 457

In [25]:
imo_df['Date_UTC'] = pd.to_datetime(imo_df['Date_UTC'])

# Group by 'imo' and remove duplicates based on combination of 'date_utc', 'time_utc', and 'distance'
imo_df = imo_df.groupby('IMO').apply(lambda x: x.drop_duplicates(subset=['Date_UTC', 'Time_UTC', 'Distance','ME_Consumption_HFO','ME_Consumption_HFO','ME_Consumption_LFO',
 'ME_Consumption_MGO',
 'ME_Consumption_MDO',
 'ME_Consumption_LNG',
 'AE_Consumption_HFO',
 'AE_Consumption_LFO',
 'AE_Consumption_MGO',
 'AE_Consumption_MDO',
 'AE_Consumption_LNG',
 'Boiler_Consumption_HFO',
 'Boiler_Consumption_LFO',
 'Boiler_Consumption_MGO',
 'Boiler_Consumption_MDO',
 'Boiler_Consumption_LNG'])).reset_index(drop=True)

In [26]:
lim_df.columns.to_list()

['Unnamed: 0',
 'MessagesId',
 'ImoNumber',
 'vName',
 'MessageType',
 'DateTimeLt',
 'DateTimeUtc',
 'Latitude',
 'Longitude',
 'CargoMT',
 'CargoTEU',
 'DraftAft',
 'DraftFwd',
 'Speed by gps',
 'Speed by log',
 'FOC_AE_DIS',
 'FOC_AE_DIS_ULS',
 'FOC_AE_DIS_VLS',
 'FOC_AE_LNG',
 'FOC_AE_RES_HS',
 'FOC_AE_RES_ULS',
 'FOC_AE_RES_VLS',
 'FOC_BLR_DIS',
 'FOC_BLR_DIS_ULS',
 'FOC_BLR_DIS_VLS',
 'FOC_BLR_LNG',
 'FOC_BLR_RES_HS',
 'FOC_BLR_RES_ULS',
 'FOC_BLR_RES_VLS',
 'FOC_ME_DIS',
 'FOC_ME_DIS_ULS',
 'FOC_ME_DIS_VLS',
 'FOC_ME_LNG',
 'FOC_ME_RES_HS',
 'FOC_ME_RES_ULS',
 'FOC_ME_RES_VLS',
 'Hours_AE_1',
 'Hours_AE_2',
 'Hours_AE_3',
 'Hours_AE_4',
 'Hours_AE_5',
 'Hours_ME',
 'Hours_SG',
 'Hours_TG',
 'Power_AE_1',
 'Power_AE_2',
 'Power_AE_3',
 'Power_AE_4',
 'Power_AE_5',
 'Power_ME',
 'Power_SG',
 'Power_TG',
 'ROB_DIS',
 'ROB_DIS_ULS',
 'ROB_DIS_VLS',
 'ROB_LNG',
 'ROB_RES_HS',
 'ROB_RES_ULS',
 'ROB_RES_VLS',
 'Port Code',
 'Port Name',
 'ETA Date/Time',
 'Eta date/time',
 'Sludge rob',
 'Sludge min discharge request',
 'Max Residual HS capacity',
 'Max Lng capacity',
 'Min Lng request',
 'Tanktainer number',
 'Port bunkering',
 'Ambient temp',
 'Sw temp',
 'Estimated departure date/time',
 'Shift berth hours',
 'Kwhr total',
 'Hold Ventilation On/Off',
 'Oil Cylinder',
 'Me total revs counter',
 'Number of Tanktainer',
 'ROB fresh water',
 'Reefers positive plugged',
 'Reefers negative plugged',
 'Egcs running time',
 'So2/co2 ratio',
 'Rob tot Sludge',
 'Ballast',
 'Egcs closed loop running time',
 'Egcs open loop running time',
 'Type of delay',
 'Reason',
 'Time hrs. anchor',
 'Time hrs. drift',
 'Time manoeuvring',
 'Manoeuvring miles by gps',
 'Manoeuvring miles by speed log',
 'Displacement',
 'Hold ventilation off',
 'Rob fresh water',
 'TEU Full',
 'TEU Empty',
 'Fresh water supply',
 'ETA Port Code',
 'ETA Port Name',
 'Tanktainer distillates transfd',
 'Bilge removed',
 'Tot sludge removed',
 'Garbage cat a - plastic removed',
 'Garbage cat b - organic removed',
 'Garbage cat c - domestic removed',
 'Garbage cat e - ashes removed',
 'Rob garbage cat a - plastic',
 'Rob garbage cat b - organic',
 'Rob garbage cat c - domestic',
 'Rob garbage cat e - ashes',
 'Egcs wet waste removed',
 'Egcs dry waste removed',
 'Requested speed',
 'Scavenge pressure',
 'Course at Sea',
 'Wind speed',
 'Wind direction',
 'Wave height',
 'Sea state',
 'SEA DIRECTION',
 'Miles by gps',
 'STEAMING TIME M/E RESIDUAL HS',
 'RPM',
 'Slip',
 'Miles speed log',
 'Time change',
 'Time sea',
 'kwhr total',
 'Eca miles',
 'Eca time',
 'Pilot date/time',
 'PIER date/time',
 'ETB Date/Time',
 'Steaming time m/e residual hs',
 'Steaming time m/e residual uls',
 'Steaming time m/e residual vls',
 'Steaming time m/e distillate vls',
 'Steaming time m/e distillate uls',
 'Rpm',
 'Product Name',
 'Physical supplier name',
 'Volume',
 'Quantity',
 'Density at 15Â°C',
 'Viscosity at 40Â°C or 50Â°C',
 'Sulfur content',
 'Bunker Order',
 'Bdn number',
 'Rob actual sludge',
 'Rob actual bilge',
 'Qty sludge disposed',
 'Steaming time m/e lng',
 'Reefer power consumption',
 'Tanktainer min request',
 'Comments',
 'Template version',
 'TANKTAINER ROB']

In [27]:
lim_df['DateTimeUtc'] = pd.to_datetime(lim_df['DateTimeUtc'])

# Group by 'imo' and remove duplicates based on combination of 'date_utc', 'time_utc', and 'distance'
lim_df = lim_df.groupby('ImoNumber').apply(lambda x: x.drop_duplicates(subset=['MessagesId', 'DateTimeUtc','RPM', 'Miles by gps','kwhr total'])).reset_index(drop=True)

In [28]:
imo_df.shape

(280085, 50)

In [29]:
lim_df.shape

(310145, 161)


columns_of_interest = ['IMO','Date_UTC', 'Time_UTC']
duplicates = imo_df.duplicated()
duplicate_rows = imo_df[duplicates]
print(duplicate_rows)
#duplicate_rows.to_csv('D.csv', index=False)
#imo_df.drop_duplicates(inplace=True)

# REPORT TYPE CHCEKING

In [30]:
unique_events_count = imo_df['Event'].nunique()

print("Number of unique events:", unique_events_count)

Number of unique events: 37

In [31]:
unique_event_count = imo_df['Event'].unique()

unique_event_count

array(['Noon (Position) - Port', 'DEPARTURE', 'Begin of sea passage',
       'End of sea passage', 'ARRIVAL', 'Noon (Position) - Sea passage',
       'DELAY', 'PORT NOON', 'COSP', 'EOSP', 'NOON', 'COSP TRANSIT',
       'Noon At Sea', 'End Of Sea Passage', 'Drop Anchor', 'Departure',
       'Begin Of Sea Passage', 'Arrival', 'Heave Anchor',
       'Noon Maneuvering', 'Noon In Port', 'Destination Changed',
       'Begin Stoppage', 'End Stoppage', 'Begin Shifting Berth',
       'Sounding Correction (At Sea)', 'Update ETA/RTA/ETD',
       'Sounding Correction (Maneuveri', 'Sounding Correction (In Port)',
       'Begin Waiting/Drifting', 'End Waiting/Drifting',
       'Drop Anchor Arrival', 'Noon', 'PORTNOON', 'Entering Canal',
       'Bunkering', 'Leaving Canal'], dtype=object)

In [32]:
imo_df

,IMO,Date_UTC,Time_UTC,Voyage_From,Voyage_To,Voyage_Number,check,Service,Latitude_Degree,Latitude_Minutes,...,Boiler_Consumption_MGO,Boiler_Consumption_MDO,Boiler_Consumption_LNG,HFO_ROB,LFO_ROB,MGO_ROB,MDO_ROB,LNG_ROB,Offhire_Reasons,Unnamed: 49
0,7826790,2022-01-01,11:00:00,ITAUG,ITAUG,NaN,7.826790e+07,NaN,37.0,11.0,...,2.0,0.0,0.0,0.0,198.05,115.39,0.0,0.00,NaN,NaN
1,7826790,2022-01-02,11:00:00,ITAUG,ITAUG,NaN,7.826790e+07,NaN,37.0,11.0,...,2.0,0.0,0.0,0.0,198.05,106.53,0.0,0.00,NaN,NaN
2,7826790,2022-01-02,18:54:00,ITAUG,ITMSN,NaN,7.826790e+08,NaN,37.0,11.0,...,0.7,0.0,0.0,0.0,198.05,103.57,0.0,0.00,NaN,NaN
3,7826790,2022-01-02,19:30:00,ITAUG,ITMSN,NaN,7.826790e+08,NaN,37.0,11.0,...,0.0,0.0,0.0,0.0,197.00,103.35,0.0,0.00,NaN,NaN
4,7826790,2022-01-03,05:48:00,ITAUG,ITMSN,NaN,7.826790e+08,NaN,38.0,6.0,...,0.9,0.0,0.0,0.0,190.80,99.06,0.0,0.00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280080,9927263,2022-12-29,20:54:00,CNTAO,NaN,XA252A,9.927263e+11,EXTRA VESSELS,35.0,48.0,...,2.2,0.0,0.0,0.0,1220.80,187.30,0.0,162.50,NaN,NaN
280081,9927263,2022-12-29,22:18:00,NaN,NaN,XA252A,9.927263e+11,EXTRA VESSELS,36.0,0.0,...,0.3,0.0,0.0,0.0,1219.60,186.20,0.0,162.50,NaN,NaN
280082,9927263,2022-12-30,04:00:00,NaN,NaN,XA252A,9.927263e+11,EXTRA VESSELS,35.0,3.0,...,0.4,0.0,0.0,0.0,1206.33,184.00,0.0,162.50,NaN,NaN
280083,9927263,2022-12-31,04:00:00,NaN,NaN,FK252A,9.927263e+11,NEW FALCON SERVICE,30.0,36.0,...,1.7,0.0,0.0,0.0,1167.43,180.60,0.0,155.38,NaN,NaN
280084,9927263,2022-12-31,04:30:00,NaN,NaN,FK252A,9.927263e+11,NEW FALCON SERVICE,30.0,35.0,...,0.2,0.0,0.0,0.0,1166.93,180.40,0.0,155.08,NaN,NaN

# Days

In [33]:
imo_df['Date_UTC'] = pd.to_datetime(imo_df['Date_UTC'])

result = imo_df.groupby('IMO')['Date_UTC'].agg(['min', 'max']).reset_index()

# Calculate number of days
result['min'] = pd.to_datetime(result['min'])
result['max'] = pd.to_datetime(result['max'])
result['Days Count'] = (result['max'] - result['min']).dt.days + 1

missing_dates = []

for _, row in result.iterrows():
    imo_no = row['IMO']
    date_range = pd.date_range(start=row['min'], end=row['max'], freq='D')
    actual_dates = set(imo_df[imo_df['IMO'] == imo_no]['Date_UTC'])
    missing = list(set(date_range) - actual_dates)
    missing_str = [date.strftime('%Y-%m-%d') for date in missing]  # Convert datetime.date objects to string
    missing_dates.append([imo_no, missing_str, len(missing)])


missing_dates_imodcs = pd.DataFrame(missing_dates, columns=['imo', 'Missing Dates', 'Count'])

print(missing_dates_imodcs)

         imo                                      Missing Dates  Count
0    7826790                                                 []      0
1    8201624                                                 []      0
2    8201636                                                 []      0
3    8201648                                                 []      0
4    8413875                                       [2022-10-27]      1
..       ...                                                ...    ...
452  9896995  [2022-09-21, 2022-11-15, 2022-12-08, 2022-08-0...      5
453  9908047                                       [2022-07-07]      1
454  9908059                                                 []      0
455  9927251                                       [2022-10-27]      1
456  9927263                           [2022-12-23, 2022-12-22]      2

[457 rows x 3 columns]

In [34]:
missing_dates_imodcs.to_csv('MIMO.csv')

In [35]:
lim_df['DateTimeUtc'] = pd.to_datetime(lim_df['DateTimeUtc'])

result = lim_df.groupby('ImoNumber')['DateTimeUtc'].agg(['min', 'max']).reset_index()

# Calculate number of days
result['min'] = pd.to_datetime(result['min'])
result['max'] = pd.to_datetime(result['max'])
result['Days Count'] = (result['max'] - result['min']).dt.days + 1

missing_dates = []

for _, row in result.iterrows():
    imo_no = row['ImoNumber']
    date_range = pd.date_range(start=row['min'], end=row['max'], freq='D').date
    actual_dates = set(lim_df[lim_df['ImoNumber'] == imo_no]['DateTimeUtc'].dt.date)
    missing = list(set(date_range) - actual_dates)
    missing_str = [date.strftime('%Y-%m-%d') for date in missing]  # Convert datetime.date objects to string
    missing_dates.append([imo_no, missing_str, len(missing)])


missing_dates_lim = pd.DataFrame(missing_dates, columns=['imo', 'Missing Dates', 'Count'])

missing_dates_lim

         imo                                      Missing Dates  Count
0    7826790  [2022-11-11, 2022-08-29, 2022-10-13, 2022-10-3...     81
1    8201624                                                 []      0
2    8201636                                                 []      0
3    8201648                                                 []      0
4    8413875                                       [2022-10-27]      1
..       ...                                                ...    ...
452  9896995  [2022-09-21, 2022-08-08, 2022-06-25, 2022-11-1...      5
453  9908047                           [2022-03-28, 2022-07-07]      2
454  9908059                                                 []      0
455  9927251                                       [2022-10-27]      1
456  9927263                                       [2022-12-23]      1

[457 rows x 3 columns]

In [36]:
missing_dates_lim.to_csv('MLIM.csv')

In [37]:
imo_df['Date_UTC']= pd.to_datetime(imo_df['Date_UTC']).dt.date
imo_df['Date_UTC']=imo_df['Date_UTC'].astype(str)

In [38]:
lim_df['DateTimeUtc']= pd.to_datetime(lim_df['DateTimeUtc']).dt.date
lim_df['DateTimeUtc']=lim_df['DateTimeUtc'].astype(str)

In [39]:
# Iterate through each row of missing_dates_imo
for _, row in missing_dates_imodcs.iterrows():
    imo_no = row['imo']
    missing_dates = row['Missing Dates']
    
    # Convert missing_dates to datetime objects
    missing_dates = pd.to_datetime(missing_dates)
    
    # Filter out rows with the specified IMO and missing dates
    lim_df = lim_df[~((lim_df['ImoNumber'] == imo_no) & lim_df['DateTimeUtc'].isin(missing_dates))]

In [40]:
# Iterate through each row of missing_dates_imo
for _, row in missing_dates_lim.iterrows():
    imo_no = row['imo']
    missing_dates = row['Missing Dates']
    
    # Convert missing_dates to datetime objects
    missing_dates = pd.to_datetime(missing_dates)
    
    # Filter out rows with the specified IMO and missing dates
    imo_df = imo_df[~((imo_df['IMO'] == imo_no) & imo_df['Date_UTC'].isin(missing_dates))]

In [41]:
imo_df.shape

(280085, 50)

In [42]:
lim_df.shape

(310145, 161)

# Fuel and Distance

In [102]:
imo_df['MGO_MDO']=imo_df[['ME_Consumption_MGO','ME_Consumption_MDO','AE_Consumption_MGO','AE_Consumption_MDO','Boiler_Consumption_MGO','Boiler_Consumption_MDO']].sum(axis=1)

In [103]:
imo_df['Total_ME']=imo_df[['ME_Consumption_HFO','ME_Consumption_LFO','ME_Consumption_MGO','ME_Consumption_MDO']].sum(axis=1)
imo_df['Total_AE']=imo_df[['AE_Consumption_HFO','AE_Consumption_LFO','AE_Consumption_MGO','AE_Consumption_MDO']].sum(axis=1)
imo_df['Total_Boiler']=imo_df[['Boiler_Consumption_HFO','Boiler_Consumption_LFO','Boiler_Consumption_MGO','Boiler_Consumption_MDO']].sum(axis=1)

In [104]:
fuel_imodcs=imo_df[['IMO','Distance','Date_UTC','ME_Consumption_HFO', 'ME_Consumption_LFO','AE_Consumption_HFO','AE_Consumption_LFO',
                    'Boiler_Consumption_HFO','Boiler_Consumption_LFO','MGO_MDO','Total_ME','Total_AE','Total_Boiler'
]]

In [105]:
fuel_imodcs

,IMO,Distance,Date_UTC,ME_Consumption_HFO,ME_Consumption_LFO,AE_Consumption_HFO,AE_Consumption_LFO,Boiler_Consumption_HFO,Boiler_Consumption_LFO,MGO_MDO,Total_ME,Total_AE,Total_Boiler
0,7826790,0.0,2022-01-01,0.0,0.00,0.0,0.0,0.0,0.0,8.86,0.00,6.86,2.0
1,7826790,0.0,2022-01-02,0.0,0.00,0.0,0.0,0.0,0.0,8.86,0.00,6.86,2.0
2,7826790,0.0,2022-01-02,0.0,0.00,0.0,0.0,0.0,0.0,2.96,0.00,2.26,0.7
3,7826790,3.3,2022-01-02,0.0,1.05,0.0,0.0,0.0,0.0,0.22,1.05,0.22,0.0
4,7826790,80.0,2022-01-03,0.0,6.20,0.0,0.0,0.0,0.0,4.29,6.20,3.39,0.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
280080,9927263,0.0,2022-12-29,0.0,0.00,0.0,0.0,0.0,0.0,6.50,0.00,4.30,2.2
280081,9927263,5.0,2022-12-29,0.0,1.20,0.0,0.0,0.0,0.0,1.10,1.20,0.80,0.3
280082,9927263,84.0,2022-12-30,0.0,13.27,0.0,0.0,0.0,0.0,2.20,13.27,1.80,0.4
280083,9927263,294.0,2022-12-31,0.0,38.90,0.0,0.0,0.0,0.0,3.40,38.90,1.70,1.7
280084,9927263,3.0,2022-12-31,0.0,0.50,0.0,0.0,0.0,0.0,0.20,0.50,0.00,0.2

In [106]:
import pandas as pd

# Assuming 'fuel_imodcs' is your DataFrame containing fuel data
fuel_imodcs['Date_UTC'] = pd.to_datetime(fuel_imodcs['Date_UTC'])

# Extracting the month from 'Date_UTC'
fuel_imodcs['month'] = fuel_imodcs['Date_UTC'].dt.month

# Grouping by 'imo' and performing aggregations
grouped_df = fuel_imodcs.groupby('IMO').agg({
    'Date_UTC': 'first',  # Assuming you want the first date in each group
    'Distance': 'sum',
    'ME_Consumption_HFO': 'sum',
    'ME_Consumption_LFO': 'sum',
    'AE_Consumption_HFO': 'sum',
    'AE_Consumption_LFO': 'sum',
    'Boiler_Consumption_HFO': 'sum',
    'Boiler_Consumption_LFO': 'sum',
    'MGO_MDO': 'sum',
    'Total_ME': 'sum',
    'Total_AE': 'sum',
    'Total_Boiler': 'sum'
}).reset_index()

# Sorting the DataFrame by 'imo'
fuel_imo_grouped_df = grouped_df.sort_values(by='IMO')


fuel_imo_grouped_df

C:\Users\akshaya\AppData\Local\Temp\ipykernel_111620\3244407165.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_imodcs['Date_UTC'] = pd.to_datetime(fuel_imodcs['Date_UTC'])
C:\Users\akshaya\AppData\Local\Temp\ipykernel_111620\3244407165.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_imodcs['month'] = fuel_imodcs['Date_UTC'].dt.month

,IMO,Date_UTC,Distance,ME_Consumption_HFO,ME_Consumption_LFO,AE_Consumption_HFO,AE_Consumption_LFO,Boiler_Consumption_HFO,Boiler_Consumption_LFO,MGO_MDO,Total_ME,Total_AE,Total_Boiler
0,7826790,2022-01-01,23379.88,0.00,3497.49,0.00,0.00,0.00,0.10,3326.54,3505.73,2904.96,413.44
1,8201624,2022-01-01,50374.70,0.00,3605.21,0.00,0.00,0.00,0.00,1886.45,4107.95,1224.05,159.66
2,8201636,2022-01-01,51726.65,0.00,3667.44,0.00,0.00,0.00,0.00,1336.50,3699.07,1113.67,191.20
3,8201648,2022-01-01,55481.10,0.00,3872.96,0.00,0.00,0.00,0.00,1265.39,3884.46,1090.35,163.54
4,8413875,2022-01-01,25750.33,0.00,1676.93,0.00,20.70,0.00,5.64,894.17,1776.55,677.88,143.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,9896995,2022-01-01,73266.10,19452.11,0.00,6033.86,0.00,945.87,0.00,165.01,19452.11,6166.32,978.42
453,9908047,2022-03-29,65377.40,0.00,11406.24,0.00,1809.39,0.00,160.43,1133.38,12024.61,2248.30,236.53
454,9908059,2022-06-28,39528.90,0.00,7407.76,0.00,1695.44,0.00,14.68,411.95,7534.81,1859.16,135.86
455,9927251,2022-10-26,15433.30,0.00,2709.53,0.00,233.66,0.00,19.60,306.38,2736.87,483.08,49.22
456,9927263,2022-12-21,854.00,0.00,99.97,0.00,0.00,0.00,0.00,61.60,99.97,33.00,28.60

In [107]:
fuel_imo_grouped_df

,IMO,Date_UTC,Distance,ME_Consumption_HFO,ME_Consumption_LFO,AE_Consumption_HFO,AE_Consumption_LFO,Boiler_Consumption_HFO,Boiler_Consumption_LFO,MGO_MDO,Total_ME,Total_AE,Total_Boiler
0,7826790,2022-01-01,23379.88,0.00,3497.49,0.00,0.00,0.00,0.10,3326.54,3505.73,2904.96,413.44
1,8201624,2022-01-01,50374.70,0.00,3605.21,0.00,0.00,0.00,0.00,1886.45,4107.95,1224.05,159.66
2,8201636,2022-01-01,51726.65,0.00,3667.44,0.00,0.00,0.00,0.00,1336.50,3699.07,1113.67,191.20
3,8201648,2022-01-01,55481.10,0.00,3872.96,0.00,0.00,0.00,0.00,1265.39,3884.46,1090.35,163.54
4,8413875,2022-01-01,25750.33,0.00,1676.93,0.00,20.70,0.00,5.64,894.17,1776.55,677.88,143.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,9896995,2022-01-01,73266.10,19452.11,0.00,6033.86,0.00,945.87,0.00,165.01,19452.11,6166.32,978.42
453,9908047,2022-03-29,65377.40,0.00,11406.24,0.00,1809.39,0.00,160.43,1133.38,12024.61,2248.30,236.53
454,9908059,2022-06-28,39528.90,0.00,7407.76,0.00,1695.44,0.00,14.68,411.95,7534.81,1859.16,135.86
455,9927251,2022-10-26,15433.30,0.00,2709.53,0.00,233.66,0.00,19.60,306.38,2736.87,483.08,49.22
456,9927263,2022-12-21,854.00,0.00,99.97,0.00,0.00,0.00,0.00,61.60,99.97,33.00,28.60

import pandas as pd

# Assuming 'fuel_imodcs' is your DataFrame containing fuel data
fuel_imodcs['Date_UTC'] = pd.to_datetime(fuel_imodcs['Date_UTC'])

# Assigning a unique number to each date within each vessel's data
fuel_imodcs['Days_running_imodcs'] = fuel_imodcs.groupby('IMO').cumcount() + 1

# Modifying the assigned day numbers to ensure they don't exceed 365
fuel_imodcs['Days_running_imodcs'] = fuel_imodcs['Days_running_imodcs'].apply(lambda x: x % 365 if x <= 365 else x % 365 + 1)

# Grouping by 'IMO' and summing the modified assigned numbers to calculate days run
grouped_dates = fuel_imodcs.groupby('IMO')['Days_running_imodcs'].agg(Days_running_imodcs='max')

# Calculating the count of missing days for each vessel
grouped_dates['Missing_days_imodcs'] = 365 - grouped_dates['Days_running_imodcs']

grouped_dates = grouped_dates.reset_index()

grouped_dates.head(7)

In [108]:
import pandas as pd

# Assuming 'fuel_imodcs' is your DataFrame containing fuel data
fuel_imodcs['Date_UTC'] = pd.to_datetime(fuel_imodcs['Date_UTC'])

# Dropping duplicate rows based on 'IMO' and 'Date_UTC' columns
fuel_imodcs.drop_duplicates(subset=['IMO', 'Date_UTC'], inplace=True)

# Assigning a unique number to each date within each vessel's data
fuel_imodcs['Days_running_imodcs'] = fuel_imodcs.groupby('IMO').cumcount() + 1

# Modifying the assigned day numbers to ensure they don't exceed 365
fuel_imodcs['Days_running_imodcs'] = fuel_imodcs['Days_running_imodcs'].apply(lambda x: x % 365 if x <= 365 else x % 365 + 1)

# Grouping by 'IMO' and summing the modified assigned numbers to calculate days run
grouped_dates = fuel_imodcs.groupby('IMO')['Days_running_imodcs'].agg(Days_running_imodcs='max')

# Calculating the count of missing days for each vessel
grouped_dates['Missing_days_imodcs'] = 365 - grouped_dates['Days_running_imodcs']

# Extracting count of unique dates for each IMO
count_unique_dates_per_imo = fuel_imodcs.groupby('IMO')['Date_UTC'].nunique().reset_index()
count_unique_dates_per_imo.columns = ['IMO', 'Count_Unique_Dates']

# Merging the two DataFrames on 'IMO'
merged_data = pd.merge(grouped_dates, count_unique_dates_per_imo, on='IMO')

merged_data.head(7)

C:\Users\akshaya\AppData\Local\Temp\ipykernel_111620\780805684.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_imodcs['Date_UTC'] = pd.to_datetime(fuel_imodcs['Date_UTC'])
C:\Users\akshaya\AppData\Local\Temp\ipykernel_111620\780805684.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_imodcs.drop_duplicates(subset=['IMO', 'Date_UTC'], inplace=True)
C:\Users\akshaya\AppData\Local\Temp\ipykernel_111620\780805684.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_imodcs['Days_running_imodcs'] = fuel_imodcs.groupby('IMO').cumcount() + 1
C:\Users\akshaya\AppData\Local\Temp\ipykernel_111620\780805684.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_imodcs['Days_running_imodcs'] = fuel_imodcs['Days_running_imodcs'].apply(lambda x: x % 365 if x <= 365 else x % 365 + 1)

       IMO  Days_running_imodcs  Missing_days_imodcs  Count_Unique_Dates
0  7826790                  364                    1                 365
1  8201624                  364                    1                 365
2  8201636                  364                    1                 365
3  8201648                  364                    1                 365
4  8413875                  364                    1                 364
5  8413887                  364                    1                 365
6  8420892                  362                    3                 362

In [109]:
merged_data.to_csv("merged_data.csv")

In [110]:
# Merging 'grouped_dates' DataFrame with 'fuel_imo_grouped_df' on the 'IMO' column
fuel_imo_grouped_df = pd.merge(fuel_imo_grouped_df, merged_data, on='IMO', how='left')

fuel_imo_grouped_df.head(7)

,IMO,Date_UTC,Distance,ME_Consumption_HFO,ME_Consumption_LFO,AE_Consumption_HFO,AE_Consumption_LFO,Boiler_Consumption_HFO,Boiler_Consumption_LFO,MGO_MDO,Total_ME,Total_AE,Total_Boiler,Days_running_imodcs,Missing_days_imodcs,Count_Unique_Dates
0,7826790,2022-01-01,23379.88,0.0,3497.49,0.0,0.0,0.0,0.10,3326.54,3505.73,2904.96,413.44,364,1,365
1,8201624,2022-01-01,50374.70,0.0,3605.21,0.0,0.0,0.0,0.00,1886.45,4107.95,1224.05,159.66,364,1,365
2,8201636,2022-01-01,51726.65,0.0,3667.44,0.0,0.0,0.0,0.00,1336.50,3699.07,1113.67,191.20,364,1,365
3,8201648,2022-01-01,55481.10,0.0,3872.96,0.0,0.0,0.0,0.00,1265.39,3884.46,1090.35,163.54,364,1,365
4,8413875,2022-01-01,25750.33,0.0,1676.93,0.0,20.7,0.0,5.64,894.17,1776.55,677.88,143.01,364,1,364
5,8413887,2022-01-01,44881.19,0.0,3206.10,0.0,0.0,0.0,0.00,1431.24,3235.40,1174.96,226.98,364,1,365
6,8420892,2022-01-01,67253.00,0.0,6285.70,0.0,0.0,0.0,0.00,1380.92,6285.70,1194.21,186.71,362,3,362

In [111]:
fuel_imo_grouped_df.to_csv('fuel_grouped_imo_df.csv')

fuel_imo_grouped_df['IMO'] = fuel_imo_grouped_df['IMO'].astype(str)
result_fuel_df = fuel_imo_grouped_df.merge(fuel_imo_grouped_df, left_on=['imo', 'month'], right_on=['IMO', 'month'], how='inner')
print(result_fuel_df)

In [112]:
#result_fuel_df.to_csv('Data comparison.csv')

In [113]:
#lim

In [114]:
lim_df['Distance_lim']= lim_df[['Miles by gps','Manoeuvring miles by gps']].sum(axis=1)
lim_df['ME_hs_lima'] =  lim_df[['FOC_ME_RES_HS']]
lim_df['AUX_hs_lima'] =  lim_df[['FOC_AE_RES_HS']]
lim_df['Boiler_hs_lima'] =  lim_df[['FOC_BLR_RES_HS']]
 
lim_df['ME_ls_lima'] =  lim_df[['FOC_ME_RES_ULS','FOC_ME_RES_VLS']].sum(axis = 1) 
lim_df['AUX_ls_lima'] =  lim_df[['FOC_ME_RES_ULS','FOC_ME_RES_VLS']].sum(axis = 1)  
lim_df['Boiler_ls_lima'] =  lim_df[['FOC_BLR_RES_VLS','FOC_BLR_RES_ULS']] .sum(axis = 1)
 
lim_df['ME_uls_lima'] =  lim_df[['FOC_ME_DIS','FOC_ME_DIS_ULS','FOC_ME_DIS_VLS']].sum(axis = 1) 
lim_df['AUX_uls_lima'] =  lim_df[['FOC_AE_DIS','FOC_AE_DIS_ULS','FOC_AE_DIS_VLS']].sum(axis = 1) 
lim_df['Boiler_uls_lima'] =  lim_df[['FOC_BLR_DIS','FOC_BLR_DIS_ULS','FOC_BLR_DIS_VLS']] .sum(axis = 1)
 
lim_df['Total_ME_lima'] = lim_df[['ME_hs_lima','ME_ls_lima','ME_uls_lima']].sum(axis = 1)   
lim_df['Total_AUX_lima'] = lim_df[['AUX_hs_lima','AUX_ls_lima','AUX_uls_lima']].sum(axis = 1) 
lim_df['Total_Boiler_lima'] = lim_df[['Boiler_hs_lima','Boiler_ls_lima','Boiler_uls_lima']].sum(axis = 1)


lim_df["Total_HS"]=lim_df[['FOC_ME_RES_HS','FOC_AE_RES_HS',"FOC_BLR_RES_HS"]].sum(axis = 1) 
lim_df["Total_LS"]=lim_df[['FOC_ME_RES_ULS','FOC_ME_RES_VLS','FOC_ME_RES_ULS','FOC_ME_RES_VLS','FOC_BLR_RES_VLS','FOC_BLR_RES_ULS']].sum(axis = 1) 
lim_df["Total_ULS"]=lim_df[['FOC_ME_DIS','FOC_ME_DIS_ULS','FOC_ME_DIS_VLS','FOC_AE_DIS','FOC_AE_DIS_ULS','FOC_AE_DIS_VLS','FOC_BLR_DIS','FOC_BLR_DIS_ULS','FOC_BLR_DIS_VLS']].sum(axis = 1)

In [115]:
fuel_lim=lim_df[['ImoNumber','vName','Distance_lim','DateTimeUtc','Total_HS','Total_LS','Total_ULS','Total_ME_lima','Total_AUX_lima','Total_Boiler_lima']]

In [116]:
import pandas as pd

# Selecting specific columns from lim_df
#fuel_lim = lim_df[['ImoNumber', 'vName', 'Miles by gps', 'DateTimeUtc', 'Total_ME_lima', 'Total_AUX_lima', 'Total_Boiler_lima']]

# Convert 'DateTimeUtc' column to datetime
fuel_lim['DateTimeUtc'] = pd.to_datetime(fuel_lim['DateTimeUtc'])

# Extracting the month from 'DateTimeUtc'

# Grouping by 'ImoNumber' and 'month' and aggregating
fuel_lim_grouped = fuel_lim.groupby(['ImoNumber']).agg({
    'vName': 'first',  # Assuming 'vName' doesn't change within a month
    'Distance_lim': 'sum',
    'DateTimeUtc': 'first',
    'Total_HS':'sum',
    'Total_LS':'sum',
    'Total_ULS':'sum',
    'Total_ME_lima': 'sum',
    'Total_AUX_lima': 'sum',
    'Total_Boiler_lima': 'sum'
}).reset_index()


fuel_lim_grouped

C:\Users\akshaya\AppData\Local\Temp\ipykernel_111620\101913375.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_lim['DateTimeUtc'] = pd.to_datetime(fuel_lim['DateTimeUtc'])

,ImoNumber,vName,Distance_lim,DateTimeUtc,Total_HS,Total_LS,Total_ULS,Total_ME_lima,Total_AUX_lima,Total_Boiler_lima
0,7826790,GNV AZZURRA,1024.96,2022-08-21,0.000,261.4000,287.66000,130.7000,383.6100,34.75000
1,8201624,MSC IRIS,50374.70,2022-01-01,0.000,7210.0868,1885.81996,4107.7704,4828.8271,159.30926
2,8201636,MSC MALIN,51726.65,2022-01-01,0.000,7334.8800,1336.49200,3699.0700,4781.1080,191.19400
3,8201648,MSC EYRA,55481.10,2022-01-01,0.000,7745.9260,1265.38200,3884.4630,4963.3060,163.53900
4,8413875,MSC GABRIELLA,25734.33,2022-01-01,0.000,3356.5000,830.86580,1714.4548,2331.0010,141.91000
...,...,...,...,...,...,...,...,...,...,...
452,9896995,MSC AMELIA,72839.10,2022-01-01,26291.304,0.0000,165.01000,19387.3340,6099.7500,969.23000
453,9908047,MSC WASHINGTON,65377.40,2022-03-27,0.000,22972.9200,1133.38600,12024.6100,11845.1560,236.54000
454,9908059,MSC VIRGINIA,39528.90,2022-06-28,0.000,14830.2000,411.95000,7534.8100,7571.4800,135.86000
455,9927251,MSC FATMA,15433.30,2022-10-26,0.000,5438.6600,306.38000,2736.8700,2958.9500,49.22000
456,9927263,MSC AAYA,854.00,2022-12-21,0.000,199.9400,61.60000,99.9700,132.9700,28.60000

import pandas as pd

# Assuming 'fuel_imodcs' is your DataFrame containing fuel data
fuel_lim['DateTimeUtc'] = pd.to_datetime(fuel_lim['DateTimeUtc'])

# Assigning a unique number to each date within each vessel's data
fuel_lim['Days_running_limasol'] = fuel_lim.groupby('ImoNumber').cumcount() + 1

# Modifying the assigned day numbers to ensure they don't exceed 365
fuel_lim['Days_running_limasol'] = fuel_lim['Days_running_limasol'].apply(lambda x: x % 365 if x <= 365 else x % 365 + 1)

# Grouping by 'IMO' and summing the modified assigned numbers to calculate days run
grouped_dates_lim = fuel_lim.groupby('ImoNumber')['Days_running_limasol'].agg(Days_running_limasol='max')
grouped_dates_lim['Lim_missing_days'] = 365 - grouped_dates_lim['Days_running_limasol']

grouped_dates_lim = grouped_dates_lim.reset_index()

grouped_dates_lim.head(7)

In [117]:
import pandas as pd

# Assuming 'fuel_lim' is your DataFrame containing fuel data
fuel_lim['DateTimeUtc'] = pd.to_datetime(fuel_lim['DateTimeUtc'])

# Dropping duplicate rows based on 'ImoNumber' and 'DateTimeUtc' columns
fuel_lim.drop_duplicates(subset=['ImoNumber', 'DateTimeUtc'], inplace=True)

# Assigning a unique number to each date within each vessel's data
fuel_lim['Days_running_limasol'] = fuel_lim.groupby('ImoNumber').cumcount() + 1

# Modifying the assigned day numbers to ensure they don't exceed 365
fuel_lim['Days_running_limasol'] = fuel_lim['Days_running_limasol'].apply(lambda x: x % 365 if x <= 365 else x % 365 + 1)

# Grouping by 'ImoNumber' and summing the modified assigned numbers to calculate days run
grouped_dates = fuel_lim.groupby('ImoNumber')['Days_running_limasol'].agg(Days_running_limasol='max')

# Calculating the count of missing days for each vessel
grouped_dates['Missing_days_limasol'] = 365 - grouped_dates['Days_running_limasol']

# Extracting count of unique dates for each ImoNumber
count_unique_dates_per_imo = fuel_lim.groupby('ImoNumber')['DateTimeUtc'].nunique().reset_index()
count_unique_dates_per_imo.columns = ['ImoNumber', 'Count_Unique_Dates']

# Merging the two DataFrames on 'ImoNumber'
merged_data_lim = pd.merge(grouped_dates, count_unique_dates_per_imo, on='ImoNumber')

merged_data_lim.head(7)

C:\Users\akshaya\AppData\Local\Temp\ipykernel_111620\2118210751.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_lim['DateTimeUtc'] = pd.to_datetime(fuel_lim['DateTimeUtc'])
C:\Users\akshaya\AppData\Local\Temp\ipykernel_111620\2118210751.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_lim.drop_duplicates(subset=['ImoNumber', 'DateTimeUtc'], inplace=True)
C:\Users\akshaya\AppData\Local\Temp\ipykernel_111620\2118210751.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_lim['Days_running_limasol'] = fuel_lim.groupby('ImoNumber').cumcount() + 1
C:\Users\akshaya\AppData\Local\Temp\ipykernel_111620\2118210751.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_lim['Days_running_limasol'] = fuel_lim['Days_running_limasol'].apply(lambda x: x % 365 if x <= 365 else x % 365 + 1)

  ImoNumber  Days_running_limasol  Missing_days_limasol  Count_Unique_Dates
0   7826790                    52                   313                  52
1   8201624                   364                     1                 365
2   8201636                   364                     1                 365
3   8201648                   364                     1                 365
4   8413875                   364                     1                 364
5   8413887                   364                     1                 365
6   8420892                   362                     3                 362

In [118]:
# Merging 'grouped_dates' DataFrame with 'fuel_imo_grouped_df' on the 'IMO' column
fuel_lim_grouped_df = pd.merge(fuel_lim_grouped, merged_data_lim, on='ImoNumber', how='left')

fuel_lim_grouped_df.head(7)

,ImoNumber,vName,Distance_lim,DateTimeUtc,Total_HS,Total_LS,Total_ULS,Total_ME_lima,Total_AUX_lima,Total_Boiler_lima,Days_running_limasol,Missing_days_limasol,Count_Unique_Dates
0,7826790,GNV AZZURRA,1024.96,2022-08-21,0.0,261.4000,287.66000,130.7000,383.6100,34.75000,52,313,52
1,8201624,MSC IRIS,50374.70,2022-01-01,0.0,7210.0868,1885.81996,4107.7704,4828.8271,159.30926,364,1,365
2,8201636,MSC MALIN,51726.65,2022-01-01,0.0,7334.8800,1336.49200,3699.0700,4781.1080,191.19400,364,1,365
3,8201648,MSC EYRA,55481.10,2022-01-01,0.0,7745.9260,1265.38200,3884.4630,4963.3060,163.53900,364,1,365
4,8413875,MSC GABRIELLA,25734.33,2022-01-01,0.0,3356.5000,830.86580,1714.4548,2331.0010,141.91000,364,1,364
5,8413887,MSC LUCIA,44881.19,2022-01-01,0.0,6412.2060,1431.23600,3235.4030,4381.0590,226.98000,364,1,365
6,8420892,MSC CHIARA,67253.00,2022-01-01,0.0,12571.3920,1380.89600,6285.6960,7479.8880,186.70400,362,3,362

In [119]:
fuel_lim_grouped_df=fuel_lim_grouped_df[['ImoNumber','vName',"DateTimeUtc",'Days_running_limasol','Missing_days_limasol','Distance_lim',"Total_HS","Total_LS","Total_ULS","Total_ME_lima","Total_AUX_lima","Total_Boiler_lima"]]

In [120]:
fuel_imo_grouped_df=fuel_imo_grouped_df[["IMO",'Date_UTC','Days_running_imodcs','Missing_days_imodcs','Distance','ME_Consumption_HFO','ME_Consumption_LFO','AE_Consumption_HFO','AE_Consumption_LFO','Boiler_Consumption_HFO','Boiler_Consumption_LFO','MGO_MDO','Total_ME','Total_AE','Total_Boiler']]

In [121]:
result_df= fuel_imo_grouped_df.merge(fuel_lim_grouped_df, left_on=['IMO'], right_on=['ImoNumber'], how='inner')

result_df

,IMO,Date_UTC,Days_running_imodcs,Missing_days_imodcs,Distance,ME_Consumption_HFO,ME_Consumption_LFO,AE_Consumption_HFO,AE_Consumption_LFO,Boiler_Consumption_HFO,...,DateTimeUtc,Days_running_limasol,Missing_days_limasol,Distance_lim,Total_HS,Total_LS,Total_ULS,Total_ME_lima,Total_AUX_lima,Total_Boiler_lima
0,7826790,2022-01-01,364,1,23379.88,0.00,3497.49,0.00,0.00,0.00,...,2022-08-21,52,313,1024.96,0.000,261.4000,287.66000,130.7000,383.6100,34.75000
1,8201624,2022-01-01,364,1,50374.70,0.00,3605.21,0.00,0.00,0.00,...,2022-01-01,364,1,50374.70,0.000,7210.0868,1885.81996,4107.7704,4828.8271,159.30926
2,8201636,2022-01-01,364,1,51726.65,0.00,3667.44,0.00,0.00,0.00,...,2022-01-01,364,1,51726.65,0.000,7334.8800,1336.49200,3699.0700,4781.1080,191.19400
3,8201648,2022-01-01,364,1,55481.10,0.00,3872.96,0.00,0.00,0.00,...,2022-01-01,364,1,55481.10,0.000,7745.9260,1265.38200,3884.4630,4963.3060,163.53900
4,8413875,2022-01-01,364,1,25750.33,0.00,1676.93,0.00,20.70,0.00,...,2022-01-01,364,1,25734.33,0.000,3356.5000,830.86580,1714.4548,2331.0010,141.91000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,9896995,2022-01-01,360,5,73266.10,19452.11,0.00,6033.86,0.00,945.87,...,2022-01-01,360,5,72839.10,26291.304,0.0000,165.01000,19387.3340,6099.7500,969.23000
453,9908047,2022-03-29,277,88,65377.40,0.00,11406.24,0.00,1809.39,0.00,...,2022-03-27,278,87,65377.40,0.000,22972.9200,1133.38600,12024.6100,11845.1560,236.54000
454,9908059,2022-06-28,187,178,39528.90,0.00,7407.76,0.00,1695.44,0.00,...,2022-06-28,187,178,39528.90,0.000,14830.2000,411.95000,7534.8100,7571.4800,135.86000
455,9927251,2022-10-26,66,299,15433.30,0.00,2709.53,0.00,233.66,0.00,...,2022-10-26,66,299,15433.30,0.000,5438.6600,306.38000,2736.8700,2958.9500,49.22000
456,9927263,2022-12-21,9,356,854.00,0.00,99.97,0.00,0.00,0.00,...,2022-12-21,10,355,854.00,0.000,199.9400,61.60000,99.9700,132.9700,28.60000

In [122]:
result_df['Diff_dist']=result_df['Distance_lim']-result_df['Distance']
result_df['Diff_ME']=result_df['Total_ME_lima']-result_df['Total_ME']
result_df['Diff_AUX']=result_df['Total_AUX_lima']-result_df['Total_AE']
result_df['Diff_Boiler']=result_df['Total_Boiler_lima']-result_df['Total_Boiler']

In [123]:
result_df.columns.to_list()

['IMO',
 'Date_UTC',
 'Days_running_imodcs',
 'Missing_days_imodcs',
 'Distance',
 'ME_Consumption_HFO',
 'ME_Consumption_LFO',
 'AE_Consumption_HFO',
 'AE_Consumption_LFO',
 'Boiler_Consumption_HFO',
 'Boiler_Consumption_LFO',
 'MGO_MDO',
 'Total_ME',
 'Total_AE',
 'Total_Boiler',
 'ImoNumber',
 'vName',
 'DateTimeUtc',
 'Days_running_limasol',
 'Missing_days_limasol',
 'Distance_lim',
 'Total_HS',
 'Total_LS',
 'Total_ULS',
 'Total_ME_lima',
 'Total_AUX_lima',
 'Total_Boiler_lima',
 'Diff_dist',
 'Diff_ME',
 'Diff_AUX',
 'Diff_Boiler']

In [124]:
result_dc=result_df[['IMO','vName','DateTimeUtc','Days_running_imodcs','Missing_days_imodcs','Days_running_limasol','Missing_days_limasol','Distance','Distance_lim','Diff_dist','Total_ME','Total_ME_lima','Diff_ME','Total_AE','Total_AUX_lima','Diff_AUX','Total_Boiler','Total_Boiler_lima','Diff_Boiler']]

In [125]:
result_dc.to_csv('result_dc_all.csv')

In [126]:
result=result_df[['IMO','vName','DateTimeUtc','Days_running_imodcs','Missing_days_imodcs','Days_running_limasol','Missing_days_limasol','Distance','Distance_lim',
'Diff_dist','ME_Consumption_HFO','ME_Consumption_LFO','AE_Consumption_HFO','AE_Consumption_LFO','Boiler_Consumption_HFO','Boiler_Consumption_LFO','MGO_MDO','Total_ME','Total_AE','Total_Boiler','Total_HS',
 'Total_LS','Total_ULS','Total_ME_lima','Total_AUX_lima','Total_Boiler_lima','Diff_ME','Diff_AUX','Diff_Boiler']]

In [127]:
result.to_csv('result_all.csv')