# IMPORT DATA

In [1]:
import pandas as pd

In [2]:
imo=pd.read_excel('MRV - IMO DCS Data 2022.xlsx')
imo

,IMO,Date_UTC,Time_UTC,Voyage_From,Voyage_To,Voyage_Number,check,Service,Latitude_Degree,Latitude_Minutes,...,Boiler_Consumption_MGO,Boiler_Consumption_MDO,Boiler_Consumption_LNG,HFO_ROB,LFO_ROB,MGO_ROB,MDO_ROB,LNG_ROB,Offhire_Reasons,Unnamed: 49
0,9235581,2022-01-01,02:00:00,NaN,NaN,KQ150A,9.235581e+11,PANDA,18.0,52.0,...,0.00,0.0,0.0,1428.51,327.70,380.88,0.0,0.0,NaN,NaN
1,9235581,2022-01-02,02:00:00,NaN,NaN,KQ150A,9.235581e+11,PANDA,23.0,22.0,...,0.00,0.0,0.0,1381.11,327.70,380.88,0.0,0.0,NaN,NaN
2,9235581,2022-01-03,02:00:00,NaN,NaN,KQ150A,9.235581e+11,PANDA,26.0,29.0,...,0.00,0.0,0.0,1349.11,327.70,380.88,0.0,0.0,NaN,NaN
3,9235581,2022-01-03,05:30:00,NaN,NaN,KQ150A,9.235581e+11,PANDA,26.0,27.0,...,0.00,0.0,0.0,1347.31,327.70,380.88,0.0,0.0,NaN,NaN
4,9235581,2022-01-03,11:54:00,CNYTN,AUBNE,KQ150A,9.235581e+11,PANDA,26.0,27.0,...,0.00,0.0,0.0,1340.01,327.70,380.88,0.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293097,9235610,2022-12-29,12:00:00,NaN,NaN,RL252A,9.235610e+10,NWC TO/FROM PORTBURY GREENOCK,53.0,30.0,...,0.28,0.0,0.0,0.00,275.31,133.09,0.0,0.0,NaN,NaN
293098,9235610,2022-12-30,01:30:00,GBLIV,NaN,RL252R,9.235610e+11,NWC TO/FROM PORTBURY GREENOCK,53.0,30.0,...,0.40,0.0,0.0,0.00,275.23,132.23,0.0,0.0,NaN,NaN
293099,9235610,2022-12-30,04:42:00,NaN,NaN,RL252R,9.235610e+11,NWC TO/FROM PORTBURY GREENOCK,53.0,32.0,...,0.04,0.0,0.0,0.00,273.63,132.00,0.0,0.0,NaN,NaN
293100,9235610,2022-12-30,12:00:00,NaN,NaN,RL252R,9.235610e+11,NWC TO/FROM PORTBURY GREENOCK,53.0,33.0,...,0.08,0.0,0.0,0.00,269.98,131.92,0.0,0.0,NaN,NaN
293101,9235610,2022-12-31,12:00:00,NaN,NaN,RL252R,9.235610e+11,NWC TO/FROM PORTBURY GREENOCK,51.0,36.0,...,0.12,0.0,0.0,0.00,257.98,131.80,0.0,0.0,NaN,NaN

In [3]:
lim=pd.read_excel('2022.xlsx')
lim

,Unnamed: 0,MessagesId,ImoNumber,vName,MessageType,DateTimeLt,DateTimeUtc,Latitude,Longitude,CargoMT,...,Bdn number,Rob actual sludge,Rob actual bilge,Qty sludge disposed,Steaming time m/e lng,Reefer power consumption,Tanktainer min request,Comments,Template version,TANKTAINER ROB
0,195574,4615891,7826790,GNV AZZURRA,EOSP,2022-08-21 20:36:00+01:00,2022-08-21 19:36:00,4116N,01925E,492.0,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
1,200875,4615898,7826790,GNV AZZURRA,EOSP,2022-08-27 18:54:00+01:00,2022-08-27 17:54:00,4116N,01925E,0.0,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
2,208384,4615895,7826790,GNV AZZURRA,EOSP,2022-09-05 07:42:00+01:00,2022-09-05 06:42:00,4110N,01650E,582.0,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
3,251964,4615893,7826790,GNV AZZURRA,Port Noon,2022-10-23 12:00:00+01:00,2022-10-23 11:00:00,NaN,NaN,582.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,255639,4615900,7826790,GNV AZZURRA,Port Noon,2022-10-27 12:00:00+01:00,2022-10-27 11:00:00,NaN,NaN,582.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280262,315110,4500198,9927263,MSC AAYA,Sailing,2022-12-30 04:54:00+08:00,2022-12-29 20:54:00,NaN,NaN,35963.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
280263,315139,4500473,9927263,MSC AAYA,COSP,2022-12-30 06:18:00+08:00,2022-12-29 22:18:00,3600N,12021E,35963.0,...,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
280264,315394,4500589,9927263,MSC AAYA,Noon,2022-12-30 12:00:00+08:00,2022-12-30 04:00:00,3503N,12130E,35963.0,...,NaN,NaN,NaN,NaN,0.0,11.6,NaN,NaN,NaN,NaN
280265,316346,4502149,9927263,MSC AAYA,EOSP,2022-12-31 12:00:00+08:00,2022-12-31 04:00:00,3036N,12316E,35963.0,...,NaN,NaN,NaN,NaN,0.0,50.0,NaN,NaN,NaN,NaN
280266,316353,4502205,9927263,MSC AAYA,Delay,2022-12-31 12:30:00+08:00,2022-12-31 04:30:00,3035N,12311E,35963.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN

In [4]:
imo.shape

(293102, 50)

In [9]:
lim.shape

(280267, 161)

# IMO CHECKING

In [10]:
imo_unique_count= len(set(imo["IMO"]))
imo_unique_count

471

In [11]:
lim_unique_count= len(set(lim["ImoNumber"]))
lim_unique_count

469

In [12]:
imo_unique_missing=set(imo["IMO"])
imo_unique_missing

{7602120,
 7826790,
 8201624,
 8201636,
 8201648,
 8413875,
 8413887,
 8420892,
 8420907,
 8505836,
 8509375,
 8509387,
 8512891,
 8512906,
 8521402,
 8608200,
 8616520,
 8618293,
 8712520,
 8714205,
 8715857,
 8715869,
 8715871,
 8913411,
 8913423,
 8913447,
 8917778,
 8918057,
 8918954,
 8918966,
 8918978,
 8918980,
 9000742,
 9004231,
 9008574,
 9008603,
 9036002,
 9038907,
 9039250,
 9043756,
 9051478,
 9051492,
 9051507,
 9057173,
 9060649,
 9062984,
 9062996,
 9064748,
 9064750,
 9067544,
 9074042,
 9084607,
 9102710,
 9102722,
 9102746,
 9103685,
 9108398,
 9110377,
 9110389,
 9110391,
 9110975,
 9113446,
 9116369,
 9120853,
 9123154,
 9123166,
 9123221,
 9124366,
 9124512,
 9127021,
 9127540,
 9134490,
 9135638,
 9138783,
 9139086,
 9139505,
 9141285,
 9141297,
 9143879,
 9144134,
 9146479,
 9147071,
 9147227,
 9149328,
 9150080,
 9152856,
 9154191,
 9154206,
 9154220,
 9155107,
 9160920,
 9160982,
 9161297,
 9162277,
 9162631,
 9162643,
 9163192,
 9163207,
 9166651,
 9166778,
 9166780,
 9169029,
 9169031,
 9169043,
 9169055,
 9169067,
 9169122,
 9180190,
 9180205,
 9180968,
 9181651,
 9181663,
 9181675,
 9188219,
 9189366,
 9190092,
 9190119,
 9193680,
 9193719,
 9194866,
 9196838,
 9196864,
 9197545,
 9200677,
 9200689,
 9203538,
 9203904,
 9210050,
 9210062,
 9210086,
 9210098,
 9215892,
 9217565,
 9219393,
 9220328,
 9221059,
 9222106,
 9222120,
 9222302,
 9224049,
 9224051,
 9224348,
 9224946,
 9225249,
 9225251,
 9226932,
 9227285,
 9227297,
 9227302,
 9227314,
 9227326,
 9227338,
 9227340,
 9228576,
 9229300,
 9229312,
 9230775,
 9231119,
 9231248,
 9231250,
 9231262,
 9231779,
 9231810,
 9231822,
 9232395,
 9232462,
 9232632,
 9232644,
 9232656,
 9232761,
 9232773,
 9232890,
 9235402,
 9235581,
 9235608,
 9235610,
 9236212,
 9236224,
 9236444,
 9236585,
 9236688,
 9236690,
 9237151,
 9237371,
 9238739,
 9238741,
 9238789,
 9238882,
 9239733,
 9239903,
 9240328,
 9240873,
 9241451,
 9241463,
 9241475,
 9242625,
 9242637,
 9242651,
 9243239,
 9243241,
 9243394,
 9243409,
 9244881,
 9246566,
 9248928,
 9250983,
 9251688,
 9251690,
 9253014,
 9253038,
 9256315,
 9256327,
 9259381,
 9259393,
 9261815,
 9261827,
 9262546,
 9262560,
 9263332,
 9263344,
 9267637,
 9267649,
 9270828,
 9275036,
 9275373,
 9275397,
 9278143,
 9278155,
 9280861,
 9281267,
 9282259,
 9282261,
 9285665,
 9285691,
 9286231,
 9286267,
 9287792,
 9287900,
 9287924,
 9289051,
 9289087,
 9289099,
 9289544,
 9289960,
 9289972,
 9290402,
 9290426,
 9292175,
 9293167,
 9293179,
 9293442,
 9293777,
 9294989,
 9294991,
 9295165,
 9295177,
 9295397,
 9297864,
 9297876,
 9299525,
 9299537,
 9301328,
 9301330,
 9301483,
 9301550,
 9301990,
 9302085,
 9302619,
 9302621,
 9302633,
 9304459,
 9304746,
 9305001,
 9305013,
 9305477,
 9305489,
 9305506,
 9306263,
 9306275,
 9307267,
 9307839,
 9308584,
 9308601,
 9308625,
 9309289,
 9309411,
 9309447,
 9309459,
 9313943,
 9313967,
 9315006,
 9315018,
 9315379,
 9315381,
 9315836,
 9315915,
 9316347,
 9316359,
 9316361,
 9316373,
 9317925,
 9317937,
 9318046,
 9318058,
 9318187,
 9318773,
 9319600,
 9322011,
 9323041,
 9326768,
 9326823,
 9326940,
 9326964,
 9327683,
 9327798,
 9327803,
 9330226,
 9330238,
 9330240,
 9330264,
 9332729,
 9334349,
 9334832,
 9334844,
 9336165,
 9336359,
 9337444,
 9341122,
 9344564,
 9346017,
 9347762,
 9347803,
 9347970,
 9350317,
 9351579,
 9354363,
 9354416,
 9357107,
 9358905,
 9360271,
 9360283,
 9365984,
 9366421,
 9369734,
 9369758,
 9374571,
 9374595,
 9376141,
 9383223,
 9392561,
 9393022,
 9393307,
 9393319,
 9393321,
 9398216,
 9398228,
 9401166,
 9401685,
 9401776,
 9403396,
 9403437,
 9408774,
 9415296,
 9419644,
 9426817,
 9433157,
 9434462,
 9435820,
 9436472,
 9439735,
 9440306,
 9449687,
 9449869,
 9453298,
 9456965,
 9463035,
 9463047,
 9463059,
 9463205,
 9463281,
 9465241,
 9465253,
 9465265,
 9465277,
 9465306,
 9465318,
 9466960,
 9467445,
 9471226,
 9471238,
 9477610,
 9491616,
 9499010,
 9502908,
 9502960,
 9503732,
 9618276,
 9618288,
 9619452,
 9622007,
 9625932,
 9625944,
 9625970,
 9631876,
 9695028,
 9702065,
 9702077,
 9702089,
 9702091,
 9702106,
 9702261,
 9702273,
 9704960,
 9704972,
 9704984,
 9704996,
 9705005,
 9706310,
 9710426,
 9710438,
 9720196,
 9720201,
 9720287,
 9720457,
 9720471,
 9720483,
 9720495,
 9720500,
 9720512,
 9720524,
 9724049,
 9735206,
 9735218,
 9745653,
 9756729,
 9756731,
 9770737,
 9770749,
 9770751,
 9770763,
 9778076,
 9778088,
 9778090,
 9778105,
 9778117,
 9785445,
 9785457,
 9785469,
 9785471,
 9785483,
 9793947,
 9839260,
 9839272,
 9839284,
 9839296,
 9839301,
 9842061,
 9842073,
 9842085,
 9842097,
 9842102,
 9857157,
 9857169,
 9857171,
 9857183,
 9896983,
 9896995,
 9908047,
 9908059,
 9927251,
 9927263}

In [13]:
lim_unique_missing=set(lim['ImoNumber'])
lim_unique_missing

{7826790,
 8201624,
 8201636,
 8201648,
 8413875,
 8413887,
 8420892,
 8420907,
 8505836,
 8509375,
 8509387,
 8512891,
 8512906,
 8521397,
 8521402,
 8608200,
 8616520,
 8618293,
 8714205,
 8715857,
 8715869,
 8715871,
 8913411,
 8913423,
 8913447,
 8917778,
 8918057,
 8918954,
 8918966,
 8918978,
 8918980,
 9000742,
 9004231,
 9008574,
 9008603,
 9036002,
 9038907,
 9039250,
 9043756,
 9051478,
 9051492,
 9051507,
 9057173,
 9060649,
 9062984,
 9062996,
 9064748,
 9064750,
 9067544,
 9074042,
 9084607,
 9102710,
 9102722,
 9102746,
 9103685,
 9108398,
 9110377,
 9110389,
 9110391,
 9110975,
 9113446,
 9116369,
 9120853,
 9123154,
 9123166,
 9123221,
 9124366,
 9124512,
 9127021,
 9127540,
 9134490,
 9135638,
 9138783,
 9139086,
 9139505,
 9141285,
 9141297,
 9143879,
 9144134,
 9146479,
 9147071,
 9147227,
 9149328,
 9152856,
 9154191,
 9154206,
 9154220,
 9155107,
 9160982,
 9161297,
 9162277,
 9162631,
 9162643,
 9163192,
 9163207,
 9166651,
 9166778,
 9166780,
 9169029,
 9169031,
 9169043,
 9169055,
 9169067,
 9169122,
 9180190,
 9180205,
 9180968,
 9181651,
 9181663,
 9181675,
 9188219,
 9189366,
 9190092,
 9190119,
 9193680,
 9193719,
 9194866,
 9196838,
 9196864,
 9197545,
 9200677,
 9200689,
 9203538,
 9203904,
 9210050,
 9210062,
 9210086,
 9210098,
 9215672,
 9215892,
 9217565,
 9219393,
 9220328,
 9221059,
 9222106,
 9222120,
 9222302,
 9224049,
 9224051,
 9224348,
 9224946,
 9225249,
 9225251,
 9226932,
 9227285,
 9227297,
 9227302,
 9227314,
 9227326,
 9227338,
 9227340,
 9228576,
 9229300,
 9229312,
 9230775,
 9231119,
 9231248,
 9231250,
 9231262,
 9231779,
 9231810,
 9231822,
 9232395,
 9232462,
 9232632,
 9232644,
 9232656,
 9232761,
 9232773,
 9232890,
 9235402,
 9235581,
 9235608,
 9235610,
 9236212,
 9236224,
 9236444,
 9236585,
 9236688,
 9236690,
 9237151,
 9238739,
 9238741,
 9238789,
 9238882,
 9239733,
 9239903,
 9240328,
 9240873,
 9241451,
 9241463,
 9241475,
 9242625,
 9242637,
 9242651,
 9243239,
 9243241,
 9243394,
 9243409,
 9244881,
 9248928,
 9250983,
 9251688,
 9251690,
 9253014,
 9253038,
 9256315,
 9256327,
 9256365,
 9259381,
 9259393,
 9261815,
 9261827,
 9262546,
 9262560,
 9263332,
 9263344,
 9267637,
 9267649,
 9270828,
 9275036,
 9275373,
 9275397,
 9278143,
 9278155,
 9280861,
 9281267,
 9282259,
 9282261,
 9285665,
 9285691,
 9286231,
 9286267,
 9287900,
 9287924,
 9289051,
 9289087,
 9289099,
 9289544,
 9289960,
 9289972,
 9290402,
 9290426,
 9292175,
 9293167,
 9293179,
 9293442,
 9293777,
 9294824,
 9294989,
 9294991,
 9295165,
 9295177,
 9295397,
 9297864,
 9297876,
 9299525,
 9299537,
 9301328,
 9301330,
 9301483,
 9301550,
 9301990,
 9302085,
 9302619,
 9302621,
 9302633,
 9304459,
 9304746,
 9305001,
 9305013,
 9305477,
 9305489,
 9305506,
 9306263,
 9306275,
 9307267,
 9307839,
 9308584,
 9308601,
 9308625,
 9309289,
 9309411,
 9309447,
 9309459,
 9313943,
 9313967,
 9315379,
 9315381,
 9315836,
 9315886,
 9315915,
 9316347,
 9316359,
 9316361,
 9316373,
 9317925,
 9317937,
 9318046,
 9318058,
 9318187,
 9318773,
 9319600,
 9322011,
 9323041,
 9326768,
 9326823,
 9327683,
 9327798,
 9327803,
 9330226,
 9330238,
 9330240,
 9330264,
 9332729,
 9334349,
 9334832,
 9334844,
 9336165,
 9336359,
 9337444,
 9341122,
 9344564,
 9346017,
 9347762,
 9347803,
 9347970,
 9350317,
 9351579,
 9357107,
 9358905,
 9360271,
 9360283,
 9366421,
 9369734,
 9369758,
 9374571,
 9374595,
 9376141,
 9383223,
 9392561,
 9393022,
 9393307,
 9393319,
 9393321,
 9398216,
 9398228,
 9401166,
 9401685,
 9401776,
 9403396,
 9403437,
 9408774,
 9415296,
 9419644,
 9426817,
 9433157,
 9434462,
 9435820,
 9436472,
 9439735,
 9440306,
 9449687,
 9449869,
 9450351,
 9453298,
 9456965,
 9463035,
 9463047,
 9463059,
 9463205,
 9463281,
 9465241,
 9465253,
 9465265,
 9465277,
 9465306,
 9465318,
 9466960,
 9467445,
 9471226,
 9471238,
 9477309,
 9477610,
 9491616,
 9499010,
 9502908,
 9502960,
 9503732,
 9618264,
 9618276,
 9618288,
 9618290,
 9618305,
 9618317,
 9619452,
 9622007,
 9625932,
 9625944,
 9625970,
 9631876,
 9695016,
 9695028,
 9702065,
 9702077,
 9702089,
 9702091,
 9702106,
 9702261,
 9702273,
 9704960,
 9704972,
 9704984,
 9704996,
 9705005,
 9706310,
 9710426,
 9710438,
 9720196,
 9720201,
 9720287,
 9720457,
 9720471,
 9720483,
 9720495,
 9720500,
 9720512,
 9720524,
 9724049,
 9735206,
 9735218,
 9745653,
 9756729,
 9756731,
 9770737,
 9770749,
 9770751,
 9770763,
 9778076,
 9778088,
 9778090,
 9778105,
 9778117,
 9785445,
 9785457,
 9785469,
 9785471,
 9785483,
 9793947,
 9839260,
 9839272,
 9839284,
 9839296,
 9839301,
 9842061,
 9842073,
 9842085,
 9842097,
 9842102,
 9857157,
 9857169,
 9857171,
 9857183,
 9896983,
 9896995,
 9908047,
 9908059,
 9927251,
 9927263}

In [14]:
missing_lim = lim_unique_missing - imo_unique_missing
missing_lim

{8521397,
 9215672,
 9256365,
 9294824,
 9315886,
 9450351,
 9477309,
 9618264,
 9618290,
 9618305,
 9618317,
 9695016}

In [15]:
missing_imo = imo_unique_missing - lim_unique_missing
missing_imo
#imp

{7602120,
 8712520,
 9150080,
 9160920,
 9237371,
 9246566,
 9287792,
 9315006,
 9315018,
 9326940,
 9326964,
 9354363,
 9354416,
 9365984}

In [16]:
print("Missing imo dcs", len(missing_imo))
print("Missing imo limmasol", len(missing_lim))

Missing imo dcs 14
Missing imo limmasol 12

In [17]:
imo_df=imo.copy()
lim_df=lim.copy()

In [18]:
imo_set ={9287792,
 9160920,
 8712520,
 9326940,
 9326964,
 9365984,
 9315006,
 9315018,
 9237371,
 9354363,
 9354416,
 9150080,
 9246566,
 7602120
}

imolst = list(imo_set)

# Create a generator expression to format each IMO number with single quotes
formatted_imolst = ("{}".format(imo) for imo in imolst)

# Convert the generator object to a list
formatted_imolst_list = list(formatted_imolst)

print(formatted_imolst_list)

['9365984', '9150080', '9237371', '9246566', '8712520', '7602120', '9315018', '9287792', '9354416', '9326964', '9160920', '9354363', '9326940', '9315006']

In [19]:
#Comparion between imo dcs with noon data

In [20]:
imo_values_df1 = set(lim['ImoNumber'])
imo_values_df2 = set(imo['IMO'])

# Identify 'imo' values in df1 that are not in df2
imos_not_in_df2 = [imo for imo in imo_values_df1 if imo not in imo_values_df2]

# Identify 'imo' values in df2 that are not in df1
imos_not_in_df1 = [imo for imo in imo_values_df2 if imo not in imo_values_df1]

In [21]:
imos_not_in_df2

[9618264,
 9450351,
 9618290,
 9618305,
 9618317,
 9294824,
 9477309,
 9256365,
 9315886,
 8521397,
 9215672,
 9695016]

In [22]:
imos_not_in_df1

[9287792,
 9160920,
 8712520,
 9326940,
 9326964,
 9365984,
 9315006,
 9315018,
 9237371,
 9354363,
 9354416,
 9150080,
 9246566,
 7602120]

In [79]:
duplicates = imo_df.duplicated()

# Print the duplicated rows
print(imo_df[duplicates])

# Count the number of duplicate rows
num_duplicates = duplicates.sum()
print("Number of duplicate rows:", num_duplicates)

            IMO    Date_UTC  Time_UTC Voyage_From Voyage_To Voyage_Number  \
261954  9704996  2022-01-01  06:30:00         NaN       NaN        IU151A
261955  9704996  2022-01-01  20:24:00       INMUN       NaN        IU151A
261956  9704996  2022-01-01  21:06:00         NaN       NaN        IU151A
261957  9704996  2022-01-02  06:30:00         NaN       NaN        IU151A
261958  9704996  2022-01-03  08:00:00         NaN       NaN        IU151A
...         ...         ...       ...         ...       ...           ...
262597  9704996  2022-12-29  11:00:00         NaN       NaN        MC251A
262598  9704996  2022-12-29  14:12:00         NaN       NaN        MC251A
262600  9704996  2022-12-30  11:00:00         NaN       NaN        MC251A
262601  9704996  2022-12-30  14:00:00       ESVLC       NaN        MC251A
262603  9704996  2022-12-31  11:00:00         NaN       NaN        MC251A

               check             Service  Latitude_Degree  Latitude_Minutes  \
261954  9.704997e+11       INDUS EXPRESS             22.0              36.0
261955  9.704997e+11       INDUS EXPRESS             22.0              36.0
261956  9.704997e+11       INDUS EXPRESS             22.0              42.0
261957  9.704997e+11       INDUS EXPRESS             21.0              39.0
261958  9.704997e+11       INDUS EXPRESS             18.0              45.0
...              ...                 ...              ...               ...
262597  9.704996e+11  CALIFORNIA EXPRESS             39.0              55.0
262598  9.704996e+11  CALIFORNIA EXPRESS             39.0              25.0
262600  9.704996e+11  CALIFORNIA EXPRESS             39.0              25.0
262601  9.704996e+11  CALIFORNIA EXPRESS             39.0              25.0
262603  9.704996e+11  CALIFORNIA EXPRESS             36.0              16.0

        ... LFO_ROB  MGO_ROB  MDO_ROB LNG_ROB  Offhire_Reasons  Unnamed: 49  \
261954  ...  492.96   550.26      0.0     0.0              NaN          NaN
261955  ...  492.96   550.26      0.0     0.0              NaN          NaN
261956  ...  492.96   550.26      0.0     0.0              NaN          NaN
261957  ...  493.79   544.86      0.0     0.0              NaN          NaN
261958  ...  493.79   544.86      0.0     0.0              NaN          NaN
...     ...     ...      ...      ...     ...              ...          ...
262597  ...  493.99   316.10      0.0     0.0              NaN          NaN
262598  ...  493.99   316.10      0.0     0.0              NaN          NaN
262600  ...  493.99  1315.97      0.0     0.0              NaN          NaN
262601  ...  493.99  1315.97      0.0     0.0              NaN          NaN
262603  ...  493.99  1315.97      0.0     0.0              NaN          NaN

        MGO_MDO Total_ME  Total_AE  Total_Boiler
261954      0.0      0.0       6.7           3.0
261955      0.0      0.0       6.7           3.0
261956      0.0      0.5       0.5           0.1
261957      0.0     26.2       4.8           1.0
261958      0.0     70.5      13.3           3.0
...         ...      ...       ...           ...
262597      0.0    116.0      13.6           0.1
262598      0.0     12.6       2.9           0.0
262600      0.0      0.0      10.2           2.8
262601      0.0      0.0       3.2           0.7
262603      0.0     45.1      12.5           2.3

[531 rows x 54 columns]
Number of duplicate rows: 531

In [82]:
# Check for duplicates in the DataFrame
duplicates_lim = lim_df.duplicated()

# Print the duplicated rows
#print(lim_df[duplicates_lim])

# Count the number of duplicate rows
num_duplicate_lim = duplicates_lim.sum()
print("Number of duplicate rows:", num_duplicate_lim)

Number of duplicate rows: 0

In [23]:
lim_df=lim.copy()
imo_df=imo.copy()

In [24]:
imo_lst=['9618305', '9294824', '9695016', '9618317', '9256365', '9450351', '9315886', '9618290', '9618264', '8521397', '9215672', '9477309']
lim_df = lim_df[~lim_df['ImoNumber'].isin(imo_lst)]
lim_df['ImoNumber'] = lim_df['ImoNumber'].astype(str)
lim_df = lim_df[~lim_df['ImoNumber'].isin(imo_lst)]

In [25]:
imo_lst=['9365984', '9150080', '9237371', '9246566', '8712520', '7602120', '9315018', '9287792', '9354416', '9326964', '9160920', '9354363', '9326940', '9315006']
imo_df = imo_df[~imo_df['IMO'].isin(imo_lst)]
imo_df['IMO'] = imo_df['IMO'].astype(str)
imo_df = imo_df[~imo_df['IMO'].isin(imo_lst)]

In [26]:
#print('limmasol',lim_df['ImoNumber'].nunique())
print('imo dcs',imo_df['IMO'].nunique())
print('Limmasol',lim_df['ImoNumber'].nunique())

imo dcs 457
Limmasol 457

# REPORT TYPE CHCEKING

In [27]:
unique_events_count = imo_df['Event'].nunique()

print("Number of unique events:", unique_events_count)

Number of unique events: 37

In [28]:
unique_event_count = imo_df['Event'].unique()

unique_event_count

array(['NOON', 'EOSP', 'ARRIVAL', 'DEPARTURE', 'COSP', 'PORT NOON',
       'DELAY', 'COSP TRANSIT', 'Begin of sea passage',
       'Noon (Position) - Sea passage', 'End of sea passage',
       'Noon (Position) - Port', 'Departure', 'Noon', 'Arrival',
       'PORTNOON', 'Noon Maneuvering', 'Heave Anchor', 'Noon In Port',
       'Begin Of Sea Passage', 'Entering Canal', 'Noon At Sea',
       'End Of Sea Passage', 'Bunkering', 'Leaving Canal', 'Drop Anchor',
       'End Waiting/Drifting', 'Destination Changed',
       'Sounding Correction (At Sea)', 'Sounding Correction (In Port)',
       'Begin Waiting/Drifting', 'Begin Stoppage', 'End Stoppage',
       'Begin Shifting Berth', 'Update ETA/RTA/ETD',
       'Sounding Correction (Maneuveri', 'Drop Anchor Arrival'],
      dtype=object)

In [29]:
imo_df

,IMO,Date_UTC,Time_UTC,Voyage_From,Voyage_To,Voyage_Number,check,Service,Latitude_Degree,Latitude_Minutes,...,Boiler_Consumption_MGO,Boiler_Consumption_MDO,Boiler_Consumption_LNG,HFO_ROB,LFO_ROB,MGO_ROB,MDO_ROB,LNG_ROB,Offhire_Reasons,Unnamed: 49
0,9235581,2022-01-01,02:00:00,NaN,NaN,KQ150A,9.235581e+11,PANDA,18.0,52.0,...,0.00,0.0,0.0,1428.51,327.70,380.88,0.0,0.0,NaN,NaN
1,9235581,2022-01-02,02:00:00,NaN,NaN,KQ150A,9.235581e+11,PANDA,23.0,22.0,...,0.00,0.0,0.0,1381.11,327.70,380.88,0.0,0.0,NaN,NaN
2,9235581,2022-01-03,02:00:00,NaN,NaN,KQ150A,9.235581e+11,PANDA,26.0,29.0,...,0.00,0.0,0.0,1349.11,327.70,380.88,0.0,0.0,NaN,NaN
3,9235581,2022-01-03,05:30:00,NaN,NaN,KQ150A,9.235581e+11,PANDA,26.0,27.0,...,0.00,0.0,0.0,1347.31,327.70,380.88,0.0,0.0,NaN,NaN
4,9235581,2022-01-03,11:54:00,CNYTN,AUBNE,KQ150A,9.235581e+11,PANDA,26.0,27.0,...,0.00,0.0,0.0,1340.01,327.70,380.88,0.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293097,9235610,2022-12-29,12:00:00,NaN,NaN,RL252A,9.235610e+10,NWC TO/FROM PORTBURY GREENOCK,53.0,30.0,...,0.28,0.0,0.0,0.00,275.31,133.09,0.0,0.0,NaN,NaN
293098,9235610,2022-12-30,01:30:00,GBLIV,NaN,RL252R,9.235610e+11,NWC TO/FROM PORTBURY GREENOCK,53.0,30.0,...,0.40,0.0,0.0,0.00,275.23,132.23,0.0,0.0,NaN,NaN
293099,9235610,2022-12-30,04:42:00,NaN,NaN,RL252R,9.235610e+11,NWC TO/FROM PORTBURY GREENOCK,53.0,32.0,...,0.04,0.0,0.0,0.00,273.63,132.00,0.0,0.0,NaN,NaN
293100,9235610,2022-12-30,12:00:00,NaN,NaN,RL252R,9.235610e+11,NWC TO/FROM PORTBURY GREENOCK,53.0,33.0,...,0.08,0.0,0.0,0.00,269.98,131.92,0.0,0.0,NaN,NaN
293101,9235610,2022-12-31,12:00:00,NaN,NaN,RL252R,9.235610e+11,NWC TO/FROM PORTBURY GREENOCK,51.0,36.0,...,0.12,0.0,0.0,0.00,257.98,131.80,0.0,0.0,NaN,NaN

# Days

In [30]:
imo_df['Date_UTC'] = pd.to_datetime(imo_df['Date_UTC'])

result = imo_df.groupby('IMO')['Date_UTC'].agg(['min', 'max']).reset_index()

# Calculate number of days
result['min'] = pd.to_datetime(result['min'])
result['max'] = pd.to_datetime(result['max'])
result['Days Count'] = (result['max'] - result['min']).dt.days + 1

missing_dates = []

for _, row in result.iterrows():
    imo_no = row['IMO']
    date_range = pd.date_range(start=row['min'], end=row['max'], freq='D')
    actual_dates = set(imo_df[imo_df['IMO'] == imo_no]['Date_UTC'])
    missing = list(set(date_range) - actual_dates)
    missing_str = [date.strftime('%Y-%m-%d') for date in missing]  # Convert datetime.date objects to string
    missing_dates.append([imo_no, missing_str, len(missing)])


missing_dates_imodcs = pd.DataFrame(missing_dates, columns=['imo', 'Missing Dates', 'Count'])

print(missing_dates_imodcs)

         imo                                      Missing Dates  Count
0    7826790                                                 []      0
1    8201624                                                 []      0
2    8201636                                                 []      0
3    8201648                                                 []      0
4    8413875                                       [2022-10-27]      1
..       ...                                                ...    ...
452  9896995  [2022-11-15, 2022-08-08, 2022-12-08, 2022-06-2...      5
453  9908047                                       [2022-07-07]      1
454  9908059                                                 []      0
455  9927251                                       [2022-10-27]      1
456  9927263                           [2022-12-22, 2022-12-23]      2

[457 rows x 3 columns]

In [31]:
lim_df['DateTimeUtc'] = pd.to_datetime(lim_df['DateTimeUtc'])

result = lim_df.groupby('ImoNumber')['DateTimeUtc'].agg(['min', 'max']).reset_index()

# Calculate number of days
result['min'] = pd.to_datetime(result['min'])
result['max'] = pd.to_datetime(result['max'])
result['Days Count'] = (result['max'] - result['min']).dt.days + 1

missing_dates = []

for _, row in result.iterrows():
    imo_no = row['ImoNumber']
    date_range = pd.date_range(start=row['min'], end=row['max'], freq='D').date
    actual_dates = set(lim_df[lim_df['ImoNumber'] == imo_no]['DateTimeUtc'].dt.date)
    missing = list(set(date_range) - actual_dates)
    missing_str = [date.strftime('%Y-%m-%d') for date in missing]  # Convert datetime.date objects to string
    missing_dates.append([imo_no, missing_str, len(missing)])


missing_dates_lim = pd.DataFrame(missing_dates, columns=['imo', 'Missing Dates', 'Count'])

missing_dates_lim

         imo                                      Missing Dates  Count
0    7826790  [2022-10-13, 2022-10-01, 2022-09-16, 2022-10-0...     81
1    8201624                                                 []      0
2    8201636                                                 []      0
3    8201648                                                 []      0
4    8413875                                       [2022-10-27]      1
..       ...                                                ...    ...
452  9896995  [2022-09-21, 2022-06-25, 2022-11-15, 2022-08-0...      5
453  9908047                                       [2022-07-07]      1
454  9908059                                                 []      0
455  9927251                                       [2022-10-27]      1
456  9927263                           [2022-12-23, 2022-12-22]      2

[457 rows x 3 columns]

In [32]:
imo_df['Date_UTC']= pd.to_datetime(imo_df['Date_UTC']).dt.date
imo_df['Date_UTC']=imo_df['Date_UTC'].astype(str)

In [33]:
lim_df['DateTimeUtc']= pd.to_datetime(lim_df['DateTimeUtc']).dt.date
lim_df['DateTimeUtc']=lim_df['DateTimeUtc'].astype(str)

In [34]:
# Iterate through each row of missing_dates_imo
for _, row in missing_dates_imodcs.iterrows():
    imo_no = row['imo']
    missing_dates = row['Missing Dates']
    
    # Convert missing_dates to datetime objects
    missing_dates = pd.to_datetime(missing_dates)
    
    # Filter out rows with the specified IMO and missing dates
    lim_df = lim_df[~((lim_df['ImoNumber'] == imo_no) & lim_df['DateTimeUtc'].isin(missing_dates))]

In [35]:
# Iterate through each row of missing_dates_imo
for _, row in missing_dates_lim.iterrows():
    imo_no = row['imo']
    missing_dates = row['Missing Dates']
    
    # Convert missing_dates to datetime objects
    missing_dates = pd.to_datetime(missing_dates)
    
    # Filter out rows with the specified IMO and missing dates
    imo_df = imo_df[~((imo_df['IMO'] == imo_no) & imo_df['Date_UTC'].isin(missing_dates))]

In [36]:
imo_df.shape

(280735, 50)

In [37]:
lim_df.shape

(274179, 161)

# Fuel and Distance

In [38]:
imo_df['MGO_MDO']=imo_df[['ME_Consumption_MGO','ME_Consumption_MDO','AE_Consumption_MGO','AE_Consumption_MDO','Boiler_Consumption_MGO','Boiler_Consumption_MDO']].sum(axis=1)

In [39]:
imo_df['Total_ME']=imo_df[['ME_Consumption_HFO','ME_Consumption_LFO','ME_Consumption_MGO','ME_Consumption_MDO']].sum(axis=1)
imo_df['Total_AE']=imo_df[['AE_Consumption_HFO','AE_Consumption_LFO','AE_Consumption_MGO','AE_Consumption_MDO']].sum(axis=1)
imo_df['Total_Boiler']=imo_df[['Boiler_Consumption_HFO','Boiler_Consumption_LFO','Boiler_Consumption_MGO','Boiler_Consumption_MDO']].sum(axis=1)

In [40]:
fuel_imodcs=imo_df[['IMO','Distance','Date_UTC','ME_Consumption_HFO', 'ME_Consumption_LFO','AE_Consumption_HFO','AE_Consumption_LFO',
                    'Boiler_Consumption_HFO','Boiler_Consumption_LFO','MGO_MDO','Total_ME','Total_AE','Total_Boiler'
]]

In [41]:
fuel_imodcs

,IMO,Distance,Date_UTC,ME_Consumption_HFO,ME_Consumption_LFO,AE_Consumption_HFO,AE_Consumption_LFO,Boiler_Consumption_HFO,Boiler_Consumption_LFO,MGO_MDO,Total_ME,Total_AE,Total_Boiler
0,9235581,314.0,2022-01-01,46.0,0.00,5.6,0.0,0.0,0.0,0.00,46.00,5.60,0.00
1,9235581,277.0,2022-01-02,42.0,0.00,5.4,0.0,0.0,0.0,0.00,42.00,5.40,0.00
2,9235581,213.0,2022-01-03,24.0,0.00,6.0,0.0,2.0,0.0,0.00,24.00,6.00,2.00
3,9235581,9.0,2022-01-03,0.8,0.00,0.5,0.0,0.5,0.0,0.00,0.80,0.50,0.50
4,9235581,67.0,2022-01-03,5.0,0.00,1.7,0.0,0.6,0.0,0.00,5.00,1.70,0.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
293097,9235610,0.0,2022-12-29,0.0,0.00,0.0,0.0,0.0,0.0,0.69,0.00,0.41,0.28
293098,9235610,0.0,2022-12-30,0.0,0.08,0.0,0.0,0.0,0.0,0.86,0.08,0.46,0.40
293099,9235610,14.2,2022-12-30,0.0,1.60,0.0,0.0,0.0,0.0,0.23,1.60,0.19,0.04
293100,9235610,52.0,2022-12-30,0.0,3.65,0.0,0.0,0.0,0.0,0.08,3.65,0.00,0.08
293101,9235610,124.0,2022-12-31,0.0,12.00,0.0,0.0,0.0,0.0,0.12,12.00,0.00,0.12

In [42]:
import pandas as pd

# Assuming 'fuel_imodcs' is your DataFrame containing fuel data
fuel_imodcs['Date_UTC'] = pd.to_datetime(fuel_imodcs['Date_UTC'])

# Extracting the month from 'Date_UTC'
fuel_imodcs['month'] = fuel_imodcs['Date_UTC'].dt.month

# Grouping by 'IMO' and 'month', and performing aggregations
grouped_df = fuel_imodcs.groupby(['IMO', 'month']).agg({
    'Date_UTC': 'first',  # Assuming you want the first date in each group
    'Distance': 'sum',
    'ME_Consumption_HFO': 'sum',
    'ME_Consumption_LFO': 'sum',
    'AE_Consumption_HFO': 'sum',
    'AE_Consumption_LFO': 'sum',
    'Boiler_Consumption_HFO': 'sum',
    'Boiler_Consumption_LFO': 'sum',
    'MGO_MDO': 'sum',
    'Total_ME': 'sum',
    'Total_AE': 'sum',
    'Total_Boiler': 'sum'
}).reset_index()

# Sorting the DataFrame by 'IMO' and 'month'
fuel_imo_month_grouped_df = grouped_df.sort_values(by=['IMO', 'month'])

fuel_imo_month_grouped_df

C:\Users\akshaya\AppData\Local\Temp\ipykernel_131540\1242921213.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_imodcs['Date_UTC'] = pd.to_datetime(fuel_imodcs['Date_UTC'])
C:\Users\akshaya\AppData\Local\Temp\ipykernel_131540\1242921213.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_imodcs['month'] = fuel_imodcs['Date_UTC'].dt.month

,IMO,month,Date_UTC,Distance,ME_Consumption_HFO,ME_Consumption_LFO,AE_Consumption_HFO,AE_Consumption_LFO,Boiler_Consumption_HFO,Boiler_Consumption_LFO,MGO_MDO,Total_ME,Total_AE,Total_Boiler
0,7826790,1,2022-01-01,711.32,0.0,101.97,0.0,0.00,0.0,0.0,277.20,101.97,216.14,61.06
1,7826790,2,2022-02-01,788.50,0.0,90.30,0.0,0.00,0.0,0.0,256.68,90.30,198.99,57.69
2,7826790,3,2022-03-01,379.50,0.0,65.48,0.0,0.00,0.0,0.0,279.69,65.48,215.66,64.03
3,7826790,4,2022-04-01,647.80,0.0,128.04,0.0,0.00,0.0,0.0,234.04,128.04,203.74,30.30
4,7826790,5,2022-05-01,1516.80,0.0,231.44,0.0,0.00,0.0,0.0,282.94,231.44,244.56,38.38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5128,9908059,12,2022-12-01,5599.60,0.0,1228.05,0.0,318.56,0.0,0.0,79.70,1235.20,337.76,53.35
5129,9927251,10,2022-10-26,739.00,0.0,83.25,0.0,0.00,0.0,0.0,12.67,86.00,6.37,3.55
5130,9927251,11,2022-11-01,5945.40,0.0,1169.32,0.0,57.09,0.0,0.0,181.59,1193.91,189.45,24.64
5131,9927251,12,2022-12-01,8748.90,0.0,1456.96,0.0,176.57,0.0,19.6,112.12,1456.96,287.26,21.03
5132,9927263,12,2022-12-21,854.00,0.0,99.97,0.0,0.00,0.0,0.0,61.60,99.97,33.00,28.60

In [44]:
fuel_imo_month_grouped_df

,IMO,month,Date_UTC,Distance,ME_Consumption_HFO,ME_Consumption_LFO,AE_Consumption_HFO,AE_Consumption_LFO,Boiler_Consumption_HFO,Boiler_Consumption_LFO,MGO_MDO,Total_ME,Total_AE,Total_Boiler
0,7826790,1,2022-01-01,711.32,0.0,101.97,0.0,0.00,0.0,0.0,277.20,101.97,216.14,61.06
1,7826790,2,2022-02-01,788.50,0.0,90.30,0.0,0.00,0.0,0.0,256.68,90.30,198.99,57.69
2,7826790,3,2022-03-01,379.50,0.0,65.48,0.0,0.00,0.0,0.0,279.69,65.48,215.66,64.03
3,7826790,4,2022-04-01,647.80,0.0,128.04,0.0,0.00,0.0,0.0,234.04,128.04,203.74,30.30
4,7826790,5,2022-05-01,1516.80,0.0,231.44,0.0,0.00,0.0,0.0,282.94,231.44,244.56,38.38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5128,9908059,12,2022-12-01,5599.60,0.0,1228.05,0.0,318.56,0.0,0.0,79.70,1235.20,337.76,53.35
5129,9927251,10,2022-10-26,739.00,0.0,83.25,0.0,0.00,0.0,0.0,12.67,86.00,6.37,3.55
5130,9927251,11,2022-11-01,5945.40,0.0,1169.32,0.0,57.09,0.0,0.0,181.59,1193.91,189.45,24.64
5131,9927251,12,2022-12-01,8748.90,0.0,1456.96,0.0,176.57,0.0,19.6,112.12,1456.96,287.26,21.03
5132,9927263,12,2022-12-21,854.00,0.0,99.97,0.0,0.00,0.0,0.0,61.60,99.97,33.00,28.60

In [45]:
import pandas as pd

# Assuming 'fuel_imodcs' is your DataFrame containing fuel data
fuel_imodcs['Date_UTC'] = pd.to_datetime(fuel_imodcs['Date_UTC'])

# Assigning a unique number to each date within each vessel's data
fuel_imodcs['Days_running_imodcs'] = fuel_imodcs.groupby('IMO').cumcount() + 1

# Modifying the assigned day numbers to ensure they don't exceed 365
fuel_imodcs['Days_running_imodcs'] = fuel_imodcs['Days_running_imodcs'].apply(lambda x: x % 365 if x <= 365 else x % 365 + 1)

# Grouping by 'IMO' and summing the modified assigned numbers to calculate days run
grouped_dates = fuel_imodcs.groupby('IMO')['Days_running_imodcs'].agg(Days_running_imodcs='max')

# Calculating the count of missing days for each vessel
grouped_dates['Missing_days_imodcs'] = 365 - grouped_dates['Days_running_imodcs']

grouped_dates = grouped_dates.reset_index()

grouped_dates.head(7)

C:\Users\akshaya\AppData\Local\Temp\ipykernel_131540\1589552094.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_imodcs['Date_UTC'] = pd.to_datetime(fuel_imodcs['Date_UTC'])
C:\Users\akshaya\AppData\Local\Temp\ipykernel_131540\1589552094.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_imodcs['Days_running_imodcs'] = fuel_imodcs.groupby('IMO').cumcount() + 1
C:\Users\akshaya\AppData\Local\Temp\ipykernel_131540\1589552094.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_imodcs['Days_running_imodcs'] = fuel_imodcs['Days_running_imodcs'].apply(lambda x: x % 365 if x <= 365 else x % 365 + 1)

       IMO  Days_running_imodcs  Missing_days_imodcs
0  7826790                  365                    0
1  8201624                  365                    0
2  8201636                  365                    0
3  8201648                  365                    0
4  8413875                  364                    1
5  8413887                  364                    1
6  8420892                  364                    1

In [46]:
# Merging 'grouped_dates' DataFrame with 'fuel_imo_grouped_df' on the 'IMO' column
fuel_imo_month_grouped_df = pd.merge(fuel_imo_month_grouped_df, grouped_dates, on='IMO', how='left')

fuel_imo_month_grouped_df.head(7)

,IMO,month,Date_UTC,Distance,ME_Consumption_HFO,ME_Consumption_LFO,AE_Consumption_HFO,AE_Consumption_LFO,Boiler_Consumption_HFO,Boiler_Consumption_LFO,MGO_MDO,Total_ME,Total_AE,Total_Boiler,Days_running_imodcs,Missing_days_imodcs
0,7826790,1,2022-01-01,711.32,0.0,101.97,0.0,0.0,0.0,0.0,277.20,101.97,216.14,61.06,365,0
1,7826790,2,2022-02-01,788.50,0.0,90.30,0.0,0.0,0.0,0.0,256.68,90.30,198.99,57.69,365,0
2,7826790,3,2022-03-01,379.50,0.0,65.48,0.0,0.0,0.0,0.0,279.69,65.48,215.66,64.03,365,0
3,7826790,4,2022-04-01,647.80,0.0,128.04,0.0,0.0,0.0,0.0,234.04,128.04,203.74,30.30,365,0
4,7826790,5,2022-05-01,1516.80,0.0,231.44,0.0,0.0,0.0,0.0,282.94,231.44,244.56,38.38,365,0
5,7826790,6,2022-06-01,1452.40,0.0,234.03,0.0,0.0,0.0,0.0,281.78,242.27,245.21,28.33,365,0
6,7826790,7,2022-07-01,5114.70,0.0,729.04,0.0,0.0,0.0,0.0,365.15,729.04,341.55,23.60,365,0

In [47]:
fuel_imo_month_grouped_df.to_csv('fuel_imo_month_grouped_df.csv')

fuel_imo_grouped_df['IMO'] = fuel_imo_grouped_df['IMO'].astype(str)
result_fuel_df = fuel_imo_grouped_df.merge(fuel_imo_grouped_df, left_on=['imo', 'month'], right_on=['IMO', 'month'], how='inner')
print(result_fuel_df)

In [ ]:
#result_fuel_df.to_csv('Data comparison.csv')

In [ ]:
#lim

In [48]:
lim_df['ME_hs_lima'] =  lim_df[['FOC_ME_RES_HS']]
lim_df['AUX_hs_lima'] =  lim_df[['FOC_AE_RES_HS']]
lim_df['Boiler_hs_lima'] =  lim_df[['FOC_BLR_RES_HS']]
 
lim_df['ME_ls_lima'] =  lim_df[['FOC_ME_RES_ULS','FOC_ME_RES_VLS']].sum(axis = 1) 
lim_df['AUX_ls_lima'] =  lim_df[['FOC_ME_RES_ULS','FOC_ME_RES_VLS']].sum(axis = 1)  
lim_df['Boiler_ls_lima'] =  lim_df[['FOC_BLR_RES_VLS','FOC_BLR_RES_ULS']] .sum(axis = 1)
 
lim_df['ME_uls_lima'] =  lim_df[['FOC_ME_DIS','FOC_ME_DIS_ULS','FOC_ME_DIS_VLS']].sum(axis = 1) 
lim_df['AUX_uls_lima'] =  lim_df[['FOC_AE_DIS','FOC_AE_DIS_ULS','FOC_AE_DIS_VLS']].sum(axis = 1) 
lim_df['Boiler_uls_lima'] =  lim_df[['FOC_BLR_DIS','FOC_BLR_DIS_ULS','FOC_BLR_DIS_VLS']] .sum(axis = 1)
 
lim_df['Total_ME_lima'] = lim_df[['ME_hs_lima','ME_ls_lima','ME_uls_lima']].sum(axis = 1)   
lim_df['Total_AUX_lima'] = lim_df[['AUX_hs_lima','AUX_ls_lima','AUX_uls_lima']].sum(axis = 1) 
lim_df['Total_Boiler_lima'] = lim_df[['Boiler_hs_lima','Boiler_ls_lima','Boiler_uls_lima']].sum(axis = 1)


lim_df["Total_HS"]=lim_df[['FOC_ME_RES_HS','FOC_AE_RES_HS',"FOC_BLR_RES_HS"]].sum(axis = 1) 
lim_df["Total_LS"]=lim_df[['FOC_ME_RES_ULS','FOC_ME_RES_VLS','FOC_ME_RES_ULS','FOC_ME_RES_VLS','FOC_BLR_RES_VLS','FOC_BLR_RES_ULS']].sum(axis = 1) 
lim_df["Total_ULS"]=lim_df[['FOC_ME_DIS','FOC_ME_DIS_ULS','FOC_ME_DIS_VLS','FOC_AE_DIS','FOC_AE_DIS_ULS','FOC_AE_DIS_VLS','FOC_BLR_DIS','FOC_BLR_DIS_ULS','FOC_BLR_DIS_VLS']].sum(axis = 1)

In [49]:
fuel_lim=lim_df[['ImoNumber','vName','Miles by gps','DateTimeUtc','Total_HS','Total_LS','Total_ULS','Total_ME_lima','Total_AUX_lima','Total_Boiler_lima']]

In [51]:
import pandas as pd

# Assuming 'fuel_lim' is your DataFrame containing fuel data
#fuel_lim = lim_df[['ImoNumber', 'vName', 'Miles by gps', 'DateTimeUtc', 'Total_ME_lima', 'Total_AUX_lima', 'Total_Boiler_lima']]

# Convert 'DateTimeUtc' column to datetime
fuel_lim['DateTimeUtc'] = pd.to_datetime(fuel_lim['DateTimeUtc'])

# Extracting the month from 'DateTimeUtc'
fuel_lim['month'] = fuel_lim['DateTimeUtc'].dt.month

# Grouping by 'ImoNumber' and 'month' and aggregating
fuel_lim_grouped = fuel_lim.groupby(['ImoNumber', 'month']).agg({
    'vName': 'first',  # Assuming 'vName' doesn't change within a month
    'Miles by gps': 'sum',
    'DateTimeUtc': 'first',
    'Total_HS':'sum',
    'Total_LS':'sum',
    'Total_ULS':'sum',
    'Total_ME_lima': 'sum',
    'Total_AUX_lima': 'sum',
    'Total_Boiler_lima': 'sum'
}).reset_index()

fuel_lim_grouped

C:\Users\akshaya\AppData\Local\Temp\ipykernel_131540\2432165454.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_lim['DateTimeUtc'] = pd.to_datetime(fuel_lim['DateTimeUtc'])
C:\Users\akshaya\AppData\Local\Temp\ipykernel_131540\2432165454.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_lim['month'] = fuel_lim['DateTimeUtc'].dt.month

,ImoNumber,month,vName,Miles by gps,DateTimeUtc,Total_HS,Total_LS,Total_ULS,Total_ME_lima,Total_AUX_lima,Total_Boiler_lima
0,7826790,8,GNV AZZURRA,222.0,2022-08-21,0.0,62.82,7.10,31.41,38.01,0.50
1,7826790,9,GNV AZZURRA,119.0,2022-09-05,0.0,33.62,4.18,16.81,20.69,0.30
2,7826790,10,GNV AZZURRA,0.0,2022-10-23,0.0,0.00,15.10,0.00,13.70,1.40
3,7826790,11,GNV AZZURRA,650.0,2022-11-02,0.0,154.78,93.66,77.39,160.00,11.05
4,7826790,12,GNV AZZURRA,0.0,2022-12-01,0.0,10.18,167.62,5.09,151.21,21.50
...,...,...,...,...,...,...,...,...,...,...,...
5012,9908059,12,MSC VIRGINIA,4959.0,2022-12-01,0.0,2456.10,79.70,1235.20,1247.25,53.35
5013,9927251,10,MSC FATMA,729.0,2022-10-26,0.0,166.50,12.67,86.00,89.62,3.55
5014,9927251,11,MSC FATMA,5230.0,2022-11-01,0.0,2338.64,181.59,1193.91,1301.68,24.64
5015,9927251,12,MSC FATMA,8653.0,2022-12-01,0.0,2933.52,112.12,1456.96,1567.65,21.03
5016,9927263,12,MSC AAYA,806.0,2022-12-21,0.0,199.94,61.60,99.97,132.97,28.60

In [52]:
import pandas as pd

# Assuming 'fuel_imodcs' is your DataFrame containing fuel data
fuel_lim['DateTimeUtc'] = pd.to_datetime(fuel_lim['DateTimeUtc'])

# Assigning a unique number to each date within each vessel's data
fuel_lim['Days_running_limasol'] = fuel_lim.groupby('ImoNumber').cumcount() + 1

# Modifying the assigned day numbers to ensure they don't exceed 365
fuel_lim['Days_running_limasol'] = fuel_lim['Days_running_limasol'].apply(lambda x: x % 365 if x <= 365 else x % 365 + 1)

# Grouping by 'IMO' and summing the modified assigned numbers to calculate days run
grouped_dates_lim = fuel_lim.groupby('ImoNumber')['Days_running_limasol'].agg(Days_running_limasol='max')
grouped_dates_lim['Lim_missing_days'] = 365 - grouped_dates_lim['Days_running_limasol']

grouped_dates_lim = grouped_dates_lim.reset_index()

grouped_dates_lim.head(7)

C:\Users\akshaya\AppData\Local\Temp\ipykernel_131540\569309145.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_lim['DateTimeUtc'] = pd.to_datetime(fuel_lim['DateTimeUtc'])
C:\Users\akshaya\AppData\Local\Temp\ipykernel_131540\569309145.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_lim['Days_running_limasol'] = fuel_lim.groupby('ImoNumber').cumcount() + 1
C:\Users\akshaya\AppData\Local\Temp\ipykernel_131540\569309145.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_lim['Days_running_limasol'] = fuel_lim['Days_running_limasol'].apply(lambda x: x % 365 if x <= 365 else x % 365 + 1)

  ImoNumber  Days_running_limasol  Lim_missing_days
0   7826790                    60               305
1   8201624                   365                 0
2   8201636                   365                 0
3   8201648                   365                 0
4   8413875                   364                 1
5   8413887                   364                 1
6   8420892                   364                 1

In [65]:
# Merging 'grouped_dates' DataFrame with 'fuel_imo_grouped_df' on the 'IMO' column
fuel_lim_grouped_df = pd.merge(fuel_lim_grouped, grouped_dates_lim, on='ImoNumber', how='left')

fuel_lim_grouped_df.head(7)

,ImoNumber,month,vName,Miles by gps,DateTimeUtc,Total_HS,Total_LS,Total_ULS,Total_ME_lima,Total_AUX_lima,Total_Boiler_lima,Days_running_limasol,Lim_missing_days
0,7826790,8,GNV AZZURRA,222.0,2022-08-21,0.0,62.82,7.10,31.41,38.01,0.50,60,305
1,7826790,9,GNV AZZURRA,119.0,2022-09-05,0.0,33.62,4.18,16.81,20.69,0.30,60,305
2,7826790,10,GNV AZZURRA,0.0,2022-10-23,0.0,0.00,15.10,0.00,13.70,1.40,60,305
3,7826790,11,GNV AZZURRA,650.0,2022-11-02,0.0,154.78,93.66,77.39,160.00,11.05,60,305
4,7826790,12,GNV AZZURRA,0.0,2022-12-01,0.0,10.18,167.62,5.09,151.21,21.50,60,305
5,8201624,1,MSC IRIS,2683.0,2022-01-01,0.0,453.94,108.42,226.97,304.32,31.07,365,0
6,8201624,2,MSC IRIS,4231.0,2022-02-01,0.0,614.60,86.76,309.30,382.60,9.46,365,0

In [66]:
fuel_lim_grouped_df=fuel_lim_grouped_df[['ImoNumber','vName',"month","DateTimeUtc",'Days_running_limasol','Lim_missing_days','Miles by gps',"Total_HS","Total_LS","Total_ULS","Total_ME_lima","Total_AUX_lima","Total_Boiler_lima"]]

In [67]:
fuel_imo_grouped_df=fuel_imo_month_grouped_df[["IMO",'month','Date_UTC','Days_running_imodcs','Missing_days_imodcs','Distance','ME_Consumption_HFO','ME_Consumption_LFO','AE_Consumption_HFO','AE_Consumption_LFO','Boiler_Consumption_HFO','Boiler_Consumption_LFO','MGO_MDO','Total_ME','Total_AE','Total_Boiler']]

In [68]:
result_df= fuel_imo_month_grouped_df.merge(fuel_lim_grouped_df, left_on=['IMO'], right_on=['ImoNumber'], how='inner')

result_df

,IMO,month_x,Date_UTC,Distance,ME_Consumption_HFO,ME_Consumption_LFO,AE_Consumption_HFO,AE_Consumption_LFO,Boiler_Consumption_HFO,Boiler_Consumption_LFO,...,DateTimeUtc,Days_running_limasol,Lim_missing_days,Miles by gps,Total_HS,Total_LS,Total_ULS,Total_ME_lima,Total_AUX_lima,Total_Boiler_lima
0,7826790,1,2022-01-01,711.32,0.0,101.97,0.0,0.00,0.0,0.0,...,2022-08-21,60,305,222.0,0.0,62.82,7.10,31.41,38.01,0.50
1,7826790,1,2022-01-01,711.32,0.0,101.97,0.0,0.00,0.0,0.0,...,2022-09-05,60,305,119.0,0.0,33.62,4.18,16.81,20.69,0.30
2,7826790,1,2022-01-01,711.32,0.0,101.97,0.0,0.00,0.0,0.0,...,2022-10-23,60,305,0.0,0.0,0.00,15.10,0.00,13.70,1.40
3,7826790,1,2022-01-01,711.32,0.0,101.97,0.0,0.00,0.0,0.0,...,2022-11-02,60,305,650.0,0.0,154.78,93.66,77.39,160.00,11.05
4,7826790,1,2022-01-01,711.32,0.0,101.97,0.0,0.00,0.0,0.0,...,2022-12-01,60,305,0.0,0.0,10.18,167.62,5.09,151.21,21.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58336,9927251,11,2022-11-01,5945.40,0.0,1169.32,0.0,57.09,0.0,0.0,...,2022-12-01,115,250,8653.0,0.0,2933.52,112.12,1456.96,1567.65,21.03
58337,9927251,12,2022-12-01,8748.90,0.0,1456.96,0.0,176.57,0.0,19.6,...,2022-10-26,115,250,729.0,0.0,166.50,12.67,86.00,89.62,3.55
58338,9927251,12,2022-12-01,8748.90,0.0,1456.96,0.0,176.57,0.0,19.6,...,2022-11-01,115,250,5230.0,0.0,2338.64,181.59,1193.91,1301.68,24.64
58339,9927251,12,2022-12-01,8748.90,0.0,1456.96,0.0,176.57,0.0,19.6,...,2022-12-01,115,250,8653.0,0.0,2933.52,112.12,1456.96,1567.65,21.03
58340,9927263,12,2022-12-21,854.00,0.0,99.97,0.0,0.00,0.0,0.0,...,2022-12-21,13,352,806.0,0.0,199.94,61.60,99.97,132.97,28.60

In [69]:
result_df['Diff_dist']=result_df['Miles by gps']-result_df['Distance']
result_df['Diff_ME']=result_df['Total_ME_lima']-result_df['Total_ME']
result_df['Diff_AUX']=result_df['Total_AUX_lima']-result_df['Total_AE']
result_df['Diff_Boiler']=result_df['Total_Boiler_lima']-result_df['Total_Boiler']

In [70]:
result_df.columns.to_list()

['IMO',
 'month_x',
 'Date_UTC',
 'Distance',
 'ME_Consumption_HFO',
 'ME_Consumption_LFO',
 'AE_Consumption_HFO',
 'AE_Consumption_LFO',
 'Boiler_Consumption_HFO',
 'Boiler_Consumption_LFO',
 'MGO_MDO',
 'Total_ME',
 'Total_AE',
 'Total_Boiler',
 'Days_running_imodcs',
 'Missing_days_imodcs',
 'ImoNumber',
 'vName',
 'month_y',
 'DateTimeUtc',
 'Days_running_limasol',
 'Lim_missing_days',
 'Miles by gps',
 'Total_HS',
 'Total_LS',
 'Total_ULS',
 'Total_ME_lima',
 'Total_AUX_lima',
 'Total_Boiler_lima',
 'Diff_dist',
 'Diff_ME',
 'Diff_AUX',
 'Diff_Boiler']

In [71]:
result_dc=result_df[['IMO','vName','month_x','DateTimeUtc','Days_running_imodcs','Missing_days_imodcs','Days_running_limasol','Lim_missing_days','Distance','Miles by gps',
'Diff_dist','Total_ME','Total_ME_lima','Diff_ME','Total_AE','Total_AUX_lima','Diff_AUX','Total_Boiler','Total_Boiler_lima','Diff_Boiler']]

In [72]:
result_dc.to_csv('result_dc_month.csv')

In [73]:
result=result_df[['IMO','vName','month_x','DateTimeUtc','Days_running_imodcs','Missing_days_imodcs','Days_running_limasol','Lim_missing_days','Distance','Miles by gps',
'Diff_dist','ME_Consumption_HFO','ME_Consumption_LFO','AE_Consumption_HFO','AE_Consumption_LFO','Boiler_Consumption_HFO','Boiler_Consumption_LFO','MGO_MDO','Total_ME','Total_AE','Total_Boiler','Total_HS',
 'Total_LS','Total_ULS','Total_ME_lima','Total_AUX_lima','Total_Boiler_lima','Diff_ME','Diff_AUX','Diff_Boiler']]

In [74]:
result.to_csv('result_month.csv')

In [ ]:
result_df.