In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
import string

In [3]:
df=pd.read_excel(r'D:\Navalt\MSC\2024\Weekly Data\CHARTER\CLIENT\MONTH\SEPT_2024_CHARTER.xlsx')

In [4]:
df.head()

,GID,VSL,IMO No,VOY,Corrected Date,REPORT DATE TIME,REPORT DATE TIME Offset,Report Type,Status,LAT,LONG,M E FOC,CARGO TOTAL,Has Cargo,STEAMING TIME,Total M E Hours Fuel Only,MILES BY GPS,OIL CYL,SPEED BY LOG,SPEED BY GPS,RPM,SLIP,WIND DIRECTION,WIND SPEED,DRAFT AFT,DRAFT FWD,DISPLACEMENT,COURSE AT SEA,WAVE HEIGHT,SEA DIRECTION,CARGO TOTAL TEU,AMBIENT TEMP,SW TEMP,MILES BY SPEED LOG,ETA PORT CODE,ETA DATE TIME,ETA DATE TIME Offset,ETA PORT,TIME CHANGE,TIME SEA,TEMP MIN,TEMP MAX,REQUESTED SPEED,REM DIST TO PILOT,REM TIME TO PILOT,TOTAL UNPLND STPGE TECH,TOTAL UNPLND STPGE OPE WX,REEFERS POSITIVE PLUGGED,REEFERS NEGATIVE PLUGGED,ME TOTAL REVS COUNTER,PORT CODE,PORT,AUX BLOWERS ON,HOLD VENTILATION ON,TIME HRS ANCHOR,TIME HRS DRIFT,REASON,TYPE OF DELAY,ETB DATE TIME,ETB DATE TIME Offset,PILOT DATE TIME,PILOT DATE TIME Offset,TIME MANOEUVRING,TUG ARR,TUG SHIFT,ETD DATE TIME,ETD DATE TIME Offset,SHIFT BERTH HOURS,CARGO LOAD,CARGO DISCH,TEU FULL,TEU EMPTY,BILGE REMOVED,GARBAGE REMOVED,GARBAGE REMVL REQSTD,GARBAGE REMVL CMPLSRY,FW SUPPLY,CY CREW SIGNED ON,CY CREW SIGNED OFF,CY DOCTORS VISIT,CY MAIL RECEIVED Ref NO,CY LUB OIL SAMPLE LANDED,CY CHECKD FOR STOWAWAYS,CY STOWAWAYS ON BOARD,CY DEP GM Mtr,CY REQUISITIONS RECEIVED,DISTANCE TO NEXT PILOT,TUG SAILING TRANSIT,STEAMING TIME M E Rsdl VLS,STEAMING TIME M E Rsdl HS,STEAMING TIME M E Rsdl ULS,STEAMING TIME M E Dstlt VLS,STEAMING TIME M E Dstlt ULS,STEAMING TIME M E Tnktnr Dstlt VLS,STEAMING TIME M E MDO,STEAMING TIME AUX 1,STEAMING TIME AUX 2,STEAMING TIME AUX 3,STEAMING TIME AUX 4,STEAMING TIME AUX 5,STEAMING TIME SH GEN,STEAMING TIME TG,FUEL M E Rsdl VLS,FUEL M E Rsdl HS,FUEL M E Rsdl ULS,FUEL M E Dstlt VLS,FUEL M E Dstlt ULS,FUEL M E MDO,FUEL M E LNG,FUEL M E Tnktnr Dstlt VLS,FUEL Aux Rsdl VLS,FUEL Aux Rsdl HS,FUEL Aux Rsdl ULS,FUEL Aux Dstlt VLS,FUEL Aux Dstlt ULS,FUEL Aux Tnktnr Dstlt VLS,FUEL Aux LNG,FUEL Aux MDO,FUEL Boiler Rsdl VLS,FUEL Boiler Rsdl HS,FUEL Boiler Rsdl ULS,FUEL Boiler Dstlt VLS,FUEL Boiler Dstlt ULS,FUEL Boiler Tnktnr Dstlt VLS,FUEL Boiler LNG,FUEL Boiler MDO,POWER KW,STEAMING LOAD KW AUX 1,STEAMING LOAD KW AUX 2,STEAMING LOAD KW AUX 3,STEAMING LOAD KW AUX 4,STEAMING LOAD KW AUX 5,STEAMING LOAD KW SH GEN,STEAMING LOAD KW TG,DECK LAST CHANGE USER,ENGINE LAST CHANGE USER,DECK PART IS COMPLETE,ENGINE PART IS COMPLETE,SCAVENGE PRESSURE,SECA ENTRY TIME,SECA ENTRY LAT,SECA ENTRY LONG,SECA EXIT TIME,SECA EXIT LAT,SECA EXIT LONG,ROB FRESH WATER,MANVRNG MILES BY GPS,MANVRNG MILES BY SPEED LOG,TANKTAINER TRANSFD QUANTITY,PILOT TAKEN,DATE TIME START TRANSIT,DATE TIME START TRANSIT Offset,DATE TIME END TRANSIT,DATE TIME END TRANSIT Offset,BALLAST,TANKTAINER NUMBER,STEAMING KWHR TOTAL,CY OTHERS,ROB FO SLUDGE,ROB LO SLUDGE,ROB BILGE,SLUDGE REMOVED FO,SLUDGE REMOVED LO,SEA STATE,CY LUB ADDED TO SYSTEM MECC,CY LUB ADDED TO SYSTEM AECC,CY LUB ADDED TO THRUSTERS,CY ME LO PURIFIER IN USE,CY BALLAST,CY BENDING MOMENT,CY SHEARING FORCE,CY TORTION MOMENT,CY SUPDT AUDITOR SIGNED ON,CY SUPDT AUDITOR SIGNED OFF,CY CASH RECEIVED,CY LUB OIL RECEIVED MECYL,CY LUB OIL RECEIVED MECC,CY LUB OIL RECEIVED AECC,CY M E UNDER PISTON TEMP,CY MAIL RECEIVED,WIND DIRECTION PORT STBD,SEA DIRECTION PORT STBD,TIME PILOT ONBOARD,GRADES ROB,SO2 CO2 RATIO,Bunker Order,Remarks,BDN Number,Fuel Type,Carbon Factor,Sulphur Content PC,Quantity,Port Delivery,Product Quality,Tanktainer Number_1,Supplier,Delivery,Vol Lt,Den,Vis,ROB Dstlt ULS,ROB Dstlt VLS,ROB Rsdl MDO,ROB Tnktnr Dstlt VLS,ROB Rsdl VLS,ROB Rsdl HS,ROB Rsdl ULS,ROB Rsdl LNG,ECA MILES,ECA TIME,EGCS DRY WASTE REMOVED,EGCS RUNNING TIME,EGCS WET SLURRY REMOVED,EGCS OPEN LOOP RUNNING TIME,EGCS CLOSED LOOP RUNNING TIME
0,60317d31-4c4d-43d7-876b-2f33e51aba38,AGIOS DIMITRIOS,9349605.0,IP434A,2024-09-01,2024-09-01 12:00:00,UTC +05:00,NOON,AT SEA,0151S,06734E,82.6,68806.0,True,24.0,24.0,414.199997,0.0,16.445833,17.258333,70.5,15.1,112.0,12.0,14.3,13.7,105028.9,206.0,3.37,152.92,5207.0,31.0,29.0,394.7,MUPLU,2024-09-04 12:00:00,UTC +04:00,PORT LOUIS,NaN,24.0,319.0,347.0,17.50,1260.7,72.0,0.0,0.0,7.0,16.0,203125380.0,INMUN,MUNDRA,False,False,NaN,NaN,WAITING FOR SCHEDULE,NaN,2024-08-26 12:00:00,UTC +05:30,NaT,NaN,NaN,NaN,NaN,2024-08-28 04:30:00,UTC +05:30,NaN,NaN,NaN,5184.0,23.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,82.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.2,0.0,0.0,0.0,0.0,0.0,0.0,1.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16921.0,787.0,0.0,756.0,0.0,0.0,0.0,0.0,"SORIANO, DOMINADOR","DEREVIANKO, YURII",True,True,0.69,NaN,NaN,NaN,NaN,NaN,NaN,218.1,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8752.0,0,1500.0,NaN,NaN,NaN,78.2,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,190.9,664.3,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
1,a2bdb2d1-315a-4ded-a8a3-09b823a77d40,AGIOS DIMITRIOS,9349605.0,IP434A,2024-09-02,2024-09-02 12:00:00,UTC +05:00,NOON,AT SEA,0813S,06439E,82.1,68806.0,True,24.0,24.0,418.100006,0.0,16.287500,17.420833,70.1,13.8,90.0,15.0,14.3,13.7,104947.4,198.0,2.98,139.27,5207.0,29.0,27.0,390.9,MUPLU,2024-09-04 12:00:00,UTC +04:00,PORT LOUIS,NaN,24.0,317.0,343.0,17.56,843.0,48.0,0.0,0.0,7.0,16.0,203226330.0,INMUN,MUNDRA,False,False,NaN,NaN,WAITING FOR SCHEDULE,NaN,2024-08-26 12:00:00,UTC +05:30,NaT,NaN,NaN,NaN,NaN,2024-08-28 04:30:00,UTC +05:30,NaN,NaN,NaN,5184.0,23.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,82.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.4,0.0,0.0,0.0,0.0,0.0,0.0,1.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16839.0,749.0,0.0,750.0,0.0,0.0,0.0,0.0,"SORIANO, DOMINADOR","DEREVIANKO, YURII",True,True,0.67,NaN,NaN,NaN,NaN,NaN,NaN,229.7,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8752.0,0,1500.0,NaN,NaN,NaN,46.6,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,189.3,572.8,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
2,8c9d6f41-23c2-4866-abf7-ce2b58c80327,AGIOS DIMITRIOS,9349605.0,IP434A,2024-09-03,2024-09-03 12:00:00,UTC +04:00,NOON,AT SEA,1445S,06131E,85.5,68806.0,True,25.0,25.0,431.200012,0.0,15.808000,17.248000,70.2,14.1,92.0,18.0,14.3,13.7,104854.6,203.0,3.63,134.82,5207.0,26.0,24.0,395.2,MUPLU,2024-09-04 12:00:00,UTC +04:00,PORT LOUIS,NaN,25.0,314.0,334.0,17.15,411.8,24.0,0.0,0.0,7.0,16.0,203331700.0,INMUN,MUNDRA,False,False,NaN,NaN,WAITING FOR SCHEDULE,NaN,2024-08-26 12:00:00,UTC +05:30,NaT,NaN,NaN,NaN,NaN,2024-08-28 04:30:00,UTC +05:30,NaN,NaN,NaN,5184.0,23.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,25.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,85.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,1.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16887.0,778.0,0.0,801.0,0.0,0.0,0.0,0.0,"SORIANO, DOMINADOR","DEREVIANKO, YURII",True,True,0.68,NaN,NaN,NaN,NaN,NaN,NaN,233.9,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8752.0,0,1550.0,NaN,NaN,NaN,35.8,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,187.8,477.3,0.0,0.0,0.0,0.0,NaN,25.0,NaN,25.0,0.0
3,6df7e111-d94e-4d1c-acfe-027d4a1092b6,AGIOS DIMITRIOS,9349605.0,IP434A,2024-09-04,2024-09-04 11:00:00,UTC +04:00,EOSP,AT SEA,1956S,05725E,77.0,68806.0,True,23.0,23.0,396.400013,0.0,16.156522,17.234783,71.3,15.8,45.0,14.0,14.3,13.7,104771.9,186.0,0.86,126.54,5207.0,24.0,23.0,371.6,MUPLU,2024-09-04 12:00:00,UTC +04:00,NaN,NaN,23.0,303.0,325.0,17.15,NaN,NaN,0.0,0.0,7.0,16.0,203429800.0,MUPLU,PORT LOUIS,False,False,NaN,NaN,WAITING FOR SCHEDULE,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,2024-08-28 04:30:00,UTC +05:30,NaN,NaN,NaN,5184.0,23.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,23.0,0.0,0.0,0.0,0.0,0.0,1.2,22.2,23.0,0.0,0.0,0.0,0.0,17.2,59.8,0.0,0.0,0.0,0.0,0.0,0.0,1.8,7.1,0.0,0.0,1.0,0.0,0.0,0.0,0.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16498.0,0.0,645.0,649.0,0.0,0.0,0.0,0.0,"SORIANO, DOMINADOR","DEREVIANKO, YURII",True,True,0.54,NaN,NaN,NaN,NaN,NaN,NaN,238.8,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8752.0,0,1300.0,NaN,NaN,NaN,41.1,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,584.8,0.0,0.0,0.0,168.1,410.4,0.0,0.0,0.0,0.0,NaN,NaN,NaN,23.0,NaN
4,61f26af2-e334-4ea1-830e-b2d314c5e087,AGIOS DIMITRIOS,9349605.0,IP434A,2024-09-04,2024-09-04 12:00:00,UTC +04:00,DLY A,DRIFTING,2007S,05723E,0.7,68806.0,True,1.0,1.0,11.200000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,14.3,13.7,104770.9,0.0,0.00,0.00,5207.0,24.0,23.0,NaN,MUPLU,2024-09-04 12:00:00,UTC +04:00,NaN,NaN,1.0,77.0,77.0,17.15,NaN,NaN,0.0,0.0,7.0,16.0,203431260.0,MUPLU,PORT LOUIS,False,False,0.0,0.0,WAITING FOR SCHEDULE,DRIFTING,NaT,NaN,NaT,NaN,1.0,NaN,NaN,2024-09-05 12:00:00,UTC +04:00,NaN,NaN,NaN,5184.0,23.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2598.0,0.0,529.0,550.0,0.0,0.0,0.0,0.0,"SORIANO, DOMINADOR","DEREVIANKO, YURII",True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,238.8,11.2,10.7,NaN,False,NaT,NaN,NaT,NaN,8752.0,0,1100.0,NaN,NaN,NaN,41.1,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,167.1,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0

In [7]:
cf=df.copy()

In [9]:
cf.shape

(135338, 215)

In [11]:
cf.duplicated('GID').sum()

38656

In [13]:
cf=cf.drop_duplicates('GID')

In [14]:
cf.duplicated('GID').sum()

0

In [17]:
cf

,GID,VSL,IMO No,VOY,Corrected Date,REPORT DATE TIME,REPORT DATE TIME Offset,Report Type,Status,LAT,LONG,M E FOC,CARGO TOTAL,Has Cargo,STEAMING TIME,Total M E Hours Fuel Only,MILES BY GPS,OIL CYL,SPEED BY LOG,SPEED BY GPS,RPM,SLIP,WIND DIRECTION,WIND SPEED,DRAFT AFT,DRAFT FWD,DISPLACEMENT,COURSE AT SEA,WAVE HEIGHT,SEA DIRECTION,CARGO TOTAL TEU,AMBIENT TEMP,SW TEMP,MILES BY SPEED LOG,ETA PORT CODE,ETA DATE TIME,ETA DATE TIME Offset,ETA PORT,TIME CHANGE,TIME SEA,TEMP MIN,TEMP MAX,REQUESTED SPEED,REM DIST TO PILOT,REM TIME TO PILOT,TOTAL UNPLND STPGE TECH,TOTAL UNPLND STPGE OPE WX,REEFERS POSITIVE PLUGGED,REEFERS NEGATIVE PLUGGED,ME TOTAL REVS COUNTER,PORT CODE,PORT,AUX BLOWERS ON,HOLD VENTILATION ON,TIME HRS ANCHOR,TIME HRS DRIFT,REASON,TYPE OF DELAY,ETB DATE TIME,ETB DATE TIME Offset,PILOT DATE TIME,PILOT DATE TIME Offset,TIME MANOEUVRING,TUG ARR,TUG SHIFT,ETD DATE TIME,ETD DATE TIME Offset,SHIFT BERTH HOURS,CARGO LOAD,CARGO DISCH,TEU FULL,TEU EMPTY,BILGE REMOVED,GARBAGE REMOVED,GARBAGE REMVL REQSTD,GARBAGE REMVL CMPLSRY,FW SUPPLY,CY CREW SIGNED ON,CY CREW SIGNED OFF,CY DOCTORS VISIT,CY MAIL RECEIVED Ref NO,CY LUB OIL SAMPLE LANDED,CY CHECKD FOR STOWAWAYS,CY STOWAWAYS ON BOARD,CY DEP GM Mtr,CY REQUISITIONS RECEIVED,DISTANCE TO NEXT PILOT,TUG SAILING TRANSIT,STEAMING TIME M E Rsdl VLS,STEAMING TIME M E Rsdl HS,STEAMING TIME M E Rsdl ULS,STEAMING TIME M E Dstlt VLS,STEAMING TIME M E Dstlt ULS,STEAMING TIME M E Tnktnr Dstlt VLS,STEAMING TIME M E MDO,STEAMING TIME AUX 1,STEAMING TIME AUX 2,STEAMING TIME AUX 3,STEAMING TIME AUX 4,STEAMING TIME AUX 5,STEAMING TIME SH GEN,STEAMING TIME TG,FUEL M E Rsdl VLS,FUEL M E Rsdl HS,FUEL M E Rsdl ULS,FUEL M E Dstlt VLS,FUEL M E Dstlt ULS,FUEL M E MDO,FUEL M E LNG,FUEL M E Tnktnr Dstlt VLS,FUEL Aux Rsdl VLS,FUEL Aux Rsdl HS,FUEL Aux Rsdl ULS,FUEL Aux Dstlt VLS,FUEL Aux Dstlt ULS,FUEL Aux Tnktnr Dstlt VLS,FUEL Aux LNG,FUEL Aux MDO,FUEL Boiler Rsdl VLS,FUEL Boiler Rsdl HS,FUEL Boiler Rsdl ULS,FUEL Boiler Dstlt VLS,FUEL Boiler Dstlt ULS,FUEL Boiler Tnktnr Dstlt VLS,FUEL Boiler LNG,FUEL Boiler MDO,POWER KW,STEAMING LOAD KW AUX 1,STEAMING LOAD KW AUX 2,STEAMING LOAD KW AUX 3,STEAMING LOAD KW AUX 4,STEAMING LOAD KW AUX 5,STEAMING LOAD KW SH GEN,STEAMING LOAD KW TG,DECK LAST CHANGE USER,ENGINE LAST CHANGE USER,DECK PART IS COMPLETE,ENGINE PART IS COMPLETE,SCAVENGE PRESSURE,SECA ENTRY TIME,SECA ENTRY LAT,SECA ENTRY LONG,SECA EXIT TIME,SECA EXIT LAT,SECA EXIT LONG,ROB FRESH WATER,MANVRNG MILES BY GPS,MANVRNG MILES BY SPEED LOG,TANKTAINER TRANSFD QUANTITY,PILOT TAKEN,DATE TIME START TRANSIT,DATE TIME START TRANSIT Offset,DATE TIME END TRANSIT,DATE TIME END TRANSIT Offset,BALLAST,TANKTAINER NUMBER,STEAMING KWHR TOTAL,CY OTHERS,ROB FO SLUDGE,ROB LO SLUDGE,ROB BILGE,SLUDGE REMOVED FO,SLUDGE REMOVED LO,SEA STATE,CY LUB ADDED TO SYSTEM MECC,CY LUB ADDED TO SYSTEM AECC,CY LUB ADDED TO THRUSTERS,CY ME LO PURIFIER IN USE,CY BALLAST,CY BENDING MOMENT,CY SHEARING FORCE,CY TORTION MOMENT,CY SUPDT AUDITOR SIGNED ON,CY SUPDT AUDITOR SIGNED OFF,CY CASH RECEIVED,CY LUB OIL RECEIVED MECYL,CY LUB OIL RECEIVED MECC,CY LUB OIL RECEIVED AECC,CY M E UNDER PISTON TEMP,CY MAIL RECEIVED,WIND DIRECTION PORT STBD,SEA DIRECTION PORT STBD,TIME PILOT ONBOARD,GRADES ROB,SO2 CO2 RATIO,Bunker Order,Remarks,BDN Number,Fuel Type,Carbon Factor,Sulphur Content PC,Quantity,Port Delivery,Product Quality,Tanktainer Number_1,Supplier,Delivery,Vol Lt,Den,Vis,ROB Dstlt ULS,ROB Dstlt VLS,ROB Rsdl MDO,ROB Tnktnr Dstlt VLS,ROB Rsdl VLS,ROB Rsdl HS,ROB Rsdl ULS,ROB Rsdl LNG,ECA MILES,ECA TIME,EGCS DRY WASTE REMOVED,EGCS RUNNING TIME,EGCS WET SLURRY REMOVED,EGCS OPEN LOOP RUNNING TIME,EGCS CLOSED LOOP RUNNING TIME
0,60317d31-4c4d-43d7-876b-2f33e51aba38,AGIOS DIMITRIOS,9349605.0,IP434A,2024-09-01,2024-09-01 12:00:00,UTC +05:00,NOON,AT SEA,0151S,06734E,82.60,68806.0,True,24.0,24.0,414.199997,0.0,16.445833,17.258333,70.5,15.1,112.0,12.0,14.3,13.7,105028.9,206.0,3.37,152.92,5207.0,31.0,29.0,394.7,MUPLU,2024-09-04 12:00:00,UTC +04:00,PORT LOUIS,NaN,24.0,319.0,347.0,17.50,1260.7,72.0,0.0,0.0,7.0,16.0,203125380.0,INMUN,MUNDRA,False,False,NaN,NaN,WAITING FOR SCHEDULE,NaN,2024-08-26 12:00:00,UTC +05:30,NaT,NaN,NaN,NaN,NaN,2024-08-28 04:30:00,UTC +05:30,NaN,NaN,NaN,5184.0,23.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,24.0,0.0,0.0,0.0,0.0,0.00,82.6,0.0,0.0,0.0,0.0,0.0,0.0,0.00,9.2,0.0,0.0,0.00,0.0,0.0,0.0,1.5,0.0,0.0,0.0,0.00,0.0,0.0,0.0,16921.0,787.0,0.0,756.0,0.0,0.0,0.0,0.0,"SORIANO, DOMINADOR","DEREVIANKO, YURII",True,True,0.69,NaN,NaN,NaN,NaN,NaN,NaN,218.1,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8752.0,0,1500.0,NaN,NaN,NaN,78.2,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,190.90,664.3,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
1,a2bdb2d1-315a-4ded-a8a3-09b823a77d40,AGIOS DIMITRIOS,9349605.0,IP434A,2024-09-02,2024-09-02 12:00:00,UTC +05:00,NOON,AT SEA,0813S,06439E,82.10,68806.0,True,24.0,24.0,418.100006,0.0,16.287500,17.420833,70.1,13.8,90.0,15.0,14.3,13.7,104947.4,198.0,2.98,139.27,5207.0,29.0,27.0,390.9,MUPLU,2024-09-04 12:00:00,UTC +04:00,PORT LOUIS,NaN,24.0,317.0,343.0,17.56,843.0,48.0,0.0,0.0,7.0,16.0,203226330.0,INMUN,MUNDRA,False,False,NaN,NaN,WAITING FOR SCHEDULE,NaN,2024-08-26 12:00:00,UTC +05:30,NaT,NaN,NaN,NaN,NaN,2024-08-28 04:30:00,UTC +05:30,NaN,NaN,NaN,5184.0,23.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,24.0,0.0,0.0,0.0,0.0,0.00,82.1,0.0,0.0,0.0,0.0,0.0,0.0,0.00,9.4,0.0,0.0,0.00,0.0,0.0,0.0,1.6,0.0,0.0,0.0,0.00,0.0,0.0,0.0,16839.0,749.0,0.0,750.0,0.0,0.0,0.0,0.0,"SORIANO, DOMINADOR","DEREVIANKO, YURII",True,True,0.67,NaN,NaN,NaN,NaN,NaN,NaN,229.7,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8752.0,0,1500.0,NaN,NaN,NaN,46.6,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,189.30,572.8,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
2,8c9d6f41-23c2-4866-abf7-ce2b58c80327,AGIOS DIMITRIOS,9349605.0,IP434A,2024-09-03,2024-09-03 12:00:00,UTC +04:00,NOON,AT SEA,1445S,06131E,85.50,68806.0,True,25.0,25.0,431.200012,0.0,15.808000,17.248000,70.2,14.1,92.0,18.0,14.3,13.7,104854.6,203.0,3.63,134.82,5207.0,26.0,24.0,395.2,MUPLU,2024-09-04 12:00:00,UTC +04:00,PORT LOUIS,NaN,25.0,314.0,334.0,17.15,411.8,24.0,0.0,0.0,7.0,16.0,203331700.0,INMUN,MUNDRA,False,False,NaN,NaN,WAITING FOR SCHEDULE,NaN,2024-08-26 12:00:00,UTC +05:30,NaT,NaN,NaN,NaN,NaN,2024-08-28 04:30:00,UTC +05:30,NaN,NaN,NaN,5184.0,23.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,25.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0,25.0,0.0,0.0,0.0,0.0,0.00,85.5,0.0,0.0,0.0,0.0,0.0,0.0,0.00,10.0,0.0,0.0,0.00,0.0,0.0,0.0,1.5,0.0,0.0,0.0,0.00,0.0,0.0,0.0,16887.0,778.0,0.0,801.0,0.0,0.0,0.0,0.0,"SORIANO, DOMINADOR","DEREVIANKO, YURII",True,True,0.68,NaN,NaN,NaN,NaN,NaN,NaN,233.9,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8752.0,0,1550.0,NaN,NaN,NaN,35.8,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,187.80,477.3,0.0,0.0,0.0,0.0,NaN,25.0,NaN,25.0,0.0
3,6df7e111-d94e-4d1c-acfe-027d4a1092b6,AGIOS DIMITRIOS,9349605.0,IP434A,2024-09-04,2024-09-04 11:00:00,UTC +04:00,EOSP,AT SEA,1956S,05725E,77.00,68806.0,True,23.0,23.0,396.400013,0.0,16.156522,17.234783,71.3,15.8,45.0,14.0,14.3,13.7,104771.9,186.0,0.86,126.54,5207.0,24.0,23.0,371.6,MUPLU,2024-09-04 12:00:00,UTC +04:00,NaN,NaN,23.0,303.0,325.0,17.15,NaN,NaN,0.0,0.0,7.0,16.0,203429800.0,MUPLU,PORT LOUIS,False,False,NaN,NaN,WAITING FOR SCHEDULE,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,2024-08-28 04:30:00,UTC +05:30,NaN,NaN,NaN,5184.0,23.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,23.0,0.0,0.0,0.0,0.0,0.0,1.2,22.2,23.0,0.0,0.0,0.0,0.0,17.20,59.8,0.0,0.0,0.0,0.0,0.0,0.0,1.80,7.1,0.0,0.0,1.00,0.0,0.0,0.0,0.7,0.0,0.0,0.0,0.00,0.0,0.0,0.0,16498.0,0.0,645.0,649.0,0.0,0.0,0.0,0.0,"SORIANO, DOMINADOR","DEREVIANKO, YURII",True,True,0.54,NaN,NaN,NaN,NaN,NaN,NaN,238.8,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8752.0,0,1300.0,NaN,NaN,NaN,41.1,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,584.80,0.0,0.0,0.0,168.10,410.4,0.0,0.0,0.0,0.0,NaN,NaN,NaN,23.0,NaN
4,61f26af2-e334-4ea1-830e-b2d314c5e087,AGIOS DIMITRIOS,9349605.0,IP434A,2024-09-04,2024-09-04 12:00:00,UTC +04:00,DLY A,DRIFTING,2007S,05723E,0.70,68806.0,True,1.0,1.0,11.200000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,14.3,13.7,104770.9,0.0,0.00,0.00,5207.0,24.0,23.0,NaN,MUPLU,2024-09-04 12:00:00,UTC +04:00,NaN,NaN,1.0,77.0,77.0,17.15,NaN,NaN,0.0,0.0,7.0,16.0,203431260.0,MUPLU,PORT LOUIS,False,False,0.0,0.0,WAITING FOR SCHEDULE,DRIFTING,NaT,NaN,NaT,NaN,1.0,NaN,NaN,2024-09-05 12:00:00,UTC +04:00,NaN,NaN,NaN,5184.0,23.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.70,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.20,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.1,0.0,0.0,0.0,0.00,0.0,0.0,0.0,2598.0,0.0,529.0,550.0,0.0,0.0,0.0,0.0,"SORIANO, DOMINADOR","DEREVIANKO, YURII",True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,238.8,11.2,10.7,NaN,False,NaT,NaN,NaT,NaN,8752.0,0,1100.0,NaN,NaN,NaN,41.1,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,167.10,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135255,3e92dec8-7bdd-4b93-a636-55153e51a23c,WEC VAN RUYSDAEL,9287792.0,EL439A,2024-10-01,2024-09-30 15:00:00,UTC +02:00,SAIL,IN PORT,4329N,00308W,0.07,6534.0,True,0.3,0.3,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,7.3,7.3,13923.0,0.0,0.00,0.00,526.0,17.0,18.0,NaN,IEDUB,2024-10-02 16:00:00,UTC +02:00,DUBLIN,NaN,3.0,415.0,450.0,15.00,NaN,NaN,0.0,0.0,9.0,0.0,9000.0,ESBIO,BILBAO,False,False,NaN,NaN,Berth Occupied,NaN,2024-09-30 07:00:00,UTC +02:00,NaT,NaN,NaN,NaN,0.0,2024-09-30 14:00:00,UTC +02:00,NaN,2563.0,0.0,514.0,12.0,0,NaN,False,False,0.0,0,0,No,0,0,0,0,0.99,0,NaN,NaN,0.3,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.5,0.0,0.0,0.0,0.3,0.0,0.07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.05,0.0,0.0,0.0,1138.0,140.0,100.0,0.0,0.0,0.0,200.0,0.0,Master,Ch Eng,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.0,NaN,NaN,0.0,False,NaT,NaN,NaT,NaN,1477.0,0,530.0,NaN,NaN,NaN,1.1,NaN,NaN,0.0,0.0,0.0,0.0,1,NaN,89.0,70.0,25.0,0,0,0.0,0.0,0.0,0.0,NaN,False,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,262.82,0.0,0.0,0.0,344.39,0.0,0.0,0.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN
135256,4c897b0e-5851-4f59-a709-5dda42e04d75,WEC VAN RUYSDAEL,9287792.0,EL439A,2024-10-01,2024-09-30 15:48:00,UTC +02:00,COSP,DRIFTING,4324N,00305W,0.58,6534.0,True,0.8,0.8,5.000000,0.0,0.000000,0.000000,0.0,0.0,10.0,10.0,7.3,7.3,13923.0,320.0,0.56,10.00,526.0,17.0,18.0,NaN,IEDUB,2024-10-02 16:00:00,UTC +02:00,DUBLIN,NaN,0.8,415.0,450.0,15.00,NaN,NaN,0.0,0.0,9.0,0.0,24000.0,ESBIO,BILBAO,False,False,NaN,NaN,Berth Occupied,NaN,2024-09-30 07:00:00,UTC +02:00,NaT,NaN,0.7,NaN,NaN,2024-09-30 14:00:00,UTC +02:00,NaN,NaN,NaN,514.0,12.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,671.0,0,0.8,0.0,0.0,0.0,0.0,0.0,0.0,0.8,0.8,0.0,0.0,0.0,0.8,0.0,0.58,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,3625.0,100.0,100.0,0.0,0.0,0.0,200.0,0.0,Master,Ch Eng,True,True,0.80,NaN,NaN,NaN,NaN,NaN,NaN,55.0,5.0,5.0,NaN,True,2024-09-30 15:48:00,UTC +02:00,NaT,NaN,1477.0,0,320.0,NaN,NaN,NaN,1.1,NaN,NaN,3.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,0.5,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,262.78,0.0,0.0,0.0,343.81,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135301,036417e3-26a6-41ec-91d6-491b482d4e47,WEC VERMEER,9237371.0,EF439A,2024-09-30,2024-09-30 12:00:00,UTC +02:00,NOON,AT SEA,3434N,00808W,28.38,5338.4,True,24.0,24.0,400.999969,0.0,16.958333,16.708333,128.0,0.0,60.0,14.0,7.6,7.2,12753.3,228.0,1.36,128.69,542.0,22.0,22.0,407.0,ESSCT,2024-10-02 00:00:00,UTC +02:00,SANTA CRUZ DE TENERIFE,NaN,24.0,409.0,430.0,15.30,552.0,36.0,0.0,0.0,2.0,5.0,121686.0,ESVLC,VALENCIA,False,False,NaN,NaN,AHEAD OF SCHEDULE,NaN,2024-09-28 16:42:00,UTC +02:00,NaT,NaN,NaN,NaN,NaN,2024-09-29 01:00:00,UTC +02:00,NaN,NaN,NaN,541.0,1.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,28.38,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,6254.7,0.0,0.0,0.0,0.0,0.0,270.0,0.0,2O,CE,True,True,2.37,NaN,NaN,NaN,NaN,NaN,NaN,61.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,2369.0,NaN,0.0,NaN,NaN,NaN,0.1,NaN,NaN,4.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,337.74,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
135336,0aa0ae08-2574-4470-ae5b-d8b97da2ce81,XIN BIN ZHOU,9185413.0,HD438R,2024-09-30,2024-09-29 12:42:00,UTC +08:00,COSP,DRIFTING,0116N,10407E,4.63,1895.0,True,3.7,3.7,55.000000,0.0,0.000000,0.000000,0.0,0.0,20.0,10.0,7.9,3.7,20524.0,80.0,0.56,20.00,99.0,35.0,29.0,NaN,CNFOC,2024-10-04 12:00:00,UTC +08:00,FUZHOU,NaN,3.7,340.0,370.0,9.00,NaN,NaN,0.0,0.0,1.0,1.0,0.0,MYTPP,TANJUNG PELEPAS,False,False,NaN,NaN,DRIFTINGING FOR BERTH,NaN,2024-09-28 21:30:00,UTC +08:00,NaT,NaN,3.7,NaN,NaN,2024-09-29 11:00:00,UTC +08:00,NaN,NaN,NaN,92.0,7.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1728.0,0,3.7,0.0,0.0,0.0,0.0,0.0,0.0,3.7,0.0,3.7,0.0,0.0,0.0,0.0,4.63,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.62,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.13,0.0,0.0,0.0,8694.0,450.0,0.0,450.0,0.0,0.0,0.0,0.0,NaN,NaN,True,True,0.04,NaN,NaN,NaN,NaN,NaN,NaN,85.0,55.0,55.0,NaN,True,NaT,NaN,NaT,NaN,3822.0,0,0.0,NaN,NaN,NaN,19.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,1.0,NaN,0.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,161.38,0.0,0.0,0.0,731.19,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135337,910af70d-9d59-4e60-9d0e-3379c5f32898,XIN BIN ZHOU,9185413.0,HD438R,2024-09-30,2024-09-30 12:00:00,UTC +08:00,NOON,AT SEA,0554N,10649E,23.71,1895.0,True,23.3,23.3,328.000003,0.0,14.077253,14.077253,0.0,0.0,180.0,10.0,7.9,3.7,20524.0,27.0,3.27,180.01,99.0,35.0,29.0,328.0,CNFOC,2024-10-04 18:00:00,UTC +08:00,FUZHOU,NaN,23.3,310.0,340.0,13.50,1400.0,104.0,0.0,0.0,1.0,1.0,0.0,MYTPP,TANJUNG PELEPAS,True,False,NaN,NaN,DRIFTINGING FOR BERTH,NaN,2024-09-28 21:30:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2024-09-29 11:00:00,UTC +08:00,NaN,NaN,NaN,92.0,7.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.3,0.0,0.0,0.0,23.3,23.71,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.91,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,5216.0,0.0,0.0,650.0,0.0,0.0,0.0,0.0,NaN,NaN,True,True,0.02,NaN,NaN,NaN,NaN,NaN,NaN,82.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,3822.0,0,0.0,NaN,NaN,NaN,19.0,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,704.57,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN

columns_of_interest = ['GID']
duplicates = df.duplicated()
duplicate_rows = df[duplicates]
print(duplicate_rows)
duplicate_rows.to_csv('D.csv', index=False)
#df.drop_duplicates(inplace=True)

In [19]:
cf.shape

(96682, 215)

## SND removal

In [23]:
cf.drop(cf[cf['Report Type'] == 'SND'].index, inplace=True)

In [24]:
cf.head()

,GID,VSL,IMO No,VOY,Corrected Date,REPORT DATE TIME,REPORT DATE TIME Offset,Report Type,Status,LAT,LONG,M E FOC,CARGO TOTAL,Has Cargo,STEAMING TIME,Total M E Hours Fuel Only,MILES BY GPS,OIL CYL,SPEED BY LOG,SPEED BY GPS,RPM,SLIP,WIND DIRECTION,WIND SPEED,DRAFT AFT,DRAFT FWD,DISPLACEMENT,COURSE AT SEA,WAVE HEIGHT,SEA DIRECTION,CARGO TOTAL TEU,AMBIENT TEMP,SW TEMP,MILES BY SPEED LOG,ETA PORT CODE,ETA DATE TIME,ETA DATE TIME Offset,ETA PORT,TIME CHANGE,TIME SEA,TEMP MIN,TEMP MAX,REQUESTED SPEED,REM DIST TO PILOT,REM TIME TO PILOT,TOTAL UNPLND STPGE TECH,TOTAL UNPLND STPGE OPE WX,REEFERS POSITIVE PLUGGED,REEFERS NEGATIVE PLUGGED,ME TOTAL REVS COUNTER,PORT CODE,PORT,AUX BLOWERS ON,HOLD VENTILATION ON,TIME HRS ANCHOR,TIME HRS DRIFT,REASON,TYPE OF DELAY,ETB DATE TIME,ETB DATE TIME Offset,PILOT DATE TIME,PILOT DATE TIME Offset,TIME MANOEUVRING,TUG ARR,TUG SHIFT,ETD DATE TIME,ETD DATE TIME Offset,SHIFT BERTH HOURS,CARGO LOAD,CARGO DISCH,TEU FULL,TEU EMPTY,BILGE REMOVED,GARBAGE REMOVED,GARBAGE REMVL REQSTD,GARBAGE REMVL CMPLSRY,FW SUPPLY,CY CREW SIGNED ON,CY CREW SIGNED OFF,CY DOCTORS VISIT,CY MAIL RECEIVED Ref NO,CY LUB OIL SAMPLE LANDED,CY CHECKD FOR STOWAWAYS,CY STOWAWAYS ON BOARD,CY DEP GM Mtr,CY REQUISITIONS RECEIVED,DISTANCE TO NEXT PILOT,TUG SAILING TRANSIT,STEAMING TIME M E Rsdl VLS,STEAMING TIME M E Rsdl HS,STEAMING TIME M E Rsdl ULS,STEAMING TIME M E Dstlt VLS,STEAMING TIME M E Dstlt ULS,STEAMING TIME M E Tnktnr Dstlt VLS,STEAMING TIME M E MDO,STEAMING TIME AUX 1,STEAMING TIME AUX 2,STEAMING TIME AUX 3,STEAMING TIME AUX 4,STEAMING TIME AUX 5,STEAMING TIME SH GEN,STEAMING TIME TG,FUEL M E Rsdl VLS,FUEL M E Rsdl HS,FUEL M E Rsdl ULS,FUEL M E Dstlt VLS,FUEL M E Dstlt ULS,FUEL M E MDO,FUEL M E LNG,FUEL M E Tnktnr Dstlt VLS,FUEL Aux Rsdl VLS,FUEL Aux Rsdl HS,FUEL Aux Rsdl ULS,FUEL Aux Dstlt VLS,FUEL Aux Dstlt ULS,FUEL Aux Tnktnr Dstlt VLS,FUEL Aux LNG,FUEL Aux MDO,FUEL Boiler Rsdl VLS,FUEL Boiler Rsdl HS,FUEL Boiler Rsdl ULS,FUEL Boiler Dstlt VLS,FUEL Boiler Dstlt ULS,FUEL Boiler Tnktnr Dstlt VLS,FUEL Boiler LNG,FUEL Boiler MDO,POWER KW,STEAMING LOAD KW AUX 1,STEAMING LOAD KW AUX 2,STEAMING LOAD KW AUX 3,STEAMING LOAD KW AUX 4,STEAMING LOAD KW AUX 5,STEAMING LOAD KW SH GEN,STEAMING LOAD KW TG,DECK LAST CHANGE USER,ENGINE LAST CHANGE USER,DECK PART IS COMPLETE,ENGINE PART IS COMPLETE,SCAVENGE PRESSURE,SECA ENTRY TIME,SECA ENTRY LAT,SECA ENTRY LONG,SECA EXIT TIME,SECA EXIT LAT,SECA EXIT LONG,ROB FRESH WATER,MANVRNG MILES BY GPS,MANVRNG MILES BY SPEED LOG,TANKTAINER TRANSFD QUANTITY,PILOT TAKEN,DATE TIME START TRANSIT,DATE TIME START TRANSIT Offset,DATE TIME END TRANSIT,DATE TIME END TRANSIT Offset,BALLAST,TANKTAINER NUMBER,STEAMING KWHR TOTAL,CY OTHERS,ROB FO SLUDGE,ROB LO SLUDGE,ROB BILGE,SLUDGE REMOVED FO,SLUDGE REMOVED LO,SEA STATE,CY LUB ADDED TO SYSTEM MECC,CY LUB ADDED TO SYSTEM AECC,CY LUB ADDED TO THRUSTERS,CY ME LO PURIFIER IN USE,CY BALLAST,CY BENDING MOMENT,CY SHEARING FORCE,CY TORTION MOMENT,CY SUPDT AUDITOR SIGNED ON,CY SUPDT AUDITOR SIGNED OFF,CY CASH RECEIVED,CY LUB OIL RECEIVED MECYL,CY LUB OIL RECEIVED MECC,CY LUB OIL RECEIVED AECC,CY M E UNDER PISTON TEMP,CY MAIL RECEIVED,WIND DIRECTION PORT STBD,SEA DIRECTION PORT STBD,TIME PILOT ONBOARD,GRADES ROB,SO2 CO2 RATIO,Bunker Order,Remarks,BDN Number,Fuel Type,Carbon Factor,Sulphur Content PC,Quantity,Port Delivery,Product Quality,Tanktainer Number_1,Supplier,Delivery,Vol Lt,Den,Vis,ROB Dstlt ULS,ROB Dstlt VLS,ROB Rsdl MDO,ROB Tnktnr Dstlt VLS,ROB Rsdl VLS,ROB Rsdl HS,ROB Rsdl ULS,ROB Rsdl LNG,ECA MILES,ECA TIME,EGCS DRY WASTE REMOVED,EGCS RUNNING TIME,EGCS WET SLURRY REMOVED,EGCS OPEN LOOP RUNNING TIME,EGCS CLOSED LOOP RUNNING TIME
0,60317d31-4c4d-43d7-876b-2f33e51aba38,AGIOS DIMITRIOS,9349605.0,IP434A,2024-09-01,2024-09-01 12:00:00,UTC +05:00,NOON,AT SEA,0151S,06734E,82.6,68806.0,True,24.0,24.0,414.199997,0.0,16.445833,17.258333,70.5,15.1,112.0,12.0,14.3,13.7,105028.9,206.0,3.37,152.92,5207.0,31.0,29.0,394.7,MUPLU,2024-09-04 12:00:00,UTC +04:00,PORT LOUIS,NaN,24.0,319.0,347.0,17.50,1260.7,72.0,0.0,0.0,7.0,16.0,203125380.0,INMUN,MUNDRA,False,False,NaN,NaN,WAITING FOR SCHEDULE,NaN,2024-08-26 12:00:00,UTC +05:30,NaT,NaN,NaN,NaN,NaN,2024-08-28 04:30:00,UTC +05:30,NaN,NaN,NaN,5184.0,23.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,82.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.2,0.0,0.0,0.0,0.0,0.0,0.0,1.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16921.0,787.0,0.0,756.0,0.0,0.0,0.0,0.0,"SORIANO, DOMINADOR","DEREVIANKO, YURII",True,True,0.69,NaN,NaN,NaN,NaN,NaN,NaN,218.1,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8752.0,0,1500.0,NaN,NaN,NaN,78.2,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,190.9,664.3,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
1,a2bdb2d1-315a-4ded-a8a3-09b823a77d40,AGIOS DIMITRIOS,9349605.0,IP434A,2024-09-02,2024-09-02 12:00:00,UTC +05:00,NOON,AT SEA,0813S,06439E,82.1,68806.0,True,24.0,24.0,418.100006,0.0,16.287500,17.420833,70.1,13.8,90.0,15.0,14.3,13.7,104947.4,198.0,2.98,139.27,5207.0,29.0,27.0,390.9,MUPLU,2024-09-04 12:00:00,UTC +04:00,PORT LOUIS,NaN,24.0,317.0,343.0,17.56,843.0,48.0,0.0,0.0,7.0,16.0,203226330.0,INMUN,MUNDRA,False,False,NaN,NaN,WAITING FOR SCHEDULE,NaN,2024-08-26 12:00:00,UTC +05:30,NaT,NaN,NaN,NaN,NaN,2024-08-28 04:30:00,UTC +05:30,NaN,NaN,NaN,5184.0,23.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,82.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.4,0.0,0.0,0.0,0.0,0.0,0.0,1.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16839.0,749.0,0.0,750.0,0.0,0.0,0.0,0.0,"SORIANO, DOMINADOR","DEREVIANKO, YURII",True,True,0.67,NaN,NaN,NaN,NaN,NaN,NaN,229.7,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8752.0,0,1500.0,NaN,NaN,NaN,46.6,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,189.3,572.8,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
2,8c9d6f41-23c2-4866-abf7-ce2b58c80327,AGIOS DIMITRIOS,9349605.0,IP434A,2024-09-03,2024-09-03 12:00:00,UTC +04:00,NOON,AT SEA,1445S,06131E,85.5,68806.0,True,25.0,25.0,431.200012,0.0,15.808000,17.248000,70.2,14.1,92.0,18.0,14.3,13.7,104854.6,203.0,3.63,134.82,5207.0,26.0,24.0,395.2,MUPLU,2024-09-04 12:00:00,UTC +04:00,PORT LOUIS,NaN,25.0,314.0,334.0,17.15,411.8,24.0,0.0,0.0,7.0,16.0,203331700.0,INMUN,MUNDRA,False,False,NaN,NaN,WAITING FOR SCHEDULE,NaN,2024-08-26 12:00:00,UTC +05:30,NaT,NaN,NaN,NaN,NaN,2024-08-28 04:30:00,UTC +05:30,NaN,NaN,NaN,5184.0,23.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,25.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,85.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,1.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16887.0,778.0,0.0,801.0,0.0,0.0,0.0,0.0,"SORIANO, DOMINADOR","DEREVIANKO, YURII",True,True,0.68,NaN,NaN,NaN,NaN,NaN,NaN,233.9,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8752.0,0,1550.0,NaN,NaN,NaN,35.8,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,187.8,477.3,0.0,0.0,0.0,0.0,NaN,25.0,NaN,25.0,0.0
3,6df7e111-d94e-4d1c-acfe-027d4a1092b6,AGIOS DIMITRIOS,9349605.0,IP434A,2024-09-04,2024-09-04 11:00:00,UTC +04:00,EOSP,AT SEA,1956S,05725E,77.0,68806.0,True,23.0,23.0,396.400013,0.0,16.156522,17.234783,71.3,15.8,45.0,14.0,14.3,13.7,104771.9,186.0,0.86,126.54,5207.0,24.0,23.0,371.6,MUPLU,2024-09-04 12:00:00,UTC +04:00,NaN,NaN,23.0,303.0,325.0,17.15,NaN,NaN,0.0,0.0,7.0,16.0,203429800.0,MUPLU,PORT LOUIS,False,False,NaN,NaN,WAITING FOR SCHEDULE,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,2024-08-28 04:30:00,UTC +05:30,NaN,NaN,NaN,5184.0,23.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,23.0,0.0,0.0,0.0,0.0,0.0,1.2,22.2,23.0,0.0,0.0,0.0,0.0,17.2,59.8,0.0,0.0,0.0,0.0,0.0,0.0,1.8,7.1,0.0,0.0,1.0,0.0,0.0,0.0,0.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16498.0,0.0,645.0,649.0,0.0,0.0,0.0,0.0,"SORIANO, DOMINADOR","DEREVIANKO, YURII",True,True,0.54,NaN,NaN,NaN,NaN,NaN,NaN,238.8,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8752.0,0,1300.0,NaN,NaN,NaN,41.1,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,584.8,0.0,0.0,0.0,168.1,410.4,0.0,0.0,0.0,0.0,NaN,NaN,NaN,23.0,NaN
4,61f26af2-e334-4ea1-830e-b2d314c5e087,AGIOS DIMITRIOS,9349605.0,IP434A,2024-09-04,2024-09-04 12:00:00,UTC +04:00,DLY A,DRIFTING,2007S,05723E,0.7,68806.0,True,1.0,1.0,11.200000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,14.3,13.7,104770.9,0.0,0.00,0.00,5207.0,24.0,23.0,NaN,MUPLU,2024-09-04 12:00:00,UTC +04:00,NaN,NaN,1.0,77.0,77.0,17.15,NaN,NaN,0.0,0.0,7.0,16.0,203431260.0,MUPLU,PORT LOUIS,False,False,0.0,0.0,WAITING FOR SCHEDULE,DRIFTING,NaT,NaN,NaT,NaN,1.0,NaN,NaN,2024-09-05 12:00:00,UTC +04:00,NaN,NaN,NaN,5184.0,23.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2598.0,0.0,529.0,550.0,0.0,0.0,0.0,0.0,"SORIANO, DOMINADOR","DEREVIANKO, YURII",True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,238.8,11.2,10.7,NaN,False,NaT,NaN,NaT,NaN,8752.0,0,1100.0,NaN,NaN,NaN,41.1,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,167.1,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0

In [26]:
cf['IMO No'].isnull().sum()

39

In [29]:
vsl_unique_null_imo = cf[cf['IMO No'].isnull()]['VSL'].unique()
vsl_unique_null_imo

array(['MSC MAURA'], dtype=object)

In [31]:
cf.loc[cf['VSL'] == 'MSC METTE', 'IMO No']=9936630

In [33]:
cf[cf['VSL'] == 'MSC METTE']

,GID,VSL,IMO No,VOY,Corrected Date,REPORT DATE TIME,REPORT DATE TIME Offset,Report Type,Status,LAT,LONG,M E FOC,CARGO TOTAL,Has Cargo,STEAMING TIME,Total M E Hours Fuel Only,MILES BY GPS,OIL CYL,SPEED BY LOG,SPEED BY GPS,RPM,SLIP,WIND DIRECTION,WIND SPEED,DRAFT AFT,DRAFT FWD,DISPLACEMENT,COURSE AT SEA,WAVE HEIGHT,SEA DIRECTION,CARGO TOTAL TEU,AMBIENT TEMP,SW TEMP,MILES BY SPEED LOG,ETA PORT CODE,ETA DATE TIME,ETA DATE TIME Offset,ETA PORT,TIME CHANGE,TIME SEA,TEMP MIN,TEMP MAX,REQUESTED SPEED,REM DIST TO PILOT,REM TIME TO PILOT,TOTAL UNPLND STPGE TECH,TOTAL UNPLND STPGE OPE WX,REEFERS POSITIVE PLUGGED,REEFERS NEGATIVE PLUGGED,ME TOTAL REVS COUNTER,PORT CODE,PORT,AUX BLOWERS ON,HOLD VENTILATION ON,TIME HRS ANCHOR,TIME HRS DRIFT,REASON,TYPE OF DELAY,ETB DATE TIME,ETB DATE TIME Offset,PILOT DATE TIME,PILOT DATE TIME Offset,TIME MANOEUVRING,TUG ARR,TUG SHIFT,ETD DATE TIME,ETD DATE TIME Offset,SHIFT BERTH HOURS,CARGO LOAD,CARGO DISCH,TEU FULL,TEU EMPTY,BILGE REMOVED,GARBAGE REMOVED,GARBAGE REMVL REQSTD,GARBAGE REMVL CMPLSRY,FW SUPPLY,CY CREW SIGNED ON,CY CREW SIGNED OFF,CY DOCTORS VISIT,CY MAIL RECEIVED Ref NO,CY LUB OIL SAMPLE LANDED,CY CHECKD FOR STOWAWAYS,CY STOWAWAYS ON BOARD,CY DEP GM Mtr,CY REQUISITIONS RECEIVED,DISTANCE TO NEXT PILOT,TUG SAILING TRANSIT,STEAMING TIME M E Rsdl VLS,STEAMING TIME M E Rsdl HS,STEAMING TIME M E Rsdl ULS,STEAMING TIME M E Dstlt VLS,STEAMING TIME M E Dstlt ULS,STEAMING TIME M E Tnktnr Dstlt VLS,STEAMING TIME M E MDO,STEAMING TIME AUX 1,STEAMING TIME AUX 2,STEAMING TIME AUX 3,STEAMING TIME AUX 4,STEAMING TIME AUX 5,STEAMING TIME SH GEN,STEAMING TIME TG,FUEL M E Rsdl VLS,FUEL M E Rsdl HS,FUEL M E Rsdl ULS,FUEL M E Dstlt VLS,FUEL M E Dstlt ULS,FUEL M E MDO,FUEL M E LNG,FUEL M E Tnktnr Dstlt VLS,FUEL Aux Rsdl VLS,FUEL Aux Rsdl HS,FUEL Aux Rsdl ULS,FUEL Aux Dstlt VLS,FUEL Aux Dstlt ULS,FUEL Aux Tnktnr Dstlt VLS,FUEL Aux LNG,FUEL Aux MDO,FUEL Boiler Rsdl VLS,FUEL Boiler Rsdl HS,FUEL Boiler Rsdl ULS,FUEL Boiler Dstlt VLS,FUEL Boiler Dstlt ULS,FUEL Boiler Tnktnr Dstlt VLS,FUEL Boiler LNG,FUEL Boiler MDO,POWER KW,STEAMING LOAD KW AUX 1,STEAMING LOAD KW AUX 2,STEAMING LOAD KW AUX 3,STEAMING LOAD KW AUX 4,STEAMING LOAD KW AUX 5,STEAMING LOAD KW SH GEN,STEAMING LOAD KW TG,DECK LAST CHANGE USER,ENGINE LAST CHANGE USER,DECK PART IS COMPLETE,ENGINE PART IS COMPLETE,SCAVENGE PRESSURE,SECA ENTRY TIME,SECA ENTRY LAT,SECA ENTRY LONG,SECA EXIT TIME,SECA EXIT LAT,SECA EXIT LONG,ROB FRESH WATER,MANVRNG MILES BY GPS,MANVRNG MILES BY SPEED LOG,TANKTAINER TRANSFD QUANTITY,PILOT TAKEN,DATE TIME START TRANSIT,DATE TIME START TRANSIT Offset,DATE TIME END TRANSIT,DATE TIME END TRANSIT Offset,BALLAST,TANKTAINER NUMBER,STEAMING KWHR TOTAL,CY OTHERS,ROB FO SLUDGE,ROB LO SLUDGE,ROB BILGE,SLUDGE REMOVED FO,SLUDGE REMOVED LO,SEA STATE,CY LUB ADDED TO SYSTEM MECC,CY LUB ADDED TO SYSTEM AECC,CY LUB ADDED TO THRUSTERS,CY ME LO PURIFIER IN USE,CY BALLAST,CY BENDING MOMENT,CY SHEARING FORCE,CY TORTION MOMENT,CY SUPDT AUDITOR SIGNED ON,CY SUPDT AUDITOR SIGNED OFF,CY CASH RECEIVED,CY LUB OIL RECEIVED MECYL,CY LUB OIL RECEIVED MECC,CY LUB OIL RECEIVED AECC,CY M E UNDER PISTON TEMP,CY MAIL RECEIVED,WIND DIRECTION PORT STBD,SEA DIRECTION PORT STBD,TIME PILOT ONBOARD,GRADES ROB,SO2 CO2 RATIO,Bunker Order,Remarks,BDN Number,Fuel Type,Carbon Factor,Sulphur Content PC,Quantity,Port Delivery,Product Quality,Tanktainer Number_1,Supplier,Delivery,Vol Lt,Den,Vis,ROB Dstlt ULS,ROB Dstlt VLS,ROB Rsdl MDO,ROB Tnktnr Dstlt VLS,ROB Rsdl VLS,ROB Rsdl HS,ROB Rsdl ULS,ROB Rsdl LNG,ECA MILES,ECA TIME,EGCS DRY WASTE REMOVED,EGCS RUNNING TIME,EGCS WET SLURRY REMOVED,EGCS OPEN LOOP RUNNING TIME,EGCS CLOSED LOOP RUNNING TIME
16394,751e8c2a-eea9-41d5-8ae6-84cdfe6b686b,MSC METTE,9936630.0,FJ429W,2024-09-01,2024-09-01 12:00:00,UTC +04:00,NOON,AT SEA,3426S,02539E,127.91,166150.8,True,24.0,24.0,471.000000,778.0,17.250000,19.625000,55.5,-3.2,0.0,35.0,14.85,14.5,246455.3,262.0,1.33,0.00,18766.0,29.0,19.0,414.0,ESVLC,2024-09-14 06:00:00,UTC +02:00,VALENCIA,NaN,24.0,285.0,302.0,18.0,5900.0,358.0,0.0,0.0,19.0,16.0,19649390.0,SGSIN,SINGAPORE,False,True,NaN,NaN,Awaiting for berthing,NaN,2024-08-17 15:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2024-08-19 13:30:00,UTC +08:00,NaN,NaN,NaN,17822.0,944.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,24.0,0.0,0.0,127.91,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.67,0.0,0.0,0.00,0.0,0.0,0.0,29840.0,0.0,1646.0,0.0,0.0,0.0,1500.0,0.0,2off,CE,True,True,1.44,NaN,NaN,NaN,NaN,NaN,NaN,540.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,4691.0,0,39360.0,Scrubber in open loop global settings,NaN,NaN,39.0,NaN,NaN,4.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.0,4238.00,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
16395,db6c4115-da82-4c36-8f5b-fb7f81e9dfd4,MSC METTE,9936630.0,FJ429W,2024-09-02,2024-09-02 12:00:00,UTC +03:00,NOON,AT SEA,3257S,01656E,159.87,166150.8,True,25.0,25.0,487.000000,948.0,18.920000,19.480000,60.3,5.6,40.0,15.0,14.85,14.5,246455.3,321.0,0.89,129.65,18766.0,29.0,19.0,473.0,ESVLC,2024-09-14 06:00:00,UTC +02:00,VALENCIA,NaN,25.0,300.0,317.0,18.0,5414.0,334.0,0.0,0.0,19.0,16.0,19739790.0,SGSIN,SINGAPORE,False,True,NaN,NaN,Awaiting for berthing,NaN,2024-08-17 15:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2024-08-19 13:30:00,UTC +08:00,NaN,NaN,NaN,17822.0,944.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0,0.0,0.0,25.0,0.0,0.0,159.87,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,36322.8,0.0,1626.0,0.0,0.0,0.0,1372.0,0.0,2off,CE,True,True,2.28,NaN,NaN,NaN,NaN,NaN,NaN,550.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,4691.0,0,40510.0,Scrubber running in open loop global settings,NaN,NaN,39.0,NaN,NaN,3.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.0,4070.02,0.0,0.0,0.0,0.0,NaN,25.0,NaN,25.0,0.0
16396,e461429c-52a0-4f26-b24c-e3026790ef9c,MSC METTE,9936630.0,FJ429W,2024-09-03,2024-09-03 12:00:00,UTC +03:00,NOON,AT SEA,2655S,01124E,143.56,166150.8,True,24.0,24.0,459.000000,859.0,18.375000,19.125000,59.4,16.3,45.0,13.0,14.85,14.5,246455.3,321.0,1.03,137.22,18766.0,29.0,17.0,441.0,ESVLC,2024-09-14 06:00:00,UTC +02:00,VALENCIA,NaN,24.0,298.0,316.0,18.0,4953.0,310.0,0.0,0.0,19.0,16.0,19825350.0,SGSIN,SINGAPORE,False,True,NaN,NaN,Awaiting for berthing,NaN,2024-08-17 15:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2024-08-19 13:30:00,UTC +08:00,NaN,NaN,NaN,17822.0,944.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,24.0,0.0,0.0,143.56,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,33943.8,0.0,1450.0,0.0,0.0,0.0,1298.0,0.0,2off,CE,True,True,2.20,NaN,NaN,NaN,NaN,NaN,NaN,550.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,4691.0,0,34680.0,Scrubber in open loop global settings,NaN,NaN,39.0,NaN,NaN,3.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.0,3919.38,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
16397,b5749bf8-b63c-400b-9256-a32722fea849,MSC METTE,9936630.0,FJ429W,2024-09-04,2024-09-04 12:00:00,UTC +02:00,NOON,AT SEA,2036S,00556E,148.32,166150.8,True,25.0,25.0,484.000000,889.0,18.720000,19.360000,59.6,5.1,140.0,24.0,14.85,14.5,246455.3,321.0,9.39,157.77,18766.0,29.0,18.0,468.0,ESVLC,2024-09-14 06:00:00,UTC +02:00,VALENCIA,NaN,25.0,297.0,314.0,18.0,4471.0,286.0,0.0,0.0,19.0,16.0,19914700.0,SGSIN,SINGAPORE,False,True,NaN,NaN,Awaiting for berthing,NaN,2024-08-17 15:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2024-08-19 13:30:00,UTC +08:00,NaN,NaN,NaN,17822.0,944.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0,0.0,0.0,25.0,0.0,0.0,148.32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,33672.4,0.0,1434.0,0.0,0.0,0.0,1280.0,0.0,2off,CE,True,True,2.20,NaN,NaN,NaN,NaN,NaN,NaN,555.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,4691.0,0,35720.0,Scrubber in open loop mode global settings,NaN,NaN,0.0,NaN,NaN,8.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.0,3763.74,0.0,0.0,0.0,0.0,NaN,25.0,NaN,25.0,0.0
16398,6b828d01-d04f-4cc4-b3f5-7c9abb59d456,MSC METTE,9936630.0,FJ429W,2024-09-05,2024-09-05 12:00:00,UTC +02:00,NOON,AT SEA,1435S,00056E,137.91,166150.8,True,24.0,24.0,470.000000,831.0,18.750000,19.583333,58.7,4.6,45.0,15.0,14.85,14.5,246455.3,321.0,1.09,130.25,18766.0,29.0,20.0,450.0,ESVLC,2024-09-14 06:00:00,UTC +02:00,VALENCIA,NaN,24.0,290.0,309.0,18.0,4021.0,210.0,0.0,0.0,19.0,16.0,19999200.0,SGSIN,SINGAPORE,False,True,NaN,NaN,Awaiting for berthing,NaN,2024-08-17 15:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2024-08-19 13:30:00,UTC +08:00,NaN,NaN,NaN,17822.0,944.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,24.0,0.0,0.0,137.91,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.84,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,32601.3,0.0,1393.0,0.0,0.0,0.0,1294.0,0.0,2off,CE,True,True,2.10,NaN,NaN,NaN,NaN,NaN,NaN,540.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,0.0,0,33320.0,Scrubber in open loop mode global settings,NaN,NaN,0.0,NaN,NaN,3.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,1.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.0,3618.99,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
16399,ee3ecd17-a29d-4f7f-97c7-d4bb9f45c703,MSC METTE,9936630.0,FJ429W,2024-09-06,2024-09-06 12:00:00,UTC +02:00,NOON,AT SEA,0833S,00357W,142.88,166150.8,True,24.0,24.0,460.000031,826.0,18.666667,19.166667,59.6,6.0,45.0,15.0,14.85,14.5,246455.3,321.0,1.05,128.91,18766.0,29.0,23.0,448.0,ESVLC,2024-09-14 06:00:00,UTC +02:00,VALENCIA,NaN,24.0,294.0,311.0,18.0,3551.0,186.0,0.0,0.0,19.0,16.0,20084960.0,SGSIN,SINGAPORE,False,True,NaN,NaN,Awaiting for berthing,NaN,2024-08-17 15:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2024-08-19 13:30:00,UTC +08:00,NaN,NaN,NaN,17822.0,944.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,24.0,0.0,0.0,142.88,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.81,0.0,0.0,0.00,0.0,0.0,0.0,33662.9,0.0,1431.0,0.0,0.0,0.0,1256.0,0.0,2OFF,CE,True,True,2.10,NaN,NaN,NaN,NaN,NaN,NaN,570.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,4691.0,0,34230.0,Scrubber in open loop mode global settings,NaN,NaN,0.0,NaN,NaN,3.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,0.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.0,3468.07,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
16400,988031b2-a18b-4070-8185-1e70fd2a29c9,MSC METTE,9936630.0,FJ429W,2024-09-07,2024-09-07 12:00:00,UTC +02:00,NOON,AT SEA,0244S,00820W,127.04,166150.8,True,23.1,23.1,438.000000,733.0,18.441558,18.961039,57.8,4.1,160.0,15.0,14.85,14.5,246455.3,321.0,6.32,171.18,18766.0,29.0,24.0,426.0,ESVLC,2024-09-14 06:00:00,UTC +02:00,VALENCIA,NaN,24.0,281.0,300.0,18.0,3115.0,162.0,0.9,0.0,19.0,16.0,20165015.0,SGSIN,SINGAPORE,False,True,NaN,NaN,Awaiting for berthing,NaN,2024-08-17 15:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2024-08-19 13:30:00,UTC +08:00,NaN,NaN,NaN,17822.0,944.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,23.1,0.0,0.0,0.0,0.0,0.0,0.1,24.0,0.0,0.0,0.0,17.3,0.0,0.0,127.04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.83,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.59,0.0,0.0,0.00,0.0,0.0,0.0,31019.0,1136.0,1768.0,0.0,0.0,0.0,1277.0,0.0,2off,CE,True,True,1.90,NaN,NaN,NaN,NaN,NaN,NaN,590.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,4691.0,0,42420.0,Scrubber in open loop global settings,NaN,NaN,0.0,NaN,NaN,7.0,0.0,200.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,0.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.0,3331.61,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
16401,915459b2-6197-448b-8074-3c2c229c9863,MSC METTE,9936630.0,FJ429W,2024-09-08,2024-09-08 12:00:00,UTC +02:00,NOON,AT SEA,0337N,01238W,137.31,166150.8,True,24.0,24.0,460.999969,815.0,19.000000,19.208333,59.1,5.1,70.0,16.0,14.85,14.5,246455.3,326.0,2.34,132.42,18766.0,29.0,27.0,456.0,ESVLC,2024-09-14 06:00:00,UTC +02:00,VALENCIA,NaN,24.0,299.0,313.0,18.0,2655.0,138.0,0.0,0.0,19.0,16.0,20250080.0,SGSIN,SINGAPORE,False,True,NaN,NaN,Awaiting for berthing,NaN,2024-08-17 15:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2024-08-19 13:30:00,UTC +08:00,NaN,NaN,NaN,17822.0,944.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,22.7,0.0,0.0,137.31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.59,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,32648.7,0.0,1571.0,0.0,0.0,0.0,1353.0,0.0,2off,CE,True,True,2.10,NaN,NaN,NaN,NaN,NaN,NaN,605.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,4691.0,0,37570.0,Scrubber in open loop global settings,NaN,NaN,0.0,NaN,NaN,4.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,1.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.0,3186.71,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
45733,8aee2714-e4a2-421f-9627-6b6940c39a09,MSC METTE,9936630.0,FJ429W,2024-09-09,2024-09-09 12:00:00,UTC +02:00,NOON,AT SEA,0947N,01648W,141.69,166150.8,True,23.2,23.2,444.500000,787.0,18.943966,19.159483,60.6,8.1,160.0,14.0,14.85,14.5,246455.3,326.0,6.02,171.58,18766.0,29.0,27.0,439.5,ESVLC,2024-09-14 06:00:00,UTC +02:00,VALENCIA,NaN,24.0,312.0,330.0,18.0,2212.0,114.0,0.8,0.0,19.0,16.0,20334849.0,SGSIN,SINGAPORE,False,True,NaN,NaN,Awaiting for berthing,NaN,2024-08-17 15:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2024-08-19 13:30:00,UTC +08:00,NaN,NaN,NaN,17822.0,944.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,23.2,0.0,0.0,0.0,0.0,0.0,0.6,24.0,0.0,0.2,0.1,1.7,0.0,0.0,141.69,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.29,0.0,0.0,0.00,0.0,0.0,0.0,34591.5,1209.0,2984.0,0.0,836.0,543.0,1431.0,0.0,2off,CE,True,True,2.40,NaN,NaN,NaN,NaN,NaN,NaN,625.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,4691.0,0,72350.0,Scrubber in open loop global settings,NaN,NaN,0.0,NaN,NaN,7.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,2.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.0,3029.64,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
45734,b35dd066-a07e-40ef-9f67-fd5d76fa58f9,MSC METTE,9936630.0,FJ429W,2024-09-10,2024-09-10 12:00:00,UTC +02:00,NOON,AT SEA,1731N,01755W,163.22,166150.8,True,24.0,24.0,477.000000,990.0,19.291667,19.875000,62.4,7.1,25.0,12.0,14.85,14.5,246455.3,3.0,0.60,150.60,18766.0,29.0,27.0,463.0,ESVLC,2024-09-14 06:00:00,UTC +02:00,VALENCIA,NaN,24.0,338.0,358.0,19.2,1734.0,90.0,0.0,0.0,19.0,16.0,20424770.0,SGSIN,SINGAPORE,False,True,NaN,NaN,Awaiting for berthing,NaN,2024-08-17 15:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2024-08-19 13:30:00,UTC +08:00,NaN,NaN,NaN,17822.0,944.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.4,0.0,0.0,2.6,0.0,0.0,163.22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,38629.5,0.0,3092.0,177.0,0.0,0.0,1328.0,0.0,2off,CE,True,True,2.46,NaN,NaN,NaN,NaN,NaN,NaN,635.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,7669.0,0,74010.0,Scrubber in open loop mode global settings,NaN,NaN,8.8,NaN,NaN,3.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,3.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.0,2851.27,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
45735,70a04aa4-2c52-417a-99ef-eafe03b9b1d3,MSC METTE,9936630.0,FJ429W,2024-09-11,2024-09-11 12:00:00,UTC +02:00,NOON,AT SEA,2447N,01546W,174.27,166150.8,True,24.0,24.0,464.000000,1055.0,18.958333,19.333333,62.6,9.9,10.0,20.0,14.85,14.5,246455.3,35.0,0.07,84.04,18766.0,29.0,22.0,455.0,ESVLC,2024-09-14 06:00:00,UTC +02:00,VALENCIA,NaN,24.0,342.0,360.0,19.2,1270.0,66.0,0.0,0.0,19.0,16.0,20514950.0,SGSIN,SINGAPORE,False,True,NaN,NaN,Awaiting for berthing,NaN,2024-08-17 15:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2024-08-19 13:30:00,UTC +08:00,NaN,NaN,NaN,17822.0,944.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.1,0.0,0.0,24.0,0.0,0.0,174.27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,41023.0,0.0,1869.0,657.0,0.0,0.0,1323.0,0.0,2off,CE,True,True,2.70,NaN,NaN,NaN,NaN,NaN,NaN,620.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,7669.0,0,44760.0,Scrubber running in open loop with global sett...,NaN,NaN,8.8,NaN,NaN,1.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,3.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.0,2667.93,0.0,0.0,0.0,4.0,NaN,24.0,NaN,24.0,0.0
45736,6ae4848d-363c-4e54-90e0-3b5d7c4a517e,MSC METTE,9936630.0,FJ429W,2024-09-12,2024-09-12 12:00:00,UTC +02:00,NOON,AT SEA,3026N,01118W,169.90,166150.8,True,24.0,24.0,412.000031,1090.0,17.000000,17.166667,61.1,17.9,10.0,40.0,14.85,14.5,246455.3,35.0,3.06,17.36,18766.0,29.0,22.0,408.0,ESVLC,2024-09-14 06:00:00,UTC +02:00,VALENCIA,NaN,24.0,320.0,341.0,19.2,858.0,42.0,0.0,0.0,19.0,16.0,20602870.0,SGSIN,SINGAPORE,False,True,NaN,NaN,Awaiting for berthing,NaN,2024-08-17 15:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2024-08-19 13:30:00,UTC +08:00,NaN,NaN,NaN,17822.0,944.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,1.7,0.0,0.0,17.4,0.0,0.0,169.90,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.55,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,39935.4,0.0,2038.0,1483.0,0.0,0.0,1288.0,0.0,2off,CE,True,True,2.50,NaN,NaN,NaN,NaN,NaN,NaN,630.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,7669.0,0,51320.0,Scrubber in open loop with global settings,NaN,NaN,8.8,NaN,NaN,5.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,3.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.0,2487.48,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
45737,5ecba68e-35a9-4c88-921f-856c04e734b6,MSC METTE,9936630.0,FJ429W,2024-09-13,2024-09-13 12:00:00,UTC +02:00,NOON,AT SEA,3550N,00604W,150.91,166150.8,True,24.0,24.0,419.000000,958.0,17.083333,17.458333,59.9,14.9,15.0,12.0,14.85,14.5,246455.3,79.0,0.25,152.11,18766.0,29.0,22.0,410.0,ESVLC,2024-09-14 10:00:00,UTC +02:00,VALENCIA,NaN,24.0,319.0,338.0,19.2,439.0,22.0,0.0,0.0,19.0,16.0,20689100.0,SGSIN,SINGAPORE,False,True,NaN,NaN,Awaiting for berthing,NaN,2024-08-17 15:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2024-08-19 13:30:00,UTC +08:00,NaN,NaN,NaN,17822.0,944.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,150.91,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.52,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,36120.0,0.0,3018.0,0.0,0.0,0.0,0.0,0.0,2off,CE,True,True,2.20,NaN,NaN,NaN,NaN,NaN,NaN,660.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,7669.0,0,72180.0,Scrubber in open loop mode with global settings,NaN,NaN,8.8,NaN,NaN,2.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,2.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.0,2322.05,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0

In [35]:
cf.loc[cf['VSL'] == 'MSC CHIYO', 'IMO No'] = 9947110

In [38]:
cf[cf['VSL'] == 'MSC CHIYO']

,GID,VSL,IMO No,VOY,Corrected Date,REPORT DATE TIME,REPORT DATE TIME Offset,Report Type,Status,LAT,LONG,M E FOC,CARGO TOTAL,Has Cargo,STEAMING TIME,Total M E Hours Fuel Only,MILES BY GPS,OIL CYL,SPEED BY LOG,SPEED BY GPS,RPM,SLIP,WIND DIRECTION,WIND SPEED,DRAFT AFT,DRAFT FWD,DISPLACEMENT,COURSE AT SEA,WAVE HEIGHT,SEA DIRECTION,CARGO TOTAL TEU,AMBIENT TEMP,SW TEMP,MILES BY SPEED LOG,ETA PORT CODE,ETA DATE TIME,ETA DATE TIME Offset,ETA PORT,TIME CHANGE,TIME SEA,TEMP MIN,TEMP MAX,REQUESTED SPEED,REM DIST TO PILOT,REM TIME TO PILOT,TOTAL UNPLND STPGE TECH,TOTAL UNPLND STPGE OPE WX,REEFERS POSITIVE PLUGGED,REEFERS NEGATIVE PLUGGED,ME TOTAL REVS COUNTER,PORT CODE,PORT,AUX BLOWERS ON,HOLD VENTILATION ON,TIME HRS ANCHOR,TIME HRS DRIFT,REASON,TYPE OF DELAY,ETB DATE TIME,ETB DATE TIME Offset,PILOT DATE TIME,PILOT DATE TIME Offset,TIME MANOEUVRING,TUG ARR,TUG SHIFT,ETD DATE TIME,ETD DATE TIME Offset,SHIFT BERTH HOURS,CARGO LOAD,CARGO DISCH,TEU FULL,TEU EMPTY,BILGE REMOVED,GARBAGE REMOVED,GARBAGE REMVL REQSTD,GARBAGE REMVL CMPLSRY,FW SUPPLY,CY CREW SIGNED ON,CY CREW SIGNED OFF,CY DOCTORS VISIT,CY MAIL RECEIVED Ref NO,CY LUB OIL SAMPLE LANDED,CY CHECKD FOR STOWAWAYS,CY STOWAWAYS ON BOARD,CY DEP GM Mtr,CY REQUISITIONS RECEIVED,DISTANCE TO NEXT PILOT,TUG SAILING TRANSIT,STEAMING TIME M E Rsdl VLS,STEAMING TIME M E Rsdl HS,STEAMING TIME M E Rsdl ULS,STEAMING TIME M E Dstlt VLS,STEAMING TIME M E Dstlt ULS,STEAMING TIME M E Tnktnr Dstlt VLS,STEAMING TIME M E MDO,STEAMING TIME AUX 1,STEAMING TIME AUX 2,STEAMING TIME AUX 3,STEAMING TIME AUX 4,STEAMING TIME AUX 5,STEAMING TIME SH GEN,STEAMING TIME TG,FUEL M E Rsdl VLS,FUEL M E Rsdl HS,FUEL M E Rsdl ULS,FUEL M E Dstlt VLS,FUEL M E Dstlt ULS,FUEL M E MDO,FUEL M E LNG,FUEL M E Tnktnr Dstlt VLS,FUEL Aux Rsdl VLS,FUEL Aux Rsdl HS,FUEL Aux Rsdl ULS,FUEL Aux Dstlt VLS,FUEL Aux Dstlt ULS,FUEL Aux Tnktnr Dstlt VLS,FUEL Aux LNG,FUEL Aux MDO,FUEL Boiler Rsdl VLS,FUEL Boiler Rsdl HS,FUEL Boiler Rsdl ULS,FUEL Boiler Dstlt VLS,FUEL Boiler Dstlt ULS,FUEL Boiler Tnktnr Dstlt VLS,FUEL Boiler LNG,FUEL Boiler MDO,POWER KW,STEAMING LOAD KW AUX 1,STEAMING LOAD KW AUX 2,STEAMING LOAD KW AUX 3,STEAMING LOAD KW AUX 4,STEAMING LOAD KW AUX 5,STEAMING LOAD KW SH GEN,STEAMING LOAD KW TG,DECK LAST CHANGE USER,ENGINE LAST CHANGE USER,DECK PART IS COMPLETE,ENGINE PART IS COMPLETE,SCAVENGE PRESSURE,SECA ENTRY TIME,SECA ENTRY LAT,SECA ENTRY LONG,SECA EXIT TIME,SECA EXIT LAT,SECA EXIT LONG,ROB FRESH WATER,MANVRNG MILES BY GPS,MANVRNG MILES BY SPEED LOG,TANKTAINER TRANSFD QUANTITY,PILOT TAKEN,DATE TIME START TRANSIT,DATE TIME START TRANSIT Offset,DATE TIME END TRANSIT,DATE TIME END TRANSIT Offset,BALLAST,TANKTAINER NUMBER,STEAMING KWHR TOTAL,CY OTHERS,ROB FO SLUDGE,ROB LO SLUDGE,ROB BILGE,SLUDGE REMOVED FO,SLUDGE REMOVED LO,SEA STATE,CY LUB ADDED TO SYSTEM MECC,CY LUB ADDED TO SYSTEM AECC,CY LUB ADDED TO THRUSTERS,CY ME LO PURIFIER IN USE,CY BALLAST,CY BENDING MOMENT,CY SHEARING FORCE,CY TORTION MOMENT,CY SUPDT AUDITOR SIGNED ON,CY SUPDT AUDITOR SIGNED OFF,CY CASH RECEIVED,CY LUB OIL RECEIVED MECYL,CY LUB OIL RECEIVED MECC,CY LUB OIL RECEIVED AECC,CY M E UNDER PISTON TEMP,CY MAIL RECEIVED,WIND DIRECTION PORT STBD,SEA DIRECTION PORT STBD,TIME PILOT ONBOARD,GRADES ROB,SO2 CO2 RATIO,Bunker Order,Remarks,BDN Number,Fuel Type,Carbon Factor,Sulphur Content PC,Quantity,Port Delivery,Product Quality,Tanktainer Number_1,Supplier,Delivery,Vol Lt,Den,Vis,ROB Dstlt ULS,ROB Dstlt VLS,ROB Rsdl MDO,ROB Tnktnr Dstlt VLS,ROB Rsdl VLS,ROB Rsdl HS,ROB Rsdl ULS,ROB Rsdl LNG,ECA MILES,ECA TIME,EGCS DRY WASTE REMOVED,EGCS RUNNING TIME,EGCS WET SLURRY REMOVED,EGCS OPEN LOOP RUNNING TIME,EGCS CLOSED LOOP RUNNING TIME
8144,8b90b40c-ae6f-4096-97d5-30715cb99475,MSC CHIYO,9947110.0,FA428A,2024-09-01,2024-09-01 12:00:00,UTC -05:00,DLY A,DRIFTING,0348N,07730W,7.2,88657.0,True,6.5,6.5,62.5,78.0,0.000000,0.000000,0.0,0.0,0.0,0.0,13.40,13.10,169650.0,0.0,0.00,0.00,10557.0,27.0,28.0,NaN,COBUN,2024-09-01 13:00:00,UTC -05:00,NaN,NaN,24.0,100.0,100.0,18.0,NaN,NaN,0.0,0.0,29.0,55.0,24003700.0,COBUN,BUENAVENTURA,False,True,0.0,17.4,AWAITING BERTH,DRIFTING,2024-09-01 16:00:00,UTC -05:00,NaT,NaN,6.6,NaN,NaN,2024-09-04 19:00:00,UTC -05:00,NaN,NaN,NaN,9043.0,1514.0,NaN,NaN,False,False,NaN,0,0,No,0,0,NaN,NaN,NaN,0,NaN,NaN,0.0,6.5,0.0,0.0,0.0,0.0,0.0,7.9,0.0,0.0,16.9,0.0,0.0,0.0,0.0,7.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.4,0.0,0.0,0.0,0.0,0.0,0.0,4950.0,2580.0,0.0,0.0,2340.0,0.0,0.0,0.0,2/O,CE,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,390.0,62.5,62.2,NaN,False,NaT,NaN,NaT,NaN,4531.0,0,58000.0,NaN,NaN,NaN,27.3,NaN,NaN,NaN,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,NaN,False,NaN,NaN,NaN,NaN,6.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,5280.6,0.0,0.0,NaN,NaN,NaN,24.0,NaN,20.0,4.0
8151,0d7093f9-2c09-4744-bc59-b2833d4be0a8,MSC CHIYO,9947110.0,FA428A,2024-09-02,2024-09-01 15:54:00,UTC -05:00,BRTH,DRIFTING,0348N,07730W,5.9,88657.0,True,3.2,3.2,27.8,37.0,0.000000,0.000000,0.0,0.0,0.0,0.0,13.40,13.10,169650.0,0.0,0.00,0.00,10557.0,27.0,28.0,NaN,COBUN,2024-09-01 13:00:00,UTC -05:00,NaN,NaN,3.9,220.0,240.0,18.0,NaN,NaN,0.0,0.0,29.0,55.0,24009260.0,COBUN,BUENAVENTURA,False,True,NaN,NaN,AWAITING BERTH,NaN,2024-09-01 16:00:00,UTC -05:00,2024-09-01 13:00:00,UTC -05:00,3.9,3.0,0.0,2024-09-04 06:00:00,UTC -05:00,NaN,NaN,NaN,9043.0,1514.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,3.2,0.0,0.0,0.0,0.0,0.0,3.9,3.5,3.7,3.7,0.0,0.0,0.0,0.0,5.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,8460.0,1026.0,857.0,1081.0,811.0,0.0,0.0,0.0,2/O,CE,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,390.0,27.8,27.4,NaN,False,NaT,NaN,NaT,NaN,4531.0,0,14000.0,NaN,NaN,NaN,27.3,NaN,NaN,0.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,6.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,5270.9,0.0,0.0,NaN,NaN,NaN,3.9,NaN,0.0,3.9
8152,e06467a1-b6b9-4adc-b43a-3a0b9d7daaa9,MSC CHIYO,9947110.0,FA428A,2024-09-02,2024-09-02 12:00:00,UTC -05:00,PORT,IN PORT,0348N,07730W,0.0,88657.0,True,20.1,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,13.40,13.10,169650.0,0.0,0.00,0.00,10557.0,31.0,28.0,NaN,COBUN,2024-09-01 13:00:00,UTC -05:00,NaN,NaN,20.1,100.0,100.0,18.0,NaN,NaN,0.0,0.0,29.0,55.0,24009260.0,COBUN,BUENAVENTURA,False,True,NaN,NaN,AWAITING BERTH,NaN,2024-09-01 16:00:00,UTC -05:00,NaT,NaN,NaN,NaN,NaN,2024-09-04 06:00:00,UTC -05:00,NaN,NaN,NaN,9043.0,1514.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1820.0,0.0,0.0,0.0,2/O,CE,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,390.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,4531.0,0,36000.0,NaN,NaN,NaN,31.4,NaN,NaN,0.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,4.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,5261.1,0.0,0.0,NaN,NaN,NaN,20.1,NaN,0.0,20.1
8153,51f9616c-1f61-4d1d-9be3-f13c20828190,MSC CHIYO,9947110.0,FA428A,2024-09-03,2024-09-03 12:00:00,UTC -05:00,PORT,IN PORT,0348N,07730W,0.0,88657.0,True,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,13.40,13.10,169650.0,0.0,0.00,0.00,10557.0,26.0,28.0,NaN,COBUN,2024-09-01 13:00:00,UTC -05:00,NaN,NaN,24.0,100.0,100.0,18.0,NaN,NaN,0.0,0.0,29.0,55.0,24009260.0,COBUN,BUENAVENTURA,False,True,NaN,NaN,AWAITING BERTH,NaN,2024-09-01 16:00:00,UTC -05:00,NaT,NaN,NaN,NaN,NaN,2024-09-04 17:00:00,UTC -05:00,NaN,NaN,NaN,9043.0,1514.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2083.0,0.0,0.0,0.0,2/O,CE,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,385.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,4531.0,0,50000.0,NaN,NaN,NaN,31.4,NaN,NaN,NaN,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,4.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,5247.3,0.0,0.0,NaN,NaN,NaN,24.0,NaN,0.0,24.0
8154,85c4ceb0-eab3-4ba5-874c-7ce9db451868,MSC CHIYO,9947110.0,FA428A,2024-09-04,2024-09-04 12:00:00,UTC -05:00,PORT,IN PORT,0348N,07730W,0.1,88657.0,True,0.1,0.1,0.0,6.0,0.000000,0.000000,0.0,0.0,0.0,0.0,13.40,13.10,169650.0,0.0,0.00,0.00,10557.0,29.0,28.0,NaN,COBUN,2024-09-01 13:00:00,UTC -05:00,NaN,NaN,24.0,100.0,100.0,18.0,NaN,NaN,0.0,0.0,29.0,55.0,24009480.0,COBUN,BUENAVENTURA,False,True,NaN,NaN,AWAITING BERTH,NaN,2024-09-01 16:00:00,UTC -05:00,NaT,NaN,NaN,NaN,NaN,2024-09-04 15:00:00,UTC -05:00,1.2,NaN,NaN,9043.0,1514.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.1,0.0,0.0,0.0,0.0,0.0,2.8,2.2,2.4,24.0,0.0,0.0,0.0,0.0,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.6,0.0,0.0,0.0,0.0,0.0,0.0,4090.0,1071.0,909.0,833.0,1958.0,0.0,0.0,0.0,2/O,CE,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,380.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,4531.0,0,54000.0,NaN,NaN,NaN,36.4,NaN,NaN,NaN,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,4.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,5232.2,0.0,0.0,NaN,NaN,NaN,24.0,NaN,0.0,24.0
8161,eb9473f0-8c49-4fcb-b8c2-f631efcba6e1,MSC CHIYO,9947110.0,FA428A,2024-09-05,2024-09-04 15:00:00,UTC -05:00,SAIL,IN PORT,0348N,07730W,0.0,79065.4,True,3.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,11.99,12.28,140852.0,0.0,0.00,0.00,11168.0,29.0,28.0,NaN,PECLL,2024-09-07 15:00:00,UTC -05:00,CALLAO,NaN,3.0,100.0,100.0,18.0,NaN,NaN,0.0,0.0,27.0,13.0,24009480.0,COBUN,BUENAVENTURA,False,True,NaN,NaN,AWAITING BERTH,NaN,2024-09-01 16:00:00,UTC -05:00,NaT,NaN,NaN,NaN,3.0,2024-09-04 15:00:00,UTC -05:00,NaN,24528.9,34120.9,6832.0,4336.0,0,NaN,False,False,0.0,0,0,No,0,0,YES,0,4.48,0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.8,0.3,0.4,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1250.0,1333.0,1000.0,2000.0,0.0,0.0,0.0,2/O,CE,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,380.0,NaN,NaN,0.0,False,NaT,NaN,NaT,NaN,5672.0,0,7800.0,NaN,NaN,NaN,36.4,NaN,NaN,0.0,0.0,0.0,0.0,1,NaN,89.0,97.0,42.0,0,0,0.0,0.0,0.0,0.0,NaN,False,NaN,NaN,NaN,NaN,6.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,5230.0,0.0,0.0,NaN,NaN,0.0,3.0,0.0,0.0,3.0
8162,b34f06b3-c7ca-47f5-8db1-188c790a1e7c,MSC CHIYO,9947110.0,FA428A,2024-09-05,2024-09-04 18:00:00,UTC -05:00,COSP,DRIFTING,0348N,07724W,3.4,79065.4,True,2.4,2.4,22.0,35.0,0.000000,0.000000,0.0,0.0,60.0,14.0,11.99,12.28,140852.0,272.0,1.11,60.00,11168.0,29.0,28.0,NaN,PECLL,2024-09-07 15:00:00,UTC -05:00,CALLAO,NaN,3.0,220.0,230.0,17.0,NaN,NaN,0.0,0.0,27.0,13.0,24014680.0,COBUN,BUENAVENTURA,True,True,NaN,NaN,AWAITING BERTH,NaN,2024-09-01 16:00:00,UTC -05:00,NaT,NaN,2.5,NaN,NaN,2024-09-04 15:00:00,UTC -05:00,NaN,NaN,NaN,6832.0,4336.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1134.0,3,0.0,2.4,0.0,0.0,0.0,0.0,0.0,1.3,1.4,3.0,2.9,0.0,0.0,0.0,0.0,3.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,6770.0,770.0,790.0,1270.0,1034.0,0.0,0.0,0.0,2/O,CE,True,True,0.8,NaN,NaN,NaN,NaN,NaN,NaN,380.0,22.0,22.0,NaN,True,NaT,NaN,NaT,NaN,5672.0,0,8900.0,NaN,NaN,NaN,36.4,NaN,NaN,3.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,2.6,NaN,6.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,5224.0,0.0,0.0,NaN,NaN,NaN,3.0,NaN,0.0,3.0
8163,71aa6a2a-586c-492c-aaea-e1428f6e1770,MSC CHIYO,9947110.0,FA428A,2024-09-05,2024-09-05 12:00:00,UTC -05:00,NOON,AT SEA,0020N,08040W,65.4,79065.4,True,18.0,18.0,300.0,536.0,16.283333,16.666667,55.0,4.2,20.0,26.0,11.99,12.28,140852.0,205.0,0.79,48.87,11168.0,24.0,28.0,293.1,PECLL,2024-09-07 15:00:00,UTC -05:00,CALLAO,NaN,18.0,300.0,310.0,17.0,834.0,51.0,0.0,0.0,27.0,13.0,24074210.0,COBUN,BUENAVENTURA,False,True,NaN,NaN,AWAITING BERTH,NaN,2024-09-01 16:00:00,UTC -05:00,NaT,NaN,NaN,NaN,NaN,2024-09-04 15:00:00,UTC -05:00,NaN,NaN,NaN,6832.0,4336.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,18.0,0.0,0.0,65.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,17430.0,0.0,0.0,1600.0,0.0,0.0,2680.0,0.0,2/O,CE,True,True,1.4,NaN,NaN,NaN,NaN,NaN,NaN,370.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,5672.0,0,53800.0,NaN,NaN,NaN,41.1,NaN,NaN,3.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,6.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,5157.0,0.0,0.0,0.0,0.0,NaN,18.0,NaN,15.6,2.4
8164,d1816f02-bfb5-4df5-9852-6625ba928aa4,MSC CHIYO,9947110.0,FA428A,2024-09-06,2024-09-06 12:00:00,UTC -05:00,NOON,AT SEA,0615S,08131W,96.8,79065.4,True,24.0,24.0,406.0,761.0,16.345833,16.916667,56.3,4.9,30.0,12.0,12.40,12.40,142838.0,156.0,0.44,137.40,11168.0,16.0,16.0,392.3,PECLL,2024-09-07 15:00:00,UTC -05:00,CALLAO,NaN,24.0,300.0,310.0,17.0,429.0,27.0,0.0,0.0,27.0,13.0,24155100.0,COBUN,BUENAVENTURA,False,True,NaN,NaN,AWAITING BERTH,NaN,2024-09-01 16:00:00,UTC -05:00,NaT,NaN,NaN,NaN,NaN,2024-09-04 15:00:00,UTC -05:00,NaN,NaN,NaN,6832.0,4336.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,96.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,19640.0,0.0,0.0,0.0,0.0,0.0,2920.0,0.0,2/O,CE,True,True,1.6,NaN,NaN,NaN,NaN,NaN,NaN,370.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,6516.0,0,70000.0,NaN,NaN,NaN,41.1,NaN,NaN,2.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,4.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,443.0,0.0,0.0,0.0,0.0,5060.2,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
8165,c867b600-d7f0-4d5e-99c7-799178ec1258,MSC CHIYO,9947110.0,FA428A,2024-09-07,2024-09-07 12:00:00,UTC -05:00,NOON,AT SEA,1144S,07737W,90.4,79065.4,True,24.0,24.0,397.3,738.0,16.475000,16.554167,55.8,6.2,20.0,17.0,12.90,12.30,145378.0,128.0,0.19,95.69,11168.0,15.0,16.0,395.4,PECLL,2024-09-07 15:00:00,UTC -05:00,CALLAO,NaN,24.0,300.0,310.0,17.0,32.0,3.0,0.0,0.0,27.0,13.0,24235410.0,COBUN,BUENAVENTURA,False,True,NaN,NaN,AWAITING BERTH,NaN,2024-09-01 16:00:00,UTC -05:00,NaT,NaN,NaN,NaN,NaN,2024-09-04 15:00:00,UTC -05:00,NaN,NaN,NaN,6832.0,4336.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.9,0.0,24.0,0.0,0.0,90.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3,0.0,0.0,0.0,0.0,0.0,0.0,18400.0,0.0,0.0,0.0,1560.0,0.0,2583.0,0.0,2/O,CE,True,True,1.4,NaN,NaN,NaN,NaN,NaN,NaN,360.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,10494.0,0,66000.0,NaN,NaN,NaN,21.7,NaN,NaN,2.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,4.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,4968.3,0.0,0.0,0.0,0.0,NaN,24.0,NaN,21.6,2.4
8166,d561458f-e602-48ad-bdd7-e9e3b30b8bfc,MSC CHIYO,9947110.0,FA428A,2024-09-08,2024-09-07 13:30:00,UTC -05:00,EOSP,AT SEA,1158S,07722W,2.4,79065.4,True,1.5,1.5,18.0,21.0,11.933333,12.000000,40.1,5.4,20.0,14.0,12.90,12.30,145378.0,128.0,0.14,76.43,11168.0,15.0,16.0,17.9,PECLL,2024-09-07 15:00:00,UTC -05:00,NaN,NaN,1.5,220.0,240.0,17.0,NaN,NaN,0.0,0.0,27.0,13.0,24239020.0,PECLL,CALLAO,True,True,NaN,NaN,AWAITING BERTH,NaN,2024-09-07 17:00:00,UTC -05:00,NaT,NaN,NaN,NaN,NaN,2024-09-04 15:00:00,UTC -05:00,NaN,NaN,NaN,6832.0,4336.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.5,0.0,0.0,0.0,0.0,0.0,1.5,0.0,0.0,0.5,0.0,0.2,0.0,0.0,2.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.0,0.0,0.0,0.0,0.0,0.0,7500.0,2667.0,0.0,0.0,1000.0,0.0,2000.0,0.0,2/O,CE,True,True,0.5,NaN,NaN,NaN,NaN,NaN,NaN,360.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,10494.0,0,4900.0,NaN,NaN,NaN,21.7,NaN,NaN,2.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,4.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,4964.9,0.0,0.0,0.0,0.0,NaN,1.5,NaN,1.5,0.0
8173,1ccbe732-926d-41ae-bfd9-7fbaa4c65b90,MSC CHIYO,9947110.0,FA428A,2024-09-08,2024-09-07 17:18:00,UTC -05:00,BRTH,DRIFTING,1158S,07722W,1.8,79065.4,True,2.1,2.1,16.6,25.0,0.000000,0.000000,0.0,0.0,0.0,0.0,12.90,12.30,145378.0,0.0,0.00,0.00,11168.0,15.0,16.0,NaN,PECLL,2024-09-07 15:00:00,UTC -05:00,NaN,NaN,3.8,220.0,240.0,17.0,NaN,NaN,0.0,0.0,27.0,13.0,24242430.0,PECLL,CALLAO,False,True,NaN,NaN,AWAITING BERTH,NaN,2024-09-07 17:00:00,UTC -05:00,2024-09-07 15:00:00,UTC -05:00,3.8,3.0,0.0,2024-09-08 15:00:00,UTC -05:00,NaN,NaN,NaN,6832.0,4336.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.1,0.0,0.0,0.0,0.0,0.0,3.8,3.3,3.3,3.4,0.0,0.0,0.0,0.0,1.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6,0.0,0.0,0.0,0.0,0.0,0.0,3840.0,1053.0,960.0,960.0,850.0,0.0,0.0,0.0,2/O,CE,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,360.0,16.6,16.7,NaN,False,NaT,NaN,NaT,NaN,10494.0,0,11500.0,NaN,NaN,NaN,21.7,NaN,NaN,0.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,5.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,4959.0,0.0,0.0,NaN,NaN,NaN,3.8,NaN,0.0,3.8
8174,57733930-7908-4f19-8416-11ec5267386b,MSC CHIYO,9947110.0,FA428A,2024-09-08,2024-09-08 12:00:00,UTC -05:00,PORT,IN PORT,1158S,07722W,0.0,79065.4,True,18.7,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,12.90,12.30,145378.0,0.0,0.00,0.00,11168.0,18.0,16.0,NaN,PECLL,2024-09-07 15:00:00,UTC -05:00,NaN,NaN,18.7,100.0,100.0,17.0,NaN,NaN,0.0,0.0,27.0,13.0,24242430.0,PECLL,CALLAO,False,True,NaN,NaN,AWAITING BERTH,NaN,2024-09-07 17:00:00,UTC -05:00,NaT,NaN,NaN,NaN,NaN,2024-09-08 15:00:00,UTC -05:00,NaN,NaN,NaN,6832.0,4336.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2032.0,0.0,0.0,0.0,2/O,CE,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,355.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,10494.0,0,38000.0,NaN,NaN,NaN,25.9,NaN,NaN,0.0,0.0,300.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,6.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,4948.0,0.0,0.0,NaN,NaN,NaN,18.7,NaN,0.0,18.7
35411,387f45f5-ab06-45e1-9802-acb4c9615ddf,MSC CHIYO,9947110.0,FA428A,2024-09-09,2024-09-08 15:12:00,UTC -05:00,SAIL,IN PORT,1158S,07722W,0.0,62864.1,True,3.2,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,12.10,10.90,129119.0,0.0,0.00,0.00,10272.0,18.0,16.0,NaN,CLSAI,2024-09-11 20:00:00,UTC -03:00,SAN ANTONIO,NaN,3.2,100.0,100.0,17.0,NaN,NaN,0.0,0.0,27.0,13.0,24242430.0,PECLL,CALLAO,False,True,NaN,NaN,AWAITING BERTH,NaN,2024-09-07 17:00:00,UTC -05:00,NaT,NaN,NaN,NaN,0.0,2024-09-08 15:00:00,UTC -05:00,NaN,4324.7,20526.0,5062.0,5210.0,0,NaN,False,False,0.0,5,5,No,0,0,YES,0,6.06,0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.8,0.2,0.2,3.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1250.0,1000.0,1000.0,1562.0,0.0,0.0,0.0,2/O,CE,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,255.0,NaN,NaN,0.0,False,NaT,NaN,NaT,NaN,10494.0,0,6400.0,NaN,NaN,NaN,25.9,NaN,NaN,0.0,0.0,0.0,0.0,1,NaN,94.0,98.0,51.0,0,0,0.0,0.0,0.0,0.0,NaN,False,NaN,NaN,NaN,NaN,4.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,4945.9,0.0,0.0,NaN,NaN,0.0,3.2,0.0,0.0,3.2

In [39]:
cf[cf['IMO No'].isnull()]['VSL'].unique()

array(['MSC MAURA'], dtype=object)

In [41]:
cf.loc[df['VSL'] == 'MSC TURIN II', 'IMO No'] = 9256365

In [44]:
cf.loc[df['VSL'] == 'MSC MAURA', 'IMO No'] = 9962536

In [48]:
cf['IMO No'].isnull().sum()

0

In [50]:
cf

,GID,VSL,IMO No,VOY,Corrected Date,REPORT DATE TIME,REPORT DATE TIME Offset,Report Type,Status,LAT,LONG,M E FOC,CARGO TOTAL,Has Cargo,STEAMING TIME,Total M E Hours Fuel Only,MILES BY GPS,OIL CYL,SPEED BY LOG,SPEED BY GPS,RPM,SLIP,WIND DIRECTION,WIND SPEED,DRAFT AFT,DRAFT FWD,DISPLACEMENT,COURSE AT SEA,WAVE HEIGHT,SEA DIRECTION,CARGO TOTAL TEU,AMBIENT TEMP,SW TEMP,MILES BY SPEED LOG,ETA PORT CODE,ETA DATE TIME,ETA DATE TIME Offset,ETA PORT,TIME CHANGE,TIME SEA,TEMP MIN,TEMP MAX,REQUESTED SPEED,REM DIST TO PILOT,REM TIME TO PILOT,TOTAL UNPLND STPGE TECH,TOTAL UNPLND STPGE OPE WX,REEFERS POSITIVE PLUGGED,REEFERS NEGATIVE PLUGGED,ME TOTAL REVS COUNTER,PORT CODE,PORT,AUX BLOWERS ON,HOLD VENTILATION ON,TIME HRS ANCHOR,TIME HRS DRIFT,REASON,TYPE OF DELAY,ETB DATE TIME,ETB DATE TIME Offset,PILOT DATE TIME,PILOT DATE TIME Offset,TIME MANOEUVRING,TUG ARR,TUG SHIFT,ETD DATE TIME,ETD DATE TIME Offset,SHIFT BERTH HOURS,CARGO LOAD,CARGO DISCH,TEU FULL,TEU EMPTY,BILGE REMOVED,GARBAGE REMOVED,GARBAGE REMVL REQSTD,GARBAGE REMVL CMPLSRY,FW SUPPLY,CY CREW SIGNED ON,CY CREW SIGNED OFF,CY DOCTORS VISIT,CY MAIL RECEIVED Ref NO,CY LUB OIL SAMPLE LANDED,CY CHECKD FOR STOWAWAYS,CY STOWAWAYS ON BOARD,CY DEP GM Mtr,CY REQUISITIONS RECEIVED,DISTANCE TO NEXT PILOT,TUG SAILING TRANSIT,STEAMING TIME M E Rsdl VLS,STEAMING TIME M E Rsdl HS,STEAMING TIME M E Rsdl ULS,STEAMING TIME M E Dstlt VLS,STEAMING TIME M E Dstlt ULS,STEAMING TIME M E Tnktnr Dstlt VLS,STEAMING TIME M E MDO,STEAMING TIME AUX 1,STEAMING TIME AUX 2,STEAMING TIME AUX 3,STEAMING TIME AUX 4,STEAMING TIME AUX 5,STEAMING TIME SH GEN,STEAMING TIME TG,FUEL M E Rsdl VLS,FUEL M E Rsdl HS,FUEL M E Rsdl ULS,FUEL M E Dstlt VLS,FUEL M E Dstlt ULS,FUEL M E MDO,FUEL M E LNG,FUEL M E Tnktnr Dstlt VLS,FUEL Aux Rsdl VLS,FUEL Aux Rsdl HS,FUEL Aux Rsdl ULS,FUEL Aux Dstlt VLS,FUEL Aux Dstlt ULS,FUEL Aux Tnktnr Dstlt VLS,FUEL Aux LNG,FUEL Aux MDO,FUEL Boiler Rsdl VLS,FUEL Boiler Rsdl HS,FUEL Boiler Rsdl ULS,FUEL Boiler Dstlt VLS,FUEL Boiler Dstlt ULS,FUEL Boiler Tnktnr Dstlt VLS,FUEL Boiler LNG,FUEL Boiler MDO,POWER KW,STEAMING LOAD KW AUX 1,STEAMING LOAD KW AUX 2,STEAMING LOAD KW AUX 3,STEAMING LOAD KW AUX 4,STEAMING LOAD KW AUX 5,STEAMING LOAD KW SH GEN,STEAMING LOAD KW TG,DECK LAST CHANGE USER,ENGINE LAST CHANGE USER,DECK PART IS COMPLETE,ENGINE PART IS COMPLETE,SCAVENGE PRESSURE,SECA ENTRY TIME,SECA ENTRY LAT,SECA ENTRY LONG,SECA EXIT TIME,SECA EXIT LAT,SECA EXIT LONG,ROB FRESH WATER,MANVRNG MILES BY GPS,MANVRNG MILES BY SPEED LOG,TANKTAINER TRANSFD QUANTITY,PILOT TAKEN,DATE TIME START TRANSIT,DATE TIME START TRANSIT Offset,DATE TIME END TRANSIT,DATE TIME END TRANSIT Offset,BALLAST,TANKTAINER NUMBER,STEAMING KWHR TOTAL,CY OTHERS,ROB FO SLUDGE,ROB LO SLUDGE,ROB BILGE,SLUDGE REMOVED FO,SLUDGE REMOVED LO,SEA STATE,CY LUB ADDED TO SYSTEM MECC,CY LUB ADDED TO SYSTEM AECC,CY LUB ADDED TO THRUSTERS,CY ME LO PURIFIER IN USE,CY BALLAST,CY BENDING MOMENT,CY SHEARING FORCE,CY TORTION MOMENT,CY SUPDT AUDITOR SIGNED ON,CY SUPDT AUDITOR SIGNED OFF,CY CASH RECEIVED,CY LUB OIL RECEIVED MECYL,CY LUB OIL RECEIVED MECC,CY LUB OIL RECEIVED AECC,CY M E UNDER PISTON TEMP,CY MAIL RECEIVED,WIND DIRECTION PORT STBD,SEA DIRECTION PORT STBD,TIME PILOT ONBOARD,GRADES ROB,SO2 CO2 RATIO,Bunker Order,Remarks,BDN Number,Fuel Type,Carbon Factor,Sulphur Content PC,Quantity,Port Delivery,Product Quality,Tanktainer Number_1,Supplier,Delivery,Vol Lt,Den,Vis,ROB Dstlt ULS,ROB Dstlt VLS,ROB Rsdl MDO,ROB Tnktnr Dstlt VLS,ROB Rsdl VLS,ROB Rsdl HS,ROB Rsdl ULS,ROB Rsdl LNG,ECA MILES,ECA TIME,EGCS DRY WASTE REMOVED,EGCS RUNNING TIME,EGCS WET SLURRY REMOVED,EGCS OPEN LOOP RUNNING TIME,EGCS CLOSED LOOP RUNNING TIME
0,60317d31-4c4d-43d7-876b-2f33e51aba38,AGIOS DIMITRIOS,9349605.0,IP434A,2024-09-01,2024-09-01 12:00:00,UTC +05:00,NOON,AT SEA,0151S,06734E,82.60,68806.0,True,24.0,24.0,414.199997,0.0,16.445833,17.258333,70.5,15.1,112.0,12.0,14.3,13.7,105028.9,206.0,3.37,152.92,5207.0,31.0,29.0,394.7,MUPLU,2024-09-04 12:00:00,UTC +04:00,PORT LOUIS,NaN,24.0,319.0,347.0,17.50,1260.7,72.0,0.0,0.0,7.0,16.0,203125380.0,INMUN,MUNDRA,False,False,NaN,NaN,WAITING FOR SCHEDULE,NaN,2024-08-26 12:00:00,UTC +05:30,NaT,NaN,NaN,NaN,NaN,2024-08-28 04:30:00,UTC +05:30,NaN,NaN,NaN,5184.0,23.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,24.0,0.0,0.0,0.0,0.0,0.00,82.6,0.0,0.0,0.0,0.0,0.0,0.0,0.00,9.2,0.0,0.0,0.00,0.0,0.0,0.0,1.5,0.0,0.0,0.0,0.00,0.0,0.0,0.0,16921.0,787.0,0.0,756.0,0.0,0.0,0.0,0.0,"SORIANO, DOMINADOR","DEREVIANKO, YURII",True,True,0.69,NaN,NaN,NaN,NaN,NaN,NaN,218.1,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8752.0,0,1500.0,NaN,NaN,NaN,78.2,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,190.90,664.3,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
1,a2bdb2d1-315a-4ded-a8a3-09b823a77d40,AGIOS DIMITRIOS,9349605.0,IP434A,2024-09-02,2024-09-02 12:00:00,UTC +05:00,NOON,AT SEA,0813S,06439E,82.10,68806.0,True,24.0,24.0,418.100006,0.0,16.287500,17.420833,70.1,13.8,90.0,15.0,14.3,13.7,104947.4,198.0,2.98,139.27,5207.0,29.0,27.0,390.9,MUPLU,2024-09-04 12:00:00,UTC +04:00,PORT LOUIS,NaN,24.0,317.0,343.0,17.56,843.0,48.0,0.0,0.0,7.0,16.0,203226330.0,INMUN,MUNDRA,False,False,NaN,NaN,WAITING FOR SCHEDULE,NaN,2024-08-26 12:00:00,UTC +05:30,NaT,NaN,NaN,NaN,NaN,2024-08-28 04:30:00,UTC +05:30,NaN,NaN,NaN,5184.0,23.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,24.0,0.0,0.0,0.0,0.0,0.00,82.1,0.0,0.0,0.0,0.0,0.0,0.0,0.00,9.4,0.0,0.0,0.00,0.0,0.0,0.0,1.6,0.0,0.0,0.0,0.00,0.0,0.0,0.0,16839.0,749.0,0.0,750.0,0.0,0.0,0.0,0.0,"SORIANO, DOMINADOR","DEREVIANKO, YURII",True,True,0.67,NaN,NaN,NaN,NaN,NaN,NaN,229.7,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8752.0,0,1500.0,NaN,NaN,NaN,46.6,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,189.30,572.8,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
2,8c9d6f41-23c2-4866-abf7-ce2b58c80327,AGIOS DIMITRIOS,9349605.0,IP434A,2024-09-03,2024-09-03 12:00:00,UTC +04:00,NOON,AT SEA,1445S,06131E,85.50,68806.0,True,25.0,25.0,431.200012,0.0,15.808000,17.248000,70.2,14.1,92.0,18.0,14.3,13.7,104854.6,203.0,3.63,134.82,5207.0,26.0,24.0,395.2,MUPLU,2024-09-04 12:00:00,UTC +04:00,PORT LOUIS,NaN,25.0,314.0,334.0,17.15,411.8,24.0,0.0,0.0,7.0,16.0,203331700.0,INMUN,MUNDRA,False,False,NaN,NaN,WAITING FOR SCHEDULE,NaN,2024-08-26 12:00:00,UTC +05:30,NaT,NaN,NaN,NaN,NaN,2024-08-28 04:30:00,UTC +05:30,NaN,NaN,NaN,5184.0,23.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,25.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0,25.0,0.0,0.0,0.0,0.0,0.00,85.5,0.0,0.0,0.0,0.0,0.0,0.0,0.00,10.0,0.0,0.0,0.00,0.0,0.0,0.0,1.5,0.0,0.0,0.0,0.00,0.0,0.0,0.0,16887.0,778.0,0.0,801.0,0.0,0.0,0.0,0.0,"SORIANO, DOMINADOR","DEREVIANKO, YURII",True,True,0.68,NaN,NaN,NaN,NaN,NaN,NaN,233.9,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8752.0,0,1550.0,NaN,NaN,NaN,35.8,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,187.80,477.3,0.0,0.0,0.0,0.0,NaN,25.0,NaN,25.0,0.0
3,6df7e111-d94e-4d1c-acfe-027d4a1092b6,AGIOS DIMITRIOS,9349605.0,IP434A,2024-09-04,2024-09-04 11:00:00,UTC +04:00,EOSP,AT SEA,1956S,05725E,77.00,68806.0,True,23.0,23.0,396.400013,0.0,16.156522,17.234783,71.3,15.8,45.0,14.0,14.3,13.7,104771.9,186.0,0.86,126.54,5207.0,24.0,23.0,371.6,MUPLU,2024-09-04 12:00:00,UTC +04:00,NaN,NaN,23.0,303.0,325.0,17.15,NaN,NaN,0.0,0.0,7.0,16.0,203429800.0,MUPLU,PORT LOUIS,False,False,NaN,NaN,WAITING FOR SCHEDULE,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,2024-08-28 04:30:00,UTC +05:30,NaN,NaN,NaN,5184.0,23.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,23.0,0.0,0.0,0.0,0.0,0.0,1.2,22.2,23.0,0.0,0.0,0.0,0.0,17.20,59.8,0.0,0.0,0.0,0.0,0.0,0.0,1.80,7.1,0.0,0.0,1.00,0.0,0.0,0.0,0.7,0.0,0.0,0.0,0.00,0.0,0.0,0.0,16498.0,0.0,645.0,649.0,0.0,0.0,0.0,0.0,"SORIANO, DOMINADOR","DEREVIANKO, YURII",True,True,0.54,NaN,NaN,NaN,NaN,NaN,NaN,238.8,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8752.0,0,1300.0,NaN,NaN,NaN,41.1,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,584.80,0.0,0.0,0.0,168.10,410.4,0.0,0.0,0.0,0.0,NaN,NaN,NaN,23.0,NaN
4,61f26af2-e334-4ea1-830e-b2d314c5e087,AGIOS DIMITRIOS,9349605.0,IP434A,2024-09-04,2024-09-04 12:00:00,UTC +04:00,DLY A,DRIFTING,2007S,05723E,0.70,68806.0,True,1.0,1.0,11.200000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,14.3,13.7,104770.9,0.0,0.00,0.00,5207.0,24.0,23.0,NaN,MUPLU,2024-09-04 12:00:00,UTC +04:00,NaN,NaN,1.0,77.0,77.0,17.15,NaN,NaN,0.0,0.0,7.0,16.0,203431260.0,MUPLU,PORT LOUIS,False,False,0.0,0.0,WAITING FOR SCHEDULE,DRIFTING,NaT,NaN,NaT,NaN,1.0,NaN,NaN,2024-09-05 12:00:00,UTC +04:00,NaN,NaN,NaN,5184.0,23.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.70,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.20,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.1,0.0,0.0,0.0,0.00,0.0,0.0,0.0,2598.0,0.0,529.0,550.0,0.0,0.0,0.0,0.0,"SORIANO, DOMINADOR","DEREVIANKO, YURII",True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,238.8,11.2,10.7,NaN,False,NaT,NaN,NaT,NaN,8752.0,0,1100.0,NaN,NaN,NaN,41.1,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,167.10,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135255,3e92dec8-7bdd-4b93-a636-55153e51a23c,WEC VAN RUYSDAEL,9287792.0,EL439A,2024-10-01,2024-09-30 15:00:00,UTC +02:00,SAIL,IN PORT,4329N,00308W,0.07,6534.0,True,0.3,0.3,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,7.3,7.3,13923.0,0.0,0.00,0.00,526.0,17.0,18.0,NaN,IEDUB,2024-10-02 16:00:00,UTC +02:00,DUBLIN,NaN,3.0,415.0,450.0,15.00,NaN,NaN,0.0,0.0,9.0,0.0,9000.0,ESBIO,BILBAO,False,False,NaN,NaN,Berth Occupied,NaN,2024-09-30 07:00:00,UTC +02:00,NaT,NaN,NaN,NaN,0.0,2024-09-30 14:00:00,UTC +02:00,NaN,2563.0,0.0,514.0,12.0,0,NaN,False,False,0.0,0,0,No,0,0,0,0,0.99,0,NaN,NaN,0.3,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.5,0.0,0.0,0.0,0.3,0.0,0.07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.05,0.0,0.0,0.0,1138.0,140.0,100.0,0.0,0.0,0.0,200.0,0.0,Master,Ch Eng,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.0,NaN,NaN,0.0,False,NaT,NaN,NaT,NaN,1477.0,0,530.0,NaN,NaN,NaN,1.1,NaN,NaN,0.0,0.0,0.0,0.0,1,NaN,89.0,70.0,25.0,0,0,0.0,0.0,0.0,0.0,NaN,False,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,262.82,0.0,0.0,0.0,344.39,0.0,0.0,0.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN
135256,4c897b0e-5851-4f59-a709-5dda42e04d75,WEC VAN RUYSDAEL,9287792.0,EL439A,2024-10-01,2024-09-30 15:48:00,UTC +02:00,COSP,DRIFTING,4324N,00305W,0.58,6534.0,True,0.8,0.8,5.000000,0.0,0.000000,0.000000,0.0,0.0,10.0,10.0,7.3,7.3,13923.0,320.0,0.56,10.00,526.0,17.0,18.0,NaN,IEDUB,2024-10-02 16:00:00,UTC +02:00,DUBLIN,NaN,0.8,415.0,450.0,15.00,NaN,NaN,0.0,0.0,9.0,0.0,24000.0,ESBIO,BILBAO,False,False,NaN,NaN,Berth Occupied,NaN,2024-09-30 07:00:00,UTC +02:00,NaT,NaN,0.7,NaN,NaN,2024-09-30 14:00:00,UTC +02:00,NaN,NaN,NaN,514.0,12.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,671.0,0,0.8,0.0,0.0,0.0,0.0,0.0,0.0,0.8,0.8,0.0,0.0,0.0,0.8,0.0,0.58,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,3625.0,100.0,100.0,0.0,0.0,0.0,200.0,0.0,Master,Ch Eng,True,True,0.80,NaN,NaN,NaN,NaN,NaN,NaN,55.0,5.0,5.0,NaN,True,2024-09-30 15:48:00,UTC +02:00,NaT,NaN,1477.0,0,320.0,NaN,NaN,NaN,1.1,NaN,NaN,3.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,0.5,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,262.78,0.0,0.0,0.0,343.81,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135301,036417e3-26a6-41ec-91d6-491b482d4e47,WEC VERMEER,9237371.0,EF439A,2024-09-30,2024-09-30 12:00:00,UTC +02:00,NOON,AT SEA,3434N,00808W,28.38,5338.4,True,24.0,24.0,400.999969,0.0,16.958333,16.708333,128.0,0.0,60.0,14.0,7.6,7.2,12753.3,228.0,1.36,128.69,542.0,22.0,22.0,407.0,ESSCT,2024-10-02 00:00:00,UTC +02:00,SANTA CRUZ DE TENERIFE,NaN,24.0,409.0,430.0,15.30,552.0,36.0,0.0,0.0,2.0,5.0,121686.0,ESVLC,VALENCIA,False,False,NaN,NaN,AHEAD OF SCHEDULE,NaN,2024-09-28 16:42:00,UTC +02:00,NaT,NaN,NaN,NaN,NaN,2024-09-29 01:00:00,UTC +02:00,NaN,NaN,NaN,541.0,1.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,28.38,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,6254.7,0.0,0.0,0.0,0.0,0.0,270.0,0.0,2O,CE,True,True,2.37,NaN,NaN,NaN,NaN,NaN,NaN,61.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,2369.0,NaN,0.0,NaN,NaN,NaN,0.1,NaN,NaN,4.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,337.74,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
135336,0aa0ae08-2574-4470-ae5b-d8b97da2ce81,XIN BIN ZHOU,9185413.0,HD438R,2024-09-30,2024-09-29 12:42:00,UTC +08:00,COSP,DRIFTING,0116N,10407E,4.63,1895.0,True,3.7,3.7,55.000000,0.0,0.000000,0.000000,0.0,0.0,20.0,10.0,7.9,3.7,20524.0,80.0,0.56,20.00,99.0,35.0,29.0,NaN,CNFOC,2024-10-04 12:00:00,UTC +08:00,FUZHOU,NaN,3.7,340.0,370.0,9.00,NaN,NaN,0.0,0.0,1.0,1.0,0.0,MYTPP,TANJUNG PELEPAS,False,False,NaN,NaN,DRIFTINGING FOR BERTH,NaN,2024-09-28 21:30:00,UTC +08:00,NaT,NaN,3.7,NaN,NaN,2024-09-29 11:00:00,UTC +08:00,NaN,NaN,NaN,92.0,7.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1728.0,0,3.7,0.0,0.0,0.0,0.0,0.0,0.0,3.7,0.0,3.7,0.0,0.0,0.0,0.0,4.63,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.62,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.13,0.0,0.0,0.0,8694.0,450.0,0.0,450.0,0.0,0.0,0.0,0.0,NaN,NaN,True,True,0.04,NaN,NaN,NaN,NaN,NaN,NaN,85.0,55.0,55.0,NaN,True,NaT,NaN,NaT,NaN,3822.0,0,0.0,NaN,NaN,NaN,19.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,1.0,NaN,0.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,161.38,0.0,0.0,0.0,731.19,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135337,910af70d-9d59-4e60-9d0e-3379c5f32898,XIN BIN ZHOU,9185413.0,HD438R,2024-09-30,2024-09-30 12:00:00,UTC +08:00,NOON,AT SEA,0554N,10649E,23.71,1895.0,True,23.3,23.3,328.000003,0.0,14.077253,14.077253,0.0,0.0,180.0,10.0,7.9,3.7,20524.0,27.0,3.27,180.01,99.0,35.0,29.0,328.0,CNFOC,2024-10-04 18:00:00,UTC +08:00,FUZHOU,NaN,23.3,310.0,340.0,13.50,1400.0,104.0,0.0,0.0,1.0,1.0,0.0,MYTPP,TANJUNG PELEPAS,True,False,NaN,NaN,DRIFTINGING FOR BERTH,NaN,2024-09-28 21:30:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2024-09-29 11:00:00,UTC +08:00,NaN,NaN,NaN,92.0,7.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.3,0.0,0.0,0.0,23.3,23.71,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.91,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,5216.0,0.0,0.0,650.0,0.0,0.0,0.0,0.0,NaN,NaN,True,True,0.02,NaN,NaN,NaN,NaN,NaN,NaN,82.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,3822.0,0,0.0,NaN,NaN,NaN,19.0,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,704.57,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN

In [51]:
import string
# Convert 'IMO No' column to strings
cf['IMO No'] = cf['IMO No'].astype(str)

# Translation table
translator = str.maketrans('', '', string.punctuation)

# Remove punctuation using translation table
cf['IMO No'] = cf['IMO No'].apply(lambda x: x.translate(translator))

# Convert cleaned strings back to integers
cf['IMO No'] = cf['IMO No'].astype(int)

In [54]:
cf['IMO No'].isnull().sum()

0

In [56]:
cf.head()

,GID,VSL,IMO No,VOY,Corrected Date,REPORT DATE TIME,REPORT DATE TIME Offset,Report Type,Status,LAT,LONG,M E FOC,CARGO TOTAL,Has Cargo,STEAMING TIME,Total M E Hours Fuel Only,MILES BY GPS,OIL CYL,SPEED BY LOG,SPEED BY GPS,RPM,SLIP,WIND DIRECTION,WIND SPEED,DRAFT AFT,DRAFT FWD,DISPLACEMENT,COURSE AT SEA,WAVE HEIGHT,SEA DIRECTION,CARGO TOTAL TEU,AMBIENT TEMP,SW TEMP,MILES BY SPEED LOG,ETA PORT CODE,ETA DATE TIME,ETA DATE TIME Offset,ETA PORT,TIME CHANGE,TIME SEA,TEMP MIN,TEMP MAX,REQUESTED SPEED,REM DIST TO PILOT,REM TIME TO PILOT,TOTAL UNPLND STPGE TECH,TOTAL UNPLND STPGE OPE WX,REEFERS POSITIVE PLUGGED,REEFERS NEGATIVE PLUGGED,ME TOTAL REVS COUNTER,PORT CODE,PORT,AUX BLOWERS ON,HOLD VENTILATION ON,TIME HRS ANCHOR,TIME HRS DRIFT,REASON,TYPE OF DELAY,ETB DATE TIME,ETB DATE TIME Offset,PILOT DATE TIME,PILOT DATE TIME Offset,TIME MANOEUVRING,TUG ARR,TUG SHIFT,ETD DATE TIME,ETD DATE TIME Offset,SHIFT BERTH HOURS,CARGO LOAD,CARGO DISCH,TEU FULL,TEU EMPTY,BILGE REMOVED,GARBAGE REMOVED,GARBAGE REMVL REQSTD,GARBAGE REMVL CMPLSRY,FW SUPPLY,CY CREW SIGNED ON,CY CREW SIGNED OFF,CY DOCTORS VISIT,CY MAIL RECEIVED Ref NO,CY LUB OIL SAMPLE LANDED,CY CHECKD FOR STOWAWAYS,CY STOWAWAYS ON BOARD,CY DEP GM Mtr,CY REQUISITIONS RECEIVED,DISTANCE TO NEXT PILOT,TUG SAILING TRANSIT,STEAMING TIME M E Rsdl VLS,STEAMING TIME M E Rsdl HS,STEAMING TIME M E Rsdl ULS,STEAMING TIME M E Dstlt VLS,STEAMING TIME M E Dstlt ULS,STEAMING TIME M E Tnktnr Dstlt VLS,STEAMING TIME M E MDO,STEAMING TIME AUX 1,STEAMING TIME AUX 2,STEAMING TIME AUX 3,STEAMING TIME AUX 4,STEAMING TIME AUX 5,STEAMING TIME SH GEN,STEAMING TIME TG,FUEL M E Rsdl VLS,FUEL M E Rsdl HS,FUEL M E Rsdl ULS,FUEL M E Dstlt VLS,FUEL M E Dstlt ULS,FUEL M E MDO,FUEL M E LNG,FUEL M E Tnktnr Dstlt VLS,FUEL Aux Rsdl VLS,FUEL Aux Rsdl HS,FUEL Aux Rsdl ULS,FUEL Aux Dstlt VLS,FUEL Aux Dstlt ULS,FUEL Aux Tnktnr Dstlt VLS,FUEL Aux LNG,FUEL Aux MDO,FUEL Boiler Rsdl VLS,FUEL Boiler Rsdl HS,FUEL Boiler Rsdl ULS,FUEL Boiler Dstlt VLS,FUEL Boiler Dstlt ULS,FUEL Boiler Tnktnr Dstlt VLS,FUEL Boiler LNG,FUEL Boiler MDO,POWER KW,STEAMING LOAD KW AUX 1,STEAMING LOAD KW AUX 2,STEAMING LOAD KW AUX 3,STEAMING LOAD KW AUX 4,STEAMING LOAD KW AUX 5,STEAMING LOAD KW SH GEN,STEAMING LOAD KW TG,DECK LAST CHANGE USER,ENGINE LAST CHANGE USER,DECK PART IS COMPLETE,ENGINE PART IS COMPLETE,SCAVENGE PRESSURE,SECA ENTRY TIME,SECA ENTRY LAT,SECA ENTRY LONG,SECA EXIT TIME,SECA EXIT LAT,SECA EXIT LONG,ROB FRESH WATER,MANVRNG MILES BY GPS,MANVRNG MILES BY SPEED LOG,TANKTAINER TRANSFD QUANTITY,PILOT TAKEN,DATE TIME START TRANSIT,DATE TIME START TRANSIT Offset,DATE TIME END TRANSIT,DATE TIME END TRANSIT Offset,BALLAST,TANKTAINER NUMBER,STEAMING KWHR TOTAL,CY OTHERS,ROB FO SLUDGE,ROB LO SLUDGE,ROB BILGE,SLUDGE REMOVED FO,SLUDGE REMOVED LO,SEA STATE,CY LUB ADDED TO SYSTEM MECC,CY LUB ADDED TO SYSTEM AECC,CY LUB ADDED TO THRUSTERS,CY ME LO PURIFIER IN USE,CY BALLAST,CY BENDING MOMENT,CY SHEARING FORCE,CY TORTION MOMENT,CY SUPDT AUDITOR SIGNED ON,CY SUPDT AUDITOR SIGNED OFF,CY CASH RECEIVED,CY LUB OIL RECEIVED MECYL,CY LUB OIL RECEIVED MECC,CY LUB OIL RECEIVED AECC,CY M E UNDER PISTON TEMP,CY MAIL RECEIVED,WIND DIRECTION PORT STBD,SEA DIRECTION PORT STBD,TIME PILOT ONBOARD,GRADES ROB,SO2 CO2 RATIO,Bunker Order,Remarks,BDN Number,Fuel Type,Carbon Factor,Sulphur Content PC,Quantity,Port Delivery,Product Quality,Tanktainer Number_1,Supplier,Delivery,Vol Lt,Den,Vis,ROB Dstlt ULS,ROB Dstlt VLS,ROB Rsdl MDO,ROB Tnktnr Dstlt VLS,ROB Rsdl VLS,ROB Rsdl HS,ROB Rsdl ULS,ROB Rsdl LNG,ECA MILES,ECA TIME,EGCS DRY WASTE REMOVED,EGCS RUNNING TIME,EGCS WET SLURRY REMOVED,EGCS OPEN LOOP RUNNING TIME,EGCS CLOSED LOOP RUNNING TIME
0,60317d31-4c4d-43d7-876b-2f33e51aba38,AGIOS DIMITRIOS,93496050,IP434A,2024-09-01,2024-09-01 12:00:00,UTC +05:00,NOON,AT SEA,0151S,06734E,82.6,68806.0,True,24.0,24.0,414.199997,0.0,16.445833,17.258333,70.5,15.1,112.0,12.0,14.3,13.7,105028.9,206.0,3.37,152.92,5207.0,31.0,29.0,394.7,MUPLU,2024-09-04 12:00:00,UTC +04:00,PORT LOUIS,NaN,24.0,319.0,347.0,17.50,1260.7,72.0,0.0,0.0,7.0,16.0,203125380.0,INMUN,MUNDRA,False,False,NaN,NaN,WAITING FOR SCHEDULE,NaN,2024-08-26 12:00:00,UTC +05:30,NaT,NaN,NaN,NaN,NaN,2024-08-28 04:30:00,UTC +05:30,NaN,NaN,NaN,5184.0,23.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,82.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.2,0.0,0.0,0.0,0.0,0.0,0.0,1.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16921.0,787.0,0.0,756.0,0.0,0.0,0.0,0.0,"SORIANO, DOMINADOR","DEREVIANKO, YURII",True,True,0.69,NaN,NaN,NaN,NaN,NaN,NaN,218.1,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8752.0,0,1500.0,NaN,NaN,NaN,78.2,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,190.9,664.3,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
1,a2bdb2d1-315a-4ded-a8a3-09b823a77d40,AGIOS DIMITRIOS,93496050,IP434A,2024-09-02,2024-09-02 12:00:00,UTC +05:00,NOON,AT SEA,0813S,06439E,82.1,68806.0,True,24.0,24.0,418.100006,0.0,16.287500,17.420833,70.1,13.8,90.0,15.0,14.3,13.7,104947.4,198.0,2.98,139.27,5207.0,29.0,27.0,390.9,MUPLU,2024-09-04 12:00:00,UTC +04:00,PORT LOUIS,NaN,24.0,317.0,343.0,17.56,843.0,48.0,0.0,0.0,7.0,16.0,203226330.0,INMUN,MUNDRA,False,False,NaN,NaN,WAITING FOR SCHEDULE,NaN,2024-08-26 12:00:00,UTC +05:30,NaT,NaN,NaN,NaN,NaN,2024-08-28 04:30:00,UTC +05:30,NaN,NaN,NaN,5184.0,23.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,82.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.4,0.0,0.0,0.0,0.0,0.0,0.0,1.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16839.0,749.0,0.0,750.0,0.0,0.0,0.0,0.0,"SORIANO, DOMINADOR","DEREVIANKO, YURII",True,True,0.67,NaN,NaN,NaN,NaN,NaN,NaN,229.7,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8752.0,0,1500.0,NaN,NaN,NaN,46.6,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,189.3,572.8,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
2,8c9d6f41-23c2-4866-abf7-ce2b58c80327,AGIOS DIMITRIOS,93496050,IP434A,2024-09-03,2024-09-03 12:00:00,UTC +04:00,NOON,AT SEA,1445S,06131E,85.5,68806.0,True,25.0,25.0,431.200012,0.0,15.808000,17.248000,70.2,14.1,92.0,18.0,14.3,13.7,104854.6,203.0,3.63,134.82,5207.0,26.0,24.0,395.2,MUPLU,2024-09-04 12:00:00,UTC +04:00,PORT LOUIS,NaN,25.0,314.0,334.0,17.15,411.8,24.0,0.0,0.0,7.0,16.0,203331700.0,INMUN,MUNDRA,False,False,NaN,NaN,WAITING FOR SCHEDULE,NaN,2024-08-26 12:00:00,UTC +05:30,NaT,NaN,NaN,NaN,NaN,2024-08-28 04:30:00,UTC +05:30,NaN,NaN,NaN,5184.0,23.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,25.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,85.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,1.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16887.0,778.0,0.0,801.0,0.0,0.0,0.0,0.0,"SORIANO, DOMINADOR","DEREVIANKO, YURII",True,True,0.68,NaN,NaN,NaN,NaN,NaN,NaN,233.9,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8752.0,0,1550.0,NaN,NaN,NaN,35.8,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,187.8,477.3,0.0,0.0,0.0,0.0,NaN,25.0,NaN,25.0,0.0
3,6df7e111-d94e-4d1c-acfe-027d4a1092b6,AGIOS DIMITRIOS,93496050,IP434A,2024-09-04,2024-09-04 11:00:00,UTC +04:00,EOSP,AT SEA,1956S,05725E,77.0,68806.0,True,23.0,23.0,396.400013,0.0,16.156522,17.234783,71.3,15.8,45.0,14.0,14.3,13.7,104771.9,186.0,0.86,126.54,5207.0,24.0,23.0,371.6,MUPLU,2024-09-04 12:00:00,UTC +04:00,NaN,NaN,23.0,303.0,325.0,17.15,NaN,NaN,0.0,0.0,7.0,16.0,203429800.0,MUPLU,PORT LOUIS,False,False,NaN,NaN,WAITING FOR SCHEDULE,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,2024-08-28 04:30:00,UTC +05:30,NaN,NaN,NaN,5184.0,23.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,23.0,0.0,0.0,0.0,0.0,0.0,1.2,22.2,23.0,0.0,0.0,0.0,0.0,17.2,59.8,0.0,0.0,0.0,0.0,0.0,0.0,1.8,7.1,0.0,0.0,1.0,0.0,0.0,0.0,0.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16498.0,0.0,645.0,649.0,0.0,0.0,0.0,0.0,"SORIANO, DOMINADOR","DEREVIANKO, YURII",True,True,0.54,NaN,NaN,NaN,NaN,NaN,NaN,238.8,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8752.0,0,1300.0,NaN,NaN,NaN,41.1,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,584.8,0.0,0.0,0.0,168.1,410.4,0.0,0.0,0.0,0.0,NaN,NaN,NaN,23.0,NaN
4,61f26af2-e334-4ea1-830e-b2d314c5e087,AGIOS DIMITRIOS,93496050,IP434A,2024-09-04,2024-09-04 12:00:00,UTC +04:00,DLY A,DRIFTING,2007S,05723E,0.7,68806.0,True,1.0,1.0,11.200000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,14.3,13.7,104770.9,0.0,0.00,0.00,5207.0,24.0,23.0,NaN,MUPLU,2024-09-04 12:00:00,UTC +04:00,NaN,NaN,1.0,77.0,77.0,17.15,NaN,NaN,0.0,0.0,7.0,16.0,203431260.0,MUPLU,PORT LOUIS,False,False,0.0,0.0,WAITING FOR SCHEDULE,DRIFTING,NaT,NaN,NaT,NaN,1.0,NaN,NaN,2024-09-05 12:00:00,UTC +04:00,NaN,NaN,NaN,5184.0,23.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2598.0,0.0,529.0,550.0,0.0,0.0,0.0,0.0,"SORIANO, DOMINADOR","DEREVIANKO, YURII",True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,238.8,11.2,10.7,NaN,False,NaT,NaN,NaT,NaN,8752.0,0,1100.0,NaN,NaN,NaN,41.1,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,167.1,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0

cf['IMO No'] = cf['IMO No'].str.isnumeric()

non_numeric_imo_unique = df[df['IMO No'].astype(str).str.isnumeric() == False]['IMO No'].unique()
non_numeric_imo_unique

df['IMO No'] = df['IMO No'].str.strip('?')

In [250]:
df_sorted = cf.sort_values(by=['IMO No', 'REPORT DATE TIME'])

In [252]:
df_sorted

,GID,VSL,IMO No,VOY,Corrected Date,REPORT DATE TIME,REPORT DATE TIME Offset,Report Type,Status,LAT,LONG,M E FOC,CARGO TOTAL,Has Cargo,STEAMING TIME,Total M E Hours Fuel Only,MILES BY GPS,OIL CYL,SPEED BY LOG,SPEED BY GPS,RPM,SLIP,WIND DIRECTION,WIND SPEED,DRAFT AFT,DRAFT FWD,DISPLACEMENT,COURSE AT SEA,WAVE HEIGHT,SEA DIRECTION,CARGO TOTAL TEU,AMBIENT TEMP,SW TEMP,MILES BY SPEED LOG,ETA PORT CODE,ETA DATE TIME,ETA DATE TIME Offset,ETA PORT,TIME CHANGE,TIME SEA,TEMP MIN,TEMP MAX,REQUESTED SPEED,REM DIST TO PILOT,REM TIME TO PILOT,TOTAL UNPLND STPGE TECH,TOTAL UNPLND STPGE OPE WX,REEFERS POSITIVE PLUGGED,REEFERS NEGATIVE PLUGGED,ME TOTAL REVS COUNTER,PORT CODE,PORT,AUX BLOWERS ON,HOLD VENTILATION ON,TIME HRS ANCHOR,TIME HRS DRIFT,REASON,TYPE OF DELAY,ETB DATE TIME,ETB DATE TIME Offset,PILOT DATE TIME,PILOT DATE TIME Offset,TIME MANOEUVRING,TUG ARR,TUG SHIFT,ETD DATE TIME,ETD DATE TIME Offset,SHIFT BERTH HOURS,CARGO LOAD,CARGO DISCH,TEU FULL,TEU EMPTY,BILGE REMOVED,GARBAGE REMOVED,GARBAGE REMVL REQSTD,GARBAGE REMVL CMPLSRY,FW SUPPLY,CY CREW SIGNED ON,CY CREW SIGNED OFF,CY DOCTORS VISIT,CY MAIL RECEIVED Ref NO,CY LUB OIL SAMPLE LANDED,CY CHECKD FOR STOWAWAYS,CY STOWAWAYS ON BOARD,CY DEP GM Mtr,CY REQUISITIONS RECEIVED,DISTANCE TO NEXT PILOT,TUG SAILING TRANSIT,STEAMING TIME M E Rsdl VLS,STEAMING TIME M E Rsdl HS,STEAMING TIME M E Rsdl ULS,STEAMING TIME M E Dstlt VLS,STEAMING TIME M E Dstlt ULS,STEAMING TIME M E Tnktnr Dstlt VLS,STEAMING TIME M E MDO,STEAMING TIME AUX 1,STEAMING TIME AUX 2,STEAMING TIME AUX 3,STEAMING TIME AUX 4,STEAMING TIME AUX 5,STEAMING TIME SH GEN,STEAMING TIME TG,FUEL M E Rsdl VLS,FUEL M E Rsdl HS,FUEL M E Rsdl ULS,FUEL M E Dstlt VLS,FUEL M E Dstlt ULS,FUEL M E MDO,FUEL M E LNG,FUEL M E Tnktnr Dstlt VLS,FUEL Aux Rsdl VLS,FUEL Aux Rsdl HS,FUEL Aux Rsdl ULS,FUEL Aux Dstlt VLS,FUEL Aux Dstlt ULS,FUEL Aux Tnktnr Dstlt VLS,FUEL Aux LNG,FUEL Aux MDO,FUEL Boiler Rsdl VLS,FUEL Boiler Rsdl HS,FUEL Boiler Rsdl ULS,FUEL Boiler Dstlt VLS,FUEL Boiler Dstlt ULS,FUEL Boiler Tnktnr Dstlt VLS,FUEL Boiler LNG,FUEL Boiler MDO,POWER KW,STEAMING LOAD KW AUX 1,STEAMING LOAD KW AUX 2,STEAMING LOAD KW AUX 3,STEAMING LOAD KW AUX 4,STEAMING LOAD KW AUX 5,STEAMING LOAD KW SH GEN,STEAMING LOAD KW TG,DECK LAST CHANGE USER,ENGINE LAST CHANGE USER,DECK PART IS COMPLETE,ENGINE PART IS COMPLETE,SCAVENGE PRESSURE,SECA ENTRY TIME,SECA ENTRY LAT,SECA ENTRY LONG,SECA EXIT TIME,SECA EXIT LAT,SECA EXIT LONG,ROB FRESH WATER,MANVRNG MILES BY GPS,MANVRNG MILES BY SPEED LOG,TANKTAINER TRANSFD QUANTITY,PILOT TAKEN,DATE TIME START TRANSIT,DATE TIME START TRANSIT Offset,DATE TIME END TRANSIT,DATE TIME END TRANSIT Offset,BALLAST,TANKTAINER NUMBER,STEAMING KWHR TOTAL,CY OTHERS,ROB FO SLUDGE,ROB LO SLUDGE,ROB BILGE,SLUDGE REMOVED FO,SLUDGE REMOVED LO,SEA STATE,CY LUB ADDED TO SYSTEM MECC,CY LUB ADDED TO SYSTEM AECC,CY LUB ADDED TO THRUSTERS,CY ME LO PURIFIER IN USE,CY BALLAST,CY BENDING MOMENT,CY SHEARING FORCE,CY TORTION MOMENT,CY SUPDT AUDITOR SIGNED ON,CY SUPDT AUDITOR SIGNED OFF,CY CASH RECEIVED,CY LUB OIL RECEIVED MECYL,CY LUB OIL RECEIVED MECC,CY LUB OIL RECEIVED AECC,CY M E UNDER PISTON TEMP,CY MAIL RECEIVED,WIND DIRECTION PORT STBD,SEA DIRECTION PORT STBD,TIME PILOT ONBOARD,GRADES ROB,SO2 CO2 RATIO,Bunker Order,Remarks,BDN Number,Fuel Type,Carbon Factor,Sulphur Content PC,Quantity,Port Delivery,Product Quality,Tanktainer Number_1,Supplier,Delivery,Vol Lt,Den,Vis,ROB Dstlt ULS,ROB Dstlt VLS,ROB Rsdl MDO,ROB Tnktnr Dstlt VLS,ROB Rsdl VLS,ROB Rsdl HS,ROB Rsdl ULS,ROB Rsdl LNG,ECA MILES,ECA TIME,EGCS DRY WASTE REMOVED,EGCS RUNNING TIME,EGCS WET SLURRY REMOVED,EGCS OPEN LOOP RUNNING TIME,EGCS CLOSED LOOP RUNNING TIME
4438,917ebf03-3390-454f-89aa-dccf9db97a7c,MSC AURELIA,76021200,407,2024-10-01,2024-10-01 06:12:00,UTC +02:00,EOSP,AT SEA,4329N,01625E,10.80,276.53,True,10.4,10.4,134.0,0.0,11.346154,12.884615,185.0,1.0,20.0,20.0,5.9,5.0,12180.0,41.0,0.46,49.18,NaN,24.0,22.0,118.0,HRSPU,2024-10-01 07:00:00,UTC +02:00,NaN,NaN,10.4,304.0,344.0,12.6,NaN,NaN,0.0,0.0,0.0,1.0,0.0,HRSPU,SPLIT,False,False,NaN,NaN,No prospects,NaN,2024-10-01 07:00:00,UTC +02:00,NaT,NaN,NaN,NaN,NaN,2024-09-30 19:30:00,UTC +02:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,10.4,0.0,0.0,10.4,0.0,10.4,10.4,0.0,0.0,0.0,0.0,0.00,0.0,0.0,10.80,0.0,0.0,0.0,0.0,0.00,0.0,0.0,2.45,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,5900.0,370.0,0.0,370.0,370.0,0.0,0.0,0.0,MASTER,CE,True,True,0.9,NaN,NaN,NaN,NaN,NaN,NaN,310.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,534.0,NaN,0.0,NaN,NaN,NaN,25.8,NaN,NaN,2.0,0.0,0.0,0.0,Both,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,299.34,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
4445,2b94394f-9e20-45d4-8dcb-78aad2db8913,MSC AURELIA,76021200,407,2024-10-01,2024-10-01 06:48:00,UTC +02:00,BRTH,DRIFTING,4329N,01625E,0.31,276.53,True,0.6,0.6,1.4,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,5.9,5.0,12180.0,0.0,0.00,0.00,NaN,24.0,22.0,NaN,HRSPU,2024-10-01 07:00:00,UTC +02:00,NaN,NaN,0.6,304.0,337.0,12.6,NaN,NaN,0.0,0.0,0.0,1.0,0.0,HRSPU,SPLIT,False,False,NaN,NaN,No prospects,NaN,2024-10-01 07:00:00,UTC +02:00,2024-10-01 06:18:00,UTC +02:00,0.7,0.0,0.0,2024-10-01 19:30:00,UTC +02:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.6,0.0,0.0,0.6,0.0,0.6,0.6,0.6,0.0,0.0,0.0,0.00,0.0,0.0,0.31,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,3000.0,350.0,0.0,350.0,350.0,240.0,0.0,0.0,MASTER,CE,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,309.0,1.4,1.4,NaN,False,NaT,NaN,NaT,NaN,534.0,NaN,0.0,NaN,NaN,NaN,25.8,NaN,NaN,0.0,0.0,0.0,0.0,Both,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,298.86,0.0,0.0,0.0,0.0,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4446,97f87d01-9113-47e8-ab85-6a67d077928d,MSC AURELIA,76021200,407,2024-10-01,2024-10-01 12:00:00,UTC +02:00,PORT,IN PORT,4329N,01625E,0.00,276.53,True,5.2,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,5.9,5.0,12180.0,0.0,0.00,0.00,NaN,24.0,22.0,NaN,HRSPU,2024-10-01 07:00:00,UTC +02:00,NaN,NaN,5.2,70.0,70.0,12.6,NaN,NaN,0.0,0.0,0.0,1.0,0.0,HRSPU,SPLIT,False,False,NaN,NaN,No prospects,NaN,2024-10-01 07:00:00,UTC +02:00,NaT,NaN,NaN,NaN,NaN,2024-10-01 19:30:00,UTC +02:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.2,0.0,5.2,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.92,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.03,0.0,0.0,0.0,0.0,400.0,0.0,400.0,0.0,0.0,0.0,0.0,MASTER,CE,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,300.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,534.0,NaN,0.0,NaN,NaN,NaN,25.8,NaN,NaN,0.0,0.0,0.0,0.0,Both,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,297.91,0.0,0.0,0.0,0.0,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4453,037d12cb-b788-4b87-8d0f-2a5e85d58a09,MSC AURELIA,76021200,407,2024-10-02,2024-10-01 19:30:00,UTC +02:00,SAIL,IN PORT,4329N,01625E,0.00,278.03,True,7.5,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,5.9,5.0,12180.0,0.0,0.00,0.00,NaN,24.0,22.0,NaN,ITAOI,2024-10-02 07:00:00,UTC +02:00,ANCONA,NaN,7.5,70.0,70.0,12.6,NaN,NaN,0.0,0.0,0.0,1.0,0.0,HRSPU,SPLIT,False,False,NaN,NaN,No prospects,NaN,2024-10-01 07:00:00,UTC +02:00,NaT,NaN,NaN,NaN,0.0,2024-10-01 19:30:00,UTC +02:00,NaN,278.03,276.53,NaN,NaN,0,NaN,False,False,0.0,0,0,No,0,0,0,0,3.4,0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.5,0.0,7.5,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,1.33,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.04,0.0,0.0,0.0,0.0,400.0,0.0,400.0,0.0,0.0,0.0,0.0,MASTER,CE,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,291.0,NaN,NaN,0.0,False,NaT,NaN,NaT,NaN,534.0,NaN,0.0,NaN,NaN,NaN,25.8,NaN,NaN,0.0,0.0,0.0,0.0,Both,NaN,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,NaN,False,NaN,NaN,NaN,NaN,0.001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,296.54,0.0,0.0,0.0,0.0,0.00,0.0,0.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN
4454,d93905d9-60aa-4acb-b662-995ff2847bb3,MSC AURELIA,76021200,407,2024-10-02,2024-10-01 19:48:00,UTC +02:00,COSP,DRIFTING,4329N,01625E,0.16,278.03,True,0.3,0.3,1.2,0.0,0.000000,0.000000,0.0,0.0,150.0,7.0,5.9,5.0,12180.0,215.0,0.28,150.00,NaN,24.0,22.0,NaN,ITAOI,2024-10-02 07:00:00,UTC +02:00,ANCONA,NaN,0.3,301.0,339.0,11.5,NaN,NaN,0.0,0.0,0.0,1.0,0.0,HRSPU,SPLIT,False,False,NaN,NaN,No prospects,NaN,2024-10-01 07:00:00,UTC +02:00,NaT,NaN,0.3,NaN,NaN,2024-10-01 19:30:00,UTC +02:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,135.0,0,0.0,0.0,0.0,0.0,0.3,0.0,0.0,0.3,0.0,0.3,0.3,0.3,0.0,0.0,0.0,0.00,0.0,0.0,0.16,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,3000.0,400.0,0.0,400.0,400.0,220.0,0.0,0.0,MASTER,CE,True,True,0.8,NaN,NaN,NaN,NaN,NaN,NaN,290.0,1.2,1.2,NaN,True,NaT,NaN,NaT,NaN,534.0,NaN,0.0,NaN,NaN,NaN,25.8,NaN,NaN,2.0,0.0,0.0,0.0,Both,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,0.4,NaN,0.001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,296.29,0.0,0.0,0.0,0.0,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30893,c874c857-3495-4f68-9dd3-d7e90604b759,MSC DOUALA VIII,99836950,UX438A,2024-10-09,2024-10-09 12:00:00,UTC +09:00,NOON,AT SEA,3000N,14220E,14.86,57754.00,True,24.0,24.0,262.0,214.0,10.250000,10.916667,37.5,3.0,20.0,12.0,12.9,12.9,94570.0,90.0,0.10,84.99,2972.0,29.0,28.0,246.0,PAPTY,2024-10-26 21:00:00,UTC -05:00,PANAMA,NaN,24.0,236.0,255.0,18.2,7856.0,427.0,0.0,0.0,4.0,31.0,1052186.0,KRPUS,BUSAN,True,True,NaN,NaN,BERTH CONGESTION,NaN,2024-10-05 14:00:00,UTC +09:00,NaT,NaN,NaN,NaN,NaN,2024-10-06 15:00:00,UTC +09:00,NaN,NaN,NaN,2774.0,198.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,14.86,0.0,0.0,0.00,0.0,0.0,0.0,0.0,8.96,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.19,0.0,0.0,0.0,3287.0,0.0,0.0,0.0,1630.0,0.0,0.0,0.0,2O,CHIEF ENGINEER,True,True,0.2,NaN,NaN,NaN,NaN,NaN,NaN,200.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8942.0,0,39115.0,"Vessel Reduced Speed to 11 kts to avoid TRS, a...",NaN,NaN,38.8,NaN,NaN,1.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,830.83,0.0,0.0,0.0,0.0,1995.90,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
30894,450e0a93-096b-4348-876f-612a526b9030,MSC DOUALA VIII,99836950,UX438A,2024-10-10,2024-10-10 12:00:00,UTC +10:00,NOON,AT SEA,3000N,14609E,15.53,57754.00,True,17.1,17.1,203.0,195.0,11.988304,11.871345,43.0,8.1,70.0,17.0,12.9,12.9,94500.0,90.0,1.65,110.77,2972.0,29.0,28.0,205.0,PAPTY,2024-10-26 21:00:00,UTC -05:00,PANAMA,NaN,23.0,302.0,319.0,19.0,7657.0,405.0,0.0,5.9,4.0,31.0,1096305.0,KRPUS,BUSAN,False,True,NaN,NaN,BERTH CONGESTION,NaN,2024-10-05 14:00:00,UTC +09:00,NaT,NaN,NaN,NaN,NaN,2024-10-06 15:00:00,UTC +09:00,NaN,NaN,NaN,2774.0,198.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,17.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.0,0.0,0.0,0.0,0.0,15.53,0.0,0.0,0.00,0.0,0.0,0.0,0.0,8.72,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.50,0.0,0.0,0.0,5106.0,0.0,0.0,0.0,1671.0,0.0,0.0,0.0,2O,CHIEF ENGINEER,True,True,1.7,NaN,NaN,NaN,NaN,NaN,NaN,195.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8942.0,0,38433.0,Vessel drifting to adjust Bad weather passing.,NaN,NaN,38.8,NaN,NaN,4.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,1.820,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,830.33,0.0,0.0,0.0,0.0,1971.65,0.0,0.0,0.0,0.0,NaN,23.0,NaN,23.0,0.0
30895,80ce03b1-385d-4e36-8f23-12f20f0da110,MSC DOUALA VIII,99836950,UX438A,2024-10-11,2024-10-11 12:00:00,UTC +10:00,NOON,AT SEA,3000N,15427E,59.01,57754.00,True,24.0,24.0,432.0,601.0,17.791667,18.000000,61.9,3.2,20.0,22.0,12.9,12.9,94430.0,91.0,0.36,70.44,2972.0,29.0,28.0,427.0,PAPTY,2024-10-27 21:00:00,UTC -05:00,PANAMA,NaN,24.0,302.0,336.0,18.0,7225.0,401.0,0.0,0.0,4.0,31.0,1185403.0,KRPUS,BUSAN,False,True,NaN,NaN,BERTH CONGESTION,NaN,2024-10-05 14:00:00,UTC +09:00,NaT,NaN,NaN,NaN,NaN,2024-10-06 15:00:00,UTC +09:00,NaN,NaN,NaN,2774.0,198.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,59.01,0.0,0.0,0.00,0.0,0.0,0.0,0.0,8.62,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,14207.0,0.0,0.0,0.0,1562.0,0.0,0.0,0.0,2O,CHIEF ENGINEER,True,True,1.8,NaN,NaN,NaN,NaN,NaN,NaN,185.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8942.0,0,37482.0,NaN,NaN,NaN,52.9,NaN,NaN,2.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,2.060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.0,1904.02,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
30896,91101114-2203-428a-a96b-93984bd454f2,MSC DOUALA VIII,99836950,UX438A,2024-10-12,2024-10-12 12:00:00,UTC +11:00,NOON,AT SEA,3000N,16219E,54.75,57754.00,True,23.0,23.0,410.0,541.0,17.304348,17.826087,0.0,0.0,10.0,25.0,12.9,12.9,94370.0,92.0,0.37,32.58,2972.0,29.0,28.0,398.0,PAPTY,2024-10-27 21:00:00,UTC -05:00,PANAMA,NaN,23.0,295.0,331.0,18.0,6815.0,377.0,0.0,0.0,4.0,31.0,1268904.0,KRPUS,BUSAN,False,True,NaN,NaN,BERTH CONGESTION,NaN,2024-10-05 14:00:00,UTC +09:00,NaT,NaN,NaN,NaN,NaN,2024-10-06 15:00:00,UTC +09:00,NaN,NaN,NaN,2774.0,198.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,23.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7,0.0,23.0,0.0,0.0,0.0,0.0,54.75,0.0,0.0,0.00,0.0,0.0,0.0,0.0,8.23,0.0,0.0,0.10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,13643.0,0.0,640.0,0.0,1535.0,0.0,0.0,0.0,2O,CHIEF ENGINEER,True,True,1.6,NaN,NaN,NaN,NaN,NaN,NaN,180.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8942.0,0,35742.0,NaN,NaN,NaN,63.4,NaN,NaN,2.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,1.510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,830.23,0.0,0.0,0.0,0.0,1841.04,0.0,0.0,0.0,0.0,NaN,23.0,NaN,23.0,0.0
30897,57d70294-bedc-46ab-8ee0-4c8e550b66a1,MSC DOUALA VIII,99836950,UX438A,2024-10-13,2024-10-13 12:00:00,UTC +11:00,NOON,AT SEA,2959N,17017E,57.29,57754.00,True,24.0,24.0,415.0,562.0,16.833333,17.291667,0.0,0.0,8.0,20.0,12.9,12.9,94310.0,91.0,0.08,47.92,2972.0,29.0,28.0,404.0,PAPTY,2024-10-27 21:00:00,UTC -05:00,PANAMA,NaN,24.0,295.0,331.0,17.9,6398.0,357.0,0.0,0.0,4.0,31.0,1355129.0,KRPUS,BUSAN,False,True,NaN,NaN,BERTH CONGESTION,NaN,2024-10-05 14:00:00,UTC +09:00,NaT,NaN,NaN,NaN,NaN,2024-10-06 15:00:00,UTC +09:00,NaN,NaN,NaN,2774.0,198.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.6,0.1,0.0,24.0,0.0,0.0,0.0,0.0,57.29,0.0,0.0,0.00,0.0,0.0,0.0,0.0,8.23,0.0,0.0,0.10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,13527.0,0.0,0.0,0.0,1554.0,0.0,0.0,0.0,2O,CHIEF ENGINEER,True,True,2.1,NaN,NaN,NaN,NaN,NaN,NaN,172.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8942.0,0,37287.0,No.1 & No.2 Generators Shut down trips tried out.,NaN,NaN,44.6,NaN,NaN,1.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,2.650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,830.13,0.0,0.0,0.0,0.0,1775.52,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0

In [253]:
df_sorted['VOY'] = df_sorted.groupby(['VSL', df_sorted['REPORT DATE TIME'].dt.date])['VOY'].transform(lambda x: x.ffill().bfill())

In [255]:
df_sorted

,GID,VSL,IMO No,VOY,Corrected Date,REPORT DATE TIME,REPORT DATE TIME Offset,Report Type,Status,LAT,LONG,M E FOC,CARGO TOTAL,Has Cargo,STEAMING TIME,Total M E Hours Fuel Only,MILES BY GPS,OIL CYL,SPEED BY LOG,SPEED BY GPS,RPM,SLIP,WIND DIRECTION,WIND SPEED,DRAFT AFT,DRAFT FWD,DISPLACEMENT,COURSE AT SEA,WAVE HEIGHT,SEA DIRECTION,CARGO TOTAL TEU,AMBIENT TEMP,SW TEMP,MILES BY SPEED LOG,ETA PORT CODE,ETA DATE TIME,ETA DATE TIME Offset,ETA PORT,TIME CHANGE,TIME SEA,TEMP MIN,TEMP MAX,REQUESTED SPEED,REM DIST TO PILOT,REM TIME TO PILOT,TOTAL UNPLND STPGE TECH,TOTAL UNPLND STPGE OPE WX,REEFERS POSITIVE PLUGGED,REEFERS NEGATIVE PLUGGED,ME TOTAL REVS COUNTER,PORT CODE,PORT,AUX BLOWERS ON,HOLD VENTILATION ON,TIME HRS ANCHOR,TIME HRS DRIFT,REASON,TYPE OF DELAY,ETB DATE TIME,ETB DATE TIME Offset,PILOT DATE TIME,PILOT DATE TIME Offset,TIME MANOEUVRING,TUG ARR,TUG SHIFT,ETD DATE TIME,ETD DATE TIME Offset,SHIFT BERTH HOURS,CARGO LOAD,CARGO DISCH,TEU FULL,TEU EMPTY,BILGE REMOVED,GARBAGE REMOVED,GARBAGE REMVL REQSTD,GARBAGE REMVL CMPLSRY,FW SUPPLY,CY CREW SIGNED ON,CY CREW SIGNED OFF,CY DOCTORS VISIT,CY MAIL RECEIVED Ref NO,CY LUB OIL SAMPLE LANDED,CY CHECKD FOR STOWAWAYS,CY STOWAWAYS ON BOARD,CY DEP GM Mtr,CY REQUISITIONS RECEIVED,DISTANCE TO NEXT PILOT,TUG SAILING TRANSIT,STEAMING TIME M E Rsdl VLS,STEAMING TIME M E Rsdl HS,STEAMING TIME M E Rsdl ULS,STEAMING TIME M E Dstlt VLS,STEAMING TIME M E Dstlt ULS,STEAMING TIME M E Tnktnr Dstlt VLS,STEAMING TIME M E MDO,STEAMING TIME AUX 1,STEAMING TIME AUX 2,STEAMING TIME AUX 3,STEAMING TIME AUX 4,STEAMING TIME AUX 5,STEAMING TIME SH GEN,STEAMING TIME TG,FUEL M E Rsdl VLS,FUEL M E Rsdl HS,FUEL M E Rsdl ULS,FUEL M E Dstlt VLS,FUEL M E Dstlt ULS,FUEL M E MDO,FUEL M E LNG,FUEL M E Tnktnr Dstlt VLS,FUEL Aux Rsdl VLS,FUEL Aux Rsdl HS,FUEL Aux Rsdl ULS,FUEL Aux Dstlt VLS,FUEL Aux Dstlt ULS,FUEL Aux Tnktnr Dstlt VLS,FUEL Aux LNG,FUEL Aux MDO,FUEL Boiler Rsdl VLS,FUEL Boiler Rsdl HS,FUEL Boiler Rsdl ULS,FUEL Boiler Dstlt VLS,FUEL Boiler Dstlt ULS,FUEL Boiler Tnktnr Dstlt VLS,FUEL Boiler LNG,FUEL Boiler MDO,POWER KW,STEAMING LOAD KW AUX 1,STEAMING LOAD KW AUX 2,STEAMING LOAD KW AUX 3,STEAMING LOAD KW AUX 4,STEAMING LOAD KW AUX 5,STEAMING LOAD KW SH GEN,STEAMING LOAD KW TG,DECK LAST CHANGE USER,ENGINE LAST CHANGE USER,DECK PART IS COMPLETE,ENGINE PART IS COMPLETE,SCAVENGE PRESSURE,SECA ENTRY TIME,SECA ENTRY LAT,SECA ENTRY LONG,SECA EXIT TIME,SECA EXIT LAT,SECA EXIT LONG,ROB FRESH WATER,MANVRNG MILES BY GPS,MANVRNG MILES BY SPEED LOG,TANKTAINER TRANSFD QUANTITY,PILOT TAKEN,DATE TIME START TRANSIT,DATE TIME START TRANSIT Offset,DATE TIME END TRANSIT,DATE TIME END TRANSIT Offset,BALLAST,TANKTAINER NUMBER,STEAMING KWHR TOTAL,CY OTHERS,ROB FO SLUDGE,ROB LO SLUDGE,ROB BILGE,SLUDGE REMOVED FO,SLUDGE REMOVED LO,SEA STATE,CY LUB ADDED TO SYSTEM MECC,CY LUB ADDED TO SYSTEM AECC,CY LUB ADDED TO THRUSTERS,CY ME LO PURIFIER IN USE,CY BALLAST,CY BENDING MOMENT,CY SHEARING FORCE,CY TORTION MOMENT,CY SUPDT AUDITOR SIGNED ON,CY SUPDT AUDITOR SIGNED OFF,CY CASH RECEIVED,CY LUB OIL RECEIVED MECYL,CY LUB OIL RECEIVED MECC,CY LUB OIL RECEIVED AECC,CY M E UNDER PISTON TEMP,CY MAIL RECEIVED,WIND DIRECTION PORT STBD,SEA DIRECTION PORT STBD,TIME PILOT ONBOARD,GRADES ROB,SO2 CO2 RATIO,Bunker Order,Remarks,BDN Number,Fuel Type,Carbon Factor,Sulphur Content PC,Quantity,Port Delivery,Product Quality,Tanktainer Number_1,Supplier,Delivery,Vol Lt,Den,Vis,ROB Dstlt ULS,ROB Dstlt VLS,ROB Rsdl MDO,ROB Tnktnr Dstlt VLS,ROB Rsdl VLS,ROB Rsdl HS,ROB Rsdl ULS,ROB Rsdl LNG,ECA MILES,ECA TIME,EGCS DRY WASTE REMOVED,EGCS RUNNING TIME,EGCS WET SLURRY REMOVED,EGCS OPEN LOOP RUNNING TIME,EGCS CLOSED LOOP RUNNING TIME
4438,917ebf03-3390-454f-89aa-dccf9db97a7c,MSC AURELIA,76021200,407,2024-10-01,2024-10-01 06:12:00,UTC +02:00,EOSP,AT SEA,4329N,01625E,10.80,276.53,True,10.4,10.4,134.0,0.0,11.346154,12.884615,185.0,1.0,20.0,20.0,5.9,5.0,12180.0,41.0,0.46,49.18,NaN,24.0,22.0,118.0,HRSPU,2024-10-01 07:00:00,UTC +02:00,NaN,NaN,10.4,304.0,344.0,12.6,NaN,NaN,0.0,0.0,0.0,1.0,0.0,HRSPU,SPLIT,False,False,NaN,NaN,No prospects,NaN,2024-10-01 07:00:00,UTC +02:00,NaT,NaN,NaN,NaN,NaN,2024-09-30 19:30:00,UTC +02:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,10.4,0.0,0.0,10.4,0.0,10.4,10.4,0.0,0.0,0.0,0.0,0.00,0.0,0.0,10.80,0.0,0.0,0.0,0.0,0.00,0.0,0.0,2.45,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,5900.0,370.0,0.0,370.0,370.0,0.0,0.0,0.0,MASTER,CE,True,True,0.9,NaN,NaN,NaN,NaN,NaN,NaN,310.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,534.0,NaN,0.0,NaN,NaN,NaN,25.8,NaN,NaN,2.0,0.0,0.0,0.0,Both,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,299.34,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
4445,2b94394f-9e20-45d4-8dcb-78aad2db8913,MSC AURELIA,76021200,407,2024-10-01,2024-10-01 06:48:00,UTC +02:00,BRTH,DRIFTING,4329N,01625E,0.31,276.53,True,0.6,0.6,1.4,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,5.9,5.0,12180.0,0.0,0.00,0.00,NaN,24.0,22.0,NaN,HRSPU,2024-10-01 07:00:00,UTC +02:00,NaN,NaN,0.6,304.0,337.0,12.6,NaN,NaN,0.0,0.0,0.0,1.0,0.0,HRSPU,SPLIT,False,False,NaN,NaN,No prospects,NaN,2024-10-01 07:00:00,UTC +02:00,2024-10-01 06:18:00,UTC +02:00,0.7,0.0,0.0,2024-10-01 19:30:00,UTC +02:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.6,0.0,0.0,0.6,0.0,0.6,0.6,0.6,0.0,0.0,0.0,0.00,0.0,0.0,0.31,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,3000.0,350.0,0.0,350.0,350.0,240.0,0.0,0.0,MASTER,CE,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,309.0,1.4,1.4,NaN,False,NaT,NaN,NaT,NaN,534.0,NaN,0.0,NaN,NaN,NaN,25.8,NaN,NaN,0.0,0.0,0.0,0.0,Both,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,298.86,0.0,0.0,0.0,0.0,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4446,97f87d01-9113-47e8-ab85-6a67d077928d,MSC AURELIA,76021200,407,2024-10-01,2024-10-01 12:00:00,UTC +02:00,PORT,IN PORT,4329N,01625E,0.00,276.53,True,5.2,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,5.9,5.0,12180.0,0.0,0.00,0.00,NaN,24.0,22.0,NaN,HRSPU,2024-10-01 07:00:00,UTC +02:00,NaN,NaN,5.2,70.0,70.0,12.6,NaN,NaN,0.0,0.0,0.0,1.0,0.0,HRSPU,SPLIT,False,False,NaN,NaN,No prospects,NaN,2024-10-01 07:00:00,UTC +02:00,NaT,NaN,NaN,NaN,NaN,2024-10-01 19:30:00,UTC +02:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.2,0.0,5.2,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.92,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.03,0.0,0.0,0.0,0.0,400.0,0.0,400.0,0.0,0.0,0.0,0.0,MASTER,CE,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,300.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,534.0,NaN,0.0,NaN,NaN,NaN,25.8,NaN,NaN,0.0,0.0,0.0,0.0,Both,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,297.91,0.0,0.0,0.0,0.0,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4453,037d12cb-b788-4b87-8d0f-2a5e85d58a09,MSC AURELIA,76021200,407,2024-10-02,2024-10-01 19:30:00,UTC +02:00,SAIL,IN PORT,4329N,01625E,0.00,278.03,True,7.5,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,5.9,5.0,12180.0,0.0,0.00,0.00,NaN,24.0,22.0,NaN,ITAOI,2024-10-02 07:00:00,UTC +02:00,ANCONA,NaN,7.5,70.0,70.0,12.6,NaN,NaN,0.0,0.0,0.0,1.0,0.0,HRSPU,SPLIT,False,False,NaN,NaN,No prospects,NaN,2024-10-01 07:00:00,UTC +02:00,NaT,NaN,NaN,NaN,0.0,2024-10-01 19:30:00,UTC +02:00,NaN,278.03,276.53,NaN,NaN,0,NaN,False,False,0.0,0,0,No,0,0,0,0,3.4,0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.5,0.0,7.5,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,1.33,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.04,0.0,0.0,0.0,0.0,400.0,0.0,400.0,0.0,0.0,0.0,0.0,MASTER,CE,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,291.0,NaN,NaN,0.0,False,NaT,NaN,NaT,NaN,534.0,NaN,0.0,NaN,NaN,NaN,25.8,NaN,NaN,0.0,0.0,0.0,0.0,Both,NaN,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,NaN,False,NaN,NaN,NaN,NaN,0.001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,296.54,0.0,0.0,0.0,0.0,0.00,0.0,0.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN
4454,d93905d9-60aa-4acb-b662-995ff2847bb3,MSC AURELIA,76021200,407,2024-10-02,2024-10-01 19:48:00,UTC +02:00,COSP,DRIFTING,4329N,01625E,0.16,278.03,True,0.3,0.3,1.2,0.0,0.000000,0.000000,0.0,0.0,150.0,7.0,5.9,5.0,12180.0,215.0,0.28,150.00,NaN,24.0,22.0,NaN,ITAOI,2024-10-02 07:00:00,UTC +02:00,ANCONA,NaN,0.3,301.0,339.0,11.5,NaN,NaN,0.0,0.0,0.0,1.0,0.0,HRSPU,SPLIT,False,False,NaN,NaN,No prospects,NaN,2024-10-01 07:00:00,UTC +02:00,NaT,NaN,0.3,NaN,NaN,2024-10-01 19:30:00,UTC +02:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,135.0,0,0.0,0.0,0.0,0.0,0.3,0.0,0.0,0.3,0.0,0.3,0.3,0.3,0.0,0.0,0.0,0.00,0.0,0.0,0.16,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,3000.0,400.0,0.0,400.0,400.0,220.0,0.0,0.0,MASTER,CE,True,True,0.8,NaN,NaN,NaN,NaN,NaN,NaN,290.0,1.2,1.2,NaN,True,NaT,NaN,NaT,NaN,534.0,NaN,0.0,NaN,NaN,NaN,25.8,NaN,NaN,2.0,0.0,0.0,0.0,Both,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,0.4,NaN,0.001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,296.29,0.0,0.0,0.0,0.0,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30893,c874c857-3495-4f68-9dd3-d7e90604b759,MSC DOUALA VIII,99836950,UX438A,2024-10-09,2024-10-09 12:00:00,UTC +09:00,NOON,AT SEA,3000N,14220E,14.86,57754.00,True,24.0,24.0,262.0,214.0,10.250000,10.916667,37.5,3.0,20.0,12.0,12.9,12.9,94570.0,90.0,0.10,84.99,2972.0,29.0,28.0,246.0,PAPTY,2024-10-26 21:00:00,UTC -05:00,PANAMA,NaN,24.0,236.0,255.0,18.2,7856.0,427.0,0.0,0.0,4.0,31.0,1052186.0,KRPUS,BUSAN,True,True,NaN,NaN,BERTH CONGESTION,NaN,2024-10-05 14:00:00,UTC +09:00,NaT,NaN,NaN,NaN,NaN,2024-10-06 15:00:00,UTC +09:00,NaN,NaN,NaN,2774.0,198.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,14.86,0.0,0.0,0.00,0.0,0.0,0.0,0.0,8.96,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.19,0.0,0.0,0.0,3287.0,0.0,0.0,0.0,1630.0,0.0,0.0,0.0,2O,CHIEF ENGINEER,True,True,0.2,NaN,NaN,NaN,NaN,NaN,NaN,200.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8942.0,0,39115.0,"Vessel Reduced Speed to 11 kts to avoid TRS, a...",NaN,NaN,38.8,NaN,NaN,1.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,830.83,0.0,0.0,0.0,0.0,1995.90,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
30894,450e0a93-096b-4348-876f-612a526b9030,MSC DOUALA VIII,99836950,UX438A,2024-10-10,2024-10-10 12:00:00,UTC +10:00,NOON,AT SEA,3000N,14609E,15.53,57754.00,True,17.1,17.1,203.0,195.0,11.988304,11.871345,43.0,8.1,70.0,17.0,12.9,12.9,94500.0,90.0,1.65,110.77,2972.0,29.0,28.0,205.0,PAPTY,2024-10-26 21:00:00,UTC -05:00,PANAMA,NaN,23.0,302.0,319.0,19.0,7657.0,405.0,0.0,5.9,4.0,31.0,1096305.0,KRPUS,BUSAN,False,True,NaN,NaN,BERTH CONGESTION,NaN,2024-10-05 14:00:00,UTC +09:00,NaT,NaN,NaN,NaN,NaN,2024-10-06 15:00:00,UTC +09:00,NaN,NaN,NaN,2774.0,198.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,17.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.0,0.0,0.0,0.0,0.0,15.53,0.0,0.0,0.00,0.0,0.0,0.0,0.0,8.72,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.50,0.0,0.0,0.0,5106.0,0.0,0.0,0.0,1671.0,0.0,0.0,0.0,2O,CHIEF ENGINEER,True,True,1.7,NaN,NaN,NaN,NaN,NaN,NaN,195.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8942.0,0,38433.0,Vessel drifting to adjust Bad weather passing.,NaN,NaN,38.8,NaN,NaN,4.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,1.820,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,830.33,0.0,0.0,0.0,0.0,1971.65,0.0,0.0,0.0,0.0,NaN,23.0,NaN,23.0,0.0
30895,80ce03b1-385d-4e36-8f23-12f20f0da110,MSC DOUALA VIII,99836950,UX438A,2024-10-11,2024-10-11 12:00:00,UTC +10:00,NOON,AT SEA,3000N,15427E,59.01,57754.00,True,24.0,24.0,432.0,601.0,17.791667,18.000000,61.9,3.2,20.0,22.0,12.9,12.9,94430.0,91.0,0.36,70.44,2972.0,29.0,28.0,427.0,PAPTY,2024-10-27 21:00:00,UTC -05:00,PANAMA,NaN,24.0,302.0,336.0,18.0,7225.0,401.0,0.0,0.0,4.0,31.0,1185403.0,KRPUS,BUSAN,False,True,NaN,NaN,BERTH CONGESTION,NaN,2024-10-05 14:00:00,UTC +09:00,NaT,NaN,NaN,NaN,NaN,2024-10-06 15:00:00,UTC +09:00,NaN,NaN,NaN,2774.0,198.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,59.01,0.0,0.0,0.00,0.0,0.0,0.0,0.0,8.62,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,14207.0,0.0,0.0,0.0,1562.0,0.0,0.0,0.0,2O,CHIEF ENGINEER,True,True,1.8,NaN,NaN,NaN,NaN,NaN,NaN,185.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8942.0,0,37482.0,NaN,NaN,NaN,52.9,NaN,NaN,2.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,2.060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.0,1904.02,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
30896,91101114-2203-428a-a96b-93984bd454f2,MSC DOUALA VIII,99836950,UX438A,2024-10-12,2024-10-12 12:00:00,UTC +11:00,NOON,AT SEA,3000N,16219E,54.75,57754.00,True,23.0,23.0,410.0,541.0,17.304348,17.826087,0.0,0.0,10.0,25.0,12.9,12.9,94370.0,92.0,0.37,32.58,2972.0,29.0,28.0,398.0,PAPTY,2024-10-27 21:00:00,UTC -05:00,PANAMA,NaN,23.0,295.0,331.0,18.0,6815.0,377.0,0.0,0.0,4.0,31.0,1268904.0,KRPUS,BUSAN,False,True,NaN,NaN,BERTH CONGESTION,NaN,2024-10-05 14:00:00,UTC +09:00,NaT,NaN,NaN,NaN,NaN,2024-10-06 15:00:00,UTC +09:00,NaN,NaN,NaN,2774.0,198.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,23.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7,0.0,23.0,0.0,0.0,0.0,0.0,54.75,0.0,0.0,0.00,0.0,0.0,0.0,0.0,8.23,0.0,0.0,0.10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,13643.0,0.0,640.0,0.0,1535.0,0.0,0.0,0.0,2O,CHIEF ENGINEER,True,True,1.6,NaN,NaN,NaN,NaN,NaN,NaN,180.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8942.0,0,35742.0,NaN,NaN,NaN,63.4,NaN,NaN,2.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,1.510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,830.23,0.0,0.0,0.0,0.0,1841.04,0.0,0.0,0.0,0.0,NaN,23.0,NaN,23.0,0.0
30897,57d70294-bedc-46ab-8ee0-4c8e550b66a1,MSC DOUALA VIII,99836950,UX438A,2024-10-13,2024-10-13 12:00:00,UTC +11:00,NOON,AT SEA,2959N,17017E,57.29,57754.00,True,24.0,24.0,415.0,562.0,16.833333,17.291667,0.0,0.0,8.0,20.0,12.9,12.9,94310.0,91.0,0.08,47.92,2972.0,29.0,28.0,404.0,PAPTY,2024-10-27 21:00:00,UTC -05:00,PANAMA,NaN,24.0,295.0,331.0,17.9,6398.0,357.0,0.0,0.0,4.0,31.0,1355129.0,KRPUS,BUSAN,False,True,NaN,NaN,BERTH CONGESTION,NaN,2024-10-05 14:00:00,UTC +09:00,NaT,NaN,NaN,NaN,NaN,2024-10-06 15:00:00,UTC +09:00,NaN,NaN,NaN,2774.0,198.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.6,0.1,0.0,24.0,0.0,0.0,0.0,0.0,57.29,0.0,0.0,0.00,0.0,0.0,0.0,0.0,8.23,0.0,0.0,0.10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,13527.0,0.0,0.0,0.0,1554.0,0.0,0.0,0.0,2O,CHIEF ENGINEER,True,True,2.1,NaN,NaN,NaN,NaN,NaN,NaN,172.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8942.0,0,37287.0,No.1 & No.2 Generators Shut down trips tried out.,NaN,NaN,44.6,NaN,NaN,1.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,2.650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,830.13,0.0,0.0,0.0,0.0,1775.52,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0

In [256]:
df_sorted['IMO No'].isnull().sum()

0

In [257]:
import pandas as pd

# Load vessel details (charter_data) from Excel
charter_data = pd.read_excel(r'C:\Users\akshaya\Downloads\charter.xlsx')

# Assuming df_sorted is your charter data, already loaded
# Clean vessel names by stripping whitespace, converting to uppercase, and removing non-alphanumeric characters for comparison
charter_data['Name'] = charter_data['Name'].str.strip().str.upper().str.replace(r'[^A-Z0-9 ]', '', regex=True)
df_sorted['VSL'] = df_sorted['VSL'].str.strip().str.upper().str.replace(r'[^A-Z0-9 ]', '', regex=True)

# Clean IMO columns by converting them to strings (in case they are numbers)
charter_data['IMO'] = charter_data['IMO'].astype(str).str.strip()
df_sorted['IMO No'] = df_sorted['IMO No'].astype(str).str.strip()

# Step 1: Check if the IMO numbers match at all
print("Number of unique IMO No in charter data:", df_sorted['IMO No'].nunique())
print("Number of unique IMO in vessel data:", charter_data['IMO'].nunique())

# Step 2: Ensure there is overlap between the two IMO columns
common_imos = set(df_sorted['IMO No']).intersection(set(charter_data['IMO']))
print(f"Number of matching IMO numbers: {len(common_imos)}")

if len(common_imos) == 0:
    print("No matching IMO numbers found between the two datasets.")
else:
    print("Matching IMO numbers exist, proceeding with further checks.")

# Step 3: Merge the two datasets on the IMO columns
merged_data = pd.merge(df_sorted, charter_data, how='left', left_on='IMO No', right_on='IMO')

# Step 4: Identify rows where names don't match
merged_data['Name_Match'] = merged_data['VSL'] == merged_data['Name']

# Filter for incorrect matches (where IMO matches but names don't)
incorrect_data = merged_data[(merged_data['Name_Match'] == False) & merged_data['IMO'].notna()]

# Save the incorrect matches if needed
incorrect_data.to_csv('incorrect_data.csv', index=False)

# Print incorrect matches
print("Incorrect name matches:")
print(incorrect_data[['IMO No', 'VSL', 'Name']])

# Step 5: Diagnose unmatched data
# Print IMOs in charter data that don't have a match in vessel data
unmatched_imos = df_sorted[~df_sorted['IMO No'].isin(charter_data['IMO'])]
print("IMOs in charter data not found in vessel data:")
print(unmatched_imos[['IMO No', 'VSL']].head(10))

# Print IMOs in vessel data that don't have a match in charter data
unmatched_vessels = charter_data[~charter_data['IMO'].isin(df_sorted['IMO No'])]
print("IMOs in vessel data not found in charter data:")
print(unmatched_vessels[['IMO', 'Name']].head(10))

Number of unique IMO No in charter data: 842
Number of unique IMO in vessel data: 125
Number of matching IMO numbers: 0
No matching IMO numbers found between the two datasets.
Incorrect name matches:
Empty DataFrame
Columns: [IMO No, VSL, Name]
Index: []
IMOs in charter data not found in vessel data:
        IMO No          VSL
4438  76021200  MSC AURELIA
4445  76021200  MSC AURELIA
4446  76021200  MSC AURELIA
4453  76021200  MSC AURELIA
4454  76021200  MSC AURELIA
4455  76021200  MSC AURELIA
4462  76021200  MSC AURELIA
4463  76021200  MSC AURELIA
4470  76021200  MSC AURELIA
4471  76021200  MSC AURELIA
IMOs in vessel data not found in charter data:
         IMO           Name
0  9147215.0  MED CERKEZKOY
1  9461441.0       MSC BARI
2  9461427.0    MSC LIVORNO
3  9461386.0     MSC GENOVA
4  9461403.0  MSC LA SPEZIA
5  9460356.0     MSC SAVONA
6  9475258.0    MSC TARANTO
7  9484431.0    MSC RAVENNA
8  9484455.0    MSC RAPALLO
9  9484479.0    MSC TRIESTE

In [262]:
df_sorted.to_excel(r'D:\Navalt\MSC\2024\Weekly Data\CHARTER\CLIENT\CORRECTED\OCT_2024.xlsx')

In [263]:
df_sorted

,GID,VSL,IMO No,VOY,Corrected Date,REPORT DATE TIME,REPORT DATE TIME Offset,Report Type,Status,LAT,LONG,M E FOC,CARGO TOTAL,Has Cargo,STEAMING TIME,Total M E Hours Fuel Only,MILES BY GPS,OIL CYL,SPEED BY LOG,SPEED BY GPS,RPM,SLIP,WIND DIRECTION,WIND SPEED,DRAFT AFT,DRAFT FWD,DISPLACEMENT,COURSE AT SEA,WAVE HEIGHT,SEA DIRECTION,CARGO TOTAL TEU,AMBIENT TEMP,SW TEMP,MILES BY SPEED LOG,ETA PORT CODE,ETA DATE TIME,ETA DATE TIME Offset,ETA PORT,TIME CHANGE,TIME SEA,TEMP MIN,TEMP MAX,REQUESTED SPEED,REM DIST TO PILOT,REM TIME TO PILOT,TOTAL UNPLND STPGE TECH,TOTAL UNPLND STPGE OPE WX,REEFERS POSITIVE PLUGGED,REEFERS NEGATIVE PLUGGED,ME TOTAL REVS COUNTER,PORT CODE,PORT,AUX BLOWERS ON,HOLD VENTILATION ON,TIME HRS ANCHOR,TIME HRS DRIFT,REASON,TYPE OF DELAY,ETB DATE TIME,ETB DATE TIME Offset,PILOT DATE TIME,PILOT DATE TIME Offset,TIME MANOEUVRING,TUG ARR,TUG SHIFT,ETD DATE TIME,ETD DATE TIME Offset,SHIFT BERTH HOURS,CARGO LOAD,CARGO DISCH,TEU FULL,TEU EMPTY,BILGE REMOVED,GARBAGE REMOVED,GARBAGE REMVL REQSTD,GARBAGE REMVL CMPLSRY,FW SUPPLY,CY CREW SIGNED ON,CY CREW SIGNED OFF,CY DOCTORS VISIT,CY MAIL RECEIVED Ref NO,CY LUB OIL SAMPLE LANDED,CY CHECKD FOR STOWAWAYS,CY STOWAWAYS ON BOARD,CY DEP GM Mtr,CY REQUISITIONS RECEIVED,DISTANCE TO NEXT PILOT,TUG SAILING TRANSIT,STEAMING TIME M E Rsdl VLS,STEAMING TIME M E Rsdl HS,STEAMING TIME M E Rsdl ULS,STEAMING TIME M E Dstlt VLS,STEAMING TIME M E Dstlt ULS,STEAMING TIME M E Tnktnr Dstlt VLS,STEAMING TIME M E MDO,STEAMING TIME AUX 1,STEAMING TIME AUX 2,STEAMING TIME AUX 3,STEAMING TIME AUX 4,STEAMING TIME AUX 5,STEAMING TIME SH GEN,STEAMING TIME TG,FUEL M E Rsdl VLS,FUEL M E Rsdl HS,FUEL M E Rsdl ULS,FUEL M E Dstlt VLS,FUEL M E Dstlt ULS,FUEL M E MDO,FUEL M E LNG,FUEL M E Tnktnr Dstlt VLS,FUEL Aux Rsdl VLS,FUEL Aux Rsdl HS,FUEL Aux Rsdl ULS,FUEL Aux Dstlt VLS,FUEL Aux Dstlt ULS,FUEL Aux Tnktnr Dstlt VLS,FUEL Aux LNG,FUEL Aux MDO,FUEL Boiler Rsdl VLS,FUEL Boiler Rsdl HS,FUEL Boiler Rsdl ULS,FUEL Boiler Dstlt VLS,FUEL Boiler Dstlt ULS,FUEL Boiler Tnktnr Dstlt VLS,FUEL Boiler LNG,FUEL Boiler MDO,POWER KW,STEAMING LOAD KW AUX 1,STEAMING LOAD KW AUX 2,STEAMING LOAD KW AUX 3,STEAMING LOAD KW AUX 4,STEAMING LOAD KW AUX 5,STEAMING LOAD KW SH GEN,STEAMING LOAD KW TG,DECK LAST CHANGE USER,ENGINE LAST CHANGE USER,DECK PART IS COMPLETE,ENGINE PART IS COMPLETE,SCAVENGE PRESSURE,SECA ENTRY TIME,SECA ENTRY LAT,SECA ENTRY LONG,SECA EXIT TIME,SECA EXIT LAT,SECA EXIT LONG,ROB FRESH WATER,MANVRNG MILES BY GPS,MANVRNG MILES BY SPEED LOG,TANKTAINER TRANSFD QUANTITY,PILOT TAKEN,DATE TIME START TRANSIT,DATE TIME START TRANSIT Offset,DATE TIME END TRANSIT,DATE TIME END TRANSIT Offset,BALLAST,TANKTAINER NUMBER,STEAMING KWHR TOTAL,CY OTHERS,ROB FO SLUDGE,ROB LO SLUDGE,ROB BILGE,SLUDGE REMOVED FO,SLUDGE REMOVED LO,SEA STATE,CY LUB ADDED TO SYSTEM MECC,CY LUB ADDED TO SYSTEM AECC,CY LUB ADDED TO THRUSTERS,CY ME LO PURIFIER IN USE,CY BALLAST,CY BENDING MOMENT,CY SHEARING FORCE,CY TORTION MOMENT,CY SUPDT AUDITOR SIGNED ON,CY SUPDT AUDITOR SIGNED OFF,CY CASH RECEIVED,CY LUB OIL RECEIVED MECYL,CY LUB OIL RECEIVED MECC,CY LUB OIL RECEIVED AECC,CY M E UNDER PISTON TEMP,CY MAIL RECEIVED,WIND DIRECTION PORT STBD,SEA DIRECTION PORT STBD,TIME PILOT ONBOARD,GRADES ROB,SO2 CO2 RATIO,Bunker Order,Remarks,BDN Number,Fuel Type,Carbon Factor,Sulphur Content PC,Quantity,Port Delivery,Product Quality,Tanktainer Number_1,Supplier,Delivery,Vol Lt,Den,Vis,ROB Dstlt ULS,ROB Dstlt VLS,ROB Rsdl MDO,ROB Tnktnr Dstlt VLS,ROB Rsdl VLS,ROB Rsdl HS,ROB Rsdl ULS,ROB Rsdl LNG,ECA MILES,ECA TIME,EGCS DRY WASTE REMOVED,EGCS RUNNING TIME,EGCS WET SLURRY REMOVED,EGCS OPEN LOOP RUNNING TIME,EGCS CLOSED LOOP RUNNING TIME
4438,917ebf03-3390-454f-89aa-dccf9db97a7c,MSC AURELIA,76021200,407,2024-10-01,2024-10-01 06:12:00,UTC +02:00,EOSP,AT SEA,4329N,01625E,10.80,276.53,True,10.4,10.4,134.0,0.0,11.346154,12.884615,185.0,1.0,20.0,20.0,5.9,5.0,12180.0,41.0,0.46,49.18,NaN,24.0,22.0,118.0,HRSPU,2024-10-01 07:00:00,UTC +02:00,NaN,NaN,10.4,304.0,344.0,12.6,NaN,NaN,0.0,0.0,0.0,1.0,0.0,HRSPU,SPLIT,False,False,NaN,NaN,No prospects,NaN,2024-10-01 07:00:00,UTC +02:00,NaT,NaN,NaN,NaN,NaN,2024-09-30 19:30:00,UTC +02:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,10.4,0.0,0.0,10.4,0.0,10.4,10.4,0.0,0.0,0.0,0.0,0.00,0.0,0.0,10.80,0.0,0.0,0.0,0.0,0.00,0.0,0.0,2.45,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,5900.0,370.0,0.0,370.0,370.0,0.0,0.0,0.0,MASTER,CE,True,True,0.9,NaN,NaN,NaN,NaN,NaN,NaN,310.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,534.0,NaN,0.0,NaN,NaN,NaN,25.8,NaN,NaN,2.0,0.0,0.0,0.0,Both,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,299.34,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
4445,2b94394f-9e20-45d4-8dcb-78aad2db8913,MSC AURELIA,76021200,407,2024-10-01,2024-10-01 06:48:00,UTC +02:00,BRTH,DRIFTING,4329N,01625E,0.31,276.53,True,0.6,0.6,1.4,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,5.9,5.0,12180.0,0.0,0.00,0.00,NaN,24.0,22.0,NaN,HRSPU,2024-10-01 07:00:00,UTC +02:00,NaN,NaN,0.6,304.0,337.0,12.6,NaN,NaN,0.0,0.0,0.0,1.0,0.0,HRSPU,SPLIT,False,False,NaN,NaN,No prospects,NaN,2024-10-01 07:00:00,UTC +02:00,2024-10-01 06:18:00,UTC +02:00,0.7,0.0,0.0,2024-10-01 19:30:00,UTC +02:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.6,0.0,0.0,0.6,0.0,0.6,0.6,0.6,0.0,0.0,0.0,0.00,0.0,0.0,0.31,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,3000.0,350.0,0.0,350.0,350.0,240.0,0.0,0.0,MASTER,CE,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,309.0,1.4,1.4,NaN,False,NaT,NaN,NaT,NaN,534.0,NaN,0.0,NaN,NaN,NaN,25.8,NaN,NaN,0.0,0.0,0.0,0.0,Both,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,298.86,0.0,0.0,0.0,0.0,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4446,97f87d01-9113-47e8-ab85-6a67d077928d,MSC AURELIA,76021200,407,2024-10-01,2024-10-01 12:00:00,UTC +02:00,PORT,IN PORT,4329N,01625E,0.00,276.53,True,5.2,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,5.9,5.0,12180.0,0.0,0.00,0.00,NaN,24.0,22.0,NaN,HRSPU,2024-10-01 07:00:00,UTC +02:00,NaN,NaN,5.2,70.0,70.0,12.6,NaN,NaN,0.0,0.0,0.0,1.0,0.0,HRSPU,SPLIT,False,False,NaN,NaN,No prospects,NaN,2024-10-01 07:00:00,UTC +02:00,NaT,NaN,NaN,NaN,NaN,2024-10-01 19:30:00,UTC +02:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.2,0.0,5.2,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.92,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.03,0.0,0.0,0.0,0.0,400.0,0.0,400.0,0.0,0.0,0.0,0.0,MASTER,CE,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,300.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,534.0,NaN,0.0,NaN,NaN,NaN,25.8,NaN,NaN,0.0,0.0,0.0,0.0,Both,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,297.91,0.0,0.0,0.0,0.0,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4453,037d12cb-b788-4b87-8d0f-2a5e85d58a09,MSC AURELIA,76021200,407,2024-10-02,2024-10-01 19:30:00,UTC +02:00,SAIL,IN PORT,4329N,01625E,0.00,278.03,True,7.5,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,5.9,5.0,12180.0,0.0,0.00,0.00,NaN,24.0,22.0,NaN,ITAOI,2024-10-02 07:00:00,UTC +02:00,ANCONA,NaN,7.5,70.0,70.0,12.6,NaN,NaN,0.0,0.0,0.0,1.0,0.0,HRSPU,SPLIT,False,False,NaN,NaN,No prospects,NaN,2024-10-01 07:00:00,UTC +02:00,NaT,NaN,NaN,NaN,0.0,2024-10-01 19:30:00,UTC +02:00,NaN,278.03,276.53,NaN,NaN,0,NaN,False,False,0.0,0,0,No,0,0,0,0,3.4,0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.5,0.0,7.5,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,1.33,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.04,0.0,0.0,0.0,0.0,400.0,0.0,400.0,0.0,0.0,0.0,0.0,MASTER,CE,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,291.0,NaN,NaN,0.0,False,NaT,NaN,NaT,NaN,534.0,NaN,0.0,NaN,NaN,NaN,25.8,NaN,NaN,0.0,0.0,0.0,0.0,Both,NaN,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,NaN,False,NaN,NaN,NaN,NaN,0.001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,296.54,0.0,0.0,0.0,0.0,0.00,0.0,0.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN
4454,d93905d9-60aa-4acb-b662-995ff2847bb3,MSC AURELIA,76021200,407,2024-10-02,2024-10-01 19:48:00,UTC +02:00,COSP,DRIFTING,4329N,01625E,0.16,278.03,True,0.3,0.3,1.2,0.0,0.000000,0.000000,0.0,0.0,150.0,7.0,5.9,5.0,12180.0,215.0,0.28,150.00,NaN,24.0,22.0,NaN,ITAOI,2024-10-02 07:00:00,UTC +02:00,ANCONA,NaN,0.3,301.0,339.0,11.5,NaN,NaN,0.0,0.0,0.0,1.0,0.0,HRSPU,SPLIT,False,False,NaN,NaN,No prospects,NaN,2024-10-01 07:00:00,UTC +02:00,NaT,NaN,0.3,NaN,NaN,2024-10-01 19:30:00,UTC +02:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,135.0,0,0.0,0.0,0.0,0.0,0.3,0.0,0.0,0.3,0.0,0.3,0.3,0.3,0.0,0.0,0.0,0.00,0.0,0.0,0.16,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,3000.0,400.0,0.0,400.0,400.0,220.0,0.0,0.0,MASTER,CE,True,True,0.8,NaN,NaN,NaN,NaN,NaN,NaN,290.0,1.2,1.2,NaN,True,NaT,NaN,NaT,NaN,534.0,NaN,0.0,NaN,NaN,NaN,25.8,NaN,NaN,2.0,0.0,0.0,0.0,Both,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,0.4,NaN,0.001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,296.29,0.0,0.0,0.0,0.0,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30893,c874c857-3495-4f68-9dd3-d7e90604b759,MSC DOUALA VIII,99836950,UX438A,2024-10-09,2024-10-09 12:00:00,UTC +09:00,NOON,AT SEA,3000N,14220E,14.86,57754.00,True,24.0,24.0,262.0,214.0,10.250000,10.916667,37.5,3.0,20.0,12.0,12.9,12.9,94570.0,90.0,0.10,84.99,2972.0,29.0,28.0,246.0,PAPTY,2024-10-26 21:00:00,UTC -05:00,PANAMA,NaN,24.0,236.0,255.0,18.2,7856.0,427.0,0.0,0.0,4.0,31.0,1052186.0,KRPUS,BUSAN,True,True,NaN,NaN,BERTH CONGESTION,NaN,2024-10-05 14:00:00,UTC +09:00,NaT,NaN,NaN,NaN,NaN,2024-10-06 15:00:00,UTC +09:00,NaN,NaN,NaN,2774.0,198.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,14.86,0.0,0.0,0.00,0.0,0.0,0.0,0.0,8.96,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.19,0.0,0.0,0.0,3287.0,0.0,0.0,0.0,1630.0,0.0,0.0,0.0,2O,CHIEF ENGINEER,True,True,0.2,NaN,NaN,NaN,NaN,NaN,NaN,200.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8942.0,0,39115.0,"Vessel Reduced Speed to 11 kts to avoid TRS, a...",NaN,NaN,38.8,NaN,NaN,1.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,830.83,0.0,0.0,0.0,0.0,1995.90,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
30894,450e0a93-096b-4348-876f-612a526b9030,MSC DOUALA VIII,99836950,UX438A,2024-10-10,2024-10-10 12:00:00,UTC +10:00,NOON,AT SEA,3000N,14609E,15.53,57754.00,True,17.1,17.1,203.0,195.0,11.988304,11.871345,43.0,8.1,70.0,17.0,12.9,12.9,94500.0,90.0,1.65,110.77,2972.0,29.0,28.0,205.0,PAPTY,2024-10-26 21:00:00,UTC -05:00,PANAMA,NaN,23.0,302.0,319.0,19.0,7657.0,405.0,0.0,5.9,4.0,31.0,1096305.0,KRPUS,BUSAN,False,True,NaN,NaN,BERTH CONGESTION,NaN,2024-10-05 14:00:00,UTC +09:00,NaT,NaN,NaN,NaN,NaN,2024-10-06 15:00:00,UTC +09:00,NaN,NaN,NaN,2774.0,198.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,17.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.0,0.0,0.0,0.0,0.0,15.53,0.0,0.0,0.00,0.0,0.0,0.0,0.0,8.72,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.50,0.0,0.0,0.0,5106.0,0.0,0.0,0.0,1671.0,0.0,0.0,0.0,2O,CHIEF ENGINEER,True,True,1.7,NaN,NaN,NaN,NaN,NaN,NaN,195.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8942.0,0,38433.0,Vessel drifting to adjust Bad weather passing.,NaN,NaN,38.8,NaN,NaN,4.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,1.820,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,830.33,0.0,0.0,0.0,0.0,1971.65,0.0,0.0,0.0,0.0,NaN,23.0,NaN,23.0,0.0
30895,80ce03b1-385d-4e36-8f23-12f20f0da110,MSC DOUALA VIII,99836950,UX438A,2024-10-11,2024-10-11 12:00:00,UTC +10:00,NOON,AT SEA,3000N,15427E,59.01,57754.00,True,24.0,24.0,432.0,601.0,17.791667,18.000000,61.9,3.2,20.0,22.0,12.9,12.9,94430.0,91.0,0.36,70.44,2972.0,29.0,28.0,427.0,PAPTY,2024-10-27 21:00:00,UTC -05:00,PANAMA,NaN,24.0,302.0,336.0,18.0,7225.0,401.0,0.0,0.0,4.0,31.0,1185403.0,KRPUS,BUSAN,False,True,NaN,NaN,BERTH CONGESTION,NaN,2024-10-05 14:00:00,UTC +09:00,NaT,NaN,NaN,NaN,NaN,2024-10-06 15:00:00,UTC +09:00,NaN,NaN,NaN,2774.0,198.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,59.01,0.0,0.0,0.00,0.0,0.0,0.0,0.0,8.62,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,14207.0,0.0,0.0,0.0,1562.0,0.0,0.0,0.0,2O,CHIEF ENGINEER,True,True,1.8,NaN,NaN,NaN,NaN,NaN,NaN,185.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8942.0,0,37482.0,NaN,NaN,NaN,52.9,NaN,NaN,2.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,2.060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.0,1904.02,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
30896,91101114-2203-428a-a96b-93984bd454f2,MSC DOUALA VIII,99836950,UX438A,2024-10-12,2024-10-12 12:00:00,UTC +11:00,NOON,AT SEA,3000N,16219E,54.75,57754.00,True,23.0,23.0,410.0,541.0,17.304348,17.826087,0.0,0.0,10.0,25.0,12.9,12.9,94370.0,92.0,0.37,32.58,2972.0,29.0,28.0,398.0,PAPTY,2024-10-27 21:00:00,UTC -05:00,PANAMA,NaN,23.0,295.0,331.0,18.0,6815.0,377.0,0.0,0.0,4.0,31.0,1268904.0,KRPUS,BUSAN,False,True,NaN,NaN,BERTH CONGESTION,NaN,2024-10-05 14:00:00,UTC +09:00,NaT,NaN,NaN,NaN,NaN,2024-10-06 15:00:00,UTC +09:00,NaN,NaN,NaN,2774.0,198.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,23.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7,0.0,23.0,0.0,0.0,0.0,0.0,54.75,0.0,0.0,0.00,0.0,0.0,0.0,0.0,8.23,0.0,0.0,0.10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,13643.0,0.0,640.0,0.0,1535.0,0.0,0.0,0.0,2O,CHIEF ENGINEER,True,True,1.6,NaN,NaN,NaN,NaN,NaN,NaN,180.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8942.0,0,35742.0,NaN,NaN,NaN,63.4,NaN,NaN,2.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,1.510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,830.23,0.0,0.0,0.0,0.0,1841.04,0.0,0.0,0.0,0.0,NaN,23.0,NaN,23.0,0.0
30897,57d70294-bedc-46ab-8ee0-4c8e550b66a1,MSC DOUALA VIII,99836950,UX438A,2024-10-13,2024-10-13 12:00:00,UTC +11:00,NOON,AT SEA,2959N,17017E,57.29,57754.00,True,24.0,24.0,415.0,562.0,16.833333,17.291667,0.0,0.0,8.0,20.0,12.9,12.9,94310.0,91.0,0.08,47.92,2972.0,29.0,28.0,404.0,PAPTY,2024-10-27 21:00:00,UTC -05:00,PANAMA,NaN,24.0,295.0,331.0,17.9,6398.0,357.0,0.0,0.0,4.0,31.0,1355129.0,KRPUS,BUSAN,False,True,NaN,NaN,BERTH CONGESTION,NaN,2024-10-05 14:00:00,UTC +09:00,NaT,NaN,NaN,NaN,NaN,2024-10-06 15:00:00,UTC +09:00,NaN,NaN,NaN,2774.0,198.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.6,0.1,0.0,24.0,0.0,0.0,0.0,0.0,57.29,0.0,0.0,0.00,0.0,0.0,0.0,0.0,8.23,0.0,0.0,0.10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,13527.0,0.0,0.0,0.0,1554.0,0.0,0.0,0.0,2O,CHIEF ENGINEER,True,True,2.1,NaN,NaN,NaN,NaN,NaN,NaN,172.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,8942.0,0,37287.0,No.1 & No.2 Generators Shut down trips tried out.,NaN,NaN,44.6,NaN,NaN,1.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,2.650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,830.13,0.0,0.0,0.0,0.0,1775.52,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0

In [ ]:
data_processing(df_sorted)