In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd

In [3]:
charter = pd.read_csv("charter_imos_dec.csv")

charter

,MessagesId,ImoNumber,vName,MessageType,DateTimeLt,DateTimeUtc,Latitude,Longitude,CargoMT,CargoTEU,...,ETB Date/Time,Steaming time m/e residual hs,Steaming time m/e residual uls,Steaming time m/e residual vls,Rpm,Shift berth hours,ROB fresh water,Rob actual sludge,Rob actual bilge,Qty sludge disposed
0,5191837,9143879,MSC LILO F,Port Noon,2024-01-01 12:00:00 +03:00,2024-01-01 09:00:00,NaN,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,50.0,NaN,NaN,NaN
1,5189396,9618264,MSC ABIDJAN,Delay,2024-01-01 12:00:00 +02:00,2024-01-01 10:00:00,3317S,01721E,36869.0,2291.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5190792,9618290,MSC ADELAIDE,Delay,2024-01-01 12:00:00 +02:00,2024-01-01 10:00:00,2920S,03216E,35148.1,2532.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5189878,9135638,MSC JEANNE,Noon,2024-01-01 12:00:00 +01:00,2024-01-01 11:00:00,5538N,01528E,14950.4,1576.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5189849,9618305,MSC ATHENS,Delay,2024-01-01 12:00:00 +01:00,2024-01-01 11:00:00,5132N,00248E,28484.0,2581.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5465,5858084,9618317,MSC ATHOS,Port Noon,2024-12-08 12:00:00 +01:00,2024-12-08 11:00:00,NaN,NaN,34983.0,3208.0,...,NaN,NaN,NaN,NaN,NaN,0.0,291.0,NaN,NaN,NaN
5466,5857994,9256365,MSC TURIN II,Sailing,2024-12-08 19:54:00 +03:00,2024-12-08 16:54:00,NaN,NaN,7763.0,1000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5467,5857995,9256365,MSC TURIN II,COSP,2024-12-08 20:12:00 +03:00,2024-12-08 17:12:00,4053N,02731E,7763.0,1000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5468,5858281,9135638,MSC JEANNE,Sailing,2024-12-09 00:30:00 +03:00,2024-12-08 21:30:00,NaN,NaN,16385.0,356.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5469,5858289,9135638,MSC JEANNE,COSP,2024-12-09 00:48:00 +03:00,2024-12-08 21:48:00,4026N,02905E,16385.0,356.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
charter.columns.to_list()

['MessagesId',
 'ImoNumber',
 'vName',
 'MessageType',
 'DateTimeLt',
 'DateTimeUtc',
 'Latitude',
 'Longitude',
 'CargoMT',
 'CargoTEU',
 'DraftAft',
 'DraftFwd',
 'Speed by gps',
 'Speed by log',
 'FOC_AE_DIS',
 'FOC_AE_LNG',
 'FOC_AE_RES_HS',
 'FOC_AE_RES_ULS',
 'FOC_AE_RES_VLS',
 'FOC_BLR_DIS',
 'FOC_BLR_LNG',
 'FOC_BLR_RES_HS',
 'FOC_BLR_RES_ULS',
 'FOC_BLR_RES_VLS',
 'FOC_ME_DIS',
 'FOC_ME_LNG',
 'FOC_ME_RES_HS',
 'FOC_ME_RES_ULS',
 'FOC_ME_RES_VLS',
 'Hours_AE_1',
 'Hours_AE_2',
 'Hours_AE_3',
 'Hours_AE_4',
 'Hours_AE_5',
 'Hours_ME',
 'Hours_SG',
 'Hours_TG',
 'Power_AE_1',
 'Power_AE_2',
 'Power_AE_3',
 'Power_AE_4',
 'Power_AE_5',
 'Power_ME',
 'Power_SG',
 'Power_TG',
 'ROB_DIS',
 'ROB_LNG',
 'ROB_RES_HS',
 'ROB_RES_ULS',
 'ROB_RES_VLS',
 'Max Residual HS capacity',
 'Max Lng capacity',
 'Min Lng request',
 'Tanktainer number',
 'Tanktainer min request',
 'Template version',
 'Port bunkering',
 'TANKTAINER ROB',
 'Comments',
 'Product Name',
 'Physical supplier name',
 'Volume',
 'Quantity',
 'Density at 15Â°C',
 'Viscosity at 40Â°C or 50Â°C',
 'Sulfur content',
 'Bunker Order',
 'Bdn number',
 'Port Code',
 'Port Name',
 'Pilot date/time',
 'PIER date/time',
 'Time manoeuvring',
 'Displacement',
 'Estimated departure date/time',
 'Number of Tanktainer',
 'Manoeuvring miles by gps',
 'Manoeuvring miles by speed log',
 'Kwhr total',
 'Hold ventilation off',
 'Reefers positive plugged',
 'Reefers negative plugged',
 'Me total revs counter',
 'Rob fresh water',
 'Egcs running time',
 'So2/co2 ratio',
 'Rob tot Sludge',
 'Ballast',
 'Egcs closed loop running time',
 'Egcs open loop running time',
 'Reefer power consumption',
 'Rob Ajustment HS',
 'Rob Adjustment VLS',
 'Rob Adjustment ULS',
 'Rob Adjustment Dist',
 'Rob Adjustment LNG',
 'Drydock2',
 'Rob Tanktainer adjustment',
 'Wind direction',
 'Miles by gps',
 'STEAMING TIME M/E RESIDUAL HS',
 'RPM',
 'Slip',
 'ETA Port Code',
 'ETA Port Name',
 'ETA Date/Time',
 'Wind speed',
 'Course at Sea',
 'Wave height',
 'Sea state',
 'Ambient temp',
 'Sw temp',
 'Miles speed log',
 'Requested speed',
 'Time change',
 'Time sea',
 'kwhr total',
 'Scavenge pressure',
 'SEA DIRECTION',
 'Eca miles',
 'Eca time',
 'Steaming time m/e lng',
 'Drydock',
 'TEU Full',
 'TEU Empty',
 'Fresh water supply',
 'Tanktainer distillates transfd',
 'Hold Ventilation On/Off',
 'Bilge removed',
 'Tot sludge removed',
 'Garbage cat a - plastic removed',
 'Garbage cat b - organic removed',
 'Garbage cat c - domestic removed',
 'Garbage cat e - ashes removed',
 'Rob garbage cat a - plastic',
 'Rob garbage cat b - organic',
 'Rob garbage cat c - domestic',
 'Rob garbage cat e - ashes',
 'Egcs wet waste removed',
 'Egcs dry waste removed',
 'Total Number of pax on board',
 'Total Number of vehicles on board',
 'Type of delay',
 'Reason',
 'Time hrs. anchor',
 'Time hrs. drift',
 'Eta date/time',
 'Sludge rob',
 'Sludge min discharge request',
 'Oil Cylinder',
 'DryDock',
 'ETB Date/Time',
 'Steaming time m/e residual hs',
 'Steaming time m/e residual uls',
 'Steaming time m/e residual vls',
 'Rpm',
 'Shift berth hours',
 'ROB fresh water',
 'Rob actual sludge',
 'Rob actual bilge',
 'Qty sludge disposed']

In [9]:
#Rename the client file column to our old db columns name
charter= charter.rename(columns = {"MessagesId":"GID",
"DateTimeLt":"Corrected Date",
"vName":"VSL",
"ImoNumber":"IMO No",
"DateTimeUtc":"REPORT DATE TIME",
"MessageType":"Report Type",
"Latitude":"LAT",
"Longitude":"LONG",
"CargoMT":"CARGO TOTAL",
"Hours_ME":'Total M E Hours Fuel Only',
"Miles by gps":"MILES BY GPS",
"Oil Cylinder":"OIL CYL",
"Speed by log":"SPEED BY LOG",
"Speed by gps":"SPEED BY GPS",
"RPM":"RPM",
"Slip":"SLIP",
"Wind direction":"WIND DIRECTION",
"Wind speed":"WIND SPEED",
"DraftAft":"DRAFT AFT",
"DraftFwd":"DRAFT FWD",
"Displacement":"DISPLACEMENT",
"Course at Sea":"COURSE AT SEA",
"Wave height":"WAVE HEIGHT",
"SEA DIRECTION":"SEA DIRECTION",
"CargoTEU":"CARGO TOTAL TEU",
"Ambient temp":"AMBIENT TEMP",
"Sw temp":"SW TEMP",
"Miles speed log":"MILES BY SPEED LOG",
"ETA Port Code":"ETA PORT CODE",
"ETA Date/Time":"ETA DATE TIME",
"ETA Port Name":"ETA PORT",
"Time change":"TIME CHANGE",
"Time sea":"TIME SEA",
"Requested speed":"REQUESTED SPEED",
"Reefers positive plugged":"REEFERS POSITIVE PLUGGED",
"Reefers negative plugged":"REEFERS NEGATIVE PLUGGED",
"Me total revs counter":"ME TOTAL REVS COUNTER",
"Port Code":"PORT CODE",
"Port Name":"PORT",
"Time hrs. anchor":"TIME HRS ANCHOR",
"Time hrs. drift":"TIME HRS DRIFT",
"Reason":"REASON",
"Type of delay":"TYPE OF DELAY",
"ETB Date/Time":"ETB DATE TIME",
"Time manoeuvring":"TIME MANOEUVRING",
"Estimated departure date/time":"ETD DATE TIME",
"Shift berth hours":"SHIFT BERTH HOURS",
"TEU Full":"TEU FULL",
"TEU Empty":"TEU EMPTY",
"Bilge removed":"BILGE REMOVED",
"Fresh water supply":"FW SUPPLY",
"Steaming time m/e residual vls":"STEAMING TIME M E Rsdl VLS",
"Steaming time m/e residual hs":"STEAMING TIME M E Rsdl HS",
"Steaming time m/e residual uls":"STEAMING TIME M E Rsdl ULS",
"Steaming time m/e distillate vls":"STEAMING TIME M E Dstlt VLS",
"Steaming time m/e distillate uls":"STEAMING TIME M E Dstlt ULS",
"Hours_AE_1":"STEAMING TIME AUX 1",
"Hours_AE_2":"STEAMING TIME AUX 2",
"Hours_AE_3":"STEAMING TIME AUX 3",
"Hours_AE_4":"STEAMING TIME AUX 4",
"Hours_AE_5":"STEAMING TIME AUX 5",
"Hours_SG":"STEAMING TIME SH GEN",
"Hours_TG":"STEAMING TIME TG",
"FOC_ME_RES_VLS":"FUEL M E Rsdl VLS",
"FOC_ME_RES_HS":"FUEL M E Rsdl HS",
"FOC_ME_RES_ULS":"FUEL M E Rsdl ULS",
"FOC_ME_DIS_VLS":"FUEL M E Dstlt VLS",
"FOC_ME_DIS_ULS":"FUEL M E Dstlt ULS",
"FOC_ME_LNG":"FUEL M E LNG",
"FOC_ME_DIS":"FUEL M E Tnktnr Dstlt VLS",
"FOC_AE_RES_VLS":"FUEL Aux Rsdl VLS",
"FOC_AE_RES_HS":"FUEL Aux Rsdl HS",
"FOC_AE_RES_ULS":"FUEL Aux Rsdl ULS",
"FOC_AE_DIS_VLS":"FUEL Aux Dstlt VLS",
"FOC_AE_DIS_ULS":"FUEL Aux Dstlt ULS",
"FOC_AE_DIS":"FUEL Aux Tnktnr Dstlt VLS",
"FOC_AE_LNG":"FUEL Aux LNG",
"FOC_BLR_RES_VLS":"FUEL Boiler Rsdl VLS",
"FOC_BLR_RES_HS":"FUEL Boiler Rsdl HS",
"FOC_BLR_RES_ULS":"FUEL Boiler Rsdl ULS",
"FOC_BLR_DIS_VLS":"FUEL Boiler Dstlt VLS",
"FOC_BLR_DIS_ULS":"FUEL Boiler Dstlt ULS",
"FOC_BLR_DIS":"FUEL Boiler Tnktnr Dstlt VLS",
"FOC_BLR_LNG":"FUEL Boiler LNG",
"Power_ME":"POWER KW",
"Power_AE_1":"STEAMING LOAD KW AUX 1",
"Power_AE_2":"STEAMING LOAD KW AUX 2",
"Power_AE_3":"STEAMING LOAD KW AUX 3",
"Power_AE_4":"STEAMING LOAD KW AUX 4",
"Power_AE_5":"STEAMING LOAD KW AUX 5",
"Power_SG":"STEAMING LOAD KW SH GEN",
"Power_TG":"STEAMING LOAD KW TG",
"Scavenge pressure":"SCAVENGE PRESSURE",
"Rob fresh water":"ROB FRESH WATER",
"Manoeuvring miles by gps":"MANVRNG MILES BY GPS",
"Manoeuvring miles by speed log":"MANVRNG MILES BY SPEED LOG",
"Ballast":"BALLAST",
"Number of Tanktainer":"TANKTAINER NUMBER",
"Rob actual bilge":"ROB BILGE",
"Sea state":"SEA STATE",
"So2/co2 ratio":"SO2 CO2 RATIO",
"Bunker Order":"Bunker Order",
"Bdn number":"BDN Number",
"Product Name":"Fuel Type",
"Sulfur content":"Sulphur Content PC",
"Quantity":"Quantity",
"Port bunkering":"Port Delivery",
"Tanktainer number":"Tanktainer Number_1",
"Physical supplier name":"Supplier",
"Volume":"Vol Lt",
"Density at 15Â°C":"Den",
"Viscosity at 40Â°C or 50Â°C":"Vis",
"ROB_DIS_ULS":"ROB Dstlt ULS",
"ROB_DIS_VLS":"ROB Dstlt VLS",
"ROB_DIS":"ROB Tnktnr Dstlt VLS",
"ROB_RES_VLS":"ROB Rsdl VLS",
"ROB_RES_HS":"ROB Rsdl HS",
"ROB_RES_ULS":"ROB Rsdl ULS",
"ROB_LNG":"ROB Rsdl LNG",
"Eca miles":"ECA MILES",
"Eca time":"ECA TIME",
"Egcs dry waste removed":"EGCS DRY WASTE REMOVED",
"Egcs running time":"EGCS RUNNING TIME",
"Egcs wet waste removed":"EGCS WET SLURRY REMOVED",
"Egcs open loop running time":"EGCS OPEN LOOP RUNNING TIME",
"Egcs closed loop running time":"EGCS CLOSED LOOP RUNNING TIME"})
charter

,GID,IMO No,VSL,Report Type,Corrected Date,REPORT DATE TIME,LAT,LONG,CARGO TOTAL,CARGO TOTAL TEU,...,ETB DATE TIME,STEAMING TIME M E Rsdl HS,STEAMING TIME M E Rsdl ULS,STEAMING TIME M E Rsdl VLS,Rpm,SHIFT BERTH HOURS,ROB fresh water,Rob actual sludge,ROB BILGE,Qty sludge disposed
0,5191837,9143879,MSC LILO F,Port Noon,2024-01-01 12:00:00 +03:00,2024-01-01 09:00:00,NaN,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,50.0,NaN,NaN,NaN
1,5189396,9618264,MSC ABIDJAN,Delay,2024-01-01 12:00:00 +02:00,2024-01-01 10:00:00,3317S,01721E,36869.0,2291.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5190792,9618290,MSC ADELAIDE,Delay,2024-01-01 12:00:00 +02:00,2024-01-01 10:00:00,2920S,03216E,35148.1,2532.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5189878,9135638,MSC JEANNE,Noon,2024-01-01 12:00:00 +01:00,2024-01-01 11:00:00,5538N,01528E,14950.4,1576.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5189849,9618305,MSC ATHENS,Delay,2024-01-01 12:00:00 +01:00,2024-01-01 11:00:00,5132N,00248E,28484.0,2581.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5465,5858084,9618317,MSC ATHOS,Port Noon,2024-12-08 12:00:00 +01:00,2024-12-08 11:00:00,NaN,NaN,34983.0,3208.0,...,NaN,NaN,NaN,NaN,NaN,0.0,291.0,NaN,NaN,NaN
5466,5857994,9256365,MSC TURIN II,Sailing,2024-12-08 19:54:00 +03:00,2024-12-08 16:54:00,NaN,NaN,7763.0,1000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5467,5857995,9256365,MSC TURIN II,COSP,2024-12-08 20:12:00 +03:00,2024-12-08 17:12:00,4053N,02731E,7763.0,1000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5468,5858281,9135638,MSC JEANNE,Sailing,2024-12-09 00:30:00 +03:00,2024-12-08 21:30:00,NaN,NaN,16385.0,356.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5469,5858289,9135638,MSC JEANNE,COSP,2024-12-09 00:48:00 +03:00,2024-12-08 21:48:00,4026N,02905E,16385.0,356.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
charter['IMO No'].nunique()

7

In [ ]:
charter = charter.drop_duplicates(subset=['GID'],keep='first')

In [13]:
duplicate_gid = charter[charter.duplicated(subset='GID', keep=False)]
duplicate_gid

Empty DataFrame
Columns: [GID, IMO No, VSL, Report Type, Corrected Date, REPORT DATE TIME, LAT, LONG, CARGO TOTAL, CARGO TOTAL TEU, DRAFT AFT, DRAFT FWD, SPEED BY GPS, SPEED BY LOG, FUEL Aux Tnktnr Dstlt VLS, FUEL Aux LNG, FUEL Aux Rsdl HS, FUEL Aux Rsdl ULS, FUEL Aux Rsdl VLS, FUEL Boiler Tnktnr Dstlt VLS, FUEL Boiler LNG, FUEL Boiler Rsdl HS, FUEL Boiler Rsdl ULS, FUEL Boiler Rsdl VLS, FUEL M E Tnktnr Dstlt VLS, FUEL M E LNG, FUEL M E Rsdl HS, FUEL M E Rsdl ULS, FUEL M E Rsdl VLS, STEAMING TIME AUX 1, STEAMING TIME AUX 2, STEAMING TIME AUX 3, STEAMING TIME AUX 4, STEAMING TIME AUX 5, Total M E Hours Fuel Only, STEAMING TIME SH GEN, STEAMING TIME TG, STEAMING LOAD KW AUX 1, STEAMING LOAD KW AUX 2, STEAMING LOAD KW AUX 3, STEAMING LOAD KW AUX 4, STEAMING LOAD KW AUX 5, POWER KW, STEAMING LOAD KW SH GEN, STEAMING LOAD KW TG, ROB Tnktnr Dstlt VLS, ROB Rsdl LNG, ROB Rsdl HS, ROB Rsdl ULS, ROB Rsdl VLS, Max Residual HS capacity, Max Lng capacity, Min Lng request, Tanktainer Number_1, Tanktainer min request, Template version, Port Delivery, TANKTAINER ROB, Comments, Fuel Type, Supplier, Vol Lt, Quantity, Den, Vis, Sulphur Content PC, Bunker Order, BDN Number, PORT CODE, PORT, Pilot date/time, PIER date/time, TIME MANOEUVRING, DISPLACEMENT, ETD DATE TIME, TANKTAINER NUMBER, MANVRNG MILES BY GPS, MANVRNG MILES BY SPEED LOG, Kwhr total, Hold ventilation off, REEFERS POSITIVE PLUGGED, REEFERS NEGATIVE PLUGGED, ME TOTAL REVS COUNTER, ROB FRESH WATER, EGCS RUNNING TIME, SO2 CO2 RATIO, Rob tot Sludge, BALLAST, EGCS CLOSED LOOP RUNNING TIME, EGCS OPEN LOOP RUNNING TIME, Reefer power consumption, Rob Ajustment HS, Rob Adjustment VLS, Rob Adjustment ULS, Rob Adjustment Dist, Rob Adjustment LNG, Drydock2, Rob Tanktainer adjustment, WIND DIRECTION, MILES BY GPS, ...]
Index: []

[0 rows x 161 columns]

In [15]:
charter.columns.to_list()

['GID',
 'IMO No',
 'VSL',
 'Report Type',
 'Corrected Date',
 'REPORT DATE TIME',
 'LAT',
 'LONG',
 'CARGO TOTAL',
 'CARGO TOTAL TEU',
 'DRAFT AFT',
 'DRAFT FWD',
 'SPEED BY GPS',
 'SPEED BY LOG',
 'FUEL Aux Tnktnr Dstlt VLS',
 'FUEL Aux LNG',
 'FUEL Aux Rsdl HS',
 'FUEL Aux Rsdl ULS',
 'FUEL Aux Rsdl VLS',
 'FUEL Boiler Tnktnr Dstlt VLS',
 'FUEL Boiler LNG',
 'FUEL Boiler Rsdl HS',
 'FUEL Boiler Rsdl ULS',
 'FUEL Boiler Rsdl VLS',
 'FUEL M E Tnktnr Dstlt VLS',
 'FUEL M E LNG',
 'FUEL M E Rsdl HS',
 'FUEL M E Rsdl ULS',
 'FUEL M E Rsdl VLS',
 'STEAMING TIME AUX 1',
 'STEAMING TIME AUX 2',
 'STEAMING TIME AUX 3',
 'STEAMING TIME AUX 4',
 'STEAMING TIME AUX 5',
 'Total M E Hours Fuel Only',
 'STEAMING TIME SH GEN',
 'STEAMING TIME TG',
 'STEAMING LOAD KW AUX 1',
 'STEAMING LOAD KW AUX 2',
 'STEAMING LOAD KW AUX 3',
 'STEAMING LOAD KW AUX 4',
 'STEAMING LOAD KW AUX 5',
 'POWER KW',
 'STEAMING LOAD KW SH GEN',
 'STEAMING LOAD KW TG',
 'ROB Tnktnr Dstlt VLS',
 'ROB Rsdl LNG',
 'ROB Rsdl HS',
 'ROB Rsdl ULS',
 'ROB Rsdl VLS',
 'Max Residual HS capacity',
 'Max Lng capacity',
 'Min Lng request',
 'Tanktainer Number_1',
 'Tanktainer min request',
 'Template version',
 'Port Delivery',
 'TANKTAINER ROB',
 'Comments',
 'Fuel Type',
 'Supplier',
 'Vol Lt',
 'Quantity',
 'Den',
 'Vis',
 'Sulphur Content PC',
 'Bunker Order',
 'BDN Number',
 'PORT CODE',
 'PORT',
 'Pilot date/time',
 'PIER date/time',
 'TIME MANOEUVRING',
 'DISPLACEMENT',
 'ETD DATE TIME',
 'TANKTAINER NUMBER',
 'MANVRNG MILES BY GPS',
 'MANVRNG MILES BY SPEED LOG',
 'Kwhr total',
 'Hold ventilation off',
 'REEFERS POSITIVE PLUGGED',
 'REEFERS NEGATIVE PLUGGED',
 'ME TOTAL REVS COUNTER',
 'ROB FRESH WATER',
 'EGCS RUNNING TIME',
 'SO2 CO2 RATIO',
 'Rob tot Sludge',
 'BALLAST',
 'EGCS CLOSED LOOP RUNNING TIME',
 'EGCS OPEN LOOP RUNNING TIME',
 'Reefer power consumption',
 'Rob Ajustment HS',
 'Rob Adjustment VLS',
 'Rob Adjustment ULS',
 'Rob Adjustment Dist',
 'Rob Adjustment LNG',
 'Drydock2',
 'Rob Tanktainer adjustment',
 'WIND DIRECTION',
 'MILES BY GPS',
 'STEAMING TIME M/E RESIDUAL HS',
 'RPM',
 'SLIP',
 'ETA PORT CODE',
 'ETA PORT',
 'ETA DATE TIME',
 'WIND SPEED',
 'COURSE AT SEA',
 'WAVE HEIGHT',
 'SEA STATE',
 'AMBIENT TEMP',
 'SW TEMP',
 'MILES BY SPEED LOG',
 'REQUESTED SPEED',
 'TIME CHANGE',
 'TIME SEA',
 'kwhr total',
 'SCAVENGE PRESSURE',
 'SEA DIRECTION',
 'ECA MILES',
 'ECA TIME',
 'Steaming time m/e lng',
 'Drydock',
 'TEU FULL',
 'TEU EMPTY',
 'FW SUPPLY',
 'Tanktainer distillates transfd',
 'Hold Ventilation On/Off',
 'BILGE REMOVED',
 'Tot sludge removed',
 'Garbage cat a - plastic removed',
 'Garbage cat b - organic removed',
 'Garbage cat c - domestic removed',
 'Garbage cat e - ashes removed',
 'Rob garbage cat a - plastic',
 'Rob garbage cat b - organic',
 'Rob garbage cat c - domestic',
 'Rob garbage cat e - ashes',
 'EGCS WET SLURRY REMOVED',
 'EGCS DRY WASTE REMOVED',
 'Total Number of pax on board',
 'Total Number of vehicles on board',
 'TYPE OF DELAY',
 'REASON',
 'TIME HRS ANCHOR',
 'TIME HRS DRIFT',
 'Eta date/time',
 'Sludge rob',
 'Sludge min discharge request',
 'OIL CYL',
 'DryDock',
 'ETB DATE TIME',
 'STEAMING TIME M E Rsdl HS',
 'STEAMING TIME M E Rsdl ULS',
 'STEAMING TIME M E Rsdl VLS',
 'Rpm',
 'SHIFT BERTH HOURS',
 'ROB fresh water',
 'Rob actual sludge',
 'ROB BILGE',
 'Qty sludge disposed']

In [17]:
import numpy as np

In [19]:
#THese columns are not there in client file but there in our db so create a column and save it as nan file 
columns = ["VOY","Status","M E FOC","Has Cargo","Total M E Hours Fuel Only","ETA DATE TIME Offset","TEMP MIN","TEMP MAX","REM DIST TO PILOT","REM TIME TO PILOT","TOTAL UNPLND STPGE TECH","TOTAL UNPLND STPGE OPE WX","AUX BLOWERS ON","HOLD VENTILATION ON","ETB DATE TIME Offset","PILOT DATE TIME","PILOT DATE TIME Offset","TUG ARR","TUG SHIFT","ETD DATE TIME Offset","CARGO LOAD","CARGO DISCH","GARBAGE REMOVED","GARBAGE REMVL REQSTD","GARBAGE REMVL CMPLSRY","CY CREW SIGNED ON","CY CREW SIGNED OFF","CY DOCTORS VISIT","CY MAIL RECEIVED Ref NO","CY LUB OIL SAMPLE LANDED","CY CHECKD FOR STOWAWAYS","CY STOWAWAYS ON BOARD","CY DEP GM Mtr","CY REQUISITIONS RECEIVED","DISTANCE TO NEXT PILOT","TUG SAILING TRANSIT","STEAMING TIME M E Tnktnr Dstlt VLS","FUEL M E MDO","FUEL Aux MDO","FUEL Boiler MDO","DECK LAST CHANGE USER","ENGINE LAST CHANGE USER","DECK PART IS COMPLETE","ENGINE PART IS COMPLETE","SECA ENTRY TIME","SECA ENTRY LAT","SECA ENTRY LONG","SECA EXIT TIME","SECA EXIT LAT","SECA EXIT LONG","TANKTAINER TRANSFD QUANTITY","PILOT TAKEN","DATE TIME START TRANSIT","DATE TIME START TRANSIT Offset","DATE TIME END TRANSIT","DATE TIME END TRANSIT Offset","STEAMING KWHR TOTAL","CY OTHERS","ROB FO SLUDGE","ROB LO SLUDGE","SLUDGE REMOVED FO","SLUDGE REMOVED LO","CY LUB ADDED TO SYSTEM MECC","CY LUB ADDED TO SYSTEM AECC","CY LUB ADDED TO THRUSTERS","CY ME LO PURIFIER IN USE","CY BALLAST","CY BENDING MOMENT","CY SHEARING FORCE","CY TORTION MOMENT","CY SUPDT AUDITOR SIGNED ON","CY SUPDT AUDITOR SIGNED OFF","CY CASH RECEIVED","CY LUB OIL RECEIVED MECYL","CY LUB OIL RECEIVED MECC","CY LUB OIL RECEIVED AECC","CY M E UNDER PISTON TEMP","CY MAIL RECEIVED","WIND DIRECTION PORT STBD","SEA DIRECTION PORT STBD","TIME PILOT ONBOARD","GRADES ROB","Remarks","Carbon Factor","Product Quality","Delivery","ROB Rsdl MDO",'STEAMING TIME M E Dstlt ULS','STEAMING TIME M E Dstlt VLS','FUEL M E Dstlt VLS','FUEL M E Dstlt ULS','FUEL Aux Dstlt VLS','FUEL Aux Dstlt ULS','FUEL Boiler Dstlt VLS','FUEL Boiler Dstlt ULS','ROB Dstlt VLS','ROB Dstlt ULS']
charter[columns] = np.nan

In [21]:
charter['STEAMING TIME M E HS'] = charter['STEAMING TIME M E Rsdl HS']
charter['STEAMING TIME M E LS'] = charter[['STEAMING TIME M E Rsdl ULS','STEAMING TIME M E Rsdl VLS']].sum(axis=1) 
charter['STEAMING TIME M E MGO'] = charter[['STEAMING TIME M E Dstlt VLS','STEAMING TIME M E Tnktnr Dstlt VLS']].sum(axis=1)
charter['STEAMING TIME M E MGO LS'] = charter['STEAMING TIME M E Dstlt ULS']
charter['FUEL M E HS'] = charter['FUEL M E Rsdl HS'] 
charter['FUEL M E LS'] = charter[['FUEL M E Rsdl VLS','FUEL M E Rsdl ULS']].sum(axis=1)
charter['FUEL M E MGO'] = charter[['FUEL M E Dstlt VLS','FUEL M E Tnktnr Dstlt VLS']].sum(axis=1)
charter['FUEL M E MGO LS'] = charter['FUEL M E Dstlt ULS']
charter['FUEL Aux HS'] = charter['FUEL Aux Rsdl HS']
charter['FUEL Aux LS'] = charter[['FUEL Aux Rsdl VLS','FUEL Aux Rsdl ULS']].sum(axis=1)
charter['FUEL Aux MGO'] = charter[['FUEL Aux Dstlt VLS','FUEL Aux Tnktnr Dstlt VLS']].sum(axis=1)
charter['FUEL Aux MGO LS'] = charter['FUEL Aux Dstlt ULS']
charter['FUEL Boiler HS'] = charter['FUEL Boiler Rsdl HS'] 
charter['FUEL Boiler LS'] = charter[['FUEL Boiler Rsdl VLS','FUEL Boiler Rsdl ULS']].sum(axis=1)
charter['FUEL Boiler MGO'] = charter[['FUEL Boiler Dstlt VLS','FUEL Boiler Tnktnr Dstlt VLS']].sum(axis=1)
charter['FUEL Boiler MGO LS'] = charter['FUEL Boiler Dstlt ULS']
charter['ROB FUEL HSFO'] = charter['ROB Rsdl HS'] 
charter['ROB FUEL LSFO'] = charter[['ROB Rsdl VLS','ROB Rsdl ULS']].sum(axis=1)
charter['ROB FUEL MDO'] = charter['ROB Rsdl MDO']
charter['ROB FUEL MGO'] = charter['ROB Dstlt VLS']
charter['ROB FUEL MGO LS'] = charter['ROB Dstlt ULS']
charter['ROB FUEL Tanktainer MGO'] = charter['ROB Tnktnr Dstlt VLS']
charter

,GID,IMO No,VSL,Report Type,Corrected Date,REPORT DATE TIME,LAT,LONG,CARGO TOTAL,CARGO TOTAL TEU,...,FUEL Boiler HS,FUEL Boiler LS,FUEL Boiler MGO,FUEL Boiler MGO LS,ROB FUEL HSFO,ROB FUEL LSFO,ROB FUEL MDO,ROB FUEL MGO,ROB FUEL MGO LS,ROB FUEL Tanktainer MGO
0,5191837,9143879,MSC LILO F,Port Noon,2024-01-01 12:00:00 +03:00,2024-01-01 09:00:00,NaN,NaN,0.0,0.0,...,NaN,0.00,0.69,NaN,NaN,22.20,NaN,NaN,NaN,26.67
1,5189396,9618264,MSC ABIDJAN,Delay,2024-01-01 12:00:00 +02:00,2024-01-01 10:00:00,3317S,01721E,36869.0,2291.0,...,NaN,0.00,4.00,NaN,1604.60,1718.90,NaN,NaN,NaN,467.30
2,5190792,9618290,MSC ADELAIDE,Delay,2024-01-01 12:00:00 +02:00,2024-01-01 10:00:00,2920S,03216E,35148.1,2532.0,...,NaN,2.38,0.00,NaN,NaN,3592.71,NaN,NaN,NaN,311.74
3,5189878,9135638,MSC JEANNE,Noon,2024-01-01 12:00:00 +01:00,2024-01-01 11:00:00,5538N,01528E,14950.4,1576.0,...,NaN,0.00,0.00,NaN,NaN,1290.32,NaN,NaN,NaN,476.92
4,5189849,9618305,MSC ATHENS,Delay,2024-01-01 12:00:00 +01:00,2024-01-01 11:00:00,5132N,00248E,28484.0,2581.0,...,NaN,0.00,2.40,NaN,5023.42,826.43,NaN,NaN,NaN,297.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5465,5858084,9618317,MSC ATHOS,Port Noon,2024-12-08 12:00:00 +01:00,2024-12-08 11:00:00,NaN,NaN,34983.0,3208.0,...,NaN,0.00,2.60,NaN,4442.40,18.62,NaN,NaN,NaN,90.20
5466,5857994,9256365,MSC TURIN II,Sailing,2024-12-08 19:54:00 +03:00,2024-12-08 16:54:00,NaN,NaN,7763.0,1000.0,...,NaN,0.00,0.32,NaN,NaN,203.33,NaN,NaN,NaN,83.20
5467,5857995,9256365,MSC TURIN II,COSP,2024-12-08 20:12:00 +03:00,2024-12-08 17:12:00,4053N,02731E,7763.0,1000.0,...,NaN,0.00,0.00,NaN,NaN,203.23,NaN,NaN,NaN,83.20
5468,5858281,9135638,MSC JEANNE,Sailing,2024-12-09 00:30:00 +03:00,2024-12-08 21:30:00,NaN,NaN,16385.0,356.0,...,NaN,0.00,0.82,NaN,NaN,331.25,NaN,NaN,NaN,101.56
5469,5858289,9135638,MSC JEANNE,COSP,2024-12-09 00:48:00 +03:00,2024-12-08 21:48:00,4026N,02905E,16385.0,356.0,...,NaN,0.00,0.00,NaN,NaN,330.91,NaN,NaN,NaN,101.53

In [23]:
#remove 'BDN Number' column
charter = charter.drop('BDN Number',axis=1)
charter

,GID,IMO No,VSL,Report Type,Corrected Date,REPORT DATE TIME,LAT,LONG,CARGO TOTAL,CARGO TOTAL TEU,...,FUEL Boiler HS,FUEL Boiler LS,FUEL Boiler MGO,FUEL Boiler MGO LS,ROB FUEL HSFO,ROB FUEL LSFO,ROB FUEL MDO,ROB FUEL MGO,ROB FUEL MGO LS,ROB FUEL Tanktainer MGO
0,5191837,9143879,MSC LILO F,Port Noon,2024-01-01 12:00:00 +03:00,2024-01-01 09:00:00,NaN,NaN,0.0,0.0,...,NaN,0.00,0.69,NaN,NaN,22.20,NaN,NaN,NaN,26.67
1,5189396,9618264,MSC ABIDJAN,Delay,2024-01-01 12:00:00 +02:00,2024-01-01 10:00:00,3317S,01721E,36869.0,2291.0,...,NaN,0.00,4.00,NaN,1604.60,1718.90,NaN,NaN,NaN,467.30
2,5190792,9618290,MSC ADELAIDE,Delay,2024-01-01 12:00:00 +02:00,2024-01-01 10:00:00,2920S,03216E,35148.1,2532.0,...,NaN,2.38,0.00,NaN,NaN,3592.71,NaN,NaN,NaN,311.74
3,5189878,9135638,MSC JEANNE,Noon,2024-01-01 12:00:00 +01:00,2024-01-01 11:00:00,5538N,01528E,14950.4,1576.0,...,NaN,0.00,0.00,NaN,NaN,1290.32,NaN,NaN,NaN,476.92
4,5189849,9618305,MSC ATHENS,Delay,2024-01-01 12:00:00 +01:00,2024-01-01 11:00:00,5132N,00248E,28484.0,2581.0,...,NaN,0.00,2.40,NaN,5023.42,826.43,NaN,NaN,NaN,297.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5465,5858084,9618317,MSC ATHOS,Port Noon,2024-12-08 12:00:00 +01:00,2024-12-08 11:00:00,NaN,NaN,34983.0,3208.0,...,NaN,0.00,2.60,NaN,4442.40,18.62,NaN,NaN,NaN,90.20
5466,5857994,9256365,MSC TURIN II,Sailing,2024-12-08 19:54:00 +03:00,2024-12-08 16:54:00,NaN,NaN,7763.0,1000.0,...,NaN,0.00,0.32,NaN,NaN,203.33,NaN,NaN,NaN,83.20
5467,5857995,9256365,MSC TURIN II,COSP,2024-12-08 20:12:00 +03:00,2024-12-08 17:12:00,4053N,02731E,7763.0,1000.0,...,NaN,0.00,0.00,NaN,NaN,203.23,NaN,NaN,NaN,83.20
5468,5858281,9135638,MSC JEANNE,Sailing,2024-12-09 00:30:00 +03:00,2024-12-08 21:30:00,NaN,NaN,16385.0,356.0,...,NaN,0.00,0.82,NaN,NaN,331.25,NaN,NaN,NaN,101.56
5469,5858289,9135638,MSC JEANNE,COSP,2024-12-09 00:48:00 +03:00,2024-12-08 21:48:00,4026N,02905E,16385.0,356.0,...,NaN,0.00,0.00,NaN,NaN,330.91,NaN,NaN,NaN,101.53

In [25]:
#add 'SINCE_DATE_TIME','SINCE_DATE_TIME_Offset' columns as null value
import numpy as np
charter['SINCE_DATE_TIME'] = np.nan
charter['SINCE_DATE_TIME_Offset'] = np.nan
charter

,GID,IMO No,VSL,Report Type,Corrected Date,REPORT DATE TIME,LAT,LONG,CARGO TOTAL,CARGO TOTAL TEU,...,FUEL Boiler MGO,FUEL Boiler MGO LS,ROB FUEL HSFO,ROB FUEL LSFO,ROB FUEL MDO,ROB FUEL MGO,ROB FUEL MGO LS,ROB FUEL Tanktainer MGO,SINCE_DATE_TIME,SINCE_DATE_TIME_Offset
0,5191837,9143879,MSC LILO F,Port Noon,2024-01-01 12:00:00 +03:00,2024-01-01 09:00:00,NaN,NaN,0.0,0.0,...,0.69,NaN,NaN,22.20,NaN,NaN,NaN,26.67,NaN,NaN
1,5189396,9618264,MSC ABIDJAN,Delay,2024-01-01 12:00:00 +02:00,2024-01-01 10:00:00,3317S,01721E,36869.0,2291.0,...,4.00,NaN,1604.60,1718.90,NaN,NaN,NaN,467.30,NaN,NaN
2,5190792,9618290,MSC ADELAIDE,Delay,2024-01-01 12:00:00 +02:00,2024-01-01 10:00:00,2920S,03216E,35148.1,2532.0,...,0.00,NaN,NaN,3592.71,NaN,NaN,NaN,311.74,NaN,NaN
3,5189878,9135638,MSC JEANNE,Noon,2024-01-01 12:00:00 +01:00,2024-01-01 11:00:00,5538N,01528E,14950.4,1576.0,...,0.00,NaN,NaN,1290.32,NaN,NaN,NaN,476.92,NaN,NaN
4,5189849,9618305,MSC ATHENS,Delay,2024-01-01 12:00:00 +01:00,2024-01-01 11:00:00,5132N,00248E,28484.0,2581.0,...,2.40,NaN,5023.42,826.43,NaN,NaN,NaN,297.20,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5465,5858084,9618317,MSC ATHOS,Port Noon,2024-12-08 12:00:00 +01:00,2024-12-08 11:00:00,NaN,NaN,34983.0,3208.0,...,2.60,NaN,4442.40,18.62,NaN,NaN,NaN,90.20,NaN,NaN
5466,5857994,9256365,MSC TURIN II,Sailing,2024-12-08 19:54:00 +03:00,2024-12-08 16:54:00,NaN,NaN,7763.0,1000.0,...,0.32,NaN,NaN,203.33,NaN,NaN,NaN,83.20,NaN,NaN
5467,5857995,9256365,MSC TURIN II,COSP,2024-12-08 20:12:00 +03:00,2024-12-08 17:12:00,4053N,02731E,7763.0,1000.0,...,0.00,NaN,NaN,203.23,NaN,NaN,NaN,83.20,NaN,NaN
5468,5858281,9135638,MSC JEANNE,Sailing,2024-12-09 00:30:00 +03:00,2024-12-08 21:30:00,NaN,NaN,16385.0,356.0,...,0.82,NaN,NaN,331.25,NaN,NaN,NaN,101.56,NaN,NaN
5469,5858289,9135638,MSC JEANNE,COSP,2024-12-09 00:48:00 +03:00,2024-12-08 21:48:00,4026N,02905E,16385.0,356.0,...,0.00,NaN,NaN,330.91,NaN,NaN,NaN,101.53,NaN,NaN

In [27]:
col = pd.read_excel(r"D:\Navalt\MSC\2023\Weekly Data\SERVER REF\Updated calculations in DB for updated fuel type 1.xlsx")
col

,Noondata,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Charter Data
0,idvessel,NaN,NaN,NaN,NaN,NaN,NaN,GID
1,GID,NaN,NaN,NaN,NaN,NaN,NaN,VSL
2,VSL,NaN,NaN,NaN,NaN,NaN,NaN,IMO_No
3,IMO_No,NaN,NaN,NaN,NaN,NaN,NaN,VOY
4,VOY,NaN,NaN,NaN,NaN,NaN,NaN,Corrected_Date
...,...,...,...,...,...,...,...,...
261,Kwhr_total,NaN,NaN,NaN,NaN,NaN,NaN,Sludge_rob
262,Sludge_rob,NaN,NaN,NaN,NaN,NaN,NaN,Sludge_min_discharge_request
263,Sludge_min_discharge_request,NaN,NaN,NaN,NaN,NaN,NaN,Rob_actual_sludge
264,Rob_actual_sludge,NaN,NaN,NaN,NaN,NaN,NaN,Qty_sludge_disposed
265,Qty_sludge_disposed,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
col_lst = col['Charter Data'].tolist()
col_lst

['GID',
 'VSL',
 'IMO_No',
 'VOY',
 'Corrected_Date',
 'REPORT_DATE_TIME',
 'REPORT_DATE_TIME_Offset',
 'Report_Type',
 'Status',
 'LAT',
 'LONG_',
 'M_E_FOC',
 'CARGO_TOTAL',
 'Has_Cargo',
 'STEAMING_TIME',
 'Total_M_E_Hours_Fuel_Only',
 'MILES_BY_GPS',
 'OIL_CYL',
 'SPEED_BY_LOG',
 'SPEED_BY_GPS',
 'RPM',
 'SLIP',
 'WIND_DIRECTION',
 'WIND_SPEED',
 'DRAFT_AFT',
 'DRAFT_FWD',
 'DISPLACEMENT',
 'COURSE_AT_SEA',
 'WAVE_HEIGHT',
 'SEA_DIRECTION',
 'CARGO_TOTAL_TEU',
 'AMBIENT_TEMP',
 'SW_TEMP',
 'MILES_BY_SPEED_LOG',
 'ETA_PORT_CODE',
 'ETA_DATE_TIME',
 'ETA_DATE_TIME_Offset',
 'ETA_PORT',
 'TIME_CHANGE',
 'TIME_SEA',
 'TEMP_MIN',
 'TEMP_MAX',
 'REQUESTED_SPEED',
 'REM_DIST_TO_PILOT',
 'REM_TIME_TO_PILOT',
 'TOTAL_UNPLND_STPGE_TECH',
 'TOTAL_UNPLND_STPGE_OPE_WX',
 'REEFERS_POSITIVE_PLUGGED',
 'REEFERS_NEGATIVE_PLUGGED',
 'ME_TOTAL_REVS_COUNTER',
 'PORT_CODE',
 'PORT',
 'AUX_BLOWERS_ON',
 'HOLD_VENTILATION_ON',
 'SINCE_DATE_TIME',
 'SINCE_DATE_TIME_Offset',
 'TIME_HRS_ANCHOR',
 'TIME_HRS_DRIFT',
 'REASON',
 'TYPE_OF_DELAY',
 'ETB_DATE_TIME',
 'ETB_DATE_TIME_Offset',
 'PILOT_DATE_TIME',
 'PILOT_DATE_TIME_Offset',
 'TIME_MANOEUVRING',
 'TUG_ARR',
 'TUG_SHIFT',
 'ETD_DATE_TIME',
 'ETD_DATE_TIME_Offset',
 'SHIFT_BERTH_HOURS',
 'CARGO_LOAD',
 'CARGO_DISCH',
 'TEU_FULL',
 'TEU_EMPTY',
 'BILGE_REMOVED',
 'GARBAGE_REMOVED',
 'GARBAGE_REMVL_REQSTD',
 'GARBAGE_REMVL_CMPLSRY',
 'FW_SUPPLY',
 'CY_CREW_SIGNED_ON',
 'CY_CREW_SIGNED_OFF',
 'CY_DOCTORS_VISIT',
 'CY_MAIL_RECEIVED_Ref_NO',
 'CY_LUB_OIL_SAMPLE_LANDED',
 'CY_CHECKD_FOR_STOWAWAYS',
 'CY_STOWAWAYS_ON_BOARD',
 'CY_DEP_GM_Mtr',
 'CY_REQUISITIONS_RECEIVED',
 'DISTANCE_TO_NEXT_PILOT',
 'TUG_SAILING_TRANSIT',
 'STEAMING_TIME_M_E_Rsdl_VLS',
 'STEAMING_TIME_M_E_Rsdl_HS',
 'STEAMING_TIME_M_E_Rsdl_ULS',
 'STEAMING_TIME_M_E_Dstlt_VLS',
 'STEAMING_TIME_M_E_Dstlt_ULS',
 'STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS',
 'STEAMING_TIME_M_E_HS',
 'STEAMING_TIME_M_E_LS',
 'STEAMING_TIME_M_E_MDO',
 'STEAMING_TIME_M_E_MGO',
 'STEAMING_TIME_M_E_MGO_LS',
 'STEAMING_TIME_AUX_1',
 'STEAMING_TIME_AUX_2',
 'STEAMING_TIME_AUX_3',
 'STEAMING_TIME_AUX_4',
 'STEAMING_TIME_AUX_5',
 'STEAMING_TIME_SH_GEN',
 'STEAMING_TIME_TG',
 'POWER_KW',
 'STEAMING_LOAD_KW_AUX_1',
 'STEAMING_LOAD_KW_AUX_2',
 'STEAMING_LOAD_KW_AUX_3',
 'STEAMING_LOAD_KW_AUX_4',
 'STEAMING_LOAD_KW_AUX_5',
 'STEAMING_LOAD_KW_SH_GEN',
 'STEAMING_LOAD_KW_TG',
 'FUEL_M_E_Rsdl_VLS',
 'FUEL_M_E_Rsdl_HS',
 'FUEL_M_E_Rsdl_ULS',
 'FUEL_M_E_Dstlt_VLS',
 'FUEL_M_E_Dstlt_ULS',
 'FUEL_M_E_Tnktnr_Dstlt_VLS',
 'FUEL_M_E_HS',
 'FUEL_M_E_LS',
 'FUEL_M_E_MDO',
 'FUEL_M_E_MGO',
 'FUEL_M_E_MGO_LS',
 'FUEL_Aux_Rsdl_VLS',
 'FUEL_Aux_Rsdl_HS',
 'FUEL_Aux_Rsdl_ULS',
 'FUEL_Aux_Dstlt_VLS',
 'FUEL_Aux_Dstlt_ULS',
 'FUEL_Aux_Tnktnr_Dstlt_VLS',
 'FUEL_AUX_HS',
 'FUEL_AUX_LS',
 'FUEL_AUX_MDO',
 'FUEL_AUX_MGO',
 'FUEL_AUX_MGO_LS',
 'FUEL_Boiler_Rsdl_VLS',
 'FUEL_Boiler_Rsdl_HS',
 'FUEL_Boiler_Rsdl_ULS',
 'FUEL_Boiler_Dstlt_VLS',
 'FUEL_Boiler_Dstlt_ULS',
 'FUEL_Boiler_Tnktnr_Dstlt_VLS',
 'FUEL_BOILER_HS',
 'FUEL_BOILER_LS',
 'FUEL_BOILER_MDO',
 'FUEL_BOILER_MGO',
 'FUEL_BOILER_MGO_LS',
 'DECK_LAST_CHANGE_USER',
 'ENGINE_LAST_CHANGE_USER',
 'DECK_PART_IS_COMPLETE',
 'ENGINE_PART_IS_COMPLETE',
 'SCAVENGE_PRESSURE',
 'SECA_ENTRY_TIME',
 'SECA_ENTRY_LAT',
 'SECA_ENTRY_LONG',
 'SECA_EXIT_TIME',
 'SECA_EXIT_LAT',
 'SECA_EXIT_LONG',
 'ROB_FRESH_WATER',
 'MANVRNG_MILES_BY_GPS',
 'MANVRNG_MILES_BY_SPEED_LOG',
 'TANKTAINER_TRANSFD_QUANTITY',
 'PILOT_TAKEN',
 'DATE_TIME_START_TRANSIT',
 'DATE_TIME_START_TRANSIT_Offset',
 'DATE_TIME_END_TRANSIT',
 'DATE_TIME_END_TRANSIT_Offset',
 'BALLAST',
 'TANKTAINER_NUMBER',
 'STEAMING_KWHR_TOTAL',
 'CY_OTHERS',
 'ROB_FO_SLUDGE',
 'ROB_LO_SLUDGE',
 'ROB_BILGE',
 'SLUDGE_REMOVED_FO',
 'SLUDGE_REMOVED_LO',
 'SEA_STATE',
 'CY_LUB_ADDED_TO_SYSTEM_MECC',
 'CY_LUB_ADDED_TO_SYSTEM_AECC',
 'CY_LUB_ADDED_TO_THRUSTERS',
 'CY_ME_LO_PURIFIER_IN_USE',
 'CY_BALLAST',
 'CY_BENDING_MOMENT',
 'CY_SHEARING_FORCE',
 'CY_TORTION_MOMENT',
 'CY_SUPDT_AUDITOR_SIGNED_ON',
 'CY_SUPDT_AUDITOR_SIGNED_OFF',
 'CY_CASH_RECEIVED',
 'CY_LUB_OIL_RECEIVED_MECYL',
 'CY_LUB_OIL_RECEIVED_MECC',
 'CY_LUB_OIL_RECEIVED_AECC',
 'CY_M_E_UNDER_PISTON_TEMP',
 'CY_MAIL_RECEIVED',
 'WIND_DIRECTION_PORT_STBD',
 'SEA_DIRECTION_PORT_STBD',
 'TIME_PILOT_ONBOARD',
 'GRADES_ROB',
 'SO2_CO2_RATIO',
 'Bunker_Order',
 'Remarks',
 'Fuel_Type',
 'Carbon_Factor',
 'Sulphur_Content_PC',
 'Quantity',
 'Port_Delivery',
 'Product_Quality',
 'Tanktainer_Number_1',
 'Supplier',
 'Delivery',
 'Vol_Lt',
 'Den',
 'Vis',
 'ROB_Dstlt_ULS',
 'ROB_Dstlt_VLS',
 'ROB_Rsdl_MDO',
 'ROB_Tnktnr_Dstlt_VLS',
 'ROB_Rsdl_VLS',
 'ROB_Rsdl_HS',
 'ROB_Rsdl_ULS',
 'ROB_Fuel_HSFO',
 'ROB_Fuel_LSFO',
 'ROB_Fuel_MDO',
 'ROB_Fuel_MGO',
 'ROB_Fuel_MGO_LS',
 'ROB_Fuel_Tanktainer_MGO',
 'ECA_MILES',
 'ECA_TIME',
 'EGCS_DRY_WASTE_REMOVED',
 'EGCS_RUNNING_TIME',
 'EGCS_WET_SLURRY_REMOVED',
 'EGCS_OPEN_LOOP_RUNNING_TIME',
 'EGCS_CLOSED_LOOP_RUNNING_TIME',
 'FUEL_M_E_LNG',
 'FUEL_Aux_LNG',
 'FUEL_Boiler_LNG',
 'ROB_Rsdl_LNG',
 'Max_Residual_HS_capacity',
 'Max_Lng_capacity',
 'Min_Lng_request',
 'Tanktainer_min_request',
 'Comments',
 'Template_version',
 'Pilot_date/time',
 'PIER_date/time',
 'Hold_ventilation_off',
 'Rob_tot_Sludge',
 'Reefer_power_consumption',
 'Tanktainer_distillates_transfd',
 'Hold_Ventilation_On/Off',
 'Tot_sludge_removed',
 'Garbage_cat_a_-_plastic_removed',
 'Garbage_cat_b_-_organic_removed',
 'Garbage_cat_c_-_domestic_removed',
 'Garbage_cat_e_-_ashes_removed',
 'Rob_garbage_cat_a_-_plastic',
 'Rob_garbage_cat_b_-_organic',
 'Rob_garbage_cat_c_-_domestic',
 'Rob_garbage_cat_e_-_ashes',
 'Kwhr_total',
 'Sludge_rob',
 'Sludge_min_discharge_request',
 'Rob_actual_sludge',
 'Qty_sludge_disposed',
 nan]

In [31]:
weekcol = charter.columns.tolist()
weekcol

['GID',
 'IMO No',
 'VSL',
 'Report Type',
 'Corrected Date',
 'REPORT DATE TIME',
 'LAT',
 'LONG',
 'CARGO TOTAL',
 'CARGO TOTAL TEU',
 'DRAFT AFT',
 'DRAFT FWD',
 'SPEED BY GPS',
 'SPEED BY LOG',
 'FUEL Aux Tnktnr Dstlt VLS',
 'FUEL Aux LNG',
 'FUEL Aux Rsdl HS',
 'FUEL Aux Rsdl ULS',
 'FUEL Aux Rsdl VLS',
 'FUEL Boiler Tnktnr Dstlt VLS',
 'FUEL Boiler LNG',
 'FUEL Boiler Rsdl HS',
 'FUEL Boiler Rsdl ULS',
 'FUEL Boiler Rsdl VLS',
 'FUEL M E Tnktnr Dstlt VLS',
 'FUEL M E LNG',
 'FUEL M E Rsdl HS',
 'FUEL M E Rsdl ULS',
 'FUEL M E Rsdl VLS',
 'STEAMING TIME AUX 1',
 'STEAMING TIME AUX 2',
 'STEAMING TIME AUX 3',
 'STEAMING TIME AUX 4',
 'STEAMING TIME AUX 5',
 'Total M E Hours Fuel Only',
 'STEAMING TIME SH GEN',
 'STEAMING TIME TG',
 'STEAMING LOAD KW AUX 1',
 'STEAMING LOAD KW AUX 2',
 'STEAMING LOAD KW AUX 3',
 'STEAMING LOAD KW AUX 4',
 'STEAMING LOAD KW AUX 5',
 'POWER KW',
 'STEAMING LOAD KW SH GEN',
 'STEAMING LOAD KW TG',
 'ROB Tnktnr Dstlt VLS',
 'ROB Rsdl LNG',
 'ROB Rsdl HS',
 'ROB Rsdl ULS',
 'ROB Rsdl VLS',
 'Max Residual HS capacity',
 'Max Lng capacity',
 'Min Lng request',
 'Tanktainer Number_1',
 'Tanktainer min request',
 'Template version',
 'Port Delivery',
 'TANKTAINER ROB',
 'Comments',
 'Fuel Type',
 'Supplier',
 'Vol Lt',
 'Quantity',
 'Den',
 'Vis',
 'Sulphur Content PC',
 'Bunker Order',
 'PORT CODE',
 'PORT',
 'Pilot date/time',
 'PIER date/time',
 'TIME MANOEUVRING',
 'DISPLACEMENT',
 'ETD DATE TIME',
 'TANKTAINER NUMBER',
 'MANVRNG MILES BY GPS',
 'MANVRNG MILES BY SPEED LOG',
 'Kwhr total',
 'Hold ventilation off',
 'REEFERS POSITIVE PLUGGED',
 'REEFERS NEGATIVE PLUGGED',
 'ME TOTAL REVS COUNTER',
 'ROB FRESH WATER',
 'EGCS RUNNING TIME',
 'SO2 CO2 RATIO',
 'Rob tot Sludge',
 'BALLAST',
 'EGCS CLOSED LOOP RUNNING TIME',
 'EGCS OPEN LOOP RUNNING TIME',
 'Reefer power consumption',
 'Rob Ajustment HS',
 'Rob Adjustment VLS',
 'Rob Adjustment ULS',
 'Rob Adjustment Dist',
 'Rob Adjustment LNG',
 'Drydock2',
 'Rob Tanktainer adjustment',
 'WIND DIRECTION',
 'MILES BY GPS',
 'STEAMING TIME M/E RESIDUAL HS',
 'RPM',
 'SLIP',
 'ETA PORT CODE',
 'ETA PORT',
 'ETA DATE TIME',
 'WIND SPEED',
 'COURSE AT SEA',
 'WAVE HEIGHT',
 'SEA STATE',
 'AMBIENT TEMP',
 'SW TEMP',
 'MILES BY SPEED LOG',
 'REQUESTED SPEED',
 'TIME CHANGE',
 'TIME SEA',
 'kwhr total',
 'SCAVENGE PRESSURE',
 'SEA DIRECTION',
 'ECA MILES',
 'ECA TIME',
 'Steaming time m/e lng',
 'Drydock',
 'TEU FULL',
 'TEU EMPTY',
 'FW SUPPLY',
 'Tanktainer distillates transfd',
 'Hold Ventilation On/Off',
 'BILGE REMOVED',
 'Tot sludge removed',
 'Garbage cat a - plastic removed',
 'Garbage cat b - organic removed',
 'Garbage cat c - domestic removed',
 'Garbage cat e - ashes removed',
 'Rob garbage cat a - plastic',
 'Rob garbage cat b - organic',
 'Rob garbage cat c - domestic',
 'Rob garbage cat e - ashes',
 'EGCS WET SLURRY REMOVED',
 'EGCS DRY WASTE REMOVED',
 'Total Number of pax on board',
 'Total Number of vehicles on board',
 'TYPE OF DELAY',
 'REASON',
 'TIME HRS ANCHOR',
 'TIME HRS DRIFT',
 'Eta date/time',
 'Sludge rob',
 'Sludge min discharge request',
 'OIL CYL',
 'DryDock',
 'ETB DATE TIME',
 'STEAMING TIME M E Rsdl HS',
 'STEAMING TIME M E Rsdl ULS',
 'STEAMING TIME M E Rsdl VLS',
 'Rpm',
 'SHIFT BERTH HOURS',
 'ROB fresh water',
 'Rob actual sludge',
 'ROB BILGE',
 'Qty sludge disposed',
 'VOY',
 'Status',
 'M E FOC',
 'Has Cargo',
 'ETA DATE TIME Offset',
 'TEMP MIN',
 'TEMP MAX',
 'REM DIST TO PILOT',
 'REM TIME TO PILOT',
 'TOTAL UNPLND STPGE TECH',
 'TOTAL UNPLND STPGE OPE WX',
 'AUX BLOWERS ON',
 'HOLD VENTILATION ON',
 'ETB DATE TIME Offset',
 'PILOT DATE TIME',
 'PILOT DATE TIME Offset',
 'TUG ARR',
 'TUG SHIFT',
 'ETD DATE TIME Offset',
 'CARGO LOAD',
 'CARGO DISCH',
 'GARBAGE REMOVED',
 'GARBAGE REMVL REQSTD',
 'GARBAGE REMVL CMPLSRY',
 'CY CREW SIGNED ON',
 'CY CREW SIGNED OFF',
 'CY DOCTORS VISIT',
 'CY MAIL RECEIVED Ref NO',
 'CY LUB OIL SAMPLE LANDED',
 'CY CHECKD FOR STOWAWAYS',
 'CY STOWAWAYS ON BOARD',
 'CY DEP GM Mtr',
 'CY REQUISITIONS RECEIVED',
 'DISTANCE TO NEXT PILOT',
 'TUG SAILING TRANSIT',
 'STEAMING TIME M E Tnktnr Dstlt VLS',
 'FUEL M E MDO',
 'FUEL Aux MDO',
 'FUEL Boiler MDO',
 'DECK LAST CHANGE USER',
 'ENGINE LAST CHANGE USER',
 'DECK PART IS COMPLETE',
 'ENGINE PART IS COMPLETE',
 'SECA ENTRY TIME',
 'SECA ENTRY LAT',
 'SECA ENTRY LONG',
 'SECA EXIT TIME',
 'SECA EXIT LAT',
 'SECA EXIT LONG',
 'TANKTAINER TRANSFD QUANTITY',
 'PILOT TAKEN',
 'DATE TIME START TRANSIT',
 'DATE TIME START TRANSIT Offset',
 'DATE TIME END TRANSIT',
 'DATE TIME END TRANSIT Offset',
 'STEAMING KWHR TOTAL',
 'CY OTHERS',
 'ROB FO SLUDGE',
 'ROB LO SLUDGE',
 'SLUDGE REMOVED FO',
 'SLUDGE REMOVED LO',
 'CY LUB ADDED TO SYSTEM MECC',
 'CY LUB ADDED TO SYSTEM AECC',
 'CY LUB ADDED TO THRUSTERS',
 'CY ME LO PURIFIER IN USE',
 'CY BALLAST',
 'CY BENDING MOMENT',
 'CY SHEARING FORCE',
 'CY TORTION MOMENT',
 'CY SUPDT AUDITOR SIGNED ON',
 'CY SUPDT AUDITOR SIGNED OFF',
 'CY CASH RECEIVED',
 'CY LUB OIL RECEIVED MECYL',
 'CY LUB OIL RECEIVED MECC',
 'CY LUB OIL RECEIVED AECC',
 'CY M E UNDER PISTON TEMP',
 'CY MAIL RECEIVED',
 'WIND DIRECTION PORT STBD',
 'SEA DIRECTION PORT STBD',
 'TIME PILOT ONBOARD',
 'GRADES ROB',
 'Remarks',
 'Carbon Factor',
 'Product Quality',
 'Delivery',
 'ROB Rsdl MDO',
 'STEAMING TIME M E Dstlt ULS',
 'STEAMING TIME M E Dstlt VLS',
 'FUEL M E Dstlt VLS',
 'FUEL M E Dstlt ULS',
 'FUEL Aux Dstlt VLS',
 'FUEL Aux Dstlt ULS',
 'FUEL Boiler Dstlt VLS',
 'FUEL Boiler Dstlt ULS',
 'ROB Dstlt VLS',
 'ROB Dstlt ULS',
 'STEAMING TIME M E HS',
 'STEAMING TIME M E LS',
 'STEAMING TIME M E MGO',
 'STEAMING TIME M E MGO LS',
 'FUEL M E HS',
 'FUEL M E LS',
 'FUEL M E MGO',
 'FUEL M E MGO LS',
 'FUEL Aux HS',
 'FUEL Aux LS',
 'FUEL Aux MGO',
 'FUEL Aux MGO LS',
 'FUEL Boiler HS',
 'FUEL Boiler LS',
 'FUEL Boiler MGO',
 'FUEL Boiler MGO LS',
 'ROB FUEL HSFO',
 'ROB FUEL LSFO',
 'ROB FUEL MDO',
 'ROB FUEL MGO',
 'ROB FUEL MGO LS',
 'ROB FUEL Tanktainer MGO',
 'SINCE_DATE_TIME',
 'SINCE_DATE_TIME_Offset']

In [33]:
#correct column names as per noon Updated calculations in DB for updated fuel type file - charter data
#main difference is _,so replace all space as _
charter.columns = charter.columns.str.replace(' ','_')

In [35]:
charter['REPORT_DATE_TIME_Offset'] = 'UTC' + charter['REPORT_DATE_TIME'].str[-6:]

In [37]:
charter.columns.tolist()

['GID',
 'IMO_No',
 'VSL',
 'Report_Type',
 'Corrected_Date',
 'REPORT_DATE_TIME',
 'LAT',
 'LONG',
 'CARGO_TOTAL',
 'CARGO_TOTAL_TEU',
 'DRAFT_AFT',
 'DRAFT_FWD',
 'SPEED_BY_GPS',
 'SPEED_BY_LOG',
 'FUEL_Aux_Tnktnr_Dstlt_VLS',
 'FUEL_Aux_LNG',
 'FUEL_Aux_Rsdl_HS',
 'FUEL_Aux_Rsdl_ULS',
 'FUEL_Aux_Rsdl_VLS',
 'FUEL_Boiler_Tnktnr_Dstlt_VLS',
 'FUEL_Boiler_LNG',
 'FUEL_Boiler_Rsdl_HS',
 'FUEL_Boiler_Rsdl_ULS',
 'FUEL_Boiler_Rsdl_VLS',
 'FUEL_M_E_Tnktnr_Dstlt_VLS',
 'FUEL_M_E_LNG',
 'FUEL_M_E_Rsdl_HS',
 'FUEL_M_E_Rsdl_ULS',
 'FUEL_M_E_Rsdl_VLS',
 'STEAMING_TIME_AUX_1',
 'STEAMING_TIME_AUX_2',
 'STEAMING_TIME_AUX_3',
 'STEAMING_TIME_AUX_4',
 'STEAMING_TIME_AUX_5',
 'Total_M_E_Hours_Fuel_Only',
 'STEAMING_TIME_SH_GEN',
 'STEAMING_TIME_TG',
 'STEAMING_LOAD_KW_AUX_1',
 'STEAMING_LOAD_KW_AUX_2',
 'STEAMING_LOAD_KW_AUX_3',
 'STEAMING_LOAD_KW_AUX_4',
 'STEAMING_LOAD_KW_AUX_5',
 'POWER_KW',
 'STEAMING_LOAD_KW_SH_GEN',
 'STEAMING_LOAD_KW_TG',
 'ROB_Tnktnr_Dstlt_VLS',
 'ROB_Rsdl_LNG',
 'ROB_Rsdl_HS',
 'ROB_Rsdl_ULS',
 'ROB_Rsdl_VLS',
 'Max_Residual_HS_capacity',
 'Max_Lng_capacity',
 'Min_Lng_request',
 'Tanktainer_Number_1',
 'Tanktainer_min_request',
 'Template_version',
 'Port_Delivery',
 'TANKTAINER_ROB',
 'Comments',
 'Fuel_Type',
 'Supplier',
 'Vol_Lt',
 'Quantity',
 'Den',
 'Vis',
 'Sulphur_Content_PC',
 'Bunker_Order',
 'PORT_CODE',
 'PORT',
 'Pilot_date/time',
 'PIER_date/time',
 'TIME_MANOEUVRING',
 'DISPLACEMENT',
 'ETD_DATE_TIME',
 'TANKTAINER_NUMBER',
 'MANVRNG_MILES_BY_GPS',
 'MANVRNG_MILES_BY_SPEED_LOG',
 'Kwhr_total',
 'Hold_ventilation_off',
 'REEFERS_POSITIVE_PLUGGED',
 'REEFERS_NEGATIVE_PLUGGED',
 'ME_TOTAL_REVS_COUNTER',
 'ROB_FRESH_WATER',
 'EGCS_RUNNING_TIME',
 'SO2_CO2_RATIO',
 'Rob_tot_Sludge',
 'BALLAST',
 'EGCS_CLOSED_LOOP_RUNNING_TIME',
 'EGCS_OPEN_LOOP_RUNNING_TIME',
 'Reefer_power_consumption',
 'Rob_Ajustment_HS',
 'Rob_Adjustment_VLS',
 'Rob_Adjustment_ULS',
 'Rob_Adjustment_Dist',
 'Rob_Adjustment_LNG',
 'Drydock2',
 'Rob_Tanktainer_adjustment',
 'WIND_DIRECTION',
 'MILES_BY_GPS',
 'STEAMING_TIME_M/E_RESIDUAL_HS',
 'RPM',
 'SLIP',
 'ETA_PORT_CODE',
 'ETA_PORT',
 'ETA_DATE_TIME',
 'WIND_SPEED',
 'COURSE_AT_SEA',
 'WAVE_HEIGHT',
 'SEA_STATE',
 'AMBIENT_TEMP',
 'SW_TEMP',
 'MILES_BY_SPEED_LOG',
 'REQUESTED_SPEED',
 'TIME_CHANGE',
 'TIME_SEA',
 'kwhr_total',
 'SCAVENGE_PRESSURE',
 'SEA_DIRECTION',
 'ECA_MILES',
 'ECA_TIME',
 'Steaming_time_m/e_lng',
 'Drydock',
 'TEU_FULL',
 'TEU_EMPTY',
 'FW_SUPPLY',
 'Tanktainer_distillates_transfd',
 'Hold_Ventilation_On/Off',
 'BILGE_REMOVED',
 'Tot_sludge_removed',
 'Garbage_cat_a_-_plastic_removed',
 'Garbage_cat_b_-_organic_removed',
 'Garbage_cat_c_-_domestic_removed',
 'Garbage_cat_e_-_ashes_removed',
 'Rob_garbage_cat_a_-_plastic',
 'Rob_garbage_cat_b_-_organic',
 'Rob_garbage_cat_c_-_domestic',
 'Rob_garbage_cat_e_-_ashes',
 'EGCS_WET_SLURRY_REMOVED',
 'EGCS_DRY_WASTE_REMOVED',
 'Total_Number_of_pax_on_board',
 'Total_Number_of_vehicles_on_board',
 'TYPE_OF_DELAY',
 'REASON',
 'TIME_HRS_ANCHOR',
 'TIME_HRS_DRIFT',
 'Eta_date/time',
 'Sludge_rob',
 'Sludge_min_discharge_request',
 'OIL_CYL',
 'DryDock',
 'ETB_DATE_TIME',
 'STEAMING_TIME_M_E_Rsdl_HS',
 'STEAMING_TIME_M_E_Rsdl_ULS',
 'STEAMING_TIME_M_E_Rsdl_VLS',
 'Rpm',
 'SHIFT_BERTH_HOURS',
 'ROB_fresh_water',
 'Rob_actual_sludge',
 'ROB_BILGE',
 'Qty_sludge_disposed',
 'VOY',
 'Status',
 'M_E_FOC',
 'Has_Cargo',
 'ETA_DATE_TIME_Offset',
 'TEMP_MIN',
 'TEMP_MAX',
 'REM_DIST_TO_PILOT',
 'REM_TIME_TO_PILOT',
 'TOTAL_UNPLND_STPGE_TECH',
 'TOTAL_UNPLND_STPGE_OPE_WX',
 'AUX_BLOWERS_ON',
 'HOLD_VENTILATION_ON',
 'ETB_DATE_TIME_Offset',
 'PILOT_DATE_TIME',
 'PILOT_DATE_TIME_Offset',
 'TUG_ARR',
 'TUG_SHIFT',
 'ETD_DATE_TIME_Offset',
 'CARGO_LOAD',
 'CARGO_DISCH',
 'GARBAGE_REMOVED',
 'GARBAGE_REMVL_REQSTD',
 'GARBAGE_REMVL_CMPLSRY',
 'CY_CREW_SIGNED_ON',
 'CY_CREW_SIGNED_OFF',
 'CY_DOCTORS_VISIT',
 'CY_MAIL_RECEIVED_Ref_NO',
 'CY_LUB_OIL_SAMPLE_LANDED',
 'CY_CHECKD_FOR_STOWAWAYS',
 'CY_STOWAWAYS_ON_BOARD',
 'CY_DEP_GM_Mtr',
 'CY_REQUISITIONS_RECEIVED',
 'DISTANCE_TO_NEXT_PILOT',
 'TUG_SAILING_TRANSIT',
 'STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS',
 'FUEL_M_E_MDO',
 'FUEL_Aux_MDO',
 'FUEL_Boiler_MDO',
 'DECK_LAST_CHANGE_USER',
 'ENGINE_LAST_CHANGE_USER',
 'DECK_PART_IS_COMPLETE',
 'ENGINE_PART_IS_COMPLETE',
 'SECA_ENTRY_TIME',
 'SECA_ENTRY_LAT',
 'SECA_ENTRY_LONG',
 'SECA_EXIT_TIME',
 'SECA_EXIT_LAT',
 'SECA_EXIT_LONG',
 'TANKTAINER_TRANSFD_QUANTITY',
 'PILOT_TAKEN',
 'DATE_TIME_START_TRANSIT',
 'DATE_TIME_START_TRANSIT_Offset',
 'DATE_TIME_END_TRANSIT',
 'DATE_TIME_END_TRANSIT_Offset',
 'STEAMING_KWHR_TOTAL',
 'CY_OTHERS',
 'ROB_FO_SLUDGE',
 'ROB_LO_SLUDGE',
 'SLUDGE_REMOVED_FO',
 'SLUDGE_REMOVED_LO',
 'CY_LUB_ADDED_TO_SYSTEM_MECC',
 'CY_LUB_ADDED_TO_SYSTEM_AECC',
 'CY_LUB_ADDED_TO_THRUSTERS',
 'CY_ME_LO_PURIFIER_IN_USE',
 'CY_BALLAST',
 'CY_BENDING_MOMENT',
 'CY_SHEARING_FORCE',
 'CY_TORTION_MOMENT',
 'CY_SUPDT_AUDITOR_SIGNED_ON',
 'CY_SUPDT_AUDITOR_SIGNED_OFF',
 'CY_CASH_RECEIVED',
 'CY_LUB_OIL_RECEIVED_MECYL',
 'CY_LUB_OIL_RECEIVED_MECC',
 'CY_LUB_OIL_RECEIVED_AECC',
 'CY_M_E_UNDER_PISTON_TEMP',
 'CY_MAIL_RECEIVED',
 'WIND_DIRECTION_PORT_STBD',
 'SEA_DIRECTION_PORT_STBD',
 'TIME_PILOT_ONBOARD',
 'GRADES_ROB',
 'Remarks',
 'Carbon_Factor',
 'Product_Quality',
 'Delivery',
 'ROB_Rsdl_MDO',
 'STEAMING_TIME_M_E_Dstlt_ULS',
 'STEAMING_TIME_M_E_Dstlt_VLS',
 'FUEL_M_E_Dstlt_VLS',
 'FUEL_M_E_Dstlt_ULS',
 'FUEL_Aux_Dstlt_VLS',
 'FUEL_Aux_Dstlt_ULS',
 'FUEL_Boiler_Dstlt_VLS',
 'FUEL_Boiler_Dstlt_ULS',
 'ROB_Dstlt_VLS',
 'ROB_Dstlt_ULS',
 'STEAMING_TIME_M_E_HS',
 'STEAMING_TIME_M_E_LS',
 'STEAMING_TIME_M_E_MGO',
 'STEAMING_TIME_M_E_MGO_LS',
 'FUEL_M_E_HS',
 'FUEL_M_E_LS',
 'FUEL_M_E_MGO',
 'FUEL_M_E_MGO_LS',
 'FUEL_Aux_HS',
 'FUEL_Aux_LS',
 'FUEL_Aux_MGO',
 'FUEL_Aux_MGO_LS',
 'FUEL_Boiler_HS',
 'FUEL_Boiler_LS',
 'FUEL_Boiler_MGO',
 'FUEL_Boiler_MGO_LS',
 'ROB_FUEL_HSFO',
 'ROB_FUEL_LSFO',
 'ROB_FUEL_MDO',
 'ROB_FUEL_MGO',
 'ROB_FUEL_MGO_LS',
 'ROB_FUEL_Tanktainer_MGO',
 'SINCE_DATE_TIME',
 'SINCE_DATE_TIME_Offset',
 'REPORT_DATE_TIME_Offset']

In [39]:
col_lst

['GID',
 'VSL',
 'IMO_No',
 'VOY',
 'Corrected_Date',
 'REPORT_DATE_TIME',
 'REPORT_DATE_TIME_Offset',
 'Report_Type',
 'Status',
 'LAT',
 'LONG_',
 'M_E_FOC',
 'CARGO_TOTAL',
 'Has_Cargo',
 'STEAMING_TIME',
 'Total_M_E_Hours_Fuel_Only',
 'MILES_BY_GPS',
 'OIL_CYL',
 'SPEED_BY_LOG',
 'SPEED_BY_GPS',
 'RPM',
 'SLIP',
 'WIND_DIRECTION',
 'WIND_SPEED',
 'DRAFT_AFT',
 'DRAFT_FWD',
 'DISPLACEMENT',
 'COURSE_AT_SEA',
 'WAVE_HEIGHT',
 'SEA_DIRECTION',
 'CARGO_TOTAL_TEU',
 'AMBIENT_TEMP',
 'SW_TEMP',
 'MILES_BY_SPEED_LOG',
 'ETA_PORT_CODE',
 'ETA_DATE_TIME',
 'ETA_DATE_TIME_Offset',
 'ETA_PORT',
 'TIME_CHANGE',
 'TIME_SEA',
 'TEMP_MIN',
 'TEMP_MAX',
 'REQUESTED_SPEED',
 'REM_DIST_TO_PILOT',
 'REM_TIME_TO_PILOT',
 'TOTAL_UNPLND_STPGE_TECH',
 'TOTAL_UNPLND_STPGE_OPE_WX',
 'REEFERS_POSITIVE_PLUGGED',
 'REEFERS_NEGATIVE_PLUGGED',
 'ME_TOTAL_REVS_COUNTER',
 'PORT_CODE',
 'PORT',
 'AUX_BLOWERS_ON',
 'HOLD_VENTILATION_ON',
 'SINCE_DATE_TIME',
 'SINCE_DATE_TIME_Offset',
 'TIME_HRS_ANCHOR',
 'TIME_HRS_DRIFT',
 'REASON',
 'TYPE_OF_DELAY',
 'ETB_DATE_TIME',
 'ETB_DATE_TIME_Offset',
 'PILOT_DATE_TIME',
 'PILOT_DATE_TIME_Offset',
 'TIME_MANOEUVRING',
 'TUG_ARR',
 'TUG_SHIFT',
 'ETD_DATE_TIME',
 'ETD_DATE_TIME_Offset',
 'SHIFT_BERTH_HOURS',
 'CARGO_LOAD',
 'CARGO_DISCH',
 'TEU_FULL',
 'TEU_EMPTY',
 'BILGE_REMOVED',
 'GARBAGE_REMOVED',
 'GARBAGE_REMVL_REQSTD',
 'GARBAGE_REMVL_CMPLSRY',
 'FW_SUPPLY',
 'CY_CREW_SIGNED_ON',
 'CY_CREW_SIGNED_OFF',
 'CY_DOCTORS_VISIT',
 'CY_MAIL_RECEIVED_Ref_NO',
 'CY_LUB_OIL_SAMPLE_LANDED',
 'CY_CHECKD_FOR_STOWAWAYS',
 'CY_STOWAWAYS_ON_BOARD',
 'CY_DEP_GM_Mtr',
 'CY_REQUISITIONS_RECEIVED',
 'DISTANCE_TO_NEXT_PILOT',
 'TUG_SAILING_TRANSIT',
 'STEAMING_TIME_M_E_Rsdl_VLS',
 'STEAMING_TIME_M_E_Rsdl_HS',
 'STEAMING_TIME_M_E_Rsdl_ULS',
 'STEAMING_TIME_M_E_Dstlt_VLS',
 'STEAMING_TIME_M_E_Dstlt_ULS',
 'STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS',
 'STEAMING_TIME_M_E_HS',
 'STEAMING_TIME_M_E_LS',
 'STEAMING_TIME_M_E_MDO',
 'STEAMING_TIME_M_E_MGO',
 'STEAMING_TIME_M_E_MGO_LS',
 'STEAMING_TIME_AUX_1',
 'STEAMING_TIME_AUX_2',
 'STEAMING_TIME_AUX_3',
 'STEAMING_TIME_AUX_4',
 'STEAMING_TIME_AUX_5',
 'STEAMING_TIME_SH_GEN',
 'STEAMING_TIME_TG',
 'POWER_KW',
 'STEAMING_LOAD_KW_AUX_1',
 'STEAMING_LOAD_KW_AUX_2',
 'STEAMING_LOAD_KW_AUX_3',
 'STEAMING_LOAD_KW_AUX_4',
 'STEAMING_LOAD_KW_AUX_5',
 'STEAMING_LOAD_KW_SH_GEN',
 'STEAMING_LOAD_KW_TG',
 'FUEL_M_E_Rsdl_VLS',
 'FUEL_M_E_Rsdl_HS',
 'FUEL_M_E_Rsdl_ULS',
 'FUEL_M_E_Dstlt_VLS',
 'FUEL_M_E_Dstlt_ULS',
 'FUEL_M_E_Tnktnr_Dstlt_VLS',
 'FUEL_M_E_HS',
 'FUEL_M_E_LS',
 'FUEL_M_E_MDO',
 'FUEL_M_E_MGO',
 'FUEL_M_E_MGO_LS',
 'FUEL_Aux_Rsdl_VLS',
 'FUEL_Aux_Rsdl_HS',
 'FUEL_Aux_Rsdl_ULS',
 'FUEL_Aux_Dstlt_VLS',
 'FUEL_Aux_Dstlt_ULS',
 'FUEL_Aux_Tnktnr_Dstlt_VLS',
 'FUEL_AUX_HS',
 'FUEL_AUX_LS',
 'FUEL_AUX_MDO',
 'FUEL_AUX_MGO',
 'FUEL_AUX_MGO_LS',
 'FUEL_Boiler_Rsdl_VLS',
 'FUEL_Boiler_Rsdl_HS',
 'FUEL_Boiler_Rsdl_ULS',
 'FUEL_Boiler_Dstlt_VLS',
 'FUEL_Boiler_Dstlt_ULS',
 'FUEL_Boiler_Tnktnr_Dstlt_VLS',
 'FUEL_BOILER_HS',
 'FUEL_BOILER_LS',
 'FUEL_BOILER_MDO',
 'FUEL_BOILER_MGO',
 'FUEL_BOILER_MGO_LS',
 'DECK_LAST_CHANGE_USER',
 'ENGINE_LAST_CHANGE_USER',
 'DECK_PART_IS_COMPLETE',
 'ENGINE_PART_IS_COMPLETE',
 'SCAVENGE_PRESSURE',
 'SECA_ENTRY_TIME',
 'SECA_ENTRY_LAT',
 'SECA_ENTRY_LONG',
 'SECA_EXIT_TIME',
 'SECA_EXIT_LAT',
 'SECA_EXIT_LONG',
 'ROB_FRESH_WATER',
 'MANVRNG_MILES_BY_GPS',
 'MANVRNG_MILES_BY_SPEED_LOG',
 'TANKTAINER_TRANSFD_QUANTITY',
 'PILOT_TAKEN',
 'DATE_TIME_START_TRANSIT',
 'DATE_TIME_START_TRANSIT_Offset',
 'DATE_TIME_END_TRANSIT',
 'DATE_TIME_END_TRANSIT_Offset',
 'BALLAST',
 'TANKTAINER_NUMBER',
 'STEAMING_KWHR_TOTAL',
 'CY_OTHERS',
 'ROB_FO_SLUDGE',
 'ROB_LO_SLUDGE',
 'ROB_BILGE',
 'SLUDGE_REMOVED_FO',
 'SLUDGE_REMOVED_LO',
 'SEA_STATE',
 'CY_LUB_ADDED_TO_SYSTEM_MECC',
 'CY_LUB_ADDED_TO_SYSTEM_AECC',
 'CY_LUB_ADDED_TO_THRUSTERS',
 'CY_ME_LO_PURIFIER_IN_USE',
 'CY_BALLAST',
 'CY_BENDING_MOMENT',
 'CY_SHEARING_FORCE',
 'CY_TORTION_MOMENT',
 'CY_SUPDT_AUDITOR_SIGNED_ON',
 'CY_SUPDT_AUDITOR_SIGNED_OFF',
 'CY_CASH_RECEIVED',
 'CY_LUB_OIL_RECEIVED_MECYL',
 'CY_LUB_OIL_RECEIVED_MECC',
 'CY_LUB_OIL_RECEIVED_AECC',
 'CY_M_E_UNDER_PISTON_TEMP',
 'CY_MAIL_RECEIVED',
 'WIND_DIRECTION_PORT_STBD',
 'SEA_DIRECTION_PORT_STBD',
 'TIME_PILOT_ONBOARD',
 'GRADES_ROB',
 'SO2_CO2_RATIO',
 'Bunker_Order',
 'Remarks',
 'Fuel_Type',
 'Carbon_Factor',
 'Sulphur_Content_PC',
 'Quantity',
 'Port_Delivery',
 'Product_Quality',
 'Tanktainer_Number_1',
 'Supplier',
 'Delivery',
 'Vol_Lt',
 'Den',
 'Vis',
 'ROB_Dstlt_ULS',
 'ROB_Dstlt_VLS',
 'ROB_Rsdl_MDO',
 'ROB_Tnktnr_Dstlt_VLS',
 'ROB_Rsdl_VLS',
 'ROB_Rsdl_HS',
 'ROB_Rsdl_ULS',
 'ROB_Fuel_HSFO',
 'ROB_Fuel_LSFO',
 'ROB_Fuel_MDO',
 'ROB_Fuel_MGO',
 'ROB_Fuel_MGO_LS',
 'ROB_Fuel_Tanktainer_MGO',
 'ECA_MILES',
 'ECA_TIME',
 'EGCS_DRY_WASTE_REMOVED',
 'EGCS_RUNNING_TIME',
 'EGCS_WET_SLURRY_REMOVED',
 'EGCS_OPEN_LOOP_RUNNING_TIME',
 'EGCS_CLOSED_LOOP_RUNNING_TIME',
 'FUEL_M_E_LNG',
 'FUEL_Aux_LNG',
 'FUEL_Boiler_LNG',
 'ROB_Rsdl_LNG',
 'Max_Residual_HS_capacity',
 'Max_Lng_capacity',
 'Min_Lng_request',
 'Tanktainer_min_request',
 'Comments',
 'Template_version',
 'Pilot_date/time',
 'PIER_date/time',
 'Hold_ventilation_off',
 'Rob_tot_Sludge',
 'Reefer_power_consumption',
 'Tanktainer_distillates_transfd',
 'Hold_Ventilation_On/Off',
 'Tot_sludge_removed',
 'Garbage_cat_a_-_plastic_removed',
 'Garbage_cat_b_-_organic_removed',
 'Garbage_cat_c_-_domestic_removed',
 'Garbage_cat_e_-_ashes_removed',
 'Rob_garbage_cat_a_-_plastic',
 'Rob_garbage_cat_b_-_organic',
 'Rob_garbage_cat_c_-_domestic',
 'Rob_garbage_cat_e_-_ashes',
 'Kwhr_total',
 'Sludge_rob',
 'Sludge_min_discharge_request',
 'Rob_actual_sludge',
 'Qty_sludge_disposed',
 nan]

In [40]:
weekcol = charter.columns.tolist()
weekcol

['GID',
 'IMO_No',
 'VSL',
 'Report_Type',
 'Corrected_Date',
 'REPORT_DATE_TIME',
 'LAT',
 'LONG',
 'CARGO_TOTAL',
 'CARGO_TOTAL_TEU',
 'DRAFT_AFT',
 'DRAFT_FWD',
 'SPEED_BY_GPS',
 'SPEED_BY_LOG',
 'FUEL_Aux_Tnktnr_Dstlt_VLS',
 'FUEL_Aux_LNG',
 'FUEL_Aux_Rsdl_HS',
 'FUEL_Aux_Rsdl_ULS',
 'FUEL_Aux_Rsdl_VLS',
 'FUEL_Boiler_Tnktnr_Dstlt_VLS',
 'FUEL_Boiler_LNG',
 'FUEL_Boiler_Rsdl_HS',
 'FUEL_Boiler_Rsdl_ULS',
 'FUEL_Boiler_Rsdl_VLS',
 'FUEL_M_E_Tnktnr_Dstlt_VLS',
 'FUEL_M_E_LNG',
 'FUEL_M_E_Rsdl_HS',
 'FUEL_M_E_Rsdl_ULS',
 'FUEL_M_E_Rsdl_VLS',
 'STEAMING_TIME_AUX_1',
 'STEAMING_TIME_AUX_2',
 'STEAMING_TIME_AUX_3',
 'STEAMING_TIME_AUX_4',
 'STEAMING_TIME_AUX_5',
 'Total_M_E_Hours_Fuel_Only',
 'STEAMING_TIME_SH_GEN',
 'STEAMING_TIME_TG',
 'STEAMING_LOAD_KW_AUX_1',
 'STEAMING_LOAD_KW_AUX_2',
 'STEAMING_LOAD_KW_AUX_3',
 'STEAMING_LOAD_KW_AUX_4',
 'STEAMING_LOAD_KW_AUX_5',
 'POWER_KW',
 'STEAMING_LOAD_KW_SH_GEN',
 'STEAMING_LOAD_KW_TG',
 'ROB_Tnktnr_Dstlt_VLS',
 'ROB_Rsdl_LNG',
 'ROB_Rsdl_HS',
 'ROB_Rsdl_ULS',
 'ROB_Rsdl_VLS',
 'Max_Residual_HS_capacity',
 'Max_Lng_capacity',
 'Min_Lng_request',
 'Tanktainer_Number_1',
 'Tanktainer_min_request',
 'Template_version',
 'Port_Delivery',
 'TANKTAINER_ROB',
 'Comments',
 'Fuel_Type',
 'Supplier',
 'Vol_Lt',
 'Quantity',
 'Den',
 'Vis',
 'Sulphur_Content_PC',
 'Bunker_Order',
 'PORT_CODE',
 'PORT',
 'Pilot_date/time',
 'PIER_date/time',
 'TIME_MANOEUVRING',
 'DISPLACEMENT',
 'ETD_DATE_TIME',
 'TANKTAINER_NUMBER',
 'MANVRNG_MILES_BY_GPS',
 'MANVRNG_MILES_BY_SPEED_LOG',
 'Kwhr_total',
 'Hold_ventilation_off',
 'REEFERS_POSITIVE_PLUGGED',
 'REEFERS_NEGATIVE_PLUGGED',
 'ME_TOTAL_REVS_COUNTER',
 'ROB_FRESH_WATER',
 'EGCS_RUNNING_TIME',
 'SO2_CO2_RATIO',
 'Rob_tot_Sludge',
 'BALLAST',
 'EGCS_CLOSED_LOOP_RUNNING_TIME',
 'EGCS_OPEN_LOOP_RUNNING_TIME',
 'Reefer_power_consumption',
 'Rob_Ajustment_HS',
 'Rob_Adjustment_VLS',
 'Rob_Adjustment_ULS',
 'Rob_Adjustment_Dist',
 'Rob_Adjustment_LNG',
 'Drydock2',
 'Rob_Tanktainer_adjustment',
 'WIND_DIRECTION',
 'MILES_BY_GPS',
 'STEAMING_TIME_M/E_RESIDUAL_HS',
 'RPM',
 'SLIP',
 'ETA_PORT_CODE',
 'ETA_PORT',
 'ETA_DATE_TIME',
 'WIND_SPEED',
 'COURSE_AT_SEA',
 'WAVE_HEIGHT',
 'SEA_STATE',
 'AMBIENT_TEMP',
 'SW_TEMP',
 'MILES_BY_SPEED_LOG',
 'REQUESTED_SPEED',
 'TIME_CHANGE',
 'TIME_SEA',
 'kwhr_total',
 'SCAVENGE_PRESSURE',
 'SEA_DIRECTION',
 'ECA_MILES',
 'ECA_TIME',
 'Steaming_time_m/e_lng',
 'Drydock',
 'TEU_FULL',
 'TEU_EMPTY',
 'FW_SUPPLY',
 'Tanktainer_distillates_transfd',
 'Hold_Ventilation_On/Off',
 'BILGE_REMOVED',
 'Tot_sludge_removed',
 'Garbage_cat_a_-_plastic_removed',
 'Garbage_cat_b_-_organic_removed',
 'Garbage_cat_c_-_domestic_removed',
 'Garbage_cat_e_-_ashes_removed',
 'Rob_garbage_cat_a_-_plastic',
 'Rob_garbage_cat_b_-_organic',
 'Rob_garbage_cat_c_-_domestic',
 'Rob_garbage_cat_e_-_ashes',
 'EGCS_WET_SLURRY_REMOVED',
 'EGCS_DRY_WASTE_REMOVED',
 'Total_Number_of_pax_on_board',
 'Total_Number_of_vehicles_on_board',
 'TYPE_OF_DELAY',
 'REASON',
 'TIME_HRS_ANCHOR',
 'TIME_HRS_DRIFT',
 'Eta_date/time',
 'Sludge_rob',
 'Sludge_min_discharge_request',
 'OIL_CYL',
 'DryDock',
 'ETB_DATE_TIME',
 'STEAMING_TIME_M_E_Rsdl_HS',
 'STEAMING_TIME_M_E_Rsdl_ULS',
 'STEAMING_TIME_M_E_Rsdl_VLS',
 'Rpm',
 'SHIFT_BERTH_HOURS',
 'ROB_fresh_water',
 'Rob_actual_sludge',
 'ROB_BILGE',
 'Qty_sludge_disposed',
 'VOY',
 'Status',
 'M_E_FOC',
 'Has_Cargo',
 'ETA_DATE_TIME_Offset',
 'TEMP_MIN',
 'TEMP_MAX',
 'REM_DIST_TO_PILOT',
 'REM_TIME_TO_PILOT',
 'TOTAL_UNPLND_STPGE_TECH',
 'TOTAL_UNPLND_STPGE_OPE_WX',
 'AUX_BLOWERS_ON',
 'HOLD_VENTILATION_ON',
 'ETB_DATE_TIME_Offset',
 'PILOT_DATE_TIME',
 'PILOT_DATE_TIME_Offset',
 'TUG_ARR',
 'TUG_SHIFT',
 'ETD_DATE_TIME_Offset',
 'CARGO_LOAD',
 'CARGO_DISCH',
 'GARBAGE_REMOVED',
 'GARBAGE_REMVL_REQSTD',
 'GARBAGE_REMVL_CMPLSRY',
 'CY_CREW_SIGNED_ON',
 'CY_CREW_SIGNED_OFF',
 'CY_DOCTORS_VISIT',
 'CY_MAIL_RECEIVED_Ref_NO',
 'CY_LUB_OIL_SAMPLE_LANDED',
 'CY_CHECKD_FOR_STOWAWAYS',
 'CY_STOWAWAYS_ON_BOARD',
 'CY_DEP_GM_Mtr',
 'CY_REQUISITIONS_RECEIVED',
 'DISTANCE_TO_NEXT_PILOT',
 'TUG_SAILING_TRANSIT',
 'STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS',
 'FUEL_M_E_MDO',
 'FUEL_Aux_MDO',
 'FUEL_Boiler_MDO',
 'DECK_LAST_CHANGE_USER',
 'ENGINE_LAST_CHANGE_USER',
 'DECK_PART_IS_COMPLETE',
 'ENGINE_PART_IS_COMPLETE',
 'SECA_ENTRY_TIME',
 'SECA_ENTRY_LAT',
 'SECA_ENTRY_LONG',
 'SECA_EXIT_TIME',
 'SECA_EXIT_LAT',
 'SECA_EXIT_LONG',
 'TANKTAINER_TRANSFD_QUANTITY',
 'PILOT_TAKEN',
 'DATE_TIME_START_TRANSIT',
 'DATE_TIME_START_TRANSIT_Offset',
 'DATE_TIME_END_TRANSIT',
 'DATE_TIME_END_TRANSIT_Offset',
 'STEAMING_KWHR_TOTAL',
 'CY_OTHERS',
 'ROB_FO_SLUDGE',
 'ROB_LO_SLUDGE',
 'SLUDGE_REMOVED_FO',
 'SLUDGE_REMOVED_LO',
 'CY_LUB_ADDED_TO_SYSTEM_MECC',
 'CY_LUB_ADDED_TO_SYSTEM_AECC',
 'CY_LUB_ADDED_TO_THRUSTERS',
 'CY_ME_LO_PURIFIER_IN_USE',
 'CY_BALLAST',
 'CY_BENDING_MOMENT',
 'CY_SHEARING_FORCE',
 'CY_TORTION_MOMENT',
 'CY_SUPDT_AUDITOR_SIGNED_ON',
 'CY_SUPDT_AUDITOR_SIGNED_OFF',
 'CY_CASH_RECEIVED',
 'CY_LUB_OIL_RECEIVED_MECYL',
 'CY_LUB_OIL_RECEIVED_MECC',
 'CY_LUB_OIL_RECEIVED_AECC',
 'CY_M_E_UNDER_PISTON_TEMP',
 'CY_MAIL_RECEIVED',
 'WIND_DIRECTION_PORT_STBD',
 'SEA_DIRECTION_PORT_STBD',
 'TIME_PILOT_ONBOARD',
 'GRADES_ROB',
 'Remarks',
 'Carbon_Factor',
 'Product_Quality',
 'Delivery',
 'ROB_Rsdl_MDO',
 'STEAMING_TIME_M_E_Dstlt_ULS',
 'STEAMING_TIME_M_E_Dstlt_VLS',
 'FUEL_M_E_Dstlt_VLS',
 'FUEL_M_E_Dstlt_ULS',
 'FUEL_Aux_Dstlt_VLS',
 'FUEL_Aux_Dstlt_ULS',
 'FUEL_Boiler_Dstlt_VLS',
 'FUEL_Boiler_Dstlt_ULS',
 'ROB_Dstlt_VLS',
 'ROB_Dstlt_ULS',
 'STEAMING_TIME_M_E_HS',
 'STEAMING_TIME_M_E_LS',
 'STEAMING_TIME_M_E_MGO',
 'STEAMING_TIME_M_E_MGO_LS',
 'FUEL_M_E_HS',
 'FUEL_M_E_LS',
 'FUEL_M_E_MGO',
 'FUEL_M_E_MGO_LS',
 'FUEL_Aux_HS',
 'FUEL_Aux_LS',
 'FUEL_Aux_MGO',
 'FUEL_Aux_MGO_LS',
 'FUEL_Boiler_HS',
 'FUEL_Boiler_LS',
 'FUEL_Boiler_MGO',
 'FUEL_Boiler_MGO_LS',
 'ROB_FUEL_HSFO',
 'ROB_FUEL_LSFO',
 'ROB_FUEL_MDO',
 'ROB_FUEL_MGO',
 'ROB_FUEL_MGO_LS',
 'ROB_FUEL_Tanktainer_MGO',
 'SINCE_DATE_TIME',
 'SINCE_DATE_TIME_Offset',
 'REPORT_DATE_TIME_Offset']

In [43]:
charter.rename(columns = {'LONG':'LONG_','FUEL_Aux_MDO':'FUEL_AUX_MDO','FUEL_Boiler_MDO':'FUEL_BOILER_MDO','FUEL_Aux_HS':'FUEL_AUX_HS','FUEL_Aux_LS':'FUEL_AUX_LS','FUEL_Aux_MGO':'FUEL_AUX_MGO','FUEL_Aux_MGO_LS':'FUEL_AUX_MGO_LS','FUEL_Boiler_HS':'FUEL_BOILER_HS','FUEL_Boiler_LS':'FUEL_BOILER_LS','FUEL_Boiler_MGO':'FUEL_BOILER_MGO','FUEL_Boiler_MGO_LS':'FUEL_BOILER_MGO_LS','ROB_FUEL_HSFO':'ROB_Fuel_HSFO','ROB_FUEL_LSFO':'ROB_Fuel_LSFO','ROB_FUEL_MDO':'ROB_Fuel_MDO','ROB_FUEL_MGO':'ROB_Fuel_MGO','ROB_FUEL_MGO_LS':'ROB_Fuel_MGO_LS','ROB_FUEL_Tanktainer_MGO':'ROB_Fuel_Tanktainer_MGO'}, inplace = True)

In [45]:
weekcol = charter.columns.tolist()
weekcol

['GID',
 'IMO_No',
 'VSL',
 'Report_Type',
 'Corrected_Date',
 'REPORT_DATE_TIME',
 'LAT',
 'LONG_',
 'CARGO_TOTAL',
 'CARGO_TOTAL_TEU',
 'DRAFT_AFT',
 'DRAFT_FWD',
 'SPEED_BY_GPS',
 'SPEED_BY_LOG',
 'FUEL_Aux_Tnktnr_Dstlt_VLS',
 'FUEL_Aux_LNG',
 'FUEL_Aux_Rsdl_HS',
 'FUEL_Aux_Rsdl_ULS',
 'FUEL_Aux_Rsdl_VLS',
 'FUEL_Boiler_Tnktnr_Dstlt_VLS',
 'FUEL_Boiler_LNG',
 'FUEL_Boiler_Rsdl_HS',
 'FUEL_Boiler_Rsdl_ULS',
 'FUEL_Boiler_Rsdl_VLS',
 'FUEL_M_E_Tnktnr_Dstlt_VLS',
 'FUEL_M_E_LNG',
 'FUEL_M_E_Rsdl_HS',
 'FUEL_M_E_Rsdl_ULS',
 'FUEL_M_E_Rsdl_VLS',
 'STEAMING_TIME_AUX_1',
 'STEAMING_TIME_AUX_2',
 'STEAMING_TIME_AUX_3',
 'STEAMING_TIME_AUX_4',
 'STEAMING_TIME_AUX_5',
 'Total_M_E_Hours_Fuel_Only',
 'STEAMING_TIME_SH_GEN',
 'STEAMING_TIME_TG',
 'STEAMING_LOAD_KW_AUX_1',
 'STEAMING_LOAD_KW_AUX_2',
 'STEAMING_LOAD_KW_AUX_3',
 'STEAMING_LOAD_KW_AUX_4',
 'STEAMING_LOAD_KW_AUX_5',
 'POWER_KW',
 'STEAMING_LOAD_KW_SH_GEN',
 'STEAMING_LOAD_KW_TG',
 'ROB_Tnktnr_Dstlt_VLS',
 'ROB_Rsdl_LNG',
 'ROB_Rsdl_HS',
 'ROB_Rsdl_ULS',
 'ROB_Rsdl_VLS',
 'Max_Residual_HS_capacity',
 'Max_Lng_capacity',
 'Min_Lng_request',
 'Tanktainer_Number_1',
 'Tanktainer_min_request',
 'Template_version',
 'Port_Delivery',
 'TANKTAINER_ROB',
 'Comments',
 'Fuel_Type',
 'Supplier',
 'Vol_Lt',
 'Quantity',
 'Den',
 'Vis',
 'Sulphur_Content_PC',
 'Bunker_Order',
 'PORT_CODE',
 'PORT',
 'Pilot_date/time',
 'PIER_date/time',
 'TIME_MANOEUVRING',
 'DISPLACEMENT',
 'ETD_DATE_TIME',
 'TANKTAINER_NUMBER',
 'MANVRNG_MILES_BY_GPS',
 'MANVRNG_MILES_BY_SPEED_LOG',
 'Kwhr_total',
 'Hold_ventilation_off',
 'REEFERS_POSITIVE_PLUGGED',
 'REEFERS_NEGATIVE_PLUGGED',
 'ME_TOTAL_REVS_COUNTER',
 'ROB_FRESH_WATER',
 'EGCS_RUNNING_TIME',
 'SO2_CO2_RATIO',
 'Rob_tot_Sludge',
 'BALLAST',
 'EGCS_CLOSED_LOOP_RUNNING_TIME',
 'EGCS_OPEN_LOOP_RUNNING_TIME',
 'Reefer_power_consumption',
 'Rob_Ajustment_HS',
 'Rob_Adjustment_VLS',
 'Rob_Adjustment_ULS',
 'Rob_Adjustment_Dist',
 'Rob_Adjustment_LNG',
 'Drydock2',
 'Rob_Tanktainer_adjustment',
 'WIND_DIRECTION',
 'MILES_BY_GPS',
 'STEAMING_TIME_M/E_RESIDUAL_HS',
 'RPM',
 'SLIP',
 'ETA_PORT_CODE',
 'ETA_PORT',
 'ETA_DATE_TIME',
 'WIND_SPEED',
 'COURSE_AT_SEA',
 'WAVE_HEIGHT',
 'SEA_STATE',
 'AMBIENT_TEMP',
 'SW_TEMP',
 'MILES_BY_SPEED_LOG',
 'REQUESTED_SPEED',
 'TIME_CHANGE',
 'TIME_SEA',
 'kwhr_total',
 'SCAVENGE_PRESSURE',
 'SEA_DIRECTION',
 'ECA_MILES',
 'ECA_TIME',
 'Steaming_time_m/e_lng',
 'Drydock',
 'TEU_FULL',
 'TEU_EMPTY',
 'FW_SUPPLY',
 'Tanktainer_distillates_transfd',
 'Hold_Ventilation_On/Off',
 'BILGE_REMOVED',
 'Tot_sludge_removed',
 'Garbage_cat_a_-_plastic_removed',
 'Garbage_cat_b_-_organic_removed',
 'Garbage_cat_c_-_domestic_removed',
 'Garbage_cat_e_-_ashes_removed',
 'Rob_garbage_cat_a_-_plastic',
 'Rob_garbage_cat_b_-_organic',
 'Rob_garbage_cat_c_-_domestic',
 'Rob_garbage_cat_e_-_ashes',
 'EGCS_WET_SLURRY_REMOVED',
 'EGCS_DRY_WASTE_REMOVED',
 'Total_Number_of_pax_on_board',
 'Total_Number_of_vehicles_on_board',
 'TYPE_OF_DELAY',
 'REASON',
 'TIME_HRS_ANCHOR',
 'TIME_HRS_DRIFT',
 'Eta_date/time',
 'Sludge_rob',
 'Sludge_min_discharge_request',
 'OIL_CYL',
 'DryDock',
 'ETB_DATE_TIME',
 'STEAMING_TIME_M_E_Rsdl_HS',
 'STEAMING_TIME_M_E_Rsdl_ULS',
 'STEAMING_TIME_M_E_Rsdl_VLS',
 'Rpm',
 'SHIFT_BERTH_HOURS',
 'ROB_fresh_water',
 'Rob_actual_sludge',
 'ROB_BILGE',
 'Qty_sludge_disposed',
 'VOY',
 'Status',
 'M_E_FOC',
 'Has_Cargo',
 'ETA_DATE_TIME_Offset',
 'TEMP_MIN',
 'TEMP_MAX',
 'REM_DIST_TO_PILOT',
 'REM_TIME_TO_PILOT',
 'TOTAL_UNPLND_STPGE_TECH',
 'TOTAL_UNPLND_STPGE_OPE_WX',
 'AUX_BLOWERS_ON',
 'HOLD_VENTILATION_ON',
 'ETB_DATE_TIME_Offset',
 'PILOT_DATE_TIME',
 'PILOT_DATE_TIME_Offset',
 'TUG_ARR',
 'TUG_SHIFT',
 'ETD_DATE_TIME_Offset',
 'CARGO_LOAD',
 'CARGO_DISCH',
 'GARBAGE_REMOVED',
 'GARBAGE_REMVL_REQSTD',
 'GARBAGE_REMVL_CMPLSRY',
 'CY_CREW_SIGNED_ON',
 'CY_CREW_SIGNED_OFF',
 'CY_DOCTORS_VISIT',
 'CY_MAIL_RECEIVED_Ref_NO',
 'CY_LUB_OIL_SAMPLE_LANDED',
 'CY_CHECKD_FOR_STOWAWAYS',
 'CY_STOWAWAYS_ON_BOARD',
 'CY_DEP_GM_Mtr',
 'CY_REQUISITIONS_RECEIVED',
 'DISTANCE_TO_NEXT_PILOT',
 'TUG_SAILING_TRANSIT',
 'STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS',
 'FUEL_M_E_MDO',
 'FUEL_AUX_MDO',
 'FUEL_BOILER_MDO',
 'DECK_LAST_CHANGE_USER',
 'ENGINE_LAST_CHANGE_USER',
 'DECK_PART_IS_COMPLETE',
 'ENGINE_PART_IS_COMPLETE',
 'SECA_ENTRY_TIME',
 'SECA_ENTRY_LAT',
 'SECA_ENTRY_LONG',
 'SECA_EXIT_TIME',
 'SECA_EXIT_LAT',
 'SECA_EXIT_LONG',
 'TANKTAINER_TRANSFD_QUANTITY',
 'PILOT_TAKEN',
 'DATE_TIME_START_TRANSIT',
 'DATE_TIME_START_TRANSIT_Offset',
 'DATE_TIME_END_TRANSIT',
 'DATE_TIME_END_TRANSIT_Offset',
 'STEAMING_KWHR_TOTAL',
 'CY_OTHERS',
 'ROB_FO_SLUDGE',
 'ROB_LO_SLUDGE',
 'SLUDGE_REMOVED_FO',
 'SLUDGE_REMOVED_LO',
 'CY_LUB_ADDED_TO_SYSTEM_MECC',
 'CY_LUB_ADDED_TO_SYSTEM_AECC',
 'CY_LUB_ADDED_TO_THRUSTERS',
 'CY_ME_LO_PURIFIER_IN_USE',
 'CY_BALLAST',
 'CY_BENDING_MOMENT',
 'CY_SHEARING_FORCE',
 'CY_TORTION_MOMENT',
 'CY_SUPDT_AUDITOR_SIGNED_ON',
 'CY_SUPDT_AUDITOR_SIGNED_OFF',
 'CY_CASH_RECEIVED',
 'CY_LUB_OIL_RECEIVED_MECYL',
 'CY_LUB_OIL_RECEIVED_MECC',
 'CY_LUB_OIL_RECEIVED_AECC',
 'CY_M_E_UNDER_PISTON_TEMP',
 'CY_MAIL_RECEIVED',
 'WIND_DIRECTION_PORT_STBD',
 'SEA_DIRECTION_PORT_STBD',
 'TIME_PILOT_ONBOARD',
 'GRADES_ROB',
 'Remarks',
 'Carbon_Factor',
 'Product_Quality',
 'Delivery',
 'ROB_Rsdl_MDO',
 'STEAMING_TIME_M_E_Dstlt_ULS',
 'STEAMING_TIME_M_E_Dstlt_VLS',
 'FUEL_M_E_Dstlt_VLS',
 'FUEL_M_E_Dstlt_ULS',
 'FUEL_Aux_Dstlt_VLS',
 'FUEL_Aux_Dstlt_ULS',
 'FUEL_Boiler_Dstlt_VLS',
 'FUEL_Boiler_Dstlt_ULS',
 'ROB_Dstlt_VLS',
 'ROB_Dstlt_ULS',
 'STEAMING_TIME_M_E_HS',
 'STEAMING_TIME_M_E_LS',
 'STEAMING_TIME_M_E_MGO',
 'STEAMING_TIME_M_E_MGO_LS',
 'FUEL_M_E_HS',
 'FUEL_M_E_LS',
 'FUEL_M_E_MGO',
 'FUEL_M_E_MGO_LS',
 'FUEL_AUX_HS',
 'FUEL_AUX_LS',
 'FUEL_AUX_MGO',
 'FUEL_AUX_MGO_LS',
 'FUEL_BOILER_HS',
 'FUEL_BOILER_LS',
 'FUEL_BOILER_MGO',
 'FUEL_BOILER_MGO_LS',
 'ROB_Fuel_HSFO',
 'ROB_Fuel_LSFO',
 'ROB_Fuel_MDO',
 'ROB_Fuel_MGO',
 'ROB_Fuel_MGO_LS',
 'ROB_Fuel_Tanktainer_MGO',
 'SINCE_DATE_TIME',
 'SINCE_DATE_TIME_Offset',
 'REPORT_DATE_TIME_Offset']

In [47]:
temp3 = []
for element in weekcol:
    if element not in col_lst:
        temp3.append(element)

temp3

['TANKTAINER_ROB',
 'Rob_Ajustment_HS',
 'Rob_Adjustment_VLS',
 'Rob_Adjustment_ULS',
 'Rob_Adjustment_Dist',
 'Rob_Adjustment_LNG',
 'Drydock2',
 'Rob_Tanktainer_adjustment',
 'STEAMING_TIME_M/E_RESIDUAL_HS',
 'kwhr_total',
 'Steaming_time_m/e_lng',
 'Drydock',
 'Total_Number_of_pax_on_board',
 'Total_Number_of_vehicles_on_board',
 'Eta_date/time',
 'DryDock',
 'Rpm',
 'ROB_fresh_water']

In [49]:
temp4 = []
for element in col_lst:
    if element not in weekcol:
        temp4.append(element)

temp4

['STEAMING_TIME', 'STEAMING_TIME_M_E_MDO', nan]

In [ ]:
# List of columns to remove
columns_to_remove = [
    'M_E_Fuel_Only_Steaming_Time',
    'TANKTAINER_ROB',
    'Rob_Ajustment_HS',
    'Rob_Adjustment_VLS',
    'Rob_Adjustment_ULS',
    'Rob_Adjustment_Dist',
    'Rob_Adjustment_LNG',
    'Drydock2',
    'Rob_Tanktainer_adjustment',
    'STEAMING_TIME_M/E_RESIDUAL_HS',
    'kwhr_total',
    'Steaming_time_m/e_lng',
    'Drydock',
    'Eta_date/time',
    'DryDock',
    'Rpm',
    'ROB_fresh_water'
]

# Drop the columns from the DataFrame
charter = charter.drop(columns=columns_to_remove, errors='ignore')

In [ ]:
charter[temp4] = np.nan
charter

In [ ]:
columns_to_fill_zero = ['FUEL_M_E_LNG', 'FUEL_Aux_LNG', 'FUEL_Boiler_LNG', 'ROB_Rsdl_LNG']

charter[columns_to_fill_zero] = charter[columns_to_fill_zero].fillna(0)
charter

In [ ]:
import re
def replace_special_characters(value):
    if isinstance(value, str):
        # Replace all the special characters with underscores
        value = re.sub(r'[,\;\!\/\\\;\'\"\@\#\$\%\^\(\)]', '_', value)
    return value

charter = charter.applymap(replace_special_characters)
charter

In [ ]:
charter[charter.apply(lambda x: x.str.contains(',|;').any(), axis=1)]

In [ ]:
#corrected_date,report_date_time column format change to yyyy-mm-dd-hh:mm:ss
charter[['Corrected_Date','REPORT_DATE_TIME']]

In [ ]:
import pandas as pd

def get_corrected_date(report_date_time, offset_str):
    # Convert 'REPORT DATE TIME' to datetime
    report_date_time = pd.to_datetime(report_date_time, errors='coerce')
    
    # Extract hours and minutes from the offset
    sign = offset_str[3]  # '+' or '-'
    hours = int(offset_str[4:6])
    minutes = int(offset_str[7:9])
    
    # Adjust the offset: '+' means subtract, '-' means add
    offset = pd.Timedelta(hours=hours, minutes=minutes * (1 if sign == '+' else -1))
    
    # Calculate the corrected date
    corrected_datetime = report_date_time - offset  # Subtract for '+' and add for '-'
    
    # Return only the date part
    return corrected_datetime.date()



# Apply the function to calculate the corrected date
charter['Corrected_Date'] = charter.apply(lambda row: get_corrected_date(row['REPORT_DATE_TIME'], row['REPORT_DATE_TIME_Offset']), axis=1)

In [ ]:
charter['Corrected_Date'] = pd.to_datetime(charter['Corrected_Date'], format='%y/%m/%d %H:%M:%S').dt.strftime('%Y-%m-%d %H:%M:%S')
charter['Corrected_Date']

In [ ]:
charter['REPORT_DATE_TIME'] = charter['REPORT_DATE_TIME'].str.replace(r'\s+\+\d{2}:\d{2}$', '', regex=True)  # For positive timezone
charter['REPORT_DATE_TIME'] = charter['REPORT_DATE_TIME'].str.replace(r'\s+-\d{2}:\d{2}$', '', regex=True)  # For negative timezone

# Remove any leading or trailing whitespace
charter['REPORT_DATE_TIME'] = charter['REPORT_DATE_TIME'].str.strip()

# Convert back to datetime
charter['REPORT_DATE_TIME'] = pd.to_datetime(charter['REPORT_DATE_TIME'])

charter

In [ ]:
charter[['Corrected_Date','REPORT_DATE_TIME']]

In [ ]:
charterfinal = charter[['GID',
 'VSL',
 'IMO_No',
 'VOY',
 'Corrected_Date',
 'REPORT_DATE_TIME',
 'REPORT_DATE_TIME_Offset',
 'Report_Type',
 'Status',
 'LAT',
 'LONG_',
 'M_E_FOC',
 'CARGO_TOTAL',
 'Has_Cargo',
 'STEAMING_TIME',
 'Total_M_E_Hours_Fuel_Only',
 'MILES_BY_GPS',
 'OIL_CYL',
 'SPEED_BY_LOG',
 'SPEED_BY_GPS',
 'RPM',
 'SLIP',
 'WIND_DIRECTION',
 'WIND_SPEED',
 'DRAFT_AFT',
 'DRAFT_FWD',
 'DISPLACEMENT',
 'COURSE_AT_SEA',
 'WAVE_HEIGHT',
 'SEA_DIRECTION',
 'CARGO_TOTAL_TEU',
 'AMBIENT_TEMP',
 'SW_TEMP',
 'MILES_BY_SPEED_LOG',
 'ETA_PORT_CODE',
 'ETA_DATE_TIME',
 'ETA_DATE_TIME_Offset',
 'ETA_PORT',
 'TIME_CHANGE',
 'TIME_SEA',
 'TEMP_MIN',
 'TEMP_MAX',
 'REQUESTED_SPEED',
 'REM_DIST_TO_PILOT',
 'REM_TIME_TO_PILOT',
 'TOTAL_UNPLND_STPGE_TECH',
 'TOTAL_UNPLND_STPGE_OPE_WX',
 'REEFERS_POSITIVE_PLUGGED',
 'REEFERS_NEGATIVE_PLUGGED',
 'ME_TOTAL_REVS_COUNTER',
 'PORT_CODE',
 'PORT',
 'AUX_BLOWERS_ON',
 'HOLD_VENTILATION_ON',
 'SINCE_DATE_TIME',
 'SINCE_DATE_TIME_Offset',
 'TIME_HRS_ANCHOR',
 'TIME_HRS_DRIFT',
 'REASON',
 'TYPE_OF_DELAY',
 'ETB_DATE_TIME',
 'ETB_DATE_TIME_Offset',
 'PILOT_DATE_TIME',
 'PILOT_DATE_TIME_Offset',
 'TIME_MANOEUVRING',
 'TUG_ARR',
 'TUG_SHIFT',
 'ETD_DATE_TIME',
 'ETD_DATE_TIME_Offset',
 'SHIFT_BERTH_HOURS',
 'CARGO_LOAD',
 'CARGO_DISCH',
 'TEU_FULL',
 'TEU_EMPTY',
 'BILGE_REMOVED',
 'GARBAGE_REMOVED',
 'GARBAGE_REMVL_REQSTD',
 'GARBAGE_REMVL_CMPLSRY',
 'FW_SUPPLY',
 'CY_CREW_SIGNED_ON',
 'CY_CREW_SIGNED_OFF',
 'CY_DOCTORS_VISIT',
 'CY_MAIL_RECEIVED_Ref_NO',
 'CY_LUB_OIL_SAMPLE_LANDED',
 'CY_CHECKD_FOR_STOWAWAYS',
 'CY_STOWAWAYS_ON_BOARD',
 'CY_DEP_GM_Mtr',
 'CY_REQUISITIONS_RECEIVED',
 'DISTANCE_TO_NEXT_PILOT',
 'TUG_SAILING_TRANSIT',
 'STEAMING_TIME_M_E_Rsdl_VLS',
 'STEAMING_TIME_M_E_Rsdl_HS',
 'STEAMING_TIME_M_E_Rsdl_ULS',
 'STEAMING_TIME_M_E_Dstlt_VLS',
 'STEAMING_TIME_M_E_Dstlt_ULS',
 'STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS',
 'STEAMING_TIME_M_E_HS',
 'STEAMING_TIME_M_E_LS',
 'STEAMING_TIME_M_E_MDO',
 'STEAMING_TIME_M_E_MGO',
 'STEAMING_TIME_M_E_MGO_LS',
 'STEAMING_TIME_AUX_1',
 'STEAMING_TIME_AUX_2',
 'STEAMING_TIME_AUX_3',
 'STEAMING_TIME_AUX_4',
 'STEAMING_TIME_AUX_5',
 'STEAMING_TIME_SH_GEN',
 'STEAMING_TIME_TG',
 'POWER_KW',
 'STEAMING_LOAD_KW_AUX_1',
 'STEAMING_LOAD_KW_AUX_2',
 'STEAMING_LOAD_KW_AUX_3',
 'STEAMING_LOAD_KW_AUX_4',
 'STEAMING_LOAD_KW_AUX_5',
 'STEAMING_LOAD_KW_SH_GEN',
 'STEAMING_LOAD_KW_TG',
 'FUEL_M_E_Rsdl_VLS',
 'FUEL_M_E_Rsdl_HS',
 'FUEL_M_E_Rsdl_ULS',
 'FUEL_M_E_Dstlt_VLS',
 'FUEL_M_E_Dstlt_ULS',
 'FUEL_M_E_Tnktnr_Dstlt_VLS',
 'FUEL_M_E_HS',
 'FUEL_M_E_LS',
 'FUEL_M_E_MDO',
 'FUEL_M_E_MGO',
 'FUEL_M_E_MGO_LS',
 'FUEL_Aux_Rsdl_VLS',
 'FUEL_Aux_Rsdl_HS',
 'FUEL_Aux_Rsdl_ULS',
 'FUEL_Aux_Dstlt_VLS',
 'FUEL_Aux_Dstlt_ULS',
 'FUEL_Aux_Tnktnr_Dstlt_VLS',
 'FUEL_AUX_HS',
 'FUEL_AUX_LS',
 'FUEL_AUX_MDO',
 'FUEL_AUX_MGO',
 'FUEL_AUX_MGO_LS',
 'FUEL_Boiler_Rsdl_VLS',
 'FUEL_Boiler_Rsdl_HS',
 'FUEL_Boiler_Rsdl_ULS',
 'FUEL_Boiler_Dstlt_VLS',
 'FUEL_Boiler_Dstlt_ULS',
 'FUEL_Boiler_Tnktnr_Dstlt_VLS',
 'FUEL_BOILER_HS',
 'FUEL_BOILER_LS',
 'FUEL_BOILER_MDO',
 'FUEL_BOILER_MGO',
 'FUEL_BOILER_MGO_LS',
 'DECK_LAST_CHANGE_USER',
 'ENGINE_LAST_CHANGE_USER',
 'DECK_PART_IS_COMPLETE',
 'ENGINE_PART_IS_COMPLETE',
 'SCAVENGE_PRESSURE',
 'SECA_ENTRY_TIME',
 'SECA_ENTRY_LAT',
 'SECA_ENTRY_LONG',
 'SECA_EXIT_TIME',
 'SECA_EXIT_LAT',
 'SECA_EXIT_LONG',
 'ROB_FRESH_WATER',
 'MANVRNG_MILES_BY_GPS',
 'MANVRNG_MILES_BY_SPEED_LOG',
 'TANKTAINER_TRANSFD_QUANTITY',
 'PILOT_TAKEN',
 'DATE_TIME_START_TRANSIT',
 'DATE_TIME_START_TRANSIT_Offset',
 'DATE_TIME_END_TRANSIT',
 'DATE_TIME_END_TRANSIT_Offset',
 'BALLAST',
 'TANKTAINER_NUMBER',
 'STEAMING_KWHR_TOTAL',
 'CY_OTHERS',
 'ROB_FO_SLUDGE',
 'ROB_LO_SLUDGE',
 'ROB_BILGE',
 'SLUDGE_REMOVED_FO',
 'SLUDGE_REMOVED_LO',
 'SEA_STATE',
 'CY_LUB_ADDED_TO_SYSTEM_MECC',
 'CY_LUB_ADDED_TO_SYSTEM_AECC',
 'CY_LUB_ADDED_TO_THRUSTERS',
 'CY_ME_LO_PURIFIER_IN_USE',
 'CY_BALLAST',
 'CY_BENDING_MOMENT',
 'CY_SHEARING_FORCE',
 'CY_TORTION_MOMENT',
 'CY_SUPDT_AUDITOR_SIGNED_ON',
 'CY_SUPDT_AUDITOR_SIGNED_OFF',
 'CY_CASH_RECEIVED',
 'CY_LUB_OIL_RECEIVED_MECYL',
 'CY_LUB_OIL_RECEIVED_MECC',
 'CY_LUB_OIL_RECEIVED_AECC',
 'CY_M_E_UNDER_PISTON_TEMP',
 'CY_MAIL_RECEIVED',
 'WIND_DIRECTION_PORT_STBD',
 'SEA_DIRECTION_PORT_STBD',
 'TIME_PILOT_ONBOARD',
 'GRADES_ROB',
 'SO2_CO2_RATIO',
 'Bunker_Order',
 'Remarks',
 'Fuel_Type',
 'Carbon_Factor',
 'Sulphur_Content_PC',
 'Quantity',
 'Port_Delivery',
 'Product_Quality',
 'Tanktainer_Number_1',
 'Supplier',
 'Delivery',
 'Vol_Lt',
 'Den',
 'Vis',
 'ROB_Dstlt_ULS',
 'ROB_Dstlt_VLS',
 'ROB_Rsdl_MDO',
 'ROB_Tnktnr_Dstlt_VLS',
 'ROB_Rsdl_VLS',
 'ROB_Rsdl_HS',
 'ROB_Rsdl_ULS',
 'ROB_Fuel_HSFO',
 'ROB_Fuel_LSFO',
 'ROB_Fuel_MDO',
 'ROB_Fuel_MGO',
 'ROB_Fuel_MGO_LS',
 'ROB_Fuel_Tanktainer_MGO',
 'ECA_MILES',
 'ECA_TIME',
 'EGCS_DRY_WASTE_REMOVED',
 'EGCS_RUNNING_TIME',
 'EGCS_WET_SLURRY_REMOVED',
 'EGCS_OPEN_LOOP_RUNNING_TIME',
 'EGCS_CLOSED_LOOP_RUNNING_TIME',
 'FUEL_M_E_LNG','FUEL_Aux_LNG','FUEL_Boiler_LNG','ROB_Rsdl_LNG']]
charterfinal

In [ ]:
charterfinal.to_csv(r"D:\Navalt\MSC\2024\Weekly Data\CHARTER\NOON\DB\CSV\charter_noondata_dec_2024.csv",index=False)

In [ ]:
charterfinal.to_csv(r"D:\Navalt\MSC\2024\Weekly Data\CHARTER\NOON\DB\EXCEL\charter_noondata_dec_2024.csv",index=False)

In [ ]:

charter_nov  = pd.read_csv(r"D:\Navalt\MSC\2024\Weekly Data\CHARTER\NOON\DB\CSV\charter_noondata_dec_2024.csv")
charter_data = pd.read_csv(r"C:\Users\akshaya\Downloads\Charter_data_.csv",)

filtered_charter_nov = charter_nov[~charter_nov['GID'].isin(charter_data['gid'])]

# Save the filtered DataFrame to a new CSV file
filtered_charter_nov.to_csv('filtered_charter_nov.csv', index=False)

print("Filtered file saved as 'filtered_charter_nov.csv'.")