In [10]:
import pandas as pd
import numpy as np
from datetime import datetime

In [11]:
noondata=pd.read_csv(r'D:\Navalt\MSC\2024\ESI\Group A\JAN24 TO JUN24\NOONDATA\Noon_data_Jan_Jun_2024.csv')

C:\Users\akshaya\AppData\Local\Temp\ipykernel_193460\14219066.py:1: DtypeWarning: Columns (74,79,80,81,82,83,84,85,86,87,89,166,168,178,183,184,195,204,215) have mixed types. Specify dtype option on import or set low_memory=False.
  noondata=pd.read_csv(r'C:\Users\akshaya\Downloads\charter data 2024_.csv')

#server noon data from jan to june
data = pd.read_csv(r"C:\Users\akshaya\Downloads\charter (2).csv")
data

In [12]:
noondata['imo'].nunique()

840

In [13]:
noondata.columns.to_list()

['id',
 'gid',
 'vessel_name',
 'imo',
 'voy',
 'corrected_date',
 'report_date_time',
 'report_date_time_offset',
 'report_type',
 'status',
 'latitude',
 'longitude',
 'm_e_foc',
 'cargo_total',
 'has_cargo',
 'steaming_time',
 'total_m_e_hours_fuel_only',
 'miles_by_gps',
 'oil_cyl',
 'speed_by_log',
 'speed_by_gps',
 'rpm',
 'slip',
 'wind_direction',
 'wind_speed',
 'draft_aft',
 'draft_fwd',
 'displacement',
 'course_at_sea',
 'wave_height',
 'sea_direction',
 'cargo_total_teu',
 'ambient_temp',
 'sw_temp',
 'miles_by_speed_log',
 'eta_port_code',
 'eta_date_time',
 'eta_date_time_offset',
 'eta_port',
 'time_change',
 'time_sea',
 'temp_min',
 'temp_max',
 'requested_speed',
 'rem_dist_to_pilot',
 'rem_time_to_pilot',
 'total_unplnd_stpge_tech',
 'total_unplnd_stpge_ope_wx',
 'reefers_positive_plugged',
 'reefers_negative_plugged',
 'me_total_revs_counter',
 'port_code',
 'port',
 'aux_blowers_on',
 'hold_ventilation_on',
 'since_date_time',
 'since_date_time_offset',
 'time_hrs_anchor',
 'time_hrs_drift',
 'reason',
 'type_of_delay',
 'etb_date_time',
 'etb_date_time_offset',
 'pilot_date_time',
 'pilot_date_time_offset',
 'time_manoeuvring',
 'tug_arr',
 'tug_shift',
 'etd_date_time',
 'etd_date_time_offset',
 'shift_berth_hours',
 'cargo_disch',
 'teu_full',
 'teu_empty',
 'bilge_removed',
 'garbage_removed',
 'garbage_remvl_reqstd',
 'garbage_remvl_cmplsry',
 'fw_supply',
 'cy_crew_signed_on',
 'cy_crew_signed_off',
 'cy_doctors_visit',
 'cy_mail_received_ref_no',
 'cy_lub_oil_sample_landed',
 'cy_checkd_for_stowaways',
 'cy_stowaways_on_board',
 'cy_dep_gm_mtr',
 'cy_requisitions_received',
 'distance_to_next_pilot',
 'tug_sailing_transit',
 'steaming_time_m_e_rsdl_vls',
 'steaming_time_m_e_rsdl_hs',
 'steaming_time_m_e_rsdl_uls',
 'steaming_time_m_e_dstlt_vls',
 'steaming_time_m_e_dstlt_uls',
 'steaming_time_m_e_tnktnr_dstlt_vls',
 'steaming_time_m_e_hs',
 'steaming_time_m_e_ls',
 'steaming_time_m_e_mdo',
 'steaming_time_m_e_mgo',
 'steaming_time_m_e_mgo_ls',
 'steaming_time_aux_1',
 'steaming_time_aux_2',
 'steaming_time_aux_3',
 'steaming_time_aux_4',
 'steaming_time_aux_5',
 'steaming_time_sh_gen',
 'steaming_time_tg',
 'power_kw',
 'steaming_load_kw_aux_1',
 'steaming_load_kw_aux_2',
 'steaming_load_kw_aux_3',
 'steaming_load_kw_aux_4',
 'steaming_load_kw_aux_5',
 'steaming_load_kw_sh_gen',
 'steaming_load_kw_tg',
 'fuel_m_e_rsdl_vls',
 'fuel_m_e_rsdl_hs',
 'fuel_m_e_rsdl_uls',
 'fuel_m_e_dstlt_vls',
 'fuel_m_e_dstlt_uls',
 'fuel_m_e_tnktnr_dstlt_vls',
 'fuel_m_e_hs',
 'fuel_m_e_ls',
 'fuel_m_e_mdo',
 'fuel_m_e_mgo',
 'fuel_m_e_mgo_ls',
 'fuel_aux_rsdl_vls',
 'fuel_aux_rsdl_hs',
 'fuel_aux_rsdl_uls',
 'fuel_aux_dstlt_vls',
 'fuel_aux_dstlt_uls',
 'fuel_aux_tnktnr_dstlt_vls',
 'fuel_aux_hs',
 'fuel_aux_ls',
 'fuel_aux_mdo',
 'fuel_aux_mgo',
 'fuel_aux_mgo_ls',
 'fuel_boiler_rsdl_vls',
 'fuel_boiler_rsdl_hs',
 'fuel_boiler_rsdl_uls',
 'fuel_boiler_dstlt_vls',
 'fuel_boiler_dstlt_uls',
 'fuel_boiler_tnktnr_dstlt_vls',
 'fuel_boiler_hs',
 'fuel_boiler_ls',
 'fuel_boiler_mdo',
 'fuel_boiler_mgo',
 'fuel_boiler_mgo_ls',
 'deck_last_change_user',
 'deck_part_is_complete',
 'engine_part_is_complete',
 'scavenge_pressure',
 'seca_entry_time',
 'seca_entry_lat',
 'seca_entry_long',
 'rob_fresh_water',
 'manvrng_miles_by_gps',
 'manvrng_miles_by_speed_log',
 'tanktainer_transfd_quantity',
 'pilot_taken',
 'date_time_start_transit',
 'date_time_start_transit_offset',
 'date_time_end_transit',
 'date_time_end_transit_offset',
 'ballast',
 'tanktainer_number',
 'steaming_kwhr_total',
 'cy_others',
 'rob_fo_sludge',
 'rob_lo_sludge',
 'rob_bilge',
 'sludge_removed_fo',
 'sludge_removed_lo',
 'sea_state',
 'cy_lub_added_to_system_mecc',
 'cy_lub_added_to_system_aecc',
 'cy_lub_added_to_thrusters',
 'cy_me_lo_purifier_in_use',
 'cy_ballast',
 'cy_bending_moment',
 'cy_shearing_force',
 'cy_tortion_moment',
 'cy_supdt_auditor_signed_on',
 'cy_supdt_auditor_signed_off',
 'cy_cash_received',
 'cy_lub_oil_received_mecyl',
 'cy_lub_oil_received_mecc',
 'cy_lub_oil_received_aecc',
 'cy_m_e_under_piston_temp',
 'cy_mail_received',
 'wind_direction_port_stbd',
 'sea_direction_port_stbd',
 'time_pilot_onboard',
 'grades_rob',
 'bunker_order',
 'remarks',
 'fuel_type',
 'carbon_factor',
 'so_2_co_2_ratio',
 'sulphur_content_pc',
 'quantity',
 'port_delivery',
 'product_quality',
 'tanktainer_number_1',
 'supplier',
 'delivery',
 'vol_lt',
 'den',
 'vis',
 'fuel_hs',
 'fuel_ls',
 'fuel_mdo',
 'fuel_mgo',
 'fuel_mgo_ls',
 'bdn',
 'rob_dstlt_uls',
 'rob_dstlt_vls',
 'rob_rsdl_mdo',
 'rob_tnktnr_dstlt_vls',
 'rob_rsdl_vls',
 'rob_rsdl_hs',
 'rob_rsdl_uls',
 'rob_fuel_hsfo',
 'rob_fuel_lsfo',
 'rob_fuel_mdo',
 'rob_fuel_mgo',
 'rob_fuel_mgo_ls',
 'rob_fuel_tanktainer_mgo',
 'eca_miles',
 'eca_time',
 'egcs_dry_waste_removed',
 'egcs_running_time',
 'egcs_wet_slurry_removed',
 'egcs_open_loop_running_time',
 'egcs_closed_loop_running_time',
 'updated_date',
 'fuel_rsdl_hs',
 'fuel_rsdl_vls',
 'fuel_rsdl_uls',
 'fuel_dstlt_vls',
 'fuel_dstlt_uls',
 'fuel_tnktnr_dstlt_vls',
 'cargo_load',
 'seca_exit_time',
 'seca_exit_lat',
 'seca_exit_long',
 'engine_last_change_user',
 'created_date',
 'created_at',
 'updated_at',
 'created_by_id',
 'updated_by_id',
 'fuel_m_e_lng',
 'fuel_aux_lng',
 'fuel_boiler_lng',
 'rob_boiler_lng']

In [22]:
def process_data(noondata):
    if noondata.empty:
        return []

    noondata['corrected_date'] = pd.to_datetime(noondata['corrected_date'])
    noondata['corrected_date'] = noondata['corrected_date'].dt.date

    try:
        data_filtered = noondata[(noondata['report_type'] != "Refueling") & (noondata['so_2_co_2_ratio'].notna())]
        data_filtered = data_filtered[(data_filtered['so_2_co_2_ratio'] > 0.0) & (data_filtered['so_2_co_2_ratio'] <= 12.7)]
    except KeyError:
        data_filtered = noondata[(noondata['report_type'] != "Refueling") & (noondata['so_2_co_2_ratio'].notna())]
        data_filtered = data_filtered[(data_filtered['so_2_co_2_ratio'] != 0.0) & (data_filtered['so_2_co_2_ratio'] <= 12.7)]

    if data_filtered.empty:
        return []

    data_filtered['so_2_co_2_ratio'] = data_filtered['so_2_co_2_ratio'].astype(float)


    data_filtered = data_filtered.sort_values(by=['corrected_date'])
    data_grouped = data_filtered.groupby(['imo', 'vessel', 'corrected_date'])['so_2_co_2_ratio'].mean().reset_index()
    data_grouped = data_grouped.sort_values(by=['vessel'])

    medium_data = data_grouped[data_grouped['so_2_co_2_ratio'] > 4.33]
    low_data = data_grouped[data_grouped['so_2_co_2_ratio'] <= 4.33]

    medium_data_count = medium_data.drop_duplicates(subset=['vessel', 'corrected_date']).groupby(['vessel'])['corrected_date'].count().reset_index()
    medium_data_mean = medium_data.groupby(['imo', 'vessel'])['so_2_co_2_ratio'].mean().reset_index()
    merged_medium = pd.merge(medium_data_count, medium_data_mean, on='vessel')

    low_data_count = low_data.drop_duplicates(subset=['vessel', 'corrected_date']).groupby(['vessel'])['corrected_date'].count().reset_index()
    low_data_mean = low_data.groupby(['imo', 'vessel'])['so_2_co_2_ratio'].mean().reset_index()
    merged_low = pd.merge(low_data_count, low_data_mean, on='vessel')

    total = pd.concat([merged_medium, merged_low]).to_dict(orient="records")
    scrubber_result = [
        {
            'vessel': j['vessel'],
            'imo': j['imo'],
            'so2_co2_ppm': round(j['so_2_co_2_ratio'], 2),
            'fuelsulphur': round(j['so_2_co_2_ratio'] * 0.023, 2),
            'scrubber_days': j['corrected_date']
        }
        for j in total
    ]

    scrubber_result = sorted(scrubber_result, key=lambda x: x['vessel'])

    return scrubber_result

results = process_data(noondata)


for result in results:
    print(result)

{'vessel': 'AMERICA', 'imo': 9285990, 'so2_co2_ppm': 6.27, 'fuelsulphur': 0.14, 'scrubber_days': 69}
{'vessel': 'AMERICA', 'imo': 9285990, 'so2_co2_ppm': 2.61, 'fuelsulphur': 0.06, 'scrubber_days': 97}
{'vessel': 'AS CALIFORNIA', 'imo': 9342695, 'so2_co2_ppm': 1.0, 'fuelsulphur': 0.02, 'scrubber_days': 1}
{'vessel': 'ATHENS GLORY', 'imo': 9247766, 'so2_co2_ppm': 0.1, 'fuelsulphur': 0.0, 'scrubber_days': 139}
{'vessel': 'BF GIANT', 'imo': 9442172, 'so2_co2_ppm': 6.07, 'fuelsulphur': 0.14, 'scrubber_days': 17}
{'vessel': 'BF GIANT', 'imo': 9442172, 'so2_co2_ppm': 2.69, 'fuelsulphur': 0.06, 'scrubber_days': 44}
{'vessel': 'BF HAMBURG', 'imo': 9332860, 'so2_co2_ppm': 0.29, 'fuelsulphur': 0.01, 'scrubber_days': 128}
{'vessel': 'CALI', 'imo': 9631101, 'so2_co2_ppm': 12.24, 'fuelsulphur': 0.28, 'scrubber_days': 8}
{'vessel': 'CATHERINE C', 'imo': 9969998, 'so2_co2_ppm': 6.25, 'fuelsulphur': 0.14, 'scrubber_days': 5}
{'vessel': 'CATHERINE C', 'imo': 9969998, 'so2_co2_ppm': 3.25, 'fuelsulphur': 0.07, 'scrubber_days': 27}
{'vessel': 'EUROPE', 'imo': 9285988, 'so2_co2_ppm': 9.81, 'fuelsulphur': 0.23, 'scrubber_days': 3}
{'vessel': 'EUROPE', 'imo': 9285988, 'so2_co2_ppm': 2.14, 'fuelsulphur': 0.05, 'scrubber_days': 114}
{'vessel': 'GREENLAND', 'imo': 9970002, 'so2_co2_ppm': 3.47, 'fuelsulphur': 0.08, 'scrubber_days': 3}
{'vessel': 'GSL LALO', 'imo': 9330525, 'so2_co2_ppm': 0.4, 'fuelsulphur': 0.01, 'scrubber_days': 175}
{'vessel': 'LE HAVRE', 'imo': 9307243, 'so2_co2_ppm': 9.72, 'fuelsulphur': 0.22, 'scrubber_days': 43}
{'vessel': 'LE HAVRE', 'imo': 9307243, 'so2_co2_ppm': 2.53, 'fuelsulphur': 0.06, 'scrubber_days': 67}
{'vessel': 'LORI', 'imo': 9631125, 'so2_co2_ppm': 4.85, 'fuelsulphur': 0.11, 'scrubber_days': 4}
{'vessel': 'LORI', 'imo': 9631125, 'so2_co2_ppm': 1.87, 'fuelsulphur': 0.04, 'scrubber_days': 137}
{'vessel': 'MSC ABIDJAN', 'imo': 9618264, 'so2_co2_ppm': 5.59, 'fuelsulphur': 0.13, 'scrubber_days': 6}
{'vessel': 'MSC ABIDJAN', 'imo': 9618264, 'so2_co2_ppm': 1.59, 'fuelsulphur': 0.04, 'scrubber_days': 162}
{'vessel': 'MSC ABY', 'imo': 9166778, 'so2_co2_ppm': 4.9, 'fuelsulphur': 0.11, 'scrubber_days': 1}
{'vessel': 'MSC ABY', 'imo': 9166778, 'so2_co2_ppm': 2.1, 'fuelsulphur': 0.05, 'scrubber_days': 14}
{'vessel': 'MSC ACAPULCO', 'imo': 9401776, 'so2_co2_ppm': 10.03, 'fuelsulphur': 0.23, 'scrubber_days': 3}
{'vessel': 'MSC ACAPULCO', 'imo': 9401776, 'so2_co2_ppm': 1.03, 'fuelsulphur': 0.02, 'scrubber_days': 5}
{'vessel': 'MSC ADELAIDE', 'imo': 9618290, 'so2_co2_ppm': 1.66, 'fuelsulphur': 0.04, 'scrubber_days': 11}
{'vessel': 'MSC ADITI', 'imo': 9235581, 'so2_co2_ppm': 0.78, 'fuelsulphur': 0.02, 'scrubber_days': 23}
{'vessel': 'MSC ADONIS', 'imo': 9706310, 'so2_co2_ppm': 0.82, 'fuelsulphur': 0.02, 'scrubber_days': 12}
{'vessel': 'MSC AGADIR', 'imo': 9619464, 'so2_co2_ppm': 7.78, 'fuelsulphur': 0.18, 'scrubber_days': 80}
{'vessel': 'MSC AGADIR', 'imo': 9619464, 'so2_co2_ppm': 2.68, 'fuelsulphur': 0.06, 'scrubber_days': 61}
{'vessel': 'MSC AGAMEMNON', 'imo': 9315381, 'so2_co2_ppm': 8.09, 'fuelsulphur': 0.19, 'scrubber_days': 7}
{'vessel': 'MSC AGAMEMNON', 'imo': 9315381, 'so2_co2_ppm': 2.6, 'fuelsulphur': 0.06, 'scrubber_days': 3}
{'vessel': 'MSC AGRIGENTO', 'imo': 9618276, 'so2_co2_ppm': 5.55, 'fuelsulphur': 0.13, 'scrubber_days': 7}
{'vessel': 'MSC AGRIGENTO', 'imo': 9618276, 'so2_co2_ppm': 1.46, 'fuelsulphur': 0.03, 'scrubber_days': 15}
{'vessel': 'MSC AJACCIO', 'imo': 9605267, 'so2_co2_ppm': 0.82, 'fuelsulphur': 0.02, 'scrubber_days': 16}
{'vessel': 'MSC ALANYA', 'imo': 9785483, 'so2_co2_ppm': 6.48, 'fuelsulphur': 0.15, 'scrubber_days': 6}
{'vessel': 'MSC ALANYA', 'imo': 9785483, 'so2_co2_ppm': 2.21, 'fuelsulphur': 0.05, 'scrubber_days': 12}
{'vessel': 'MSC ALBANY', 'imo': 9619438, 'so2_co2_ppm': 7.19, 'fuelsulphur': 0.17, 'scrubber_days': 68}
{'vessel': 'MSC ALBANY', 'imo': 9619438, 'so2_co2_ppm': 2.59, 'fuelsulphur': 0.06, 'scrubber_days': 87}
{'vessel': 'MSC ALDI III', 'imo': 9341122, 'so2_co2_ppm': 0.59, 'fuelsulphur': 0.01, 'scrubber_days': 26}
{'vessel': 'MSC ALEXANDRA', 'imo': 9461374, 'so2_co2_ppm': 1.1, 'fuelsulphur': 0.03, 'scrubber_days': 1}
{'vessel': 'MSC ALGHERO', 'imo': 9618288, 'so2_co2_ppm': 6.28, 'fuelsulphur': 0.14, 'scrubber_days': 12}
{'vessel': 'MSC ALGHERO', 'imo': 9618288, 'so2_co2_ppm': 1.45, 'fuelsulphur': 0.03, 'scrubber_days': 11}
{'vessel': 'MSC ALINA', 'imo': 9695016, 'so2_co2_ppm': 0.02, 'fuelsulphur': 0.0, 'scrubber_days': 24}
{'vessel': 'MSC ALIYA', 'imo': 9842097, 'so2_co2_ppm': 8.18, 'fuelsulphur': 0.19, 'scrubber_days': 7}
{'vessel': 'MSC ALIYA', 'imo': 9842097, 'so2_co2_ppm': 2.23, 'fuelsulphur': 0.05, 'scrubber_days': 5}
{'vessel': 'MSC ALLEGRA', 'imo': 9897028, 'so2_co2_ppm': 0.75, 'fuelsulphur': 0.02, 'scrubber_days': 175}
{'vessel': 'MSC ALTAIR', 'imo': 9465277, 'so2_co2_ppm': 0.98, 'fuelsulphur': 0.02, 'scrubber_days': 23}
{'vessel': 'MSC ALTAMIRA', 'imo': 9619426, 'so2_co2_ppm': 6.4, 'fuelsulphur': 0.15, 'scrubber_days': 6}
{'vessel': 'MSC ALTAMIRA', 'imo': 9619426, 'so2_co2_ppm': 1.91, 'fuelsulphur': 0.04, 'scrubber_days': 50}
{'vessel': 'MSC AMALFI', 'imo': 9605279, 'so2_co2_ppm': 0.32, 'fuelsulphur': 0.01, 'scrubber_days': 141}
{'vessel': 'MSC AMBRA', 'imo': 9839480, 'so2_co2_ppm': 4.45, 'fuelsulphur': 0.1, 'scrubber_days': 2}
{'vessel': 'MSC AMBRA', 'imo': 9839480, 'so2_co2_ppm': 0.67, 'fuelsulphur': 0.02, 'scrubber_days': 173}
{'vessel': 'MSC AMELIA', 'imo': 9896995, 'so2_co2_ppm': 8.48, 'fuelsulphur': 0.19, 'scrubber_days': 6}
{'vessel': 'MSC AMELIA', 'imo': 9896995, 'so2_co2_ppm': 0.92, 'fuelsulphur': 0.02, 'scrubber_days': 14}
{'vessel': 'MSC AMY', 'imo': 9242651, 'so2_co2_ppm': 0.1, 'fuelsulphur': 0.0, 'scrubber_days': 26}
{'vessel': 'MSC ANAHITA', 'imo': 9302085, 'so2_co2_ppm': 0.67, 'fuelsulphur': 0.02, 'scrubber_days': 23}
{'vessel': 'MSC ANCHORAGE', 'imo': 9619440, 'so2_co2_ppm': 8.38, 'fuelsulphur': 0.19, 'scrubber_days': 28}
{'vessel': 'MSC ANCHORAGE', 'imo': 9619440, 'so2_co2_ppm': 1.54, 'fuelsulphur': 0.04, 'scrubber_days': 103}
{'vessel': 'MSC ANGELA', 'imo': 9351593, 'so2_co2_ppm': 2.29, 'fuelsulphur': 0.05, 'scrubber_days': 117}
{'vessel': 'MSC ANISHA R.', 'imo': 9227297, 'so2_co2_ppm': 0.92, 'fuelsulphur': 0.02, 'scrubber_days': 7}
{'vessel': 'MSC ANITA', 'imo': 9947146, 'so2_co2_ppm': 0.54, 'fuelsulphur': 0.01, 'scrubber_days': 12}
{'vessel': 'MSC ANS', 'imo': 9282261, 'so2_co2_ppm': 0.29, 'fuelsulphur': 0.01, 'scrubber_days': 24}
{'vessel': 'MSC ANTIGUA', 'imo': 9619476, 'so2_co2_ppm': 9.31, 'fuelsulphur': 0.21, 'scrubber_days': 74}
{'vessel': 'MSC ANTIGUA', 'imo': 9619476, 'so2_co2_ppm': 1.88, 'fuelsulphur': 0.04, 'scrubber_days': 59}
{'vessel': 'MSC ANTONELLA', 'imo': 9702273, 'so2_co2_ppm': 9.5, 'fuelsulphur': 0.22, 'scrubber_days': 1}
{'vessel': 'MSC ANTONELLA', 'imo': 9702273, 'so2_co2_ppm': 1.74, 'fuelsulphur': 0.04, 'scrubber_days': 25}
{'vessel': 'MSC ANTONIA', 'imo': 9398216, 'so2_co2_ppm': 6.52, 'fuelsulphur': 0.15, 'scrubber_days': 5}
{'vessel': 'MSC ANTONIA', 'imo': 9398216, 'so2_co2_ppm': 1.96, 'fuelsulphur': 0.05, 'scrubber_days': 9}
{'vessel': 'MSC ANYA', 'imo': 9297864, 'so2_co2_ppm': 2.19, 'fuelsulphur': 0.05, 'scrubber_days': 17}
{'vessel': 'MSC ANZU', 'imo': 9710426, 'so2_co2_ppm': 12.7, 'fuelsulphur': 0.29, 'scrubber_days': 1}
{'vessel': 'MSC ANZU', 'imo': 9710426, 'so2_co2_ppm': 1.99, 'fuelsulphur': 0.05, 'scrubber_days': 6}
{'vessel': 'MSC APOLLINE', 'imo': 9896983, 'so2_co2_ppm': 0.97, 'fuelsulphur': 0.02, 'scrubber_days': 25}
{'vessel': 'MSC AQUARIUS', 'imo': 9262704, 'so2_co2_ppm': 0.49, 'fuelsulphur': 0.01, 'scrubber_days': 117}
{'vessel': 'MSC ARICA', 'imo': 9619452, 'so2_co2_ppm': 1.24, 'fuelsulphur': 0.03, 'scrubber_days': 24}
{'vessel': 'MSC ARINA', 'imo': 9839284, 'so2_co2_ppm': 1.09, 'fuelsulphur': 0.02, 'scrubber_days': 23}
{'vessel': 'MSC ARUSHI R.', 'imo': 9244881, 'so2_co2_ppm': 0.17, 'fuelsulphur': 0.0, 'scrubber_days': 26}
{'vessel': 'MSC ASTRID III', 'imo': 9263344, 'so2_co2_ppm': 0.98, 'fuelsulphur': 0.02, 'scrubber_days': 23}
{'vessel': 'MSC ASYA', 'imo': 9339296, 'so2_co2_ppm': 6.98, 'fuelsulphur': 0.16, 'scrubber_days': 30}
{'vessel': 'MSC ASYA', 'imo': 9339296, 'so2_co2_ppm': 3.54, 'fuelsulphur': 0.08, 'scrubber_days': 64}
{'vessel': 'MSC ATHENS', 'imo': 9618305, 'so2_co2_ppm': 0.53, 'fuelsulphur': 0.01, 'scrubber_days': 164}
{'vessel': 'MSC ATHOS', 'imo': 9618317, 'so2_co2_ppm': 0.1, 'fuelsulphur': 0.0, 'scrubber_days': 1}
{'vessel': 'MSC AURIGA', 'imo': 9857183, 'so2_co2_ppm': 0.23, 'fuelsulphur': 0.01, 'scrubber_days': 25}
{'vessel': 'MSC AVNI', 'imo': 9756729, 'so2_co2_ppm': 1.14, 'fuelsulphur': 0.03, 'scrubber_days': 26}
{'vessel': 'MSC AZOV', 'imo': 9605255, 'so2_co2_ppm': 0.93, 'fuelsulphur': 0.02, 'scrubber_days': 80}
{'vessel': 'MSC BANU III', 'imo': 9263332, 'so2_co2_ppm': 1.18, 'fuelsulphur': 0.03, 'scrubber_days': 26}
{'vessel': 'MSC BARBARA', 'imo': 9226932, 'so2_co2_ppm': 0.34, 'fuelsulphur': 0.01, 'scrubber_days': 24}
{'vessel': 'MSC BARI', 'imo': 9461441, 'so2_co2_ppm': 8.91, 'fuelsulphur': 0.2, 'scrubber_days': 101}
{'vessel': 'MSC BARI', 'imo': 9461441, 'so2_co2_ppm': 2.27, 'fuelsulphur': 0.05, 'scrubber_days': 51}
{'vessel': 'MSC BASEL V', 'imo': 9360764, 'so2_co2_ppm': 9.71, 'fuelsulphur': 0.22, 'scrubber_days': 8}
{'vessel': 'MSC BEATRICE', 'imo': 9399014, 'so2_co2_ppm': 0.73, 'fuelsulphur': 0.02, 'scrubber_days': 109}
{'vessel': 'MSC BEIJING', 'imo': 9289099, 'so2_co2_ppm': 4.85, 'fuelsulphur': 0.11, 'scrubber_days': 1}
{'vessel': 'MSC BEIJING', 'imo': 9289099, 'so2_co2_ppm': 2.12, 'fuelsulphur': 0.05, 'scrubber_days': 24}
{'vessel': 'MSC BEIRA IV', 'imo': 9477309, 'so2_co2_ppm': 6.56, 'fuelsulphur': 0.15, 'scrubber_days': 8}
{'vessel': 'MSC BEIRA IV', 'imo': 9477309, 'so2_co2_ppm': 1.87, 'fuelsulphur': 0.04, 'scrubber_days': 16}
{'vessel': 'MSC BERANGERE', 'imo': 9930947, 'so2_co2_ppm': 5.3, 'fuelsulphur': 0.12, 'scrubber_days': 1}
{'vessel': 'MSC BERANGERE', 'imo': 9930947, 'so2_co2_ppm': 0.87, 'fuelsulphur': 0.02, 'scrubber_days': 13}
{'vessel': 'MSC BERN V', 'imo': 9362449, 'so2_co2_ppm': 7.28, 'fuelsulphur': 0.17, 'scrubber_days': 8}
{'vessel': 'MSC BERN V', 'imo': 9362449, 'so2_co2_ppm': 3.08, 'fuelsulphur': 0.07, 'scrubber_days': 8}
{'vessel': 'MSC BERYL', 'imo': 9467392, 'so2_co2_ppm': 0.0, 'fuelsulphur': 0.0, 'scrubber_days': 131}
{'vessel': 'MSC BETTINA', 'imo': 9399038, 'so2_co2_ppm': 6.48, 'fuelsulphur': 0.15, 'scrubber_days': 5}
{'vessel': 'MSC BETTINA', 'imo': 9399038, 'so2_co2_ppm': 1.89, 'fuelsulphur': 0.04, 'scrubber_days': 163}
{'vessel': 'MSC BHAVYA V', 'imo': 9297876, 'so2_co2_ppm': 0.14, 'fuelsulphur': 0.0, 'scrubber_days': 25}
{'vessel': 'MSC BIANCA SILVIA', 'imo': 9930935, 'so2_co2_ppm': 8.34, 'fuelsulphur': 0.19, 'scrubber_days': 20}
{'vessel': 'MSC BIANCA SILVIA', 'imo': 9930935, 'so2_co2_ppm': 4.17, 'fuelsulphur': 0.1, 'scrubber_days': 1}
{'vessel': 'MSC BOSPHORUS', 'imo': 9247742, 'so2_co2_ppm': 0.21, 'fuelsulphur': 0.0, 'scrubber_days': 47}
{'vessel': 'MSC BREMEN', 'imo': 9369734, 'so2_co2_ppm': 0.93, 'fuelsulphur': 0.02, 'scrubber_days': 23}
{'vessel': 'MSC BREMERHAVEN V', 'imo': 9313967, 'so2_co2_ppm': 0.52, 'fuelsulphur': 0.01, 'scrubber_days': 13}
{'vessel': 'MSC BRIDGEPORT', 'imo': 9243409, 'so2_co2_ppm': 0.48, 'fuelsulphur': 0.01, 'scrubber_days': 26}
{'vessel': 'MSC BRITTANY', 'imo': 9724049, 'so2_co2_ppm': 0.4, 'fuelsulphur': 0.01, 'scrubber_days': 25}
{'vessel': 'MSC BRUNELLA', 'imo': 9702106, 'so2_co2_ppm': 4.78, 'fuelsulphur': 0.11, 'scrubber_days': 10}
{'vessel': 'MSC BRUNELLA', 'imo': 9702106, 'so2_co2_ppm': 2.92, 'fuelsulphur': 0.07, 'scrubber_days': 15}
{'vessel': 'MSC BUSAN', 'imo': 9289087, 'so2_co2_ppm': 1.75, 'fuelsulphur': 0.04, 'scrubber_days': 25}
{'vessel': 'MSC CAMILLE', 'imo': 9404651, 'so2_co2_ppm': 5.29, 'fuelsulphur': 0.12, 'scrubber_days': 10}
{'vessel': 'MSC CAMILLE', 'imo': 9404651, 'so2_co2_ppm': 1.71, 'fuelsulphur': 0.04, 'scrubber_days': 167}
{'vessel': 'MSC CANCUN', 'imo': 9403396, 'so2_co2_ppm': 0.37, 'fuelsulphur': 0.01, 'scrubber_days': 11}
{'vessel': 'MSC CANDIDA', 'imo': 9946714, 'so2_co2_ppm': 7.78, 'fuelsulphur': 0.18, 'scrubber_days': 13}
{'vessel': 'MSC CAPELLA', 'imo': 9465289, 'so2_co2_ppm': 1.12, 'fuelsulphur': 0.03, 'scrubber_days': 129}
{'vessel': 'MSC CAPUCINE R', 'imo': 9210086, 'so2_co2_ppm': 5.18, 'fuelsulphur': 0.12, 'scrubber_days': 5}
{'vessel': 'MSC CAPUCINE R', 'imo': 9210086, 'so2_co2_ppm': 3.37, 'fuelsulphur': 0.08, 'scrubber_days': 13}
{'vessel': 'MSC CARLA III', 'imo': 9124512, 'so2_co2_ppm': 0.59, 'fuelsulphur': 0.01, 'scrubber_days': 25}
{'vessel': 'MSC CARMELITA', 'imo': 9946879, 'so2_co2_ppm': 0.2, 'fuelsulphur': 0.0, 'scrubber_days': 24}
{'vessel': 'MSC CASSANDRE', 'imo': 9785471, 'so2_co2_ppm': 1.67, 'fuelsulphur': 0.04, 'scrubber_days': 2}
{'vessel': 'MSC CATERINA', 'imo': 9705005, 'so2_co2_ppm': 0.61, 'fuelsulphur': 0.01, 'scrubber_days': 16}
{'vessel': 'MSC CELESTINO MARESCA', 'imo': 9930040, 'so2_co2_ppm': 8.23, 'fuelsulphur': 0.19, 'scrubber_days': 26}
{'vessel': 'MSC CELESTINO MARESCA', 'imo': 9930040, 'so2_co2_ppm': 1.04, 'fuelsulphur': 0.02, 'scrubber_days': 138}
{'vessel': 'MSC CHANNE', 'imo': 9710438, 'so2_co2_ppm': 6.79, 'fuelsulphur': 0.16, 'scrubber_days': 17}
{'vessel': 'MSC CHANNE', 'imo': 9710438, 'so2_co2_ppm': 4.0, 'fuelsulphur': 0.09, 'scrubber_days': 6}
{'vessel': 'MSC CHARLOTTE', 'imo': 9330238, 'so2_co2_ppm': 1.0, 'fuelsulphur': 0.02, 'scrubber_days': 9}
{'vessel': 'MSC CHINA', 'imo': 9936642, 'so2_co2_ppm': 0.3, 'fuelsulphur': 0.01, 'scrubber_days': 25}
{'vessel': 'MSC CHIYO', 'imo': 9947110, 'so2_co2_ppm': 5.53, 'fuelsulphur': 0.13, 'scrubber_days': 7}
{'vessel': 'MSC CHIYO', 'imo': 9947110, 'so2_co2_ppm': 2.18, 'fuelsulphur': 0.05, 'scrubber_days': 18}
{'vessel': 'MSC CHLOE', 'imo': 9720483, 'so2_co2_ppm': 12.01, 'fuelsulphur': 0.28, 'scrubber_days': 1}
{'vessel': 'MSC CLARA', 'imo': 9708693, 'so2_co2_ppm': 7.04, 'fuelsulphur': 0.16, 'scrubber_days': 35}
{'vessel': 'MSC CLARA', 'imo': 9708693, 'so2_co2_ppm': 1.87, 'fuelsulphur': 0.04, 'scrubber_days': 136}
{'vessel': 'MSC CLAUDE GIRARDET', 'imo': 9936628, 'so2_co2_ppm': 8.2, 'fuelsulphur': 0.19, 'scrubber_days': 6}
{'vessel': 'MSC CLAUDE GIRARDET', 'imo': 9936628, 'so2_co2_ppm': 2.75, 'fuelsulphur': 0.06, 'scrubber_days': 8}
{'vessel': 'MSC CLEA', 'imo': 9720524, 'so2_co2_ppm': 7.38, 'fuelsulphur': 0.17, 'scrubber_days': 4}
{'vessel': 'MSC CLEA', 'imo': 9720524, 'so2_co2_ppm': 2.25, 'fuelsulphur': 0.05, 'scrubber_days': 3}
{'vessel': 'MSC CLORINDA', 'imo': 9484429, 'so2_co2_ppm': 5.72, 'fuelsulphur': 0.13, 'scrubber_days': 8}
{'vessel': 'MSC CLORINDA', 'imo': 9484429, 'so2_co2_ppm': 2.68, 'fuelsulphur': 0.06, 'scrubber_days': 5}
{'vessel': 'MSC CORINNA', 'imo': 9307267, 'so2_co2_ppm': 5.26, 'fuelsulphur': 0.12, 'scrubber_days': 6}
{'vessel': 'MSC CORINNA', 'imo': 9307267, 'so2_co2_ppm': 1.88, 'fuelsulphur': 0.04, 'scrubber_days': 19}
{'vessel': 'MSC CRISTINA', 'imo': 9465241, 'so2_co2_ppm': 7.33, 'fuelsulphur': 0.17, 'scrubber_days': 3}
{'vessel': 'MSC CRISTINA', 'imo': 9465241, 'so2_co2_ppm': 0.95, 'fuelsulphur': 0.02, 'scrubber_days': 17}
{'vessel': 'MSC DAKAR X', 'imo': 9605231, 'so2_co2_ppm': 0.7, 'fuelsulphur': 0.02, 'scrubber_days': 53}
{'vessel': 'MSC DAMLA', 'imo': 9250983, 'so2_co2_ppm': 0.76, 'fuelsulphur': 0.02, 'scrubber_days': 25}
{'vessel': 'MSC DANIT', 'imo': 9404649, 'so2_co2_ppm': 1.0, 'fuelsulphur': 0.02, 'scrubber_days': 1}
{'vessel': 'MSC DARIEN', 'imo': 9243394, 'so2_co2_ppm': 0.32, 'fuelsulphur': 0.01, 'scrubber_days': 25}
{'vessel': 'MSC DARLENE', 'imo': 9930959, 'so2_co2_ppm': 8.36, 'fuelsulphur': 0.19, 'scrubber_days': 9}
{'vessel': 'MSC DARLENE', 'imo': 9930959, 'so2_co2_ppm': 1.56, 'fuelsulphur': 0.04, 'scrubber_days': 16}
{'vessel': 'MSC DEILA', 'imo': 9461415, 'so2_co2_ppm': 7.99, 'fuelsulphur': 0.18, 'scrubber_days': 23}
{'vessel': 'MSC DEILA', 'imo': 9461415, 'so2_co2_ppm': 2.26, 'fuelsulphur': 0.05, 'scrubber_days': 26}
{'vessel': 'MSC DESIREE', 'imo': 9745665, 'so2_co2_ppm': 0.64, 'fuelsulphur': 0.01, 'scrubber_days': 168}
{'vessel': 'MSC DIANA', 'imo': 9755933, 'so2_co2_ppm': 9.97, 'fuelsulphur': 0.23, 'scrubber_days': 80}
{'vessel': 'MSC DIANA', 'imo': 9755933, 'so2_co2_ppm': 1.13, 'fuelsulphur': 0.03, 'scrubber_days': 76}
{'vessel': 'MSC DILETTA', 'imo': 9897004, 'so2_co2_ppm': 5.85, 'fuelsulphur': 0.13, 'scrubber_days': 7}
{'vessel': 'MSC DILETTA', 'imo': 9897004, 'so2_co2_ppm': 1.98, 'fuelsulphur': 0.05, 'scrubber_days': 168}
{'vessel': 'MSC DITTE', 'imo': 9754953, 'so2_co2_ppm': 7.94, 'fuelsulphur': 0.18, 'scrubber_days': 107}
{'vessel': 'MSC DITTE', 'imo': 9754953, 'so2_co2_ppm': 2.58, 'fuelsulphur': 0.06, 'scrubber_days': 58}
{'vessel': 'MSC DONATA', 'imo': 9237151, 'so2_co2_ppm': 6.75, 'fuelsulphur': 0.16, 'scrubber_days': 2}
{'vessel': 'MSC DONATA', 'imo': 9237151, 'so2_co2_ppm': 0.87, 'fuelsulphur': 0.02, 'scrubber_days': 23}
{'vessel': 'MSC DYMPHNA', 'imo': 9110391, 'so2_co2_ppm': 6.23, 'fuelsulphur': 0.14, 'scrubber_days': 21}
{'vessel': 'MSC DYMPHNA', 'imo': 9110391, 'so2_co2_ppm': 3.85, 'fuelsulphur': 0.09, 'scrubber_days': 4}
{'vessel': 'MSC ELA', 'imo': 9282259, 'so2_co2_ppm': 0.53, 'fuelsulphur': 0.01, 'scrubber_days': 23}
{'vessel': 'MSC ELAINE', 'imo': 9393321, 'so2_co2_ppm': 0.97, 'fuelsulphur': 0.02, 'scrubber_days': 19}
{'vessel': 'MSC ELENI', 'imo': 9278143, 'so2_co2_ppm': 0.58, 'fuelsulphur': 0.01, 'scrubber_days': 25}
{'vessel': 'MSC ELISA XIII', 'imo': 9463059, 'so2_co2_ppm': 1.84, 'fuelsulphur': 0.04, 'scrubber_days': 25}
{'vessel': 'MSC ELLEN', 'imo': 9166780, 'so2_co2_ppm': 0.21, 'fuelsulphur': 0.0, 'scrubber_days': 17}
{'vessel': 'MSC ELOANE', 'imo': 9755957, 'so2_co2_ppm': 7.02, 'fuelsulphur': 0.16, 'scrubber_days': 23}
{'vessel': 'MSC ELOANE', 'imo': 9755957, 'so2_co2_ppm': 1.72, 'fuelsulphur': 0.04, 'scrubber_days': 133}
{'vessel': 'MSC ELODIE', 'imo': 9704972, 'so2_co2_ppm': 5.98, 'fuelsulphur': 0.14, 'scrubber_days': 2}
{'vessel': 'MSC ELODIE', 'imo': 9704972, 'so2_co2_ppm': 3.84, 'fuelsulphur': 0.09, 'scrubber_days': 4}
{'vessel': 'MSC EMANUELA', 'imo': 9399052, 'so2_co2_ppm': 6.87, 'fuelsulphur': 0.16, 'scrubber_days': 58}
{'vessel': 'MSC EMANUELA', 'imo': 9399052, 'so2_co2_ppm': 3.51, 'fuelsulphur': 0.08, 'scrubber_days': 6}
{'vessel': 'MSC EMMA', 'imo': 9463047, 'so2_co2_ppm': 7.25, 'fuelsulphur': 0.17, 'scrubber_days': 4}
{'vessel': 'MSC EMMA', 'imo': 9463047, 'so2_co2_ppm': 2.75, 'fuelsulphur': 0.06, 'scrubber_days': 21}
{'vessel': 'MSC ENGLAND', 'imo': 9232890, 'so2_co2_ppm': 2.03, 'fuelsulphur': 0.05, 'scrubber_days': 7}
{'vessel': 'MSC ERICA', 'imo': 9755191, 'so2_co2_ppm': 5.6, 'fuelsulphur': 0.13, 'scrubber_days': 20}
{'vessel': 'MSC ERICA', 'imo': 9755191, 'so2_co2_ppm': 1.58, 'fuelsulphur': 0.04, 'scrubber_days': 156}
{'vessel': 'MSC ESTHI', 'imo': 9304411, 'so2_co2_ppm': 11.3, 'fuelsulphur': 0.26, 'scrubber_days': 5}
{'vessel': 'MSC ESTHI', 'imo': 9304411, 'so2_co2_ppm': 0.42, 'fuelsulphur': 0.01, 'scrubber_days': 124}
{'vessel': 'MSC EUGENIA', 'imo': 9785469, 'so2_co2_ppm': 1.11, 'fuelsulphur': 0.03, 'scrubber_days': 23}
{'vessel': 'MSC EVA', 'imo': 9401130, 'so2_co2_ppm': 7.13, 'fuelsulphur': 0.16, 'scrubber_days': 86}
{'vessel': 'MSC EVA', 'imo': 9401130, 'so2_co2_ppm': 1.48, 'fuelsulphur': 0.03, 'scrubber_days': 38}
{'vessel': 'MSC EVEREST VIII', 'imo': 9286231, 'so2_co2_ppm': 0.89, 'fuelsulphur': 0.02, 'scrubber_days': 25}
{'vessel': 'MSC EXPRESS III', 'imo': 9374571, 'so2_co2_ppm': 0.36, 'fuelsulphur': 0.01, 'scrubber_days': 22}
{'vessel': 'MSC FAITH', 'imo': 9842085, 'so2_co2_ppm': 6.37, 'fuelsulphur': 0.15, 'scrubber_days': 3}
{'vessel': 'MSC FAITH', 'imo': 9842085, 'so2_co2_ppm': 2.41, 'fuelsulphur': 0.06, 'scrubber_days': 5}
{'vessel': 'MSC FEBE', 'imo': 9839478, 'so2_co2_ppm': 7.2, 'fuelsulphur': 0.17, 'scrubber_days': 47}
{'vessel': 'MSC FEBE', 'imo': 9839478, 'so2_co2_ppm': 1.54, 'fuelsulphur': 0.04, 'scrubber_days': 129}
{'vessel': 'MSC FIAMMETTA', 'imo': 9369758, 'so2_co2_ppm': 0.79, 'fuelsulphur': 0.02, 'scrubber_days': 25}

In [8]:
data_filtered = noondata[(noondata['report_type'] != "Refueling") & (noondata['so_2_co_2_ratio'].notna())]
data_filtered = data_filtered[(data_filtered['so_2_co_2_ratio'] > 0) & (data_filtered['so_2_co_2_ratio'] <= 12.7)]

data_filtered

,id,pi_sog,pi_stw,true_wind_dir,true_wind_speed,relative_wind_speed,relative_wind_direction,caa,corrected_power,rw,...,rob_garbage_cat_a_plastic,rob_garbage_cat_b_organic,rob_garbage_cat_c_domestic,rob_garbage_cat_e_ashes,qty_sludge_disposed,steaming_time_m_e_lng,reefer_power_consumption,wind_direction_side,sea_direction_side,tot_sludge_removed
531,5633377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
534,5633380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,856.0,NaN,NaN,NaN
536,5633382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,400.0,NaN,NaN,NaN
538,5633384,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
539,5633385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.2,0.0,0.2,0.0,NaN,NaN,0.0,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30247,5943031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,4933.0,70S,139S,NaN
30248,5943032,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,5072.0,57S,124S,NaN
30249,5943033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,5435.0,55S,118S,NaN
30250,5943034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,5239.0,39S,125S,NaN
30251,5943035,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,5162.0,27S,111S,NaN

In [9]:
data_filtered['so_2_co_2_ratio'] = data_filtered['so_2_co_2_ratio'].astype(float)

In [10]:
data_filtered = data_filtered.sort_values(by=['corrected_date'])
data_grouped = data_filtered.groupby(['imo', 'vessel', 'corrected_date'])['so_2_co_2_ratio'].mean().reset_index()
data_grouped = data_grouped.sort_values(by=['vessel'])
data_grouped.head(30)

           imo       vessel corrected_date  so_2_co_2_ratio
18393  9618264  MSC ABIDJAN     2024-01-03         1.600000
18386  9618264  MSC ABIDJAN     2023-12-27         1.600000
18385  9618264  MSC ABIDJAN     2023-12-26         1.600000
18384  9618264  MSC ABIDJAN     2023-12-25         1.500000
18383  9618264  MSC ABIDJAN     2023-12-24         1.566667
18382  9618264  MSC ABIDJAN     2023-12-23         1.700000
18381  9618264  MSC ABIDJAN     2023-12-22         1.600000
18380  9618264  MSC ABIDJAN     2023-12-21         1.600000
18387  9618264  MSC ABIDJAN     2023-12-28         1.500000
18379  9618264  MSC ABIDJAN     2023-12-20         1.600000
18377  9618264  MSC ABIDJAN     2023-12-18         1.700000
18376  9618264  MSC ABIDJAN     2023-12-17         1.550000
18375  9618264  MSC ABIDJAN     2023-12-16         1.400000
18374  9618264  MSC ABIDJAN     2023-12-15         1.700000
18373  9618264  MSC ABIDJAN     2023-12-14         1.600000
18372  9618264  MSC ABIDJAN     2023-12-13         1.700000
18371  9618264  MSC ABIDJAN     2023-12-12         1.600000
18378  9618264  MSC ABIDJAN     2023-12-19         1.700000
18370  9618264  MSC ABIDJAN     2023-12-11         1.600000
18388  9618264  MSC ABIDJAN     2023-12-29         1.600000
18390  9618264  MSC ABIDJAN     2023-12-31         1.600000
18406  9618264  MSC ABIDJAN     2024-01-16         1.600000
18405  9618264  MSC ABIDJAN     2024-01-15         1.600000
18404  9618264  MSC ABIDJAN     2024-01-14         1.600000
18403  9618264  MSC ABIDJAN     2024-01-13         1.666667
18402  9618264  MSC ABIDJAN     2024-01-12         1.600000
18401  9618264  MSC ABIDJAN     2024-01-11         1.600000
18400  9618264  MSC ABIDJAN     2024-01-10         1.600000
18389  9618264  MSC ABIDJAN     2023-12-30         1.600000
18399  9618264  MSC ABIDJAN     2024-01-09         1.500000

In [11]:
medium_data = data_grouped[data_grouped['so_2_co_2_ratio'] > 4.33]
low_data = data_grouped[data_grouped['so_2_co_2_ratio'] <= 4.33]

In [31]:
low_data.to_csv('low_data.csv')

In [12]:

# Drop duplicates and count occurrences
medium_data_count = medium_data.drop_duplicates(subset=['vessel', 'corrected_date']).groupby(['vessel'])['corrected_date'].count().reset_index()
medium_data_mean = medium_data.groupby(['imo', 'vessel'])['so_2_co_2_ratio'].mean().reset_index()
merged_medium = pd.merge(medium_data_count, medium_data_mean, on='vessel')
merged_medium

            vessel  corrected_date      imo  so_2_co_2_ratio
0      MSC ABIDJAN               4  9618264         5.242500
1          MSC ABY               5  9166778         6.240000
2     MSC ACAPULCO              19  9401776         9.275088
3        MSC ADITI               7  9235581         6.496429
4    MSC AGRIGENTO               4  9618276         8.200000
..             ...             ...      ...              ...
139     MSC WAVE F               1  9232462        11.000000
140      MSC WESER              13  9236690         5.323077
141    MSC YASHI B              22  9778090         5.519545
142   MSC YUVIKA V               1  9141285        12.660000
143    MSC ZLATA R              10  9227314         6.312167

[144 rows x 4 columns]

In [17]:
medium_data.drop_duplicates(subset=['vessel', 'corrected_date']).groupby(['vessel'])['corrected_date'].count().reset_index()
medium_data[medium_data['vessel']=='MSC ACAPULCO']

           imo        vessel corrected_date  so_2_co_2_ratio
15922  9401776  MSC ACAPULCO     2023-11-15        10.000000
15923  9401776  MSC ACAPULCO     2023-11-16         8.666667
15925  9401776  MSC ACAPULCO     2023-11-21         8.000000
15926  9401776  MSC ACAPULCO     2023-11-22        10.000000
15927  9401776  MSC ACAPULCO     2023-11-23         9.000000
15928  9401776  MSC ACAPULCO     2023-12-04        12.000000
15929  9401776  MSC ACAPULCO     2023-12-08        12.000000
15930  9401776  MSC ACAPULCO     2023-12-09        11.000000
15931  9401776  MSC ACAPULCO     2023-12-17        12.000000
15932  9401776  MSC ACAPULCO     2023-12-26        12.000000
15934  9401776  MSC ACAPULCO     2024-03-20         4.500000
15921  9401776  MSC ACAPULCO     2023-11-06         7.000000
15940  9401776  MSC ACAPULCO     2024-03-27         5.060000
15920  9401776  MSC ACAPULCO     2023-11-05         7.000000
15918  9401776  MSC ACAPULCO     2023-11-03        10.000000
15917  9401776  MSC ACAPULCO     2023-11-01        11.000000
15916  9401776  MSC ACAPULCO     2023-10-30         8.000000
15915  9401776  MSC ACAPULCO     2023-10-09         8.000000
15919  9401776  MSC ACAPULCO     2023-11-04        11.000000

In [19]:
medium_data_mean = medium_data.groupby(['imo', 'vessel'])['so_2_co_2_ratio'].mean().reset_index()
medium_data_mean

         imo          vessel  so_2_co_2_ratio
0    9060649  MSC MONICA III         5.125000
1    9103685     MSC BRIANNA         6.805926
2    9110377    MSC SAMANTHA        11.095000
3    9110389    MSC KATYAYNI         4.835000
4    9110391     MSC DYMPHNA         7.203725
..       ...             ...              ...
139  9946843  MSC NOA ARIELA         5.712143
140  9946855   MSC VALENTINA         5.606944
141  9947110       MSC CHIYO         6.628889
142  9947122    MSC VIVIENNE         4.801852
143  9947134       MSC GIUSY         5.485714

[144 rows x 3 columns]

In [33]:
low_data_count = low_data.drop_duplicates(subset=['vessel', 'corrected_date']).groupby(['vessel'])['corrected_date'].count().reset_index()
low_data_mean = low_data.groupby(['imo', 'vessel'])['so_2_co_2_ratio'].mean().reset_index()
merged_low = pd.merge(low_data_count, low_data_mean, on='vessel')
merged_low

             vessel  corrected_date      imo  so_2_co_2_ratio
0       MSC ABIDJAN             155  9618264         1.583674
1           MSC ABY               1  9166778         4.200000
2      MSC ACAPULCO              11  9401776         2.033303
3         MSC ADITI             177  9235581         0.966964
4        MSC ADONIS              97  9706310         0.348591
..              ...             ...      ...              ...
243     MSC ZLATA R             150  9227314         1.179968
244    WEC DE HOOGH             102  9315018         0.454469
245  WEC FRANS HALS              17  9326964         1.364412
246    WEC VAN GOGH              81  9246566         2.025926
247    WEC VAN RIJN              29  9315006         0.425190

[248 rows x 4 columns]

In [35]:
low_data_count

             vessel  corrected_date
0       MSC ABIDJAN             155
1           MSC ABY               1
2      MSC ACAPULCO              11
3         MSC ADITI             177
4        MSC ADONIS              97
..              ...             ...
243     MSC ZLATA R             150
244    WEC DE HOOGH             102
245  WEC FRANS HALS              17
246    WEC VAN GOGH              81
247    WEC VAN RIJN              29

[248 rows x 2 columns]

In [36]:
total = pd.concat([merged_medium, merged_low]).reset_index(drop=True)  # Concatenate and reset index

In [37]:
# total[total['corrected_date']>=182]
filtered_total = total[total['corrected_date'] >= 182]
#total[total['corrected_date'] >= 182]
filtered_total

             vessel  corrected_date      imo  so_2_co_2_ratio
152    MSC ALDI III             184  9341122         0.322844
153     MSC ALGHERO             183  9618288         1.678132
172    MSC ARUSHI R             182  9244881         0.429483
180    MSC BANU III             182  9263332         1.046809
185      MSC BHAVYA             183  9297876         0.095808
206   MSC CHARLOTTE             183  9330238         1.016393
238  MSC GENERAL IV             183  9344708         0.377546
327    MSC RHIANNON             183  9224051         0.233162
365      MSC TIA II             183  9193680         3.362614
386    MSC YUVIKA V             182  9141285         2.808391

In [38]:
total = pd.concat([merged_medium, merged_low]).reset_index(drop=True)  # Concatenate and reset index
total

             vessel  corrected_date      imo  so_2_co_2_ratio
0       MSC ABIDJAN               4  9618264         5.242500
1           MSC ABY               5  9166778         6.240000
2      MSC ACAPULCO              19  9401776         9.275088
3         MSC ADITI               7  9235581         6.496429
4     MSC AGRIGENTO               4  9618276         8.200000
..              ...             ...      ...              ...
387     MSC ZLATA R             150  9227314         1.179968
388    WEC DE HOOGH             102  9315018         0.454469
389  WEC FRANS HALS              17  9326964         1.364412
390    WEC VAN GOGH              81  9246566         2.025926
391    WEC VAN RIJN              29  9315006         0.425190

[392 rows x 4 columns]

In [39]:
total = pd.concat([merged_medium, merged_low]).to_dict(orient="records")
scrubber_result = [
    {
        'vessel': j['vessel'],
        'imo': j['imo'],
        'so2_co2_ppm': round(j['so_2_co_2_ratio'], 2),
        'fuelsulphur': round(j['so_2_co_2_ratio'] * 0.023, 2),
        'scrubber_days': j['corrected_date']
    }
    for j in total
]

In [40]:
total

[{'vessel': 'MSC ABIDJAN',
  'corrected_date': 4,
  'imo': 9618264,
  'so_2_co_2_ratio': 5.2425},
 {'vessel': 'MSC ABY',
  'corrected_date': 5,
  'imo': 9166778,
  'so_2_co_2_ratio': 6.24},
 {'vessel': 'MSC ACAPULCO',
  'corrected_date': 19,
  'imo': 9401776,
  'so_2_co_2_ratio': 9.275087719298245},
 {'vessel': 'MSC ADITI',
  'corrected_date': 7,
  'imo': 9235581,
  'so_2_co_2_ratio': 6.496428571428571},
 {'vessel': 'MSC AGRIGENTO',
  'corrected_date': 4,
  'imo': 9618276,
  'so_2_co_2_ratio': 8.2},
 {'vessel': 'MSC ALANYA',
  'corrected_date': 12,
  'imo': 9785483,
  'so_2_co_2_ratio': 6.206666666666667},
 {'vessel': 'MSC ALIYA',
  'corrected_date': 22,
  'imo': 9842097,
  'so_2_co_2_ratio': 7.36869696969697},
 {'vessel': 'MSC ALTAIR',
  'corrected_date': 10,
  'imo': 9465277,
  'so_2_co_2_ratio': 7.052},
 {'vessel': 'MSC AMELIA',
  'corrected_date': 25,
  'imo': 9896995,
  'so_2_co_2_ratio': 6.783333333333334},
 {'vessel': 'MSC ANNICK',
  'corrected_date': 1,
  'imo': 9169122,
  'so_2_co_2_ratio': 4.34},
 {'vessel': 'MSC ANS',
  'corrected_date': 14,
  'imo': 9282261,
  'so_2_co_2_ratio': 6.0},
 {'vessel': 'MSC ANTONELLA',
  'corrected_date': 9,
  'imo': 9702273,
  'so_2_co_2_ratio': 6.36962962962963},
 {'vessel': 'MSC ANTONIA',
  'corrected_date': 12,
  'imo': 9398216,
  'so_2_co_2_ratio': 10.533333333333333},
 {'vessel': 'MSC ANYA',
  'corrected_date': 11,
  'imo': 9297864,
  'so_2_co_2_ratio': 8.845454545454546},
 {'vessel': 'MSC APOLLINE',
  'corrected_date': 19,
  'imo': 9896983,
  'so_2_co_2_ratio': 5.707017543859649},
 {'vessel': 'MSC ARCHIMIDIS',
  'corrected_date': 10,
  'imo': 9315379,
  'so_2_co_2_ratio': 9.337},
 {'vessel': 'MSC ARIA III',
  'corrected_date': 1,
  'imo': 9374595,
  'so_2_co_2_ratio': 5.0},
 {'vessel': 'MSC ARICA',
  'corrected_date': 1,
  'imo': 9619452,
  'so_2_co_2_ratio': 6.15},
 {'vessel': 'MSC ARINA',
  'corrected_date': 21,
  'imo': 9839284,
  'so_2_co_2_ratio': 5.7214285714285715},
 {'vessel': 'MSC ASTRID III',
  'corrected_date': 2,
  'imo': 9263344,
  'so_2_co_2_ratio': 5.2},
 {'vessel': 'MSC AUBE F',
  'corrected_date': 2,
  'imo': 9360283,
  'so_2_co_2_ratio': 5.516666666666667},
 {'vessel': 'MSC BANU III',
  'corrected_date': 1,
  'imo': 9263332,
  'so_2_co_2_ratio': 5.4},
 {'vessel': 'MSC BARBARA',
  'corrected_date': 1,
  'imo': 9226932,
  'so_2_co_2_ratio': 4.4},
 {'vessel': 'MSC BEIJING',
  'corrected_date': 1,
  'imo': 9289099,
  'so_2_co_2_ratio': 4.5},
 {'vessel': 'MSC BEIRA IV',
  'corrected_date': 30,
  'imo': 9477309,
  'so_2_co_2_ratio': 8.159},
 {'vessel': 'MSC BERANGERE',
  'corrected_date': 26,
  'imo': 9930947,
  'so_2_co_2_ratio': 7.326923076923077},
 {'vessel': 'MSC BIANCA SILVIA',
  'corrected_date': 75,
  'imo': 9930935,
  'so_2_co_2_ratio': 7.791488888888889},
 {'vessel': 'MSC BRIANNA',
  'corrected_date': 54,
  'imo': 9103685,
  'so_2_co_2_ratio': 6.8059259259259255},
 {'vessel': 'MSC BRUNELLA',
  'corrected_date': 14,
  'imo': 9702106,
  'so_2_co_2_ratio': 4.841309523809524},
 {'vessel': 'MSC CANCUN',
  'corrected_date': 44,
  'imo': 9403396,
  'so_2_co_2_ratio': 5.815454545454545},
 {'vessel': 'MSC CANDIDA',
  'corrected_date': 21,
  'imo': 9946714,
  'so_2_co_2_ratio': 8.373015873015873},
 {'vessel': 'MSC CAPRI',
  'corrected_date': 12,
  'imo': 9154220,
  'so_2_co_2_ratio': 7.101388888888889},
 {'vessel': 'MSC CAPUCINE R',
  'corrected_date': 5,
  'imo': 9210086,
  'so_2_co_2_ratio': 6.421333333333334},
 {'vessel': 'MSC CAROLE',
  'corrected_date': 8,
  'imo': 9785445,
  'so_2_co_2_ratio': 6.25},
 {'vessel': 'MSC CASSANDRE',
  'corrected_date': 39,
  'imo': 9785471,
  'so_2_co_2_ratio': 5.717286324786325},
 {'vessel': 'MSC CATERINA',
  'corrected_date': 15,
  'imo': 9705005,
  'so_2_co_2_ratio': 5.502888888888889},
 {'vessel': 'MSC CELINE',
  'corrected_date': 4,
  'imo': 9316361,
  'so_2_co_2_ratio': 5.491666666666667},
 {'vessel': 'MSC CHARLESTON',
  'corrected_date': 2,
  'imo': 9299537,
  'so_2_co_2_ratio': 5.5},
 {'vessel': 'MSC CHIYO',
  'corrected_date': 15,
  'imo': 9947110,
  'so_2_co_2_ratio': 6.6288888888888895},
 {'vessel': 'MSC CHLOE',
  'corrected_date': 2,
  'imo': 9720483,
  'so_2_co_2_ratio': 9.545},
 {'vessel': 'MSC CLAUDE GIRARDET',
  'corrected_date': 23,
  'imo': 9936628,
  'so_2_co_2_ratio': 6.7614492753623185},
 {'vessel': 'MSC CLEA',
  'corrected_date': 18,
  'imo': 9720524,
  'so_2_co_2_ratio': 7.324759259259259},
 {'vessel': 'MSC CORINNA',
  'corrected_date': 2,
  'imo': 9307267,
  'so_2_co_2_ratio': 5.300000000000001},
 {'vessel': 'MSC CRISTINA',
  'corrected_date': 10,
  'imo': 9465241,
  'so_2_co_2_ratio': 8.440000000000001},
 {'vessel': 'MSC DAMLA',
  'corrected_date': 2,
  'imo': 9250983,
  'so_2_co_2_ratio': 4.595000000000001},
 {'vessel': 'MSC DARLENE',
  'corrected_date': 29,
  'imo': 9930959,
  'so_2_co_2_ratio': 7.127586206896551},
 {'vessel': 'MSC DONATA',
  'corrected_date': 7,
  'imo': 9237151,
  'so_2_co_2_ratio': 8.72},
 {'vessel': 'MSC DYMPHNA',
  'corrected_date': 17,
  'imo': 9110391,
  'so_2_co_2_ratio': 7.203725490196079},
 {'vessel': 'MSC ELA',
  'corrected_date': 6,
  'imo': 9282259,
  'so_2_co_2_ratio': 6.616666666666667},
 {'vessel': 'MSC ELAINE',
  'corrected_date': 7,
  'imo': 9393321,
  'so_2_co_2_ratio': 5.248571428571429},
 {'vessel': 'MSC ELBE III',
  'corrected_date': 30,
  'imo': 9236688,
  'so_2_co_2_ratio': 5.605833333333334},
 {'vessel': 'MSC ELISA XIII',
  'corrected_date': 1,
  'imo': 9463059,
  'so_2_co_2_ratio': 4.776},
 {'vessel': 'MSC ELMA',
  'corrected_date': 47,
  'imo': 9735218,
  'so_2_co_2_ratio': 7.3695390070921984},
 {'vessel': 'MSC ENGLAND',
  'corrected_date': 18,
  'imo': 9232890,
  'so_2_co_2_ratio': 7.029907407407407},
 {'vessel': 'MSC EUGENIA',
  'corrected_date': 43,
  'imo': 9785469,
  'so_2_co_2_ratio': 7.079476744186047},
 {'vessel': 'MSC FAITH',
  'corrected_date': 25,
  'imo': 9842085,
  'so_2_co_2_ratio': 5.73432},
 {'vessel': 'MSC FIE X',
  'corrected_date': 28,
  'imo': 9120853,
  'so_2_co_2_ratio': 8.564702380952381},
 {'vessel': 'MSC GEMMA',
  'corrected_date': 52,
  'imo': 9936616,
  'so_2_co_2_ratio': 8.340384615384615},
 {'vessel': 'MSC GISELLE',
  'corrected_date': 10,
  'imo': 9720196,
  'so_2_co_2_ratio': 7.559},
 {'vessel': 'MSC GIUSY',
  'corrected_date': 7,
  'imo': 9947134,
  'so_2_co_2_ratio': 5.485714285714286},
 {'vessel': 'MSC HANNAH',
  'corrected_date': 5,
  'imo': 9316347,
  'so_2_co_2_ratio': 4.96},
 {'vessel': 'MSC IMMA III',
  'corrected_date': 4,
  'imo': 9124366,
  'so_2_co_2_ratio': 6.934166666666666},
 {'vessel': 'MSC IRINA',
  'corrected_date': 14,
  'imo': 9929429,
  'so_2_co_2_ratio': 7.124285714285714},
 {'vessel': 'MSC ISABELLA',
  'corrected_date': 105,
  'imo': 9839272,
  'so_2_co_2_ratio': 7.861968253968254},
 {'vessel': 'MSC JAPAN',
  'corrected_date': 26,
  'imo': 9110975,
  'so_2_co_2_ratio': 5.733846153846154},
 {'vessel': 'MSC JEONGMIN',
  'corrected_date': 20,
  'imo': 9720471,
  'so_2_co_2_ratio': 6.252142857142857},
 {'vessel': 'MSC JESSENIA R',
  'corrected_date': 23,
  'imo': 9215672,
  'so_2_co_2_ratio': 7.356014492753623},
 {'vessel': 'MSC JEWEL',
  'corrected_date': 6,
  'imo': 9842073,
  'so_2_co_2_ratio': 6.086111111111111},
 {'vessel': 'MSC JOSSELINE',
  'corrected_date': 10,
  'imo': 9842061,
  'so_2_co_2_ratio': 7.276000000000001},
 {'vessel': 'MSC JULIA R',
  'corrected_date': 4,
  'imo': 9227338,
  'so_2_co_2_ratio': 7.6825},
 {'vessel': 'MSC KALAMATA VII',
  'corrected_date': 1,
  'imo': 9244946,
  'so_2_co_2_ratio': 9.3},
 {'vessel': 'MSC KATRINA',
  'corrected_date': 44,
  'imo': 9467445,
  'so_2_co_2_ratio': 7.314015151515151},
 {'vessel': 'MSC KATYA R',
  'corrected_date': 1,
  'imo': 9227302,
  'so_2_co_2_ratio': 4.6},
 {'vessel': 'MSC KATYAYNI',
  'corrected_date': 2,
  'imo': 9110389,
  'so_2_co_2_ratio': 4.835},
 {'vessel': 'MSC KUMSAL',
  'corrected_date': 2,
  'imo': 9305506,
  'so_2_co_2_ratio': 6.82},
 {'vessel': 'MSC LILOU III',
  'corrected_date': 1,
  'imo': 9334349,
  'so_2_co_2_ratio': 9.9},
 {'vessel': 'MSC LISBON',
  'corrected_date': 41,
  'imo': 9304459,
  'so_2_co_2_ratio': 5.593577235772358},
 {'vessel': 'MSC LONG BEACH VI',
  'corrected_date': 89,
  'imo': 9327803,
  'so_2_co_2_ratio': 11.219775280898876},
 {'vessel': 'MSC LORETO',
  'corrected_date': 85,
  'imo': 9934735,
  'so_2_co_2_ratio': 5.037058823529412},
 {'vessel': 'MSC MADHU B',
  'corrected_date': 1,
  'imo': 9778088,
  'so_2_co_2_ratio': 4.5},
 {'vessel': 'MSC MANZANILLO',
  'corrected_date': 6,
  'imo': 9289960,
  'so_2_co_2_ratio': 4.7},
 {'vessel': 'MSC MARA',
  'corrected_date': 35,
  'imo': 9932892,
  'so_2_co_2_ratio': 4.731428571428571},
 {'vessel': 'MSC MARGRIT',
  'corrected_date': 3,
  'imo': 9465318,
  'so_2_co_2_ratio': 7.07},
 {'vessel': 'MSC MARIELLA',
  'corrected_date': 5,
  'imo': 9934747,
  'so_2_co_2_ratio': 8.080000000000002},
 {'vessel': 'MSC MATTINA',
  'corrected_date': 40,
  'imo': 9315915,
  'so_2_co_2_ratio': 7.85125},
 {'vessel': 'MSC MAXINE',
  'corrected_date': 38,
  'imo': 9720287,
  'so_2_co_2_ratio': 6.068789473684211},
 {'vessel': 'MSC MELINE',
  'corrected_date': 2,
  'imo': 9702077,
  'so_2_co_2_ratio': 4.5},
 {'vessel': 'MSC MELTEMI III',
  'corrected_date': 1,
  'imo': 9440306,
  'so_2_co_2_ratio': 9.0},
 {'vessel': 'MSC MICHEL CAPPELLINI',
  'corrected_date': 6,
  'imo': 9929431,
  'so_2_co_2_ratio': 7.26111111111111},
 {'vessel': 'MSC MICOL',
  'corrected_date': 22,
  'imo': 9931290,
  'so_2_co_2_ratio': 7.155454545454546},
 {'vessel': 'MSC MINA',
  'corrected_date': 35,
  'imo': 9839260,
  'so_2_co_2_ratio': 6.131904761904762},
 {'vessel': 'MSC MONICA III',
  'corrected_date': 4,
  'imo': 9060649,
  'so_2_co_2_ratio': 5.125},
 {'vessel': 'MSC NADRIELY',
  'corrected_date': 7,
  'imo': 9149328,
  'so_2_co_2_ratio': 9.586428571428572},
 {'vessel': 'MSC NASSAU',
  'corrected_date': 1,
  'imo': 9471226,
  'so_2_co_2_ratio': 6.1},
 {'vessel': 'MSC NATASHA XIII',
  'corrected_date': 2,
  'imo': 9463035,
  'so_2_co_2_ratio': 4.45},
 {'vessel': 'MSC NELA',
  'corrected_date': 51,
  'imo': 9839296,
  'so_2_co_2_ratio': 6.094593837535014},
 {'vessel': 'MSC NICOLA MASTRO',
  'corrected_date': 45,
  'imo': 9930064,
  'so_2_co_2_ratio': 7.808888888888888},
 {'vessel': 'MSC NIOVI VIII',
  'corrected_date': 56,
  'imo': 9290488,
  'so_2_co_2_ratio': 8.567857142857143},
 {'vessel': 'MSC NITYA B',
  'corrected_date': 1,
  'imo': 9778117,
  'so_2_co_2_ratio': 4.753333333333333},
 {'vessel': 'MSC NOA',
  'corrected_date': 11,
  'imo': 9398228,
  'so_2_co_2_ratio': 6.371818181818182},
 {'vessel': 'MSC NOA ARIELA',
  'corrected_date': 14,
  'imo': 9946843,
  'so_2_co_2_ratio': 5.712142857142857},
 {'vessel': 'MSC OLIA',
  'corrected_date': 1,
  'imo': 9408774,
  'so_2_co_2_ratio': 4.97},
 {'vessel': 'MSC ORNELLA',
  'corrected_date': 1,
  'imo': 9281267,
  'so_2_co_2_ratio': 4.4},
 {'vessel': 'MSC PALAK',
  'corrected_date': 1,
  'imo': 9735206,
  'so_2_co_2_ratio': 6.32},
 {'vessel': 'MSC PAOLA',
  'corrected_date': 2,
  'imo': 9161297,
  'so_2_co_2_ratio': 5.0},
 {'vessel': 'MSC PARIS',
  'corrected_date': 1,
  'imo': 9301483,
  'so_2_co_2_ratio': 4.5},
 {'vessel': 'MSC PATNAREE III',
  'corrected_date': 5,
  'imo': 9240328,
  'so_2_co_2_ratio': 8.0},
 {'vessel': 'MSC PEGASUS',
  'corrected_date': 1,
  'imo': 9267637,
  'so_2_co_2_ratio': 4.55},
 {'vessel': 'MSC PETRA',
  'corrected_date': 10,
  'imo': 9222302,
  'so_2_co_2_ratio': 4.7125},
 {'vessel': 'MSC PILAR VI',
  'corrected_date': 1,
  'imo': 9248148,
  'so_2_co_2_ratio': 5.2},
 {'vessel': 'MSC RAYSHMI',
  'corrected_date': 54,
  'imo': 9785457,
  'so_2_co_2_ratio': 6.868780864197531},
 {'vessel': 'MSC RENEE',
  'corrected_date': 28,
  'imo': 9465306,
  'so_2_co_2_ratio': 7.5651190476190475},
 {'vessel': 'MSC ROMANE',
  'corrected_date': 30,
  'imo': 9745653,
  'so_2_co_2_ratio': 5.186222222222223},
 {'vessel': 'MSC RUBY',
  'corrected_date': 11,
  'imo': 9502960,
  'so_2_co_2_ratio': 6.033030303030302},
 {'vessel': 'MSC SAGITTA III',
  'corrected_date': 23,
  'imo': 9401166,
  'so_2_co_2_ratio': 7.413043478260869},
 {'vessel': 'MSC SAMANTHA',
  'corrected_date': 2,
  'imo': 9110377,
  'so_2_co_2_ratio': 11.094999999999999},
 {'vessel': 'MSC SAO PAULO',
  'corrected_date': 2,
  'imo': 9147071,
  'so_2_co_2_ratio': 7.029999999999999},
 {'vessel': 'MSC SARA ELENA',
  'corrected_date': 53,
  'imo': 9702261,
  'so_2_co_2_ratio': 6.762578616352202},
 {'vessel': 'MSC SHAHAR',
  'corrected_date': 84,
  'imo': 9471238,
  'so_2_co_2_ratio': 5.510119047619048},
 {'vessel': 'MSC SHANVI III',
  'corrected_date': 20,
  'imo': 9392561,
  'so_2_co_2_ratio': 6.492208333333333},
 {'vessel': 'MSC SHIRLEY',
  'corrected_date': 12,
  'imo': 9224049,
  'so_2_co_2_ratio': 5.611250000000001},
 {'vessel': 'MSC SHUBA B',
  'corrected_date': 3,
  'imo': 9778076,
  'so_2_co_2_ratio': 5.1499999999999995},
 {'vessel': 'MSC SILVER II',
  'corrected_date': 59,
  'imo': 9225249,
  'so_2_co_2_ratio': 11.916242937853108},
 {'vessel': 'MSC SILVIA',
  'corrected_date': 6,
  'imo': 9720457,
  'so_2_co_2_ratio': 7.645},
 {'vessel': 'MSC SINES R',
  'corrected_date': 20,
  'imo': 9210098,
  'so_2_co_2_ratio': 5.596666666666667},
 {'vessel': 'MSC SIXIN',
  'corrected_date': 54,
  'imo': 9839301,
  'so_2_co_2_ratio': 6.967746913580247},
 {'vessel': 'MSC SOFIA CELESTE',
  'corrected_date': 15,
  'imo': 9702091,
  'so_2_co_2_ratio': 6.503333333333333},
 {'vessel': 'MSC SOFIA PAZ',
  'corrected_date': 49,
  'imo': 9695028,
  'so_2_co_2_ratio': 9.761224489795918},
 {'vessel': 'MSC TAMARA',
  'corrected_date': 3,
  'imo': 9351579,
  'so_2_co_2_ratio': 9.733333333333333},
 {'vessel': 'MSC TAMPICO',
  'corrected_date': 42,
  'imo': 9317937,
  'so_2_co_2_ratio': 6.593531746031746},
 {'vessel': 'MSC TESSA',
  'corrected_date': 1,
  'imo': 9930038,
  'so_2_co_2_ratio': 5.4},
 {'vessel': 'MSC TIANPING',
  'corrected_date': 21,
  'imo': 9305489,
  'so_2_co_2_ratio': 7.314761904761904},
 {'vessel': 'MSC TOKYO',
  'corrected_date': 1,
  'imo': 9318046,
  'so_2_co_2_ratio': 5.1},
 {'vessel': 'MSC TUXPAN',
  'corrected_date': 2,
  'imo': 9289972,
  'so_2_co_2_ratio': 5.0},
 {'vessel': 'MSC VALENTINA',
  'corrected_date': 12,
  'imo': 9946855,
  'so_2_co_2_ratio': 5.606944444444444},
 {'vessel': 'MSC VEGA',
  'corrected_date': 7,
  'imo': 9465265,
  'so_2_co_2_ratio': 5.459285714285714},
 {'vessel': 'MSC VIRGO',
  'corrected_date': 6,
  'imo': 9857171,
  'so_2_co_2_ratio': 4.883333333333334},
 {'vessel': 'MSC VITA',
  'corrected_date': 12,
  'imo': 9702089,
  'so_2_co_2_ratio': 5.082777777777777},
 {'vessel': 'MSC VIVIENNE',
  'corrected_date': 9,
  'imo': 9947122,
  'so_2_co_2_ratio': 4.801851851851852},
 {'vessel': 'MSC WAVE F',
  'corrected_date': 1,
  'imo': 9232462,
  'so_2_co_2_ratio': 11.0},
 {'vessel': 'MSC WESER',
  'corrected_date': 13,
  'imo': 9236690,
  'so_2_co_2_ratio': 5.323076923076924},
 {'vessel': 'MSC YASHI B',
  'corrected_date': 22,
  'imo': 9778090,
  'so_2_co_2_ratio': 5.5195454545454545},
 {'vessel': 'MSC YUVIKA V',
  'corrected_date': 1,
  'imo': 9141285,
  'so_2_co_2_ratio': 12.66},
 {'vessel': 'MSC ZLATA R',
  'corrected_date': 10,
  'imo': 9227314,
  'so_2_co_2_ratio': 6.312166666666667},
 {'vessel': 'MSC ABIDJAN',
  'corrected_date': 155,
  'imo': 9618264,
  'so_2_co_2_ratio': 1.5836735483870967},
 {'vessel': 'MSC ABY',
  'corrected_date': 1,
  'imo': 9166778,
  'so_2_co_2_ratio': 4.2},
 {'vessel': 'MSC ACAPULCO',
  'corrected_date': 11,
  'imo': 9401776,
  'so_2_co_2_ratio': 2.0333030303030304},
 {'vessel': 'MSC ADITI',
  'corrected_date': 177,
  'imo': 9235581,
  'so_2_co_2_ratio': 0.9669636803874092},
 {'vessel': 'MSC ADONIS',
  'corrected_date': 97,
  'imo': 9706310,
  'so_2_co_2_ratio': 0.3485910652920962},
 {'vessel': 'MSC AGAMEMNON',
  'corrected_date': 1,
  'imo': 9315381,
  'so_2_co_2_ratio': 1.97},
 {'vessel': 'MSC AGRIGENTO',
  'corrected_date': 69,
  'imo': 9618276,
  'so_2_co_2_ratio': 1.3449782608695653},
 {'vessel': 'MSC ALANYA',
  'corrected_date': 127,
  'imo': 9785483,
  'so_2_co_2_ratio': 1.7211286089238846},
 {'vessel': 'MSC ALDI III',
  'corrected_date': 184,
  'imo': 9341122,
  'so_2_co_2_ratio': 0.3228440734989648},
 {'vessel': 'MSC ALGHERO',
  'corrected_date': 183,
  'imo': 9618288,
  'so_2_co_2_ratio': 1.678131537861046},
 {'vessel': 'MSC ALINA',
  'corrected_date': 91,
  'imo': 9695016,
  'so_2_co_2_ratio': 0.0252014652014652},
 {'vessel': 'MSC ALIYA',
  'corrected_date': 154,
  'imo': 9842097,
  'so_2_co_2_ratio': 1.4643766233766233},
 {'vessel': 'MSC ALTAIR',
  'corrected_date': 114,
  'imo': 9465277,
  'so_2_co_2_ratio': 1.2926023391812864},
 {'vessel': 'MSC AMELIA',
  'corrected_date': 155,
  'imo': 9896995,
  'so_2_co_2_ratio': 1.017505376344086},
 {'vessel': 'MSC AMY',
  'corrected_date': 176,
  'imo': 9242651,
  'so_2_co_2_ratio': 0.1533901515151515},
 {'vessel': 'MSC ANAHITA',
  'corrected_date': 180,
  'imo': 9302085,
  'so_2_co_2_ratio': 0.8469518518518518},
 {'vessel': 'MSC ANISHA R',
  'corrected_date': 159,
  'imo': 9227297,
  'so_2_co_2_ratio': 1.089269392033543},
 {'vessel': 'MSC ANNICK',
  'corrected_date': 9,
  'imo': 9169122,
  'so_2_co_2_ratio': 1.6855555555555555},
 {'vessel': 'MSC ANS',
  'corrected_date': 167,
  'imo': 9282261,
  'so_2_co_2_ratio': 0.42985528942115764},
 {'vessel': 'MSC ANTONELLA',
  'corrected_date': 168,
  'imo': 9702273,
  'so_2_co_2_ratio': 1.6854166666666666},
 {'vessel': 'MSC ANTONIA',
  'corrected_date': 104,
  'imo': 9398216,
  'so_2_co_2_ratio': 1.6019391025641025},
 {'vessel': 'MSC ANYA',
  'corrected_date': 114,
  'imo': 9297864,
  'so_2_co_2_ratio': 0.8738304093567252},
 {'vessel': 'MSC ANZU',
  'corrected_date': 11,
  'imo': 9710426,
  'so_2_co_2_ratio': 1.7466666666666668},
 {'vessel': 'MSC APOLLINE',
  'corrected_date': 162,
  'imo': 9896983,
  'so_2_co_2_ratio': 1.4869650205761316},
 {'vessel': 'MSC ARCHIMIDIS',
  'corrected_date': 1,
  'imo': 9315379,
  'so_2_co_2_ratio': 1.3},
 {'vessel': 'MSC ARICA',
  'corrected_date': 163,
  'imo': 9619452,
  'so_2_co_2_ratio': 0.7066707566462167},
 {'vessel': 'MSC ARIES',
  'corrected_date': 83,
  'imo': 9857169,
  'so_2_co_2_ratio': 0.7615261044176707},
 {'vessel': 'MSC ARINA',
  'corrected_date': 154,
  'imo': 9839284,
  'so_2_co_2_ratio': 1.26512987012987},
 {'vessel': 'MSC ARUSHI R',
  'corrected_date': 182,
  'imo': 9244881,
  'so_2_co_2_ratio': 0.42948260073260075},
 {'vessel': 'MSC ASTRID III',
  'corrected_date': 180,
  'imo': 9263344,
  'so_2_co_2_ratio': 0.8656537037037038},
 {'vessel': 'MSC ATHENS',
  'corrected_date': 151,
  'imo': 9618305,
  'so_2_co_2_ratio': 0.5550496688741722},
 {'vessel': 'MSC ATHOS',
  'corrected_date': 11,
  'imo': 9618317,
  'so_2_co_2_ratio': 0.6343181818181818},
 {'vessel': 'MSC AUBE F',
  'corrected_date': 15,
  'imo': 9360283,
  'so_2_co_2_ratio': 1.21},
 {'vessel': 'MSC AURIGA',
  'corrected_date': 35,
  'imo': 9857183,
  'so_2_co_2_ratio': 0.5767619047619048},
 {'vessel': 'MSC AVNI',
  'corrected_date': 70,
  'imo': 9756729,
  'so_2_co_2_ratio': 1.4810190476190477},
 {'vessel': 'MSC BALTIC III',
  'corrected_date': 1,
  'imo': 9241475,
  'so_2_co_2_ratio': 4.0},
 {'vessel': 'MSC BANU III',
  'corrected_date': 182,
  'imo': 9263332,
  'so_2_co_2_ratio': 1.046808608058608},
 {'vessel': 'MSC BARBARA',
  'corrected_date': 117,
  'imo': 9226932,
  'so_2_co_2_ratio': 1.7995726495726496},
 {'vessel': 'MSC BEIJING',
  'corrected_date': 85,
  'imo': 9289099,
  'so_2_co_2_ratio': 2.149913725490196},
 {'vessel': 'MSC BEIRA IV',
  'corrected_date': 50,
  'imo': 9477309,
  'so_2_co_2_ratio': 1.6011000000000002},
 {'vessel': 'MSC BERANGERE',
  'corrected_date': 95,
  'imo': 9930947,
  'so_2_co_2_ratio': 1.6487719298245613},
 {'vessel': 'MSC BHAVYA',
  'corrected_date': 183,
  'imo': 9297876,
  'so_2_co_2_ratio': 0.09580757220921156},
 {'vessel': 'MSC BIANCA SILVIA',
  'corrected_date': 99,
  'imo': 9930935,
  'so_2_co_2_ratio': 2.424074074074074},
 {'vessel': 'MSC BRANKA',
  'corrected_date': 11,
  'imo': 9720495,
  'so_2_co_2_ratio': 3.3636363636363638},
 {'vessel': 'MSC BREMEN',
  'corrected_date': 140,

In [41]:
scrubber_result

[{'vessel': 'MSC ABIDJAN',
  'imo': 9618264,
  'so2_co2_ppm': 5.24,
  'fuelsulphur': 0.12,
  'scrubber_days': 4},
 {'vessel': 'MSC ABY',
  'imo': 9166778,
  'so2_co2_ppm': 6.24,
  'fuelsulphur': 0.14,
  'scrubber_days': 5},
 {'vessel': 'MSC ACAPULCO',
  'imo': 9401776,
  'so2_co2_ppm': 9.28,
  'fuelsulphur': 0.21,
  'scrubber_days': 19},
 {'vessel': 'MSC ADITI',
  'imo': 9235581,
  'so2_co2_ppm': 6.5,
  'fuelsulphur': 0.15,
  'scrubber_days': 7},
 {'vessel': 'MSC AGRIGENTO',
  'imo': 9618276,
  'so2_co2_ppm': 8.2,
  'fuelsulphur': 0.19,
  'scrubber_days': 4},
 {'vessel': 'MSC ALANYA',
  'imo': 9785483,
  'so2_co2_ppm': 6.21,
  'fuelsulphur': 0.14,
  'scrubber_days': 12},
 {'vessel': 'MSC ALIYA',
  'imo': 9842097,
  'so2_co2_ppm': 7.37,
  'fuelsulphur': 0.17,
  'scrubber_days': 22},
 {'vessel': 'MSC ALTAIR',
  'imo': 9465277,
  'so2_co2_ppm': 7.05,
  'fuelsulphur': 0.16,
  'scrubber_days': 10},
 {'vessel': 'MSC AMELIA',
  'imo': 9896995,
  'so2_co2_ppm': 6.78,
  'fuelsulphur': 0.16,
  'scrubber_days': 25},
 {'vessel': 'MSC ANNICK',
  'imo': 9169122,
  'so2_co2_ppm': 4.34,
  'fuelsulphur': 0.1,
  'scrubber_days': 1},
 {'vessel': 'MSC ANS',
  'imo': 9282261,
  'so2_co2_ppm': 6.0,
  'fuelsulphur': 0.14,
  'scrubber_days': 14},
 {'vessel': 'MSC ANTONELLA',
  'imo': 9702273,
  'so2_co2_ppm': 6.37,
  'fuelsulphur': 0.15,
  'scrubber_days': 9},
 {'vessel': 'MSC ANTONIA',
  'imo': 9398216,
  'so2_co2_ppm': 10.53,
  'fuelsulphur': 0.24,
  'scrubber_days': 12},
 {'vessel': 'MSC ANYA',
  'imo': 9297864,
  'so2_co2_ppm': 8.85,
  'fuelsulphur': 0.2,
  'scrubber_days': 11},
 {'vessel': 'MSC APOLLINE',
  'imo': 9896983,
  'so2_co2_ppm': 5.71,
  'fuelsulphur': 0.13,
  'scrubber_days': 19},
 {'vessel': 'MSC ARCHIMIDIS',
  'imo': 9315379,
  'so2_co2_ppm': 9.34,
  'fuelsulphur': 0.21,
  'scrubber_days': 10},
 {'vessel': 'MSC ARIA III',
  'imo': 9374595,
  'so2_co2_ppm': 5.0,
  'fuelsulphur': 0.11,
  'scrubber_days': 1},
 {'vessel': 'MSC ARICA',
  'imo': 9619452,
  'so2_co2_ppm': 6.15,
  'fuelsulphur': 0.14,
  'scrubber_days': 1},
 {'vessel': 'MSC ARINA',
  'imo': 9839284,
  'so2_co2_ppm': 5.72,
  'fuelsulphur': 0.13,
  'scrubber_days': 21},
 {'vessel': 'MSC ASTRID III',
  'imo': 9263344,
  'so2_co2_ppm': 5.2,
  'fuelsulphur': 0.12,
  'scrubber_days': 2},
 {'vessel': 'MSC AUBE F',
  'imo': 9360283,
  'so2_co2_ppm': 5.52,
  'fuelsulphur': 0.13,
  'scrubber_days': 2},
 {'vessel': 'MSC BANU III',
  'imo': 9263332,
  'so2_co2_ppm': 5.4,
  'fuelsulphur': 0.12,
  'scrubber_days': 1},
 {'vessel': 'MSC BARBARA',
  'imo': 9226932,
  'so2_co2_ppm': 4.4,
  'fuelsulphur': 0.1,
  'scrubber_days': 1},
 {'vessel': 'MSC BEIJING',
  'imo': 9289099,
  'so2_co2_ppm': 4.5,
  'fuelsulphur': 0.1,
  'scrubber_days': 1},
 {'vessel': 'MSC BEIRA IV',
  'imo': 9477309,
  'so2_co2_ppm': 8.16,
  'fuelsulphur': 0.19,
  'scrubber_days': 30},
 {'vessel': 'MSC BERANGERE',
  'imo': 9930947,
  'so2_co2_ppm': 7.33,
  'fuelsulphur': 0.17,
  'scrubber_days': 26},
 {'vessel': 'MSC BIANCA SILVIA',
  'imo': 9930935,
  'so2_co2_ppm': 7.79,
  'fuelsulphur': 0.18,
  'scrubber_days': 75},
 {'vessel': 'MSC BRIANNA',
  'imo': 9103685,
  'so2_co2_ppm': 6.81,
  'fuelsulphur': 0.16,
  'scrubber_days': 54},
 {'vessel': 'MSC BRUNELLA',
  'imo': 9702106,
  'so2_co2_ppm': 4.84,
  'fuelsulphur': 0.11,
  'scrubber_days': 14},
 {'vessel': 'MSC CANCUN',
  'imo': 9403396,
  'so2_co2_ppm': 5.82,
  'fuelsulphur': 0.13,
  'scrubber_days': 44},
 {'vessel': 'MSC CANDIDA',
  'imo': 9946714,
  'so2_co2_ppm': 8.37,
  'fuelsulphur': 0.19,
  'scrubber_days': 21},
 {'vessel': 'MSC CAPRI',
  'imo': 9154220,
  'so2_co2_ppm': 7.1,
  'fuelsulphur': 0.16,
  'scrubber_days': 12},
 {'vessel': 'MSC CAPUCINE R',
  'imo': 9210086,
  'so2_co2_ppm': 6.42,
  'fuelsulphur': 0.15,
  'scrubber_days': 5},
 {'vessel': 'MSC CAROLE',
  'imo': 9785445,
  'so2_co2_ppm': 6.25,
  'fuelsulphur': 0.14,
  'scrubber_days': 8},
 {'vessel': 'MSC CASSANDRE',
  'imo': 9785471,
  'so2_co2_ppm': 5.72,
  'fuelsulphur': 0.13,
  'scrubber_days': 39},
 {'vessel': 'MSC CATERINA',
  'imo': 9705005,
  'so2_co2_ppm': 5.5,
  'fuelsulphur': 0.13,
  'scrubber_days': 15},
 {'vessel': 'MSC CELINE',
  'imo': 9316361,
  'so2_co2_ppm': 5.49,
  'fuelsulphur': 0.13,
  'scrubber_days': 4},
 {'vessel': 'MSC CHARLESTON',
  'imo': 9299537,
  'so2_co2_ppm': 5.5,
  'fuelsulphur': 0.13,
  'scrubber_days': 2},
 {'vessel': 'MSC CHIYO',
  'imo': 9947110,
  'so2_co2_ppm': 6.63,
  'fuelsulphur': 0.15,
  'scrubber_days': 15},
 {'vessel': 'MSC CHLOE',
  'imo': 9720483,
  'so2_co2_ppm': 9.54,
  'fuelsulphur': 0.22,
  'scrubber_days': 2},
 {'vessel': 'MSC CLAUDE GIRARDET',
  'imo': 9936628,
  'so2_co2_ppm': 6.76,
  'fuelsulphur': 0.16,
  'scrubber_days': 23},
 {'vessel': 'MSC CLEA',
  'imo': 9720524,
  'so2_co2_ppm': 7.32,
  'fuelsulphur': 0.17,
  'scrubber_days': 18},
 {'vessel': 'MSC CORINNA',
  'imo': 9307267,
  'so2_co2_ppm': 5.3,
  'fuelsulphur': 0.12,
  'scrubber_days': 2},
 {'vessel': 'MSC CRISTINA',
  'imo': 9465241,
  'so2_co2_ppm': 8.44,
  'fuelsulphur': 0.19,
  'scrubber_days': 10},
 {'vessel': 'MSC DAMLA',
  'imo': 9250983,
  'so2_co2_ppm': 4.6,
  'fuelsulphur': 0.11,
  'scrubber_days': 2},
 {'vessel': 'MSC DARLENE',
  'imo': 9930959,
  'so2_co2_ppm': 7.13,
  'fuelsulphur': 0.16,
  'scrubber_days': 29},
 {'vessel': 'MSC DONATA',
  'imo': 9237151,
  'so2_co2_ppm': 8.72,
  'fuelsulphur': 0.2,
  'scrubber_days': 7},
 {'vessel': 'MSC DYMPHNA',
  'imo': 9110391,
  'so2_co2_ppm': 7.2,
  'fuelsulphur': 0.17,
  'scrubber_days': 17},
 {'vessel': 'MSC ELA',
  'imo': 9282259,
  'so2_co2_ppm': 6.62,
  'fuelsulphur': 0.15,
  'scrubber_days': 6},
 {'vessel': 'MSC ELAINE',
  'imo': 9393321,
  'so2_co2_ppm': 5.25,
  'fuelsulphur': 0.12,
  'scrubber_days': 7},
 {'vessel': 'MSC ELBE III',
  'imo': 9236688,
  'so2_co2_ppm': 5.61,
  'fuelsulphur': 0.13,
  'scrubber_days': 30},
 {'vessel': 'MSC ELISA XIII',
  'imo': 9463059,
  'so2_co2_ppm': 4.78,
  'fuelsulphur': 0.11,
  'scrubber_days': 1},
 {'vessel': 'MSC ELMA',
  'imo': 9735218,
  'so2_co2_ppm': 7.37,
  'fuelsulphur': 0.17,
  'scrubber_days': 47},
 {'vessel': 'MSC ENGLAND',
  'imo': 9232890,
  'so2_co2_ppm': 7.03,
  'fuelsulphur': 0.16,
  'scrubber_days': 18},
 {'vessel': 'MSC EUGENIA',
  'imo': 9785469,
  'so2_co2_ppm': 7.08,
  'fuelsulphur': 0.16,
  'scrubber_days': 43},
 {'vessel': 'MSC FAITH',
  'imo': 9842085,
  'so2_co2_ppm': 5.73,
  'fuelsulphur': 0.13,
  'scrubber_days': 25},
 {'vessel': 'MSC FIE X',
  'imo': 9120853,
  'so2_co2_ppm': 8.56,
  'fuelsulphur': 0.2,
  'scrubber_days': 28},
 {'vessel': 'MSC GEMMA',
  'imo': 9936616,
  'so2_co2_ppm': 8.34,
  'fuelsulphur': 0.19,
  'scrubber_days': 52},
 {'vessel': 'MSC GISELLE',
  'imo': 9720196,
  'so2_co2_ppm': 7.56,
  'fuelsulphur': 0.17,
  'scrubber_days': 10},
 {'vessel': 'MSC GIUSY',
  'imo': 9947134,
  'so2_co2_ppm': 5.49,
  'fuelsulphur': 0.13,
  'scrubber_days': 7},
 {'vessel': 'MSC HANNAH',
  'imo': 9316347,
  'so2_co2_ppm': 4.96,
  'fuelsulphur': 0.11,
  'scrubber_days': 5},
 {'vessel': 'MSC IMMA III',
  'imo': 9124366,
  'so2_co2_ppm': 6.93,
  'fuelsulphur': 0.16,
  'scrubber_days': 4},
 {'vessel': 'MSC IRINA',
  'imo': 9929429,
  'so2_co2_ppm': 7.12,
  'fuelsulphur': 0.16,
  'scrubber_days': 14},
 {'vessel': 'MSC ISABELLA',
  'imo': 9839272,
  'so2_co2_ppm': 7.86,
  'fuelsulphur': 0.18,
  'scrubber_days': 105},
 {'vessel': 'MSC JAPAN',
  'imo': 9110975,
  'so2_co2_ppm': 5.73,
  'fuelsulphur': 0.13,
  'scrubber_days': 26},
 {'vessel': 'MSC JEONGMIN',
  'imo': 9720471,
  'so2_co2_ppm': 6.25,
  'fuelsulphur': 0.14,
  'scrubber_days': 20},
 {'vessel': 'MSC JESSENIA R',
  'imo': 9215672,
  'so2_co2_ppm': 7.36,
  'fuelsulphur': 0.17,
  'scrubber_days': 23},
 {'vessel': 'MSC JEWEL',
  'imo': 9842073,
  'so2_co2_ppm': 6.09,
  'fuelsulphur': 0.14,
  'scrubber_days': 6},
 {'vessel': 'MSC JOSSELINE',
  'imo': 9842061,
  'so2_co2_ppm': 7.28,
  'fuelsulphur': 0.17,
  'scrubber_days': 10},
 {'vessel': 'MSC JULIA R',
  'imo': 9227338,
  'so2_co2_ppm': 7.68,
  'fuelsulphur': 0.18,
  'scrubber_days': 4},
 {'vessel': 'MSC KALAMATA VII',
  'imo': 9244946,
  'so2_co2_ppm': 9.3,
  'fuelsulphur': 0.21,
  'scrubber_days': 1},
 {'vessel': 'MSC KATRINA',
  'imo': 9467445,
  'so2_co2_ppm': 7.31,
  'fuelsulphur': 0.17,
  'scrubber_days': 44},
 {'vessel': 'MSC KATYA R',
  'imo': 9227302,
  'so2_co2_ppm': 4.6,
  'fuelsulphur': 0.11,
  'scrubber_days': 1},
 {'vessel': 'MSC KATYAYNI',
  'imo': 9110389,
  'so2_co2_ppm': 4.83,
  'fuelsulphur': 0.11,
  'scrubber_days': 2},
 {'vessel': 'MSC KUMSAL',
  'imo': 9305506,
  'so2_co2_ppm': 6.82,
  'fuelsulphur': 0.16,
  'scrubber_days': 2},
 {'vessel': 'MSC LILOU III',
  'imo': 9334349,
  'so2_co2_ppm': 9.9,
  'fuelsulphur': 0.23,
  'scrubber_days': 1},
 {'vessel': 'MSC LISBON',
  'imo': 9304459,
  'so2_co2_ppm': 5.59,
  'fuelsulphur': 0.13,
  'scrubber_days': 41},
 {'vessel': 'MSC LONG BEACH VI',
  'imo': 9327803,
  'so2_co2_ppm': 11.22,
  'fuelsulphur': 0.26,
  'scrubber_days': 89},
 {'vessel': 'MSC LORETO',
  'imo': 9934735,
  'so2_co2_ppm': 5.04,
  'fuelsulphur': 0.12,
  'scrubber_days': 85},
 {'vessel': 'MSC MADHU B',
  'imo': 9778088,
  'so2_co2_ppm': 4.5,
  'fuelsulphur': 0.1,
  'scrubber_days': 1},
 {'vessel': 'MSC MANZANILLO',
  'imo': 9289960,
  'so2_co2_ppm': 4.7,
  'fuelsulphur': 0.11,
  'scrubber_days': 6},
 {'vessel': 'MSC MARA',
  'imo': 9932892,
  'so2_co2_ppm': 4.73,
  'fuelsulphur': 0.11,
  'scrubber_days': 35},
 {'vessel': 'MSC MARGRIT',
  'imo': 9465318,
  'so2_co2_ppm': 7.07,
  'fuelsulphur': 0.16,
  'scrubber_days': 3},
 {'vessel': 'MSC MARIELLA',
  'imo': 9934747,
  'so2_co2_ppm': 8.08,
  'fuelsulphur': 0.19,
  'scrubber_days': 5},
 {'vessel': 'MSC MATTINA',
  'imo': 9315915,
  'so2_co2_ppm': 7.85,
  'fuelsulphur': 0.18,
  'scrubber_days': 40},
 {'vessel': 'MSC MAXINE',
  'imo': 9720287,
  'so2_co2_ppm': 6.07,
  'fuelsulphur': 0.14,
  'scrubber_days': 38},
 {'vessel': 'MSC MELINE',
  'imo': 9702077,
  'so2_co2_ppm': 4.5,
  'fuelsulphur': 0.1,
  'scrubber_days': 2},
 {'vessel': 'MSC MELTEMI III',
  'imo': 9440306,
  'so2_co2_ppm': 9.0,
  'fuelsulphur': 0.21,
  'scrubber_days': 1},
 {'vessel': 'MSC MICHEL CAPPELLINI',
  'imo': 9929431,
  'so2_co2_ppm': 7.26,
  'fuelsulphur': 0.17,
  'scrubber_days': 6},
 {'vessel': 'MSC MICOL',
  'imo': 9931290,
  'so2_co2_ppm': 7.16,
  'fuelsulphur': 0.16,
  'scrubber_days': 22},
 {'vessel': 'MSC MINA',
  'imo': 9839260,
  'so2_co2_ppm': 6.13,
  'fuelsulphur': 0.14,
  'scrubber_days': 35},
 {'vessel': 'MSC MONICA III',
  'imo': 9060649,
  'so2_co2_ppm': 5.12,
  'fuelsulphur': 0.12,
  'scrubber_days': 4},
 {'vessel': 'MSC NADRIELY',
  'imo': 9149328,
  'so2_co2_ppm': 9.59,
  'fuelsulphur': 0.22,
  'scrubber_days': 7},
 {'vessel': 'MSC NASSAU',
  'imo': 9471226,
  'so2_co2_ppm': 6.1,
  'fuelsulphur': 0.14,
  'scrubber_days': 1},
 {'vessel': 'MSC NATASHA XIII',
  'imo': 9463035,
  'so2_co2_ppm': 4.45,
  'fuelsulphur': 0.1,
  'scrubber_days': 2},
 {'vessel': 'MSC NELA',
  'imo': 9839296,
  'so2_co2_ppm': 6.09,
  'fuelsulphur': 0.14,
  'scrubber_days': 51},
 {'vessel': 'MSC NICOLA MASTRO',
  'imo': 9930064,
  'so2_co2_ppm': 7.81,
  'fuelsulphur': 0.18,
  'scrubber_days': 45},
 {'vessel': 'MSC NIOVI VIII',
  'imo': 9290488,
  'so2_co2_ppm': 8.57,
  'fuelsulphur': 0.2,
  'scrubber_days': 56},
 {'vessel': 'MSC NITYA B',
  'imo': 9778117,
  'so2_co2_ppm': 4.75,
  'fuelsulphur': 0.11,
  'scrubber_days': 1},
 {'vessel': 'MSC NOA',
  'imo': 9398228,
  'so2_co2_ppm': 6.37,
  'fuelsulphur': 0.15,
  'scrubber_days': 11},
 {'vessel': 'MSC NOA ARIELA',
  'imo': 9946843,
  'so2_co2_ppm': 5.71,
  'fuelsulphur': 0.13,
  'scrubber_days': 14},
 {'vessel': 'MSC OLIA',
  'imo': 9408774,
  'so2_co2_ppm': 4.97,
  'fuelsulphur': 0.11,
  'scrubber_days': 1},
 {'vessel': 'MSC ORNELLA',
  'imo': 9281267,
  'so2_co2_ppm': 4.4,
  'fuelsulphur': 0.1,
  'scrubber_days': 1},
 {'vessel': 'MSC PALAK',
  'imo': 9735206,
  'so2_co2_ppm': 6.32,
  'fuelsulphur': 0.15,
  'scrubber_days': 1},
 {'vessel': 'MSC PAOLA',
  'imo': 9161297,
  'so2_co2_ppm': 5.0,
  'fuelsulphur': 0.11,
  'scrubber_days': 2},
 {'vessel': 'MSC PARIS',
  'imo': 9301483,
  'so2_co2_ppm': 4.5,
  'fuelsulphur': 0.1,
  'scrubber_days': 1},
 {'vessel': 'MSC PATNAREE III',
  'imo': 9240328,
  'so2_co2_ppm': 8.0,
  'fuelsulphur': 0.18,
  'scrubber_days': 5},
 {'vessel': 'MSC PEGASUS',
  'imo': 9267637,
  'so2_co2_ppm': 4.55,
  'fuelsulphur': 0.1,
  'scrubber_days': 1},
 {'vessel': 'MSC PETRA',
  'imo': 9222302,
  'so2_co2_ppm': 4.71,
  'fuelsulphur': 0.11,
  'scrubber_days': 10},
 {'vessel': 'MSC PILAR VI',
  'imo': 9248148,
  'so2_co2_ppm': 5.2,
  'fuelsulphur': 0.12,
  'scrubber_days': 1},
 {'vessel': 'MSC RAYSHMI',
  'imo': 9785457,
  'so2_co2_ppm': 6.87,
  'fuelsulphur': 0.16,
  'scrubber_days': 54},
 {'vessel': 'MSC RENEE',
  'imo': 9465306,
  'so2_co2_ppm': 7.57,
  'fuelsulphur': 0.17,
  'scrubber_days': 28},
 {'vessel': 'MSC ROMANE',
  'imo': 9745653,
  'so2_co2_ppm': 5.19,
  'fuelsulphur': 0.12,
  'scrubber_days': 30},
 {'vessel': 'MSC RUBY',
  'imo': 9502960,
  'so2_co2_ppm': 6.03,
  'fuelsulphur': 0.14,
  'scrubber_days': 11},
 {'vessel': 'MSC SAGITTA III',
  'imo': 9401166,
  'so2_co2_ppm': 7.41,
  'fuelsulphur': 0.17,
  'scrubber_days': 23},
 {'vessel': 'MSC SAMANTHA',
  'imo': 9110377,
  'so2_co2_ppm': 11.09,
  'fuelsulphur': 0.26,
  'scrubber_days': 2},
 {'vessel': 'MSC SAO PAULO',
  'imo': 9147071,
  'so2_co2_ppm': 7.03,
  'fuelsulphur': 0.16,
  'scrubber_days': 2},
 {'vessel': 'MSC SARA ELENA',
  'imo': 9702261,
  'so2_co2_ppm': 6.76,
  'fuelsulphur': 0.16,
  'scrubber_days': 53},
 {'vessel': 'MSC SHAHAR',
  'imo': 9471238,
  'so2_co2_ppm': 5.51,
  'fuelsulphur': 0.13,
  'scrubber_days': 84},
 {'vessel': 'MSC SHANVI III',
  'imo': 9392561,
  'so2_co2_ppm': 6.49,
  'fuelsulphur': 0.15,
  'scrubber_days': 20},
 {'vessel': 'MSC SHIRLEY',
  'imo': 9224049,
  'so2_co2_ppm': 5.61,
  'fuelsulphur': 0.13,
  'scrubber_days': 12},
 {'vessel': 'MSC SHUBA B',
  'imo': 9778076,
  'so2_co2_ppm': 5.15,
  'fuelsulphur': 0.12,
  'scrubber_days': 3},
 {'vessel': 'MSC SILVER II',
  'imo': 9225249,
  'so2_co2_ppm': 11.92,
  'fuelsulphur': 0.27,
  'scrubber_days': 59},
 {'vessel': 'MSC SILVIA',
  'imo': 9720457,
  'so2_co2_ppm': 7.64,
  'fuelsulphur': 0.18,
  'scrubber_days': 6},
 {'vessel': 'MSC SINES R',
  'imo': 9210098,
  'so2_co2_ppm': 5.6,
  'fuelsulphur': 0.13,
  'scrubber_days': 20},
 {'vessel': 'MSC SIXIN',
  'imo': 9839301,
  'so2_co2_ppm': 6.97,
  'fuelsulphur': 0.16,
  'scrubber_days': 54},
 {'vessel': 'MSC SOFIA CELESTE',
  'imo': 9702091,
  'so2_co2_ppm': 6.5,
  'fuelsulphur': 0.15,
  'scrubber_days': 15},
 {'vessel': 'MSC SOFIA PAZ',
  'imo': 9695028,
  'so2_co2_ppm': 9.76,
  'fuelsulphur': 0.22,
  'scrubber_days': 49},
 {'vessel': 'MSC TAMARA',
  'imo': 9351579,
  'so2_co2_ppm': 9.73,
  'fuelsulphur': 0.22,
  'scrubber_days': 3},
 {'vessel': 'MSC TAMPICO',
  'imo': 9317937,
  'so2_co2_ppm': 6.59,
  'fuelsulphur': 0.15,
  'scrubber_days': 42},
 {'vessel': 'MSC TESSA',
  'imo': 9930038,
  'so2_co2_ppm': 5.4,
  'fuelsulphur': 0.12,
  'scrubber_days': 1},
 {'vessel': 'MSC TIANPING',
  'imo': 9305489,
  'so2_co2_ppm': 7.31,
  'fuelsulphur': 0.17,
  'scrubber_days': 21},
 {'vessel': 'MSC TOKYO',
  'imo': 9318046,
  'so2_co2_ppm': 5.1,
  'fuelsulphur': 0.12,
  'scrubber_days': 1},
 {'vessel': 'MSC TUXPAN',
  'imo': 9289972,
  'so2_co2_ppm': 5.0,
  'fuelsulphur': 0.11,
  'scrubber_days': 2},
 {'vessel': 'MSC VALENTINA',
  'imo': 9946855,
  'so2_co2_ppm': 5.61,
  'fuelsulphur': 0.13,
  'scrubber_days': 12},
 {'vessel': 'MSC VEGA',
  'imo': 9465265,
  'so2_co2_ppm': 5.46,
  'fuelsulphur': 0.13,
  'scrubber_days': 7},
 {'vessel': 'MSC VIRGO',
  'imo': 9857171,
  'so2_co2_ppm': 4.88,
  'fuelsulphur': 0.11,
  'scrubber_days': 6},
 {'vessel': 'MSC VITA',
  'imo': 9702089,
  'so2_co2_ppm': 5.08,
  'fuelsulphur': 0.12,
  'scrubber_days': 12},
 {'vessel': 'MSC VIVIENNE',
  'imo': 9947122,
  'so2_co2_ppm': 4.8,
  'fuelsulphur': 0.11,
  'scrubber_days': 9},
 {'vessel': 'MSC WAVE F',
  'imo': 9232462,
  'so2_co2_ppm': 11.0,
  'fuelsulphur': 0.25,
  'scrubber_days': 1},
 {'vessel': 'MSC WESER',
  'imo': 9236690,
  'so2_co2_ppm': 5.32,
  'fuelsulphur': 0.12,
  'scrubber_days': 13},
 {'vessel': 'MSC YASHI B',
  'imo': 9778090,
  'so2_co2_ppm': 5.52,
  'fuelsulphur': 0.13,
  'scrubber_days': 22},
 {'vessel': 'MSC YUVIKA V',
  'imo': 9141285,
  'so2_co2_ppm': 12.66,
  'fuelsulphur': 0.29,
  'scrubber_days': 1},
 {'vessel': 'MSC ZLATA R',
  'imo': 9227314,
  'so2_co2_ppm': 6.31,
  'fuelsulphur': 0.15,
  'scrubber_days': 10},
 {'vessel': 'MSC ABIDJAN',
  'imo': 9618264,
  'so2_co2_ppm': 1.58,
  'fuelsulphur': 0.04,
  'scrubber_days': 155},
 {'vessel': 'MSC ABY',
  'imo': 9166778,
  'so2_co2_ppm': 4.2,
  'fuelsulphur': 0.1,
  'scrubber_days': 1},
 {'vessel': 'MSC ACAPULCO',
  'imo': 9401776,
  'so2_co2_ppm': 2.03,
  'fuelsulphur': 0.05,
  'scrubber_days': 11},
 {'vessel': 'MSC ADITI',
  'imo': 9235581,
  'so2_co2_ppm': 0.97,
  'fuelsulphur': 0.02,
  'scrubber_days': 177},
 {'vessel': 'MSC ADONIS',
  'imo': 9706310,
  'so2_co2_ppm': 0.35,
  'fuelsulphur': 0.01,
  'scrubber_days': 97},
 {'vessel': 'MSC AGAMEMNON',
  'imo': 9315381,
  'so2_co2_ppm': 1.97,
  'fuelsulphur': 0.05,
  'scrubber_days': 1},
 {'vessel': 'MSC AGRIGENTO',
  'imo': 9618276,
  'so2_co2_ppm': 1.34,
  'fuelsulphur': 0.03,
  'scrubber_days': 69},
 {'vessel': 'MSC ALANYA',
  'imo': 9785483,
  'so2_co2_ppm': 1.72,
  'fuelsulphur': 0.04,
  'scrubber_days': 127},
 {'vessel': 'MSC ALDI III',
  'imo': 9341122,
  'so2_co2_ppm': 0.32,
  'fuelsulphur': 0.01,
  'scrubber_days': 184},
 {'vessel': 'MSC ALGHERO',
  'imo': 9618288,
  'so2_co2_ppm': 1.68,
  'fuelsulphur': 0.04,
  'scrubber_days': 183},
 {'vessel': 'MSC ALINA',
  'imo': 9695016,
  'so2_co2_ppm': 0.03,
  'fuelsulphur': 0.0,
  'scrubber_days': 91},
 {'vessel': 'MSC ALIYA',
  'imo': 9842097,
  'so2_co2_ppm': 1.46,
  'fuelsulphur': 0.03,
  'scrubber_days': 154},
 {'vessel': 'MSC ALTAIR',
  'imo': 9465277,
  'so2_co2_ppm': 1.29,
  'fuelsulphur': 0.03,
  'scrubber_days': 114},
 {'vessel': 'MSC AMELIA',
  'imo': 9896995,
  'so2_co2_ppm': 1.02,
  'fuelsulphur': 0.02,
  'scrubber_days': 155},
 {'vessel': 'MSC AMY',
  'imo': 9242651,
  'so2_co2_ppm': 0.15,
  'fuelsulphur': 0.0,
  'scrubber_days': 176},
 {'vessel': 'MSC ANAHITA',
  'imo': 9302085,
  'so2_co2_ppm': 0.85,
  'fuelsulphur': 0.02,
  'scrubber_days': 180},
 {'vessel': 'MSC ANISHA R',
  'imo': 9227297,
  'so2_co2_ppm': 1.09,
  'fuelsulphur': 0.03,
  'scrubber_days': 159},
 {'vessel': 'MSC ANNICK',
  'imo': 9169122,
  'so2_co2_ppm': 1.69,
  'fuelsulphur': 0.04,
  'scrubber_days': 9},
 {'vessel': 'MSC ANS',
  'imo': 9282261,
  'so2_co2_ppm': 0.43,
  'fuelsulphur': 0.01,
  'scrubber_days': 167},
 {'vessel': 'MSC ANTONELLA',
  'imo': 9702273,
  'so2_co2_ppm': 1.69,
  'fuelsulphur': 0.04,
  'scrubber_days': 168},
 {'vessel': 'MSC ANTONIA',
  'imo': 9398216,
  'so2_co2_ppm': 1.6,
  'fuelsulphur': 0.04,
  'scrubber_days': 104},
 {'vessel': 'MSC ANYA',
  'imo': 9297864,
  'so2_co2_ppm': 0.87,
  'fuelsulphur': 0.02,
  'scrubber_days': 114},
 {'vessel': 'MSC ANZU',
  'imo': 9710426,
  'so2_co2_ppm': 1.75,
  'fuelsulphur': 0.04,
  'scrubber_days': 11},
 {'vessel': 'MSC APOLLINE',
  'imo': 9896983,
  'so2_co2_ppm': 1.49,
  'fuelsulphur': 0.03,
  'scrubber_days': 162},
 {'vessel': 'MSC ARCHIMIDIS',
  'imo': 9315379,
  'so2_co2_ppm': 1.3,
  'fuelsulphur': 0.03,
  'scrubber_days': 1},
 {'vessel': 'MSC ARICA',
  'imo': 9619452,
  'so2_co2_ppm': 0.71,
  'fuelsulphur': 0.02,
  'scrubber_days': 163},
 {'vessel': 'MSC ARIES',
  'imo': 9857169,
  'so2_co2_ppm': 0.76,
  'fuelsulphur': 0.02,
  'scrubber_days': 83},
 {'vessel': 'MSC ARINA',
  'imo': 9839284,
  'so2_co2_ppm': 1.27,
  'fuelsulphur': 0.03,
  'scrubber_days': 154},
 {'vessel': 'MSC ARUSHI R',
  'imo': 9244881,
  'so2_co2_ppm': 0.43,
  'fuelsulphur': 0.01,
  'scrubber_days': 182},
 {'vessel': 'MSC ASTRID III',
  'imo': 9263344,
  'so2_co2_ppm': 0.87,
  'fuelsulphur': 0.02,
  'scrubber_days': 180},
 {'vessel': 'MSC ATHENS',
  'imo': 9618305,
  'so2_co2_ppm': 0.56,

In [42]:
# Ensure 'vessel' key exists in all dictionaries before sorting
scrubber_result = sorted(scrubber_result, key=lambda x: x.get('imo', ''))

In [43]:
scrubber_result

[{'vessel': 'MSC SARISKA V',
  'imo': 8715857,
  'so2_co2_ppm': 2.0,
  'fuelsulphur': 0.05,
  'scrubber_days': 1},
 {'vessel': 'MSC SANTHYA',
  'imo': 8913411,
  'so2_co2_ppm': 0.36,
  'fuelsulphur': 0.01,
  'scrubber_days': 168},
 {'vessel': 'MSC JORDAN',
  'imo': 8918980,
  'so2_co2_ppm': 1.0,
  'fuelsulphur': 0.02,
  'scrubber_days': 2},
 {'vessel': 'MSC TASMANIA',
  'imo': 9008574,
  'so2_co2_ppm': 0.46,
  'fuelsulphur': 0.01,
  'scrubber_days': 144},
 {'vessel': 'MSC ROBERTA V',
  'imo': 9038907,
  'so2_co2_ppm': 0.58,
  'fuelsulphur': 0.01,
  'scrubber_days': 83},
 {'vessel': 'MSC MONICA III',
  'imo': 9060649,
  'so2_co2_ppm': 5.12,
  'fuelsulphur': 0.12,
  'scrubber_days': 4},
 {'vessel': 'MSC MONICA III',
  'imo': 9060649,
  'so2_co2_ppm': 1.9,
  'fuelsulphur': 0.04,
  'scrubber_days': 102},
 {'vessel': 'MSC POLARIS',
  'imo': 9074042,
  'so2_co2_ppm': 0.31,
  'fuelsulphur': 0.01,
  'scrubber_days': 125},
 {'vessel': 'MSC BRIANNA',
  'imo': 9103685,
  'so2_co2_ppm': 6.81,
  'fuelsulphur': 0.16,
  'scrubber_days': 54},
 {'vessel': 'MSC BRIANNA',
  'imo': 9103685,
  'so2_co2_ppm': 4.23,
  'fuelsulphur': 0.1,
  'scrubber_days': 1},
 {'vessel': 'MSC SAMANTHA',
  'imo': 9110377,
  'so2_co2_ppm': 11.09,
  'fuelsulphur': 0.26,
  'scrubber_days': 2},
 {'vessel': 'MSC SAMANTHA',
  'imo': 9110377,
  'so2_co2_ppm': 1.66,
  'fuelsulphur': 0.04,
  'scrubber_days': 66},
 {'vessel': 'MSC KATYAYNI',
  'imo': 9110389,
  'so2_co2_ppm': 4.83,
  'fuelsulphur': 0.11,
  'scrubber_days': 2},
 {'vessel': 'MSC KATYAYNI',
  'imo': 9110389,
  'so2_co2_ppm': 0.36,
  'fuelsulphur': 0.01,
  'scrubber_days': 30},
 {'vessel': 'MSC DYMPHNA',
  'imo': 9110391,
  'so2_co2_ppm': 7.2,
  'fuelsulphur': 0.17,
  'scrubber_days': 17},
 {'vessel': 'MSC DYMPHNA',
  'imo': 9110391,
  'so2_co2_ppm': 2.48,
  'fuelsulphur': 0.06,
  'scrubber_days': 161},
 {'vessel': 'MSC JAPAN',
  'imo': 9110975,
  'so2_co2_ppm': 5.73,
  'fuelsulphur': 0.13,
  'scrubber_days': 26},
 {'vessel': 'MSC JAPAN',
  'imo': 9110975,
  'so2_co2_ppm': 2.22,
  'fuelsulphur': 0.05,
  'scrubber_days': 151},
 {'vessel': 'MSC FIE X',
  'imo': 9120853,
  'so2_co2_ppm': 8.56,
  'fuelsulphur': 0.2,
  'scrubber_days': 28},
 {'vessel': 'MSC FIE X',
  'imo': 9120853,
  'so2_co2_ppm': 1.2,
  'fuelsulphur': 0.03,
  'scrubber_days': 145},
 {'vessel': 'MSC KOREA',
  'imo': 9123154,
  'so2_co2_ppm': 0.11,
  'fuelsulphur': 0.0,
  'scrubber_days': 93},
 {'vessel': 'MSC IMMA III',
  'imo': 9124366,
  'so2_co2_ppm': 6.93,
  'fuelsulphur': 0.16,
  'scrubber_days': 4},
 {'vessel': 'MSC IMMA III',
  'imo': 9124366,
  'so2_co2_ppm': 0.82,
  'fuelsulphur': 0.02,
  'scrubber_days': 159},
 {'vessel': 'MSC CARLA III',
  'imo': 9124512,
  'so2_co2_ppm': 0.75,
  'fuelsulphur': 0.02,
  'scrubber_days': 155},
 {'vessel': 'MSC REBECCA III',
  'imo': 9139505,
  'so2_co2_ppm': 0.93,
  'fuelsulphur': 0.02,
  'scrubber_days': 97},
 {'vessel': 'MSC YUVIKA V',
  'imo': 9141285,
  'so2_co2_ppm': 12.66,
  'fuelsulphur': 0.29,
  'scrubber_days': 1},
 {'vessel': 'MSC YUVIKA V',
  'imo': 9141285,
  'so2_co2_ppm': 2.81,
  'fuelsulphur': 0.06,
  'scrubber_days': 182},
 {'vessel': 'MSC RIONA',
  'imo': 9144134,
  'so2_co2_ppm': 0.4,
  'fuelsulphur': 0.01,
  'scrubber_days': 120},
 {'vessel': 'MSC SAO PAULO',
  'imo': 9147071,
  'so2_co2_ppm': 7.03,
  'fuelsulphur': 0.16,
  'scrubber_days': 2},
 {'vessel': 'MSC SAO PAULO',
  'imo': 9147071,
  'so2_co2_ppm': 1.02,
  'fuelsulphur': 0.02,
  'scrubber_days': 78},
 {'vessel': 'MSC NADRIELY',
  'imo': 9149328,
  'so2_co2_ppm': 9.59,
  'fuelsulphur': 0.22,
  'scrubber_days': 7},
 {'vessel': 'MSC NADRIELY',
  'imo': 9149328,
  'so2_co2_ppm': 0.34,
  'fuelsulphur': 0.01,
  'scrubber_days': 2},
 {'vessel': 'MSC POSITANO',
  'imo': 9154191,
  'so2_co2_ppm': 3.21,
  'fuelsulphur': 0.07,
  'scrubber_days': 70},
 {'vessel': 'MSC CAPRI',
  'imo': 9154220,
  'so2_co2_ppm': 7.1,
  'fuelsulphur': 0.16,
  'scrubber_days': 12},
 {'vessel': 'MSC CAPRI',
  'imo': 9154220,
  'so2_co2_ppm': 0.57,
  'fuelsulphur': 0.01,
  'scrubber_days': 158},
 {'vessel': 'MSC MARIA PIA',
  'imo': 9155107,
  'so2_co2_ppm': 0.57,
  'fuelsulphur': 0.01,
  'scrubber_days': 82},
 {'vessel': 'MSC PAOLA',
  'imo': 9161297,
  'so2_co2_ppm': 5.0,
  'fuelsulphur': 0.11,
  'scrubber_days': 2},
 {'vessel': 'MSC PAOLA',
  'imo': 9161297,
  'so2_co2_ppm': 0.35,
  'fuelsulphur': 0.01,
  'scrubber_days': 172},
 {'vessel': 'MSC ABY',
  'imo': 9166778,
  'so2_co2_ppm': 6.24,
  'fuelsulphur': 0.14,
  'scrubber_days': 5},
 {'vessel': 'MSC ABY',
  'imo': 9166778,
  'so2_co2_ppm': 4.2,
  'fuelsulphur': 0.1,
  'scrubber_days': 1},
 {'vessel': 'MSC ELLEN',
  'imo': 9166780,
  'so2_co2_ppm': 0.38,
  'fuelsulphur': 0.01,
  'scrubber_days': 165},
 {'vessel': 'MSC ANNICK',
  'imo': 9169122,
  'so2_co2_ppm': 4.34,
  'fuelsulphur': 0.1,
  'scrubber_days': 1},
 {'vessel': 'MSC ANNICK',
  'imo': 9169122,
  'so2_co2_ppm': 1.69,
  'fuelsulphur': 0.04,
  'scrubber_days': 9},
 {'vessel': 'MSC INGRID',
  'imo': 9181651,
  'so2_co2_ppm': 0.44,
  'fuelsulphur': 0.01,
  'scrubber_days': 18},
 {'vessel': 'MSC MATILDE V',
  'imo': 9181663,
  'so2_co2_ppm': 0.45,
  'fuelsulphur': 0.01,
  'scrubber_days': 108},
 {'vessel': 'MSC SARAH V',
  'imo': 9181675,
  'so2_co2_ppm': 0.95,
  'fuelsulphur': 0.02,
  'scrubber_days': 125},
 {'vessel': 'MSC TIA II',
  'imo': 9193680,
  'so2_co2_ppm': 3.36,
  'fuelsulphur': 0.08,
  'scrubber_days': 183},
 {'vessel': 'MSC YORK VII',
  'imo': 9196838,
  'so2_co2_ppm': 0.42,
  'fuelsulphur': 0.01,
  'scrubber_days': 19},
 {'vessel': 'MSC MICHIGAN VII',
  'imo': 9196864,
  'so2_co2_ppm': 0.76,
  'fuelsulphur': 0.02,
  'scrubber_days': 58},
 {'vessel': 'MSC ILLINOIS VII',
  'imo': 9197545,
  'so2_co2_ppm': 0.88,
  'fuelsulphur': 0.02,
  'scrubber_days': 76},
 {'vessel': 'MSC SYDNEY VI',
  'imo': 9200677,
  'so2_co2_ppm': 0.65,
  'fuelsulphur': 0.01,
  'scrubber_days': 56},
 {'vessel': 'MSC CAPUCINE R',
  'imo': 9210086,
  'so2_co2_ppm': 6.42,
  'fuelsulphur': 0.15,
  'scrubber_days': 5},
 {'vessel': 'MSC CAPUCINE R',
  'imo': 9210086,
  'so2_co2_ppm': 2.7,
  'fuelsulphur': 0.06,
  'scrubber_days': 157},
 {'vessel': 'MSC SINES R',
  'imo': 9210098,
  'so2_co2_ppm': 5.6,
  'fuelsulphur': 0.13,
  'scrubber_days': 20},
 {'vessel': 'MSC SINES R',
  'imo': 9210098,
  'so2_co2_ppm': 3.99,
  'fuelsulphur': 0.09,
  'scrubber_days': 109},
 {'vessel': 'MSC JESSENIA R',
  'imo': 9215672,
  'so2_co2_ppm': 7.36,
  'fuelsulphur': 0.17,
  'scrubber_days': 23},
 {'vessel': 'MSC JESSENIA R',
  'imo': 9215672,
  'so2_co2_ppm': 2.26,
  'fuelsulphur': 0.05,
  'scrubber_days': 151},
 {'vessel': 'MSC ELIZABETH III',
  'imo': 9215892,
  'so2_co2_ppm': 2.0,
  'fuelsulphur': 0.05,
  'scrubber_days': 1},
 {'vessel': 'MSC PETRA',
  'imo': 9222302,
  'so2_co2_ppm': 4.71,
  'fuelsulphur': 0.11,
  'scrubber_days': 10},
 {'vessel': 'MSC PETRA',
  'imo': 9222302,
  'so2_co2_ppm': 2.39,
  'fuelsulphur': 0.06,
  'scrubber_days': 168},
 {'vessel': 'MSC SHIRLEY',
  'imo': 9224049,
  'so2_co2_ppm': 5.61,
  'fuelsulphur': 0.13,
  'scrubber_days': 12},
 {'vessel': 'MSC SHIRLEY',
  'imo': 9224049,
  'so2_co2_ppm': 0.96,
  'fuelsulphur': 0.02,
  'scrubber_days': 117},
 {'vessel': 'MSC RHIANNON',
  'imo': 9224051,
  'so2_co2_ppm': 0.23,
  'fuelsulphur': 0.01,
  'scrubber_days': 183},
 {'vessel': 'MSC SINGAPORE IV',
  'imo': 9224348,
  'so2_co2_ppm': 0.45,
  'fuelsulphur': 0.01,
  'scrubber_days': 139},
 {'vessel': 'MSC SILVER II',
  'imo': 9225249,
  'so2_co2_ppm': 11.92,
  'fuelsulphur': 0.27,
  'scrubber_days': 59},
 {'vessel': 'MSC BARBARA',
  'imo': 9226932,
  'so2_co2_ppm': 4.4,
  'fuelsulphur': 0.1,
  'scrubber_days': 1},
 {'vessel': 'MSC BARBARA',
  'imo': 9226932,
  'so2_co2_ppm': 1.8,
  'fuelsulphur': 0.04,
  'scrubber_days': 117},
 {'vessel': 'MSC ANISHA R',
  'imo': 9227297,
  'so2_co2_ppm': 1.09,
  'fuelsulphur': 0.03,
  'scrubber_days': 159},
 {'vessel': 'MSC KATYA R',
  'imo': 9227302,
  'so2_co2_ppm': 4.6,
  'fuelsulphur': 0.11,
  'scrubber_days': 1},
 {'vessel': 'MSC KATYA R',
  'imo': 9227302,
  'so2_co2_ppm': 0.49,
  'fuelsulphur': 0.01,
  'scrubber_days': 173},
 {'vessel': 'MSC ZLATA R',
  'imo': 9227314,
  'so2_co2_ppm': 6.31,
  'fuelsulphur': 0.15,
  'scrubber_days': 10},
 {'vessel': 'MSC ZLATA R',
  'imo': 9227314,
  'so2_co2_ppm': 1.18,
  'fuelsulphur': 0.03,
  'scrubber_days': 150},
 {'vessel': 'MSC VIDISHA R',
  'imo': 9227326,
  'so2_co2_ppm': 0.31,
  'fuelsulphur': 0.01,
  'scrubber_days': 120},
 {'vessel': 'MSC JULIA R',
  'imo': 9227338,
  'so2_co2_ppm': 7.68,
  'fuelsulphur': 0.18,
  'scrubber_days': 4},
 {'vessel': 'MSC JULIA R',
  'imo': 9227338,
  'so2_co2_ppm': 0.51,
  'fuelsulphur': 0.01,
  'scrubber_days': 82},
 {'vessel': 'MSC DENMARK VI',
  'imo': 9231250,
  'so2_co2_ppm': 0.83,
  'fuelsulphur': 0.02,
  'scrubber_days': 53},
 {'vessel': 'MSC SWEDEN VI',
  'imo': 9231262,
  'so2_co2_ppm': 1.04,
  'fuelsulphur': 0.02,
  'scrubber_days': 141},
 {'vessel': 'MSC MEXICO V',
  'imo': 9231779,
  'so2_co2_ppm': 0.21,
  'fuelsulphur': 0.0,
  'scrubber_days': 66},
 {'vessel': 'MSC HONG KONG V',
  'imo': 9231810,
  'so2_co2_ppm': 0.99,
  'fuelsulphur': 0.02,
  'scrubber_days': 112},
 {'vessel': 'MSC SHANGHAI V',
  'imo': 9231822,
  'so2_co2_ppm': 0.58,
  'fuelsulphur': 0.01,
  'scrubber_days': 93},
 {'vessel': 'MSC WAVE F',
  'imo': 9232462,
  'so2_co2_ppm': 11.0,
  'fuelsulphur': 0.25,
  'scrubber_days': 1},
 {'vessel': 'MSC ENGLAND',
  'imo': 9232890,
  'so2_co2_ppm': 7.03,
  'fuelsulphur': 0.16,
  'scrubber_days': 18},
 {'vessel': 'MSC ENGLAND',
  'imo': 9232890,
  'so2_co2_ppm': 1.57,
  'fuelsulphur': 0.04,
  'scrubber_days': 119},
 {'vessel': 'MSC RADIANT III',
  'imo': 9235402,
  'so2_co2_ppm': 1.0,
  'fuelsulphur': 0.02,
  'scrubber_days': 1},
 {'vessel': 'MSC ADITI',
  'imo': 9235581,
  'so2_co2_ppm': 6.5,
  'fuelsulphur': 0.15,
  'scrubber_days': 7},
 {'vessel': 'MSC ADITI',
  'imo': 9235581,
  'so2_co2_ppm': 0.97,
  'fuelsulphur': 0.02,
  'scrubber_days': 177},
 {'vessel': 'MSC ELBE III',
  'imo': 9236688,
  'so2_co2_ppm': 5.61,
  'fuelsulphur': 0.13,
  'scrubber_days': 30},
 {'vessel': 'MSC ELBE III',
  'imo': 9236688,
  'so2_co2_ppm': 2.83,
  'fuelsulphur': 0.07,
  'scrubber_days': 9},
 {'vessel': 'MSC WESER',
  'imo': 9236690,
  'so2_co2_ppm': 5.32,
  'fuelsulphur': 0.12,
  'scrubber_days': 13},
 {'vessel': 'MSC WESER',
  'imo': 9236690,
  'so2_co2_ppm': 1.98,
  'fuelsulphur': 0.05,
  'scrubber_days': 86},
 {'vessel': 'MSC DONATA',
  'imo': 9237151,
  'so2_co2_ppm': 8.72,
  'fuelsulphur': 0.2,
  'scrubber_days': 7},
 {'vessel': 'MSC DONATA',
  'imo': 9237151,
  'so2_co2_ppm': 0.28,
  'fuelsulphur': 0.01,
  'scrubber_days': 165},
 {'vessel': 'MSC MANU',
  'imo': 9238789,
  'so2_co2_ppm': 0.53,
  'fuelsulphur': 0.01,
  'scrubber_days': 181},
 {'vessel': 'MSC SANDY III',
  'imo': 9239733,
  'so2_co2_ppm': 1.0,
  'fuelsulphur': 0.02,
  'scrubber_days': 1},
 {'vessel': 'MSC PATNAREE III',
  'imo': 9240328,
  'so2_co2_ppm': 8.0,
  'fuelsulphur': 0.18,
  'scrubber_days': 5},
 {'vessel': 'MSC PATNAREE III',
  'imo': 9240328,
  'so2_co2_ppm': 0.42,
  'fuelsulphur': 0.01,
  'scrubber_days': 174},
 {'vessel': 'MSC RESILIENT III',
  'imo': 9240873,
  'so2_co2_ppm': 0.7,
  'fuelsulphur': 0.02,
  'scrubber_days': 7},
 {'vessel': 'MSC BALTIC III',
  'imo': 9241475,
  'so2_co2_ppm': 4.0,
  'fuelsulphur': 0.09,
  'scrubber_days': 1},
 {'vessel': 'MSC AMY',
  'imo': 9242651,
  'so2_co2_ppm': 0.15,
  'fuelsulphur': 0.0,
  'scrubber_days': 176},
 {'vessel': 'MSC DARIEN',
  'imo': 9243394,
  'so2_co2_ppm': 0.52,
  'fuelsulphur': 0.01,
  'scrubber_days': 138},
 {'vessel': 'MSC BRIDGEPORT',
  'imo': 9243409,
  'so2_co2_ppm': 0.6,
  'fuelsulphur': 0.01,
  'scrubber_days': 116},
 {'vessel': 'MSC ARUSHI R',
  'imo': 9244881,
  'so2_co2_ppm': 0.43,
  'fuelsulphur': 0.01,
  'scrubber_days': 182},
 {'vessel': 'MSC KALAMATA VII',
  'imo': 9244946,
  'so2_co2_ppm': 9.3,
  'fuelsulphur': 0.21,
  'scrubber_days': 1},
 {'vessel': 'MSC KALAMATA VII',
  'imo': 9244946,
  'so2_co2_ppm': 0.75,
  'fuelsulphur': 0.02,
  'scrubber_days': 77},
 {'vessel': 'WEC VAN GOGH',
  'imo': 9246566,
  'so2_co2_ppm': 2.03,
  'fuelsulphur': 0.05,
  'scrubber_days': 81},
 {'vessel': 'MSC PILAR VI',
  'imo': 9248148,
  'so2_co2_ppm': 5.2,
  'fuelsulphur': 0.12,
  'scrubber_days': 1},
 {'vessel': 'MSC PILAR VI',
  'imo': 9248148,
  'so2_co2_ppm': 0.45,
  'fuelsulphur': 0.01,
  'scrubber_days': 62},
 {'vessel': 'MSC DAMLA',
  'imo': 9250983,
  'so2_co2_ppm': 4.6,
  'fuelsulphur': 0.11,
  'scrubber_days': 2},
 {'vessel': 'MSC DAMLA',
  'imo': 9250983,
  'so2_co2_ppm': 0.39,
  'fuelsulphur': 0.01,
  'scrubber_days': 181},
 {'vessel': 'MSC VANESSA',
  'imo': 9251688,
  'so2_co2_ppm': 0.89,
  'fuelsulphur': 0.02,
  'scrubber_days': 26},
 {'vessel': 'MSC LUDOVICA',
  'imo': 9251690,
  'so2_co2_ppm': 1.56,
  'fuelsulphur': 0.04,
  'scrubber_days': 52},
 {'vessel': 'MSC BANU III',
  'imo': 9263332,
  'so2_co2_ppm': 5.4,
  'fuelsulphur': 0.12,
  'scrubber_days': 1},
 {'vessel': 'MSC BANU III',
  'imo': 9263332,
  'so2_co2_ppm': 1.05,
  'fuelsulphur': 0.02,
  'scrubber_days': 182},
 {'vessel': 'MSC ASTRID III',
  'imo': 9263344,
  'so2_co2_ppm': 5.2,
  'fuelsulphur': 0.12,
  'scrubber_days': 2},
 {'vessel': 'MSC ASTRID III',
  'imo': 9263344,
  'so2_co2_ppm': 0.87,
  'fuelsulphur': 0.02,
  'scrubber_days': 180},
 {'vessel': 'MSC PEGASUS',
  'imo': 9267637,
  'so2_co2_ppm': 4.55,
  'fuelsulphur': 0.1,
  'scrubber_days': 1},
 {'vessel': 'MSC PEGASUS',
  'imo': 9267637,
  'so2_co2_ppm': 1.75,
  'fuelsulphur': 0.04,
  'scrubber_days': 177},
 {'vessel': 'MSC PHOENIX',
  'imo': 9267649,
  'so2_co2_ppm': 3.17,
  'fuelsulphur': 0.07,
  'scrubber_days': 84},
 {'vessel': 'MSC ELENI',
  'imo': 9278143,
  'so2_co2_ppm': 0.42,
  'fuelsulphur': 0.01,
  'scrubber_days': 122},
 {'vessel': 'MSC ORNELLA',
  'imo': 9281267,
  'so2_co2_ppm': 4.4,
  'fuelsulphur': 0.1,
  'scrubber_days': 1},
 {'vessel': 'MSC ORNELLA',
  'imo': 9281267,
  'so2_co2_ppm': 0.77,
  'fuelsulphur': 0.02,
  'scrubber_days': 120},
 {'vessel': 'MSC ELA',
  'imo': 9282259,
  'so2_co2_ppm': 6.62,
  'fuelsulphur': 0.15,
  'scrubber_days': 6},
 {'vessel': 'MSC ELA',
  'imo': 9282259,
  'so2_co2_ppm': 1.03,
  'fuelsulphur': 0.02,
  'scrubber_days': 165},
 {'vessel': 'MSC ANS',
  'imo': 9282261,
  'so2_co2_ppm': 6.0,
  'fuelsulphur': 0.14,
  'scrubber_days': 14},
 {'vessel': 'MSC ANS',
  'imo': 9282261,
  'so2_co2_ppm': 0.43,
  'fuelsulphur': 0.01,
  'scrubber_days': 167},
 {'vessel': 'MSC VANCOUVER',
  'imo': 9285691,
  'so2_co2_ppm': 0.42,
  'fuelsulphur': 0.01,
  'scrubber_days': 110},
 {'vessel': 'MSC EVEREST VIII',
  'imo': 9286231,
  'so2_co2_ppm': 0.36,
  'fuelsulphur': 0.01,
  'scrubber_days': 179},
 {'vessel': 'MSC VERACRUZ',
  'imo': 9287924,
  'so2_co2_ppm': 1.48,
  'fuelsulphur': 0.03,
  'scrubber_days': 154},
 {'vessel': 'MSC BUSAN',
  'imo': 9289087,
  'so2_co2_ppm': 1.62,
  'fuelsulphur': 0.04,
  'scrubber_days': 156},
 {'vessel': 'MSC BEIJING',
  'imo': 9289099,
  'so2_co2_ppm': 4.5,
  'fuelsulphur': 0.1,
  'scrubber_days': 1},
 {'vessel': 'MSC BEIJING',
  'imo': 9289099,
  'so2_co2_ppm': 2.15,
  'fuelsulphur': 0.05,
  'scrubber_days': 85},
 {'vessel': 'MSC MANZANILLO',
  'imo': 9289960,
  'so2_co2_ppm': 4.7,
  'fuelsulphur': 0.11,
  'scrubber_days': 6},
 {'vessel': 'MSC MANZANILLO',
  'imo': 9289960,
  'so2_co2_ppm': 2.72,
  'fuelsulphur': 0.06,
  'scrubber_days': 129},
 {'vessel': 'MSC TUXPAN',
  'imo': 9289972,
  'so2_co2_ppm': 5.0,
  'fuelsulphur': 0.11,
  'scrubber_days': 2},
 {'vessel': 'MSC TUXPAN',
  'imo': 9289972,
  'so2_co2_ppm': 2.7,
  'fuelsulphur': 0.06,
  'scrubber_days': 95},
 {'vessel': 'MSC SANTA MARIA',
  'imo': 9290426,
  'so2_co2_ppm': 2.23,
  'fuelsulphur': 0.05,
  'scrubber_days': 108},
 {'vessel': 'MSC NIOVI VIII',
  'imo': 9290488,
  'so2_co2_ppm': 8.57,
  'fuelsulphur': 0.2,
  'scrubber_days': 56},
 {'vessel': 'MSC NIOVI VIII',
  'imo': 9290488,
  'so2_co2_ppm': 3.05,
  'fuelsulphur': 0.07,
  'scrubber_days': 41},
 {'vessel': 'MSC RONIT R',
  'imo': 9293167,
  'so2_co2_ppm': 0.19,
  'fuelsulphur': 0.0,
  'scrubber_days': 166},
 {'vessel': 'MSC MIRELLA V',
  'imo': 9293179,
  'so2_co2_ppm': 0.42,
  'fuelsulphur': 0.01,
  'scrubber_days': 160},
 {'vessel': 'MSC ANYA',
  'imo': 9297864,
  'so2_co2_ppm': 8.85,
  'fuelsulphur': 0.2,
  'scrubber_days': 11},
 {'vessel': 'MSC ANYA',
  'imo': 9297864,
  'so2_co2_ppm': 0.87,
  'fuelsulphur': 0.02,
  'scrubber_days': 114},
 {'vessel': 'MSC BHAVYA',
  'imo': 9297876,
  'so2_co2_ppm': 0.1,
  'fuelsulphur': 0.0,
  'scrubber_days': 183},
 {'vessel': 'MSC PORTO III',
  'imo': 9299020,
  'so2_co2_ppm': 1.0,
  'fuelsulphur': 0.02,
  'scrubber_days': 181},
 {'vessel': 'MSC TORONTO',
  'imo': 9299525,
  'so2_co2_ppm': 2.98,
  'fuelsulphur': 0.07,
  'scrubber_days': 45},
 {'vessel': 'MSC CHARLESTON',
  'imo': 9299537,
  'so2_co2_ppm': 5.5,
  'fuelsulphur': 0.13,
  'scrubber_days': 2},
 {'vessel': 'MSC CHARLESTON',
  'imo': 9299537,
  'so2_co2_ppm': 1.42,
  'fuelsulphur': 0.03,
  'scrubber_days': 60},
 {'vessel': 'MSC PARIS',
  'imo': 9301483,
  'so2_co2_ppm': 4.5,
  'fuelsulphur': 0.1,
  'scrubber_days': 1},
 {'vessel': 'MSC PARIS',
  'imo': 9301483,
  'so2_co2_ppm': 0.59,
  'fuelsulphur': 0.01,
  'scrubber_days': 69},
 {'vessel': 'MSC ANAHITA',
  'imo': 9302085,
  'so2_co2_ppm': 0.85,
  'fuelsulphur': 0.02,
  'scrubber_days': 180},
 {'vessel': 'MSC LISBON',
  'imo': 9304459,
  'so2_co2_ppm': 5.59,
  'fuelsulphur': 0.13,
  'scrubber_days': 41},
 {'vessel': 'MSC LISBON',
  'imo': 9304459,
  'so2_co2_ppm': 2.39,
  'fuelsulphur': 0.06,
  'scrubber_days': 138},
 {'vessel': 'MSC TIANSHAN',
  'imo': 9305477,
  'so2_co2_ppm': 0.51,
  'fuelsulphur': 0.01,
  'scrubber_days': 142},
 {'vessel': 'MSC TIANPING',
  'imo': 9305489,
  'so2_co2_ppm': 7.31,
  'fuelsulphur': 0.17,
  'scrubber_days': 21},
 {'vessel': 'MSC TIANPING',
  'imo': 9305489,
  'so2_co2_ppm': 0.9,
  'fuelsulphur': 0.02,
  'scrubber_days': 150},
 {'vessel': 'MSC KUMSAL',
  'imo': 9305506,
  'so2_co2_ppm': 6.82,
  'fuelsulphur': 0.16,
  'scrubber_days': 2},
 {'vessel': 'MSC KUMSAL',
  'imo': 9305506,
  'so2_co2_ppm': 1.38,
  'fuelsulphur': 0.03,
  'scrubber_days': 171},
 {'vessel': 'MSC CORINNA',
  'imo': 9307267,
  'so2_co2_ppm': 5.3,
  'fuelsulphur': 0.12,
  'scrubber_days': 2},
 {'vessel': 'MSC CORINNA',
  'imo': 9307267,
  'so2_co2_ppm': 2.1,
  'fuelsulphur': 0.05,
  'scrubber_days': 167},
 {'vessel': 'MSC LEANDRA',
  'imo': 9313943,
  'so2_co2_ppm': 0.49,
  'fuelsulphur': 0.01,
  'scrubber_days': 119},
 {'vessel': 'MSC BREMERHAVEN',
  'imo': 9313967,
  'so2_co2_ppm': 0.29,
  'fuelsulphur': 0.01,
  'scrubber_days': 16},
 {'vessel': 'WEC VAN RIJN',
  'imo': 9315006,
  'so2_co2_ppm': 0.43,
  'fuelsulphur': 0.01,
  'scrubber_days': 29},
 {'vessel': 'WEC DE HOOGH',
  'imo': 9315018,
  'so2_co2_ppm': 0.45,
  'fuelsulphur': 0.01,
  'scrubber_days': 102},
 {'vessel': 'MSC ARCHIMIDIS',
  'imo': 9315379,
  'so2_co2_ppm': 9.34,
  'fuelsulphur': 0.21,
  'scrubber_days': 10},
 {'vessel': 'MSC ARCHIMIDIS',
  'imo': 9315379,
  'so2_co2_ppm': 1.3,
  'fuelsulphur': 0.03,
  'scrubber_days': 1},
 {'vessel': 'MSC AGAMEMNON',
  'imo': 9315381,
  'so2_co2_ppm': 1.97,
  'fuelsulphur': 0.05,
  'scrubber_days': 1},
 {'vessel': 'MSC MATTINA',
  'imo': 9315915,
  'so2_co2_ppm': 7.85,
  'fuelsulphur': 0.18,
  'scrubber_days': 40},
 {'vessel': 'MSC MATTINA',
  'imo': 9315915,
  'so2_co2_ppm': 2.06,
  'fuelsulphur': 0.05,
  'scrubber_days': 73},
 {'vessel': 'MSC HANNAH',
  'imo': 9316347,
  'so2_co2_ppm': 4.96,
  'fuelsulphur': 0.11,
  'scrubber_days': 5},
 {'vessel': 'MSC HANNAH',
  'imo': 9316347,
  'so2_co2_ppm': 2.18,
  'fuelsulphur': 0.05,
  'scrubber_days': 172},
 {'vessel': 'MSC CELINE',
  'imo': 9316361,
  'so2_co2_ppm': 5.49,
  'fuelsulphur': 0.13,
  'scrubber_days': 4},
 {'vessel': 'MSC CELINE',
  'imo': 9316361,
  'so2_co2_ppm': 0.19,
  'fuelsulphur': 0.0,
  'scrubber_days': 176},
 {'vessel': 'MSC TAMPICO',
  'imo': 9317937,
  'so2_co2_ppm': 6.59,
  'fuelsulphur': 0.15,
  'scrubber_days': 42},
 {'vessel': 'MSC TAMPICO',
  'imo': 9317937,