In [1]:
import pandas as pd

In [2]:
esi = pd.read_excel(r"D:\Navalt\MSC\2024\ESI\Group A\JUL23 TO DEC23\CLIENT FILE\ESI Vessels current window.xlsx")
esi

,IMO,Fleet,Group,Vessel,Scrubber,GT,Year of Keel laid
0,9297589,CHARTER,NaN,ALANA,No,11662,2002
1,9625970,9,ANASTASIA,ANASTASIA,No,51168,2012
2,9342695,CHARTER,NaN,AS California,No,28340,2007
3,9314947,CHARTER,NaN,AS CAMELLIA,Yes,28927,2005
4,9321897,CHARTER,NaN,AS Nadia,No,38332,2007
...,...,...,...,...,...,...,...
422,9315018,1,WEC4,WEC DE HOOGH,No,11662,2004
423,9326964,1,WEC,WEC FRANS HALS,Yes,9990,2004
424,9354363,1,WEC,WEC MONDRIAAN,No,9981,2006
425,9315006,1,WEC4,WEC VAN RIJN,No,11662,2004
426,9252993,CHARTER,NaN,Zhu Cheng Xin Zhou,No,25703,2002

In [3]:
esi_sorrento = esi[(esi['Fleet'] == 'SORRENTO') & (esi['Scrubber'] == 'Yes')]
esi_sorrento

,IMO,Fleet,Group,Vessel,Scrubber,GT,Year of Keel laid
59,9839480,SORRENTO,NaN,MSC AMBRA,Yes,232618,2020
91,9399014,SORRENTO,NaN,MSC BEATRICE,Yes,151559,2009
115,9930040,SORRENTO,NaN,MSC CELESTINO MARESCA,Yes,236078,2020
120,9708693,SORRENTO,NaN,MSC CLARA,Yes,192237,2015
136,9897004,SORRENTO,NaN,MSC DILETTA,Yes,228786,2020
166,9401116,SORRENTO,NaN,MSC FRANCESCA,Yes,131771,2008
195,9398371,SORRENTO,NaN,MSC IVANA,Yes,131771,2008
211,9399026,SORRENTO,NaN,MSC KALINA,Yes,151559,2009
214,9467457,SORRENTO,NaN,MSC KATIE,Yes,140096,2012
228,9225665,SORRENTO,NaN,MSC LAURA,Yes,75590,2001
240,9230490,SORRENTO,NaN,MSC LORETTA,Yes,73819,2002
265,9708679,SORRENTO,NaN,MSC MAYA,Yes,192237,2015
267,9226918,SORRENTO,NaN,MSC MELISSA,Yes,73819,2002
271,9230488,SORRENTO,NaN,MSC MICHAELA,Yes,73819,2002
273,9897016,SORRENTO,NaN,MSC MICHELLE,Yes,228786,2020
282,9955789,SORRENTO,NaN,MSC NAHARA,Yes,45387,2023
305,9703291,SORRENTO,NaN,MSC OSCAR,Yes,192237,2014
326,9754965,SORRENTO,NaN,MSC REEF,Yes,194308,2016
369,9404663,SORRENTO,NaN,MSC SONIA,Yes,153092,2010
372,9279989,SORRENTO,NaN,MSC STELLA,Yes,73819,2004
375,9708681,SORRENTO,NaN,MSC SVEVA,Yes,192237,2015
419,9703318,SORRENTO,NaN,MSC ZOE,Yes,192237,2015

In [4]:
charter = pd.read_excel(r"D:\Navalt\MSC\2023\Weekly Data\CHARTER\raw_data_charter\raw_data_charter_41-52.xlsx")
charter

,GID,VSL,IMO No,VOY,Corrected Date,REPORT DATE TIME,REPORT DATE TIME Offset,Report Type,Status,LAT,...,ROB Rsdl HS,ROB Rsdl ULS,ROB Rsdl LNG,ECA MILES,ECA TIME,EGCS DRY WASTE REMOVED,EGCS RUNNING TIME,EGCS WET SLURRY REMOVED,EGCS OPEN LOOP RUNNING TIME,EGCS CLOSED LOOP RUNNING TIME
0,e5df09ef-2ee5-4b90-ba50-2203166ad051,AGIOS DIMITRIOS,9349605,NaN,2023-12-29,2023-12-28 19:41:59,UTC -05:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,01a10f31-cb8a-4197-8325-316e4a99db49,AGIOS DIMITRIOS,9349605,NaN,2023-12-29,2023-12-28 19:41:59,UTC -05:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6e473f22-a63f-438b-b75b-bb74ac5d944e,AGIOS DIMITRIOS,9349605,NaN,2023-12-29,2023-12-28 19:41:59,UTC -05:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,a8369fa3-38a7-433e-bade-dd6f19229ce6,AGIOS DIMITRIOS,9349605,NaN,2023-12-29,2023-12-28 19:41:59,UTC -05:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,f0fb079f-951e-49b8-a53c-ea79734d5d53,AGIOS DIMITRIOS,9349605,NaN,2023-12-29,2023-12-28 19:41:59,UTC -05:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10079,a7a3a4b9-a1c4-4b62-a657-c89fbedb1d5f,ZHU CHENG XIN ZHOU,9252993,NaN,2024-01-07,2024-01-06 21:23:59,UTC +08:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10080,d5169069-f7d5-46f0-9876-2ae5dc423a59,ZHU CHENG XIN ZHOU,9252993,NaN,2024-01-07,2024-01-06 21:23:59,UTC +08:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10081,d88d338a-e3e1-4539-84f2-22b96930cb57,ZHU CHENG XIN ZHOU,9252993,NaN,2024-01-07,2024-01-06 21:23:59,UTC +08:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10082,86218b81-26be-46d6-8bf5-f5b3ac366913,ZHU CHENG XIN ZHOU,9252993,HD351R,2024-01-07,2024-01-06 21:24:00,UTC +08:00,BRTH,DRIFTING,2512N,...,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0
10083,25d70868-0a7a-48d5-8579-a8720d2cb9a4,ZHU CHENG XIN ZHOU,9252993,HD351R,2024-01-07,2024-01-07 12:00:00,UTC +08:00,PORT,IN PORT,2512N,...,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0

In [5]:
esi_sorrento_lst = esi_sorrento['IMO'].to_list()
esi_sorrento_lst

[9839480,
 9399014,
 9930040,
 9708693,
 9897004,
 9401116,
 9398371,
 9399026,
 9467457,
 9225665,
 9230490,
 9708679,
 9226918,
 9230488,
 9897016,
 9955789,
 9703291,
 9754965,
 9404663,
 9279989,
 9708681,
 9703318]

In [6]:
sorrentodata_final = charter[charter['IMO No'].isin(esi_sorrento_lst)]
pd.set_option('display.max_columns', None)  
sorrentodata_final

,GID,VSL,IMO No,VOY,Corrected Date,REPORT DATE TIME,REPORT DATE TIME Offset,Report Type,Status,LAT,...,ROB Rsdl HS,ROB Rsdl ULS,ROB Rsdl LNG,ECA MILES,ECA TIME,EGCS DRY WASTE REMOVED,EGCS RUNNING TIME,EGCS WET SLURRY REMOVED,EGCS OPEN LOOP RUNNING TIME,EGCS CLOSED LOOP RUNNING TIME
3969,fa889360-fc62-4bab-b312-18f9aa43bba0,MSC AMBRA,9839480,QG350E,2023-12-29,2023-12-29 12:00:00,UTC +01:00,NOON,AT SEA,2116N,...,5911.00,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
3970,d3e0069e-3b0b-459b-9f83-466fef229e09,MSC AMBRA,9839480,QG350E,2023-12-30,2023-12-30 12:00:00,UTC +01:00,NOON,AT SEA,1300N,...,5708.00,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
3971,fabd45c8-4ddc-4fca-bd98-91625f2764e4,MSC AMBRA,9839480,QG350E,2023-12-31,2023-12-31 12:00:00,UTC +01:00,NOON,AT SEA,0559N,...,5504.00,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
3972,66664352-4eb9-4a6a-a3e7-3fcd675cb8a2,MSC AMBRA,9839480,QG350E,2024-01-01,2024-01-01 12:00:00,UTC +01:00,NOON,AT SEA,0016S,...,5291.00,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
3973,70dd500b-7b1f-424f-8d30-623d17e3bd2a,MSC AMBRA,9839480,QG350E,2024-01-02,2024-01-02 12:00:00,UTC +01:00,NOON,AT SEA,0619S,...,5085.00,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9513,afc2bc7d-0a23-40e4-bcbd-498dd483793e,MSC ZOE,9703318,FT348W,2024-01-03,2024-01-03 12:00:00,UTC +01:00,NOON,AT SEA,0749S,...,2337.25,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
9514,6df76a90-641b-4965-9f3c-08269cc972c0,MSC ZOE,9703318,FT348W,2024-01-04,2024-01-04 12:00:00,UTC +01:00,NOON,AT SEA,0209S,...,2199.55,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
9515,436d1d69-5440-46fb-a5bc-b33dcacfc8f9,MSC ZOE,9703318,FT348W,2024-01-05,2024-01-05 12:00:00,UTC +01:00,NOON,AT SEA,0340N,...,2059.45,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
9516,b65991f8-796f-4209-a0a9-3ff98b2c7a6e,MSC ZOE,9703318,FT348W,2024-01-06,2024-01-06 12:00:00,UTC +00:00,NOON,AT SEA,0855N,...,1911.75,0.0,0.0,0.0,0.0,NaN,25.0,NaN,25.0,0.0
9517,9e3c9133-d25b-463d-a7f8-dc54df4d99c6,MSC ZOE,9703318,FT348W,2024-01-07,2024-01-07 12:00:00,UTC +00:00,NOON,AT SEA,1500N,...,1767.95,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0

In [29]:
pd.set_option('display.max_columns', None)  
sorrentodata_final

,GID,VSL,IMO No,VOY,Corrected Date,REPORT DATE TIME,REPORT DATE TIME Offset,Report Type,Status,LAT,LONG,M E FOC,CARGO TOTAL,Has Cargo,STEAMING TIME,Total M E Hours Fuel Only,MILES BY GPS,OIL CYL,SPEED BY LOG,SPEED BY GPS,RPM,SLIP,WIND DIRECTION,WIND SPEED,DRAFT AFT,DRAFT FWD,DISPLACEMENT,COURSE AT SEA,WAVE HEIGHT,SEA DIRECTION,CARGO TOTAL TEU,AMBIENT TEMP,SW TEMP,MILES BY SPEED LOG,ETA PORT CODE,ETA DATE TIME,ETA DATE TIME Offset,ETA PORT,TIME CHANGE,TIME SEA,TEMP MIN,TEMP MAX,REQUESTED SPEED,REM DIST TO PILOT,REM TIME TO PILOT,TOTAL UNPLND STPGE TECH,TOTAL UNPLND STPGE OPE WX,REEFERS POSITIVE PLUGGED,REEFERS NEGATIVE PLUGGED,ME TOTAL REVS COUNTER,PORT CODE,PORT,AUX BLOWERS ON,HOLD VENTILATION ON,TIME HRS ANCHOR,TIME HRS DRIFT,REASON,TYPE OF DELAY,ETB DATE TIME,ETB DATE TIME Offset,PILOT DATE TIME,PILOT DATE TIME Offset,TIME MANOEUVRING,TUG ARR,TUG SHIFT,ETD DATE TIME,ETD DATE TIME Offset,SHIFT BERTH HOURS,CARGO LOAD,CARGO DISCH,TEU FULL,TEU EMPTY,BILGE REMOVED,GARBAGE REMOVED,GARBAGE REMVL REQSTD,GARBAGE REMVL CMPLSRY,FW SUPPLY,CY CREW SIGNED ON,CY CREW SIGNED OFF,CY DOCTORS VISIT,CY MAIL RECEIVED Ref NO,CY LUB OIL SAMPLE LANDED,CY CHECKD FOR STOWAWAYS,CY STOWAWAYS ON BOARD,CY DEP GM Mtr,CY REQUISITIONS RECEIVED,DISTANCE TO NEXT PILOT,TUG SAILING TRANSIT,STEAMING TIME M E Rsdl VLS,STEAMING TIME M E Rsdl HS,STEAMING TIME M E Rsdl ULS,STEAMING TIME M E Dstlt VLS,STEAMING TIME M E Dstlt ULS,STEAMING TIME M E Tnktnr Dstlt VLS,STEAMING TIME M E MDO,STEAMING TIME AUX 1,STEAMING TIME AUX 2,STEAMING TIME AUX 3,STEAMING TIME AUX 4,STEAMING TIME AUX 5,STEAMING TIME SH GEN,STEAMING TIME TG,FUEL M E Rsdl VLS,FUEL M E Rsdl HS,FUEL M E Rsdl ULS,FUEL M E Dstlt VLS,FUEL M E Dstlt ULS,FUEL M E MDO,FUEL M E LNG,FUEL M E Tnktnr Dstlt VLS,FUEL Aux Rsdl VLS,FUEL Aux Rsdl HS,FUEL Aux Rsdl ULS,FUEL Aux Dstlt VLS,FUEL Aux Dstlt ULS,FUEL Aux Tnktnr Dstlt VLS,FUEL Aux LNG,FUEL Aux MDO,FUEL Boiler Rsdl VLS,FUEL Boiler Rsdl HS,FUEL Boiler Rsdl ULS,FUEL Boiler Dstlt VLS,FUEL Boiler Dstlt ULS,FUEL Boiler Tnktnr Dstlt VLS,FUEL Boiler LNG,FUEL Boiler MDO,POWER KW,STEAMING LOAD KW AUX 1,STEAMING LOAD KW AUX 2,STEAMING LOAD KW AUX 3,STEAMING LOAD KW AUX 4,STEAMING LOAD KW AUX 5,STEAMING LOAD KW SH GEN,STEAMING LOAD KW TG,DECK LAST CHANGE USER,ENGINE LAST CHANGE USER,DECK PART IS COMPLETE,ENGINE PART IS COMPLETE,SCAVENGE PRESSURE,SECA ENTRY TIME,SECA ENTRY LAT,SECA ENTRY LONG,SECA EXIT TIME,SECA EXIT LAT,SECA EXIT LONG,ROB FRESH WATER,MANVRNG MILES BY GPS,MANVRNG MILES BY SPEED LOG,TANKTAINER TRANSFD QUANTITY,PILOT TAKEN,DATE TIME START TRANSIT,DATE TIME START TRANSIT Offset,DATE TIME END TRANSIT,DATE TIME END TRANSIT Offset,BALLAST,TANKTAINER NUMBER,STEAMING KWHR TOTAL,CY OTHERS,ROB FO SLUDGE,ROB LO SLUDGE,ROB BILGE,SLUDGE REMOVED FO,SLUDGE REMOVED LO,SEA STATE,CY LUB ADDED TO SYSTEM MECC,CY LUB ADDED TO SYSTEM AECC,CY LUB ADDED TO THRUSTERS,CY ME LO PURIFIER IN USE,CY BALLAST,CY BENDING MOMENT,CY SHEARING FORCE,CY TORTION MOMENT,CY SUPDT AUDITOR SIGNED ON,CY SUPDT AUDITOR SIGNED OFF,CY CASH RECEIVED,CY LUB OIL RECEIVED MECYL,CY LUB OIL RECEIVED MECC,CY LUB OIL RECEIVED AECC,CY M E UNDER PISTON TEMP,CY MAIL RECEIVED,WIND DIRECTION PORT STBD,SEA DIRECTION PORT STBD,TIME PILOT ONBOARD,GRADES ROB,SO2 CO2 RATIO,Bunker Order,Remarks,BDN Number,Fuel Type,Carbon Factor,Sulphur Content PC,Quantity,Port Delivery,Product Quality,Tanktainer Number_1,Supplier,Delivery,Vol Lt,Den,Vis,ROB Dstlt ULS,ROB Dstlt VLS,ROB Rsdl MDO,ROB Tnktnr Dstlt VLS,ROB Rsdl VLS,ROB Rsdl HS,ROB Rsdl ULS,ROB Rsdl LNG,ECA MILES,ECA TIME,EGCS DRY WASTE REMOVED,EGCS RUNNING TIME,EGCS WET SLURRY REMOVED,EGCS OPEN LOOP RUNNING TIME,EGCS CLOSED LOOP RUNNING TIME
3969,fa889360-fc62-4bab-b312-18f9aa43bba0,MSC AMBRA,9839480,QG350E,2023-12-29,2023-12-29 12:00:00,UTC +01:00,NOON,AT SEA,2116N,01741W,136.0,163369.6,True,24.0,24.0,390.0,700.0,16.125000,16.250000,57.93,4.31,10.0,16.0,14.5,14.1,243119.0,181.0,0.04,100.07,14686.0,21.0,20.0,387.0,OMSLL,2024-01-15 01:00:00,UTC +04:00,SALALAH,NaN,24.0,300.0,320.0,20.1,7933.0,394.0,0.0,0.0,321.0,458.0,72910225.0,MAPTM,TANGER MED,False,True,NaN,NaN,WAITING PILOT BOARDING TIME,NaN,2023-12-26 02:00:00,UTC +01:00,NaT,NaN,NaN,NaN,NaN,2023-12-27 00:00:00,UTC +01:00,NaN,NaN,NaN,11119.0,3567.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,24.0,0.0,0.0,0.0,0.0,136.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32000.0,0.0,0.0,2300.0,2300.0,0.0,0.0,0.0,NaN,CH. ENG. CIBELLI G.,True,True,1.70,NaN,NaN,NaN,NaN,NaN,NaN,760.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,3485.0,0.0,119000.0,NaN,NaN,NaN,29.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,5911.00,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
3970,d3e0069e-3b0b-459b-9f83-466fef229e09,MSC AMBRA,9839480,QG350E,2023-12-30,2023-12-30 12:00:00,UTC +01:00,NOON,AT SEA,1300N,01742W,173.0,163369.6,True,24.0,24.0,495.0,790.0,20.375000,20.625000,71.81,3.35,40.0,31.0,14.5,14.1,242956.0,171.0,2.30,81.10,14686.0,25.0,25.0,489.0,OMSLL,2024-01-15 01:00:00,UTC +04:00,SALALAH,NaN,24.0,300.0,320.0,20.1,7435.0,370.0,0.0,0.0,321.0,458.0,73013631.0,MAPTM,TANGER MED,False,True,NaN,NaN,WAITING PILOT BOARDING TIME,NaN,2023-12-26 02:00:00,UTC +01:00,NaT,NaN,NaN,NaN,NaN,2023-12-27 00:00:00,UTC +01:00,NaN,NaN,NaN,11119.0,3567.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,24.0,0.0,0.0,0.0,0.0,173.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41000.0,0.0,2600.0,0.0,2600.0,0.0,0.0,0.0,NaN,CH. ENG. CIBELLI G.,True,True,1.60,NaN,NaN,NaN,NaN,NaN,NaN,800.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,3485.0,0.0,123000.0,NaN,NaN,NaN,32.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,5708.00,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
3971,fabd45c8-4ddc-4fca-bd98-91625f2764e4,MSC AMBRA,9839480,QG350E,2023-12-31,2023-12-31 12:00:00,UTC +01:00,NOON,AT SEA,0559N,01336W,173.0,163369.6,True,24.0,24.0,494.0,800.0,20.291667,20.583333,71.26,2.98,18.0,19.0,14.5,14.1,242782.0,143.0,0.23,113.18,14686.0,28.0,29.0,487.0,OMSLL,2024-01-15 01:00:00,UTC +04:00,SALALAH,NaN,24.0,300.0,320.0,20.1,6944.0,346.0,0.0,0.0,321.0,458.0,73116251.0,MAPTM,TANGER MED,False,True,NaN,NaN,WAITING PILOT BOARDING TIME,NaN,2023-12-26 02:00:00,UTC +01:00,NaT,NaN,NaN,NaN,NaN,2023-12-27 00:00:00,UTC +01:00,NaN,NaN,NaN,11119.0,3567.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,24.0,0.0,0.0,0.0,0.0,173.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,31.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40000.0,0.0,2700.0,0.0,2700.0,0.0,0.0,0.0,NaN,CH. ENG. CIBELLI G.,True,True,1.60,NaN,NaN,NaN,NaN,NaN,NaN,830.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,3485.0,0.0,129000.0,NaN,NaN,NaN,33.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,5504.00,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
3972,66664352-4eb9-4a6a-a3e7-3fcd675cb8a2,MSC AMBRA,9839480,QG350E,2024-01-01,2024-01-01 12:00:00,UTC +01:00,NOON,AT SEA,0016S,00854W,181.0,163369.6,True,24.0,24.0,469.0,840.0,19.458333,19.541667,70.91,6.33,5.0,28.0,14.5,14.1,242611.0,143.0,0.43,16.29,14686.0,28.0,27.0,467.0,OMSLL,2024-01-15 01:00:00,UTC +04:00,SALALAH,NaN,24.0,300.0,320.0,20.1,6476.0,322.0,0.0,0.0,321.0,458.0,73220656.0,MAPTM,TANGER MED,False,True,NaN,NaN,WAITING PILOT BOARDING TIME,NaN,2023-12-26 02:00:00,UTC +01:00,NaT,NaN,NaN,NaN,NaN,2023-12-27 00:00:00,UTC +01:00,NaN,NaN,NaN,11119.0,3567.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,24.0,0.0,0.0,0.0,0.0,181.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,42000.0,0.0,2800.0,0.0,2800.0,0.0,0.0,0.0,NaN,CH. ENG. CIBELLI G.,True,True,1.70,NaN,NaN,NaN,NaN,NaN,NaN,870.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,3485.0,0.0,133900.0,NaN,NaN,NaN,33.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,5291.00,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
3973,70dd500b-7b1f-424f-8d30-623d17e3bd2a,MSC AMBRA,9839480,QG350E,2024-01-02,2024-01-02 12:00:00,UTC +01:00,NOON,AT SEA,0619S,00423W,174.0,163369.6,True,24.0,24.0,453.0,800.0,18.750000,18.875000,69.72,9.27,12.0,32.0,14.5,14.1,242425.0,143.0,1.12,28.17,14686.0,27.0,27.0,450.0,OMSLL,2024-01-15 01:00:00,UTC +04:00,SALALAH,NaN,24.0,300.0,320.0,20.2,6024.0,298.0,0.0,0.0,321.0,458.0,73321058.0,MAPTM,TANGER MED,False,True,NaN,NaN,WAITING PILOT BOARDING TIME,NaN,2023-12-26 02:00:00,UTC +01:00,NaT,NaN,NaN,NaN,NaN,2023-12-27 00:00:00,UTC +01:00,NaN,NaN,NaN,11119.0,3567.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,24.0,0.0,0.0,0.0,0.0,174.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40000.0,0.0,2800.0,0.0,2800.0,0.0,0.0,0.0,NaN,CH. ENG. CIBELLI G.,True,True,1.60,NaN,NaN,NaN,NaN,NaN,NaN,890.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,3485.0,0.0,133000.0,NaN,NaN,NaN,33.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,5085.00,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9513,afc2bc7d-0a23-40e4-bcbd-498dd483793e,MSC ZOE,9703318,FT348W,2024-01-03,2024-01-03 12:00:00,UTC +01:00,NOON,AT SEA,0749S,00222W,126.1,186237.0,True,24.0,24.0,422.0,735.0,16.125000,17.583333,64.78,10.98,50.0,3.0,16.4,16.4,256810.7,324.0,1.41,171.65,13858.0,28.0,26.0,387.0,EGPSE,2024-01-16 08:00:00,UTC +02:00,PORT SAID EAST,NaN,24.0,280.0,310.0,16.6,5089.0,307.0,0.0,0.0,10.0,32.0,171808520.0,SGSIN,SINGAPORE,False,True,NaN,NaN,WAITING FOR NINGBO PILOT,NaN,2023-12-15 06:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2023-12-16 07:00:00,UTC +08:00,NaN,NaN,NaN,13756.0,102.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,126.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28449.0,2250.0,0.0,0.0,0.0,0.0,0.0,0.0,MASTER,CH.ENG,True,True,1.39,NaN,NaN,NaN,NaN,NaN,NaN,506.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,2890.5,0.0,54000.0,NaN,NaN,NaN,14.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,9.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2337.25,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
9514,6df76a90-641b-4965-9f3c-08269cc972c0,MSC ZOE,9703318,FT348W,2024-01-04,2024-01-04 12:00:00,UTC +01:00,NOON,AT SEA,0209S,00627W,124.7,186237.0,True,24.0,24.0,418.0,722.0,16.041667,17.416667,64.56,11.49,40.0,3.0,16.4,16.4,256810.7,324.0,1.31,172.74,13858.0,33.0,28.0,385.0,EGPSE,2024-01-16 08:00:00,UTC +02:00,PORT SAID EAST,NaN,24.0,280.0,310.0,16.5,4689.0,283.0,0.0,0.0,10.0,32.0,171901490.0,SGSIN,SINGAPORE,False,True,NaN,NaN,WAITING FOR NINGBO PILOT,NaN,2023-12-15 06:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2023-12-16 07:00:00,UTC +08:00,NaN,NaN,NaN,13756.0,102.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,124.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28104.0,2250.0,0.0,0.0,0.0,0.0,0.0,0.0,MASTER,CH.ENG,True,True,1.37,NaN,NaN,NaN,NaN,NaN,NaN,490.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,2890.5,0.0,54000.0,NaN,NaN,NaN,14.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,11.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2199.55,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
9515,436d1d69-5440-46fb-a5bc-b33dcacfc8f9,MSC ZOE,9703318,FT348W,2024-01-05,2024-01-05 12:00:00,UTC +01:00,NOON,AT SEA,0340N,01039W,126.5,186237.0,True,24.0,24.0,429.0,730.0,16.041667,17.875000,64.91,9.64,10.0,15.0,16.4,16.4,256810.7,324.0,0.09,139.99,13858.0,31.0,29.0,385.0,EGPSE,2024-01-16 08:00:00,UTC +02:00,PORT SAID EAST,NaN,24.0,280.0,310.0,16.4,4242.0,259.0,0.0,0.0,10.0,32.0,171994960.0,SGSIN,SINGAPORE,False,True,NaN,NaN,WAITING FOR NINGBO PILOT,NaN,2023-12-15 06:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2023-12-16 07:00:00,UTC +08:00,NaN,NaN,NaN,13756.0,102.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,126.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28536.0,2350.0,0.0,0.0,0.0,0.0,0.0,0.0,MASTER,CH.ENG,True,True,1.40,NaN,NaN,NaN,NaN,NaN,NaN,483.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,2890.5,0.0,56400.0,NaN,NaN,NaN,17.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,11.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2059.45,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
9516,b65991f8-796f-4209-a0a9-3ff98b2c7a6e,MSC ZOE,9703318,FT348W,2024-01-06,2024-01-06 12:00:00,UTC +00:00,NOON,AT SEA,0855N,01533W,133.0,186237.0,True,25.0,25.0,430.0,774.0,16.000000,17.200000,65.15,13.41,20.0,18.0,16.4,16.4,256810.7,316.0,0.21,92.66,13858.0,29.0,29.0,400.0,EGPSE,2024-01-16 08:00:00,UTC +02:00,PORT SAID EAST,NaN,25.0,280.0,310.0,16.3,3812.0,234.0,0.0,0.0,10.0,32.0,172092690.0,SGSIN,SINGAPORE,False,True,NaN,NaN,WAITING FOR NINGBO PILOT,NaN,2023-12-15 06:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2023-12-16 07:00:00,UTC +08:00,NaN,NaN,NaN,13756.0,102.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,25.0,0.0,0.0,0.0,0.0,0.0,25.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,133.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28744.0,2350.0,1100.0,0.0,0.0,0.0,0.0,0.0,MASTER,CH.ENG,True,True,1.41,NaN,NaN,NaN,NaN,NaN,NaN,474.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,2890.5,0.0,80750.0,NaN,NaN,NaN,20.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,11.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,1911.75,0.0,0.0,0.0,0.0,NaN,25.0,NaN,25.0,0.0
9517,9e3c9133-d25b-463d-a7f8-dc54df4d99c6,MSC ZOE,9703318,FT348W,2024-01-07,2024-01-07 12:00:00,UTC +00:00,NOON,AT SEA,1500N,01751W,129.9,186237.0,True,24.0,24.0,403.0,786.0,15.666667,16.791667,64.78,14.98,20.0,20.0,16.4,16.4,256810.7,357.0,0.29,73.69,13858.0,26.0,25.0,376.0,EGPSE,2024-01-16 08:00:00,UTC +02:00,PORT SAID EAST,NaN,24.0,280.0,310.0,16.3,3399.0,210.0,0.0,0.0,10.0,32.0,172185970.0,SGSIN,SINGAPORE,False,True,NaN,NaN,WAITING FOR NINGBO PILOT,NaN,2023-12-15 06:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2023-12-16 07:00:00,UTC +08:00,NaN,NaN,NaN,13756.0,102.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,129.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29389.0,2350.0,1100.0,0.0,0.0,0.0,0.0,0.0,MASTER,CH.ENG,True,True,1.43,NaN,NaN,NaN,NaN,NaN,NaN,461.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,2890.5,0.0,78400.0,NaN,NaN,NaN,20.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,7.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,1767.95,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0

In [25]:
imo_counts = sorrentodata_final['IMO No'].value_counts()
imo_counts

9930040    64
9398371    57
9225665    50
9754965    46
9404663    44
9708679    43
9279989    41
9226918    37
9230488    36
9897016    27
9467457    26
9399014    26
9399026    20
9708693    20
9703291    17
9230490    16
9708681    10
9839480    10
9401116    10
9897004    10
9703318    10
Name: IMO No, dtype: int64

In [26]:
sorrentodata_final['IMO No'].nunique()

21

In [27]:

scrubber = sorrentodata_final.loc[(sorrentodata_final['Report Type'] != "REFL") & (sorrentodata_final['SO2 CO2 RATIO'].notnull())]

scrubber_2 = sorrentodata_final.loc[(sorrentodata_final['SO2 CO2 RATIO'].astype(float) != 0.0) & (sorrentodata_final['SO2 CO2 RATIO'].astype(float) <= 12.7)]

In [30]:
scrubber

,GID,VSL,IMO No,VOY,Corrected Date,REPORT DATE TIME,REPORT DATE TIME Offset,Report Type,Status,LAT,LONG,M E FOC,CARGO TOTAL,Has Cargo,STEAMING TIME,Total M E Hours Fuel Only,MILES BY GPS,OIL CYL,SPEED BY LOG,SPEED BY GPS,RPM,SLIP,WIND DIRECTION,WIND SPEED,DRAFT AFT,DRAFT FWD,DISPLACEMENT,COURSE AT SEA,WAVE HEIGHT,SEA DIRECTION,CARGO TOTAL TEU,AMBIENT TEMP,SW TEMP,MILES BY SPEED LOG,ETA PORT CODE,ETA DATE TIME,ETA DATE TIME Offset,ETA PORT,TIME CHANGE,TIME SEA,TEMP MIN,TEMP MAX,REQUESTED SPEED,REM DIST TO PILOT,REM TIME TO PILOT,TOTAL UNPLND STPGE TECH,TOTAL UNPLND STPGE OPE WX,REEFERS POSITIVE PLUGGED,REEFERS NEGATIVE PLUGGED,ME TOTAL REVS COUNTER,PORT CODE,PORT,AUX BLOWERS ON,HOLD VENTILATION ON,TIME HRS ANCHOR,TIME HRS DRIFT,REASON,TYPE OF DELAY,ETB DATE TIME,ETB DATE TIME Offset,PILOT DATE TIME,PILOT DATE TIME Offset,TIME MANOEUVRING,TUG ARR,TUG SHIFT,ETD DATE TIME,ETD DATE TIME Offset,SHIFT BERTH HOURS,CARGO LOAD,CARGO DISCH,TEU FULL,TEU EMPTY,BILGE REMOVED,GARBAGE REMOVED,GARBAGE REMVL REQSTD,GARBAGE REMVL CMPLSRY,FW SUPPLY,CY CREW SIGNED ON,CY CREW SIGNED OFF,CY DOCTORS VISIT,CY MAIL RECEIVED Ref NO,CY LUB OIL SAMPLE LANDED,CY CHECKD FOR STOWAWAYS,CY STOWAWAYS ON BOARD,CY DEP GM Mtr,CY REQUISITIONS RECEIVED,DISTANCE TO NEXT PILOT,TUG SAILING TRANSIT,STEAMING TIME M E Rsdl VLS,STEAMING TIME M E Rsdl HS,STEAMING TIME M E Rsdl ULS,STEAMING TIME M E Dstlt VLS,STEAMING TIME M E Dstlt ULS,STEAMING TIME M E Tnktnr Dstlt VLS,STEAMING TIME M E MDO,STEAMING TIME AUX 1,STEAMING TIME AUX 2,STEAMING TIME AUX 3,STEAMING TIME AUX 4,STEAMING TIME AUX 5,STEAMING TIME SH GEN,STEAMING TIME TG,FUEL M E Rsdl VLS,FUEL M E Rsdl HS,FUEL M E Rsdl ULS,FUEL M E Dstlt VLS,FUEL M E Dstlt ULS,FUEL M E MDO,FUEL M E LNG,FUEL M E Tnktnr Dstlt VLS,FUEL Aux Rsdl VLS,FUEL Aux Rsdl HS,FUEL Aux Rsdl ULS,FUEL Aux Dstlt VLS,FUEL Aux Dstlt ULS,FUEL Aux Tnktnr Dstlt VLS,FUEL Aux LNG,FUEL Aux MDO,FUEL Boiler Rsdl VLS,FUEL Boiler Rsdl HS,FUEL Boiler Rsdl ULS,FUEL Boiler Dstlt VLS,FUEL Boiler Dstlt ULS,FUEL Boiler Tnktnr Dstlt VLS,FUEL Boiler LNG,FUEL Boiler MDO,POWER KW,STEAMING LOAD KW AUX 1,STEAMING LOAD KW AUX 2,STEAMING LOAD KW AUX 3,STEAMING LOAD KW AUX 4,STEAMING LOAD KW AUX 5,STEAMING LOAD KW SH GEN,STEAMING LOAD KW TG,DECK LAST CHANGE USER,ENGINE LAST CHANGE USER,DECK PART IS COMPLETE,ENGINE PART IS COMPLETE,SCAVENGE PRESSURE,SECA ENTRY TIME,SECA ENTRY LAT,SECA ENTRY LONG,SECA EXIT TIME,SECA EXIT LAT,SECA EXIT LONG,ROB FRESH WATER,MANVRNG MILES BY GPS,MANVRNG MILES BY SPEED LOG,TANKTAINER TRANSFD QUANTITY,PILOT TAKEN,DATE TIME START TRANSIT,DATE TIME START TRANSIT Offset,DATE TIME END TRANSIT,DATE TIME END TRANSIT Offset,BALLAST,TANKTAINER NUMBER,STEAMING KWHR TOTAL,CY OTHERS,ROB FO SLUDGE,ROB LO SLUDGE,ROB BILGE,SLUDGE REMOVED FO,SLUDGE REMOVED LO,SEA STATE,CY LUB ADDED TO SYSTEM MECC,CY LUB ADDED TO SYSTEM AECC,CY LUB ADDED TO THRUSTERS,CY ME LO PURIFIER IN USE,CY BALLAST,CY BENDING MOMENT,CY SHEARING FORCE,CY TORTION MOMENT,CY SUPDT AUDITOR SIGNED ON,CY SUPDT AUDITOR SIGNED OFF,CY CASH RECEIVED,CY LUB OIL RECEIVED MECYL,CY LUB OIL RECEIVED MECC,CY LUB OIL RECEIVED AECC,CY M E UNDER PISTON TEMP,CY MAIL RECEIVED,WIND DIRECTION PORT STBD,SEA DIRECTION PORT STBD,TIME PILOT ONBOARD,GRADES ROB,SO2 CO2 RATIO,Bunker Order,Remarks,BDN Number,Fuel Type,Carbon Factor,Sulphur Content PC,Quantity,Port Delivery,Product Quality,Tanktainer Number_1,Supplier,Delivery,Vol Lt,Den,Vis,ROB Dstlt ULS,ROB Dstlt VLS,ROB Rsdl MDO,ROB Tnktnr Dstlt VLS,ROB Rsdl VLS,ROB Rsdl HS,ROB Rsdl ULS,ROB Rsdl LNG,ECA MILES,ECA TIME,EGCS DRY WASTE REMOVED,EGCS RUNNING TIME,EGCS WET SLURRY REMOVED,EGCS OPEN LOOP RUNNING TIME,EGCS CLOSED LOOP RUNNING TIME
3969,fa889360-fc62-4bab-b312-18f9aa43bba0,MSC AMBRA,9839480,QG350E,2023-12-29,2023-12-29 12:00:00,UTC +01:00,NOON,AT SEA,2116N,01741W,136.0,163369.6,True,24.0,24.0,390.0,700.0,16.125000,16.250000,57.93,4.31,10.0,16.0,14.5,14.1,243119.0,181.0,0.04,100.07,14686.0,21.0,20.0,387.0,OMSLL,2024-01-15 01:00:00,UTC +04:00,SALALAH,NaN,24.0,300.0,320.0,20.1,7933.0,394.0,0.0,0.0,321.0,458.0,72910225.0,MAPTM,TANGER MED,False,True,NaN,NaN,WAITING PILOT BOARDING TIME,NaN,2023-12-26 02:00:00,UTC +01:00,NaT,NaN,NaN,NaN,NaN,2023-12-27 00:00:00,UTC +01:00,NaN,NaN,NaN,11119.0,3567.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,24.0,0.0,0.0,0.0,0.0,136.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32000.0,0.0,0.0,2300.0,2300.0,0.0,0.0,0.0,NaN,CH. ENG. CIBELLI G.,True,True,1.70,NaN,NaN,NaN,NaN,NaN,NaN,760.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,3485.0,0.0,119000.0,NaN,NaN,NaN,29.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,5911.00,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
3970,d3e0069e-3b0b-459b-9f83-466fef229e09,MSC AMBRA,9839480,QG350E,2023-12-30,2023-12-30 12:00:00,UTC +01:00,NOON,AT SEA,1300N,01742W,173.0,163369.6,True,24.0,24.0,495.0,790.0,20.375000,20.625000,71.81,3.35,40.0,31.0,14.5,14.1,242956.0,171.0,2.30,81.10,14686.0,25.0,25.0,489.0,OMSLL,2024-01-15 01:00:00,UTC +04:00,SALALAH,NaN,24.0,300.0,320.0,20.1,7435.0,370.0,0.0,0.0,321.0,458.0,73013631.0,MAPTM,TANGER MED,False,True,NaN,NaN,WAITING PILOT BOARDING TIME,NaN,2023-12-26 02:00:00,UTC +01:00,NaT,NaN,NaN,NaN,NaN,2023-12-27 00:00:00,UTC +01:00,NaN,NaN,NaN,11119.0,3567.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,24.0,0.0,0.0,0.0,0.0,173.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41000.0,0.0,2600.0,0.0,2600.0,0.0,0.0,0.0,NaN,CH. ENG. CIBELLI G.,True,True,1.60,NaN,NaN,NaN,NaN,NaN,NaN,800.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,3485.0,0.0,123000.0,NaN,NaN,NaN,32.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,5708.00,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
3971,fabd45c8-4ddc-4fca-bd98-91625f2764e4,MSC AMBRA,9839480,QG350E,2023-12-31,2023-12-31 12:00:00,UTC +01:00,NOON,AT SEA,0559N,01336W,173.0,163369.6,True,24.0,24.0,494.0,800.0,20.291667,20.583333,71.26,2.98,18.0,19.0,14.5,14.1,242782.0,143.0,0.23,113.18,14686.0,28.0,29.0,487.0,OMSLL,2024-01-15 01:00:00,UTC +04:00,SALALAH,NaN,24.0,300.0,320.0,20.1,6944.0,346.0,0.0,0.0,321.0,458.0,73116251.0,MAPTM,TANGER MED,False,True,NaN,NaN,WAITING PILOT BOARDING TIME,NaN,2023-12-26 02:00:00,UTC +01:00,NaT,NaN,NaN,NaN,NaN,2023-12-27 00:00:00,UTC +01:00,NaN,NaN,NaN,11119.0,3567.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,24.0,0.0,0.0,0.0,0.0,173.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,31.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40000.0,0.0,2700.0,0.0,2700.0,0.0,0.0,0.0,NaN,CH. ENG. CIBELLI G.,True,True,1.60,NaN,NaN,NaN,NaN,NaN,NaN,830.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,3485.0,0.0,129000.0,NaN,NaN,NaN,33.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,5504.00,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
3972,66664352-4eb9-4a6a-a3e7-3fcd675cb8a2,MSC AMBRA,9839480,QG350E,2024-01-01,2024-01-01 12:00:00,UTC +01:00,NOON,AT SEA,0016S,00854W,181.0,163369.6,True,24.0,24.0,469.0,840.0,19.458333,19.541667,70.91,6.33,5.0,28.0,14.5,14.1,242611.0,143.0,0.43,16.29,14686.0,28.0,27.0,467.0,OMSLL,2024-01-15 01:00:00,UTC +04:00,SALALAH,NaN,24.0,300.0,320.0,20.1,6476.0,322.0,0.0,0.0,321.0,458.0,73220656.0,MAPTM,TANGER MED,False,True,NaN,NaN,WAITING PILOT BOARDING TIME,NaN,2023-12-26 02:00:00,UTC +01:00,NaT,NaN,NaN,NaN,NaN,2023-12-27 00:00:00,UTC +01:00,NaN,NaN,NaN,11119.0,3567.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,24.0,0.0,0.0,0.0,0.0,181.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,42000.0,0.0,2800.0,0.0,2800.0,0.0,0.0,0.0,NaN,CH. ENG. CIBELLI G.,True,True,1.70,NaN,NaN,NaN,NaN,NaN,NaN,870.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,3485.0,0.0,133900.0,NaN,NaN,NaN,33.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,5291.00,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
3973,70dd500b-7b1f-424f-8d30-623d17e3bd2a,MSC AMBRA,9839480,QG350E,2024-01-02,2024-01-02 12:00:00,UTC +01:00,NOON,AT SEA,0619S,00423W,174.0,163369.6,True,24.0,24.0,453.0,800.0,18.750000,18.875000,69.72,9.27,12.0,32.0,14.5,14.1,242425.0,143.0,1.12,28.17,14686.0,27.0,27.0,450.0,OMSLL,2024-01-15 01:00:00,UTC +04:00,SALALAH,NaN,24.0,300.0,320.0,20.2,6024.0,298.0,0.0,0.0,321.0,458.0,73321058.0,MAPTM,TANGER MED,False,True,NaN,NaN,WAITING PILOT BOARDING TIME,NaN,2023-12-26 02:00:00,UTC +01:00,NaT,NaN,NaN,NaN,NaN,2023-12-27 00:00:00,UTC +01:00,NaN,NaN,NaN,11119.0,3567.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,24.0,0.0,0.0,0.0,0.0,174.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40000.0,0.0,2800.0,0.0,2800.0,0.0,0.0,0.0,NaN,CH. ENG. CIBELLI G.,True,True,1.60,NaN,NaN,NaN,NaN,NaN,NaN,890.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,3485.0,0.0,133000.0,NaN,NaN,NaN,33.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,5085.00,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9513,afc2bc7d-0a23-40e4-bcbd-498dd483793e,MSC ZOE,9703318,FT348W,2024-01-03,2024-01-03 12:00:00,UTC +01:00,NOON,AT SEA,0749S,00222W,126.1,186237.0,True,24.0,24.0,422.0,735.0,16.125000,17.583333,64.78,10.98,50.0,3.0,16.4,16.4,256810.7,324.0,1.41,171.65,13858.0,28.0,26.0,387.0,EGPSE,2024-01-16 08:00:00,UTC +02:00,PORT SAID EAST,NaN,24.0,280.0,310.0,16.6,5089.0,307.0,0.0,0.0,10.0,32.0,171808520.0,SGSIN,SINGAPORE,False,True,NaN,NaN,WAITING FOR NINGBO PILOT,NaN,2023-12-15 06:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2023-12-16 07:00:00,UTC +08:00,NaN,NaN,NaN,13756.0,102.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,126.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28449.0,2250.0,0.0,0.0,0.0,0.0,0.0,0.0,MASTER,CH.ENG,True,True,1.39,NaN,NaN,NaN,NaN,NaN,NaN,506.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,2890.5,0.0,54000.0,NaN,NaN,NaN,14.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,9.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2337.25,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
9514,6df76a90-641b-4965-9f3c-08269cc972c0,MSC ZOE,9703318,FT348W,2024-01-04,2024-01-04 12:00:00,UTC +01:00,NOON,AT SEA,0209S,00627W,124.7,186237.0,True,24.0,24.0,418.0,722.0,16.041667,17.416667,64.56,11.49,40.0,3.0,16.4,16.4,256810.7,324.0,1.31,172.74,13858.0,33.0,28.0,385.0,EGPSE,2024-01-16 08:00:00,UTC +02:00,PORT SAID EAST,NaN,24.0,280.0,310.0,16.5,4689.0,283.0,0.0,0.0,10.0,32.0,171901490.0,SGSIN,SINGAPORE,False,True,NaN,NaN,WAITING FOR NINGBO PILOT,NaN,2023-12-15 06:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2023-12-16 07:00:00,UTC +08:00,NaN,NaN,NaN,13756.0,102.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,124.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28104.0,2250.0,0.0,0.0,0.0,0.0,0.0,0.0,MASTER,CH.ENG,True,True,1.37,NaN,NaN,NaN,NaN,NaN,NaN,490.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,2890.5,0.0,54000.0,NaN,NaN,NaN,14.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,11.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2199.55,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
9515,436d1d69-5440-46fb-a5bc-b33dcacfc8f9,MSC ZOE,9703318,FT348W,2024-01-05,2024-01-05 12:00:00,UTC +01:00,NOON,AT SEA,0340N,01039W,126.5,186237.0,True,24.0,24.0,429.0,730.0,16.041667,17.875000,64.91,9.64,10.0,15.0,16.4,16.4,256810.7,324.0,0.09,139.99,13858.0,31.0,29.0,385.0,EGPSE,2024-01-16 08:00:00,UTC +02:00,PORT SAID EAST,NaN,24.0,280.0,310.0,16.4,4242.0,259.0,0.0,0.0,10.0,32.0,171994960.0,SGSIN,SINGAPORE,False,True,NaN,NaN,WAITING FOR NINGBO PILOT,NaN,2023-12-15 06:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2023-12-16 07:00:00,UTC +08:00,NaN,NaN,NaN,13756.0,102.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,126.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28536.0,2350.0,0.0,0.0,0.0,0.0,0.0,0.0,MASTER,CH.ENG,True,True,1.40,NaN,NaN,NaN,NaN,NaN,NaN,483.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,2890.5,0.0,56400.0,NaN,NaN,NaN,17.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,11.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2059.45,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
9516,b65991f8-796f-4209-a0a9-3ff98b2c7a6e,MSC ZOE,9703318,FT348W,2024-01-06,2024-01-06 12:00:00,UTC +00:00,NOON,AT SEA,0855N,01533W,133.0,186237.0,True,25.0,25.0,430.0,774.0,16.000000,17.200000,65.15,13.41,20.0,18.0,16.4,16.4,256810.7,316.0,0.21,92.66,13858.0,29.0,29.0,400.0,EGPSE,2024-01-16 08:00:00,UTC +02:00,PORT SAID EAST,NaN,25.0,280.0,310.0,16.3,3812.0,234.0,0.0,0.0,10.0,32.0,172092690.0,SGSIN,SINGAPORE,False,True,NaN,NaN,WAITING FOR NINGBO PILOT,NaN,2023-12-15 06:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2023-12-16 07:00:00,UTC +08:00,NaN,NaN,NaN,13756.0,102.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,25.0,0.0,0.0,0.0,0.0,0.0,25.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,133.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28744.0,2350.0,1100.0,0.0,0.0,0.0,0.0,0.0,MASTER,CH.ENG,True,True,1.41,NaN,NaN,NaN,NaN,NaN,NaN,474.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,2890.5,0.0,80750.0,NaN,NaN,NaN,20.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,11.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,1911.75,0.0,0.0,0.0,0.0,NaN,25.0,NaN,25.0,0.0
9517,9e3c9133-d25b-463d-a7f8-dc54df4d99c6,MSC ZOE,9703318,FT348W,2024-01-07,2024-01-07 12:00:00,UTC +00:00,NOON,AT SEA,1500N,01751W,129.9,186237.0,True,24.0,24.0,403.0,786.0,15.666667,16.791667,64.78,14.98,20.0,20.0,16.4,16.4,256810.7,357.0,0.29,73.69,13858.0,26.0,25.0,376.0,EGPSE,2024-01-16 08:00:00,UTC +02:00,PORT SAID EAST,NaN,24.0,280.0,310.0,16.3,3399.0,210.0,0.0,0.0,10.0,32.0,172185970.0,SGSIN,SINGAPORE,False,True,NaN,NaN,WAITING FOR NINGBO PILOT,NaN,2023-12-15 06:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2023-12-16 07:00:00,UTC +08:00,NaN,NaN,NaN,13756.0,102.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,129.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29389.0,2350.0,1100.0,0.0,0.0,0.0,0.0,0.0,MASTER,CH.ENG,True,True,1.43,NaN,NaN,NaN,NaN,NaN,NaN,461.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,2890.5,0.0,78400.0,NaN,NaN,NaN,20.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,7.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,1767.95,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0

In [31]:
scrubber

,GID,VSL,IMO No,VOY,Corrected Date,REPORT DATE TIME,REPORT DATE TIME Offset,Report Type,Status,LAT,LONG,M E FOC,CARGO TOTAL,Has Cargo,STEAMING TIME,Total M E Hours Fuel Only,MILES BY GPS,OIL CYL,SPEED BY LOG,SPEED BY GPS,RPM,SLIP,WIND DIRECTION,WIND SPEED,DRAFT AFT,DRAFT FWD,DISPLACEMENT,COURSE AT SEA,WAVE HEIGHT,SEA DIRECTION,CARGO TOTAL TEU,AMBIENT TEMP,SW TEMP,MILES BY SPEED LOG,ETA PORT CODE,ETA DATE TIME,ETA DATE TIME Offset,ETA PORT,TIME CHANGE,TIME SEA,TEMP MIN,TEMP MAX,REQUESTED SPEED,REM DIST TO PILOT,REM TIME TO PILOT,TOTAL UNPLND STPGE TECH,TOTAL UNPLND STPGE OPE WX,REEFERS POSITIVE PLUGGED,REEFERS NEGATIVE PLUGGED,ME TOTAL REVS COUNTER,PORT CODE,PORT,AUX BLOWERS ON,HOLD VENTILATION ON,TIME HRS ANCHOR,TIME HRS DRIFT,REASON,TYPE OF DELAY,ETB DATE TIME,ETB DATE TIME Offset,PILOT DATE TIME,PILOT DATE TIME Offset,TIME MANOEUVRING,TUG ARR,TUG SHIFT,ETD DATE TIME,ETD DATE TIME Offset,SHIFT BERTH HOURS,CARGO LOAD,CARGO DISCH,TEU FULL,TEU EMPTY,BILGE REMOVED,GARBAGE REMOVED,GARBAGE REMVL REQSTD,GARBAGE REMVL CMPLSRY,FW SUPPLY,CY CREW SIGNED ON,CY CREW SIGNED OFF,CY DOCTORS VISIT,CY MAIL RECEIVED Ref NO,CY LUB OIL SAMPLE LANDED,CY CHECKD FOR STOWAWAYS,CY STOWAWAYS ON BOARD,CY DEP GM Mtr,CY REQUISITIONS RECEIVED,DISTANCE TO NEXT PILOT,TUG SAILING TRANSIT,STEAMING TIME M E Rsdl VLS,STEAMING TIME M E Rsdl HS,STEAMING TIME M E Rsdl ULS,STEAMING TIME M E Dstlt VLS,STEAMING TIME M E Dstlt ULS,STEAMING TIME M E Tnktnr Dstlt VLS,STEAMING TIME M E MDO,STEAMING TIME AUX 1,STEAMING TIME AUX 2,STEAMING TIME AUX 3,STEAMING TIME AUX 4,STEAMING TIME AUX 5,STEAMING TIME SH GEN,STEAMING TIME TG,FUEL M E Rsdl VLS,FUEL M E Rsdl HS,FUEL M E Rsdl ULS,FUEL M E Dstlt VLS,FUEL M E Dstlt ULS,FUEL M E MDO,FUEL M E LNG,FUEL M E Tnktnr Dstlt VLS,FUEL Aux Rsdl VLS,FUEL Aux Rsdl HS,FUEL Aux Rsdl ULS,FUEL Aux Dstlt VLS,FUEL Aux Dstlt ULS,FUEL Aux Tnktnr Dstlt VLS,FUEL Aux LNG,FUEL Aux MDO,FUEL Boiler Rsdl VLS,FUEL Boiler Rsdl HS,FUEL Boiler Rsdl ULS,FUEL Boiler Dstlt VLS,FUEL Boiler Dstlt ULS,FUEL Boiler Tnktnr Dstlt VLS,FUEL Boiler LNG,FUEL Boiler MDO,POWER KW,STEAMING LOAD KW AUX 1,STEAMING LOAD KW AUX 2,STEAMING LOAD KW AUX 3,STEAMING LOAD KW AUX 4,STEAMING LOAD KW AUX 5,STEAMING LOAD KW SH GEN,STEAMING LOAD KW TG,DECK LAST CHANGE USER,ENGINE LAST CHANGE USER,DECK PART IS COMPLETE,ENGINE PART IS COMPLETE,SCAVENGE PRESSURE,SECA ENTRY TIME,SECA ENTRY LAT,SECA ENTRY LONG,SECA EXIT TIME,SECA EXIT LAT,SECA EXIT LONG,ROB FRESH WATER,MANVRNG MILES BY GPS,MANVRNG MILES BY SPEED LOG,TANKTAINER TRANSFD QUANTITY,PILOT TAKEN,DATE TIME START TRANSIT,DATE TIME START TRANSIT Offset,DATE TIME END TRANSIT,DATE TIME END TRANSIT Offset,BALLAST,TANKTAINER NUMBER,STEAMING KWHR TOTAL,CY OTHERS,ROB FO SLUDGE,ROB LO SLUDGE,ROB BILGE,SLUDGE REMOVED FO,SLUDGE REMOVED LO,SEA STATE,CY LUB ADDED TO SYSTEM MECC,CY LUB ADDED TO SYSTEM AECC,CY LUB ADDED TO THRUSTERS,CY ME LO PURIFIER IN USE,CY BALLAST,CY BENDING MOMENT,CY SHEARING FORCE,CY TORTION MOMENT,CY SUPDT AUDITOR SIGNED ON,CY SUPDT AUDITOR SIGNED OFF,CY CASH RECEIVED,CY LUB OIL RECEIVED MECYL,CY LUB OIL RECEIVED MECC,CY LUB OIL RECEIVED AECC,CY M E UNDER PISTON TEMP,CY MAIL RECEIVED,WIND DIRECTION PORT STBD,SEA DIRECTION PORT STBD,TIME PILOT ONBOARD,GRADES ROB,SO2 CO2 RATIO,Bunker Order,Remarks,BDN Number,Fuel Type,Carbon Factor,Sulphur Content PC,Quantity,Port Delivery,Product Quality,Tanktainer Number_1,Supplier,Delivery,Vol Lt,Den,Vis,ROB Dstlt ULS,ROB Dstlt VLS,ROB Rsdl MDO,ROB Tnktnr Dstlt VLS,ROB Rsdl VLS,ROB Rsdl HS,ROB Rsdl ULS,ROB Rsdl LNG,ECA MILES,ECA TIME,EGCS DRY WASTE REMOVED,EGCS RUNNING TIME,EGCS WET SLURRY REMOVED,EGCS OPEN LOOP RUNNING TIME,EGCS CLOSED LOOP RUNNING TIME
3969,fa889360-fc62-4bab-b312-18f9aa43bba0,MSC AMBRA,9839480,QG350E,2023-12-29,2023-12-29 12:00:00,UTC +01:00,NOON,AT SEA,2116N,01741W,136.0,163369.6,True,24.0,24.0,390.0,700.0,16.125000,16.250000,57.93,4.31,10.0,16.0,14.5,14.1,243119.0,181.0,0.04,100.07,14686.0,21.0,20.0,387.0,OMSLL,2024-01-15 01:00:00,UTC +04:00,SALALAH,NaN,24.0,300.0,320.0,20.1,7933.0,394.0,0.0,0.0,321.0,458.0,72910225.0,MAPTM,TANGER MED,False,True,NaN,NaN,WAITING PILOT BOARDING TIME,NaN,2023-12-26 02:00:00,UTC +01:00,NaT,NaN,NaN,NaN,NaN,2023-12-27 00:00:00,UTC +01:00,NaN,NaN,NaN,11119.0,3567.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,24.0,0.0,0.0,0.0,0.0,136.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32000.0,0.0,0.0,2300.0,2300.0,0.0,0.0,0.0,NaN,CH. ENG. CIBELLI G.,True,True,1.70,NaN,NaN,NaN,NaN,NaN,NaN,760.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,3485.0,0.0,119000.0,NaN,NaN,NaN,29.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,5911.00,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
3970,d3e0069e-3b0b-459b-9f83-466fef229e09,MSC AMBRA,9839480,QG350E,2023-12-30,2023-12-30 12:00:00,UTC +01:00,NOON,AT SEA,1300N,01742W,173.0,163369.6,True,24.0,24.0,495.0,790.0,20.375000,20.625000,71.81,3.35,40.0,31.0,14.5,14.1,242956.0,171.0,2.30,81.10,14686.0,25.0,25.0,489.0,OMSLL,2024-01-15 01:00:00,UTC +04:00,SALALAH,NaN,24.0,300.0,320.0,20.1,7435.0,370.0,0.0,0.0,321.0,458.0,73013631.0,MAPTM,TANGER MED,False,True,NaN,NaN,WAITING PILOT BOARDING TIME,NaN,2023-12-26 02:00:00,UTC +01:00,NaT,NaN,NaN,NaN,NaN,2023-12-27 00:00:00,UTC +01:00,NaN,NaN,NaN,11119.0,3567.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,24.0,0.0,0.0,0.0,0.0,173.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41000.0,0.0,2600.0,0.0,2600.0,0.0,0.0,0.0,NaN,CH. ENG. CIBELLI G.,True,True,1.60,NaN,NaN,NaN,NaN,NaN,NaN,800.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,3485.0,0.0,123000.0,NaN,NaN,NaN,32.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,5708.00,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
3971,fabd45c8-4ddc-4fca-bd98-91625f2764e4,MSC AMBRA,9839480,QG350E,2023-12-31,2023-12-31 12:00:00,UTC +01:00,NOON,AT SEA,0559N,01336W,173.0,163369.6,True,24.0,24.0,494.0,800.0,20.291667,20.583333,71.26,2.98,18.0,19.0,14.5,14.1,242782.0,143.0,0.23,113.18,14686.0,28.0,29.0,487.0,OMSLL,2024-01-15 01:00:00,UTC +04:00,SALALAH,NaN,24.0,300.0,320.0,20.1,6944.0,346.0,0.0,0.0,321.0,458.0,73116251.0,MAPTM,TANGER MED,False,True,NaN,NaN,WAITING PILOT BOARDING TIME,NaN,2023-12-26 02:00:00,UTC +01:00,NaT,NaN,NaN,NaN,NaN,2023-12-27 00:00:00,UTC +01:00,NaN,NaN,NaN,11119.0,3567.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,24.0,0.0,0.0,0.0,0.0,173.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,31.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40000.0,0.0,2700.0,0.0,2700.0,0.0,0.0,0.0,NaN,CH. ENG. CIBELLI G.,True,True,1.60,NaN,NaN,NaN,NaN,NaN,NaN,830.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,3485.0,0.0,129000.0,NaN,NaN,NaN,33.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,5504.00,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
3972,66664352-4eb9-4a6a-a3e7-3fcd675cb8a2,MSC AMBRA,9839480,QG350E,2024-01-01,2024-01-01 12:00:00,UTC +01:00,NOON,AT SEA,0016S,00854W,181.0,163369.6,True,24.0,24.0,469.0,840.0,19.458333,19.541667,70.91,6.33,5.0,28.0,14.5,14.1,242611.0,143.0,0.43,16.29,14686.0,28.0,27.0,467.0,OMSLL,2024-01-15 01:00:00,UTC +04:00,SALALAH,NaN,24.0,300.0,320.0,20.1,6476.0,322.0,0.0,0.0,321.0,458.0,73220656.0,MAPTM,TANGER MED,False,True,NaN,NaN,WAITING PILOT BOARDING TIME,NaN,2023-12-26 02:00:00,UTC +01:00,NaT,NaN,NaN,NaN,NaN,2023-12-27 00:00:00,UTC +01:00,NaN,NaN,NaN,11119.0,3567.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,24.0,0.0,0.0,0.0,0.0,181.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,42000.0,0.0,2800.0,0.0,2800.0,0.0,0.0,0.0,NaN,CH. ENG. CIBELLI G.,True,True,1.70,NaN,NaN,NaN,NaN,NaN,NaN,870.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,3485.0,0.0,133900.0,NaN,NaN,NaN,33.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,5291.00,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
3973,70dd500b-7b1f-424f-8d30-623d17e3bd2a,MSC AMBRA,9839480,QG350E,2024-01-02,2024-01-02 12:00:00,UTC +01:00,NOON,AT SEA,0619S,00423W,174.0,163369.6,True,24.0,24.0,453.0,800.0,18.750000,18.875000,69.72,9.27,12.0,32.0,14.5,14.1,242425.0,143.0,1.12,28.17,14686.0,27.0,27.0,450.0,OMSLL,2024-01-15 01:00:00,UTC +04:00,SALALAH,NaN,24.0,300.0,320.0,20.2,6024.0,298.0,0.0,0.0,321.0,458.0,73321058.0,MAPTM,TANGER MED,False,True,NaN,NaN,WAITING PILOT BOARDING TIME,NaN,2023-12-26 02:00:00,UTC +01:00,NaT,NaN,NaN,NaN,NaN,2023-12-27 00:00:00,UTC +01:00,NaN,NaN,NaN,11119.0,3567.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,24.0,0.0,0.0,0.0,0.0,174.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40000.0,0.0,2800.0,0.0,2800.0,0.0,0.0,0.0,NaN,CH. ENG. CIBELLI G.,True,True,1.60,NaN,NaN,NaN,NaN,NaN,NaN,890.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,3485.0,0.0,133000.0,NaN,NaN,NaN,33.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,5085.00,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9513,afc2bc7d-0a23-40e4-bcbd-498dd483793e,MSC ZOE,9703318,FT348W,2024-01-03,2024-01-03 12:00:00,UTC +01:00,NOON,AT SEA,0749S,00222W,126.1,186237.0,True,24.0,24.0,422.0,735.0,16.125000,17.583333,64.78,10.98,50.0,3.0,16.4,16.4,256810.7,324.0,1.41,171.65,13858.0,28.0,26.0,387.0,EGPSE,2024-01-16 08:00:00,UTC +02:00,PORT SAID EAST,NaN,24.0,280.0,310.0,16.6,5089.0,307.0,0.0,0.0,10.0,32.0,171808520.0,SGSIN,SINGAPORE,False,True,NaN,NaN,WAITING FOR NINGBO PILOT,NaN,2023-12-15 06:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2023-12-16 07:00:00,UTC +08:00,NaN,NaN,NaN,13756.0,102.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,126.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28449.0,2250.0,0.0,0.0,0.0,0.0,0.0,0.0,MASTER,CH.ENG,True,True,1.39,NaN,NaN,NaN,NaN,NaN,NaN,506.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,2890.5,0.0,54000.0,NaN,NaN,NaN,14.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,9.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2337.25,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
9514,6df76a90-641b-4965-9f3c-08269cc972c0,MSC ZOE,9703318,FT348W,2024-01-04,2024-01-04 12:00:00,UTC +01:00,NOON,AT SEA,0209S,00627W,124.7,186237.0,True,24.0,24.0,418.0,722.0,16.041667,17.416667,64.56,11.49,40.0,3.0,16.4,16.4,256810.7,324.0,1.31,172.74,13858.0,33.0,28.0,385.0,EGPSE,2024-01-16 08:00:00,UTC +02:00,PORT SAID EAST,NaN,24.0,280.0,310.0,16.5,4689.0,283.0,0.0,0.0,10.0,32.0,171901490.0,SGSIN,SINGAPORE,False,True,NaN,NaN,WAITING FOR NINGBO PILOT,NaN,2023-12-15 06:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2023-12-16 07:00:00,UTC +08:00,NaN,NaN,NaN,13756.0,102.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,124.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28104.0,2250.0,0.0,0.0,0.0,0.0,0.0,0.0,MASTER,CH.ENG,True,True,1.37,NaN,NaN,NaN,NaN,NaN,NaN,490.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,2890.5,0.0,54000.0,NaN,NaN,NaN,14.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,11.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2199.55,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
9515,436d1d69-5440-46fb-a5bc-b33dcacfc8f9,MSC ZOE,9703318,FT348W,2024-01-05,2024-01-05 12:00:00,UTC +01:00,NOON,AT SEA,0340N,01039W,126.5,186237.0,True,24.0,24.0,429.0,730.0,16.041667,17.875000,64.91,9.64,10.0,15.0,16.4,16.4,256810.7,324.0,0.09,139.99,13858.0,31.0,29.0,385.0,EGPSE,2024-01-16 08:00:00,UTC +02:00,PORT SAID EAST,NaN,24.0,280.0,310.0,16.4,4242.0,259.0,0.0,0.0,10.0,32.0,171994960.0,SGSIN,SINGAPORE,False,True,NaN,NaN,WAITING FOR NINGBO PILOT,NaN,2023-12-15 06:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2023-12-16 07:00:00,UTC +08:00,NaN,NaN,NaN,13756.0,102.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,126.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28536.0,2350.0,0.0,0.0,0.0,0.0,0.0,0.0,MASTER,CH.ENG,True,True,1.40,NaN,NaN,NaN,NaN,NaN,NaN,483.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,2890.5,0.0,56400.0,NaN,NaN,NaN,17.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,11.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2059.45,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
9516,b65991f8-796f-4209-a0a9-3ff98b2c7a6e,MSC ZOE,9703318,FT348W,2024-01-06,2024-01-06 12:00:00,UTC +00:00,NOON,AT SEA,0855N,01533W,133.0,186237.0,True,25.0,25.0,430.0,774.0,16.000000,17.200000,65.15,13.41,20.0,18.0,16.4,16.4,256810.7,316.0,0.21,92.66,13858.0,29.0,29.0,400.0,EGPSE,2024-01-16 08:00:00,UTC +02:00,PORT SAID EAST,NaN,25.0,280.0,310.0,16.3,3812.0,234.0,0.0,0.0,10.0,32.0,172092690.0,SGSIN,SINGAPORE,False,True,NaN,NaN,WAITING FOR NINGBO PILOT,NaN,2023-12-15 06:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2023-12-16 07:00:00,UTC +08:00,NaN,NaN,NaN,13756.0,102.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,25.0,0.0,0.0,0.0,0.0,0.0,25.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,133.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28744.0,2350.0,1100.0,0.0,0.0,0.0,0.0,0.0,MASTER,CH.ENG,True,True,1.41,NaN,NaN,NaN,NaN,NaN,NaN,474.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,2890.5,0.0,80750.0,NaN,NaN,NaN,20.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,11.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,1911.75,0.0,0.0,0.0,0.0,NaN,25.0,NaN,25.0,0.0
9517,9e3c9133-d25b-463d-a7f8-dc54df4d99c6,MSC ZOE,9703318,FT348W,2024-01-07,2024-01-07 12:00:00,UTC +00:00,NOON,AT SEA,1500N,01751W,129.9,186237.0,True,24.0,24.0,403.0,786.0,15.666667,16.791667,64.78,14.98,20.0,20.0,16.4,16.4,256810.7,357.0,0.29,73.69,13858.0,26.0,25.0,376.0,EGPSE,2024-01-16 08:00:00,UTC +02:00,PORT SAID EAST,NaN,24.0,280.0,310.0,16.3,3399.0,210.0,0.0,0.0,10.0,32.0,172185970.0,SGSIN,SINGAPORE,False,True,NaN,NaN,WAITING FOR NINGBO PILOT,NaN,2023-12-15 06:00:00,UTC +08:00,NaT,NaN,NaN,NaN,NaN,2023-12-16 07:00:00,UTC +08:00,NaN,NaN,NaN,13756.0,102.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,129.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29389.0,2350.0,1100.0,0.0,0.0,0.0,0.0,0.0,MASTER,CH.ENG,True,True,1.43,NaN,NaN,NaN,NaN,NaN,NaN,461.0,NaN,NaN,NaN,False,NaT,NaN,NaT,NaN,2890.5,0.0,78400.0,NaN,NaN,NaN,20.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,7.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,1767.95,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0

In [15]:
print(refl_sorrento['SO2 CO2 RATIO'])

4974    NaN
4975    NaN
4976    NaN
4977    NaN
5114    NaN
6653    NaN
7674    2.5
7882    NaN
7883    NaN
8104    NaN
Name: SO2 CO2 RATIO, dtype: float64