In [1]:
import pandas as pd

In [2]:
data= pd.read_csv(r'D:\Navalt\Files\Agrigento(noon)_2023.csv')
data

,id,pi_sog,pi_stw,true_wind_dir,true_wind_speed,relative_wind_speed,relative_wind_direction,caa,corrected_power,rw,...,rob_garbage_cat_a_plastic,rob_garbage_cat_b_organic,rob_garbage_cat_c_domestic,rob_garbage_cat_e_ashes,qty_sludge_disposed,steaming_time_m_e_lng,reefer_power_consumption,wind_direction_side,sea_direction_side,tot_sludge_removed
0,3967337,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4024822,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4035777,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4556116,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4136078,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
780,4678893,-16.18025,-17.41289,63.87343,13.40235,5.27933,295.32903,0.07655,19640.16520,-43786.38527,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
781,4682049,-16.66119,-18.32759,85.00000,4.93003,3.20796,0.00000,0.64615,13209.01733,-29859.39422,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
782,4683294,-18.31479,-18.54489,-53.27597,1.14677,8.10846,4.41983,0.69028,12887.67514,10955.08236,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
783,4687173,-18.46259,-18.46259,-35.48605,8.01865,12.45870,27.87660,0.65387,12037.36750,68699.76975,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
784,4688863,-17.14677,-17.37130,-50.57986,9.18713,14.81501,18.70469,0.73044,14110.71001,123651.57002,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data.columns

Index(['id', 'pi_sog', 'pi_stw', 'true_wind_dir', 'true_wind_speed',
       'relative_wind_speed', 'relative_wind_direction', 'caa',
       'corrected_power', 'rw',
       ...
       'rob_garbage_cat_a_plastic', 'rob_garbage_cat_b_organic',
       'rob_garbage_cat_c_domestic', 'rob_garbage_cat_e_ashes',
       'qty_sludge_disposed', 'steaming_time_m_e_lng',
       'reefer_power_consumption', 'wind_direction_side', 'sea_direction_side',
       'tot_sludge_removed'],
      dtype='object', length=356)

In [4]:
for i in data.columns:    
    if "date" in i:
        print(i)

corrected_date
report_date_time
report_date_time_offset
eta_date_time
eta_date_time_offset
since_date_time
since_date_time_offset
etb_date_time
etb_date_time_offset
pilot_date_time
pilot_date_time_offset
etd_date_time
etd_date_time_offset
date_time_start_transit
date_time_start_transit_offset
date_time_end_transit
date_time_end_transit_offset
same_date
updated_date
updated_at
updated_by_id

In [5]:
speed_by_gps
power_kw
rpm
draft
sea_state
report_date_time

NameError: name 'speed_by_gps' is not defined

In [7]:
df=data[['report_date_time','speed_by_gps','power_kw','rpm','draft','sea_state']]
df

        report_date_time  speed_by_gps  power_kw   rpm  draft  sea_state
0    2023-01-08 06:41:59        0.0000         0   0.0   0.00        NaN
1    2023-01-19 06:29:59        0.0000         0   0.0   0.00        NaN
2    2023-01-12 22:47:59        0.0000         0   0.0   0.00        NaN
3    2023-10-28 12:35:00        0.0000         0   0.0   0.00        NaN
4    2023-04-12 18:00:00        0.0000         0   0.0   0.00        NaN
..                   ...           ...       ...   ...    ...        ...
780  2023-12-27 12:00:00       16.3200     19115  57.8  11.65        4.0
781  2023-12-28 12:00:00       14.5833     12889  51.0  11.65        4.0
782  2023-12-29 12:00:00       14.2000     13002  51.1  11.65        3.0
783  2023-12-30 12:00:00       13.9167     12740  50.7  11.65        4.0
784  2023-12-31 12:00:00       14.7600     15452  53.7  11.65        4.0

[785 rows x 6 columns]

In [8]:
df['speed_by_gps'].min()

0.0

In [9]:
df['speed_by_gps'].max()

20.0417

In [10]:
new_df=df[df['speed_by_gps'] > 0.0].reset_index().drop("index",axis=1)
new_df

        report_date_time  speed_by_gps  power_kw   rpm  draft  sea_state
0    2023-09-29 08:24:00       18.8235     27157  67.0  12.45        3.0
1    2023-04-01 12:00:00       12.9583      8894  45.7  13.80        3.0
2    2023-01-21 12:00:00       15.6250     12118  51.5  13.60        3.0
3    2023-01-26 12:00:00       13.6667     10069  48.0  13.60        2.0
4    2023-01-29 12:00:00       13.0000      9846  47.5  13.60        4.0
..                   ...           ...       ...   ...    ...        ...
308  2023-12-27 12:00:00       16.3200     19115  57.8  11.65        4.0
309  2023-12-28 12:00:00       14.5833     12889  51.0  11.65        4.0
310  2023-12-29 12:00:00       14.2000     13002  51.1  11.65        3.0
311  2023-12-30 12:00:00       13.9167     12740  50.7  11.65        4.0
312  2023-12-31 12:00:00       14.7600     15452  53.7  11.65        4.0

[313 rows x 6 columns]

In [11]:
new_df['speed_by_gps'].min()

8.0

In [12]:
new_df['speed_by_gps'].max()

20.0417

In [ ]:

min_sog = round(float(df.min(skipna=True)))
max_sog =round(float(df.max(skipna=True)))


range_no = max_sog - min_sog

if min_sog == 0 and max_sog == 0:
        sog_data = [{'range' :'0 - 0','value' : 0}]

else:

    if range_no <5:
        range_list = list(range(0, max_sog+2))

    else:
        range_list = list(range(0, max_sog+2 , 2))

In [30]:

min_sog = round(float(new_df['speed_by_gps'].min(skipna=True)))
max_sog =round(float(new_df['speed_by_gps'].max(skipna=True)))
#max_sog=14

range_no = max_sog - min_sog

print(range_no)

12

In [31]:
if min_sog == 0 and max_sog == 0:
        sog_data = [{'range' :'0 - 0','value' : 0}]

else:

    if range_no <5:
        range_list = list(range(0, max_sog+2))

    else:
        range_list = list(range(0, max_sog+2 , 2))
        
print(range_list)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [ ]:
df = (((df*2).round().astype(int)))/2

df2 = pd.DataFrame()

df2 = pd.cut(x = df['values'],bins = range_list )



df2 = df2.value_counts().sort_index()

In [32]:
def round_x(x):
    x=int(round(x*2))/2
    return(x)

In [33]:
round_x(2.3896)

2.5

In [34]:
new_df

        report_date_time  speed_by_gps  power_kw   rpm  draft  sea_state
0    2023-09-29 08:24:00          19.0   27157.0  67.0   12.5        3.0
1    2023-04-01 12:00:00          13.0    8894.0  45.5   14.0        3.0
2    2023-01-21 12:00:00          15.5   12118.0  51.5   13.5        3.0
3    2023-01-26 12:00:00          13.5   10069.0  48.0   13.5        2.0
4    2023-01-29 12:00:00          13.0    9846.0  47.5   13.5        4.0
..                   ...           ...       ...   ...    ...        ...
308  2023-12-27 12:00:00          16.5   19115.0  58.0   11.5        4.0
309  2023-12-28 12:00:00          14.5   12889.0  51.0   11.5        4.0
310  2023-12-29 12:00:00          14.0   13002.0  51.0   11.5        3.0
311  2023-12-30 12:00:00          14.0   12740.0  50.5   11.5        4.0
312  2023-12-31 12:00:00          15.0   15452.0  53.5   11.5        4.0

[313 rows x 6 columns]

In [22]:
new_df['speed_by_gps']= new_df['speed_by_gps'].apply(round_x)

0      19.0
1      13.0
2      15.5
3      13.5
4      13.0
       ...
308    16.5
309    14.5
310    14.0
311    14.0
312    15.0
Name: speed_by_gps, Length: 313, dtype: float64

In [35]:
new_df['speed_by_gps']= new_df['speed_by_gps'].apply(round_x)
new_df['power_kw']=new_df['power_kw'].apply(round_x)
new_df['rpm']=new_df['rpm'].apply(round_x)
new_df['draft']=new_df['draft'].apply(round_x)
new_df['sea_state']=new_df['sea_state'].apply(round_x)

In [36]:
new_df

        report_date_time  speed_by_gps  power_kw   rpm  draft  sea_state
0    2023-09-29 08:24:00          19.0   27157.0  67.0   12.5        3.0
1    2023-04-01 12:00:00          13.0    8894.0  45.5   14.0        3.0
2    2023-01-21 12:00:00          15.5   12118.0  51.5   13.5        3.0
3    2023-01-26 12:00:00          13.5   10069.0  48.0   13.5        2.0
4    2023-01-29 12:00:00          13.0    9846.0  47.5   13.5        4.0
..                   ...           ...       ...   ...    ...        ...
308  2023-12-27 12:00:00          16.5   19115.0  58.0   11.5        4.0
309  2023-12-28 12:00:00          14.5   12889.0  51.0   11.5        4.0
310  2023-12-29 12:00:00          14.0   13002.0  51.0   11.5        3.0
311  2023-12-30 12:00:00          14.0   12740.0  50.5   11.5        4.0
312  2023-12-31 12:00:00          15.0   15452.0  53.5   11.5        4.0

[313 rows x 6 columns]

In [37]:
range_list

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [43]:
df2=pd.cut(x = new_df['speed_by_gps'],bins = range_list )
df2

0      (18, 20]
1      (12, 14]
2      (14, 16]
3      (12, 14]
4      (12, 14]
         ...
308    (16, 18]
309    (14, 16]
310    (12, 14]
311    (12, 14]
312    (14, 16]
Name: speed_by_gps, Length: 313, dtype: category
Categories (10, interval[int64, right]): [(0, 2] < (2, 4] < (4, 6] < (6, 8] ... (12, 14] < (14, 16] < (16, 18] < (18, 20]]

In [45]:
df22 = df2.value_counts().sort_index()
df22

(0, 2]       0
(2, 4]       0
(4, 6]       0
(6, 8]       1
(8, 10]      8
(10, 12]    59
(12, 14]    91
(14, 16]    70
(16, 18]    72
(18, 20]    12
Name: speed_by_gps, dtype: int64

In [50]:
df22

(0, 2]       0
(2, 4]       0
(4, 6]       0
(6, 8]       1
(8, 10]      8
(10, 12]    59
(12, 14]    91
(14, 16]    70
(16, 18]    72
(18, 20]    12
Name: speed_by_gps, dtype: int64

In [51]:
df3=pd.DataFrame()
df3['range'] = df22.keys()
df3

      range
0    (0, 2]
1    (2, 4]
2    (4, 6]
3    (6, 8]
4   (8, 10]
5  (10, 12]
6  (12, 14]
7  (14, 16]
8  (16, 18]
9  (18, 20]

In [79]:
df3['value'] = df22.values
df3

   range  value
0    0-2      0
1    2-4      0
2    4-6      0
3    6-8      1
4   8-10      8
5  10-12     59
6  12-14     91
7  14-16     70
8  16-18     72
9  18-20     12

In [80]:
df3['value']

0     0
1     0
2     0
3     1
4     8
5    59
6    91
7    70
8    72
9    12
Name: value, dtype: int64

In [82]:
((df3['value']/sum_of_sog)*100).round(2).values

array([ 0.  ,  0.  ,  0.  ,  0.32,  2.56, 18.85, 29.07, 22.36, 23.  ,
        3.83])

In [77]:
sum_of_sog= sum(df22.values)
sum_of_sog

313

In [83]:
import re
sum_of_sog= sum(df22.values)
df3['value'] = ((df3['value']/sum_of_sog)*100).round(2).values

df3['range'] = df3['range'].astype(str)

df3['range'] = df3['range'].str.replace(',','-',regex=True)
df3['range'] = df3['range'].str.replace(re.escape("("), '', regex=True)
df3['range'] = df3['range'].str.replace(']','',regex=True)
df3['range'] = df3['range'].str.replace(' ','',regex=True)

In [84]:
df3

   range  value
0    0-2   0.00
1    2-4   0.00
2    4-6   0.00
3    6-8   0.32
4   8-10   2.56
5  10-12  18.85
6  12-14  29.07
7  14-16  22.36
8  16-18  23.00
9  18-20   3.83