In [1]:
import pandas as pd

# Oct

In [46]:

week12=pd.read_excel(r'D:\Navalt\MSC\2024\Weekly Data\CHARTER\CLIENT\OneDrive_1_10-17-2024\10a.Complete data Week 40 2024.xlsx')
week13=pd.read_excel(r'D:\Navalt\MSC\2024\Weekly Data\CHARTER\CLIENT\OneDrive_1_10-17-2024\10b.Complete data Week 41 2024.xlsx')

In [47]:
oct=pd.concat([week12,week13])

In [48]:
# Ensure 'REPORT DATE TIME' is in datetime format
oct['REPORT DATE TIME'] = pd.to_datetime(oct['REPORT DATE TIME'])

# Filter the DataFrame for the given date range
filtered_oct = oct[(oct['REPORT DATE TIME'] >= pd.Timestamp('2024-10-01 00:00:00')) & 
                   (oct['REPORT DATE TIME'] <= pd.Timestamp('2024-10-30 23:59:59'))]

In [52]:
filtered_oct

,GID,VSL,IMO No,VOY,Corrected Date,REPORT DATE TIME,REPORT DATE TIME Offset,Report Type,Status,LAT,...,ROB Rsdl HS,ROB Rsdl ULS,ROB Rsdl LNG,ECA MILES,ECA TIME,EGCS DRY WASTE REMOVED,EGCS RUNNING TIME,EGCS WET SLURRY REMOVED,EGCS OPEN LOOP RUNNING TIME,EGCS CLOSED LOOP RUNNING TIME
21,ff6fdd11-d9e7-414d-8c38-36d5d61989b4,AGIOS DIMITRIOS,9349605.0,IP434A,2024-10-01,2024-10-01 12:00:00,UTC +01:00,DLY A,DRIFTING,5152N,...,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0
22,6f32b992-ebf6-4a9f-a94a-ff65495b7b62,AGIOS DIMITRIOS,9349605.0,NaN,2024-10-02,2024-10-01 14:29:59,UTC +01:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,ad522182-ef6b-4060-a141-be1401486fe5,AGIOS DIMITRIOS,9349605.0,NaN,2024-10-02,2024-10-01 14:29:59,UTC +01:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,cd65c3ab-99a0-4c70-b1ac-deb95c3f94b5,AGIOS DIMITRIOS,9349605.0,NaN,2024-10-02,2024-10-01 14:29:59,UTC +01:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,54690106-8d71-4dd2-9231-77e47ce36288,AGIOS DIMITRIOS,9349605.0,NaN,2024-10-02,2024-10-01 14:29:59,UTC +01:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33563,49418a11-1b45-4e45-890e-985887b61fed,XIN BIN ZHOU,9185413.0,NaN,2024-10-13,2024-10-13 09:23:59,UTC +08:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33564,37035dde-8403-4380-be66-adae368da05b,XIN BIN ZHOU,9185413.0,NaN,2024-10-13,2024-10-13 09:23:59,UTC +08:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33565,b91022a5-e0a6-48d2-802f-3f4f5ac2ce2a,XIN BIN ZHOU,9185413.0,NaN,2024-10-13,2024-10-13 09:23:59,UTC +08:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33566,2152068a-7d3c-45ec-a05d-5f4dfa7c94ca,XIN BIN ZHOU,9185413.0,NaN,2024-10-13,2024-10-13 09:23:59,UTC +08:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33567,5372c4a1-00dd-4855-9da4-4add21c2dbbe,XIN BIN ZHOU,9185413.0,HD440A,2024-10-13,2024-10-13 09:24:00,UTC +08:00,SAIL,IN PORT,2024N,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN

# Sept

In [35]:
week6=pd.read_excel(r'D:\Navalt\MSC\2024\Weekly Data\CHARTER\CLIENT\OneDrive_1_10-17-2024\08e.Complete data Week 35 2024.xlsx')
week7=pd.read_excel(r'D:\Navalt\MSC\2024\Weekly Data\CHARTER\CLIENT\OneDrive_1_10-17-2024\09a.Complete data Week 36 2024.xlsx')
week8=pd.read_excel(r'D:\Navalt\MSC\2024\Weekly Data\CHARTER\CLIENT\OneDrive_1_10-17-2024\09b.Complete data Week 37 2024.xlsx')
week9=pd.read_excel(r'D:\Navalt\MSC\2024\Weekly Data\CHARTER\CLIENT\OneDrive_1_10-17-2024\09c.Complete data Week 38 2024.xlsx')
week10=pd.read_excel(r'D:\Navalt\MSC\2024\Weekly Data\CHARTER\CLIENT\OneDrive_1_10-17-2024\09d.Complete data Week 39 2024.xlsx')
week12=pd.read_excel(r'D:\Navalt\MSC\2024\Weekly Data\CHARTER\CLIENT\OneDrive_1_10-17-2024\10a.Complete data Week 40 2024.xlsx')

In [36]:
sep=pd.concat([week6,week7,week8,week9,week10,week12])

In [37]:
# Ensure 'REPORT DATE TIME' is in datetime format
sep['REPORT DATE TIME'] = pd.to_datetime(sep['REPORT DATE TIME'])

# Filter the DataFrame for the given date range
filtered_sep = sep[(sep['REPORT DATE TIME'] >= pd.Timestamp('2024-09-01 00:00:00')) & 
                   (sep['REPORT DATE TIME'] <= pd.Timestamp('2024-09-30 23:59:59'))]

In [41]:
filtered_sep

,GID,VSL,IMO No,VOY,Corrected Date,REPORT DATE TIME,REPORT DATE TIME Offset,Report Type,Status,LAT,...,ROB Rsdl HS,ROB Rsdl ULS,ROB Rsdl LNG,ECA MILES,ECA TIME,EGCS DRY WASTE REMOVED,EGCS RUNNING TIME,EGCS WET SLURRY REMOVED,EGCS OPEN LOOP RUNNING TIME,EGCS CLOSED LOOP RUNNING TIME
41,60317d31-4c4d-43d7-876b-2f33e51aba38,AGIOS DIMITRIOS,9349605.0,IP434A,2024-09-01,2024-09-01 12:00:00,UTC +05:00,NOON,AT SEA,0151S,...,664.3,0.0,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0
105,6fbc4172-e9c2-4821-b2aa-21bd364589ae,ALANA,9297589.0,RC435A,2024-09-01,2024-09-01 12:00:00,UTC +01:00,DLY A,DRIFTING,5446N,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,56f0701e-4677-4945-a9fa-bf1522289889,ALLEGRO,9142447.0,UB435R,2024-09-01,2024-09-01 12:00:00,UTC -04:00,NOON,AT SEA,2548N,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
170,f08cad56-b736-42e2-bc0e-c513d8445d73,AMERICA,9285990.0,IU432A,2024-09-01,2024-09-01 12:00:00,UTC +03:00,NOON,AT SEA,2444S,...,3255.5,0.0,0.0,0.0,0.0,NaN,25.0,NaN,25.0,0.0
180,3360c237-f600-40f5-a12a-7fd49ca6b2f7,ANASTASIA,9625970.0,66B,2024-09-01,2024-09-01 09:12:00,UTC +10:00,EOSP,AT SEA,2327S,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33437,38f093c1-34fd-4e66-a8c8-b3af6207b07f,XIN BIN ZHOU,9185413.0,NaN,2024-09-29,2024-09-29 08:59:59,UTC +08:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33438,12add201-ad87-409e-a338-adb1ae788aaf,XIN BIN ZHOU,9185413.0,NaN,2024-09-29,2024-09-29 08:59:59,UTC +08:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33439,a5dcacae-ea08-4a69-8c96-f2025d907101,XIN BIN ZHOU,9185413.0,HD438R,2024-09-29,2024-09-29 09:00:00,UTC +08:00,SAIL,IN PORT,0105N,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN
33440,0aa0ae08-2574-4470-ae5b-d8b97da2ce81,XIN BIN ZHOU,9185413.0,HD438R,2024-09-30,2024-09-29 12:42:00,UTC +08:00,COSP,DRIFTING,0116N,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33441,910af70d-9d59-4e60-9d0e-3379c5f32898,XIN BIN ZHOU,9185413.0,HD438R,2024-09-30,2024-09-30 12:00:00,UTC +08:00,NOON,AT SEA,0554N,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN

# Aug

In [5]:

week1=pd.read_excel(r'D:\Navalt\MSC\2024\Weekly Data\CHARTER\CLIENT\OneDrive_1_10-17-2024\08a.Complete data Week 31 2024.xlsx')
week2=pd.read_excel(r'D:\Navalt\MSC\2024\Weekly Data\CHARTER\CLIENT\OneDrive_1_10-17-2024\08b.Complete data Week 32 2024.xlsx')
week3=pd.read_excel(r'D:\Navalt\MSC\2024\Weekly Data\CHARTER\CLIENT\OneDrive_1_10-17-2024\08c.Complete data Week 33 2024.xlsx')
week4=pd.read_excel(r'D:\Navalt\MSC\2024\Weekly Data\CHARTER\CLIENT\OneDrive_1_10-17-2024\08d.Complete data Week 34 2024.xlsx')
week5=pd.read_excel(r'D:\Navalt\MSC\2024\Weekly Data\CHARTER\CLIENT\OneDrive_1_10-17-2024\08e.Complete data Week 35 2024.xlsx')
week6=pd.read_excel(r'D:\Navalt\MSC\2024\Weekly Data\CHARTER\CLIENT\OneDrive_1_10-17-2024\09a.Complete data Week 36 2024.xlsx')

In [7]:
aug=pd.concat([week1,week2,week3,week4,week5,week6])
aug

,GID,VSL,IMO No,VOY,Corrected Date,REPORT DATE TIME,REPORT DATE TIME Offset,Report Type,Status,LAT,...,ROB Rsdl HS,ROB Rsdl ULS,ROB Rsdl LNG,ECA MILES,ECA TIME,EGCS DRY WASTE REMOVED,EGCS RUNNING TIME,EGCS WET SLURRY REMOVED,EGCS OPEN LOOP RUNNING TIME,EGCS CLOSED LOOP RUNNING TIME
0,016f879c-3103-4beb-a1eb-fa7b154119e1,AGIOS DIMITRIOS,9349605.0,NaN,2024-07-26,2024-07-25 14:59:59,UTC +02:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7bc20a25-952a-493a-8076-5bf1bff1a517,AGIOS DIMITRIOS,9349605.0,NaN,2024-07-26,2024-07-25 14:59:59,UTC +02:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,9caf387a-5b98-4acf-82e1-542c03b2a7d8,AGIOS DIMITRIOS,9349605.0,NaN,2024-07-26,2024-07-25 14:59:59,UTC +02:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,468e64e9-8689-4b55-8879-3460d98eb400,AGIOS DIMITRIOS,9349605.0,NaN,2024-07-26,2024-07-25 14:59:59,UTC +02:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2af20a8f-9173-467e-afea-b11469d26f8d,AGIOS DIMITRIOS,9349605.0,NaN,2024-07-26,2024-07-25 14:59:59,UTC +02:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33016,94f913fa-601c-449d-91d4-b50870ebd017,XIN BIN ZHOU,9185413.0,NaN,2024-09-08,2024-09-07 19:47:59,UTC +08:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33017,1e5ec366-eab1-46b9-907d-e3676fc0ed47,XIN BIN ZHOU,9185413.0,NaN,2024-09-08,2024-09-07 19:47:59,UTC +08:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33018,8860fc93-a371-4998-99d1-0c7b638fc3d3,XIN BIN ZHOU,9185413.0,HE433R,2024-09-08,2024-09-07 19:48:00,UTC +08:00,SAIL,IN PORT,2328N,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN
33019,7160c49a-8e4b-4063-b238-b8b46e302e82,XIN BIN ZHOU,9185413.0,HE433R,2024-09-08,2024-09-07 20:36:00,UTC +08:00,COSP,DRIFTING,2308N,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33020,19109ac8-bc1a-4e5b-92c2-056dbd9ed746,XIN BIN ZHOU,9185413.0,HE433R,2024-09-08,2024-09-08 11:24:00,UTC +08:00,EOSP,AT SEA,2308N,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN

In [11]:
# Creating a new DataFrame filtered for the date range
filtered_aug = aug[(aug['REPORT DATE TIME'] >= '2024-08-01 00:00:00') & (aug['REPORT DATE TIME'] <= '2024-08-31 23:59:59')]
filtered_aug

,GID,VSL,IMO No,VOY,Corrected Date,REPORT DATE TIME,REPORT DATE TIME Offset,Report Type,Status,LAT,...,ROB Rsdl HS,ROB Rsdl ULS,ROB Rsdl LNG,ECA MILES,ECA TIME,EGCS DRY WASTE REMOVED,EGCS RUNNING TIME,EGCS WET SLURRY REMOVED,EGCS OPEN LOOP RUNNING TIME,EGCS CLOSED LOOP RUNNING TIME
25,e8111a26-6999-4636-94b9-48d5d0a61122,AGIOS DIMITRIOS,9349605.0,IB428R,2024-08-01,2024-08-01 12:00:00,UTC +02:00,PORT,IN PORT,2959S,...,1866.5,0.0,0.0,NaN,NaN,NaN,24.0,NaN,24.0,0.0
26,f9be231e-1aec-4f75-a278-ac62eaf4663a,AGIOS DIMITRIOS,9349605.0,NaN,2024-08-02,2024-08-02 10:29:59,UTC +02:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,4d1f3855-df2e-4db9-99f4-6cd7cf3b996b,AGIOS DIMITRIOS,9349605.0,NaN,2024-08-02,2024-08-02 10:29:59,UTC +02:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,cf559b84-1b0c-4a07-94c3-7e88b112b386,AGIOS DIMITRIOS,9349605.0,NaN,2024-08-02,2024-08-02 10:29:59,UTC +02:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,ecbe12c6-fcca-4fd0-9e3f-300603e4db0f,AGIOS DIMITRIOS,9349605.0,NaN,2024-08-02,2024-08-02 10:29:59,UTC +02:00,SND,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32948,c1457ed4-a141-43f9-a3ee-0d0278984012,XIN BIN ZHOU,9185413.0,HE433R,2024-08-30,2024-08-29 18:42:00,UTC +08:00,COSP,DRIFTING,2035N,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32949,d6a34e16-0863-4a69-9289-48f1170214e1,XIN BIN ZHOU,9185413.0,HE433R,2024-08-30,2024-08-30 12:00:00,UTC +08:00,NOON,AT SEA,1758N,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
32950,b6ab1264-387b-43ab-ab20-019eda3641e8,XIN BIN ZHOU,9185413.0,HE433R,2024-08-31,2024-08-31 12:00:00,UTC +08:00,NOON,AT SEA,1758N,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
32951,b294fe8b-665e-42fe-a308-14b7a35fe116,XIN BIN ZHOU,9185413.0,HE433R,2024-09-01,2024-08-31 15:30:00,UTC +08:00,EOSP,AT SEA,2227N,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
32952,01cf2d2e-e88e-47dd-a921-e9d6323a5d47,XIN BIN ZHOU,9185413.0,HE433R,2024-09-01,2024-08-31 17:30:00,UTC +08:00,BRTH,DRIFTING,2227N,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# july